// Pobočka s bránou — texty e-mailů (fr, nl, pl, uk). Generováno z kanonických textů
// zadání 2026-10-04 (copy_i18n) DOSLOVNĚ + validGear/validMoto/pageLink.
// {gate} = kód schránky (jen tělo mailu majiteli rezervace), {n} = č. dveří šatny.
import type { Lang } from './i18n.ts'
import type { GateTexts } from './branch-gate.ts'

export const GATE_TEXTS_B: Partial<Record<Lang, GateTexts>> = {
  fr: {
    gateLabel: "Code de la boîte à clés du portail",
    gateHint: "Boîte du haut, sur le pilier droit du portail — vous n'en avez besoin que si le portail est fermé.",
    lockerLabelDoor: "Code du vestiaire (porte n° {n})",
    validGear: "Le code du vestiaire et le code de la moto sont valables pendant la location.",
    validMoto: "Le code de la moto est valable pendant la location.",
    procTitle: "Marche à suivre à l'agence de Velké Němčice",
    step1Code: "Si le portail d'entrée est fermé, ouvrez la boîte à clés du HAUT, sur le pilier droit du portail, avec le code {gate} — elle contient la clé du cadenas du portail. Déverrouillez le portail, entrez et garez-vous sur l'une des places 1–7, à droite le long de la clôture. Votre voiture peut y stationner gratuitement pendant toute la durée de la location.",
    step1NoCode: "Si le portail d'entrée est fermé, ouvrez la boîte à clés du HAUT, sur le pilier droit du portail, avec le code que vous recevrez en même temps que les codes de votre réservation — elle contient la clé du cadenas du portail. Déverrouillez le portail, entrez et garez-vous sur l'une des places 1–7, à droite le long de la clôture. Votre voiture peut y stationner gratuitement pendant toute la durée de la location.",
    step2GearDoor: "Sur l'écran, saisissez le code du vestiaire (vestiaire = porte n° {n}), changez-vous, ajustez les tailles dans le protocole de remise, puis signez-le.",
    step2Gear: "Sur l'écran, saisissez le code du vestiaire, changez-vous, ajustez les tailles dans le protocole de remise, puis signez-le.",
    step3Gear: "Saisissez le code moto, prenez la moto et refermez les portes du vestiaire et du box.",
    step2NoGear: "Sur l'écran, saisissez le code moto, signez le protocole de remise, prenez la moto et refermez la porte du box.",
    stepImportant: "IMPORTANT : si le portail était fermé, refermez-le en partant et verrouillez-le avec le cadenas, puis remettez la clé dans la boîte du haut et tournez les molettes pour que le code ne reste pas affiché. Si le portail était ouvert, laissez-le ouvert. Procédez de la même manière lors du retour de la moto.",
    pageLink: "Photos de l'agence et du parking (places 1–7) sur la page de l'agence →",
  },
  nl: {
    gateLabel: "Code van het sleutelkastje met de poortsleutel",
    gateHint: "Bovenste kastje aan de rechterpaal van de poort — u heeft de code alleen nodig als de poort gesloten is.",
    lockerLabelDoor: "Kleedkamercode (deur nr. {n})",
    validGear: "De kleedkamercode en de motorcode zijn geldig tijdens de huurperiode.",
    validMoto: "De motorcode is geldig tijdens de huurperiode.",
    procTitle: "Werkwijze bij de vestiging Velké Němčice",
    step1Code: "Is de toegangspoort gesloten, open dan met de code {gate} het BOVENSTE kastje aan de rechterpaal van de poort — daarin zit de sleutel van het hangslot op de poort. Ontgrendel de poort, rijd naar binnen en parkeer op een van de plekken 1–7 rechts langs het hek. Uw auto mag hier de hele huurperiode gratis blijven staan.",
    step1NoCode: "Is de toegangspoort gesloten, open dan het BOVENSTE kastje aan de rechterpaal van de poort met de code die u samen met de codes van uw reservering ontvangt — daarin zit de sleutel van het hangslot op de poort. Ontgrendel de poort, rijd naar binnen en parkeer op een van de plekken 1–7 rechts langs het hek. Uw auto mag hier de hele huurperiode gratis blijven staan.",
    step2GearDoor: "Voer op het display de kleedkamercode in (kleedkamer = deur nr. {n}), kleed u om, pas in het overdrachtsprotocol de maten aan en onderteken het protocol.",
    step2Gear: "Voer op het display de kleedkamercode in, kleed u om, pas in het overdrachtsprotocol de maten aan en onderteken het protocol.",
    step3Gear: "Voer de motorcode in, neem de motor mee en sluit zowel de deur van de kleedkamer als die van de box.",
    step2NoGear: "Voer op het display de motorcode in, onderteken het overdrachtsprotocol, neem de motor mee en sluit de deur van de box.",
    stepImportant: "BELANGRIJK: Was de poort gesloten, sluit hem dan na vertrek weer, vergrendel hem met het hangslot, leg de sleutel terug in het bovenste kastje en verdraai de cijferwieltjes, zodat de code niet blijft staan. Stond de poort open, laat hem dan open. Ga bij het terugbrengen van de motor op dezelfde manier te werk.",
    pageLink: "Foto's van de vestiging en de parkeerplaats (plekken 1–7) vindt u op de pagina van de vestiging →",
  },
  pl: {
    gateLabel: "Kod do skrytki z kluczem do bramy",
    gateHint: "Górna skrytka na prawym słupku bramy — kod jest potrzebny tylko wtedy, gdy brama jest zamknięta.",
    lockerLabelDoor: "Kod do szatni (drzwi nr {n})",
    validGear: "Kod do szatni i kod do motocykla są ważne przez czas trwania wypożyczenia.",
    validMoto: "Kod do motocykla jest ważny przez czas trwania wypożyczenia.",
    procTitle: "Jak postępować w oddziale Velké Němčice",
    step1Code: "Jeśli brama wjazdowa jest zamknięta, proszę otworzyć GÓRNĄ skrytkę na prawym słupku bramy kodem {gate} — znajduje się w niej klucz do kłódki bramy. Proszę zdjąć kłódkę, otworzyć bramę, wjechać do środka i zaparkować na dowolnym z miejsc 1–7 po prawej stronie przy ogrodzeniu. Samochód może tu stać bezpłatnie przez cały czas wypożyczenia.",
    step1NoCode: "Jeśli brama wjazdowa jest zamknięta, proszę otworzyć GÓRNĄ skrytkę na prawym słupku bramy kodem przesłanym razem z kodami dostępu do oddziału — znajduje się w niej klucz do kłódki bramy. Proszę zdjąć kłódkę, otworzyć bramę, wjechać do środka i zaparkować na dowolnym z miejsc 1–7 po prawej stronie przy ogrodzeniu. Samochód może tu stać bezpłatnie przez cały czas wypożyczenia.",
    step2GearDoor: "Proszę wpisać na wyświetlaczu kod do szatni (szatnia = drzwi nr {n}), przebrać się, w protokole przekazania dopasować rozmiary i podpisać protokół.",
    step2Gear: "Proszę wpisać na wyświetlaczu kod do szatni, przebrać się, w protokole przekazania dopasować rozmiary i podpisać protokół.",
    step3Gear: "Proszę wpisać kod do motocykla, wyprowadzić go i zamknąć drzwi szatni oraz boksu.",
    step2NoGear: "Proszę wpisać na wyświetlaczu kod do motocykla, podpisać protokół przekazania, wyprowadzić motocykl i zamknąć drzwi boksu.",
    stepImportant: "WAŻNE: Jeśli brama była zamknięta, po wyjeździe proszę ją ponownie zamknąć, zabezpieczyć kłódką, odłożyć klucz z powrotem do górnej skrytki i przekręcić pokrętła szyfru, aby kod nie pozostał ustawiony. Otwartą bramę proszę pozostawić otwartą. Tak samo należy postąpić przy zwrocie motocykla.",
    pageLink: "Zdjęcia oddziału i parkingu (miejsca 1–7) znajdą Państwo na stronie oddziału →",
  },
  uk: {
    gateLabel: "Код скриньки з ключем від воріт",
    gateHint: "Верхня скринька на правому стовпі воріт — код потрібен вам лише тоді, коли ворота зачинені.",
    lockerLabelDoor: "Код роздягальні (двері № {n})",
    validGear: "Код до роздягальні й код до мотоцикла дійсні протягом усього строку оренди.",
    validMoto: "Код до мотоцикла дійсний протягом усього строку оренди.",
    procTitle: "Порядок дій у філії Velké Němčice",
    step1Code: "Якщо вʼїзні ворота зачинені, відкрийте ВЕРХНЮ скриньку на правому стовпі воріт кодом {gate} — у ній лежить ключ від навісного замка воріт. Відімкніть ворота, заїдьте всередину й припаркуйтеся на будь-якому з місць 1–7 праворуч біля паркану. Автомобіль може безкоштовно стояти тут протягом усього часу оренди.",
    step1NoCode: "Якщо вʼїзні ворота зачинені, відкрийте ВЕРХНЮ скриньку на правому стовпі воріт кодом, який ви отримаєте разом із кодами до бронювання, — у ній лежить ключ від навісного замка воріт. Відімкніть ворота, заїдьте всередину й припаркуйтеся на будь-якому з місць 1–7 праворуч біля паркану. Автомобіль може безкоштовно стояти тут протягом усього часу оренди.",
    step2GearDoor: "На дисплеї введіть код роздягальні (роздягальня = двері № {n}), перевдягніться, у протоколі передачі відкоригуйте розміри та підпишіть протокол.",
    step2Gear: "На дисплеї введіть код роздягальні, перевдягніться, у протоколі передачі відкоригуйте розміри та підпишіть протокол.",
    step3Gear: "Введіть код мотоцикла, заберіть мотоцикл і зачиніть двері роздягальні та боксу.",
    step2NoGear: "На дисплеї введіть код мотоцикла, підпишіть протокол передачі, заберіть мотоцикл і зачиніть двері боксу.",
    stepImportant: "ВАЖЛИВО: Якщо ворота були зачинені, після відʼїзду знову зачиніть їх, замкніть навісним замком, поверніть ключ у верхню скриньку й прокрутіть коліщата з цифрами, щоб код не залишився набраним. Відчинені ворота залиште відчиненими. Дійте так само й під час повернення мотоцикла.",
    pageLink: "Фото філії та парковки (місця 1–7) — на сторінці філії →",
  },
}
