@echo off
chcp 65001 >nul 2>&1
echo.
echo ========================================================
echo   MotoGo24 - Upload webu na VSECHNY domeny
echo ========================================================
echo.

set "PS=%TEMP%\motogo-multi-upload.ps1"

echo $ftpServer = 'ftp://130.193.9.44' > "%PS%"
echo $ftpPass   = 'heslo666' >> "%PS%"
echo $Slozka    = 'C:\Users\HP Z2\Desktop\Vel-n-main\motogo-web-php' >> "%PS%"
echo. >> "%PS%"
echo $domeny = @( >> "%PS%"
echo     @{ Nazev='motogo24.com'; Jazyk='EN'; User='mainftp123192'; Slozka='motogo24.com' }, >> "%PS%"
echo     @{ Nazev='motogo24.es';  Jazyk='ES'; User='mainftp123228'; Slozka='motogo24.es' }, >> "%PS%"
echo     @{ Nazev='motogo24.pl';  Jazyk='PL'; User='mainftp123234'; Slozka='motogo24.pl' }, >> "%PS%"
echo     @{ Nazev='motogo24.at';  Jazyk='DE'; User='mainftp123231'; Slozka='motogo24.at' } >> "%PS%"
echo ) >> "%PS%"
echo. >> "%PS%"
echo Write-Host '' >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo Write-Host '  MotoGo24 - Multi-domain Upload' -Fore Yellow >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo Write-Host "  Zdroj: $Slozka" -Fore Cyan >> "%PS%"
echo Write-Host '' >> "%PS%"
echo. >> "%PS%"
echo if (-not (Test-Path $Slozka)) { >> "%PS%"
echo     Write-Host "  CHYBA: Slozka $Slozka neexistuje!" -Fore Red >> "%PS%"
echo     Read-Host '  Stiskni Enter' >> "%PS%"
echo     exit >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo function New-FtpDir { >> "%PS%"
echo     param($ftpPath, $cred) >> "%PS%"
echo     try { >> "%PS%"
echo         $uri = "$ftpServer$ftpPath" >> "%PS%"
echo         $r = [System.Net.FtpWebRequest]::Create($uri) >> "%PS%"
echo         $r.Method = [System.Net.WebRequestMethods+Ftp]::MakeDirectory >> "%PS%"
echo         $r.Credentials = $cred >> "%PS%"
echo         $r.UseBinary = $true >> "%PS%"
echo         $r.UsePassive = $true >> "%PS%"
echo         $resp = $r.GetResponse() >> "%PS%"
echo         $resp.Close() >> "%PS%"
echo     } catch {} >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo function Send-FtpFile { >> "%PS%"
echo     param($localFile, $ftpPath, $cred) >> "%PS%"
echo     try { >> "%PS%"
echo         $uri = "$ftpServer$ftpPath" >> "%PS%"
echo         $r = [System.Net.FtpWebRequest]::Create($uri) >> "%PS%"
echo         $r.Method = [System.Net.WebRequestMethods+Ftp]::UploadFile >> "%PS%"
echo         $r.Credentials = $cred >> "%PS%"
echo         $r.UseBinary = $true >> "%PS%"
echo         $r.UsePassive = $true >> "%PS%"
echo         $data = [System.IO.File]::ReadAllBytes($localFile) >> "%PS%"
echo         $r.ContentLength = $data.Length >> "%PS%"
echo         $s = $r.GetRequestStream() >> "%PS%"
echo         $s.Write($data, 0, $data.Length) >> "%PS%"
echo         $s.Close() >> "%PS%"
echo         $resp = $r.GetResponse() >> "%PS%"
echo         $resp.Close() >> "%PS%"
echo         return $true >> "%PS%"
echo     } catch { >> "%PS%"
echo         return $false >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo $soubory = Get-ChildItem -Path $Slozka -Recurse -File >> "%PS%"
echo $celkem = $soubory.Count >> "%PS%"
echo $celkoveChyby = 0 >> "%PS%"
echo. >> "%PS%"
echo foreach ($dom in $domeny) { >> "%PS%"
echo     $ftpCilova = '/' + $dom.Slozka >> "%PS%"
echo     $cred = New-Object System.Net.NetworkCredential($dom.User, $ftpPass) >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     Write-Host "  ================================================" -Fore Yellow >> "%PS%"
echo     Write-Host "  $($dom.Nazev) [$($dom.Jazyk)] - user: $($dom.User)" -Fore Green >> "%PS%"
echo     Write-Host "  ================================================" -Fore Yellow >> "%PS%"
echo. >> "%PS%"
echo     $ok = 0 >> "%PS%"
echo     $chyby = 0 >> "%PS%"
echo. >> "%PS%"
echo     foreach ($soubor in $soubory) { >> "%PS%"
echo         $rel = $soubor.FullName.Substring($Slozka.Length).Replace('\','/') >> "%PS%"
echo         $ftpCesta = "$ftpCilova$rel" >> "%PS%"
echo         $ftpDir = $ftpCesta.Substring(0, $ftpCesta.LastIndexOf('/')) >> "%PS%"
echo         if ($ftpDir -ne $ftpCilova) { >> "%PS%"
echo             $parts = $ftpDir.Substring($ftpCilova.Length).Split('/', [StringSplitOptions]::RemoveEmptyEntries) >> "%PS%"
echo             $cur = $ftpCilova >> "%PS%"
echo             foreach ($p in $parts) { >> "%PS%"
echo                 $cur = "$cur/$p" >> "%PS%"
echo                 New-FtpDir $cur $cred >> "%PS%"
echo             } >> "%PS%"
echo         } >> "%PS%"
echo         $ok++ >> "%PS%"
echo         $pct = [math]::Round(($ok / $celkem) * 100) >> "%PS%"
echo         Write-Host "  [$ok/$celkem] ($pct%%) $rel " -NoNewline >> "%PS%"
echo         $result = Send-FtpFile $soubor.FullName $ftpCesta $cred >> "%PS%"
echo         if ($result) { Write-Host 'OK' -Fore Green } >> "%PS%"
echo         else { Write-Host 'CHYBA' -Fore Red; $chyby++ } >> "%PS%"
echo     } >> "%PS%"
echo. >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     if ($chyby -eq 0) { >> "%PS%"
echo         Write-Host "  $($dom.Nazev): $celkem/$celkem OK" -Fore Green >> "%PS%"
echo     } else { >> "%PS%"
echo         Write-Host "  $($dom.Nazev): $($ok - $chyby)/$celkem OK, $chyby chyb" -Fore Red >> "%PS%"
echo         $celkoveChyby += $chyby >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo Write-Host '' >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo if ($celkoveChyby -eq 0) { >> "%PS%"
echo     Write-Host '  VSECHNY 4 DOMENY NAHRANE USPESNE!' -Fore Green >> "%PS%"
echo } else { >> "%PS%"
echo     Write-Host "  HOTOVO s $celkoveChyby chybami celkem" -Fore Red >> "%PS%"
echo } >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo Write-Host '  http://motogo24.com  (EN)' -Fore Cyan >> "%PS%"
echo Write-Host '  http://motogo24.es   (ES)' -Fore Cyan >> "%PS%"
echo Write-Host '  http://motogo24.pl   (PL)' -Fore Cyan >> "%PS%"
echo Write-Host '  http://motogo24.at   (DE)' -Fore Cyan >> "%PS%"
echo Write-Host '' >> "%PS%"

powershell -ExecutionPolicy Bypass -File "%PS%"

echo.
pause
