<?php
// MotoGo24 — pages_es.php (auto-generated by merge_pages.php; parts: 1)

return [
    'pages' => [
        'kontakt' => [
            'seo' => [
                'title' => 'Contacto | MotoGo24 – Alquiler de motos Vysočina',
                'description' => 'Contactos del alquiler de motos Motogo24 en Pelhřimov. Teléfono +420 774 256 271, e-mail info@motogo24.cz. Servicio 24/7, dirección Mezná 9, 393 01 Pelhřimov.',
                'keywords' => 'contacto Motogo24, alquiler de motos Pelhřimov, teléfono, dirección, horario, 24/7',
            ],
            'h1' => 'Contactos del alquiler de motos Motogo24',
            'intro' => '¿Tienes alguna pregunta sobre el <strong>alquiler de motos</strong>, quieres pedir un <strong>vale regalo</strong>, necesitas ayuda para elegir o quieres directamente <strong>concertar una reserva</strong>? Estamos aquí para ti todos los días, <strong>24/7</strong>.',
            'quick' => [
                [
                    'label' => 'LLÁMANOS',
                    'value' => '+420 774 256 271',
                    'href' => 'tel:+420774256271',
                    'icon' => 'gfx/telefon.svg',
                    'alt' => 'Teléfono',
                ],
                [
                    'label' => 'ESCRÍBENOS',
                    'value' => 'info@motogo24.cz',
                    'href' => 'mailto:info@motogo24.cz',
                    'icon' => 'gfx/email.svg',
                    'alt' => 'E-mail',
                ],
                [
                    'label' => 'BUZÓN DE DATOS',
                    'value' => 'iuw3vnb',
                    'href' => NULL,
                    'icon' => NULL,
                    'alt' => NULL,
                ],
            ],
            'place' => [
                'title' => 'Establecimiento',
                'address_label' => 'Dirección:',
                'address' => 'Mezná 9, 393 01 Pelhřimov',
                'hours_label' => 'Horario:',
                'hours' => 'LU – DO: 00:00 – 24:00 (24/7)<br>Incluyendo fines de semana y festivos',
                'billing_title' => 'Datos de facturación',
                'billing_name' => 'Bc. Petra Semorádová',
                'billing_address' => 'Mezná 9, 393 01 Pelhřimov',
                'billing_ico' => '21874263',
                'billing_vat' => 'No soy contribuyente del IVA',
                'billing_note' => 'La empresa fue inscrita el 31. 7. 2024 en el Ayuntamiento de Pelhřimov.',
            ],
            'social_title' => 'Síguenos',
            'social' => [
                [
                    'label' => 'facebook',
                    'href' => '#',
                    'icon' => 'gfx/facebook.svg',
                    'alt' => 'Facebook',
                ],
                [
                    'label' => 'instagram',
                    'href' => '#',
                    'icon' => 'gfx/instagram.svg',
                    'alt' => 'Instagram',
                ],
            ],
            'side_cta' => [
                'title' => '¿Quieres concertar una reserva?',
                'text' => 'Reserva tu moto online en pocos minutos y lánzate a la aventura.',
                'button' => [
                    'label' => 'RESERVAR ONLINE',
                    'href' => '/rezervace',
                    'cls' => 'btndark',
                ],
            ],
            'map' => [
                'title' => 'Dónde encontrarnos',
                'src' => 'https://www.google.com/maps?q=Mezn%C3%A1+9%2C+393+01+Pelh%C5%99imov&hl=cs&z=15&output=embed',
            ],
            'seo_text' => [
                'title' => 'Contactos – Alquiler de motos Vysočina (Pelhřimov)',
                'body' => 'Motogo24 es un <strong>moderno alquiler de motos en Vysočina</strong>. Tenemos nuestra sede en <strong>Pelhřimov</strong>, abrimos <strong>24/7</strong> y alquilamos <strong>sin depósito</strong>, con el <strong>equipamiento completo incluido en el precio</strong>.',
            ],
        ],
        'jak_pujcit' => [
            'seo' => [
                'title' => 'Cómo alquilar una moto | MotoGo24',
                'description' => 'Cómo alquilar una moto en Motogo24. Procedimiento sencillo: elección, reserva, recogida. Sin depósito, equipamiento incluido, servicio 24/7.',
                'keywords' => 'cómo alquilar una moto, proceso de alquiler, reserva de moto, alquiler de motos Vysočina',
            ],
            'h1' => 'Cómo alquilar una moto',
            'intro' => 'En <strong>Motogo24 – Alquiler de motos en Vysočina</strong>, alquilar es sencillo, rápido y justo.',
            'links' => [
                [
                    'href' => '/jak-pujcit/postup',
                    'label' => 'Proceso de alquiler',
                ],
                [
                    'href' => '/jak-pujcit/prevzeti',
                    'label' => 'Recogida en el establecimiento',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-pujcovna',
                    'label' => 'Devolución de la moto en el establecimiento',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-jinde',
                    'label' => 'Devolución de la moto en otro lugar',
                ],
                [
                    'href' => '/jak-pujcit/co-v-cene',
                    'label' => 'Qué incluye el precio del alquiler',
                ],
                [
                    'href' => '/jak-pujcit/pristaveni',
                    'label' => 'Entrega de la moto',
                ],
                [
                    'href' => '/jak-pujcit/dokumenty',
                    'label' => 'Documentos y manuales',
                ],
                [
                    'href' => '/jak-pujcit/faq',
                    'label' => 'Preguntas frecuentes',
                ],
            ],
        ],
        'jak_pujcit_postup' => [
            'seo' => [
                'title' => 'Proceso de alquiler de moto | MotoGo24',
                'description' => 'Proceso de alquiler de moto en Motogo24 paso a paso. Reserva online, equipamiento incluido, sin depósito, servicio 24/7 y posibilidad de entrega.',
                'keywords' => 'proceso de alquiler de moto, cómo alquilar una moto, reserva de moto, alquiler de motos Pelhřimov',
            ],
            'h1' => 'Proceso de alquiler de moto',
            'intro' => '<p>En <strong>Motogo24 – Alquiler de motos en Vysočina</strong>, alquilar es sencillo, rápido y justo. <strong>Sin depósito, con equipamiento incluido y servicio 24/7</strong>. Mira lo fácil que funciona.</p><p>&nbsp;</p><h2>Cómo alquilar una moto – Alquiler Motogo24 Vysočina</h2><p>En el <strong>alquiler de motos Motogo24</strong>, el <strong>proceso de alquiler</strong> es simple: <strong>reserva online</strong>, <strong>equipamiento incluido</strong>, <strong>sin depósito</strong>, <strong>servicio 24/7</strong> y posibilidad de <strong>entrega de la moto</strong>. Tanto si buscas una <strong>moto de viaje</strong> para el fin de semana, una <strong>moto deportiva</strong> para la adrenalina o una <strong>enduro</strong> para el todoterreno, con nosotros encontrarás la solución ideal.</p>',
            'process' => [
                'title' => 'Cómo se desarrolla el alquiler paso a paso',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Elige la moto',
                        'text' => 'Echa un vistazo a nuestra oferta de <strong>motos de viaje, deportivas, enduro y motos infantiles</strong> y elige la adecuada.',
                    ],
                    [
                        'icon' => 'gfx/kontaktni-udaje.svg',
                        'title' => '2. Número de pilotos',
                        'text' => 'Decide si vas solo o con un acompañante. Te ofreceremos las máquinas y el equipamiento adecuados.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '3. Reserva online',
                        'text' => 'Reserva fácilmente la moto según la fecha. Realiza el pago previamente <strong>online</strong>.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => '4. Equipamiento incluido',
                        'text' => 'Automáticamente, como conductor, recibirás casco, chaqueta, pantalones y guantes. La talla la eliges en la reserva.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => '5. Confirmación y pago',
                        'text' => 'La reserva es vinculante tras la confirmación. El pago se realiza online.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '6. Recogida de la moto',
                        'text' => 'Recoges la moto personalmente en Pelhřimov o utilizas la <strong>entrega</strong> en el lugar acordado.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '7. Disfruta del viaje',
                        'text' => 'Lánzate a la carretera – <strong>sin depósito, sin estrés</strong>, con condiciones claras y seguro incluido.',
                    ],
                    [
                        'icon' => 'gfx/vrat-motorku-vcas.svg',
                        'title' => '8. Devolución de la moto',
                        'text' => 'Devuelves la moto en cualquier momento durante el último día del alquiler. No tienes que repostar ni lavarla.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Preguntas frecuentes',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => '¿Es necesario un depósito al alquilar?',
                        'a' => 'No. <strong>Alquilamos sin depósito</strong> – de forma justa y sin obstáculos innecesarios.',
                    ],
                    [
                        'q' => '¿El equipamiento está incluido en el precio del alquiler?',
                        'a' => 'Sí. Cada conductor recibe <strong>casco, chaqueta, pantalones y guantes gratis</strong>.',
                    ],
                    [
                        'q' => '¿Dónde puedo recoger la moto?',
                        'a' => 'La recogida se realiza en Pelhřimov; también ofrecemos <strong>entrega de la moto</strong> en el lugar que elijas.',
                    ],
                    [
                        'q' => '¿Hasta cuándo debo devolver la moto?',
                        'a' => 'Puedes devolver la moto en cualquier momento durante el último día del alquiler – incluso a medianoche.',
                    ],
                ],
            ],
            'cta' => [
                'title' => '¿Listo para rodar?',
                'text' => 'Reserva tu moto online hoy mismo y disfruta de la <strong>libertad sobre dos ruedas</strong>.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vyzvednuti' => [
            'seo' => [
                'title' => 'Recogida de la moto en el establecimiento | MotoGo24',
                'description' => 'Recogida de la moto en el establecimiento de Pelhřimov. Servicio 24/7, sin depósito, equipamiento incluido. Qué llevar y cómo se realiza la entrega.',
                'keywords' => 'recogida de moto en el establecimiento, recogida de moto, alquiler Pelhřimov, recogida 24/7',
            ],
            'h1' => 'Recogida de la moto en el establecimiento – rápido, sencillo y 24/7',
            'intro' => 'En <strong>Motogo24 – Alquiler de motos Vysočina</strong>, la <strong>recogida de la moto</strong> es cuestión de pocos minutos. Alquilamos <strong>sin depósito</strong>, con <strong>equipamiento incluido</strong> y <strong>servicio 24/7</strong>.',
            'top_cta' => [
                'label' => 'RESERVAR ONLINE',
                'href' => '/rezervace',
            ],
            'place' => [
                'title' => 'Dónde se realiza la recogida',
                'address_label' => 'Dirección:',
                'hours_label' => 'Horario:',
                'map_title' => 'Cómo llegar',
                'address' => 'Mezná 9, 393 01 <strong>Pelhřimov</strong> (Vysočina)',
                'hours' => '<em>24/7</em>',
                'phone' => '+420 774 256 271',
                'return_title' => 'Devolución de la moto – sin estrés',
                'return_text' => 'Puedes devolver la moto <strong>en cualquier momento durante el último día del alquiler</strong>. Más información en <a href="/jak-pujcit/vraceni-pujcovna">devolución en el establecimiento</a> o <a href="/jak-pujcit/vraceni-jinde">devolución en otro lugar</a>.',
            ],
            'steps' => [
                'title' => 'Cómo se desarrolla la recogida paso a paso',
                'items' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Llega a la hora acordada',
                        'text' => 'a nuestra dirección o espera la entrega',
                    ],
                    [
                        'icon' => 'gfx/overime-doklady.svg',
                        'title' => 'Verificamos los documentos',
                        'text' => 'DNI/pasaporte + permiso de conducir de la categoría correspondiente',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Entregamos la moto y el equipamiento',
                        'text' => 'casco, chaqueta, pantalones, guantes',
                    ],
                    [
                        'icon' => 'gfx/prevezmi-motorku.svg',
                        'title' => 'Breve familiarización con la máquina',
                        'text' => 'controles, consejos, recomendaciones de ruta',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'Firmamos el protocolo de entrega',
                        'text' => 'y ya puedes ponerte en marcha',
                    ],
                ],
            ],
            'bring' => [
                'title' => 'Qué llevar contigo',
                'items' => [
                    '<strong>DNI / pasaporte</strong>',
                    '<strong>Permiso de conducir</strong> de la categoría correspondiente (A/A2 según la moto)',
                    '<strong>Calzado adecuado</strong> (las botas de moto se pueden alquilar como extra)',
                ],
                'cta' => [
                    'label' => 'RESERVAR FECHA',
                    'href' => '/rezervace',
                ],
            ],
            'faq' => [
                'title' => 'Preguntas frecuentes sobre la recogida',
                'items' => [
                    [
                        'q' => '¿Tengo que pagar un depósito al recoger la moto?',
                        'a' => 'No, <strong>alquilamos sin depósito</strong>. Las condiciones son claras y justas.',
                    ],
                    [
                        'q' => '¿Es posible el contacto sin encuentro personal?',
                        'a' => 'Sí, ofrecemos <strong>entrega sin contacto</strong> previo acuerdo.',
                    ],
                    [
                        'q' => '¿Qué pasa si no llego a la hora acordada?',
                        'a' => 'Avísanos por teléfono – ajustaremos la hora o te ofreceremos la <strong>entrega</strong>.',
                    ],
                    [
                        'q' => '¿El equipamiento del acompañante también está incluido?',
                        'a' => 'El equipamiento del conductor está siempre incluido. El equipamiento del acompañante se puede añadir como <strong>extra</strong>.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Recogida de la moto en el establecimiento – Motogo24 Vysočina',
                'text' => 'Motogo24 es un <strong>alquiler de motos en Vysočina</strong> con <strong>recogida y devolución 24/7</strong>, <strong>sin depósito</strong> y con <strong>equipamiento incluido</strong>.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_pujcovna' => [
            'seo' => [
                'title' => 'Devolución de la moto en el establecimiento | MotoGo24',
                'description' => 'Devolución de la moto directamente en el establecimiento de Pelhřimov. 24/7, sin depósito, sin trámites innecesarios. Cómo se realiza la devolución de la moto paso a paso.',
                'keywords' => 'devolución de moto, devolución de moto en el establecimiento, alquiler Pelhřimov, devolución de moto 24/7',
            ],
            'h1' => 'Devolución de la moto en el establecimiento',
            'intro' => 'Devuelves cómodamente la moto directamente en <strong>Motogo24 – Alquiler de motos en Vysočina</strong>. <strong>Servicio 24/7</strong>, sin estrés y con condiciones justas.',
            'top_cta' => [
                'label' => 'RESERVAR ONLINE',
                'href' => '/rezervace',
            ],
            'place' => [
                'title' => 'Dónde y cuándo devolver la moto',
                'address' => 'Mezná 9, 393 01 <strong>Pelhřimov</strong> (Vysočina)',
                'hours' => '<em>24/7</em> – en cualquier momento durante el último día del alquiler',
                'phone' => '+420 774 256 271',
                'note_title' => 'Qué hay que cumplir',
                'note_text' => 'Devuelve la moto <strong>a la hora acordada</strong> y en un estado técnico similar al que la recibiste. <strong>No exigimos ni el depósito lleno ni el lavado.</strong>',
                'map_src' => 'https://frame.mapy.cz/s/?x=15.15413&y=49.35169&z=14&source=coor&id=15.15413%2C49.35169',
            ],
            'steps' => [
                'title' => 'Cómo se desarrolla la devolución en el establecimiento',
                'items' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Llega a la hora acordada',
                        'text' => 'a la dirección del alquiler en Pelhřimov',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Revisamos juntos el estado de la moto',
                        'text' => 'comprobación de la carrocería, depósito y equipamiento',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Devuelves el equipamiento',
                        'text' => 'casco, chaqueta, pantalones, guantes',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'Firmamos el protocolo de devolución',
                        'text' => 'un registro claro y justo',
                    ],
                    [
                        'icon' => 'gfx/potvrzeni-rezervace.svg',
                        'title' => 'Listo',
                        'text' => 'te enviaremos la confirmación por e-mail',
                    ],
                ],
            ],
            'tips' => [
                'title' => 'Consejos prácticos para la devolución',
                'items' => [
                    '<strong>No exigimos el depósito lleno</strong> – el combustible solo se cobra en caso necesario.',
                    '<strong>No es necesario lavar la moto</strong> – la suciedad normal del trayecto está bien.',
                    '<strong>Devolución tardía</strong> avísala con antelación por teléfono para acordar una solución.',
                    '<strong>Devolución sin contacto</strong> es posible previo acuerdo.',
                ],
                'cta' => [
                    'label' => 'RESERVAR FECHA',
                    'href' => '/rezervace',
                ],
            ],
            'faq' => [
                'title' => 'Preguntas frecuentes sobre la devolución en el establecimiento',
                'items' => [
                    [
                        'q' => '¿Qué pasa si no llego a la hora acordada de devolución?',
                        'a' => 'Avísanos por teléfono, por favor. Normalmente acordamos un <strong>aplazamiento de unas horas</strong>; un retraso mayor puede ser cobrado según la lista de precios.',
                    ],
                    [
                        'q' => '¿Tengo que lavar la moto?',
                        'a' => 'No. La suciedad normal está bien, <strong>no exigimos</strong> el lavado.',
                    ],
                    [
                        'q' => '¿Tengo que devolver la moto con el depósito lleno?',
                        'a' => 'No es obligatorio. Si el depósito no está lleno, repostaremos y <strong>cobraremos solo el precio real</strong> sin recargos.',
                    ],
                    [
                        'q' => '¿Qué pasa si el establecimiento está cerrado?',
                        'a' => 'El servicio es <strong>24/7</strong>. Por la noche basta con llamar al +420 774 256 271 y acordaremos la entrega.',
                    ],
                    [
                        'q' => '¿Puedo devolver la moto en otro lugar?',
                        'a' => 'Sí, utiliza <a href="/jak-pujcit/vraceni-jinde"><strong>devolución de la moto en otro lugar</strong></a> (entrega/recogida según la lista de precios).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Devolución de la moto en el establecimiento – Motogo24 Pelhřimov',
                'text' => 'Devuelve la moto directamente con nosotros en Pelhřimov – <strong>24/7, sin depósito, sin estrés</strong>.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'poukazy' => [
            'seo' => [
                'title' => 'Alquiler de motos Vysočina - Vales',
                'description' => 'Compra un vale regalo para el alquiler de moto. Validez 3 años, sin depósito, equipamiento incluido. Vale electrónico o impreso. Pedido online.',
                'keywords' => 'vale regalo moto, voucher alquiler de moto, regalo para motoristas, vale Motogo24, alquiler de motos Vysočina',
                'og_image' => 'https://motogo24.cz/gfx/darkovy-poukaz.jpg',
            ],
            'h1' => 'Compra un vale regalo – ¡regala una experiencia sobre dos ruedas!',
            'intro_left' => '<p>¿Buscas un regalo original para tu pareja, amigo o padre?</p><p>&nbsp;</p><p>Nuestros <strong>vales regalo para el alquiler de moto</strong> de Motogo24 – <strong>Alquiler de motos Vysočina</strong> – encantarán tanto a principiantes como a pilotos experimentados.</p><p>&nbsp;</p><p>Elige el valor del vale o una moto concreta y regala libertad sobre dos ruedas.</p>',
            'intro_cta' => [
                'label' => 'PEDIR VALE REGALO',
                'href' => '/koupit-darkovy-poukaz',
                'aria' => 'Pedir vale regalo para el alquiler de moto en el alquiler Motogo24',
            ],
            'intro_image' => [
                'src' => 'gfx/darkovy-poukaz.jpg',
                'alt' => 'Vale regalo',
            ],
            'steps' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => '1. Elige',
                    'text' => 'Elige el valor del vale o una moto concreta.',
                ],
                [
                    'icon' => 'gfx/zaplat.svg',
                    'title' => '2. Paga',
                    'text' => 'Paga online.',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => '3. Recoge',
                    'text' => 'El vale, tras el pago, llegará a tu bandeja de entrada.',
                ],
            ],
            'validity_note' => 'Todos los vouchers tienen <strong>validez de 3 años</strong> desde la fecha de emisión. <strong>El destinatario elige por sí mismo la fecha del alquiler</strong> que le convenga. Puede contactarnos por e-mail, teléfono o redes sociales.',
            'why' => [
                'title' => 'Por qué comprar un vale',
                'items' => [
                    '<strong>Elección flexible</strong> – valor del vale o moto concreta.',
                    '<strong>Validez 3 años</strong> – el destinatario elige la fecha por sí mismo.',
                    '<strong>Sin depósito</strong> – condiciones justas sin obstáculos innecesarios.',
                    '<strong>Equipamiento incluido</strong> – casco, chaqueta, pantalones y guantes gratis.',
                    '<strong>Servicio 24/7</strong> – recogida y devolución en cualquier momento del día del alquiler.',
                    '<strong>Pedido online</strong> – el vale te llegará por e-mail tras el pago.',
                ],
            ],
            'how' => [
                'title' => 'Cómo utilizar el vale',
                'items' => [
                    '<strong>Motos de viaje</strong> – roadtrip de fin de semana por Vysočina o toda la República Checa.',
                    '<strong>Motos deportivas</strong> – conducción adrenalínica en las curvas.',
                    '<strong>Enduro</strong> – terreno ligero y aventura fuera de las carreteras principales.',
                    '<strong>Motos infantiles</strong> – primeros viajes para pequeños pilotos bajo supervisión.',
                ],
            ],
            'catalog_cta' => [
                'label' => 'VER CATÁLOGO DE MOTOS',
                'href' => '/katalog',
            ],
            'faq' => [
                'title' => 'Preguntas frecuentes sobre los vales regalo',
                'items' => [
                    [
                        'q' => '¿Cuál es la validez del vale regalo?',
                        'a' => 'Todos los vouchers tienen una validez de <strong>3 años</strong> desde la fecha de emisión. La fecha del alquiler la elige el destinatario por sí mismo.',
                    ],
                    [
                        'q' => '¿Cómo entregan el vale?',
                        'a' => '<strong>Inmediatamente por e-mail</strong> tras el pago. Bajo petición también podemos preparar una impresión de regalo en el establecimiento.',
                    ],
                    [
                        'q' => '¿Tiene que pagar el destinatario un depósito?',
                        'a' => 'No. <strong>Alquilamos sin depósito</strong>. Las condiciones son claras y justas, el equipamiento del conductor está incluido en el precio.',
                    ],
                    [
                        'q' => '¿Se puede cambiar la fecha de uso?',
                        'a' => 'Sí, <strong>la fecha se puede cambiar previo acuerdo</strong> según la disponibilidad de la moto concreta en nuestro calendario.',
                    ],
                    [
                        'q' => '¿En qué motos se puede canjear el voucher?',
                        'a' => 'En <strong>motos de viaje, deportivas, enduro e infantiles</strong> de la oferta de Motogo24 – según el valor elegido del vale.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Vale regalo para el alquiler de moto – Vysočina',
                'text' => 'Motogo24 es un <strong>alquiler de motos en Vysočina</strong> con <strong>servicio 24/7</strong>, <strong>sin depósito</strong> y <strong>equipamiento incluido</strong>. El voucher de regalo es la opción ideal para regalar una experiencia de <em>motorbike rental</em> – desde <strong>motos de viaje</strong>, pasando por <strong>deportivas</strong>, hasta <strong>enduro</strong> y <strong>motos infantiles</strong>.',
                'buttons' => [
                    [
                        'label' => 'PEDIR VOUCHER',
                        'href' => '/koupit-darkovy-poukaz',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_cena' => [
            'seo' => [
                'title' => 'Alquiler de motos Vysočina – Cómo alquilar – Qué incluye el precio',
                'description' => 'Descubre qué incluye el precio del alquiler de motos en MotoGo24. Condiciones claras, equipo y servicios sin tarifas ocultas. Reserva tu moto fácilmente online.',
                'keywords' => 'alquiler de motos Vysočina, alquiler motos Pelhřimov, alquiler sin depósito, alquiler 24/7, reserva online moto',
            ],
            'h1' => 'Qué incluye el precio del alquiler de motos',
            'intro' => 'En <strong>MotoGo24 – alquiler de motos en Vysočina</strong> obtienes condiciones justas. <strong>Sin depósito, con equipo del conductor incluido y servicio 24/7</strong>. Todo lo que necesitas para una conducción segura y agradable está incluido.',
            'cta' => [
                'title' => 'Equipo incluido – alquiler de motos MotoGo24 – Vysočina',
                'text' => '<strong>MotoGo24 es un alquiler de motos moderno en Vysočina</strong> con equipo del conductor incluido, alquiler sin depósito y servicio 24/7. Elige una <strong>moto de turismo, supermoto, naked o infantil</strong> y reserva online.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR EN LÍNEA',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                        'aria' => 'Reservar moto con equipo incluido en Motogo24',
                    ],
                ],
            ],
        ],
        'jak_pujcit_dokumenty' => [
            'seo' => [
                'title' => 'Alquiler de motos Vysočina – Documentos y manuales',
                'description' => 'Contrato de alquiler, condiciones y documentos necesarios para alquilar una moto. Sin depósito, normas claras, seguro incluido.',
                'keywords' => 'contrato alquiler moto, documentos alquiler, condiciones alquiler, seguro moto, MotoGo24',
            ],
            'h1' => 'Contrato de alquiler y depósito – condiciones justas sin anticipo',
            'intro' => 'En <strong>MotoGo24</strong> apostamos por la simplicidad y la equidad. Alquilamos <strong>sin depósito</strong>, con un <strong>contrato claro</strong>, <strong>seguro incluido</strong> y <strong>equipo del conductor</strong>.',
            'top_cta' => [
                'label' => 'RESERVAR EN LÍNEA',
                'href' => '/rezervace',
                'aria' => 'Reservar moto online en Motogo24',
            ],
            'cta' => [
                'title' => 'Contrato sin depósito – alquiler de motos Vysočina',
                'text' => 'MotoGo24 es un <strong>alquiler de motos en Vysočina</strong> con condiciones justas.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR EN LÍNEA',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_pristaveni' => [
            'seo' => [
                'title' => 'Entrega de la moto | MotoGo24',
                'description' => 'Entrega de la moto en tu puerta. Llevamos la moto al hotel, estación o cualquier dirección. Tarifa desde 290 Kč. Servicio 24/7.',
                'keywords' => 'entrega moto, llevar moto, entrega motocicleta, alquiler motos Vysočina',
            ],
            'h1' => 'Entrega de la moto – directa a ti',
            'intro' => '¿Quieres salir sin tener que ir al alquiler? Organizamos <strong>la entrega de la moto</strong> en el <strong>lugar acordado</strong>.',
            'top_cta' => [
                'label' => 'RESERVAR CON ENTREGA',
                'href' => '/rezervace?delivery=1',
            ],
            'cta' => [
                'title' => 'Entrega de la moto – alquiler de motos Vysočina',
                'text' => 'MotoGo24 ofrece <strong>entrega de la moto</strong> en la región y fuera. <strong>Servicio 24/7, sin depósito, equipo incluido</strong>.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR CON ENTREGA',
                        'href' => '/rezervace?delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_jinde' => [
            'seo' => [
                'title' => 'Devolución de moto en otro lugar | MotoGo24',
                'description' => 'Devuelve la moto fuera del alquiler – desde el hotel, estación u otra dirección. Recogida en Vysočina y fuera. Precio según distancia, servicio 24/7.',
                'keywords' => 'devolución moto otro lugar, recogida moto, devolución fuera alquiler, alquiler motos Vysočina',
            ],
            'h1' => 'Devolución de moto en otro lugar – recogida hasta donde estés',
            'intro' => 'No tienes que volver al alquiler. <strong>MotoGo24</strong> ofrece <strong>recogida de la moto</strong> desde el lugar que te conviene – hotel, estación, dirección propia.',
            'top_cta' => [
                'label' => 'RESERVAR CON RECOGIDA',
                'href' => '/rezervace?return_delivery=1',
            ],
            'cta' => [
                'title' => 'Devolución de moto en cualquier lugar – MotoGo24',
                'text' => 'MotoGo24 organiza la <strong>recogida de la moto</strong> desde el lugar que te conviene. <strong>24/7, sin depósito, sin preocupaciones.</strong>',
                'buttons' => [
                    [
                        'label' => 'RESERVAR CON RECOGIDA',
                        'href' => '/rezervace?return_delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'faq' => [
            'seo' => [
                'title' => 'Preguntas frecuentes | MotoGo24',
                'description' => 'Preguntas frecuentes sobre alquiler de motos. Reserva, recogida, devolución, condiciones, entrega, viajes al extranjero, vales regalo.',
                'keywords' => 'FAQ alquiler motos, preguntas alquiler moto, condiciones alquiler, depósito, equipo',
            ],
            'h1' => 'Preguntas frecuentes – alquiler de motos MotoGo24',
            'closing' => 'Nuestro <strong>alquiler de motos en Vysočina</strong> está aquí para todos los que quieren vivir una <strong>conducción inolvidable</strong> sin complicaciones.',
            'cta' => [
                'label' => 'Reservar moto online',
                'href' => '/rezervace',
            ],
        ],
        'home' => [
            'seo' => [
                'title' => 'Alquiler de motos en Vysočina | MotoGo24',
                'description' => 'Alquila una moto en Vysočina. Sin depósito, equipo incluido, servicio 24/7. Motos de turismo, sport, enduro e infantiles. Reserva online.',
                'keywords' => 'alquiler motos Vysočina, alquiler motos Pelhřimov, alquiler sin depósito, alquiler 24/7, motos para alquilar, reserva online moto',
                'og_image' => NULL,
            ],
            'hero' => [
                'image' => 'gfx/hero-banner.jpg',
                'alt' => 'Alquiler de motos Vysočina',
                'eyebrow' => '<strong>Alquiler de motos</strong> en Vysočina',
                'body' => 'Alquila una moto en Vysočina fácilmente online.<br>Elige entre modelos de turismo, sport y enduro.<br>Reserva con pago con tarjeta y recogida rápida.',
                'cta_primary' => [
                    'label' => 'ELIGE TU MOTO',
                    'href' => '/katalog',
                    'cls' => 'btngreen',
                ],
                'cta_secondary' => [
                    'label' => 'CÓMO FUNCIONA',
                    'href' => '/jak-pujcit',
                    'cls' => 'btndark',
                ],
            ],
            'h1' => 'Alquiler de motos Vysočina Motogo24 – sin depósito y 24/7',
            'intro' => 'Bienvenido a <strong>Motogo24</strong> – tu alquiler de motos en Vysočina. Aquí alquilas una moto <strong>sin depósito</strong>, con equipo incluido y en modo <strong>24/7</strong>. Ya busques moto de turismo, sport, enduro o infantil, Motogo24 en el corazón de Vysočina te ofrece la moto perfecta.',
            'signposts_title' => 'Guía rápida por Motogo24',
            'signposts' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => 'Catálogo de motos',
                    'text' => 'Mira nuestra oferta de motos de alquiler — desde modelos sport hasta de turismo.',
                    'btn' => 'CATÁLOGO DE MOTOS',
                    'href' => '/katalog',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => 'Cómo alquilar una moto',
                    'text' => 'Proceso sencillo: elige una moto, reserva y sal a la carretera.',
                    'btn' => 'CÓMO ALQUILAR',
                    'href' => '/jak-pujcit',
                ],
                [
                    'icon' => 'gfx/rezervace-online.svg',
                    'title' => 'Reserva online',
                    'text' => 'Reserva tu moto a través de nuestro sencillo sistema online.',
                    'btn' => 'RESERVAR MOTO',
                    'href' => '/rezervace',
                ],
                [
                    'icon' => 'gfx/kontakt.svg',
                    'title' => 'Contacto y mapa',
                    'text' => 'Visita nuestro alquiler de motos en Pelhřimov o contáctanos.',
                    'btn' => 'CONTACTO',
                    'href' => '/kontakt',
                ],
                [
                    'icon' => 'gfx/faq.svg',
                    'title' => 'Preguntas frecuentes',
                    'text' => 'Las preguntas más habituales sobre el alquiler de motos en un solo lugar.',
                    'btn' => 'FAQ',
                    'href' => '/jak-pujcit/faq',
                ],
                [
                    'icon' => 'gfx/uzij-si-jizdu.svg',
                    'title' => 'Rutas en moto',
                    'text' => 'Descubre las mejores rutas en moto por la República Checa para turistas y locales.',
                    'btn' => 'RUTAS EN MOTO',
                    'href' => '/blog',
                ],
            ],
            'motos_section' => [
                'title' => 'Nuestras motos para alquilar en Vysočina',
                'intro' => 'Mira nuestra oferta de motos de turismo, sport y enduro de nuestro alquiler en Vysočina.',
                'empty' => 'Actualmente no tenemos motos disponibles.',
                'cta_label' => 'CATÁLOGO DE MOTOS',
                'cta_href' => '/katalog',
                'limit' => 4,
            ],
            'process' => [
                'title' => 'Cómo funciona el alquiler de motos en Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Elige',
                        'text' => 'Elige tu moto ideal de nuestra oferta de motos de alquiler.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Reserva',
                        'text' => 'Reserva tu moto a través de nuestro sencillo sistema online.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '3. Recoge',
                        'text' => 'Recoge la moto en nuestro alquiler de Pelhřimov.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '4. Disfruta del viaje',
                        'text' => 'Vive la libertad y descubre la República Checa en motos de alquiler.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Preguntas frecuentes',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => '¿Cómo puedo reservar una moto?',
                        'a' => 'Puedes reservar una moto a través de nuestro sistema de reserva online aquí mismo en la web. También puedes contactarnos por correo, teléfono o redes sociales.',
                    ],
                    [
                        'q' => '¿Puedo alquilar una moto sin reserva previa?',
                        'a' => 'Por desgracia no. Cada moto debe reservarse con antelación – online, por teléfono, correo o redes sociales.',
                    ],
                    [
                        'q' => '¿Tengo que dejar un depósito?',
                        'a' => '¡No! Con nosotros <strong>no pagas ningún depósito</strong>. En esto nuestro alquiler se diferencia claramente de la mayoría de la competencia.',
                    ],
                    [
                        'q' => '¿Puedo viajar al extranjero con la moto?',
                        'a' => 'Sí, puedes viajar al extranjero con la moto sin problema. No restringimos los viajes fuera de la República Checa; solo debes respetar la validez territorial del seguro (carta verde).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Reserva tu moto online',
                'text' => 'Nuestro <strong>alquiler de motos Vysočina</strong> está abierto <strong>24/7</strong>. Unos clics y tu viaje comienza.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR MOTO',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Vale regalo',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Consejos de rutas',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
            'blog' => [
                'title' => 'Blog y consejos',
                'empty' => 'Aún no hay artículos.',
                'cta_label' => 'LEER MÁS EN EL BLOG',
                'cta_href' => '/blog',
                'limit' => 3,
            ],
            'reviews' => [
                'title' => 'Lo que dicen nuestros clientes',
                'intro' => 'Reseñas reales de motoristas que alquilaron con nosotros. Gracias por cada valoración.',
            ],
        ],
        'pujcovna' => [
            'seo' => [
                'title' => 'Sobre el alquiler de motos | MotoGo24',
                'description' => 'Alquiler de motos Motogo24 en Vysočina. Sin depósito, con reserva online y equipo incluido. Motos de turismo, sport, enduro e infantiles. Servicio 24/7.',
                'keywords' => 'alquiler motos, alquiler motos Vysočina, motos sin depósito, alquiler 24/7, equipo incluido',
            ],
            'breadcrumb' => [
                [
                    'label' => 'Inicio',
                    'href' => '/',
                ],
                'Alquiler de motos',
            ],
            'intro' => [
                'h1' => 'Alquiler de motos Vysočina Motogo24',
                'body' => 'Nuestro <strong>alquiler de motos en Vysočina</strong> en Pelhřimov ofrece <strong>alquiler de motos</strong> sin obstáculos – <strong>sin depósito</strong>, con <strong>reserva online</strong> y <strong>equipo incluido</strong>. Elige entre <strong>motos de turismo</strong>, <strong>sport</strong>, <strong>enduro</strong> e <strong>infantiles</strong>, y sal cuando quieras: estamos abiertos <strong>24/7</strong>.',
            ],
            'benefits' => [
                'title' => 'Por qué alquilar con nosotros',
                'closing' => '¿Buscas un <strong>alquiler de motos en Vysočina</strong>? Motogo24 ofrece condiciones justas, un proceso claro y máquinas en perfecto estado para viajes por la República Checa y al extranjero.',
                'buttons' => [
                    [
                        'label' => 'Ver motos para alquilar',
                        'href' => '/katalog',
                        'cls' => 'btngreen',
                    ],
                    [
                        'label' => 'RESERVAR',
                        'href' => '/rezervace',
                        'cls' => 'btngreen pulse',
                    ],
                ],
                'items' => [
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'Sin depósito',
                        'text' => 'y sin tarifas ocultas',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Reserva online',
                        'text' => 'en unos clics',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Equipo del piloto incluido',
                        'text' => 'casco, chaqueta, pantalones y guantes',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => 'Servicio 24/7',
                        'text' => 'para recogida y devolución según tu reserva',
                    ],
                    [
                        'icon' => 'gfx/ico-spolecne.svg',
                        'title' => 'Estamos contigo',
                        'text' => 'si pasa cualquier cosa',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Entrega y recogida',
                        'text' => 'en el lugar acordado',
                    ],
                ],
            ],
            'process' => [
                'title' => 'Cómo funciona el alquiler en Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Elige una moto',
                        'text' => 'Mira nuestra oferta y elige el tipo que se ajuste a ti, a tu experiencia y a tu permiso de conducir.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Reserva online',
                        'text' => 'Haz tu reserva por fecha o por una moto concreta que quieras alquilar.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => '3. Elige el equipo',
                        'text' => 'El equipo del piloto está incluido; el del pasajero tiene un suplemento. La talla la eliges en el local.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => '4. Paga',
                        'text' => 'Paga fácilmente online a través de la pasarela de pago.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '5. Recoge la moto',
                        'text' => 'Recoge la moto en el alquiler o en el lugar que elegiste al reservar.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '6. Disfruta del viaje',
                        'text' => 'Sal a la carretera, descubre nuevas experiencias y disfruta plenamente de la libertad sobre dos ruedas.',
                    ],
                    [
                        'icon' => 'gfx/vrat-motorku-vcas.svg',
                        'title' => '7. Devuelve la moto',
                        'text' => 'Devuelve la moto el día acordado – directamente en el alquiler o en el lugar acordado.',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'Descuento para el próximo viaje',
                        'text' => 'Tras devolver la moto te enviaremos automáticamente un código de descuento de 200 Kč para tu próxima reserva.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Preguntas frecuentes',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => '¿Cómo puedo reservar una moto?',
                        'a' => 'Puedes reservar una moto a través de nuestro sistema de reserva online aquí mismo en la web. También puedes contactarnos por correo, teléfono o redes sociales.',
                    ],
                    [
                        'q' => '¿Puedo alquilar una moto sin reserva previa?',
                        'a' => 'Por desgracia no. Cada moto debe reservarse con antelación.',
                    ],
                    [
                        'q' => '¿Tengo que dejar un depósito?',
                        'a' => '¡No! Con nosotros <strong>no pagas ningún depósito</strong>. En esto nuestro alquiler se diferencia claramente de la mayoría de la competencia.',
                    ],
                    [
                        'q' => '¿Puedo viajar al extranjero con la moto?',
                        'a' => 'Sí, puedes viajar al extranjero con la moto sin problema. No restringimos los viajes fuera de la República Checa; solo debes respetar la validez territorial del seguro (carta verde).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Reserva tu moto online',
                'text' => 'Nuestro <strong>alquiler de motos Vysočina</strong> está abierto <strong>24/7</strong>.',
                'buttons' => [
                    [
                        'label' => 'RESERVAR MOTO',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Vale regalo',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Consejos de rutas',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
        ],
    ],
];
