<?php
// MotoGo24 — pages_en.php (auto-generated by merge_pages.php; parts: 1)

return [
    'pages' => [
        'oblasti' => [
            'hero' => [
                'h1' => 'Motorcycle rental in your region and town',
                'intro' => 'Looking for a <strong>motorcycle rental</strong> near you? MotoGo24 delivers a motorcycle to towns across the Czech Republic. Pick your region and see where we bring bikes – <strong>no deposit</strong>, <strong>online booking</strong> and full riding gear included.',
            ],
            'regionsTitle' => 'Choose your region',
            'citiesLabel' => 'Motorcycle rental in towns:',
            'regionCta' => 'View region',
            'cta' => [
                'title' => 'Town not on the list?',
                'text' => 'We deliver bikes almost anywhere in the Czech Republic. Drop us a message or book online right away.',
                'buttons' => [
                    ['label' => 'BOOK A MOTORCYCLE', 'href' => '/rezervace', 'cls' => 'btngreen pulse'],
                    ['label' => 'Contact us', 'href' => '/kontakt', 'cls' => 'btndark'],
                ],
            ],
            'detail' => [
                'seoTitle' => 'Motorcycle rental {region} – rent a bike in towns of the region | MotoGo24',
                'seoDescription' => 'Motorcycle rental in {regionLoc}. MotoGo24 delivers a motorcycle to towns in {regionLoc} – no deposit, online booking, gear included. We also rent in: {cities}.',
                'heroTagline' => 'Rent a motorcycle in {regionLoc} – no deposit, gear included, 24/7 pickup.',
                'heroCta' => 'BOOK A MOTORCYCLE',
                'h1' => 'Motorcycle rental {region}',
                'intro' => 'Looking for a reliable <strong>motorcycle rental in {regionLoc}</strong>? MotoGo24 brings and delivers a bike straight to your town. We offer <strong>motorcycle rental with no deposit</strong>, online booking and full riding gear included. Whether you live in a big city or a small town, we are happy to deliver.',
                'citiesTitle' => 'Motorcycle rental in towns of the region',
                'citiesIntro' => 'We deliver and collect bikes in these towns and their surroundings:',
                'cityTitle' => 'Motorcycle rental {city}',
                'cityText' => 'Rent a motorcycle in {city} and the surrounding area. We deliver the bike to an agreed spot and collect it after your rental – with no deposit and everything you need.',
                'cta' => [
                    'title' => 'Book a motorcycle in {regionLoc}',
                    'text' => 'Pick a bike, choose your dates and we will deliver it. MotoGo24 is open around the clock.',
                    'buttons' => [
                        ['label' => 'BOOK A MOTORCYCLE', 'href' => '/rezervace', 'cls' => 'btngreen pulse'],
                        ['label' => 'View motorcycles', 'href' => '/katalog', 'cls' => 'btndark'],
                    ],
                ],
                'faq' => [
                    'title' => 'Frequently asked questions',
                    'items' => [
                        ['q' => 'Do you deliver the motorcycle to my town?', 'a' => 'Yes. We deliver the bike to an agreed spot in {regionLoc} and elsewhere in the Czech Republic. Just enter the place in your booking.'],
                        ['q' => 'Do I have to pay a deposit?', 'a' => 'No. Our <strong>motorcycle rental</strong> requires no deposit or card hold.'],
                    ],
                ],
            ],
        ],
        'kontakt' => [
            'seo' => [
                'title' => 'Contact | MotoGo24 – motorcycle rental Vysočina',
                'description' => 'Contacts for the Motogo24 motorcycle rental in Pelhřimov. Phone +420 774 256 271, e-mail info@motogo24.cz. 24/7 service, address Mezná 9, 393 01 Pelhřimov.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Contacts – Motogo24 motorcycle rental',
            'intro' => 'Got a question about <strong>renting a motorcycle</strong>, want to order a <strong>gift voucher</strong>, need help choosing or simply want to <strong>arrange a booking</strong>? We are here for you every day, <strong>around the clock</strong>.',
            'quick' => [
                [
                    'label' => 'CALL US',
                    'value' => '+420 774 256 271',
                    'href' => 'tel:+420774256271',
                    'icon' => 'gfx/telefon.svg',
                    'alt' => 'Phone',
                ],
                [
                    'label' => 'WRITE TO US',
                    'value' => 'info@motogo24.cz',
                    'href' => 'mailto:info@motogo24.cz',
                    'icon' => 'gfx/email.svg',
                    'alt' => 'E-mail',
                ],
                [
                    'label' => 'DATA BOX',
                    'value' => 'iuw3vnb',
                    'href' => NULL,
                    'icon' => NULL,
                    'alt' => NULL,
                ],
            ],
            'place' => [
                'title' => 'Premises',
                'address_label' => 'Address:',
                'address' => 'Mezná 9, 393 01 Pelhřimov',
                'hours_label' => 'Opening hours:',
                'hours' => 'MON – SUN: 00:00 – 24:00 (24/7)<br>Including weekends and public holidays',
                'billing_title' => 'Billing details',
                'billing_name' => 'Bc. Petra Semorádová',
                'billing_address' => 'Mezná 9, 393 01 Pelhřimov',
                'billing_ico' => '21874263',
                'billing_vat' => 'Not a VAT payer',
                'billing_note' => 'The company was registered on 31 July 2024 with the Municipal Office in Pelhřimov.',
            ],
            'social_title' => 'Follow us',
            'social' => [
                [
                    'label' => 'facebook',
                    'href' => '#',
                    'icon' => 'gfx/facebook.svg',
                    'alt' => 'Facebook',
                ],
                [
                    'label' => 'instagram',
                    'href' => '#',
                    'icon' => 'gfx/instagram.svg',
                    'alt' => 'Instagram',
                ],
            ],
            'side_cta' => [
                'title' => 'Want to arrange a booking?',
                'text' => 'Book your motorcycle online in just a few minutes and head off for an adventure.',
                'button' => [
                    'label' => 'BOOK ONLINE',
                    'href' => '/rezervace',
                    'cls' => 'btndark',
                ],
            ],
            'map' => [
                'title' => 'Where to find us',
                'src' => 'https://www.google.com/maps?q=Mezn%C3%A1+9%2C+393+01+Pelh%C5%99imov&hl=cs&z=15&output=embed',
            ],
            'seo_text' => [
                'title' => 'Contacts – motorcycle rental Vysočina (Pelhřimov)',
                'body' => 'Motogo24 is a <strong>modern motorcycle rental in Vysočina</strong>. We are based in <strong>Pelhřimov</strong>, open <strong>24/7</strong>, and we rent <strong>without deposit</strong>, with full <strong>gear included</strong>.',
            ],
        ],
        'jak_pujcit' => [
            'seo' => [
                'title' => 'How to rent a motorcycle | MotoGo24',
                'description' => 'How to rent a motorcycle at Motogo24. A simple process: choose, book, pick up. Without deposit, gear included, 24/7 service.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'How to rent a motorcycle',
            'intro' => 'At <strong>Motogo24 – motorcycle rental in Vysočina</strong>, renting is simple, quick and fair.',
            'links' => [
                [
                    'href' => '/jak-pujcit/postup',
                    'label' => 'Rental process',
                ],
                [
                    'href' => '/jak-pujcit/prevzeti',
                    'label' => 'Pick-up at the rental',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-pujcovna',
                    'label' => 'Returning the motorcycle to the rental',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-jinde',
                    'label' => 'Returning the motorcycle elsewhere',
                ],
                [
                    'href' => '/jak-pujcit/co-v-cene',
                    'label' => 'What is included in the rental price',
                ],
                [
                    'href' => '/jak-pujcit/pristaveni',
                    'label' => 'Motorcycle delivery',
                ],
                [
                    'href' => '/jak-pujcit/dokumenty',
                    'label' => 'Documents and manuals',
                ],
                [
                    'href' => '/jak-pujcit/faq',
                    'label' => 'Frequently asked questions',
                ],
            ],
        ],
        'jak_pujcit_postup' => [
            'seo' => [
                'title' => 'Motorcycle rental process | MotoGo24',
                'description' => 'Motorcycle rental process at Motogo24 step by step. Online booking, gear included, without deposit, 24/7 service and delivery option.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Rental process',
            'intro_p1' => 'At <strong>Motogo24 – motorcycle rental in Vysočina</strong> renting is simple, quick and fair.&nbsp;<strong>No deposit, with rider gear included and 24/7 service for picking up and returning the motorcycle</strong>. See for yourself how easily it works.',
            'intro_h2' => 'How to rent a motorcycle – Motogo24 rental – Vysočina',
            'intro_p2' => 'At our <strong>motorcycle rental</strong> you can do everything online: choose a motorcycle, pick a date and fill in the booking form – including gear and handover method. Pick up the motorcycle in Pelhřimov, or order delivery anywhere in the Czech Republic. You pay online when completing the booking.',
            'process' => [
                'title' => 'How the rental works step by step',
                'grid' => 'gr4',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Pick a motorcycle',
                        'text' => 'Browse our range of <strong>touring, sports, enduro and kids motorcycles</strong> and choose the right one.',
                    ],
                    [
                        'icon' => 'gfx/kontaktni-udaje.svg',
                        'title' => '2. Number of riders',
                        'text' => 'Choose whether you ride solo or with a passenger. We will offer you suitable bikes and gear.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '3. Online booking',
                        'text' => 'Easily book a motorcycle by date. Pay in advance <strong>online</strong>.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => '4. Gear included',
                        'text' => 'As the rider, you automatically get a helmet, jacket, trousers and gloves. You choose your size when booking.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => '5. Confirmation and payment',
                        'text' => 'The booking is binding once confirmed. You pay online.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '6. Picking up the motorcycle',
                        'text' => 'Pick up the motorcycle in person in Pelhřimov or use our <strong>delivery</strong> to an agreed location.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '7. Enjoy the ride',
                        'text' => 'Hit the road – <strong>without deposit, without stress</strong>, with clear terms and insurance included.',
                    ],
                    [
                        'icon' => 'gfx/vrat-motorku-vcas.svg',
                        'title' => '8. Returning the motorcycle',
                        'text' => 'You can return the motorcycle any time during the last day of the rental. No need to refuel or wash it.',
                    ],
                ],
            ],
            'gallery' => [
                'image' => '/gfx/vybava_diagram_motogo24_1200px.svg',
                'alt' => 'Gear diagram&nbsp;Motogo24',
                'group' => 'gal_1',
            ],
            'sizes' => [
                'adult' => [
                    'title' => 'Adult gear',
                    'headers' => [
                        'Gear',
                        'Available sizes',
                    ],
                    'rows' => [
                        [
                            'Helmet',
                            'XS, S, M, L, XL',
                        ],
                        [
                            'Jacket',
                            'S, M, L, XL, 2XL, 3XL, 4XL, 5XL, 6XL',
                        ],
                        [
                            'Trousers',
                            'M, L, XL, 2XL, 3XL, 4XL, 5XL, 6XL',
                        ],
                        [
                            'Gloves',
                            'M, L, XL',
                        ],
                        [
                            'Motorcycle boots',
                            '39–46',
                        ],
                        [
                            'Balaclava',
                            'universal',
                        ],
                        [
                            'Hi-vis vest&nbsp;',
                            'universal',
                        ],
                    ],
                ],
                'kid' => [
                    'title' => 'Kids\' gear',
                    'headers' => [
                        'Gear',
                        'Available sizes',
                    ],
                    'rows' => [
                        [
                            'Helmet',
                            'S (47–48 cm), M (49–50 cm), L (51–52 cm)',
                        ],
                        [
                            'Jacket',
                            '110–116, 122–128, 134–140, 146–152 cm',
                        ],
                        [
                            'Trousers',
                            '110–116, 122–128, 134–140, 146–152 cm',
                        ],
                        [
                            'Gloves',
                            'XS/S (4–7 yrs), M/L (8–12 yrs)',
                        ],
                        [
                            'Motorcycle boots',
                            '29–35',
                        ],
                        [
                            'Balaclava',
                            'S (4–7 yrs), M (8–12 yrs)',
                        ],
                        [
                            'Hi-vis vest&nbsp;',
                            'XS, S, M',
                        ],
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Frequently asked questions',
                'items' => [
                    [
                        'q' => 'Is a deposit required when renting?',
                        'a' => 'No. <strong>We rent without deposit</strong> – fairly and without unnecessary obstacles.',
                    ],
                    [
                        'q' => 'Is the gear included in the rental price?',
                        'a' => 'Yes. Every rider gets a <strong>helmet, jacket, trousers and gloves for free</strong>.',
                    ],
                    [
                        'q' => 'Where can I pick up the motorcycle?',
                        'a' => 'Pick-up takes place in Pelhřimov, or we offer <strong>motorcycle delivery</strong> to a location of your choice.',
                    ],
                    [
                        'q' => 'By when do I have to return the motorcycle?',
                        'a' => 'You can return the motorcycle any time during the last day of the rental – even at midnight.',
                    ],
                ],
                'more_link' => [
                    'label' => 'More frequently asked questions',
                    'href' => '/jak-pujcit/faq',
                    'aria' => 'Read more frequently asked questions',
                ],
            ],
            'cta' => [
                'title' => 'Ready to ride?',
                'text' => 'Book your motorcycle online today and enjoy <strong>freedom on two wheels</strong>.',
                'buttons' => [
                    [
                        'label' => 'BOOK ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
            'intro' => '<p>At <strong>Motogo24 – motorcycle rental in Vysočina</strong>, renting is simple, quick and fair. <strong>Without deposit, with gear included and 24/7 service</strong>. See how easy it is.</p><p>&nbsp;</p><h2>How to rent a motorcycle – Motogo24 Vysočina rental</h2><p>At the <strong>Motogo24 motorcycle rental</strong>, the <strong>rental process</strong> is simple: <strong>online booking</strong>, <strong>gear included</strong>, <strong>without deposit</strong>, <strong>24/7 service</strong> and the option of <strong>motorcycle delivery</strong>. Whether you are looking for a <strong>touring motorcycle</strong> for the weekend, a <strong>sports motorcycle</strong> for adrenaline or an <strong>enduro</strong> for off-road, you will find the ideal solution with us.</p>',
        ],
        'jak_pujcit_vyzvednuti' => [
            'seo' => [
                'title' => 'Motorcycle pick-up at the rental | MotoGo24',
                'description' => 'Motorcycle pick-up at the rental in Pelhřimov. 24/7 service, without deposit, gear included. What to bring and how the handover works.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Motorcycle pick-up at the rental – fast, simple and 24/7',
            'intro' => 'At <strong>Motogo24 – motorcycle rental Vysočina</strong>, <strong>picking up a motorcycle</strong> takes only a few minutes. We rent <strong>without deposit</strong>, with <strong>gear included</strong> and <strong>24/7 service</strong>.',
            'top_cta' => [
                'aria' => 'Go to the online booking for a motorcycle at the Motogo24 rental',
                'label' => 'BOOK ONLINE',
                'href' => '/rezervace',
            ],
            'place' => [
                'map_src' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d53928.274636159236!2d15.154130970132716!3d49.35168867371007!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470ce75bf69a97b3%3A0xe75f9d3fadf02b5b!2zTWV6bsOhIDksIDM5MyAwMSBNZXpuw6E!5e0!3m2!1scs!2scz!4v1759860051295!5m2!1scs!2scz',
                'title' => 'Where the pick-up takes place',
                'address_label' => 'Address:',
                'hours_label' => 'Opening hours:',
                'map_title' => 'How to find us',
                'address' => 'Mezná 9, 393 01 <strong>Pelhřimov</strong> (Vysočina)',
                'hours' => '<em>24/7</em>',
                'phone' => '+420 774 256 271',
                'return_title' => 'Returning the motorcycle – stress-free',
                'return_text' => 'You can return the motorcycle <strong>any time during the last day of the rental</strong>. For more information see <a href="/jak-pujcit/vraceni-pujcovna">return at the rental</a> or <a href="/jak-pujcit/vraceni-jinde">return elsewhere</a>.',
            ],
            'process' => [
                'title' => 'How pickup at the rental works',
                'grid' => 'gr4',
                'steps' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Come at the agreed time',
                        'text' => 'To our address: Mezná 9, 393 01 Pelhřimov.',
                    ],
                    [
                        'icon' => 'gfx/overime-doklady.svg',
                        'title' => 'We verify the documents',
                        'text' => 'ID card/passport and a driving licence of the appropriate category',
                    ],
                    [
                        'icon' => 'gfx/doplnime-smlouvu.svg',
                        'title' => 'We complete the contract',
                        'text' => 'We complete the pre-filled rental contract with the data from your documents.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'You choose and try on the gear',
                        'text' => 'You can try on the gear from your booking in our fitting cubicle.',
                    ],
                    [
                        'icon' => 'gfx/prevezmi-motorku.svg',
                        'title' => 'We go over the motorcycle together',
                        'text' => 'We check the condition of the machine and you get familiar with its controls.',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'We sign the handover protocol',
                        'text' => 'We document the condition of the motorcycle and gear before the rental.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'We hand over the keys',
                        'text' => 'The motorcycle is ready and waiting for you.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => 'You can set off',
                        'text' => 'Hit the road – no deposit, no stress. The rest is just asphalt and freedom.',
                    ],
                ],
            ],
            'amenities' => [
                'title' => 'What you\'ll find at the rental',
                'lead' => 'For a comfortable pickup we\'ve got ready – all free:',
                'items' => [
                    'customer parking (limited capacity)',
                    'Wi-Fi',
                    'toilet',
                    'a fitting cubicle to try on the gear',
                    'lockable lockers for storing personal items you don\'t want to take on the trip (limited capacity)',
                ],
                'cta' => [
                    'label' => 'BOOK A TIME',
                    'href' => '/rezervace',
                    'aria' => 'Book a time to pick up a motorcycle at Motogo24',
                ],
            ],
            'bring' => [
                'title' => 'What to bring with you',
                'items' => [
                    '<strong>ID card / passport</strong>',
                    '<strong>Driving licence</strong> of the relevant category (A/A2 depending on the motorcycle)',
                    '<strong>Suitable footwear</strong> (motorcycle boots can be rented as an extra)',
                ],
                'cta' => [
                    'label' => 'BOOK A DATE',
                    'href' => '/rezervace',
                ],
            ],
            'faq' => [
                'title' => 'Frequently asked questions about pick-up',
                'items' => [
                    [
                        'q' => 'Do I have to pay a deposit at pick-up?',
                        'a' => 'No, <strong>we rent without deposit</strong>. The terms are clear and fair.',
                    ],
                    [
                        'q' => 'Is contactless handover possible?',
                        'a' => 'Yes, we offer <strong>contactless handover</strong> by arrangement.',
                    ],
                    [
                        'q' => 'What if I cannot make the agreed time?',
                        'a' => 'Let us know by phone – we will adjust the time, or offer <strong>delivery</strong>.',
                    ],
                    [
                        'q' => 'Is gear for the passenger also included in the price?',
                        'a' => 'Gear for the rider is always included. Gear for the passenger can be added as an <strong>extra</strong>.',
                    ],
                ],
            ],
            'mid_cta' => [
                'label' => 'BOOK A PICKUP',
                'href' => '/rezervace',
                'aria' => 'Book a motorcycle pickup at the Motogo24 rental',
            ],
            'cta' => [
                'text2' => 'Choose a <strong>touring, supermoto, naked or kids\' motorcycle</strong> and book it conveniently online.',
                'title' => 'Motorcycle pick-up at the rental – Motogo24 Vysočina',
                'text' => 'Motogo24 is a <strong>motorcycle rental in Vysočina</strong> with <strong>24/7 pick-up and return</strong>, <strong>without deposit</strong> and with <strong>gear included</strong>.',
                'buttons' => [
                    [
                        'label' => 'BOOK ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
            'steps' => [
                'title' => 'How the pick-up works step by step',
                'items' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Arrive at the agreed time',
                        'text' => 'at our address or wait for the delivery',
                    ],
                    [
                        'icon' => 'gfx/overime-doklady.svg',
                        'title' => 'We verify your documents',
                        'text' => 'ID/passport + driving licence of the relevant category',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'We hand over the motorcycle and gear',
                        'text' => 'helmet, jacket, trousers, gloves',
                    ],
                    [
                        'icon' => 'gfx/prevezmi-motorku.svg',
                        'title' => 'A short briefing on the bike',
                        'text' => 'controls, tips, route recommendations',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'We sign the handover protocol',
                        'text' => 'and you can hit the road',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_pujcovna' => [
            'seo' => [
                'title' => 'Returning the motorcycle at the rental | MotoGo24',
                'description' => 'Returning the motorcycle directly at the Pelhřimov rental. 24/7, without deposit, without unnecessary admin. How motorcycle return works step by step.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Returning the motorcycle at the rental',
            'intro' => 'You return the motorcycle conveniently directly at <strong>Motogo24 – motorcycle rental in Vysočina</strong>. <strong>24/7 service</strong>, no stress and fair terms.',
            'process' => [
                'grid' => 'gr4',
                'steps' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Come at the agreed time',
                        'text' => '',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Hand over the keys and gear',
                        'text' => '',
                    ],
                    [
                        'icon' => 'gfx/prevezmi-motorku.svg',
                        'title' => 'We check the condition of the motorcycle and gear together',
                        'text' => '',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'You\'ll get an e-mail with the rental completion confirmation, the final invoice and a discount code for your next booking.',
                        'text' => '',
                    ],
                ],
            ],
            'time' => [
                'title' => 'Return time',
                'text' => 'Please keep to the return time – it helps us make sure the next customer picks up the motorcycle on time. If you do end up running late, please let us know by phone. Until midnight of the last rental day you pay no fee. If you return the motorcycle significantly after that, you\'ll be charged rent for another day.',
            ],
            'issues' => [
                'title' => 'Discrepancies on return',
                'lead' => 'On handover we check the condition of the motorcycle and gear together. If any of the situations below occurs, we draw up a report of the damage found:',
                'items' => [
                    'missing gear',
                    'damaged gear',
                    'damaged motorcycle',
                ],
                'closing' => 'The customer signs the report and receives a copy of it. The further procedure is governed by the terms of the rental contract and the terms and conditions.',
            ],
            'faq' => [
                'title' => 'Frequently asked questions about return at the rental',
                'items' => [
                    [
                        'q' => 'What if I cannot make the agreed return time?',
                        'a' => 'Please let us know by phone. Most often we agree on <strong>moving the time by a few hours</strong>; longer delays may be charged according to the price list.',
                    ],
                    [
                        'q' => 'Do I have to wash the motorcycle?',
                        'a' => 'No. Ordinary dirt is fine, washing is <strong>not required</strong>.',
                    ],
                    [
                        'q' => 'Do I have to return the motorcycle with a full tank?',
                        'a' => 'It is not mandatory. If the tank is not full, we will refuel it and <strong>charge only the actual price</strong> with no surcharges.',
                    ],
                    [
                        'q' => 'What if the rental is closed?',
                        'a' => 'Our service is <strong>24/7</strong>. At night just call +420 774 256 271 and we will arrange the handover.',
                    ],
                    [
                        'q' => 'Can I return the motorcycle elsewhere?',
                        'a' => 'Yes, use <a href="/jak-pujcit/vraceni-jinde"><strong>returning the motorcycle elsewhere</strong></a> (delivery/pick-up according to the price list).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Returning the motorcycle at the rental – Motogo24 Pelhřimov',
                'text' => 'Return the motorcycle directly with us in Pelhřimov – <strong>24/7, without deposit, without stress</strong>.',
                'buttons' => [
                    [
                        'label' => 'BOOK ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
            'top_cta' => [
                'label' => 'BOOK ONLINE',
                'href' => '/rezervace',
            ],
            'place' => [
                'title' => 'Where and when to return the motorcycle',
                'address' => 'Mezná 9, 393 01 <strong>Pelhřimov</strong> (Vysočina)',
                'hours' => '<em>24/7</em> – any time during the last day of the rental',
                'phone' => '+420 774 256 271',
                'note_title' => 'What needs to be done',
                'note_text' => 'Return the motorcycle <strong>at the agreed time</strong> and in a similar technical condition to the one you took it over in. <strong>We do not require a full tank or washing.</strong>',
                'map_src' => 'https://frame.mapy.cz/s/?x=15.15413&y=49.35169&z=14&source=coor&id=15.15413%2C49.35169',
            ],
            'steps' => [
                'title' => 'How the return at the rental works',
                'items' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Arrive at the agreed time',
                        'text' => 'at the rental address in Pelhřimov',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Together we check the motorcycle',
                        'text' => 'inspection of bodywork, fuel tank and gear',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'You return the gear',
                        'text' => 'helmet, jacket, trousers, gloves',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'We sign the return protocol',
                        'text' => 'a clear and fair record',
                    ],
                    [
                        'icon' => 'gfx/potvrzeni-rezervace.svg',
                        'title' => 'Done',
                        'text' => 'we will send you a confirmation by e-mail',
                    ],
                ],
            ],
            'tips' => [
                'title' => 'Practical tips for returning',
                'items' => [
                    '<strong>We do not require a full tank</strong> – fuel is charged only when needed.',
                    '<strong>Washing the motorcycle is not required</strong> – ordinary dirt from riding is fine.',
                    '<strong>Late return</strong> – call us in advance so we can arrange a solution.',
                    '<strong>Contactless return</strong> is possible by prior arrangement.',
                ],
                'cta' => [
                    'label' => 'BOOK A DATE',
                    'href' => '/rezervace',
                ],
            ],
        ],
        'poukazy' => [
            'seo' => [
                'title' => 'Motorcycle rental Vysočina - Vouchers',
                'description' => 'Buy a gift voucher for motorcycle rental. Valid for 3 years, without deposit, gear included. Electronic and printed voucher. Online order.',
                'keywords' => 'motorcycle rental Czech Republic',
                'og_image' => 'https://www.motogo24.cz/gfx/darkovy-poukaz.jpg',
            ],
            'h1' => 'Buy a gift voucher – give the experience of two wheels!',
            'intro_left' => '<p>Looking for an original gift for your partner, friend or dad?</p><p>&nbsp;</p><p>Our <strong>gift vouchers for motorcycle rental</strong> from Motogo24 – <strong>motorcycle rental Vysočina</strong> – will please beginners and experienced riders alike.</p><p>&nbsp;</p><p>Choose the voucher value or a specific motorcycle and give the gift of freedom on two wheels.</p>',
            'intro_cta' => [
                'label' => 'ORDER A GIFT VOUCHER',
                'href' => '/koupit-darkovy-poukaz',
                'aria' => 'Order a gift voucher for motorcycle rental at Motogo24',
            ],
            'intro_image' => [
                'src' => 'gfx/darkovy-poukaz.jpg',
                'alt' => 'Gift voucher',
            ],
            'steps' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => '1. Choose',
                    'text' => 'Choose the voucher value or a specific motorcycle.',
                ],
                [
                    'icon' => 'gfx/zaplat.svg',
                    'title' => '2. Pay',
                    'text' => 'Pay online.',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => '3. Receive',
                    'text' => 'After payment, the voucher arrives in your e-mail inbox.',
                ],
            ],
            'validity_note' => 'All vouchers are <strong>valid for 3 years</strong> from the date of issue. <strong>The recipient chooses the rental date</strong> that suits them. They can contact us by e-mail, phone or social media.',
            'why' => [
                'title' => 'Why buy a voucher',
                'items' => [
                    '<strong>Flexible choice</strong> – voucher value or a specific motorcycle.',
                    '<strong>Valid for 3 years</strong> – the recipient picks the date themselves.',
                    '<strong>Without deposit</strong> – fair conditions without unnecessary obstacles.',
                    '<strong>Gear included</strong> – helmet, jacket, trousers and gloves for free.',
                    '<strong>24/7 service</strong> – pick-up and return any time on the rental day.',
                    '<strong>Online order</strong> – the voucher arrives by e-mail after payment.',
                ],
            ],
            'how' => [
                'title' => 'How to use the voucher',
                'items' => [
                    '<strong>Touring motorcycles</strong> – a weekend road trip across Vysočina or the whole Czech Republic.',
                    '<strong>Sports motorcycles</strong> – an adrenaline ride through the corners.',
                    '<strong>Enduro</strong> – light terrain and adventure off the main roads.',
                    '<strong>Kids motorcycles</strong> – first rides for little riders under supervision.',
                ],
            ],
            'catalog_cta' => [
                'label' => 'VIEW MOTORCYCLE CATALOGUE',
                'href' => '/katalog',
            ],
            'faq' => [
                'title' => 'Frequently asked questions about gift vouchers',
                'items' => [
                    [
                        'q' => 'How long is the gift voucher valid?',
                        'a' => 'All vouchers are valid for <strong>3 years</strong> from the date of issue. The recipient chooses the rental date themselves.',
                    ],
                    [
                        'q' => 'How will you deliver the voucher?',
                        'a' => '<strong>Immediately by e-mail</strong> after payment. On request we can also prepare a gift print at our premises.',
                    ],
                    [
                        'q' => 'Does the recipient have to pay a deposit?',
                        'a' => 'No. <strong>We rent without deposit</strong>. The terms are clear and fair, the rider gear is included.',
                    ],
                    [
                        'q' => 'Can the redemption date be changed?',
                        'a' => 'Yes, <strong>the date can be changed by arrangement</strong> based on the availability of the specific motorcycle in our calendar.',
                    ],
                    [
                        'q' => 'Which motorcycles can the voucher be redeemed for?',
                        'a' => 'For <strong>touring, sports, enduro and kids motorcycles</strong> in the Motogo24 range – depending on the chosen voucher value.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Gift voucher for motorcycle rental – Vysočina',
                'text' => 'Motogo24 is a <strong>motorcycle rental in Vysočina</strong> with <strong>24/7 service</strong>, <strong>without deposit</strong> and <strong>gear included</strong>. A gift voucher is the perfect way to give a <em>motorbike rental</em> experience – from <strong>touring</strong> through <strong>sports</strong> to <strong>enduro</strong> and <strong>kids motorcycles</strong>.',
                'buttons' => [
                    [
                        'label' => 'ORDER A VOUCHER',
                        'href' => '/koupit-darkovy-poukaz',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_cena' => [
            'seo' => [
                'title' => 'Motorcycle rental Vysočina – How to rent – What is included',
                'description' => 'Find out what is included in the motorcycle rental price at MotoGo24. The rental offers clear conditions, gear and services without hidden fees. Book your motorcycle online easily.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'What is included in the motorcycle rental price',
            'intro' => 'At <strong>MotoGo24 – motorcycle rental in Vysočina</strong> you get fair conditions. <strong>Without deposit, with rider gear included and 24/7 service</strong>. Everything you need for a safe and pleasant ride is part of the rental.',
            'gear' => [
                'basic' => [
                    'title' => 'Basic gear included',
                    'lead' => 'Every rider has a complete set of <strong>motorcycle gear</strong> included in the rental price:',
                    'items' => [
                        '<strong>helmet</strong>',
                        '<strong>motorcycle jacket</strong> with protectors',
                        '<strong>motorcycle trousers</strong>',
                        '<strong>gloves</strong>',
                    ],
                    'note1' => 'The gear is available in several sizes and we clean and check it regularly.',
                    'note2' => 'Selected motorcycles are fitted with top cases – see the motorcycle detail in the catalogue.',
                ],
                'extra' => [
                    'title' => 'Extra gear for a surcharge',
                    'lead' => 'Riding with a passenger or want motorcycle boots? You can add them when booking:',
                    'items' => [
                        'passenger gear (helmet, jacket, trousers, gloves)',
                        'motorcycle boots – for the rider and the passenger',
                    ],
                ],
                'services' => [
                    'title' => 'Extra services for a surcharge',
                    'items' => [
                        'delivery of the motorcycle to an agreed place anywhere in the Czech Republic',
                        'returning the motorcycle somewhere other than the rental address',
                    ],
                ],
            ],
            'benefits' => [
                'title' => 'Other benefits included',
                'grid' => 'gr5',
                'items' => [
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Online booking',
                        'text' => 'quick and easy booking from the comfort of home.',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => '24/7 service',
                        'text' => 'book and set off any time – day, night or weekend. You choose the pickup time when booking.',
                    ],
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'No deposit',
                        'text' => 'no deposit when renting.',
                    ],
                    [
                        'icon' => 'gfx/jasne-podminky.svg',
                        'title' => 'Clear conditions',
                        'text' => 'no hidden fees.',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'Discount on your next booking',
                        'text' => 'after every completed rental you get a discount code for your next booking.&nbsp;',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Gear included – motorcycle rental MotoGo24 – Vysočina',
                'text' => '<strong>MotoGo24 is a modern motorcycle rental in Vysočina</strong> with rider gear included, no-deposit rental and 24/7 service. Choose a <strong>touring, supermoto, naked or kids\' motorcycle</strong> and book online. Everything is clear and without hidden fees.',
                'buttons' => [
                    [
                        'label' => 'BOOK ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                        'aria' => 'Book a motorcycle with gear included at the Motogo24 rental',
                    ],
                ],
            ],
        ],
        'jak_pujcit_dokumenty' => [
            'seo' => [
                'title' => 'Motorcycle rental Vysočina – How to rent – Documents and manuals',
                'description' => 'Rental agreement, terms and necessary documents for renting a motorcycle. Without deposit, clear rules, insurance included.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Rental agreement and deposit – fair conditions without an advance',
            'intro' => 'At <strong>MotoGo24</strong> we focus on simplicity and fairness. We rent <strong>without deposit</strong>, with a <strong>clear rental agreement</strong>, <strong>insurance included</strong> and <strong>rider gear</strong>.',
            'top_cta' => [
                'label' => 'BOOK ONLINE',
                'href' => '/rezervace',
                'aria' => 'Book a motorcycle online at Motogo24',
            ],
            'summary' => [
                'title' => 'Summary of the main points',
                'items' => [
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'No deposit / advance',
                        'text' => 'we rent the motorcycle without blocking any money',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Online booking',
                        'text' => 'including payment',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Rider gear',
                        'text' => 'included (helmet, jacket, trousers, gloves)',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => '24/7 service',
                        'text' => 'pickup and return any time on the rental day',
                    ],
                    [
                        'icon' => 'gfx/jasne-podminky.svg',
                        'title' => 'Clear usage rules',
                        'text' => 'at home and abroad (per the green card)',
                    ],
                    [
                        'icon' => 'gfx/zadne-skryte-poplatky.svg',
                        'title' => 'No hidden fees',
                        'text' => 'everything is stated below and in the contract',
                    ],
                ],
            ],
            'required_docs' => [
                'title' => 'What you need to sign the contract',
                'items' => [
                    '<strong>ID card / passport</strong>',
                    '<strong>Driving licence</strong>&nbsp;of the appropriate category (A / A2 depending on the machine)',
                    '<strong>Age</strong>&nbsp;min. 18 (for kids\' motorcycles a legal guardian is liable)',
                    '<strong>Contacts</strong>&nbsp;(phone, e-mail) for communication and booking confirmation',
                ],
            ],
            'payments' => [
                'title' => 'Payments, cancellation and fees',
                'lead' => '<strong>Deposit:</strong>&nbsp;<em>not required</em>. The rental payment is made online or on pickup.',
                'aria' => 'Overview of payments and fees',
                'headers' => [
                    'Item',
                    'Conditions',
                ],
                'rows' => [
                    [
                        '<strong>Rental payment</strong>',
                        'Online in advance.',
                    ],
                    [
                        '<strong>Booking cancellation</strong>',
                        'Free of charge until an agreed time (stated in the booking confirmation). Later by individual agreement.',
                    ],
                    [
                        '<strong>Fuel &amp; cleaning</strong>',
                        'Return with no obligation to refuel or wash. Excessive dirt is handled individually.',
                    ],
                    [
                        '<strong>Delivery / collection</strong>',
                        'According to the delivery price list (Vysočina / surroundings). Confirmed at booking.',
                    ],
                    [
                        '<strong>Late return</strong>',
                        'Please return on time on the last rental day; for delays we charge as agreed (with regard to other bookings).',
                    ],
                ],
                'mid_cta' => [
                    'label' => 'CONTINUE TO BOOKING',
                    'href' => '/rezervace',
                    'aria' => 'Book a motorcycle and agree to the Motogo24 rental contract',
                ],
            ],
            'usage' => [
                'title' => 'Using the motorcycle and liability',
                'items' => [
                    'Ride in&nbsp;<strong>compliance with the rules</strong>&nbsp;and with regard to the technical condition and type of the motorcycle.',
                    'The renter is liable for&nbsp;<strong>fines and offences</strong>&nbsp;(we pass on information as required by law).',
                    '<strong>Abroad</strong>: possible; follow the territorial validity of the insurance (green card). Some countries may be excluded.',
                    'In the event of an&nbsp;<strong>accident or breakdown</strong>&nbsp;follow the instructions in the on-board kit (accident form, Motogo24 contact).',
                    '<strong>Service and maintenance</strong>&nbsp;is handled by us; report faults immediately.',
                    '<strong>Modifications to the motorcycle</strong>&nbsp;are not allowed without consent.',
                ],
            ],
            'handover' => [
                'title' => 'Handover and return',
                'items' => [
                    '<strong>Pickup</strong>&nbsp;takes place in Pelhřimov (Mezná 9) or use&nbsp;<a href="/jak-pujcit/pristaveni">delivery</a>.',
                    'At handover you receive&nbsp;<strong>keys, gear and documents</strong>&nbsp;(vehicle registration, green card, accident form).',
                    '<strong>Return</strong>&nbsp;any time during the last rental day (even at midnight). No washing or refuelling needed.',
                ],
            ],
            'privacy' => [
                'title' => 'Personal data and security',
                'text' => 'We process personal data only for the purpose of concluding and fulfilling the rental contract (identification, communication, invoicing). Details are in the <a href="/cms/zasady-ochrany-osobnich-udaju">personal data processing policy</a>.',
            ],
            'documents' => [
                'title' => 'Documents to download',
                'items' => [
                    [
                        'name' => 'Rental contract',
                        'href' => '/cms/smlouva-o-pronajmu',
                        'size' => '87.4kB',
                    ],
                    [
                        'name' => 'Handover protocol',
                        'href' => '/cms/predavaci-protokol',
                        'size' => '47.6kB',
                    ],
                    [
                        'name' => 'Terms and conditions',
                        'href' => '/cms/obchodni-podminky',
                        'size' => '87.7kB',
                    ],
                    [
                        'name' => 'Privacy policy',
                        'href' => '/cms/zasady-ochrany-osobnich-udaju',
                        'size' => '76.3kB',
                    ],
                ],
            ],
            'midcta' => [
                'title' => 'Agree to the conditions? Book and ride.',
                'text' => 'Choose from&nbsp;<strong>touring, sport, enduro and kids\' motorcycles</strong>&nbsp;and confirm your booking online.',
            ],
            'cta' => [
                'title' => 'Rental agreement without deposit – motorcycle rental Vysočina',
                'text' => 'MotoGo24 is a <strong>motorcycle rental in Vysočina</strong> with fair conditions.',
                'buttons' => [
                    [
                        'label' => 'BOOK ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_pristaveni' => [
            'seo' => [
                'title' => 'Motorcycle delivery | MotoGo24',
                'description' => 'Motorcycle delivery to your door. We bring the motorcycle to your hotel, train station or any address. Delivery price list from 290 Kč. 24/7 service.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Motorcycle delivery – brought right to you',
            'intro' => 'Want to ride without the hassle of getting to the rental? We arrange <strong>motorcycle delivery</strong> to a <strong>place of your choice</strong>.',
            'top_cta' => [
                'label' => 'BOOK WITH DELIVERY',
                'href' => '/rezervace?delivery=1',
            ],
            'when' => [
                'title' => 'When delivery comes in handy',
                'items' => [
                    '<strong>Start of a&nbsp;road trip</strong>&nbsp;– we bring the motorcycle straight to the start of your trip.',
                    '<strong>Hotel or guesthouse</strong>&nbsp;– delivery to your accommodation to save you time.',
                    '<strong>Train/bus station</strong>&nbsp;– a smooth transfer with no waiting.',
                    '<strong>Company events and gifts</strong>&nbsp;– a surprise for partners or your team.',
                ],
            ],
            'why' => [
                'title' => 'Why use motorcycle delivery',
                'grid' => 'gr5',
                'items' => [
                    [
                        'icon' => 'gfx/vyzvednuti-vraceni-motorky.svg',
                        'title' => 'Flexibility',
                        'text' => 'We bring the motorcycle wherever you need – home, to a hotel, to a station or to the start of your trip.',
                    ],
                    [
                        'icon' => 'gfx/ico-pohodli.svg',
                        'title' => 'Convenience',
                        'text' => 'You don\'t have to arrange transport to the rental – where to leave your car or who will drive you.',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => '24/7 service',
                        'text' => 'We arrange delivery for an agreed time – evenings or weekends are fine. Just pick the time when booking.',
                    ],
                    [
                        'icon' => 'gfx/uspora-casu.svg',
                        'title' => 'Time saved',
                        'text' => 'The time saved travelling to the rental and back you can spend on yourself.',
                    ],
                    [
                        'icon' => 'gfx/ico-vybava.svg',
                        'title' => 'Gear delivered too',
                        'text' => 'We also bring the rented gear in the requested sizes straight to you.',
                    ],
                ],
            ],
            'process' => [
                'title' => 'How delivery works',
                'grid' => 'gr5',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => 'Choose a motorcycle',
                        'text' => 'Browse our range of touring, supermoto, naked and kids\' motorcycles and pick the right one.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Pick a date',
                        'text' => 'Choose the date you want to ride in the calendar. You\'ll see which motorcycles are available.',
                    ],
                    [
                        'icon' => 'gfx/kontaktni-udaje.svg',
                        'title' => 'Contact details',
                        'text' => 'Fill in your name, address, e-mail and phone.',
                    ],
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Delivery time',
                        'text' => 'Choose when we deliver the motorcycle – evenings or weekends are fine.',
                    ],
                    [
                        'icon' => 'gfx/vyzvednuti-vraceni-motorky.svg',
                        'title' => 'Delivery location',
                        'text' => 'Enter the address to deliver to – home, a hotel, a station or the start of your trip.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Gear',
                        'text' => 'Basic rider gear is included. Enter the required sizes for all gear items in the Note field – mandatory.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => 'Confirmation and payment',
                        'text' => 'Check the order summary, agree to the conditions and pay online.',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'Handover on site',
                        'text' => 'At handover we check the documents, complete the contract and sign the handover protocol.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => 'Enjoy the ride',
                        'text' => 'Hit the road – no deposit, no stress. The rest is just asphalt and freedom.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Return the motorcycle',
                        'text' => 'Return the motorcycle on time at the agreed place. No refuelling or washing needed.',
                    ],
                ],
            ],
            'pricing' => [
                'title' => 'Delivery price list',
                'lead' => '<strong>The delivery price has three components:</strong>',
                'items' => [
                    '<strong>500 CZK</strong>&nbsp;for loading the motorcycle,',
                    '<strong>500 CZK</strong>&nbsp;for unloading the motorcycle,',
                    '<strong>20 CZK</strong>&nbsp;per kilometre (the distance from the rental to the destination and back is counted)',
                ],
                'example' => '<strong>Example:</strong>&nbsp;Want the motorcycle delivered 30 km from the rental? You pay 500 + 500 + (30 × 2 × 20) =&nbsp;<strong>2,200 CZK.</strong>',
            ],
            'faq' => [
                'title' => 'Frequently asked questions about delivery',
                'items' => [
                    [
                        'q' => 'How far in advance should I order delivery?',
                        'a' => 'Ideally <strong>when</strong> <strong>booking online</strong> – you enter the address and time. For urgent requests, contact us by phone.',
                    ],
                    [
                        'q' => 'Can I return the motorcycle somewhere other than where I picked it up?',
                        'a' => 'Yes, we charge <strong>collection</strong> based on the distance from Pelhřimov. We arrange it at booking.',
                    ],
                    [
                        'q' => 'How much does delivery outside Vysočina cost?',
                        'a' => 'We follow a distance table. Over 100 km we calculate the price <strong>individually</strong>.',
                    ],
                    [
                        'q' => 'Is there a deposit?',
                        'a' => 'No. <strong>We rent without a deposit</strong>, the conditions are clear and fair.',
                    ],
                    [
                        'q' => 'Is the rider gear included too?',
                        'a' => 'Yes. Helmet, jacket, trousers and gloves are&nbsp;<strong>included in the rental</strong>&nbsp;for the rider.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Motorcycle delivery – motorcycle rental Vysočina',
                'text' => 'MotoGo24 offers <strong>motorcycle delivery</strong> across the region and beyond. <strong>24/7 service, no deposit, gear included.</strong>',
                'buttons' => [
                    [
                        'label' => 'BOOK WITH DELIVERY',
                        'href' => '/rezervace?delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_jinde' => [
            'seo' => [
                'title' => 'Return motorcycle elsewhere – pickup service | MotoGo24',
                'description' => 'Return your motorcycle off the rental site – from a hotel, train station or any address. Pickup throughout Vysočina and beyond. Price by distance, 24/7 service.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Return motorcycle elsewhere – pickup brought to you',
            'intro' => 'You don\'t have to return to the rental. <strong>MotoGo24</strong> offers <strong>motorcycle pickup</strong> from a place that suits you – hotel, train station or your own address.',
            'top_cta' => [
                'label' => 'BOOK WITH PICKUP',
                'href' => '/rezervace?return_delivery=1',
            ],
            'when' => [
                'title' => 'When return elsewhere comes in handy',
                'items' => [
                    '<strong>End of a road trip</strong>&nbsp;– the rental started in Pelhřimov, the trip ends elsewhere. Hand the motorcycle over to us where your trip ends.',
                    '<strong>One-way trip</strong>&nbsp;– travelling back home by train or bus? Hand the motorcycle over to us before you leave.',
                    '<strong>Hotel or guesthouse</strong>&nbsp;– hand the motorcycle over to us right at your accommodation, so you don\'t have to figure out the way back to the rental.',
                    '<strong>Company event</strong>&nbsp;– a rental for a group with the return right at the event location.',
                ],
            ],
            'why' => [
                'title' => 'Why use return elsewhere',
                'grid' => 'gr5',
                'items' => [
                    [
                        'icon' => 'gfx/vyzvednuti-vraceni-motorky.svg',
                        'title' => 'Flexibility',
                        'text' => 'You choose the return location to match your route – a hotel, a station, a car park or anywhere else.',
                    ],
                    [
                        'icon' => 'gfx/uspora-casu.svg',
                        'title' => 'Time saved',
                        'text' => 'You save the trip back to the rental and home – you hand the motorcycle over where you are.',
                    ],
                    [
                        'icon' => 'gfx/ico-pohodli.svg',
                        'title' => 'Convenience',
                        'text' => 'You don\'t have to figure out how to get home from the rental.&nbsp;',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => '24/7 service',
                        'text' => 'We arrange the return for an agreed time – evenings or weekends are fine.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Simplicity',
                        'text' => 'You hand over the keys and gear, we check the motorcycle and leave. No extra paperwork.',
                    ],
                ],
            ],
            'process' => [
                'title' => 'How return elsewhere works',
                'grid' => 'gr5',
                'steps' => [
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => 'Choose the return place and time',
                        'text' => 'In the booking form, enter the address and time when you\'ll hand the motorcycle over.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Get the gear ready',
                        'text' => 'Before the handover, prepare the gear that was part of the rental.',
                    ],
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'We arrive at the agreed time',
                        'text' => 'We\'ll arrive at the agreed place exactly at the agreed time.',
                    ],
                    [
                        'icon' => 'gfx/prevezmi-motorku.svg',
                        'title' => 'We check the motorcycle and gear together',
                        'text' => 'We check the condition of the motorcycle and gear, load up and leave.&nbsp;',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'You\'ll get a confirmation by e-mail',
                        'text' => 'A rental completion confirmation, the final invoice and a discount code for your next booking.',
                    ],
                ],
            ],
            'pricing' => [
                'title' => 'Return-elsewhere price list',
                'lead' => 'The price has three components:',
                'items' => [
                    '500 CZK for loading the motorcycle',
                    '500 CZK for unloading the motorcycle',
                    '20 CZK per kilometre (the distance from the return location to the rental and back)',
                ],
                'example_title' => 'Example:',
                'example_q' => 'Want to return the motorcycle 30 km from the rental?',
                'example_a' => 'You pay 500 + 500 + (30 × 2 × 20) = 2,200 CZK.',
            ],
            'issues' => [
                'title' => 'Discrepancies on return',
                'lead' => 'On return we check the condition of the motorcycle and gear together. If any of the situations below occurs, we draw up a report of the damage found:',
                'items' => [
                    'missing gear',
                    'damaged gear',
                    'damaged motorcycle',
                ],
                'closing' => 'The customer signs the report and receives a copy of it. The further procedure is governed by the terms of the rental contract and the terms and conditions.',
            ],
            'faq' => [
                'title' => 'Frequently asked questions about returning the motorcycle elsewhere',
                'items' => [
                    [
                        'q' => 'By when do I have to return the motorcycle?',
                        'a' => 'Return the motorcycle ideally at the agreed time. If you return at the rental, you can come by arrangement any time during the last rental day – no later than midnight, with no penalties. If you return at another location, the agreed time is binding.',
                    ],
                    [
                        'q' => 'Do I have to return it with a full tank and clean?',
                        'a' => 'No. You don\'t refuel or wash with us. Just make sure the reserve light isn\'t on.&nbsp;',
                    ],
                    [
                        'q' => 'When returning at another location, can I return the motorcycle earlier than we agreed?&nbsp;',
                        'a' => 'We set off from Pelhřimov to the agreed place exactly according to the agreed time, so an earlier return is unfortunately not possible. If your plans change, get in touch – we\'ll try to adjust the time, but it depends on our current workload.',
                    ],
                    [
                        'q' => 'Can I really return the motorcycle anywhere in the Czech Republic?&nbsp;',
                        'a' => 'Yes, we\'ll come to collect the motorcycle anywhere in the Czech Republic. You enter the return location when booking – it can be a hotel, a car park, a station or any other address.',
                    ],
                    [
                        'q' => 'How far in advance do I have to report a return at another location?&nbsp;',
                        'a' => 'You enter the return location and time already in the booking form.&nbsp;',
                    ],
                    [
                        'q' => 'What if I\'m late to the return location?&nbsp;',
                        'a' => 'Call us as soon as you know you won\'t make it on time. We\'ll work it out – we usually wait for you. We just need to know how big a delay to expect so we can adjust our day\'s plan.',
                    ],
                    [
                        'q' => 'How is the price for a return at another location calculated?&nbsp;',
                        'a' => 'The price includes 500 CZK for loading, 500 CZK for unloading and 20 CZK per kilometre of the distance from the return location to the rental (and back). For example, when returning 50 km from Pelhřimov you pay 500 + 500 + (50 × 2 × 20) = 3,000 CZK.',
                    ],
                    [
                        'q' => 'Do I pay for the return elsewhere separately, or is it part of the rental price?&nbsp;',
                        'a' => 'Return at another location is an additional service and is paid for separately, on top of the rental price.&nbsp;',
                    ],
                    [
                        'q' => 'What if I want to pick up the motorcycle in Pelhřimov but return it elsewhere – is that possible?&nbsp;',
                        'a' => 'Yes, you can pick up the motorcycle at our place in Pelhřimov and return it where you need.&nbsp;',
                    ],
                    [
                        'q' => 'What should I have ready when you come for the motorcycle?&nbsp;',
                        'a' => 'Have the keys and all the gear that was part of the rental ready. We check the condition of the motorcycle and gear together.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Return motorcycle anywhere – MotoGo24',
                'text' => 'MotoGo24 arranges <strong>motorcycle pickup</strong> from a place that suits you. <strong>24/7, no deposit, no hassle.</strong>',
                'buttons' => [
                    [
                        'label' => 'BOOK WITH PICKUP',
                        'href' => '/rezervace?return_delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'faq' => [
            'seo' => [
                'title' => 'Frequently asked questions | MotoGo24',
                'description' => 'Frequently asked questions about renting a motorcycle. Booking, pickup, return, conditions, delivery, travelling abroad, gift vouchers.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'h1' => 'Frequently asked questions – motorcycle rental MotoGo24',
            'closing' => 'Our <strong>motorcycle rental in Vysočina</strong> is here for everyone who wants an <strong>unforgettable ride</strong> without unnecessary complications.',
            'cta' => [
                'label' => 'Book a motorcycle online',
                'href' => '/rezervace',
            ],
        ],
        'home' => [
            'seo' => [
                'title' => 'Motorcycle rental in Vysočina | MotoGo24',
                'description' => 'Rent a motorcycle in Vysočina. Without deposit, gear included, 24/7 service. Touring, sport, enduro and kids\' motorcycles. Online booking.',
                'keywords' => 'motorcycle rental Czech Republic',
                'og_image' => NULL,
            ],
            'hero' => [
                'image' => 'gfx/hero-banner.jpg',
                'alt' => 'Motorcycle rental Vysočina',
                'eyebrow' => '<strong>Motorcycle rental</strong> in Vysočina',
                'body' => 'Rent a motorcycle in Vysočina easily online.<br>Choose from touring, sport and enduro models.<br>Booking with card payment and quick pickup.',
                'cta_primary' => [
                    'label' => 'CHOOSE A MOTORCYCLE',
                    'href' => '/katalog',
                    'cls' => 'btngreen',
                ],
                'cta_secondary' => [
                    'label' => 'RESERVATION',
                    'href' => '/rezervace',
                    'cls' => 'btndark',
                ],
            ],
            'h1' => 'Motorcycle rental Vysočina Motogo24 – without deposit and 24/7',
            'intro' => 'Welcome to <strong>Motogo24</strong> – your motorcycle rental in Vysočina. With us you rent a motorcycle <strong>without deposit</strong>, with gear included and in <strong>24/7</strong> mode. Whether you\'re looking for a touring, sport, enduro or kids\' motorcycle, Motogo24 in the heart of Vysočina has the right one for you.',
            'signposts_title' => 'Quick guide around Motogo24',
            'signposts' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => 'Motorcycle catalog',
                    'text' => 'Browse our offer of motorcycles for rent — from sport to touring models.',
                    'btn' => 'MOTORCYCLE CATALOG',
                    'href' => '/katalog',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => 'How to rent a motorcycle',
                    'text' => 'A simple process: choose a motorcycle to rent, book and ride.',
                    'btn' => 'HOW TO RENT',
                    'href' => '/jak-pujcit',
                ],
                [
                    'icon' => 'gfx/rezervace-online.svg',
                    'title' => 'Online motorcycle booking',
                    'text' => 'Book a motorcycle for rent through our easy online system.',
                    'btn' => 'BOOK A MOTORCYCLE',
                    'href' => '/rezervace',
                ],
                [
                    'icon' => 'gfx/kontakt.svg',
                    'title' => 'Contacts and map',
                    'text' => 'Visit our motorcycle rental in Pelhřimov or contact us.',
                    'btn' => 'CONTACT',
                    'href' => '/kontakt',
                ],
                [
                    'icon' => 'gfx/faq.svg',
                    'title' => 'Frequently asked questions',
                    'text' => 'The most common questions about renting a motorcycle in one place.',
                    'btn' => 'FAQ',
                    'href' => '/jak-pujcit/faq',
                ],
                [
                    'icon' => 'gfx/uzij-si-jizdu.svg',
                    'title' => 'Motorcycle trips',
                    'text' => 'Discover the best motorcycle routes in the Czech Republic for tourists and locals.',
                    'btn' => 'MOTORCYCLE ROUTES',
                    'href' => '/blog',
                ],
            ],
            'motos_section' => [
                'title' => 'Our motorcycles for rent in Vysočina',
                'intro' => 'Browse our offer of touring, sport and enduro from our motorcycle rental in Vysočina.',
                'empty' => 'We currently have no motorcycles available.',
                'cta_label' => 'MOTORCYCLE CATALOG',
                'cta_href' => '/katalog',
                'limit' => 4,
            ],
            'process' => [
                'title' => 'How motorcycle rental works in Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Choose',
                        'text' => 'Pick your ideal motorcycle from our offer of motorcycles for rent.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Book',
                        'text' => 'Book your motorcycle rental through our simple online system.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '3. Pick up',
                        'text' => 'Pick up the motorcycle at our rental in Pelhřimov.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '4. Enjoy the ride',
                        'text' => 'Embrace the freedom and discover the Czech Republic on rental motorcycles.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Frequently asked questions',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => 'How can I book a motorcycle?',
                        'a' => 'You can book a motorcycle through our online booking system right here on the website. Or contact us by e-mail, phone or via social media.',
                    ],
                    [
                        'q' => 'Can I rent a motorcycle without booking in advance?',
                        'a' => 'Unfortunately not. Every motorcycle has to be booked in advance — online, by phone, e-mail or via social media.',
                    ],
                    [
                        'q' => 'Do I have to pay a deposit?',
                        'a' => 'No! With us you <strong>do not pay any deposit</strong>. Our rental is fundamentally different from most of the competition in this respect.',
                    ],
                    [
                        'q' => 'Can I take the motorcycle abroad?',
                        'a' => 'Yes, you can travel abroad with the motorcycle without any problem. We don\'t restrict trips outside the Czech Republic; you only need to comply with the territorial validity of your insurance (green card).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Book your motorcycle online',
                'text' => 'Our <strong>motorcycle rental Vysočina</strong> is open <strong>24/7</strong>. A few clicks and your ride begins.',
                'buttons' => [
                    [
                        'label' => 'BOOK A MOTORCYCLE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Gift voucher',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Route tips',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
            'blog' => [
                'title' => 'Blog and tips',
                'empty' => 'No articles yet.',
                'cta_label' => 'READ MORE ON THE BLOG',
                'cta_href' => '/blog',
                'limit' => 3,
            ],
            'reviews' => [
                'title' => 'What our customers say',
                'intro' => 'Real reviews from riders who rented with us. Thank you for every rating.',
            ],
        ],
        'pujcovna' => [
            'seo' => [
                'title' => 'About the motorcycle rental | MotoGo24',
                'description' => 'Motogo24 motorcycle rental in Vysočina. Without deposit, with online booking and gear included. Touring, sport, enduro and kids\' motorcycles. 24/7 service.',
                'keywords' => 'motorcycle rental Czech Republic',
            ],
            'breadcrumb' => [
                [
                    'label' => 'Home',
                    'href' => '/',
                ],
                'Motorcycle rental',
            ],
            'intro' => [
                'h1' => 'Motorcycle rental Vysočina Motogo24',
                'body' => 'Our <strong>motorcycle rental in Vysočina</strong> in Pelhřimov offers <strong>motorcycle rentals</strong> without unnecessary obstacles – <strong>without deposit</strong>, with <strong>online booking</strong> and <strong>gear included</strong>. Choose from <strong>touring</strong>, <strong>sport</strong>, <strong>enduro</strong> and <strong>kids\' motorcycles</strong>, and head off any time: we\'re open <strong>24/7</strong>.',
            ],
            'benefits' => [
                'title' => 'Why rent a motorcycle with us',
                'closing' => 'Looking for a <strong>motorcycle rental in Vysočina</strong>? Motogo24 – <strong>motorcycle rental in Vysočina</strong> – offers fair conditions, a clear procedure and top-maintained machines for trips around the Czech Republic and abroad.',
                'buttons' => [
                    [
                        'label' => 'See motorcycles for rent',
                        'href' => '/katalog',
                        'cls' => 'btngreen',
                    ],
                    [
                        'label' => 'BOOK NOW',
                        'href' => '/rezervace',
                        'cls' => 'btngreen pulse',
                    ],
                ],
                'items' => [
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'No deposit',
                        'text' => 'and no hidden fees',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Online booking',
                        'text' => 'in just a few clicks',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Rider gear included',
                        'text' => 'helmet, jacket, trousers and gloves',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => '24/7 service',
                        'text' => 'for pickup and return per your booking',
                    ],
                    [
                        'icon' => 'gfx/ico-spolecne.svg',
                        'title' => 'We\'re in it together',
                        'text' => 'if anything happens',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Motorcycle delivery & pickup',
                        'text' => 'to an agreed place',
                    ],
                ],
            ],
            'process' => [
                'title' => 'How motorcycle rental works in Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Pick a motorcycle',
                        'text' => 'Browse our offer and choose the type that suits you, your experience and your licence.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Book online',
                        'text' => 'Reserve by date or by a specific motorcycle you want to rent.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => '3. Choose gear',
                        'text' => 'Rider gear is included; passenger gear costs extra. You can choose the size on site.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => '4. Pay',
                        'text' => 'Pay easily online through the payment gateway.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '5. Pick up the motorcycle',
                        'text' => 'Pick up the motorcycle directly at the rental, or at the place you selected when booking.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '6. Enjoy the ride',
                        'text' => 'Hit the road, discover new experiences and enjoy the full freedom of two wheels.',
                    ],
                    [
                        'icon' => 'gfx/vrat-motorku-vcas.svg',
                        'title' => '7. Return the motorcycle',
                        'text' => 'Simply return the motorcycle on the agreed day – at the rental, or at the agreed place.',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'Discount for your next ride',
                        'text' => 'After returning the motorcycle, we\'ll automatically send you a 200 Kč discount code for your next booking.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Frequently asked questions',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => 'How can I book a motorcycle?',
                        'a' => 'You can book a motorcycle through our online booking system right here on the website. Or contact us by e-mail, phone or via social media.',
                    ],
                    [
                        'q' => 'Can I rent a motorcycle without booking in advance?',
                        'a' => 'Unfortunately not. Every motorcycle has to be booked in advance.',
                    ],
                    [
                        'q' => 'Do I have to pay a deposit?',
                        'a' => 'No! With us you <strong>do not pay any deposit</strong>. Our rental is fundamentally different from most of the competition in this respect.',
                    ],
                    [
                        'q' => 'Can I take the motorcycle abroad?',
                        'a' => 'Yes, you can travel abroad with the motorcycle without any problem. We don\'t restrict trips outside the Czech Republic; you only need to comply with the territorial validity of your insurance (green card).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Book your motorcycle online',
                'text' => 'Our <strong>motorcycle rental Vysočina</strong> is open <strong>24/7</strong>. A few clicks and your ride begins.',
                'buttons' => [
                    [
                        'label' => 'BOOK A MOTORCYCLE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Gift voucher',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Route tips',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
        ],
    ],
];
