<?php
// MotoGo24 — pages_fr.php (auto-generated by merge_pages.php; parts: 1)

return [
    'pages' => [
        'kontakt' => [
            'seo' => [
                'title' => 'Contact | MotoGo24 – Location de motos Vysočina',
                'description' => 'Contacts pour la location de motos Motogo24 à Pelhřimov. Téléphone +420 774 256 271, e-mail info@motogo24.cz. Service 24h/24, adresse Mezná 9, 393 01 Pelhřimov.',
                'keywords' => 'contact Motogo24, location de motos Pelhřimov, téléphone, adresse, horaires, 24h/24',
            ],
            'h1' => 'Contacts location de motos Motogo24',
            'intro' => 'Tu as une question sur la <strong>location d\'une moto</strong>, tu veux commander un <strong>bon cadeau</strong>, être conseillé dans ton choix ou directement <strong>convenir d\'une réservation</strong> ? Nous sommes là pour toi tous les jours, <strong>24h/24</strong>.',
            'quick' => [
                [
                    'label' => 'APPELLE-NOUS',
                    'value' => '+420 774 256 271',
                    'href' => 'tel:+420774256271',
                    'icon' => 'gfx/telefon.svg',
                    'alt' => 'Téléphone',
                ],
                [
                    'label' => 'ÉCRIS-NOUS',
                    'value' => 'info@motogo24.cz',
                    'href' => 'mailto:info@motogo24.cz',
                    'icon' => 'gfx/email.svg',
                    'alt' => 'E-mail',
                ],
                [
                    'label' => 'BOÎTE DE DONNÉES',
                    'value' => 'iuw3vnb',
                    'href' => NULL,
                    'icon' => NULL,
                    'alt' => NULL,
                ],
            ],
            'place' => [
                'title' => 'Établissement',
                'address_label' => 'Adresse :',
                'address' => 'Mezná 9, 393 01 Pelhřimov',
                'hours_label' => 'Horaires d\'ouverture :',
                'hours' => 'LUN – DIM : 00:00 – 24:00 (24h/24)<br>Y compris week-ends et jours fériés',
                'billing_title' => 'Coordonnées de facturation',
                'billing_name' => 'Bc. Petra Semorádová',
                'billing_address' => 'Mezná 9, 393 01 Pelhřimov',
                'billing_ico' => '21874263',
                'billing_vat' => 'Non assujettie à la TVA',
                'billing_note' => 'La société a été enregistrée le 31. 7. 2024 auprès de la mairie de Pelhřimov.',
            ],
            'social_title' => 'Suis-nous',
            'social' => [
                [
                    'label' => 'facebook',
                    'href' => '#',
                    'icon' => 'gfx/facebook.svg',
                    'alt' => 'Facebook',
                ],
                [
                    'label' => 'instagram',
                    'href' => '#',
                    'icon' => 'gfx/instagram.svg',
                    'alt' => 'Instagram',
                ],
            ],
            'side_cta' => [
                'title' => 'Tu veux convenir d\'une réservation ?',
                'text' => 'Réserve ta moto en ligne en quelques minutes et pars à l\'aventure.',
                'button' => [
                    'label' => 'RÉSERVER EN LIGNE',
                    'href' => '/rezervace',
                    'cls' => 'btndark',
                ],
            ],
            'map' => [
                'title' => 'Où nous trouver',
                'src' => 'https://www.google.com/maps?q=Mezn%C3%A1+9%2C+393+01+Pelh%C5%99imov&hl=cs&z=15&output=embed',
            ],
            'seo_text' => [
                'title' => 'Contacts – Location de motos Vysočina (Pelhřimov)',
                'body' => 'Motogo24 est une <strong>location de motos moderne en Vysočina</strong>. Nous sommes basés à <strong>Pelhřimov</strong>, ouverts <strong>24h/24</strong> et nous louons <strong>sans caution</strong>, avec l\'<strong>équipement complet inclus dans le prix</strong>.',
            ],
        ],
        'jak_pujcit' => [
            'seo' => [
                'title' => 'Comment louer une moto | MotoGo24',
                'description' => 'Comment louer une moto chez Motogo24. Procédure simple : choix, réservation, prise en main. Sans caution, équipement inclus, service 24h/24.',
                'keywords' => 'comment louer une moto, processus de location, réservation moto, location de motos Vysočina',
            ],
            'h1' => 'Comment louer une moto',
            'intro' => 'Chez <strong>Motogo24 – location de motos en Vysočina</strong>, louer est simple, rapide et équitable.',
            'links' => [
                [
                    'href' => '/jak-pujcit/postup',
                    'label' => 'Processus de location',
                ],
                [
                    'href' => '/jak-pujcit/prevzeti',
                    'label' => 'Prise en main à la location',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-pujcovna',
                    'label' => 'Restitution de la moto à la location',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-jinde',
                    'label' => 'Restitution de la moto ailleurs',
                ],
                [
                    'href' => '/jak-pujcit/co-v-cene',
                    'label' => 'Ce qui est inclus dans le prix',
                ],
                [
                    'href' => '/jak-pujcit/pristaveni',
                    'label' => 'Livraison de la moto',
                ],
                [
                    'href' => '/jak-pujcit/dokumenty',
                    'label' => 'Documents et notices',
                ],
                [
                    'href' => '/jak-pujcit/faq',
                    'label' => 'Questions fréquentes',
                ],
            ],
        ],
        'jak_pujcit_postup' => [
            'seo' => [
                'title' => 'Processus de location | MotoGo24',
                'description' => 'Processus de location d\'une moto chez Motogo24 étape par étape. Réservation en ligne, équipement inclus, sans caution, service 24h/24 et possibilité de livraison.',
                'keywords' => 'processus de location moto, comment louer une moto, réservation moto, location de motos Pelhřimov',
            ],
            'h1' => 'Processus de location',
            'intro' => '<p>Chez <strong>Motogo24 – location de motos en Vysočina</strong>, louer est simple, rapide et équitable. <strong>Sans caution, avec équipement inclus et service 24h/24</strong>. Découvre comme c\'est facile.</p><p>&nbsp;</p><h2>Comment louer une moto – location Motogo24 Vysočina</h2><p>Chez la <strong>location de motos Motogo24</strong>, le <strong>processus de location</strong> est simple : <strong>réservation en ligne</strong>, <strong>équipement inclus</strong>, <strong>sans caution</strong>, <strong>service 24h/24</strong> et possibilité de <strong>livraison de moto</strong>. Que tu cherches une <strong>moto routière</strong> pour le week-end, une <strong>moto sportive</strong> pour l\'adrénaline ou une <strong>enduro</strong> pour le tout-terrain, tu trouveras chez nous la solution idéale.</p>',
            'process' => [
                'title' => 'Comment se déroule la location étape par étape',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Choisis ta moto',
                        'text' => 'Découvre notre offre de <strong>motos routières, sportives, enduro et pour enfants</strong> et choisis celle qu\'il te faut.',
                    ],
                    [
                        'icon' => 'gfx/kontaktni-udaje.svg',
                        'title' => '2. Nombre de pilotes',
                        'text' => 'Choisis si tu pars seul ou avec un passager. Nous te proposerons les machines et l\'équipement adaptés.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '3. Réservation en ligne',
                        'text' => 'Réserve simplement la moto selon la date. Effectue le paiement à l\'avance <strong>en ligne</strong>.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => '4. Équipement inclus',
                        'text' => 'En tant que pilote, tu reçois automatiquement casque, blouson, pantalon et gants. Tu choisis la taille lors de la réservation.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => '5. Confirmation et paiement',
                        'text' => 'La réservation est ferme après confirmation. Tu effectues le paiement en ligne.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '6. Prise en main de la moto',
                        'text' => 'Tu prends la moto en main personnellement à Pelhřimov ou tu profites de la <strong>livraison</strong> à un endroit convenu.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '7. Profite de la balade',
                        'text' => 'Pars sur la route – <strong>sans caution, sans stress</strong>, avec des conditions claires et l\'assurance incluse.',
                    ],
                    [
                        'icon' => 'gfx/vrat-motorku-vcas.svg',
                        'title' => '8. Restitution de la moto',
                        'text' => 'Tu rends la moto à n\'importe quel moment durant le dernier jour de location. Pas besoin de faire le plein ni de la laver.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Questions fréquentes',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => 'Une caution est-elle nécessaire pour la location ?',
                        'a' => 'Non. <strong>Nous louons sans caution</strong> – équitablement et sans obstacles inutiles.',
                    ],
                    [
                        'q' => 'L\'équipement est-il inclus dans le prix de la location ?',
                        'a' => 'Oui. Chaque pilote reçoit <strong>casque, blouson, pantalon et gants gratuitement</strong>.',
                    ],
                    [
                        'q' => 'Où puis-je prendre en main la moto ?',
                        'a' => 'La prise en main se fait à Pelhřimov, ou bien nous proposons la <strong>livraison de la moto</strong> à l\'endroit de ton choix.',
                    ],
                    [
                        'q' => 'Jusqu\'à quand dois-je rendre la moto ?',
                        'a' => 'Tu peux rendre la moto à n\'importe quel moment durant le dernier jour de location – même à minuit.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Prêt à rouler ?',
                'text' => 'Réserve ta moto en ligne dès aujourd\'hui et profite de la <strong>liberté sur deux roues</strong>.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER EN LIGNE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vyzvednuti' => [
            'seo' => [
                'title' => 'Prise en main de la moto à la location | MotoGo24',
                'description' => 'Prise en main de la moto à la location de Pelhřimov. Service 24h/24, sans caution, équipement inclus. Que prendre avec soi et comment se déroule la remise.',
                'keywords' => 'prise en main moto à la location, retrait de la moto, location Pelhřimov, prise en main 24h/24',
            ],
            'h1' => 'Prise en main de la moto à la location – rapide, simple et 24h/24',
            'intro' => 'Chez <strong>Motogo24 – location de motos Vysočina</strong>, la <strong>prise en main de la moto</strong> est l\'affaire de quelques minutes. Nous louons <strong>sans caution</strong>, avec <strong>équipement inclus</strong> et un <strong>service 24h/24</strong>.',
            'top_cta' => [
                'label' => 'RÉSERVER EN LIGNE',
                'href' => '/rezervace',
            ],
            'place' => [
                'title' => 'Où se déroule la prise en main',
                'address' => 'Mezná 9, 393 01 <strong>Pelhřimov</strong> (Vysočina)',
                'hours' => '<em>24h/24</em>',
                'phone' => '+420 774 256 271',
                'return_title' => 'Restitution de la moto – sans stress',
                'return_text' => 'Tu peux rendre la moto <strong>à n\'importe quel moment durant le dernier jour de location</strong>. Plus d\'informations dans <a href="/jak-pujcit/vraceni-pujcovna">restitution à la location</a> ou <a href="/jak-pujcit/vraceni-jinde">restitution ailleurs</a>.',
                'map_src' => 'https://frame.mapy.cz/s/?x=15.15413&y=49.35169&z=14&source=coor&id=15.15413%2C49.35169',
            ],
            'steps' => [
                'title' => 'Comment se déroule la prise en main étape par étape',
                'items' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Viens à l\'heure convenue',
                        'text' => 'à notre adresse ou attends la livraison',
                    ],
                    [
                        'icon' => 'gfx/overime-doklady.svg',
                        'title' => 'Nous vérifions les documents',
                        'text' => 'CI/passeport + permis de conduire de la catégorie correspondante',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Nous remettons la moto et l\'équipement',
                        'text' => 'casque, blouson, pantalon, gants',
                    ],
                    [
                        'icon' => 'gfx/prevezmi-motorku.svg',
                        'title' => 'Brève présentation de la machine',
                        'text' => 'commandes, conseils, recommandations d\'itinéraire',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'Nous signons le procès-verbal de remise',
                        'text' => 'et tu peux partir',
                    ],
                ],
            ],
            'bring' => [
                'title' => 'Que prendre avec soi',
                'items' => [
                    '<strong>Carte d\'identité / passeport</strong>',
                    '<strong>Permis de conduire</strong> de la catégorie correspondante (A/A2 selon la moto)',
                    '<strong>Chaussures adaptées</strong> (les bottes moto peuvent être louées en option)',
                ],
                'cta' => [
                    'label' => 'RÉSERVER UNE DATE',
                    'href' => '/rezervace',
                ],
            ],
            'faq' => [
                'title' => 'Questions fréquentes sur la prise en main',
                'items' => [
                    [
                        'q' => 'Dois-je payer une caution lors de la prise en main ?',
                        'a' => 'Non, <strong>nous louons sans caution</strong>. Les conditions sont clairement définies et équitables.',
                    ],
                    [
                        'q' => 'Un contact sans rencontre en personne est-il possible ?',
                        'a' => 'Oui, nous proposons une <strong>remise sans contact</strong> sur accord préalable.',
                    ],
                    [
                        'q' => 'Et si je n\'arrive pas à l\'heure convenue ?',
                        'a' => 'Préviens-nous par téléphone – nous adapterons l\'heure ou proposerons la <strong>livraison</strong>.',
                    ],
                    [
                        'q' => 'L\'équipement pour le passager est-il aussi inclus dans le prix ?',
                        'a' => 'L\'équipement pour le pilote est toujours inclus. L\'équipement pour le passager peut être commandé en option en <strong>supplément</strong>.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Prise en main de la moto à la location – Motogo24 Vysočina',
                'text' => 'Motogo24 est une <strong>location de motos en Vysočina</strong> avec <strong>prise en main et restitution 24h/24</strong>, <strong>sans caution</strong> et avec <strong>équipement inclus</strong>.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER EN LIGNE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_pujcovna' => [
            'seo' => [
                'title' => 'Restitution de la moto à la location | MotoGo24',
                'description' => 'Restitution de la moto directement à la location de Pelhřimov. 24h/24, sans caution, sans paperasse inutile. Comment se déroule la restitution étape par étape.',
                'keywords' => 'restitution moto, restitution de la moto à la location, location Pelhřimov, restitution moto 24h/24',
            ],
            'h1' => 'Restitution de la moto à la location',
            'intro' => 'Tu rends la moto confortablement directement chez <strong>Motogo24 – location de motos en Vysočina</strong>. <strong>Service 24h/24</strong>, sans stress et conditions équitables.',
            'top_cta' => [
                'label' => 'RÉSERVER EN LIGNE',
                'href' => '/rezervace',
            ],
            'place' => [
                'title' => 'Où et quand rendre la moto',
                'address' => 'Mezná 9, 393 01 <strong>Pelhřimov</strong> (Vysočina)',
                'hours' => '<em>24h/24</em> – à n\'importe quel moment durant le dernier jour de location',
                'phone' => '+420 774 256 271',
                'note_title' => 'Ce qu\'il faut respecter',
                'note_text' => 'Rends la moto <strong>à l\'heure convenue</strong> et dans un état technique similaire à celui dans lequel tu l\'as prise. <strong>Nous n\'exigeons ni le plein ni le lavage.</strong>',
                'map_src' => 'https://frame.mapy.cz/s/?x=15.15413&y=49.35169&z=14&source=coor&id=15.15413%2C49.35169',
            ],
            'steps' => [
                'title' => 'Comment se déroule la restitution à la location',
                'items' => [
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Viens à l\'heure convenue',
                        'text' => 'à l\'adresse de la location à Pelhřimov',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Nous vérifions ensemble l\'état de la moto',
                        'text' => 'contrôle de la carrosserie, du réservoir et de l\'équipement',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Tu rends l\'équipement',
                        'text' => 'casque, blouson, pantalon, gants',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'Nous signons le procès-verbal de restitution',
                        'text' => 'enregistrement clair et équitable',
                    ],
                    [
                        'icon' => 'gfx/potvrzeni-rezervace.svg',
                        'title' => 'Terminé',
                        'text' => 'nous t\'envoyons la confirmation par e-mail',
                    ],
                ],
            ],
            'tips' => [
                'title' => 'Conseils pratiques pour la restitution',
                'items' => [
                    '<strong>Nous n\'exigeons pas le plein</strong> – le carburant n\'est facturé qu\'en cas de besoin.',
                    '<strong>Le lavage de la moto n\'est pas nécessaire</strong> – la saleté courante de conduite est acceptable.',
                    '<strong>Restitution tardive</strong> à signaler à l\'avance par téléphone, afin que nous puissions trouver une solution.',
                    '<strong>Restitution sans contact</strong> possible sur accord préalable.',
                ],
                'cta' => [
                    'label' => 'RÉSERVER UNE DATE',
                    'href' => '/rezervace',
                ],
            ],
            'faq' => [
                'title' => 'Questions fréquentes sur la restitution à la location',
                'items' => [
                    [
                        'q' => 'Et si je n\'arrive pas à l\'heure convenue de restitution ?',
                        'a' => 'Préviens-nous par téléphone s\'il te plaît. Nous nous mettons généralement d\'accord sur un <strong>décalage de quelques heures</strong> ; un retard plus long peut être facturé selon le tarif.',
                    ],
                    [
                        'q' => 'Dois-je laver la moto ?',
                        'a' => 'Non. La saleté courante est acceptable, nous <strong>n\'exigeons pas</strong> le lavage.',
                    ],
                    [
                        'q' => 'Dois-je rendre la moto avec le plein ?',
                        'a' => 'Ce n\'est pas obligatoire. Si le réservoir n\'est pas plein, nous complétons le carburant et <strong>ne facturons que le prix réel</strong> sans majoration.',
                    ],
                    [
                        'q' => 'Et si la location est fermée ?',
                        'a' => 'Le service est <strong>24h/24</strong>. La nuit, il suffit d\'appeler le +420 774 256 271 et nous convenons de la remise.',
                    ],
                    [
                        'q' => 'Puis-je rendre la moto à un autre endroit ?',
                        'a' => 'Oui, profite de la <a href="/jak-pujcit/vraceni-jinde"><strong>restitution de la moto ailleurs</strong></a> (livraison/transport selon le tarif).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Restitution de la moto à la location – Motogo24 Pelhřimov',
                'text' => 'Rends la moto directement chez nous à Pelhřimov – <strong>24h/24, sans caution, sans stress</strong>.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER EN LIGNE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'poukazy' => [
            'seo' => [
                'title' => 'Location de motos Vysočina - Bons cadeaux',
                'description' => 'Achète un bon cadeau pour la location d\'une moto. Validité 3 ans, sans caution, équipement inclus. Bon électronique ou imprimé. Commande en ligne.',
                'keywords' => 'bon cadeau moto, voucher location moto, cadeau pour motard, bon Motogo24, location de motos Vysočina',
                'og_image' => 'https://motogo24.cz/gfx/darkovy-poukaz.jpg',
            ],
            'h1' => 'Achète un bon cadeau – offre une expérience sur deux roues !',
            'intro_left' => '<p>Tu cherches un cadeau original pour ton ou ta partenaire, un ami ou ton père ?</p><p>&nbsp;</p><p>Nos <strong>bons cadeaux pour la location d\'une moto</strong> de Motogo24 – <strong>location de motos Vysočina</strong> – raviront aussi bien les débutants que les pilotes expérimentés.</p><p>&nbsp;</p><p>Choisis la valeur du bon ou une moto précise et offre la liberté sur deux roues.</p>',
            'intro_cta' => [
                'label' => 'COMMANDER UN BON CADEAU',
                'href' => '/koupit-darkovy-poukaz',
                'aria' => 'Commander un bon cadeau pour la location d\'une moto à la location Motogo24',
            ],
            'intro_image' => [
                'src' => 'gfx/darkovy-poukaz.jpg',
                'alt' => 'Bon cadeau',
            ],
            'steps' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => '1. Choisis',
                    'text' => 'Tu choisis la valeur du bon ou une moto précise.',
                ],
                [
                    'icon' => 'gfx/zaplat.svg',
                    'title' => '2. Paie',
                    'text' => 'Tu paies en ligne.',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => '3. Récupère',
                    'text' => 'Le bon arrive dans ta boîte e-mail après le paiement.',
                ],
            ],
            'validity_note' => 'Tous les vouchers ont une <strong>validité de 3 ans</strong> à compter de la date d\'émission. <strong>La personne offerte choisit elle-même la date de location</strong> qui lui convient. Elle peut nous contacter par e-mail, par téléphone ou via les réseaux sociaux.',
            'why' => [
                'title' => 'Pourquoi acheter un bon',
                'items' => [
                    '<strong>Choix flexible</strong> – valeur du bon ou moto précise.',
                    '<strong>Validité 3 ans</strong> – la personne offerte choisit elle-même la date.',
                    '<strong>Sans caution</strong> – conditions équitables sans obstacles inutiles.',
                    '<strong>Équipement inclus</strong> – casque, blouson, pantalon et gants gratuits.',
                    '<strong>Service 24h/24</strong> – prise en main et restitution à tout moment durant le jour de location.',
                    '<strong>Commande en ligne</strong> – le bon te parvient par e-mail après le paiement.',
                ],
            ],
            'how' => [
                'title' => 'Comment utiliser le bon',
                'items' => [
                    '<strong>Motos routières</strong> – road trip de week-end en Vysočina ou dans toute la République tchèque.',
                    '<strong>Motos sportives</strong> – conduite à sensations dans les virages.',
                    '<strong>Enduro</strong> – terrain léger et aventure hors des sentiers battus.',
                    '<strong>Motos pour enfants</strong> – premières balades pour petits pilotes sous surveillance.',
                ],
            ],
            'catalog_cta' => [
                'label' => 'VOIR LE CATALOGUE DE MOTOS',
                'href' => '/katalog',
            ],
            'faq' => [
                'title' => 'Questions fréquentes sur les bons cadeaux',
                'items' => [
                    [
                        'q' => 'Quelle est la validité du bon cadeau ?',
                        'a' => 'Tous les vouchers ont une validité de <strong>3 ans</strong> à compter de la date d\'émission. La personne offerte choisit elle-même la date de location.',
                    ],
                    [
                        'q' => 'Comment livrez-vous le bon ?',
                        'a' => '<strong>Immédiatement par e-mail</strong> après le paiement. Sur demande, nous pouvons aussi préparer une impression cadeau dans l\'établissement.',
                    ],
                    [
                        'q' => 'La personne offerte doit-elle déposer une caution ?',
                        'a' => 'Non. <strong>Nous louons sans caution</strong>. Les conditions sont claires et équitables, l\'équipement du pilote est inclus.',
                    ],
                    [
                        'q' => 'Peut-on changer la date d\'utilisation ?',
                        'a' => 'Oui, <strong>la date peut être modifiée d\'un commun accord</strong> selon la disponibilité de la moto concernée dans notre calendrier.',
                    ],
                    [
                        'q' => 'Sur quelles motos le voucher peut-il être utilisé ?',
                        'a' => 'Sur les <strong>motos routières, sportives, enduro et pour enfants</strong> de l\'offre Motogo24 – selon la valeur du bon choisie.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Bon cadeau pour la location d\'une moto – Vysočina',
                'text' => 'Motogo24 est une <strong>location de motos en Vysočina</strong> avec <strong>service 24h/24</strong>, <strong>sans caution</strong> et <strong>équipement inclus</strong>. Le voucher cadeau est le choix idéal pour offrir une expérience de <em>motorbike rental</em> – des <strong>motos routières</strong> aux <strong>motos sportives</strong> en passant par l\'<strong>enduro</strong> et les <strong>motos pour enfants</strong>.',
                'buttons' => [
                    [
                        'label' => 'COMMANDER UN VOUCHER',
                        'href' => '/koupit-darkovy-poukaz',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_cena' => [
            'seo' => [
                'title' => 'Location de motos Vysočina – Comment louer – Ce qui est inclus',
                'description' => 'Découvre ce qui est inclus dans le prix de location chez MotoGo24. Conditions claires, équipement et services sans frais cachés. Réserve ta moto en ligne facilement.',
                'keywords' => 'location de motos Vysočina, location motos Pelhřimov, location sans caution, location 24h/24, réservation en ligne moto',
            ],
            'h1' => 'Ce qui est inclus dans le prix de location',
            'intro' => 'Chez <strong>MotoGo24 – location de motos en Vysočina</strong>, tu obtiens des conditions justes. <strong>Sans caution, avec équipement du conducteur inclus et service 24h/24</strong>. Tout ce dont tu as besoin pour rouler en sécurité est inclus.',
            'cta' => [
                'title' => 'Équipement inclus – location de motos MotoGo24 – Vysočina',
                'text' => '<strong>MotoGo24 est une location de motos moderne en Vysočina</strong> avec équipement du conducteur inclus, location sans caution et service 24h/24. Choisis une <strong>moto de tourisme, supermoto, naked ou pour enfants</strong> et réserve en ligne.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER EN LIGNE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                        'aria' => 'Réserver une moto avec équipement inclus chez Motogo24',
                    ],
                ],
            ],
        ],
        'jak_pujcit_dokumenty' => [
            'seo' => [
                'title' => 'Location de motos Vysočina – Documents et manuels',
                'description' => 'Contrat de location, conditions et documents nécessaires pour louer une moto. Sans caution, règles claires, assurance incluse.',
                'keywords' => 'contrat location moto, documents location, conditions location, assurance moto, MotoGo24',
            ],
            'h1' => 'Contrat de location et caution – conditions justes sans avance',
            'intro' => 'Chez <strong>MotoGo24</strong>, nous misons sur la simplicité et l\'équité. Nous louons <strong>sans caution</strong>, avec un <strong>contrat clair</strong>, <strong>assurance incluse</strong> et <strong>équipement du conducteur</strong>.',
            'top_cta' => [
                'label' => 'RÉSERVER EN LIGNE',
                'href' => '/rezervace',
                'aria' => 'Réserver une moto en ligne chez Motogo24',
            ],
            'cta' => [
                'title' => 'Contrat sans caution – location de motos Vysočina',
                'text' => 'MotoGo24 est une <strong>location de motos en Vysočina</strong> avec des conditions justes.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER EN LIGNE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_pristaveni' => [
            'seo' => [
                'title' => 'Livraison de la moto | MotoGo24',
                'description' => 'Livraison de la moto à ta porte. Nous apportons la moto à ton hôtel, gare ou n\'importe quelle adresse. Tarif à partir de 290 Kč. Service 24h/24.',
                'keywords' => 'livraison moto, apport moto, livraison motocycle, location motos Vysočina',
            ],
            'h1' => 'Livraison de la moto – directement à toi',
            'intro' => 'Tu veux partir sans devoir te déplacer à la location ? Nous organisons <strong>la livraison de la moto</strong> au <strong>lieu convenu</strong>.',
            'top_cta' => [
                'label' => 'RÉSERVER AVEC LIVRAISON',
                'href' => '/rezervace?delivery=1',
            ],
            'cta' => [
                'title' => 'Livraison de la moto – location de motos Vysočina',
                'text' => 'MotoGo24 propose la <strong>livraison de la moto</strong> dans la région et au-delà. <strong>Service 24h/24, sans caution, équipement inclus</strong>.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER AVEC LIVRAISON',
                        'href' => '/rezervace?delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_jinde' => [
            'seo' => [
                'title' => 'Restitution de moto ailleurs | MotoGo24',
                'description' => 'Rends la moto en dehors de la location – depuis l\'hôtel, gare ou autre adresse. Récupération en Vysočina et au-delà. Prix selon distance, service 24h/24.',
                'keywords' => 'restitution moto ailleurs, récupération moto, restitution hors location, location motos Vysočina',
            ],
            'h1' => 'Restitution de moto ailleurs – récupération à toi',
            'intro' => 'Pas besoin de revenir à la location. <strong>MotoGo24</strong> propose la <strong>récupération de la moto</strong> depuis le lieu qui te convient – hôtel, gare, ton adresse.',
            'top_cta' => [
                'label' => 'RÉSERVER AVEC RÉCUPÉRATION',
                'href' => '/rezervace?return_delivery=1',
            ],
            'cta' => [
                'title' => 'Restitution de moto n\'importe où – MotoGo24',
                'text' => 'MotoGo24 organise la <strong>récupération de la moto</strong> depuis le lieu qui te convient. <strong>24h/24, sans caution, sans souci.</strong>',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER AVEC RÉCUPÉRATION',
                        'href' => '/rezervace?return_delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'faq' => [
            'seo' => [
                'title' => 'Foire aux questions | MotoGo24',
                'description' => 'Questions fréquentes sur la location de motos. Réservation, prise en charge, restitution, conditions, livraison, voyages à l\'étranger, bons cadeaux.',
                'keywords' => 'FAQ location motos, questions location moto, conditions location, caution, équipement',
            ],
            'h1' => 'Foire aux questions – location de motos MotoGo24',
            'closing' => 'Notre <strong>location de motos en Vysočina</strong> est là pour tous ceux qui veulent vivre une <strong>balade inoubliable</strong> sans complications.',
            'cta' => [
                'label' => 'Réserver une moto en ligne',
                'href' => '/rezervace',
            ],
        ],
        'home' => [
            'seo' => [
                'title' => 'Location de motos en Vysočina | MotoGo24',
                'description' => 'Loue une moto en Vysočina. Sans caution, équipement inclus, service 24h/24. Motos de tourisme, sport, enduro et pour enfants. Réservation en ligne.',
                'keywords' => 'location motos Vysočina, location motos Pelhřimov, location sans caution, location 24h/24, motos à louer, réservation en ligne moto',
                'og_image' => NULL,
            ],
            'hero' => [
                'image' => 'gfx/hero-banner.jpg',
                'alt' => 'Location de motos Vysočina',
                'eyebrow' => '<strong>Location de motos</strong> en Vysočina',
                'body' => 'Loue une moto en Vysočina facilement en ligne.<br>Choisis parmi des modèles tourisme, sport et enduro.<br>Réservation avec paiement par carte et prise en charge rapide.',
                'cta_primary' => [
                    'label' => 'CHOISIS TA MOTO',
                    'href' => '/katalog',
                    'cls' => 'btngreen',
                ],
                'cta_secondary' => [
                    'label' => 'COMMENT ÇA MARCHE',
                    'href' => '/jak-pujcit',
                    'cls' => 'btndark',
                ],
            ],
            'h1' => 'Location de motos Vysočina Motogo24 – sans caution et 24h/24',
            'intro' => 'Bienvenue chez <strong>Motogo24</strong> – ta location de motos en Vysočina. Ici tu loues une moto <strong>sans caution</strong>, avec équipement inclus et en mode <strong>24h/24</strong>. Que tu cherches une moto de tourisme, sport, enduro ou pour enfants, Motogo24 au cœur de Vysočina te propose la moto idéale.',
            'signposts_title' => 'Guide rapide chez Motogo24',
            'signposts' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => 'Catalogue de motos',
                    'text' => 'Découvre notre offre de motos à louer — du sport au tourisme.',
                    'btn' => 'CATALOGUE DE MOTOS',
                    'href' => '/katalog',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => 'Comment louer une moto',
                    'text' => 'Processus simple : choisis une moto, réserve et pars en route.',
                    'btn' => 'COMMENT LOUER',
                    'href' => '/jak-pujcit',
                ],
                [
                    'icon' => 'gfx/rezervace-online.svg',
                    'title' => 'Réservation en ligne',
                    'text' => 'Réserve ta moto via notre système en ligne facile.',
                    'btn' => 'RÉSERVER UNE MOTO',
                    'href' => '/rezervace',
                ],
                [
                    'icon' => 'gfx/kontakt.svg',
                    'title' => 'Contact et carte',
                    'text' => 'Visite notre location de motos à Pelhřimov ou contacte-nous.',
                    'btn' => 'CONTACT',
                    'href' => '/kontakt',
                ],
                [
                    'icon' => 'gfx/faq.svg',
                    'title' => 'Foire aux questions',
                    'text' => 'Les questions les plus fréquentes sur la location de motos en un seul endroit.',
                    'btn' => 'FAQ',
                    'href' => '/jak-pujcit/faq',
                ],
                [
                    'icon' => 'gfx/uzij-si-jizdu.svg',
                    'title' => 'Itinéraires moto',
                    'text' => 'Découvre les meilleurs itinéraires moto en République tchèque pour touristes et locaux.',
                    'btn' => 'ITINÉRAIRES MOTO',
                    'href' => '/blog',
                ],
            ],
            'motos_section' => [
                'title' => 'Nos motos à louer en Vysočina',
                'intro' => 'Découvre notre offre de motos tourisme, sport et enduro de notre location en Vysočina.',
                'empty' => 'Actuellement aucune moto disponible.',
                'cta_label' => 'CATALOGUE DE MOTOS',
                'cta_href' => '/katalog',
                'limit' => 4,
            ],
            'process' => [
                'title' => 'Comment fonctionne la location en Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Choisis',
                        'text' => 'Choisis ta moto idéale dans notre offre de motos à louer.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Réserve',
                        'text' => 'Réserve ta moto via notre système en ligne simple.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '3. Récupère',
                        'text' => 'Récupère la moto à notre location à Pelhřimov.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '4. Profite du voyage',
                        'text' => 'Vis la liberté et découvre la République tchèque sur des motos de location.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Foire aux questions',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => 'Comment puis-je réserver une moto ?',
                        'a' => 'Tu peux réserver une moto via notre système de réservation en ligne directement ici sur le site. Ou contacte-nous par e-mail, téléphone ou réseaux sociaux.',
                    ],
                    [
                        'q' => 'Puis-je louer une moto sans réservation préalable ?',
                        'a' => 'Hélas non. Chaque moto doit être réservée à l\'avance — en ligne, par téléphone, e-mail ou réseaux sociaux.',
                    ],
                    [
                        'q' => 'Dois-je verser une caution ?',
                        'a' => 'Non ! Chez nous tu <strong>ne paies aucune caution</strong>. Notre location se distingue ainsi fondamentalement de la plupart de la concurrence.',
                    ],
                    [
                        'q' => 'Puis-je voyager à l\'étranger avec la moto ?',
                        'a' => 'Oui, tu peux voyager à l\'étranger sans problème. Nous ne limitons pas les voyages hors de la République tchèque ; tu dois juste respecter la validité territoriale de l\'assurance (carte verte).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Réserve ta moto en ligne',
                'text' => 'Notre <strong>location de motos Vysočina</strong> est ouverte <strong>24h/24</strong>. Quelques clics et ta balade commence.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER UNE MOTO',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Bon cadeau',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Conseils d\'itinéraire',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
            'blog' => [
                'title' => 'Blog et conseils',
                'empty' => 'Aucun article pour le moment.',
                'cta_label' => 'LIRE PLUS SUR LE BLOG',
                'cta_href' => '/blog',
                'limit' => 3,
            ],
            'reviews' => [
                'title' => 'Ce que disent nos clients',
                'intro' => 'Avis réels de motards qui ont loué chez nous. Merci pour chaque évaluation.',
            ],
        ],
        'pujcovna' => [
            'seo' => [
                'title' => 'À propos de la location de motos | MotoGo24',
                'description' => 'Location de motos Motogo24 en Vysočina. Sans caution, avec réservation en ligne et équipement inclus. Motos de tourisme, sport, enduro et pour enfants. Service 24h/24.',
                'keywords' => 'location motos, location motos Vysočina, motos sans caution, location 24h/24, équipement inclus',
            ],
            'breadcrumb' => [
                [
                    'label' => 'Accueil',
                    'href' => '/',
                ],
                'Location de motos',
            ],
            'intro' => [
                'h1' => 'Location de motos Vysočina Motogo24',
                'body' => 'Notre <strong>location de motos en Vysočina</strong> à Pelhřimov propose la <strong>location de motos</strong> sans obstacles – <strong>sans caution</strong>, avec <strong>réservation en ligne</strong> et <strong>équipement inclus</strong>. Choisis parmi des <strong>motos de tourisme</strong>, <strong>sport</strong>, <strong>enduro</strong> et <strong>pour enfants</strong>, et pars quand tu veux : nous sommes ouverts <strong>24h/24</strong>.',
            ],
            'benefits' => [
                'title' => 'Pourquoi louer chez nous',
                'closing' => 'Tu cherches une <strong>location de motos en Vysočina</strong> ? Motogo24 propose des conditions justes, un processus clair et des machines parfaitement entretenues pour des voyages en République tchèque et à l\'étranger.',
                'buttons' => [
                    [
                        'label' => 'Voir les motos à louer',
                        'href' => '/katalog',
                        'cls' => 'btngreen',
                    ],
                    [
                        'label' => 'RÉSERVER',
                        'href' => '/rezervace',
                        'cls' => 'btngreen pulse',
                    ],
                ],
                'items' => [
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'Sans caution',
                        'text' => 'et sans frais cachés',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Réservation en ligne',
                        'text' => 'en quelques clics',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Équipement pilote inclus',
                        'text' => 'casque, blouson, pantalon et gants',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => 'Service 24h/24',
                        'text' => 'pour la prise en charge et le retour selon ta réservation',
                    ],
                    [
                        'icon' => 'gfx/ico-spolecne.svg',
                        'title' => 'Nous sommes avec toi',
                        'text' => 'si quelque chose se passe',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Livraison et reprise',
                        'text' => 'à un endroit convenu',
                    ],
                ],
            ],
            'process' => [
                'title' => 'Comment fonctionne la location en Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Choisis une moto',
                        'text' => 'Découvre notre offre et choisis le type qui te convient, à ton expérience et à ton permis.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Réserve en ligne',
                        'text' => 'Réserve par date ou par moto précise que tu veux louer.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => '3. Choisis l\'équipement',
                        'text' => 'L\'équipement pilote est inclus, celui du passager est en supplément. La taille se choisit sur place.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => '4. Paie',
                        'text' => 'Paie facilement en ligne via la passerelle de paiement.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '5. Récupère la moto',
                        'text' => 'Récupère la moto directement à la location, ou à l\'endroit choisi lors de la réservation.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '6. Profite du voyage',
                        'text' => 'Prends la route, découvre de nouvelles expériences et profite pleinement de la liberté à deux roues.',
                    ],
                    [
                        'icon' => 'gfx/vrat-motorku-vcas.svg',
                        'title' => '7. Rends la moto',
                        'text' => 'Rends simplement la moto le jour convenu – à la location ou à un endroit convenu.',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'Réduction pour la prochaine balade',
                        'text' => 'Après le retour de la moto nous t\'envoyons automatiquement un code de réduction de 200 Kč pour ta prochaine réservation.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Foire aux questions',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => 'Comment puis-je réserver une moto ?',
                        'a' => 'Tu peux réserver une moto via notre système de réservation en ligne directement ici sur le site. Ou contacte-nous par e-mail, téléphone ou réseaux sociaux.',
                    ],
                    [
                        'q' => 'Puis-je louer une moto sans réservation préalable ?',
                        'a' => 'Hélas non. Chaque moto doit être réservée à l\'avance.',
                    ],
                    [
                        'q' => 'Dois-je verser une caution ?',
                        'a' => 'Non ! Chez nous tu <strong>ne paies aucune caution</strong>. Notre location se distingue ainsi fondamentalement de la plupart de la concurrence.',
                    ],
                    [
                        'q' => 'Puis-je voyager à l\'étranger avec la moto ?',
                        'a' => 'Oui, tu peux voyager à l\'étranger sans problème. Nous ne limitons pas les voyages hors de la République tchèque ; il suffit de respecter la validité territoriale de l\'assurance (carte verte).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Réserve ta moto en ligne',
                'text' => 'Notre <strong>location de motos Vysočina</strong> est ouverte <strong>24h/24</strong>.',
                'buttons' => [
                    [
                        'label' => 'RÉSERVER UNE MOTO',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Bon cadeau',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Conseils d\'itinéraire',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
        ],
    ],
];
