<?php
// MotoGo24 — pages_pl.php (auto-generated by merge_pages.php; parts: 0)

return [
    'pages' => [
        'jak_pujcit_cena' => [
            'seo' => [
                'title' => 'Wypożyczalnia motocykli Vysočina – Jak wypożyczyć – Co jest w cenie',
                'description' => 'Sprawdź, co zawiera cena wynajmu motocykla w MotoGo24. Jasne warunki, wyposażenie i usługi bez ukrytych opłat. Zarezerwuj motocykl online.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Co jest w cenie wynajmu motocykla',
            'intro' => 'W <strong>MotoGo24 – wypożyczalni motocykli w Vysočina</strong> otrzymasz uczciwe warunki. <strong>Bez kaucji, z wyposażeniem kierowcy w cenie i obsługą całodobową</strong>. Wszystko, czego potrzebujesz do bezpiecznej i przyjemnej jazdy, jest wliczone.',
            'gear' => [
                'basic' => [
                    'title' => 'Podstawowe wyposażenie w cenie',
                    'lead' => 'Każdy kierowca ma do dyspozycji kompletne <strong>wyposażenie motocyklowe</strong>, które jest wliczone w cenę wynajmu:',
                    'items' => [
                        '<strong>kask</strong>',
                        '<strong>kurtka motocyklowa</strong> z ochraniaczami',
                        '<strong>spodnie motocyklowe</strong>',
                        '<strong>rękawice</strong>',
                    ],
                    'note1' => 'Wyposażenie jest dostępne w wielu rozmiarach, regularnie je czyścimy i sprawdzamy.',
                    'note2' => 'Wybrane motocykle są wyposażone w kufry – zobacz szczegóły motocykla w katalogu.',
                ],
                'extra' => [
                    'title' => 'Wyposażenie dodatkowe za dopłatą',
                    'lead' => 'Jedziesz z pasażerem albo chcesz buty motocyklowe? Możesz je domówić przy rezerwacji:',
                    'items' => [
                        'wyposażenie dla pasażera (kask, kurtka, spodnie, rękawice)',
                        'buty motocyklowe – dla kierowcy i pasażera',
                    ],
                ],
                'services' => [
                    'title' => 'Usługi dodatkowe za dopłatą',
                    'items' => [
                        'podstawienie motocykla w umówione miejsce w dowolnym punkcie Czech',
                        'zwrot motocykla w innym miejscu niż adres wypożyczalni',
                    ],
                ],
            ],
            'benefits' => [
                'title' => 'Inne korzyści w cenie',
                'grid' => 'gr5',
                'items' => [
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Rezerwacja online',
                        'text' => 'szybka i prosta rezerwacja z domowego zacisza.',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => 'Obsługa całodobowa',
                        'text' => 'rezerwuj i wyruszaj o dowolnej porze – w dzień, w nocy i w weekend. Godzinę odbioru wybierasz przy rezerwacji.',
                    ],
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'Bez kaucji',
                        'text' => 'brak kaucji przy wynajmie.',
                    ],
                    [
                        'icon' => 'gfx/jasne-podminky.svg',
                        'title' => 'Jasne warunki',
                        'text' => 'bez ukrytych opłat.',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'Zniżka na kolejną rezerwację',
                        'text' => 'po każdym zakończonym wynajmie otrzymujesz kod rabatowy na kolejną rezerwację.&nbsp;',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Wyposażenie w cenie – wypożyczalnia motocykli MotoGo24 – Vysočina',
                'text' => '<strong>MotoGo24 to nowoczesna wypożyczalnia motocykli w Vysočina</strong> z wyposażeniem kierowcy w cenie, wynajmem bez kaucji i obsługą całodobową. Wybierz <strong>motocykl turystyczny, supermoto, naked lub dla dzieci</strong> i zarezerwuj online.',
                'buttons' => [
                    [
                        'label' => 'REZERWUJ ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                        'aria' => 'Zarezerwuj motocykl z wyposażeniem w cenie w Motogo24',
                    ],
                ],
            ],
        ],
        'jak_pujcit_dokumenty' => [
            'seo' => [
                'title' => 'Wypożyczalnia motocykli Vysočina – Dokumenty i instrukcje',
                'description' => 'Umowa najmu, warunki i dokumenty potrzebne do wynajmu motocykla. Bez kaucji, jasne zasady, ubezpieczenie w cenie.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Umowa najmu i kaucja – uczciwe warunki bez zaliczki',
            'intro' => 'W <strong>MotoGo24</strong> stawiamy na prostotę i uczciwość. Wypożyczamy <strong>bez kaucji</strong>, z <strong>jasną umową najmu</strong>, <strong>ubezpieczeniem w cenie</strong> i <strong>wyposażeniem kierowcy</strong>.',
            'top_cta' => [
                'label' => 'REZERWUJ ONLINE',
                'href' => '/rezervace',
                'aria' => 'Zarezerwuj motocykl online w Motogo24',
            ],
            'summary' => [
                'title' => 'Podsumowanie najważniejszych punktów',
                'items' => [
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'Bez kaucji / zaliczki',
                        'text' => 'wypożyczamy motocykl bez blokowania pieniędzy',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Rezerwacja online',
                        'text' => 'wraz z płatnością',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Wyposażenie kierowcy',
                        'text' => 'w cenie (kask, kurtka, spodnie, rękawice)',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => 'Obsługa całodobowa',
                        'text' => 'odbiór i zwrot o dowolnej porze w dniu wynajmu',
                    ],
                    [
                        'icon' => 'gfx/jasne-podminky.svg',
                        'title' => 'Jasne zasady użytkowania',
                        'text' => 'w kraju i za granicą (zgodnie z zieloną kartą)',
                    ],
                    [
                        'icon' => 'gfx/zadne-skryte-poplatky.svg',
                        'title' => 'Bez ukrytych opłat',
                        'text' => 'wszystko jest podane poniżej i w umowie',
                    ],
                ],
            ],
            'required_docs' => [
                'title' => 'Czego potrzebujesz do zawarcia umowy',
                'items' => [
                    '<strong>Dowód osobisty / paszport</strong>',
                    '<strong>Prawo jazdy</strong>&nbsp;odpowiedniej kategorii (A / A2 w zależności od maszyny)',
                    '<strong>Wiek</strong>&nbsp;min. 18 lat (przy motocyklach dziecięcych odpowiada przedstawiciel ustawowy)',
                    '<strong>Kontakty</strong>&nbsp;(telefon, e-mail) do komunikacji i potwierdzenia rezerwacji',
                ],
            ],
            'payments' => [
                'title' => 'Płatności, rezygnacja i opłaty',
                'lead' => '<strong>Kaucja:</strong>&nbsp;<em>nie wymagamy</em>. Płatność za wynajem odbywa się online lub przy odbiorze.',
                'aria' => 'Przegląd płatności i opłat',
                'headers' => [
                    'Pozycja',
                    'Warunki',
                ],
                'rows' => [
                    [
                        '<strong>Płatność za wynajem</strong>',
                        'Online z góry.',
                    ],
                    [
                        '<strong>Rezygnacja z rezerwacji</strong>',
                        'Bezpłatnie do umówionego czasu (podanego w potwierdzeniu rezerwacji). Później według indywidualnych ustaleń.',
                    ],
                    [
                        '<strong>Paliwo i czyszczenie</strong>',
                        'Zwrot bez obowiązku tankowania i mycia. Nadmierne zabrudzenie rozpatrujemy indywidualnie.',
                    ],
                    [
                        '<strong>Podstawienie / odbiór</strong>',
                        'Według cennika podstawienia (Vysočina / okolice). Potwierdzamy przy rezerwacji.',
                    ],
                    [
                        '<strong>Spóźniony zwrot</strong>',
                        'Prosimy o terminowy zwrot w ostatnim dniu wynajmu; przy opóźnieniu naliczamy według ustaleń (z uwzględnieniem innych rezerwacji).',
                    ],
                ],
                'mid_cta' => [
                    'label' => 'PRZEJDŹ DO REZERWACJI',
                    'href' => '/rezervace',
                    'aria' => 'Zarezerwuj motocykl i zaakceptuj umowę najmu Motogo24',
                ],
            ],
            'usage' => [
                'title' => 'Użytkowanie motocykla i odpowiedzialność',
                'items' => [
                    'Jedź&nbsp;<strong>zgodnie z przepisami</strong>&nbsp;i z uwzględnieniem stanu technicznego oraz typu motocykla.',
                    'Za&nbsp;<strong>mandaty i wykroczenia</strong>&nbsp;odpowiada najemca (informacje przekazujemy zgodnie z prawem).',
                    '<strong>Zagranica</strong>: możliwa; kieruj się terytorialną ważnością ubezpieczenia (zielona karta). Niektóre kraje mogą być wyłączone.',
                    'W razie&nbsp;<strong>wypadku lub awarii</strong>&nbsp;postępuj zgodnie z instrukcją w zestawie pokładowym (formularz wypadkowy, kontakt do Motogo24).',
                    '<strong>Serwis i konserwację</strong>&nbsp;zapewniamy my; usterki zgłaszaj natychmiast.',
                    '<strong>Modyfikacje motocykla</strong>&nbsp;bez zgody nie są dozwolone.',
                ],
            ],
            'handover' => [
                'title' => 'Przekazanie i zwrot',
                'items' => [
                    '<strong>Odbiór</strong>&nbsp;odbywa się w Pelhřimovie (Mezná 9) lub skorzystaj z&nbsp;<a href="/jak-pujcit/pristaveni">podstawienia</a>.',
                    'Przy przekazaniu otrzymujesz&nbsp;<strong>kluczyki, wyposażenie i dokumenty</strong>&nbsp;(dowód rejestracyjny, zielona karta, formularz wypadkowy).',
                    '<strong>Zwrot</strong>&nbsp;o dowolnej porze w ostatnim dniu wynajmu (nawet o północy). Nie trzeba myć ani tankować.',
                ],
            ],
            'privacy' => [
                'title' => 'Dane osobowe i bezpieczeństwo',
                'text' => 'Dane osobowe przetwarzamy wyłącznie w celu zawarcia i realizacji umowy najmu (identyfikacja, komunikacja, fakturowanie). Szczegóły znajdziesz w <a href="/cms/zasady-ochrany-osobnich-udaju">polityce przetwarzania danych osobowych</a>.',
            ],
            'documents' => [
                'title' => 'Dokumenty do pobrania',
                'items' => [
                    [
                        'name' => 'Umowa najmu',
                        'href' => '/cms/smlouva-o-pronajmu',
                        'size' => '87.4kB',
                    ],
                    [
                        'name' => 'Protokół przekazania',
                        'href' => '/cms/predavaci-protokol',
                        'size' => '47.6kB',
                    ],
                    [
                        'name' => 'Regulamin',
                        'href' => '/cms/obchodni-podminky',
                        'size' => '87.7kB',
                    ],
                    [
                        'name' => 'Polityka prywatności',
                        'href' => '/cms/zasady-ochrany-osobnich-udaju',
                        'size' => '76.3kB',
                    ],
                ],
            ],
            'midcta' => [
                'title' => 'Zgadzasz się z warunkami? Rezerwuj i jedź.',
                'text' => 'Wybierz spośród&nbsp;<strong>motocykli turystycznych, sportowych, enduro i dziecięcych</strong>&nbsp;i potwierdź rezerwację online.',
            ],
            'cta' => [
                'title' => 'Umowa najmu bez kaucji – wypożyczalnia motocykli Vysočina',
                'text' => 'MotoGo24 to <strong>wypożyczalnia motocykli w Vysočina</strong> z uczciwymi warunkami.',
                'buttons' => [
                    [
                        'label' => 'REZERWUJ ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_pristaveni' => [
            'seo' => [
                'title' => 'Dostawa motocykla | MotoGo24',
                'description' => 'Dostawa motocykla pod twoje drzwi. Dowieziemy motocykl do hotelu, na dworzec lub pod inny adres. Cennik od 290 Kč. Obsługa całodobowa.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Dostawa motocykla – prosto do ciebie',
            'intro' => 'Chcesz wyruszyć bez konieczności jazdy do wypożyczalni? Zorganizujemy <strong>dostawę motocykla</strong> w <strong>uzgodnione miejsce</strong>.',
            'top_cta' => [
                'label' => 'REZERWUJ Z DOSTAWĄ',
                'href' => '/rezervace?delivery=1',
            ],
            'when' => [
                'title' => 'Kiedy podstawienie się przydaje',
                'items' => [
                    '<strong>Początek&nbsp;roadtripu</strong>&nbsp;– przywieziemy motocykl prosto na start twojej trasy.',
                    '<strong>Hotel lub pensjonat</strong>&nbsp;– dostawa do miejsca zakwaterowania, żebyś oszczędził czas.',
                    '<strong>Dworzec kolejowy/autobusowy</strong>&nbsp;– płynna przesiadka bez czekania.',
                    '<strong>Imprezy firmowe i prezenty</strong>&nbsp;– niespodzianka dla partnerów lub zespołu.',
                ],
            ],
            'why' => [
                'title' => 'Dlaczego skorzystać z podstawienia motocykla',
                'grid' => 'gr5',
                'items' => [
                    [
                        'icon' => 'gfx/vyzvednuti-vraceni-motorky.svg',
                        'title' => 'Elastyczność',
                        'text' => 'Przywieziemy motocykl tam, gdzie potrzebujesz – do domu, do hotelu, na dworzec albo na start trasy.',
                    ],
                    [
                        'icon' => 'gfx/ico-pohodli.svg',
                        'title' => 'Wygoda',
                        'text' => 'Nie musisz organizować dojazdu do wypożyczalni – gdzie zostawić auto albo kto cię przywiezie.',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => 'Obsługa całodobowa',
                        'text' => 'Podstawienie umawiamy na ustaloną godzinę – spokojnie wieczorem albo w weekend. Wystarczy wybrać godzinę przy rezerwacji.',
                    ],
                    [
                        'icon' => 'gfx/uspora-casu.svg',
                        'title' => 'Oszczędność czasu',
                        'text' => 'Czas zaoszczędzony na dojeździe do wypożyczalni i z powrotem możesz poświęcić sobie.',
                    ],
                    [
                        'icon' => 'gfx/ico-vybava.svg',
                        'title' => 'Wyposażenie ze sobą',
                        'text' => 'Przywieziemy też wypożyczone wyposażenie w żądanych rozmiarach prosto do ciebie.',
                    ],
                ],
            ],
            'process' => [
                'title' => 'Jak przebiega podstawienie',
                'grid' => 'gr5',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => 'Wybierz motocykl',
                        'text' => 'Przejrzyj naszą ofertę motocykli turystycznych, supermoto, naked i dziecięcych i wybierz właściwy.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Wybierz termin',
                        'text' => 'Wybierz w kalendarzu datę, w której chcesz wyruszyć. Zobaczysz, które motocykle są wolne.',
                    ],
                    [
                        'icon' => 'gfx/kontaktni-udaje.svg',
                        'title' => 'Dane kontaktowe',
                        'text' => 'Wpisz imię, adres, e-mail i telefon.',
                    ],
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Godzina podstawienia',
                        'text' => 'Wybierz, kiedy podstawimy motocykl – spokojnie wieczorem albo w weekend.',
                    ],
                    [
                        'icon' => 'gfx/vyzvednuti-vraceni-motorky.svg',
                        'title' => 'Miejsce podstawienia',
                        'text' => 'Podaj adres, pod który przywieźć motocykl – dom, hotel, dworzec albo start trasy.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Wyposażenie',
                        'text' => 'Podstawowe wyposażenie kierowcy jest w cenie. Żądane rozmiary wszystkich części wyposażenia podaj w polu Uwaga – obowiązkowe.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => 'Potwierdzenie i płatność',
                        'text' => 'Sprawdź podsumowanie zamówienia, zaakceptuj warunki i zapłać online.',
                    ],
                    [
                        'icon' => 'gfx/podpis-dokumentu.svg',
                        'title' => 'Odbiór na miejscu',
                        'text' => 'Przy przekazaniu sprawdzimy dokumenty, uzupełnimy umowę i podpiszemy protokół przekazania.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => 'Ciesz się jazdą',
                        'text' => 'W trasę – bez kaucji, bez stresu. Reszta to już tylko asfalt i wolność.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Zwróć motocykl',
                        'text' => 'Zwróć motocykl na czas w umówionym miejscu. Nie trzeba tankować ani myć.',
                    ],
                ],
            ],
            'pricing' => [
                'title' => 'Cennik podstawienia',
                'lead' => '<strong>Cena podstawienia składa się z trzech elementów:</strong>',
                'items' => [
                    '<strong>500 CZK</strong>&nbsp;za załadunek motocykla,',
                    '<strong>500 CZK</strong>&nbsp;za rozładunek motocykla,',
                    '<strong>20 CZK</strong>&nbsp;za każdy kilometr (liczona jest odległość z wypożyczalni do miejsca docelowego i z powrotem)',
                ],
                'example' => '<strong>Przykład:</strong>&nbsp;Chcesz, by motocykl podstawić 30 km od wypożyczalni? Zapłacisz 500 + 500 + (30 × 2 × 20) =&nbsp;<strong>2 200 CZK.</strong>',
            ],
            'faq' => [
                'title' => 'Najczęściej zadawane pytania o podstawienie',
                'items' => [
                    [
                        'q' => 'Z jakim wyprzedzeniem zamówić podstawienie?',
                        'a' => 'Najlepiej <strong>przy</strong> <strong>rezerwacji online</strong> – podajesz adres i godzinę. W pilnych sprawach skontaktuj się z nami telefonicznie.',
                    ],
                    [
                        'q' => 'Czy mogę zwrócić motocykl w innym miejscu niż go odebrałem?',
                        'a' => 'Tak, naliczamy <strong>odbiór</strong> w zależności od odległości od Pelhřimova. Umawiamy to przy rezerwacji.',
                    ],
                    [
                        'q' => 'Ile kosztuje podstawienie poza Vysočinę?',
                        'a' => 'Kierujemy się tabelą odległości. Powyżej 100 km cenę kalkulujemy <strong>indywidualnie</strong>.',
                    ],
                    [
                        'q' => 'Czy pobierana jest kaucja?',
                        'a' => 'Nie. <strong>Wypożyczamy bez kaucji</strong>, warunki są jasne i uczciwe.',
                    ],
                    [
                        'q' => 'Czy wyposażenie kierowcy też jest w cenie?',
                        'a' => 'Tak. Kask, kurtka, spodnie i rękawice są dla kierowcy&nbsp;<strong>w cenie wynajmu</strong>.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Dostawa motocykla – wypożyczalnia motocykli Vysočina',
                'text' => 'MotoGo24 oferuje <strong>dostawę motocykla</strong> w regionie i poza nim. <strong>Obsługa całodobowa, bez kaucji, wyposażenie w cenie</strong>.',
                'buttons' => [
                    [
                        'label' => 'REZERWUJ Z DOSTAWĄ',
                        'href' => '/rezervace?delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_jinde' => [
            'seo' => [
                'title' => 'Zwrot motocykla w innym miejscu | MotoGo24',
                'description' => 'Zwróć motocykl poza wypożyczalnią – z hotelu, dworca lub innego adresu. Odbiór w Vysočina i poza nią.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Zwrot motocykla w innym miejscu – odbiór do ciebie',
            'intro' => 'Nie musisz wracać do wypożyczalni. <strong>MotoGo24</strong> oferuje <strong>odbiór motocykla</strong> z miejsca, które ci pasuje – hotel, dworzec, własny adres.',
            'top_cta' => [
                'label' => 'REZERWUJ Z ODBIOREM',
                'href' => '/rezervace?return_delivery=1',
            ],
            'when' => [
                'title' => 'Kiedy zwrot w innym miejscu się przydaje',
                'items' => [
                    '<strong>Koniec roadtripu</strong>&nbsp;– wynajem zaczął się w Pelhřimovie, trasa kończy się gdzie indziej. Przekaż nam motocykl tam, gdzie kończy się twoja wyprawa.',
                    '<strong>Podróż w jedną stronę</strong>&nbsp;– wracasz do domu pociągiem lub autobusem? Przekaż nam motocykl przed odjazdem.',
                    '<strong>Hotel lub pensjonat</strong>&nbsp;– przekaż nam motocykl bezpośrednio przy miejscu zakwaterowania, żebyś nie musiał myśleć o powrocie do wypożyczalni.',
                    '<strong>Impreza firmowa</strong>&nbsp;– wynajem dla grupy ze zwrotem bezpośrednio na miejscu imprezy.',
                ],
            ],
            'why' => [
                'title' => 'Dlaczego skorzystać ze zwrotu w innym miejscu',
                'grid' => 'gr5',
                'items' => [
                    [
                        'icon' => 'gfx/vyzvednuti-vraceni-motorky.svg',
                        'title' => 'Elastyczność',
                        'text' => 'Wybierasz miejsce zwrotu zgodnie z trasą – hotel, dworzec, parking albo gdziekolwiek indziej.',
                    ],
                    [
                        'icon' => 'gfx/uspora-casu.svg',
                        'title' => 'Oszczędność czasu',
                        'text' => 'Oszczędzasz drogę powrotną do wypożyczalni i do domu – przekazujesz motocykl tam, gdzie jesteś.',
                    ],
                    [
                        'icon' => 'gfx/ico-pohodli.svg',
                        'title' => 'Wygoda',
                        'text' => 'Nie musisz się zastanawiać, jak dostać się z wypożyczalni do domu.&nbsp;',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => 'Obsługa całodobowa',
                        'text' => 'Zwrot umawiamy na ustaloną godzinę – spokojnie wieczorem albo w weekend.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Prostota',
                        'text' => 'Przekazujesz kluczyki i wyposażenie, my sprawdzamy motocykl i odjeżdżamy. Bez dodatkowych formalności.',
                    ],
                ],
            ],
            'process' => [
                'title' => 'Jak przebiega zwrot w innym miejscu',
                'grid' => 'gr5',
                'steps' => [
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => 'Wybierz miejsce i godzinę zwrotu',
                        'text' => 'W formularzu rezerwacji podaj adres i godzinę, o której przekażesz motocykl.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Przygotuj wyposażenie',
                        'text' => 'Przed przekazaniem przygotuj wyposażenie, które było częścią wynajmu.',
                    ],
                    [
                        'icon' => 'gfx/cas-prevzeti-motorky.svg',
                        'title' => 'Przyjedziemy o umówionej godzinie',
                        'text' => 'Dotrzemy na umówione miejsce dokładnie o umówionej godzinie.',
                    ],
                    [
                        'icon' => 'gfx/prevezmi-motorku.svg',
                        'title' => 'Wspólnie sprawdzimy motocykl i wyposażenie',
                        'text' => 'Sprawdzimy stan motocykla i wyposażenia, załadujemy i odjedziemy.&nbsp;',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'Na e-mail przyjdzie potwierdzenie',
                        'text' => 'Potwierdzenie zakończenia wynajmu, faktura końcowa i kod rabatowy na kolejną rezerwację.',
                    ],
                ],
            ],
            'pricing' => [
                'title' => 'Cennik zwrotu w innym miejscu',
                'lead' => 'Cena składa się z trzech elementów:',
                'items' => [
                    '500 CZK za załadunek motocykla',
                    '500 CZK za rozładunek motocykla',
                    '20 CZK za każdy kilometr (odległość z miejsca zwrotu do wypożyczalni i z powrotem)',
                ],
                'example_title' => 'Przykład:',
                'example_q' => 'Chcesz zwrócić motocykl 30 km od wypożyczalni?',
                'example_a' => 'Zapłacisz 500 + 500 + (30 × 2 × 20) = 2 200 CZK.',
            ],
            'issues' => [
                'title' => 'Niezgodności przy zwrocie',
                'lead' => 'Przy zwrocie wspólnie sprawdzamy stan motocykla i wyposażenia. Gdyby wystąpiła któraś z poniższych sytuacji, sporządzamy protokół stwierdzonego uszkodzenia:',
                'items' => [
                    'brakujące wyposażenie',
                    'uszkodzone wyposażenie',
                    'uszkodzony motocykl',
                ],
                'closing' => 'Klient podpisuje protokół i otrzymuje jego kopię. Dalsze postępowanie reguluje umowa najmu i regulamin.',
            ],
            'faq' => [
                'title' => 'Najczęściej zadawane pytania o zwrot motocykla w innym miejscu',
                'items' => [
                    [
                        'q' => 'Do kiedy muszę zwrócić motocykl?',
                        'a' => 'Zwróć motocykl najlepiej o umówionej godzinie. Jeśli zwracasz w wypożyczalni, możesz po uzgodnieniu przyjechać o dowolnej porze w ostatnim dniu wynajmu – najpóźniej do północy, bez żadnych sankcji. Jeśli zwracasz w innym miejscu, umówiona godzina jest wiążąca.',
                    ],
                    [
                        'q' => 'Czy muszę zwrócić z pełnym bakiem i czysty?',
                        'a' => 'Nie. U nas nie tankujesz ani nie myjesz. Tylko pilnuj, żeby nie świeciła kontrolka rezerwy.&nbsp;',
                    ],
                    [
                        'q' => 'Czy przy zwrocie w innym miejscu mogę zwrócić motocykl wcześniej, niż się umówiliśmy?&nbsp;',
                        'a' => 'Na umówione miejsce wyjeżdżamy z Pelhřimova dokładnie według umówionego czasu, więc wcześniejszy zwrot niestety nie jest możliwy. Jeśli zmienią ci się plany, odezwij się – spróbujemy dostosować godzinę, ale zależy to od naszego aktualnego obciążenia.',
                    ],
                    [
                        'q' => 'Czy naprawdę mogę zwrócić motocykl gdziekolwiek w Czechach?&nbsp;',
                        'a' => 'Tak, przyjedziemy po motocykl gdziekolwiek w Czechach. Miejsce zwrotu podajesz przy rezerwacji – może to być hotel, parking, dworzec lub jakikolwiek inny adres.',
                    ],
                    [
                        'q' => 'Z jakim wyprzedzeniem muszę zgłosić zwrot w innym miejscu?&nbsp;',
                        'a' => 'Miejsce i godzinę zwrotu podajesz już w formularzu rezerwacji.&nbsp;',
                    ],
                    [
                        'q' => 'Co, jeśli spóźnię się na miejsce zwrotu?&nbsp;',
                        'a' => 'Zadzwoń do nas, gdy tylko wiesz, że nie zdążysz na czas. Dogadamy się – zwykle na ciebie poczekamy. Musimy tylko wiedzieć, z jakim opóźnieniem mamy się liczyć, żeby dostosować plan dnia.',
                    ],
                    [
                        'q' => 'Jak liczona jest cena za zwrot w innym miejscu?&nbsp;',
                        'a' => 'Cena obejmuje 500 CZK za załadunek, 500 CZK za rozładunek i 20 CZK za każdy kilometr odległości z miejsca zwrotu do wypożyczalni (i z powrotem). Na przykład przy zwrocie 50 km od Pelhřimova zapłacisz 500 + 500 + (50 × 2 × 20) = 3 000 CZK.',
                    ],
                    [
                        'q' => 'Czy za zwrot w innym miejscu płacę osobno, czy jest to część ceny wynajmu?&nbsp;',
                        'a' => 'Zwrot w innym miejscu to usługa dodatkowa i płaci się za nią osobno, poza ceną wynajmu.&nbsp;',
                    ],
                    [
                        'q' => 'Co, jeśli chcę odebrać motocykl w Pelhřimovie, ale zwrócić w innym miejscu – czy to możliwe?&nbsp;',
                        'a' => 'Tak, możesz odebrać motocykl u nas w Pelhřimovie i zwrócić go tam, gdzie potrzebujesz.&nbsp;',
                    ],
                    [
                        'q' => 'Co mam mieć przygotowane, gdy przyjedziecie po motocykl?&nbsp;',
                        'a' => 'Miej przygotowane kluczyki i całe wyposażenie, które było częścią wynajmu. Wspólnie sprawdzimy stan motocykla i wyposażenia.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Zwrot motocykla wszędzie – MotoGo24',
                'text' => 'MotoGo24 organizuje <strong>odbiór motocykla</strong> z miejsca, które ci pasuje. <strong>Całodobowo, bez kaucji, bez zmartwień.</strong>',
                'buttons' => [
                    [
                        'label' => 'REZERWUJ Z ODBIOREM',
                        'href' => '/rezervace?return_delivery=1',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'faq' => [
            'seo' => [
                'title' => 'Najczęściej zadawane pytania | MotoGo24',
                'description' => 'Najczęściej zadawane pytania dotyczące wynajmu motocykla. Rezerwacja, odbiór, zwrot, warunki, dostawa, podróże zagraniczne, bony prezentowe.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Najczęściej zadawane pytania – wypożyczalnia motocykli MotoGo24',
            'closing' => 'Nasza <strong>wypożyczalnia motocykli w Vysočina</strong> jest dla wszystkich, którzy chcą przeżyć <strong>niezapomnianą jazdę</strong> bez zbędnych komplikacji.',
            'cta' => [
                'label' => 'Zarezerwuj motocykl online',
                'href' => '/rezervace',
            ],
        ],
        'home' => [
            'seo' => [
                'title' => 'Wypożyczalnia motocykli w Vysočina | MotoGo24',
                'description' => 'Wypożycz motocykl w Vysočina. Bez kaucji, wyposażenie w cenie, obsługa całodobowa. Motocykle turystyczne, sportowe, enduro i dla dzieci. Rezerwacja online.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
                'og_image' => NULL,
            ],
            'hero' => [
                'image' => 'gfx/hero-banner.jpg',
                'alt' => 'Wypożyczalnia motocykli Vysočina',
                'eyebrow' => '<strong>Wypożyczalnia motocykli</strong> w Vysočina',
                'body' => 'Wypożycz motocykl w Vysočina łatwo online.<br>Wybierz spośród modeli turystycznych, sportowych i enduro.<br>Rezerwacja z płatnością kartą i szybkim odbiorem.',
                'cta_primary' => [
                    'label' => 'WYBIERZ MOTOCYKL',
                    'href' => '/katalog',
                    'cls' => 'btngreen',
                ],
                'cta_secondary' => [
                    'label' => 'JAK TO DZIAŁA',
                    'href' => '/jak-pujcit',
                    'cls' => 'btndark',
                ],
            ],
            'h1' => 'Wypożyczalnia motocykli Vysočina Motogo24 – bez kaucji i całodobowo',
            'intro' => 'Witamy w <strong>Motogo24</strong> – twojej wypożyczalni motocykli w Vysočina. U nas wypożyczasz motocykl <strong>bez kaucji</strong>, z wyposażeniem w cenie i w trybie <strong>całodobowym</strong>. Niezależnie czy szukasz motocykla turystycznego, sportowego, enduro czy dla dzieci, Motogo24 w sercu Vysočina ma dla ciebie odpowiedni motocykl.',
            'signposts_title' => 'Szybki przewodnik po Motogo24',
            'signposts' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => 'Katalog motocykli',
                    'text' => 'Zobacz naszą ofertę motocykli do wynajęcia — od sportowych po turystyczne.',
                    'btn' => 'KATALOG MOTOCYKLI',
                    'href' => '/katalog',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => 'Jak wypożyczyć motocykl',
                    'text' => 'Prosty proces: wybierz motocykl, zarezerwuj i ruszaj.',
                    'btn' => 'JAK WYPOŻYCZYĆ',
                    'href' => '/jak-pujcit',
                ],
                [
                    'icon' => 'gfx/rezervace-online.svg',
                    'title' => 'Rezerwacja online',
                    'text' => 'Zarezerwuj motocykl przez nasz prosty system online.',
                    'btn' => 'ZAREZERWUJ MOTOCYKL',
                    'href' => '/rezervace',
                ],
                [
                    'icon' => 'gfx/kontakt.svg',
                    'title' => 'Kontakt i mapa',
                    'text' => 'Odwiedź naszą wypożyczalnię w Pelhřimovie lub skontaktuj się z nami.',
                    'btn' => 'KONTAKT',
                    'href' => '/kontakt',
                ],
                [
                    'icon' => 'gfx/faq.svg',
                    'title' => 'Najczęściej zadawane pytania',
                    'text' => 'Najczęstsze pytania o wynajem motocykla zebrane w jednym miejscu.',
                    'btn' => 'FAQ',
                    'href' => '/jak-pujcit/faq',
                ],
                [
                    'icon' => 'gfx/uzij-si-jizdu.svg',
                    'title' => 'Trasy motocyklowe',
                    'text' => 'Odkryj najlepsze trasy motocyklowe w Czechach dla turystów i lokalnych.',
                    'btn' => 'TRASY MOTOCYKLOWE',
                    'href' => '/blog',
                ],
            ],
            'motos_section' => [
                'title' => 'Nasze motocykle do wynajęcia w Vysočina',
                'intro' => 'Zobacz naszą ofertę motocykli turystycznych, sportowych i enduro z naszej wypożyczalni w Vysočina.',
                'empty' => 'Aktualnie nie mamy dostępnych motocykli.',
                'cta_label' => 'KATALOG MOTOCYKLI',
                'cta_href' => '/katalog',
                'limit' => 4,
            ],
            'process' => [
                'title' => 'Jak działa wypożyczanie motocykli w Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Wybierz',
                        'text' => 'Wybierz idealny motocykl z naszej oferty motocykli do wynajęcia.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Zarezerwuj',
                        'text' => 'Zarezerwuj motocykl przez nasz prosty system online.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '3. Odbierz',
                        'text' => 'Odbierz motocykl w naszej wypożyczalni w Pelhřimovie.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '4. Ciesz się jazdą',
                        'text' => 'Poczuj wolność i odkryj Czechy na motocyklach do wynajęcia.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Najczęściej zadawane pytania',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => 'Jak mogę zarezerwować motocykl?',
                        'a' => 'Motocykl możesz zarezerwować przez nasz system rezerwacji online bezpośrednio na stronie. Lub skontaktuj się z nami przez e-mail, telefon lub media społecznościowe.',
                    ],
                    [
                        'q' => 'Czy mogę wypożyczyć motocykl bez wcześniejszej rezerwacji?',
                        'a' => 'Niestety nie. Każdy motocykl trzeba zarezerwować z wyprzedzeniem — online, telefonicznie, e-mailem lub przez media społecznościowe.',
                    ],
                    [
                        'q' => 'Czy muszę wpłacić kaucję?',
                        'a' => 'Nie! U nas <strong>nie płacisz żadnej kaucji</strong>. Tym fundamentalnie różnimy się od większości konkurencji.',
                    ],
                    [
                        'q' => 'Czy mogę pojechać motocyklem za granicę?',
                        'a' => 'Tak, motocyklem bez problemu pojedziesz za granicę. Podróży poza Czechy nie ograniczamy; trzeba tylko zachować terytorialny zakres ubezpieczenia (zielona karta).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Zarezerwuj motocykl online',
                'text' => 'Nasza <strong>wypożyczalnia motocykli Vysočina</strong> jest otwarta <strong>całodobowo</strong>. Kilka kliknięć i twoja jazda się rozpoczyna.',
                'buttons' => [
                    [
                        'label' => 'ZAREZERWUJ MOTOCYKL',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Bon prezentowy',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Wskazówki dotyczące tras',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
            'blog' => [
                'title' => 'Blog i wskazówki',
                'empty' => 'Brak artykułów.',
                'cta_label' => 'CZYTAJ WIĘCEJ NA BLOGU',
                'cta_href' => '/blog',
                'limit' => 3,
            ],
            'reviews' => [
                'title' => 'Co mówią nasi klienci',
                'intro' => 'Prawdziwe opinie motocyklistów, którzy u nas wynajmowali. Dziękujemy za każdą ocenę.',
            ],
        ],
        'pujcovna' => [
            'seo' => [
                'title' => 'O wypożyczalni motocykli | MotoGo24',
                'description' => 'Wypożyczalnia motocykli Motogo24 w Vysočina. Bez kaucji, z rezerwacją online i wyposażeniem w cenie. Motocykle turystyczne, sportowe, enduro i dla dzieci.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'breadcrumb' => [
                [
                    'label' => 'Strona główna',
                    'href' => '/',
                ],
                'Wypożyczalnia motocykli',
            ],
            'intro' => [
                'h1' => 'Wypożyczalnia motocykli Vysočina Motogo24',
                'body' => 'Nasza <strong>wypożyczalnia motocykli w Vysočina</strong> w Pelhřimov oferuje <strong>wynajem motocykli</strong> bez zbędnych przeszkód – <strong>bez kaucji</strong>, z <strong>rezerwacją online</strong> i <strong>wyposażeniem w cenie</strong>. Wybierz spośród <strong>motocykli turystycznych</strong>, <strong>sportowych</strong>, <strong>enduro</strong> i <strong>dla dzieci</strong>, i wyrusz kiedy chcesz: jesteśmy otwarci <strong>całodobowo</strong>.',
            ],
            'benefits' => [
                'title' => 'Dlaczego wypożyczać u nas',
                'closing' => 'Szukasz <strong>wypożyczalni motocykli w Vysočina</strong>? Motogo24 oferuje uczciwe warunki, jasny proces i doskonale utrzymane maszyny do podróży po Czechach i za granicą.',
                'buttons' => [
                    [
                        'label' => 'Zobacz motocykle do wynajęcia',
                        'href' => '/katalog',
                        'cls' => 'btngreen',
                    ],
                    [
                        'label' => 'REZERWUJ',
                        'href' => '/rezervace',
                        'cls' => 'btngreen pulse',
                    ],
                ],
                'items' => [
                    [
                        'icon' => 'gfx/ico-bez-kauce.svg',
                        'title' => 'Bez kaucji',
                        'text' => 'i bez ukrytych opłat',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => 'Rezerwacja online',
                        'text' => 'w kilka kliknięć',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => 'Wyposażenie kierowcy w cenie',
                        'text' => 'kask, kurtka, spodnie i rękawice',
                    ],
                    [
                        'icon' => 'gfx/ico-nonstop.svg',
                        'title' => 'Obsługa całodobowa',
                        'text' => 'do odbioru i zwrotu zgodnie z rezerwacją',
                    ],
                    [
                        'icon' => 'gfx/ico-spolecne.svg',
                        'title' => 'Jesteśmy razem',
                        'text' => 'gdy coś się wydarzy',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => 'Dostawa i odbiór motocykla',
                        'text' => 'w umówione miejsce',
                    ],
                ],
            ],
            'process' => [
                'title' => 'Jak działa wypożyczanie w Vysočina',
                'steps' => [
                    [
                        'icon' => 'gfx/vyber-motorku.svg',
                        'title' => '1. Wybierz motocykl',
                        'text' => 'Zobacz naszą ofertę i wybierz typ, który ci odpowiada, twoim doświadczeniom i prawu jazdy.',
                    ],
                    [
                        'icon' => 'gfx/rezervace-online.svg',
                        'title' => '2. Zarezerwuj online',
                        'text' => 'Zarezerwuj według daty lub konkretnego motocykla, który chcesz wypożyczyć.',
                    ],
                    [
                        'icon' => 'gfx/vyber-vybavu.svg',
                        'title' => '3. Wybierz wyposażenie',
                        'text' => 'Wyposażenie kierowcy jest w cenie, dla pasażera za dopłatą. Rozmiar wybierzesz na miejscu.',
                    ],
                    [
                        'icon' => 'gfx/zaplat.svg',
                        'title' => '4. Zapłać',
                        'text' => 'Zapłać prosto online przez bramkę płatności.',
                    ],
                    [
                        'icon' => 'gfx/predani-motorky.svg',
                        'title' => '5. Odbierz motocykl',
                        'text' => 'Odbierz motocykl bezpośrednio w wypożyczalni lub w wybranym przy rezerwacji miejscu.',
                    ],
                    [
                        'icon' => 'gfx/uzij-si-jizdu.svg',
                        'title' => '6. Ciesz się jazdą',
                        'text' => 'Wyrusz w drogę, odkrywaj nowe doświadczenia i ciesz się pełną wolnością na dwóch kołach.',
                    ],
                    [
                        'icon' => 'gfx/vrat-motorku-vcas.svg',
                        'title' => '7. Zwróć motocykl',
                        'text' => 'Po prostu zwróć motocykl w umówionym dniu – w wypożyczalni lub w umówionym miejscu.',
                    ],
                    [
                        'icon' => 'gfx/sleva-na-pristi-jizdu.svg',
                        'title' => 'Zniżka na kolejną jazdę',
                        'text' => 'Po zwrocie motocykla automatycznie wyślemy ci kod rabatowy 200 Kč na kolejną rezerwację.',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'Najczęściej zadawane pytania',
                'more_link' => '/jak-pujcit/faq',
                'items' => [
                    [
                        'q' => 'Jak mogę zarezerwować motocykl?',
                        'a' => 'Motocykl możesz zarezerwować przez nasz system rezerwacji online bezpośrednio na stronie. Lub skontaktuj się z nami e-mailem, telefonicznie lub przez media społecznościowe.',
                    ],
                    [
                        'q' => 'Czy mogę wypożyczyć motocykl bez wcześniejszej rezerwacji?',
                        'a' => 'Niestety nie. Każdy motocykl trzeba zarezerwować z wyprzedzeniem.',
                    ],
                    [
                        'q' => 'Czy muszę wpłacić kaucję?',
                        'a' => 'Nie! U nas <strong>nie płacisz żadnej kaucji</strong>. Tym fundamentalnie różnimy się od większości konkurencji.',
                    ],
                    [
                        'q' => 'Czy mogę pojechać motocyklem za granicę?',
                        'a' => 'Tak, motocyklem bez problemu pojedziesz za granicę. Podróży poza Czechy nie ograniczamy; trzeba tylko zachować terytorialny zakres ubezpieczenia (zielona karta).',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Zarezerwuj motocykl online',
                'text' => 'Nasza <strong>wypożyczalnia motocykli Vysočina</strong> jest otwarta <strong>całodobowo</strong>.',
                'buttons' => [
                    [
                        'label' => 'ZAREZERWUJ MOTOCYKL',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                    [
                        'label' => 'Bon prezentowy',
                        'href' => '/poukazy',
                        'cls' => 'btndark',
                    ],
                    [
                        'label' => 'Wskazówki dotyczące tras',
                        'href' => '/blog',
                        'cls' => 'btndark',
                    ],
                ],
            ],
        ],
        'kontakt' => [
            'seo' => [
                'title' => 'Kontakt | MotoGo24 – wypożyczalnia motocykli Vysočina',
                'description' => 'Kontakty do wypożyczalni motocykli Motogo24 w Pelhřimov. Telefon +420 774 256 271, e-mail info@motogo24.cz. Obsługa całodobowa, adres Mezná 9, 393 01 Pelhřimov.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Kontakt – wypożyczalnia motocykli Motogo24',
            'intro' => 'Masz pytanie dotyczące <strong>wynajmu motocykla</strong>, chcesz zamówić <strong>bon prezentowy</strong>, potrzebujesz pomocy w wyborze albo chcesz od razu <strong>umówić rezerwację</strong>? Jesteśmy dla ciebie codziennie, <strong>całodobowo</strong>.',
            'side_cta' => [
                'title' => 'Chcesz umówić rezerwację?',
                'text' => 'Zarezerwuj motocykl online w kilka minut i wyrusz na przygodę.',
                'button' => [
                    'label' => 'REZERWUJ ONLINE',
                    'href' => '/rezervace',
                    'cls' => 'btndark',
                ],
            ],
            'quick' => [
                [
                    'label' => 'ZADZWOŃ DO NAS',
                    'value' => '+420 774 256 271',
                    'href' => 'tel:+420774256271',
                    'icon' => 'gfx/telefon.svg',
                    'alt' => 'Telefon',
                ],
                [
                    'label' => 'NAPISZ DO NAS',
                    'value' => 'info@motogo24.cz',
                    'href' => 'mailto:info@motogo24.cz',
                    'icon' => 'gfx/email.svg',
                    'alt' => 'E-mail',
                ],
                [
                    'label' => 'SKRZYNKA DANYCH',
                    'value' => 'iuw3vnb',
                    'href' => NULL,
                    'icon' => NULL,
                    'alt' => NULL,
                ],
            ],
            'place' => [
                'title' => 'Lokal',
                'address_label' => 'Adres:',
                'address' => 'Mezná 9, 393 01 Pelhřimov',
                'hours_label' => 'Godziny otwarcia:',
                'hours' => 'PN – ND: 00:00 – 24:00 (całodobowo)<br>W tym weekendy i święta',
                'billing_title' => 'Dane do faktury',
                'billing_name' => 'Bc. Petra Semorádová',
                'billing_address' => 'Mezná 9, 393 01 Pelhřimov',
                'billing_ico' => '21874263',
                'billing_vat' => 'Nie jestem płatnikiem VAT',
                'billing_note' => 'Firma została zarejestrowana 31.7.2024 w Urzędzie Miejskim w Pelhřimovie.',
            ],
            'social' => [
                [
                    'label' => 'facebook',
                    'href' => '#',
                    'icon' => 'gfx/facebook.svg',
                    'alt' => 'Facebook',
                ],
                [
                    'label' => 'instagram',
                    'href' => '#',
                    'icon' => 'gfx/instagram.svg',
                    'alt' => 'Instagram',
                ],
            ],
            'social_title' => 'Śledź nas',
            'map' => [
                'title' => 'Gdzie nas znaleźć',
                'src' => 'https://www.google.com/maps?q=Mezn%C3%A1+9%2C+393+01+Pelh%C5%99imov&hl=cs&z=15&output=embed',
            ],
            'seo_text' => [
                'title' => 'Kontakt – wypożyczalnia motocykli Vysočina (Pelhřimov)',
                'body' => 'Motogo24 to <strong>nowoczesna wypożyczalnia motocykli w Vysočina</strong>. Mieścimy się w <strong>Pelhřimov</strong>, jesteśmy otwarci <strong>całodobowo</strong> i wypożyczamy <strong>bez kaucji</strong>, z kompletnym <strong>wyposażeniem w cenie</strong>.',
            ],
        ],
        'jak_pujcit' => [
            'seo' => [
                'title' => 'Jak wypożyczyć motocykl | MotoGo24',
                'description' => 'Jak wypożyczyć motocykl w Motogo24. Prosty proces: wybór, rezerwacja, odbiór. Bez kaucji, wyposażenie w cenie, obsługa całodobowa.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Jak wypożyczyć motocykl',
            'intro' => 'W <strong>Motogo24 – wypożyczalni motocykli w Vysočina</strong> wypożyczanie jest proste, szybkie i uczciwe.',
            'links' => [
                [
                    'href' => '/jak-pujcit/postup',
                    'label' => 'Procedura wynajmu motocykla',
                ],
                [
                    'href' => '/jak-pujcit/prevzeti',
                    'label' => 'Odbiór w wypożyczalni',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-pujcovna',
                    'label' => 'Zwrot motocykla w wypożyczalni',
                ],
                [
                    'href' => '/jak-pujcit/vraceni-jinde',
                    'label' => 'Zwrot motocykla w innym miejscu',
                ],
                [
                    'href' => '/jak-pujcit/co-v-cene',
                    'label' => 'Co jest w cenie wynajmu',
                ],
                [
                    'href' => '/jak-pujcit/pristaveni',
                    'label' => 'Podstawienie motocykla',
                ],
                [
                    'href' => '/jak-pujcit/dokumenty',
                    'label' => 'Dokumenty i instrukcje',
                ],
                [
                    'href' => '/jak-pujcit/faq',
                    'label' => 'Najczęściej zadawane pytania',
                ],
            ],
        ],
        'jak_pujcit_postup' => [
            'seo' => [
                'title' => 'Proces wypożyczenia motocykla | MotoGo24',
                'description' => 'Proces wypożyczenia motocykla w Motogo24 krok po kroku. Rezerwacja online, wyposażenie w cenie, bez kaucji, obsługa całodobowa i dostawa.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Proces wypożyczenia motocykla',
            'intro' => '<p>W <strong>Motogo24 – wypożyczalni motocykli w Vysočina</strong> wypożyczanie jest proste, szybkie i uczciwe. <strong>Bez kaucji, z wyposażeniem w cenie i obsługą całodobową</strong>.</p>',
            'cta' => [
                'title' => 'Gotowy na jazdę?',
                'text' => 'Zarezerwuj motocykl online już dziś i ciesz się <strong>wolnością na dwóch kołach</strong>.',
                'buttons' => [
                    [
                        'label' => 'REZERWUJ ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vyzvednuti' => [
            'seo' => [
                'title' => 'Odbiór motocykla w wypożyczalni | MotoGo24',
                'description' => 'Odbiór motocykla w wypożyczalni Pelhřimov. Obsługa całodobowa, bez kaucji, wyposażenie w cenie. Co zabrać i jak przebiega odbiór.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Odbiór motocykla w wypożyczalni – szybko, łatwo i całodobowo',
            'intro' => 'W <strong>Motogo24 – wypożyczalni motocykli Vysočina</strong> <strong>odbiór motocykla</strong> trwa kilka minut.',
            'top_cta' => [
                'label' => 'REZERWUJ ONLINE',
                'href' => '/rezervace',
            ],
            'cta' => [
                'title' => 'Odbiór motocykla w wypożyczalni – Motogo24 Vysočina',
                'text' => 'Motogo24 to <strong>wypożyczalnia motocykli w Vysočina</strong> z <strong>całodobowym odbiorem i zwrotem</strong>.',
                'buttons' => [
                    [
                        'label' => 'REZERWUJ ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'jak_pujcit_vraceni_pujcovna' => [
            'seo' => [
                'title' => 'Zwrot motocykla w wypożyczalni | MotoGo24',
                'description' => 'Zwrot motocykla bezpośrednio w wypożyczalni Pelhřimov. Całodobowo, bez kaucji, bez zbędnej biurokracji.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
            ],
            'h1' => 'Zwrot motocykla w wypożyczalni',
            'intro' => 'Motocykl wracasz wygodnie bezpośrednio w <strong>Motogo24 – wypożyczalni motocykli w Vysočina</strong>. <strong>Obsługa całodobowa</strong>, bez stresu.',
            'top_cta' => [
                'label' => 'REZERWUJ ONLINE',
                'href' => '/rezervace',
            ],
            'cta' => [
                'title' => 'Zwrot motocykla w wypożyczalni – Motogo24 Pelhřimov',
                'text' => 'Wróć motocyklem bezpośrednio do nas w Pelhřimov – <strong>całodobowo, bez kaucji, bez stresu</strong>.',
                'buttons' => [
                    [
                        'label' => 'REZERWUJ ONLINE',
                        'href' => '/rezervace',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
        'poukazy' => [
            'seo' => [
                'title' => 'Wypożyczalnia motocykli Vysočina – Bony',
                'description' => 'Kup bon prezentowy na wynajem motocykla. Ważność 3 lata, bez kaucji, wyposażenie w cenie. Bon elektroniczny i drukowany.',
                'keywords' => 'wypożyczalnia motocykli Czechy',
                'og_image' => 'https://www.motogo24.cz/gfx/darkovy-poukaz.jpg',
            ],
            'h1' => 'Kup bon prezentowy – podaruj przygodę na dwóch kołach!',
            'intro_left' => '<p>Szukasz oryginalnego prezentu dla partnera, przyjaciela albo taty?</p><p>&nbsp;</p><p>Nasze <strong>bony prezentowe na wynajem motocykla</strong> od Motogo24 – <strong>wypożyczalnia motocykli Vysočina</strong> – ucieszą zarówno początkujących, jak i doświadczonych kierowców.</p><p>&nbsp;</p><p>Wybierz wartość bonu albo konkretny motocykl i podaruj wolność na dwóch kołach.</p>',
            'intro_cta' => [
                'label' => 'ZAMÓW BON PREZENTOWY',
                'href' => '/koupit-darkovy-poukaz',
                'aria' => 'Zamów bon prezentowy na wynajem motocykla w wypożyczalni Motogo24',
            ],
            'intro_image' => [
                'src' => 'gfx/darkovy-poukaz.jpg',
                'alt' => 'Bon prezentowy',
            ],
            'steps' => [
                [
                    'icon' => 'gfx/vyber-motorku.svg',
                    'title' => '1. Wybierz',
                    'text' => 'Wybierasz wartość bonu albo konkretny motocykl.',
                ],
                [
                    'icon' => 'gfx/zaplat.svg',
                    'title' => '2. Zapłać',
                    'text' => 'Płacisz online.',
                ],
                [
                    'icon' => 'gfx/potvrzeni-rezervace.svg',
                    'title' => '3. Odbierz',
                    'text' => 'Bon po opłaceniu trafia na twoją skrzynkę e-mail.',
                ],
            ],
            'validity_note' => 'Wszystkie bony są <strong>ważne 3 lata</strong> od daty wystawienia. <strong>Obdarowany sam wybiera termin wynajmu</strong>, który mu pasuje. Może się z nami skontaktować e-mailem, telefonicznie lub przez media społecznościowe.',
            'why' => [
                'title' => 'Dlaczego warto kupić bon',
                'items' => [
                    '<strong>Elastyczny wybór</strong> – wartość bonu albo konkretny motocykl.',
                    '<strong>Ważność 3 lata</strong> – obdarowany sam wybiera termin.',
                    '<strong>Bez kaucji</strong> – uczciwe warunki bez zbędnych przeszkód.',
                    '<strong>Wyposażenie w cenie</strong> – kask, kurtka, spodnie i rękawice gratis.',
                    '<strong>Obsługa całodobowa</strong> – odbiór i zwrot o dowolnej porze w dniu wynajmu.',
                    '<strong>Zamówienie online</strong> – bon po opłaceniu przychodzi e-mailem.',
                ],
            ],
            'how' => [
                'title' => 'Jak wykorzystać bon',
                'items' => [
                    '<strong>Motocykle turystyczne</strong> – weekendowy roadtrip po Vysočinie i całych Czechach.',
                    '<strong>Motocykle sportowe</strong> – adrenalinowa jazda na zakrętach.',
                    '<strong>Enduro</strong> – lekki teren i przygoda poza głównymi drogami.',
                    '<strong>Motocykle dziecięce</strong> – pierwsze przejażdżki dla małych kierowców pod nadzorem.',
                ],
            ],
            'catalog_cta' => [
                'label' => 'ZOBACZ KATALOG MOTOCYKLI',
                'href' => '/katalog',
            ],
            'faq' => [
                'title' => 'Najczęściej zadawane pytania o bony prezentowe',
                'items' => [
                    [
                        'q' => 'Jaka jest ważność bonu prezentowego?',
                        'a' => 'Wszystkie bony są ważne <strong>3 lata</strong> od daty wystawienia. Termin wynajmu obdarowany wybiera sam.',
                    ],
                    [
                        'q' => 'Jak dostarczacie bon?',
                        'a' => '<strong>Natychmiast e-mailem</strong> po opłaceniu. Na życzenie przygotujemy też wydruk prezentowy w lokalu.',
                    ],
                    [
                        'q' => 'Czy obdarowany musi wpłacać kaucję?',
                        'a' => 'Nie. <strong>Wypożyczamy bez kaucji</strong>. Warunki są jasne i uczciwe, wyposażenie kierowcy jest w cenie.',
                    ],
                    [
                        'q' => 'Czy można zmienić termin realizacji?',
                        'a' => 'Tak, <strong>termin można zmienić po uzgodnieniu</strong> w zależności od dostępności danego motocykla w naszym kalendarzu.',
                    ],
                    [
                        'q' => 'Na jakie motocykle można zrealizować bon?',
                        'a' => 'Na <strong>motocykle turystyczne, sportowe, enduro i dziecięce</strong> z oferty Motogo24 – zależnie od wybranej wartości bonu.',
                    ],
                ],
            ],
            'cta' => [
                'title' => 'Bon prezentowy na wynajem motocykla – Vysočina',
                'text' => 'Motogo24 to <strong>wypożyczalnia motocykli w Vysočina</strong> z <strong>obsługą całodobową</strong>, <strong>bez kaucji</strong> i <strong>wyposażeniem w cenie</strong>.',
                'buttons' => [
                    [
                        'label' => 'ZAMÓW BON',
                        'href' => '/koupit-darkovy-poukaz',
                        'cls' => 'btndark pulse',
                    ],
                ],
            ],
        ],
    ],
];
