workflows:
  motogo-android:
    name: MotoGo24 Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/motogo-app-flutter
          flutter pub get
      - name: Build APK (debug)
        script: |
          cd $CM_BUILD_DIR/motogo-app-flutter
          flutter build apk --debug
    artifacts:
      - motogo-app-flutter/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mnastrojarna@gmail.com
        notify:
          success: true
          failure: true
