@echo off
chcp 65001 >nul 2>&1
echo.
echo ========================================================
echo   MotoGo24 - Upload na VSECHNY 7 domen
echo   .cz Forpsi + .com .es .pl .at .fr .nl Hosting90
echo ========================================================
echo.

set "PS=%TEMP%\motogo-all7-upload.ps1"

echo $Slozka = 'C:\Users\HP Z2\Desktop\Vel-n-main\motogo-web-php' > "%PS%"
echo. >> "%PS%"
echo # Definice domen >> "%PS%"
echo $domeny = @( >> "%PS%"
echo     @{ Nazev='motogo24.com'; Jazyk='EN'; Server='ftp://130.193.9.44';   User='mainftp123192'; Pass='heslo666';        Root='/motogo24.com' }, >> "%PS%"
echo     @{ Nazev='motogo24.es';  Jazyk='ES'; Server='ftp://130.193.9.44';   User='mainftp123228'; Pass='heslo666';        Root='/motogo24.es' }, >> "%PS%"
echo     @{ Nazev='motogo24.pl';  Jazyk='PL'; Server='ftp://130.193.9.44';   User='mainftp123234'; Pass='heslo666';        Root='/motogo24.pl' }, >> "%PS%"
echo     @{ Nazev='motogo24.at';  Jazyk='DE'; Server='ftp://130.193.9.44';   User='mainftp123231'; Pass='heslo666';        Root='/motogo24.at' }, >> "%PS%"
echo     @{ Nazev='motogo24.fr';  Jazyk='FR'; Server='ftp://130.193.9.44';   User='mainftp123252'; Pass='heslo666';        Root='/motogo24.fr' }, >> "%PS%"
echo     @{ Nazev='motogo24.nl';  Jazyk='NL'; Server='ftp://130.193.9.44';   User='mainftp123249'; Pass='heslo666';        Root='/motogo24.nl' }, >> "%PS%"
echo     @{ Nazev='motogo24.cz';  Jazyk='CS'; Server='ftp://ftpx.forpsi.com'; User='www.motogo24.cz'; Pass='va.a2n8y.9iCZFn'; Root='/www' } >> "%PS%"
echo ) >> "%PS%"
echo. >> "%PS%"
echo Write-Host '' >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo Write-Host '  MotoGo24 - Upload na 7 domen' -Fore Yellow >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo Write-Host "  Zdroj: $Slozka" -Fore Cyan >> "%PS%"
echo Write-Host '' >> "%PS%"
echo. >> "%PS%"
echo if (-not (Test-Path $Slozka)) { >> "%PS%"
echo     Write-Host "  CHYBA: Slozka $Slozka neexistuje!" -Fore Red >> "%PS%"
echo     Read-Host '  Stiskni Enter' >> "%PS%"
echo     exit >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo $htaccessPath = Join-Path $Slozka '.htaccess' >> "%PS%"
echo if (-not (Test-Path $htaccessPath)) { >> "%PS%"
echo     Write-Host "  VAROVANI: .htaccess nenalezen ve zdrojove slozce!" -Fore Yellow >> "%PS%"
echo     Write-Host "  Cesta: $htaccessPath" -Fore Yellow >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo } else { >> "%PS%"
echo     Write-Host "  .htaccess nalezen ve zdrojove slozce - bude se nahravat z gitu" -Fore Green >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo function New-FtpDir { >> "%PS%"
echo     param($srv, $ftpPath, $cred) >> "%PS%"
echo     try { >> "%PS%"
echo         $uri = $srv + $ftpPath >> "%PS%"
echo         $r = [System.Net.FtpWebRequest]::Create($uri) >> "%PS%"
echo         $r.Method = [System.Net.WebRequestMethods+Ftp]::MakeDirectory >> "%PS%"
echo         $r.Credentials = $cred >> "%PS%"
echo         $r.UseBinary = $true; $r.UsePassive = $true >> "%PS%"
echo         $resp = $r.GetResponse(); $resp.Close() >> "%PS%"
echo     } catch {} >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo function Send-FtpFile { >> "%PS%"
echo     param($srv, $localFile, $ftpPath, $cred) >> "%PS%"
echo     try { >> "%PS%"
echo         $uri = $srv + $ftpPath >> "%PS%"
echo         $r = [System.Net.FtpWebRequest]::Create($uri) >> "%PS%"
echo         $r.Method = [System.Net.WebRequestMethods+Ftp]::UploadFile >> "%PS%"
echo         $r.Credentials = $cred >> "%PS%"
echo         $r.UseBinary = $true; $r.UsePassive = $true >> "%PS%"
echo         $data = [System.IO.File]::ReadAllBytes($localFile) >> "%PS%"
echo         $r.ContentLength = $data.Length >> "%PS%"
echo         $s = $r.GetRequestStream(); $s.Write($data, 0, $data.Length); $s.Close() >> "%PS%"
echo         $resp = $r.GetResponse(); $resp.Close() >> "%PS%"
echo         return $true >> "%PS%"
echo     } catch { return $false } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo $soubory = Get-ChildItem -Path $Slozka -Recurse -File -Force >> "%PS%"
echo $celkem = $soubory.Count >> "%PS%"
echo $celkoveChyby = 0 >> "%PS%"
echo. >> "%PS%"
echo foreach ($d in $domeny) { >> "%PS%"
echo     $cred = New-Object System.Net.NetworkCredential($d.User, $d.Pass) >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     Write-Host "  ================================================" -Fore Yellow >> "%PS%"
echo     Write-Host "  $($d.Nazev) [$($d.Jazyk)] - $($d.Server)" -Fore Green >> "%PS%"
echo     Write-Host "  ================================================" -Fore Yellow >> "%PS%"
echo. >> "%PS%"
echo     $ok = 0 >> "%PS%"
echo     $chyby = 0 >> "%PS%"
echo. >> "%PS%"
echo     foreach ($soubor in $soubory) { >> "%PS%"
echo         $rel = $soubor.FullName.Substring($Slozka.Length).Replace('\','/') >> "%PS%"
echo         $ftpCesta = $d.Root + $rel >> "%PS%"
echo         $ftpDir = $ftpCesta.Substring(0, $ftpCesta.LastIndexOf('/')) >> "%PS%"
echo         if ($ftpDir -ne $d.Root) { >> "%PS%"
echo             $parts = $ftpDir.Substring($d.Root.Length).Split('/', [StringSplitOptions]::RemoveEmptyEntries) >> "%PS%"
echo             $cur = $d.Root >> "%PS%"
echo             foreach ($p in $parts) { >> "%PS%"
echo                 $cur = "$cur/$p" >> "%PS%"
echo                 New-FtpDir $d.Server $cur $cred >> "%PS%"
echo             } >> "%PS%"
echo         } >> "%PS%"
echo         $ok++ >> "%PS%"
echo         $pct = [math]::Round(($ok / $celkem) * 100) >> "%PS%"
echo         Write-Host "  [$ok/$celkem] ($pct%%) $rel " -NoNewline >> "%PS%"
echo         $result = Send-FtpFile $d.Server $soubor.FullName $ftpCesta $cred >> "%PS%"
echo         if ($result) { Write-Host 'OK' -Fore Green } >> "%PS%"
echo         else { Write-Host 'CHYBA' -Fore Red; $chyby++ } >> "%PS%"
echo     } >> "%PS%"
echo. >> "%PS%"
echo     Write-Host '' >> "%PS%"
echo     if ($chyby -eq 0) { >> "%PS%"
echo         Write-Host "  $($d.Nazev): $celkem/$celkem OK" -Fore Green >> "%PS%"
echo     } else { >> "%PS%"
echo         Write-Host "  $($d.Nazev): $($ok - $chyby)/$celkem OK, $chyby chyb" -Fore Red >> "%PS%"
echo         $celkoveChyby += $chyby >> "%PS%"
echo     } >> "%PS%"
echo } >> "%PS%"
echo. >> "%PS%"
echo Write-Host '' >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo if ($celkoveChyby -eq 0) { >> "%PS%"
echo     Write-Host '  VSECHNY 7 DOMEN NAHRANE USPESNE!' -Fore Green >> "%PS%"
echo } else { >> "%PS%"
echo     Write-Host "  HOTOVO s $celkoveChyby chybami celkem" -Fore Red >> "%PS%"
echo } >> "%PS%"
echo Write-Host '  ========================================================' -Fore Yellow >> "%PS%"
echo Write-Host '  https://motogo24.cz   (CS) - Forpsi' -Fore Cyan >> "%PS%"
echo Write-Host '  https://motogo24.com  (EN) - Hosting90' -Fore Cyan >> "%PS%"
echo Write-Host '  https://motogo24.es   (ES) - Hosting90' -Fore Cyan >> "%PS%"
echo Write-Host '  https://motogo24.pl   (PL) - Hosting90' -Fore Cyan >> "%PS%"
echo Write-Host '  https://motogo24.at   (DE) - Hosting90' -Fore Cyan >> "%PS%"
echo Write-Host '  https://motogo24.fr   (FR) - Hosting90' -Fore Cyan >> "%PS%"
echo Write-Host '  https://motogo24.nl   (NL) - Hosting90' -Fore Cyan >> "%PS%"
echo Write-Host '' >> "%PS%"

powershell -ExecutionPolicy Bypass -File "%PS%"

echo.
pause
