<?php
// PL překlady recenzí (data/reviews.php, klíč = id recenze) — landing v2, renderLpReviews().
// Přeloženo z českých originálů (věrně, bez přikrášlení; „…“ = text na zdroji zkrácený).
// Recenze s 'lang' => 'en' se nepřekládá. Struktura = lang/v2/es/reviews.php.
return ['pages' => ['landing' => ['common' => [
    'reviews_tr' => [
        'karel-s-google' => 'Super, wypożyczyłem RVM 500 na 1 dzień, wszystko odbyło się online, bez kaucji, motocykl był rano gotowy, wieczorem go oddałem, bez limitu kilometrów i super kontakt z właścicielem ;) Polecam',
        'libor-j-google' => 'Wyjątkowe usługi wśród wypożyczalni motocykli, nie jesteśmy motocyklistami, nie mamy sprzętu. Zamówiliśmy motocykl w aplikacji, przyjechaliśmy, motocykl był gotowy, …',
        'jirka-s-google' => 'Plusy: elastyczność czasowa, przyjazne podejście, świetnie przygotowana maszyna, bez konieczności wpłacania kaucji, aplikacja mobilna …',
        'zdenek-r-google' => 'Bardzo polecam, wypożyczyłem z polecenia Triumph Tiger 1200 Explorer, szybki i wygodny proces rezerwacji, płatności i odbioru motocykla, a przy zwrocie ucieszyła mnie świetna kawa :-)',
        'lenka-g-google' => 'Wspaniałe ludzkie podejście! Jeśli myślicie o wypożyczeniu motocykla na próbę dla dziecka, nie popełnicie tu błędu. Miła i przyjazna obsługa przez cały czas. Zdecydowanie polecam 🙂',
        'jaroslav-j-google' => 'Jednym słowem NIESAMOWITE. Gorąco polecam. Po latach dostałem okazję wrócić do młodości, kiedy jeździłem całkiem sporo. Bezbłędna obsługa od zamówienia motocykla, przez wypożyczenie razem z wyposażeniem, aż po zwrot. Właściciele życzliwi i pomocni. 👍',
        'laza-google' => 'Świetne doświadczenie z wypożyczeniem, motocykl miałem na 2 dni, także z przyczepką. Motocykle są zadbane, obsługa bardzo miła i pomocna. Pan, który przekazywał mi motocykl, pomógł mi go nawet załadować i zabezpieczyć. Jak dla mnie świetne doświadczenie i z pewnością mogę tylko polecić.',
        'romana-k-google' => 'Dziękujemy za fajną wycieczkę. Mieliśmy z mężem wypożyczone BMW GS 1200, a ja całe wyposażenie na motocykl. Świetna obsługa, dobry kontakt, przyjemne otoczenie. Bardzo polecamy i jeszcze kiedyś wrócimy :-).',
        'daniel-h-google' => 'Absolutny motocyklowy raj – polecam na sto procent! Szukałem niezawodnej wypożyczalni na wycieczkę i ten wybór był strzałem w dziesiątkę. Od pierwszego kontaktu aż po zwrot maszyny zupełnie bezbłędne doświadczenie.',
        'martin-k-google' => 'Prosta rezerwacja, niska cena, piękna okolica na przejażdżkę. Szybkie przekazanie i pomocny personel.',
        'zdenek-firmy' => 'Perfekcyjna wypożyczalnia! Super podejście, żadnej kaucji, nie musicie martwić się myciem motocykla, a wyposażenie pożyczą wam za darmo. Szybko, uczciwie i bez zmartwień. Nie ma się do czego przyczepić.',
        'petr-c-firmy' => 'Świetne doświadczenie. Doceniam przede wszystkim przyjazne i pomocne podejście, wszystko przebiegło zupełnie bez problemów. Motocykl był gotowy o umówionej godzinie, do tego z pełnym bakiem, więc mogłem od razu ruszać. Przekazanie było szybkie i bez zbędnego przeciągania, podobnie jak zwrot, który był możliwy o każdej porze, nawet w nocy. Dużym plusem było też to, że przed zwrotem nie trzeba było dotankować – człowiek nie musi sobie zawracać głowy zbędnymi zmartwieniami.',
        'marian-l-fb' => '… Wszystko łatwo załatwiłem przez aplikację, ceny i warunki wypożyczenia najlepsze ze wszystkich, jakie znalazłem. Po przyjściu do wypożyczalni przywitała mnie sympatyczna i bardzo miła pani właścicielka. Ze wszystkim mnie zapoznała, chętnie odpowiedziała na moje pytania (sprawy techn.…). Motocykl i akcesoria były już przygotowane. Zwrot maszyny do wypożyczalni również przebiegł zupełnie w porządku. … Duże zadowolenie z podejścia, a także z motocykla.',
        'martin-o-firmy' => 'Perfekcyjna wypożyczalnia motocykli – łatwe zamówienie, dobre ceny, szybkie i łatwe przekazanie + bonus w postaci świetnych dróg w okolicy.',
        'strdyna-firmy' => 'Pierwszy raz zdecydowałem się wypożyczyć motocykl turystyczny dla większej wygody we dwoje i jestem w pełni zadowolony! … Motocykl (Benelli TRK 502 X) czekał w dobrym stanie technicznym, umyty, z pełnym bakiem, gotowy do jazdy, tuż obok zaparkowałem auto, które mogło zostać na ogrodzonym parkingu przez weekend. Świetne podejście pani właścicielki i zwrot bez problemu, nawet z propozycją kawy na drogę do domu.',
        'hancl-firmy' => 'Motocykl był przygotowany na umówioną godzinę. Cała komunikacja od początku działała na 100%. … Przy przekazaniu maszyny pani właścicielka wszystko wyjaśniła. … Co jeszcze doceniam: gdy pojawi się jakikolwiek problem, wystarczy zadzwonić. Świetne wsparcie techniczne. … Bardzo mi się podobało, że maszynę możecie oddać wieczorem. Ładnie i przejrzyście zrobiona strona i aplikacja. Polecam tę wypożyczalnię 10/10.',
        'jan-r-fb' => 'To po prostu wspaniała firma i ekipa ludzi, którzy kochają motocykle. Mogę wszystkim tylko polecić. Świetnie się bawiłem. Szeroki wybór motocykli i odzieży, którą spokojnie przymierzycie. Miłe i życzliwe podejście. Po prostu bomba. Bardzo dziękuję.',
        'dejv-m-firmy' => '… Kiedy przyjechałem po motocykl, wszystko było już przygotowane, zaproponowano mi kawę i wszystko wyjaśniono. Motocykl był przygotowany w doskonałym stanie technicznym, czysty i z praktycznie pełnym bakiem. Zwrot przebiegł również gładko i całkowicie profesjonalnie. Od komunikacji, przez rezerwację, po realizację. Dokumenty przyszły z odpowiednim wyprzedzeniem, więc nie ma żadnego zbędnego przeciągania. …',
        'pavel-s-fb' => 'Wypożyczyliśmy dwa skutery, oba nowe i w super stanie. Obsługa na piątkę, a do tego są sympatyczni i zupełnie wyluzowani. Dziękujemy i polecamy.',
        'jan-m-firmy' => 'Normalnie nie piszę recenzji, ale na tę muszę znaleźć czas... Ponadstandardowe podejście, które nie ma sobie równych. Bardzo pomocna i miła pani. Świetna strona internetowa, aplikacja i system rezerwacji. …',
    ],
]]]];
