// Znalostní báze 2/2: Web motogo24.cz + mobilní aplikace + integrace + architektura
// Slouží nástroji get_system_guide. Udržovat v souladu s motogo-web-php, Motogo-app-main a CLAUDE.md.

export const KNOWLEDGE_APPS: Record<string, string> = {

  'web-rezervace': `WEB motogo24.cz — REZERVAČNÍ FLOW (/rezervace, 7 jazyků cs/en/de/es/fr/nl/pl, anonymní bez registrace):
KROK 1: výběr stroje (katalog s filtrem ŘP, dynamický ceník per den, sort_order) + termín + čas vyzvednutí/vrácení (pozdní vyzvednutí ≥12:00 u 2+ dnů = sleva 50 % na 1. den) → create_web_booking (kontrola překryvů, „1 e-mail = max 1 rezervace na den").
KROK 2: přehled + výbava (velikosti dle skladu pobočky, vozík 400 Kč/den, spolujezdec) + doprava (vyzvednutí na pobočce/přistavení s GPS) + slevy (promo kód/voucher/dárkový poukaz — max 1 procentní) + VOLBA PLATBY: karta (Stripe Checkout) NEBO QR/převod (VS ze sekvence, ZF mailem, splatnost 4 h, ruční potvrzení ve Velíně). Zákazník může přepnout metodu (zpět z brány).
KROK 3 (PO platbě — flow „platba před doklady" od 6.7.2026): doklady — povinná ČÍSLA dokladů (OP/pas + ŘP), scan nepovinný (Mindee OCR ověření), heslo k účtu (poslední 4 znaky slouží AI agentovi jako 3. faktor). Resume: /rezervace?resume=<id> (i cross-device PC→mobil přes QR).
MAILY: web_booking_reserved (smlouva+VOP po dokladech), invoice_payment_receipt (DP+ZF po platbě), abandoned po 15 min, missing_docs po 30 min, booking_qr_payment (QR pokyny). Nezaplacená web rezervace se ruší po 4 h.`,

  'web-ostatni': `WEB — DALŠÍ ČÁSTI: Katalog (/katalog + detail: specifikace, videa, galerie, ceník, recenze, dostupnost) · E-shop (/shop: produkty s velikostmi, checkout pickup 0/pošta 99 Kč, Stripe) · Dárkové poukazy (/poukazy: objednávka s fakturačními údaji, PDF poukaz mailem) · Trasy a body zájmu (výpis z DB) · Blog · FAQ (DB-driven) · Dokumenty (/jak-pujcit/dokumenty: smluvní dokumenty + custom /dokumenty/<slug>) · Úprava rezervace (/upravit-rezervaci: přihlášení, změna termínu/motorky/výbavy s přepočtem a refundem) · AI ASISTENT (widget vpravo dole, edge ai-public-agent: poradí, spočítá cenu, VYTVOŘÍ rezervaci [created_via_ai=🤖 badge], najde/upraví rezervaci po ověření; konverzace se logují do ai_public_conversations) · Návštěvnost se loguje cookieless (visitor_log) · REST API pro partnery (api_keys) + AI crawler tracking (ai_traffic_log).`,

  'app-funkce': `MOBILNÍ APLIKACE MotoGo24 (Flutter, Android=master + iOS kopie, 7 jazyků):
REZERVACE: katalog → detail (fotky, videa, specifikace) → booking formulář (core/booking_form_widget.dart, sekce 1–6: termín, výbava, doprava, slevy, souhrn) → platba kartou (Stripe: Google Pay/Apple Pay, uložené karty) → smlouva mailem. Úpravy/prodloužení/storno přímo v appce.
VĚRNOST: ranky 1–20 (Startér→Legenda MotoGo, sleva 1–20 % JEN na app rezervace), barevný ring MG loga dle ranku, žebříček (přezdívka, opt-in), měsíční výherci, bonusové body.
TRASY: doporučené vyjížďky od pobočky (mapa, POI s čísly po směru jízdy, navigace), katalog zajímavých míst (kategorie), komunitní obsah (návrh trasy přes Mapy.com link, vlastní body zájmu — moderuje Velín), recenze tras (hvězdy+fotky), MOJE ZÁŽITKY: uložené vlastní trasy + automaticky „objevená místa" (dojezd ≤200 m).
SOS: nouzová tlačítka (nehoda/porucha/krádež/sdílení polohy) → fotky, GPS, nejbližší servis → Velín řeší, náhradní motorka.
SAMOOBSLUHA: kód ke dveřím boxu, elektronický předávací protokol (stav km, fotky, podpis; 1h okno, po hodině auto-fill), škodní protokol.
DALŠÍ: skenování dokladů (OCR ověření), push notifikace (FCM), profil (doklady, souhlasy, karty), e-shop, poukazy, offline guard, kontrola aktualizací. Instalace se evidují (app_installations → DAU/WAU/MAU).`,

  'app-pravidla': `APPKA — PLATFORMNÍ PRAVIDLA (pro vývoj): dva stromy motogo-app-flutter (Android MASTER) a motogo-app-flutter-ios — každou změnu sdíleného kódu dělat v OBOU (diff -rq lib/), záměrné rozdíly: main.dart, onboarding_overlays (App Store 5.1.1), update_check_provider (store URL), offline_guard, payment_methods_screen (iOS bez ručního zadání karty), card_payment_sheet (Apple vs Google Pay), payment_error_mapper, translations hlavní soubory. iOS pinuje STARŠÍ balíčky (connectivity_plus 5, flutter_stripe 11, firebase 15/3.x...) — porty z Androidu musí používat kompatibilní API. Build: Codemagic. Rezervační formulář je JEN core/booking_form_widget.dart.`,

  'integrace': `INTEGRACE A SLUŽBY: Stripe (platby web+app, refundy, uložené karty, webhook-receiver → DP/doklady; Apple Pay/Google Pay v appce) · Resend (e-maily z noreply@motogo24.cz, šablony v DB, logy sent_emails) · FCM (push, tokeny push_tokens) · Mindee OCR (ověření dokladů: OP/pas/ŘP → verified_at/until) · OCR faktur (receive-invoice → financial_events, dodavatelé, sklad) · Abra Flexi (účetní export flexi-sync, výkazy flexi_reports) · Mapy.com (routing tras, share linky) · Slevomat Partner API (auto-uplatnění voucherů) · Anthropic Claude (AI copilot Velín, ai-public-agent web widget, ai-moto-agent appka, návrhy odpovědí na zprávy, auto-překlady translate-content/translate-document do 7 jazyků) · Twilio/WhatsApp+SMS (message_log).`,

  'architektura': `ARCHITEKTURA A NASAZENÍ: Monorepo — velin/ (React 18+Vite+Tailwind, superadmin dashboard, deploy Vercel při push do main) · motogo-web-php (veřejný web) · Motogo-app-main/motogo-app-flutter[-ios] (mobilní appky, Codemagic) · supabase/ (Edge Functions + SQL migrace; projekt vnwnqteskbykeucanlhk) · doc-scanner/ (Capacitor vstup účetních dokladů). AUTODEPLOY: merge do main = živé nasazení — edge funkce přes deploy-functions.yml, SQL migrace přes deploy-sql.yml (evidence _git_migrations, chybná migrace blokuje další → issue s labelem sql-deploy-failed), denní šifrovaná záloha 6:00. Dokumentace backendu: SUPABASE_BACKEND_STATE_1..6.md (tabulky/sloupce/RPC/triggery/RLS/changelog).`,

  'domena-pojmy': `DOMÉNOVÝ SLOVNÍK: ZF=zálohová faktura (výzva k platbě, advance/proforma) · DP=daňový doklad o přijaté platbě (payment_receipt) · KF=konečná faktura (final; odečítá DP záporným řádkem) · dobropis=credit_note (záporný total, refundy) · realizovaná rezervace=zaplacená (paid/partial_refund/refund_pending/refunded)+nestornovaná+netestovací → JEDINÁ správná definice obratu · is_test/is_test_account=testovací data z AI tréninku, VŽDY vyřadit z čísel · booking_source=web/app · created_via_ai=rezervaci vytvořil AI widget · door codes=kódy ke dveřím samoobslužné pobočky per rezervace · handover protokol=elektronické předání (stav km→mileage_start) · gear shortage=deficit výbavy na pobočce · SKU konvence=kategorie-typ-varianta (prislusenstvi-boots-43) · storno tabulka=refund ≥7 dní 100 %/2–7 dní 50 %/<2 dny 0 % · věrnostní rank=1–20, sleva jen app · VS=variabilní symbol (číselný, sekvence booking_vs_seq).`,
}
