// Znalostní báze 1/2: Velín (superadmin dashboard) — encyklopedie sekcí + provozní návody
// Slouží nástroji get_system_guide. Udržovat v souladu s velin/src (Sidebar, App.jsx) a SUPABASE_BACKEND_STATE_*.

export const KNOWLEDGE_VELIN: Record<string, string> = {

  'velin-navigace': `VELÍN — NAVIGACE (levý sidebar, cesty pro [NAV:...]):
⚡ / (Velín=Dashboard: KPI dlaždice, dnešní rezervace, nízké zásoby, AI widget) · 🏍️ /flotila (+ /flotila/:id detail) · 📅 /rezervace (+ /rezervace/:id) · 👥 /zakaznici (+ /zakaznici/:id) · 💰 /finance · 📄 /dokumenty · 🏢 /pobocky · 📦 /logistika (Logistika zboží, badge deficitů) · 🛣️ /trasy · 🔧 /servis · 💬 /zpravy (badge nepřečtených) · 🌐 /cms (Texty webu) · 🧠 /analyza · 🏷️ /slevove-kody · 🛒 /e-shop · 🏛️ /statni-sprava · 🤖 /ai-copilot · 👔 /orchestrator (AI Ředitel) · 🚨 /sos (badge otevřených) · 👷 /zamestnanci.
Plovoucí AI panel: Ctrl+K kdekoli (kromě /ai-copilot). Role adminů: superadmin/manager/operator/viewer (admin_users.role, branch_access, permissions).`,

  'velin-flotila': `FLOTILA (/flotila): seznam motorek (filtr stav/pobočka/kategorie, řazení vč. ručního sort_order #N). Detail (/flotila/:id): specifikace (výkon, objem, ŘP skupiny license_groups multi-select — 'N'=dětská výlučná), ceny per den (price_mon..sun), kauce, servisní intervaly (olej/pneu/komplet, km i dny, tracking_unit km/mh), stav (active/maintenance/unavailable+důvod+do kdy/retired), box_number (samoobslužná pobočka), vozík (is_trailer → gear add-on „Vozík"), fotogalerie+videa MP4+SEO alty, auto-překlady (translate-content, 7 jazyků), STK, pořizovací cena/nájezd. Korekce nájezdu: tlačítko „Korigovat" (RPC correct_motorcycle_mileage, nikdy pod purchase_mileage; nájezd jinak roste sám z protokolů a servisů přes GREATEST). Výměna motorky zákazníkovi: SwapModal (Model A switch přes swap_handoff_bookings) nebo split (Model B split_booking_moto_swap).`,

  'velin-rezervace': `REZERVACE (/rezervace): seznam s filtry (stav: pending/reserved/active/completed/cancelled; platba: unpaid/paid/refund_pending/partial_refund/refunded; zdroj web/app; 🤖 badge=created_via_ai). Detail (/rezervace/:id): termín+časy, motorka, zákazník, výbava (velikosti rider+passenger), doprava (pickup/return method+adresa+GPS), platba (Stripe PI/refund odkaz, karta brand+last4, ruční potvrzení PaymentConfirmModal → confirm_payment s VS/č.transakce), slevy (booking_discounts: promo+voucher+loyalty+late-pickup), dokumenty (smlouva, ZF/DP/KF, dobropis), door codes, protokoly (předávací handover_protocol_*, škodní), úpravy (BookingModifyModal — přepočet ceny Varianta B; u zaplacené s doplatkem → QR mail booking_qr_payment_surcharge, potvrzení „Potvrdit doplatek" → confirm_booking_surcharge), storno (cancel_booking_tracked → refund tabulka 7+dní=100 %, 2-7=50 %, <2=0 % + dobropis + mail), badge „QR/PŘEVOD — ČEKÁ · VS" a „DOPLATEK — ČEKÁ". Funnel časy: doba vyplnění/do zaplacení, zařízení PC→Mobil.`,

  'velin-zakaznici': `ZÁKAZNÍCI (/zakaznici): seznam+hledání. Detail: profil (kontakty, adresa, ŘP skupiny, doklady — čísla+ověření Mindee OCR: id/license/passport verified_at+until), souhlasy (9× consent, marketing opt-in od 2026-07, „Neznámé"=NULL), oprávnění appky (app_permissions), spolehlivost (reliability_score), blokace (is_blocked+důvod), věrnost (rank, přezdívka, bonus body, leaderboard opt-in), rezervace, recenze, dokumenty, platební karty (Stripe), reklamace. Score widget: skóre z rezervací/hodnocení/reklamací.`,

  'velin-finance': `FINANCE (/finance) — 10 záložek: Přehled (tržby dle sumInvoiceRevenue: DP+KF+shop_final−dobropisy, bez dvojího počítání e-shopu, bez testů/storen; nezaplacené=zálohovky bez DP) · Faktury (vydané, typy: advance/proforma=ZF výzva, payment_receipt=DP doklad o platbě, final=KF konečná, shop_proforma/shop_final, credit_note=dobropis; status se NEmění na paid — zaplacení poznáš dle TYPU dokladu) · Dobropisy · Dodací listy (AI párování s fakturami) · Smlouvy · Účetnictví (podzáložky: účetní záznamy accounting_entries [type income/expense + POVINNÁ category], pokladna, majetek DM/KM, odpisy, závazky [status+paid_amount], DPH přiznání, daňová přiznání, výkazy Flexi) · Faktury přijaté (OCR příjem receive-invoice, dodavatelé auto-upsert) · Platby · Pokladna · Sklad. Finanční události (financial_events): centrální pipeline revenue/expense/asset/payroll → validace → schválení (approval_queue) → export Abra Flexi (flexi-sync); výjimky v accounting_exceptions.`,

  'velin-dokumenty': `DOKUMENTY (/dokumenty): šablony dokumentů (5 smluvních typů + vlastní custom_documents s publikací na web /dokumenty/<slug>, verze, HTML editor, auto-překlad translate-document), vygenerované PDF, nahrané doklady zákazníků, zaslané maily (sent_emails s náhledem příloh přes signed URL), e-mailové šablony (email_templates, editovatelné, placeholdery {{...}}, attachments řídí přílohy send-booking-email). Číselné řady: atomicky next_document_number (document_number_counters).`,

  'velin-pobocky': `POBOČKY (/pobocky): karta pobočky (branch_code 6 číslic, is_open nonstop toggle, typ), motorky na pobočce, příslušenství (branch_accessories typ+velikost+počet, propojeno se skladem přes SKU prislusenstvi-{typ}-{velikost}, „Spravovat typy"=accessory_types vč. cen), door codes per rezervace. Samoobslužná pobočka (kiosk): konfigurace (hudba, časy dveří/světla, FV endpoint), zařízení-tablety (párování device_token, online<70 s), mapování dveří na Shelly relé, servisní kódy, kamery, stav FV elektrárny (battery SOC, PV výkon), vzdálené příkazy (otevřít dveře/hudba/identify/reload), audit otevření (branch_door_events).`,

  'velin-logistika': `LOGISTIKA ZBOŽÍ (/logistika): fronta deficitů výbavy (gear_shortages — trigger z rezervací hlídá boty/helmy/rukavice/kalhoty/bundy per pobočka+velikost+datum; stavy open→warehouse_filled/transfer_requested/order_created→resolved/dismissed; badge v sidebaru) + Naskladnění (stock_receipts: párování DL⇄faktura, kontrola duplicit dle č.dokladu+datum, „chybí DL" u faktur bez dodacího listu; DL=jen sklad, faktura=finance i sklad, proforma se neeviduje).`,

  'velin-trasy': `TRASY (/trasy): doporučené motovyjížďky per pobočka (okruh/za body zájmu, km, min, obtížnost, waypoints, POI podél trasy s pořadím po směru jízdy, mapy.com link, fotky, auto-překlady). Moderace: návrhy tras od uživatelů z appky (status pending → schválit/zamítnout), komunitní body (user_pois pending), recenze tras (hvězdy+text+fotky, skrýt nevhodné). Katalog samostatných bodů zájmu (points_of_interest, kategorie food/castle/lookout/water/sights/nature/military/aviation/tech/moto).`,

  'velin-servis': `SERVIS (/servis): blížící se servisy (dle intervalů km/dny z motorky + analytics_service_plan projekce due date z průměrného denního nájezdu), servisní objednávky (pending/in_service/completed), log údržby (maintenance_log: typ, km, technik z zaměstnanců, hodiny práce, náklady, díly ze skladu service_parts), plány údržby (maintenance_schedules). Dokončený servis auto-bumpne nájezd motorky a last_service_date.`,

  'velin-zpravy': `ZPRÁVY (/zpravy): vlákna se zákazníky (SMS/WhatsApp/email), AI návrhy odpovědí (ai-customer-messages-suggest: confidence low/medium/high, admin schválí/upraví/zamítne, auto-send dle nastavení), šablony rychlých odpovědí, hromadné kampaně (broadcast_campaigns: segment+šablona+plánování, edge send-broadcast), centrální log odeslaného (message_log). In-app zprávy zákazníkům (admin_messages → FCM push).`,

  'velin-cms': `TEXTY WEBU (/cms): CMS stránky (blog s wizardem+SEO alty), proměnné (cms_variables, kategorie general/web/pricing/contact/content/legal, inline edit z webu přes cms-save), FAQ (kategorie, featured na home, publikace), recenze zákazníků (moderace visible), feature flagy, app_settings (key-value jsonb). Vše s auto-překlady do 7 jazyků (translate-content).`,

  'velin-analyza': `ANALÝZA (/analyza) — 15 záložek: Výkon poboček · Výkon motorek (tržby/vytížení/ranking) · Nájezd km (z protokolů, RPC analytics_moto_km/customer_km) · Poptávka kategorií · Optimální flotila (model FLEET_CALC) · Doporučení přesunů · Doporučení lokací · Zákazníci (segmentace VIP/Regular/Occasional, top, města, ŘP) · Web funnel (kroky create→gateway→paid→doklady, zařízení, časy; flow „platba před doklady" od 6.7.2026) · App funnel (instalace→registrace→rezervace) · Návštěvnost (visitor_log RPC get_visitor_stats: zdroje/země/zařízení/hodiny/heatmapa; cookieless GDPR) · Aplikace (get_app_install_stats: DAU/WAU/MAU, push) · AI traffic (crawleři/REST/MCP/widget + citace „kde nás zmínila AI") · AI konverzace (web widget ai_public_conversations + appka ai_customer_conversations) · Statistiky. Definice obratu: zaplacené+nestornované+netestovací rezervace (payment_status ∈ paid/partial_refund/refund_pending/refunded) — NE jen completed!`,

  'velin-slevy-eshop': `SLEVOVÉ KÓDY (/slevove-kody): promo kódy (percent/fixed, platnost, max použití, min objednávka, zdroj slevomat/eshop/spoluprace/vraceni/ostatni) + vouchery (dárkové poukazy: aktivní/uplatněné/expirované, zdroj, vazba na e-shop objednávku) + záložka Slevomat (auto-uplatnění přes Partner API: stavy applied/failed/invalid..., retry). Pravidlo: max JEDNA procentní sleva na rezervaci (booking_discounts). E-SHOP (/e-shop): objednávky (new→confirmed→processing→shipped→delivered; vratky/refundy), produkty (velikosti+sklad per velikost size_stock, fotky+alty, překlady), nákupní objednávky dodavatelům (purchase_orders, auto-pravidla při nízké zásobě).`,

  'velin-ostatni': `STÁTNÍ SPRÁVA (/statni-sprava): STK termíny flotily (expirace 30/60/90 dní), pojistky, daňové povinnosti (DPH kvartální, DPPO, kontrolní hlášení, silniční daň), výkazy z Abra Flexi + odeslání datovkou. SOS PANEL (/sos): incidenty (nehoda/krádež/porucha/sdílení polohy; severity; timeline akcí; náhradní motorka sos_swap_bookings; odtah; vina zákazníka; napojení na servis). ZAMĚSTNANCI (/zamestnanci): karty (mzda, sazba, dovolená), docházka (emp_attendance), dovolené (schvalování), směny (plánování per pobočka), dokumenty (smlouvy DPP/DPČ...), výplatní pásky (acc_payrolls: SP/ZP, záloha daně, čistá). AI ŘEDITEL (/orchestrator): denní briefing, KPI monitoring, prioritní fronta, zdraví agentů.`,

  'proces-platba': `NÁVOD — POTVRZENÍ RUČNÍ PLATBY (QR/převod/hotově): Rezervace → detail → panel Platba → „Potvrdit platbu" (PaymentConfirmModal) → vybrat metodu, VS, datum, č. transakce → potvrdit. Systém: nastaví paid, vystaví DP (payment_receipt), pošle mail s doklady, uplatní slevy/vouchery (redeem_booking_discounts_on_paid), u Slevomat voucheru auto-uplatní přes API. QR rezervace čekají s badge „QR/PŘEVOD — ČEKÁ · VS ..."; nezaplacené web rezervace ruší cron po 4 h (app po 10 min).`,

  'proces-storno-uprava': `NÁVOD — STORNO: detail rezervace → Stornovat → důvod → systém spočte refund dle tabulky (≥7 dní 100 %, 2–7 dní 50 %, <2 dny 0 %), provede Stripe refund (process-refund), vystaví dobropis, pošle mail; stav refund_pending→refunded po potvrzení Stripe. ÚPRAVA REZERVACE: detail → Upravit (BookingModifyModal) → změna termínu/motorky/výbavy → přepočet ceny (Varianta B: sleva se přepočítá na nový obsah) → přeplatek=auto refund+dobropis; doplatek u zaplacené="Zákazník doplatí" → mail s QR+VS → po zaplacení „Potvrdit doplatek" (pošle odložený booking_modified mail + rozdílový DP). Zákazník sám: web /upravit-rezervaci, appka, nebo AI widget (3FA: booking_id+kontakt+4 znaky hesla, limit 3 změny/den). VÝMĚNA MOTORKY: SwapModal — Model A (navazující rezervace, switch po podpisu protokolu) / Model B (split jedné rezervace, NET doplatek/vratka).`,

  'proces-sklad-sos': `NÁVOD — NASKLADNĚNÍ: Logistika → Naskladnění → doklad (faktura/DL) → OCR vytěží položky → SKU POVINNĚ dle konvence: prislusenstvi-{typ}-{velikost} (přes accessorySku, velikost přesně 43/XL/2XL/UNI), dily-{slug}, material-{slug}, zbozi-{slug}, spotrebni-{slug} — validace validateSku(). Kontrola duplicity dle č. dokladu+datum; párování DL⇄faktura. SOS ŘEŠENÍ: SOS panel → incident → acknowledged → dle typu: porucha (servis/výměna), nehoda (fotky, policie, vina), krádež → náhradní motorka (swap přes sos_swap_bookings zachová platby), odtah, zprávy zákazníkovi (šablony sos_response/tow/replacement...), resolved. Timeline loguje každý krok.`,
}
