<?php
// EN překlady recenzí (data/reviews.php, klíč = id recenze) — landing v2, renderLpReviews().
// Překládáno z českých originálů; „…“ = zkrácení jako v originále. Recenze s 'lang' => 'en' se nepřekládá.
return ['pages' => ['landing' => ['common' => [
    'reviews_tr' => [
        'karel-s-google' => 'Great, I rented an RVM 500 for 1 day, everything was done online, no deposit, the bike was ready in the morning, I returned it in the evening, no kilometre limit and great arrangements with the owner ;) I recommend it',
        'libor-j-google' => 'Exceptional service among motorcycle rentals, we\'re not bikers, we don\'t have gear. We ordered the bike in the app, we arrived, the bike was ready, …',
        'jirka-s-google' => 'Pluses: flexible timing, friendly approach, a superbly prepared machine, no deposit needed, mobile app …',
        'zdenek-r-google' => 'Highly recommend, I rented a Triumph Tiger 1200 Explorer on a recommendation, quick and comfortable booking, payment and bike pick-up, and on return the excellent coffee was a nice touch too :-)',
        'lenka-g-google' => 'A great human approach! If you\'re thinking of renting a motorcycle for your child to try, you won\'t go wrong here. Kind and friendly dealings the whole time. Definitely recommend 🙂',
        'jaroslav-j-google' => 'In one word: AMAZING. Warmly recommended. After years I got the chance to go back to my youth, when I used to ride quite a lot. Flawless service from ordering the bike to renting it, gear included, and returning it. The owners are accommodating and helpful. 👍',
        'laza-google' => 'A great rental experience, I had the bike for 2 days, with a trailer too. The bikes are well maintained, the staff very pleasant and helpful. The gentleman who handed the bike over to me even helped me load and secure it. For me a great experience and I can only recommend it.',
        'romana-k-google' => 'Thank you for a lovely trip. My husband and I rented a BMW GS 1200, and I also rented all the riding gear. Great service, communication, nice surroundings. We highly recommend it and will be back some time :-).',
        'daniel-h-google' => 'An absolute biker\'s paradise – I recommend it wholeheartedly! I was looking for a reliable rental for a trip and this choice hit the bull\'s-eye. From the first contact to returning the machine, a completely flawless experience.',
        'martin-k-google' => 'Simple booking, low price, a beautiful area for a ride. Quick handover and helpful staff.',
        'zdenek-firmy' => 'A perfect rental! Great dealings, no deposit, you don\'t have to bother washing the bike and they lend you the gear for free. Quick, honest and hassle-free. Nothing to fault.',
        'petr-c-firmy' => 'A great experience. I especially appreciate the friendly and accommodating approach; everything went without any problems at all. The bike was ready at the agreed time and with a full tank too, so I could set off straight away. The handover was quick with no needless delays, and so was the return, which was possible at any time, even at night. Another big plus was that there was no need to refuel before returning – so you don\'t have to deal with needless worries.',
        'marian-l-fb' => '… I sorted everything easily with the app; the prices and rental conditions were the best of all I found. When I arrived at the rental, I was welcomed by the owner, a likeable and very nice lady. She showed me everything and willingly answered my questions (technical matters…). The bike and accessories were already prepared. Returning the machine to the rental also went perfectly. … Very satisfied with the approach and with the bike too.',
        'martin-o-firmy' => 'A perfect motorcycle rental - easy ordering, good prices, quick and easy handover + a bonus in the form of great roads around the area.',
        'strdyna-firmy' => 'For the first time I decided to rent a touring bike for more comfort for two, and I\'m extremely satisfied! … The bike (Benelli TRK 502 X) was waiting in good technical condition, washed, with a full tank, ready to ride; I parked my car right next to it, where it could stay in a fenced car park over the weekend. A great approach from the owner and a trouble-free return, even with an offer of coffee for the journey home.',
        'hancl-firmy' => 'The bike was ready at the agreed time. All communication worked 100% right from the start. … At the handover the owner explained everything. … Another thing I appreciate: if any problem comes up, you just need to call. Excellent technical support. … What I really liked is that you can return the machine in the evening. A nicely made, clear website and app. I recommend this rental 10/10.',
        'jan-r-fb' => 'It\'s simply an amazing company and a bunch of people who love motorcycles. I can only recommend it to everyone. I enjoyed it enormously. A wide choice of bikes and clothing that you can try on at your leisure. Kind and accommodating approach. Simply brilliant. Thank you very much.',
        'dejv-m-firmy' => '… When I arrived for the bike, everything was already prepared, I was offered a coffee and everything was explained to me. The bike was in excellent technical condition, clean and with a practically full tank. The return then also went smoothly and completely professionally. From the communication and booking to the rental itself. The documents were sent well in advance, so there are no needless delays. …',
        'pavel-s-fb' => 'We rented two scooters, both new and in great condition. The service was top-notch and on top of that they\'re likeable and totally easy-going. Thank you, we recommend them.',
        'jan-m-firmy' => 'I don\'t normally write reviews, but I have to make time for this one... An above-standard approach that has no equal. A very helpful and pleasant lady. Great website, app and booking system. …',
    ],
]]]];
