// i18n-tpl-2.js – Template screen translations part 2 (edit, rdtl) for MotoGo24
(function(){
function m(s){for(var l in s){if(!I18N[l])continue;for(var k in s[l])I18N[l][k]=s[l][k];}}
m({
cs:{
edit:{
editTitle:'Upravit rezervaci',tabExtend:'Prodloužit / Změna místa',tabShorten:'Zkrácení / Změna místa',dateSection:'Termín',yourReservation:'Vaše stávající rezervace',pickupDelivery:'Přistavení motorky',returnPickup:'Vrácení motorky',atBranch:'Na pobočce',toYourAddr:'Přistavení na vaši adresu',fromYourAddr:'Odvoz z vaší adresy',deliveryAddr:'Ulice a č.p. / č.o.',returnAddr:'Ulice a č.p. / č.o.',deliveryTime:'Čas přistavení',returnTime:'Čas vrácení',enterAddr:'Zadejte adresu',branchChange:'Změna pobočky',active:'Aktivní',comingSoon:'Připravujeme',soonLabel:'Již brzy',motoChange:'Změna motorky',currentMoto:'Aktuální motorka',selectNewMoto:'Vyberte novou motorku',extras:'Doplňky',priceChange:'Změna ceny',origPrice:'Původní cena',extension:'Prodloužení',shortening:'Zkrácení (vrácení)',returnFee:'Odvoz na vlastní adresu',returnDiff:'Rozdíl odvozu (nové místo)',motoDiff:'Změna motorky',extrasLabel:'Doplňky',toPayRefund:'K doplatku / vrácení',saveChanges:'Uložit změny →',cancelNote:'Storno podmínky: 7+ dní = 100 % vrácení · 2–7 dní = 50 % · méně než 2 dny = bez vrácení.',calLegCurrent:'Stávající',calLegShortened:'Zkráceno'
},
rdtl:{
resDetail:'Detail rezervace',motoSection:'Motorka',model:'Model',category:'Kategorie',pickupLabel:'Vyzvednutí',returnLabel:'Vrácení',duration:'Délka výpůjčky',pickupPlace:'Místo vyzvednutí',returnPlace:'Místo vrácení',paySection:'Platba',pricePerDay:'Cena za den',deposit:'Záloha',noDeposit:'Neúčtujeme ✓',totalLabel:'Celkem',payMethod:'Způsob platby',rideHistory:'Průběh výpůjčky',totalPrice:'Celková cena',docsDownload:'Doklady ke stažení',advanceInvoice:'Zálohová faktura',handoverProtocol:'Předávací protokol',digitalView:'Digitální · zobrazit a podepsat',finalInvoice:'Konečná faktura',myRes:'Moje rezervace',resManagement:'Správa všech rezervací',filterAll:'Vše',filterActive:'Aktivní',filterUpcoming:'Nadcházející',filterDone:'Dokončené',tapToRate:'Klepněte na hvězdičku pro hodnocení',bookAgain:'Znovu rezervovat',contract:'Smlouva',invoice:'Faktura',contractsTitle:'Dokumenty a smlouvy',contractsSub:'Archiv smluvní dokumentace',gdprAccess:'Přístupné pouze vám. Zpracování dle GDPR.'
}
},
en:{
edit:{
editTitle:'Edit reservation',tabExtend:'Extend / Change location',tabShorten:'Shorten / Change location',dateSection:'Dates',yourReservation:'Your current reservation',pickupDelivery:'Motorcycle delivery',returnPickup:'Motorcycle return',atBranch:'At the branch',toYourAddr:'Delivery to your address',fromYourAddr:'Pick-up from your address',deliveryAddr:'Street and house No.',returnAddr:'Street and house No.',deliveryTime:'Delivery time',returnTime:'Return time',enterAddr:'Enter address',branchChange:'Branch change',active:'Active',comingSoon:'Coming soon',soonLabel:'Soon',motoChange:'Motorcycle change',currentMoto:'Current motorcycle',selectNewMoto:'Select a new motorcycle',extras:'Extras',priceChange:'Price change',origPrice:'Original price',extension:'Extension',shortening:'Shortening (refund)',returnFee:'Pick-up from your address',returnDiff:'Pick-up difference (new location)',motoDiff:'Motorcycle change',extrasLabel:'Extras',toPayRefund:'To pay / refund',saveChanges:'Save changes →',cancelNote:'Cancellation policy: 7+ days = 100% refund · 2–7 days = 50% · less than 2 days = no refund.',calLegCurrent:'Current',calLegShortened:'Shortened'
},
rdtl:{
resDetail:'Reservation detail',motoSection:'Motorcycle',model:'Model',category:'Category',pickupLabel:'Pick-up',returnLabel:'Return',duration:'Rental duration',pickupPlace:'Pick-up location',returnPlace:'Return location',paySection:'Payment',pricePerDay:'Price per day',deposit:'Deposit',noDeposit:'Not charged ✓',totalLabel:'Total',payMethod:'Payment method',rideHistory:'Ride history',totalPrice:'Total price',docsDownload:'Documents to download',advanceInvoice:'Advance invoice',handoverProtocol:'Handover protocol',digitalView:'Digital · view and sign',finalInvoice:'Final invoice',myRes:'My reservations',resManagement:'Manage all reservations',filterAll:'All',filterActive:'Active',filterUpcoming:'Upcoming',filterDone:'Completed',tapToRate:'Tap a star to rate',bookAgain:'Book again',contract:'Contract',invoice:'Invoice',contractsTitle:'Documents and contracts',contractsSub:'Contract documentation archive',gdprAccess:'Accessible only to you. Processed under GDPR.'
}
},
de:{
edit:{
editTitle:'Reservierung bearbeiten',tabExtend:'Verlängern / Ort ändern',tabShorten:'Verkürzen / Ort ändern',dateSection:'Termin',yourReservation:'Ihre aktuelle Reservierung',pickupDelivery:'Motorrad-Zustellung',returnPickup:'Motorrad-Rückgabe',atBranch:'In der Filiale',toYourAddr:'Zustellung an Ihre Adresse',fromYourAddr:'Abholung von Ihrer Adresse',deliveryAddr:'Straße und Hausnr.',returnAddr:'Straße und Hausnr.',deliveryTime:'Zustellzeit',returnTime:'Rückgabezeit',enterAddr:'Adresse eingeben',branchChange:'Filialwechsel',active:'Aktiv',comingSoon:'Demnächst',soonLabel:'Bald',motoChange:'Motorradwechsel',currentMoto:'Aktuelles Motorrad',selectNewMoto:'Neues Motorrad wählen',extras:'Zubehör',priceChange:'Preisänderung',origPrice:'Ursprünglicher Preis',extension:'Verlängerung',shortening:'Verkürzung (Erstattung)',returnFee:'Abholung von eigener Adresse',returnDiff:'Abholdifferenz (neuer Ort)',motoDiff:'Motorradwechsel',extrasLabel:'Zubehör',toPayRefund:'Nachzahlung / Erstattung',saveChanges:'Änderungen speichern →',cancelNote:'Stornobedingungen: 7+ Tage = 100 % Erstattung · 2–7 Tage = 50 % · weniger als 2 Tage = keine Erstattung.',calLegCurrent:'Aktuell',calLegShortened:'Verkürzt'
},
rdtl:{
resDetail:'Reservierungsdetail',motoSection:'Motorrad',model:'Modell',category:'Kategorie',pickupLabel:'Abholung',returnLabel:'Rückgabe',duration:'Mietdauer',pickupPlace:'Abholort',returnPlace:'Rückgabeort',paySection:'Zahlung',pricePerDay:'Preis pro Tag',deposit:'Kaution',noDeposit:'Wird nicht berechnet ✓',totalLabel:'Gesamt',payMethod:'Zahlungsmethode',rideHistory:'Mietverlauf',totalPrice:'Gesamtpreis',docsDownload:'Dokumente zum Download',advanceInvoice:'Vorauszahlungsrechnung',handoverProtocol:'Übergabeprotokoll',digitalView:'Digital · anzeigen und unterschreiben',finalInvoice:'Schlussrechnung',myRes:'Meine Reservierungen',resManagement:'Alle Reservierungen verwalten',filterAll:'Alle',filterActive:'Aktiv',filterUpcoming:'Bevorstehend',filterDone:'Abgeschlossen',tapToRate:'Tippen Sie auf einen Stern zur Bewertung',bookAgain:'Erneut buchen',contract:'Vertrag',invoice:'Rechnung',contractsTitle:'Dokumente und Verträge',contractsSub:'Vertragsdokumentationsarchiv',gdprAccess:'Nur für Sie zugänglich. Verarbeitung gemäß DSGVO.'
}
},
es:{
edit:{
editTitle:'Editar reserva',tabExtend:'Ampliar / Cambiar lugar',tabShorten:'Acortar / Cambiar lugar',dateSection:'Fechas',yourReservation:'Su reserva actual',pickupDelivery:'Entrega de la moto',returnPickup:'Devolución de la moto',atBranch:'En la sucursal',toYourAddr:'Entrega en su dirección',fromYourAddr:'Recogida en su dirección',deliveryAddr:'Calle y n.º',returnAddr:'Calle y n.º',deliveryTime:'Hora de entrega',returnTime:'Hora de devolución',enterAddr:'Introduzca dirección',branchChange:'Cambio de sucursal',active:'Activa',comingSoon:'Próximamente',soonLabel:'Pronto',motoChange:'Cambio de moto',currentMoto:'Moto actual',selectNewMoto:'Seleccione una nueva moto',extras:'Extras',priceChange:'Cambio de precio',origPrice:'Precio original',extension:'Ampliación',shortening:'Acortamiento (reembolso)',returnFee:'Recogida en su dirección',returnDiff:'Diferencia de recogida (nuevo lugar)',motoDiff:'Cambio de moto',extrasLabel:'Extras',toPayRefund:'A pagar / reembolso',saveChanges:'Guardar cambios →',cancelNote:'Política de cancelación: 7+ días = 100 % reembolso · 2–7 días = 50 % · menos de 2 días = sin reembolso.',calLegCurrent:'Actual',calLegShortened:'Acortado'
},
rdtl:{
resDetail:'Detalle de la reserva',motoSection:'Motocicleta',model:'Modelo',category:'Categoría',pickupLabel:'Recogida',returnLabel:'Devolución',duration:'Duración del alquiler',pickupPlace:'Lugar de recogida',returnPlace:'Lugar de devolución',paySection:'Pago',pricePerDay:'Precio por día',deposit:'Depósito',noDeposit:'No se cobra ✓',totalLabel:'Total',payMethod:'Método de pago',rideHistory:'Historial del alquiler',totalPrice:'Precio total',docsDownload:'Documentos para descargar',advanceInvoice:'Factura anticipada',handoverProtocol:'Protocolo de entrega',digitalView:'Digital · ver y firmar',finalInvoice:'Factura final',myRes:'Mis reservas',resManagement:'Gestionar todas las reservas',filterAll:'Todas',filterActive:'Activas',filterUpcoming:'Próximas',filterDone:'Completadas',tapToRate:'Pulse una estrella para valorar',bookAgain:'Reservar de nuevo',contract:'Contrato',invoice:'Factura',contractsTitle:'Documentos y contratos',contractsSub:'Archivo de documentación contractual',gdprAccess:'Accesible solo para usted. Tratamiento según RGPD.'
}
},
fr:{
edit:{
editTitle:'Modifier la réservation',tabExtend:'Prolonger / Changer de lieu',tabShorten:'Raccourcir / Changer de lieu',dateSection:'Dates',yourReservation:'Votre réservation actuelle',pickupDelivery:'Livraison de la moto',returnPickup:'Retour de la moto',atBranch:'En agence',toYourAddr:'Livraison à votre adresse',fromYourAddr:'Enlèvement à votre adresse',deliveryAddr:'Rue et n°',returnAddr:'Rue et n°',deliveryTime:'Heure de livraison',returnTime:'Heure de retour',enterAddr:'Saisissez l\'adresse',branchChange:'Changement d\'agence',active:'Active',comingSoon:'Bientôt disponible',soonLabel:'Bientôt',motoChange:'Changement de moto',currentMoto:'Moto actuelle',selectNewMoto:'Sélectionnez une nouvelle moto',extras:'Accessoires',priceChange:'Changement de prix',origPrice:'Prix d\'origine',extension:'Prolongation',shortening:'Raccourcissement (remboursement)',returnFee:'Enlèvement à votre adresse',returnDiff:'Différence d\'enlèvement (nouveau lieu)',motoDiff:'Changement de moto',extrasLabel:'Accessoires',toPayRefund:'À payer / remboursement',saveChanges:'Enregistrer les modifications →',cancelNote:'Conditions d\'annulation : 7+ jours = 100 % remboursement · 2–7 jours = 50 % · moins de 2 jours = sans remboursement.',calLegCurrent:'Actuelle',calLegShortened:'Raccourcie'
},
rdtl:{
resDetail:'Détail de la réservation',motoSection:'Moto',model:'Modèle',category:'Catégorie',pickupLabel:'Retrait',returnLabel:'Retour',duration:'Durée de location',pickupPlace:'Lieu de retrait',returnPlace:'Lieu de retour',paySection:'Paiement',pricePerDay:'Prix par jour',deposit:'Caution',noDeposit:'Non facturée ✓',totalLabel:'Total',payMethod:'Mode de paiement',rideHistory:'Historique de location',totalPrice:'Prix total',docsDownload:'Documents à télécharger',advanceInvoice:'Facture d\'acompte',handoverProtocol:'Protocole de remise',digitalView:'Numérique · afficher et signer',finalInvoice:'Facture finale',myRes:'Mes réservations',resManagement:'Gérer toutes les réservations',filterAll:'Toutes',filterActive:'Actives',filterUpcoming:'À venir',filterDone:'Terminées',tapToRate:'Appuyez sur une étoile pour évaluer',bookAgain:'Réserver à nouveau',contract:'Contrat',invoice:'Facture',contractsTitle:'Documents et contrats',contractsSub:'Archive de documentation contractuelle',gdprAccess:'Accessible uniquement par vous. Traitement conforme au RGPD.'
}
},
nl:{
edit:{
editTitle:'Reservering bewerken',tabExtend:'Verlengen / Locatie wijzigen',tabShorten:'Verkorten / Locatie wijzigen',dateSection:'Data',yourReservation:'Uw huidige reservering',pickupDelivery:'Bezorging van de motor',returnPickup:'Retour van de motor',atBranch:'Bij het filiaal',toYourAddr:'Bezorging op uw adres',fromYourAddr:'Ophalen op uw adres',deliveryAddr:'Straat en huisnr.',returnAddr:'Straat en huisnr.',deliveryTime:'Bezorgtijd',returnTime:'Retourtijd',enterAddr:'Voer adres in',branchChange:'Filiaalwissel',active:'Actief',comingSoon:'Binnenkort beschikbaar',soonLabel:'Binnenkort',motoChange:'Motorwissel',currentMoto:'Huidige motor',selectNewMoto:'Selecteer een nieuwe motor',extras:'Extra\'s',priceChange:'Prijswijziging',origPrice:'Oorspronkelijke prijs',extension:'Verlenging',shortening:'Verkorting (terugbetaling)',returnFee:'Ophalen van eigen adres',returnDiff:'Ophaaldifferentie (nieuwe locatie)',motoDiff:'Motorwissel',extrasLabel:'Extra\'s',toPayRefund:'Bij te betalen / terugbetaling',saveChanges:'Wijzigingen opslaan →',cancelNote:'Annuleringsvoorwaarden: 7+ dagen = 100 % terugbetaling · 2–7 dagen = 50 % · minder dan 2 dagen = geen terugbetaling.',calLegCurrent:'Huidig',calLegShortened:'Verkort'
},
rdtl:{
resDetail:'Reserveringsdetail',motoSection:'Motor',model:'Model',category:'Categorie',pickupLabel:'Ophalen',returnLabel:'Retour',duration:'Verhuurduur',pickupPlace:'Ophaallocatie',returnPlace:'Retourlocatie',paySection:'Betaling',pricePerDay:'Prijs per dag',deposit:'Borg',noDeposit:'Wordt niet berekend ✓',totalLabel:'Totaal',payMethod:'Betaalmethode',rideHistory:'Verhuurgeschiedenis',totalPrice:'Totaalprijs',docsDownload:'Documenten om te downloaden',advanceInvoice:'Voorschotfactuur',handoverProtocol:'Overdrachtsprotocol',digitalView:'Digitaal · bekijken en ondertekenen',finalInvoice:'Eindfactuur',myRes:'Mijn reserveringen',resManagement:'Alle reserveringen beheren',filterAll:'Alle',filterActive:'Actief',filterUpcoming:'Aankomend',filterDone:'Voltooid',tapToRate:'Tik op een ster om te beoordelen',bookAgain:'Opnieuw boeken',contract:'Contract',invoice:'Factuur',contractsTitle:'Documenten en contracten',contractsSub:'Archief van contractdocumentatie',gdprAccess:'Alleen voor u toegankelijk. Verwerking conform AVG.'
}
},
pl:{
edit:{
editTitle:'Edytuj rezerwację',tabExtend:'Przedłuż / Zmień miejsce',tabShorten:'Skróć / Zmień miejsce',dateSection:'Termin',yourReservation:'Twoja aktualna rezerwacja',pickupDelivery:'Dostawa motocykla',returnPickup:'Zwrot motocykla',atBranch:'W oddziale',toYourAddr:'Dostawa pod Twój adres',fromYourAddr:'Odbiór z Twojego adresu',deliveryAddr:'Ulica i nr',returnAddr:'Ulica i nr',deliveryTime:'Czas dostawy',returnTime:'Czas zwrotu',enterAddr:'Wpisz adres',branchChange:'Zmiana oddziału',active:'Aktywna',comingSoon:'Wkrótce dostępne',soonLabel:'Wkrótce',motoChange:'Zmiana motocykla',currentMoto:'Aktualny motocykl',selectNewMoto:'Wybierz nowy motocykl',extras:'Dodatki',priceChange:'Zmiana ceny',origPrice:'Pierwotna cena',extension:'Przedłużenie',shortening:'Skrócenie (zwrot)',returnFee:'Odbiór z własnego adresu',returnDiff:'Różnica odbioru (nowe miejsce)',motoDiff:'Zmiana motocykla',extrasLabel:'Dodatki',toPayRefund:'Do dopłaty / zwrotu',saveChanges:'Zapisz zmiany →',cancelNote:'Warunki anulowania: 7+ dni = 100 % zwrotu · 2–7 dni = 50 % · mniej niż 2 dni = bez zwrotu.',calLegCurrent:'Aktualna',calLegShortened:'Skrócona'
},
rdtl:{
resDetail:'Szczegóły rezerwacji',motoSection:'Motocykl',model:'Model',category:'Kategoria',pickupLabel:'Odbiór',returnLabel:'Zwrot',duration:'Czas wynajmu',pickupPlace:'Miejsce odbioru',returnPlace:'Miejsce zwrotu',paySection:'Płatność',pricePerDay:'Cena za dzień',deposit:'Kaucja',noDeposit:'Nie pobieramy ✓',totalLabel:'Razem',payMethod:'Metoda płatności',rideHistory:'Przebieg wynajmu',totalPrice:'Cena całkowita',docsDownload:'Dokumenty do pobrania',advanceInvoice:'Faktura zaliczkowa',handoverProtocol:'Protokół przekazania',digitalView:'Cyfrowy · wyświetl i podpisz',finalInvoice:'Faktura końcowa',myRes:'Moje rezerwacje',resManagement:'Zarządzanie wszystkimi rezerwacjami',filterAll:'Wszystkie',filterActive:'Aktywne',filterUpcoming:'Nadchodzące',filterDone:'Zakończone',tapToRate:'Dotknij gwiazdki, aby ocenić',bookAgain:'Zarezerwuj ponownie',contract:'Umowa',invoice:'Faktura',contractsTitle:'Dokumenty i umowy',contractsSub:'Archiwum dokumentacji umownej',gdprAccess:'Dostępne tylko dla Ciebie. Przetwarzanie zgodnie z RODO.'
}
}
});
})();
