// i18n-tpl.js – Template screen translations part 1 (proto) for MotoGo24
(function(){
function m(s){for(var l in s){if(!I18N[l])continue;for(var k in s[l])I18N[l][k]=s[l][k];}}
m({
cs:{
proto:{
title:'Předávací protokol',subtitle:'Přečtěte a potvrďte digitálním podpisem',identification:'Identifikace',lessor:'Pronajímatel',lessee:'Nájemce',contractNum:'Číslo smlouvy',motorcycle:'Motocykl',brandModel:'Značka / Model',vin:'VIN',odometer:'Tachometr při předání',fuelLevel:'Stav paliva',fuelFull:'Plná nádrž',equipment:'Výbava a příslušenství',checkAll:'Zaškrtněte vše co bylo předáno:',keys:'Klíče (od motorky + od kufru)',greenCard:'Zelená karta (mezinárodní pojištění)',regCert:'Malý technický průkaz',reflVests:'2× reflexní vesta',firstAid:'Motolékárnička',accidentForm:'Záznam o dopravní nehodě s propiskou',balaclava:'Kukla (nová – zůstává nájemci)',riderHelmet:'Helma řidiče',gloves:'Rukavice',jacket:'Bunda',trousers:'Kalhoty',otherNote:'Ostatní příslušenství (poznámka)',otherPlaceholder:'kufry, GPS, boty...',condition:'Potvrzení stavu',damageLabel:'Existující poškození při předání (pokud žádné, nechte prázdné)',damagePlaceholder:'Popis stávajících škrábanců, poškození...',conditionText:'Nájemce potvrzuje, že se s Předávacím protokolem seznámil, souhlasí s jeho obsahem a přebírá motocykl ve výše uvedeném stavu.',digitalSign:'Digitální podpis',signInstr:'Potvrďte svou totožnost pro digitální podpis protokolu:',faceTouch:'Face / Touch ID',pinCode:'PIN kód',enterPin:'Zadejte váš PIN (heslo z profilu)',confirmSign:'Potvrdit podpis',protocolSigned:'Protokol podepsán',submitProtocol:'Odeslat protokol MotoGo24'
}
},
en:{
proto:{
title:'Handover Protocol',subtitle:'Read and confirm with a digital signature',identification:'Identification',lessor:'Lessor',lessee:'Lessee',contractNum:'Contract number',motorcycle:'Motorcycle',brandModel:'Brand / Model',vin:'VIN',odometer:'Odometer at handover',fuelLevel:'Fuel level',fuelFull:'Full tank',equipment:'Equipment and accessories',checkAll:'Check all items handed over:',keys:'Keys (motorcycle + top case)',greenCard:'Green card (international insurance)',regCert:'Registration certificate',reflVests:'2× reflective vest',firstAid:'First-aid kit',accidentForm:'Accident report form with pen',balaclava:'Balaclava (new – stays with the lessee)',riderHelmet:'Rider helmet',gloves:'Gloves',jacket:'Jacket',trousers:'Trousers',otherNote:'Other accessories (note)',otherPlaceholder:'panniers, GPS, boots...',condition:'Condition confirmation',damageLabel:'Existing damage at handover (leave blank if none)',damagePlaceholder:'Description of existing scratches, damage...',conditionText:'The lessee confirms having read the Handover Protocol, agrees with its content and accepts the motorcycle in the condition described above.',digitalSign:'Digital signature',signInstr:'Confirm your identity for the digital signature of the protocol:',faceTouch:'Face / Touch ID',pinCode:'PIN code',enterPin:'Enter your PIN (profile password)',confirmSign:'Confirm signature',protocolSigned:'Protocol signed',submitProtocol:'Submit protocol to MotoGo24'
}
},
de:{
proto:{
title:'Übergabeprotokoll',subtitle:'Lesen und mit digitaler Unterschrift bestätigen',identification:'Identifikation',lessor:'Vermieter',lessee:'Mieter',contractNum:'Vertragsnummer',motorcycle:'Motorrad',brandModel:'Marke / Modell',vin:'VIN',odometer:'Tachostand bei Übergabe',fuelLevel:'Tankstand',fuelFull:'Voller Tank',equipment:'Ausrüstung und Zubehör',checkAll:'Alles Übergebene ankreuzen:',keys:'Schlüssel (Motorrad + Koffer)',greenCard:'Grüne Karte (internationale Versicherung)',regCert:'Zulassungsbescheinigung',reflVests:'2× Warnweste',firstAid:'Verbandskasten',accidentForm:'Unfallbericht mit Kugelschreiber',balaclava:'Sturmhaube (neu – verbleibt beim Mieter)',riderHelmet:'Fahrerhelm',gloves:'Handschuhe',jacket:'Jacke',trousers:'Hose',otherNote:'Sonstiges Zubehör (Anmerkung)',otherPlaceholder:'Koffer, GPS, Stiefel...',condition:'Zustandsbestätigung',damageLabel:'Vorhandene Schäden bei Übergabe (leer lassen, wenn keine)',damagePlaceholder:'Beschreibung vorhandener Kratzer, Schäden...',conditionText:'Der Mieter bestätigt, das Übergabeprotokoll gelesen zu haben, stimmt dem Inhalt zu und übernimmt das Motorrad im oben beschriebenen Zustand.',digitalSign:'Digitale Unterschrift',signInstr:'Bestätigen Sie Ihre Identität für die digitale Unterschrift des Protokolls:',faceTouch:'Face / Touch ID',pinCode:'PIN-Code',enterPin:'Geben Sie Ihre PIN ein (Profilpasswort)',confirmSign:'Unterschrift bestätigen',protocolSigned:'Protokoll unterschrieben',submitProtocol:'Protokoll an MotoGo24 senden'
}
},
es:{
proto:{
title:'Protocolo de entrega',subtitle:'Lea y confirme con firma digital',identification:'Identificación',lessor:'Arrendador',lessee:'Arrendatario',contractNum:'Número de contrato',motorcycle:'Motocicleta',brandModel:'Marca / Modelo',vin:'VIN',odometer:'Cuentakilómetros en la entrega',fuelLevel:'Nivel de combustible',fuelFull:'Tanque lleno',equipment:'Equipamiento y accesorios',checkAll:'Marque todo lo entregado:',keys:'Llaves (moto + cofre)',greenCard:'Carta verde (seguro internacional)',regCert:'Permiso de circulación',reflVests:'2× chaleco reflectante',firstAid:'Botiquín de primeros auxilios',accidentForm:'Formulario de accidente con bolígrafo',balaclava:'Pasamontañas (nuevo – queda para el arrendatario)',riderHelmet:'Casco del piloto',gloves:'Guantes',jacket:'Chaqueta',trousers:'Pantalones',otherNote:'Otros accesorios (nota)',otherPlaceholder:'maletas, GPS, botas...',condition:'Confirmación del estado',damageLabel:'Daños existentes en la entrega (dejar en blanco si no hay)',damagePlaceholder:'Descripción de arañazos, daños existentes...',conditionText:'El arrendatario confirma haber leído el Protocolo de entrega, está de acuerdo con su contenido y acepta la motocicleta en el estado descrito.',digitalSign:'Firma digital',signInstr:'Confirme su identidad para la firma digital del protocolo:',faceTouch:'Face / Touch ID',pinCode:'Código PIN',enterPin:'Introduzca su PIN (contraseña del perfil)',confirmSign:'Confirmar firma',protocolSigned:'Protocolo firmado',submitProtocol:'Enviar protocolo a MotoGo24'
}
},
fr:{
proto:{
title:'Protocole de remise',subtitle:'Lisez et confirmez avec une signature numérique',identification:'Identification',lessor:'Bailleur',lessee:'Locataire',contractNum:'Numéro de contrat',motorcycle:'Moto',brandModel:'Marque / Modèle',vin:'VIN',odometer:'Compteur à la remise',fuelLevel:'Niveau de carburant',fuelFull:'Réservoir plein',equipment:'Équipement et accessoires',checkAll:'Cochez tout ce qui a été remis :',keys:'Clés (moto + top case)',greenCard:'Carte verte (assurance internationale)',regCert:'Certificat d\'immatriculation',reflVests:'2× gilet réfléchissant',firstAid:'Trousse de secours',accidentForm:'Constat d\'accident avec stylo',balaclava:'Cagoule (neuve – reste au locataire)',riderHelmet:'Casque pilote',gloves:'Gants',jacket:'Veste',trousers:'Pantalon',otherNote:'Autres accessoires (note)',otherPlaceholder:'valises, GPS, bottes...',condition:'Confirmation de l\'état',damageLabel:'Dommages existants à la remise (laisser vide si aucun)',damagePlaceholder:'Description des rayures, dommages existants...',conditionText:'Le locataire confirme avoir lu le Protocole de remise, en accepte le contenu et prend en charge la moto dans l\'état décrit ci-dessus.',digitalSign:'Signature numérique',signInstr:'Confirmez votre identité pour la signature numérique du protocole :',faceTouch:'Face / Touch ID',pinCode:'Code PIN',enterPin:'Saisissez votre PIN (mot de passe du profil)',confirmSign:'Confirmer la signature',protocolSigned:'Protocole signé',submitProtocol:'Envoyer le protocole à MotoGo24'
}
},
nl:{
proto:{
title:'Overdrachtsprotocol',subtitle:'Lees en bevestig met een digitale handtekening',identification:'Identificatie',lessor:'Verhuurder',lessee:'Huurder',contractNum:'Contractnummer',motorcycle:'Motor',brandModel:'Merk / Model',vin:'VIN',odometer:'Kilometerstand bij overdracht',fuelLevel:'Brandstofniveau',fuelFull:'Volle tank',equipment:'Uitrusting en accessoires',checkAll:'Vink alles aan wat is overgedragen:',keys:'Sleutels (motor + topkoffer)',greenCard:'Groene kaart (internationale verzekering)',regCert:'Kentekenbewijs',reflVests:'2× reflecterend vest',firstAid:'EHBO-set',accidentForm:'Schadeformulier met pen',balaclava:'Bivakmuts (nieuw – blijft bij de huurder)',riderHelmet:'Helm rijder',gloves:'Handschoenen',jacket:'Jas',trousers:'Broek',otherNote:'Overige accessoires (opmerking)',otherPlaceholder:'koffers, GPS, laarzen...',condition:'Bevestiging van de staat',damageLabel:'Bestaande schade bij overdracht (leeg laten indien geen)',damagePlaceholder:'Beschrijving van bestaande krassen, schade...',conditionText:'De huurder bevestigt het Overdrachtsprotocol te hebben gelezen, gaat akkoord met de inhoud en aanvaardt de motor in de hierboven beschreven staat.',digitalSign:'Digitale handtekening',signInstr:'Bevestig uw identiteit voor de digitale ondertekening van het protocol:',faceTouch:'Face / Touch ID',pinCode:'PIN-code',enterPin:'Voer uw PIN in (profielwachtwoord)',confirmSign:'Handtekening bevestigen',protocolSigned:'Protocol ondertekend',submitProtocol:'Protocol verzenden naar MotoGo24'
}
},
pl:{
proto:{
title:'Protokół przekazania',subtitle:'Przeczytaj i potwierdź podpisem cyfrowym',identification:'Identyfikacja',lessor:'Wynajmujący',lessee:'Najemca',contractNum:'Numer umowy',motorcycle:'Motocykl',brandModel:'Marka / Model',vin:'VIN',odometer:'Przebieg przy przekazaniu',fuelLevel:'Poziom paliwa',fuelFull:'Pełny bak',equipment:'Wyposażenie i akcesoria',checkAll:'Zaznacz wszystko, co zostało przekazane:',keys:'Klucze (motocykl + kufer)',greenCard:'Zielona karta (ubezpieczenie międzynarodowe)',regCert:'Dowód rejestracyjny',reflVests:'2× kamizelka odblaskowa',firstAid:'Apteczka',accidentForm:'Formularz wypadkowy z długopisem',balaclava:'Kominiarka (nowa – zostaje u najemcy)',riderHelmet:'Kask kierowcy',gloves:'Rękawice',jacket:'Kurtka',trousers:'Spodnie',otherNote:'Pozostałe akcesoria (uwaga)',otherPlaceholder:'kufry, GPS, buty...',condition:'Potwierdzenie stanu',damageLabel:'Istniejące uszkodzenia przy przekazaniu (zostaw puste, jeśli brak)',damagePlaceholder:'Opis istniejących zarysowań, uszkodzeń...',conditionText:'Najemca potwierdza, że zapoznał się z Protokołem przekazania, zgadza się z jego treścią i przyjmuje motocykl w opisanym powyżej stanie.',digitalSign:'Podpis cyfrowy',signInstr:'Potwierdź swoją tożsamość w celu cyfrowego podpisania protokołu:',faceTouch:'Face / Touch ID',pinCode:'Kod PIN',enterPin:'Wpisz swój PIN (hasło z profilu)',confirmSign:'Potwierdź podpis',protocolSigned:'Protokół podpisany',submitProtocol:'Wyślij protokół do MotoGo24'
}
}
});
})();
