/* MotoGo24 — Cookie consent + Consent Mode v2 wiring.
 *
 * GTM container je již načtený v <head> (renderGtmHead) s default consent='denied'.
 * Tento skript: 1) přečte existující consent cookie a buď zavolá gtag('consent','update',...)
 * nebo zobrazí banner pokud cookie chybí; 2) na klik accept/reject/save zapíše cookie
 * + zavolá gtag('consent','update',...); 3) Sklik retargeting (nečte Consent Mode)
 * loaduje dynamicky až po marketing consentu.
 */
!function(){var e=window.MG_CONSENT_CFG||{},t="mg_cookie_consent";function n(){var e=("; "+document.cookie).split("; "+t+"=");if(e.length<2)return null;var n=e.pop().split(";").shift();try{return JSON.parse(decodeURIComponent(n))}catch(e){return null}}function a(e){var n=encodeURIComponent(JSON.stringify(e)),a="https:"===location.protocol?";secure":"";document.cookie=t+"="+n+";path=/;max-age=31536000;samesite=Lax"+a}function o(e,t){var n=window.gtag||function(){(window.dataLayer=window.dataLayer||[]).push(arguments)};n("consent","update",{analytics_storage:e?"granted":"denied",ad_storage:t?"granted":"denied",ad_user_data:t?"granted":"denied",ad_personalization:t?"granted":"denied"})}function r(t){t&&(o(!!t.analytics,!!t.marketing),t.marketing&&function(t){if(t&&!window.__mgSklikLoaded){window.__mgSklikLoaded=!0,window.seznam_retargeting_id=t;var n=document.createElement("script");n.async=!0,n.src="https://c.imedia.cz/js/retargeting.js",document.head.appendChild(n)}}(e.sklikId))}function s(e){var t=document.getElementById("mg-consent");if(t){t.hidden=!1;var n=document.getElementById("mg-consent-settings"),a=document.querySelector("[data-consent-action=save]");e?(n&&(n.hidden=!1),a&&(a.hidden=!1)):(n&&(n.hidden=!0),a&&(a.hidden=!0))}}function i(e,t){var n,o={necessary:1,analytics:e?1:0,marketing:t?1:0,v:2,ts:Math.floor(Date.now()/1e3)};a(o),r(o),(n=document.getElementById("mg-consent"))&&(n.hidden=!0)}function c(){var e=n();e?r(e):s(!1);var t=document.getElementById("mg-consent");t&&t.addEventListener("click",function(e){var t=e.target.closest("[data-consent-action]");if(t){e.preventDefault();var n=t.getAttribute("data-consent-action");if("accept-all"===n)i(!0,!0);else if("reject-all"===n)i(!1,!1);else if("settings"===n)s(!0);else if("save"===n){var a=document.getElementById("mg-consent-analytics"),o=document.getElementById("mg-consent-marketing");i(a&&a.checked,o&&o.checked)}}}),document.addEventListener("click",function(e){if(e.target.closest("[data-cookie-prefs]")){e.preventDefault();var t=n(),a=document.getElementById("mg-consent-analytics"),o=document.getElementById("mg-consent-marketing");a&&(a.checked=!(!t||!t.analytics)),o&&(o.checked=!(!t||!t.marketing)),s(!0)}})}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",c):c()}();
