<?php
// Překlady recenzí (data/reviews.php, klíč = id recenze) — landing v2, renderLpReviews().
// NL (nizozemština) — přeloženo z českých originálů, „…“ zachováno; recenze v angličtině se nepřekládá.
return ['pages' => ['landing' => ['common' => [
    'reviews_tr' => [
        'karel-s-google' => 'Super, ik had voor 1 dag een RVM 500 gehuurd, alles ging online, zonder borg, de motor stond \'s ochtends klaar, \'s avonds bracht ik hem terug, zonder kilometerbeperking en super afspraken met de eigenaar ;) Aanrader',
        'libor-j-google' => 'Uitzonderlijke service onder de motorverhuurders, we zijn geen motorrijders en hebben geen uitrusting. We bestelden de motor in de app, kwamen aan, de motor stond klaar, …',
        'jirka-s-google' => 'Pluspunten: flexibele tijden, vriendelijke aanpak, perfect voorbereide machine, geen borg nodig, mobiele app …',
        'zdenek-r-google' => 'Echt een aanrader, ik huurde op aanraden een Triumph Tiger 1200 Explorer, snel en gemakkelijk reserveren, betalen en de motor ophalen, en ook bij het terugbrengen deed de uitstekende koffie me plezier :-)',
        'lenka-g-google' => 'Geweldige, menselijke aanpak! Als je overweegt een motor te huren zodat je kind het eens kan proberen, zit je hier goed. Vriendelijk en hartelijk contact van begin tot eind. Absoluut een aanrader 🙂',
        'jaroslav-j-google' => 'In één woord: FANTASTISCH. Van harte aanbevolen. Na jaren kreeg ik de kans terug te gaan naar mijn jeugd, toen ik best veel reed. Perfecte service, van het bestellen van de motor en het huren inclusief uitrusting tot het terugbrengen. De eigenaren zijn behulpzaam en bereidwillig. 👍',
        'laza-google' => 'Geweldige huurervaring, ik had de motor 2 dagen, ook met aanhanger. De motoren zijn goed onderhouden, het personeel is erg vriendelijk en behulpzaam. De meneer die me de motor overhandigde, hielp me hem zelfs in te laden en vast te zetten. Voor mij een geweldige ervaring en ik kan het alleen maar aanraden.',
        'romana-k-google' => 'Bedankt voor een fijn uitstapje. Mijn man en ik hadden een BMW GS 1200 gehuurd en ik alle motoruitrusting. Geweldige service, goede afspraken, mooie omgeving. Echt een aanrader en we komen zeker nog eens terug :-).',
        'daniel-h-google' => 'Een absoluut motorparadijs – ik raad het volmondig aan! Ik zocht een betrouwbare verhuurder voor een tocht en deze keuze was een schot in de roos. Van het eerste contact tot het terugbrengen van de machine een volkomen vlekkeloze ervaring.',
        'martin-k-google' => 'Eenvoudig reserveren, lage prijs, prachtige omgeving voor een rit. Snelle overdracht en behulpzaam personeel.',
        'zdenek-firmy' => 'Perfecte verhuur! Super contact, geen borg, je hoeft je niet druk te maken over het wassen van de motor en de uitrusting krijg je gratis te leen. Snel, eerlijk en zorgeloos. Niets op aan te merken.',
        'petr-c-firmy' => 'Geweldige ervaring. Ik waardeer vooral de vriendelijke en behulpzame aanpak, alles verliep zonder enig probleem. De motor stond op het afgesproken tijdstip klaar en bovendien met een volle tank, zodat ik meteen kon vertrekken. De overdracht was snel en zonder onnodig oponthoud, net als het terugbrengen, dat op elk moment kon, zelfs \'s nachts. Een groot pluspunt was ook dat je voor het terugbrengen niet hoefde bij te tanken – zo hoef je je geen onnodige zorgen te maken.',
        'marian-l-fb' => '… Ik regelde alles eenvoudig via de app, de prijzen en huurvoorwaarden waren de beste van alle die ik vond. Bij aankomst werd ik verwelkomd door de sympathieke en zeer vriendelijke eigenaresse. Ze legde me alles uit en beantwoordde bereidwillig mijn vragen (techn. zaken…). De motor en de accessoires stonden al klaar. Ook het terugbrengen van de machine verliep helemaal goed. … Zeer tevreden over de aanpak en ook over de motor.',
        'martin-o-firmy' => 'Perfecte motorverhuur - eenvoudig bestellen, goede prijzen, snelle en makkelijke overdracht + als bonus prachtige wegen in de omgeving.',
        'strdyna-firmy' => 'Voor het eerst besloot ik een toermotor te huren voor meer comfort met z\'n tweeën en ik ben uiterst tevreden! … De motor (Benelli TRK 502 X) stond in goede technische staat klaar, gewassen en met een volle tank, klaar voor de rit; mijn auto parkeerde ik er direct naast, op een omheinde parkeerplaats waar hij het hele weekend kon blijven staan. Geweldige aanpak van de eigenaresse en probleemloos terugbrengen, zelfs met een kop koffie voor onderweg naar huis.',
        'hancl-firmy' => 'De motor stond op het afgesproken tijdstip klaar. Alle communicatie werkte vanaf het begin 100%. … Bij de overdracht legde de eigenaresse alles uit. … Wat ik ook waardeer: als er een probleem is, hoef je alleen maar te bellen. Uitstekende technische ondersteuning. … Wat me erg beviel, is dat je de machine \'s avonds kunt terugbrengen. Mooie en overzichtelijke website en app. Ik raad deze verhuur aan: 10/10.',
        'jan-r-fb' => 'Het is gewoon een geweldig bedrijf en een groep mensen die van motoren houden. Ik kan het iedereen alleen maar aanraden. Ik heb er enorm van genoten. Ruime keuze aan motoren en kleding die je rustig kunt passen. Vriendelijke en behulpzame aanpak. Gewoon top. Hartelijk dank.',
        'dejv-m-firmy' => '… Toen ik de motor kwam ophalen, stond alles al klaar, kreeg ik koffie aangeboden en werd alles uitgelegd. De motor was in uitstekende technische staat, schoon en met een vrijwel volle tank. Ook het terugbrengen verliep soepel en volkomen professioneel. Van de communicatie en reservering tot de uitvoering. De documenten werden ruim op tijd gestuurd, dus geen onnodig oponthoud. …',
        'pavel-s-fb' => 'We huurden twee scooters, allebei nieuw en in topstaat. De service was top en bovendien zijn ze sympathiek en heel relaxed. Bedankt, we raden het aan.',
        'jan-m-firmy' => 'Normaal schrijf ik geen reviews, maar hier moet ik er even tijd voor maken... Een uitzonderlijke aanpak die zijn weerga niet kent. Een zeer behulpzame en vriendelijke dame. Geweldige website, app en reserveringssysteem. …',
    ],
]]]];
