export const SEV = {
  ok:   { bg: '#dcfce7', color: '#166534', label: 'OK', cz: 'V pořádku' },
  fail: { bg: '#fef2f2', color: '#dc2626', label: 'PROBLÉM', cz: 'Nalezen problém' },
  warn: { bg: '#fef3c7', color: '#92400e', label: 'VAROVÁNÍ', cz: 'Vyžaduje pozornost' },
  info: { bg: '#eff6ff', color: '#1e40af', label: 'INFO', cz: 'Informace' },
}

// Czech descriptions for known actions
export const ACTION_DESC = {
  alert_stk_expiring: 'STK brzy vyprší — naplánovat kontrolu',
  alert_stk_expired: 'STK PROŠLÁ — motorka nesmí jezdit!',
  alert_stk_missing: 'STK není vyplněna v systému',
  inconsistency_active_but_in_service: 'Motorka je "aktivní" ale má otevřenou servisní zakázku',
  alert_no_pricing: 'Motorka nemá nastavený ceník',
  check_stk: 'Kontrola platnosti STK',
  cross_check_service_ok: 'Servis vs stav motorky — v pořádku',
  moto_has_active_bookings: 'Motorka má aktivní rezervace',
  moto_no_bookings: 'Motorka nemá žádné rezervace',
  fetch_fleet: 'Načtení flotily',
  set_maintenance: 'Motorka přepnuta do servisu',
  verify_returned_active: 'Motorka vrácena do stavu "aktivní"',
  detect_maintenance: 'Detekce přechodu do servisu',
  verify_active: 'Kontrola návratu motorky do stavu "aktivní" po servisu',
  verify_pricing_set: 'Kontrola ceníku motorky',
  verify_pricing: 'Kontrola ceníku',
  alert_incomplete_profile: 'Zákazník má nekompletní profil (chybí telefon/doklady)',
  detect_booking_without_docs: 'Zákazník má rezervaci ale nemá ověřené doklady!',
  detect_missing_docs: 'Zákazníkovi chybí doklady',
  detect_duplicate_profiles: 'Nalezeny duplicitní profily (stejný email)',
  detect_incomplete_profile: 'Nekompletní profil zákazníka',
  detect_no_docs: 'Zákazník bez dokladů',
  verify_profile: 'Kontrola profilu zákazníka',
  verify_profile_completeness: 'Kontrola kompletnosti profilu',
  handle_live_message: 'Zpracování živé zprávy od zákazníka',
  handle_message: 'Zpracování zprávy',
  check_blocked_status: 'Kontrola blokace zákazníka',
  booking_without_docs: 'Rezervace vytvořena bez dokladů',
  customer_reserves: 'Zákazník vytvořil rezervaci',
  customer_pays: 'Zákazník zaplatil',
  customer_picks_up: 'Zákazník vyzvednul motorku',
  customer_returns: 'Zákazník vrátil motorku',
  customer_extends: 'Zákazník prodloužil rezervaci',
  customer_shortens: 'Zákazník zkrátil rezervaci',
  customer_cancels: 'Zákazník stornoval rezervaci',
  customer_complains: 'Zákazník podal reklamaci',
  customer_rates_5: 'Zákazník hodnotil 5 hvězdiček',
  customer_rates_4: 'Zákazník hodnotil 4 hvězdičky',
  customer_rates_3: 'Zákazník hodnotil 3 hvězdičky',
  customer_rates_2: 'Zákazník hodnotil 2 hvězdičky',
  customer_rates_1: 'Zákazník hodnotil 1 hvězdičku',
  complaint_during_ride: 'Zákazník si stěžuje během jízdy',
  auto_cancel_no_payment: 'Automatické storno — zákazník nezaplatil',
  waiting_for_payment: 'Čeká se na platbu',
  payment_confirmed: 'Platba potvrzena',
  velin_created_booking: 'Velín vytvořil rezervaci',
  change_pickup_location: 'Změna místa vyzvednutí',
  change_return_location: 'Změna místa vrácení',
  watchdog_availability: 'Kontrola dostupnosti motorky',
  verify_price: 'Kontrola ceny',
  verify_invoice_generated: 'Kontrola vygenerování faktury',
  edge_shorten: 'Test zkrácení rezervace',
  cancel_and_verify: 'Storno a kontrola',
  create_for_change_test: 'Rezervace pro test změny',
  detect_overlap: 'Detekována kolize termínů — motorka je již zarezervována',
  first_booking: 'První rezervace (test kolize)',
  booking_no_docs: 'Rezervace bez dokladů (test)',
  edge_cancel_after_pay: 'Test storna po zaplacení',
  edge_booking_on_maintenance_moto: 'Test rezervace motorky v servisu',
  edge_multiple_bookings: 'Test více rezervací jednoho zákazníka',
  alert_missing_kf: 'Po dokončení rezervace se NEVYGENEROVALA konečná faktura',
  alert_zero_price: 'Ceník vrací nulovou cenu — chyba v nastavení',
  verify_kf_generated: 'Kontrola vygenerování konečné faktury',
  cross_check_payment_invoice: 'Zaplacená rezervace — kontrola existence faktury',
  verify_document_chain: 'Kontrola kompletní dokladové řady (ZF→DL→KF)',
  verify_price_calculation: 'Kontrola výpočtu ceny',
  verify_promo_discount: 'Kontrola slevy promo kódu',
  verify_payment: 'Kontrola platby',
  verify_promo: 'Kontrola promo kódu',
  verify_log: 'Kontrola zápisu do servisního logu',
  verify_log_entry: 'Kontrola záznamu v servisním logu',
  sos_triggered_repair: 'SOS incident vyvolal servisní zakázku',
  velin_created_order: 'Velín vytvořil servisní zakázku',
  verify_repair: 'Kontrola opravy',
  sos_service: 'Servisní zakázka po SOS',
  sos_light: 'Lehký SOS incident (porucha/defekt)',
  sos_heavy: 'Těžký SOS incident (nehoda/krádež)',
  create_incident: 'Vytvořen SOS incident',
  coordinate: 'Koordinace řešení SOS',
  resolve: 'SOS incident vyřešen',
  booking_failed: 'Rezervace pro SOS se nepodařila',
  post_sos_complete: 'Rezervace dokončena po SOS',
  coordinate_technician: 'Přiřazen technik',
  alert_missing_checkout: 'Zaměstnanci nemají zapsaný odchod v docházce',
  alert_pending_vacations: 'Neschválené žádosti o dovolenou',
  inconsistency_vacation_vs_shift: 'Zaměstnanec na dovolené má přiřazenou směnu!',
  alert_overtime: 'Překročen limit přesčasů (>5 směn/týden)',
  fetch_employees: 'Načtení zaměstnanců',
  verify_employee_profile: 'Kontrola profilu zaměstnance',
  fetch_shifts: 'Načtení směn',
  check_11h_rest: 'Kontrola 11h odpočinku mezi směnami',
  fetch_attendance: 'Načtení docházky',
  fetch_vacations: 'Načtení dovolených',
  vacation_shift_ok: 'Dovolená vs směny — v pořádku',
  check_overtime_ok: 'Přesčasy v normě',
  fetch_employee_docs: 'Načtení dokumentů zaměstnanců',
  alert_employee_without_docs: 'Zaměstnanec bez dokumentů (smlouva, BOZP)',
  alert_duplicate_shifts: 'Zaměstnanec má 2 směny v jeden den!',
  check_no_duplicate_shifts: 'Žádné duplicitní směny',
  alert_no_hourly_rate: 'Zaměstnanec bez hodinové sazby',
  alert_employee_no_contact: 'Zaměstnanec bez kontaktu (email/telefon)',
  alert_too_many_on_vacation: 'Příliš mnoho zaměstnanců na dovolené najednou!',
  hr_summary: 'Celkový HR souhrn',
  anomaly_no_price: 'Aktivní motorky bez nastaveného ceníku',
  fetch_fleet_data: 'Načtení dat flotily',
  count_bookings_reserved: 'Počet rezervací ve stavu "rezervováno"',
  count_bookings_active: 'Počet aktivních rezervací',
  count_bookings_completed: 'Počet dokončených rezervací',
  count_bookings_cancelled: 'Počet stornovaných rezervací',
  customer_segmentation: 'Segmentace zákazníků',
  sos_by_type: 'SOS incidenty dle typu',
  price_analysis: 'Cenová analýza',
  branch_occupancy: 'Obsazenost pobočky',
  rating_analysis: 'Analýza hodnocení zákazníků',
  analyze_pricing: 'Analýza ceníku motorky',
  analyze_branches: 'Analýza poboček',
  generate_report: 'Generování reportu',
  alert_stk_critical: 'STK vyprší do 14 dní — URGENTNÍ',
  alert_stk_warning: 'STK vyprší do 30 dní',
  inconsistency_expired_stk_active: 'Motorka s prošlou STK je stále ve stavu "aktivní"!',
  check_vin_completeness: 'Kontrola vyplnění VIN u všech motorek',
  check_spz_completeness: 'Kontrola vyplnění SPZ u všech motorek',
  verify_stk: 'Kontrola platnosti STK',
  compliance_summary: 'Souhrn shody s předpisy',
  alert_empty_template: 'Emailová šablona má prázdný obsah — nebude fungovat',
  alert_empty_msg_templates: 'Šablony zpráv s prázdným obsahem',
  alert_missing_contract_template: 'CHYBÍ šablona nájemní smlouvy!',
  alert_missing_vop_template: 'CHYBÍ šablona VOP!',
  fetch_settings: 'Načtení nastavení',
  fetch_email_templates: 'Načtení emailových šablon',
  verify_email_template: 'Kontrola emailové šablony',
  fetch_message_templates: 'Načtení šablon zpráv',
  check_contract_template: 'Kontrola šablony smlouvy',
  check_vop_template: 'Kontrola šablony VOP',
  fetch_automation_rules: 'Načtení automatických pravidel',
  automation_summary: 'Souhrn automatických pravidel',
  template_trigger_consistency: 'Konzistence šablon a pravidel',
  fk_bookings_moto: 'Integrita dat: rezervace → motorka',
  fk_bookings_user: 'Integrita dat: rezervace → zákazník',
  completed_has_returned_at: 'Dokončené rezervace mají datum vrácení',
  active_has_paid: 'Aktivní rezervace mají zaplaceno',
  resolved_has_date: 'Vyřešené SOS mají datum vyřešení',
  active_has_price: 'Aktivní motorky mají nastavený ceník',
  orphan_threads: 'Konverzace bez zpráv (osiřelé záznamy)',
  invoices_complete: 'Faktury mají číslo a částku',
  branches_audit: 'Kontrola poboček',
  admin_users_exist: 'Existence admin uživatelů',
  integrity_summary: 'Celkový souhrn integrity dat',
  check_unassigned_sos: 'Otevřené SOS incidenty bez přiřazeného řešitele',
  check_old_unpaid: 'Nezaplacené rezervace starší 24 hodin',
  check_long_maintenance: 'Servisní zakázky otevřené déle než 7 dní',
  check_closed_branches: 'Zavřené pobočky',
  check_unanswered_messages: 'Nezodpovězené zprávy zákazníků',
  check_admin_users: 'Kontrola admin uživatelů',
  kpi_summary: 'Souhrn klíčových ukazatelů (KPI)',
  agent_coordination_check: 'Kontrola zdraví všech agentů',
  create_promo: 'Vytvoření promo kódu',
  promo_audit: 'Audit promo kódů',
  alert_expired_active_promos: 'Promo kódy po expiraci stále aktivní!',
  alert_overused_promos: 'Promo kódy překročily limit použití!',
  fetch_accessory_types: 'Načtení příslušenství',
  voucher_audit: 'Audit voucherů',
  alert_expired_vouchers: 'Vouchery po expiraci stále aktivní!',
  fetch_orders: 'Načtení objednávek',
  pending_orders: 'Nevyřízené objednávky',
  verify_stock: 'Kontrola skladu',
  alert_inactive_accessories: 'Neaktivní příslušenství stále v nabídce',
  alert_zero_value_voucher: 'Voucher s nulovou hodnotou ale stále aktivní!',
  alert_stale_pending_orders: 'Objednávky čekající déle než 24 hodin!',
  alert_paid_not_shipped: 'Zaplacená objednávka ale nebyla odeslána!',
  alert_invalid_promo_value: 'Promo kód s neplatnou hodnotou (>100%)',
  verify_no_bookings_on_maintenance: 'Kontrola: žádné rezervace na motorce v servisu',
  verify_full_lifecycle_invoice: 'Kontrola faktury po kompletním lifecycle',
  edge_change_both_locations: 'Změna vyzvednutí i vrácení',
  edge_first_extend: 'První prodloužení',
  edge_second_extend: 'Druhé prodloužení po sobě',
  edge_first_sos: 'První SOS na rezervaci',
  edge_second_light_sos: 'Druhý lehký SOS na stejné rezervaci',
  cross_check_booking_profile: 'Cross-check profil zákazníka vs rezervace',
}

export function classify(entry) {
  if (!entry.success) return 'fail'
  if (entry.action?.includes('alert_') || entry.action?.includes('inconsistency_')) return 'fail'
  if (entry.action?.includes('detect_') || entry.action?.includes('anomaly_')) return 'warn'
  if (entry.action?.includes('verify_') || entry.action?.includes('check_') || entry.action?.includes('cross_check')) return 'ok'
  return 'info'
}

export function descCz(entry) {
  const desc = ACTION_DESC[entry.action]
  if (desc) return desc
  return (entry.action || '').replace(/_/g, ' ').replace(/^[a-z]/, c => c.toUpperCase())
}

export function detailCz(entry) {
  const s = entry.result_summary
  if (!s || s === 'ok') return ''
  return s
}
