<?php
// Překlady recenzí do FR (data/reviews.php, klíč = id recenze) — landing v2, renderLpReviews().
// Překládáno z češtiny (hlas zákazníka, bez přikrášlení; „…“ = zkrácený originál).
// Recenze s 'lang' => 'en' se nepřekládá. Struktura = lang/v2/es/reviews.php.
return ['pages' => ['landing' => ['common' => [
    'reviews_tr' => [
        'karel-s-google' => 'Super, j\'ai loué une RVM 500 pour 1 jour, tout s\'est fait en ligne, sans caution, la moto était prête le matin, je l\'ai rendue le soir, sans limite de kilomètres et super entente avec le propriétaire ;) Je recommande',
        'libor-j-google' => 'Un service exceptionnel parmi les loueurs de motos : nous ne sommes pas motards, nous n\'avons pas d\'équipement. Nous avons réservé la moto dans l\'appli, nous sommes arrivés, la moto était prête, …',
        'jirka-s-google' => 'Les plus : flexibilité horaire, accueil sympathique, machine parfaitement préparée, pas de dépôt à verser, appli mobile …',
        'zdenek-r-google' => 'Je recommande vivement. Sur recommandation, j\'ai loué une Triumph Tiger 1200 Explorer : réservation, paiement et retrait de la moto rapides et pratiques, et au retour, un excellent café m\'a fait plaisir :-)',
        'lenka-g-google' => 'Une approche humaine formidable ! Si vous pensez louer une moto pour que votre enfant l\'essaie, vous ne ferez pas d\'erreur ici. Un accueil gentil et sympathique du début à la fin. Je recommande vivement 🙂',
        'jaroslav-j-google' => 'En un mot : GÉNIAL. Je recommande chaleureusement. Après des années, j\'ai eu l\'occasion de retrouver ma jeunesse, quand je roulais pas mal. Un service impeccable, de la commande de la moto à la location avec l\'équipement, jusqu\'au retour. Des propriétaires arrangeants et serviables. 👍',
        'laza-google' => 'Super expérience de location : j\'ai eu la moto 2 jours, avec la remorque aussi. Les motos sont bien entretenues, le personnel très agréable et serviable. Le monsieur qui m\'a remis la moto m\'a même aidé à la charger et à l\'arrimer. Pour moi, une super expérience, je ne peux que recommander.',
        'romana-k-google' => 'Merci pour une chouette sortie. Mon mari et moi avions loué une BMW GS 1200, et moi tout l\'équipement moto. Super service, bonne communication, cadre agréable. Nous recommandons vivement et nous reviendrons :-).',
        'daniel-h-google' => 'Un vrai paradis pour motards : je recommande les yeux fermés ! Je cherchais un loueur fiable pour une sortie et ce choix a fait mouche. Du premier contact jusqu\'au retour de la machine, une expérience absolument sans faute.',
        'martin-k-google' => 'Réservation simple, prix bas, superbe coin pour une balade. Remise rapide et personnel serviable.',
        'zdenek-firmy' => 'Loueur parfait ! Super accueil, aucune caution, pas besoin de vous soucier du lavage de la moto et l\'équipement vous est prêté gratuitement. Rapide, honnête et sans souci. Rien à redire.',
        'petr-c-firmy' => 'Super expérience. J\'apprécie surtout l\'accueil sympathique et arrangeant ; tout s\'est passé sans le moindre problème. La moto était prête à l\'heure convenue et en plus avec le plein, donc j\'ai pu partir tout de suite. La remise a été rapide, sans attente inutile, tout comme le retour, possible à tout moment, même la nuit. Autre gros plus : pas besoin de refaire le plein avant le retour, on évite ainsi des soucis inutiles.',
        'marian-l-fb' => '… J\'ai tout réglé facilement avec l\'appli ; les prix et conditions de location, les meilleurs de tous ceux que j\'ai trouvés. À mon arrivée, j\'ai été accueilli par la propriétaire, sympathique et très gentille. Elle m\'a tout présenté et a répondu volontiers à mes questions (aspects techniques…). La moto et les accessoires étaient déjà prêts. Le retour de la machine s\'est lui aussi parfaitement passé. … Très satisfait de l\'accueil et aussi de la moto.',
        'martin-o-firmy' => 'Un loueur de motos parfait : commande facile, bons prix, remise rapide et simple et, en bonus, de superbes routes dans les environs.',
        'strdyna-firmy' => 'Pour la première fois, j\'ai loué une routière pour plus de confort à deux et je suis ravi ! … La moto (Benelli TRK 502 X) m\'attendait en bon état, lavée et avec le plein, prête pour la balade ; j\'ai garé ma voiture juste à côté, sur un parking clôturé où elle a pu rester tout le week-end. Super accueil de la propriétaire et retour sans problème, avec même un café proposé pour la route du retour.',
        'hancl-firmy' => 'La moto était prête à l\'heure convenue. Toute la communication a fonctionné à 100 % dès le début. … À la remise, la propriétaire m\'a tout expliqué. … Autre chose que j\'apprécie : au moindre problème, il suffit d\'appeler. Excellent support technique. … Ce qui m\'a beaucoup plu : on peut rendre la machine le soir. Site et appli beaux et clairs. Je recommande ce loueur : 10/10.',
        'jan-r-fb' => 'Une entreprise tout simplement géniale et une équipe de passionnés de moto. Je ne peux que la recommander à tous. Je me suis énormément régalé. Large choix de motos et de vêtements que l\'on essaie tranquillement. Accueil gentil et arrangeant. Tout simplement top. Merci beaucoup.',
        'dejv-m-firmy' => '… Quand je suis venu chercher la moto, tout était déjà prêt, on m\'a proposé un café et tout expliqué. La moto était en excellent état, propre et avec le réservoir pratiquement plein. Le retour s\'est lui aussi passé sans accroc et de façon totalement professionnelle. De la communication à la réservation jusqu\'à la remise. Les documents ont été envoyés suffisamment à l\'avance, donc aucune attente inutile. …',
        'pavel-s-fb' => 'Nous avons loué deux scooters, tous deux neufs et en super état. L\'accueil était au top et en plus ils sont sympas et très cool. Merci, nous recommandons !',
        'jan-m-firmy' => 'Normalement, je n\'écris pas d\'avis, mais pour celui-ci je dois prendre le temps… Un accueil hors du commun, sans égal. Une dame très serviable et agréable. Super site, appli et système de réservation. …',
    ],
]]]];
