<?php
// ===== Pobočky — landing v2: CS defaulty textů (pbV2Defaults v pobocky-v2-lib.php) =====
// Struktura = 'pages.pobocky.v2' v lang/v2/<lang>/pobocky-v2.php. branches[0] = Mezná,
// branches[1] = Velké Němčice (pořadí jako pobockyDefaults()). Ikony (i) = názvy z pbIcon().
// compare[].v = [Mezná, Velké Němčice], ok: 1 = ✓, 0 = ✗, bez ok = neutrální; count = počet motorek z DB.

return [
    'panel' => [
        'cta_primary' => ['label' => 'REZERVOVAT', 'href' => '/rezervace'],
        'cta_secondary' => ['label' => 'VYBRAT MOTORKU', 'href' => '/katalog'],
        'chips' => ['2 pobočky: Vysočina a Brno', 'Bez kauce', 'Výbava v ceně'],
    ],
    'cards_title' => 'Vyber si pobočku',
    'book_here' => 'Rezervovat zde',
    'book_branch' => 'Rezervovat na této pobočce',
    'motos_branch' => 'Motorky této pobočky',
    'motos_label' => 'motorek na pobočce',
    'about_title' => 'O pobočce',
    'hours_title' => 'Provozní doba',
    'gear_title' => 'Výbava',
    'in_bike_title' => 'V motorce najdeš',
    'guide_hint' => 'Projdi si celý postup krok za krokem.',
    'guide_step' => 'Krok {n} z {total}',
    'guide_prev' => 'Předchozí',
    'guide_next' => 'Další krok',
    'guide_done' => 'Rezervovat',
    'map_title' => 'Jak k nám',
    'map_open' => 'Navigovat',
    'video_badge' => 'Video',
    'video_lead' => 'Podívej se, jak převzetí motorky na pobočce probíhá — ať víš předem, co tě čeká.',
    'fleet_title' => 'Motorky na této pobočce',
    'other_title' => 'Naše druhá pobočka',
    'compare_title' => 'Mezná vs Velké Němčice',
    'compare_intro' => 'Obě pobočky v kostce — vyber si tu, která ti sedí.',
    'compare' => [
        ['label' => 'Předání motorky', 'i' => 'user', 'v' => [['t' => 'Osobně — vše vysvětlíme a pomůžeme s nastavením'], ['t' => 'Sám, bez obsluhy — kódy z aplikace a dotykový displej']]],
        ['label' => 'Provozní doba', 'i' => 'clock', 'v' => [['t' => 'PO–NE nonstop vč. víkendů a svátků, čas zvolíš v rezervaci'], ['t' => 'Nonstop 24/7, vrácení kdykoliv poslední den do 24:00']]],
        ['label' => 'Výbava pro řidiče v ceně', 'i' => 'helmet', 'v' => [['ok' => 1, 't' => 'Ano'], ['ok' => 1, 't' => 'Ano, motocyklové boty za příplatek']]],
        ['label' => 'Velikosti výbavy', 'i' => 'tag', 'v' => [['t' => 'Bundy a kalhoty až 6XL'], ['t' => 'Helmy S–3XL, bundy, kalhoty a rukavice do 4XL']]],
        ['label' => 'Nepromoky a doplňková výbava', 'i' => 'rain', 'v' => [['ok' => 1, 't' => 'Ano'], ['ok' => 0, 't' => 'Ne — jen v Mezné']]],
        ['label' => 'Přistavení na adresu', 'i' => 'truck', 'v' => [['ok' => 1, 't' => 'Ano, za příplatek'], ['ok' => 0, 't' => 'Ne — převzetí i vrácení jen na pobočce']]],
        ['label' => 'Doklady', 'i' => 'doc', 'v' => [['t' => 'Nahraješ online, jinak je zkontrolujeme na místě'], ['t' => 'Nutné nahrát a ověřit online předem']]],
        ['label' => 'Zázemí', 'i' => 'kiosk', 'v' => [['t' => 'Wi-Fi, WC, převlékací kabinka a uzamykatelné skříňky'], ['t' => 'Šatna (dveře č. 8), dotykový displej a kóje s motorkami']]],
        ['label' => 'Parkování zdarma', 'i' => 'parking', 'v' => [['ok' => 1, 't' => 'Ano, po celou dobu výpůjčky'], ['ok' => 1, 't' => 'Ano, po celou dobu výpůjčky']]],
        ['label' => 'Dojezd', 'i' => 'car', 'v' => [['t' => 'cca 90 min z Prahy'], ['t' => '20 min z jižního okraje Brna (cca 30 min z centra), 35 min z letiště, 1 h 40 min z Vídně']]],
        ['label' => 'Motorek na pobočce', 'i' => 'moto', 'count' => 1, 'v' => [['t' => '{n}'], ['t' => '{n}']]],
    ],
    'branches' => [
        [
            'short' => 'Mezná',
            'highlight' => 'Osobní předání motorky — vše ti vysvětlíme',
            'dist' => ['cca 90 min z Prahy'],
            'stats' => [['v' => '90 min', 'l' => 'z Prahy (cca)'], ['v' => '6XL', 'l' => 'max. velikost výbavy'], ['v' => 'PO–NE', 'l' => 'nonstop']],
            'facts' => [
                ['i' => 'clock', 't' => 'PO–NE nonstop vč. svátků'], ['i' => 'user', 't' => 'Osobní předání'],
                ['i' => 'helmet', 't' => 'Výbava v ceně až do 6XL'], ['i' => 'rain', 't' => 'Nepromoky k zapůjčení'],
                ['i' => 'truck', 't' => 'Přistavení na adresu za příplatek'], ['i' => 'parking', 't' => 'Parkování zdarma'], ['i' => 'shield', 't' => 'Bez kauce'],
            ],
            'guide' => ['Rezervace a doklady', 'Příjezd na pobočku', 'Předání motorky a výbavy', 'Vrácení motorky'],
            'gear' => [['i' => 'helmet', 't' => 'Helma'], ['i' => 'jacket', 't' => 'Bunda'], ['i' => 'pants', 't' => 'Kalhoty'], ['i' => 'gloves', 't' => 'Rukavice'], ['i' => 'rain', 't' => 'Nepromoky']],
            'sizes' => 'Bundy a kalhoty ve velikostech až do 6XL',
            'in_bike' => [],
            'gallery' => [],
        ],
        [
            'short' => 'Velké Němčice',
            'highlight' => '100 % nonstop, bez obsluhy',
            'dist' => ['20 min z jižního okraje Brna, cca 30 min z centra', 'cca 35 min z letiště Brno-Tuřany', 'cca 1 h 40 min z Vídně'],
            'stats' => [['v' => '24/7', 'l' => 'nonstop, bez obsluhy'], ['v' => '30 min', 'l' => 'z centra Brna (cca)'], ['v' => '35 min', 'l' => 'z letiště Brno-Tuřany (cca)']],
            'facts' => [
                ['i' => 'phone', 't' => 'Převzetí kódem z aplikace'], ['i' => 'parking', 't' => 'Parkování zdarma'],
                ['i' => 'helmet', 't' => 'Výbava pro řidiče v ceně'], ['i' => 'percent', 't' => 'Vyzvednutí od 12:00: 1. den za polovinu (2+ dny)'],
                ['i' => 'moon', 't' => 'Vrácení poslední den do 24:00'], ['i' => 'shield', 't' => 'Bez kauce'],
            ],
            'guide' => ['Rezervace, platba a doklady', 'Brána a parkování', 'Šatna a výbava', 'Protokol a motorka', 'Brána při odjezdu', 'Vrácení motorky'],
            'gear' => [['i' => 'helmet', 't' => 'Helma'], ['i' => 'jacket', 't' => 'Bunda s páteřákem'], ['i' => 'pants', 't' => 'Kalhoty'], ['i' => 'gloves', 't' => 'Rukavice'], ['i' => 'balaclava', 't' => 'Kukla'], ['i' => 'boots', 't' => 'Boty (za příplatek)']],
            'sizes' => 'Helmy S–3XL, bundy, kalhoty a rukavice do 4XL (větší v Mezné)',
            'in_bike' => [['i' => 'vest', 't' => 'Reflexní vesta'], ['i' => 'firstaid', 't' => 'Lékárnička'], ['i' => 'doc', 't' => 'Záznam o nehodě'], ['i' => 'lock', 't' => 'Kotoučový zámek'], ['i' => 'phone', 't' => 'Klíček k držáku telefonu']],
            'gallery' => [],
        ],
    ],
];
