Současný stav supabase:

| query                                               |
| --------------------------------------------------- |
| SELECT * FROM public.accounting_entries LIMIT 5;    |
| SELECT * FROM public.admin_audit_log LIMIT 5;       |
| SELECT * FROM public.admin_messages LIMIT 5;        |
| SELECT * FROM public.admin_users LIMIT 5;           |
| SELECT * FROM public.ai_actions LIMIT 5;            |
| SELECT * FROM public.ai_conversations LIMIT 5;      |
| SELECT * FROM public.ai_logs LIMIT 5;               |
| SELECT * FROM public.app_settings LIMIT 5;          |
| SELECT * FROM public.automation_rules LIMIT 5;      |
| SELECT * FROM public.booking_cancellations LIMIT 5; |
| SELECT * FROM public.booking_extras LIMIT 5;        |
| SELECT * FROM public.bookings LIMIT 5;              |
| SELECT * FROM public.branch_performance LIMIT 5;    |
| SELECT * FROM public.branches LIMIT 5;              |
| SELECT * FROM public.cash_register LIMIT 5;         |
| SELECT * FROM public.cms_pages LIMIT 5;             |
| SELECT * FROM public.cms_variables LIMIT 5;         |
| SELECT * FROM public.daily_stats LIMIT 5;           |
| SELECT * FROM public.debug_log LIMIT 5;             |
| SELECT * FROM public.document_templates LIMIT 5;    |
| SELECT * FROM public.documents LIMIT 5;             |
| SELECT * FROM public.email_templates LIMIT 5;       |
| SELECT * FROM public.extras_catalog LIMIT 5;        |
| SELECT * FROM public.feature_flags LIMIT 5;         |
| SELECT * FROM public.generated_documents LIMIT 5;   |
| SELECT * FROM public.inventory LIMIT 5;             |
| SELECT * FROM public.inventory_movements LIMIT 5;   |
| SELECT * FROM public.invoices LIMIT 5;              |
| SELECT * FROM public.maintenance_log LIMIT 5;       |
| SELECT * FROM public.maintenance_schedules LIMIT 5; |
| SELECT * FROM public.message_templates LIMIT 5;     |
| SELECT * FROM public.message_threads LIMIT 5;       |
| SELECT * FROM public.messages LIMIT 5;              |
| SELECT * FROM public.moto_day_prices LIMIT 5;       |
| SELECT * FROM public.moto_locations LIMIT 5;        |
| SELECT * FROM public.moto_performance LIMIT 5;      |
| SELECT * FROM public.motorcycles LIMIT 5;           |
| SELECT * FROM public.notification_log LIMIT 5;      |
| SELECT * FROM public.notification_rules LIMIT 5;    |
| SELECT * FROM public.predictions LIMIT 5;           |
| SELECT * FROM public.pricing_rules LIMIT 5;         |
| SELECT * FROM public.profiles LIMIT 5;              |
| SELECT * FROM public.promo_code_usage LIMIT 5;      |
| SELECT * FROM public.promo_codes LIMIT 5;           |
| SELECT * FROM public.purchase_order_items LIMIT 5;  |
| SELECT * FROM public.purchase_orders LIMIT 5;       |
| SELECT * FROM public.push_tokens LIMIT 5;           |
| SELECT * FROM public.reviews LIMIT 5;               |
| SELECT * FROM public.sent_emails LIMIT 5;           |
| SELECT * FROM public.service_orders LIMIT 5;        |
| SELECT * FROM public.shop_order_items LIMIT 5;      |
| SELECT * FROM public.shop_orders LIMIT 5;           |
| SELECT * FROM public.sos_incidents LIMIT 5;         |
| SELECT * FROM public.sos_timeline LIMIT 5;          |
| SELECT * FROM public.suppliers LIMIT 5;             |
| SELECT * FROM public.tax_records LIMIT 5;           |
| SELECT * FROM public.vouchers LIMIT 5;              |