CREATE TRIGGER trg_acc_employees_updated BEFORE UPDATE ON public.acc_employees FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_acc_liabilities_updated BEFORE UPDATE ON public.acc_liabilities FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_acc_long_term_assets_updated BEFORE UPDATE ON public.acc_long_term_assets FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_acc_payrolls_updated BEFORE UPDATE ON public.acc_payrolls FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_auto_liabilities_payroll AFTER INSERT ON public.acc_payrolls FOR EACH ROW EXECUTE FUNCTION auto_liabilities_from_payroll();
CREATE TRIGGER trg_acc_short_term_assets_updated BEFORE UPDATE ON public.acc_short_term_assets FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_acc_tax_returns_updated BEFORE UPDATE ON public.acc_tax_returns FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_acc_vat_returns_updated BEFORE UPDATE ON public.acc_vat_returns FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_accessory_types_updated BEFORE UPDATE ON public.accessory_types FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_email_on_door_codes_message AFTER INSERT ON public.admin_messages FOR EACH ROW WHEN ((new.type = 'door_codes'::text)) EXECUTE FUNCTION trg_email_on_door_codes_message();
CREATE TRIGGER trg_push_on_admin_message AFTER INSERT ON public.admin_messages FOR EACH ROW EXECUTE FUNCTION trg_push_on_admin_message();
CREATE TRIGGER trg_admin_users_updated BEFORE UPDATE ON public.admin_users FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_ai_conversations_updated BEFORE UPDATE ON public.ai_conversations FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_ai_customer_conversations_updated BEFORE UPDATE ON public.ai_customer_conversations FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_app_installations_touch BEFORE UPDATE ON public.app_installations FOR EACH ROW EXECUTE FUNCTION app_installations_touch();
CREATE TRIGGER trg_app_settings_updated BEFORE UPDATE ON public.app_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_auto_order_rules_updated BEFORE UPDATE ON public.auto_order_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER bookings_auto_accounting AFTER UPDATE OF payment_status ON public.bookings FOR EACH ROW WHEN (((new.payment_status = 'paid'::payment_status) AND (old.payment_status IS DISTINCT FROM 'paid'::payment_status))) EXECUTE FUNCTION auto_accounting_on_booking_paid();
CREATE TRIGGER bookings_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER gear_shortage_on_booking AFTER INSERT OR UPDATE OF start_date, end_date, moto_id, status, helmet_size, jacket_size, pants_size, boots_size, gloves_size, passenger_helmet_size, passenger_jacket_size, passenger_pants_size, passenger_boots_size, passenger_gloves_size ON public.bookings FOR EACH ROW EXECUTE FUNCTION trg_gear_shortage_on_booking();
CREATE TRIGGER realloc_booking_discounts AFTER UPDATE OF discount_amount, total_price ON public.bookings FOR EACH ROW EXECUTE FUNCTION trg_realloc_booking_discounts();
CREATE TRIGGER redeem_booking_discounts AFTER UPDATE OF payment_status ON public.bookings FOR EACH ROW EXECUTE FUNCTION redeem_booking_discounts_on_paid();
CREATE TRIGGER trg_auto_deactivate_door_codes AFTER UPDATE OF status ON public.bookings FOR EACH ROW WHEN (((new.status = ANY (ARRAY['completed'::booking_status, 'cancelled'::booking_status])) AND (old.status IS DISTINCT FROM new.status))) EXECUTE FUNCTION auto_deactivate_door_codes();
CREATE TRIGGER trg_auto_generate_door_codes_insert AFTER INSERT ON public.bookings FOR EACH ROW WHEN ((new.status = ANY (ARRAY['active'::booking_status, 'reserved'::booking_status]))) EXECUTE FUNCTION auto_generate_door_codes();
CREATE TRIGGER trg_auto_generate_door_codes_update AFTER UPDATE OF status ON public.bookings FOR EACH ROW WHEN (((new.status = ANY (ARRAY['active'::booking_status, 'reserved'::booking_status])) AND (old.status IS DISTINCT FROM new.status))) EXECUTE FUNCTION auto_generate_door_codes();
CREATE TRIGGER trg_booking_mileage_to_moto AFTER INSERT OR UPDATE OF mileage_start ON public.bookings FOR EACH ROW EXECUTE FUNCTION trg_booking_mileage_to_moto();
CREATE TRIGGER trg_booking_modified_email AFTER UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION trg_send_booking_modified_email();
CREATE TRIGGER trg_booking_payment_fill_seconds BEFORE INSERT OR UPDATE OF payment_status, confirmed_at ON public.bookings FOR EACH ROW EXECUTE FUNCTION trg_booking_payment_fill_seconds();
CREATE TRIGGER trg_check_booking_overlap BEFORE INSERT OR UPDATE OF start_date, end_date, moto_id ON public.bookings FOR EACH ROW EXECUTE FUNCTION check_booking_overlap();
CREATE TRIGGER trg_check_trailer_overlap BEFORE INSERT OR UPDATE OF moto_id, trailer_moto_id, start_date, end_date, status ON public.bookings FOR EACH ROW EXECUTE FUNCTION check_trailer_overlap();
CREATE TRIGGER trg_check_user_booking_overlap BEFORE INSERT OR UPDATE OF start_date, end_date, user_id, status ON public.bookings FOR EACH ROW EXECUTE FUNCTION check_user_booking_overlap();
CREATE TRIGGER trg_detect_consecutive_booking BEFORE INSERT ON public.bookings FOR EACH ROW EXECUTE FUNCTION detect_consecutive_booking();
CREATE TRIGGER trg_gate_obsluzna_activation BEFORE UPDATE OF status ON public.bookings FOR EACH ROW WHEN (((new.status = 'active'::booking_status) AND (old.status <> 'active'::booking_status))) EXECUTE FUNCTION _gate_obsluzna_activation();
CREATE TRIGGER trg_generate_final_invoice AFTER UPDATE OF status ON public.bookings FOR EACH ROW WHEN (((old.status = 'active'::booking_status) AND (new.status = 'completed'::booking_status))) EXECUTE FUNCTION generate_final_invoice_on_complete();
CREATE TRIGGER trg_notify_booking_activated_email AFTER UPDATE OF status ON public.bookings FOR EACH ROW WHEN (((new.status = 'active'::booking_status) AND (old.status = 'reserved'::booking_status))) EXECUTE FUNCTION notify_booking_activated_email();
CREATE TRIGGER trg_notify_booking_cancelled_email AFTER UPDATE OF status ON public.bookings FOR EACH ROW WHEN (((new.status = 'cancelled'::booking_status) AND (old.status IS DISTINCT FROM 'cancelled'::booking_status))) EXECUTE FUNCTION notify_booking_cancelled_email();
CREATE TRIGGER trg_notify_booking_completed_email AFTER UPDATE OF status ON public.bookings FOR EACH ROW WHEN (((new.status = 'completed'::booking_status) AND (old.status = 'active'::booking_status))) EXECUTE FUNCTION notify_booking_completed_email();
CREATE TRIGGER trg_regen_codes_on_moto_change AFTER UPDATE OF moto_id ON public.bookings FOR EACH ROW WHEN (((old.moto_id IS DISTINCT FROM new.moto_id) AND (new.status = ANY (ARRAY['active'::booking_status, 'reserved'::booking_status])))) EXECUTE FUNCTION regen_door_codes_on_moto_change();
CREATE TRIGGER trg_release_swap_next_codes AFTER UPDATE OF status, returned_at ON public.bookings FOR EACH ROW WHEN ((((new.status = 'completed'::booking_status) OR (new.returned_at IS NOT NULL)) AND ((old.status IS DISTINCT FROM new.status) OR (old.returned_at IS DISTINCT FROM new.returned_at)))) EXECUTE FUNCTION release_swap_next_codes();
CREATE TRIGGER trg_restore_vouchers_on_cancel AFTER UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION restore_vouchers_on_cancel();
CREATE TRIGGER trg_track_booking_content_changes BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION track_booking_content_changes();
CREATE TRIGGER trg_validate_app_loyalty BEFORE INSERT ON public.bookings FOR EACH ROW EXECUTE FUNCTION validate_app_loyalty_discount();
CREATE TRIGGER trg_validate_late_pickup BEFORE INSERT ON public.bookings FOR EACH ROW EXECUTE FUNCTION validate_late_pickup_discount();
CREATE TRIGGER trg_branch_accessories_updated BEFORE UPDATE ON public.branch_accessories FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_branch_cameras_touch BEFORE UPDATE ON public.branch_cameras FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_branch_door_codes_updated BEFORE UPDATE ON public.branch_door_codes FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_notify_door_codes AFTER INSERT ON public.branch_door_codes FOR EACH ROW WHEN ((new.code_type = 'motorcycle'::text)) EXECUTE FUNCTION trg_notify_door_codes();
CREATE TRIGGER trg_withhold_swap_next_codes BEFORE INSERT ON public.branch_door_codes FOR EACH ROW EXECUTE FUNCTION withhold_swap_next_codes();
CREATE TRIGGER trg_branch_doors_touch BEFORE UPDATE ON public.branch_doors FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_branch_kiosk_config_touch BEFORE UPDATE ON public.branch_kiosk_config FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_branch_service_codes_touch BEFORE UPDATE ON public.branch_service_codes FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_branches_updated BEFORE UPDATE ON public.branches FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER cms_pages_updated_at BEFORE UPDATE ON public.cms_pages FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_sync_cms_flat_to_nested AFTER INSERT OR UPDATE ON public.cms_variables FOR EACH ROW WHEN ((new.key = ANY (ARRAY['web.pujcovna.h1'::text, 'web.pujcovna.intro'::text, 'web.pujcovna.ben.bottom'::text, 'web.pujcovna.ben.3'::text, 'web.pujcovna.ben.4'::text, 'web.pujcovna.ben.6'::text, 'web.pujcovna.step.1'::text, 'web.pujcovna.step.2'::text, 'web.pujcovna.step.3'::text, 'web.pujcovna.step.4'::text, 'web.pujcovna.step.5'::text, 'web.pujcovna.step.6'::text, 'web.pujcovna.step.7'::text, 'web.pujcovna.step.8'::text, 'web.kontakt.hours'::text, 'web.kontakt.seo'::text]))) EXECUTE FUNCTION sync_cms_flat_to_nested();
CREATE TRIGGER trg_contracts_updated BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_custom_documents_updated_at BEFORE UPDATE ON public.custom_documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_delivery_notes_updated BEFORE UPDATE ON public.delivery_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_release_codes_on_doc_upload AFTER INSERT ON public.documents FOR EACH ROW WHEN ((new.type = ANY (ARRAY['id_card'::text, 'passport'::text, 'drivers_license'::text, 'id_photo'::text, 'license_photo'::text]))) EXECUTE FUNCTION release_withheld_door_codes();
CREATE TRIGGER trg_email_templates_updated BEFORE UPDATE ON public.email_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_emp_attendance_updated BEFORE UPDATE ON public.emp_attendance FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_emp_documents_updated BEFORE UPDATE ON public.emp_documents FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_emp_shifts_updated BEFORE UPDATE ON public.emp_shifts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_emp_vacations_updated BEFORE UPDATE ON public.emp_vacations FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER faq_items_set_updated_at BEFORE UPDATE ON public.faq_items FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();
CREATE TRIGGER trg_fe_updated BEFORE UPDATE ON public.financial_events FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_flexi_reports_updated BEFORE UPDATE ON public.flexi_reports FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_activate_on_handover_protocol_doc AFTER INSERT ON public.generated_documents FOR EACH ROW EXECUTE FUNCTION _activate_on_handover_protocol_doc();
CREATE TRIGGER trg_sync_generated_doc_to_documents AFTER INSERT ON public.generated_documents FOR EACH ROW EXECUTE FUNCTION sync_generated_doc_to_documents();
CREATE TRIGGER inventory_updated_at BEFORE UPDATE ON public.inventory FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_cap_refund_to_paid BEFORE INSERT ON public.invoices FOR EACH ROW EXECUTE FUNCTION _cap_refund_to_paid();
CREATE TRIGGER trg_post_invoice_to_financial_event AFTER INSERT ON public.invoices FOR EACH ROW EXECUTE FUNCTION post_invoice_to_financial_event();
CREATE TRIGGER trg_send_booking_completed_email AFTER INSERT ON public.invoices FOR EACH ROW WHEN ((new.type = 'final'::text)) EXECUTE FUNCTION trg_send_booking_completed_email();
CREATE TRIGGER trg_sync_invoice_pdf_update AFTER UPDATE OF pdf_path ON public.invoices FOR EACH ROW EXECUTE FUNCTION sync_invoice_pdf_update();
CREATE TRIGGER trg_sync_invoice_to_documents AFTER INSERT ON public.invoices FOR EACH ROW EXECUTE FUNCTION sync_invoice_to_documents();
CREATE TRIGGER trg_kiosk_command_broadcast AFTER INSERT ON public.kiosk_commands FOR EACH ROW WHEN ((new.status = 'pending'::text)) EXECUTE FUNCTION kiosk_command_broadcast();
CREATE TRIGGER trg_kiosk_devices_touch BEFORE UPDATE ON public.kiosk_devices FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER maintenance_log_after_insert AFTER INSERT ON public.maintenance_log FOR EACH ROW EXECUTE FUNCTION update_moto_after_service();
CREATE TRIGGER maintenance_log_after_update AFTER UPDATE OF km_at_service, status, completed_date ON public.maintenance_log FOR EACH ROW EXECUTE FUNCTION update_moto_after_service();
CREATE TRIGGER trg_message_templates_updated BEFORE UPDATE ON public.message_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_bridge_admin_message AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION bridge_admin_message_to_app();
CREATE TRIGGER moto_day_prices_updated BEFORE UPDATE ON public.moto_day_prices FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_sync_moto_day_prices AFTER INSERT OR UPDATE ON public.moto_day_prices FOR EACH ROW EXECUTE FUNCTION sync_moto_day_prices_to_motorcycles();
CREATE TRIGGER motorcycles_updated_at BEFORE UPDATE ON public.motorcycles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_moto_purchase_mileage_floor BEFORE INSERT OR UPDATE OF mileage, purchase_mileage ON public.motorcycles FOR EACH ROW EXECUTE FUNCTION trg_moto_purchase_mileage_floor();
CREATE TRIGGER trg_sync_moto_to_assets AFTER INSERT OR UPDATE ON public.motorcycles FOR EACH ROW EXECUTE FUNCTION sync_motorcycle_to_assets();
CREATE TRIGGER trg_payment_methods_updated BEFORE UPDATE ON public.payment_methods FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_poi_ratings_updated BEFORE UPDATE ON public.poi_ratings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_poi_catalog_updated BEFORE UPDATE ON public.points_of_interest FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_products_updated BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_normalize_registration_source BEFORE INSERT OR UPDATE OF registration_source ON public.profiles FOR EACH ROW EXECUTE FUNCTION normalize_registration_source();
CREATE TRIGGER trg_release_codes_on_profile_verify AFTER UPDATE OF id_verified_at, passport_verified_at, license_verified_at, id_number, license_number ON public.profiles FOR EACH ROW EXECUTE FUNCTION release_codes_on_profile_verify();
CREATE TRIGGER trg_set_promo_code_source BEFORE INSERT ON public.promo_codes FOR EACH ROW EXECUTE FUNCTION set_promo_code_source();
CREATE TRIGGER purchase_orders_updated_at BEFORE UPDATE ON public.purchase_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_route_pois_updated BEFORE UPDATE ON public.route_pois FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_route_reviews_updated BEFORE UPDATE ON public.route_reviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_routes_set_countries BEFORE INSERT OR UPDATE OF waypoints, geometry, countries ON public.routes FOR EACH ROW EXECUTE FUNCTION routes_set_countries();
CREATE TRIGGER trg_routes_updated BEFORE UPDATE ON public.routes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_service_orders_updated BEFORE UPDATE ON public.service_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_service_parts_updated BEFORE UPDATE ON public.service_parts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_auto_process_voucher_order BEFORE UPDATE OF payment_status ON public.shop_orders FOR EACH ROW WHEN (((new.payment_status = 'paid'::text) AND (old.payment_status IS DISTINCT FROM 'paid'::text))) EXECUTE FUNCTION auto_process_voucher_order();
CREATE TRIGGER trg_generate_shop_final_on_ship AFTER UPDATE OF status, payment_status ON public.shop_orders FOR EACH ROW WHEN (((new.status = ANY (ARRAY['shipped'::text, 'delivered'::text])) AND (old.status IS DISTINCT FROM new.status) AND (new.payment_status = 'paid'::text))) EXECUTE FUNCTION generate_shop_final_on_ship();
CREATE TRIGGER trg_shop_order_confirmed_email AFTER UPDATE OF payment_status ON public.shop_orders FOR EACH ROW EXECUTE FUNCTION trg_send_shop_order_confirmed_email();
CREATE TRIGGER trg_shop_order_number BEFORE INSERT ON public.shop_orders FOR EACH ROW EXECUTE FUNCTION generate_shop_order_number();
CREATE TRIGGER trg_shop_orders_updated BEFORE UPDATE ON public.shop_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_notify_sos_incident_email AFTER INSERT ON public.sos_incidents FOR EACH ROW EXECUTE FUNCTION notify_sos_incident_email();
CREATE TRIGGER trg_one_active_sos BEFORE INSERT ON public.sos_incidents FOR EACH ROW EXECUTE FUNCTION check_one_active_sos();
CREATE TRIGGER trg_sos_auto_severity BEFORE INSERT ON public.sos_incidents FOR EACH ROW EXECUTE FUNCTION sos_auto_severity();
CREATE TRIGGER trg_sos_auto_timeline AFTER INSERT ON public.sos_incidents FOR EACH ROW EXECUTE FUNCTION sos_auto_timeline();
CREATE TRIGGER trg_sos_incidents_updated BEFORE UPDATE ON public.sos_incidents FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_sos_notify_user AFTER INSERT ON public.sos_incidents FOR EACH ROW EXECUTE FUNCTION sos_notify_user_on_create();
CREATE TRIGGER trg_suppliers_updated BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_user_pois_updated BEFORE UPDATE ON public.user_pois FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_saved_routes_updated BEFORE UPDATE ON public.user_saved_routes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_slevomat_auto_apply AFTER INSERT OR UPDATE OF status ON public.vouchers FOR EACH ROW EXECUTE FUNCTION slevomat_auto_apply_on_redeem();
CREATE TRIGGER trg_vouchers_updated BEFORE UPDATE ON public.vouchers FOR EACH ROW EXECUTE FUNCTION update_updated_at();
