// Texty webu: Úprava rezervace (/upravit-rezervaci)
// Stránka je JS-driven. PHP renderuje shell + i18n payload z `lang/cs.php`
// přes `t('editRez.*')` které prochází `_i18nCmsOverlay` (klíče tvaru
// `web.layout.editRez.*` v cms_variables). Když admin ve Velíně uloží text,
// `MG_I18N` ho dostane na další reload stránky.
//
// Pokrývá VŠECHNY klíče editRez.* (+ dow.short.*) které stránka renderuje:
// kalendář, validace, detail, motorka, místo, historie, souhlasy, doklady,
// chyby, stavové štítky atd.

export const PAGE_UPRAVIT_REZERVACE = {
  id: 'upravit-rezervaci', label: 'Úprava rezervace', icon: '✏️', url: '/upravit-rezervaci',
  description: 'Klientský portál pro úpravu / prodloužení / zkrácení / storno rezervace. Texty se rendrují přes JS z i18n overlay (klíče web.layout.editRez.*).',
  sections: [
    {
      id: 'meta', label: 'SEO meta',
      fields: [
        { key: 'web.layout.editRez.title', label: 'Page <title>', default: 'Upravit rezervaci' },
        { key: 'web.layout.editRez.description', label: 'Meta description', type: 'textarea', default: 'Upravte termín, prodlužte, zkraťte nebo zrušte svou rezervaci. Vrácení peněz dle storno podmínek.' },
      ]
    },
    {
      id: 'intro', label: 'Úvod stránky',
      fields: [
        { key: 'web.layout.editRez.h1', label: 'H1 nadpis', default: 'Upravit rezervaci' },
        { key: 'web.layout.editRez.intro', label: 'Úvodní text', type: 'textarea', default: 'Přihlaste se a spravujte svou rezervaci — můžete <strong>prodloužit</strong>, <strong>zkrátit</strong> nebo <strong>zrušit</strong> termín. Vrácení peněz proběhne automaticky podle storno podmínek.' },
        { key: 'web.layout.editRez.loading', label: 'Hláška „Načítám…"', default: 'Načítám…' },
      ]
    },
    {
      id: 'login', label: 'Přihlášení',
      fields: [
        { key: 'web.layout.editRez.login.title', label: 'Nadpis přihlášení', default: 'Přihlášení' },
        { key: 'web.layout.editRez.login.help', label: 'Pomocný text', type: 'textarea', default: 'Zadejte e-mail a heslo z rezervace. Heslo jste si nastavili při dokončení rezervace nebo v aplikaci.' },
        { key: 'web.layout.editRez.login.email', label: 'Label „E-mail"', default: 'E-mail' },
        { key: 'web.layout.editRez.login.password', label: 'Label „Heslo"', default: 'Heslo' },
        { key: 'web.layout.editRez.login.submit', label: 'Tlačítko „Přihlásit"', default: 'PŘIHLÁSIT' },
        { key: 'web.layout.editRez.login.submitting', label: 'Tlačítko „Přihlašuji…"', default: 'Přihlašuji…' },
        { key: 'web.layout.editRez.login.forgot', label: 'Odkaz „Zapomněl jsem heslo"', default: 'Zapomněl(a) jsem heslo' },
        { key: 'web.layout.editRez.login.tip', label: 'Tip pod formulářem', type: 'textarea', default: 'Tip: Pokud nemáte heslo, použijte odkaz „Zapomněl jsem heslo" — pošleme vám e-mail s nastavením.' },
        { key: 'web.layout.editRez.login.error', label: 'Chyba při přihlášení', default: 'Nesprávný e-mail nebo heslo.' },
      ]
    },
    {
      id: 'forgot', label: 'Zapomenuté heslo',
      fields: [
        { key: 'web.layout.editRez.forgot.title', label: 'Nadpis', default: 'Obnova hesla' },
        { key: 'web.layout.editRez.forgot.help', label: 'Pomocný text', type: 'textarea', default: 'Zadejte číslo rezervace a e-mail. Pošleme vám odkaz pro nastavení nového hesla.' },
        { key: 'web.layout.editRez.forgot.bookingId', label: 'Label „Číslo rezervace"', default: 'Číslo rezervace (z potvrzení)' },
        { key: 'web.layout.editRez.forgot.email', label: 'Label „E-mail"', default: 'E-mail z rezervace' },
        { key: 'web.layout.editRez.forgot.submit', label: 'Tlačítko „Odeslat"', default: 'POSLAT ODKAZ' },
        { key: 'web.layout.editRez.forgot.submitting', label: 'Tlačítko „Odesílám…"', default: 'Odesílám…' },
        { key: 'web.layout.editRez.forgot.success', label: 'Hláška úspěchu', type: 'textarea', default: 'Pokud rezervace existuje, poslali jsme e-mail s odkazem pro nastavení hesla.' },
        { key: 'web.layout.editRez.forgot.error', label: 'Hláška chyby', default: 'Nepodařilo se odeslat e-mail. Zkuste to prosím znovu.' },
        { key: 'web.layout.editRez.forgot.back', label: 'Tlačítko „Zpět na přihlášení"', default: '← Zpět na přihlášení' },
      ]
    },
    {
      id: 'reset', label: 'Reset hesla (po kliknutí na link z e-mailu)',
      fields: [
        { key: 'web.layout.editRez.reset.title', label: 'Nadpis', default: 'Nastavit nové heslo' },
        { key: 'web.layout.editRez.reset.help', label: 'Pomocný text', type: 'textarea', default: 'Zadejte nové heslo (min. 6 znaků). Po uložení budete přihlášen(a) a uvidíte své rezervace.' },
        { key: 'web.layout.editRez.reset.otpHelp', label: 'Pomocný text k OTP', type: 'textarea', default: 'Poslali jsme vám ověřovací kód na <strong>{email}</strong>. Zadejte 8-místný kód z e-mailu (stejný kód funguje pro aplikaci i web) a nastavte si nové heslo.' },
        { key: 'web.layout.editRez.reset.otpCode', label: 'Label „Ověřovací kód"', default: 'Ověřovací kód z e-mailu (8 znaků)' },
        { key: 'web.layout.editRez.reset.password', label: 'Label „Nové heslo"', default: 'Nové heslo' },
        { key: 'web.layout.editRez.reset.password2', label: 'Label „Heslo znovu"', default: 'Heslo znovu' },
        { key: 'web.layout.editRez.reset.submit', label: 'Tlačítko „Uložit"', default: 'ULOŽIT NOVÉ HESLO' },
        { key: 'web.layout.editRez.reset.submitting', label: 'Tlačítko „Ukládám…"', default: 'Ukládám…' },
        { key: 'web.layout.editRez.reset.success', label: 'Hláška úspěchu', default: 'Heslo nastaveno. Pokračujte do svých rezervací.' },
        { key: 'web.layout.editRez.reset.error', label: 'Hláška chyby', default: 'Nepodařilo se uložit heslo. Zkuste to prosím znovu.' },
        { key: 'web.layout.editRez.reset.tooShort', label: 'Validace „Krátké heslo"', default: 'Heslo musí mít alespoň 6 znaků.' },
        { key: 'web.layout.editRez.reset.mismatch', label: 'Validace „Hesla se neshodují"', default: 'Zadaná hesla se neshodují.' },
        { key: 'web.layout.editRez.reset.otpInvalid', label: 'Validace „Špatný kód"', default: 'Neplatný nebo expirovaný kód. Zkuste si nechat poslat nový.' },
      ]
    },
    {
      id: 'list', label: 'Seznam rezervací / objednávek',
      fields: [
        { key: 'web.layout.editRez.list.title', label: 'Nadpis „Vaše rezervace"', default: 'Vaše rezervace' },
        { key: 'web.layout.editRez.list.shopTitle', label: 'Nadpis „E-shop objednávky"', default: 'E-shop objednávky' },
        { key: 'web.layout.editRez.list.vouchersTitle', label: 'Nadpis „Dárkové poukazy"', default: 'Dárkové poukazy' },
        { key: 'web.layout.editRez.list.empty', label: 'Hláška „Žádné rezervace"', type: 'textarea', default: 'Nemáte žádnou rezervaci.' },
        { key: 'web.layout.editRez.list.openNew', label: 'Tlačítko „Nová rezervace"', default: 'Vytvořit novou rezervaci' },
        { key: 'web.layout.editRez.list.choose', label: 'Tlačítko „Vybrat"', default: 'Klikněte pro výběr' },
        { key: 'web.layout.editRez.list.payCta', label: 'Tlačítko „Zaplatit"', default: '💳 Pokračovat k platbě' },
        { key: 'web.layout.editRez.list.payAria', label: 'Aria-label „Zaplatit"', default: 'Pokračovat k platbě' },
        { key: 'web.layout.editRez.list.shopRowTitle', label: 'Řádek „E-shop objednávka"', default: 'E-shop objednávka' },
        { key: 'web.layout.editRez.list.voucherRowTitle', label: 'Řádek „Dárkový poukaz"', default: 'Dárkový poukaz' },
        { key: 'web.layout.editRez.logout', label: 'Tlačítko „Odhlásit"', default: 'Odhlásit se' },
      ]
    },
    {
      id: 'filters', label: 'Filtr stavů rezervací',
      fields: [
        { key: 'web.layout.editRez.filter.all', label: 'Filtr „Vše"', default: 'Vše' },
        { key: 'web.layout.editRez.filter.active', label: 'Filtr „Aktivní"', default: 'Aktivní' },
        { key: 'web.layout.editRez.filter.upcoming', label: 'Filtr „Nadcházející"', default: 'Nadcházející' },
        { key: 'web.layout.editRez.filter.completed', label: 'Filtr „Dokončené"', default: 'Dokončené' },
        { key: 'web.layout.editRez.filter.cancelled', label: 'Filtr „Zrušené"', default: 'Zrušené' },
      ]
    },
    {
      id: 'statuses', label: 'Stavové štítky rezervace',
      fields: [
        { key: 'web.layout.editRez.status.pending', label: 'Stav „Čeká na zaplacení"', default: 'Čeká na zaplacení' },
        { key: 'web.layout.editRez.status.unpaid', label: 'Stav „Nezaplaceno"', default: 'Nezaplaceno' },
        { key: 'web.layout.editRez.status.reserved', label: 'Stav „Rezervováno"', default: 'Rezervováno' },
        { key: 'web.layout.editRez.status.upcoming', label: 'Stav „Nadcházející"', default: 'Nadcházející' },
        { key: 'web.layout.editRez.status.active', label: 'Stav „Probíhá"', default: 'Probíhá' },
        { key: 'web.layout.editRez.status.completed', label: 'Stav „Dokončeno"', default: 'Dokončeno' },
        { key: 'web.layout.editRez.status.cancelled', label: 'Stav „Zrušeno"', default: 'Zrušeno' },
      ]
    },
    {
      id: 'shopStatus', label: 'Stavy e-shop objednávek',
      fields: [
        { key: 'web.layout.editRez.shopStatus.new', label: 'E-shop „Nová"', default: 'Nová' },
        { key: 'web.layout.editRez.shopStatus.confirmed', label: 'E-shop „Potvrzená"', default: 'Potvrzená' },
        { key: 'web.layout.editRez.shopStatus.processing', label: 'E-shop „Zpracovává se"', default: 'Zpracovává se' },
        { key: 'web.layout.editRez.shopStatus.shipped', label: 'E-shop „Odeslána"', default: 'Odeslána' },
        { key: 'web.layout.editRez.shopStatus.delivered', label: 'E-shop „Doručena"', default: 'Doručena' },
        { key: 'web.layout.editRez.shopStatus.cancelled', label: 'E-shop „Zrušena"', default: 'Zrušena' },
        { key: 'web.layout.editRez.shopStatus.returned', label: 'E-shop „Vrácena"', default: 'Vrácena' },
        { key: 'web.layout.editRez.shopStatus.refunded', label: 'E-shop „Refundována"', default: 'Refundována' },
      ]
    },
    {
      id: 'voucherStatus', label: 'Stavy poukazů',
      fields: [
        { key: 'web.layout.editRez.voucherStatus.active', label: 'Poukaz „Aktivní"', default: 'Aktivní' },
        { key: 'web.layout.editRez.voucherStatus.redeemed', label: 'Poukaz „Uplatněn"', default: 'Uplatněn' },
        { key: 'web.layout.editRez.voucherStatus.expired', label: 'Poukaz „Expirován"', default: 'Expirován' },
        { key: 'web.layout.editRez.voucherStatus.cancelled', label: 'Poukaz „Zrušen"', default: 'Zrušen' },
      ]
    },
    {
      id: 'tabs', label: 'Záložky detailu rezervace',
      fields: [
        { key: 'web.layout.editRez.tab.detail', label: 'Záložka „Detail"', default: 'Detail' },
        { key: 'web.layout.editRez.tab.extend', label: 'Záložka „Prodloužit"', default: 'Prodloužit' },
        { key: 'web.layout.editRez.tab.shorten', label: 'Záložka „Zkrátit"', default: 'Zkrátit' },
        { key: 'web.layout.editRez.tab.cancel', label: 'Záložka „Storno"', default: 'Storno' },
        { key: 'web.layout.editRez.tab.moto', label: 'Záložka „Změna motorky"', default: 'Změna motorky' },
        { key: 'web.layout.editRez.tab.location', label: 'Záložka „Změna místa"', default: 'Změna místa' },
        { key: 'web.layout.editRez.tab.docs', label: 'Záložka „Doklady"', default: 'Doklady' },
      ]
    },
    {
      id: 'detail', label: 'Detail rezervace — popisky',
      fields: [
        { key: 'web.layout.editRez.detail.title', label: 'Nadpis „Detail rezervace"', default: 'Detail rezervace' },
        { key: 'web.layout.editRez.detail.bookingId', label: 'Label „Číslo rezervace"', default: 'Číslo rezervace' },
        { key: 'web.layout.editRez.detail.bookingNum', label: 'Label „Číslo rezervace" (alt)', default: 'Číslo rezervace' },
        { key: 'web.layout.editRez.detail.moto', label: 'Label „Motorka"', default: 'Motorka' },
        { key: 'web.layout.editRez.detail.dates', label: 'Label „Termín"', default: 'Termín' },
        { key: 'web.layout.editRez.detail.dateLabel', label: 'Label „Termín" (alt)', default: 'Termín' },
        { key: 'web.layout.editRez.detail.timeLabel', label: 'Label „Čas vyzvednutí / vrácení"', default: 'Čas vyzvednutí / vrácení' },
        { key: 'web.layout.editRez.detail.timeAtRental', label: 'Text „při vrácení v půjčovně"', default: 'při vrácení v půjčovně' },
        { key: 'web.layout.editRez.detail.pickup', label: 'Label „Vyzvednutí"', default: 'Vyzvednutí' },
        { key: 'web.layout.editRez.detail.return', label: 'Label „Vrácení"', default: 'Vrácení' },
        { key: 'web.layout.editRez.detail.pickupPlace', label: 'Label „Místo vyzvednutí"', default: 'Místo vyzvednutí' },
        { key: 'web.layout.editRez.detail.returnPlace', label: 'Label „Místo vrácení"', default: 'Místo vrácení' },
        { key: 'web.layout.editRez.detail.pickupShort', label: 'Krátký label „Vyzvednutí"', default: 'Vyzvednutí' },
        { key: 'web.layout.editRez.detail.deliveryShort', label: 'Krátký label „Přistavení"', default: 'Přistavení' },
        { key: 'web.layout.editRez.detail.deliveryAddr', label: 'Label „Přistavení na adresu:"', default: 'Přistavení na adresu:' },
        { key: 'web.layout.editRez.detail.pickupAtRental', label: 'Label „Vyzvednutí v půjčovně:"', default: 'Vyzvednutí v půjčovně:' },
        { key: 'web.layout.editRez.detail.returnAtAddr', label: 'Label „Vrácení na adrese:"', default: 'Vrácení na adrese:' },
        { key: 'web.layout.editRez.detail.returnAtRental', label: 'Label „Vrácení v půjčovně:"', default: 'Vrácení v půjčovně:' },
        { key: 'web.layout.editRez.detail.totalPaid', label: 'Label „Celkem zaplaceno"', default: 'Celkem zaplaceno' },
        { key: 'web.layout.editRez.detail.daysCount', label: 'Šablona „X dnů"', default: '{n} dnů', hint: '{n} = počet' },
        { key: 'web.layout.editRez.detail.dayCount.1', label: 'Pluralizace „1 den"', default: '{n} den' },
        { key: 'web.layout.editRez.detail.dayCount.few', label: 'Pluralizace „2-4 dny"', default: '{n} dny' },
        { key: 'web.layout.editRez.detail.dayCount.many', label: 'Pluralizace „5+ dní"', default: '{n} dní' },
        { key: 'web.layout.editRez.detail.priceBreakdown', label: 'Nadpis „Cenový rozpis"', default: 'Cenový rozpis' },
        { key: 'web.layout.editRez.detail.priceRental', label: 'Položka „Pronájem motorky"', default: 'Pronájem motorky' },
        { key: 'web.layout.editRez.detail.priceExtras', label: 'Položka „Příslušenství"', default: 'Příslušenství' },
        { key: 'web.layout.editRez.detail.priceDelivery', label: 'Položka „Přistavení / vrácení"', default: 'Přistavení / vrácení' },
        { key: 'web.layout.editRez.detail.priceDiscount', label: 'Položka „Sleva"', default: 'Sleva' },
        { key: 'web.layout.editRez.detail.priceTotal', label: 'Položka „Celkem zaplaceno"', default: 'Celkem zaplaceno' },
        { key: 'web.layout.editRez.detail.gearTitle', label: 'Nadpis „Výbava"', default: 'Výbava' },
        { key: 'web.layout.editRez.detail.gearRider', label: 'Štítek „Řidič"', default: 'Řidič' },
        { key: 'web.layout.editRez.detail.gearPassenger', label: 'Štítek „Spolujezdec"', default: 'Spolujezdec' },
        { key: 'web.layout.editRez.detail.licenseRequired', label: 'Šablona „Vyžaduje ŘP"', default: 'Vyžaduje ŘP: {lic}', hint: '{lic} = skupina ŘP' },
        { key: 'web.layout.editRez.detail.licenseNone', label: 'Štítek „Bez ŘP"', default: 'Bez ŘP' },
        { key: 'web.layout.editRez.detail.historyTitle', label: 'Nadpis „Historie úprav"', default: 'Historie úprav' },
      ]
    },
    {
      id: 'extend', label: 'Prodloužení rezervace',
      fields: [
        { key: 'web.layout.editRez.extend.title', label: 'Nadpis', default: 'Prodloužit rezervaci' },
        { key: 'web.layout.editRez.extend.help', label: 'Pomocný text (krátký)', type: 'textarea', default: 'V kalendáři klikněte na den před původním začátkem (vyzvednutí dříve) nebo na den po původním konci (vrácení později). Zaplatíte pouze rozdíl ceny.' },
        { key: 'web.layout.editRez.extend.helpUpcoming', label: 'Pomocný text (nadcházející)', type: 'textarea', default: 'V kalendáři klikněte na den před začátkem rezervace (vyzvednutí dříve) nebo na den po jejím konci (vrácení později). Můžete prodloužit obě strany — opětovným kliknutím na prodloužený okraj výběr zrušíte.' },
        { key: 'web.layout.editRez.extend.helpActive', label: 'Pomocný text (probíhající)', type: 'textarea', default: 'U probíhající rezervace lze prodloužit jen vrácení. V kalendáři klikněte na den po původním konci.' },
        { key: 'web.layout.editRez.extend.helpUpcomingLong', label: 'Pomocný text dlouhý (nadcházející)', type: 'textarea', default: 'V kalendáři klikněte na <strong>den před {start}</strong> (vyzvednutí dříve) <em>nebo</em> na <strong>den po {end}</strong> (vrácení později). Můžete prodloužit obě strany.', hint: '{start}, {end} = datumy rezervace' },
        { key: 'web.layout.editRez.extend.helpActiveLong', label: 'Pomocný text dlouhý (probíhající)', type: 'textarea', default: 'V kalendáři klikněte na <strong>den po {end}</strong> — prodlouží se vrácení o tento počet dní. Začátek ({start}) už nelze měnit, protože rezervace už běží.', hint: '{start}, {end} = datumy rezervace' },
        { key: 'web.layout.editRez.extend.newStart', label: 'Label „Nový začátek"', default: 'Nový začátek' },
        { key: 'web.layout.editRez.extend.newEnd', label: 'Label „Nový konec"', default: 'Nový konec' },
        { key: 'web.layout.editRez.extend.priceDiff', label: 'Label „Doplatek"', default: 'Doplatek' },
        { key: 'web.layout.editRez.extend.cta', label: 'Tlačítko „Prodloužit"', default: 'Pokračovat na platbu →' },
        { key: 'web.layout.editRez.extend.creating', label: 'Tlačítko „Zpracovávám…"', default: 'Vytvářím platbu…' },
        { key: 'web.layout.editRez.extend.unavailable', label: 'Hláška „Není dostupné"', default: 'V požadovaném termínu motorka není dostupná. Zvolte prosím jiný termín.' },
        { key: 'web.layout.editRez.extend.noChange', label: 'Hláška „Žádná změna"', default: 'Vyberte prosím nové datumy.' },
        { key: 'web.layout.editRez.extend.addedDays', label: 'Banner „Přidané dny:"', default: 'Přidané dny:' },
      ]
    },
    {
      id: 'shorten', label: 'Zkrácení rezervace',
      fields: [
        { key: 'web.layout.editRez.shorten.title', label: 'Nadpis', default: 'Zkrátit rezervaci' },
        { key: 'web.layout.editRez.shorten.help', label: 'Pomocný text (krátký)', type: 'textarea', default: 'Vyberte stranu (Začátek nebo Konec) a v kalendáři klikněte uvnitř rezervace na nový den. Vracíme peníze podle storno podmínek.' },
        { key: 'web.layout.editRez.shorten.helpUpcoming', label: 'Pomocný text (nadcházející)', type: 'textarea', default: 'Vyberte tlačítkem nahoře, jestli chcete zkrátit Začátek (pozdější vyzvednutí) nebo Konec (dřívější vrácení). Pak v kalendáři klikněte uvnitř rezervace na nový den. Opětovný klik na zkrácený okraj výběr zruší.' },
        { key: 'web.layout.editRez.shorten.helpActive', label: 'Pomocný text (probíhající)', type: 'textarea', default: 'U probíhající rezervace lze zkrátit jen vrácení. V kalendáři klikněte na den před původním koncem (a ne dříve než dnešek).' },
        { key: 'web.layout.editRez.shorten.helpUpcomingLong', label: 'Pomocný text dlouhý (nadcházející)', type: 'textarea', default: 'Vyberte stranu, kterou chcete zkrátit (Začátek = pozdější vyzvednutí, Konec = dřívější vrácení), pak klikněte v kalendáři uvnitř rezervace na nový den. Refund podle storno podmínek.' },
        { key: 'web.layout.editRez.shorten.helpActiveLong', label: 'Pomocný text dlouhý (probíhající)', type: 'textarea', default: 'V kalendáři klikněte na <strong>den před {end}</strong> — vrátíte motorku dříve. Začátek ({start}) už nelze měnit, protože rezervace běží. Refund podle storno podmínek.', hint: '{start}, {end} = datumy rezervace' },
        { key: 'web.layout.editRez.shorten.dirStart', label: 'Tlačítko „Zkrátit začátek"', default: '← Zkrátit začátek' },
        { key: 'web.layout.editRez.shorten.dirEnd', label: 'Tlačítko „Zkrátit konec"', default: 'Zkrátit konec →' },
        { key: 'web.layout.editRez.shorten.refund', label: 'Šablona „Vrátíme {amount}"', default: 'Vrátíme {amount} ({percent}%)', hint: '{amount}, {percent}' },
        { key: 'web.layout.editRez.shorten.refundZero', label: 'Hláška „Bez nároku na refund"', type: 'textarea', default: '0 Kč — méně než 48 hodin do termínu, refund dle storno podmínek nelze. Rezervaci ale můžete zkrátit i tak.' },
        { key: 'web.layout.editRez.shorten.cta', label: 'Tlačítko „Zkrátit a vrátit peníze"', default: 'Zkrátit a vrátit peníze' },
        { key: 'web.layout.editRez.shorten.ctaNoRefund', label: 'Tlačítko „Zkrátit (bez refundu)"', default: 'Zkrátit (bez vrácení peněz)' },
        { key: 'web.layout.editRez.shorten.confirming', label: 'Tlačítko „Zkracuji…"', default: 'Zkracuji…' },
        { key: 'web.layout.editRez.shorten.success', label: 'Hláška úspěchu (s refundem)', default: 'Rezervace zkrácena. Vrácení {amount} Kč ({percent}%) na původní platební metodu.' },
        { key: 'web.layout.editRez.shorten.successNoRefund', label: 'Hláška úspěchu (bez refundu)', default: 'Rezervace zkrácena. Refund dle storno podmínek nebyl možný.' },
        { key: 'web.layout.editRez.shorten.reasonLabel', label: 'Label „Důvod (volitelné)"', default: 'Důvod (volitelné)' },
      ]
    },
    {
      id: 'cancel', label: 'Storno rezervace',
      fields: [
        { key: 'web.layout.editRez.cancel.title', label: 'Nadpis', default: 'Zrušit rezervaci' },
        { key: 'web.layout.editRez.cancel.warn', label: 'Varování', type: 'textarea', default: 'Tuto akci nelze vrátit. Po zrušení bude rezervace stornována a vrátíme peníze podle storno podmínek.' },
        { key: 'web.layout.editRez.cancel.refundLabel', label: 'Label „Vrátíme"', default: 'Vrátíme' },
        { key: 'web.layout.editRez.cancel.reasonLabel', label: 'Label „Důvod (volitelné)"', default: 'Důvod zrušení (volitelné)' },
        { key: 'web.layout.editRez.cancel.reasonPlaceholder', label: 'Placeholder „Důvod"', default: 'Např. změna plánů' },
        { key: 'web.layout.editRez.cancel.cta', label: 'Tlačítko „Stornovat"', default: 'Stornovat rezervaci' },
        { key: 'web.layout.editRez.cancel.confirming', label: 'Tlačítko „Stornuji…"', default: 'Stornuji…' },
        { key: 'web.layout.editRez.cancel.success', label: 'Hláška úspěchu', default: 'Rezervace byla stornována. Vrácení {amount} Kč ({percent}%) proběhne během několika minut.' },
        { key: 'web.layout.editRez.cancel.confirmTitle', label: 'Potvrzovací dialog — nadpis', default: 'Opravdu chcete stornovat rezervaci?' },
        { key: 'web.layout.editRez.cancel.confirmYes', label: 'Tlačítko „Ano, stornovat"', default: 'Ano, stornovat' },
        { key: 'web.layout.editRez.cancel.confirmNo', label: 'Tlačítko „Zrušit"', default: 'Zrušit' },
      ]
    },
    {
      id: 'storno', label: 'Storno podmínky (popis)',
      fields: [
        { key: 'web.layout.editRez.storno.title', label: 'Nadpis', default: 'Storno podmínky' },
        { key: 'web.layout.editRez.storno.tier1', label: 'Tier 1 — popis', type: 'textarea', default: '<strong>Více než 7 dní</strong> před začátkem: <strong>100 %</strong> vrácení' },
        { key: 'web.layout.editRez.storno.tier2', label: 'Tier 2 — popis', type: 'textarea', default: '<strong>2 až 7 dní</strong> před začátkem: <strong>50 %</strong> vrácení' },
        { key: 'web.layout.editRez.storno.tier3', label: 'Tier 3 — popis', type: 'textarea', default: '<strong>Méně než 2 dny</strong> před začátkem: <strong>nevratné</strong> (0 %)' },
        { key: 'web.layout.editRez.storno.note', label: 'Poznámka', type: 'textarea', default: 'Vrácení proběhne automaticky na původní platební metodu (kartu).' },
      ]
    },
    {
      id: 'moto_change', label: 'Změna motorky',
      fields: [
        { key: 'web.layout.editRez.moto.title', label: 'Nadpis', default: 'Změnit motorku' },
        { key: 'web.layout.editRez.moto.help', label: 'Pomocný text', type: 'textarea', default: 'Vyberte jinou motorku pro váš termín. Lze pouze pro nadcházející rezervace s odpovídajícím řidičským průkazem. Zaplatí se pouze rozdíl ceny.' },
        { key: 'web.layout.editRez.moto.intro', label: 'Úvod', type: 'textarea', default: 'Vyberte si jinou motorku z naší flotily — zobrazujeme všechny dostupné v daném termínu, kompatibilní s vaším řidičským oprávněním.' },
        { key: 'web.layout.editRez.moto.loading', label: 'Načítání', default: 'Načítám flotilu…' },
        { key: 'web.layout.editRez.moto.licReq', label: 'Šablona „ŘP: {lic}"', default: 'ŘP: {lic}' },
        { key: 'web.layout.editRez.moto.licPill', label: 'Štítek „ŘP {lic}"', default: 'ŘP {lic}' },
        { key: 'web.layout.editRez.moto.noLicPill', label: 'Štítek „Bez ŘP"', default: 'Bez ŘP' },
        { key: 'web.layout.editRez.moto.samePrice', label: 'Štítek „Stejná cena"', default: 'Stejná cena' },
        { key: 'web.layout.editRez.moto.diffRefund', label: 'Šablona „{amount} (vrátíme)"', default: '{amount} (vrátíme)' },
        { key: 'web.layout.editRez.moto.diffUp', label: 'Šablona „+{amount} za celou rezervaci"', default: '+{amount} za celou rezervaci' },
        { key: 'web.layout.editRez.moto.priceTotal', label: 'Štítek „celkem"', default: 'celkem' },
        { key: 'web.layout.editRez.moto.priceVs', label: 'Štítek „vs."', default: 'vs.' },
        { key: 'web.layout.editRez.moto.reasonLicense', label: 'Důvod „Nedostatečné ŘP"', default: '🚫 Nedostatečné ŘP' },
        { key: 'web.layout.editRez.moto.reasonOccupied', label: 'Důvod „V termínu obsazené"', default: '📅 V termínu obsazené' },
        { key: 'web.layout.editRez.moto.unavailable', label: 'Štítek „Nedostupné"', default: 'Nedostupné' },
        { key: 'web.layout.editRez.moto.noOptions', label: 'Hláška „Žádné varianty"', default: 'Žádné jiné motorky nejsou k dispozici.' },
        { key: 'web.layout.editRez.moto.confirm', label: 'Hláška „Změnit?"', default: 'Změnit na vybranou motorku?' },
        { key: 'web.layout.editRez.moto.selectThis', label: 'Tlačítko „Vybrat tuto motorku"', default: 'Vybrat tuto motorku →' },
        { key: 'web.layout.editRez.moto.licenseInsufficient', label: 'Hláška „Nemáte ŘP"', default: 'Nedostatečný řidičský průkaz' },
        { key: 'web.layout.editRez.moto.notAvailable', label: 'Hláška „V termínu obsazeno"', default: 'V termínu obsazeno' },
        { key: 'web.layout.editRez.moto.backToDetail', label: 'Odkaz „Zpět na detail"', default: '← Zpět na detail' },
        { key: 'web.layout.editRez.moto.confirmTitle', label: 'Potvrzení nadpis', default: 'Změnit motorku na {name}?' },
        { key: 'web.layout.editRez.moto.confirmYes', label: 'Tlačítko „Ano, změnit"', default: 'Ano, změnit motorku' },
        { key: 'web.layout.editRez.moto.confirmNo', label: 'Tlačítko „Ne, ponechat"', default: 'Ne, ponechat' },
      ]
    },
    {
      id: 'location', label: 'Změna místa vyzvednutí / vrácení',
      fields: [
        { key: 'web.layout.editRez.loc.title', label: 'Nadpis', default: 'Změnit místo vyzvednutí / vrácení' },
        { key: 'web.layout.editRez.loc.help', label: 'Pomocný text', type: 'textarea', default: 'Změnte způsob a místo vyzvednutí nebo vrácení. Cena za přistavení/odvoz se vrací 100 % bez ohledu na čas; nová cena se doplatí přes Stripe nebo se vrátí přeplatek.' },
        { key: 'web.layout.editRez.loc.pickup', label: 'Label „Vyzvednutí"', default: 'Vyzvednutí' },
        { key: 'web.layout.editRez.loc.return', label: 'Label „Vrácení"', default: 'Vrácení' },
        { key: 'web.layout.editRez.loc.headPickup', label: 'Hlavička „Vyzvednutí motorky"', default: '📥 Vyzvednutí motorky' },
        { key: 'web.layout.editRez.loc.headReturn', label: 'Hlavička „Vrácení motorky"', default: '📤 Vrácení motorky' },
        { key: 'web.layout.editRez.loc.atRental', label: 'Možnost „V půjčovně"', default: 'V půjčovně Mezná 9, 393 01 Mezná' },
        { key: 'web.layout.editRez.loc.atRentalTitle', label: 'Karta „V půjčovně Mezná"', default: 'V půjčovně Mezná' },
        { key: 'web.layout.editRez.loc.atRentalDescPickup', label: 'Popis (vyzvednutí v půjčovně)', type: 'textarea', default: 'Mezná 9, 257 87 — autonomní pobočka, otevřeno nonstop. <strong>0 Kč.</strong>' },
        { key: 'web.layout.editRez.loc.atRentalDescReturn', label: 'Popis (vrácení v půjčovně)', type: 'textarea', default: 'Vrátíte v autonomní pobočce. <strong>0 Kč.</strong>' },
        { key: 'web.layout.editRez.loc.delivery', label: 'Možnost „Přistavení"', default: 'Přistavení na adresu' },
        { key: 'web.layout.editRez.loc.deliveryReturn', label: 'Možnost „Odvoz z adresy"', default: 'Odvoz z adresy' },
        { key: 'web.layout.editRez.loc.deliveryTitle', label: 'Karta „Přistavení na adresu"', default: 'Přistavení na adresu' },
        { key: 'web.layout.editRez.loc.deliveryReturnTitle', label: 'Karta „Vyzvedneme od vás"', default: 'Vyzvedneme od vás' },
        { key: 'web.layout.editRez.loc.deliveryDescPickup', label: 'Popis (přistavení)', type: 'textarea', default: '<strong>1 000 Kč + 40 Kč/km</strong> z Mezné. Cena se vypočte automaticky z trasy.' },
        { key: 'web.layout.editRez.loc.deliveryDescReturn', label: 'Popis (odvoz)', type: 'textarea', default: '<strong>1 000 Kč + 40 Kč/km</strong> z Mezné. Cena se vypočte automaticky.' },
        { key: 'web.layout.editRez.loc.addrPlaceholder', label: 'Placeholder adresy', default: 'Zadejte adresu (ulice, město)' },
        { key: 'web.layout.editRez.loc.mapBtn', label: 'Tlačítko „Vybrat na mapě"', default: 'Vybrat na mapě' },
        { key: 'web.layout.editRez.loc.pickOnMapBtn', label: 'Tlačítko „Vybrat na mapě" (alt)', default: '📍 Vybrat na mapě' },
        { key: 'web.layout.editRez.loc.pickOnMap', label: 'Hláška „Vyberte místo na mapě"', default: 'Vyberte místo na mapě' },
        { key: 'web.layout.editRez.loc.pickConfirm', label: 'Tlačítko „Potvrdit"', default: 'Potvrdit' },
        { key: 'web.layout.editRez.loc.routing', label: 'Hláška „Počítám trasu…"', default: 'Počítám trasu od pobočky Mezná…' },
        { key: 'web.layout.editRez.loc.routeSummary', label: 'Souhrn trasy', type: 'textarea', default: '<strong>{km} km</strong> z Mezné · {kmInt} × 40 Kč + 1 000 Kč = <strong>{fee}</strong>' },
        { key: 'web.layout.editRez.loc.geocodeFail', label: 'Hláška „Adresa nenalezena"', default: 'Adresu se nepodařilo najít. Zkuste přesnější zadání.' },
        { key: 'web.layout.editRez.loc.noPriceChange', label: 'Hláška „Beze změny ceny"', default: 'Beze změny ceny.' },
        { key: 'web.layout.editRez.loc.cta', label: 'Tlačítko „Uložit změnu"', default: 'Uložit změnu' },
        { key: 'web.layout.editRez.loc.confirm', label: 'Hláška „Uložit změnu?"', default: 'Uložit změnu?' },
        { key: 'web.layout.editRez.loc.timesTitle', label: 'Nadpis „Časy vyzvednutí a vrácení"', default: 'Časy vyzvednutí a vrácení' },
        { key: 'web.layout.editRez.loc.timesHelp', label: 'Pomocný text k časům', type: 'textarea', default: 'Změna času je zdarma — pokud měníte jen čas, žádný doplatek.' },
        { key: 'web.layout.editRez.loc.pickupTime', label: 'Label „Čas vyzvednutí"', default: 'Čas vyzvednutí' },
        { key: 'web.layout.editRez.loc.returnTime', label: 'Label „Čas vrácení"', default: 'Čas vrácení' },
        { key: 'web.layout.editRez.loc.timeOnly', label: 'Štítek „Změna času (zdarma)"', default: 'Změna času (zdarma)' },
        { key: 'web.layout.editRez.loc.calc.pickupOrig', label: 'Kalkulace — Vyzvednutí původní', default: 'Vyzvednutí — původní' },
        { key: 'web.layout.editRez.loc.calc.pickupNew', label: 'Kalkulace — Vyzvednutí nové', default: 'Vyzvednutí — nové' },
        { key: 'web.layout.editRez.loc.calc.returnOrig', label: 'Kalkulace — Vrácení původní', default: 'Vrácení — původní' },
        { key: 'web.layout.editRez.loc.calc.returnNew', label: 'Kalkulace — Vrácení nové', default: 'Vrácení — nové' },
        { key: 'web.layout.editRez.loc.calc.atRentalShort', label: 'Kalkulace — V půjčovně (0 Kč)', default: 'V půjčovně (0 Kč)' },
        { key: 'web.layout.editRez.loc.calc.kmFormula', label: 'Kalkulace — vzorec km', default: '{km} km × 40 Kč + 1 000 Kč = ' },
        { key: 'web.layout.editRez.loc.calc.surcharge', label: 'Kalkulace — Doplatek', default: 'Doplatek' },
        { key: 'web.layout.editRez.loc.calc.surchargeStripe', label: 'Kalkulace — Doplatek (Stripe)', default: 'Doplatek (Stripe)' },
        { key: 'web.layout.editRez.loc.calc.refund', label: 'Kalkulace — Vrátíme', default: 'Vrátíme' },
        { key: 'web.layout.editRez.loc.calc.noChange', label: 'Kalkulace — Bez změny', default: 'Bez změny ceny' },
        { key: 'web.layout.editRez.loc.calc.verifying', label: 'Kalkulace — „Ověřuji…"', default: 'Ověřuji u serveru…' },
      ]
    },
    {
      id: 'docs', label: 'Doklady (sekce + uploader)',
      fields: [
        { key: 'web.layout.editRez.doc.title', label: 'Nadpis', default: 'Doklady ke stažení' },
        { key: 'web.layout.editRez.doc.help', label: 'Pomocný text', type: 'textarea', default: 'Všechny doklady k vaší rezervaci si můžete kdykoliv stáhnout.' },
        { key: 'web.layout.editRez.doc.empty', label: 'Hláška „Žádné dokumenty"', default: 'K této objednávce zatím nejsou doklady.' },
        { key: 'web.layout.editRez.doc.download', label: 'Tlačítko „Stáhnout"', default: 'Stáhnout PDF' },
        { key: 'web.layout.editRez.doc.notAvailable', label: 'Hláška „Není k dispozici"', default: 'Doklad není momentálně dostupný.' },
        { key: 'web.layout.editRez.doc.close', label: 'Tlačítko „Zavřít"', default: 'Zavřít' },
        { key: 'web.layout.editRez.doc.uploadTitle', label: 'Nadpis „Nahrát doklady"', default: 'Nahrát / aktualizovat doklady' },
        { key: 'web.layout.editRez.doc.uploadHelp', label: 'Pomocný text k nahrávání', type: 'textarea', default: 'Nahrajte občanku/pas a řidičák — sken proběhne přes Mindee OCR. Bez ověřených dokladů systém nevydá přístupové kódy k motorce.' },
        { key: 'web.layout.editRez.doc.idLabel', label: 'Label „Občanka / pas"', default: 'Občanka / pas' },
        { key: 'web.layout.editRez.doc.licenseLabel', label: 'Label „Řidičský průkaz"', default: 'Řidičský průkaz' },
        { key: 'web.layout.editRez.doc.uploadBtn', label: 'Tlačítko „Nahrát"', default: 'Nahrát' },
        { key: 'web.layout.editRez.doc.updateBtn', label: 'Tlačítko „Aktualizovat"', default: 'Aktualizovat' },
        { key: 'web.layout.editRez.doc.archiveTitle', label: 'Nadpis „Doklady ke stažení"', default: 'Doklady ke stažení' },
      ]
    },
    {
      id: 'docTypes', label: 'Doklady — názvy typů',
      fields: [
        { key: 'web.layout.editRez.doc.type.proforma', label: 'Typ „Zálohová faktura"', default: 'Zálohová faktura' },
        { key: 'web.layout.editRez.doc.type.advance', label: 'Typ „Zálohová faktura" (advance)', default: 'Zálohová faktura' },
        { key: 'web.layout.editRez.doc.type.invoice_advance', label: 'Typ „Zálohová faktura" (invoice_advance)', default: 'Zálohová faktura' },
        { key: 'web.layout.editRez.doc.type.final', label: 'Typ „Konečná faktura"', default: 'Konečná faktura' },
        { key: 'web.layout.editRez.doc.type.issued', label: 'Typ „Konečná faktura" (issued)', default: 'Konečná faktura' },
        { key: 'web.layout.editRez.doc.type.invoice_final', label: 'Typ „Konečná faktura" (invoice_final)', default: 'Konečná faktura' },
        { key: 'web.layout.editRez.doc.type.payment_receipt', label: 'Typ „Platební doklad"', default: 'Platební doklad' },
        { key: 'web.layout.editRez.doc.type.shop_proforma', label: 'Typ „Zálohová faktura (e-shop)"', default: 'Zálohová faktura (e-shop)' },
        { key: 'web.layout.editRez.doc.type.shop_final', label: 'Typ „Daňový doklad (e-shop)"', default: 'Daňový doklad (e-shop)' },
        { key: 'web.layout.editRez.doc.type.invoice_shop', label: 'Typ „Daňový doklad (e-shop)" (invoice_shop)', default: 'Daňový doklad (e-shop)' },
        { key: 'web.layout.editRez.doc.type.credit_note', label: 'Typ „Dobropis"', default: 'Dobropis' },
        { key: 'web.layout.editRez.doc.type.contract', label: 'Typ „Smlouva o pronájmu"', default: 'Smlouva o pronájmu' },
        { key: 'web.layout.editRez.doc.type.rental_contract', label: 'Typ „Smlouva o pronájmu" (rental_contract)', default: 'Smlouva o pronájmu' },
        { key: 'web.layout.editRez.doc.type.vop', label: 'Typ „VOP"', default: 'VOP' },
        { key: 'web.layout.editRez.doc.type.protocol', label: 'Typ „Předávací protokol"', default: 'Předávací protokol' },
        { key: 'web.layout.editRez.doc.type.handover_protocol', label: 'Typ „Předávací protokol" (handover_protocol)', default: 'Předávací protokol' },
        { key: 'web.layout.editRez.doc.type.unknown', label: 'Typ „Doklad" (fallback)', default: 'Doklad' },
      ]
    },
    {
      id: 'pending', label: 'Nezaplacená rezervace (varování)',
      fields: [
        { key: 'web.layout.editRez.pending.title', label: 'Nadpis', default: 'Rezervace čeká na zaplacení' },
        { key: 'web.layout.editRez.pending.text', label: 'Text', type: 'textarea', default: 'Tato rezervace ještě nebyla potvrzena platbou. Dokud nezaplatíte, motorka pro vás není rezervována. Úpravy (datum, motorka, místo) půjdou až po dokončení platby.' },
        { key: 'web.layout.editRez.pending.payNow', label: 'Tlačítko „Zaplatit"', default: '💳 Pokračovat k platbě' },
        { key: 'web.layout.editRez.pending.cancelNow', label: 'Tlačítko „Zrušit"', default: 'Zrušit rezervaci' },
        { key: 'web.layout.editRez.pending.confirmCancel', label: 'Potvrzovací dialog — text', default: 'Opravdu chcete zrušit nezaplacenou rezervaci?' },
        { key: 'web.layout.editRez.pending.confirmYes', label: 'Tlačítko „Ano, zrušit"', default: 'Ano, zrušit' },
        { key: 'web.layout.editRez.pending.confirmNo', label: 'Tlačítko „Ne, ponechat"', default: 'Ne, ponechat' },
        { key: 'web.layout.editRez.pending.cancelReason', label: 'Důvod zrušení (interní)', default: 'Zrušeno zákazníkem před zaplacením' },
      ]
    },
    {
      id: 'consents', label: 'Souhlasy (GDPR / VOP / marketing)',
      fields: [
        { key: 'web.layout.editRez.consents.cardTitle', label: 'Nadpis sekce', default: 'Souhlasy a komunikace' },
        { key: 'web.layout.editRez.consents.help', label: 'Pomocný text', type: 'textarea', default: 'Změny se ukládají automaticky. Souhlasy potřebné pro rezervaci nelze odvolat během nadcházející nebo aktivní rezervace — volně lze kdykoliv odvolat pouze marketing.' },
        { key: 'web.layout.editRez.consents.required', label: 'Štítek „Povinné"', default: 'Povinné' },
        { key: 'web.layout.editRez.consents.optional', label: 'Štítek „Volitelné"', default: 'Volitelné' },
        { key: 'web.layout.editRez.consents.sectionRequired', label: 'Sekce „Povinné pro rezervaci"', default: 'Povinné pro rezervaci' },
        { key: 'web.layout.editRez.consents.sectionOptional', label: 'Sekce „Volitelné — komunikace a marketing"', default: 'Volitelné — komunikace a marketing' },
        { key: 'web.layout.editRez.consents.toggleYes', label: 'Toggle „Ano"', default: 'Ano' },
        { key: 'web.layout.editRez.consents.toggleNo', label: 'Toggle „Ne"', default: 'Ne' },
        { key: 'web.layout.editRez.consents.grantAll', label: 'Tlačítko „Přijmout vše"', default: '✓ Přijmout vše' },
        { key: 'web.layout.editRez.consents.revokeAll', label: 'Tlačítko „Odvolat vše"', default: 'Odvolat vše' },
        { key: 'web.layout.editRez.consents.confirmRevoke', label: 'Potvrzovací dialog — text', default: 'Opravdu chcete odvolat všechny souhlasy?' },
        { key: 'web.layout.editRez.consents.confirmYes', label: 'Tlačítko „Odvolat vše" (potvrzení)', default: 'Odvolat vše' },
        { key: 'web.layout.editRez.consents.confirmNo', label: 'Tlačítko „Zachovat"', default: 'Zachovat' },
        { key: 'web.layout.editRez.consents.lockedBadge', label: 'Štítek „Uzamčeno"', default: 'Uzamčeno' },
        { key: 'web.layout.editRez.consents.lockedHint', label: 'Hint „Uzamčeno"', type: 'textarea', default: 'Souhlas nelze odvolat během nadcházející nebo aktivní rezervace.' },
        { key: 'web.layout.editRez.consents.lockedRevokeBlocked', label: 'Hláška „Nelze odvolat"', type: 'textarea', default: 'Tento souhlas nelze odvolat během nadcházející nebo aktivní rezervace. Volně lze odvolat pouze marketing.' },
        { key: 'web.layout.editRez.consents.activeBookingNote', label: 'Poznámka u aktivní rezervace', type: 'textarea', default: 'Máte nadcházející nebo aktivní rezervaci. Souhlasy potřebné k provozu rezervace (komunikace, foto dokladů, GDPR, VOP, smlouva) jsou uzamčené až do dokončení nebo zrušení rezervace. Volně lze kdykoliv odvolat pouze marketing.' },
        { key: 'web.layout.editRez.consents.granted', label: 'Toast „Souhlas udělen"', default: 'Souhlas udělen.' },
        { key: 'web.layout.editRez.consents.revoked', label: 'Toast „Souhlas odvolán"', default: 'Souhlas odvolán.' },
        { key: 'web.layout.editRez.consents.allGranted', label: 'Toast „Všechny souhlasy uděleny"', default: 'Všechny souhlasy uděleny.' },
        { key: 'web.layout.editRez.consents.allRevoked', label: 'Toast „Všechny souhlasy odvolány"', default: 'Všechny souhlasy odvolány.' },
        { key: 'web.layout.editRez.consents.marketingRevoked', label: 'Toast „Marketing odvolán"', type: 'textarea', default: 'Odvolán marketingový souhlas. Ostatní souhlasy zůstávají kvůli nadcházející rezervaci.' },
        { key: 'web.layout.editRez.consents.saveError', label: 'Chyba uložení (jeden)', default: 'Nepodařilo se uložit souhlas.' },
        { key: 'web.layout.editRez.consents.saveErrorPlural', label: 'Chyba uložení (více)', default: 'Nepodařilo se uložit souhlasy.' },
      ]
    },
    {
      id: 'consentItems', label: 'Souhlasy — jednotlivé položky',
      fields: [
        { key: 'web.layout.editRez.consents.label.gdpr', label: 'GDPR — název', default: 'GDPR' },
        { key: 'web.layout.editRez.consents.desc.gdpr', label: 'GDPR — popis', type: 'textarea', default: 'Souhlas se zpracováním osobních údajů.' },
        { key: 'web.layout.editRez.consents.label.vop', label: 'VOP — název', default: 'VOP' },
        { key: 'web.layout.editRez.consents.desc.vop', label: 'VOP — popis', type: 'textarea', default: 'Všeobecné obchodní podmínky.' },
        { key: 'web.layout.editRez.consents.label.contract', label: 'Smlouva — název', default: 'Nájemní smlouva' },
        { key: 'web.layout.editRez.consents.desc.contract', label: 'Smlouva — popis', type: 'textarea', default: 'Souhlas s návrhem nájemní smlouvy MotoGo24.' },
        { key: 'web.layout.editRez.consents.label.dataProcessing', label: 'Zpracování dat — název', default: 'Zpracování dat' },
        { key: 'web.layout.editRez.consents.desc.dataProcessing', label: 'Zpracování dat — popis', type: 'textarea', default: 'Souhlas se zpracováním dat pro plnění smlouvy.' },
        { key: 'web.layout.editRez.consents.label.marketing', label: 'Marketing — název', default: 'Marketing' },
        { key: 'web.layout.editRez.consents.desc.marketing', label: 'Marketing — popis', type: 'textarea', default: 'Newslettery, slevové akce a novinky.' },
        { key: 'web.layout.editRez.consents.label.email', label: 'E-mail — název', default: 'Email' },
        { key: 'web.layout.editRez.consents.desc.email', label: 'E-mail — popis', type: 'textarea', default: 'Komunikace e-mailem (potvrzení, faktury, smlouvy).' },
        { key: 'web.layout.editRez.consents.label.sms', label: 'SMS — název', default: 'SMS' },
        { key: 'web.layout.editRez.consents.desc.sms', label: 'SMS — popis', type: 'textarea', default: 'Komunikace přes SMS (přístupové kódy, urgentní upozornění).' },
        { key: 'web.layout.editRez.consents.label.whatsapp', label: 'WhatsApp — název', default: 'WhatsApp' },
        { key: 'web.layout.editRez.consents.desc.whatsapp', label: 'WhatsApp — popis', type: 'textarea', default: 'Komunikace přes WhatsApp.' },
        { key: 'web.layout.editRez.consents.label.push', label: 'Push — název', default: 'Push' },
        { key: 'web.layout.editRez.consents.desc.push', label: 'Push — popis', type: 'textarea', default: 'Push notifikace v aplikaci MotoGo24.' },
        { key: 'web.layout.editRez.consents.label.photo', label: 'Foto dokladů — název', default: 'Foto dokladů' },
        { key: 'web.layout.editRez.consents.desc.photo', label: 'Foto dokladů — popis', type: 'textarea', default: 'Fotografování dokladů přes Mindee OCR pro autonomní pobočku.' },
      ]
    },
    {
      id: 'history', label: 'Historie úprav',
      fields: [
        { key: 'web.layout.editRez.history.empty', label: 'Hláška „Žádná historie"', default: 'Rezervace ještě nebyla upravována.' },
        { key: 'web.layout.editRez.history.startChanged', label: 'Záznam „Začátek změněn"', default: '📅 Začátek: <s>{from}</s> → <strong>{to}</strong>' },
        { key: 'web.layout.editRez.history.endChanged', label: 'Záznam „Konec změněn"', default: '📅 Konec: <s>{from}</s> → <strong>{to}</strong>' },
        { key: 'web.layout.editRez.history.motoChanged', label: 'Záznam „Motorka změněna"', default: '🏍️ Motorka byla změněna' },
        { key: 'web.layout.editRez.history.locationChanged', label: 'Záznam „Místo změněno"', default: '📍 Změna místa vyzvednutí / vrácení' },
        { key: 'web.layout.editRez.history.generic', label: 'Záznam „Úprava"', default: 'Úprava rezervace' },
        { key: 'web.layout.editRez.history.sourceWeb', label: 'Zdroj „Z webu"', default: 'Z webu' },
        { key: 'web.layout.editRez.history.sourceApp', label: 'Zdroj „Z aplikace"', default: 'Z aplikace' },
        { key: 'web.layout.editRez.history.sourceAdmin', label: 'Zdroj „Admin"', default: 'Admin' },
        { key: 'web.layout.editRez.history.sourceSystem', label: 'Zdroj „Vytvoření"', default: 'Vytvoření' },
      ]
    },
    {
      id: 'calendar', label: 'Kalendář — měsíce, dny, legenda',
      fields: [
        { key: 'web.layout.editRez.cal.month.1', label: 'Leden', default: 'Leden' },
        { key: 'web.layout.editRez.cal.month.2', label: 'Únor', default: 'Únor' },
        { key: 'web.layout.editRez.cal.month.3', label: 'Březen', default: 'Březen' },
        { key: 'web.layout.editRez.cal.month.4', label: 'Duben', default: 'Duben' },
        { key: 'web.layout.editRez.cal.month.5', label: 'Květen', default: 'Květen' },
        { key: 'web.layout.editRez.cal.month.6', label: 'Červen', default: 'Červen' },
        { key: 'web.layout.editRez.cal.month.7', label: 'Červenec', default: 'Červenec' },
        { key: 'web.layout.editRez.cal.month.8', label: 'Srpen', default: 'Srpen' },
        { key: 'web.layout.editRez.cal.month.9', label: 'Září', default: 'Září' },
        { key: 'web.layout.editRez.cal.month.10', label: 'Říjen', default: 'Říjen' },
        { key: 'web.layout.editRez.cal.month.11', label: 'Listopad', default: 'Listopad' },
        { key: 'web.layout.editRez.cal.month.12', label: 'Prosinec', default: 'Prosinec' },
        { key: 'web.layout.editRez.cal.dow.1', label: 'DOW Po', default: 'Po' },
        { key: 'web.layout.editRez.cal.dow.2', label: 'DOW Út', default: 'Út' },
        { key: 'web.layout.editRez.cal.dow.3', label: 'DOW St', default: 'St' },
        { key: 'web.layout.editRez.cal.dow.4', label: 'DOW Čt', default: 'Čt' },
        { key: 'web.layout.editRez.cal.dow.5', label: 'DOW Pá', default: 'Pá' },
        { key: 'web.layout.editRez.cal.dow.6', label: 'DOW So', default: 'So' },
        { key: 'web.layout.editRez.cal.dow.7', label: 'DOW Ne', default: 'Ne' },
        { key: 'web.layout.editRez.cal.prev', label: 'Tlačítko „Předchozí měsíc"', default: 'Předchozí měsíc' },
        { key: 'web.layout.editRez.cal.next', label: 'Tlačítko „Další měsíc"', default: 'Další měsíc' },
        { key: 'web.layout.editRez.cal.locked', label: 'Štítek „(zamčeno)"', default: '(zamčeno)' },
        { key: 'web.layout.editRez.cal.newRange', label: 'Banner „Nový termín:"', default: 'Nový termín:' },
        { key: 'web.layout.editRez.cal.clear', label: 'Tlačítko „Zrušit"', default: '✕ Zrušit' },
        { key: 'web.layout.editRez.cal.legend.kept', label: 'Legenda „Zachováno"', default: 'Zachováno' },
        { key: 'web.layout.editRez.cal.legend.removed', label: 'Legenda „Zkráceno"', default: 'Zkráceno' },
        { key: 'web.layout.editRez.cal.legend.outOfBooking', label: 'Legenda „Mimo rezervaci"', default: 'Mimo rezervaci' },
        { key: 'web.layout.editRez.cal.legend.free', label: 'Legenda „Volné"', default: 'Volné' },
        { key: 'web.layout.editRez.cal.legend.thisBooking', label: 'Legenda „Tato rezervace"', default: 'Tato rezervace' },
        { key: 'web.layout.editRez.cal.legend.extension', label: 'Legenda „Prodloužení"', default: 'Prodloužení' },
        { key: 'web.layout.editRez.cal.legend.occupied', label: 'Legenda „Obsazené"', default: 'Obsazené' },
        { key: 'web.layout.dow.short.0', label: 'Krátce „Ne" (0)', default: 'Ne' },
        { key: 'web.layout.dow.short.1', label: 'Krátce „Po" (1)', default: 'Po' },
        { key: 'web.layout.dow.short.2', label: 'Krátce „Út" (2)', default: 'Út' },
        { key: 'web.layout.dow.short.3', label: 'Krátce „St" (3)', default: 'St' },
        { key: 'web.layout.dow.short.4', label: 'Krátce „Čt" (4)', default: 'Čt' },
        { key: 'web.layout.dow.short.5', label: 'Krátce „Pá" (5)', default: 'Pá' },
        { key: 'web.layout.dow.short.6', label: 'Krátce „So" (6)', default: 'So' },
      ]
    },
    {
      id: 'validate', label: 'Validace kalendáře',
      fields: [
        { key: 'web.layout.editRez.validate.pastDate', label: 'Datum v minulosti', default: 'Nelze vybrat datum v minulosti.' },
        { key: 'web.layout.editRez.validate.dayOccupied', label: 'Den obsazený', default: 'Tento den je obsazený jinou rezervací.' },
        { key: 'web.layout.editRez.validate.activeStartLocked', label: 'Začátek zamčen (probíhá)', type: 'textarea', default: 'U probíhající rezervace nelze měnit datum vyzvednutí. Klikněte na den po {date}.' },
        { key: 'web.layout.editRez.validate.gapBeforeStart', label: 'Mezera před začátkem', default: 'Mezi vybraným datem a začátkem rezervace jsou obsazené dny.' },
        { key: 'web.layout.editRez.validate.gapAfterEnd', label: 'Mezera po konci', default: 'Mezi koncem rezervace a vybraným datem jsou obsazené dny.' },
        { key: 'web.layout.editRez.validate.extendBefore', label: 'Prodloužit „před"', default: 'Pro prodloužení klikněte na den před {date}.' },
        { key: 'web.layout.editRez.validate.extendAfter', label: 'Prodloužit „po"', default: 'Pro prodloužení klikněte na den po {date}.' },
        { key: 'web.layout.editRez.validate.extendEither', label: 'Prodloužit „před nebo po"', type: 'textarea', default: 'Toto je vaše rezervace. Pro prodloužení klikněte na den před {start} nebo po {end}.' },
        { key: 'web.layout.editRez.validate.shortenInside', label: 'Zkrátit „uvnitř"', default: 'Pro zkrácení klikněte uvnitř vaší rezervace.' },
        { key: 'web.layout.editRez.validate.shortenBefore', label: 'Zkrátit „před"', default: 'Pro zkrácení klikněte na den před {date}.' },
        { key: 'web.layout.editRez.validate.shortenPast', label: 'Zkrátit do minulosti', default: 'Nelze zkrátit do minulosti.' },
        { key: 'web.layout.editRez.validate.shortenPickSide', label: 'Vyberte stranu', default: 'Nejdříve vyberte, jestli chcete zkrátit Začátek, nebo Konec.' },
        { key: 'web.layout.editRez.validate.startAfterEnd', label: 'Začátek po konci', default: 'Začátek nesmí být po konci.' },
        { key: 'web.layout.editRez.validate.endBeforeStart', label: 'Konec před začátkem', default: 'Konec nesmí být před začátkem.' },
      ]
    },
    {
      id: 'range', label: 'Kalendář — rozsah dat (banner)',
      fields: [
        { key: 'web.layout.editRez.range.newStart', label: 'Label „Nový začátek"', default: 'Nový začátek' },
        { key: 'web.layout.editRez.range.newEnd', label: 'Label „Nový konec"', default: 'Nový konec' },
        { key: 'web.layout.editRez.range.startBetween', label: 'Šablona „Začátek: {min} – {max}"', default: 'Začátek: {min} – {max}' },
        { key: 'web.layout.editRez.range.endBetween', label: 'Šablona „Konec: {min} – {max}"', default: 'Konec: {min} – {max}' },
      ]
    },
    {
      id: 'dayWord', label: 'Den/dny (pluralizace)',
      fields: [
        { key: 'web.layout.editRez.dayWord.1', label: 'Slovo „den" (1)', default: 'den' },
        { key: 'web.layout.editRez.dayWord.few', label: 'Slovo „dny" (2-4)', default: 'dny' },
        { key: 'web.layout.editRez.dayWord.many', label: 'Slovo „dní" (5+)', default: 'dní' },
      ]
    },
    {
      id: 'change', label: 'Hlášky po změně rezervace',
      fields: [
        { key: 'web.layout.editRez.change.success', label: 'Změna úspěšná', default: 'Změna byla uložena.' },
        { key: 'web.layout.editRez.change.successWithRefund', label: 'Změna úspěšná (s refundem)', default: 'Změna byla uložena. Vrátíme vám {amount} během několika minut.' },
        { key: 'web.layout.editRez.postStripe.applying', label: 'Po Stripe — aplikuji', default: 'Platba potvrzena, dokončuji změnu rezervace…' },
        { key: 'web.layout.editRez.postStripe.error', label: 'Po Stripe — chyba', type: 'textarea', default: 'Platba proběhla, ale změnu rezervace se nepodařilo dokončit. Kontaktujte nás prosím.' },
      ]
    },
    {
      id: 'errors', label: 'Chybové hlášky',
      fields: [
        { key: 'web.layout.editRez.err.generic', label: 'Obecná chyba', default: 'Něco se pokazilo. Zkuste to prosím znovu.' },
        { key: 'web.layout.editRez.err.notFound', label: 'Rezervace nenalezena', default: 'Rezervace nebyla nalezena.' },
        { key: 'web.layout.editRez.err.wrongStatus', label: 'Nesprávný stav', default: 'Tuto rezervaci již nelze upravit.' },
        { key: 'web.layout.editRez.err.notPaid', label: 'Není zaplaceno', default: 'Rezervace zatím není zaplacená — kontaktujte nás.' },
        { key: 'web.layout.editRez.err.activeStartLocked', label: 'Začátek zamčen', default: 'U probíhající rezervace nelze měnit datum vyzvednutí.' },
        { key: 'web.layout.editRez.err.activeMotoLocked', label: 'Motorka zamčena', default: 'U probíhající rezervace nelze změnit motorku.' },
        { key: 'web.layout.editRez.err.invalidRange', label: 'Neplatný termín', default: 'Vyberte platný termín.' },
        { key: 'web.layout.editRez.err.notShortening', label: 'Nezkracuje', default: 'Pro zkrácení musí být nové datumy uvnitř původních.' },
        { key: 'web.layout.editRez.err.notExtending', label: 'Neprodlužuje', type: 'textarea', default: 'Nový termín musí obsahovat původní rozsah — vyberte den před začátkem nebo po konci původní rezervace.' },
        { key: 'web.layout.editRez.err.cantEdit', label: 'Nelze upravit', default: 'Tuto rezervaci nelze upravit (dokončená nebo stornovaná).' },
        { key: 'web.layout.editRez.err.serverDown', label: 'Server nedostupný', type: 'textarea', default: 'Přihlašovací služba momentálně nedostupná. Zkuste to prosím za chvíli, nebo nás kontaktujte na +420 774 256 271.' },
        { key: 'web.layout.editRez.err.emailNotConfirmed', label: 'E-mail nepotvrzen', default: 'E-mail ještě nebyl potvrzen. Zkontrolujte e-mailovou schránku nebo nám napište.' },
      ]
    },
  ]
}
