// i18n-moto2.js – Motorcycle description & feature translations (bikes 6–14) for MotoGo24
(function(){
function m(s){for(var l in s){if(!I18N[l])continue;for(var k in s[l]){if(!I18N[l][k])I18N[l][k]={};for(var j in s[l][k])I18N[l][k][j]=s[l][k][j];}}}
m({
cs:{moto:{
'yamaha-xt660':{desc:'Legendární supermoto s jednoválcovým motorem. XT 660 X je ikonou mezi supermoto motorkami – lehká, agilní, perfektní pro město i silnici. Ideální pro jezdce A2 kategorie.',feats:['Supermoto – město i silnice','Lehká a agilní','Kategorie A2','Průjezd hustou zástavbou','Sportovní styl']},
'kawasaki-z900':{desc:'Čtyřválcový naked bike plný adrenalinu. Kawasaki Z 900 nabízí brutální výkon, ostrý design a moderní elektroniku. Perfektní volba pro jezdce, kteří chtějí výkon a styl v jednom.',feats:['Naked bike – sportovní jízda','Čtyřválcový motor – brutální výkon','Moderní elektronika','Styl a výkon','Pro zkušené jezdce']},
'yamaha-mt09':{desc:'Trojválcový naked bike se zuřivým charakterem. Yamaha MT-09 je "Dark Side of Japan" – agresivní, zábavný a nepředvídatelný. Výborná volba pro jezdce, kteří chtějí maximální zábavu na silnici.',feats:['Naked bike – maximální zábava','Trojválcový motor – unikátní charakter','Agresivní výkon','Lehká a agilní','Dark Side of Japan']},
'yamaha-tenere':{desc:'Rallye legenda pro silnici. Yamaha Super Ténéré je inspirována vítězi Dakaru – výkonný dvojválec, obří nádrž a výborná ergonomie pro extrémně dlouhé trasy. Dokonalý cestovní partner.',feats:['Rallye adventure – inspirace Dakarem','Obrovský dojezd','Extrémně pohodlná','Jízda ve dvou','Silnice + terén']},
'ducati-multistrada':{desc:'Italská vášeň v podobě adventure motorky. Ducati Multistrada 1200 nabízí brutální výkon L-twin motoru, prémiové elektronické systémy a charakteristický italský zvuk. Pro milovníky Ducati.',feats:['Italský L-twin – unikátní zvuk','Prémiová elektronika – 4 jízdní režimy','Silnice i terén','Jízda ve dvou','Pro zkušené jezdce']},
'ktm-1290':{desc:'Ready to Race v adventure světě. KTM 1290 Super Adventure je nejextrémnější adventure motorka v naší flotile. Výkonný V-twin, prémiová WP elektronika a oranzové barvy KTM. Pro skutečné dobrodruhy.',feats:['Nejvýkonnější adventure v nabídce','V-twin 160 koní – extrémní výkon','WP elektronika – terén i silnice','Prémiové vybavení','Pouze pro zkušené']},
'yamaha-pw50':{desc:'Malý pomocník pro velké začátky. Yamaha PW 50 je legendární dětská motorka pro první kroky v motosportu. Automatická převodovka, nízké sedlo a maximálních 50 ccm jsou ideální pro děti od 3 let.',feats:['Dětská motorka – od 3 let','Automatická převodovka','Nízké sedlo – 485 mm','Omezovač plynu pro rodiče','Legendární volba pro začátky']},
'ktm-sx65':{desc:'Závodní motokros pro mladé piloty. KTM SX 65 je skutečná závodní motorka v malém provedení – pro děti 7–12 let. Výkonný dvoutaktní motor, závodní podvozek a oranžové KTM barvy.',feats:['Závodní motokros pro děti','Dvoutaktní motor – závodní výkon','Věk 7–12 let','Uzavřené tratě / areály','Výchozí bod závodní kariéry']},
'triumph-tiger':{desc:'Britský elegán pro světové dobrodružství. Triumph Tiger 1200 Explorer je prémiová adventure motorka s trojválcovým motorem, bohatou výbavou a elegantním britským designem. Ideální pro dlouhé transcontinentální jízdy.',feats:['Britský trojválec – unikátní charakter','Prémiové GT vybavení','Transcontinentální cestování','Jízda ve dvou','Elegantní design']}
}},
en:{moto:{
'yamaha-xt660':{desc:'Legendary supermoto with a single-cylinder engine. The XT 660 X is an icon among supermoto bikes – light, agile, perfect for city and road riding. Ideal for A2 licence holders.',feats:['Supermoto – city & road','Light and agile','A2 licence category','Navigating dense urban areas','Sporty style']},
'kawasaki-z900':{desc:'Four-cylinder naked bike full of adrenaline. The Kawasaki Z 900 offers brutal power, sharp design and modern electronics. The perfect choice for riders who want performance and style in one.',feats:['Naked bike – sporty riding','Four-cylinder engine – brutal power','Modern electronics','Style and performance','For experienced riders']},
'yamaha-mt09':{desc:'Triple-cylinder naked bike with a furious character. The Yamaha MT-09 is the "Dark Side of Japan" – aggressive, fun and unpredictable. An excellent choice for riders seeking maximum fun on the road.',feats:['Naked bike – maximum fun','Triple-cylinder engine – unique character','Aggressive power','Light and agile','Dark Side of Japan']},
'yamaha-tenere':{desc:'Rally legend for the road. The Yamaha Super Ténéré is inspired by Dakar winners – a powerful twin engine, huge tank and superb ergonomics for extremely long routes. The perfect touring partner.',feats:['Rally adventure – Dakar inspired','Enormous range','Extremely comfortable','Two-up riding','Road + off-road']},
'ducati-multistrada':{desc:'Italian passion in the form of an adventure bike. The Ducati Multistrada 1200 delivers brutal L-twin power, premium electronic systems and the characteristic Italian sound. For Ducati enthusiasts.',feats:['Italian L-twin – unique sound','Premium electronics – 4 riding modes','Road and off-road','Two-up riding','For experienced riders']},
'ktm-1290':{desc:'Ready to Race in the adventure world. The KTM 1290 Super Adventure is the most extreme adventure bike in our fleet. A powerful V-twin, premium WP electronics and KTM\'s signature orange colours. For true adventurers.',feats:['Most powerful adventure in the fleet','V-twin 160 hp – extreme power','WP electronics – off-road & road','Premium equipment','For experienced riders only']},
'yamaha-pw50':{desc:'A small helper for big beginnings. The Yamaha PW 50 is a legendary kids\' bike for first steps in motorsport. Automatic transmission, low seat and a maximum of 50 cc are ideal for children from 3 years old.',feats:['Kids\' bike – from age 3','Automatic transmission','Low seat – 485 mm','Throttle limiter for parents','Legendary choice for beginners']},
'ktm-sx65':{desc:'Racing motocross for young riders. The KTM SX 65 is a real racing motorcycle in a small package – for children aged 7–12. A powerful two-stroke engine, racing chassis and KTM\'s signature orange colours.',feats:['Racing motocross for kids','Two-stroke engine – racing power','Age 7–12','Closed tracks / circuits','Starting point of a racing career']},
'triumph-tiger':{desc:'A British gentleman for global adventure. The Triumph Tiger 1200 Explorer is a premium adventure motorcycle with a triple-cylinder engine, rich equipment and elegant British design. Ideal for long transcontinental rides.',feats:['British triple – unique character','Premium GT equipment','Transcontinental touring','Two-up riding','Elegant design']}
}},
de:{moto:{
'yamaha-xt660':{desc:'Legendäre Supermoto mit Einzylindermotor. Die XT 660 X ist eine Ikone unter den Supermoto-Bikes – leicht, agil, perfekt für Stadt und Landstraße. Ideal für Fahrer der A2-Klasse.',feats:['Supermoto – Stadt & Straße','Leicht und agil','Führerscheinklasse A2','Durch dichten Stadtverkehr','Sportlicher Stil']},
'kawasaki-z900':{desc:'Vierzylinder-Naked-Bike voller Adrenalin. Die Kawasaki Z 900 bietet brutale Leistung, scharfes Design und moderne Elektronik. Die perfekte Wahl für Fahrer, die Leistung und Stil vereinen wollen.',feats:['Naked Bike – sportliches Fahren','Vierzylindermotor – brutale Leistung','Moderne Elektronik','Stil und Leistung','Für erfahrene Fahrer']},
'yamaha-mt09':{desc:'Dreizylinder-Naked-Bike mit wildem Charakter. Die Yamaha MT-09 ist die „Dark Side of Japan" – aggressiv, spaßig und unberechenbar. Eine ausgezeichnete Wahl für Fahrer, die maximalen Spaß auf der Straße suchen.',feats:['Naked Bike – maximaler Spaß','Dreizylindermotor – einzigartiger Charakter','Aggressive Leistung','Leicht und agil','Dark Side of Japan']},
'yamaha-tenere':{desc:'Rallye-Legende für die Straße. Die Yamaha Super Ténéré ist von Dakar-Siegern inspiriert – leistungsstarker Zweizylinder, riesiger Tank und hervorragende Ergonomie für extrem lange Strecken. Der perfekte Reisepartner.',feats:['Rallye-Adventure – inspiriert von der Dakar','Enorme Reichweite','Extrem komfortabel','Fahren zu zweit','Straße + Gelände']},
'ducati-multistrada':{desc:'Italienische Leidenschaft in Form eines Adventure-Bikes. Die Ducati Multistrada 1200 bietet brutale L-Twin-Leistung, Premium-Elektroniksysteme und den charakteristischen italienischen Sound. Für Ducati-Liebhaber.',feats:['Italienischer L-Twin – einzigartiger Sound','Premium-Elektronik – 4 Fahrmodi','Straße und Gelände','Fahren zu zweit','Für erfahrene Fahrer']},
'ktm-1290':{desc:'Ready to Race in der Adventure-Welt. Die KTM 1290 Super Adventure ist das extremste Adventure-Bike unserer Flotte. Leistungsstarker V-Twin, Premium-WP-Elektronik und die orangene KTM-Farben. Für echte Abenteurer.',feats:['Stärkstes Adventure der Flotte','V-Twin 160 PS – extreme Leistung','WP-Elektronik – Gelände & Straße','Premium-Ausstattung','Nur für erfahrene Fahrer']},
'yamaha-pw50':{desc:'Kleiner Helfer für große Anfänge. Die Yamaha PW 50 ist ein legendäres Kindermotorrad für die ersten Schritte im Motorsport. Automatikgetriebe, niedriger Sitz und maximal 50 ccm sind ideal für Kinder ab 3 Jahren.',feats:['Kindermotorrad – ab 3 Jahren','Automatikgetriebe','Niedriger Sitz – 485 mm','Gasbegrenzer für Eltern','Legendäre Wahl für Anfänger']},
'ktm-sx65':{desc:'Renn-Motocross für junge Piloten. Die KTM SX 65 ist ein echtes Rennmotorrad im Kleinformat – für Kinder von 7–12 Jahren. Leistungsstarker Zweitaktmotor, Rennfahrwerk und die orangenen KTM-Farben.',feats:['Renn-Motocross für Kinder','Zweitaktmotor – Rennleistung','Alter 7–12 Jahre','Geschlossene Strecken / Gelände','Startpunkt einer Rennkarriere']},
'triumph-tiger':{desc:'Britischer Gentleman für weltweites Abenteuer. Die Triumph Tiger 1200 Explorer ist ein Premium-Adventure-Motorrad mit Dreizylindermotor, reicher Ausstattung und elegantem britischem Design. Ideal für lange transkontinentale Fahrten.',feats:['Britischer Dreizylinder – einzigartiger Charakter','Premium-GT-Ausstattung','Transkontinentales Reisen','Fahren zu zweit','Elegantes Design']}
}},
es:{moto:{
'yamaha-xt660':{desc:'Supermoto legendaria con motor monocilíndrico. La XT 660 X es un icono entre las motos supermoto – ligera, ágil, perfecta para la ciudad y la carretera. Ideal para titulares del permiso A2.',feats:['Supermoto – ciudad y carretera','Ligera y ágil','Categoría de permiso A2','Tránsito por zonas urbanas densas','Estilo deportivo']},
'kawasaki-z900':{desc:'Naked bike de cuatro cilindros repleta de adrenalina. La Kawasaki Z 900 ofrece una potencia brutal, un diseño afilado y electrónica moderna. La elección perfecta para pilotos que quieren rendimiento y estilo a la vez.',feats:['Naked bike – conducción deportiva','Motor de cuatro cilindros – potencia brutal','Electrónica moderna','Estilo y rendimiento','Para pilotos experimentados']},
'yamaha-mt09':{desc:'Naked bike de tres cilindros con un carácter furioso. La Yamaha MT-09 es el "Dark Side of Japan" – agresiva, divertida e impredecible. Una excelente elección para pilotos que buscan la máxima diversión en la carretera.',feats:['Naked bike – diversión máxima','Motor de tres cilindros – carácter único','Potencia agresiva','Ligera y ágil','Dark Side of Japan']},
'yamaha-tenere':{desc:'Leyenda del rally para la carretera. La Yamaha Super Ténéré está inspirada en los ganadores del Dakar – potente bicilíndrico, depósito enorme y excelente ergonomía para rutas extremadamente largas. El compañero de viaje perfecto.',feats:['Rally adventure – inspirada en el Dakar','Autonomía enorme','Extremadamente cómoda','Conducción en pareja','Carretera + fuera de ruta']},
'ducati-multistrada':{desc:'Pasión italiana en forma de moto adventure. La Ducati Multistrada 1200 ofrece una potencia brutal del motor L-twin, sistemas electrónicos premium y el característico sonido italiano. Para los amantes de Ducati.',feats:['L-twin italiano – sonido único','Electrónica premium – 4 modos de conducción','Carretera y fuera de ruta','Conducción en pareja','Para pilotos experimentados']},
'ktm-1290':{desc:'Ready to Race en el mundo adventure. La KTM 1290 Super Adventure es la moto adventure más extrema de nuestra flota. Potente V-twin, electrónica WP premium y los colores naranjas de KTM. Para verdaderos aventureros.',feats:['La adventure más potente de la flota','V-twin 160 CV – potencia extrema','Electrónica WP – fuera de ruta y carretera','Equipamiento premium','Solo para pilotos experimentados']},
'yamaha-pw50':{desc:'Un pequeño ayudante para grandes comienzos. La Yamaha PW 50 es una legendaria moto infantil para los primeros pasos en el motociclismo. Transmisión automática, asiento bajo y un máximo de 50 cc son ideales para niños desde 3 años.',feats:['Moto infantil – desde 3 años','Transmisión automática','Asiento bajo – 485 mm','Limitador de gas para padres','Elección legendaria para principiantes']},
'ktm-sx65':{desc:'Motocross de competición para jóvenes pilotos. La KTM SX 65 es una auténtica moto de carreras en formato reducido – para niños de 7 a 12 años. Potente motor de dos tiempos, chasis de competición y los colores naranjas de KTM.',feats:['Motocross de competición para niños','Motor de dos tiempos – potencia de carreras','Edad 7–12 años','Circuitos cerrados / recintos','Punto de partida de una carrera deportiva']},
'triumph-tiger':{desc:'Un caballero británico para la aventura mundial. La Triumph Tiger 1200 Explorer es una moto adventure premium con motor de tres cilindros, equipamiento completo y elegante diseño británico. Ideal para largos viajes transcontinentales.',feats:['Tricilíndrico británico – carácter único','Equipamiento GT premium','Viajes transcontinentales','Conducción en pareja','Diseño elegante']}
}},
fr:{moto:{
'yamaha-xt660':{desc:'Supermoto légendaire avec moteur monocylindre. La XT 660 X est une icône parmi les motos supermoto – légère, agile, parfaite pour la ville et la route. Idéale pour les titulaires du permis A2.',feats:['Supermoto – ville et route','Légère et agile','Catégorie de permis A2','Circulation en zone urbaine dense','Style sportif']},
'kawasaki-z900':{desc:'Roadster quatre cylindres gorgé d\'adrénaline. La Kawasaki Z 900 offre une puissance brutale, un design acéré et une électronique moderne. Le choix parfait pour les pilotes qui veulent performance et style à la fois.',feats:['Roadster – conduite sportive','Moteur quatre cylindres – puissance brutale','Électronique moderne','Style et performance','Pour pilotes expérimentés']},
'yamaha-mt09':{desc:'Roadster trois cylindres au caractère furieux. La Yamaha MT-09 est le « Dark Side of Japan » – agressive, amusante et imprévisible. Un excellent choix pour les pilotes qui recherchent un maximum de plaisir sur la route.',feats:['Roadster – plaisir maximal','Moteur trois cylindres – caractère unique','Puissance agressive','Légère et agile','Dark Side of Japan']},
'yamaha-tenere':{desc:'Légende du rallye pour la route. La Yamaha Super Ténéré est inspirée des vainqueurs du Dakar – bicylindre puissant, réservoir immense et excellente ergonomie pour les trajets extrêmement longs. Le partenaire de voyage parfait.',feats:['Rallye adventure – inspirée du Dakar','Autonomie énorme','Extrêmement confortable','Conduite à deux','Route + tout-terrain']},
'ducati-multistrada':{desc:'Passion italienne sous la forme d\'une moto adventure. La Ducati Multistrada 1200 offre la puissance brutale du moteur L-twin, des systèmes électroniques premium et le son italien caractéristique. Pour les passionnés de Ducati.',feats:['L-twin italien – son unique','Électronique premium – 4 modes de conduite','Route et tout-terrain','Conduite à deux','Pour pilotes expérimentés']},
'ktm-1290':{desc:'Ready to Race dans le monde adventure. La KTM 1290 Super Adventure est la moto adventure la plus extrême de notre flotte. V-twin puissant, électronique WP premium et les couleurs orange de KTM. Pour les vrais aventuriers.',feats:['L\'adventure la plus puissante de la flotte','V-twin 160 ch – puissance extrême','Électronique WP – tout-terrain et route','Équipement premium','Réservée aux pilotes expérimentés']},
'yamaha-pw50':{desc:'Un petit assistant pour de grands débuts. La Yamaha PW 50 est une moto pour enfants légendaire pour les premiers pas en sport moto. Boîte automatique, selle basse et un maximum de 50 cm³ sont idéaux pour les enfants dès 3 ans.',feats:['Moto pour enfants – dès 3 ans','Boîte automatique','Selle basse – 485 mm','Limiteur de gaz pour les parents','Choix légendaire pour les débutants']},
'ktm-sx65':{desc:'Motocross de compétition pour jeunes pilotes. La KTM SX 65 est une vraie moto de course en format réduit – pour les enfants de 7 à 12 ans. Moteur deux temps puissant, châssis de compétition et les couleurs orange de KTM.',feats:['Motocross de compétition pour enfants','Moteur deux temps – puissance de course','Âge 7–12 ans','Circuits fermés / zones dédiées','Point de départ d\'une carrière en compétition']},
'triumph-tiger':{desc:'Un gentleman britannique pour l\'aventure mondiale. La Triumph Tiger 1200 Explorer est une moto adventure premium avec moteur trois cylindres, équipement riche et design britannique élégant. Idéale pour les longs parcours transcontinentaux.',feats:['Trois cylindres britannique – caractère unique','Équipement GT premium','Voyages transcontinentaux','Conduite à deux','Design élégant']}
}},
nl:{moto:{
'yamaha-xt660':{desc:'Legendarische supermoto met eencilindermotor. De XT 660 X is een icoon onder de supermoto\'s – licht, wendbaar, perfect voor stad en weg. Ideaal voor rijders met een A2-rijbewijs.',feats:['Supermoto – stad & weg','Licht en wendbaar','Rijbewijscategorie A2','Door druk stadsverkeer','Sportieve stijl']},
'kawasaki-z900':{desc:'Viercilinder naked bike vol adrenaline. De Kawasaki Z 900 biedt brute kracht, een scherp design en moderne elektronica. De perfecte keuze voor rijders die prestaties en stijl in één willen.',feats:['Naked bike – sportief rijden','Viercilindermotor – brute kracht','Moderne elektronica','Stijl en prestaties','Voor ervaren rijders']},
'yamaha-mt09':{desc:'Driecilinder naked bike met een woest karakter. De Yamaha MT-09 is de "Dark Side of Japan" – agressief, vermakelijk en onvoorspelbaar. Een uitstekende keuze voor rijders die maximaal plezier op de weg zoeken.',feats:['Naked bike – maximaal plezier','Driecilindermotor – uniek karakter','Agressief vermogen','Licht en wendbaar','Dark Side of Japan']},
'yamaha-tenere':{desc:'Rallyelegende voor de weg. De Yamaha Super Ténéré is geïnspireerd door Dakar-winnaars – krachtige tweecilinder, enorme tank en uitstekende ergonomie voor extreem lange routes. De perfecte reispartner.',feats:['Rally adventure – geïnspireerd door de Dakar','Enorm bereik','Extreem comfortabel','Rijden met passagier','Weg + offroad']},
'ducati-multistrada':{desc:'Italiaanse passie in de vorm van een adventure motor. De Ducati Multistrada 1200 levert brute L-twin kracht, premium elektronische systemen en het kenmerkende Italiaanse geluid. Voor Ducati-liefhebbers.',feats:['Italiaanse L-twin – uniek geluid','Premium elektronica – 4 rijmodi','Weg en offroad','Rijden met passagier','Voor ervaren rijders']},
'ktm-1290':{desc:'Ready to Race in de adventure-wereld. De KTM 1290 Super Adventure is de meest extreme adventure motor in onze vloot. Krachtige V-twin, premium WP-elektronica en de oranje KTM-kleuren. Voor echte avonturiers.',feats:['Krachtigste adventure in de vloot','V-twin 160 pk – extreem vermogen','WP-elektronica – offroad & weg','Premium uitrusting','Uitsluitend voor ervaren rijders']},
'yamaha-pw50':{desc:'Een kleine helper voor een groot begin. De Yamaha PW 50 is een legendarische kindermotor voor de eerste stappen in de motorsport. Automatische versnellingsbak, laag zadel en maximaal 50 cc zijn ideaal voor kinderen vanaf 3 jaar.',feats:['Kindermotor – vanaf 3 jaar','Automatische versnellingsbak','Laag zadel – 485 mm','Gasbegrenzer voor ouders','Legendarische keuze voor beginners']},
'ktm-sx65':{desc:'Wedstrijdmotocross voor jonge rijders. De KTM SX 65 is een echte racemotor in klein formaat – voor kinderen van 7–12 jaar. Krachtige tweetaktmotor, racechassis en de oranje KTM-kleuren.',feats:['Wedstrijdmotocross voor kinderen','Tweetaktmotor – racevermogen','Leeftijd 7–12 jaar','Gesloten circuits / terreinen','Startpunt van een racecarrière']},
'triumph-tiger':{desc:'Een Britse gentleman voor wereldwijd avontuur. De Triumph Tiger 1200 Explorer is een premium adventure motor met driecilindermotor, rijke uitrusting en elegant Brits design. Ideaal voor lange transcontinentale ritten.',feats:['Britse driecilinder – uniek karakter','Premium GT-uitrusting','Transcontinentaal reizen','Rijden met passagier','Elegant design']}
}},
pl:{moto:{
'yamaha-xt660':{desc:'Legendarne supermoto z jednocylindrowym silnikiem. XT 660 X to ikona wśród motocykli supermoto – lekki, zwinny, idealny do miasta i na szosę. Idealny dla posiadaczy prawa jazdy kategorii A2.',feats:['Supermoto – miasto i szosa','Lekki i zwinny','Kategoria prawa jazdy A2','Przejazd przez gęstą zabudowę','Sportowy styl']},
'kawasaki-z900':{desc:'Czterocylindrowy naked bike pełen adrenaliny. Kawasaki Z 900 oferuje brutalną moc, ostry design i nowoczesną elektronikę. Idealny wybór dla jeźdźców, którzy chcą mocy i stylu w jednym.',feats:['Naked bike – sportowa jazda','Silnik czterocylindrowy – brutalna moc','Nowoczesna elektronika','Styl i moc','Dla doświadczonych jeźdźców']},
'yamaha-mt09':{desc:'Trójcylindrowy naked bike o wściekłym charakterze. Yamaha MT-09 to „Dark Side of Japan" – agresywna, zabawna i nieprzewidywalna. Doskonały wybór dla jeźdźców szukających maksymalnej zabawy na drodze.',feats:['Naked bike – maksymalna zabawa','Silnik trójcylindrowy – unikalny charakter','Agresywna moc','Lekki i zwinny','Dark Side of Japan']},
'yamaha-tenere':{desc:'Legendy rajdów na drodze. Yamaha Super Ténéré jest inspirowana zwycięzcami Dakaru – mocny dwucylindrowy silnik, ogromny zbiornik i doskonała ergonomia na ekstremalnie długie trasy. Idealny partner podróży.',feats:['Rally adventure – inspiracja Dakarem','Ogromny zasięg','Ekstremalnie wygodna','Jazda we dwoje','Szosa + teren']},
'ducati-multistrada':{desc:'Włoska pasja w formie motocykla adventure. Ducati Multistrada 1200 oferuje brutalną moc silnika L-twin, premium systemy elektroniczne i charakterystyczny włoski dźwięk. Dla miłośników Ducati.',feats:['Włoski L-twin – unikalny dźwięk','Premium elektronika – 4 tryby jazdy','Szosa i teren','Jazda we dwoje','Dla doświadczonych jeźdźców']},
'ktm-1290':{desc:'Ready to Race w świecie adventure. KTM 1290 Super Adventure to najbardziej ekstremalny motocykl adventure w naszej flocie. Mocny V-twin, premium elektronika WP i pomarańczowe barwy KTM. Dla prawdziwych poszukiwaczy przygód.',feats:['Najmocniejszy adventure we flocie','V-twin 160 KM – ekstremalna moc','Elektronika WP – teren i szosa','Wyposażenie premium','Wyłącznie dla doświadczonych']},
'yamaha-pw50':{desc:'Mały pomocnik na wielkie początki. Yamaha PW 50 to legendarny motocykl dziecięcy na pierwsze kroki w motosporcie. Automatyczna skrzynia biegów, niskie siedzenie i maksymalnie 50 ccm są idealne dla dzieci od 3 lat.',feats:['Motocykl dziecięcy – od 3 lat','Automatyczna skrzynia biegów','Niskie siedzenie – 485 mm','Ogranicznik gazu dla rodziców','Legendarny wybór na początek']},
'ktm-sx65':{desc:'Wyścigowy motocross dla młodych zawodników. KTM SX 65 to prawdziwy motocykl wyścigowy w małym wydaniu – dla dzieci w wieku 7–12 lat. Mocny silnik dwusuwowy, wyścigowe podwozie i pomarańczowe barwy KTM.',feats:['Wyścigowy motocross dla dzieci','Silnik dwusuwowy – wyścigowa moc','Wiek 7–12 lat','Zamknięte tory / tereny','Punkt startowy kariery wyścigowej']},
'triumph-tiger':{desc:'Brytyjski dżentelmen na światowe przygody. Triumph Tiger 1200 Explorer to premium motocykl adventure z trójcylindrowym silnikiem, bogatym wyposażeniem i eleganckim brytyjskim designem. Idealny na długie podróże transkontynentalne.',feats:['Brytyjski trójcylindrowy – unikalny charakter','Wyposażenie GT premium','Podróże transkontynentalne','Jazda we dwoje','Elegancki design']}
}}
});
})();
