<?php
// DE překlady recenzí (němčina; data/reviews.php, klíč = id recenze) — landing v2, renderLpReviews().
// Překlad z českých originálů (věrně, bez přikrášlení); recenze s 'lang' => 'en' se nepřekládá.
return ['pages' => ['landing' => ['common' => [
    'reviews_tr' => [
        'karel-s-google' => 'Super, ich hatte für 1 Tag eine RVM 500 gemietet, alles lief online, ohne Kaution, das Motorrad war morgens bereit, abends habe ich es zurückgegeben, ohne Kilometerbegrenzung und super Absprache mit dem Inhaber ;) Kann ich empfehlen',
        'libor-j-google' => 'Außergewöhnlicher Service unter den Motorradvermietungen, wir sind keine Motorradfahrer, haben keine Ausrüstung. Wir haben das Motorrad in der App bestellt, sind hingefahren, das Motorrad war bereit, …',
        'jirka-s-google' => 'Plus: zeitliche Flexibilität, freundlicher Umgang, super vorbereitete Maschine, keine Kaution nötig, mobile App …',
        'zdenek-r-google' => 'Sehr zu empfehlen, ich habe mir auf Empfehlung eine Triumph Tiger 1200 Explorer gemietet, schneller und bequemer Ablauf bei Reservierung, Bezahlung und Abholung des Motorrads, und bei der Rückgabe hat mich ein ausgezeichneter Kaffee gefreut :-)',
        'lenka-g-google' => 'Super menschlicher Umgang! Wer überlegt, ein Motorrad zum Ausprobieren fürs Kind zu mieten, macht hier nichts falsch. Die ganze Zeit nett und freundlich. Auf jeden Fall zu empfehlen 🙂',
        'jaroslav-j-google' => 'Mit einem Wort: FANTASTISCH. Wärmstens zu empfehlen. Nach Jahren bekam ich die Gelegenheit, in meine Jugend zurückzukehren, als ich ziemlich viel gefahren bin. Einwandfreier Service von der Bestellung des Motorrads über die Miete samt Ausrüstung bis zur Rückgabe. Die Inhaber entgegenkommend und hilfsbereit. 👍',
        'laza-google' => 'Tolle Erfahrung mit der Miete, ich hatte das Motorrad für 2 Tage, auch mit Anhänger. Die Motorräder sind gepflegt, das Personal sehr angenehm und hilfsbereit. Der Herr, der mir das Motorrad übergeben hat, half mir sogar beim Aufladen und Sichern. Für mich eine tolle Erfahrung, ich kann es auf jeden Fall nur empfehlen.',
        'romana-k-google' => 'Danke für den schönen Ausflug. Mein Mann und ich hatten eine BMW GS 1200 gemietet und ich die komplette Motorradausrüstung. Toller Service, gute Absprache, schöne Umgebung. Sehr zu empfehlen, wir kommen bestimmt mal wieder :-).',
        'daniel-h-google' => 'Ein absolutes Motorradparadies – uneingeschränkt zu empfehlen! Ich habe eine zuverlässige Vermietung für einen Ausflug gesucht und diese Wahl war ein Volltreffer. Vom ersten Kontakt bis zur Rückgabe der Maschine ein absolut fehlerfreies Erlebnis.',
        'martin-k-google' => 'Einfache Reservierung, niedriger Preis, wunderschöne Gegend für eine Ausfahrt. Schnelle Übergabe und hilfsbereites Personal.',
        'zdenek-firmy' => 'Perfekte Vermietung! Super Umgang, keine Kaution, ums Waschen des Motorrads muss man sich nicht kümmern und die Ausrüstung bekommt man kostenlos geliehen. Schnell, ehrlich und sorgenfrei. Es gibt nichts auszusetzen.',
        'petr-c-firmy' => 'Tolle Erfahrung. Ich schätze vor allem den freundlichen und entgegenkommenden Umgang, alles lief völlig problemlos. Das Motorrad war zur vereinbarten Zeit bereit und dazu vollgetankt, sodass ich gleich losfahren konnte. Die Übergabe war schnell und ohne unnötige Verzögerung, genauso die Rückgabe, die jederzeit möglich war, auch nachts. Ein großes Plus war auch, dass man vor der Rückgabe nicht nachtanken musste – so muss man sich keine unnötigen Sorgen machen.',
        'marian-l-fb' => '… Alles habe ich einfach über die App erledigt, Preise und Mietbedingungen die besten von allen, die ich gefunden habe. Bei meiner Ankunft in der Vermietung begrüßte mich die sympathische und sehr nette Inhaberin. Sie hat mich mit allem vertraut gemacht und meine Fragen bereitwillig beantwortet (techn. Angelegenheiten…). Motorrad und Zubehör waren schon vorbereitet. Auch die Rückgabe der Maschine verlief völlig problemlos. … Sehr zufrieden mit dem Umgang und auch mit dem Motorrad.',
        'martin-o-firmy' => 'Perfekte Motorradvermietung – einfache Bestellung, gute Preise, schnelle und einfache Übergabe + als Bonus traumhafte Strecken in der Umgebung.',
        'strdyna-firmy' => 'Zum ersten Mal habe ich mich entschieden, einen Tourer für mehr Komfort zu zweit zu mieten, und ich bin rundum zufrieden! … Das Motorrad (Benelli TRK 502 X) wartete in gutem technischem Zustand, gewaschen und vollgetankt bereit für die Ausfahrt, direkt daneben habe ich mein Auto geparkt, das auf dem umzäunten Parkplatz übers Wochenende stehen bleiben konnte. Toller Umgang der Inhaberin und problemlose Rückgabe, sogar mit einem Kaffee für die Heimfahrt.',
        'hancl-firmy' => 'Das Motorrad war zur vereinbarten Zeit bereit. Die gesamte Kommunikation hat von Anfang an zu 100 % funktioniert. … Bei der Übergabe hat die Inhaberin alles erklärt. … Was ich außerdem schätze: Wenn irgendein Problem auftaucht, genügt ein Anruf. Hervorragender technischer Support. … Was mir sehr gefallen hat: Man kann die Maschine abends zurückgeben. Schön und übersichtlich gemachte Website und App. Diese Vermietung empfehle ich 10/10.',
        'jan-r-fb' => 'Es ist einfach eine großartige Firma und eine Truppe von Leuten, die Motorräder lieben. Ich kann sie allen nur empfehlen. Ich habe es riesig genossen. Große Auswahl an Motorrädern und Bekleidung, die man ganz entspannt anprobieren kann. Nette und entgegenkommende Art. Einfach klasse. Vielen Dank.',
        'dejv-m-firmy' => '… Als ich das Motorrad abholen kam, war schon alles vorbereitet, mir wurde Kaffee angeboten und alles drumherum erklärt. Das Motorrad war in ausgezeichnetem technischem Zustand, sauber und praktisch vollgetankt. Die anschließende Rückgabe verlief ebenfalls reibungslos und absolut professionell. Von der Kommunikation über die Reservierung bis zur Umsetzung. Die Dokumente kamen mit ausreichend Vorlauf, also keine unnötigen Verzögerungen. …',
        'pavel-s-fb' => 'Wir haben zwei Roller gemietet, beide neu und in super Zustand. Der Service war erstklassig, und außerdem sind sie sympathisch und total entspannt. Danke, wir empfehlen es weiter.',
        'jan-m-firmy' => 'Normalerweise schreibe ich keine Bewertungen, aber hierfür muss ich mir Zeit nehmen... Ein Umgang weit über dem Standard, der seinesgleichen sucht. Eine sehr hilfsbereite und angenehme Dame. Tolle Website, App und Buchungssystem. …',
    ],
]]]];
