// i18n-moto2-2.js – Motorcycle description & feature translations (bikes 6–14, fr/nl/pl) for MotoGo24
(function(){
function m(s){for(var l in s){if(!I18N[l])continue;for(var k in s[l]){if(!I18N[l][k])I18N[l][k]={};for(var j in s[l][k])I18N[l][k][j]=s[l][k][j];}}}
m({
fr:{moto:{
'yamaha-xt660':{desc:'Supermoto légendaire avec moteur monocylindre. La XT 660 X est une icône parmi les motos supermoto – légère, agile, parfaite pour la ville et la route. Idéale pour les titulaires du permis A2.',feats:['Supermoto – ville et route','Légère et agile','Catégorie de permis A2','Circulation en zone urbaine dense','Style sportif']},
'kawasaki-z900':{desc:'Roadster quatre cylindres gorgé d\'adrénaline. La Kawasaki Z 900 offre une puissance brutale, un design acéré et une électronique moderne. Le choix parfait pour les pilotes qui veulent performance et style à la fois.',feats:['Roadster – conduite sportive','Moteur quatre cylindres – puissance brutale','Électronique moderne','Style et performance','Pour pilotes expérimentés']},
'yamaha-mt09':{desc:'Roadster trois cylindres au caractère furieux. La Yamaha MT-09 est le « Dark Side of Japan » – agressive, amusante et imprévisible. Un excellent choix pour les pilotes qui recherchent un maximum de plaisir sur la route.',feats:['Roadster – plaisir maximal','Moteur trois cylindres – caractère unique','Puissance agressive','Légère et agile','Dark Side of Japan']},
'yamaha-tenere':{desc:'Légende du rallye pour la route. La Yamaha Super Ténéré est inspirée des vainqueurs du Dakar – bicylindre puissant, réservoir immense et excellente ergonomie pour les trajets extrêmement longs. Le partenaire de voyage parfait.',feats:['Rallye adventure – inspirée du Dakar','Autonomie énorme','Extrêmement confortable','Conduite à deux','Route + tout-terrain']},
'ducati-multistrada':{desc:'Passion italienne sous la forme d\'une moto adventure. La Ducati Multistrada 1200 offre la puissance brutale du moteur L-twin, des systèmes électroniques premium et le son italien caractéristique. Pour les passionnés de Ducati.',feats:['L-twin italien – son unique','Électronique premium – 4 modes de conduite','Route et tout-terrain','Conduite à deux','Pour pilotes expérimentés']},
'ktm-1290':{desc:'Ready to Race dans le monde adventure. La KTM 1290 Super Adventure est la moto adventure la plus extrême de notre flotte. V-twin puissant, électronique WP premium et les couleurs orange de KTM. Pour les vrais aventuriers.',feats:['L\'adventure la plus puissante de la flotte','V-twin 160 ch – puissance extrême','Électronique WP – tout-terrain et route','Équipement premium','Réservée aux pilotes expérimentés']},
'yamaha-pw50':{desc:'Un petit assistant pour de grands débuts. La Yamaha PW 50 est une moto pour enfants légendaire pour les premiers pas en sport moto. Boîte automatique, selle basse et un maximum de 50 cm³ sont idéaux pour les enfants dès 3 ans.',feats:['Moto pour enfants – dès 3 ans','Boîte automatique','Selle basse – 485 mm','Limiteur de gaz pour les parents','Choix légendaire pour les débutants']},
'ktm-sx65':{desc:'Motocross de compétition pour jeunes pilotes. La KTM SX 65 est une vraie moto de course en format réduit – pour les enfants de 7 à 12 ans. Moteur deux temps puissant, châssis de compétition et les couleurs orange de KTM.',feats:['Motocross de compétition pour enfants','Moteur deux temps – puissance de course','Âge 7–12 ans','Circuits fermés / zones dédiées','Point de départ d\'une carrière en compétition']},
'triumph-tiger':{desc:'Un gentleman britannique pour l\'aventure mondiale. La Triumph Tiger 1200 Explorer est une moto adventure premium avec moteur trois cylindres, équipement riche et design britannique élégant. Idéale pour les longs parcours transcontinentaux.',feats:['Trois cylindres britannique – caractère unique','Équipement GT premium','Voyages transcontinentaux','Conduite à deux','Design élégant']}
}},
nl:{moto:{
'yamaha-xt660':{desc:'Legendarische supermoto met eencilindermotor. De XT 660 X is een icoon onder de supermoto\'s – licht, wendbaar, perfect voor stad en weg. Ideaal voor rijders met een A2-rijbewijs.',feats:['Supermoto – stad & weg','Licht en wendbaar','Rijbewijscategorie A2','Door druk stadsverkeer','Sportieve stijl']},
'kawasaki-z900':{desc:'Viercilinder naked bike vol adrenaline. De Kawasaki Z 900 biedt brute kracht, een scherp design en moderne elektronica. De perfecte keuze voor rijders die prestaties en stijl in één willen.',feats:['Naked bike – sportief rijden','Viercilindermotor – brute kracht','Moderne elektronica','Stijl en prestaties','Voor ervaren rijders']},
'yamaha-mt09':{desc:'Driecilinder naked bike met een woest karakter. De Yamaha MT-09 is de "Dark Side of Japan" – agressief, vermakelijk en onvoorspelbaar. Een uitstekende keuze voor rijders die maximaal plezier op de weg zoeken.',feats:['Naked bike – maximaal plezier','Driecilindermotor – uniek karakter','Agressief vermogen','Licht en wendbaar','Dark Side of Japan']},
'yamaha-tenere':{desc:'Rallyelegende voor de weg. De Yamaha Super Ténéré is geïnspireerd door Dakar-winnaars – krachtige tweecilinder, enorme tank en uitstekende ergonomie voor extreem lange routes. De perfecte reispartner.',feats:['Rally adventure – geïnspireerd door de Dakar','Enorm bereik','Extreem comfortabel','Rijden met passagier','Weg + offroad']},
'ducati-multistrada':{desc:'Italiaanse passie in de vorm van een adventure motor. De Ducati Multistrada 1200 levert brute L-twin kracht, premium elektronische systemen en het kenmerkende Italiaanse geluid. Voor Ducati-liefhebbers.',feats:['Italiaanse L-twin – uniek geluid','Premium elektronica – 4 rijmodi','Weg en offroad','Rijden met passagier','Voor ervaren rijders']},
'ktm-1290':{desc:'Ready to Race in de adventure-wereld. De KTM 1290 Super Adventure is de meest extreme adventure motor in onze vloot. Krachtige V-twin, premium WP-elektronica en de oranje KTM-kleuren. Voor echte avonturiers.',feats:['Krachtigste adventure in de vloot','V-twin 160 pk – extreem vermogen','WP-elektronica – offroad & weg','Premium uitrusting','Uitsluitend voor ervaren rijders']},
'yamaha-pw50':{desc:'Een kleine helper voor een groot begin. De Yamaha PW 50 is een legendarische kindermotor voor de eerste stappen in de motorsport. Automatische versnellingsbak, laag zadel en maximaal 50 cc zijn ideaal voor kinderen vanaf 3 jaar.',feats:['Kindermotor – vanaf 3 jaar','Automatische versnellingsbak','Laag zadel – 485 mm','Gasbegrenzer voor ouders','Legendarische keuze voor beginners']},
'ktm-sx65':{desc:'Wedstrijdmotocross voor jonge rijders. De KTM SX 65 is een echte racemotor in klein formaat – voor kinderen van 7–12 jaar. Krachtige tweetaktmotor, racechassis en de oranje KTM-kleuren.',feats:['Wedstrijdmotocross voor kinderen','Tweetaktmotor – racevermogen','Leeftijd 7–12 jaar','Gesloten circuits / terreinen','Startpunt van een racecarrière']},
'triumph-tiger':{desc:'Een Britse gentleman voor wereldwijd avontuur. De Triumph Tiger 1200 Explorer is een premium adventure motor met driecilindermotor, rijke uitrusting en elegant Brits design. Ideaal voor lange transcontinentale ritten.',feats:['Britse driecilinder – uniek karakter','Premium GT-uitrusting','Transcontinentaal reizen','Rijden met passagier','Elegant design']}
}},
pl:{moto:{
'yamaha-xt660':{desc:'Legendarne supermoto z jednocylindrowym silnikiem. XT 660 X to ikona wśród motocykli supermoto – lekki, zwinny, idealny do miasta i na szosę. Idealny dla posiadaczy prawa jazdy kategorii A2.',feats:['Supermoto – miasto i szosa','Lekki i zwinny','Kategoria prawa jazdy A2','Przejazd przez gęstą zabudowę','Sportowy styl']},
'kawasaki-z900':{desc:'Czterocylindrowy naked bike pełen adrenaliny. Kawasaki Z 900 oferuje brutalną moc, ostry design i nowoczesną elektronikę. Idealny wybór dla jeźdźców, którzy chcą mocy i stylu w jednym.',feats:['Naked bike – sportowa jazda','Silnik czterocylindrowy – brutalna moc','Nowoczesna elektronika','Styl i moc','Dla doświadczonych jeźdźców']},
'yamaha-mt09':{desc:'Trójcylindrowy naked bike o wściekłym charakterze. Yamaha MT-09 to „Dark Side of Japan" – agresywna, zabawna i nieprzewidywalna. Doskonały wybór dla jeźdźców szukających maksymalnej zabawy na drodze.',feats:['Naked bike – maksymalna zabawa','Silnik trójcylindrowy – unikalny charakter','Agresywna moc','Lekki i zwinny','Dark Side of Japan']},
'yamaha-tenere':{desc:'Legendy rajdów na drodze. Yamaha Super Ténéré jest inspirowana zwycięzcami Dakaru – mocny dwucylindrowy silnik, ogromny zbiornik i doskonała ergonomia na ekstremalnie długie trasy. Idealny partner podróży.',feats:['Rally adventure – inspiracja Dakarem','Ogromny zasięg','Ekstremalnie wygodna','Jazda we dwoje','Szosa + teren']},
'ducati-multistrada':{desc:'Włoska pasja w formie motocykla adventure. Ducati Multistrada 1200 oferuje brutalną moc silnika L-twin, premium systemy elektroniczne i charakterystyczny włoski dźwięk. Dla miłośników Ducati.',feats:['Włoski L-twin – unikalny dźwięk','Premium elektronika – 4 tryby jazdy','Szosa i teren','Jazda we dwoje','Dla doświadczonych jeźdźców']},
'ktm-1290':{desc:'Ready to Race w świecie adventure. KTM 1290 Super Adventure to najbardziej ekstremalny motocykl adventure w naszej flocie. Mocny V-twin, premium elektronika WP i pomarańczowe barwy KTM. Dla prawdziwych poszukiwaczy przygód.',feats:['Najmocniejszy adventure we flocie','V-twin 160 KM – ekstremalna moc','Elektronika WP – teren i szosa','Wyposażenie premium','Wyłącznie dla doświadczonych']},
'yamaha-pw50':{desc:'Mały pomocnik na wielkie początki. Yamaha PW 50 to legendarny motocykl dziecięcy na pierwsze kroki w motosporcie. Automatyczna skrzynia biegów, niskie siedzenie i maksymalnie 50 ccm są idealne dla dzieci od 3 lat.',feats:['Motocykl dziecięcy – od 3 lat','Automatyczna skrzynia biegów','Niskie siedzenie – 485 mm','Ogranicznik gazu dla rodziców','Legendarny wybór na początek']},
'ktm-sx65':{desc:'Wyścigowy motocross dla młodych zawodników. KTM SX 65 to prawdziwy motocykl wyścigowy w małym wydaniu – dla dzieci w wieku 7–12 lat. Mocny silnik dwusuwowy, wyścigowe podwozie i pomarańczowe barwy KTM.',feats:['Wyścigowy motocross dla dzieci','Silnik dwusuwowy – wyścigowa moc','Wiek 7–12 lat','Zamknięte tory / tereny','Punkt startowy kariery wyścigowej']},
'triumph-tiger':{desc:'Brytyjski dżentelmen na światowe przygody. Triumph Tiger 1200 Explorer to premium motocykl adventure z trójcylindrowym silnikiem, bogatym wyposażeniem i eleganckim brytyjskim designem. Idealny na długie podróże transkontynentalne.',feats:['Brytyjski trójcylindrowy – unikalny charakter','Wyposażenie GT premium','Podróże transkontynentalne','Jazda we dwoje','Elegancki design']}
}}
});
})();
