// i18n-tpl.js – Template screen translations for MotoGo24
(function(){
function m(s){for(var l in s){if(!I18N[l])continue;for(var k in s[l])I18N[l][k]=s[l][k];}}
m({
cs:{
proto:{
title:'Předávací protokol',subtitle:'Přečtěte a potvrďte digitálním podpisem',identification:'Identifikace',lessor:'Pronajímatel',lessee:'Nájemce',contractNum:'Číslo smlouvy',motorcycle:'Motocykl',brandModel:'Značka / Model',vin:'VIN',odometer:'Tachometr při předání',fuelLevel:'Stav paliva',fuelFull:'Plná nádrž',equipment:'Výbava a příslušenství',checkAll:'Zaškrtněte vše co bylo předáno:',keys:'Klíče (od motorky + od kufru)',greenCard:'Zelená karta (mezinárodní pojištění)',regCert:'Malý technický průkaz',reflVests:'2× reflexní vesta',firstAid:'Motolékárnička',accidentForm:'Záznam o dopravní nehodě s propiskou',balaclava:'Kukla (nová – zůstává nájemci)',riderHelmet:'Helma řidiče',gloves:'Rukavice',jacket:'Bunda',trousers:'Kalhoty',otherNote:'Ostatní příslušenství (poznámka)',otherPlaceholder:'kufry, GPS, boty...',condition:'Potvrzení stavu',damageLabel:'Existující poškození při předání (pokud žádné, nechte prázdné)',damagePlaceholder:'Popis stávajících škrábanců, poškození...',conditionText:'Nájemce potvrzuje, že se s Předávacím protokolem seznámil, souhlasí s jeho obsahem a přebírá motocykl ve výše uvedeném stavu.',digitalSign:'Digitální podpis',signInstr:'Potvrďte svou totožnost pro digitální podpis protokolu:',faceTouch:'Face / Touch ID',pinCode:'PIN kód',enterPin:'Zadejte váš PIN (heslo z profilu)',confirmSign:'Potvrdit podpis',protocolSigned:'Protokol podepsán',submitProtocol:'Odeslat protokol MotoGo24'
},
edit:{
editTitle:'Upravit rezervaci',tabExtend:'Prodloužit / Změna místa',tabShorten:'Zkrácení / Změna místa',dateSection:'Termín',yourReservation:'Vaše stávající rezervace',pickupDelivery:'Přistavení motorky',returnPickup:'Vrácení motorky',atBranch:'Na pobočce',toYourAddr:'Přistavení na vaši adresu',fromYourAddr:'Odvoz z vaší adresy',deliveryAddr:'Adresa přistavení',returnAddr:'Adresa vrácení',deliveryTime:'Čas přistavení',returnTime:'Čas vrácení',enterAddr:'Zadejte adresu',branchChange:'Změna pobočky',active:'Aktivní',comingSoon:'Připravujeme',soonLabel:'Již brzy',motoChange:'Změna motorky',currentMoto:'Aktuální motorka',selectNewMoto:'Vyberte novou motorku',extras:'Doplňky',priceChange:'Změna ceny',origPrice:'Původní cena',extension:'Prodloužení',shortening:'Zkrácení (vrácení)',returnFee:'Odvoz na vlastní adresu',returnDiff:'Rozdíl odvozu (nové místo)',motoDiff:'Změna motorky',extrasLabel:'Doplňky',toPayRefund:'K doplatku / vrácení',saveChanges:'Uložit změny →',cancelNote:'Storno podmínky: 7+ dní = 100 % vrácení · 2–7 dní = 50 % · méně než 2 dny = bez vrácení.',calLegCurrent:'Stávající',calLegShortened:'Zkráceno'
},
rdtl:{
resDetail:'Detail rezervace',motoSection:'Motorka',model:'Model',category:'Kategorie',pickupLabel:'Vyzvednutí',returnLabel:'Vrácení',duration:'Délka výpůjčky',pickupPlace:'Místo vyzvednutí',returnPlace:'Místo vrácení',paySection:'Platba',pricePerDay:'Cena za den',deposit:'Záloha',noDeposit:'Neúčtujeme ✓',totalLabel:'Celkem',payMethod:'Způsob platby',rideHistory:'Průběh výpůjčky',totalPrice:'Celková cena',docsDownload:'Doklady ke stažení',advanceInvoice:'Zálohová faktura',handoverProtocol:'Předávací protokol',digitalView:'Digitální · zobrazit a podepsat',finalInvoice:'Konečná faktura',myRes:'Moje rezervace',resManagement:'Správa všech rezervací',filterAll:'Vše',filterActive:'Aktivní',filterUpcoming:'Nadcházející',filterDone:'Dokončené',tapToRate:'Klepněte na hvězdičku pro hodnocení',bookAgain:'Znovu rezervovat',contract:'Smlouva',invoice:'Faktura',contractsTitle:'Dokumenty a smlouvy',contractsSub:'Archiv smluvní dokumentace',gdprAccess:'Přístupné pouze vám. Zpracování dle GDPR.'
}
},
en:{
proto:{
title:'Handover Protocol',subtitle:'Read and confirm with a digital signature',identification:'Identification',lessor:'Lessor',lessee:'Lessee',contractNum:'Contract number',motorcycle:'Motorcycle',brandModel:'Brand / Model',vin:'VIN',odometer:'Odometer at handover',fuelLevel:'Fuel level',fuelFull:'Full tank',equipment:'Equipment and accessories',checkAll:'Check all items handed over:',keys:'Keys (motorcycle + top case)',greenCard:'Green card (international insurance)',regCert:'Registration certificate',reflVests:'2× reflective vest',firstAid:'First-aid kit',accidentForm:'Accident report form with pen',balaclava:'Balaclava (new – stays with the lessee)',riderHelmet:'Rider helmet',gloves:'Gloves',jacket:'Jacket',trousers:'Trousers',otherNote:'Other accessories (note)',otherPlaceholder:'panniers, GPS, boots...',condition:'Condition confirmation',damageLabel:'Existing damage at handover (leave blank if none)',damagePlaceholder:'Description of existing scratches, damage...',conditionText:'The lessee confirms having read the Handover Protocol, agrees with its content and accepts the motorcycle in the condition described above.',digitalSign:'Digital signature',signInstr:'Confirm your identity for the digital signature of the protocol:',faceTouch:'Face / Touch ID',pinCode:'PIN code',enterPin:'Enter your PIN (profile password)',confirmSign:'Confirm signature',protocolSigned:'Protocol signed',submitProtocol:'Submit protocol to MotoGo24'
},
edit:{
editTitle:'Edit reservation',tabExtend:'Extend / Change location',tabShorten:'Shorten / Change location',dateSection:'Dates',yourReservation:'Your current reservation',pickupDelivery:'Motorcycle delivery',returnPickup:'Motorcycle return',atBranch:'At the branch',toYourAddr:'Delivery to your address',fromYourAddr:'Pick-up from your address',deliveryAddr:'Delivery address',returnAddr:'Return address',deliveryTime:'Delivery time',returnTime:'Return time',enterAddr:'Enter address',branchChange:'Branch change',active:'Active',comingSoon:'Coming soon',soonLabel:'Soon',motoChange:'Motorcycle change',currentMoto:'Current motorcycle',selectNewMoto:'Select a new motorcycle',extras:'Extras',priceChange:'Price change',origPrice:'Original price',extension:'Extension',shortening:'Shortening (refund)',returnFee:'Pick-up from your address',returnDiff:'Pick-up difference (new location)',motoDiff:'Motorcycle change',extrasLabel:'Extras',toPayRefund:'To pay / refund',saveChanges:'Save changes →',cancelNote:'Cancellation policy: 7+ days = 100% refund · 2–7 days = 50% · less than 2 days = no refund.',calLegCurrent:'Current',calLegShortened:'Shortened'
},
rdtl:{
resDetail:'Reservation detail',motoSection:'Motorcycle',model:'Model',category:'Category',pickupLabel:'Pick-up',returnLabel:'Return',duration:'Rental duration',pickupPlace:'Pick-up location',returnPlace:'Return location',paySection:'Payment',pricePerDay:'Price per day',deposit:'Deposit',noDeposit:'Not charged ✓',totalLabel:'Total',payMethod:'Payment method',rideHistory:'Ride history',totalPrice:'Total price',docsDownload:'Documents to download',advanceInvoice:'Advance invoice',handoverProtocol:'Handover protocol',digitalView:'Digital · view and sign',finalInvoice:'Final invoice',myRes:'My reservations',resManagement:'Manage all reservations',filterAll:'All',filterActive:'Active',filterUpcoming:'Upcoming',filterDone:'Completed',tapToRate:'Tap a star to rate',bookAgain:'Book again',contract:'Contract',invoice:'Invoice',contractsTitle:'Documents and contracts',contractsSub:'Contract documentation archive',gdprAccess:'Accessible only to you. Processed under GDPR.'
}
},
de:{
proto:{
title:'Übergabeprotokoll',subtitle:'Lesen und mit digitaler Unterschrift bestätigen',identification:'Identifikation',lessor:'Vermieter',lessee:'Mieter',contractNum:'Vertragsnummer',motorcycle:'Motorrad',brandModel:'Marke / Modell',vin:'VIN',odometer:'Tachostand bei Übergabe',fuelLevel:'Tankstand',fuelFull:'Voller Tank',equipment:'Ausrüstung und Zubehör',checkAll:'Alles Übergebene ankreuzen:',keys:'Schlüssel (Motorrad + Koffer)',greenCard:'Grüne Karte (internationale Versicherung)',regCert:'Zulassungsbescheinigung',reflVests:'2× Warnweste',firstAid:'Verbandskasten',accidentForm:'Unfallbericht mit Kugelschreiber',balaclava:'Sturmhaube (neu – verbleibt beim Mieter)',riderHelmet:'Fahrerhelm',gloves:'Handschuhe',jacket:'Jacke',trousers:'Hose',otherNote:'Sonstiges Zubehör (Anmerkung)',otherPlaceholder:'Koffer, GPS, Stiefel...',condition:'Zustandsbestätigung',damageLabel:'Vorhandene Schäden bei Übergabe (leer lassen, wenn keine)',damagePlaceholder:'Beschreibung vorhandener Kratzer, Schäden...',conditionText:'Der Mieter bestätigt, das Übergabeprotokoll gelesen zu haben, stimmt dem Inhalt zu und übernimmt das Motorrad im oben beschriebenen Zustand.',digitalSign:'Digitale Unterschrift',signInstr:'Bestätigen Sie Ihre Identität für die digitale Unterschrift des Protokolls:',faceTouch:'Face / Touch ID',pinCode:'PIN-Code',enterPin:'Geben Sie Ihre PIN ein (Profilpasswort)',confirmSign:'Unterschrift bestätigen',protocolSigned:'Protokoll unterschrieben',submitProtocol:'Protokoll an MotoGo24 senden'
},
edit:{
editTitle:'Reservierung bearbeiten',tabExtend:'Verlängern / Ort ändern',tabShorten:'Verkürzen / Ort ändern',dateSection:'Termin',yourReservation:'Ihre aktuelle Reservierung',pickupDelivery:'Motorrad-Zustellung',returnPickup:'Motorrad-Rückgabe',atBranch:'In der Filiale',toYourAddr:'Zustellung an Ihre Adresse',fromYourAddr:'Abholung von Ihrer Adresse',deliveryAddr:'Zustelladresse',returnAddr:'Rückgabeadresse',deliveryTime:'Zustellzeit',returnTime:'Rückgabezeit',enterAddr:'Adresse eingeben',branchChange:'Filialwechsel',active:'Aktiv',comingSoon:'Demnächst',soonLabel:'Bald',motoChange:'Motorradwechsel',currentMoto:'Aktuelles Motorrad',selectNewMoto:'Neues Motorrad wählen',extras:'Zubehör',priceChange:'Preisänderung',origPrice:'Ursprünglicher Preis',extension:'Verlängerung',shortening:'Verkürzung (Erstattung)',returnFee:'Abholung von eigener Adresse',returnDiff:'Abholdifferenz (neuer Ort)',motoDiff:'Motorradwechsel',extrasLabel:'Zubehör',toPayRefund:'Nachzahlung / Erstattung',saveChanges:'Änderungen speichern →',cancelNote:'Stornobedingungen: 7+ Tage = 100 % Erstattung · 2–7 Tage = 50 % · weniger als 2 Tage = keine Erstattung.',calLegCurrent:'Aktuell',calLegShortened:'Verkürzt'
},
rdtl:{
resDetail:'Reservierungsdetail',motoSection:'Motorrad',model:'Modell',category:'Kategorie',pickupLabel:'Abholung',returnLabel:'Rückgabe',duration:'Mietdauer',pickupPlace:'Abholort',returnPlace:'Rückgabeort',paySection:'Zahlung',pricePerDay:'Preis pro Tag',deposit:'Kaution',noDeposit:'Wird nicht berechnet ✓',totalLabel:'Gesamt',payMethod:'Zahlungsmethode',rideHistory:'Mietverlauf',totalPrice:'Gesamtpreis',docsDownload:'Dokumente zum Download',advanceInvoice:'Vorauszahlungsrechnung',handoverProtocol:'Übergabeprotokoll',digitalView:'Digital · anzeigen und unterschreiben',finalInvoice:'Schlussrechnung',myRes:'Meine Reservierungen',resManagement:'Alle Reservierungen verwalten',filterAll:'Alle',filterActive:'Aktiv',filterUpcoming:'Bevorstehend',filterDone:'Abgeschlossen',tapToRate:'Tippen Sie auf einen Stern zur Bewertung',bookAgain:'Erneut buchen',contract:'Vertrag',invoice:'Rechnung',contractsTitle:'Dokumente und Verträge',contractsSub:'Vertragsdokumentationsarchiv',gdprAccess:'Nur für Sie zugänglich. Verarbeitung gemäß DSGVO.'
}
},
es:{
proto:{
title:'Protocolo de entrega',subtitle:'Lea y confirme con firma digital',identification:'Identificación',lessor:'Arrendador',lessee:'Arrendatario',contractNum:'Número de contrato',motorcycle:'Motocicleta',brandModel:'Marca / Modelo',vin:'VIN',odometer:'Cuentakilómetros en la entrega',fuelLevel:'Nivel de combustible',fuelFull:'Tanque lleno',equipment:'Equipamiento y accesorios',checkAll:'Marque todo lo entregado:',keys:'Llaves (moto + cofre)',greenCard:'Carta verde (seguro internacional)',regCert:'Permiso de circulación',reflVests:'2× chaleco reflectante',firstAid:'Botiquín de primeros auxilios',accidentForm:'Formulario de accidente con bolígrafo',balaclava:'Pasamontañas (nuevo – queda para el arrendatario)',riderHelmet:'Casco del piloto',gloves:'Guantes',jacket:'Chaqueta',trousers:'Pantalones',otherNote:'Otros accesorios (nota)',otherPlaceholder:'maletas, GPS, botas...',condition:'Confirmación del estado',damageLabel:'Daños existentes en la entrega (dejar en blanco si no hay)',damagePlaceholder:'Descripción de arañazos, daños existentes...',conditionText:'El arrendatario confirma haber leído el Protocolo de entrega, está de acuerdo con su contenido y acepta la motocicleta en el estado descrito.',digitalSign:'Firma digital',signInstr:'Confirme su identidad para la firma digital del protocolo:',faceTouch:'Face / Touch ID',pinCode:'Código PIN',enterPin:'Introduzca su PIN (contraseña del perfil)',confirmSign:'Confirmar firma',protocolSigned:'Protocolo firmado',submitProtocol:'Enviar protocolo a MotoGo24'
},
edit:{
editTitle:'Editar reserva',tabExtend:'Ampliar / Cambiar lugar',tabShorten:'Acortar / Cambiar lugar',dateSection:'Fechas',yourReservation:'Su reserva actual',pickupDelivery:'Entrega de la moto',returnPickup:'Devolución de la moto',atBranch:'En la sucursal',toYourAddr:'Entrega en su dirección',fromYourAddr:'Recogida en su dirección',deliveryAddr:'Dirección de entrega',returnAddr:'Dirección de devolución',deliveryTime:'Hora de entrega',returnTime:'Hora de devolución',enterAddr:'Introduzca dirección',branchChange:'Cambio de sucursal',active:'Activa',comingSoon:'Próximamente',soonLabel:'Pronto',motoChange:'Cambio de moto',currentMoto:'Moto actual',selectNewMoto:'Seleccione una nueva moto',extras:'Extras',priceChange:'Cambio de precio',origPrice:'Precio original',extension:'Ampliación',shortening:'Acortamiento (reembolso)',returnFee:'Recogida en su dirección',returnDiff:'Diferencia de recogida (nuevo lugar)',motoDiff:'Cambio de moto',extrasLabel:'Extras',toPayRefund:'A pagar / reembolso',saveChanges:'Guardar cambios →',cancelNote:'Política de cancelación: 7+ días = 100 % reembolso · 2–7 días = 50 % · menos de 2 días = sin reembolso.',calLegCurrent:'Actual',calLegShortened:'Acortado'
},
rdtl:{
resDetail:'Detalle de la reserva',motoSection:'Motocicleta',model:'Modelo',category:'Categoría',pickupLabel:'Recogida',returnLabel:'Devolución',duration:'Duración del alquiler',pickupPlace:'Lugar de recogida',returnPlace:'Lugar de devolución',paySection:'Pago',pricePerDay:'Precio por día',deposit:'Depósito',noDeposit:'No se cobra ✓',totalLabel:'Total',payMethod:'Método de pago',rideHistory:'Historial del alquiler',totalPrice:'Precio total',docsDownload:'Documentos para descargar',advanceInvoice:'Factura anticipada',handoverProtocol:'Protocolo de entrega',digitalView:'Digital · ver y firmar',finalInvoice:'Factura final',myRes:'Mis reservas',resManagement:'Gestionar todas las reservas',filterAll:'Todas',filterActive:'Activas',filterUpcoming:'Próximas',filterDone:'Completadas',tapToRate:'Pulse una estrella para valorar',bookAgain:'Reservar de nuevo',contract:'Contrato',invoice:'Factura',contractsTitle:'Documentos y contratos',contractsSub:'Archivo de documentación contractual',gdprAccess:'Accesible solo para usted. Tratamiento según RGPD.'
}
},
fr:{
proto:{
title:'Protocole de remise',subtitle:'Lisez et confirmez avec une signature numérique',identification:'Identification',lessor:'Bailleur',lessee:'Locataire',contractNum:'Numéro de contrat',motorcycle:'Moto',brandModel:'Marque / Modèle',vin:'VIN',odometer:'Compteur à la remise',fuelLevel:'Niveau de carburant',fuelFull:'Réservoir plein',equipment:'Équipement et accessoires',checkAll:'Cochez tout ce qui a été remis :',keys:'Clés (moto + top case)',greenCard:'Carte verte (assurance internationale)',regCert:'Certificat d\'immatriculation',reflVests:'2× gilet réfléchissant',firstAid:'Trousse de secours',accidentForm:'Constat d\'accident avec stylo',balaclava:'Cagoule (neuve – reste au locataire)',riderHelmet:'Casque pilote',gloves:'Gants',jacket:'Veste',trousers:'Pantalon',otherNote:'Autres accessoires (note)',otherPlaceholder:'valises, GPS, bottes...',condition:'Confirmation de l\'état',damageLabel:'Dommages existants à la remise (laisser vide si aucun)',damagePlaceholder:'Description des rayures, dommages existants...',conditionText:'Le locataire confirme avoir lu le Protocole de remise, en accepte le contenu et prend en charge la moto dans l\'état décrit ci-dessus.',digitalSign:'Signature numérique',signInstr:'Confirmez votre identité pour la signature numérique du protocole :',faceTouch:'Face / Touch ID',pinCode:'Code PIN',enterPin:'Saisissez votre PIN (mot de passe du profil)',confirmSign:'Confirmer la signature',protocolSigned:'Protocole signé',submitProtocol:'Envoyer le protocole à MotoGo24'
},
edit:{
editTitle:'Modifier la réservation',tabExtend:'Prolonger / Changer de lieu',tabShorten:'Raccourcir / Changer de lieu',dateSection:'Dates',yourReservation:'Votre réservation actuelle',pickupDelivery:'Livraison de la moto',returnPickup:'Retour de la moto',atBranch:'En agence',toYourAddr:'Livraison à votre adresse',fromYourAddr:'Enlèvement à votre adresse',deliveryAddr:'Adresse de livraison',returnAddr:'Adresse de retour',deliveryTime:'Heure de livraison',returnTime:'Heure de retour',enterAddr:'Saisissez l\'adresse',branchChange:'Changement d\'agence',active:'Active',comingSoon:'Bientôt disponible',soonLabel:'Bientôt',motoChange:'Changement de moto',currentMoto:'Moto actuelle',selectNewMoto:'Sélectionnez une nouvelle moto',extras:'Accessoires',priceChange:'Changement de prix',origPrice:'Prix d\'origine',extension:'Prolongation',shortening:'Raccourcissement (remboursement)',returnFee:'Enlèvement à votre adresse',returnDiff:'Différence d\'enlèvement (nouveau lieu)',motoDiff:'Changement de moto',extrasLabel:'Accessoires',toPayRefund:'À payer / remboursement',saveChanges:'Enregistrer les modifications →',cancelNote:'Conditions d\'annulation : 7+ jours = 100 % remboursement · 2–7 jours = 50 % · moins de 2 jours = sans remboursement.',calLegCurrent:'Actuelle',calLegShortened:'Raccourcie'
},
rdtl:{
resDetail:'Détail de la réservation',motoSection:'Moto',model:'Modèle',category:'Catégorie',pickupLabel:'Retrait',returnLabel:'Retour',duration:'Durée de location',pickupPlace:'Lieu de retrait',returnPlace:'Lieu de retour',paySection:'Paiement',pricePerDay:'Prix par jour',deposit:'Caution',noDeposit:'Non facturée ✓',totalLabel:'Total',payMethod:'Mode de paiement',rideHistory:'Historique de location',totalPrice:'Prix total',docsDownload:'Documents à télécharger',advanceInvoice:'Facture d\'acompte',handoverProtocol:'Protocole de remise',digitalView:'Numérique · afficher et signer',finalInvoice:'Facture finale',myRes:'Mes réservations',resManagement:'Gérer toutes les réservations',filterAll:'Toutes',filterActive:'Actives',filterUpcoming:'À venir',filterDone:'Terminées',tapToRate:'Appuyez sur une étoile pour évaluer',bookAgain:'Réserver à nouveau',contract:'Contrat',invoice:'Facture',contractsTitle:'Documents et contrats',contractsSub:'Archive de documentation contractuelle',gdprAccess:'Accessible uniquement par vous. Traitement conforme au RGPD.'
}
},
nl:{
proto:{
title:'Overdrachtsprotocol',subtitle:'Lees en bevestig met een digitale handtekening',identification:'Identificatie',lessor:'Verhuurder',lessee:'Huurder',contractNum:'Contractnummer',motorcycle:'Motor',brandModel:'Merk / Model',vin:'VIN',odometer:'Kilometerstand bij overdracht',fuelLevel:'Brandstofniveau',fuelFull:'Volle tank',equipment:'Uitrusting en accessoires',checkAll:'Vink alles aan wat is overgedragen:',keys:'Sleutels (motor + topkoffer)',greenCard:'Groene kaart (internationale verzekering)',regCert:'Kentekenbewijs',reflVests:'2× reflecterend vest',firstAid:'EHBO-set',accidentForm:'Schadeformulier met pen',balaclava:'Bivakmuts (nieuw – blijft bij de huurder)',riderHelmet:'Helm rijder',gloves:'Handschoenen',jacket:'Jas',trousers:'Broek',otherNote:'Overige accessoires (opmerking)',otherPlaceholder:'koffers, GPS, laarzen...',condition:'Bevestiging van de staat',damageLabel:'Bestaande schade bij overdracht (leeg laten indien geen)',damagePlaceholder:'Beschrijving van bestaande krassen, schade...',conditionText:'De huurder bevestigt het Overdrachtsprotocol te hebben gelezen, gaat akkoord met de inhoud en aanvaardt de motor in de hierboven beschreven staat.',digitalSign:'Digitale handtekening',signInstr:'Bevestig uw identiteit voor de digitale ondertekening van het protocol:',faceTouch:'Face / Touch ID',pinCode:'PIN-code',enterPin:'Voer uw PIN in (profielwachtwoord)',confirmSign:'Handtekening bevestigen',protocolSigned:'Protocol ondertekend',submitProtocol:'Protocol verzenden naar MotoGo24'
},
edit:{
editTitle:'Reservering bewerken',tabExtend:'Verlengen / Locatie wijzigen',tabShorten:'Verkorten / Locatie wijzigen',dateSection:'Data',yourReservation:'Uw huidige reservering',pickupDelivery:'Bezorging van de motor',returnPickup:'Retour van de motor',atBranch:'Bij het filiaal',toYourAddr:'Bezorging op uw adres',fromYourAddr:'Ophalen op uw adres',deliveryAddr:'Bezorgadres',returnAddr:'Retouradres',deliveryTime:'Bezorgtijd',returnTime:'Retourtijd',enterAddr:'Voer adres in',branchChange:'Filiaalwissel',active:'Actief',comingSoon:'Binnenkort beschikbaar',soonLabel:'Binnenkort',motoChange:'Motorwissel',currentMoto:'Huidige motor',selectNewMoto:'Selecteer een nieuwe motor',extras:'Extra\'s',priceChange:'Prijswijziging',origPrice:'Oorspronkelijke prijs',extension:'Verlenging',shortening:'Verkorting (terugbetaling)',returnFee:'Ophalen van eigen adres',returnDiff:'Ophaaldifferentie (nieuwe locatie)',motoDiff:'Motorwissel',extrasLabel:'Extra\'s',toPayRefund:'Bij te betalen / terugbetaling',saveChanges:'Wijzigingen opslaan →',cancelNote:'Annuleringsvoorwaarden: 7+ dagen = 100 % terugbetaling · 2–7 dagen = 50 % · minder dan 2 dagen = geen terugbetaling.',calLegCurrent:'Huidig',calLegShortened:'Verkort'
},
rdtl:{
resDetail:'Reserveringsdetail',motoSection:'Motor',model:'Model',category:'Categorie',pickupLabel:'Ophalen',returnLabel:'Retour',duration:'Verhuurduur',pickupPlace:'Ophaallocatie',returnPlace:'Retourlocatie',paySection:'Betaling',pricePerDay:'Prijs per dag',deposit:'Borg',noDeposit:'Wordt niet berekend ✓',totalLabel:'Totaal',payMethod:'Betaalmethode',rideHistory:'Verhuurgeschiedenis',totalPrice:'Totaalprijs',docsDownload:'Documenten om te downloaden',advanceInvoice:'Voorschotfactuur',handoverProtocol:'Overdrachtsprotocol',digitalView:'Digitaal · bekijken en ondertekenen',finalInvoice:'Eindfactuur',myRes:'Mijn reserveringen',resManagement:'Alle reserveringen beheren',filterAll:'Alle',filterActive:'Actief',filterUpcoming:'Aankomend',filterDone:'Voltooid',tapToRate:'Tik op een ster om te beoordelen',bookAgain:'Opnieuw boeken',contract:'Contract',invoice:'Factuur',contractsTitle:'Documenten en contracten',contractsSub:'Archief van contractdocumentatie',gdprAccess:'Alleen voor u toegankelijk. Verwerking conform AVG.'
}
},
pl:{
proto:{
title:'Protokół przekazania',subtitle:'Przeczytaj i potwierdź podpisem cyfrowym',identification:'Identyfikacja',lessor:'Wynajmujący',lessee:'Najemca',contractNum:'Numer umowy',motorcycle:'Motocykl',brandModel:'Marka / Model',vin:'VIN',odometer:'Przebieg przy przekazaniu',fuelLevel:'Poziom paliwa',fuelFull:'Pełny bak',equipment:'Wyposażenie i akcesoria',checkAll:'Zaznacz wszystko, co zostało przekazane:',keys:'Klucze (motocykl + kufer)',greenCard:'Zielona karta (ubezpieczenie międzynarodowe)',regCert:'Dowód rejestracyjny',reflVests:'2× kamizelka odblaskowa',firstAid:'Apteczka',accidentForm:'Formularz wypadkowy z długopisem',balaclava:'Kominiarka (nowa – zostaje u najemcy)',riderHelmet:'Kask kierowcy',gloves:'Rękawice',jacket:'Kurtka',trousers:'Spodnie',otherNote:'Pozostałe akcesoria (uwaga)',otherPlaceholder:'kufry, GPS, buty...',condition:'Potwierdzenie stanu',damageLabel:'Istniejące uszkodzenia przy przekazaniu (zostaw puste, jeśli brak)',damagePlaceholder:'Opis istniejących zarysowań, uszkodzeń...',conditionText:'Najemca potwierdza, że zapoznał się z Protokołem przekazania, zgadza się z jego treścią i przyjmuje motocykl w opisanym powyżej stanie.',digitalSign:'Podpis cyfrowy',signInstr:'Potwierdź swoją tożsamość w celu cyfrowego podpisania protokołu:',faceTouch:'Face / Touch ID',pinCode:'Kod PIN',enterPin:'Wpisz swój PIN (hasło z profilu)',confirmSign:'Potwierdź podpis',protocolSigned:'Protokół podpisany',submitProtocol:'Wyślij protokół do MotoGo24'
},
edit:{
editTitle:'Edytuj rezerwację',tabExtend:'Przedłuż / Zmień miejsce',tabShorten:'Skróć / Zmień miejsce',dateSection:'Termin',yourReservation:'Twoja aktualna rezerwacja',pickupDelivery:'Dostawa motocykla',returnPickup:'Zwrot motocykla',atBranch:'W oddziale',toYourAddr:'Dostawa pod Twój adres',fromYourAddr:'Odbiór z Twojego adresu',deliveryAddr:'Adres dostawy',returnAddr:'Adres zwrotu',deliveryTime:'Czas dostawy',returnTime:'Czas zwrotu',enterAddr:'Wpisz adres',branchChange:'Zmiana oddziału',active:'Aktywna',comingSoon:'Wkrótce dostępne',soonLabel:'Wkrótce',motoChange:'Zmiana motocykla',currentMoto:'Aktualny motocykl',selectNewMoto:'Wybierz nowy motocykl',extras:'Dodatki',priceChange:'Zmiana ceny',origPrice:'Pierwotna cena',extension:'Przedłużenie',shortening:'Skrócenie (zwrot)',returnFee:'Odbiór z własnego adresu',returnDiff:'Różnica odbioru (nowe miejsce)',motoDiff:'Zmiana motocykla',extrasLabel:'Dodatki',toPayRefund:'Do dopłaty / zwrotu',saveChanges:'Zapisz zmiany →',cancelNote:'Warunki anulowania: 7+ dni = 100 % zwrotu · 2–7 dni = 50 % · mniej niż 2 dni = bez zwrotu.',calLegCurrent:'Aktualna',calLegShortened:'Skrócona'
},
rdtl:{
resDetail:'Szczegóły rezerwacji',motoSection:'Motocykl',model:'Model',category:'Kategoria',pickupLabel:'Odbiór',returnLabel:'Zwrot',duration:'Czas wynajmu',pickupPlace:'Miejsce odbioru',returnPlace:'Miejsce zwrotu',paySection:'Płatność',pricePerDay:'Cena za dzień',deposit:'Kaucja',noDeposit:'Nie pobieramy ✓',totalLabel:'Razem',payMethod:'Metoda płatności',rideHistory:'Przebieg wynajmu',totalPrice:'Cena całkowita',docsDownload:'Dokumenty do pobrania',advanceInvoice:'Faktura zaliczkowa',handoverProtocol:'Protokół przekazania',digitalView:'Cyfrowy · wyświetl i podpisz',finalInvoice:'Faktura końcowa',myRes:'Moje rezerwacje',resManagement:'Zarządzanie wszystkimi rezerwacjami',filterAll:'Wszystkie',filterActive:'Aktywne',filterUpcoming:'Nadchodzące',filterDone:'Zakończone',tapToRate:'Dotknij gwiazdki, aby ocenić',bookAgain:'Zarezerwuj ponownie',contract:'Umowa',invoice:'Faktura',contractsTitle:'Dokumenty i umowy',contractsSub:'Archiwum dokumentacji umownej',gdprAccess:'Dostępne tylko dla Ciebie. Przetwarzanie zgodnie z RODO.'
}
}
});
})();
