// i18n-perm.js – Permission overlay + misc hardcoded translations for MotoGo24
(function(){
function m(s){for(var l in s){if(!I18N[l])continue;for(var k in s[l])I18N[l][k]=s[l][k];}}
m({
cs:{perm:{title:'Vítejte v MotoGo24',sub:'Pro plnou funkčnost potřebujeme váš souhlas',biometric:'Biometrické ověření',biometricDesc:'Rychlé přihlášení pomocí otisku prstu',location:'Poloha',locationDesc:'Navigace k půjčovně, sdílení pozice při poruše',camera:'Fotoaparát',cameraDesc:'Skenování dokladů, dokumentace škod',microphone:'Mikrofon',microphoneDesc:'Hlasové dotazy pro AI asistenta',notifications:'Oznámení',notificationsDesc:'SOS aktualizace, zprávy z MotoGo24, stav rezervací',allowAll:'Povolit vše a pokračovat →',skip:'Přeskočit – nastavím později'},
offline:{title:'Žádné připojení k internetu',sub:'Pro používání MotoGo24 je potřeba internetové připojení.',hint:'Zkontrolujte Wi-Fi nebo mobilní data.',retryBtn:'Zkusit znovu',stillOffline:'Stále bez připojení…'}},
en:{perm:{title:'Welcome to MotoGo24',sub:'We need your consent for full functionality',biometric:'Biometric verification',biometricDesc:'Quick login with fingerprint',location:'Location',locationDesc:'Navigation to branch, sharing position during breakdown',camera:'Camera',cameraDesc:'Document scanning, damage documentation',microphone:'Microphone',microphoneDesc:'Voice queries for AI assistant',notifications:'Notifications',notificationsDesc:'SOS updates, messages from MotoGo24, reservation status',allowAll:'Allow all and continue →',skip:'Skip – I\'ll set up later'},
offline:{title:'No internet connection',sub:'MotoGo24 requires an internet connection.',hint:'Check your Wi-Fi or mobile data.',retryBtn:'Try again',stillOffline:'Still no connection…'}},
de:{perm:{title:'Willkommen bei MotoGo24',sub:'Für volle Funktionalität benötigen wir Ihre Zustimmung',biometric:'Biometrische Verifizierung',biometricDesc:'Schnelle Anmeldung per Fingerabdruck',location:'Standort',locationDesc:'Navigation zur Filiale, Standortfreigabe bei Panne',camera:'Kamera',cameraDesc:'Dokumentenscan, Schadensdokumentation',microphone:'Mikrofon',microphoneDesc:'Sprachbefehle für den KI-Assistenten',notifications:'Benachrichtigungen',notificationsDesc:'SOS-Updates, Nachrichten von MotoGo24, Buchungsstatus',allowAll:'Alle erlauben und fortfahren →',skip:'Überspringen – später einstellen'},
offline:{title:'Keine Internetverbindung',sub:'MotoGo24 benötigt eine Internetverbindung.',hint:'Prüfen Sie WLAN oder mobile Daten.',retryBtn:'Erneut versuchen',stillOffline:'Immer noch keine Verbindung…'}},
es:{perm:{title:'Bienvenido a MotoGo24',sub:'Necesitamos su consentimiento para la funcionalidad completa',biometric:'Verificación biométrica',biometricDesc:'Inicio rápido con huella dactilar',location:'Ubicación',locationDesc:'Navegación a la sucursal, compartir posición durante avería',camera:'Cámara',cameraDesc:'Escaneo de documentos, documentación de daños',microphone:'Micrófono',microphoneDesc:'Consultas de voz para el asistente IA',notifications:'Notificaciones',notificationsDesc:'Actualizaciones SOS, mensajes de MotoGo24, estado de reservas',allowAll:'Permitir todo y continuar →',skip:'Omitir – lo configuraré más tarde'},
offline:{title:'Sin conexión a Internet',sub:'MotoGo24 requiere conexión a Internet.',hint:'Compruebe su Wi-Fi o datos móviles.',retryBtn:'Reintentar',stillOffline:'Aún sin conexión…'}},
fr:{perm:{title:'Bienvenue chez MotoGo24',sub:'Nous avons besoin de votre consentement pour toutes les fonctionnalités',biometric:'Vérification biométrique',biometricDesc:'Connexion rapide par empreinte digitale',location:'Position',locationDesc:'Navigation vers l\'agence, partage de position en cas de panne',camera:'Appareil photo',cameraDesc:'Numérisation de documents, documentation des dommages',microphone:'Microphone',microphoneDesc:'Questions vocales pour l\'assistant IA',notifications:'Notifications',notificationsDesc:'Mises à jour SOS, messages de MotoGo24, statut des réservations',allowAll:'Tout autoriser et continuer →',skip:'Passer – je configurerai plus tard'},
offline:{title:'Pas de connexion Internet',sub:'MotoGo24 nécessite une connexion Internet.',hint:'Vérifiez votre Wi-Fi ou vos données mobiles.',retryBtn:'Réessayer',stillOffline:'Toujours pas de connexion…'}},
nl:{perm:{title:'Welkom bij MotoGo24',sub:'We hebben uw toestemming nodig voor volledige functionaliteit',biometric:'Biometrische verificatie',biometricDesc:'Snel inloggen met vingerafdruk',location:'Locatie',locationDesc:'Navigatie naar filiaal, locatie delen bij pech',camera:'Camera',cameraDesc:'Documenten scannen, schadedocumentatie',microphone:'Microfoon',microphoneDesc:'Spraakcommando\'s voor de AI-assistent',notifications:'Meldingen',notificationsDesc:'SOS-updates, berichten van MotoGo24, reserveringsstatus',allowAll:'Alles toestaan en doorgaan →',skip:'Overslaan – ik stel later in'},
offline:{title:'Geen internetverbinding',sub:'MotoGo24 vereist een internetverbinding.',hint:'Controleer uw Wi-Fi of mobiele data.',retryBtn:'Opnieuw proberen',stillOffline:'Nog steeds geen verbinding…'}},
pl:{perm:{title:'Witaj w MotoGo24',sub:'Potrzebujemy Twojej zgody na pełną funkcjonalność',biometric:'Weryfikacja biometryczna',biometricDesc:'Szybkie logowanie odciskiem palca',location:'Lokalizacja',locationDesc:'Nawigacja do oddziału, udostępnianie pozycji przy awarii',camera:'Aparat',cameraDesc:'Skanowanie dokumentów, dokumentacja szkód',microphone:'Mikrofon',microphoneDesc:'Zapytania głosowe do asystenta AI',notifications:'Powiadomienia',notificationsDesc:'Aktualizacje SOS, wiadomości z MotoGo24, status rezerwacji',allowAll:'Zezwól na wszystko i kontynuuj →',skip:'Pomiń – ustawię później'},
offline:{title:'Brak połączenia z Internetem',sub:'MotoGo24 wymaga połączenia z Internetem.',hint:'Sprawdź Wi-Fi lub dane komórkowe.',retryBtn:'Spróbuj ponownie',stillOffline:'Wciąż brak połączenia…'}}
});
})();
