-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — Slovinsko II (10 tras, SI)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- Pozn.: záměrně mimo oblasti existujících SI tras (Bled/Bohinj, Logarská dolina
-- a Solčavsko, Vršič/Soča, Kras s Postojnou, Škocjanem a Lipicou).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Maribor a Pohorje – štajerské serpentiny
  delete from public.routes where name = 'Maribor a Pohorje – štajerské serpentiny' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Maribor a Pohorje – štajerské serpentiny', 'Okruh kolem zeleného masivu Pohorje spojuje druhé největší slovinské město s tichými horskými silnicemi mezi smrkovými lesy a rašeliništi. Z nábřeží Lent v Mariboru se jede podél Drávy do Ruše a odtud dlouhým stoupáním plným serpentin přes Lovrenc na Pohorju až na hřebenovou Roglu v 1517 metrech. Sjezd přes Zreče a vinařské Slovenske Konjice nabídne úplně jiný svět — vinice, staré náměstí a ruiny kartuziánského kláštera v Žiče. Asfalt je většinou kvalitní, ale na hřebeni počítejte s úzkou vozovkou, lesní zvěří a o víkendech s cyklisty. Nejlepší období je květen až říjen; brzy zjara a pozdě na podzim bývá na Rogle chladno a mokro.', 'loop', 120, 240, 'medium',
     '[{"lat": 46.5576, "lng": 15.6446, "label": "Start: Maribor (Lent)"}, {"lat": 46.5389, "lng": 15.5158, "label": "Ruše"}, {"lat": 46.5406, "lng": 15.3939, "label": "Lovrenc na Pohorju"}, {"lat": 46.4531, "lng": 15.3319, "label": "Rogla"}, {"lat": 46.3369, "lng": 15.4269, "label": "Slovenske Konjice"}, {"lat": 46.3110, "lng": 15.4531, "label": "Žička kartuzija"}, {"lat": 46.5576, "lng": 15.6446, "label": "Cíl: Maribor (Lent)"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.5576,15.6446&destination=46.5576,15.6446&travelmode=driving&waypoints=46.5389,15.5158%7C46.5406,15.3939%7C46.4531,15.3319%7C46.3369,15.4269%7C46.3110,15.4531', 'https://commons.wikimedia.org/wiki/Special:FilePath/Maribor%20Lent.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Maribor%20Lent.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mariborsko%20Pohorje.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lovren%C5%A1ka%20jezera.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rogla.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Slovenske%20Konjice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C4%8Dka%20kartuzija.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Maribor.jpg"}'::text[], '{"Maribor – Lent a Stará trta","Mariborsko Pohorje","Lovrenška jezera","Rogla (1517 m)","Slovenske Konjice","Žička kartuzija","Restaurace: Gostilna Maribor (Maribor)"}'::text[], '{"SI"}'::text[], false, 5210, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Maribor – Lent a Stará trta', 'Historické nábřeží Lent na břehu Drávy je nejstarší částí Mariboru a roste tu Stará trta — přes čtyři sta let stará vinná réva, zapsaná v Guinnessově knize jako nejstarší plodící réva světa. Kolem Domu Staré trty najdete kavárny, vinotéky a příjemnou promenádu. Ideální místo na kávu před vyjížďkou a fotku motorky u řeky.', 46.5576, 15.6446, 'https://commons.wikimedia.org/wiki/Special:FilePath/Maribor%20Lent.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Maribor%20Lent.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stara%20trta.jpg"}'::text[], 0),
    (v_route, 'Mariborsko Pohorje', 'Lyžařské a turistické středisko na svazích přímo nad Mariborem, kam z městské čtvrti Radvanje vyjíždí kabinková lanovka. Od spodní stanice se silnice stáčí do prvních serpentin a nahoře se otevírají výhledy na město a údolí Drávy. V zimě se tu jezdí slalom Zlatá liška, v létě je to nástupiště do lesů Pohorje.', 46.5279, 15.6013, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mariborsko%20Pohorje.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mariborsko%20Pohorje.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pohorje.jpg"}'::text[], 1),
    (v_route, 'Lovrenška jezera', 'Největší vrchovištní rašeliniště ve Slovinsku s dvaceti temnými jezírky, schované v sedle mezi Roglou a Lovrencem. Od silnice k němu vede dřevěný chodník a vyhlídková věž, ze které přehlédnete celou náhorní plošinu. Krátká procházka je příjemným protažením nohou uprostřed horské etapy okruhu.', 46.4864, 15.4064, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lovren%C5%A1ka%20jezera.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lovren%C5%A1ka%20jezera.jpg"}'::text[], 2),
    (v_route, 'Rogla (1517 m)', 'Nejvyšší bod okruhu — horské středisko na zalesněném hřebeni Pohorje s rozhlednou, chatami a stezkou v korunách stromů. Silnice sem stoupá z obou stran dlouhými, pravidelnými serpentinami s výborným rytmem jízdy. Za jasného počasí dohlédnete až na Kamnicko-Savinjské Alpy; i v létě si sem vezměte teplejší vrstvu.', 46.4531, 15.3319, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rogla.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rogla.jpg"}'::text[], 3),
    (v_route, 'Slovenske Konjice', 'Malebné vinařské městečko pod horou Konjiška gora, jehož protáhlé staré náměstí lemují měšťanské domy s pestrými fasádami a potok tekoucí středem ulice. Okolní svahy pokrývají vinice Štajerska a v místních vinotékách ochutnáte bílá vína z okolí. Příjemná zastávka po sjezdu z hor.', 46.3369, 15.4269, 'https://commons.wikimedia.org/wiki/Special:FilePath/Slovenske%20Konjice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slovenske%20Konjice.jpg"}'::text[], 4),
    (v_route, 'Žička kartuzija', 'Působivé ruiny kartuziánského kláštera z 12. století, ukryté v tichém údolí sv. Jana Křtitele u Žiče. Byl to jeden z prvních kartuziánských klášterů mimo Francii a dnes tu vedle gotických zdí funguje i jedna z nejstarších lékáren v Evropě a bylinková zahrada. Ke klášteru vede úzká slepá silnička údolím — krátká odbočka, která stojí za to.', 46.3110, 15.4531, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C4%8Dka%20kartuzija.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C4%8Dka%20kartuzija.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Gostilna Maribor (Maribor)', 'Výborně hodnocená restaurace v historickém centru Mariboru, která moderně servíruje štajerskou klasiku — od hovězího vývaru s domácími nudlemi po pohorský hrnec a místní vína. Poctivé porce a milá obsluha z ní dělají ideální tečku za okruhem. V sezóně se hodí rezervace.', 46.5586, 15.6450, 'https://commons.wikimedia.org/wiki/Special:FilePath/Maribor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Maribor.jpg"}'::text[], 6);

  -- Goriška Brda a Vipavská dolina
  delete from public.routes where name = 'Goriška Brda a Vipavská dolina' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Goriška Brda a Vipavská dolina', 'Pohodová vyjížďka nejslunnějším koutem Slovinska, kde se na dohled od italské hranice vlní vinice, cypřiše a kamenné vesničky — Goriška Brda se ne nadarmo přezdívají slovinské Toskánsko. Z Nové Gorice se přes slavný Solkanský most vydáte úzkými silničkami po hřebenech Brd kolem Šmartna a zámku Dobrovo, poté se vrátíte do Vipavské doliny za bílými víny a středověkým Vipavským Križem. Silnice jsou klidné, zvlněné a plné krátkých zatáček mezi vinicemi; provoz je minimální, jen během vinobraní potkáte traktory. Ideální sezóna je duben až červen a září až říjen, kdy se sklízí hrozny a kraj voní moštem. Pozor na burju — prudký nárazový vítr, který ve Vipavské dolině umí zavřít i hlavní silnici; před jízdou zkontrolujte předpověď.', 'loop', 110, 210, 'easy',
     '[{"lat": 45.9558, "lng": 13.6486, "label": "Start: Nova Gorica"}, {"lat": 46.0064, "lng": 13.6417, "label": "Solkanský most"}, {"lat": 46.0072, "lng": 13.5411, "label": "Šmartno"}, {"lat": 45.9967, "lng": 13.5261, "label": "Dobrovo"}, {"lat": 45.8703, "lng": 13.8825, "label": "Vipavski Križ"}, {"lat": 45.8461, "lng": 13.9633, "label": "Vipava"}, {"lat": 45.8564, "lng": 13.9436, "label": "Dvorec Zemono"}, {"lat": 45.9558, "lng": 13.6486, "label": "Cíl: Nova Gorica"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.9558,13.6486&destination=45.9558,13.6486&travelmode=driving&waypoints=46.0064,13.6417%7C46.0072,13.5411%7C45.9967,13.5261%7C45.8703,13.8825%7C45.8461,13.9633%7C45.8564,13.9436', 'https://commons.wikimedia.org/wiki/Special:FilePath/Solkan%20Bridge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Solkan%20Bridge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0martno,%20Gori%C5%A1ka%20Brda.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Dobrovo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vipavski%20Kri%C5%BE.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vipava,%20Slovenia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dvorec%20Zemono.jpg"}'::text[], '{"Solkanský most","Šmartno (Goriška Brda)","Zámek Dobrovo","Vipavski Križ","Vipava (prameny řeky)","Restaurace: Gostilna pri Lojzetu (dvorec Zemono)"}'::text[], '{"SI"}'::text[], false, 5220, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Solkanský most', 'Železniční most přes smaragdovou Sočiu u Solkanu má hlavní oblouk o rozpětí 85 metrů — největší kamenný obloukový most na železnici na světě. Nejlepší výhled je z vyhlídky u silnice na levém břehu, kde se dá pohodlně zastavit. Kombinace tyrkysové řeky a bílého kamene je jedno z nejfotogeničtějších míst Primorska.', 46.0064, 13.6417, 'https://commons.wikimedia.org/wiki/Special:FilePath/Solkan%20Bridge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Solkan%20Bridge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Solkanski%20most.jpg"}'::text[], 0),
    (v_route, 'Šmartno (Goriška Brda)', 'Opevněná středověká vesnice na vrcholu kopce uprostřed Brd, obehnaná hradbami s věžemi a považovaná za nejkrásnější vesnici kraje. Kamenné uličky ukrývají galerie, vinotéky a výhledy na moře vinic; kousek odtud stojí rozhledna Gonjače s panoramatem od Alp po Jadran. Povinná zastávka každé vyjížďky po Brdech.', 46.0072, 13.5411, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0martno,%20Gori%C5%A1ka%20Brda.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0martno,%20Gori%C5%A1ka%20Brda.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gori%C5%A1ka%20brda.jpg"}'::text[], 1),
    (v_route, 'Zámek Dobrovo', 'Renesanční zámek ze 17. století uprostřed vinic je centrem vinařství Goriška Brda — v jeho sklepích sídlí vinotéka místního družstva Klet Brda, největšího producenta vína v zemi. Ochutnáte tu rebulu i další místní odrůdy (řidič samozřejmě jen degustačně přivoní) a prohlédnete si zámecké sály. Kolem zámku se rozprostírají nejslavnější vinohrady Slovinska.', 45.9967, 13.5261, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Dobrovo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Dobrovo.jpg"}'::text[], 2),
    (v_route, 'Vipavski Križ', 'Drobné opevněné městečko na návrší uprostřed Vipavské doliny, celé památkově chráněné — hradby, kapucínský klášter a kamenné domy se od středověku téměř nezměnily. Z hradeb je krásný výhled na dolinu rámovanou plošinou Trnovského lesa. Patří k nejmenším a nejpůvabnějším historickým sídlům v zemi.', 45.8703, 13.8825, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vipavski%20Kri%C5%BE.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vipavski%20Kri%C5%BE.jpg"}'::text[], 3),
    (v_route, 'Vipava (prameny řeky)', 'Městečko Vipava vyrostlo přímo kolem pramenů stejnojmenné řeky, která tu vyvěrá hned několika krasovými výtoky pod skalní stěnou — říká se jí proto slovinské Benátky. Přes ramena řeky se klene řada kamenných můstků a v okolí sídlí známá vinařství. Příjemné místo na procházku a zmrzlinu ve stínu platanů.', 45.8461, 13.9633, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vipava,%20Slovenia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vipava,%20Slovenia.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Gostilna pri Lojzetu (dvorec Zemono)', 'Legendární restaurace šéfkuchaře Tomaže Kavčiče v barokním letohrádku Zemono nad Vipavskou dolinou, oceněná michelinskou hvězdou. Servíruje hravou degustační kuchyni z místních surovin s výhledem na vinice; kdo chce jen lehčí oběd, najde v okolí Vipavy i neformálnější podniky. Zážitková tečka okruhu — rezervace nutná.', 45.8564, 13.9436, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dvorec%20Zemono.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dvorec%20Zemono.jpg"}'::text[], 5);

  -- Slovinská Istrie – Piran a solné pánve
  delete from public.routes where name = 'Slovinská Istrie – Piran a solné pánve' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Slovinská Istrie – Piran a solné pánve', 'Krátký, ale zážitky nabitý okruh po celém slovinském pobřeží — od přístavního Koperu přes rybářskou Izolu a útesy Strunjanu až do benátského Piranu a k solným pánvím Sečovlje. Zpáteční část vede vnitrozemím Istrie mezi olivovníky a kamennými vesnicemi ke kostelíku v Hrastovlje se slavnou freskou Tance smrti. Pobřežní silnice je malebná, ale v červenci a srpnu počítejte s hustým provozem a placeným parkováním; do Piranu je nejlepší dorazit brzy ráno. Ideální je jaro a podzim, kdy je moře fotogenické a silnice prázdné. Jízda je technicky nenáročná, jen ve vnitrozemí zpozorněte na úzkých okreskách s posypem štěrku.', 'loop', 85, 180, 'easy',
     '[{"lat": 45.5481, "lng": 13.7302, "label": "Start: Koper"}, {"lat": 45.5386, "lng": 13.6606, "label": "Izola"}, {"lat": 45.5364, "lng": 13.6069, "label": "Strunjan"}, {"lat": 45.5283, "lng": 13.5683, "label": "Piran"}, {"lat": 45.4772, "lng": 13.6083, "label": "Sečovlje"}, {"lat": 45.5069, "lng": 13.9081, "label": "Hrastovlje"}, {"lat": 45.5481, "lng": 13.7302, "label": "Cíl: Koper"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.5481,13.7302&destination=45.5481,13.7302&travelmode=driving&waypoints=45.5386,13.6606%7C45.5364,13.6069%7C45.5283,13.5683%7C45.4772,13.6083%7C45.5069,13.9081', 'https://commons.wikimedia.org/wiki/Special:FilePath/Piran.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Koper.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Izola.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Strunjan%20cliff.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Piran.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Se%C4%8Doveljske%20soline.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrastovlje.jpg"}'::text[], '{"Koper – Titov trg","Izola","Strunjanské útesy","Piran – Tartiniho náměstí","Sečoveljské solné pánve","Hrastovlje – kostel sv. Trojice"}'::text[], '{"SI"}'::text[], false, 5230, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Koper – Titov trg', 'Historické jádro největšího slovinského přístavu vyrostlo pod benátskou správou a Titovo náměstí s Pretorským palácem, loggií a katedrálou je toho nejlepší ukázkou. Ze zvonice katedrály je výhled na celý Terstský záliv. Motorku pohodlně odstavíte u nábřeží a centrum projdete pěšky za půl hodiny.', 45.5481, 13.7302, 'https://commons.wikimedia.org/wiki/Special:FilePath/Koper.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Koper.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Titov%20trg,%20Koper.jpg"}'::text[], 0),
    (v_route, 'Izola', 'Bývalý rybářský ostrov, dnes půvabné městečko s pestrobarevnými domy namačkanými kolem přístavu plného lodí. Uličky voní grilovanými sardinkami a na rozdíl od Piranu si Izola drží civilnější, místní atmosféru. Ideální zastávka na ranní kávu na molu.', 45.5386, 13.6606, 'https://commons.wikimedia.org/wiki/Special:FilePath/Izola.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Izola.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Izola,%20Slovenia.jpg"}'::text[], 1),
    (v_route, 'Strunjanské útesy', 'Nejvyšší flyšové útesy na celém Jadranu — osmdesátimetrová stěna Strunjanského poloostrova spadá kolmo do moře v chráněné přírodní rezervaci. Od silnice vede krátká stezka na vyhlídku nad zátokou Mesečev zaliv, jednou z nejzachovalejších částí slovinského pobřeží. Krásné místo na fotku, koupání je dole v zátoce.', 45.5364, 13.6069, 'https://commons.wikimedia.org/wiki/Special:FilePath/Strunjan%20cliff.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Strunjan%20cliff.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Strunjan.jpg"}'::text[], 2),
    (v_route, 'Piran – Tartiniho náměstí', 'Nejkrásnější město slovinského pobřeží: benátské paláce, oválné Tartiniho náměstí a špička poloostrova s majákem, kde se uličky sbíhají k moři. Vyplatí se vystoupat ke kostelu sv. Jiří a hradbám — výhled na červené střechy a záliv je ikonou celé země. Do centra motorky nesmí, parkuje se u vjezdu do města.', 45.5283, 13.5683, 'https://commons.wikimedia.org/wiki/Special:FilePath/Piran.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piran.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tartinijev%20trg,%20Piran.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Fritolin pri Cantini (Piran)', 'Kultovní neformální podnik na náměstíčku za piranským přístavem, kde si smažené i grilované ryby objednáte u okénka a sníte je u stolků pod slunečníky. Čerstvé kalamáry, sardinky a rybí polévka za férové ceny — přesně to, co k Jadranu patří. Ve špičce počítejte s frontou, stojí za to.', 45.5278, 13.5697, 'https://commons.wikimedia.org/wiki/Special:FilePath/Piran.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piran.jpg"}'::text[], 4),
    (v_route, 'Sečoveljské solné pánve', 'Rozlehlá krajina solných polí u ústí řeky Dragonji, kde se sůl sbírá ručně stejným způsobem už sedm set let. Krajinný park je rájem vodních ptáků a v muzeu solinářství uvidíte domky solinářů i dřevěné nástroje. Květ soli ze Sečovlje je vyhlášená pochoutka a hezký suvenýr do kufru motorky.', 45.4772, 13.6083, 'https://commons.wikimedia.org/wiki/Special:FilePath/Se%C4%8Doveljske%20soline.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Se%C4%8Doveljske%20soline.jpg"}'::text[], 5),
    (v_route, 'Hrastovlje – kostel sv. Trojice', 'Drobný románský kostelík obehnaný protitureckou zdí ukrývá nejslavnější středověkou fresku Slovinska — Tanec smrti z roku 1490, na němž kostlivci odvádějí k hrobu papeže i sedláka. Kostel stojí nad kamennou vesničkou na okraji istrijského vnitrozemí, kam vede klidná okreska mezi olivovníky. Malé, ale nezapomenutelné místo.', 45.5069, 13.9081, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrastovlje.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrastovlje.jpg"}'::text[], 6);

  -- Bela krajina – údolí řeky Kolpy
  delete from public.routes where name = 'Bela krajina – údolí řeky Kolpy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Bela krajina – údolí řeky Kolpy', 'Nejjižnější kout Slovinska je krajem březových hájů, vinic a nejteplejší slovinské řeky Kolpy, která tu tvoří hranici s Chorvatskem. Okruh z Metliky vede nejprve k poutnímu areálu Tri fare a poté podél Kolpy přes Adlešiče a Vinicu — silnice kopíruje řeku, střídá krátké zatáčky a průjezdy vesničkami s vinnými sklípky. Přes Črnomelj se vrátíte kolem smaragdového pramene Krupy zpět do Metliky. Provoz je tu minimální i v sezóně, asfalt slušný, jen na okreskách u řeky počítejte s úzkou vozovkou a v létě s koupajícími se výletníky. Nejhezčí je pozdní jaro, kdy jsou březové steljniky svěže zelené, a babí léto s vinobraním.', 'loop', 85, 180, 'easy',
     '[{"lat": 45.6478, "lng": 15.3153, "label": "Start: Metlika"}, {"lat": 45.6486, "lng": 15.3308, "label": "Tri fare (Rosalnice)"}, {"lat": 45.5250, "lng": 15.3081, "label": "Adlešiči (Kolpa)"}, {"lat": 45.4614, "lng": 15.2536, "label": "Vinica"}, {"lat": 45.5711, "lng": 15.1889, "label": "Črnomelj"}, {"lat": 45.6317, "lng": 15.1592, "label": "Pramen Krupy"}, {"lat": 45.6478, "lng": 15.3153, "label": "Cíl: Metlika"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.6478,15.3153&destination=45.6478,15.3153&travelmode=driving&waypoints=45.6486,15.3308%7C45.5250,15.3081%7C45.4614,15.2536%7C45.5711,15.1889%7C45.6317,15.1592', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kolpa%20river.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Metlika.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tri%20fare,%20Rosalnice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kolpa%20river.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Crnomelj.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Izvir%20Krupe.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Metlika.jpg"}'::text[], '{"Metlika (hrad a vinařské muzeum)","Tri fare (Rosalnice)","Řeka Kolpa u Adlešičů","Črnomelj","Pramen Krupy","Restaurace: Gostilna Müller (Metlika)"}'::text[], '{"SI"}'::text[], false, 5240, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Metlika (hrad a vinařské muzeum)', 'Pohraniční městečko s trojicí náměstí a renesančním hradem, v němž sídlí muzeum Bela krajiny a slovinské vinařské muzeum. Metlika je centrem vinorodého kraje — právě odtud pochází lehké červené víno metliška črnina. Příjemný start okruhu s kavárnami na náměstí Mestni trg.', 45.6478, 15.3153, 'https://commons.wikimedia.org/wiki/Special:FilePath/Metlika.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Metlika.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Metlika.jpg"}'::text[], 0),
    (v_route, 'Tri fare (Rosalnice)', 'Unikátní poutní areál na kraji vesnice Rosalnice — tři gotické kostely stojící těsně vedle sebe na jednom hřbitově za společnou zdí. Podobný soubor nemá ve střední Evropě obdoby a jeho původ sahá až k templářům. Klidné, téměř mystické místo pět minut od Metliky.', 45.6486, 15.3308, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tri%20fare,%20Rosalnice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tri%20fare,%20Rosalnice.jpg"}'::text[], 1),
    (v_route, 'Řeka Kolpa u Adlešičů', 'Nejteplejší slovinská řeka se u Adlešičů líně vine mezi jezy starých mlýnů a v létě se v ní dá výborně koupat. Silnice podél Kolpy patří k nejmalebnějším v kraji — z jedné strany řeka a chorvatský břeh, z druhé vinice a březové háje. U jezů je řada travnatých plácků, kde se dá zastavit a smočit nohy.', 45.5250, 15.3081, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kolpa%20river.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kolpa%20river.jpg"}'::text[], 2),
    (v_route, 'Črnomelj', 'Hlavní město Bela krajiny leží na skalním ostrohu obtékaném řekami Lahinja a Dobličica. Staré jádro s hradem a kostelem obejdete za chvíli; město je známé folklorním festivalem Jurjevanje, nejstarším ve Slovinsku, který slaví zelené jaro. Dobré místo na doplnění paliva a kávu.', 45.5711, 15.1889, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Crnomelj.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Crnomelj.jpg"}'::text[], 3),
    (v_route, 'Pramen Krupy', 'Řeka Krupa vyvěrá v plné síle přímo z třicetimetrové skalní stěny — smaragdově zelená hladina pod převisem patří k nejkrásnějším krasovým pramenům v zemi. Od parkoviště u vesnice Krupa je to k prameni pár minut pěšky. V podzemí zdejšího krasu žije vzácný jeskynní mlok macarát.', 45.6317, 15.1592, 'https://commons.wikimedia.org/wiki/Special:FilePath/Izvir%20Krupe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Izvir%20Krupe.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Gostilna Müller (Metlika)', 'Rodinná gostilna na kraji Metliky s dlouhou tradicí a výborným hodnocením, proslulá belokrajinskou kuchyní — jehněčím a prasátkem z pece, domácí poviticí a plackou belokranjska pogača. K jídlu nalévají místní vína z okolních vinic. Ideální závěr okruhu.', 45.6494, 15.3122, 'https://commons.wikimedia.org/wiki/Special:FilePath/Metlika.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Metlika.jpg"}'::text[], 5);

  -- Kočevsko – země pralesů a medvědů
  delete from public.routes where name = 'Kočevsko – země pralesů a medvědů' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kočevsko – země pralesů a medvědů', 'Vyjížďka nejzalesněnějším a nejdivočejším koutem Slovinska, kde lesy pokrývají devět desetin krajiny a žije tu nejhustší populace medvěda hnědého v Evropě. Od hradu Turjak sjedete kolem rodiště slovinského písemnictví v Rašici do Ribnice, městečka proslulého výrobou dřevěného nádobí suha roba, a přes poutní kostel Nova Štifta pokračujete lesními silnicemi do Kočevje k jezeru v bývalém dole. Silnice jsou klidné a plynulé, vedou dlouhými lesními úseky — právě tady platí dvojnásob: pozor na zvěř, zvlášť za soumraku. Trasa je nenáročná a krásná od jara do podzimu; na podzim lesy Kočevského Rogu hrají všemi barvami. Medvěda z motorky nejspíš nepotkáte, ale vědomí, že tu někde je, dodává jízdě říz.', 'loop', 110, 200, 'easy',
     '[{"lat": 45.8792, "lng": 14.6089, "label": "Start: hrad Turjak"}, {"lat": 45.8494, "lng": 14.6236, "label": "Rašica"}, {"lat": 45.7392, "lng": 14.7278, "label": "Ribnica"}, {"lat": 45.7211, "lng": 14.6392, "label": "Nova Štifta"}, {"lat": 45.6431, "lng": 14.8636, "label": "Kočevje"}, {"lat": 45.8792, "lng": 14.6089, "label": "Cíl: hrad Turjak"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.8792,14.6089&destination=45.8792,14.6089&travelmode=driving&waypoints=45.8494,14.6236%7C45.7392,14.7278%7C45.7211,14.6392%7C45.6431,14.8636', 'https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Turjak.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Turjak.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Trubarjeva%20doma%C4%8Dija.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ribnica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nova%20%C5%A0tifta.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C4%8Devje.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rajhenavski%20Rog.jpg"}'::text[], '{"Hrad Turjak","Trubarjeva domačija (Rašica)","Ribnica","Nova Štifta","Kočevje a Rudniško jezero","Prales Rajhenavski Rog"}'::text[], '{"SI"}'::text[], false, 5250, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Turjak', 'Mohutný hrad rodu Auerspergů na skále nad údolím střeží cestu na Kočevsko už od 13. století. Prohlédnete si rytířský sál, kapli a hradby s výhledem do kraje; hrad hrál důležitou roli i za druhé světové války. Prostorné parkoviště pod hradem je pohodlný start okruhu.', 45.8792, 14.6089, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Turjak.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Turjak.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Turjak%20Castle.jpg"}'::text[], 0),
    (v_route, 'Trubarjeva domačija (Rašica)', 'Rodný statek Primože Trubara, autora první slovinsky tištěné knihy, je dnes malebným skanzenem s mlýnem, pilou a expozicí o počátcích slovinského písemnictví. Areál leží u potoka pod vesnicí Rašica hned u silnice. Krátká zastávka, která dává jízdě přes tenhle tichý kraj historický kontext.', 45.8494, 14.6236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trubarjeva%20doma%C4%8Dija.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trubarjeva%20doma%C4%8Dija.jpg"}'::text[], 1),
    (v_route, 'Ribnica', 'Městečko proslulé po staletí výrobou suché roby — dřevěného nádobí, sít a košíků, které ribničtí podomní obchodníci roznášeli po celé Evropě. V hradu u řeky Bistrice sídlí muzeum řemesel a v obchůdcích koupíte originální dřevěné suvenýry. Živé náměstí s kavárnami zve na zastávku.', 45.7392, 14.7278, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ribnica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ribnica.jpg"}'::text[], 2),
    (v_route, 'Nova Štifta', 'Barokní poutní kostel Nanebevzetí Panny Marie z poloviny 17. století patří k nejkrásnějším ve Slovinsku — osmiboká stavba s arkádami stojí osaměle na svahu nad ribnickým údolím vedle mohutné staleté lípy. K poutnímu místu vede klidná silnička s pěkným výhledem zpět do kraje. Ideální krátká odbočka z Ribnice.', 45.7211, 14.6392, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nova%20%C5%A0tifta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nova%20%C5%A0tifta.jpg"}'::text[], 3),
    (v_route, 'Kočevje a Rudniško jezero', 'Centrum Kočevska leží uprostřed nekonečných lesů a jeho jezero vzniklé zatopením hnědouhelného dolu má sytě modrou barvu a promenádu s plážemi. Město bylo po staletí domovem kočevských Němců a jeho pohnutou historii přibližuje regionální muzeum. U jezera se dobře odpočívá s výhledem na hladinu a lesnaté hřebeny Rogu.', 45.6431, 14.8636, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C4%8Devje.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C4%8Devje.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rudni%C5%A1ko%20jezero.jpg"}'::text[], 4),
    (v_route, 'Prales Rajhenavski Rog', 'V hřebenech Kočevského Rogu se dochoval jeden z posledních pravých pralesů Evropy — les, do kterého člověk nikdy nezasáhl sekerou, s jedlemi a buky vysokými přes čtyřicet metrů. K okraji rezervace vede z Kočevje zpevněná lesní cesta a naučná stezka; do samotného pralesa se nevstupuje, obdivuje se z hranice. Tady pochopíte, proč se Kočevsku říká slovinská divočina.', 45.6606, 14.9761, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rajhenavski%20Rog.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rajhenavski%20Rog.jpg"}'::text[], 5);

  -- Prekmurje a Prlekija – Ptuj, Jeruzalem a Vinarium
  delete from public.routes where name = 'Prekmurje a Prlekija – Ptuj, Jeruzalem a Vinarium' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Prekmurje a Prlekija – Ptuj, Jeruzalem a Vinarium', 'Pohodový okruh nejvýchodnějším Slovinskem, krajem vinic, rovin kolem řeky Mury a čápů na komínech. Z nejstaršího slovinského města Ptuje se vydáte vinařskou cestou přes kopce Prlekije do Jeruzalemu, odkud pokračujete přes Muru k plovoucímu mlýnu v Ižakovcích a k rozhledně Vinarium nad Lendavou. Zpáteční část vede přes Plečnikův kostel v Bogojině a zámecké město Murska Sobota. Silnice jsou rovné nebo zvlněné, technicky nenáročné — tohle je trasa na vychutnávání krajiny, vína (až po jízdě) a proslulého prekmurského gibanice. Nejhezčí je od jara do vinobraní; v létě počítejte s horkem, roviny Prekmurje jsou nejteplejším koutem země.', 'loop', 175, 300, 'easy',
     '[{"lat": 46.4203, "lng": 15.8700, "label": "Start: Ptuj"}, {"lat": 46.4072, "lng": 16.1544, "label": "Ormož"}, {"lat": 46.4761, "lng": 16.1878, "label": "Jeruzalem"}, {"lat": 46.5761, "lng": 16.2314, "label": "Ižakovci (mlýn na Muře)"}, {"lat": 46.5672, "lng": 16.4661, "label": "Lendava (Vinarium)"}, {"lat": 46.6739, "lng": 16.2703, "label": "Bogojina"}, {"lat": 46.6586, "lng": 16.1614, "label": "Murska Sobota"}, {"lat": 46.4203, "lng": 15.8700, "label": "Cíl: Ptuj"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.4203,15.8700&destination=46.4203,15.8700&travelmode=driving&waypoints=46.4072,16.1544%7C46.4761,16.1878%7C46.5761,16.2314%7C46.5672,16.4661%7C46.6739,16.2703%7C46.6586,16.1614', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ptuj%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ptuj%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jeruzalem,%20Slovenia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Babi%C4%8Dev%20mlin.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vinarium%20Lendava.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bogojina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Murska%20Sobota.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Murska%20Sobota.jpg"}'::text[], '{"Ptuj – hrad nad Drávou","Jeruzalem – vinice Prlekije","Plovoucí mlýn na Muře (Ižakovci)","Rozhledna Vinarium (Lendava)","Bogojina – Plečnikův kostel","Murska Sobota","Restaurace: Gostilna Rajh (Bakovci)"}'::text[], '{"SI"}'::text[], false, 5260, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Ptuj – hrad nad Drávou', 'Nejstarší doložené město Slovinska s římskými kořeny, jehož panorama s hradem nad Drávou patří k nejfotografovanějším pohledům země. Dlážděné uličky, věž městského kostela a vinné sklepy Ptujska klet lákají k procházce; hradní muzeum vystavuje masky kurentů, tradičních masopustních postav zapsaných v UNESCO. Skvělý start i cíl okruhu.', 46.4203, 15.8700, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ptuj%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ptuj%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ptuj.jpg"}'::text[], 0),
    (v_route, 'Jeruzalem – vinice Prlekije', 'Vesnička na hřebeni vinorodých kopců, pojmenovaná podle křižáků, kterým zdejší víno připomnělo Svatou zemi. Vinařská cesta z Ormože do Jeruzalemu je jedna z nejkrásnějších v zemi — samý výhled, vinohrad a klaněnec. Nahoře čekají vinotéky, kaple a panoráma až k maďarské hranici.', 46.4761, 16.1878, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jeruzalem,%20Slovenia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jeruzalem,%20Slovenia.jpg"}'::text[], 1),
    (v_route, 'Plovoucí mlýn na Muře (Ižakovci)', 'Na Ostrově lásky u Ižakovců kotví věrná replika plovoucího mlýna, jaké kdysi po desítkách mlely obilí přímo na proudu řeky Mury. Přes řeku vás převeze lanový přívoz brod a v mlýně koupíte čerstvě semletou mouku. Idylické místo na piknik ve stínu vrb u nejvodnatější slovinské řeky.', 46.5761, 16.2314, 'https://commons.wikimedia.org/wiki/Special:FilePath/Babi%C4%8Dev%20mlin.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Babi%C4%8Dev%20mlin.jpg"}'::text[], 2),
    (v_route, 'Rozhledna Vinarium (Lendava)', 'Třiapadesát metrů vysoká vyhlídková věž mezi vinicemi Lendavských goric nabízí výhled do čtyř zemí najednou — Slovinska, Maďarska, Chorvatska a Rakouska. Nahoru vyjedete výtahem nebo po 240 schodech; dole se ochutnává místní specialita bograč, kotlíkový guláš na čtyři druhy masa. Nejnavštěvovanější atrakce Prekmurje.', 46.5672, 16.4661, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vinarium%20Lendava.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vinarium%20Lendava.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lendava.jpg"}'::text[], 3),
    (v_route, 'Bogojina – Plečnikův kostel', 'Kostel Nanebevstoupení Páně v Bogojině je venkovským mistrovským dílem architekta Jože Plečnika — bílá rotunda s válcovou věží, uvnitř strop zdobený prekmurskou keramikou. Stojí na návrší nad vesnicí a je vidět z daleka přes roviny. Krátká, ale architektonicky nejcennější zastávka okruhu.', 46.6739, 16.2703, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bogojina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bogojina.jpg"}'::text[], 4),
    (v_route, 'Murska Sobota', 'Hlavní město Prekmurje s renesančním zámkem uprostřed rozlehlého městského parku, v němž sídlí regionální muzeum s expozicí o životě na rovině kolem Mury. Město je příjemné na krátkou procházku a kávu; v okolních vesnicích hnízdí na komínech čápi, symbol celého kraje.', 46.6586, 16.1614, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Murska%20Sobota.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Murska%20Sobota.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Murska%20Sobota.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Gostilna Rajh (Bakovci)', 'Rodinná restaurace v Bakovcích u Murske Soboty patří k nejlepším ve Slovinsku a je vyhlášenou svatyní prekmurské kuchyně — bograč, dödöle (bramborové noky se škvarky) a pravá prekmurska gibanica podle receptu babičky Rajhových. Doporučená michelinským průvodcem, přesto s poctivými venkovskými porcemi. Rezervace se vyplatí.', 46.6203, 16.1339, 'https://commons.wikimedia.org/wiki/Special:FilePath/Murska%20Sobota.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Murska%20Sobota.jpg"}'::text[], 6);

  -- Škofjeloško hribovje a kostelík Jamnik
  delete from public.routes where name = 'Škofjeloško hribovje a kostelík Jamnik' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Škofjeloško hribovje a kostelík Jamnik', 'Kopcovitý okruh mezi Škofjou Lokou a Sorišskou planinou prověří chuť do zatáček — úzké silničky Škofjeloského a Selského pohoří šplhají na hřebeny, padají do údolí a servírují výhledy na Julské Alpy i Kamnicko-Savinjské štíty. Ze středověké Škofje Loky vystoupáte ke kovářské vesnici Kropa a k osamělému kostelíku na hřebeni Jamnik, jednomu z nejfotografovanějších míst Slovinska. Přes památné Dražgoše sjedete do Železniků a Selskou dolinou pokračujete do malované vesnice Sorica a na sedlo Soriška planina. Vozovka je místy úzká, s ostrými slepými zatáčkami a v zimě neudržovaná — trasa je nejlepší od května do října. Odměnou za soustředěnou jízdu jsou prázdné silnice a atmosféra starého horského Kraňska.', 'loop', 100, 220, 'medium',
     '[{"lat": 46.1656, "lng": 14.3064, "label": "Start: Škofja Loka"}, {"lat": 46.2933, "lng": 14.2069, "label": "Kropa"}, {"lat": 46.2775, "lng": 14.1836, "label": "Jamnik"}, {"lat": 46.2467, "lng": 14.1653, "label": "Dražgoše"}, {"lat": 46.2258, "lng": 14.1697, "label": "Železniki"}, {"lat": 46.2189, "lng": 14.0269, "label": "Sorica"}, {"lat": 46.2094, "lng": 14.0119, "label": "Soriška planina"}, {"lat": 46.1656, "lng": 14.3064, "label": "Cíl: Škofja Loka"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.1656,14.3064&destination=46.1656,14.3064&travelmode=driving&waypoints=46.2933,14.2069%7C46.2775,14.1836%7C46.2467,14.1653%7C46.2258,14.1697%7C46.2189,14.0269%7C46.2094,14.0119', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0kofja%20Loka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0kofja%20Loka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kropa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jamnik%20church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dra%C5%BEgo%C5%A1e.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDelezniki.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sorica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sori%C5%A1ka%20planina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0kofja%20Loka.jpg"}'::text[], '{"Škofja Loka","Kropa – kovářská vesnice","Kostelík Jamnik","Dražgoše","Železniki","Sorica","Soriška planina","Restaurace: Gostilna Kašča (Škofja Loka)"}'::text[], '{"SI"}'::text[], false, 5270, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Škofja Loka', 'Nejzachovalejší středověké město Slovinska s hradem, kamenným Kapucínským mostem a náměstím lemovaným malovanými měšťanskými domy. Tisíc let historie biskupského panství je tu vidět na každém kroku a hradní muzeum nabízí výhled na staré střechy. Ideální výchozí bod okruhu s kavárnami na Mestnem trgu.', 46.1656, 14.3064, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0kofja%20Loka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0kofja%20Loka.jpg"}'::text[], 0),
    (v_route, 'Kropa – kovářská vesnice', 'Úzké údolí potoka Kroparica po staletí žilo kovářstvím — vodní kladiva tu kula hřebíky pro půl Evropy a dnes řemeslo připomíná kovářské muzeum a zdobené kované detaily na každém domě. Vesnice sevřená mezi skalami působí, jako by se v ní zastavil čas. Odtud stoupá úzká silnička přímo na hřeben k Jamniku.', 46.2933, 14.2069, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kropa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kropa.jpg"}'::text[], 1),
    (v_route, 'Kostelík Jamnik', 'Kostelík sv. Primože a Felicijana stojí osaměle na travnatém hřebeni nad údolím a s panoramatem Julských Alp v zádech patří k nejfotografovanějším motivům Slovinska. Za úsvitu a při inverzích, kdy z moře mlhy trčí jen kostelík a hory, sem míří fotografové z celého světa. Motorku necháte u silnice a k vrcholu dojdete pár minut pěšky.', 46.2775, 14.1836, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jamnik%20church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jamnik%20church.jpg"}'::text[], 2),
    (v_route, 'Dražgoše', 'Horská vesnice proslulá bitvou z ledna 1942, kdy se tu partyzáni jako první v okupované Evropě postavili německé přesile v otevřeném boji; památník nad vesnicí připomíná její tragickou daň. Dnes je to tiché místo s dalekým výhledem do hor. Silnice od Jamniku k Dražgošam je jedna z nejhezčích hřebenovek v okolí.', 46.2467, 14.1653, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dra%C5%BEgo%C5%A1e.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dra%C5%BEgo%C5%A1e.jpg"}'::text[], 3),
    (v_route, 'Železniki', 'Podlouhlé městečko na dně Selské doliny se šest set let živilo železářstvím — dochovala se tu jediná zachovalá vysoká pec ve Slovinsku a muzeum s expozicí slavné železnikarské paličkované krajky. Domy tu stojí namačkané mezi řekou a svahy, což dává městečku nezaměnitelný ráz. Dobré místo na doplnění paliva před horskou etapou.', 46.2258, 14.1697, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDelezniki.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDelezniki.jpg"}'::text[], 4),
    (v_route, 'Sorica', 'Malovaná horská vesnice na slunečné terase nad Selskou dolinou, rodiště impresionisty Ivana Grohara, jehož ateliér si tu můžete prohlédnout. Vesnici založili ve středověku osadníci z Tyrolska a alpský ráz si drží dodnes. Ze silnice nad vesnicí je jeden z nejhezčích výhledů celé trasy.', 46.2189, 14.0269, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sorica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sorica.jpg"}'::text[], 5),
    (v_route, 'Soriška planina', 'Horské sedlo v 1300 metrech mezi Selskou dolinou a Baškou grapou, v zimě malé lyžařské středisko, v létě rozhledové pastviny s panoramatem od Triglavu po Ratitovec. Nejvyšší bod okruhu — ideální místo na fotku motorky s horami v pozadí. Sjezd zpět do doliny je dlouhá řada serpentin, tak s rozvahou.', 46.2094, 14.0119, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sori%C5%A1ka%20planina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sori%C5%A1ka%20planina.jpg"}'::text[], 6),
    (v_route, 'Restaurace: Gostilna Kašča (Škofja Loka)', 'Restaurace a vinotéka v šest set let staré kamenné sýpce na Spodním trgu ve Škofje Loce, jedna z nejlépe hodnocených v okolí. Pod gotickými klenbami servírují loške štruklje, zvěřinu i steaky a k tomu dobrý výběr slovinských vín. Stylová tečka za okruhem po starém Kraňsku.', 46.1647, 14.3078, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0kofja%20Loka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0kofja%20Loka.jpg"}'::text[], 7);

  -- Dolenjska – údolí řeky Krky
  delete from public.routes where name = 'Dolenjska – údolí řeky Krky' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Dolenjska – údolí řeky Krky', 'Putování podél nejdelší čistě slovinské řeky od cisterciáckého kláštera Stična až do Kostanjevice na Krki, městečka na říčním ostrově. Krka teče zeleným údolím přes travertinové jezy a silnice ji věrně sleduje — jízda je plynulá, s výhledy na hrady, vrbové břehy a vinice Dolenjska, kde zraje lehké růžové víno cviček. Cestou minete mohutný hrad v Žužemberku, projedete krajským Novým mestem a kolem pohádkového vodního hradu Otočec dorazíte ke kartuziánskému klášteru Pleterje. Trasa je nenáročná, vhodná i pro méně zkušené jezdce a krásná od jara do podzimu. V létě přibývá cyklistů a u jezů se koupou místní, tak u řeky zpomalte a vychutnejte si tempo Dolenjska.', 'poi', 95, 180, 'easy',
     '[{"lat": 45.9575, "lng": 14.8069, "label": "Start: klášter Stična"}, {"lat": 45.8336, "lng": 14.9292, "label": "Žužemberk"}, {"lat": 45.8036, "lng": 15.1689, "label": "Novo mesto"}, {"lat": 45.8386, "lng": 15.2247, "label": "Otočec"}, {"lat": 45.8206, "lng": 15.3372, "label": "Pleterje"}, {"lat": 45.8461, "lng": 15.4231, "label": "Cíl: Kostanjevica na Krki"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.9575,14.8069&destination=45.8461,15.4231&travelmode=driving&waypoints=45.8336,14.9292%7C45.8036,15.1689%7C45.8386,15.2247%7C45.8206,15.3372', 'https://commons.wikimedia.org/wiki/Special:FilePath/Oto%C4%8Dec%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sti%C4%8Dna%20Abbey.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDu%C5%BEemberk%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Novo%20mesto.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Oto%C4%8Dec%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzija%20Pleterje.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kostanjevica%20na%20Krki.jpg"}'::text[], '{"Klášter Stična","Hrad Žužemberk","Novo mesto – Glavni trg","Hrad Otočec","Kartuziánský klášter Pleterje","Kostanjevica na Krki"}'::text[], '{"SI"}'::text[], false, 5280, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Klášter Stična', 'Nejstarší klášter ve Slovinsku, založený cisterciáky roku 1136 a dodnes obývaný mnichy. Za mohutnými zdmi se skrývá románská bazilika, gotický ambit a muzeum křesťanství; klášterní obchůdek prodává proslulé bylinné čaje patera Ašiče. Klidné místo na start jízdy údolím Krky.', 45.9575, 14.8069, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sti%C4%8Dna%20Abbey.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sti%C4%8Dna%20Abbey.jpg"}'::text[], 0),
    (v_route, 'Hrad Žužemberk', 'Jedna z nejmalebnějších pevností v zemi — hrad s mohutnými okrouhlými baštami stojí na terase přímo nad travertinovými jezy Krky uprostřed městečka. Přes léto se na nádvoří konají trhy a koncerty, z hradeb je krásný pohled na řeku. Pod hradem se dá zastavit hned u vody.', 45.8336, 14.9292, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDu%C5%BEemberk%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDu%C5%BEemberk%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20%C5%BDu%C5%BEemberk.jpg"}'::text[], 1),
    (v_route, 'Novo mesto – Glavni trg', 'Hlavní město Dolenjska leží v dramatickém meandru Krky a jeho obloukovité Hlavní náměstí s podloubími patří k nejhezčím ve Slovinsku. Kapitulní kostel sv. Mikuláše ukrývá obraz od Tintoretta a městské muzeum světoznámé halštatské nálezy — kraj byl před třemi tisíci lety centrem doby železné. Živé kavárny zvou k pauze nad řekou.', 45.8036, 15.1689, 'https://commons.wikimedia.org/wiki/Special:FilePath/Novo%20mesto.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Novo%20mesto.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Glavni%20trg,%20Novo%20mesto.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Gostišče Loka (Novo mesto)', 'Výborně hodnocená restaurace na břehu Krky pod Hlavním náměstím, s terasou přímo u vody a výhledem na staré město. Nabízí dolenjskou kuchyni i moderní jídla, čerstvé ryby a k tomu sklenku cvičku pro spolujezdce. V létě je terasa nad řekou nejpříjemnějším místem ve městě.', 45.8022, 15.1697, 'https://commons.wikimedia.org/wiki/Special:FilePath/Novo%20mesto.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Novo%20mesto.jpg"}'::text[], 3),
    (v_route, 'Hrad Otočec', 'Jediný vodní hrad ve Slovinsku stojí na ostrůvku uprostřed Krky a s cimbuřím zrcadlícím se v hladině vypadá jako z pohádky. Dnes v něm sídlí zámecký hotel, ale přes mostky se dá projít na nádvoří a kolem ostrova vede příjemná procházka. Jedno z nejromantičtějších zastavení trasy.', 45.8386, 15.2247, 'https://commons.wikimedia.org/wiki/Special:FilePath/Oto%C4%8Dec%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oto%C4%8Dec%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Oto%C4%8Dec.jpg"}'::text[], 4),
    (v_route, 'Kartuziánský klášter Pleterje', 'Jediná dosud živá kartouza ve Slovinsku leží v tichém údolí pod Gorjanci — mniši žijí v přísném mlčení, návštěvníkům je přístupný gotický kostel a multivize o životě řádu. U kláštera koupíte proslulou hruškovici z hrušek pěstovaných přímo v lahvích a vedle stojí skanzen dolenjského statku. Místo, kde se čas zastavil.', 45.8206, 15.3372, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzija%20Pleterje.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzija%20Pleterje.jpg"}'::text[], 5),
    (v_route, 'Kostanjevica na Krki', 'Nejmenší slovinské město leží celé na říčním ostrově obtékaném Krkou — dva mostky, dvě ulice a atmosféra, které místní říkají dolenjské Benátky. V bývalém cisterciáckém klášteře sídlí galerie Božidar Jakac s největší sbírkou umění v zemi a nádherným arkádovým nádvořím. Půvabná tečka za trasou údolím Krky.', 45.8461, 15.4231, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kostanjevica%20na%20Krki.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kostanjevica%20na%20Krki.jpg"}'::text[], 6);

  -- Idrija a Cerkljansko – rtuť, čipky a nemocnice Franja
  delete from public.routes where name = 'Idrija a Cerkljansko – rtuť, čipky a nemocnice Franja' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Idrija a Cerkljansko – rtuť, čipky a nemocnice Franja', 'Technicky zábavný okruh zvrásněnou krajinou mezi Logatcem, Idrijí a Cerknem, kde se silnice bez ustání kroutí přes hřebeny a hluboká údolí říček Idrijca a Sora. Hlavním magnetem je Idrija — město rtuťového dolu zapsané v UNESCO, proslulé paličkovanou krajkou a knedlíčky žlikrofi. Za Idrijí se zastavíte u tajemného krasového Divjeho jezera, přes Cerkno dojedete k partyzánské nemocnici Franja ukryté v soutěsce a zpět se vrátíte přes krajkářské městečko Žiri. Silnice jsou úzké, samá zatáčka a místy zvlněný asfalt — přesně to, co baví; kamionů tu potkáte minimum. Nejlepší období je květen až říjen, po dešti pozor na vlhké lesní úseky a padané kamení.', 'loop', 115, 230, 'medium',
     '[{"lat": 45.9144, "lng": 14.2258, "label": "Start: Logatec"}, {"lat": 46.0022, "lng": 14.0272, "label": "Idrija"}, {"lat": 45.9906, "lng": 14.0189, "label": "Divje jezero"}, {"lat": 46.1253, "lng": 13.9814, "label": "Cerkno"}, {"lat": 46.1461, "lng": 14.0072, "label": "Nemocnice Franja"}, {"lat": 46.0442, "lng": 14.1097, "label": "Žiri"}, {"lat": 45.9144, "lng": 14.2258, "label": "Cíl: Logatec"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.9144,14.2258&destination=45.9144,14.2258&travelmode=driving&waypoints=46.0022,14.0272%7C45.9906,14.0189%7C46.1253,13.9814%7C46.1461,14.0072%7C46.0442,14.1097', 'https://commons.wikimedia.org/wiki/Special:FilePath/Idrija.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Idrija.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Gewerkenegg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Divje%20jezero.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cerkno.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Partizanska%20bolnica%20Franja.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDiri.jpg"}'::text[], '{"Idrija – rtuťový důl UNESCO","Hrad Gewerkenegg","Divje jezero","Cerkno","Partyzánská nemocnice Franja","Žiri"}'::text[], '{"SI"}'::text[], false, 5290, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Idrija – rtuťový důl UNESCO', 'Pět set let se tu těžila rtuť a idrijský důl, druhý největší na světě, je dnes součástí světového dědictví UNESCO. Štola Antonijev rov vás zavede přímo do podzemí mezi kapky ryzí rtuti ve skále. Město proslavila i paličkovaná krajka — idrijská čipka — a knedlíčky žlikrofi, první slovinské jídlo s chráněným označením.', 46.0022, 14.0272, 'https://commons.wikimedia.org/wiki/Special:FilePath/Idrija.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Idrija.jpg"}'::text[], 0),
    (v_route, 'Hrad Gewerkenegg', 'Renesanční hrad nad Idrijí nechali v 16. století postavit správci rtuťového dolu jako sídlo a sklad — dnes v něm sídlí městské muzeum s expozicemi o rtuti, krajce a dějinách hornického města. Arkádové nádvoří s freskami patří k nejhezčím ve Slovinsku. Od hradu je pěkný výhled na střechy Idrije.', 46.0031, 14.0253, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Gewerkenegg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grad%20Gewerkenegg.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Gostilna Pri Škafarju (Idrija)', 'Tradiční rodinná gostilna v centru Idrije, nejlepší adresa na ochutnání pravých idrijských žlikrofů — bramborových knedlíčků s tvarem třírohého klobouku, servírovaných se skopovou omáčkou bakalca. Poctivá domácí kuchyně a přátelské ceny z ní dělají ideální obědovou zastávku okruhu.', 46.0017, 14.0281, 'https://commons.wikimedia.org/wiki/Special:FilePath/Idrija.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Idrija.jpg"}'::text[], 2),
    (v_route, 'Divje jezero', 'Divoké jezero pod kolmou skalní stěnou je zatopená krasová jeskyně, z níž po deštích vyvěrá voda takovou silou, že hladina doslova kypí — potápěči v sifonu dosáhli hloubky přes 160 metrů a dna nedosáhli. Smaragdová hladina obklopená stěnami působí až tajemně. Od parkoviště u silnice je to k jezeru pár minut po naučné stezce.', 45.9906, 14.0189, 'https://commons.wikimedia.org/wiki/Special:FilePath/Divje%20jezero.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Divje%20jezero.jpg"}'::text[], 3),
    (v_route, 'Cerkno', 'Městečko v kotlině pod lyžařským střediskem je známé masopustními maskami laufarji s dřevěnými obličeji, které vystavuje místní muzeum. Okolí nabízí hustou síť klikatých silniček — sem se sjíždějí slovinští motorkáři trénovat zatáčky. Příjemná kávová pauza před závěrečnou etapou.', 46.1253, 13.9814, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cerkno.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cerkno.jpg"}'::text[], 4),
    (v_route, 'Partyzánská nemocnice Franja', 'V těsné soutěsce Pasice u Cerkna se za druhé světové války skrývala tajná partyzánská nemocnice — dřevěné baráky u potoka, kam raněné nosili se zavázanýma očima, ošetřily přes pět set vojáků a Němci ji nikdy neobjevili. Dnes je památkou pod ochranou UNESCO se vstupem po lávkách soutěskou. Silné místo, které bere dech i bez motorky.', 46.1461, 14.0072, 'https://commons.wikimedia.org/wiki/Special:FilePath/Partizanska%20bolnica%20Franja.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Partizanska%20bolnica%20Franja.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Franja%20Partisan%20Hospital.jpg"}'::text[], 5),
    (v_route, 'Žiri', 'Městečko na rozhraní tří slovinských regionů, proslulé výrobou obuvi a paličkované krajky — místní krajkářská škola patří k nejstarším v zemi. Okolní kopce nabízejí poslední porci zatáček před návratem do Logatce. V muzeu Žiri si prohlédnete, jak se z malé vsi stalo centrum ševcovského řemesla.', 46.0442, 14.1097, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDiri.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDiri.jpg"}'::text[], 6);

  -- Údolí Savinje – Celje, Laško a Žalec
  delete from public.routes where name = 'Údolí Savinje – Celje, Laško a Žalec' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí Savinje – Celje, Laško a Žalec', 'Nenáročný okruh dolním Posavinjem spojuje knížecí Celje s pivním Laškem a chmelařským Žalcem — krajem, kterému se říká údolí zeleného zlata. Od největšího středověkého hradu ve Slovinsku sjedete soutěskou Savinje do lázeňského Laška, kde se od roku 1825 vaří nejznámější slovinské pivo. Zpět přes Celje pokračujete do Šempeteru k římské nekropoli a do Žalce, kde z veřejné fontány teče šest druhů piva z okolního chmele. Silnice podél Savinje je svižná a malebná, mezi chmelnicemi se jede po rovinách — ideální odpolední vyjížďka bez technických nástrah. Trasa je krásná od jara do podzimu, nejzajímavější v září, kdy vrcholí sklizeň chmele; pivní ochutnávky si nechte až po odstavení motorky.', 'loop', 70, 160, 'easy',
     '[{"lat": 46.2361, "lng": 15.2675, "label": "Start: Celje"}, {"lat": 46.2197, "lng": 15.2753, "label": "Stari grad Celje"}, {"lat": 46.1544, "lng": 15.2364, "label": "Laško"}, {"lat": 46.2564, "lng": 15.1214, "label": "Šempeter"}, {"lat": 46.2514, "lng": 15.1647, "label": "Žalec"}, {"lat": 46.2708, "lng": 15.2469, "label": "Šmartinsko jezero"}, {"lat": 46.2361, "lng": 15.2675, "label": "Cíl: Celje"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.2361,15.2675&destination=46.2361,15.2675&travelmode=driving&waypoints=46.2197,15.2753%7C46.1544,15.2364%7C46.2564,15.1214%7C46.2514,15.1647%7C46.2708,15.2469', 'https://commons.wikimedia.org/wiki/Special:FilePath/Celje%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Celje%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/La%C5%A1ko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rimska%20nekropola%20%C5%A0empeter.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fontana%20piv%20Zeleno%20zlato.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0martinsko%20jezero.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Celje.jpg"}'::text[], '{"Celjský hrad (Stari grad)","Laško","Římská nekropole Šempeter","Žalec – Fontána piv","Šmartinsko jezero","Restaurace: Stari Pisker (Celje)"}'::text[], '{"SI"}'::text[], false, 5300, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Celjský hrad (Stari grad)', 'Největší středověký hrad ve Slovinsku, sídlo mocných Celjských hrabat, jejichž tři hvězdy dodnes září ve slovinském státním znaku. Z Friedrichovy věže se otevírá výhled na město, meandr Savinje a při dobré viditelnosti až ke Kamnicko-Savinjským Alpám. Na hrad vede pěkná krátká silnička — ideální rozjezd okruhu.', 46.2197, 15.2753, 'https://commons.wikimedia.org/wiki/Special:FilePath/Celje%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Celje%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stari%20grad%20Celje.jpg"}'::text[], 0),
    (v_route, 'Laško', 'Lázeňské městečko sevřené v údolí Savinje žije pivem a včelami — pivovar Laško tu vaří zlatorog od roku 1825 a ochutnávku nabízí návštěvnické centrum. Nad městečkem stojí hrad Tabor, u řeky termální lázně. Silnice z Celje do Laška soutěskou podél řeky a železnice je nejhezčí úsek okruhu.', 46.1544, 15.2364, 'https://commons.wikimedia.org/wiki/Special:FilePath/La%C5%A1ko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/La%C5%A1ko.jpg"}'::text[], 1),
    (v_route, 'Římská nekropole Šempeter', 'Nejvýznamnější římská památka ve Slovinsku — pohřebiště zámožných rodin antické Celeie s monumentálními mramorovými hrobkami zdobenými reliéfy bájí a výjevů z každodenního života. Náhrobky vysoké až osm metrů stojí v upraveném parku přímo u silnice. Krátká, ale působivá cesta o dva tisíce let zpět.', 46.2564, 15.1214, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rimska%20nekropola%20%C5%A0empeter.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rimska%20nekropola%20%C5%A0empeter.jpg"}'::text[], 2),
    (v_route, 'Žalec – Fontána piv', 'Hlavní město slovinského chmelařství postavilo světový unikát — veřejnou fontánu Zeleno zlato, z níž si do zálohované sklenice natočíte šest druhů piv z místního chmele. Kolem městečka se táhnou chmelnice, jejich příběh vypráví Ekomuzeum chmelařství. Řidič degustaci pochopitelně odloží, spolujezdec si ji užije za oba.', 46.2514, 15.1647, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fontana%20piv%20Zeleno%20zlato.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fontana%20piv%20Zeleno%20zlato.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDalec.jpg"}'::text[], 3),
    (v_route, 'Šmartinsko jezero', 'Jedno z největších umělých jezer ve Slovinsku s členitými zátokami a zalesněnými břehy leží jen pár kilometrů od centra Celje. Kolem hladiny vede okružní stezka, na břehu jsou pláže, půjčovny lodiček a příjemné kavárny s terasou nad vodou. Klidná předposlední zastávka před návratem do města.', 46.2708, 15.2469, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0martinsko%20jezero.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0martinsko%20jezero.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Stari Pisker (Celje)', 'Legendární grilovna ve starém vězení v centru Celje, dlouhodobě jedna z nejlépe hodnocených restaurací ve městě. Servírují vyzrálé steaky, žebra a burgery z lokálního masa; interiér s cihlovými klenbami má nezaměnitelnou atmosféru. Po okruhu údolím Savinje ideální místo na vydatnou večeři — v pátek a v sobotu rezervujte.', 46.2297, 15.2611, 'https://commons.wikimedia.org/wiki/Special:FilePath/Celje.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Celje.jpg"}'::text[], 5);

end $$;
