-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — SRBSKO (10 tras, červenec 2026)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Srbsko – Národní park Tara a Kućica na Drini
  delete from public.routes where name = 'Srbsko – Národní park Tara a Kućica na Drini' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Národní park Tara a Kućica na Drini', 'Okruh po náhorní plošině Tara, jednom z nejzelenějších koutů Srbska. Z Bajiny Bašty vystoupáte lesními serpentinami přes klášter Rača na hřeben, kde se z vyhlídky Banjska stena otevírá pohled na smaragdovou Drinu sto metrů pod vámi. Asfalt je v národním parku většinou slušný, ale úzký a se spadaným jehličím ve stínech — brzdit s citem. Cestou minete jezero Zaovine, horské středisko Mitrovac i slavný domeček na skále uprostřed Driny. Nejlépe od května do října; v létě počítejte s pomalejšími auty u vyhlídek a s možností odpolední bouřky.', 'loop', 115, 210, 'medium',
     '[{"lat": 43.9711, "lng": 19.5626, "label": "Start: Bajina Bašta"}, {"lat": 43.9268, "lng": 19.5836, "label": "Klášter Rača"}, {"lat": 43.9245, "lng": 19.4569, "label": "Mitrovac na Taře"}, {"lat": 43.8905, "lng": 19.4102, "label": "Jezero Zaovine"}, {"lat": 43.9394, "lng": 19.4103, "label": "Vyhlídka Banjska stena"}, {"lat": 43.9599, "lng": 19.4869, "label": "Perućac"}, {"lat": 43.9711, "lng": 19.5626, "label": "Cíl: Bajina Bašta"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.9711,19.5626&destination=43.9711,19.5626&travelmode=driving&waypoints=43.9268,19.5836%7C43.9245,19.4569%7C43.8905,19.4102%7C43.9394,19.4103%7C43.9599,19.4869', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bajina_Ba%C5%A1ta,_ku%C4%87ica_na_steni_(_Ku%C4%87ica_na_Drini_).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bajina_Ba%C5%A1ta,_ku%C4%87ica_na_steni_(_Ku%C4%87ica_na_Drini_).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Raca_Monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mitrovac_na_Tari_-_panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zaovine_Lake_(Jezero_Zaovine).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Banjska_stena_-_Tara_02.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hidroelektrana_Bajina_Ba%C5%A1ta_006.jpg"}'::text[], '{"Kućica na Drini","Klášter Rača","Mitrovac na Taře","Jezero Zaovine","Vyhlídka Banjska stena","Přehrada Perućac"}'::text[], '{"RS"}'::text[], false, 5010, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kućica na Drini', 'Ikonický dřevěný domek na skalisku uprostřed řeky Driny, jeden z nejfotografovanějších motivů Srbska. Stojí tu od roku 1968 a přežil už několik povodní. Nejlepší pohled je přímo z nábřeží u Bajiny Bašty, pár minut od startu trasy.', 43.9858, 19.5247, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bajina_Ba%C5%A1ta,_ku%C4%87ica_na_steni_(_Ku%C4%87ica_na_Drini_).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bajina_Ba%C5%A1ta,_ku%C4%87ica_na_steni_(_Ku%C4%87ica_na_Drini_).jpg"}'::text[], 0),
    (v_route, 'Klášter Rača', 'Pravoslavný klášter ze 13. století, založený králem Dragutinem, ukrytý v zalesněném údolí říčky Rači. Za druhé světové války tu mniši schovávali vzácné Miroslavovo evangelium. Klidná zastávka hned na začátku stoupání do hor.', 43.9268, 19.5836, 'https://commons.wikimedia.org/wiki/Special:FilePath/Raca_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Raca_Monastery.jpg"}'::text[], 1),
    (v_route, 'Mitrovac na Taře', 'Horská osada v srdci národního parku v nadmořské výšce kolem 1000 metrů, s návštěvnickým centrem NP Tara. Louky vonící borovicemi jsou ideální na krátkou pauzu a kávu z termosky. V okolí žije medvěd hnědý — odpadky rozhodně nenechávejte venku.', 43.9245, 19.4569, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mitrovac_na_Tari_-_panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mitrovac_na_Tari_-_panoramio.jpg"}'::text[], 2),
    (v_route, 'Jezero Zaovine', 'Rozvětvená přehradní nádrž s tyrkysovou vodou obklopená loukami a lesy, tišší sestra známějšího Perućacu. Úzká silnička kolem břehů patří k nejhezčím úsekům trasy. V zátokách se dá v létě i vykoupat.', 43.8905, 19.4102, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zaovine_Lake_(Jezero_Zaovine).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zaovine_Lake_(Jezero_Zaovine).jpg"}'::text[], 3),
    (v_route, 'Vyhlídka Banjska stena', 'Nejslavnější vyhlídka národního parku Tara — kolmý sráz vysoko nad kaňonem Driny a jezerem Perućac. Od parkoviště je to pohodlných deset minut pěšky lesem. Za jasného dne dohlédnete hluboko do Bosny na protějším břehu.', 43.9394, 19.4103, 'https://commons.wikimedia.org/wiki/Special:FilePath/Banjska_stena_-_Tara_02.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Banjska_stena_-_Tara_02.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vidikovac_Banjska_stena,_Nacionali_park_Tara.jpg"}'::text[], 4),
    (v_route, 'Přehrada Perućac', 'Mohutná hráz hydroelektrárny Bajina Bašta přehrazuje Drinu a vytváří 50 km dlouhé jezero v kaňonu. Sjezd serpentinami od Banjske steny k hladině je zábavný, ale pozor na štěrk v zatáčkách. U vody je několik plováren a bufetů na osvěžení.', 43.9635, 19.4831, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hidroelektrana_Bajina_Ba%C5%A1ta_006.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hidroelektrana_Bajina_Ba%C5%A1ta_006.jpg"}'::text[], 5);

  -- Srbsko – Zlatibor a Šarganská osmička
  delete from public.routes where name = 'Srbsko – Zlatibor a Šarganská osmička' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Zlatibor a Šarganská osmička', 'Okruh po nejoblíbenější srbské hoře spojuje pastviny Zlatiboru, krápníkovou jeskyni, vodopád i legendární úzkokolejku Šarganskou osmičku v Mokré Goře. Silnice jsou tu na srbské poměry výborné, s dlouhými přehlednými oblouky mezi pastvinami a svižnými serpentinami při sjezdu do Mokré Gory. Vrcholem dne je dřevěné městečko Drvengrad režiséra Emira Kusturici na kopci Mećavnik. Ideální od dubna do října; o víkendech počítejte kolem Zlatiboru s hustším provozem a v obcích s radary. Večer si nechte čas na skvělou místní kuchyni — pršut a kajmak jsou tu povinnost.', 'loop', 150, 250, 'medium',
     '[{"lat": 43.7286, "lng": 19.7004, "label": "Start: Zlatibor"}, {"lat": 43.7047, "lng": 19.8085, "label": "Stopića jeskyně"}, {"lat": 43.6567, "lng": 19.8425, "label": "Vodopád Gostilje"}, {"lat": 43.6939, "lng": 19.8244, "label": "Sirogojno"}, {"lat": 43.7908, "lng": 19.5033, "label": "Mokra Gora – Šarganská osmička"}, {"lat": 43.7953, "lng": 19.5124, "label": "Drvengrad"}, {"lat": 43.7286, "lng": 19.7004, "label": "Cíl: Zlatibor"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.7286,19.7004&destination=43.7286,19.7004&travelmode=driving&waypoints=43.7047,19.8085%7C43.6567,19.8425%7C43.6939,19.8244%7C43.7908,19.5033%7C43.7953,19.5124', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sargan_Eight_-_Golubici_station.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Park_jezero_zlatibor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stopi%C4%87a_Pe%C4%87ina2.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zaledjeni_vodopad_Gostilje,_Zlatibor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Staro_Selo_-_Sirogojno5.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Sargan_Eight_-_Golubici_station.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Drvengrad_-_panorama.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Zlatiborsko_jezero_-_panoramio.jpg"}'::text[], '{"Zlatibor – jezírko a centrum","Stopića jeskyně","Vodopád Gostilje","Skanzen Sirogojno","Šarganská osmička","Drvengrad","Restaurace: El Paso City (Zlatibor)"}'::text[], '{"RS"}'::text[], false, 5020, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zlatibor – jezírko a centrum', 'Živé horské letovisko s promenádou kolem jezírka Kraljeve Vode. Ráno je ideální čas na kávu a doplnění zásob, než se dav turistů probudí. Odtud se rozjíždějí silnice do všech koutů pohoří.', 43.7286, 19.7004, 'https://commons.wikimedia.org/wiki/Special:FilePath/Park_jezero_zlatibor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Park_jezero_zlatibor.jpg"}'::text[], 0),
    (v_route, 'Stopića jeskyně', 'Krápníková jeskyně s obřím vstupním portálem a proslulými travertinovými kaskádami, po kterých teče voda. Prohlídka po osvětlených lávkách zabere zhruba hodinu. Uvnitř je stabilních 8 stupňů — vezměte si vrstvu navíc.', 43.7047, 19.8085, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stopi%C4%87a_Pe%C4%87ina2.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stopi%C4%87a_Pe%C4%87ina2.jpg"}'::text[], 1),
    (v_route, 'Vodopád Gostilje', 'Dvacetimetrový vodopád na okraji stejnojmenné vesnice, k němuž vede krátká upravená stezka. Nejmohutnější je na jaře po tání; v horkých dnech osvěží vodní tříšť u tůně pod skálou. U parkoviště je stánek s domácí malinovou šťávou.', 43.6567, 19.8425, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zaledjeni_vodopad_Gostilje,_Zlatibor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zaledjeni_vodopad_Gostilje,_Zlatibor.jpg"}'::text[], 2),
    (v_route, 'Skanzen Sirogojno', 'Muzeum Staro selo pod širým nebem — kompletní zlatiborská vesnice z 19. století s roubenkami, mlýnem i hospodou. Vesnice je zároveň proslulá ručně pletenými svetry. Prohlídka příjemně protáhne nohy po hodině v sedle.', 43.6939, 19.8244, 'https://commons.wikimedia.org/wiki/Special:FilePath/Staro_Selo_-_Sirogojno5.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Staro_Selo_-_Sirogojno5.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Sirogojno.jpg"}'::text[], 3),
    (v_route, 'Šarganská osmička', 'Legendární úzkokolejka, která stoupá do kopců smyčkou ve tvaru osmičky přes 22 tunelů a 5 mostů. Nostalgický vlak Ćira jezdí několikrát denně z nádraží Mokra Gora — jízdenku kupte předem, v sezoně bývá plno. Výlet vlakem trvá zhruba dvě a půl hodiny.', 43.7908, 19.5033, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sargan_Eight_-_Golubici_station.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sargan_Eight_-_Golubici_station.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/JZ-83-173_sarganska1.jpg"}'::text[], 4),
    (v_route, 'Drvengrad', 'Dřevěné etno-městečko, které si režisér Emir Kusturica postavil na kopci Mećavnik nad Mokrou Gorou. Ulice pojmenované po filmařích, kino, galerie i vynikající restaurace. Z hradeb je krásný výhled na celé údolí a trať osmičky.', 43.7953, 19.5124, 'https://commons.wikimedia.org/wiki/Special:FilePath/Drvengrad_-_panorama.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Drvengrad_-_panorama.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Mokra_Gora,_Drvengrad.JPG"}'::text[], 5),
    (v_route, 'Restaurace: El Paso City (Zlatibor)', 'Westernové městečko s výborně hodnocenou restaurací kousek od centra Zlatiboru — grilované maso, telecí pod sačem a domácí chléb z pece. Ideální tečka za okruhem, večer tu bývá živá hudba. Velké parkoviště přímo u vjezdu.', 43.7350, 19.6990, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zlatiborsko_jezero_-_panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zlatiborsko_jezero_-_panoramio.jpg"}'::text[], 6);

  -- Srbsko – Meandry Uvce a klášter Mileševa
  delete from public.routes where name = 'Srbsko – Meandry Uvce a klášter Mileševa' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Meandry Uvce a klášter Mileševa', 'Divoký jihozápad Srbska: vyhlídka Molitva nad dokonale zakroucenými meandry řeky Uvce patří k nejsilnějším přírodním scenériím Balkánu. Nad kaňonem krouží největší evropská kolonie supů bělohlavých s rozpětím křídel přes dva metry. Trasa kombinuje kvalitní hlavní tah přes pohoří Zlatar s úzkými místními cestami k vyhlídkám — poslední kilometry k Molitvě jsou zpevněný šotolinový úsek, jeďte pomalu a po dešti zvažte pěší dojití. Cestou zpět čeká klášter Mileševa s proslulou freskou Bílého anděla a přehrada Kokin Brod. Nejlepší období je květen až září, brzy ráno bývá nad meandry mlha jako z jiného světa.', 'loop', 145, 250, 'medium',
     '[{"lat": 43.4614, "lng": 19.8228, "label": "Start: Nova Varoš"}, {"lat": 43.3178, "lng": 19.9114, "label": "Vyhlídka Molitva"}, {"lat": 43.4310, "lng": 19.7930, "label": "Zlatarské jezero"}, {"lat": 43.3866, "lng": 19.6606, "label": "Klášter Mileševa"}, {"lat": 43.3387, "lng": 19.6494, "label": "Prijepolje"}, {"lat": 43.4930, "lng": 19.7370, "label": "Kokin Brod"}, {"lat": 43.4614, "lng": 19.8228, "label": "Cíl: Nova Varoš"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.4614,19.8228&destination=43.4614,19.8228&travelmode=driving&waypoints=43.3178,19.9114%7C43.4310,19.7930%7C43.3866,19.6606%7C43.3387,19.6494%7C43.4930,19.7370', 'https://commons.wikimedia.org/wiki/Special:FilePath/Meandri_Uvca_%E2%80%93_vidikovac_Molitva.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Meandri_Uvca_%E2%80%93_vidikovac_Molitva.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rezervat_prirode_Uvac,_Beloglavi_sup_02.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zlatarsko_jezero_-_panoramio_(1).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mileseva_Monastery_2.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Prijepolje_Sahat_Kula.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Nova_Varos_Kokin_Brod_uvac_river_Radoinjsko_Lake_IMG_9943.JPG"}'::text[], '{"Vyhlídka Molitva","Rezervace Uvac – supi bělohlaví","Zlatarské jezero","Klášter Mileševa","Prijepolje – Sahat kula","Přehrada Kokin Brod"}'::text[], '{"RS"}'::text[], false, 5030, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vyhlídka Molitva', 'Nejslavnější pohled na meandry Uvce — řeka se pod vámi kroutí v dokonalých smyčkách mezi vápencovými stěnami. Z parkoviště vede k okraji srázu krátká pěšina. Držte se dál od hrany, zábradlí je jen místy.', 43.3178, 19.9114, 'https://commons.wikimedia.org/wiki/Special:FilePath/Meandri_Uvca_%E2%80%93_vidikovac_Molitva.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Meandri_Uvca_%E2%80%93_vidikovac_Molitva.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Meandri_Uvca.jpg"}'::text[], 0),
    (v_route, 'Rezervace Uvac – supi bělohlaví', 'Speciální přírodní rezervace chrání kolonii supů bělohlavých, kterých tu žije několik stovek. Nejlépe je pozorujete dopoledne, když nad kaňonem chytají termiku. Z přístaviště pod vyhlídkou vyplouvají i vyhlídkové čluny k jeskyni Ledena pećina.', 43.3300, 19.8850, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rezervat_prirode_Uvac,_Beloglavi_sup_02.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rezervat_prirode_Uvac,_Beloglavi_sup_02.jpg"}'::text[], 1),
    (v_route, 'Zlatarské jezero', 'Protáhlé přehradní jezero pod horou Zlatar, lemované chatami a plážemi. Silnice po jeho východním břehu nabízí sérii plynulých zatáček s výhledy na hladinu. Dobré místo na koupání i rychlý oběd u vody.', 43.4310, 19.7930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zlatarsko_jezero_-_panoramio_(1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zlatarsko_jezero_-_panoramio_(1).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kanjon_Uvca,_Zlatarsko_jezero,_Specijalni_rezervat_prirode_Uvac.JPG"}'::text[], 2),
    (v_route, 'Klášter Mileševa', 'Klášter z roku 1234, pohřebiště krále Vladislava a domov Bílého anděla — fresky, která je považována za jedno z vrcholných děl evropského středověku. Areál leží v tichém údolí kousek od Prijepolje. Vstup je zdarma, vhodné je zakrýt ramena a kolena.', 43.3866, 19.6606, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mileseva_Monastery_2.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mileseva_Monastery_2.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Beli_andjeo2.jpg"}'::text[], 3),
    (v_route, 'Prijepolje – Sahat kula', 'Městečko na soutoku Lima a Mileševky s orientální hodinovou věží ze 17. století. Směs pravoslavné a osmanské architektury dodává centru zvláštní atmosféru pomezí. Na korzu u řeky se dobře doplňuje kofein.', 43.3387, 19.6494, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prijepolje_Sahat_Kula.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prijepolje_Sahat_Kula.JPG"}'::text[], 4),
    (v_route, 'Přehrada Kokin Brod', 'Hráz na Uvci vzdouvá Radoinjské jezero se zelenkavou vodou obklopené borovými lesy. Silnice vede přímo po koruně hráze — kratičká, ale efektní pasáž. Poslední fotozastávka před návratem do Nove Varoše.', 43.4930, 19.7370, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nova_Varos_Kokin_Brod_uvac_river_Radoinjsko_Lake_IMG_9943.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nova_Varos_Kokin_Brod_uvac_river_Radoinjsko_Lake_IMG_9943.JPG"}'::text[], 5);

  -- Srbsko – Fruška Gora a Sremski Karlovci
  delete from public.routes where name = 'Srbsko – Fruška Gora a Sremski Karlovci' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Fruška Gora a Sremski Karlovci', 'Pohodový okruh vinařskou krajinou Vojvodiny: mohutná Petrovaradinská pevnost nad Dunajem, barokní Sremski Karlovci s vinnými sklepy a zalesněný hřeben Fruške Gory, kterému se říká srbský Athos — je tu šestnáct klášterů. Silnice přes národní park jsou stinné a klikaté, o víkendech ale počítejte s cyklisty. Trasa je nenáročná, ideální i jako první zahraniční vyjížďka nebo odpolední okruh. Nejhezčí je na jaře, kdy kvetou sady, a na podzim v době vinobraní. Ochutnávku bermetu — místního kořeněného vína — si nechte až na večer po odstavení motorky.', 'loop', 95, 150, 'easy',
     '[{"lat": 45.2551, "lng": 19.8452, "label": "Start: Novi Sad"}, {"lat": 45.2526, "lng": 19.8620, "label": "Petrovaradinská pevnost"}, {"lat": 45.2029, "lng": 19.9335, "label": "Sremski Karlovci"}, {"lat": 45.1198, "lng": 19.9384, "label": "Klášter Krušedol"}, {"lat": 45.1178, "lng": 19.8547, "label": "Klášter Novo Hopovo"}, {"lat": 45.1554, "lng": 19.8492, "label": "Iriški venac"}, {"lat": 45.2018, "lng": 19.7684, "label": "Ledinské jezero"}, {"lat": 45.2551, "lng": 19.8452, "label": "Cíl: Novi Sad"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.2551,19.8452&destination=45.2551,19.8452&travelmode=driving&waypoints=45.2526,19.8620%7C45.2029,19.9335%7C45.1198,19.9384%7C45.1178,19.8547%7C45.1554,19.8492%7C45.2018,19.7684', 'https://commons.wikimedia.org/wiki/Special:FilePath/Petrovaradin_Fortress,_Novi_Sad,_Serbia_14.09.2016.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Petrovaradin_Fortress,_Novi_Sad,_Serbia_14.09.2016.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/SREMSKI_KARLOVCI_Sveti_Nikola.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Sremski_Karlovci,_Kapela_Mira.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Krusedol_Monastery,_Fruska_Gora,_Serbia.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Novo_Hopovo_monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Iri%C5%A1ki_venac,_spomenik_Sloboda_001.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ledinacko_jezero,_Fruska_Gora.jpg"}'::text[], '{"Petrovaradinská pevnost","Sremski Karlovci","Restaurace: Dunav (Sremski Karlovci)","Klášter Krušedol","Klášter Novo Hopovo","Iriški venac – památník Sloboda","Ledinské jezero"}'::text[], '{"RS"}'::text[], false, 5040, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Petrovaradinská pevnost', 'Gibraltar na Dunaji — jedna z největších barokních pevností Evropy s proslulou hodinovou věží, jejíž velká ručička ukazuje hodiny, aby ji viděli lodníci z řeky. Z hradeb je nejlepší panorama Nového Sadu. Každý červenec pevnost hostí festival EXIT.', 45.2526, 19.8620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Petrovaradin_Fortress,_Novi_Sad,_Serbia_14.09.2016.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Petrovaradin_Fortress,_Novi_Sad,_Serbia_14.09.2016.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Varadin_bridge_and_Novi_Sad_from_Petrovaradin_Fortress_4.jpg"}'::text[], 0),
    (v_route, 'Sremski Karlovci', 'Barokní městečko, které bývalo duchovním centrem srbského národa — katedrála, patriarchát, nejstarší srbské gymnázium a všude kolem vinné sklepy. Náměstí s kašnou Čtyři lvi je jako kulisa z filmu. Ochutnejte místní kuglof a nakupte bermet na doma.', 45.2029, 19.9335, 'https://commons.wikimedia.org/wiki/Special:FilePath/SREMSKI_KARLOVCI_Sveti_Nikola.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/SREMSKI_KARLOVCI_Sveti_Nikola.JPG"}'::text[], 1),
    (v_route, 'Restaurace: Dunav (Sremski Karlovci)', 'Tradiční, výborně hodnocená restaurace přímo na hlavním náměstí — sremské speciality, říční ryby a domácí štrúdl. V létě se sedí na zahrádce pod platany. Ideální oběd v půlce okruhu.', 45.2036, 19.9331, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sremski_Karlovci,_Kapela_Mira.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sremski_Karlovci,_Kapela_Mira.jpg"}'::text[], 2),
    (v_route, 'Klášter Krušedol', 'Nejvýznamnější z fruškogorských klášterů, založený počátkem 16. století, pohřebiště srbských despotů i krále Milana Obrenoviće. Červenobílý kostel obklopuje udržovaná zahrada. Klidné místo, kde provoz utichne na dohled od brány.', 45.1198, 19.9384, 'https://commons.wikimedia.org/wiki/Special:FilePath/Krusedol_Monastery,_Fruska_Gora,_Serbia.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Krusedol_Monastery,_Fruska_Gora,_Serbia.JPG"}'::text[], 3),
    (v_route, 'Klášter Novo Hopovo', 'Klášter s elegantním kostelem podle vzoru athoských staveb, ukrytý pod jižními svahy Fruške Gory u Irigu. Působil zde i osvícenec Dositej Obradović. Zastávka na pár minut ticha před stoupáním na hřeben.', 45.1178, 19.8547, 'https://commons.wikimedia.org/wiki/Special:FilePath/Novo_Hopovo_monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Novo_Hopovo_monastery.jpg"}'::text[], 4),
    (v_route, 'Iriški venac – památník Sloboda', 'Sedlo na hřebeni Fruške Gory s monumentálním partyzánským památníkem Sloboda a televizní věží. Kříží se tu všechny cesty přes národní park, v lese jsou stánky s medem a klobásami. Odtud už se jen klesá zpátky k Dunaji.', 45.1554, 19.8492, 'https://commons.wikimedia.org/wiki/Special:FilePath/Iri%C5%A1ki_venac,_spomenik_Sloboda_001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Iri%C5%A1ki_venac,_spomenik_Sloboda_001.jpg"}'::text[], 5),
    (v_route, 'Ledinské jezero', 'Zatopený lom nad vesnicí Ledinci s průzračnou zelenou vodou pod bílými stěnami. V létě oblíbené koupaliště místních, mimo sezonu úplně prázdné. Krátká odbočka z hlavní silnice po zpevněné cestě.', 45.2018, 19.7684, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ledinacko_jezero,_Fruska_Gora.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ledinacko_jezero,_Fruska_Gora.jpg"}'::text[], 6);

  -- Srbsko – Kopaonik a Pančićův vrch
  delete from public.routes where name = 'Srbsko – Kopaonik a Pančićův vrch' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Kopaonik a Pančićův vrch', 'Přejezd nejvyššího srbského pohoří z údolí Ibaru do údolí Rasiny. Z Rašky se serpentinami vystoupá přes lázničky Jošanička Banja až do dvou tisíc metrů k Pančićovu vrchu — výškový rozdíl přes 1400 metrů znamená dlouhé stoupání plné vracečů a znatelně chladnější vzduch nahoře. Asfalt je díky lyžařskému středisku kvalitní, jen v pozdním létě pozor na štěrk po opravách a na volně se pasoucí krávy nad hranicí lesa. Sjezd na východ přes Brzeće do Brusu je rychlý a plynulý. Jezdit se dá bezpečně od června do konce září, mimo tuto dobu hrozí i sníh.', 'poi', 95, 180, 'medium',
     '[{"lat": 43.2861, "lng": 20.6091, "label": "Start: Raška"}, {"lat": 43.3894, "lng": 20.7561, "label": "Jošanička Banja"}, {"lat": 43.2856, "lng": 20.8122, "label": "Kopaonik – středisko"}, {"lat": 43.2692, "lng": 20.8256, "label": "Pančićův vrch"}, {"lat": 43.2926, "lng": 20.8460, "label": "Brzeće"}, {"lat": 43.3846, "lng": 21.0330, "label": "Cíl: Brus"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.2861,20.6091&destination=43.3846,21.0330&travelmode=driving&waypoints=43.3894,20.7561%7C43.2856,20.8122%7C43.2692,20.8256%7C43.2926,20.8460', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_Pancicev-vrh.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Banja_jo%C5%A1anica_-_panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_jankove_bare.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C4%8Dara_Kopaonik.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_Pancicev-vrh.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/NP_Kopaonik_(NP02)_-_Bele_Stene_01.jpg"}'::text[], '{"Jošanička Banja","Jankove bare","Kopaonik – středisko","Pančićův vrch","Bele stene"}'::text[], '{"RS"}'::text[], false, 5050, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Jošanička Banja', 'Malé lázně s jedněmi z nejteplejších pramenů v Srbsku — voda tu vyvěrá s teplotou kolem 78 stupňů. Rodiště legendární hrdinky první světové války Milunky Savić, která tu má památník. Poslední civilizace před dlouhým stoupáním na hřeben.', 43.3894, 20.7561, 'https://commons.wikimedia.org/wiki/Special:FilePath/Banja_jo%C5%A1anica_-_panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Banja_jo%C5%A1anica_-_panoramio.jpg"}'::text[], 0),
    (v_route, 'Jankove bare', 'Rozlehlé horské rašeliniště a louky v národním parku, chráněná rezervace s dřevěnou vyhlídkou. Kontrast tichých mokřadů a smrkových lesů pár kilometrů od rušného střediska. Krátká odbočka ze silnice, ideální na protažení nohou.', 43.2547, 20.7690, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_jankove_bare.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_jankove_bare.jpg"}'::text[], 1),
    (v_route, 'Kopaonik – středisko', 'Největší horské středisko Srbska v 1770 metrech. V létě jezdí kabinová lanovka, funguje tu spousta restaurací a stánků — dobré místo na oběd s výhledem na sjezdovky zarostlé borůvčím. Benzinka je až dole v údolí, nahoře nedotankujete.', 43.2856, 20.8122, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C4%8Dara_Kopaonik.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C4%8Dara_Kopaonik.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_zima.jpg"}'::text[], 2),
    (v_route, 'Pančićův vrch', 'Nejvyšší bod Kopaoniku (2017 m) s mauzoleem botanika Josifa Pančiće a radarovou kopulí. Za jasného počasí dohlédnete až na Prokletije. K vrcholu se dá vyjet lanovkou nebo dojít po hřebenové stezce; nahoře fouká vždy, vezměte si nákrčník.', 43.2692, 20.8256, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_Pancicev-vrh.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kopaonik_Pancicev-vrh.JPG"}'::text[], 3),
    (v_route, 'Bele stene', 'Bílé vápencové skalní věže vystupující z lesů na východním okraji národního parku. Vyhlídka na údolí Rasiny a začátek dlouhého sjezdu do Brzeće. Fotogenické hlavně v nízkém večerním slunci.', 43.2790, 20.7930, 'https://commons.wikimedia.org/wiki/Special:FilePath/NP_Kopaonik_(NP02)_-_Bele_Stene_01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/NP_Kopaonik_(NP02)_-_Bele_Stene_01.jpg"}'::text[], 4);

  -- Srbsko – Údolí Driny a Tršić
  delete from public.routes where name = 'Srbsko – Údolí Driny a Tršić' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Údolí Driny a Tršić', 'Cesta podél hraniční řeky Driny z Loznice na jih do Ljubovije. Začíná se v elegantních lázních Banja Koviljača, pokračuje do Tršiće, rodné vesnice jazykovědce Vuka Karadžiće, a k tichému klášteru Tronoša. Hlavní silnice podél Zvornického jezera se vine mezi skálou a vodou — krásná, ale frekventovaná, držte odstupy od kamionů. Odbočka přes hory kolem památníku Mačkov kamen nabídne prázdné serpentiny s výhledy na celé Podriní. Sjízdné od jara do podzimu; v létě je údolí horké, hory nahoře příjemně chladné.', 'poi', 135, 210, 'medium',
     '[{"lat": 44.5333, "lng": 19.2258, "label": "Start: Loznica"}, {"lat": 44.5171, "lng": 19.1571, "label": "Banja Koviljača"}, {"lat": 44.4749, "lng": 19.2438, "label": "Tršić"}, {"lat": 44.4479, "lng": 19.2793, "label": "Klášter Tronoša"}, {"lat": 44.3966, "lng": 19.1121, "label": "Mali Zvornik"}, {"lat": 44.3333, "lng": 19.4000, "label": "Mačkov kamen"}, {"lat": 44.1886, "lng": 19.3752, "label": "Cíl: Ljubovija"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=44.5333,19.2258&destination=44.1886,19.3752&travelmode=driving&waypoints=44.5171,19.1571%7C44.4749,19.2438%7C44.4479,19.2793%7C44.3966,19.1121%7C44.3333,19.4000', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rodna_ku%C4%87a_Vuka_Stefanovi%C4%87a_Karad%C5%BEi%C4%87a,_Tr%C5%A1i%C4%87,_Srbija.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Park_Banja_Koviljaca.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Rodna_ku%C4%87a_Vuka_Stefanovi%C4%87a_Karad%C5%BEi%C4%87a,_Tr%C5%A1i%C4%87,_Srbija.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Trono%C5%A1a_monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zvorni%C4%8Dko_jezero,_Zvornik.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ma%C4%8Dkov_kamen,_kosturnica,_Ljubovija_03.JPG"}'::text[], '{"Banja Koviljača","Tršić – rodiště Vuka Karadžiće","Klášter Tronoša","Zvornické jezero","Mačkov kamen"}'::text[], '{"RS"}'::text[], false, 5060, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Banja Koviljača', 'Nejstarší srbské lázně s nádherným parkem, secesními vilami a honosným Kur-salonem z dob království. Sirné a železité prameny tu léčí už dvě století. Příjemné místo na ranní kávu před vyjetím podél Driny.', 44.5171, 19.1571, 'https://commons.wikimedia.org/wiki/Special:FilePath/Park_Banja_Koviljaca.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Park_Banja_Koviljaca.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Fountain_in_Banja_Koviljaca.JPG"}'::text[], 0),
    (v_route, 'Tršić – rodiště Vuka Karadžiće', 'Upravená etno-vesnice s roubenkou, v níž se roku 1787 narodil reformátor srbského jazyka Vuk Stefanović Karadžić. Kolem památníku voní lipová alej, fungují tu dílny starých řemesel a stánky s domácími produkty. Prohlídka zabere půl hodinky.', 44.4749, 19.2438, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rodna_ku%C4%87a_Vuka_Stefanovi%C4%87a_Karad%C5%BEi%C4%87a,_Tr%C5%A1i%C4%87,_Srbija.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rodna_ku%C4%87a_Vuka_Stefanovi%C4%87a_Karad%C5%BEi%C4%87a,_Tr%C5%A1i%C4%87,_Srbija.jpg"}'::text[], 1),
    (v_route, 'Klášter Tronoša', 'Klášter ze 14. století schovaný v lesích nad Tršićem, kde se malý Vuk Karadžić učil číst a psát. Známý je obřími vyřezávanými svícemi, které se zapalují o Velikonocích. Přístup po úzké, ale asfaltované cestě údolím.', 44.4479, 19.2793, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trono%C5%A1a_monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trono%C5%A1a_monastery.jpg"}'::text[], 2),
    (v_route, 'Zvornické jezero', 'Přehradní jezero na Drině mezi Malým Zvornikem a Zvornikem, sevřené strmými svahy. Silnice kopíruje břeh a nabízí dlouhé plynulé oblouky nad vodou. Na srbské straně je několik vyhlídkových odpočívadel s grilem.', 44.3735, 19.1198, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zvorni%C4%8Dko_jezero,_Zvornik.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zvorni%C4%8Dko_jezero,_Zvornik.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zvornik_Drina_Dam.JPG"}'::text[], 3),
    (v_route, 'Mačkov kamen', 'Památník a kostnice na hoře Jagodnja připomínající jednu z nejkrvavějších bitev srbské armády v roce 1914. Vede sem prázdná horská silnice s výhledy přes celé údolí Driny do Bosny. Pieta i panorama v jednom — vrchol této trasy.', 44.3333, 19.4000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ma%C4%8Dkov_kamen,_kosturnica,_Ljubovija_03.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ma%C4%8Dkov_kamen,_kosturnica,_Ljubovija_03.JPG"}'::text[], 4);

  -- Srbsko – Kláštery Studenica a Žiča
  delete from public.routes where name = 'Srbsko – Kláštery Studenica a Žiča' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Kláštery Studenica a Žiča', 'Okruh z Kraljeva takzvaným Údolím králů: rudá Žiča, kde se korunovali srbští panovníci, soutěska Ibaru přezdívaná údolí šeříků a na skále nad ní přízračná zřícenina Magliče. Vrcholem je klášter Studenica na seznamu UNESCO s mramorovým kostelem z 12. století. Hlavní tah soutěskou je svižný, ale frekventovaný — kamiony předjíždějte s rozmyslem; závěrečná dvanáctikilometrová odbočka ke Studenici je úzká horská silnička plná zatáček. Nejkrásněji je tu v květnu, kdy podél Ibaru kvetou šeříky, jež podle legendy nechal vysázet král Uroš pro svou francouzskou nevěstu Helenu z Anjou.', 'loop', 135, 210, 'medium',
     '[{"lat": 43.7258, "lng": 20.6893, "label": "Start: Kraljevo"}, {"lat": 43.6959, "lng": 20.6459, "label": "Klášter Žiča"}, {"lat": 43.6500, "lng": 20.6250, "label": "Soutěska Ibaru"}, {"lat": 43.6011, "lng": 20.5911, "label": "Pevnost Maglič"}, {"lat": 43.4863, "lng": 20.5316, "label": "Klášter Studenica"}, {"lat": 43.7258, "lng": 20.6893, "label": "Cíl: Kraljevo"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.7258,20.6893&destination=43.7258,20.6893&travelmode=driving&waypoints=43.6959,20.6459%7C43.6500,20.6250%7C43.6011,20.5911%7C43.4863,20.5316', 'https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_Studenica_-_The_Studenica_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_%C5%BDi%C4%8Da,_Kraljevo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Reka_Ibar_02.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Maglic-7k.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_Studenica_-_The_Studenica_Monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Milutin,_Kraljevo_01.jpg"}'::text[], '{"Klášter Žiča","Soutěska Ibaru","Pevnost Maglič","Klášter Studenica","Kraljevo – pomník krále Milutina"}'::text[], '{"RS"}'::text[], false, 5070, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Klášter Žiča', 'Sytě červený klášter založený svatým Sávou roku 1208, korunovační chrám sedmi srbských králů — pro každého prý byla proražena nová brána. Leží jen pár kilometrů za Kraljevem v zeleni sadů. Otevřeno denně, vstup volný.', 43.6959, 20.6459, 'https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_%C5%BDi%C4%8Da,_Kraljevo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_%C5%BDi%C4%8Da,_Kraljevo.jpg"}'::text[], 0),
    (v_route, 'Soutěska Ibaru', 'Sevřené údolí, kterým se řeka Ibar prodírá mezi Kraljevem a Raškou. Silnice kopíruje každý záhyb zelené řeky — jedna zatáčka střídá druhou. V květnu svahy rozkvétají šeříky, odtud přezdívka údolí jorgovanů.', 43.6500, 20.6250, 'https://commons.wikimedia.org/wiki/Special:FilePath/Reka_Ibar_02.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Reka_Ibar_02.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Reka_Ibar_Kraljevo_01.jpg"}'::text[], 1),
    (v_route, 'Pevnost Maglič', 'Středověký hrad na skalním ostrohu, který řeka Ibar obtéká ze tří stran — jedna z nejfotogeničtějších zřícenin Srbska. Nahoru vede strmá pěší stezka s visutou lávkou přes řeku, výstup zabere asi 25 minut. Motorku nechte na odpočívadle u silnice.', 43.6011, 20.5911, 'https://commons.wikimedia.org/wiki/Special:FilePath/Maglic-7k.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Maglic-7k.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/MAGLIC_-_main_tower.JPG"}'::text[], 2),
    (v_route, 'Klášter Studenica', 'Nejvýznamnější srbský klášter, zapsaný na seznamu UNESCO — kostel z bílého mramoru ukrývá fresky, které ovlivnily celé byzantské umění. Založil jej roku 1190 Stefan Nemanja, zakladatel srbského státu. Ticho za hradbami stojí za celou cestu.', 43.4863, 20.5316, 'https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_Studenica_-_The_Studenica_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_Studenica_-_The_Studenica_Monastery.jpg"}'::text[], 3),
    (v_route, 'Kraljevo – pomník krále Milutina', 'Královské město, jehož znak nese sedm korun podle sedmi panovníků korunovaných v Žiče. Na okružním náměstí stojí pomník krále Milutina a kolem něj kavárny na závěrečné posezení. Dobré místo na večeři po dni v sedle.', 43.7239, 20.6875, 'https://commons.wikimedia.org/wiki/Special:FilePath/Milutin,_Kraljevo_01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Milutin,_Kraljevo_01.jpg"}'::text[], 4);

  -- Srbsko – Đavolja varoš a Niš
  delete from public.routes where name = 'Srbsko – Đavolja varoš a Niš' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Đavolja varoš a Niš', 'Výprava z Niše, města Konstantina Velikého, údolím Toplice k jednomu z nejpodivnějších přírodních útvarů Evropy — Ďáblovu městu s dvěma stovkami hliněných věží s kamennými čepicemi. Ráno si projděte nišskou pevnost a mrazivou Ćele kulu, věž z lebek. Silnice údolím Toplice je rychlá a přehledná, posledních třicet kilometrů od Kuršumlije se mění v úzkou zvlněnou cestu mezi kopci — právě ta je jízdně nejzábavnější. Na jihu je sezona dlouhá, od dubna do listopadu; v létě vyjeďte brzy, odpoledne bývá přes třicet stupňů.', 'loop', 190, 280, 'medium',
     '[{"lat": 43.3209, "lng": 21.8958, "label": "Start: Niš"}, {"lat": 43.3269, "lng": 21.8934, "label": "Nišská pevnost"}, {"lat": 43.2331, "lng": 21.5872, "label": "Prokuplje"}, {"lat": 43.1406, "lng": 21.2722, "label": "Kuršumlija"}, {"lat": 42.9940, "lng": 21.4070, "label": "Đavolja varoš"}, {"lat": 43.3122, "lng": 21.9235, "label": "Ćele kula"}, {"lat": 43.3209, "lng": 21.8958, "label": "Cíl: Niš"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.3209,21.8958&destination=43.3209,21.8958&travelmode=driving&waypoints=43.3269,21.8934%7C43.2331,21.5872%7C43.1406,21.2722%7C42.9940,21.4070%7C43.3122,21.9235', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%90avolja_Varo%C5%A1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%A1_Fortress,_Ni%C5%A1,_Serbia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kazandzijsko_Nis.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Hisar_Fortress_in_Prokuplje_02.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%90avolja_Varo%C5%A1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nis_Cele_Kula.JPG"}'::text[], '{"Nišská pevnost","Restaurace: Stara Srbija (Niš)","Prokuplje – Hisar","Đavolja varoš","Ćele kula"}'::text[], '{"RS"}'::text[], false, 5080, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Nišská pevnost', 'Rozlehlá osmanská pevnost z 18. století na břehu Nišavy, postavená na základech římského Naissu — rodiště císaře Konstantina. Uvnitř hradeb jsou kavárny, letní scéna a stín pod stoletými stromy. Motorku zaparkujete přímo u Istanbulské brány.', 43.3269, 21.8934, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%A1_Fortress,_Ni%C5%A1,_Serbia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%A1_Fortress,_Ni%C5%A1,_Serbia.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Stara Srbija (Niš)', 'Proslulá kafana v uličce Kazandžijsko sokače, poslední dochované řemeslnické čtvrti Niše. Jižanská kuchyně v nejlepší formě — pljeskavice, punjene paprike a domácí rakije. Zajděte sem na vydatnou snídani nebo na večeři po návratu.', 43.3187, 21.8946, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kazandzijsko_Nis.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kazandzijsko_Nis.JPG"}'::text[], 1),
    (v_route, 'Prokuplje – Hisar', 'Návrší Hisar nad městem Prokuplje se zbytky středověké pevnosti a byzantské baziliky. Krátká odbočka s pěkným rozhledem na údolí Toplice, kterým pojedete dál na západ. Dole ve městě je poslední větší benzinka před horami.', 43.2306, 21.5861, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hisar_Fortress_in_Prokuplje_02.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hisar_Fortress_in_Prokuplje_02.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prokuplje,_panorama_02.jpg"}'::text[], 2),
    (v_route, 'Đavolja varoš', 'Ďáblovo město — 202 hliněných věží až 15 metrů vysokých, každá s kamennou čepicí, vzniklých erozí sopečných hornin. Okolní prameny mají extrémně kyselou, rudě zbarvenou vodu. Od parkoviště vede k útvarům okruh po dřevěných lávkách, počítejte s hodinou chůze.', 42.9940, 21.4070, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%90avolja_Varo%C5%A1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%90avolja_Varo%C5%A1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Djavolja_varos_3.jpg"}'::text[], 3),
    (v_route, 'Ćele kula', 'Věž z lebek — memento z roku 1809, kdy osmanský paša nechal do věže zazdít lebky padlých srbských povstalců od Čegru. Z původních 952 lebek jich zbývá 58, dnes chráněných kaplí. Jedno z nejsilnějších míst Srbska, zastavte se tu na zpáteční cestě.', 43.3122, 21.9235, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nis_Cele_Kula.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nis_Cele_Kula.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Cele_kula_spolja.jpg"}'::text[], 4);

  -- Srbsko – Vršac a Deliblatská peščara
  delete from public.routes where name = 'Srbsko – Vršac a Deliblatská peščara' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Vršac a Deliblatská peščara', 'Nečekaná tvář Vojvodiny: vinařské město Vršac pod jedinými skutečnými kopci Banátu, středověká strážní věž na vrcholu a pak rovinatý přesun k jezerům u Bele Crkvy a do Deliblatské peščary — největší evropské písečné pouště, dnes zarostlé akáty a stepní trávou. Silnice jsou rovné a rychlé, o zábavu se postarají krátké serpentiny na Vršacký breg a zvlněné úseky mezi dunami. Pozor na boční vítr košava, který umí na rovinách pořádně zatlačit, a na zemědělskou techniku v sezoně. Ideální jarní nebo podzimní celodenní výlet, v létě se u jezer skvěle zchladíte.', 'loop', 150, 210, 'easy',
     '[{"lat": 45.1180, "lng": 21.2990, "label": "Start: Vršac"}, {"lat": 45.1281, "lng": 21.3223, "label": "Vršacká věž"}, {"lat": 45.0819, "lng": 21.3897, "label": "Klášter Mesić"}, {"lat": 44.8975, "lng": 21.4169, "label": "Bela Crkva"}, {"lat": 44.9210, "lng": 21.0930, "label": "Deliblatská peščara – Čardak"}, {"lat": 45.1180, "lng": 21.2990, "label": "Cíl: Vršac"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.1180,21.2990&destination=45.1180,21.2990&travelmode=driving&waypoints=45.1281,21.3223%7C45.0819,21.3897%7C44.8975,21.4169%7C44.9210,21.0930', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1a%C4%8Dka_kula_posle_obnove1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1ac-_gradska_ku%C4%87a.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1a%C4%8Dka_kula_posle_obnove1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_Mesic.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Bela_Crkva_lakes_-_morning.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hills_of_Deliblatska_pescara,_Serbia.JPG"}'::text[], '{"Vršac – centrum","Vršacká věž","Klášter Mesić","Jezera u Bele Crkvy","Deliblatská peščara"}'::text[], '{"RS"}'::text[], false, 5090, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vršac – centrum', 'Vinařská metropole Banátu s barokní radnicí, farmaceutickým muzeem v nejstarší lékárně a katedrálou svatého Gerharda. Kolem města se rozkládají vinice už od římských dob. Kavárny na pěší zóně jsou ideální na start dne.', 45.1180, 21.2990, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1ac-_gradska_ku%C4%87a.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1ac-_gradska_ku%C4%87a.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1ac_sa_Brega,_no%C4%87u.jpg"}'::text[], 0),
    (v_route, 'Vršacká věž', 'Středověká strážní věž z 15. století na vrcholu Vršackého bregu, přístupná krátkými serpentinami nad městem. Z ochozu přehlédnete vinice, celý Banát a za dobré viditelnosti i rumunské Karpaty. Nahoře skoro vždy fouká — ideální osvěžení v letním dni.', 45.1281, 21.3223, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1a%C4%8Dka_kula_posle_obnove1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1a%C4%8Dka_kula_posle_obnove1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vr%C5%A1a%C4%8Dka_kula_posle_obnove2.jpg"}'::text[], 1),
    (v_route, 'Klášter Mesić', 'Pravoslavný klášter ze 15. století schovaný v tichém údolí Vršackých hor u rumunské hranice. Kolem vede klidná silnička vinicemi a sady. Pěkná krátká zastávka mimo hlavní tahy.', 45.0819, 21.3897, 'https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_Mesic.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Manastir_Mesic.JPG"}'::text[], 2),
    (v_route, 'Jezera u Bele Crkvy', 'Soustava sedmi jezer v bývalých štěrkovnách s nejčistší vodou pro koupání v Srbsku. Písčité pláže, kempy a bufety podél břehů — v létě živo, mimo sezonu klid. Hlavní jezero je hned u silnice, zastávka na vykoupání se přímo nabízí.', 44.8975, 21.4169, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bela_Crkva_lakes_-_morning.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bela_Crkva_lakes_-_morning.jpg"}'::text[], 3),
    (v_route, 'Deliblatská peščara', 'Evropská Sahara — 300 km² zvlněných písečných dun navátých v době ledové, dnes chráněná rezervace se stepní flórou, vlky a orly královskými. Silnice přes peščaru u výletiště Čardak se vlní mezi borovicemi jako horská cesta v rovině. Písek umí navát i na asfalt, v zatáčkách zpomalte.', 44.9210, 21.0930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hills_of_Deliblatska_pescara,_Serbia.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hills_of_Deliblatska_pescara,_Serbia.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Deliblatska_pe%C5%A1%C4%8Dara_i_drvo.jpg"}'::text[], 4);

  -- Srbsko – Rtanj, Sokobanja a Felix Romuliana
  delete from public.routes where name = 'Srbsko – Rtanj, Sokobanja a Felix Romuliana' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Srbsko – Rtanj, Sokobanja a Felix Romuliana', 'Okruh východním Srbskem, které většina turistů mine — a dělá chybu. Z lázeňské Sokobanje se jede pod dokonale pyramidální horou Rtanj, opředenou legendami o zázračné energii, přes Boljevac k římskému císařskému paláci Felix Romuliana u Gamzigradu, památce UNESCO. Silnice jsou prázdné, zvlněné a s novým asfaltem na hlavních tazích; na vedlejších úsecích počítejte místy s výtluky a pomalými traktory. Kraj je proslulý bylinkovým čajem rtanjským a vřesovým medem — stánky u cesty stojí za zastávku. Nejlépe od května do října, na jaře je kotlina kolem Rtnje sytě zelená.', 'loop', 165, 240, 'medium',
     '[{"lat": 43.6415, "lng": 21.8720, "label": "Start: Sokobanja"}, {"lat": 43.7200, "lng": 21.9100, "label": "Rtanj"}, {"lat": 43.8256, "lng": 21.9525, "label": "Boljevac"}, {"lat": 43.8994, "lng": 22.1858, "label": "Felix Romuliana"}, {"lat": 43.9036, "lng": 22.2847, "label": "Zaječar"}, {"lat": 43.6415, "lng": 21.8720, "label": "Cíl: Sokobanja"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.6415,21.8720&destination=43.6415,21.8720&travelmode=driving&waypoints=43.7200,21.9100%7C43.8256,21.9525%7C43.8994,22.1858%7C43.9036,22.2847', 'https://commons.wikimedia.org/wiki/Special:FilePath/Planina_Rtanj.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sokobanja_view.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Planina_Rtanj.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Boljevac_sa_Rtnja1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gamzigrad_-_Felix_Romuliana_(by_Pudelek)_2.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Wiki.Biseri_III_Trg_oslobo%C4%91enja_(Zaje%C4%8Dar)_655.jpg"}'::text[], '{"Sokobanja","Hora Rtanj","Boljevac","Felix Romuliana","Zaječar"}'::text[], '{"RS"}'::text[], false, 5100, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Sokobanja', 'Nejstarší srbské vzdušné lázně s osmanským hammámem, pěší zónou plnou kaváren a horským vzduchem, který sem jezdil dýchat i nobelovec Ivo Andrić. Ráno na promenádě koupíte burek a čerstvý bylinkový čaj z Rtnje. Odtud se vyráží do kotliny pod pyramidu.', 43.6415, 21.8720, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sokobanja_view.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sokobanja_view.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Sokobanja_2015_pesacka_zona.jpg"}'::text[], 0),
    (v_route, 'Hora Rtanj', 'Dokonale symetrická vápencová pyramida vysoká 1565 metrů, o níž legendy tvrdí, že vyzařuje léčivou energii — konspirační teorie sem roku 2012 přivedly davy čekající na konec světa. Silnice obkružuje horu a nabízí ji stále v jiném úhlu. Na úpatí rostou proslulé bylinky na rtanjský čaj.', 43.7200, 21.9100, 'https://commons.wikimedia.org/wiki/Special:FilePath/Planina_Rtanj.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Planina_Rtanj.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Piramida_Rtanj.jpg"}'::text[], 1),
    (v_route, 'Boljevac', 'Klidné městečko pod severním svahem Rtnje, odkud je na pyramidu nejhezčí ucelený pohled. Dobré místo na doplnění paliva a rychlou kávu na náměstí. Odtud se stáčí na východ k římským památkám.', 43.8256, 21.9525, 'https://commons.wikimedia.org/wiki/Special:FilePath/Boljevac_sa_Rtnja1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Boljevac_sa_Rtnja1.jpg"}'::text[], 2),
    (v_route, 'Felix Romuliana', 'Opevněný palác, který si císař Galerius postavil na místě svého rodiště a pojmenoval po matce Romule — památka UNESCO s mohutnými věžemi, mozaikami a chrámy z přelomu 3. a 4. století. Areál u Gamzigradu se prochází volně, počítejte s hodinou. Na slunci tu není stín, helmu i bundu nechte u motorky.', 43.8994, 22.1858, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gamzigrad_-_Felix_Romuliana_(by_Pudelek)_2.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gamzigrad_-_Felix_Romuliana_(by_Pudelek)_2.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Feliks_Romulijana_u_predvecerje.JPG"}'::text[], 3),
    (v_route, 'Zaječar', 'Okresní město s příjemným náměstím osvobození a Národním muzeem, kde jsou vystaveny originály nálezů z Felix Romuliany včetně porfyrové hlavy císaře Galeria. Kraj je také domovem piva Zaječarsko. Poslední zastávka před návratem přes kopce do Sokobanje.', 43.9036, 22.2847, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wiki.Biseri_III_Trg_oslobo%C4%91enja_(Zaje%C4%8Dar)_655.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wiki.Biseri_III_Trg_oslobo%C4%91enja_(Zaje%C4%8Dar)_655.jpg"}'::text[], 4);

end $$;
