-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — Španělsko 2 (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Aragonské Pyreneje – Ordesa a Aínsa
  delete from public.routes where name = 'Aragonské Pyreneje – Ordesa a Aínsa' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Aragonské Pyreneje – Ordesa a Aínsa', 'Přejezd aragonskými Pyrenejemi od pevnosti v Jace až pod třítisícovku Monte Perdido. Silnice N-260 se přes průsmyk Cotefablo vlní hlubokými lesy do Torly, brány národního parku Ordesa y Monte Perdido, a dál kaňonem řeky Ara do středověké Aínsy. Závěr patří tiché silnici do Bielsy a ledovcovému údolí Pineta. Asfalt je vesměs výborný, zatáček nekonečně a provoz mimo srpen minimální. Nejlépe od května do října, brzy zjara bývají výše položené úseky studené. Pozor na cyklisty a na štěrk splavený do serpentin po bouřkách.', 'poi', 150, 210, 'medium',
     '[{"lat": 42.5710, "lng": -0.5498, "label": "Start: Jaca"}, {"lat": 42.6273, "lng": -0.3192, "label": "Biescas"}, {"lat": 42.6273, "lng": -0.1125, "label": "Torla"}, {"lat": 42.4162, "lng": 0.1381, "label": "Aínsa"}, {"lat": 42.6335, "lng": 0.2213, "label": "Cíl: Bielsa"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.5710,-0.5498&destination=42.6335,0.2213&travelmode=driving&waypoints=42.6273,-0.3192%7C42.6273,-0.1125%7C42.4162,0.1381', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ciudadela%20Jaca%20Vista%20Aerea.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ciudadela%20Jaca%20Vista%20Aerea.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20des%20del%20Canal%20de%20Arbenuso.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Torla,%20valle%20ordesa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20Mayor,%20Ainsa,%20Spain.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Valle%20de%20Pineta%2001.jpg"}'::text[], '{"Jaca – citadela","Biescas","Torla a údolí Ordesa","Aínsa – Plaza Mayor","Bielsa a Valle de Pineta"}'::text[], '{"ES"}'::text[], false, 3610, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Jaca – citadela', 'Pěticípá renesanční pevnost ze 16. století, jedna z nejzachovalejších v Evropě — v příkopu se navíc prohánějí jeleni. Jaca je přirozená brána do aragonských Pyrenejí a dobré místo na kávu před horami.', 42.5710, -0.5498, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ciudadela%20Jaca%20Vista%20Aerea.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ciudadela%20Jaca%20Vista%20Aerea.JPG"}'::text[], 0),
    (v_route, 'Biescas', 'Kamenné městečko na řece Gállego u vstupu do údolí Tena. Ideální rychlá zastávka před stoupáním do průsmyku Cotefablo.', 42.6273, -0.3192, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20des%20del%20Canal%20de%20Arbenuso.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20des%20del%20Canal%20de%20Arbenuso.jpg"}'::text[], 1),
    (v_route, 'Torla a údolí Ordesa', 'Vesnice s břidlicovými střechami pod kolmou stěnou Mondarruega, brána národního parku Ordesa y Monte Perdido. Z vyhlídek nad vsí se otevírá jeden z nejslavnějších horských pohledů Španělska.', 42.6273, -0.1125, 'https://commons.wikimedia.org/wiki/Special:FilePath/Torla,%20valle%20ordesa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Torla,%20valle%20ordesa.jpg"}'::text[], 2),
    (v_route, 'Aínsa – Plaza Mayor', 'Dokonale dochované středověké náměstí s podloubím a románskou zvonicí, od níž je vidět masiv Monte Perdido. Jedno z nejkrásnějších městeček Španělska.', 42.4162, 0.1381, 'https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20Mayor,%20Ainsa,%20Spain.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20Mayor,%20Ainsa,%20Spain.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Callizo (Aínsa)', 'Oceňovaná kuchyně přímo na středověkém náměstí — moderní pojetí horských surovin Pyrenejí. V sezóně rezervuj předem, degustační menu stojí za delší pauzu.', 42.4165, 0.1379, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20A%C3%ADnsa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20A%C3%ADnsa.jpg"}'::text[], 4),
    (v_route, 'Bielsa a Valle de Pineta', 'Slepé ledovcové údolí zakončené kilometrovou stěnou Monte Perdido. Silnička z Bielsy k parádoru na konci údolí je nádherná tečka za trasou.', 42.6335, 0.2213, 'https://commons.wikimedia.org/wiki/Special:FilePath/Valle%20de%20Pineta%2001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Valle%20de%20Pineta%2001.jpg"}'::text[], 5);

  -- Baskické pobřeží – San Sebastián a Gaztelugatxe
  delete from public.routes where name = 'Baskické pobřeží – San Sebastián a Gaztelugatxe' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Baskické pobřeží – San Sebastián a Gaztelugatxe', 'Pobřežní klasika Baskicka po silnicích N-634 a BI-3438 nad útesy Biskajského zálivu. Z elegantního San Sebastiánu se jede přes rybářskou Getarii a vrstevnaté útesy flysch v Zumaii, dál kolem Lekeitia a Gerniky až k ikonickému ostrůvku Gaztelugatxe. Finále obstará Bilbao s Guggenheimovým muzeem. Úzké pobřežní silničky se kroutí nad mořem a výhled se otevírá na každém kilometru. Ideální od jara do podzimu — počítej s vlhkým atlantickým počasím a o víkendech s hustším provozem. Baskicko je gastronomická velmoc, plánuj zastávky na pintxos.', 'poi', 160, 240, 'medium',
     '[{"lat": 43.3183, "lng": -1.9860, "label": "Start: San Sebastián"}, {"lat": 43.3059, "lng": -2.2039, "label": "Getaria"}, {"lat": 43.2989, "lng": -2.2616, "label": "Zumaia"}, {"lat": 43.3645, "lng": -2.5039, "label": "Lekeitio"}, {"lat": 43.3170, "lng": -2.6716, "label": "Gernika"}, {"lat": 43.4470, "lng": -2.7854, "label": "Gaztelugatxe"}, {"lat": 43.2687, "lng": -2.9340, "label": "Cíl: Bilbao"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.3183,-1.9860&destination=43.2687,-2.9340&travelmode=driving&waypoints=43.3059,-2.2039%7C43.2989,-2.2616%7C43.3645,-2.5039%7C43.3170,-2.6716%7C43.4470,-2.7854', 'https://commons.wikimedia.org/wiki/Special:FilePath/LA%20CONCHA,%20SAN%20SEBASTI%C3%81N,%20SPAIN.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/LA%20CONCHA,%20SAN%20SEBASTI%C3%81N,%20SPAIN.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Getaria,%20Harbour%20and%20Mount%20San%20Anton.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zumaia%27s%20Flysch%20cliffs..JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Puerto%20de%20Lekeitio%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Arbol%20de%20Gernika%20d%C3%ADa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/San%20Juan%20de%20Gaztelugatxe,%20Bermeo.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Guggenheim%20Museum,%20Bilbao,%20July%202010%20(11).JPG"}'::text[], '{"San Sebastián – pláž La Concha","Getaria – rybářský přístav","Zumaia – útesy flysch","Lekeitio","Gernika","San Juan de Gaztelugatxe","Bilbao – Guggenheimovo muzeum"}'::text[], '{"ES"}'::text[], false, 3620, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'San Sebastián – pláž La Concha', 'Mušlová zátoka s promenádou patří k nejkrásnějším městským plážím světa. Elegantní lázeňské město je zároveň hlavním městem baskické gastronomie.', 43.3183, -1.9860, 'https://commons.wikimedia.org/wiki/Special:FilePath/LA%20CONCHA,%20SAN%20SEBASTI%C3%81N,%20SPAIN.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/LA%20CONCHA,%20SAN%20SEBASTI%C3%81N,%20SPAIN.JPG"}'::text[], 0),
    (v_route, 'Getaria – rybářský přístav', 'Rodiště mořeplavce Elcana s přístavem schovaným za skalnatou horou San Antón, které místní říkají Myš. Nad grily u přístavu voní čerstvě ulovené ryby.', 43.3059, -2.2039, 'https://commons.wikimedia.org/wiki/Special:FilePath/Getaria,%20Harbour%20and%20Mount%20San%20Anton.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Getaria,%20Harbour%20and%20Mount%20San%20Anton.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Elkano (Getaria)', 'Legendární podnik s michelinskou hvězdou, kde se celé ryby grilují na dřevěném uhlí před vchodem. Jedna z nejslavnějších rybích restaurací Evropy — rezervace nutná.', 43.3055, -2.2045, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Getaria.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Getaria.jpg"}'::text[], 2),
    (v_route, 'Zumaia – útesy flysch', 'Vrstevnaté útesy jako listy kamenné knihy staré 60 milionů let, známé i ze Hry o trůny. Nejlepší pohled je z pláže Itzurun pod kostelem San Telmo.', 43.2989, -2.2616, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zumaia%27s%20Flysch%20cliffs..JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zumaia%27s%20Flysch%20cliffs..JPG"}'::text[], 3),
    (v_route, 'Lekeitio', 'Barevný rybářský přístav s ostrůvkem, na který se dá při odlivu dojít pěšky po dně. Skvělé místo na kávu nad mořem v půlce trasy.', 43.3645, -2.5039, 'https://commons.wikimedia.org/wiki/Special:FilePath/Puerto%20de%20Lekeitio%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puerto%20de%20Lekeitio%20-%20panoramio.jpg"}'::text[], 4),
    (v_route, 'Gernika', 'Posvátné město Basků s dubem, pod nímž se po staletí scházel baskický sněm; bombardování z roku 1937 zvěčnil Picasso. Krátká zastávka s velkou historií.', 43.3170, -2.6716, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arbol%20de%20Gernika%20d%C3%ADa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arbol%20de%20Gernika%20d%C3%ADa.jpg"}'::text[], 5),
    (v_route, 'San Juan de Gaztelugatxe', 'Poustevna na skalnatém ostrůvku spojená s pevninou kamenným mostem a 241 schody — Dračí kámen ze Hry o trůny. Nejikoničtější místo baskického pobřeží.', 43.4470, -2.7854, 'https://commons.wikimedia.org/wiki/Special:FilePath/San%20Juan%20de%20Gaztelugatxe,%20Bermeo.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/San%20Juan%20de%20Gaztelugatxe,%20Bermeo.JPG"}'::text[], 6),
    (v_route, 'Bilbao – Guggenheimovo muzeum', 'Titanová vlna Franka Gehryho, která proměnila průmyslové město v metropoli moderního umění. Zaparkuj na nábřeží a projdi se kolem obřího pavouka Maman.', 43.2687, -2.9340, 'https://commons.wikimedia.org/wiki/Special:FilePath/Guggenheim%20Museum,%20Bilbao,%20July%202010%20(11).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Guggenheim%20Museum,%20Bilbao,%20July%202010%20(11).JPG"}'::text[], 7);

  -- Galicie – Costa da Morte a mys Fisterra
  delete from public.routes where name = 'Galicie – Costa da Morte a mys Fisterra' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Galicie – Costa da Morte a mys Fisterra', 'Okruh divokým pobřežím smrti — Costa da Morte — ze Santiaga de Compostela. Krajem žulových vesnic a eukalyptových lesů se jede k vodopádu Ézaro, který padá přímo do oceánu, a na mys Fisterra, středověký konec světa. Zpáteční cesta přes svatyni v Muxíi patří k nejkrásnějším pobřežním úsekům Španělska. Silnice jsou úzké, ale s výborným povrchem a téměř bez provozu. Nejlepší je léto a září; atlantická mlha a přeháňky ale můžou přijít kdykoli, přibal nepromok.', 'loop', 220, 300, 'medium',
     '[{"lat": 42.8806, "lng": -8.5449, "label": "Start: Santiago de Compostela"}, {"lat": 42.9070, "lng": -8.7080, "label": "Ponte Maceira"}, {"lat": 42.9110, "lng": -9.1280, "label": "Ézaro"}, {"lat": 42.8830, "lng": -9.2720, "label": "Fisterra"}, {"lat": 43.1120, "lng": -9.2180, "label": "Muxía"}, {"lat": 42.8806, "lng": -8.5449, "label": "Cíl: Santiago de Compostela"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.8806,-8.5449&destination=42.8806,-8.5449&travelmode=driving&waypoints=42.9070,-8.7080%7C42.9110,-9.1280%7C42.8830,-9.2720%7C43.1120,-9.2180', 'https://commons.wikimedia.org/wiki/Special:FilePath/Obradoiro%20facade%20-%20Cathedral%20of%20Santiago%20de%20Compostela%20(5).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Obradoiro%20facade%20-%20Cathedral%20of%20Santiago%20de%20Compostela%20(5).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Ponte%20Maceira.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ezaro%20-%2003%20-%20Fervenza-Cascada-Waterfall.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Finisterre%20-%20lighthouse.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Santuario%20de%20Nuestra%20Se%C3%B1ora%20de%20La%20Barca.JPG"}'::text[], '{"Santiago de Compostela – katedrála","Ponte Maceira","Vodopád Ézaro","Fisterra – maják na konci světa","Muxía – svatyně Virxe da Barca"}'::text[], '{"ES"}'::text[], false, 3630, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Santiago de Compostela – katedrála', 'Cíl svatojakubských poutí s barokním průčelím Obradoiro. Na náměstí sleduj poutníky, kteří právě došli — za chvíli pojedeš tam, kam mnozí pokračují: na konec světa.', 42.8806, -8.5449, 'https://commons.wikimedia.org/wiki/Special:FilePath/Obradoiro%20facade%20-%20Cathedral%20of%20Santiago%20de%20Compostela%20(5).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Obradoiro%20facade%20-%20Cathedral%20of%20Santiago%20de%20Compostela%20(5).JPG"}'::text[], 0),
    (v_route, 'Ponte Maceira', 'Středověký most přes řeku Tambre v jedné z nejmalebnějších vesnic Galicie. Kamenné mlýny, jezy a zeleň jako z pohlednice.', 42.9070, -8.7080, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ponte%20Maceira.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ponte%20Maceira.jpg"}'::text[], 1),
    (v_route, 'Vodopád Ézaro', 'Jediné místo v Evropě, kde řeka padá po žulových deskách přímo do oceánu. Hora Pindo nad vodopádem bývala posvátným Olympem Keltů.', 42.9110, -9.1280, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ezaro%20-%2003%20-%20Fervenza-Cascada-Waterfall.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ezaro%20-%2003%20-%20Fervenza-Cascada-Waterfall.jpg"}'::text[], 2),
    (v_route, 'Fisterra – maják na konci světa', 'Mys, který Římané považovali za konec známého světa a kde poutníci tradičně pálili boty. Nultý kilometrovník a nekonečný Atlantik pod útesy.', 42.8830, -9.2720, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Finisterre%20-%20lighthouse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Finisterre%20-%20lighthouse.jpg"}'::text[], 3),
    (v_route, 'Restaurace: O Semáforo (Fisterra)', 'Restaurace v bývalé signální stanici přímo na mysu — čerstvé mořské plody s výhledem, který nemá v Evropě obdoby.', 42.8827, -9.2716, 'https://commons.wikimedia.org/wiki/Special:FilePath/Faro%20de%20Fisterra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Faro%20de%20Fisterra.jpg"}'::text[], 4),
    (v_route, 'Muxía – svatyně Virxe da Barca', 'Poutní kostel na skalách bičovaných příbojem; podle legendy sem Panna Maria připlula na kamenné lodi. Divoké zakončení Costa da Morte.', 43.1120, -9.2180, 'https://commons.wikimedia.org/wiki/Special:FilePath/Santuario%20de%20Nuestra%20Se%C3%B1ora%20de%20La%20Barca.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Santuario%20de%20Nuestra%20Se%C3%B1ora%20de%20La%20Barca.JPG"}'::text[], 5);

  -- Extremadura – Trujillo, Guadalupe a Monfragüe
  delete from public.routes where name = 'Extremadura – Trujillo, Guadalupe a Monfragüe' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Extremadura – Trujillo, Guadalupe a Monfragüe', 'Pohodový okruh Extremadurou, krajem conquistadorů, čapích hnízd a dubových pastvin dehesa. Z kamenného UNESCO města Cáceres se jede do Trujilla a poté zvlněnou krajinou ke klášteru Guadalupe, poutnímu klenotu mudéjarské architektury. Návrat vede národním parkem Monfragüe, kde nad skálou Salto del Gitano krouží desítky supů, a přes Plasencii. Silnice jsou prázdné a rychlé, ideální na volnější tempo a dlouhé rovinky. Nejlépe na jaře a na podzim — v létě tu bývá i přes 40 °C. Pozor na zvěř za svítání a za soumraku.', 'loop', 330, 300, 'easy',
     '[{"lat": 39.4753, "lng": -6.3723, "label": "Start: Cáceres"}, {"lat": 39.4633, "lng": -5.8810, "label": "Trujillo"}, {"lat": 39.4527, "lng": -5.3273, "label": "Guadalupe"}, {"lat": 39.8281, "lng": -6.0530, "label": "Monfragüe"}, {"lat": 40.0301, "lng": -6.0884, "label": "Plasencia"}, {"lat": 39.4753, "lng": -6.3723, "label": "Cíl: Cáceres"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=39.4753,-6.3723&destination=39.4753,-6.3723&travelmode=driving&waypoints=39.4633,-5.8810%7C39.4527,-5.3273%7C39.8281,-6.0530%7C40.0301,-6.0884', 'https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20de%20Santa%20Mar%C3%ADa,%20C%C3%A1ceres.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20de%20Santa%20Mar%C3%ADa,%20C%C3%A1ceres.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20Mayor%20con%20la%20estatua%20ecuestre%20de%20Francisco%20Pizarro.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Real%20Monasterio%20de%20Santa%20Mar%C3%ADa%20de%20Guadalupe%202.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Salto%20del%20Gitano,%20Parque%20Nacional%20de%20Monfrag%C3%BCe%20(69623).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Catedral%20de%20Plasencia-1.JPG"}'::text[], '{"Cáceres – staré město","Trujillo – Plaza Mayor","Klášter Guadalupe","Monfragüe – Salto del Gitano","Plasencia"}'::text[], '{"ES"}'::text[], false, 3640, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Cáceres – staré město', 'Kompletně dochované středověké a renesanční město na seznamu UNESCO; věže paláců obsadili čápi. Sloužilo i jako kulisa Hry o trůny.', 39.4753, -6.3723, 'https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20de%20Santa%20Mar%C3%ADa,%20C%C3%A1ceres.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20de%20Santa%20Mar%C3%ADa,%20C%C3%A1ceres.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A1ceres,%20Ciudad%20Monumental.JPG"}'::text[], 0),
    (v_route, 'Trujillo – Plaza Mayor', 'Rodiště dobyvatele Peru Francisca Pizarra s jedním z nejkrásnějších náměstí Španělska a jeho jezdeckou sochou. Nad městem stojí maurský hrad s výhledem na dehesu.', 39.4633, -5.8810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20Mayor%20con%20la%20estatua%20ecuestre%20de%20Francisco%20Pizarro.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20Mayor%20con%20la%20estatua%20ecuestre%20de%20Francisco%20Pizarro.jpg"}'::text[], 1),
    (v_route, 'Restaurace: La Troya (Trujillo)', 'Legendární mesón přímo na náměstí — obří porce extremadurské kuchyně, ibérico vepřové a proslulý předkrm zdarma. Instituce, kam se jezdí přes půl Španělska.', 39.4636, -5.8815, 'https://commons.wikimedia.org/wiki/Special:FilePath/Estatua%20de%20Francisco%20Pizarro%20en%20Trujillo.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Estatua%20de%20Francisco%20Pizarro%20en%20Trujillo.JPG"}'::text[], 2),
    (v_route, 'Klášter Guadalupe', 'Královský klášter na seznamu UNESCO, nejvýznamnější mariánské poutní místo Španělska s mudéjarským rajským dvorem. Horská cesta k němu přes pohoří Villuercas je motorkářský bonus.', 39.4527, -5.3273, 'https://commons.wikimedia.org/wiki/Special:FilePath/Real%20Monasterio%20de%20Santa%20Mar%C3%ADa%20de%20Guadalupe%202.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Real%20Monasterio%20de%20Santa%20Mar%C3%ADa%20de%20Guadalupe%202.JPG"}'::text[], 3),
    (v_route, 'Monfragüe – Salto del Gitano', 'Skalní stěna nad soutěskou řeky Tajo, kde krouží desítky supů bělohlavých — jedno z nejlepších pozorování dravců v Evropě, a to přímo od silnice.', 39.8281, -6.0530, 'https://commons.wikimedia.org/wiki/Special:FilePath/Salto%20del%20Gitano,%20Parque%20Nacional%20de%20Monfrag%C3%BCe%20(69623).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Salto%20del%20Gitano,%20Parque%20Nacional%20de%20Monfrag%C3%BCe%20(69623).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mirador%20del%20Salto%20del%20Gitano%20y%20Rio%20Tajo.jpg"}'::text[], 4),
    (v_route, 'Plasencia', 'Hrazené město se dvěma katedrálami srostlými do jedné a živým náměstím. Příjemná poslední zastávka před návratem do Cáceresu.', 40.0301, -6.0884, 'https://commons.wikimedia.org/wiki/Special:FilePath/Catedral%20de%20Plasencia-1.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Catedral%20de%20Plasencia-1.JPG"}'::text[], 5);

  -- Kastilské hrady – Segovia, Pedraza a Coca
  delete from public.routes where name = 'Kastilské hrady – Segovia, Pedraza a Coca' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kastilské hrady – Segovia, Pedraza a Coca', 'Okruh kastilskou náhorní plošinou za nejkrásnějšími hrady Španělska. Start pod segovijským Alcázarem, který inspiroval pohádkové zámky, pokračuje do středověké Pedrazy a městečka Sepúlveda nad kaňonem řeky Duratón. Přes borové lesy se jede k mohutnému hradu v Cuéllaru a k cihlovému mudéjarskému skvostu Coca. Silnice jsou přehledné, prázdné a rychlé — ideální i pro méně zkušené jezdce. Jaro a podzim nabízejí nejlepší světlo i teploty, v létě jezdi raději dopoledne. Ve vesnicích zpomal, na náměstí se často vjíždí po hrbolaté dlažbě.', 'loop', 230, 240, 'easy',
     '[{"lat": 40.9481, "lng": -4.1184, "label": "Start: Segovia"}, {"lat": 41.1315, "lng": -3.8113, "label": "Pedraza"}, {"lat": 41.2967, "lng": -3.7477, "label": "Sepúlveda"}, {"lat": 41.4019, "lng": -4.3175, "label": "Cuéllar"}, {"lat": 41.2156, "lng": -4.5228, "label": "Coca"}, {"lat": 40.9481, "lng": -4.1184, "label": "Cíl: Segovia"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=40.9481,-4.1184&destination=40.9481,-4.1184&travelmode=driving&waypoints=41.1315,-3.8113%7C41.2967,-3.7477%7C41.4019,-4.3175%7C41.2156,-4.5228', 'https://commons.wikimedia.org/wiki/Special:FilePath/Panor%C3%A1mica%20Oto%C3%B1o%20Alc%C3%A1zar%20de%20Segovia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Panor%C3%A1mica%20Oto%C3%B1o%20Alc%C3%A1zar%20de%20Segovia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Pedraza%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sep%C3%BAlveda,%20Segovia,%20Spain%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Cu%C3%A9llar%20(Segovia).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Coca.jpg"}'::text[], '{"Segovia – Alcázar","Pedraza","Sepúlveda","Hrad Cuéllar","Hrad Coca"}'::text[], '{"ES"}'::text[], false, 3650, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Segovia – Alcázar', 'Hrad na skalní ostruze nad soutokem dvou řek, předloha pohádkových zámků — kamenná loď s modrými věžemi, kde korunovali kastilské krále. Kousek odtud stojí slavný římský akvadukt.', 40.9526, -4.1290, 'https://commons.wikimedia.org/wiki/Special:FilePath/Panor%C3%A1mica%20Oto%C3%B1o%20Alc%C3%A1zar%20de%20Segovia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Panor%C3%A1mica%20Oto%C3%B1o%20Alc%C3%A1zar%20de%20Segovia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Alcazar%20de%20Segovia.JPG"}'::text[], 0),
    (v_route, 'Restaurace: Mesón de Cándido (Segovia)', 'Ikonická restaurace pod římským akvaduktem, kde se pečené sele tradičně porcuje talířem. Gastronomická legenda Kastilie s historií sahající do 18. století.', 40.9477, -4.1181, 'https://commons.wikimedia.org/wiki/Special:FilePath/Acueducto%20de%20Segovia%2001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Acueducto%20de%20Segovia%2001.jpg"}'::text[], 1),
    (v_route, 'Pedraza', 'Dokonale dochovaná středověká vesnice s hradem a arkádovým náměstím, celá z medově zbarveného kamene. Začátkem července ji při slavnosti rozsvěcují tisíce svíček.', 41.1315, -3.8113, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Pedraza%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Pedraza%201.jpg"}'::text[], 2),
    (v_route, 'Sepúlveda', 'Městečko nad kaňonem řeky Duratón, kde nad červenými střechami krouží supi. Proslulé jehněčím pečeným v hliněných pecích.', 41.2967, -3.7477, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sep%C3%BAlveda,%20Segovia,%20Spain%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sep%C3%BAlveda,%20Segovia,%20Spain%20-%20panoramio.jpg"}'::text[], 3),
    (v_route, 'Hrad Cuéllar', 'Mohutný hrad vévodů z Alburquerque nad městem, které se pyšní nejstaršími běhy býků ve Španělsku. Kombinace gotiky a renesance uprostřed borových lesů.', 41.4019, -4.3175, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Cu%C3%A9llar%20(Segovia).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Cu%C3%A9llar%20(Segovia).jpg"}'::text[], 4),
    (v_route, 'Hrad Coca', 'Cihlový mudéjarský hrad, vrchol vojenské architektury 15. století — spíš palác než pevnost. Jeden z nejfotogeničtějších hradů Evropy.', 41.2156, -4.5228, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Coca.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Coca.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20Coca%20(Segovia).jpg"}'::text[], 5);

  -- Katalánsko – sopky Garrotxy a Rupit
  delete from public.routes where name = 'Katalánsko – sopky Garrotxy a Rupit' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Katalánsko – sopky Garrotxy a Rupit', 'Krátká, ale intenzivní vyjížďka katalánským vnitrozemím po legendární silnici C-153. Z Vicu se stoupá k přehradě Sau s potopenou kostelní věží a přes stovky zatáček do kamenného Rupitu. Následuje sopečná krajina Garrotxy — kráter Montsacopa v Olotu, středověká Santa Pau a Castellfollit de la Roca na hraně čedičového srázu. Cíl leží u románského mostu v Besalú. Asfalt je skvělý, zatáčky technické a provoz slabý; o víkendech sem ovšem míří půlka motorkářů z Barcelony. Jezdit se dá prakticky celý rok.', 'poi', 110, 180, 'medium',
     '[{"lat": 41.9303, "lng": 2.2546, "label": "Start: Vic"}, {"lat": 41.9709, "lng": 2.3990, "label": "Pantà de Sau"}, {"lat": 42.0234, "lng": 2.4655, "label": "Rupit"}, {"lat": 42.1876, "lng": 2.4899, "label": "Olot"}, {"lat": 42.1446, "lng": 2.5697, "label": "Santa Pau"}, {"lat": 42.1990, "lng": 2.6996, "label": "Cíl: Besalú"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=41.9303,2.2546&destination=42.1990,2.6996&travelmode=driving&waypoints=41.9709,2.3990%7C42.0234,2.4655%7C42.1876,2.4899%7C42.1446,2.5697', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vic%20(Barcelona).%20Plaza%20Mayor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vic%20(Barcelona).%20Plaza%20Mayor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tavertet%20-%20Panta%20de%20Sau%20-%20Catalunya%20-%20Spain.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rupit%20i%20Pruit,%20Barcelona,%20Spain%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Volcan%20Montsacopa%20(1).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Castellfollit%20de%20la%20Roca%20-%20Vista%20frontal.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20Vell%20de%20Besal%C3%BA.JPG"}'::text[], '{"Vic – Plaça Major","Přehrada Sau","Rupit","Olot – sopka Montsacopa","Castellfollit de la Roca","Besalú – středověký most"}'::text[], '{"ES"}'::text[], false, 3660, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vic – Plaça Major', 'Rozlehlé středověké tržní náměstí lemované podloubím, srdce katalánského vnitrozemí. V úterý a v sobotu tu bývá tradiční trh.', 41.9303, 2.2546, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vic%20(Barcelona).%20Plaza%20Mayor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vic%20(Barcelona).%20Plaza%20Mayor.jpg"}'::text[], 0),
    (v_route, 'Přehrada Sau', 'Z hladiny přehrady vystupuje věž potopeného románského kostela — čím sušší rok, tím víc staré vesnice vystoupí. Vyhlídky ze silnice nad kaňonem řeky Ter jsou velkolepé.', 41.9709, 2.3990, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tavertet%20-%20Panta%20de%20Sau%20-%20Catalunya%20-%20Spain.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tavertet%20-%20Panta%20de%20Sau%20-%20Catalunya%20-%20Spain.jpg"}'::text[], 1),
    (v_route, 'Rupit', 'Kamenná vesnice přilepená ke skále, do části se vchází po visutém mostě. Jedno z nejromantičtějších míst Katalánska.', 42.0234, 2.4655, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rupit%20i%20Pruit,%20Barcelona,%20Spain%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rupit%20i%20Pruit,%20Barcelona,%20Spain%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Riera%20de%20Rupit,%20a%20su%20paso%20por%20Rupit.jpg"}'::text[], 2),
    (v_route, 'Olot – sopka Montsacopa', 'Město mezi čtyřmi vyhaslými sopkami; na kráter Montsacopa s kostelíkem se dá vyjít přímo z centra. Sopečná krajina Garrotxy čítá přes čtyřicet kuželů.', 42.1876, 2.4899, 'https://commons.wikimedia.org/wiki/Special:FilePath/Volcan%20Montsacopa%20(1).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Volcan%20Montsacopa%20(1).JPG"}'::text[], 3),
    (v_route, 'Restaurace: Cal Sastre (Santa Pau)', 'Rodinný podnik ve středověké Santa Pau proslulý fazolemi fesols de Santa Pau a vulkanickou katalánskou kuchyní. Náměstíčko s podloubím je bonus navrch.', 42.1446, 2.5697, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pla%C3%A7a%20de%20Santa%20Pau,%20la%20Garrotxa,%20Girona.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pla%C3%A7a%20de%20Santa%20Pau,%20la%20Garrotxa,%20Girona.jpg"}'::text[], 4),
    (v_route, 'Castellfollit de la Roca', 'Vesnice natěsnaná na hraně padesátimetrového čedičového srázu nad řekou Fluvià. Nejlepší pohled je z protějšího břehu řeky.', 42.2200, 2.5520, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castellfollit%20de%20la%20Roca%20-%20Vista%20frontal.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castellfollit%20de%20la%20Roca%20-%20Vista%20frontal.jpg"}'::text[], 5),
    (v_route, 'Besalú – středověký most', 'Opevněný románský most s bránou uprostřed vede do jednoho z nejzachovalejších středověkých městeček Katalánska s židovskou čtvrtí a rituální lázní mikve.', 42.1990, 2.6996, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20Vell%20de%20Besal%C3%BA.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20Vell%20de%20Besal%C3%BA.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Besal%C3%BA%20-%20Pont%20Vell%2010.JPG"}'::text[], 6);

  -- Alpujarras – bílé vesnice pod Sierra Nevadou
  delete from public.routes where name = 'Alpujarras – bílé vesnice pod Sierra Nevadou' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Alpujarras – bílé vesnice pod Sierra Nevadou', 'Balkónová silnice A-4132 nad údolím Poqueira patří k nejpůsobivějším ve Španělsku — bílé vesnice Alpujarras se lepí na jižní svahy Sierra Nevady ve výšce přes tisíc metrů. Z lázeňského Lanjarónu se šplhá do Pampaneiry, Capileiry a do nejvýše položené vesnice Španělska Trevélez, proslulé horskou šunkou. Dál na východ se krajina mění v polopoušť s výhledy až ke Středozemnímu moři. Úzké serpentiny vyžadují pozornost, odměnou je nekonečné klopení. Ideální od dubna do listopadu, v zimě může výše mrznout. Pozor na turistické autobusy mezi vesnicemi.', 'poi', 85, 150, 'medium',
     '[{"lat": 36.9190, "lng": -3.4770, "label": "Start: Lanjarón"}, {"lat": 36.9394, "lng": -3.3618, "label": "Pampaneira"}, {"lat": 36.9612, "lng": -3.3585, "label": "Capileira"}, {"lat": 37.0007, "lng": -3.2654, "label": "Trevélez"}, {"lat": 36.9970, "lng": -3.0610, "label": "Yegen"}, {"lat": 36.9670, "lng": -3.0560, "label": "Cíl: Ugíjar"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=36.9190,-3.4770&destination=36.9670,-3.0560&travelmode=driving&waypoints=36.9394,-3.3618%7C36.9612,-3.3585%7C37.0007,-3.2654%7C36.9970,-3.0610', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Lanjar%C3%B3n.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Lanjar%C3%B3n.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pampaneira.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Capileira.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Trev%C3%A9lez.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Yegen.jpg"}'::text[], '{"Lanjarón","Pampaneira","Capileira","Trevélez","Yegen"}'::text[], '{"ES"}'::text[], false, 3670, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lanjarón', 'Brána Alpujarras — lázeňské městečko s maurským hradem a pramenitou vodou známou po celém Španělsku. Odtud silnice začíná šplhat do hor.', 36.9190, -3.4770, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Lanjar%C3%B3n.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Lanjar%C3%B3n.jpg"}'::text[], 0),
    (v_route, 'Pampaneira', 'První z bílých vesnic v rokli Poqueira — komíny s kloboučky, tkalcovské dílny a uličky, kterými teče voda z hor. Berberská architektura přenesená z afrického Atlasu.', 36.9394, -3.3618, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pampaneira.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pampaneira.jpg"}'::text[], 1),
    (v_route, 'Capileira', 'Nejvýše položená vesnice rokle Poqueira s výhledy na Mulhacén, nejvyšší horu Pyrenejského poloostrova. Bílé terasy domů tu visí nad hlubokým údolím.', 36.9612, -3.3585, 'https://commons.wikimedia.org/wiki/Special:FilePath/Capileira.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Capileira.jpg"}'::text[], 2),
    (v_route, 'Trevélez', 'Nejvýše položená vesnice Španělska (1 486 m) a hlavní město sušené šunky, která tu zraje v čistém horském vzduchu. Serpentiny sem nahoru jsou zážitek samy o sobě.', 37.0007, -3.2654, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trev%C3%A9lez.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trev%C3%A9lez.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Mesón La Fragua (Trevélez)', 'Horská hospoda s terasou nad střechami Trevélezu — místní šunka, kozí sýr a pstruh ze Sierra Nevady. Poctivá kuchyně po serpentinách chutná dvojnásob.', 37.0010, -3.2650, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Trev%C3%A9lez.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Trev%C3%A9lez.jpg"}'::text[], 4),
    (v_route, 'Yegen', 'Vesnice, kterou proslavil britský spisovatel Gerald Brenan knihou Jih od Granady. Východní Alpujarras jsou syrovější a prázdnější — silnice tu bývá jen pro tebe.', 36.9970, -3.0610, 'https://commons.wikimedia.org/wiki/Special:FilePath/Yegen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Yegen.jpg"}'::text[], 5);

  -- Sierra de Cazorla – zelené srdce Andalusie
  delete from public.routes where name = 'Sierra de Cazorla – zelené srdce Andalusie' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sierra de Cazorla – zelené srdce Andalusie', 'Přírodní park Sierras de Cazorla, Segura y Las Villas je největší chráněné území Španělska a silnice A-319 podél mladého Guadalquiviru jeho páteř. Z Cazorly pod maurským hradem se jede borovými lesy k tyrkysové řece Borosa a podél dlouhé přehrady Tranco. Závěr přes horské vesničky Hornos a Segura de la Sierra s hradem na kuželu je čistá motorkářská radost. Zatáčky nemají konce, provoz je minimální a vzduch voní pryskyřicí. Nejlépe od dubna do června a v září, o letních víkendech bývá u přehrady rušněji. Pozor na kozorožce a divočáky na silnici.', 'poi', 105, 150, 'medium',
     '[{"lat": 37.9105, "lng": -3.0037, "label": "Start: Cazorla"}, {"lat": 38.0110, "lng": -2.8940, "label": "Torre del Vinagre"}, {"lat": 38.1720, "lng": -2.7960, "label": "Embalse del Tranco"}, {"lat": 38.2180, "lng": -2.7200, "label": "Hornos"}, {"lat": 38.2980, "lng": -2.6520, "label": "Cíl: Segura de la Sierra"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.9105,-3.0037&destination=38.2980,-2.6520&travelmode=driving&waypoints=38.0110,-2.8940%7C38.1720,-2.7960%7C38.2180,-2.7200', 'https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20la%20Yedra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20la%20Yedra.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rio%20Borosa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Embalse%20del%20Tranco.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hornos%20de%20Segura.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Segura%20de%20la%20Sierra.jpg"}'::text[], '{"Cazorla – hrad La Yedra","Río Borosa – Torre del Vinagre","Embalse del Tranco","Hornos","Segura de la Sierra"}'::text[], '{"ES"}'::text[], false, 3680, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Cazorla – hrad La Yedra', 'Bílé městečko pod skalami s maurským hradem La Yedra, brána největšího přírodního parku Španělska. Úzké uličky ústí na náměstí s výhledem na hradby.', 37.9105, -3.0037, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20la%20Yedra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castillo%20de%20la%20Yedra.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Mesón Leandro (Cazorla)', 'Rodinný mesón s horskou kuchyní — zvěřina, místní pstruh a segurské olivové oleje. Ideální vydatný start před vjezdem do parku.', 37.9130, -3.0020, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Cazorla.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Cazorla.jpg"}'::text[], 1),
    (v_route, 'Río Borosa – Torre del Vinagre', 'Návštěvnické centrum u tyrkysové řeky Borosa, nejslavnější soutěsky parku s dřevěnými lávkami nad vodou. Krátká procházka od parkoviště stojí za protažení nohou.', 38.0110, -2.8940, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rio%20Borosa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rio%20Borosa.jpg"}'::text[], 2),
    (v_route, 'Embalse del Tranco', 'Dlouhá přehrada na mladém Guadalquiviru — silnice se vine podél břehů desítky kilometrů. Vyhlídky míří na ostrůvek se zříceninou hradu Bujaraiza.', 38.1720, -2.7960, 'https://commons.wikimedia.org/wiki/Special:FilePath/Embalse%20del%20Tranco.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Embalse%20del%20Tranco.jpg"}'::text[], 3),
    (v_route, 'Hornos', 'Vesnička na skalním ostrohu vysoko nad hladinou přehrady, s hradem a planetáriem v jeho věži. Výhled obsáhne celé údolí Guadalquiviru.', 38.2180, -2.7200, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hornos%20de%20Segura.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hornos%20de%20Segura.jpg"}'::text[], 4),
    (v_route, 'Segura de la Sierra', 'Hrad na dokonalém kuželu nad horskou vesnicí, jedno z nejpůsobivějších panoramat Andalusie. Serpentiny nahoru jsou třešnička na konci trasy.', 38.2980, -2.6520, 'https://commons.wikimedia.org/wiki/Special:FilePath/Segura%20de%20la%20Sierra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Segura%20de%20la%20Sierra.jpg"}'::text[], 5);

  -- Maestrazgo – Morella, Cantavieja a Teruel
  delete from public.routes where name = 'Maestrazgo – Morella, Cantavieja a Teruel' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Maestrazgo – Morella, Cantavieja a Teruel', 'Maestrazgo je zapomenutá horská země na pomezí Aragonu a Valencie — kamenná města na skalách, kaňony a silnice, kde potkáš víc supů než aut. Start na hradbách Morelly, pak středověký Mirambel a Cantavieja přilepená na hraně útesu. Silnice A-1702 kolem skalních věží Órganos de Montoro patří k nejlepším motorkářským asfaltům Španělska. Cíl je v Teruelu, městě mudéjarských věží zapsaných na seznamu UNESCO. Úseky jsou úzké a odlehlé — tankuj, kde se dá. Nejlépe od května do října, přes zimu tu leží sníh.', 'poi', 170, 240, 'medium',
     '[{"lat": 40.6190, "lng": -0.1000, "label": "Start: Morella"}, {"lat": 40.5900, "lng": -0.3430, "label": "Mirambel"}, {"lat": 40.5270, "lng": -0.4050, "label": "Cantavieja"}, {"lat": 40.6470, "lng": -0.6690, "label": "Órganos de Montoro"}, {"lat": 40.3440, "lng": -1.1069, "label": "Cíl: Teruel"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=40.6190,-0.1000&destination=40.3440,-1.1069&travelmode=driving&waypoints=40.5900,-0.3430%7C40.5270,-0.4050%7C40.6470,-0.6690', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Morella.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Morella.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mirambel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cantavieja.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%93rganos%20de%20Montoro.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Torre%20de%20El%20Salvador%20(Teruel).jpg"}'::text[], '{"Morella","Mirambel","Cantavieja","Órganos de Montoro","Teruel – mudéjarské věže"}'::text[], '{"ES"}'::text[], false, 3690, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Morella', 'Město obehnané dvěma kilometry hradeb s hradem na skále uprostřed — z dálky vypadá jako kamenná koruna. Jedno z nejkrásnějších měst Španělska a domov sýrových koláčků flaons.', 40.6190, -0.1000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Morella.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Morella.jpg"}'::text[], 0),
    (v_route, 'Mirambel', 'Kompletně zachovalé hrazené městečko, kde se od středověku skoro nic nezměnilo. Klenotem je brána Portal de las Monjas se zdobeným mřížovím.', 40.5900, -0.3430, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mirambel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mirambel.jpg"}'::text[], 1),
    (v_route, 'Cantavieja', 'Hlavní město Maestrazga přilepené na hraně útesu ve 1 300 metrech, s gotickým arkádovým náměstím. Silnice sem nahoru je jedna dlouhá serpentina.', 40.5270, -0.4050, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cantavieja.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cantavieja.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Balfagón (Cantavieja)', 'Horský hotel s kuchyní z místních surovin — jehněčí ternasco, hřiby a lanýže z Maestrazga. Spolehlivá zastávka v kraji, kde je restaurací poskrovnu.', 40.5265, -0.4045, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Cantavieja.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Cantavieja.jpg"}'::text[], 3),
    (v_route, 'Órganos de Montoro', 'Stometrové skalní varhany nad silnicí A-1702 — vápencové věže, kde hnízdí supi a po římsách šplhají kozorožci. Nejfotogeničtější úsek celé trasy.', 40.6470, -0.6690, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%93rganos%20de%20Montoro.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%93rganos%20de%20Montoro.jpg"}'::text[], 4),
    (v_route, 'Teruel – mudéjarské věže', 'Nejmenší provinční metropole Španělska s cihlovými věžemi zdobenými keramikou, zapsanými na seznamu UNESCO. Město legendárních milenců z Teruelu a výborné šunky.', 40.3440, -1.1069, 'https://commons.wikimedia.org/wiki/Special:FilePath/Torre%20de%20El%20Salvador%20(Teruel).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Torre%20de%20El%20Salvador%20(Teruel).jpg"}'::text[], 5);

  -- La Rioja – vinice, kláštery a tapas
  delete from public.routes where name = 'La Rioja – vinice, kláštery a tapas' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'La Rioja – vinice, kláštery a tapas', 'Pohodový vinařský okruh krajem Rioja, kde se zatáčky střídají s nekonečnými lány vinic pod hřebenem Sierra de Cantabria. Z Logroña vede cesta do opevněné Laguardie na kopci, do vinařské metropole Haro a ke klášteru Yuso v San Millán, kolébce psané španělštiny. Zpátky se jede přes královskou Nájeru podél řeky Ebro. Silnice jsou klidné, rychlé a přehledné — ideální na první zahraniční kilometry i na podzimní vyjížďku ve vinobraní. Večer si nech čas na Calle del Laurel, nejslavnější tapas ulici Španělska. Pozor na zemědělskou techniku mezi vinicemi.', 'loop', 160, 210, 'easy',
     '[{"lat": 42.4661, "lng": -2.4449, "label": "Start: Logroño"}, {"lat": 42.5551, "lng": -2.5850, "label": "Laguardia"}, {"lat": 42.5760, "lng": -2.8470, "label": "Haro"}, {"lat": 42.3262, "lng": -2.8652, "label": "San Millán de la Cogolla"}, {"lat": 42.4162, "lng": -2.7331, "label": "Nájera"}, {"lat": 42.4661, "lng": -2.4449, "label": "Cíl: Logroño"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.4661,-2.4449&destination=42.4661,-2.4449&travelmode=driving&waypoints=42.5551,-2.5850%7C42.5760,-2.8470%7C42.3262,-2.8652%7C42.4162,-2.7331', 'https://commons.wikimedia.org/wiki/Special:FilePath/Puente%20de%20Piedra,%20Logro%C3%B1o.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puente%20de%20Piedra,%20Logro%C3%B1o.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Laguardia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Haro,%20La%20Rioja.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monasterio%20de%20Yuso.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monasterio%20de%20Santa%20Mar%C3%ADa%20la%20Real%20de%20N%C3%A1jera.jpg"}'::text[], '{"Logroño","Laguardia","Haro","Klášter Yuso (San Millán de la Cogolla)","Nájera – klášter Santa María la Real"}'::text[], '{"ES"}'::text[], false, 3700, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Logroño', 'Metropole Rioji na řece Ebro s katedrálou a kamenným mostem svatojakubské cesty. Startovní i cílový bod vinařského okruhu.', 42.4661, -2.4449, 'https://commons.wikimedia.org/wiki/Special:FilePath/Puente%20de%20Piedra,%20Logro%C3%B1o.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puente%20de%20Piedra,%20Logro%C3%B1o.jpg"}'::text[], 0),
    (v_route, 'Laguardia', 'Opevněné městečko na kopci uprostřed moře vinic, celé podryté středověkými vinnými sklepy — auta dovnitř nesmí, motorku zaparkuješ před hradbami. Výhled na hřeben Sierra de Cantabria.', 42.5551, -2.5850, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Laguardia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20de%20Laguardia.jpg"}'::text[], 1),
    (v_route, 'Haro', 'Vinařské hlavní město Rioji se čtvrtí Barrio de la Estación, kde sídlí nejslavnější vinařství země. Ochutnávku ale nech na dobu, kdy motorka stojí.', 42.5760, -2.8470, 'https://commons.wikimedia.org/wiki/Special:FilePath/Haro,%20La%20Rioja.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Haro,%20La%20Rioja.jpg"}'::text[], 2),
    (v_route, 'Klášter Yuso (San Millán de la Cogolla)', 'Klášter na seznamu UNESCO, kde byly nalezeny první písemné záznamy španělštiny. Tiché údolí San Millán je krásný kontrast k vinicím.', 42.3262, -2.8652, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monasterio%20de%20Yuso.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monasterio%20de%20Yuso.jpg"}'::text[], 3),
    (v_route, 'Nájera – klášter Santa María la Real', 'Pohřebiště navarrských králů s gotickým klášterem vestavěným do červené skály. Nájera bývala hlavním městem Navarrského království.', 42.4162, -2.7331, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monasterio%20de%20Santa%20Mar%C3%ADa%20la%20Real%20de%20N%C3%A1jera.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monasterio%20de%20Santa%20Mar%C3%ADa%20la%20Real%20de%20N%C3%A1jera.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Bar Soriano (Logroño)', 'Legenda z Calle del Laurel, nejslavnější tapas uličky Španělska — už přes 80 let tu dělají jedinou věc: žampionové špízy s krevetou. Ideální tečka za okruhem.', 42.4657, -2.4461, 'https://commons.wikimedia.org/wiki/Special:FilePath/Calle%20Laurel,%20Logro%C3%B1o.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Calle%20Laurel,%20Logro%C3%B1o.jpg"}'::text[], 5);

end $$;
