-- ==================================================================
-- MotoGo24 - KATALOG BODU ZAJMU: DAVKA 2 (50 overenych flagship bodu)
-- Rucne kuratovana data: overene GPS + popisy v 8 jazycich.
-- Kategorie EXPLICITNI (spolehlivy filtr). Idempotentni dle source.
-- Voda 15 | Hrady a zamky 15 | Rozhledny 4 | Pamatky 6 | Priroda 10
-- ==================================================================

delete from public.points_of_interest where source = 'curated-batch2';

insert into public.points_of_interest
  (category, name, description, lat, lng, country, source, sort_order, translations)
values
-- == VODA ==========================================================
('water', 'Slapská přehrada',
 'Nejznámější vltavská přehrada s hlubokým údolím a vyhlídkami na hráz; klasika vyjížděk podél Vltavy.',
 49.8199, 14.4370, 'CZ', 'curated-batch2', 100,
 '{"en":{"name":"Slapy Reservoir","description":"The best-known Vltava dam with a deep valley and dam viewpoints; a classic ride along the Vltava."},
   "de":{"name":"Stausee Slapy","description":"Der bekannteste Moldaustausee mit tiefem Tal und Aussichtspunkten an der Staumauer; ein Klassiker entlang der Moldau."},
   "pl":{"name":"Zbiornik Slapy","description":"Najbardziej znana zapora na Wełtawie z głęboką doliną i punktami widokowymi; klasyka wypraw wzdłuż Wełtawy."},
   "nl":{"name":"Stuwmeer Slapy","description":"De bekendste Moldau-stuwdam met een diep dal en uitzichtpunten; een klassieker langs de Moldau."},
   "es":{"name":"Embalse de Slapy","description":"La presa más conocida del Moldava, con un valle profundo y miradores; un clásico junto al Moldava."},
   "fr":{"name":"Barrage de Slapy","description":"Le barrage le plus connu de la Vltava, avec une vallée profonde et des belvédères ; un classique le long de la Vltava."},
   "uk":{"name":"Слапське водосховище","description":"Найвідоміша гребля на Влтаві з глибокою долиною та оглядовими точками; класика поїздок уздовж Влтави."}}'::jsonb),

('water', 'Vranovská přehrada',
 'Přehrada na Dyji zvaná „Moravský Jadran" s plážemi a zámkem Vranov tyčícím se nad hladinou.',
 48.9048, 15.8830, 'CZ', 'curated-batch2', 101,
 '{"en":{"name":"Vranov Reservoir","description":"A dam on the Dyje nicknamed the Moravian Adriatic, with beaches and Vranov chateau towering above the water."},
   "de":{"name":"Stausee Vranov (Frain)","description":"Ein Stausee an der Thaya, die Mährische Adria genannt, mit Stränden und dem Schloss Frain über dem Wasser."},
   "pl":{"name":"Zbiornik Vranov","description":"Zapora na Dyi zwana Morawskim Adriatykiem, z plażami i zamkiem Vranov górującym nad wodą."},
   "nl":{"name":"Stuwmeer Vranov","description":"Een stuwmeer aan de Dyje, de Moravische Adriatische Zee genoemd, met stranden en kasteel Vranov boven het water."},
   "es":{"name":"Embalse de Vranov","description":"Una presa en el Dyje apodada el Adriático moravo, con playas y el castillo de Vranov sobre el agua."},
   "fr":{"name":"Lac de Vranov","description":"Un barrage sur la Dyje surnommé l''Adriatique morave, avec des plages et le château de Vranov dominant l''eau."},
   "uk":{"name":"Вранівське водосховище","description":"Гребля на Диї, звана Моравською Адріатикою, з пляжами та замком Вранов над водою."}}'::jsonb),

('water', 'Nechranická přehrada',
 'Přehrada na Ohři s nejdelší sypanou hrází ve střední Evropě; široká hladina a klid severozápadních Čech.',
 50.3517, 13.3890, 'CZ', 'curated-batch2', 102,
 '{"en":{"name":"Nechranice Reservoir","description":"A dam on the Ohře with Central Europe''s longest earth-fill dike; wide waters in the calm of northwest Bohemia."},
   "de":{"name":"Stausee Nechranice","description":"Ein Stausee an der Eger mit dem längsten Schüttdamm Mitteleuropas; weite Wasserfläche im ruhigen Nordwestböhmen."},
   "pl":{"name":"Zbiornik Nechranice","description":"Zapora na Ohrzy z najdłuższą zaporą ziemną w Europie Środkowej; szeroka tafla wody na spokojnym północnym zachodzie Czech."},
   "nl":{"name":"Stuwmeer Nechranice","description":"Een dam in de Ohře met de langste aarden dam van Midden-Europa; weids water in het rustige noordwesten van Bohemen."},
   "es":{"name":"Embalse de Nechranice","description":"Una presa en el Ohře con el dique de tierra más largo de Europa Central; aguas anchas en el tranquilo noroeste de Bohemia."},
   "fr":{"name":"Barrage de Nechranice","description":"Un barrage sur l''Ohře doté de la plus longue digue en remblai d''Europe centrale ; un vaste plan d''eau au calme."},
   "uk":{"name":"Нехраницьке водосховище","description":"Гребля на Огрже з найдовшою насипною дамбою Центральної Європи; широке плесо на спокійному північному заході Чехії."}}'::jsonb),

('water', 'Vodní nádrž Rozkoš',
 '„České moře" u České Skalice — rozlehlá vodní plocha s výhledy na Krkonoše na obzoru.',
 50.3790, 16.0930, 'CZ', 'curated-batch2', 103,
 '{"en":{"name":"Rozkoš Reservoir","description":"The Czech Sea near Česká Skalice — a vast water surface with the Giant Mountains on the horizon."},
   "de":{"name":"Stausee Rozkoš","description":"Das Böhmische Meer bei Česká Skalice — eine weite Wasserfläche mit dem Riesengebirge am Horizont."},
   "pl":{"name":"Zbiornik Rozkoš","description":"Czeskie morze koło Czeskiej Skalicy — rozległa tafla wody z Karkonoszami na horyzoncie."},
   "nl":{"name":"Stuwmeer Rozkoš","description":"De Tsjechische zee bij Česká Skalice — een uitgestrekt wateroppervlak met het Reuzengebergte aan de horizon."},
   "es":{"name":"Embalse de Rozkoš","description":"El mar checo junto a Česká Skalice: una vasta lámina de agua con los Montes Gigantes en el horizonte."},
   "fr":{"name":"Lac de Rozkoš","description":"La mer tchèque près de Česká Skalice — un vaste plan d''eau avec les monts des Géants à l''horizon."},
   "uk":{"name":"Водосховище Розкош","description":"Чеське море біля Ческої Скалиці — широке плесо з Крконошами на обрії."}}'::jsonb),

('water', 'Sečská přehrada',
 'Přehrada v Železných horách se zříceninou hradu Oheb nad hrází; oblíbený okruh Železnými horami.',
 49.8250, 15.6570, 'CZ', 'curated-batch2', 104,
 '{"en":{"name":"Seč Reservoir","description":"A dam in the Iron Mountains with the Oheb castle ruin above; a favourite loop through the Železné hory."},
   "de":{"name":"Stausee Seč","description":"Ein Stausee im Eisengebirge mit der Burgruine Oheb darüber; eine beliebte Runde durch die Železné hory."},
   "pl":{"name":"Zbiornik Seč","description":"Zapora w Żelaznych Górach z ruiną zamku Oheb powyżej; ulubiona pętla przez Železné hory."},
   "nl":{"name":"Stuwmeer Seč","description":"Een stuwmeer in het IJzergebergte met de burchtruïne Oheb erboven; een geliefde lus door de Železné hory."},
   "es":{"name":"Embalse de Seč","description":"Una presa en las Montañas de Hierro con la ruina del castillo Oheb encima; un circuito favorito."},
   "fr":{"name":"Barrage de Seč","description":"Un barrage dans les monts de Fer avec la ruine du château d''Oheb au-dessus ; une boucle appréciée."},
   "uk":{"name":"Сечське водосховище","description":"Гребля в Залізних горах із руїною замку Огеб над нею; улюблене коло Залізними горами."}}'::jsonb),

('water', 'Dalešická přehrada',
 'Hluboký kaňon Jihlavy s nejvyšší sypanou hrází v Česku; vyhlídky Wilsonka a stezky nad hladinou.',
 49.1130, 16.1150, 'CZ', 'curated-batch2', 105,
 '{"en":{"name":"Dalešice Reservoir","description":"A deep canyon of the Jihlava with Czechia''s tallest earth-fill dam; viewpoints and trails above the water."},
   "de":{"name":"Stausee Dalešice","description":"Ein tiefer Canyon der Jihlava mit dem höchsten Schüttdamm Tschechiens; Aussichtspunkte und Wege über dem Wasser."},
   "pl":{"name":"Zbiornik Dalešice","description":"Głęboki kanion Jihlavy z najwyższą zaporą ziemną w Czechach; punkty widokowe i ścieżki nad wodą."},
   "nl":{"name":"Stuwmeer Dalešice","description":"Een diepe canyon van de Jihlava met de hoogste aarden dam van Tsjechië; uitzichtpunten en paden boven het water."},
   "es":{"name":"Embalse de Dalešice","description":"Un cañón profundo del Jihlava con la presa de tierra más alta de Chequia; miradores y senderos sobre el agua."},
   "fr":{"name":"Barrage de Dalešice","description":"Un canyon profond de la Jihlava avec le plus haut barrage en remblai de Tchéquie ; belvédères et sentiers."},
   "uk":{"name":"Далешицьке водосховище","description":"Глибокий каньйон Їглави з найвищою насипною греблею Чехії; оглядові точки та стежки над водою."}}'::jsonb),

('water', 'Vodní dílo Nové Mlýny',
 'Trojice nádrží pod Pálavou — hladina, vinice a vápencové bradlo Pálavy v jednom výhledu.',
 48.8570, 16.5900, 'CZ', 'curated-batch2', 106,
 '{"en":{"name":"Nové Mlýny Reservoirs","description":"Three reservoirs beneath Pálava — water, vineyards and the limestone ridge in a single view."},
   "de":{"name":"Stauseen Nové Mlýny","description":"Drei Stauseen unterhalb der Pollauer Berge — Wasser, Weinberge und der Kalksteinkamm in einem Blick."},
   "pl":{"name":"Zbiorniki Nové Mlýny","description":"Trzy zbiorniki pod Pálavą — woda, winnice i wapienna grań w jednym widoku."},
   "nl":{"name":"Stuwmeren Nové Mlýny","description":"Drie stuwmeren onder de Pálava — water, wijngaarden en de kalkstenen kam in één blik."},
   "es":{"name":"Embalses de Nové Mlýny","description":"Tres embalses bajo Pálava: agua, viñedos y la cresta caliza en una sola vista."},
   "fr":{"name":"Réservoirs de Nové Mlýny","description":"Trois retenues sous la Pálava — eau, vignobles et crête calcaire dans un même panorama."},
   "uk":{"name":"Водосховища Нове Млини","description":"Три водойми під Палавою — вода, виноградники та вапняковий хребет в одному краєвиді."}}'::jsonb),

('water', 'Liptovská Mara',
 'Největší slovenská přehrada pod Západními Tatrami; panorama štítů nad hladinou po celém obvodu.',
 49.1000, 19.5200, 'SK', 'curated-batch2', 107,
 '{"en":{"name":"Liptovská Mara","description":"Slovakia''s largest reservoir beneath the Western Tatras; a panorama of peaks above the water all around."},
   "de":{"name":"Liptovská Mara","description":"Der größte Stausee der Slowakei unter der Westtatra; ringsum ein Panorama der Gipfel über dem Wasser."},
   "pl":{"name":"Liptovská Mara","description":"Największy słowacki zbiornik pod Tatrami Zachodnimi; panorama szczytów nad wodą dookoła."},
   "nl":{"name":"Liptovská Mara","description":"Het grootste stuwmeer van Slowakije onder de Westelijke Tatra; rondom een panorama van toppen boven het water."},
   "es":{"name":"Liptovská Mara","description":"El mayor embalse de Eslovaquia bajo los Tatras Occidentales; panorama de cumbres sobre el agua."},
   "fr":{"name":"Liptovská Mara","description":"Le plus grand réservoir de Slovaquie sous les Tatras occidentales ; panorama de sommets tout autour."},
   "uk":{"name":"Ліптовська Мара","description":"Найбільше водосховище Словаччини під Західними Татрами; панорама вершин над водою довкола."}}'::jsonb),

('water', 'Zemplínska šírava',
 '„Slovenské moře" na východě země — rozlehlá teplá nádrž s plážemi pod Vihorlatem.',
 48.7900, 21.9500, 'SK', 'curated-batch2', 108,
 '{"en":{"name":"Zemplínska šírava","description":"The Slovak Sea in the country''s east — a vast warm reservoir with beaches beneath Vihorlat."},
   "de":{"name":"Zemplínska šírava","description":"Das Slowakische Meer im Osten des Landes — ein weiter, warmer Stausee mit Stränden unter dem Vihorlat."},
   "pl":{"name":"Zemplínska šírava","description":"Słowackie morze na wschodzie kraju — rozległy ciepły zbiornik z plażami pod Vihorlatem."},
   "nl":{"name":"Zemplínska šírava","description":"De Slowaakse zee in het oosten van het land — een groot warm stuwmeer met stranden onder de Vihorlat."},
   "es":{"name":"Zemplínska šírava","description":"El mar eslovaco en el este del país: un vasto embalse cálido con playas bajo el Vihorlat."},
   "fr":{"name":"Zemplínska šírava","description":"La mer slovaque à l''est du pays — un vaste réservoir chaud avec plages sous le Vihorlat."},
   "uk":{"name":"Земплінська Ширава","description":"Словацьке море на сході країни — велика тепла водойма з пляжами під Вигорлатом."}}'::jsonb),

('water', 'Štrbské pleso',
 'Ikonické tatranské pleso s promenádou a výhledy na štíty Vysokých Tater; symbol slovenských hor.',
 49.1200, 20.0580, 'SK', 'curated-batch2', 109,
 '{"en":{"name":"Štrbské pleso","description":"The iconic Tatra lake with a promenade and views of the High Tatras peaks; a symbol of Slovak mountains."},
   "de":{"name":"Štrbské pleso (Tschirmer See)","description":"Der ikonische Tatrasee mit Promenade und Blick auf die Gipfel der Hohen Tatra; ein Symbol der slowakischen Berge."},
   "pl":{"name":"Szczyrbskie Jezioro","description":"Kultowe tatrzańskie jezioro z promenadą i widokiem na szczyty Tatr Wysokich; symbol słowackich gór."},
   "nl":{"name":"Štrbské pleso","description":"Het iconische Tatrameer met promenade en zicht op de toppen van de Hoge Tatra; symbool van de Slowaakse bergen."},
   "es":{"name":"Štrbské pleso","description":"El icónico lago de los Tatras con paseo y vistas a las cumbres de los Altos Tatras; símbolo de las montañas eslovacas."},
   "fr":{"name":"Štrbské pleso","description":"Le lac emblématique des Tatras avec promenade et vue sur les sommets des Hautes Tatras ; symbole des montagnes slovaques."},
   "uk":{"name":"Штрбске плесо","description":"Культове татранське озеро з променадою та краєвидами на вершини Високих Татр; символ словацьких гір."}}'::jsonb),

('water', 'Jezioro Śniardwy',
 'Největší polské jezero v srdci Mazur; nekonečná hladina a přístavy mazurské jezerní krajiny.',
 53.7500, 21.7300, 'PL', 'curated-batch2', 110,
 '{"en":{"name":"Lake Śniardwy","description":"Poland''s largest lake in the heart of Masuria; endless waters and harbours of the lakeland."},
   "de":{"name":"Spirdingsee (Śniardwy)","description":"Polens größter See im Herzen Masurens; endlose Wasserfläche und Häfen der Seenlandschaft."},
   "pl":{"name":"Jezioro Śniardwy","description":"Największe polskie jezioro w sercu Mazur; bezkresna tafla i porty krainy jezior."},
   "nl":{"name":"Śniardwy-meer","description":"Het grootste meer van Polen in het hart van Mazurië; eindeloos water en havens van het merenland."},
   "es":{"name":"Lago Śniardwy","description":"El mayor lago de Polonia en el corazón de Masuria; aguas infinitas y puertos de la región de los lagos."},
   "fr":{"name":"Lac Śniardwy","description":"Le plus grand lac de Pologne au cœur de la Mazurie ; eaux infinies et ports du pays des lacs."},
   "uk":{"name":"Озеро Снярдви","description":"Найбільше озеро Польщі в серці Мазур; безкрає плесо та гавані озерного краю."}}'::jsonb),

('water', 'Jezioro Czorsztyńskie',
 'Přehradní jezero v Pieninách mezi hrady Czorsztyn a Niedzica; jedna z nejmalebnějších vodních ploch Polska.',
 49.4130, 20.3200, 'PL', 'curated-batch2', 111,
 '{"en":{"name":"Lake Czorsztyn","description":"A reservoir in the Pieniny between Czorsztyn and Niedzica castles; one of Poland''s most picturesque waters."},
   "de":{"name":"Czorsztyn-Stausee","description":"Ein Stausee in den Pieninen zwischen den Burgen Czorsztyn und Niedzica; eines der malerischsten Gewässer Polens."},
   "pl":{"name":"Jezioro Czorsztyńskie","description":"Zbiornik w Pieninach między zamkami w Czorsztynie i Niedzicy; jedna z najbardziej malowniczych wód Polski."},
   "nl":{"name":"Czorsztyn-meer","description":"Een stuwmeer in de Pieniny tussen de kastelen Czorsztyn en Niedzica; een van de schilderachtigste wateren van Polen."},
   "es":{"name":"Lago Czorsztyn","description":"Un embalse en los Pieninos entre los castillos de Czorsztyn y Niedzica; una de las aguas más pintorescas de Polonia."},
   "fr":{"name":"Lac de Czorsztyn","description":"Un lac de barrage dans les Piénines entre les châteaux de Czorsztyn et Niedzica ; l''un des plans d''eau les plus pittoresques de Pologne."},
   "uk":{"name":"Чорштинське озеро","description":"Водосховище в Пенінах між замками Чорштин і Недзиця; одне з наймальовничіших плес Польщі."}}'::jsonb),

('water', 'Wörthersee',
 'Nejteplejší alpské jezero Korutan s tyrkysovou vodou a promenádami; ráj vyjížděk jižního Rakouska.',
 46.6260, 14.1550, 'AT', 'curated-batch2', 112,
 '{"en":{"name":"Wörthersee","description":"Carinthia''s warmest Alpine lake with turquoise water and promenades; a riding paradise of southern Austria."},
   "de":{"name":"Wörthersee","description":"Kärntens wärmster Alpensee mit türkisem Wasser und Promenaden; ein Ausfahrtsparadies Südösterreichs."},
   "pl":{"name":"Wörthersee","description":"Najcieplejsze alpejskie jezioro Karyntii z turkusową wodą i promenadami; raj przejażdżek południowej Austrii."},
   "nl":{"name":"Wörthersee","description":"Het warmste Alpenmeer van Karinthië met turquoise water en promenades; een ritparadijs in Zuid-Oostenrijk."},
   "es":{"name":"Wörthersee","description":"El lago alpino más cálido de Carintia, de aguas turquesa y paseos; un paraíso para rutas del sur de Austria."},
   "fr":{"name":"Wörthersee","description":"Le lac alpin le plus chaud de Carinthie, aux eaux turquoise et promenades ; paradis des virées du sud de l''Autriche."},
   "uk":{"name":"Вертерзе","description":"Найтепліше альпійське озеро Каринтії з бірюзовою водою та променадами; рай для поїздок півднем Австрії."}}'::jsonb),

('water', 'Achensee',
 'Tyrolský fjord mezi pohořími Karwendel a Rofan; horská silnice podél břehu patří k nejhezčím v Tyrolsku.',
 47.4400, 11.7100, 'AT', 'curated-batch2', 113,
 '{"en":{"name":"Achensee","description":"The Tyrolean fjord between the Karwendel and Rofan ranges; the shoreline road is among Tyrol''s finest."},
   "de":{"name":"Achensee","description":"Der Tiroler Fjord zwischen Karwendel und Rofan; die Uferstraße zählt zu den schönsten Tirols."},
   "pl":{"name":"Achensee","description":"Tyrolski fiord między masywami Karwendel i Rofan; droga wzdłuż brzegu należy do najpiękniejszych w Tyrolu."},
   "nl":{"name":"Achensee","description":"De Tiroolse fjord tussen Karwendel en Rofan; de oeverweg behoort tot de mooiste van Tirol."},
   "es":{"name":"Achensee","description":"El fiordo tirolés entre Karwendel y Rofan; la carretera de la orilla es de las más bellas del Tirol."},
   "fr":{"name":"Achensee","description":"Le fjord tyrolien entre le Karwendel et le Rofan ; la route du rivage compte parmi les plus belles du Tyrol."},
   "uk":{"name":"Ахензе","description":"Тірольський фіорд між масивами Карвендель і Рофан; дорога вздовж берега — одна з найгарніших у Тіролі."}}'::jsonb),

('water', 'Neusiedler See',
 'Stepní jezero na hranici s Maďarskem, obklopené vinicemi a rákosím; UNESCO krajina Burgenlandu.',
 47.8500, 16.7700, 'AT', 'curated-batch2', 114,
 '{"en":{"name":"Lake Neusiedl","description":"A steppe lake on the Hungarian border ringed by vineyards and reeds; the UNESCO landscape of Burgenland."},
   "de":{"name":"Neusiedler See","description":"Ein Steppensee an der ungarischen Grenze, umgeben von Weingärten und Schilf; die UNESCO-Landschaft des Burgenlands."},
   "pl":{"name":"Jezioro Nezyderskie","description":"Stepowe jezioro na granicy z Węgrami, otoczone winnicami i trzcinami; krajobraz UNESCO Burgenlandu."},
   "nl":{"name":"Neusiedler See","description":"Een steppemeer aan de Hongaarse grens, omringd door wijngaarden en riet; het UNESCO-landschap van Burgenland."},
   "es":{"name":"Lago Neusiedl","description":"Un lago estepario en la frontera húngara, rodeado de viñedos y cañaverales; paisaje UNESCO de Burgenland."},
   "fr":{"name":"Lac de Neusiedl","description":"Un lac de steppe à la frontière hongroise, entouré de vignes et de roseaux ; paysage UNESCO du Burgenland."},
   "uk":{"name":"Нойзідлер-Зе","description":"Степове озеро на кордоні з Угорщиною серед виноградників і очерету; ландшафт ЮНЕСКО Бургенланду."}}'::jsonb),

-- == HRADY A ZAMKY =================================================
('castle', 'Hrad Pernštejn',
 'Nedobytný mramorový hrad nad Svratkou, jeden z nejzachovalejších gotických hradů Evropy.',
 49.4510, 16.3180, 'CZ', 'curated-batch2', 120,
 '{"en":{"name":"Pernštejn Castle","description":"The impregnable marble castle above the Svratka, one of Europe''s best-preserved Gothic castles."},
   "de":{"name":"Burg Pernstein","description":"Die uneinnehmbare Marmorburg über der Svratka, eine der besterhaltenen gotischen Burgen Europas."},
   "pl":{"name":"Zamek Pernštejn","description":"Niezdobyty marmurowy zamek nad Svratką, jeden z najlepiej zachowanych gotyckich zamków Europy."},
   "nl":{"name":"Burcht Pernštejn","description":"De onneembare marmeren burcht boven de Svratka, een van de best bewaarde gotische burchten van Europa."},
   "es":{"name":"Castillo de Pernštejn","description":"El inexpugnable castillo de mármol sobre el Svratka, uno de los castillos góticos mejor conservados de Europa."},
   "fr":{"name":"Château de Pernštejn","description":"Le château de marbre imprenable au-dessus de la Svratka, l''un des châteaux gothiques les mieux conservés d''Europe."},
   "uk":{"name":"Замок Пернштейн","description":"Неприступний мармуровий замок над Свраткою, один із найкраще збережених готичних замків Європи."}}'::jsonb),

('castle', 'Hrad Křivoklát',
 'Královský lovecký hrad v hlubokých křivoklátských lesích; gotická kaple patří k nejcennějším v zemi.',
 50.0380, 13.8720, 'CZ', 'curated-batch2', 121,
 '{"en":{"name":"Křivoklát Castle","description":"A royal hunting castle deep in the Křivoklát forests; its Gothic chapel is among the country''s finest."},
   "de":{"name":"Burg Pürglitz (Křivoklát)","description":"Eine königliche Jagdburg tief in den Wäldern von Křivoklát; die gotische Kapelle zählt zu den wertvollsten des Landes."},
   "pl":{"name":"Zamek Křivoklát","description":"Królewski zamek myśliwski w głębi křivoklátských lasów; gotycka kaplica należy do najcenniejszych w kraju."},
   "nl":{"name":"Burcht Křivoklát","description":"Een koninklijke jachtburcht diep in de bossen van Křivoklát; de gotische kapel behoort tot de mooiste van het land."},
   "es":{"name":"Castillo de Křivoklát","description":"Un castillo real de caza en lo profundo de los bosques de Křivoklát; su capilla gótica es de las más valiosas del país."},
   "fr":{"name":"Château de Křivoklát","description":"Un château royal de chasse au cœur des forêts de Křivoklát ; sa chapelle gothique compte parmi les plus précieuses du pays."},
   "uk":{"name":"Замок Крживоклат","description":"Королівський мисливський замок у глибині крживоклатських лісів; готична каплиця — одна з найцінніших у країні."}}'::jsonb),

('castle', 'Hrad Kost',
 'Gotický hrad v Českém ráji, který nikdy nebyl dobyt; tyčí se na pískovcovém ostrohu mezi rybníky.',
 50.4900, 15.1350, 'CZ', 'curated-batch2', 122,
 '{"en":{"name":"Kost Castle","description":"A Gothic castle in Bohemian Paradise that was never conquered; it rises on a sandstone spur between ponds."},
   "de":{"name":"Burg Kost","description":"Eine gotische Burg im Böhmischen Paradies, die nie erobert wurde; sie erhebt sich auf einem Sandsteinsporn zwischen Teichen."},
   "pl":{"name":"Zamek Kost","description":"Gotycki zamek w Czeskim Raju, nigdy nie zdobyty; wznosi się na piaskowcowym cyplu między stawami."},
   "nl":{"name":"Burcht Kost","description":"Een gotische burcht in het Boheems Paradijs die nooit werd veroverd; hij rijst op een zandstenen uitloper tussen vijvers."},
   "es":{"name":"Castillo de Kost","description":"Un castillo gótico del Paraíso Bohemio que nunca fue conquistado; se alza sobre un espolón de arenisca entre estanques."},
   "fr":{"name":"Château de Kost","description":"Un château gothique du Paradis tchèque jamais conquis ; il se dresse sur un éperon de grès entre des étangs."},
   "uk":{"name":"Замок Кост","description":"Готичний замок у Чеському раю, який ніколи не був завойований; височіє на пісковиковому мисі між ставками."}}'::jsonb),

('castle', 'Hrad Trosky',
 'Dvojice čedičových věží Baba a Panna — nezaměnitelná silueta a symbol Českého ráje.',
 50.5160, 15.2300, 'CZ', 'curated-batch2', 123,
 '{"en":{"name":"Trosky Castle","description":"The twin basalt towers Baba and Panna — the unmistakable silhouette and symbol of Bohemian Paradise."},
   "de":{"name":"Burg Trosky","description":"Die Basalt-Zwillingstürme Baba und Panna — die unverwechselbare Silhouette und das Symbol des Böhmischen Paradieses."},
   "pl":{"name":"Zamek Trosky","description":"Bliźniacze bazaltowe wieże Baba i Panna — niepowtarzalna sylwetka i symbol Czeskiego Raju."},
   "nl":{"name":"Burcht Trosky","description":"De basalten tweelingtorens Baba en Panna — het onmiskenbare silhouet en symbool van het Boheems Paradijs."},
   "es":{"name":"Castillo de Trosky","description":"Las torres gemelas de basalto Baba y Panna: la silueta inconfundible y símbolo del Paraíso Bohemio."},
   "fr":{"name":"Château de Trosky","description":"Les tours jumelles de basalte Baba et Panna — la silhouette immanquable et symbole du Paradis tchèque."},
   "uk":{"name":"Замок Троски","description":"Дві базальтові вежі Баба та Панна — незабутній силует і символ Чеського раю."}}'::jsonb),

('castle', 'Hrad Bezděz',
 'Přemyslovský královský hrad na výrazném vrchu nad Máchovým krajem; výstup odmění dalekým výhledem.',
 50.5390, 14.7230, 'CZ', 'curated-batch2', 124,
 '{"en":{"name":"Bezděz Castle","description":"A Přemyslid royal castle on a prominent hill above Mácha country; the climb rewards with far-reaching views."},
   "de":{"name":"Burg Bösig (Bezděz)","description":"Eine königliche Přemysliden-Burg auf markantem Hügel über dem Mácha-Land; der Aufstieg belohnt mit weiten Ausblicken."},
   "pl":{"name":"Zamek Bezděz","description":"Królewski zamek Przemyślidów na wyrazistym wzgórzu nad krajem Machy; wspinaczka nagradza dalekimi widokami."},
   "nl":{"name":"Burcht Bezděz","description":"Een koninklijke Přemysliden-burcht op een markante heuvel boven het Mácha-land; de klim beloont met verre uitzichten."},
   "es":{"name":"Castillo de Bezděz","description":"Un castillo real premislida sobre una colina prominente; la subida recompensa con amplias vistas."},
   "fr":{"name":"Château de Bezděz","description":"Un château royal přemyslide sur une colline marquante ; la montée récompense par de vastes panoramas."},
   "uk":{"name":"Замок Бездєз","description":"Королівський замок Пржемисловичів на помітному пагорбі над Маховим краєм; підйом винагороджує далекими краєвидами."}}'::jsonb),

('castle', 'Hrad Loket',
 'Kamenný hrad v meandru Ohře obepnutý středověkým městečkem; kulisa jak z filmu — a taky v něm hrála.',
 50.1860, 12.7540, 'CZ', 'curated-batch2', 125,
 '{"en":{"name":"Loket Castle","description":"A stone castle in a meander of the Ohře wrapped by a medieval town; a film-set scenery — it actually starred in one."},
   "de":{"name":"Burg Elbogen (Loket)","description":"Eine steinerne Burg in einer Egerschleife, umschlossen von einem mittelalterlichen Städtchen; eine Filmkulisse — sie spielte tatsächlich mit."},
   "pl":{"name":"Zamek Loket","description":"Kamienny zamek w meandrze Ohrzy otoczony średniowiecznym miasteczkiem; sceneria jak z filmu — i faktycznie w nim zagrała."},
   "nl":{"name":"Burcht Loket","description":"Een stenen burcht in een meander van de Ohře, omsloten door een middeleeuws stadje; filmdecor — en speelde er echt in mee."},
   "es":{"name":"Castillo de Loket","description":"Un castillo de piedra en un meandro del Ohře rodeado de un pueblo medieval; escenario de película, y de hecho salió en una."},
   "fr":{"name":"Château de Loket","description":"Un château de pierre dans un méandre de l''Ohře, enserré par une ville médiévale ; un décor de cinéma — il a d''ailleurs joué dans un film."},
   "uk":{"name":"Замок Локет","description":"Кам''яний замок у меандрі Огрже в обіймах середньовічного містечка; кінодекорація — і справді знімався у фільмі."}}'::jsonb),

('castle', 'Zámek Konopiště',
 'Romantické sídlo následníka trůnu Františka Ferdinanda d''Este s růžovou zahradou a trofejemi.',
 49.7800, 14.6570, 'CZ', 'curated-batch2', 126,
 '{"en":{"name":"Konopiště Chateau","description":"The romantic residence of heir apparent Franz Ferdinand d''Este with a rose garden and hunting trophies."},
   "de":{"name":"Schloss Konopischt","description":"Der romantische Sitz des Thronfolgers Franz Ferdinand d''Este mit Rosengarten und Jagdtrophäen."},
   "pl":{"name":"Zamek Konopiště","description":"Romantyczna rezydencja następcy tronu Franciszka Ferdynanda d''Este z ogrodem różanym i trofeami."},
   "nl":{"name":"Kasteel Konopiště","description":"De romantische residentie van troonopvolger Franz Ferdinand d''Este met rozentuin en jachttrofeeën."},
   "es":{"name":"Castillo de Konopiště","description":"La residencia romántica del heredero Francisco Fernando de Este, con rosaleda y trofeos de caza."},
   "fr":{"name":"Château de Konopiště","description":"La résidence romantique de l''archiduc François-Ferdinand d''Este, avec roseraie et trophées de chasse."},
   "uk":{"name":"Замок Конопіште","description":"Романтична резиденція спадкоємця трону Франца Фердинанда д''Есте з трояндовим садом і трофеями."}}'::jsonb),

('castle', 'Zámek Český Krumlov',
 'Rozsáhlý areál nad meandrem Vltavy s barokní věží a otáčivým hledištěm; perla UNESCO jižních Čech.',
 48.8130, 14.3150, 'CZ', 'curated-batch2', 127,
 '{"en":{"name":"Český Krumlov Castle","description":"A vast complex above a Vltava meander with a Baroque tower and revolving auditorium; South Bohemia''s UNESCO pearl."},
   "de":{"name":"Schloss Krumau","description":"Ein weitläufiger Komplex über einer Moldauschleife mit Barockturm und Drehbühne; die UNESCO-Perle Südböhmens."},
   "pl":{"name":"Zamek Český Krumlov","description":"Rozległy kompleks nad meandrem Wełtawy z barokową wieżą i obrotową widownią; perła UNESCO południowych Czech."},
   "nl":{"name":"Kasteel Český Krumlov","description":"Een uitgestrekt complex boven een Moldau-meander met barokke toren en draaiend theater; de UNESCO-parel van Zuid-Bohemen."},
   "es":{"name":"Castillo de Český Krumlov","description":"Un vasto complejo sobre un meandro del Moldava con torre barroca y auditorio giratorio; perla UNESCO de Bohemia del Sur."},
   "fr":{"name":"Château de Český Krumlov","description":"Un vaste ensemble au-dessus d''un méandre de la Vltava, avec tour baroque et théâtre tournant ; perle UNESCO de la Bohême du Sud."},
   "uk":{"name":"Замок Чеський Крумлов","description":"Великий комплекс над меандром Влтави з бароковою вежею та обертовою глядацькою залою; перлина ЮНЕСКО Південної Богемії."}}'::jsonb),

('castle', 'Zámek Lednice',
 'Novogotický zámek s palmovým skleníkem a minaretem v Lednicko-valtickém areálu UNESCO.',
 48.8020, 16.8060, 'CZ', 'curated-batch2', 128,
 '{"en":{"name":"Lednice Chateau","description":"A neo-Gothic chateau with a palm greenhouse and minaret in the UNESCO Lednice-Valtice landscape."},
   "de":{"name":"Schloss Eisgrub (Lednice)","description":"Ein neugotisches Schloss mit Palmenhaus und Minarett in der UNESCO-Kulturlandschaft Lednice-Valtice."},
   "pl":{"name":"Zamek Lednice","description":"Neogotycki pałac z palmiarnią i minaretem w krajobrazie UNESCO Lednice-Valtice."},
   "nl":{"name":"Kasteel Lednice","description":"Een neogotisch kasteel met palmenkas en minaret in het UNESCO-landschap Lednice-Valtice."},
   "es":{"name":"Castillo de Lednice","description":"Un palacio neogótico con invernadero de palmeras y minarete en el paisaje UNESCO de Lednice-Valtice."},
   "fr":{"name":"Château de Lednice","description":"Un château néogothique avec serre aux palmiers et minaret dans le paysage UNESCO de Lednice-Valtice."},
   "uk":{"name":"Замок Леднице","description":"Неоготичний замок з пальмовою оранжереєю та мінаретом у ландшафті ЮНЕСКО Леднице-Валтице."}}'::jsonb),

('castle', 'Spišský hrad',
 'Jeden z největších hradních areálů střední Evropy na travertinové kupě; památka UNESCO nad Spiší.',
 48.9990, 20.7680, 'SK', 'curated-batch2', 129,
 '{"en":{"name":"Spiš Castle","description":"One of Central Europe''s largest castle complexes on a travertine mound; a UNESCO site above the Spiš region."},
   "de":{"name":"Zipser Burg","description":"Eine der größten Burganlagen Mitteleuropas auf einem Travertinhügel; UNESCO-Welterbe über der Zips."},
   "pl":{"name":"Zamek Spiski","description":"Jeden z największych kompleksów zamkowych Europy Środkowej na trawertynowym wzgórzu; obiekt UNESCO nad Spiszem."},
   "nl":{"name":"Kasteel Spiš","description":"Een van de grootste burchtcomplexen van Midden-Europa op een travertijnheuvel; UNESCO-erfgoed boven de Spiš."},
   "es":{"name":"Castillo de Spiš","description":"Uno de los mayores complejos de castillos de Europa Central sobre un montículo de travertino; sitio UNESCO."},
   "fr":{"name":"Château de Spiš","description":"L''un des plus grands ensembles castraux d''Europe centrale sur une butte de travertin ; site UNESCO au-dessus du Spiš."},
   "uk":{"name":"Спішський град","description":"Один із найбільших замкових комплексів Центральної Європи на травертиновому пагорбі; об''єкт ЮНЕСКО над Спішем."}}'::jsonb),

('castle', 'Oravský hrad',
 '„Orlí hnízdo" na skále 112 metrů nad řekou Oravou; jeden z nejpůsobivějších hradů Slovenska.',
 49.2610, 19.3580, 'SK', 'curated-batch2', 130,
 '{"en":{"name":"Orava Castle","description":"An eagle''s nest on a cliff 112 metres above the Orava river; one of Slovakia''s most striking castles."},
   "de":{"name":"Arwaburg (Orava)","description":"Ein Adlerhorst auf einem Felsen 112 Meter über der Orava; eine der eindrucksvollsten Burgen der Slowakei."},
   "pl":{"name":"Zamek Orawski","description":"Orle gniazdo na skale 112 metrów nad Orawą; jeden z najbardziej imponujących zamków Słowacji."},
   "nl":{"name":"Burcht Orava","description":"Een adelaarsnest op een rots 112 meter boven de Orava; een van de indrukwekkendste burchten van Slowakije."},
   "es":{"name":"Castillo de Orava","description":"Un nido de águila sobre una roca a 112 metros del río Orava; uno de los castillos más impresionantes de Eslovaquia."},
   "fr":{"name":"Château d''Orava","description":"Un nid d''aigle sur un rocher à 112 mètres au-dessus de l''Orava ; l''un des châteaux les plus spectaculaires de Slovaquie."},
   "uk":{"name":"Оравський замок","description":"Орлине гніздо на скелі 112 метрів над річкою Оравою; один із найвражаючіших замків Словаччини."}}'::jsonb),

('castle', 'Trenčiansky hrad',
 'Mohutný hrad Matúše Čáka nad Váhem s legendární Studní lásky; dominanta Považí.',
 48.8940, 18.0440, 'SK', 'curated-batch2', 131,
 '{"en":{"name":"Trenčín Castle","description":"The mighty castle of Matúš Čák above the Váh with the legendary Well of Love; the landmark of the Váh valley."},
   "de":{"name":"Burg Trentschin","description":"Die mächtige Burg des Matúš Čák über der Waag mit dem legendären Brunnen der Liebe; das Wahrzeichen des Waagtals."},
   "pl":{"name":"Zamek w Trenczynie","description":"Potężny zamek Matúša Čáka nad Wagiem z legendarną Studnią Miłości; dominanta doliny Wagu."},
   "nl":{"name":"Kasteel Trenčín","description":"De machtige burcht van Matúš Čák boven de Váh met de legendarische Liefdesput; hét herkenningspunt van de Váh-vallei."},
   "es":{"name":"Castillo de Trenčín","description":"El poderoso castillo de Matúš Čák sobre el Váh con el legendario Pozo del Amor; hito del valle del Váh."},
   "fr":{"name":"Château de Trenčín","description":"Le puissant château de Matúš Čák au-dessus du Váh avec le légendaire puits de l''Amour ; emblème de la vallée du Váh."},
   "uk":{"name":"Тренчинський замок","description":"Могутній замок Матуша Чака над Вагом з легендарною Криницею кохання; домінанта Поважжя."}}'::jsonb),

('castle', 'Wawel',
 'Královský hrad a katedrála na návrší nad Vislou — srdce polské historie v Krakově.',
 50.0540, 19.9350, 'PL', 'curated-batch2', 132,
 '{"en":{"name":"Wawel","description":"The royal castle and cathedral on a hill above the Vistula — the heart of Polish history in Kraków."},
   "de":{"name":"Wawel","description":"Königsschloss und Kathedrale auf dem Hügel über der Weichsel — das Herz der polnischen Geschichte in Krakau."},
   "pl":{"name":"Wawel","description":"Zamek królewski i katedra na wzgórzu nad Wisłą — serce polskiej historii w Krakowie."},
   "nl":{"name":"Wawel","description":"Het koninklijk kasteel en de kathedraal op de heuvel boven de Wisła — het hart van de Poolse geschiedenis in Krakau."},
   "es":{"name":"Wawel","description":"El castillo real y la catedral sobre el Vístula: el corazón de la historia polaca en Cracovia."},
   "fr":{"name":"Wawel","description":"Le château royal et la cathédrale sur la colline au-dessus de la Vistule — le cœur de l''histoire polonaise à Cracovie."},
   "uk":{"name":"Вавель","description":"Королівський замок і собор на пагорбі над Віслою — серце польської історії в Кракові."}}'::jsonb),

('castle', 'Zamek Książ',
 'Třetí největší polský zámek na skále nad hlubokým údolím; tajemné podzemí z druhé světové války.',
 50.8420, 16.2900, 'PL', 'curated-batch2', 133,
 '{"en":{"name":"Książ Castle","description":"Poland''s third-largest castle on a rock above a deep valley; mysterious WWII tunnels below."},
   "de":{"name":"Schloss Fürstenstein (Książ)","description":"Polens drittgrößtes Schloss auf einem Felsen über einem tiefen Tal; geheimnisvolle Stollen aus dem Zweiten Weltkrieg."},
   "pl":{"name":"Zamek Książ","description":"Trzeci co do wielkości zamek Polski na skale nad głęboką doliną; tajemnicze podziemia z II wojny światowej."},
   "nl":{"name":"Kasteel Książ","description":"Het op twee na grootste kasteel van Polen op een rots boven een diep dal; mysterieuze tunnels uit WOII."},
   "es":{"name":"Castillo de Książ","description":"El tercer castillo más grande de Polonia sobre una roca; misteriosos túneles de la Segunda Guerra Mundial."},
   "fr":{"name":"Château de Książ","description":"Le troisième plus grand château de Pologne sur un rocher ; de mystérieux souterrains de la Seconde Guerre mondiale."},
   "uk":{"name":"Замок Ксьонж","description":"Третій за величиною замок Польщі на скелі над глибокою долиною; таємничі підземелля Другої світової."}}'::jsonb),

('castle', 'Burg Hochosterwitz',
 'Hrad na 175 m vysoké skále se 14 branami podél přístupové cesty; korutanská pohádková silueta.',
 46.7550, 14.4520, 'AT', 'curated-batch2', 134,
 '{"en":{"name":"Hochosterwitz Castle","description":"A castle on a 175-metre rock with 14 gates along the approach; Carinthia''s fairy-tale silhouette."},
   "de":{"name":"Burg Hochosterwitz","description":"Eine Burg auf 175 Meter hohem Fels mit 14 Toren am Aufgang; Kärntens Märchensilhouette."},
   "pl":{"name":"Zamek Hochosterwitz","description":"Zamek na 175-metrowej skale z 14 bramami wzdłuż drogi; bajkowa sylwetka Karyntii."},
   "nl":{"name":"Burcht Hochosterwitz","description":"Een burcht op een 175 meter hoge rots met 14 poorten langs de oprit; het sprookjessilhouet van Karinthië."},
   "es":{"name":"Castillo de Hochosterwitz","description":"Un castillo sobre una roca de 175 metros con 14 puertas en el camino; la silueta de cuento de Carintia."},
   "fr":{"name":"Château de Hochosterwitz","description":"Un château sur un rocher de 175 mètres avec 14 portes le long de la montée ; la silhouette féerique de la Carinthie."},
   "uk":{"name":"Замок Гохостервіц","description":"Замок на 175-метровій скелі з 14 брамами вздовж дороги; казковий силует Каринтії."}}'::jsonb),

-- == ROZHLEDNY =====================================================
('lookout', 'Petřínská rozhledna',
 'Pražská „malá Eiffelovka" na Petříně; výhled na celé město i daleké Středohoří.',
 50.0835, 14.3950, 'CZ', 'curated-batch2', 140,
 '{"en":{"name":"Petřín Lookout Tower","description":"Prague''s little Eiffel Tower on Petřín hill; views over the whole city and beyond."},
   "de":{"name":"Aussichtsturm Petřín","description":"Prags kleiner Eiffelturm auf dem Petřín; Blick über die ganze Stadt und weit darüber hinaus."},
   "pl":{"name":"Wieża widokowa na Petřínie","description":"Praska mała wieża Eiffla na wzgórzu Petřín; widok na całe miasto i dalej."},
   "nl":{"name":"Petřín-uitkijktoren","description":"De kleine Eiffeltoren van Praag op de Petřín; uitzicht over de hele stad en verder."},
   "es":{"name":"Torre de Petřín","description":"La pequeña torre Eiffel de Praga en la colina de Petřín; vistas de toda la ciudad y más allá."},
   "fr":{"name":"Tour de Petřín","description":"La petite tour Eiffel de Prague sur la colline de Petřín ; vue sur toute la ville et au-delà."},
   "uk":{"name":"Петршинська вежа","description":"Празька маленька Ейфелева вежа на Петршині; краєвид на все місто й далі."}}'::jsonb),

('lookout', 'Praděd — vysílač a rozhledna',
 'Nejvýše položená stavba Česka na vrcholu Pradědu; vyhlídka nad hřebeny Jeseníků.',
 50.0830, 17.2310, 'CZ', 'curated-batch2', 141,
 '{"en":{"name":"Praděd Tower","description":"Czechia''s highest structure atop Praděd; a lookout above the Jeseníky ridges."},
   "de":{"name":"Sender Praděd (Altvater)","description":"Das höchstgelegene Bauwerk Tschechiens auf dem Altvater; Aussicht über die Kämme des Altvatergebirges."},
   "pl":{"name":"Wieża na Pradziadzie","description":"Najwyżej położona budowla Czech na szczycie Pradziada; widok ponad grzbietami Jesioników."},
   "nl":{"name":"Praděd-toren","description":"Het hoogstgelegen bouwwerk van Tsjechië op de Praděd; uitzicht over de kammen van de Jeseníky."},
   "es":{"name":"Torre de Praděd","description":"La construcción más alta de Chequia en la cima del Praděd; mirador sobre las crestas de los Jeseníky."},
   "fr":{"name":"Tour du Praděd","description":"La construction la plus élevée de Tchéquie au sommet du Praděd ; belvédère au-dessus des crêtes des Jeseníky."},
   "uk":{"name":"Вежа на Прадєді","description":"Найвище розташована споруда Чехії на вершині Прадєда; оглядовий майданчик над хребтами Єсеників."}}'::jsonb),

('lookout', 'Poledník',
 'Rozhledna z bývalé vojenské věže na šumavském vrcholu; kruhový výhled na Šumavu i Alpy.',
 49.0630, 13.3960, 'CZ', 'curated-batch2', 142,
 '{"en":{"name":"Poledník Lookout","description":"A lookout tower converted from a military installation on a Šumava summit; 360° views of Šumava and the Alps."},
   "de":{"name":"Aussichtsturm Poledník (Mittagsberg)","description":"Ein aus einem Militärturm umgebauter Aussichtsturm auf einem Böhmerwaldgipfel; Rundblick auf Šumava und Alpen."},
   "pl":{"name":"Wieża Poledník","description":"Wieża widokowa przebudowana z obiektu wojskowego na szczycie Szumawy; panorama 360° na Szumawę i Alpy."},
   "nl":{"name":"Uitkijktoren Poledník","description":"Een uit een militaire toren verbouwde uitkijktoren op een Šumava-top; 360°-zicht op Šumava en de Alpen."},
   "es":{"name":"Mirador de Poledník","description":"Una torre militar convertida en mirador en una cumbre de Šumava; vistas de 360° de Šumava y los Alpes."},
   "fr":{"name":"Tour du Poledník","description":"Une tour militaire reconvertie en belvédère sur un sommet de la Šumava ; vue à 360° sur la Šumava et les Alpes."},
   "uk":{"name":"Вежа Поледнік","description":"Оглядова вежа, перебудована з військової, на шумавській вершині; круговий огляд Шумави й Альп."}}'::jsonb),

('lookout', 'Donauturm',
 'Věž s vyhlídkou 150 metrů nad Vídní a otáčivou kavárnou; celé město a Dunaj jako na dlani.',
 48.2400, 16.4100, 'AT', 'curated-batch2', 143,
 '{"en":{"name":"Danube Tower","description":"A tower with a viewing deck 150 metres above Vienna and a revolving café; the whole city and the Danube at your feet."},
   "de":{"name":"Donauturm","description":"Ein Turm mit Aussichtsplattform 150 Meter über Wien und Drehcafé; die ganze Stadt und die Donau zu Füßen."},
   "pl":{"name":"Wieża Dunajska","description":"Wieża z tarasem widokowym 150 metrów nad Wiedniem i obrotową kawiarnią; całe miasto i Dunaj jak na dłoni."},
   "nl":{"name":"Donauturm","description":"Een toren met uitzichtplatform 150 meter boven Wenen en draaiend café; de hele stad en de Donau aan je voeten."},
   "es":{"name":"Torre del Danubio","description":"Una torre con mirador a 150 metros sobre Viena y cafetería giratoria; toda la ciudad y el Danubio a tus pies."},
   "fr":{"name":"Tour du Danube","description":"Une tour avec plate-forme à 150 mètres au-dessus de Vienne et café tournant ; toute la ville et le Danube à vos pieds."},
   "uk":{"name":"Дунайська вежа","description":"Вежа з оглядовим майданчиком 150 метрів над Віднем та обертовою кав''ярнею; усе місто й Дунай як на долоні."}}'::jsonb),

-- == PAMATKY =======================================================
('sights', 'Kostnice v Sedlci',
 'Světově proslulá kaple vyzdobená lidskými kostmi u Kutné Hory; památka UNESCO.',
 49.9620, 15.2880, 'CZ', 'curated-batch2', 150,
 '{"en":{"name":"Sedlec Ossuary","description":"The world-famous chapel decorated with human bones near Kutná Hora; a UNESCO site."},
   "de":{"name":"Beinhaus Sedlec","description":"Die weltberühmte, mit menschlichen Knochen geschmückte Kapelle bei Kutná Hora; UNESCO-Welterbe."},
   "pl":{"name":"Kaplica Czaszek w Sedlcu","description":"Słynna na cały świat kaplica ozdobiona ludzkimi kośćmi koło Kutnej Hory; obiekt UNESCO."},
   "nl":{"name":"Ossuarium van Sedlec","description":"De wereldberoemde met mensenbeenderen versierde kapel bij Kutná Hora; UNESCO-erfgoed."},
   "es":{"name":"Osario de Sedlec","description":"La célebre capilla decorada con huesos humanos cerca de Kutná Hora; sitio UNESCO."},
   "fr":{"name":"Ossuaire de Sedlec","description":"La chapelle mondialement célèbre décorée d''ossements humains près de Kutná Hora ; site UNESCO."},
   "uk":{"name":"Костниця в Седлеці","description":"Всесвітньо відома каплиця, прикрашена людськими кістками, біля Кутної Гори; об''єкт ЮНЕСКО."}}'::jsonb),

('sights', 'Poutní kostel na Zelené hoře',
 'Santiniho vrcholné dílo barokní gotiky ve tvaru pěticípé hvězdy u Žďáru nad Sázavou; UNESCO.',
 49.5800, 15.9420, 'CZ', 'curated-batch2', 151,
 '{"en":{"name":"Pilgrimage Church at Zelená hora","description":"Santini''s masterpiece of Baroque Gothic shaped as a five-pointed star near Žďár nad Sázavou; UNESCO."},
   "de":{"name":"Wallfahrtskirche auf Zelená hora","description":"Santinis Meisterwerk der Barockgotik in Form eines fünfzackigen Sterns bei Žďár nad Sázavou; UNESCO."},
   "pl":{"name":"Kościół pielgrzymkowy na Zelenej horze","description":"Arcydzieło barokowego gotyku Santiniego w kształcie pięcioramiennej gwiazdy koło Żdziaru nad Sazawą; UNESCO."},
   "nl":{"name":"Bedevaartkerk op Zelená hora","description":"Santini''s meesterwerk van barokgotiek in de vorm van een vijfpuntige ster bij Žďár nad Sázavou; UNESCO."},
   "es":{"name":"Iglesia de peregrinación de Zelená hora","description":"La obra maestra del gótico barroco de Santini en forma de estrella de cinco puntas; UNESCO."},
   "fr":{"name":"Église de pèlerinage de Zelená hora","description":"Le chef-d''œuvre de gothique baroque de Santini en forme d''étoile à cinq branches ; UNESCO."},
   "uk":{"name":"Паломницький костел на Зеленій горі","description":"Шедевр барокової готики Сантіні у формі п''ятикутної зірки біля Ждяру-над-Сазавою; ЮНЕСКО."}}'::jsonb),

('sights', 'Bazilika Velehrad',
 'Nejvýznamnější moravské poutní místo spjaté s cyrilometodějskou tradicí; monumentální barokní bazilika.',
 49.1050, 17.3940, 'CZ', 'curated-batch2', 152,
 '{"en":{"name":"Velehrad Basilica","description":"Moravia''s foremost pilgrimage site tied to the Cyril and Methodius tradition; a monumental Baroque basilica."},
   "de":{"name":"Basilika Velehrad","description":"Mährens bedeutendster Wallfahrtsort, verbunden mit der kyrillomethodianischen Tradition; eine monumentale Barockbasilika."},
   "pl":{"name":"Bazylika w Velehradzie","description":"Najważniejsze morawskie miejsce pielgrzymkowe związane z tradycją cyrylometodiańską; monumentalna barokowa bazylika."},
   "nl":{"name":"Basiliek van Velehrad","description":"Moravië''s belangrijkste bedevaartsoord, verbonden met de Cyrillus-en-Methodius-traditie; een monumentale barokke basiliek."},
   "es":{"name":"Basílica de Velehrad","description":"El principal lugar de peregrinación de Moravia, ligado a la tradición de Cirilo y Metodio; monumental basílica barroca."},
   "fr":{"name":"Basilique de Velehrad","description":"Le premier lieu de pèlerinage de Moravie, lié à la tradition de Cyrille et Méthode ; une basilique baroque monumentale."},
   "uk":{"name":"Базиліка Велеград","description":"Найважливіше моравське місце паломництва, пов''язане з кирило-мефодіївською традицією; монументальна барокова базиліка."}}'::jsonb),

('sights', 'Jasná Góra',
 'Nejslavnější polské poutní místo s ikonou Černé Madony v Čenstochové; duchovní srdce Polska.',
 50.8150, 19.0970, 'PL', 'curated-batch2', 153,
 '{"en":{"name":"Jasna Góra","description":"Poland''s most famous pilgrimage site with the Black Madonna icon in Częstochowa; the country''s spiritual heart."},
   "de":{"name":"Jasna Góra","description":"Polens berühmtester Wallfahrtsort mit der Ikone der Schwarzen Madonna in Tschenstochau; das geistliche Herz des Landes."},
   "pl":{"name":"Jasna Góra","description":"Najsłynniejsze polskie sanktuarium z ikoną Czarnej Madonny w Częstochowie; duchowe serce Polski."},
   "nl":{"name":"Jasna Góra","description":"Polens beroemdste bedevaartsoord met de icoon van de Zwarte Madonna in Częstochowa; het spirituele hart van het land."},
   "es":{"name":"Jasna Góra","description":"El santuario más famoso de Polonia con el icono de la Virgen Negra en Częstochowa; el corazón espiritual del país."},
   "fr":{"name":"Jasna Góra","description":"Le plus célèbre sanctuaire de Pologne avec l''icône de la Vierge noire à Częstochowa ; le cœur spirituel du pays."},
   "uk":{"name":"Ясна Гура","description":"Найвідоміше польське місце паломництва з іконою Чорної Мадонни в Ченстохові; духовне серце Польщі."}}'::jsonb),

('sights', 'Solný důl Wieliczka',
 'Staletí těžby soli v podzemním labyrintu s kaplemi vytesanými do soli; památka UNESCO u Krakova.',
 49.9830, 20.0540, 'PL', 'curated-batch2', 154,
 '{"en":{"name":"Wieliczka Salt Mine","description":"Centuries of salt mining in an underground labyrinth with chapels carved in salt; a UNESCO site near Kraków."},
   "de":{"name":"Salzbergwerk Wieliczka","description":"Jahrhunderte des Salzabbaus in einem unterirdischen Labyrinth mit in Salz gehauenen Kapellen; UNESCO-Welterbe bei Krakau."},
   "pl":{"name":"Kopalnia soli Wieliczka","description":"Wieki wydobycia soli w podziemnym labiryncie z kaplicami wykutymi w soli; obiekt UNESCO pod Krakowem."},
   "nl":{"name":"Zoutmijn Wieliczka","description":"Eeuwen zoutwinning in een ondergronds labyrint met in zout uitgehouwen kapellen; UNESCO-erfgoed bij Krakau."},
   "es":{"name":"Minas de sal de Wieliczka","description":"Siglos de minería de sal en un laberinto subterráneo con capillas talladas en sal; sitio UNESCO cerca de Cracovia."},
   "fr":{"name":"Mine de sel de Wieliczka","description":"Des siècles d''extraction du sel dans un labyrinthe souterrain aux chapelles taillées dans le sel ; site UNESCO près de Cracovie."},
   "uk":{"name":"Соляна шахта Величка","description":"Століття видобутку солі в підземному лабіринті з каплицями, вирізьбленими в солі; об''єкт ЮНЕСКО біля Кракова."}}'::jsonb),

('sights', 'Bazilika Mariazell',
 'Nejvýznamnější rakouské poutní místo v štýrských horách; cíl poutníků ze střední Evropy po staletí.',
 47.7730, 15.3180, 'AT', 'curated-batch2', 155,
 '{"en":{"name":"Mariazell Basilica","description":"Austria''s foremost pilgrimage site in the Styrian mountains; a goal of Central European pilgrims for centuries."},
   "de":{"name":"Basilika Mariazell","description":"Österreichs bedeutendster Wallfahrtsort in den steirischen Bergen; seit Jahrhunderten Ziel mitteleuropäischer Pilger."},
   "pl":{"name":"Bazylika w Mariazell","description":"Najważniejsze austriackie sanktuarium w górach Styrii; od wieków cel pielgrzymów z Europy Środkowej."},
   "nl":{"name":"Basiliek van Mariazell","description":"Oostenrijks belangrijkste bedevaartsoord in de Stiermarkse bergen; al eeuwen het doel van Midden-Europese pelgrims."},
   "es":{"name":"Basílica de Mariazell","description":"El principal santuario de Austria en las montañas de Estiria; meta de peregrinos centroeuropeos durante siglos."},
   "fr":{"name":"Basilique de Mariazell","description":"Le premier lieu de pèlerinage d''Autriche dans les montagnes styriennes ; but des pèlerins d''Europe centrale depuis des siècles."},
   "uk":{"name":"Базиліка Маріацелль","description":"Найважливіше австрійське місце паломництва в штирійських горах; мета паломників Центральної Європи століттями."}}'::jsonb),

-- == PRIRODA A REZERVACE ===========================================
('nature', 'Propast Macocha',
 'Přes 138 metrů hluboká propast v Moravském krasu s vyhlídkovými můstky; vstup do Punkevních jeskyní.',
 49.3730, 16.7290, 'CZ', 'curated-batch2', 160,
 '{"en":{"name":"Macocha Abyss","description":"A gorge over 138 metres deep in the Moravian Karst with viewing bridges; gateway to the Punkva Caves."},
   "de":{"name":"Macocha-Schlucht","description":"Eine über 138 Meter tiefe Schlucht im Mährischen Karst mit Aussichtsstegen; Zugang zu den Punkva-Höhlen."},
   "pl":{"name":"Przepaść Macocha","description":"Ponad 138-metrowa przepaść w Krasie Morawskim z mostkami widokowymi; wejście do Jaskiń Punkevních."},
   "nl":{"name":"Macocha-kloof","description":"Een ruim 138 meter diepe kloof in de Moravische Karst met uitzichtbruggen; toegang tot de Punkva-grotten."},
   "es":{"name":"Abismo de Macocha","description":"Una sima de más de 138 metros en el Karst Moravo con pasarelas; entrada a las cuevas de Punkva."},
   "fr":{"name":"Gouffre de Macocha","description":"Un gouffre de plus de 138 mètres dans le karst morave avec passerelles ; l''entrée des grottes de Punkva."},
   "uk":{"name":"Прірва Мацоха","description":"Понад 138-метрова прірва в Моравському красі з оглядовими містками; вхід до Пунквенних печер."}}'::jsonb),

('nature', 'Prachovské skály',
 'Pískovcové skalní město v Českém ráji s vyhlídkami a soutěskami; klasika skalních měst.',
 50.4630, 15.2910, 'CZ', 'curated-batch2', 161,
 '{"en":{"name":"Prachov Rocks","description":"A sandstone rock town in Bohemian Paradise with viewpoints and gorges; the classic of Czech rock cities."},
   "de":{"name":"Prachauer Felsen","description":"Eine Sandstein-Felsenstadt im Böhmischen Paradies mit Aussichtspunkten und Schluchten; der Klassiker der Felsenstädte."},
   "pl":{"name":"Prachovskie Skały","description":"Piaskowcowe skalne miasto w Czeskim Raju z punktami widokowymi i wąwozami; klasyka skalnych miast."},
   "nl":{"name":"Prachov-rotsen","description":"Een zandsteen-rotsenstad in het Boheems Paradijs met uitzichtpunten en kloven; dé klassieker onder de rotssteden."},
   "es":{"name":"Rocas de Prachov","description":"Una ciudad de rocas de arenisca en el Paraíso Bohemio con miradores y gargantas; el clásico de las ciudades rocosas."},
   "fr":{"name":"Rochers de Prachov","description":"Une ville de rochers de grès du Paradis tchèque avec belvédères et gorges ; le classique des cités rocheuses."},
   "uk":{"name":"Праховські скелі","description":"Пісковикове скельне місто в Чеському раю з оглядовими точками та ущелинами; класика скельних міст."}}'::jsonb),

('nature', 'Boubínský prales',
 'Jeden z nejstarších pralesů Evropy pod vrcholem Boubína; šumavská divočina chráněná od roku 1858.',
 48.9770, 13.8100, 'CZ', 'curated-batch2', 162,
 '{"en":{"name":"Boubín Primeval Forest","description":"One of Europe''s oldest primeval forests below Boubín peak; Šumava wilderness protected since 1858."},
   "de":{"name":"Kubany-Urwald (Boubín)","description":"Einer der ältesten Urwälder Europas unter dem Kubany-Gipfel; Böhmerwald-Wildnis, geschützt seit 1858."},
   "pl":{"name":"Puszcza Boubińska","description":"Jeden z najstarszych lasów pierwotnych Europy pod szczytem Boubín; szumawska dzicz chroniona od 1858 roku."},
   "nl":{"name":"Oerbos van Boubín","description":"Een van de oudste oerbossen van Europa onder de Boubín-top; Šumava-wildernis, beschermd sinds 1858."},
   "es":{"name":"Bosque primigenio de Boubín","description":"Uno de los bosques vírgenes más antiguos de Europa bajo el pico Boubín; protegido desde 1858."},
   "fr":{"name":"Forêt primaire de Boubín","description":"L''une des plus anciennes forêts primaires d''Europe sous le sommet du Boubín ; protégée depuis 1858."},
   "uk":{"name":"Боубінський праліс","description":"Один із найстаріших пралісів Європи під вершиною Боубін; шумавська дика природа, охоронювана з 1858 року."}}'::jsonb),

('nature', 'Národní přírodní rezervace SOOS',
 'Rašeliniště a bahenní sopky na dně vyschlého slaného jezera u Františkových Lázní; kus Islandu v Čechách.',
 50.1480, 12.4060, 'CZ', 'curated-batch2', 163,
 '{"en":{"name":"SOOS Nature Reserve","description":"Peat bogs and mud volcanoes on the bed of a dried salt lake near Františkovy Lázně; a piece of Iceland in Bohemia."},
   "de":{"name":"Naturreservat SOOS","description":"Moore und Schlammvulkane auf dem Grund eines ausgetrockneten Salzsees bei Franzensbad; ein Stück Island in Böhmen."},
   "pl":{"name":"Rezerwat SOOS","description":"Torfowiska i wulkany błotne na dnie wyschniętego słonego jeziora koło Franciszkowych Łaźni; kawałek Islandii w Czechach."},
   "nl":{"name":"Natuurreservaat SOOS","description":"Veenmoerassen en moddervulkanen op de bodem van een opgedroogd zoutmeer bij Františkovy Lázně; een stukje IJsland in Bohemen."},
   "es":{"name":"Reserva natural SOOS","description":"Turberas y volcanes de lodo en el lecho de un lago salado seco; un pedazo de Islandia en Bohemia."},
   "fr":{"name":"Réserve naturelle SOOS","description":"Tourbières et volcans de boue au fond d''un lac salé asséché ; un morceau d''Islande en Bohême."},
   "uk":{"name":"Заповідник SOOS","description":"Торфовища та грязьові вулкани на дні висохлого солоного озера біля Франтішкових Лазнів; шматочок Ісландії в Чехії."}}'::jsonb),

('nature', 'Prielom Dunajca',
 'Kaňon Dunajce mezi vápencovými stěnami Pienin; vory pltníků a stezka podél řeky na slovensko-polské hranici.',
 49.4170, 20.4160, 'SK', 'curated-batch2', 164,
 '{"en":{"name":"Dunajec River Gorge","description":"The Dunajec canyon between the limestone walls of the Pieniny; rafts and a riverside trail on the Slovak-Polish border."},
   "de":{"name":"Dunajec-Durchbruch","description":"Der Dunajec-Canyon zwischen den Kalkwänden der Pieninen; Flöße und ein Uferweg an der slowakisch-polnischen Grenze."},
   "pl":{"name":"Przełom Dunajca","description":"Kanion Dunajca między wapiennymi ścianami Pienin; tratwy flisackie i szlak wzdłuż rzeki na granicy słowacko-polskiej."},
   "nl":{"name":"Dunajec-kloof","description":"De Dunajec-canyon tussen de kalkstenen wanden van de Pieniny; vlotten en een pad langs de rivier op de Slowaaks-Poolse grens."},
   "es":{"name":"Garganta del Dunajec","description":"El cañón del Dunajec entre paredes calizas de los Pieninos; balsas y un sendero junto al río en la frontera eslovaco-polaca."},
   "fr":{"name":"Gorges du Dunajec","description":"Le canyon du Dunajec entre les parois calcaires des Piénines ; radeaux et sentier au bord de l''eau à la frontière slovaco-polonaise."},
   "uk":{"name":"Пролом Дунайця","description":"Каньйон Дунайця між вапняковими стінами Пенін; плоти плотогонів і стежка вздовж річки на словацько-польському кордоні."}}'::jsonb),

('nature', 'Slovenský raj — Suchá Belá',
 'Nejznámější roklina Slovenského ráje s žebříky a vodopády; adrenalinová procházka soutěskou.',
 48.9600, 20.3750, 'SK', 'curated-batch2', 165,
 '{"en":{"name":"Slovak Paradise — Suchá Belá","description":"The best-known gorge of Slovak Paradise with ladders and waterfalls; an adrenaline walk through the canyon."},
   "de":{"name":"Slowakisches Paradies — Suchá Belá","description":"Die bekannteste Klamm des Slowakischen Paradieses mit Leitern und Wasserfällen; eine Adrenalinwanderung."},
   "pl":{"name":"Słowacki Raj — Suchá Belá","description":"Najbardziej znany wąwóz Słowackiego Raju z drabinami i wodospadami; adrenalinowy spacer przełomem."},
   "nl":{"name":"Slowaaks Paradijs — Suchá Belá","description":"De bekendste kloof van het Slowaaks Paradijs met ladders en watervallen; een adrenalinewandeling."},
   "es":{"name":"Paraíso Eslovaco — Suchá Belá","description":"La garganta más conocida del Paraíso Eslovaco con escaleras y cascadas; un paseo de adrenalina."},
   "fr":{"name":"Paradis slovaque — Suchá Belá","description":"La gorge la plus connue du Paradis slovaque avec échelles et cascades ; une randonnée à sensations."},
   "uk":{"name":"Словацький рай — Суха Бела","description":"Найвідоміша ущелина Словацького раю з драбинами й водоспадами; адреналінова прогулянка тісниною."}}'::jsonb),

('nature', 'Ojcowski Park Narodowy',
 'Nejmenší polský národní park s vápencovými skalami, jeskyněmi a Pieskovou skálou u Krakova.',
 50.2110, 19.8300, 'PL', 'curated-batch2', 166,
 '{"en":{"name":"Ojców National Park","description":"Poland''s smallest national park with limestone crags, caves and Pieskowa Skała castle near Kraków."},
   "de":{"name":"Nationalpark Ojców","description":"Polens kleinster Nationalpark mit Kalkfelsen, Höhlen und der Burg Pieskowa Skała bei Krakau."},
   "pl":{"name":"Ojcowski Park Narodowy","description":"Najmniejszy polski park narodowy z wapiennymi skałami, jaskiniami i zamkiem Pieskowa Skała pod Krakowem."},
   "nl":{"name":"Nationaal Park Ojców","description":"Polens kleinste nationale park met kalksteenrotsen, grotten en kasteel Pieskowa Skała bij Krakau."},
   "es":{"name":"Parque Nacional de Ojców","description":"El parque nacional más pequeño de Polonia, con peñas calizas, cuevas y el castillo de Pieskowa Skała."},
   "fr":{"name":"Parc national d''Ojców","description":"Le plus petit parc national de Pologne, avec rochers calcaires, grottes et le château de Pieskowa Skała."},
   "uk":{"name":"Ойцовський національний парк","description":"Найменший польський нацпарк із вапняковими скелями, печерами та замком Пєскова Скала біля Кракова."}}'::jsonb),

('nature', 'Krimmlské vodopády',
 'Nejvyšší vodopády Rakouska — 380 metrů ve třech kaskádách na kraji Vysokých Taur.',
 47.2030, 12.1720, 'AT', 'curated-batch2', 167,
 '{"en":{"name":"Krimml Waterfalls","description":"Austria''s tallest waterfalls — 380 metres in three cascades at the edge of the Hohe Tauern."},
   "de":{"name":"Krimmler Wasserfälle","description":"Österreichs höchste Wasserfälle — 380 Meter in drei Stufen am Rand der Hohen Tauern."},
   "pl":{"name":"Wodospady Krimml","description":"Najwyższe wodospady Austrii — 380 metrów w trzech kaskadach na skraju Wysokich Taurów."},
   "nl":{"name":"Krimml-watervallen","description":"De hoogste watervallen van Oostenrijk — 380 meter in drie cascades aan de rand van de Hohe Tauern."},
   "es":{"name":"Cascadas de Krimml","description":"Las cascadas más altas de Austria: 380 metros en tres saltos al borde de los Altos Tauern."},
   "fr":{"name":"Chutes de Krimml","description":"Les plus hautes chutes d''Autriche — 380 mètres en trois paliers en bordure des Hohe Tauern."},
   "uk":{"name":"Водоспади Крімль","description":"Найвищі водоспади Австрії — 380 метрів у три каскади на краю Високих Тауерн."}}'::jsonb),

('nature', 'Eisriesenwelt',
 'Největší ledová jeskyně světa ve stěně Hochkogelu u Werfenu; kilometry ledových síní.',
 47.5030, 13.1900, 'AT', 'curated-batch2', 168,
 '{"en":{"name":"Eisriesenwelt","description":"The world''s largest ice cave in the Hochkogel wall near Werfen; kilometres of ice halls."},
   "de":{"name":"Eisriesenwelt","description":"Die größte Eishöhle der Welt in der Hochkogelwand bei Werfen; Kilometer von Eishallen."},
   "pl":{"name":"Eisriesenwelt","description":"Największa lodowa jaskinia świata w ścianie Hochkogelu koło Werfen; kilometry lodowych sal."},
   "nl":{"name":"Eisriesenwelt","description":"De grootste ijsgrot ter wereld in de wand van de Hochkogel bij Werfen; kilometers ijszalen."},
   "es":{"name":"Eisriesenwelt","description":"La cueva de hielo más grande del mundo en la pared del Hochkogel; kilómetros de salas heladas."},
   "fr":{"name":"Eisriesenwelt","description":"La plus grande grotte de glace du monde dans la paroi du Hochkogel ; des kilomètres de salles glacées."},
   "uk":{"name":"Айсризенвельт","description":"Найбільша льодова печера світу в стіні Хохкогеля біля Верфена; кілометри крижаних залів."}}'::jsonb),

('nature', 'Szczeliniec Wielki',
 'Nejvyšší vrchol polských Stolových hor se skalním labyrintem a výhledy do Kladska.',
 50.4850, 16.3390, 'PL', 'curated-batch2', 169,
 '{"en":{"name":"Szczeliniec Wielki","description":"The highest summit of Poland''s Table Mountains with a rock labyrinth and views over the Kłodzko region."},
   "de":{"name":"Große Heuscheuer (Szczeliniec)","description":"Der höchste Gipfel des polnischen Heuscheuergebirges mit Felslabyrinth und Blick ins Glatzer Land."},
   "pl":{"name":"Szczeliniec Wielki","description":"Najwyższy szczyt polskich Gór Stołowych ze skalnym labiryntem i widokami na ziemię kłodzką."},
   "nl":{"name":"Szczeliniec Wielki","description":"De hoogste top van de Poolse Tafelbergen met een rotslabyrint en uitzicht over het Kłodzko-land."},
   "es":{"name":"Szczeliniec Wielki","description":"La cumbre más alta de las Montañas de Mesa polacas, con laberinto rocoso y vistas de la región de Kłodzko."},
   "fr":{"name":"Szczeliniec Wielki","description":"Le plus haut sommet des monts Tabulaires polonais, avec labyrinthe rocheux et vues sur le pays de Kłodzko."},
   "uk":{"name":"Щелінець Великий","description":"Найвища вершина польських Столових гір зі скельним лабіринтом і краєвидами Клодзької землі."}}'::jsonb);
