-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — VELKÁ BRITÁNIE (10 tras, sort 3910–4000)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Anglie – Lake District a průsmyk Hardknott
  delete from public.routes where name = 'Anglie – Lake District a průsmyk Hardknott' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Lake District a průsmyk Hardknott', 'Jezerní okruh z Keswicku je koncentrát toho nejlepšího z anglického Lake Districtu: úzké silničky mezi kamennými zídkami, zrcadlící se jezera a dva nejstrmější asfaltové průsmyky Anglie — Hardknott a Wrynose se sklonem až 30 % a vlásenkami jako z Alp v kapesním vydání. Přes Honister Pass sjedete k jezeru Buttermere, údolím Eskdale vystoupáte na Hardknott s římskou pevností a přes Ambleside a Kirkstone Pass se vrátíte zpět. POZOR: v celé Británii se jezdí VLEVO — na jednoproudých úsecích s výhybnami (passing places) buďte trpěliví a pouštějte protijedoucí. Nejlepší je květen až září, mimo víkendové špičky; povrch je místy hrbolatý a v průsmycích počítejte s ovcemi na vozovce a s rychle se měnícím počasím. Na kávu a výborné jídlo zastavte v Ambleside.', 'loop', 175, 330, 'hard',
     '[{"lat": 54.6013, "lng": -3.1347, "label": "Start: Keswick"}, {"lat": 54.5116, "lng": -3.1994, "label": "Honister Pass"}, {"lat": 54.5417, "lng": -3.2766, "label": "Buttermere"}, {"lat": 54.4029, "lng": -3.2116, "label": "Hardknott Pass"}, {"lat": 54.4287, "lng": -2.9613, "label": "Ambleside"}, {"lat": 54.4700, "lng": -2.9265, "label": "Kirkstone Pass"}, {"lat": 54.6013, "lng": -3.1347, "label": "Cíl: Keswick"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.6013,-3.1347&destination=54.6013,-3.1347&travelmode=driving&waypoints=54.5116,-3.1994%7C54.5417,-3.2766%7C54.4029,-3.2116%7C54.4287,-2.9613%7C54.4700,-2.9265', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ashness%20Bridge,%20Lake%20District%20-%20June%202009.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ashness%20Bridge,%20Lake%20District%20-%20June%202009.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Honister%20Pass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Buttermere,%20Lake%20District%20-%20June%202009.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hardknott%20Pass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Wrynose%20Pass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bridge%20House,%20Ambleside.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kirkstone%20Pass.jpg"}'::text[], '{"Ashness Bridge","Honister Pass","Buttermere","Hardknott Pass","Wrynose Pass","Restaurace: The Old Stamp House (Ambleside)","Kirkstone Pass"}'::text[], '{"GB"}'::text[], false, 3910, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Ashness Bridge', 'Nejfotografovanější kamenný mostek Anglie nad jezerem Derwentwater, jen kousek od Keswicku po silničce do Watendlath. Ideální první fotozastávka okruhu — motorka na středověkém mostku s panoramatem Skiddaw v zádech.', 54.5758, -3.0900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ashness%20Bridge,%20Lake%20District%20-%20June%202009.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ashness%20Bridge,%20Lake%20District%20-%20June%202009.jpg"}'::text[], 0),
    (v_route, 'Honister Pass', 'Průsmyk (356 m) s divokou skalní scenérií a břidlicovým dolem Honister Slate Mine na vrcholu. Sjezd k Buttermere patří k nejhezčím kilometrům Lake Districtu — úzký, strmý a mezi zídkami, brzděte s předstihem.', 54.5116, -3.1994, 'https://commons.wikimedia.org/wiki/Special:FilePath/Honister%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Honister%20Pass.jpg"}'::text[], 1),
    (v_route, 'Buttermere', 'Tiché jezero sevřené horami Haystacks a High Stile, oblíbené místo horolezce Alfreda Wainwrighta. U jezera je farma se slavnou zmrzlinou a krátká procházka k břehu stojí za protažení nohou.', 54.5417, -3.2766, 'https://commons.wikimedia.org/wiki/Special:FilePath/Buttermere,%20Lake%20District%20-%20June%202009.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Buttermere,%20Lake%20District%20-%20June%202009.jpg"}'::text[], 2),
    (v_route, 'Hardknott Pass', 'Nejstrmější silnice Anglie — sklon až 30 %, vlásenky první rychlostní stupeň a pod vrcholem ruiny římské pevnosti Mediobogdum s výhledem do údolí Eskdale. Jezděte jen za sucha, mokrý asfalt tu umí potrápit i zkušené.', 54.4029, -3.2116, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hardknott%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hardknott%20Pass.jpg"}'::text[], 3),
    (v_route, 'Wrynose Pass', 'Dvojče Hardknottu hned za údolím — na vrcholu stojí Three Shire Stone, kde se historicky stýkala tři anglická hrabství. Technická jednoproudka s výhybnami; kdo jede vlevo poprvé, tady si to opravdu osahá.', 54.4160, -3.1130, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wrynose%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wrynose%20Pass.jpg"}'::text[], 4),
    (v_route, 'Restaurace: The Old Stamp House (Ambleside)', 'Michelinskou hvězdou ověnčený podnik v domě, kde úřadoval básník William Wordsworth — moderní kumbrijská kuchyně z lokálních surovin. Na rychlejší oběd poslouží kavárny na hlavní ulici u ikonického Bridge House.', 54.4287, -2.9620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bridge%20House,%20Ambleside.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bridge%20House,%20Ambleside.jpg"}'::text[], 5),
    (v_route, 'Kirkstone Pass', 'Nejvyšší průsmyk Lake Districtu otevřený celoročně (454 m) s historickým hostincem na vrcholu a výhledem na jezero Windermere. Odbočka „The Struggle" z Ambleside je strmá zkratka pro odvážné.', 54.4700, -2.9265, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kirkstone%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kirkstone%20Pass.jpg"}'::text[], 6);

  -- Anglie – Yorkshire Dales a Buttertubs Pass
  delete from public.routes where name = 'Anglie – Yorkshire Dales a Buttertubs Pass' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Yorkshire Dales a Buttertubs Pass', 'Okruh národním parkem Yorkshire Dales z městečka Hawes spojuje to, co Angličané milují: vřesoviště, kamenné zídky táhnoucí se po horizont a rychlé, přehledné silnice s výhledy. Buttertubs Pass označil Jeremy Clarkson za jednu z nejlepších silnic Anglie, u Tan Hill se zastavíte v nejvýše položené hospodě Británie a pod viaduktem Ribblehead pochopíte, proč sem jezdí fotografové z celého světa. Přes vápencový amfiteátr Malham Cove a vodopády Aysgarth se vrátíte zpět do Wensleydale, domoviny slavného sýra. Jezdí se VLEVO a na jednoproudých úsecích čekejte výhybny, ovce a o víkendech cyklisty. Ideální od dubna do října; na otevřených vřesovištích umí pořádně foukat.', 'loop', 190, 300, 'medium',
     '[{"lat": 54.3040, "lng": -2.1980, "label": "Start: Hawes"}, {"lat": 54.3450, "lng": -2.2010, "label": "Buttertubs Pass"}, {"lat": 54.4426, "lng": -2.1631, "label": "Tan Hill"}, {"lat": 54.2107, "lng": -2.3703, "label": "Ribblehead"}, {"lat": 54.0722, "lng": -2.1580, "label": "Malham"}, {"lat": 54.2919, "lng": -1.9819, "label": "Aysgarth"}, {"lat": 54.3040, "lng": -2.1980, "label": "Cíl: Hawes"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.3040,-2.1980&destination=54.3040,-2.1980&travelmode=driving&waypoints=54.3450,-2.2010%7C54.4426,-2.1631%7C54.2107,-2.3703%7C54.0722,-2.1580%7C54.2919,-1.9819', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ribblehead%20Viaduct.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Buttertubs%20Pass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Muker,%20Swaledale.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tan%20Hill%20Inn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ribblehead%20Viaduct.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Malham%20Cove.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Aysgarth%20Falls.jpg"}'::text[], '{"Buttertubs Pass","Muker (Swaledale)","Restaurace: Tan Hill Inn","Ribblehead Viaduct","Malham Cove","Aysgarth Falls"}'::text[], '{"GB"}'::text[], false, 3920, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Buttertubs Pass', 'Legendární horská silnice mezi Wensleydale a Swaledale, pojmenovaná po hlubokých vápencových jámách u vrcholu, kam prý farmáři v horku ukládali máslo. Rychlé esíčka, skvělý asfalt a výhledy — jedna z nejlepších motorkářských silnic severní Anglie.', 54.3450, -2.2010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Buttertubs%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Buttertubs%20Pass.jpg"}'::text[], 0),
    (v_route, 'Muker (Swaledale)', 'Kamenná vesnička v nejmalebnějším údolí Dales, obklopená loukami se stodolami a zídkami, jak je znáte z pohlednic. V červnu tu kvetou slavné květnaté louky; zastavte na čaj a koláč v místní čajovně.', 54.3776, -2.1390, 'https://commons.wikimedia.org/wiki/Special:FilePath/Muker,%20Swaledale.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Muker,%20Swaledale.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Tan Hill Inn', 'Nejvýše položená hospoda Velké Británie (528 m) uprostřed vřesovišť — vyhlášené pivo, poctivé hospodské jídlo a krb, který prý nevyhasl desítky let. Kultovní zastávka motorkářů; v zimě tu hosty občas zavěje sníh na několik dní.', 54.4426, -2.1631, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tan%20Hill%20Inn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tan%20Hill%20Inn.jpg"}'::text[], 2),
    (v_route, 'Ribblehead Viaduct', 'Monumentální železniční viadukt z roku 1874 s 24 oblouky na trati Settle–Carlisle, tyčící se uprostřed pusté krajiny Three Peaks. Parkoviště je přímo u silnice B6255 — s trochou štěstí přes viadukt zrovna pojede parní vlak.', 54.2107, -2.3703, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ribblehead%20Viaduct.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ribblehead%20Viaduct.jpg"}'::text[], 3),
    (v_route, 'Malham Cove', 'Osmdesátimetrový vápencový amfiteátr s proslulou „dlažbou" na hraně — natáčel se tu i Harry Potter. Od parkoviště ve vsi Malham je to pěšky asi 20 minut; nahoře odměna v podobě výhledu na celé Airedale.', 54.0722, -2.1580, 'https://commons.wikimedia.org/wiki/Special:FilePath/Malham%20Cove.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Malham%20Cove.jpg"}'::text[], 4),
    (v_route, 'Aysgarth Falls', 'Trojice širokých kaskád řeky Ure ve Wensleydale, známá z filmu Robin Hood: Král zbojníků. Krátká zastávka na protažení — vodopády jsou pár minut chůze od parkoviště, nejmohutnější bývají po dešti.', 54.2919, -1.9819, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aysgarth%20Falls.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aysgarth%20Falls.jpg"}'::text[], 5);

  -- Anglie – Peak District a Snake Pass
  delete from public.routes where name = 'Anglie – Peak District a Snake Pass' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Peak District a Snake Pass', 'Okruh nejstarším národním parkem Anglie začíná v Glossopu proslulou A57 Snake Pass — hadovitou horskou silnicí přes vřesoviště, kterou si motorkáři z Manchesteru a Sheffieldu hlídají jako rodinné stříbro. Kolem přehrad Ladybower sjedete do údolí Hope Valley, projedete dramatickou vápencovou soutěskou Winnats Pass nad Castletonem a přes panství Chatsworth dorazíte do Matlock Bath — viktoriánského lázeňského městečka, které je o víkendech neoficiálním srazem motorkářů z celé Anglie. Jezdí se VLEVO; na Snake Pass pozor na zvlněný povrch, boční vítr a o víkendech na policejní měření. Nejlépe ve všední den od jara do podzimu, v zimě bývá průsmyk zavřený kvůli sněhu.', 'loop', 150, 240, 'medium',
     '[{"lat": 53.4432, "lng": -1.9490, "label": "Start: Glossop"}, {"lat": 53.4326, "lng": -1.8560, "label": "Snake Pass"}, {"lat": 53.3780, "lng": -1.7130, "label": "Ladybower"}, {"lat": 53.3436, "lng": -1.7767, "label": "Castleton"}, {"lat": 53.2277, "lng": -1.6110, "label": "Chatsworth"}, {"lat": 53.1220, "lng": -1.5610, "label": "Matlock Bath"}, {"lat": 53.4432, "lng": -1.9490, "label": "Cíl: Glossop"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=53.4432,-1.9490&destination=53.4432,-1.9490&travelmode=driving&waypoints=53.4326,-1.8560%7C53.3780,-1.7130%7C53.3436,-1.7767%7C53.2277,-1.6110%7C53.1220,-1.5610', 'https://commons.wikimedia.org/wiki/Special:FilePath/Winnats%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Snake%20Pass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ladybower%20Reservoir.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Winnats%20Pass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Peveril%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Chatsworth%20House.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Matlock%20Bath.jpg"}'::text[], '{"Snake Pass (A57)","Ladybower Reservoir","Winnats Pass","Castleton a Peveril Castle","Chatsworth House","Matlock Bath"}'::text[], '{"GB"}'::text[], false, 3930, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Snake Pass (A57)', 'Slavná horská silnice mezi Glossopem a Sheffieldem, vinoucí se přes vřesoviště Bleaklow do výšky 512 m. Dlouhé zatáčky, žádné zídky, jen otevřená pustina — jeden z nejopojnějších úseků Anglie, který ale vyžaduje respekt k počasí.', 53.4326, -1.8560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Snake%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Snake%20Pass.jpg"}'::text[], 0),
    (v_route, 'Ladybower Reservoir', 'Přehrada s ikonickými zvonovými přepady, u níž za války trénovali piloti slavné operace Dambusters s poskakující bombou. Silnice A57 vede přímo přes viadukt nad hladinou; parkoviště u hráze zve na krátkou pauzu.', 53.3780, -1.7130, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ladybower%20Reservoir.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ladybower%20Reservoir.jpg"}'::text[], 1),
    (v_route, 'Winnats Pass', 'Dechberoucí vápencová soutěska nad Castletonem — silnice stoupá až 20% sklonem mezi kolmými travnatými věžemi. Krátký, ale nezapomenutelný úsek; v protisměru se tu s autobusem lépe potkává zespoda.', 53.3410, -1.8040, 'https://commons.wikimedia.org/wiki/Special:FilePath/Winnats%20Pass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Winnats%20Pass.jpg"}'::text[], 2),
    (v_route, 'Castleton a Peveril Castle', 'Kamenné městečko pod normanským hradem Peveril z 11. století, obklopené jeskyněmi, kde se těží unikátní polodrahokam Blue John. Ideální místo na oběd — hospody tu vaří poctivé yorkshirské klasiky.', 53.3436, -1.7767, 'https://commons.wikimedia.org/wiki/Special:FilePath/Peveril%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Peveril%20Castle.jpg"}'::text[], 3),
    (v_route, 'Chatsworth House', 'Velkolepé sídlo vévodů z Devonshiru s barokními zahradami a kaskádou — „Pemberley" z Pýchy a předsudku. I bez prohlídky stojí za zastávku průjezd parkem, kde se mezi silnicí a řekou pasou stáda jelenů.', 53.2277, -1.6110, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chatsworth%20House.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chatsworth%20House.jpg"}'::text[], 4),
    (v_route, 'Matlock Bath', 'Viktoriánské lázně v soutěsce řeky Derwent, o víkendech největší přirozený sraz motorkářů v Anglii — promenáda je lemovaná stovkami strojů, stánky s fish and chips a obchody s vybavením. Nad údolím jezdí lanovka na Heights of Abraham.', 53.1220, -1.5610, 'https://commons.wikimedia.org/wiki/Special:FilePath/Matlock%20Bath.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Matlock%20Bath.jpg"}'::text[], 5);

  -- Anglie – Cat and Fiddle a Goytské údolí
  delete from public.routes where name = 'Anglie – Cat and Fiddle a Goytské údolí' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Cat and Fiddle a Goytské údolí', 'Krátký, ale intenzivní okruh po západním okraji Peak Districtu kolem silnice A537 Macclesfield–Buxton, které nikdo neřekne jinak než „Cat and Fiddle" podle hospody na jejím vrcholu. Sedm mil zatáček s výhledy na Cheshirskou nížinu patří k nejslavnějším motorkářským silnicím Británie — a také k nejhlídanějším, takže průměrové kamery berte vážně a užívejte si rytmus, ne rychlost. Z lázeňského Buxtonu pokračujete po neméně zábavné A53 kolem skalního hřebene The Roaches a přes Wildboarclough pod „cheshirským Matterhornem" Shutlingsloe zpět. Jezdí se VLEVO; na vřesovištích počítejte s větrem, mlhou a volně pobíhajícími ovcemi. Ideální brzy ráno ve všední den, od jara do podzimu.', 'loop', 105, 180, 'medium',
     '[{"lat": 53.2587, "lng": -2.1256, "label": "Start: Macclesfield"}, {"lat": 53.2437, "lng": -1.9967, "label": "Cat and Fiddle"}, {"lat": 53.2591, "lng": -1.9110, "label": "Buxton"}, {"lat": 53.1650, "lng": -1.9930, "label": "The Roaches"}, {"lat": 53.2317, "lng": -2.0090, "label": "Wildboarclough"}, {"lat": 53.2587, "lng": -2.1256, "label": "Cíl: Macclesfield"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=53.2587,-2.1256&destination=53.2587,-2.1256&travelmode=driving&waypoints=53.2437,-1.9967%7C53.2591,-1.9110%7C53.1650,-1.9930%7C53.2317,-2.0090', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cat%20and%20Fiddle%20Inn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cat%20and%20Fiddle%20Inn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Errwood%20Reservoir.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/The%20Crescent,%20Buxton.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Buxton%20Opera%20House.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/The%20Roaches.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Shutlingsloe.jpg"}'::text[], '{"Cat and Fiddle Inn","Errwood Reservoir (Goyt Valley)","Buxton – The Crescent","Restaurace: The Old Hall Hotel (Buxton)","The Roaches","Shutlingsloe"}'::text[], '{"GB"}'::text[], false, 3940, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Cat and Fiddle Inn', 'Druhá nejvýše položená hospoda Anglie (515 m), která dala jméno celé silnici A537 — dnes v budově sídlí i palírna whisky Forest Distillery. Tradiční zastávka motorkářů s výhledem přes celý Cheshire až k Walesu.', 53.2437, -1.9967, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cat%20and%20Fiddle%20Inn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cat%20and%20Fiddle%20Inn.jpg"}'::text[], 0),
    (v_route, 'Errwood Reservoir (Goyt Valley)', 'Klidná přehrada v Goytském údolí, kam vede krásná odbočka z hlavního tahu — úzká silnička kolem vody, ruiny sídla Errwood Hall a v červnu kvetoucí rododendrony. Perfektní tichá pauza mezi dvěma slavnými silnicemi.', 53.2740, -1.9950, 'https://commons.wikimedia.org/wiki/Special:FilePath/Errwood%20Reservoir.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Errwood%20Reservoir.jpg"}'::text[], 1),
    (v_route, 'Buxton – The Crescent', 'Gruzínský lázeňský půlměsíc z 18. století, kterým chtěl vévoda z Devonshiru konkurovat Bathu — dnes luxusní lázně a symbol města. Buxtonská minerálka od pramene St Ann je tu k ochutnání zdarma.', 53.2591, -1.9110, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Crescent,%20Buxton.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/The%20Crescent,%20Buxton.jpg"}'::text[], 2),
    (v_route, 'Restaurace: The Old Hall Hotel (Buxton)', 'Podnik, který se hlásí k titulu nejstaršího hotelu Anglie — nocovala tu i Marie Stuartovna. Skvělá poloha u Opera House a Pavilion Gardens, poctivá britská kuchyně a odpolední čaj pro nemotorizovanou část posádky.', 53.2585, -1.9125, 'https://commons.wikimedia.org/wiki/Special:FilePath/Buxton%20Opera%20House.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Buxton%20Opera%20House.jpg"}'::text[], 3),
    (v_route, 'The Roaches', 'Zubatý gritstonový hřeben nad silnicí A53 u Leeku, ráj horolezců s výhledem na půl Anglie — za jasného dne dohlédnete až na velšské hory. Podle legendy tu v 70. letech žili uprchlí klokani ze soukromého zvěřince.', 53.1650, -1.9930, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Roaches.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/The%20Roaches.jpg"}'::text[], 4),
    (v_route, 'Shutlingsloe', '„Cheshirský Matterhorn" — nápadný kuželovitý kopec (506 m) nad vesničkou Wildboarclough, kde podle pověsti zabili posledního divočáka v Anglii. Silnička údolím Clough Brook je úzká jednoproudka jako stvořená pro pomalé kochání.', 53.2317, -2.0090, 'https://commons.wikimedia.org/wiki/Special:FilePath/Shutlingsloe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Shutlingsloe.jpg"}'::text[], 5);

  -- Anglie – Cotswolds, medové vesnice
  delete from public.routes where name = 'Anglie – Cotswolds, medové vesnice' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Cotswolds, medové vesnice', 'Pohodový okruh krajinou Cotswolds, kde je každá vesnice postavená z medově zbarveného vápence a vypadá jako kulisa historického filmu. Z Burfordu se svezete k nejfotografovanější uličce Anglie — Arlington Row v Bibury — projedete „anglické Benátky" Bourton-on-the-Water, tržní městečka Stow-on-the-Wold a Chipping Campden a vystoupáte k romantické vyhlídkové věži Broadway Tower. Silnice jsou tu klidné, zvlněné a přehledné, ideální i pro méně zkušené jezdce nebo jízdu ve dvou. Jezdí se VLEVO; pozor na úzké uličky v centrech vesnic, projíždějící traktory a víkendové davy turistů — Bibury je nejhezčí brzy ráno. Krásné je to od jara do podzimu, v říjnu se buky barví dozlatova.', 'loop', 120, 210, 'easy',
     '[{"lat": 51.8085, "lng": -1.6362, "label": "Start: Burford"}, {"lat": 51.7599, "lng": -1.8330, "label": "Bibury"}, {"lat": 51.8523, "lng": -1.7550, "label": "Bourton-on-the-Water"}, {"lat": 51.9300, "lng": -1.7220, "label": "Stow-on-the-Wold"}, {"lat": 52.0244, "lng": -1.8358, "label": "Broadway Tower"}, {"lat": 52.0500, "lng": -1.7790, "label": "Chipping Campden"}, {"lat": 51.8085, "lng": -1.6362, "label": "Cíl: Burford"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.8085,-1.6362&destination=51.8085,-1.6362&travelmode=driving&waypoints=51.7599,-1.8330%7C51.8523,-1.7550%7C51.9300,-1.7220%7C52.0244,-1.8358%7C52.0500,-1.7790', 'https://commons.wikimedia.org/wiki/Special:FilePath/Arlington%20Row,%20Bibury.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Burford%20High%20Street.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Arlington%20Row,%20Bibury.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bourton-on-the-Water.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stow-on-the-Wold.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Broadway%20tower%20edit.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Broadway,%20Worcestershire.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Chipping%20Campden%20High%20Street.jpg"}'::text[], '{"Burford","Bibury – Arlington Row","Bourton-on-the-Water","Stow-on-the-Wold","Broadway Tower","Restaurace: The Lygon Arms (Broadway)","Chipping Campden"}'::text[], '{"GB"}'::text[], false, 3950, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Burford', '„Brána do Cotswolds" — středověké městečko, jehož hlavní ulice se svažuje mezi kamennými domy ke starému mostu přes řeku Windrush. Antikvariáty, čajovny a jedna z nejstarších lékáren v Anglii.', 51.8085, -1.6362, 'https://commons.wikimedia.org/wiki/Special:FilePath/Burford%20High%20Street.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Burford%20High%20Street.jpg"}'::text[], 0),
    (v_route, 'Bibury – Arlington Row', 'Řada tkalcovských domků ze 17. století, kterou William Morris označil za nejkrásnější vesnickou scenérii Anglie — najdete ji i v britských pasech. Přijeďte brzy ráno, přes den bývá plno; hned vedle je historická pstruží farma.', 51.7599, -1.8330, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arlington%20Row,%20Bibury.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arlington%20Row,%20Bibury.jpg"}'::text[], 1),
    (v_route, 'Bourton-on-the-Water', '„Benátky Cotswolds" — mělká říčka Windrush protéká přímo návsí pod nízkými kamennými mostky. K vidění je tu i automobilové muzeum a miniaturní model celé vesnice v měřítku 1:9.', 51.8523, -1.7550, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bourton-on-the-Water.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bourton-on-the-Water.jpg"}'::text[], 2),
    (v_route, 'Stow-on-the-Wold', 'Nejvýše položené městečko Cotswolds s rozlehlým tržním náměstím, kde se křižovaly středověké ovčí stezky. U kostela sv. Edwarda rostou z portálu dva tisy — dveře jako z Pána prstenů.', 51.9300, -1.7220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stow-on-the-Wold.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stow-on-the-Wold.jpg"}'::text[], 3),
    (v_route, 'Broadway Tower', 'Romantická „bláznivá věž" z roku 1798 na druhém nejvyšším bodě Cotswolds — za jasného dne z ní dohlédnete do třinácti hrabství. Příjezdová silnička po hřebeni je krásná sama o sobě; u věže žije stádo jelenů.', 52.0244, -1.8358, 'https://commons.wikimedia.org/wiki/Special:FilePath/Broadway%20tower%20edit.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Broadway%20tower%20edit.jpg"}'::text[], 4),
    (v_route, 'Restaurace: The Lygon Arms (Broadway)', 'Historický hostinec ze 16. století na hlavní třídě „nejkrásnější vesnice Anglie" — nocoval tu Oliver Cromwell i Karel I. Elegantní grill room s poctivými britskými klasikami; na lehčí oběd poslouží kavárny přímo na Broadway High Street.', 52.0390, -1.8580, 'https://commons.wikimedia.org/wiki/Special:FilePath/Broadway,%20Worcestershire.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Broadway,%20Worcestershire.jpg"}'::text[], 5),
    (v_route, 'Chipping Campden', 'Perla mezi cotswoldskými městečky s obloukovou tržnicí z roku 1627 uprostřed hlavní ulice. Odsud startuje dálková stezka Cotswold Way; kamenné domy tu mají snad nejsytější medový odstín z celé oblasti.', 52.0500, -1.7790, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chipping%20Campden%20High%20Street.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chipping%20Campden%20High%20Street.jpg"}'::text[], 6);

  -- Anglie – Cornwall a Land's End
  delete from public.routes where name = 'Anglie – Cornwall a Land''s End' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Cornwall a Land''s End', 'Okruh úplným koncem Anglie: z Penzance kolem pohádkového ostrovního zámku St Michael''s Mount na nejjižnější bod Británie Lizard Point, a poté přes rybářský Mousehole a divadlo Minack vytesané do útesu až na slavný mys Land''s End. Zpáteční cesta vede přes bývalé hornické pobřeží u St Just do uměleckého přístavu St Ives s tyrkysovou vodou jako z Karibiku. Kornwallské silničky jsou úzké, lemované vysokými živými ploty a plné slepých zatáček — jezdí se VLEVO, takže houkněte klaksonem před nepřehlednou zúženinou a počítejte s couváním k výhybně. Nejkrásněji je tu v květnu a červnu nebo v září, o letních prázdninách oblast praská ve švech. Vůně moře, pastis a čerstvé krabí sendviče k téhle trase patří.', 'loop', 160, 300, 'medium',
     '[{"lat": 50.1188, "lng": -5.5376, "label": "Start: Penzance"}, {"lat": 50.1170, "lng": -5.4770, "label": "Marazion – St Michael''s Mount"}, {"lat": 49.9591, "lng": -5.2151, "label": "Lizard Point"}, {"lat": 50.0403, "lng": -5.6519, "label": "Porthcurno – Minack"}, {"lat": 50.0664, "lng": -5.7147, "label": "Land''s End"}, {"lat": 50.2110, "lng": -5.4800, "label": "St Ives"}, {"lat": 50.1188, "lng": -5.5376, "label": "Cíl: Penzance"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.1188,-5.5376&destination=50.1188,-5.5376&travelmode=driving&waypoints=50.1170,-5.4770%7C49.9591,-5.2151%7C50.0403,-5.6519%7C50.0664,-5.7147%7C50.2110,-5.4800', 'https://commons.wikimedia.org/wiki/Special:FilePath/St%20Michael''s%20Mount.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/St%20Michael''s%20Mount.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lizard%20Point,%20Cornwall.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mousehole%20Harbour.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Minack%20Theatre.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Land''s%20End.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/St%20Ives%20Cornwall.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/The%20Sloop%20Inn,%20St%20Ives.jpg"}'::text[], '{"St Michael''s Mount","Lizard Point","Mousehole","Minack Theatre","Land''s End","St Ives","Restaurace: The Sloop Inn (St Ives)"}'::text[], '{"GB"}'::text[], false, 3960, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'St Michael''s Mount', 'Kornwallské dvojče francouzského Mont-Saint-Michel — hradní ostrov, na který se za odlivu dojde pěšky po dlážděné hrázi z Marazionu. Zkontrolujte si časy přílivu; za vysoké vody jezdí přívozní loďky.', 50.1170, -5.4770, 'https://commons.wikimedia.org/wiki/Special:FilePath/St%20Michael''s%20Mount.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/St%20Michael''s%20Mount.jpg"}'::text[], 0),
    (v_route, 'Lizard Point', 'Nejjižnější bod Velké Británie s majákem, tuleni pod útesy a kioskem s krabími sendviči. Poloostrov Lizard má vlastní mikroklima a vzácnou geologii — hadec odsud se brousí na suvenýry už dvě stě let.', 49.9591, -5.2151, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lizard%20Point,%20Cornwall.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lizard%20Point,%20Cornwall.jpg"}'::text[], 1),
    (v_route, 'Mousehole', 'Miniaturní rybářský přístav, o kterém básník Dylan Thomas prohlásil, že je nejkrásnější vesnicí Anglie. Vjezd do přístavu se na zimu zahrazuje trámy proti bouřím; uličky jsou tak úzké, že motorka je tu ideální dopravní prostředek.', 50.0838, -5.5385, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mousehole%20Harbour.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mousehole%20Harbour.jpg"}'::text[], 2),
    (v_route, 'Minack Theatre', 'Divadlo pod širým nebem vytesané do žulového útesu nad tyrkysovou zátokou Porthcurno — z hlediště je vidět na moře a s trochou štěstí i na delfíny. Vybudovala ho vlastníma rukama Rowena Cade ve 30. letech.', 50.0403, -5.6519, 'https://commons.wikimedia.org/wiki/Special:FilePath/Minack%20Theatre.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Minack%20Theatre.jpg"}'::text[], 3),
    (v_route, 'Land''s End', 'Nejzápadnější výběžek Anglie, kde končí silnice a začíná Atlantik — slavný ukazatel s nápisem „John o'' Groats 874 mil" je povinná fotka. Nejhezčí jsou útesy kousek od turistického areálu, směrem k zátoce Sennen.', 50.0664, -5.7147, 'https://commons.wikimedia.org/wiki/Special:FilePath/Land''s%20End.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Land''s%20End.jpg"}'::text[], 4),
    (v_route, 'St Ives', 'Umělecký přístav s plážemi, které by obstály i ve Středomoří, pobočkou galerie Tate a uličkami plnými ateliérů. Pozor na racky — kornwallský pasty nebo zmrzlinu vám umí vytrhnout přímo z ruky.', 50.2110, -5.4800, 'https://commons.wikimedia.org/wiki/Special:FilePath/St%20Ives%20Cornwall.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/St%20Ives%20Cornwall.jpg"}'::text[], 5),
    (v_route, 'Restaurace: The Sloop Inn (St Ives)', 'Přístavní hospoda z roku 1312 přímo na nábřeží — čerstvé ryby, kornwallský ale a stoly, od kterých sledujete rybářské lodě. Jedna z nejstarších hospod v Cornwallu a ideální tečka před návratem do Penzance.', 50.2119, -5.4790, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Sloop%20Inn,%20St%20Ives.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/The%20Sloop%20Inn,%20St%20Ives.jpg"}'::text[], 6);

  -- Anglie – Devon a národní park Dartmoor
  delete from public.routes where name = 'Anglie – Devon a národní park Dartmoor' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Devon a národní park Dartmoor', 'Okruh z Exeteru přes tajemný Dartmoor — největší divočinu jižní Anglie, kde se mezi žulovými skalisky (tory) volně pasou poníci a krajina inspirovala Psa baskervillského. Silnice B3212 napříč vřesovištěm patří k nejhezčím v Devonu: otevřené výhledy, plynulé zatáčky a středověké kamenné mosty v Postbridge a Dartmeetu. Zastavíte u skalní věže Haytor, ve vesničce Widecombe-in-the-Moor i u kostelíka na sopečném suku Brent Tor, odkud je vidět půlka hrabství. Jezdí se VLEVO a zdejší poníci ani ovce silnici nikomu neuhýbají — v mlze, která umí spadnout během minut, jeďte opravdu opatrně. Nejlepší od května do října; v srpnu vřesoviště fialoví.', 'loop', 145, 250, 'medium',
     '[{"lat": 50.7236, "lng": -3.5275, "label": "Start: Exeter"}, {"lat": 50.5800, "lng": -3.7530, "label": "Haytor"}, {"lat": 50.5761, "lng": -3.8110, "label": "Widecombe-in-the-Moor"}, {"lat": 50.5920, "lng": -3.9120, "label": "Postbridge"}, {"lat": 50.5540, "lng": -3.9660, "label": "Two Bridges"}, {"lat": 50.6053, "lng": -4.1600, "label": "Brent Tor"}, {"lat": 50.7236, "lng": -3.5275, "label": "Cíl: Exeter"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.7236,-3.5275&destination=50.7236,-3.5275&travelmode=driving&waypoints=50.5800,-3.7530%7C50.5761,-3.8110%7C50.5920,-3.9120%7C50.5540,-3.9660%7C50.6053,-4.1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Haytor%20Rocks.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Haytor%20Rocks.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Widecombe-in-the-Moor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dartmeet.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Postbridge%20Clapper%20Bridge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Two%20Bridges%20Hotel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dartmoor%20Prison.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brentor%20Church.jpg"}'::text[], '{"Haytor","Widecombe-in-the-Moor","Dartmeet","Postbridge – Clapper Bridge","Restaurace: Two Bridges Hotel (Dartmoor)","Princetown","Brent Tor"}'::text[], '{"GB"}'::text[], false, 3970, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Haytor', 'Nejslavnější žulová skalní věž Dartmooru, viditelná až od pobřeží — od parkoviště u silnice je to nahoru jen pár minut. Výhled na celé jižní Devonsko a první setkání s dartmoorskými poníky.', 50.5800, -3.7530, 'https://commons.wikimedia.org/wiki/Special:FilePath/Haytor%20Rocks.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Haytor%20Rocks.jpg"}'::text[], 0),
    (v_route, 'Widecombe-in-the-Moor', 'Vesnička v hlubokém údolí uprostřed vřesovišť s kostelem přezdívaným „katedrála vřesovišť", opěvovaná ve staré lidové písni o jarmarku. Hospoda a čajovna na návsi zvou na devonský cream tea — nejdřív džem, pak smetana, ať nenaštvete místní.', 50.5761, -3.8110, 'https://commons.wikimedia.org/wiki/Special:FilePath/Widecombe-in-the-Moor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Widecombe-in-the-Moor.jpg"}'::text[], 1),
    (v_route, 'Dartmeet', 'Soutok Východního a Západního Dartu s prastarým kamenným mostem — jedno z nejmalebnějších míst parku. V řece se dá za horkého dne smočit; na parkovišti pozor na poníky, kteří loudí svačiny.', 50.5468, -3.8730, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dartmeet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dartmeet.jpg"}'::text[], 2),
    (v_route, 'Postbridge – Clapper Bridge', 'Nejzachovalejší středověký „clapper bridge" v Anglii — obří žulové desky přes řeku Dart položené ve 13. století. Stojí hned vedle silnice B3212 a je to nejfotografovanější kamenný most Dartmooru.', 50.5920, -3.9120, 'https://commons.wikimedia.org/wiki/Special:FilePath/Postbridge%20Clapper%20Bridge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Postbridge%20Clapper%20Bridge.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Two Bridges Hotel (Dartmoor)', 'Historický hostinec z 18. století u brodu přes Západní Dart, uprostřed ničeho a přesně proto dokonalý — krby, devonská kuchyně a vyhlášený cream tea. Ideální oběd v půlce okruhu.', 50.5540, -3.9660, 'https://commons.wikimedia.org/wiki/Special:FilePath/Two%20Bridges%20Hotel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Two%20Bridges%20Hotel.jpg"}'::text[], 4),
    (v_route, 'Princetown', 'Nejvýše položené městečko Dartmooru, kterému dominuje věznice z napoleonských válek — dnes s muzeem, kde uvidíte i vězeňské výrobky a historii útěků, které inspirovaly Conana Doyla. Návštěvnické centrum parku sídlí v hotelu, kde Pes baskervillský vznikal.', 50.5450, -3.9920, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dartmoor%20Prison.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dartmoor%20Prison.jpg"}'::text[], 5),
    (v_route, 'Brent Tor', 'Kostelík sv. Michaela z 13. století na vrcholu osamělého sopečného suku na západním okraji Dartmooru — jedna z nejdramatičtějších siluet Devonu. Krátký výšlap od parkoviště odmění výhledem od Plymouth Sound až po Bodmin Moor.', 50.6053, -4.1600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brentor%20Church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brentor%20Church.jpg"}'::text[], 6);

  -- Anglie – Northumberland, hrady a Hadriánův val
  delete from public.routes where name = 'Anglie – Northumberland, hrady a Hadriánův val' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Northumberland, hrady a Hadriánův val', 'Cesta nejméně zalidněným hrabstvím Anglie od římského Hadriánova valu k hradům na břehu Severního moře. Z Corbridge vyjedete podél valu k pevnosti Housesteads, pak prázdnými silnicemi přes vřesoviště Northumberlandu na pobřeží: filmový Alnwick (Bradavice z Harryho Pottera), rybářský Craster s vyhlášenými uzenými sledi, romantická zřícenina Dunstanburgh a majestátní Bamburgh Castle na skále nad plážovými dunami. Finále patří ostrovu Lindisfarne, na který vede silnice zaplavovaná přílivem — časy bezpečného přejezdu si POVINNĚ ověřte předem. Jezdí se VLEVO; silnice jsou tu širší a prázdnější než jinde v Anglii, ideální na plynulé tempo. Nejlépe květen až září, od moře ale i v létě fouká chladný vítr.', 'poi', 185, 280, 'easy',
     '[{"lat": 54.9740, "lng": -2.0180, "label": "Start: Corbridge"}, {"lat": 55.0130, "lng": -2.3310, "label": "Housesteads"}, {"lat": 55.4156, "lng": -1.7060, "label": "Alnwick"}, {"lat": 55.4720, "lng": -1.5930, "label": "Craster"}, {"lat": 55.6090, "lng": -1.7150, "label": "Bamburgh"}, {"lat": 55.6805, "lng": -1.8010, "label": "Cíl: Lindisfarne"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.9740,-2.0180&destination=55.6805,-1.8010&travelmode=driving&waypoints=55.0130,-2.3310%7C55.4156,-1.7060%7C55.4720,-1.5930%7C55.6090,-1.7150', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamburgh%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hadrians%20Wall%20from%20Housesteads1%20crop.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Alnwick%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Craster%20Harbour.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dunstanburgh%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bamburgh%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lindisfarne%20Castle.jpg"}'::text[], '{"Hadriánův val – Housesteads","Alnwick Castle","Restaurace: The Jolly Fisherman (Craster)","Dunstanburgh Castle","Bamburgh Castle","Lindisfarne (Holy Island)"}'::text[], '{"GB"}'::text[], false, 3980, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hadriánův val – Housesteads', 'Nejzachovalejší římská pevnost Británie na hřebeni Hadriánova valu (UNESCO) — kasárna, sýpky i nejstarší dochované latríny v zemi. Val se odsud vlní po útesech Whin Sill jako kamenný had; krátká procházka po hradbě je povinnost.', 55.0130, -2.3310, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hadrians%20Wall%20from%20Housesteads1%20crop.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hadrians%20Wall%20from%20Housesteads1%20crop.jpg"}'::text[], 0),
    (v_route, 'Alnwick Castle', 'Druhý největší obývaný hrad Anglie, sídlo vévodů z Northumberlandu — filmové Bradavice, kde Harry Potter poprvé letěl na koštěti. Vedle hradu vyrostla velkolepá zahrada Alnwick Garden s jedovou zahradou za mřížemi.', 55.4156, -1.7060, 'https://commons.wikimedia.org/wiki/Special:FilePath/Alnwick%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Alnwick%20Castle.jpg"}'::text[], 1),
    (v_route, 'Restaurace: The Jolly Fisherman (Craster)', 'Hospoda nad miniaturním přístavem proslulá krabí polévkou a výhledem na moře — Craster je domovem legendárních uzených sleďů (kippers) z udírny rodiny Robsonů, funguje tu už od roku 1856. Odsud vede pobřežní pěšina ke zřícenině Dunstanburgh.', 55.4720, -1.5930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Craster%20Harbour.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Craster%20Harbour.jpg"}'::text[], 2),
    (v_route, 'Dunstanburgh Castle', 'Rozeklaná zřícenina hradu ze 14. století na osamělém výběžku, kam nevede žádná silnice — jen půlhodinová procházka po pobřeží z Crasteru mezi pasoucími se ovcemi. Jedna z nejromantičtějších siluet Anglie, milovaná malířem Turnerem.', 55.4900, -1.5940, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dunstanburgh%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dunstanburgh%20Castle.jpg"}'::text[], 3),
    (v_route, 'Bamburgh Castle', 'Mohutný hrad na čedičové skále přímo nad plážemi a dunami — bývalé sídlo králů Northumbrie a dnes jedna z nejfotogeničtějších pevností Británie. Silnice podél pláže nabízí ten nejlepší pohled; ve vsi má muzeum viktoriánská hrdinka Grace Darling.', 55.6090, -1.7150, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamburgh%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bamburgh%20Castle.jpg"}'::text[], 4),
    (v_route, 'Lindisfarne (Holy Island)', 'Svatý ostrov, kolébka anglického křesťanství s klášterem vypleněným Vikingy roku 793 a hrádkem na kuželové skále. Přístupová silnice po hrázi se dvakrát denně noří pod příliv — přejíždějte JEN v publikovaných bezpečných časech, uvízlá auta tu tahají každý rok.', 55.6805, -1.8010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lindisfarne%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lindisfarne%20Castle.jpg"}'::text[], 5);

  -- Isle of Man – okruh TT Mountain Course
  delete from public.routes where name = 'Isle of Man – okruh TT Mountain Course' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Isle of Man – okruh TT Mountain Course', 'Svatá pouť každého motorkáře: objet 60 km dlouhý Mountain Course, na kterém se od roku 1907 jezdí nejslavnější a nejnebezpečnější silniční závod světa — Isle of Man TT. Od tribun TT Grandstand v Douglasu projedete Ballacraine a Kirk Michael, skočíte (pomalu!) přes hrbatý mostek v Ballaugh, otočíte se na náměstí v Ramsey a vystoupáte horským úsekem kolem Snaefellu k legendární zatáčce Creg-ny-Baa. Na ostrov se dostanete trajektem z Liverpoolu nebo Heyshamu; jezdí se VLEVO a na horském úseku mimo obce NENÍ obecný rychlostní limit — o to větší sebekázeň je na místě, silnice je obousměrná a zrádná. Mimo závodní týdny (přelom května a června) je okruh příjemně prázdný; přidejte si odbočku k obřímu vodnímu kolu v Laxey a k hradu Peel. Počasí se nad Snaefellem mění bleskově.', 'loop', 105, 180, 'medium',
     '[{"lat": 54.1670, "lng": -4.4680, "label": "Start: Douglas (TT Grandstand)"}, {"lat": 54.3110, "lng": -4.5430, "label": "Ballaugh Bridge"}, {"lat": 54.3220, "lng": -4.3810, "label": "Ramsey"}, {"lat": 54.2652, "lng": -4.4620, "label": "Bungalow (Snaefell)"}, {"lat": 54.1953, "lng": -4.4384, "label": "Creg-ny-Baa"}, {"lat": 54.2360, "lng": -4.4010, "label": "Laxey"}, {"lat": 54.1670, "lng": -4.4680, "label": "Cíl: Douglas"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.1670,-4.4680&destination=54.1670,-4.4680&travelmode=driving&waypoints=54.3110,-4.5430%7C54.3220,-4.3810%7C54.2652,-4.4620%7C54.1953,-4.4384%7C54.2360,-4.4010', 'https://commons.wikimedia.org/wiki/Special:FilePath/Douglas%20Isle%20of%20Man.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Douglas%20Isle%20of%20Man.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ballaugh%20Bridge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ramsey%20Isle%20of%20Man.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Snaefell%20Mountain%20Railway.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Creg-ny-Baa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Laxey%20Wheel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Peel%20Castle.jpg"}'::text[], '{"TT Grandstand (Douglas)","Ballaugh Bridge","Ramsey","Snaefell Mountain Road (Bungalow)","Restaurace: Creg-ny-Baa","Laxey Wheel","Peel Castle"}'::text[], '{"GB","IM"}'::text[], false, 3990, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'TT Grandstand (Douglas)', 'Start a cíl závodu TT na Glencrutchery Road — tribuny, ručně obsluhovaná výsledková tabule a památník jezdců. Hned vedle je pomník legendárního Joeyho Dunlopa; tady začíná i vaše kolo okruhu.', 54.1670, -4.4680, 'https://commons.wikimedia.org/wiki/Special:FilePath/Douglas%20Isle%20of%20Man.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Douglas%20Isle%20of%20Man.jpg"}'::text[], 0),
    (v_route, 'Ballaugh Bridge', 'Hrbatý kamenný mostek, na kterém závodníci TT létají metry vysoko — nejslavnější skok okruhu. V civilním provozu přejíždějte krokem; hned u mostu je hospoda Raven, odkud se skoky při závodech sledují nejlépe.', 54.3110, -4.5430, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ballaugh%20Bridge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ballaugh%20Bridge.jpg"}'::text[], 1),
    (v_route, 'Ramsey', 'Druhé největší město ostrova s přístavem a proslulou vlásenkou Ramsey Hairpin, kde okruh začíná stoupat do hor. Na náměstí Parliament Square se při závodech tvoří legendární atmosféra; dobrá zastávka na kávu před horským úsekem.', 54.3220, -4.3810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ramsey%20Isle%20of%20Man.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ramsey%20Isle%20of%20Man.jpg"}'::text[], 2),
    (v_route, 'Snaefell Mountain Road (Bungalow)', 'Nejrychlejší část okruhu přes úbočí hory Snaefell (621 m) — na Bungalow kříží silnici historická horská tramvaj, kterou se dá vyjet až na vrchol s výhledem na „sedm království". Mimo obce tu neplatí obecný rychlostní limit, přesto: hlavu chladnou.', 54.2652, -4.4620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Snaefell%20Mountain%20Railway.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Snaefell%20Mountain%20Railway.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Creg-ny-Baa', 'Legendární hospoda v pravotočivé zatáčce sjezdu z hor, jedno z nejslavnějších diváckých míst TT — jídlo s výhledem přímo na trať. Burger „TT" a manská specialita queenies (hřebenatky) jsou sázka na jistotu.', 54.1953, -4.4384, 'https://commons.wikimedia.org/wiki/Special:FilePath/Creg-ny-Baa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Creg-ny-Baa.jpg"}'::text[], 4),
    (v_route, 'Laxey Wheel', 'Největší funkční vodní kolo světa „Lady Isabella" (průměr 22 m) z roku 1854, které odvodňovalo doly na zinek a olovo. Krátká odbočka z okruhu; z Laxey jezdí na Snaefell i horská železnice.', 54.2360, -4.4010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Laxey%20Wheel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Laxey%20Wheel.jpg"}'::text[], 5),
    (v_route, 'Peel Castle', 'Rozlehlá hradní zřícenina Vikingů a keltských svatých na ostrůvku St Patrick''s Isle nad rybářským Peelem na západním pobřeží. Ochutnejte místní uzenáče a manskou zmrzlinu na nábřeží; západy slunce jsou odsud nejhezčí na ostrově.', 54.2261, -4.6980, 'https://commons.wikimedia.org/wiki/Special:FilePath/Peel%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Peel%20Castle.jpg"}'::text[], 6);

  -- Anglie – Kent a Sussex, bílé útesy
  delete from public.routes where name = 'Anglie – Kent a Sussex, bílé útesy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Anglie – Kent a Sussex, bílé útesy', 'Pobřežní cesta „zahradou Anglie" z katedrálního Canterbury do bohémského Brightonu, po trase křídových útesů, chmelnic a středověkých přístavů. Nad Doverem se projdete po hraně slavných bílých útesů s výhledem na Francii, ve středověkém Rye zaparkujete pod hrázděnými domy dlážděné Mermaid Street a přes větrné mysy Beachy Head a Seven Sisters dojedete na promenádu v Brightonu. Silnice jsou nenáročné a scenérie velkolepé — ideální trasa na první seznámení s ježděním VLEVO, klidně hned po příjezdu trajektem či Eurotunelem do Doveru. Pozor na hustý provoz kolem přístavů a na silný boční vítr na útesech; k okrajům útesů nechoďte, křída se bortí. Krásné celoročně, nejlépe květen–září.', 'poi', 185, 280, 'easy',
     '[{"lat": 51.2798, "lng": 1.0830, "label": "Start: Canterbury"}, {"lat": 51.1340, "lng": 1.3280, "label": "Dover"}, {"lat": 50.9500, "lng": 0.7330, "label": "Rye"}, {"lat": 50.7373, "lng": 0.2529, "label": "Beachy Head"}, {"lat": 50.7590, "lng": 0.1530, "label": "Seven Sisters"}, {"lat": 50.8225, "lng": -0.1372, "label": "Cíl: Brighton"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.2798,1.0830&destination=50.8225,-0.1372&travelmode=driving&waypoints=51.1340,1.3280%7C50.9500,0.7330%7C50.7373,0.2529%7C50.7590,0.1530', 'https://commons.wikimedia.org/wiki/Special:FilePath/Canterbury%20Cathedral%20-%20Portal%20Nave%20Cross-spire.jpeg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Canterbury%20Cathedral%20-%20Portal%20Nave%20Cross-spire.jpeg","https://commons.wikimedia.org/wiki/Special:FilePath/White%20cliffs%20of%20dover%2009%202004.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dover%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mermaid%20Street,%20Rye.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rye,%20East%20Sussex.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Beachy%20Head%20and%20Lighthouse,%20East%20Sussex,%20England%20-%20April%202010.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Seven%20Sisters%20cliffs.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brighton%20Palace%20Pier.jpg"}'::text[], '{"Canterbury – katedrála","Bílé útesy doverské","Dover Castle","Rye – Mermaid Street","Restaurace: The Mermaid Inn (Rye)","Beachy Head","Seven Sisters","Brighton Palace Pier"}'::text[], '{"GB"}'::text[], false, 4000, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Canterbury – katedrála', 'Matka anglikánské církve a cíl poutníků z Canterburských povídek (UNESCO) — gotická katedrála, kde byl roku 1170 zavražděn arcibiskup Tomáš Becket. Historické centrum s hrázděnými domy se nejlépe projde pěšky, motorku nechte na záchytném parkovišti.', 51.2798, 1.0830, 'https://commons.wikimedia.org/wiki/Special:FilePath/Canterbury%20Cathedral%20-%20Portal%20Nave%20Cross-spire.jpeg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Canterbury%20Cathedral%20-%20Portal%20Nave%20Cross-spire.jpeg"}'::text[], 0),
    (v_route, 'Bílé útesy doverské', 'Symbol Anglie — křídová stěna vysoká přes sto metrů, za jasného dne s výhledem přes Kanál až na francouzské pobřeží. Od návštěvnického centra vede pěšina po hraně k majáku South Foreland; k okraji útesů se nepřibližujte.', 51.1340, 1.3280, 'https://commons.wikimedia.org/wiki/Special:FilePath/White%20cliffs%20of%20dover%2009%202004.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/White%20cliffs%20of%20dover%2009%202004.jpg"}'::text[], 1),
    (v_route, 'Dover Castle', '„Klíč k Anglii" — největší anglický hrad, strážící úžinu od dob Jindřicha II. V křídě pod ním se skrývají válečné tunely, odcizené velení evakuace z Dunkerku v roce 1940; expozice patří k nejlepším v zemi.', 51.1290, 1.3210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dover%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dover%20Castle.jpg"}'::text[], 2),
    (v_route, 'Rye – Mermaid Street', 'Dlážděná ulička lemovaná hrázděnými domy z 15. století — jedna z nejfotogeničtějších ulic Anglie v městečku bývalých pašeráků. Rye kdysi stálo přímo u moře; dnes z citadely shlížíte na míle mokřadů plných ovcí.', 50.9497, 0.7340, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mermaid%20Street,%20Rye.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mermaid%20Street,%20Rye.jpg"}'::text[], 3),
    (v_route, 'Restaurace: The Mermaid Inn (Rye)', 'Legendární hostinec se sklepy z roku 1156 a přestavbou z roku 1420 — doupě pašeráckého gangu Hawkhurst, dnes vyhlášená restaurace s krby a duchy podle místních pověstí. Perfektní oběd v polovině trasy.', 50.9500, 0.7330, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rye,%20East%20Sussex.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rye,%20East%20Sussex.jpg"}'::text[], 4),
    (v_route, 'Beachy Head', 'Nejvyšší křídový útes Británie (162 m) s červenobílým majákem u paty stěny — silnice po mysu od Eastbourne je krátká, ale scénicky velkolepá. Na hraně bývá silný vítr, motorku stavějte proti němu a k okraji nechoďte.', 50.7373, 0.2529, 'https://commons.wikimedia.org/wiki/Special:FilePath/Beachy%20Head%20and%20Lighthouse,%20East%20Sussex,%20England%20-%20April%202010.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Beachy%20Head%20and%20Lighthouse,%20East%20Sussex,%20England%20-%20April%202010.jpg"}'::text[], 5),
    (v_route, 'Seven Sisters', 'Sedm zvlněných křídových útesů mezi Cuckmere Haven a Birling Gap — panorama, které filmaři používají místo Doveru, protože je bez lodí a přístavů. Nejlepší pohled je od pobřežních domků u ústí řeky Cuckmere.', 50.7590, 0.1530, 'https://commons.wikimedia.org/wiki/Special:FilePath/Seven%20Sisters%20cliffs.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Seven%20Sisters%20cliffs.jpg"}'::text[], 6),
    (v_route, 'Brighton Palace Pier', 'Viktoriánské zábavní molo z roku 1899 — symbol nejživějšího přímořského města Anglie s promenádou, pouťovými atrakcemi a fish and chips v papíru. Kousek odtud stojí exotický Royal Pavilion s indickými kupolemi; důstojná tečka za trasou.', 50.8160, -0.1370, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brighton%20Palace%20Pier.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brighton%20Palace%20Pier.jpg"}'::text[], 7);

end $$;
