-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — STŘEDNÍ ČECHY (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Brdy a Příbramsko
  delete from public.routes where name = 'Brdy a Příbramsko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Brdy a Příbramsko', 'Okruh nově otevřenou chráněnou krajinnou oblastí Brdy a okolím Příbrami. Lesní silnice bývalého vojenského prostoru, poutní Svatá Hora a zámek Dobříš spojují klid, historii a svěží vzduch nedaleko Prahy. Nejlepší od jara do podzimu; pozor na lesní úseky a zvěř.', 'loop', 150, 210, 'medium',
     '[{"lat": 49.6853, "lng": 14.01, "label": "Start: Příbram"}, {"lat": 49.71, "lng": 13.85, "label": "Brdy – Tok"}, {"lat": 49.7794, "lng": 14.1706, "label": "Dobříš"}, {"lat": 49.6853, "lng": 14.01, "label": "Cíl: Příbram"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.6853,14.01&destination=49.6853,14.01&travelmode=driving&waypoints=49.71,13.85%7C49.7794,14.1706', 'https://commons.wikimedia.org/wiki/Special:FilePath/Svat%C3%A1_Hora_P%C5%99%C3%ADbram.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svat%C3%A1_Hora_P%C5%99%C3%ADbram.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Dob%C5%99%C3%AD%C5%A1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brdy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hornick%C3%A9_muzeum_P%C5%99%C3%ADbram.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Mn%C3%AD%C5%A1ek_pod_Brdy.jpg"}'::text[], '{"Svatá Hora u Příbrami","Zámek Dobříš","Brdy – vrch Tok","Hornické muzeum Příbram","Zámek Mníšek pod Brdy"}'::text[], '{"CZ"}'::text[], false, 2210, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Svatá Hora u Příbrami', 'Nádherný barokní poutní areál s ambity a stříbrným oltářem nad Příbramí, jedno z nejvýznamnějších mariánských poutních míst Čech. Skvost od Dientzenhofera.', 49.6853, 14.0208, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svat%C3%A1_Hora_P%C5%99%C3%ADbram.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svat%C3%A1_Hora_P%C5%99%C3%ADbram.jpg"}'::text[], 0),
    (v_route, 'Zámek Dobříš', 'Elegantní rokokový zámek s francouzskou a anglickou zahradou, sídlo Colloredo-Mansfeldů. Zvaný český Versailles.', 49.7794, 14.1706, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Dob%C5%99%C3%AD%C5%A1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Dob%C5%99%C3%AD%C5%A1.jpg"}'::text[], 1),
    (v_route, 'Brdy – vrch Tok', 'Jedno z nejvyšších míst Brd s vřesovišti v bývalé dopadové ploše, dnes klidná chráněná krajina. Ráj lesních silnic.', 49.71, 13.85, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brdy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brdy.jpg"}'::text[], 2),
    (v_route, 'Hornické muzeum Příbram', 'Největší hornické muzeum v Česku s možností svezení důlním vláčkem. Připomínka stříbrné a uranové minulosti.', 49.6772, 14.0089, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hornick%C3%A9_muzeum_P%C5%99%C3%ADbram.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hornick%C3%A9_muzeum_P%C5%99%C3%ADbram.jpg"}'::text[], 3),
    (v_route, 'Zámek Mníšek pod Brdy', 'Barokní zámek s věžemi na okraji Brd, obklopený lesy. Půvabná zastávka na cestě z Prahy.', 49.8683, 14.2622, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Mn%C3%AD%C5%A1ek_pod_Brdy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Mn%C3%AD%C5%A1ek_pod_Brdy.jpg"}'::text[], 4);

  -- Berounsko a hrady Točník a Žebrák
  delete from public.routes where name = 'Berounsko a hrady Točník a Žebrák' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Berounsko a hrady Točník a Žebrák', 'Okruh Českým krasem a Podbrdskem kolem dvojice hradů nad Žebrákem. Skalnaté údolí Berounky, sklářský Nižbor a medvědi v Berouně nabízí historii i příjemnou jízdu nedaleko Prahy. Nejlepší od jara do podzimu; pozor na turisty u hradů.', 'loop', 130, 180, 'easy',
     '[{"lat": 49.9639, "lng": 14.0722, "label": "Start: Beroun"}, {"lat": 49.876, "lng": 13.897, "label": "Žebrák"}, {"lat": 49.858, "lng": 13.882, "label": "Točník"}, {"lat": 49.9639, "lng": 14.0722, "label": "Cíl: Beroun"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.9639,14.0722&destination=49.9639,14.0722&travelmode=driving&waypoints=49.876,13.897%7C49.858,13.882', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_To%C4%8Dn%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_To%C4%8Dn%C3%ADk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_%C5%BDebr%C3%A1k.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Beroun.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEbor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svat%C3%BD_Jan_pod_Skalou.jpg"}'::text[], '{"Hrad Točník","Hrad Žebrák","Beroun – medvědárium","Sklárna Nižbor","Svatý Jan pod Skalou"}'::text[], '{"CZ"}'::text[], false, 2220, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Točník', 'Královský gotický hrad Václava IV. na skále nad Žebrákem s dochovaným palácem. Působivá dominanta kraje.', 49.858, 13.882, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_To%C4%8Dn%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_To%C4%8Dn%C3%ADk.jpg"}'::text[], 0),
    (v_route, 'Hrad Žebrák', 'Zřícenina staršího hradu pod Točníkem s válcovou věží, romanticky posazená na ostrohu. Dvojice hradů na dohled.', 49.876, 13.897, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_%C5%BDebr%C3%A1k.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_%C5%BDebr%C3%A1k.jpg"}'::text[], 1),
    (v_route, 'Beroun – medvědárium', 'Historické město s medvědy Vojtou, Kubou a Matějem z večerníčku. Příjemná zastávka na náměstí.', 49.9639, 14.0722, 'https://commons.wikimedia.org/wiki/Special:FilePath/Beroun.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Beroun.jpg"}'::text[], 2),
    (v_route, 'Sklárna Nižbor', 'Rukodělná sklárna Rückl s prohlídkou výroby broušeného skla nad Berounkou. Zastávka pro milovníky řemesla.', 49.9944, 14.04, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEbor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEbor.jpg"}'::text[], 3),
    (v_route, 'Svatý Jan pod Skalou', 'Malebná obec s klášterem a vápencovou skálou v srdci Českého krasu. Klidné poutní místo v údolí.', 49.9686, 14.135, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svat%C3%BD_Jan_pod_Skalou.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svat%C3%BD_Jan_pod_Skalou.jpg"}'::text[], 4);

  -- Slapy a Svatojánské proudy
  delete from public.routes where name = 'Slapy a Svatojánské proudy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Slapy a Svatojánské proudy', 'Trasa údolím Vltavy jižně od Prahy podél kaskády přehrad. Hráz Slapské přehrady, rekreační Štěchovice a skalnaté meandry nabízí vodu, výhledy a klikaté silnice nad řekou. Nejlepší od jara do podzimu; pozor na víkendový provoz u vody.', 'poi', 120, 165, 'easy',
     '[{"lat": 49.85, "lng": 14.415, "label": "Start: Štěchovice"}, {"lat": 49.821, "lng": 14.427, "label": "Slapská přehrada – hráz"}, {"lat": 49.78, "lng": 14.4, "label": "Živohošť"}, {"lat": 49.85, "lng": 14.415, "label": "Cíl: Štěchovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.85,14.415&destination=49.85,14.415&travelmode=driving&waypoints=49.821,14.427%7C49.78,14.4', 'https://commons.wikimedia.org/wiki/Special:FilePath/Slapy_dam.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slapy_dam.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0t%C4%9Bchovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svatoj%C3%A1nsk%C3%A9_proudy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vyhl%C3%ADdka_M%C3%A1j.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDivoho%C5%A1%C5%A5.jpg"}'::text[], '{"Slapská přehrada – hráz","Štěchovice","Svatojánské proudy","Vyhlídka Máj (Teletín)","Živohošť"}'::text[], '{"CZ"}'::text[], false, 2230, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Slapská přehrada – hráz', 'Mohutná hráz nejznámější vltavské přehrady, oblíbené rekreační jezero středních Čech. Výhled na vodní hladinu i turbíny.', 49.821, 14.427, 'https://commons.wikimedia.org/wiki/Special:FilePath/Slapy_dam.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slapy_dam.jpg"}'::text[], 0),
    (v_route, 'Štěchovice', 'Rekreační městečko u Vltavy s přístavištěm a nedalekou přehradou. Brána do vltavského kaňonu.', 49.85, 14.415, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0t%C4%9Bchovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0t%C4%9Bchovice.jpg"}'::text[], 1),
    (v_route, 'Svatojánské proudy', 'Bývalé divoké peřeje Vltavy, dnes zklidněné přehradou, s romantickými skalami. Malebná scenérie kaňonu.', 49.835, 14.415, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svatoj%C3%A1nsk%C3%A9_proudy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svatoj%C3%A1nsk%C3%A9_proudy.jpg"}'::text[], 2),
    (v_route, 'Vyhlídka Máj (Teletín)', 'Slavná skalní vyhlídka nad meandrem Vltavy s pohledem na zákrut řeky. Jeden z nejfotografovanějších výhledů Čech.', 49.788, 14.415, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vyhl%C3%ADdka_M%C3%A1j.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vyhl%C3%ADdka_M%C3%A1j.jpg"}'::text[], 3),
    (v_route, 'Živohošť', 'Rekreační osada u Slapského jezera s plážemi a kostelem. Zastávka na koupání a klid.', 49.78, 14.4, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDivoho%C5%A1%C5%A5.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDivoho%C5%A1%C5%A5.jpg"}'::text[], 4);

  -- Podblanicko a hora Blaník
  delete from public.routes where name = 'Podblanicko a hora Blaník' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Podblanicko a hora Blaník', 'Okruh idylickým Podblanickem kolem bájné hory Blaník, kde podle pověsti spí vojsko svatého Václava. Zámek ve Vlašimi, klidné silnice a lesy nabízí pohodovou jízdu opředenou legendou. Nejlepší od jara do podzimu; pozor na zvěř na okresních silnicích.', 'loop', 140, 180, 'easy',
     '[{"lat": 49.706, "lng": 14.899, "label": "Start: Vlašim"}, {"lat": 49.638, "lng": 14.873, "label": "Velký Blaník"}, {"lat": 49.808, "lng": 14.933, "label": "Český Šternberk"}, {"lat": 49.706, "lng": 14.899, "label": "Cíl: Vlašim"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.706,14.899&destination=49.706,14.899&travelmode=driving&waypoints=49.638,14.873%7C49.808,14.933', 'https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%BD_Blan%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%BD_Blan%C3%ADk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Vla%C5%A1im.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_%C4%8Cesk%C3%BD_%C5%A0ternberk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lou%C5%88ovice_pod_Blan%C3%ADkem.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vla%C5%A1im.jpg"}'::text[], '{"Velký Blaník","Zámek a park Vlašim","Hrad Český Šternberk","Louňovice pod Blaníkem","Podblanické muzeum"}'::text[], '{"CZ"}'::text[], false, 2240, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Velký Blaník', 'Bájná zalesněná hora s rozhlednou na vrcholu, kde podle pověsti čeká blanické vojsko na nejtěžší chvíli národa. Symbolický vrchol Čech.', 49.638, 14.873, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%BD_Blan%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%BD_Blan%C3%ADk.jpg"}'::text[], 0),
    (v_route, 'Zámek a park Vlašim', 'Zámek s jedním z nejstarších krajinářských parků v Česku podél řeky Blanice. Příjemná zastávka na procházku.', 49.706, 14.899, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Vla%C5%A1im.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Vla%C5%A1im.jpg"}'::text[], 1),
    (v_route, 'Hrad Český Šternberk', 'Mohutný gotický hrad tyčící se na skalním ostrohu nad Sázavou, v držení rodu Šternberků přes 700 let. Jeden z nejzachovalejších hradů Čech.', 49.808, 14.933, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_%C4%8Cesk%C3%BD_%C5%A0ternberk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_%C4%8Cesk%C3%BD_%C5%A0ternberk.jpg"}'::text[], 2),
    (v_route, 'Louňovice pod Blaníkem', 'Půvabné městečko pod Blaníkem s muzeem a výchozím bodem na horu. Klidná zastávka na úpatí legendy.', 49.628, 14.883, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lou%C5%88ovice_pod_Blan%C3%ADkem.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lou%C5%88ovice_pod_Blan%C3%ADkem.jpg"}'::text[], 3),
    (v_route, 'Podblanické muzeum', 'Muzeum přírody a historie kraje ve Vlašimi. Vhodná zastávka i za nepohody.', 49.706, 14.901, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vla%C5%A1im.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vla%C5%A1im.jpg"}'::text[], 4);

  -- Kokořínsko, Bezděz a Máchův kraj
  delete from public.routes where name = 'Kokořínsko, Bezděz a Máchův kraj' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kokořínsko, Bezděz a Máchův kraj', 'Trasa pískovcovým Kokořínskem a Máchovým krajem plným skal, hradů a rybníků. Dvojvěží hradu Bezděz, tajemná Houska a Máchovo jezero nabízí romantickou přírodu severně od Prahy. Nejlepší od jara do podzimu; pozor na úzké lesní silnice.', 'poi', 160, 210, 'easy',
     '[{"lat": 50.427, "lng": 14.568, "label": "Start: Mělník"}, {"lat": 50.489, "lng": 14.585, "label": "Houska"}, {"lat": 50.539, "lng": 14.72, "label": "Bezděz"}, {"lat": 50.581, "lng": 14.64, "label": "Máchovo jezero"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.427,14.568&destination=50.581,14.64&travelmode=driving&waypoints=50.489,14.585%7C50.539,14.72', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Bezd%C4%9Bz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Bezd%C4%9Bz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Houska.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%A1chovo_jezero.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_M%C4%9Bln%C3%ADk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pokli%C4%8Dky_Koko%C5%99%C3%ADn.jpg"}'::text[], '{"Hrad Bezděz","Hrad Houska","Máchovo jezero","Zámek Mělník a soutok","Pokličky (Kokořínský důl)"}'::text[], '{"CZ"}'::text[], false, 2250, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Bezděz', 'Majestátní raně gotický královský hrad s dvěma věžemi na vrcholu čedičového kužele, dominanta Máchova kraje. Nezapomenutelné výhledy do kraje.', 50.539, 14.72, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Bezd%C4%9Bz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Bezd%C4%9Bz.jpg"}'::text[], 0),
    (v_route, 'Hrad Houska', 'Tajemný gotický hrad opředený legendami o bráně do pekla. Záhadná zastávka uprostřed lesů Kokořínska.', 50.489, 14.585, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Houska.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Houska.jpg"}'::text[], 1),
    (v_route, 'Máchovo jezero', 'Rozlehlé rybniční jezero u Doks, oblíbené rekreační místo opěvané básníkem Máchou. Pláže a projížďky lodí.', 50.581, 14.64, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%A1chovo_jezero.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%A1chovo_jezero.jpg"}'::text[], 2),
    (v_route, 'Zámek Mělník a soutok', 'Renesanční zámek nad soutokem Labe a Vltavy s vinicemi a proslulým vínem. Výhled na spojení dvou řek.', 50.35, 14.474, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_M%C4%9Bln%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_M%C4%9Bln%C3%ADk.jpg"}'::text[], 3),
    (v_route, 'Pokličky (Kokořínský důl)', 'Bizarní pískovcové skalní útvary ve tvaru hub v srdci Kokořínského dolu. Půvabná zastávka na stezce.', 50.462, 14.56, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pokli%C4%8Dky_Koko%C5%99%C3%ADn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pokli%C4%8Dky_Koko%C5%99%C3%ADn.jpg"}'::text[], 4);

  -- Český ráj – skály a hrady
  delete from public.routes where name = 'Český ráj – skály a hrady' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Český ráj – skály a hrady', 'Okruh geoparkem Český ráj plným skalních měst a hradů na severu středních Čech. Zřícenina Trosky, Hrubá Skála a Prachovské skály nabízí dramatickou pískovcovou scenérii a klikaté silnice. Nejlepší od jara do podzimu; pozor na turisty a úzké silnice.', 'loop', 150, 210, 'medium',
     '[{"lat": 50.587, "lng": 15.16, "label": "Start: Turnov"}, {"lat": 50.514, "lng": 15.229, "label": "Trosky"}, {"lat": 50.482, "lng": 15.315, "label": "Prachovské skály"}, {"lat": 50.587, "lng": 15.16, "label": "Cíl: Turnov"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.587,15.16&destination=50.587,15.16&travelmode=driving&waypoints=50.514,15.229%7C50.482,15.315', 'https://commons.wikimedia.org/wiki/Special:FilePath/Trosky.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trosky.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrub%C3%A1_Sk%C3%A1la.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prachovsk%C3%A9_sk%C3%A1ly.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Kost.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Vald%C5%A1tejn.jpg"}'::text[], '{"Hrad Trosky","Hrubá Skála","Prachovské skály","Hrad Kost","Hrad Valdštejn"}'::text[], '{"CZ"}'::text[], false, 2260, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Trosky', 'Ikonická zřícenina se dvěma věžemi Baba a Panna na čedičových sopouchech, symbol Českého ráje. Nejznámější silueta kraje.', 50.514, 15.229, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trosky.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trosky.jpg"}'::text[], 0),
    (v_route, 'Hrubá Skála', 'Zámek na pískovcových skalách nad skalním městem s vyhlídkami. Půvabná zastávka v srdci Českého ráje.', 50.542, 15.196, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrub%C3%A1_Sk%C3%A1la.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrub%C3%A1_Sk%C3%A1la.jpg"}'::text[], 1),
    (v_route, 'Prachovské skály', 'Rozlehlé skalní město s věžemi, roklemi a vyhlídkami u Jičína. Ráj turistů i horolezců.', 50.482, 15.315, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prachovsk%C3%A9_sk%C3%A1ly.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prachovsk%C3%A9_sk%C3%A1ly.jpg"}'::text[], 2),
    (v_route, 'Hrad Kost', 'Výborně zachovalý gotický hrad v údolí Plakánku, jeden z nejmohutnějších v Čechách. Působivá pevnost mezi rybníky.', 50.514, 15.098, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Kost.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Kost.jpg"}'::text[], 3),
    (v_route, 'Hrad Valdštejn', 'Nejstarší hrad Českého ráje na pískovcových skalách s romantickými mosty. Kolébka rodu Valdštejnů.', 50.588, 15.176, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Vald%C5%A1tejn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Vald%C5%A1tejn.jpg"}'::text[], 4);

  -- Kutnohorsko a Železné hory
  delete from public.routes where name = 'Kutnohorsko a Železné hory' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kutnohorsko a Železné hory', 'Okruh stříbrnou Kutnou Horou a zvlněnými Železnými horami. Kostnice v Sedlci, romantický zámek Žleby a klidné silnice nabízí historii i pohodovou jízdu východně od Prahy. Nejlepší od jara do podzimu; pozor na turisty v Kutné Hoře.', 'loop', 140, 180, 'easy',
     '[{"lat": 49.961, "lng": 15.288, "label": "Start: Kutná Hora – Sedlec"}, {"lat": 49.891, "lng": 15.489, "label": "Žleby"}, {"lat": 49.82, "lng": 15.56, "label": "Železné hory"}, {"lat": 49.961, "lng": 15.288, "label": "Cíl: Kutná Hora"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.961,15.288&destination=49.961,15.288&travelmode=driving&waypoints=49.891,15.489%7C49.82,15.56', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sedlec_Ossuary.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sedlec_Ossuary.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_%C5%BDleby.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vla%C5%A1sk%C3%BD_dv%C5%AFr.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ka%C5%88k.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pa%C5%99%C3%AD%C5%BEov.jpg"}'::text[], '{"Kostnice v Sedlci","Zámek Žleby","Vlašský dvůr","Kaňk","Přehrada Pařížov"}'::text[], '{"CZ"}'::text[], false, 2270, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kostnice v Sedlci', 'Proslulá kaple vyzdobená lidskými kostmi s ohromujícím lustrem, UNESCO památka. Ojedinělý a působivý zážitek.', 49.961, 15.288, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sedlec_Ossuary.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sedlec_Ossuary.jpg"}'::text[], 0),
    (v_route, 'Zámek Žleby', 'Romantický novogotický zámek s dochovanými interiéry, sbírkou zbraní a oborou. Pohádková zastávka v Železných horách.', 49.891, 15.489, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_%C5%BDleby.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_%C5%BDleby.jpg"}'::text[], 1),
    (v_route, 'Vlašský dvůr', 'Bývalá královská mincovna a sídlo, kde se razil pražský groš. Srdce stříbrné slávy Kutné Hory.', 49.948, 15.267, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vla%C5%A1sk%C3%BD_dv%C5%AFr.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vla%C5%A1sk%C3%BD_dv%C5%AFr.jpg"}'::text[], 2),
    (v_route, 'Kaňk', 'Vrch nad Kutnou Horou s výhledem na město a pozůstatky dolování stříbra. Klidná zastávka nad městem.', 49.972, 15.29, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ka%C5%88k.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ka%C5%88k.jpg"}'::text[], 3),
    (v_route, 'Přehrada Pařížov', 'Malebná kamenná přehrada na Doubravě v Železných horách. Osvěžující zastávka v přírodě.', 49.831, 15.556, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pa%C5%99%C3%AD%C5%BEov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pa%C5%99%C3%AD%C5%BEov.jpg"}'::text[], 4);

  -- Polabí a jeho zámky
  delete from public.routes where name = 'Polabí a jeho zámky' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Polabí a jeho zámky', 'Trasa rovinatým Polabím východně od Prahy plným zámků a lázní. Lázeňské Poděbrady, romantický Loučeň a skanzen v Přerově nad Labem nabízí pohodovou jízdu a historii u řeky Labe. Nejlepší od jara do podzimu; pozor na provoz ve městech.', 'poi', 150, 180, 'easy',
     '[{"lat": 50.142, "lng": 15.119, "label": "Start: Poděbrady"}, {"lat": 50.288, "lng": 15.017, "label": "Loučeň"}, {"lat": 50.169, "lng": 14.803, "label": "Přerov nad Labem"}, {"lat": 50.142, "lng": 15.119, "label": "Cíl: Poděbrady"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.142,15.119&destination=50.142,15.119&travelmode=driving&waypoints=50.288,15.017%7C50.169,14.803', 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Pod%C4%9Bbrady.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Pod%C4%9Bbrady.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Lou%C4%8De%C5%88.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skanzen_P%C5%99erov_nad_Labem.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nymburk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Lys%C3%A1_nad_Labem.jpg"}'::text[], '{"Zámek a lázně Poděbrady","Zámek Loučeň","Skanzen Přerov nad Labem","Nymburk – hradby","Lysá nad Labem"}'::text[], '{"CZ"}'::text[], false, 2280, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek a lázně Poděbrady', 'Renesanční zámek na břehu Labe s lázeňskou kolonádou a rodištěm krále Jiřího. Klidná zastávka u řeky.', 50.142, 15.119, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Pod%C4%9Bbrady.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Pod%C4%9Bbrady.jpg"}'::text[], 0),
    (v_route, 'Zámek Loučeň', 'Barokní zámek s rozlehlým parkem plným bludišť a labyrintů. Zábavná zastávka pro celou posádku.', 50.288, 15.017, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Lou%C4%8De%C5%88.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Lou%C4%8De%C5%88.jpg"}'::text[], 1),
    (v_route, 'Skanzen Přerov nad Labem', 'Nejstarší národopisné muzeum v přírodě v Čechách s roubenými staveními Polabí. Cesta do venkovské minulosti.', 50.169, 14.803, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skanzen_P%C5%99erov_nad_Labem.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skanzen_P%C5%99erov_nad_Labem.jpg"}'::text[], 2),
    (v_route, 'Nymburk – hradby', 'Historické město s dochovanými cihlovými hradbami na břehu Labe, spjaté s Bohumilem Hrabalem. Příjemná zastávka.', 50.186, 15.041, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nymburk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nymburk.jpg"}'::text[], 3),
    (v_route, 'Lysá nad Labem', 'Barokní zámek se sochařskou výzdobou a rozlehlým parkem. Elegantní zastávka v Polabí.', 50.201, 14.834, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Lys%C3%A1_nad_Labem.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Lys%C3%A1_nad_Labem.jpg"}'::text[], 4);

  -- Rakovnicko a Lánsko
  delete from public.routes where name = 'Rakovnicko a Lánsko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rakovnicko a Lánsko', 'Okruh lesnatým Rakovnickem a Křivoklátskem na západě středních Čech. Prezidentské Lány, údolí Berounky a chmelařský Rakovník nabízí klidnou jízdu zelenými lesy. Nejlepší od jara do podzimu; pozor na zvěř na lesních silnicích.', 'loop', 130, 180, 'easy',
     '[{"lat": 50.104, "lng": 13.734, "label": "Start: Rakovník"}, {"lat": 50.124, "lng": 13.951, "label": "Lány"}, {"lat": 50.033, "lng": 13.933, "label": "Zbečno"}, {"lat": 50.104, "lng": 13.734, "label": "Cíl: Rakovník"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.104,13.734&destination=50.104,13.734&travelmode=driving&waypoints=50.124,13.951%7C50.033,13.933', 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1ny.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1ny.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rakovn%C3%ADk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zbe%C4%8Dno.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kru%C5%A1ovice.jpg"}'::text[], '{"Lány – zámek a hrob T. G. Masaryka","Rakovník","Zbečno a Hamousův statek","Křivoklátsko – Nezabudické skály","Krušovice – pivovar"}'::text[], '{"CZ"}'::text[], false, 2290, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lány – zámek a hrob T. G. Masaryka', 'Prezidentský zámek s parkem a nedalekým lesním hřbitovem, kde odpočívá první prezident. Pietní zastávka v lesích.', 50.124, 13.951, 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1ny.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1ny.jpg"}'::text[], 0),
    (v_route, 'Rakovník', 'Historické chmelařské město s dvojicí bran a náměstím. Klidná výchozí zastávka kraje.', 50.104, 13.734, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rakovn%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rakovn%C3%ADk.jpg"}'::text[], 1),
    (v_route, 'Zbečno a Hamousův statek', 'Vesnice v údolí Berounky s dochovaným roubeným statkem. Ukázka venkovské architektury Křivoklátska.', 50.033, 13.933, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zbe%C4%8Dno.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zbe%C4%8Dno.jpg"}'::text[], 2),
    (v_route, 'Křivoklátsko – Nezabudické skály', 'Skalnaté stráně nad meandrem Berounky v chráněné krajinné oblasti. Klidná zastávka nad řekou.', 50.01, 13.895, 'https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg"}'::text[], 3),
    (v_route, 'Krušovice – pivovar', 'Tradiční pivovar v srdci Rakovnicka s dlouhou historií vaření piva. Zastávka pro spolujezdce.', 50.171, 13.862, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kru%C5%A1ovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kru%C5%A1ovice.jpg"}'::text[], 4);

  -- Křivoklátské lesy a Nižbor
  delete from public.routes where name = 'Křivoklátské lesy a Nižbor' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Křivoklátské lesy a Nižbor', 'Okruh hlubokými lesy chráněné krajinné oblasti Křivoklátsko podél řeky Berounky. Skryjská jezírka s trilobity, keltský Nižbor a klikaté lesní silnice nabízí přírodu a klid nedaleko Prahy. Nejlepší od jara do podzimu; pozor na úzké lesní silnice a zvěř.', 'loop', 140, 180, 'medium',
     '[{"lat": 49.9944, "lng": 14.043, "label": "Start: Nižbor"}, {"lat": 49.945, "lng": 13.752, "label": "Skryje"}, {"lat": 50.047, "lng": 13.872, "label": "Roztoky u Křivoklátu"}, {"lat": 49.9944, "lng": 14.043, "label": "Cíl: Nižbor"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.9944,14.043&destination=49.9944,14.043&travelmode=driving&waypoints=49.945,13.752%7C50.047,13.872', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEbor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEbor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skryjsk%C3%A1_jez%C3%ADrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Zbiroh.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg"}'::text[], '{"Keltské oppidum Nižbor","Skryjská jezírka","Roztoky u Křivoklátu","Zbiroh – zámek","Čertova skála u Berounky"}'::text[], '{"CZ"}'::text[], false, 2300, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Keltské oppidum Nižbor', 'Keltské informační centrum na místě dávného osídlení nad Berounkou. Cesta ke kořenům české historie.', 49.9944, 14.043, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEbor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEbor.jpg"}'::text[], 0),
    (v_route, 'Skryjská jezírka', 'Romantická jezírka s vodopádem v hlubokých lesích Křivoklátska, proslulá nálezy trilobitů. Idylická zastávka v přírodě.', 49.945, 13.752, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skryjsk%C3%A1_jez%C3%ADrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skryjsk%C3%A1_jez%C3%ADrka.jpg"}'::text[], 1),
    (v_route, 'Roztoky u Křivoklátu', 'Vesnice v údolí Berounky pod křivoklátskými lesy s železniční zastávkou. Výchozí bod do divočiny.', 50.047, 13.872, 'https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg"}'::text[], 2),
    (v_route, 'Zbiroh – zámek', 'Zámek na skále, kde Alfons Mucha maloval Slovanskou epopej. Historická zastávka na okraji kraje.', 49.858, 13.768, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Zbiroh.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Zbiroh.jpg"}'::text[], 3),
    (v_route, 'Čertova skála u Berounky', 'Skalní útvar nad meandrem řeky s výhledem do křivoklátských lesů. Klidná vyhlídka na stezce.', 49.96, 13.87, 'https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Berounka.jpg"}'::text[], 4);

end $$;
