-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — DÁNSKO (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Skagen a špička Jutska
  delete from public.routes where name = 'Skagen a špička Jutska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Skagen a špička Jutska', 'Pohodová vyjížďka na nejsevernější cíp Dánska, kde se stýkají dvě moře. Malířský Skagen, putující duna a mys Grenen nabízí zvláštní severské světlo a rovné pobřežní silnice. Nejlepší od května do září; pozor na vítr a písek na silnici.', 'loop', 150, 210, 'easy',
     '[{"lat": 57.7211, "lng": 10.5836, "label": "Start: Skagen"}, {"lat": 57.7444, "lng": 10.6633, "label": "Grenen"}, {"lat": 57.6014, "lng": 10.3944, "label": "Råbjerg Mile"}, {"lat": 57.7211, "lng": 10.5836, "label": "Cíl: Skagen"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=57.7211,10.5836&destination=57.7211,10.5836&travelmode=driving&waypoints=57.7444,10.6633%7C57.6014,10.3944', 'https://commons.wikimedia.org/wiki/Special:FilePath/Skagen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skagen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grenen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%A5bjerg_Mile.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Den_Tilsandede_Kirke.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rubjerg_Knude_Fyr.jpg"}'::text[], '{"Skagen","Grenen","Råbjerg Mile","Zapískovaný kostel","Maják Rubjerg Knude"}'::text[], '{"DK"}'::text[], false, 3510, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Skagen', 'Půvabné rybářské a malířské městečko se žlutými domky a zvláštním severským světlem, jež lákalo umělce. Srdce nejsevernějšího Jutska.', 57.7211, 10.5836, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skagen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skagen.jpg"}'::text[], 0),
    (v_route, 'Grenen', 'Písečná kosa na samém cípu Dánska, kde se srážejí vlny Severního a Baltského moře. Symbolický konec pevniny.', 57.7444, 10.6633, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grenen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grenen.jpg"}'::text[], 1),
    (v_route, 'Råbjerg Mile', 'Největší putující písečná duna severní Evropy, pomalu se sunoucí krajinou. Ojedinělý přírodní úkaz.', 57.6014, 10.3944, 'https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%A5bjerg_Mile.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%A5bjerg_Mile.jpg"}'::text[], 2),
    (v_route, 'Zapískovaný kostel', 'Věž kostela zaváta pískem, jediné, co zbylo po zaniklém kostele u Skagenu. Připomínka síly písečných dun.', 57.7239, 10.5406, 'https://commons.wikimedia.org/wiki/Special:FilePath/Den_Tilsandede_Kirke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Den_Tilsandede_Kirke.jpg"}'::text[], 3),
    (v_route, 'Maják Rubjerg Knude', 'Osamělý maják na okraji písečného útesu, jenž musel být kvůli erozi přesunut. Dramatická scenérie západního pobřeží.', 57.4494, 9.7756, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rubjerg_Knude_Fyr.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rubjerg_Knude_Fyr.jpg"}'::text[], 4);

  -- Divoké západní pobřeží Jutska
  delete from public.routes where name = 'Divoké západní pobřeží Jutska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Divoké západní pobřeží Jutska', 'Trasa podél větrné pláže Severního moře na západě Jutska. Nekonečné duny, fjord Ringkøbing, rybářské přístavy a bunkry Atlantického valu nabízí syrovou krásu a rovné silnice. Nejlepší od jara do podzimu; pozor na silný vítr a písek.', 'poi', 170, 225, 'easy',
     '[{"lat": 56.09, "lng": 8.2436, "label": "Start: Ringkøbing"}, {"lat": 55.9992, "lng": 8.1258, "label": "Hvide Sande"}, {"lat": 55.5578, "lng": 8.0794, "label": "Blåvand"}, {"lat": 56.09, "lng": 8.2436, "label": "Cíl: Ringkøbing"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=56.09,8.2436&destination=56.09,8.2436&travelmode=driving&waypoints=55.9992,8.1258%7C55.5578,8.0794', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ringk%C3%B8bing.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ringk%C3%B8bing.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hvide_Sande.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bl%C3%A5vand.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bovbjerg_Fyr.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tipperne.jpg"}'::text[], '{"Ringkøbing","Hvide Sande","Blåvand a maják","Bovbjerg Fyr","Tipperne"}'::text[], '{"DK"}'::text[], false, 3520, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Ringkøbing', 'Půvabné městečko na břehu stejnojmenného fjordu s dlážděným náměstím. Klidná zastávka u vody na západě.', 56.09, 8.2436, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ringk%C3%B8bing.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ringk%C3%B8bing.jpg"}'::text[], 0),
    (v_route, 'Hvide Sande', 'Rušný rybářský přístav na úzké kose mezi fjordem a mořem, ráj surfařů. Zastávka na čerstvé ryby.', 55.9992, 8.1258, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hvide_Sande.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hvide_Sande.jpg"}'::text[], 1),
    (v_route, 'Blåvand a maják', 'Nejzápadnější bod Dánska s majákem, dunami a betonovými bunkry proměněnými v umění. Nekonečné pláže.', 55.5578, 8.0794, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bl%C3%A5vand.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bl%C3%A5vand.jpg"}'::text[], 2),
    (v_route, 'Bovbjerg Fyr', 'Červený maják na jílovém útesu nad Severním mořem s výhledem na pobřeží. Ikonická zastávka západu.', 56.5303, 8.1706, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bovbjerg_Fyr.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bovbjerg_Fyr.jpg"}'::text[], 3),
    (v_route, 'Tipperne', 'Ptačí rezervace na jižním konci fjordu Ringkøbing, ráj tažného ptactva. Klidné místo pro milovníky přírody.', 55.85, 8.22, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tipperne.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tipperne.jpg"}'::text[], 4);

  -- Křídové útesy Møns Klint
  delete from public.routes where name = 'Křídové útesy Møns Klint' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Křídové útesy Møns Klint', 'Okruh jihovýchodním ostrovem Møn se slavnými bílými útesy. Křídové stěny padající do tyrkysového moře, kostely s freskami a temná obloba nabízí neobvyklou dánskou scenérii. Nejlepší od jara do podzimu; pozor na turisty u útesů.', 'loop', 140, 195, 'easy',
     '[{"lat": 54.9856, "lng": 12.2842, "label": "Start: Stege"}, {"lat": 54.9694, "lng": 12.5411, "label": "Møns Klint"}, {"lat": 54.9639, "lng": 12.42, "label": "Elmelunde"}, {"lat": 54.9856, "lng": 12.2842, "label": "Cíl: Stege"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.9856,12.2842&destination=54.9856,12.2842&travelmode=driving&waypoints=54.9694,12.5411%7C54.9639,12.42', 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%B8ns_Klint.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%B8ns_Klint.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stege.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Elmelunde_Kirke.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Liselund.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/GeoCenter_M%C3%B8ns_Klint.jpg"}'::text[], '{"Møns Klint","Stege","Kostel Elmelunde","Liselund","GeoCenter Møns Klint"}'::text[], '{"DK"}'::text[], false, 3530, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Møns Klint', 'Oslnivě bílé křídové útesy vysoké až 128 m padající do tyrkysového Baltu. Nejdramatičtější pobřeží Dánska.', 54.9694, 12.5411, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%B8ns_Klint.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%B8ns_Klint.jpg"}'::text[], 0),
    (v_route, 'Stege', 'Hlavní městečko ostrova Møn se středověkou bránou a přístavem. Klidná zastávka s dánskou atmosférou.', 54.9856, 12.2842, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stege.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stege.jpg"}'::text[], 1),
    (v_route, 'Kostel Elmelunde', 'Bílý kostel s proslulými středověkými freskami mistra z Elmelunde. Klenot ostrovní gotiky.', 54.9639, 12.42, 'https://commons.wikimedia.org/wiki/Special:FilePath/Elmelunde_Kirke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Elmelunde_Kirke.jpg"}'::text[], 2),
    (v_route, 'Liselund', 'Romantický zámeček s doškovou střechou v anglickém parku u útesů. Idylická zastávka mezi stromy.', 54.9756, 12.5203, 'https://commons.wikimedia.org/wiki/Special:FilePath/Liselund.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Liselund.jpg"}'::text[], 3),
    (v_route, 'GeoCenter Møns Klint', 'Moderní návštěvnické centrum vysvětlující vznik útesů a geologii ostrova. Vhodné i za nepohody.', 54.97, 12.53, 'https://commons.wikimedia.org/wiki/Special:FilePath/GeoCenter_M%C3%B8ns_Klint.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/GeoCenter_M%C3%B8ns_Klint.jpg"}'::text[], 4);

  -- Ostrov Fyn a zámek Egeskov
  delete from public.routes where name = 'Ostrov Fyn a zámek Egeskov' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Ostrov Fyn a zámek Egeskov', 'Okruh zeleným ostrovem Fyn, zahradou Dánska. Renesanční vodní zámek Egeskov, rodné město H. C. Andersena a přístav Svendborg spojují pohádku, zámky a klidné silnice. Nejlepší od jara do podzimu; pozor na provoz v Odense.', 'loop', 160, 210, 'easy',
     '[{"lat": 55.3959, "lng": 10.3883, "label": "Start: Odense"}, {"lat": 55.1747, "lng": 10.42, "label": "Egeskov"}, {"lat": 55.0603, "lng": 10.6108, "label": "Svendborg"}, {"lat": 55.3959, "lng": 10.3883, "label": "Cíl: Odense"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=55.3959,10.3883&destination=55.3959,10.3883&travelmode=driving&waypoints=55.1747,10.42%7C55.0603,10.6108', 'https://commons.wikimedia.org/wiki/Special:FilePath/Egeskov_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Egeskov_Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Odense.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svendborg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Faaborg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%86r%C3%B8sk%C3%B8bing.jpg"}'::text[], '{"Zámek Egeskov","Odense – dům H. C. Andersena","Svendborg","Faaborg","Ostrov Ærø – Ærøskøbing"}'::text[], '{"DK"}'::text[], false, 3540, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Egeskov', 'Nejlépe zachovaný renesanční vodní zámek Evropy, obklopený zahradami a bludišti. Pohádková dominanta Fynu.', 55.1747, 10.42, 'https://commons.wikimedia.org/wiki/Special:FilePath/Egeskov_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Egeskov_Castle.jpg"}'::text[], 0),
    (v_route, 'Odense – dům H. C. Andersena', 'Rodné město slavného pohádkáře s dlážděnými uličkami a muzeem. Srdce ostrova plné historie.', 55.3959, 10.3883, 'https://commons.wikimedia.org/wiki/Special:FilePath/Odense.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Odense.jpg"}'::text[], 1),
    (v_route, 'Svendborg', 'Živý přístav na jihu Fynu, výchozí bod k jižním ostrůvkům. Příjemná zastávka u vody.', 55.0603, 10.6108, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svendborg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svendborg.jpg"}'::text[], 2),
    (v_route, 'Faaborg', 'Půvabné historické městečko se žlutými domky a zvonicí na jihozápadě ostrova. Idylická zastávka.', 55.0958, 10.2417, 'https://commons.wikimedia.org/wiki/Special:FilePath/Faaborg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Faaborg.jpg"}'::text[], 3),
    (v_route, 'Ostrov Ærø – Ærøskøbing', 'Trajektem dostupné pohádkové městečko s dlážděnými uličkami a barevnými domky. Skok mimo čas.', 54.8867, 10.4108, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%86r%C3%B8sk%C3%B8bing.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%86r%C3%B8sk%C3%B8bing.jpg"}'::text[], 4);

  -- Severní Sjælland – zámky a hrady
  delete from public.routes where name = 'Severní Sjælland – zámky a hrady' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Severní Sjælland – zámky a hrady', 'Trasa nejkrásnějšími zámky severního Sjællandu severně od Kodaně. Hamletův Kronborg, vodní Frederiksborg a katedrála v Roskilde nabízí koncentraci dánské historie na krátké vzdálenosti. Nejlepší od jara do podzimu; pozor na hustý provoz u Kodaně.', 'poi', 130, 180, 'easy',
     '[{"lat": 56.0389, "lng": 12.6142, "label": "Start: Helsingør"}, {"lat": 55.935, "lng": 12.3006, "label": "Hillerød"}, {"lat": 55.6417, "lng": 12.0797, "label": "Roskilde"}, {"lat": 56.0389, "lng": 12.6142, "label": "Cíl: Helsingør"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=56.0389,12.6142&destination=56.0389,12.6142&travelmode=driving&waypoints=55.935,12.3006%7C55.6417,12.0797', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kronborg_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kronborg_Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Frederiksborg_Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Roskilde_Cathedral.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Viking_Ship_Museum_Roskilde.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dyrehaven.jpg"}'::text[], '{"Zámek Kronborg","Zámek Frederiksborg","Katedrála Roskilde","Muzeum vikingských lodí Roskilde","Dyrehaven"}'::text[], '{"DK"}'::text[], false, 3550, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Kronborg', 'Renesanční pevnost v Helsingøru, kulisa Shakespearova Hamleta, UNESCO památka. Střeží úžinu Øresund proti Švédsku.', 56.0389, 12.6214, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kronborg_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kronborg_Castle.jpg"}'::text[], 0),
    (v_route, 'Zámek Frederiksborg', 'Nádherný renesanční vodní zámek v Hillerødu, dnes muzeum národních dějin. Nejfotogeničtější zámek Dánska.', 55.935, 12.3006, 'https://commons.wikimedia.org/wiki/Special:FilePath/Frederiksborg_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Frederiksborg_Castle.jpg"}'::text[], 1),
    (v_route, 'Katedrála Roskilde', 'Cihlová katedrála UNESCO, pohřebiště dánských králů po staletí. Impozantní gotická stavba.', 55.6417, 12.0797, 'https://commons.wikimedia.org/wiki/Special:FilePath/Roskilde_Cathedral.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Roskilde_Cathedral.jpg"}'::text[], 2),
    (v_route, 'Muzeum vikingských lodí Roskilde', 'Muzeum s originály vikingských lodí vyzdvižených z fjordu a živou loděnicí. Skvělý pohled do dějin.', 55.6533, 12.0839, 'https://commons.wikimedia.org/wiki/Special:FilePath/Viking_Ship_Museum_Roskilde.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Viking_Ship_Museum_Roskilde.jpg"}'::text[], 3),
    (v_route, 'Dyrehaven', 'Královská obora se stády jelenů a loveckým zámečkem u Kodaně. Klidná zastávka v přírodě.', 55.7889, 12.5644, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dyrehaven.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dyrehaven.jpg"}'::text[], 4);

  -- Bornholm – slunečný ostrov
  delete from public.routes where name = 'Bornholm – slunečný ostrov' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Bornholm – slunečný ostrov', 'Okruh baltským ostrovem Bornholm, dánským ostrovem slunce. Zřícenina Hammershus, kulaté kostely, skalnaté pobřeží a uzené sledě nabízí jedinečnou atmosféru dál od pevniny. Nejlepší od května do září; pozor na trajektovou dopravu na ostrov.', 'loop', 120, 180, 'medium',
     '[{"lat": 55.1, "lng": 14.7, "label": "Start: Rønne"}, {"lat": 55.2731, "lng": 14.7597, "label": "Hammershus"}, {"lat": 55.2117, "lng": 14.98, "label": "Gudhjem"}, {"lat": 55.1, "lng": 14.7, "label": "Cíl: Rønne"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=55.1,14.7&destination=55.1,14.7&travelmode=driving&waypoints=55.2731,14.7597%7C55.2117,14.98', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hammershus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hammershus.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%B8nne.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gudhjem.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98sterlars_Kirke.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Helligdomsklipperne.jpg"}'::text[], '{"Zřícenina Hammershus","Rønne","Gudhjem","Kulatý kostel Østerlars","Skály Helligdomsklipperne"}'::text[], '{"DK"}'::text[], false, 3560, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zřícenina Hammershus', 'Největší středověká zřícenina severní Evropy na skalnatém útesu nad mořem. Symbol Bornholmu.', 55.2731, 14.7597, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hammershus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hammershus.jpg"}'::text[], 0),
    (v_route, 'Rønne', 'Hlavní město a přístav ostrova s barevnými domky a dlážděnými uličkami. Brána Bornholmu.', 55.1, 14.7, 'https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%B8nne.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%B8nne.jpg"}'::text[], 1),
    (v_route, 'Gudhjem', 'Malebné rybářské městečko na skalnatém svahu proslulé uzenými sledi. Nejhezčí zastávka pobřeží.', 55.2117, 14.98, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gudhjem.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gudhjem.jpg"}'::text[], 2),
    (v_route, 'Kulatý kostel Østerlars', 'Největší z proslulých kulatých kostelů Bornholmu, sloužících i jako pevnost. Ojedinělá románská stavba.', 55.15, 14.95, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98sterlars_Kirke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98sterlars_Kirke.jpg"}'::text[], 3),
    (v_route, 'Skály Helligdomsklipperne', 'Dramatické žulové útesy nad mořem na severním pobřeží ostrova. Působivá scenérie a stezky.', 55.23, 14.87, 'https://commons.wikimedia.org/wiki/Special:FilePath/Helligdomsklipperne.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Helligdomsklipperne.jpg"}'::text[], 4);

  -- Djursland a hory Mols Bjerge
  delete from public.routes where name = 'Djursland a hory Mols Bjerge' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Djursland a hory Mols Bjerge', 'Okruh poloostrovem Djursland východně od Aarhusu. Kopcovitý národní park Mols Bjerge, staré přístavní Ebeltoft a pláže nabízí zvlněné silnice a dánskou idylu. Nejlepší od jara do podzimu; pozor na turisty v sezoně.', 'loop', 150, 195, 'medium',
     '[{"lat": 56.1948, "lng": 10.6772, "label": "Start: Ebeltoft"}, {"lat": 56.2258, "lng": 10.55, "label": "Mols Bjerge"}, {"lat": 56.4139, "lng": 10.88, "label": "Grenaa"}, {"lat": 56.1948, "lng": 10.6772, "label": "Cíl: Ebeltoft"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=56.1948,10.6772&destination=56.1948,10.6772&travelmode=driving&waypoints=56.2258,10.55%7C56.4139,10.88', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ebeltoft.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ebeltoft.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mols_Bjerge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fregatten_Jylland.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kal%C3%B8_Slotsruin.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grenaa.jpg"}'::text[], '{"Ebeltoft","Národní park Mols Bjerge","Fregata Jylland","Kalø Slotsruin","Grenaa – pláž"}'::text[], '{"DK"}'::text[], false, 3570, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Ebeltoft', 'Kouzelné historické městečko s doškovými domky, nejmenší radnicí a starou fregatou Jylland. Perla Djurslandu.', 56.1948, 10.6772, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ebeltoft.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ebeltoft.jpg"}'::text[], 0),
    (v_route, 'Národní park Mols Bjerge', 'Zvlněná ledovcová krajina s kopci, vřesovišti a výhledy na moře. Ráj klidných silnic a přírody.', 56.2258, 10.55, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mols_Bjerge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mols_Bjerge.jpg"}'::text[], 1),
    (v_route, 'Fregata Jylland', 'Nejdelší dřevěná válečná loď světa v suchém doku v Ebeltoftu. Fascinující námořní památka.', 56.19, 10.68, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fregatten_Jylland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fregatten_Jylland.jpg"}'::text[], 2),
    (v_route, 'Kalø Slotsruin', 'Zřícenina hradu na ostrůvku spojeném s pevninou dlážděnou cestou. Romantická zastávka u moře.', 56.29, 10.48, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kal%C3%B8_Slotsruin.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kal%C3%B8_Slotsruin.jpg"}'::text[], 3),
    (v_route, 'Grenaa – pláž', 'Široká písečná pláž na východním cípu poloostrova, oblíbené letovisko. Zastávka na koupání.', 56.4139, 10.88, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grenaa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grenaa.jpg"}'::text[], 4);

  -- Jižní Jutsko a Ribe
  delete from public.routes where name = 'Jižní Jutsko a Ribe' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Jižní Jutsko a Ribe', 'Trasa nejstarším městem Dánska a jižním pomezím u německé hranice. Středověké Ribe s čápy, pohádkové Møgeltønder a slapová oblast Vadehavet nabízí historii a ojedinělou přírodu. Nejlepší od jara do podzimu; pozor na příliv v pobřežní oblasti.', 'poi', 160, 210, 'easy',
     '[{"lat": 55.3277, "lng": 8.7683, "label": "Start: Ribe"}, {"lat": 54.9358, "lng": 8.79, "label": "Møgeltønder"}, {"lat": 54.9364, "lng": 8.8628, "label": "Tønder"}, {"lat": 55.3277, "lng": 8.7683, "label": "Cíl: Ribe"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=55.3277,8.7683&destination=55.3277,8.7683&travelmode=driving&waypoints=54.9358,8.79%7C54.9364,8.8628', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ribe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ribe.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%B8gelt%C3%B8nder.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%B8nder.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vadehavet.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mand%C3%B8.jpg"}'::text[], '{"Ribe","Møgeltønder","Tønder","Vadehavet – slapové moře","Mandø"}'::text[], '{"DK"}'::text[], false, 3580, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Ribe', 'Nejstarší město Dánska s katedrálou, křivolakými uličkami a čapími hnízdy. Živoucí středověká atmosféra.', 55.3277, 8.7683, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ribe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ribe.jpg"}'::text[], 0),
    (v_route, 'Møgeltønder', 'Pohádková vesnice s dlážděnou lipovou alejí a zámkem, kde bydlí dánská princezna. Jedna z nejhezčích uliček země.', 54.9358, 8.7906, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%B8gelt%C3%B8nder.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%B8gelt%C3%B8nder.jpg"}'::text[], 1),
    (v_route, 'Tønder', 'Historické město proslulé krajkami a starobylými domy u německé hranice. Klidná zastávka na jihu.', 54.9364, 8.8628, 'https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%B8nder.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%B8nder.jpg"}'::text[], 2),
    (v_route, 'Vadehavet – slapové moře', 'UNESCO chráněné slapové moře s obřími hejny ptáků a jevem sort sol. Ojedinělý přírodní zážitek.', 55.15, 8.55, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vadehavet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vadehavet.jpg"}'::text[], 3),
    (v_route, 'Mandø', 'Ostrůvek dostupný jen za odlivu po dně moře, oáza klidu a ptactva. Dobrodružná zastávka.', 55.28, 8.55, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mand%C3%B8.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mand%C3%B8.jpg"}'::text[], 4);

  -- Limfjord a severní Jutsko
  delete from public.routes where name = 'Limfjord a severní Jutsko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Limfjord a severní Jutsko', 'Okruh kolem klikatého Limfjordu, který přetíná severní Jutsko. Živý Aalborg, ostrov Mors a divoká krajina Thy nabízí vodu na všech stranách a klidné pobřežní silnice. Nejlepší od jara do podzimu; pozor na vítr u fjordu.', 'loop', 180, 225, 'easy',
     '[{"lat": 57.0488, "lng": 9.9217, "label": "Start: Aalborg"}, {"lat": 56.7975, "lng": 8.86, "label": "Nykøbing Mors"}, {"lat": 56.9558, "lng": 8.6942, "label": "Thisted"}, {"lat": 57.0488, "lng": 9.9217, "label": "Cíl: Aalborg"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=57.0488,9.9217&destination=57.0488,9.9217&travelmode=driving&waypoints=56.7975,8.86%7C56.9558,8.6942', 'https://commons.wikimedia.org/wiki/Special:FilePath/Aalborg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aalborg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mors.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Thy_National_Park.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fur.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sp%C3%B8ttrup_Borg.jpg"}'::text[], '{"Aalborg","Ostrov Mors – Molerové útesy","Národní park Thy","Fur","Spøttrup Borg"}'::text[], '{"DK"}'::text[], false, 3590, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Aalborg', 'Živé město na břehu Limfjordu s renesančními domy a moderním nábřežím. Kulturní srdce severu.', 57.0488, 9.9217, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aalborg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aalborg.jpg"}'::text[], 0),
    (v_route, 'Ostrov Mors – Molerové útesy', 'Ostrov uprostřed Limfjordu s jílovými útesy plnými zkamenělin. Geologicky ojedinělé místo.', 56.7975, 8.86, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mors.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mors.jpg"}'::text[], 1),
    (v_route, 'Národní park Thy', 'První dánský národní park s dunami, vřesovišti a divokým pobřežím Severního moře. Nejdivočejší kout země.', 56.9558, 8.6942, 'https://commons.wikimedia.org/wiki/Special:FilePath/Thy_National_Park.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Thy_National_Park.jpg"}'::text[], 2),
    (v_route, 'Fur', 'Malý ostrov proslulý molerovými útesy a klidnou idylou. Skok mimo civilizaci.', 56.82, 9.02, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fur.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fur.jpg"}'::text[], 3),
    (v_route, 'Spøttrup Borg', 'Nejlépe zachovaný středověký vodní hrad Dánska s příkopy a valy. Působivá pevnost u fjordu.', 56.63, 8.93, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sp%C3%B8ttrup_Borg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sp%C3%B8ttrup_Borg.jpg"}'::text[], 4);

  -- Jižní Sjælland a útesy Stevns Klint
  delete from public.routes where name = 'Jižní Sjælland a útesy Stevns Klint' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Jižní Sjælland a útesy Stevns Klint', 'Okruh jižním Sjællandem k útesům Stevns Klint zapsaným na seznam UNESCO. Vápencové stěny s kostelem na okraji, přístav Køge a klidná krajina nabízí historii a moře. Nejlepší od jara do podzimu; pozor na okraj útesů.', 'loop', 140, 180, 'easy',
     '[{"lat": 55.4581, "lng": 12.1836, "label": "Start: Køge"}, {"lat": 55.2894, "lng": 12.45, "label": "Stevns Klint"}, {"lat": 55.3125, "lng": 12.3894, "label": "Store Heddinge"}, {"lat": 55.4581, "lng": 12.1836, "label": "Cíl: Køge"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=55.4581,12.1836&destination=55.4581,12.1836&travelmode=driving&waypoints=55.2894,12.45%7C55.3125,12.3894', 'https://commons.wikimedia.org/wiki/Special:FilePath/Stevns_Klint.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stevns_Klint.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B8ge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Store_Heddinge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vall%C3%B8_Slot.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stevnsfort.jpg"}'::text[], '{"Stevns Klint","Køge","Store Heddinge","Vallø Slot","Pevnost Stevnsfort"}'::text[], '{"DK"}'::text[], false, 3600, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Stevns Klint', 'Vápencové útesy UNESCO se stopou dopadu meteoritu, jenž vyhubil dinosaury, a kostelem na hraně. Ojedinělá geologická památka.', 55.2894, 12.45, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stevns_Klint.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stevns_Klint.jpg"}'::text[], 0),
    (v_route, 'Køge', 'Historické přístavní město s náměstím a hrázděnými domy jižně od Kodaně. Příjemná výchozí zastávka.', 55.4581, 12.1836, 'https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B8ge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B8ge.jpg"}'::text[], 1),
    (v_route, 'Store Heddinge', 'Městečko s ojedinělým osmibokým románským kostelem uprostřed poloostrova Stevns. Klidná zastávka.', 55.3125, 12.3894, 'https://commons.wikimedia.org/wiki/Special:FilePath/Store_Heddinge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Store_Heddinge.jpg"}'::text[], 2),
    (v_route, 'Vallø Slot', 'Renesanční vodní zámek s věžemi obklopený parkem a lesy. Romantická zastávka mimo hlavní tahy.', 55.41, 12.23, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vall%C3%B8_Slot.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vall%C3%B8_Slot.jpg"}'::text[], 3),
    (v_route, 'Pevnost Stevnsfort', 'Studenoválečná podzemní pevnost vytesaná do vápence útesů. Fascinující vojenská památka.', 55.2894, 12.45, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stevnsfort.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stevnsfort.jpg"}'::text[], 4);

end $$;
