-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — JIŽNÍ MORAVA (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Brno a hrad Veveří
  delete from public.routes where name = 'Brno a hrad Veveří' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Brno a hrad Veveří', 'Okruh moravskou metropolí a jejím okolím. Hrad Špilberk nad městem, romantický Veveří nad Brněnskou přehradou a vila Tugendhat nabízí kulturu i vodní scenérii. Nejlepší od jara do podzimu; pozor na provoz v Brně.', 'loop', 120, 165, 'easy',
     '[{"lat": 49.1947, "lng": 16.5989, "label": "Start: Brno – Špilberk"}, {"lat": 49.2558, "lng": 16.4622, "label": "Veveří"}, {"lat": 49.2411, "lng": 16.51, "label": "Brněnská přehrada"}, {"lat": 49.1947, "lng": 16.5989, "label": "Cíl: Brno"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.1947,16.5989&destination=49.1947,16.5989&travelmode=driving&waypoints=49.2558,16.4622%7C49.2411,16.51', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0pilberk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0pilberk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Veve%C5%99%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vila_Tugendhat.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brn%C4%9Bnsk%C3%A1_p%C5%99ehrada.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Petrov_Brno.jpg"}'::text[], '{"Hrad Špilberk","Hrad Veveří","Vila Tugendhat","Brněnská přehrada","Katedrála Petrov"}'::text[], '{"CZ"}'::text[], false, 2310, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Špilberk', 'Mohutná pevnost nad Brnem, kdysi obávaná žalářní kasematy, dnes muzeum s výhledem na město. Symbol moravské metropole.', 49.1947, 16.5989, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0pilberk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0pilberk.jpg"}'::text[], 0),
    (v_route, 'Hrad Veveří', 'Rozlehlý gotický hrad na ostrohu nad Brněnskou přehradou, jeden z nejstarších a největších v zemi. Malebná dominanta nad vodou.', 49.2558, 16.4622, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Veve%C5%99%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Veve%C5%99%C3%AD.jpg"}'::text[], 1),
    (v_route, 'Vila Tugendhat', 'Funkcionalistická vila architekta Miese van der Rohe, skvost moderní architektury zapsaný na seznam UNESCO. Ikona meziválečného Brna.', 49.2075, 16.6156, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vila_Tugendhat.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vila_Tugendhat.jpg"}'::text[], 2),
    (v_route, 'Brněnská přehrada', 'Oblíbené rekreační jezero na okraji Brna s výletními loděmi a plážemi. Osvěžující zastávka u vody.', 49.2411, 16.51, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brn%C4%9Bnsk%C3%A1_p%C5%99ehrada.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brn%C4%9Bnsk%C3%A1_p%C5%99ehrada.jpg"}'::text[], 3),
    (v_route, 'Katedrála Petrov', 'Gotická katedrála na skále nad Brnem se dvěma věžemi, symbol města ze stokorunové bankovky. Působivá dominanta.', 49.1911, 16.6075, 'https://commons.wikimedia.org/wiki/Special:FilePath/Petrov_Brno.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Petrov_Brno.jpg"}'::text[], 4);

  -- Slavkovské bojiště a zámky
  delete from public.routes where name = 'Slavkovské bojiště a zámky' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Slavkovské bojiště a zámky', 'Okruh krajem slavné bitvy tří císařů u Slavkova východně od Brna. Zámek Slavkov, Mohyla míru a vinařské kopce nabízí historii a klidnou jízdu. Nejlepší od jara do podzimu; pozor na zemědělskou techniku.', 'loop', 130, 165, 'easy',
     '[{"lat": 49.1533, "lng": 16.8764, "label": "Start: Slavkov u Brna"}, {"lat": 49.1281, "lng": 16.7614, "label": "Mohyla míru"}, {"lat": 49.15, "lng": 17.0, "label": "Bučovice"}, {"lat": 49.1533, "lng": 16.8764, "label": "Cíl: Slavkov u Brna"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.1533,16.8764&destination=49.1533,16.8764&travelmode=driving&waypoints=49.1281,16.7614%7C49.15,17.0', 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Slavkov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Slavkov.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mohyla_m%C3%ADru.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Bu%C4%8Dovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Slavkov_u_Brna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDd%C3%A1nick%C3%BD_les.jpg"}'::text[], '{"Zámek Slavkov (Austerlitz)","Mohyla míru","Zámek Bučovice","Rozhledna Urbanov","Ždánický les"}'::text[], '{"CZ"}'::text[], false, 2320, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Slavkov (Austerlitz)', 'Barokní zámek, kde byl po bitvě u Slavkova roku 1805 uzavřen mír. Elegantní sídlo s historií tří císařů.', 49.1533, 16.8764, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Slavkov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Slavkov.jpg"}'::text[], 0),
    (v_route, 'Mohyla míru', 'Secesní památník na místě nejkrvavějších bojů bitvy u Slavkova s muzeem. Pietní vrchol slavkovského bojiště.', 49.1281, 16.7614, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mohyla_m%C3%ADru.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mohyla_m%C3%ADru.jpg"}'::text[], 1),
    (v_route, 'Zámek Bučovice', 'Renesanční zámek s arkádovým nádvořím italského typu, klenot mezi moravskými zámky. Skvost daleko od davů.', 49.1497, 17.0, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Bu%C4%8Dovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Bu%C4%8Dovice.jpg"}'::text[], 2),
    (v_route, 'Rozhledna Urbanov', 'Vyhlídka nad slavkovským bojištěm s pohledem na místa historické bitvy. Klidná zastávka nad vinicemi.', 49.13, 16.83, 'https://commons.wikimedia.org/wiki/Special:FilePath/Slavkov_u_Brna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slavkov_u_Brna.jpg"}'::text[], 3),
    (v_route, 'Ždánický les', 'Rozlehlý listnatý les jižně od bojiště, ráj klidných silnic. Osvěžující zastávka v zeleni.', 49.05, 16.95, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDd%C3%A1nick%C3%BD_les.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDd%C3%A1nick%C3%BD_les.jpg"}'::text[], 4);

  -- Moravský kras jinak – Sloup a Blansko
  delete from public.routes where name = 'Moravský kras jinak – Sloup a Blansko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Moravský kras jinak – Sloup a Blansko', 'Okruh severní částí Moravského krasu mimo přeplněnou Macochu. Sloupsko-šošůvské jeskyně, poutní Křtiny a lesní silnice nabízí podzemní krásy a klid. Nejlepší od jara do podzimu; pozor na chladno v jeskyních a lesní úseky.', 'loop', 110, 165, 'medium',
     '[{"lat": 49.3644, "lng": 16.6439, "label": "Start: Blansko"}, {"lat": 49.4111, "lng": 16.7392, "label": "Sloupsko-šošůvské jeskyně"}, {"lat": 49.2975, "lng": 16.7461, "label": "Křtiny"}, {"lat": 49.3644, "lng": 16.6439, "label": "Cíl: Blansko"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3644,16.6439&destination=49.3644,16.6439&travelmode=driving&waypoints=49.4111,16.7392%7C49.2975,16.7461', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sloupsko-%C5%A1o%C5%A1%C5%AFvsk%C3%A9_jeskyn%C4%9B.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sloupsko-%C5%A1o%C5%A1%C5%AFvsk%C3%A9_jeskyn%C4%9B.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/K%C5%99tiny.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Blansko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Moravsk%C3%BD_kras.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Balcarka.jpg"}'::text[], '{"Sloupsko-šošůvské jeskyně","Poutní kostel Křtiny","Blansko – zámek","Rudické propadání","Jeskyně Balcarka"}'::text[], '{"CZ"}'::text[], false, 2330, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Sloupsko-šošůvské jeskyně', 'Rozsáhlý jeskynní systém se sály, propastmi a podzemní říčkou na severu Moravského krasu. Podzemní zážitek bez davů.', 49.4111, 16.7392, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sloupsko-%C5%A1o%C5%A1%C5%AFvsk%C3%A9_jeskyn%C4%9B.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sloupsko-%C5%A1o%C5%A1%C5%AFvsk%C3%A9_jeskyn%C4%9B.jpg"}'::text[], 0),
    (v_route, 'Poutní kostel Křtiny', 'Skvostný barokní poutní chrám od Santiniho zvaný perla Moravy. Duchovní zastávka mezi lesy.', 49.2975, 16.7461, 'https://commons.wikimedia.org/wiki/Special:FilePath/K%C5%99tiny.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/K%C5%99tiny.jpg"}'::text[], 1),
    (v_route, 'Blansko – zámek', 'Zámek s muzeem Blanenska a litinou, výchozí bod do Moravského krasu. Klidná zastávka na řece Svitavě.', 49.3644, 16.6439, 'https://commons.wikimedia.org/wiki/Special:FilePath/Blansko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Blansko.jpg"}'::text[], 2),
    (v_route, 'Rudické propadání', 'Působivé místo, kde potok mizí v podzemí krasu, s větrnou jeskyní. Zajímavá zastávka pro přírodovědce.', 49.394, 16.735, 'https://commons.wikimedia.org/wiki/Special:FilePath/Moravsk%C3%BD_kras.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Moravsk%C3%BD_kras.jpg"}'::text[], 3),
    (v_route, 'Jeskyně Balcarka', 'Bohatě zdobená krápníková jeskyně u Ostrova u Macochy. Barevný podzemní skvost.', 49.373, 16.755, 'https://commons.wikimedia.org/wiki/Special:FilePath/Balcarka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Balcarka.jpg"}'::text[], 4);

  -- Pernštejn a Svratecko
  delete from public.routes where name = 'Pernštejn a Svratecko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Pernštejn a Svratecko', 'Okruh k jednomu z nejkrásnějších hradů Moravy na severozápadě kraje. Mohutný Pernštejn, údolí Svratky a lesnaté kopce nabízí historii a klikaté silnice. Nejlepší od jara do podzimu; pozor na úzké silnice v údolí.', 'loop', 140, 195, 'medium',
     '[{"lat": 49.4553, "lng": 16.35, "label": "Start: Nedvědice"}, {"lat": 49.5508, "lng": 16.3167, "label": "Pernštejn"}, {"lat": 49.4258, "lng": 16.35, "label": "Doubravník"}, {"lat": 49.4553, "lng": 16.35, "label": "Cíl: Nedvědice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.4553,16.35&destination=49.4553,16.35&travelmode=driving&waypoints=49.5508,16.3167%7C49.4258,16.35', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Pern%C5%A1tejn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Pern%C5%A1tejn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nedv%C4%9Bdice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Doubravn%C3%ADk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADrsk%C3%A1_p%C5%99ehrada.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svratka.jpg"}'::text[], '{"Hrad Pernštejn","Nedvědice","Doubravník – kostel","Vírská přehrada","Zubří – rozhledna"}'::text[], '{"CZ"}'::text[], false, 2340, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Pernštejn', 'Skvostně zachovalý gotický hrad zvaný mramorový, jeden z nejkrásnějších v Česku, kulisa mnoha filmů. Nezapomenutelná dominanta Svratecka.', 49.5508, 16.3167, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Pern%C5%A1tejn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Pern%C5%A1tejn.jpg"}'::text[], 0),
    (v_route, 'Nedvědice', 'Městečko pod Pernštejnem v údolí Svratky, výchozí bod k hradu. Klidná zastávka mezi kopci.', 49.4553, 16.35, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nedv%C4%9Bdice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nedv%C4%9Bdice.jpg"}'::text[], 1),
    (v_route, 'Doubravník – kostel', 'Obec s pozoruhodným renesančním kostelem a hrobkou Mitrovských. Klidná zastávka v údolí.', 49.4258, 16.3517, 'https://commons.wikimedia.org/wiki/Special:FilePath/Doubravn%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Doubravn%C3%ADk.jpg"}'::text[], 2),
    (v_route, 'Vírská přehrada', 'Malebná kamenná přehrada s vysokou hrází v hlubokém údolí Svratky. Působivá zastávka u vody.', 49.56, 16.213, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADrsk%C3%A1_p%C5%99ehrada.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADrsk%C3%A1_p%C5%99ehrada.jpg"}'::text[], 3),
    (v_route, 'Zubří – rozhledna', 'Vyhlídkové místo nad údolím Svratky s pohledem do kraje. Klidná zastávka nad lesy.', 49.48, 16.29, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svratka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svratka.jpg"}'::text[], 4);

  -- Boskovicko a Malá Haná
  delete from public.routes where name = 'Boskovicko a Malá Haná' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Boskovicko a Malá Haná', 'Okruh půvabnou krajinou Boskovicka na severu jižní Moravy. Hrad a zámek Boskovice, židovské město a klidné silnice nabízí historii a pohodovou jízdu. Nejlepší od jara do podzimu; pozor na provoz v obcích.', 'loop', 130, 180, 'easy',
     '[{"lat": 49.4881, "lng": 16.6603, "label": "Start: Boskovice"}, {"lat": 49.49, "lng": 16.66, "label": "Hrad Boskovice"}, {"lat": 49.63, "lng": 16.71, "label": "Jevíčko"}, {"lat": 49.4881, "lng": 16.6603, "label": "Cíl: Boskovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.4881,16.6603&destination=49.4881,16.6603&travelmode=driving&waypoints=49.49,16.66%7C49.63,16.71', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Boskovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Boskovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Boskovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jev%C3%AD%C4%8Dko.jpg"}'::text[], '{"Hrad Boskovice","Zámek Boskovice","Židovské město Boskovice","Westernové městečko Boskovice","Jevíčko"}'::text[], '{"CZ"}'::text[], false, 2350, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Boskovice', 'Malebná zřícenina gotického hradu na kopci nad městem s dochovanými hradbami. Dominanta Boskovicka.', 49.4906, 16.66, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Boskovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Boskovice.jpg"}'::text[], 0),
    (v_route, 'Zámek Boskovice', 'Elegantní empírový zámek s dochovanými interiéry v centru města. Klidná zastávka pod hradem.', 49.4881, 16.6603, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Boskovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Boskovice.jpg"}'::text[], 1),
    (v_route, 'Židovské město Boskovice', 'Jedna z nejzachovalejších židovských čtvrtí v Česku se synagogou a hřbitovem. Cesta do minulosti.', 49.4881, 16.655, 'https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice.jpg"}'::text[], 2),
    (v_route, 'Westernové městečko Boskovice', 'Zábavní westernové městečko s koňmi a představeními. Zábavná zastávka pro celou posádku.', 49.49, 16.67, 'https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice.jpg"}'::text[], 3),
    (v_route, 'Jevíčko', 'Historické městečko s věží a náměstím na pomezí Čech a Moravy. Klidná zastávka mimo hlavní tahy.', 49.6331, 16.7139, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jev%C3%AD%C4%8Dko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jev%C3%AD%C4%8Dko.jpg"}'::text[], 4);

  -- Slovácko – Milotice a Strážnice
  delete from public.routes where name = 'Slovácko – Milotice a Strážnice' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Slovácko – Milotice a Strážnice', 'Trasa vinařským Slováckem plným lidových tradic. Barokní zámek Milotice, skanzen ve Strážnici a vinné sklepy nabízí folklor, víno a rovinaté silnice. Nejlepší od jara do podzimu; pozor na provoz v obcích za vinobraní.', 'poi', 140, 180, 'easy',
     '[{"lat": 48.9464, "lng": 17.14, "label": "Start: Milotice"}, {"lat": 48.9, "lng": 17.32, "label": "Strážnice"}, {"lat": 48.87, "lng": 17.25, "label": "Petrov – Plže"}, {"lat": 48.9464, "lng": 17.14, "label": "Cíl: Milotice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9464,17.14&destination=48.9464,17.14&travelmode=driving&waypoints=48.9,17.32%7C48.87,17.25', 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Milotice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Milotice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skanzen_Str%C3%A1%C5%BEnice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pl%C5%BEe_Petrov.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Str%C3%A1%C5%BEnice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ba%C5%A5%C5%AFv_kan%C3%A1l.jpg"}'::text[], '{"Zámek Milotice","Skanzen Strážnice","Vinné sklepy Petrov-Plže","Zámek Strážnice","Baťův kanál"}'::text[], '{"CZ"}'::text[], false, 2360, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Milotice', 'Skvostný barokní zámek s francouzskou zahradou zvaný perla jihovýchodní Moravy, kulisa mnoha pohádek. Elegantní zastávka Slovácka.', 48.9464, 17.14, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Milotice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Milotice.jpg"}'::text[], 0),
    (v_route, 'Skanzen Strážnice', 'Národopisné muzeum v přírodě s ukázkou lidové architektury Slovácka a folklorními slavnostmi. Živá tradice regionu.', 48.9014, 17.3164, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skanzen_Str%C3%A1%C5%BEnice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skanzen_Str%C3%A1%C5%BEnice.jpg"}'::text[], 1),
    (v_route, 'Vinné sklepy Petrov-Plže', 'Malebná ulička bíle malovaných vinných sklepů, památková rezervace lidového stavitelství. Zastávka na slovácké víno.', 48.87, 17.253, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pl%C5%BEe_Petrov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pl%C5%BEe_Petrov.jpg"}'::text[], 2),
    (v_route, 'Zámek Strážnice', 'Renesanční zámek v parku, sídlo Ústavu lidové kultury. Klidná zastávka u Baťova kanálu.', 48.9014, 17.3164, 'https://commons.wikimedia.org/wiki/Special:FilePath/Str%C3%A1%C5%BEnice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Str%C3%A1%C5%BEnice.jpg"}'::text[], 3),
    (v_route, 'Baťův kanál', 'Historický plavební kanál protkávající Slovácko, dnes ráj rekreační plavby. Zastávka u vody.', 48.9014, 17.3164, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ba%C5%A5%C5%AFv_kan%C3%A1l.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ba%C5%A5%C5%AFv_kan%C3%A1l.jpg"}'::text[], 4);

  -- Velehrad, Modrá a Buchlovské kopce
  delete from public.routes where name = 'Velehrad, Modrá a Buchlovské kopce' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Velehrad, Modrá a Buchlovské kopce', 'Okruh duchovním srdcem Moravy v Chřibech. Poutní bazilika Velehrad, archeoskanzen Modrá a lesnaté kopce nabízí historii velkomoravskou i pohodovou jízdu. Nejlepší od jara do podzimu; pozor na turisty u poutních míst.', 'loop', 120, 165, 'easy',
     '[{"lat": 49.1064, "lng": 17.3939, "label": "Start: Velehrad"}, {"lat": 49.11, "lng": 17.36, "label": "Modrá"}, {"lat": 49.14, "lng": 17.38, "label": "Salaš"}, {"lat": 49.1064, "lng": 17.3939, "label": "Cíl: Velehrad"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.1064,17.3939&destination=49.1064,17.3939&travelmode=driving&waypoints=49.11,17.36%7C49.14,17.38', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bazilika_Velehrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bazilika_Velehrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C5%99iby.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Uhersk%C3%A9_Hradi%C5%A1t%C4%9B.jpg"}'::text[], '{"Bazilika Velehrad","Archeoskanzen Modrá","Živá voda Modrá","Chřiby – Kazatelna","Uherské Hradiště"}'::text[], '{"CZ"}'::text[], false, 2370, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Bazilika Velehrad', 'Velkolepá poutní bazilika, nejvýznamnější cyrilometodějské poutní místo Moravy. Duchovní srdce národa.', 49.1064, 17.3939, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bazilika_Velehrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bazilika_Velehrad.jpg"}'::text[], 0),
    (v_route, 'Archeoskanzen Modrá', 'Rekonstrukce velkomoravského opevněného sídliště nedaleko Velehradu. Cesta do dob Velké Moravy.', 49.1064, 17.36, 'https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A1.jpg"}'::text[], 1),
    (v_route, 'Živá voda Modrá', 'Expozice s prosklenou nádrží, kde lze pozorovat ryby pod hladinou. Zábavná zastávka pro rodiny.', 49.1064, 17.36, 'https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A1.jpg"}'::text[], 2),
    (v_route, 'Chřiby – Kazatelna', 'Skalní vyhlídka v lesnatých Chřibech s výhledem na Slovácko. Klidná zastávka mezi stromy.', 49.14, 17.38, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C5%99iby.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C5%99iby.jpg"}'::text[], 3),
    (v_route, 'Uherské Hradiště', 'Historické město na řece Moravě, srdce Slovácka s pěkným náměstím. Živá zastávka s dobrým zázemím.', 49.0697, 17.46, 'https://commons.wikimedia.org/wiki/Special:FilePath/Uhersk%C3%A9_Hradi%C5%A1t%C4%9B.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Uhersk%C3%A9_Hradi%C5%A1t%C4%9B.jpg"}'::text[], 4);

  -- Mikulčice a soutok Moravy
  delete from public.routes where name = 'Mikulčice a soutok Moravy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mikulčice a soutok Moravy', 'Trasa nejjižnějším cípem Moravy k slovanskému hradišti Mikulčice u soutoku Moravy a Dyje. Archeologický park, lužní lesy a vinařské obce nabízí historii Velké Moravy a rovinatou jízdu. Nejlepší od jara do podzimu; pozor na horko a komáry v luzích.', 'poi', 130, 165, 'easy',
     '[{"lat": 48.8064, "lng": 17.05, "label": "Start: Mikulčice"}, {"lat": 48.68, "lng": 16.94, "label": "Soutok Moravy a Dyje"}, {"lat": 48.72, "lng": 16.97, "label": "Lanžhot"}, {"lat": 48.8064, "lng": 17.05, "label": "Cíl: Mikulčice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.8064,17.05&destination=48.8064,17.05&travelmode=driving&waypoints=48.68,16.94%7C48.72,16.97', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mikul%C4%8Dice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mikul%C4%8Dice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Soutok_Moravy_a_Dyje.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lan%C5%BEhot.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Podlu%C5%BE%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pohansko.jpg"}'::text[], '{"Slovanské hradiště Mikulčice","Soutok Moravy a Dyje","Lanžhot","Kostice – vinné sklepy","Pohansko"}'::text[], '{"CZ"}'::text[], false, 2380, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Slovanské hradiště Mikulčice', 'Archeologický park na místě jednoho z hlavních center Velké Moravy s kostely a nálezy. Kolébka moravské státnosti.', 48.8064, 17.05, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mikul%C4%8Dice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mikul%C4%8Dice.jpg"}'::text[], 0),
    (v_route, 'Soutok Moravy a Dyje', 'Rozlehlé lužní lesy u trojmezí s Rakouskem a Slovenskem, ráj ptactva a starých dubů. Divoká zastávka na jihu.', 48.68, 16.94, 'https://commons.wikimedia.org/wiki/Special:FilePath/Soutok_Moravy_a_Dyje.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Soutok_Moravy_a_Dyje.jpg"}'::text[], 1),
    (v_route, 'Lanžhot', 'Nejjižnější město Moravy s folklorními tradicemi u hranice. Klidná zastávka mezi luhy.', 48.72, 16.97, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lan%C5%BEhot.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lan%C5%BEhot.jpg"}'::text[], 2),
    (v_route, 'Kostice – vinné sklepy', 'Vinařská obec Podluží s lidovými tradicemi a sklepy. Zastávka na jižní víno.', 48.745, 16.955, 'https://commons.wikimedia.org/wiki/Special:FilePath/Podlu%C5%BE%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Podlu%C5%BE%C3%AD.jpg"}'::text[], 3),
    (v_route, 'Pohansko', 'Archeologické naleziště velkomoravského dvorce s loveckým zámečkem u Břeclavi. Cesta do dávné minulosti.', 48.723, 16.885, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pohansko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pohansko.jpg"}'::text[], 4);

  -- Znojemsko a řeka Dyje
  delete from public.routes where name = 'Znojemsko a řeka Dyje' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Znojemsko a řeka Dyje', 'Okruh vinařským Znojemskem podél meandrů řeky Dyje. Loucký klášter, vyhlídky nad Dyjí a vinné sklepy nabízí historii a víno na jihu Moravy. Nejlepší od jara do podzimu; pozor na provoz ve Znojmě a horko.', 'loop', 130, 180, 'easy',
     '[{"lat": 48.8555, "lng": 16.0488, "label": "Start: Znojmo"}, {"lat": 48.85, "lng": 15.87, "label": "Hardegg (vyhlídka)"}, {"lat": 48.79, "lng": 16.06, "label": "Šatov – sklepy"}, {"lat": 48.8555, "lng": 16.0488, "label": "Cíl: Znojmo"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.8555,16.0488&destination=48.8555,16.0488&travelmode=driving&waypoints=48.85,15.87%7C48.79,16.06', 'https://commons.wikimedia.org/wiki/Special:FilePath/Louck%C3%BD_kl%C3%A1%C5%A1ter.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Louck%C3%BD_kl%C3%A1%C5%A1ter.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Znojmo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0atov.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Podyj%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Znojmo.jpg"}'::text[], '{"Loucký klášter","Znojemský hrad a Vlkova věž","Šatovské vinné sklepy","Vyhlídka nad Dyjí (Králův stolec)","Konice – kaple"}'::text[], '{"CZ"}'::text[], false, 2390, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Loucký klášter', 'Mohutný barokní klášter premonstrátů na okraji Znojma s vinařstvím. Působivá zastávka nad Dyjí.', 48.8394, 16.0334, 'https://commons.wikimedia.org/wiki/Special:FilePath/Louck%C3%BD_kl%C3%A1%C5%A1ter.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Louck%C3%BD_kl%C3%A1%C5%A1ter.jpg"}'::text[], 0),
    (v_route, 'Znojemský hrad a Vlkova věž', 'Hrad s rotundou a vyhlídkovou věží nad meandrem Dyje. Historická dominanta města.', 48.8567, 16.0472, 'https://commons.wikimedia.org/wiki/Special:FilePath/Znojmo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Znojmo.jpg"}'::text[], 1),
    (v_route, 'Šatovské vinné sklepy', 'Malebná ulička vinných sklepů s malovaným sklepem v obci u hranice. Zastávka na znojemské víno.', 48.79, 16.06, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0atov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0atov.jpg"}'::text[], 2),
    (v_route, 'Vyhlídka nad Dyjí (Králův stolec)', 'Skalní vyhlídka nad meandry Dyje v národním parku. Pohled na divokou řeku v soutěsce.', 48.85, 15.9, 'https://commons.wikimedia.org/wiki/Special:FilePath/Podyj%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Podyj%C3%AD.jpg"}'::text[], 3),
    (v_route, 'Konice – kaple', 'Vinařská obec u Znojma s poutní kaplí a sklepy. Klidná zastávka mezi vinicemi.', 48.83, 16.03, 'https://commons.wikimedia.org/wiki/Special:FilePath/Znojmo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Znojmo.jpg"}'::text[], 4);

  -- Rajhrad a Židlochovicko
  delete from public.routes where name = 'Rajhrad a Židlochovicko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rajhrad a Židlochovicko', 'Okruh úrodnou krajinou jižně od Brna mezi klášterem a zámky. Benediktinský klášter Rajhrad, lovecký zámek Židlochovice a vinařské obce nabízí historii a pohodovou jízdu. Nejlepší od jara do podzimu; pozor na provoz u Brna.', 'loop', 110, 150, 'easy',
     '[{"lat": 49.0906, "lng": 16.61, "label": "Start: Rajhrad"}, {"lat": 49.04, "lng": 16.62, "label": "Židlochovice"}, {"lat": 48.96, "lng": 16.64, "label": "Nosislav – sklepy"}, {"lat": 49.0906, "lng": 16.61, "label": "Cíl: Rajhrad"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.0906,16.61&destination=49.0906,16.61&travelmode=driving&waypoints=49.04,16.62%7C48.96,16.64', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter_Rajhrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter_Rajhrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_%C5%BDidlochovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%BDhon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nosislav.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Blu%C4%8Dina.jpg"}'::text[], '{"Klášter Rajhrad","Zámek Židlochovice","Výhon u Židlochovic","Nosislav – vinné sklepy","Blučina"}'::text[], '{"CZ"}'::text[], false, 2400, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Klášter Rajhrad', 'Nejstarší benediktinský klášter na Moravě s barokní bazilikou od Santiniho a Památníkem písemnictví. Duchovní a kulturní klenot.', 49.0906, 16.6122, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter_Rajhrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter_Rajhrad.jpg"}'::text[], 0),
    (v_route, 'Zámek Židlochovice', 'Barokní lovecký zámek s rozlehlým parkem, kdysi oblíbené sídlo císaře. Elegantní zastávka nad Svratkou.', 49.042, 16.62, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_%C5%BDidlochovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_%C5%BDidlochovice.jpg"}'::text[], 1),
    (v_route, 'Výhon u Židlochovic', 'Nejvyšší kopec jižně od Brna s vyhlídkou na Pálavu a vinice. Klidná zastávka nad krajem.', 49.03, 16.63, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%BDhon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%BDhon.jpg"}'::text[], 2),
    (v_route, 'Nosislav – vinné sklepy', 'Vinařská obec s tradičními sklepy uprostřed vinic. Zastávka na jihomoravské víno.', 48.96, 16.64, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nosislav.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nosislav.jpg"}'::text[], 3),
    (v_route, 'Blučina', 'Obec s archeologickými nálezy a vinicemi nad Svratkou. Klidná zastávka mezi révou.', 49.058, 16.647, 'https://commons.wikimedia.org/wiki/Special:FilePath/Blu%C4%8Dina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Blu%C4%8Dina.jpg"}'::text[], 4);

end $$;
