-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — FRANCIE (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Vogézy – Route des Crêtes a Grand Ballon
  delete from public.routes where name = 'Vogézy – Route des Crêtes a Grand Ballon' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Vogézy – Route des Crêtes a Grand Ballon', 'Legendární hřebenová silnice Route des Crêtes vznikla za první světové války jako zásobovací trasa a dnes je to jedna z nejlepších motorkářských silnic východní Francie. Okruh z Munsteru střídá stovky plynulých zatáček v bukových a smrkových lesích s otevřenými pastvinami na hřebeni, odkud dohlédnete přes rýnskou nížinu až k Alpám. Vrcholem je výjezd na Grand Ballon (1424 m), nejvyšší horu Vogéz, a pietní zastávka na bojišti Hartmannswillerkopf. Povrch je vesměs výborný, ideální sezóna od května do října; nejvyšší úseky bývají v zimě uzavřené. O letních víkendech počítejte s cyklisty a pomalejšími auty, na hřebeni se rychle mění počasí a padají mlhy.', 'loop', 140, 240, 'medium',
     '[{"lat": 48.0406, "lng": 7.1390, "label": "Start: Munster"}, {"lat": 48.1367, "lng": 7.0908, "label": "Lac Blanc"}, {"lat": 48.0633, "lng": 7.0225, "label": "Col de la Schlucht"}, {"lat": 48.0403, "lng": 7.0161, "label": "Hohneck"}, {"lat": 47.9011, "lng": 7.0839, "label": "Grand Ballon"}, {"lat": 47.8558, "lng": 7.1594, "label": "Hartmannswillerkopf"}, {"lat": 48.0406, "lng": 7.1390, "label": "Cíl: Munster"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.0406,7.1390&destination=48.0406,7.1390&travelmode=driving&waypoints=48.1367,7.0908%7C48.0633,7.0225%7C48.0403,7.0161%7C47.9011,7.0839%7C47.8558,7.1594', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20Blanc%20Vosges.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20Blanc%20Vosges.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Col%20de%20la%20Schlucht.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Hohneck.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grand%20Ballon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hartmannswillerkopf.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Munster%20(Haut-Rhin).jpg"}'::text[], '{"Lac Blanc","Col de la Schlucht","Hohneck","Grand Ballon","Hartmannswillerkopf (Vieil Armand)","Restaurace: Hôtel Verte Vallée (Munster)"}'::text[], '{"FR"}'::text[], false, 3810, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lac Blanc', 'Ledovcové jezero v žulovém kotli pod hřebenem Vogéz, obklopené skalami a lesem. Silnice k němu stoupá dlouhou sérií serpentin od Orbey a nahoře na vás čeká parkoviště přímo u břehu i občerstvení. Skvělé místo na první fotopauzu před najetím na hřebenovku.', 48.1367, 7.0908, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20Blanc%20Vosges.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20Blanc%20Vosges.jpg"}'::text[], 0),
    (v_route, 'Col de la Schlucht', 'Nejznámější vogézské sedlo (1139 m) na hranici Alsaska a Lotrinska, křižovatka hřebenové Route des Crêtes. Nedávno zrekonstruovaný areál nabízí kavárny a výhledy do údolí Munsteru. Odtud pokračuje hřebenovka na jih po jedné z nejplynulejších silnic v pohoří.', 48.0633, 7.0225, 'https://commons.wikimedia.org/wiki/Special:FilePath/Col%20de%20la%20Schlucht.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Col%20de%20la%20Schlucht.jpg"}'::text[], 1),
    (v_route, 'Hohneck', 'Třetí nejvyšší vrchol Vogéz (1363 m) s odbočkou přímo z hřebenovky až téměř na vrchol. Kruhový rozhled zabírá kary s jezírky, pastviny s krávami vogézského plemene i celý hřeben pohoří. Za jasného dne jsou vidět Alpy včetně Mont Blanku.', 48.0403, 7.0161, 'https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Hohneck.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Hohneck.jpg"}'::text[], 2),
    (v_route, 'Grand Ballon', 'Nejvyšší hora Vogéz (1424 m) s charakteristickou radarovou koulí na vrcholu. Silnice se přes sedlo pod vrcholem přehoupne v dlouhých zatáčkách s výhledy na rýnskou nížinu, Schwarzwald a za dobré viditelnosti i alpské štíty. U horského hotelu se dá pohodlně zastavit na kávu.', 47.9011, 7.0839, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grand%20Ballon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grand%20Ballon.jpg"}'::text[], 3),
    (v_route, 'Hartmannswillerkopf (Vieil Armand)', 'Národní památník první světové války na kopci, o který se v letech 1915–1916 sváděly krvavé boje mezi Francií a Německem. Zachovalé zákopy, krypta a hřbitov s tisíci kříži jsou působivou pietní zastávkou přímo u sjezdu z hřebenovky. Vstup do zákopového areálu je volný.', 47.8558, 7.1594, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hartmannswillerkopf.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hartmannswillerkopf.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Hôtel Verte Vallée (Munster)', 'Zavedená hotelová restaurace v zeleném údolí Munsteru s poctivou alsaskou kuchyní — nechybí místní sýr munster, baeckeoffe ani ryby z horských potoků. Hosté chválí kvalitu jídla i klidnou zahradu, ideální na závěrečnou večeři po hřebenech. Rezervace se o víkendech vyplatí.', 48.0406, 7.1390, 'https://commons.wikimedia.org/wiki/Special:FilePath/Munster%20(Haut-Rhin).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Munster%20(Haut-Rhin).jpg"}'::text[], 5);

  -- Alsaská vinná stezka – Riquewihr a Haut-Kœnigsbourg
  delete from public.routes where name = 'Alsaská vinná stezka – Riquewihr a Haut-Kœnigsbourg' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Alsaská vinná stezka – Riquewihr a Haut-Kœnigsbourg', 'Pohodová vyjížďka po slavné Route des Vins d''Alsace, která se vine úpatím Vogéz mezi nekonečnými vinicemi ryzlinku a gewürztraminentu. Okruh z Colmaru navléká jako korálky nejkrásnější hrázděná městečka Francie — Eguisheim, Kaysersberg, Riquewihr a Ribeauvillé — a vrcholí výjezdem serpentinami k mohutnému hradu Haut-Kœnigsbourg. Silnice jsou úzké, ale kvalitní, provoz mimo sezónu klidný; jde spíš o požitkářskou jízdu s častými zastávkami než o sportovní svezení. Nejhezčí je pozdní léto a vinobraní v září a říjnu, kdy vinice zezlátnou. O víkendech počítejte s turisty v uličkách a plnými parkovišti u městeček.', 'loop', 95, 180, 'easy',
     '[{"lat": 48.0778, "lng": 7.3556, "label": "Start: Colmar"}, {"lat": 48.0428, "lng": 7.3062, "label": "Eguisheim"}, {"lat": 48.1392, "lng": 7.2617, "label": "Kaysersberg"}, {"lat": 48.1667, "lng": 7.2986, "label": "Riquewihr"}, {"lat": 48.1953, "lng": 7.3196, "label": "Ribeauvillé"}, {"lat": 48.2494, "lng": 7.3444, "label": "Château du Haut-Kœnigsbourg"}, {"lat": 48.0778, "lng": 7.3556, "label": "Cíl: Colmar"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.0778,7.3556&destination=48.0778,7.3556&travelmode=driving&waypoints=48.0428,7.3062%7C48.1392,7.2617%7C48.1667,7.2986%7C48.1953,7.3196%7C48.2494,7.3444', 'https://commons.wikimedia.org/wiki/Special:FilePath/Eguisheim.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eguisheim.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kaysersberg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Riquewihr.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Riquewihr.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ribeauvill%C3%A9.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Haut-Koenigsbourg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Colmar%20Petite%20Venise.jpg"}'::text[], '{"Eguisheim","Kaysersberg","Riquewihr","Restaurace: La Table du Gourmet (Riquewihr)","Ribeauvillé","Château du Haut-Kœnigsbourg","Colmar – Petite Venise"}'::text[], '{"FR"}'::text[], false, 3820, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Eguisheim', 'Vesnice postavená v soustředných kruzích kolem hradu, pravidelně volená mezi nejkrásnější vesnice Francie. Hrázděné domy obsypané muškáty a vinné sklípky lákají k první degustační zastávce (pro jezdce samozřejmě jen ochutnávka nealko moštu). Motorku zaparkujete u hradeb a centrum projdete pěšky za půl hodiny.', 48.0428, 7.3062, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eguisheim.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eguisheim.jpg"}'::text[], 0),
    (v_route, 'Kaysersberg', 'Rodiště Alberta Schweitzera s kamenným opevněným mostem přes říčku Weiss a zříceninou hradu nad vinicemi. Z hradní věže je nejhezčí výhled na moře vinic celé stezky. Městečko bylo vyhlášeno nejoblíbenější vesnicí Francouzů.', 48.1392, 7.2617, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kaysersberg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kaysersberg.jpg"}'::text[], 1),
    (v_route, 'Riquewihr', 'Snad nejfotografovanější městečko Alsaska, obehnané hradbami a prakticky nezměněné od 16. století. Barevné hrázděné domy v hlavní ulici prý inspirovaly kulisy pohádky Kráska a zvíře. Uvnitř hradeb se nejezdí, parkoviště je hned za branou.', 48.1667, 7.2986, 'https://commons.wikimedia.org/wiki/Special:FilePath/Riquewihr.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Riquewihr.jpg"}'::text[], 2),
    (v_route, 'Restaurace: La Table du Gourmet (Riquewihr)', 'Michelinskou hvězdou oceněná restaurace šéfkuchaře Jeana-Luca Brendela v červeném hrázděném domě z roku 1554. Moderní alsaská kuchyně staví na zelenině a bylinkách z vlastní zahrady; degustační menu patří k zážitkům celé trasy. Na oběd je nutná rezervace, levnější alternativou jsou okolní winstuby.', 48.1668, 7.2984, 'https://commons.wikimedia.org/wiki/Special:FilePath/Riquewihr.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Riquewihr.jpg"}'::text[], 3),
    (v_route, 'Ribeauvillé', 'Město tří hradů — nad vinicemi se tyčí zříceniny Saint-Ulrich, Girsberg a Haut-Ribeaupierre. Dlouhé náměstí lemují renesanční kašny a domy vinařů, v září tu probíhá slavný festival pištců. Příjemná zastávka na kávu před stoupáním k Haut-Kœnigsbourgu.', 48.1953, 7.3196, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ribeauvill%C3%A9.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ribeauvill%C3%A9.jpg"}'::text[], 4),
    (v_route, 'Château du Haut-Kœnigsbourg', 'Monumentální hrad na skalním ostrohu 757 m nad rýnskou nížinou, počátkem 20. století velkolepě obnovený císařem Vilémem II. Serpentiny k hradu jsou nejzábavnějším úsekem celé trasy a z hradeb dohlédnete přes Rýn až ke Schwarzwaldu. V hlavní sezóně dorazte brzy ráno, parkoviště se rychle plní.', 48.2494, 7.3444, 'https://commons.wikimedia.org/wiki/Special:FilePath/Haut-Koenigsbourg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Haut-Koenigsbourg.jpg"}'::text[], 5),
    (v_route, 'Colmar – Petite Venise', 'Čtvrť Malé Benátky v historickém centru Colmaru, kde se hrázděné domy zrcadlí v kanálech říčky Lauch. Ideální místo na závěrečnou procházku a večeři po okruhu; staré město je z velké části pěší zóna. Colmar je zároveň hlavním městem alsaského vína a sídlem slavného Isenheimského oltáře.', 48.0733, 7.3585, 'https://commons.wikimedia.org/wiki/Special:FilePath/Colmar%20Petite%20Venise.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Colmar%20Petite%20Venise.jpg"}'::text[], 6);

  -- Provence – Mont Ventoux a vesnice Luberonu
  delete from public.routes where name = 'Provence – Mont Ventoux a vesnice Luberonu' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Provence – Mont Ventoux a vesnice Luberonu', 'Okruh srdcem Provence spojuje dvě tváře kraje: holý vápencový obr Mont Ventoux (1910 m) s legendárním stoupáním z Bédoin a malebné vesnice Luberonu posazené na skalách nad levandulovými poli. Z vrcholu Ventoux, kde to při mistralu pořádně fouká, sjedete přes levandulové plošiny u Sault do kraje okrových skal Roussillonu a kamenného Gordes. Silnice jsou úzké, zatáčkovité a v létě rozpálené — jeďte brzy ráno, kdy je Ventoux bez aut a levandule nejvoňavější. Nejlepší termín je konec června a červenec, kdy kvete levandule; vrchol Ventoux bývá otevřený zhruba od května do listopadu. Pozor na cyklisty, kterých na Ventoux potkáte stovky, a na štěrk v serpentinách nad hranicí lesa.', 'loop', 165, 280, 'medium',
     '[{"lat": 44.0556, "lng": 5.0489, "label": "Start: Carpentras"}, {"lat": 44.1244, "lng": 5.1797, "label": "Bédoin"}, {"lat": 44.1741, "lng": 5.2786, "label": "Mont Ventoux"}, {"lat": 44.0894, "lng": 5.4103, "label": "Sault"}, {"lat": 43.9028, "lng": 5.2928, "label": "Roussillon"}, {"lat": 43.9114, "lng": 5.2003, "label": "Gordes"}, {"lat": 43.9231, "lng": 5.1272, "label": "Fontaine-de-Vaucluse"}, {"lat": 44.0556, "lng": 5.0489, "label": "Cíl: Carpentras"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=44.0556,5.0489&destination=44.0556,5.0489&travelmode=driving&waypoints=44.1244,5.1797%7C44.1741,5.2786%7C44.0894,5.4103%7C43.9028,5.2928%7C43.9114,5.2003%7C43.9231,5.1272', 'https://commons.wikimedia.org/wiki/Special:FilePath/MontVentoux.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/MontVentoux.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sault%20Vaucluse.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Roussillon%20Vaucluse.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gordes.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20de%20S%C3%A9nanque.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fontaine-de-Vaucluse.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Carpentras.jpg"}'::text[], '{"Mont Ventoux","Sault – levandulová pole","Roussillon – okrové skály","Gordes","Abbaye de Sénanque","Fontaine-de-Vaucluse","Restaurace: Chez Serge (Carpentras)"}'::text[], '{"FR"}'::text[], false, 3830, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Mont Ventoux', 'Obr Provence — osamělá hora s holým vápencovým vrcholem, který z dálky vypadá jako zasněžený. Stoupání z Bédoin má 21 km a přes 1600 výškových metrů, nahoře čeká meteorologická věž, památník cyklisty Toma Simpsona a výhled od Alp po Středozemní moře. Při silném mistralu bývá vrcholová silnice uzavřená.', 44.1741, 5.2786, 'https://commons.wikimedia.org/wiki/Special:FilePath/MontVentoux.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/MontVentoux.jpg"}'::text[], 0),
    (v_route, 'Sault – levandulová pole', 'Městečko na skalní terase nad náhorní plošinou, která se na přelomu června a července změní ve fialový oceán levandule. Sjezd z Ventoux přes Sault patří k nejvoňavějším kilometrům Francie. V místních obchůdcích koupíte levandulový med a nugát.', 44.0894, 5.4103, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sault%20Vaucluse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sault%20Vaucluse.jpg"}'::text[], 1),
    (v_route, 'Roussillon – okrové skály', 'Vesnice vystavěná na největším ložisku okru v Evropě — domy i skály kolem hrají všemi odstíny červené, oranžové a žluté. Krátká procházka Sentier des Ocres vede bývalými lomy jako z jiné planety. Patří mezi oficiálně nejkrásnější vesnice Francie.', 43.9028, 5.2928, 'https://commons.wikimedia.org/wiki/Special:FilePath/Roussillon%20Vaucluse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Roussillon%20Vaucluse.jpg"}'::text[], 2),
    (v_route, 'Gordes', 'Ikona Luberonu — kamenná vesnice nalepená na skalním srázu, kterou proslavily filmy i fotografie z vyhlídky na příjezdové silnici. Renesanční zámek a bludiště kamenných uliček stojí za hodinovou zastávku. Vyhlídka bývá v poledne obsypaná, ráno ji máte pro sebe.', 43.9114, 5.2003, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gordes.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gordes.jpg"}'::text[], 3),
    (v_route, 'Abbaye de Sénanque', 'Cisterciácké opatství z 12. století ukryté v úzkém údolí pod Gordes, před kterým kvetou nejfotografovanější levandulové záhony světa. Mniši tu dodnes žijí a hospodaří; kostel je přístupný a v obchůdku prodávají vlastní levandulové produkty. Úzká přístupová silnice vyžaduje ohleduplnost k protijedoucím.', 43.9286, 5.1869, 'https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20de%20S%C3%A9nanque.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20de%20S%C3%A9nanque.jpg"}'::text[], 4),
    (v_route, 'Fontaine-de-Vaucluse', 'Nejmohutnější pramen Francie — smaragdové jezírko pod 230 m vysokou skalní stěnou, ze kterého vyvěrá řeka Sorgue. Na jaře chrlí až 90 kubíků vody za sekundu a údolí hučí jako vodopád. Podél řeky vede stinná promenáda s kavárnami, ideální na ochlazení v horkém dni.', 43.9231, 5.1272, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fontaine-de-Vaucluse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fontaine-de-Vaucluse.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Chez Serge (Carpentras)', 'Oblíbená restaurace v historickém centru Carpentras, která spojuje provensálskou kuchyni s vynikající prací s lanýži a pizzou z pece na dřevo. Hosté dlouhodobě chválí poměr ceny a kvality i výběr místních vín. Skvělá tečka za celodenním okruhem po Provence.', 44.0546, 5.0478, 'https://commons.wikimedia.org/wiki/Special:FilePath/Carpentras.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Carpentras.jpg"}'::text[], 6);

  -- Ardèche – kaňon řeky a Pont d'Arc
  delete from public.routes where name = 'Ardèche – kaňon řeky a Pont d''Arc' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Ardèche – kaňon řeky a Pont d''Arc', 'Vyhlídková silnice D290 nad kaňonem Gorges de l''Ardèche je jedna z nejefektnějších jízd jižní Francie — 30 km zatáček po hraně vápencové soutěsky s tuctem vyhlídek vysoko nad smaragdovou řekou plnou kánoí. Okruh z Vallon-Pont-d''Arc začíná u slavného skalního oblouku Pont d''Arc, pokračuje po korniši ke všem belvedérům a vrací se přes jeskynní systém Aven d''Orgnac a středověké vesničky Labeaume, Balazuc a Vogüé v údolí řeky. Povrch je dobrý, ale v létě tu bývá hustý turistický provoz a rozpálený asfalt — nejlépe se jede květen, červen a září. Ráno po ránu bývají v kaňonu mlhy a na korniši zvěř. U vyhlídek parkujte jen na značených místech, odtahy tu fungují spolehlivě.', 'loop', 120, 210, 'medium',
     '[{"lat": 44.4067, "lng": 4.3928, "label": "Start: Vallon-Pont-d''Arc"}, {"lat": 44.3803, "lng": 4.4122, "label": "Pont d''Arc"}, {"lat": 44.3390, "lng": 4.5160, "label": "Belvédère de la Madeleine"}, {"lat": 44.3186, "lng": 4.4108, "label": "Aven d''Orgnac"}, {"lat": 44.5083, "lng": 4.3711, "label": "Balazuc"}, {"lat": 44.5386, "lng": 4.4144, "label": "Vogüé"}, {"lat": 44.4067, "lng": 4.3928, "label": "Cíl: Vallon-Pont-d''Arc"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=44.4067,4.3928&destination=44.4067,4.3928&travelmode=driving&waypoints=44.3803,4.4122%7C44.3390,4.5160%7C44.3186,4.4108%7C44.5083,4.3711%7C44.5386,4.4144', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20d%27Arc.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20d%27Arc.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gorges%20de%20l%27Ard%C3%A8che.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Aven%20d%27Orgnac.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Labeaume.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Balazuc.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vog%C3%BC%C3%A9.jpg"}'::text[], '{"Pont d''Arc","Belvédère de la Madeleine (Gorges de l''Ardèche)","Aven d''Orgnac","Labeaume","Balazuc","Vogüé"}'::text[], '{"FR"}'::text[], false, 3840, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Pont d''Arc', 'Přírodní skalní oblouk vysoký 54 metrů, kterým protéká řeka Ardèche — symbol celého kraje a startovní brána kaňonu. Pláže pod obloukem lákají ke koupání, nad řekou křižují kánoe. Kousek odtud je replika jeskyně Chauvet s nejstaršími malbami lidstva.', 44.3803, 4.4122, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20d%27Arc.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20d%27Arc.jpg"}'::text[], 0),
    (v_route, 'Belvédère de la Madeleine (Gorges de l''Ardèche)', 'Nejslavnější z vyhlídek na korniši D290 — řeka se tu 300 metrů pod vámi stáčí kolem skalní jehly Cathédrale. Vyhlídková silnice mezi Vallon a Saint-Martin-d''Ardèche nabízí tucet podobných balkonů, Madeleine je z nich nejvzdušnější. Ideální místo na fotku celé soutěsky.', 44.3390, 4.5160, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gorges%20de%20l%27Ard%C3%A8che.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gorges%20de%20l%27Ard%C3%A8che.jpg"}'::text[], 1),
    (v_route, 'Aven d''Orgnac', 'Jedna z největších zpřístupněných propastí Evropy — výtah vás sveze 121 metrů pod zem do sálů s krápníky vysokými přes 10 metrů. Prohlídka trvá hodinu a v podzemí je stálých 12 °C, což v létě přijde vhod. Součástí areálu je moderní muzeum pravěku.', 44.3186, 4.4108, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aven%20d%27Orgnac.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aven%20d%27Orgnac.jpg"}'::text[], 2),
    (v_route, 'Labeaume', 'Kamenná vesnice vklíněná mezi skály nad říčkou Beaume, s náměstíčkem pod platany a domy srostlými s vápencovou stěnou. Od řeky se dá vyjít na vyhlídku nad meandrem. Klidnější alternativa přeplněných slavnějších sousedů.', 44.4703, 4.3417, 'https://commons.wikimedia.org/wiki/Special:FilePath/Labeaume.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Labeaume.jpg"}'::text[], 3),
    (v_route, 'Balazuc', 'Oficiálně jedna z nejkrásnějších vesnic Francie — kamenné domy šplhají po útesu nad řekou Ardèche a silnice pod vesnicí přechází řeku úzkým mostem s krásným výhledem. Románský kostelík a uličky sotva na šířku ramen stojí za procházku. V létě funguje pláž přímo pod vsí.', 44.5083, 4.3711, 'https://commons.wikimedia.org/wiki/Special:FilePath/Balazuc.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Balazuc.jpg"}'::text[], 4),
    (v_route, 'Vogüé', 'Vesnice pod obloukovitou skalní stěnou, které vévodí zámek rodu Vogüé s visutými zahradami. Domy s podloubími lemují břeh Ardèche a od mostu je jedno z nejmalebnějších panoramat kraje. Dobrá kávová zastávka před návratem do Vallon.', 44.5386, 4.4144, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vog%C3%BC%C3%A9.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vog%C3%BC%C3%A9.jpg"}'::text[], 5);

  -- Auvergne – kraj vyhaslých sopek
  delete from public.routes where name = 'Auvergne – kraj vyhaslých sopek' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Auvergne – kraj vyhaslých sopek', 'Okruh největším sopečným polem Evropy — Chaîne des Puys u Clermont-Ferrand je od roku 2018 na seznamu UNESCO a z motorky vypadá jako krajina z jiné planety: desítky pravidelných zelených kuželů, kráterová jezera a horské pastviny. Trasa vede prázdnými silnicemi přes úpatí Puy de Dôme, kolem jezera Guéry do lázeňského Le Mont-Dore pod nejvyšší horou Massif Central Puy de Sancy a zpět přes kráterové jezero Pavin a středověké Besse. Provoz je i v sezóně minimální, asfalt slušný a zatáček nekonečno; ideální období je květen až říjen. Počítejte s rychlými změnami počasí — Sancy umí i v létě zatáhnout a zchladit pod deset stupňů. Na pastvinách se volně pohybují krávy salers, v zatáčkách přes hřebeny jezděte s rezervou.', 'loop', 150, 240, 'medium',
     '[{"lat": 45.7772, "lng": 3.0870, "label": "Start: Clermont-Ferrand"}, {"lat": 45.7961, "lng": 2.9700, "label": "Puy de Pariou"}, {"lat": 45.7722, "lng": 2.9644, "label": "Puy de Dôme"}, {"lat": 45.6083, "lng": 2.8092, "label": "Lac de Guéry"}, {"lat": 45.5714, "lng": 2.8083, "label": "Le Mont-Dore"}, {"lat": 45.4956, "lng": 2.8878, "label": "Lac Pavin"}, {"lat": 45.5178, "lng": 2.9331, "label": "Besse-et-Saint-Anastaise"}, {"lat": 45.7772, "lng": 3.0870, "label": "Cíl: Clermont-Ferrand"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.7772,3.0870&destination=45.7772,3.0870&travelmode=driving&waypoints=45.7961,2.9700%7C45.7722,2.9644%7C45.6083,2.8092%7C45.5714,2.8083%7C45.4956,2.8878%7C45.5178,2.9331', 'https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20de%20D%C3%B4me.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20de%20D%C3%B4me.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20Pariou.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Gu%C3%A9ry.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20de%20Sancy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Mont-Dore.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20Pavin.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Besse-et-Saint-Anastaise.jpg"}'::text[], '{"Puy de Dôme","Puy de Pariou","Lac de Guéry","Puy de Sancy","Restaurace: Le Bougnat (Le Mont-Dore)","Lac Pavin","Besse-et-Saint-Anastaise"}'::text[], '{"FR"}'::text[], false, 3850, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Puy de Dôme', 'Nejvyšší sopka řetězu Chaîne des Puys (1465 m) s římským chrámem boha Merkura na vrcholu. Nahoru vás vyveze zubačka Panoramique des Dômes — z vrcholu přehlédnete všech osmdesát sopek najednou. Symbol Auvergne a jeden z nejnavštěvovanějších vrcholů Francie.', 45.7722, 2.9644, 'https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20de%20D%C3%B4me.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20de%20D%C3%B4me.jpg"}'::text[], 0),
    (v_route, 'Puy de Pariou', 'Učebnicová sopka s dokonale kruhovým kráterem hlubokým 97 metrů, známá z reklam na minerálku Volvic. Z parkoviště u silnice D941 se dá vyjít na hranu kráteru za necelou hodinu. Kužel porostlý trávou je nejfotogeničtější z celého řetězu.', 45.7961, 2.9700, 'https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20Pariou.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20Pariou.jpg"}'::text[], 1),
    (v_route, 'Lac de Guéry', 'Nejvýše položené jezero Auvergne (1250 m) vzniklé přehrazením údolí lávovým proudem, s výhledem na skalní věže Tuilière a Sanadoire. Silnice přes Col de Guéry patří k nejhezčím úsekům okruhu. V zimě se tu jako na jediném místě Francie loví ryby dírou v ledu.', 45.6083, 2.8092, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Gu%C3%A9ry.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Gu%C3%A9ry.jpg"}'::text[], 2),
    (v_route, 'Puy de Sancy', 'Nejvyšší hora Francouzského středohoří (1885 m), rozeklaný pozůstatek obřího stratovulkánu nad lázněmi Le Mont-Dore. Lanovka a schody vás dostanou na vrcholový hřeben s výhledem přes půl Francie. Pod horou pramení Dordogne.', 45.5286, 2.8139, 'https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20de%20Sancy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puy%20de%20Sancy.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Le Bougnat (Le Mont-Dore)', 'Tradiční auvergnská hospoda v centru lázeňského Le Mont-Dore, kde servírují krajové speciality jako truffade, aligot a potée auvergnate. Poctivé porce, místní sýry saint-nectaire a přátelská atmosféra z ní dělají ideální obědovou zastávku uprostřed okruhu. V sezóně počítejte s čekáním.', 45.5714, 2.8083, 'https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Mont-Dore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Mont-Dore.jpg"}'::text[], 4),
    (v_route, 'Lac Pavin', 'Dokonale kruhové kráterové jezero o průměru 800 metrů a hloubce 92 metrů, nejmladší sopečný útvar Francie (vybuchl před pouhými 7000 lety). Temně modrá hladina obklopená lesem působí až tajemně — podle pověstí je na dně potopené město. Kolem jezera vede pohodlná stezka.', 45.4956, 2.8878, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20Pavin.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20Pavin.jpg"}'::text[], 5),
    (v_route, 'Besse-et-Saint-Anastaise', 'Středověké městečko postavené z černé lávy, s branami, věžemi a kupeckými domy z 15. století. Je centrem výroby sýra saint-nectaire — v krámcích ho koupíte přímo od farmářů. Tmavý kámen dává uličkám nezaměnitelnou atmosféru.', 45.5178, 2.9331, 'https://commons.wikimedia.org/wiki/Special:FilePath/Besse-et-Saint-Anastaise.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Besse-et-Saint-Anastaise.jpg"}'::text[], 6);

  -- Pyreneje – Col du Tourmalet a Pic du Midi
  delete from public.routes where name = 'Pyreneje – Col du Tourmalet a Pic du Midi' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Pyreneje – Col du Tourmalet a Pic du Midi', 'Okruh přes dva legendární pyrenejské průsmyky Tour de France — Col du Tourmalet (2115 m), nejvyšší silniční sedlo francouzských Pyrenejí, a zelený Col d''Aspin (1490 m). Z poutního města Lourdes stoupáte soutěskou do Luz-Saint-Sauveur a pak devatenácti kilometry serpentin na Tourmalet, kde vás přivítá socha obřího cyklisty a výhled na observatoř Pic du Midi. Sjezd přes lyžařskou La Mongie střídá pastviny s volně pobíhajícími ovcemi, lamami a kravami — brzděte s předstihem. Průsmyky jsou průjezdné zhruba od června do října, mimo tento čas hrozí sníh; nejlepší je září, kdy zmizí karavany. Náročnější trasa odmění jezdce jedním z nejkrásnějších vysokohorských dnů ve Francii.', 'loop', 165, 270, 'hard',
     '[{"lat": 43.0983, "lng": -0.0508, "label": "Start: Lourdes"}, {"lat": 42.8722, "lng": 0.0011, "label": "Luz-Saint-Sauveur"}, {"lat": 42.9083, "lng": 0.1450, "label": "Col du Tourmalet"}, {"lat": 42.9394, "lng": 0.3258, "label": "Col d''Aspin"}, {"lat": 42.9047, "lng": 0.3592, "label": "Arreau"}, {"lat": 43.0647, "lng": 0.1497, "label": "Bagnères-de-Bigorre"}, {"lat": 43.0983, "lng": -0.0508, "label": "Cíl: Lourdes"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.0983,-0.0508&destination=43.0983,-0.0508&travelmode=driving&waypoints=42.8722,0.0011%7C42.9083,0.1450%7C42.9394,0.3258%7C42.9047,0.3592%7C43.0647,0.1497', 'https://commons.wikimedia.org/wiki/Special:FilePath/Col%20du%20Tourmalet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lourdes%20Basilique.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Luz-Saint-Sauveur.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Col%20du%20Tourmalet.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pic%20du%20Midi%20de%20Bigorre.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Col%20d%27Aspin.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Arreau.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bagn%C3%A8res-de-Bigorre.jpg"}'::text[], '{"Sanktuárium Lourdes","Luz-Saint-Sauveur","Col du Tourmalet","Pic du Midi de Bigorre","Col d''Aspin","Arreau","Restaurace: Le Jardin des Brouches (Bagnères-de-Bigorre)"}'::text[], '{"FR"}'::text[], false, 3860, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Sanktuárium Lourdes', 'Nejnavštěvovanější poutní místo Francie s bazilikou Růžence nad jeskyní zjevení Panny Marie. I bez náboženského rozměru stojí monumentální areál nad řekou Gave de Pau za ranní procházku, než vyrazíte do hor. Večer tu probíhají působivá světelná procesí.', 43.0975, -0.0583, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lourdes%20Basilique.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lourdes%20Basilique.jpg"}'::text[], 0),
    (v_route, 'Luz-Saint-Sauveur', 'Horské městečko na soutoku dvou údolí s opevněným templářským kostelem a Napoleonovým mostem klenoucím se 65 metrů nad soutěskou. Poslední zastávka na kávu a palivo před stoupáním na Tourmalet. V sezóně tu žije čilý horský ruch.', 42.8722, 0.0011, 'https://commons.wikimedia.org/wiki/Special:FilePath/Luz-Saint-Sauveur.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Luz-Saint-Sauveur.jpg"}'::text[], 1),
    (v_route, 'Col du Tourmalet', 'Nejslavnější průsmyk Tour de France (2115 m), zdolávaný závodem častěji než kterýkoli jiný. Na vrcholu stojí stříbrná socha Octave Lapize — Géant du Tourmalet — a panorama holých štítů střeží observatoř na Pic du Midi. Serpentiny z obou stran patří k nejlepším motorkářským stoupáním Pyrenejí.', 42.9083, 0.1450, 'https://commons.wikimedia.org/wiki/Special:FilePath/Col%20du%20Tourmalet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Col%20du%20Tourmalet.jpg"}'::text[], 2),
    (v_route, 'Pic du Midi de Bigorre', 'Hvězdárna na vrcholu ve výšce 2877 m, kam z lyžařské La Mongie jezdí kabinová lanovka. Z teras je závratný výhled na tři sta kilometrů pyrenejského hřebene — za jasného dne jeden z nejlepších vyhlídkových bodů Francie. Nahoře funguje muzeum i restaurace.', 42.9369, 0.1411, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pic%20du%20Midi%20de%20Bigorre.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pic%20du%20Midi%20de%20Bigorre.jpg"}'::text[], 3),
    (v_route, 'Col d''Aspin', 'Zelený protipól drsného Tourmaletu — sedlo v 1490 m obklopené pastvinami s výhledem na štít Arbizon. Krávy tu leží klidně i uprostřed silnice, což dodává průsmyku pohodovou atmosféru. Sjezd do Arreau je plynulý tanec dlouhých zatáček mezi lesy.', 42.9394, 0.3258, 'https://commons.wikimedia.org/wiki/Special:FilePath/Col%20d%27Aspin.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Col%20d%27Aspin.jpg"}'::text[], 4),
    (v_route, 'Arreau', 'Půvabné kamenné městečko na soutoku dvou řek, křižovatka pyrenejských údolí s hrázděnou tržnicí a břidlicovými střechami. Ideální místo na oběd nebo zmrzlinu mezi průsmyky. Odtud se trasa stáčí zpět na sever podél řeky Neste.', 42.9047, 0.3592, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arreau.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arreau.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Le Jardin des Brouches (Bagnères-de-Bigorre)', 'Vyhlášená restaurace v lázeňském Bagnères-de-Bigorre s moderní pyrenejskou kuchyní z lokálních surovin — jehněčí z okolních pastvin, horské sýry a sezónní zelenina. Hosté dlouhodobě chválí přívětivou obsluhu i zahradní terasu. Skvělé zakončení vysokohorského dne.', 43.0647, 0.1497, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bagn%C3%A8res-de-Bigorre.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bagn%C3%A8res-de-Bigorre.jpg"}'::text[], 6);

  -- Bretaň – Pointe du Raz a poloostrov Crozon
  delete from public.routes where name = 'Bretaň – Pointe du Raz a poloostrov Crozon' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Bretaň – Pointe du Raz a poloostrov Crozon', 'Okruh nejdivočejším koncem Bretaně — krajem Finistère, „koncem světa". Z Quimperu zamíříte přes středověký Locronan na poloostrov Crozon k útesům Pointe de Pen-Hir, pak podél zálivu do rybářského Douarnenez a na západní výspu Francie Pointe du Raz, kde se Atlantik tříští o žulové skály u majáků. Silnice jsou úzké, zvlněné a lemované kamennými zídkami a vřesovišti; provoz mimo červenec a srpen minimální. Nejhezčí je jízda za proměnlivého počasí, kdy se nad oceánem honí mraky — počítejte ale s větrem a přeháňkami v kterémkoli měsíci. Pozor na kluzké rozjeté řasy a písek na pobřežních úsecích.', 'loop', 210, 300, 'medium',
     '[{"lat": 47.9960, "lng": -4.1028, "label": "Start: Quimper"}, {"lat": 48.0981, "lng": -4.2094, "label": "Locronan"}, {"lat": 48.2597, "lng": -4.6272, "label": "Pointe de Pen-Hir"}, {"lat": 48.0922, "lng": -4.3286, "label": "Douarnenez"}, {"lat": 48.0397, "lng": -4.7369, "label": "Pointe du Raz"}, {"lat": 48.0219, "lng": -4.5386, "label": "Audierne"}, {"lat": 47.9960, "lng": -4.1028, "label": "Cíl: Quimper"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.9960,-4.1028&destination=47.9960,-4.1028&travelmode=driving&waypoints=48.0981,-4.2094%7C48.2597,-4.6272%7C48.0922,-4.3286%7C48.0397,-4.7369%7C48.0219,-4.5386', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pointe%20du%20Raz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Locronan.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Locronan.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pointe%20de%20Pen-Hir.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Douarnenez.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pointe%20du%20Raz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20Saint-Corentin%20de%20Quimper.jpg"}'::text[], '{"Locronan","Restaurace: Crêperie Ty Coz (Locronan)","Pointe de Pen-Hir","Douarnenez","Pointe du Raz","Quimper – katedrála sv. Korentina"}'::text[], '{"FR"}'::text[], false, 3870, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Locronan', 'Dokonale zachované středověké městečko z žulových domů kolem kostela sv. Ronana, kde se točily filmy jako Tess. Auta ani motorky do centra nesmí, parkoviště je hned za vsí. Jedna z oficiálně nejkrásnějších vesnic Francie a povinná zastávka trasy.', 48.0981, -4.2094, 'https://commons.wikimedia.org/wiki/Special:FilePath/Locronan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Locronan.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Crêperie Ty Coz (Locronan)', 'Tradiční bretaňská creperie v kamenném domě přímo v historickém jádru Locronanu. Pohankové galettes s místními surovinami a sladké palačinky s karamelem ze slaného másla patří k nejlépe hodnoceným v kraji. K tomu si dejte jablečný cidre — pro jezdce samozřejmě až večer, nebo sáhněte po nealko moštu.', 48.0980, -4.2092, 'https://commons.wikimedia.org/wiki/Special:FilePath/Locronan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Locronan.jpg"}'::text[], 1),
    (v_route, 'Pointe de Pen-Hir', 'Nejefektnější mys poloostrova Crozon se 70metrovými útesy a řadou skalisek Tas de Pois trčících z oceánu. Nad útesy stojí mohutný kříž — památník bretaňského odboje. Kolem vedou stezky vřesovištěm s výhledy, které berou dech.', 48.2597, -4.6272, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pointe%20de%20Pen-Hir.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pointe%20de%20Pen-Hir.jpg"}'::text[], 2),
    (v_route, 'Douarnenez', 'Rybářské město proslulé sardinkami a přístavem Port-Rhu s muzejními loděmi. Podle legendy leží v zálivu potopené město Ys. Nábřeží s barevnými domky a konzervárenskými krámky je příjemné místo na protažení nohou.', 48.0922, -4.3286, 'https://commons.wikimedia.org/wiki/Special:FilePath/Douarnenez.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Douarnenez.jpg"}'::text[], 3),
    (v_route, 'Pointe du Raz', 'Nejzápadnější dramatický výběžek Bretaně — žulové útesy vysoké 72 metrů, o které se tříští atlantický příboj, a výhled na maják Vieille v divoké úžině Raz de Sein. Od parkoviště k mysu se jde pěšky asi 20 minut vřesovištěm. Za bouřlivého počasí nezapomenutelné divadlo živlů.', 48.0397, -4.7369, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pointe%20du%20Raz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pointe%20du%20Raz.jpg"}'::text[], 4),
    (v_route, 'Quimper – katedrála sv. Korentina', 'Hlavní město tradiční Cornouaille s gotickou katedrálou, jejíž dvě věže dominují hrázděnému starému městu na řece Odet. Město proslulo ručně malovanou fajánsí, kterou tu vyrábějí přes 300 let. Ideální start i cíl okruhu s dobrou nabídkou ubytování.', 47.9960, -4.1028, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20Saint-Corentin%20de%20Quimper.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20Saint-Corentin%20de%20Quimper.jpg"}'::text[], 5);

  -- Normandie – útesy Étretat a Honfleur
  delete from public.routes where name = 'Normandie – útesy Étretat a Honfleur' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Normandie – útesy Étretat a Honfleur', 'Pohodová jízda podél Alabastrového pobřeží Normandie z Fécampu do Deauville, ve stopách impresionistů. Křídové útesy u Étretat s proslulými skalními oblouky patří k nejikoničtějším scenériím Francie a silnice mezi poli lnu a řepky nad nimi jsou příjemně plynulé. Přes elegantní most Pont de Normandie, klenoucí se 60 metrů nad ústím Seiny, dojedete do malířského přístavu Honfleur a zakončíte na promenádě mondénního Deauville. Trasa je nenáročná a krásná od jara do podzimu; nejhezčí světlo na útesech je ráno a za soumraku. Počítejte s větrem od Kanálu a o víkendech s výletním provozem u Étretat, kde parkujte na záchytných parkovištích.', 'poi', 110, 180, 'easy',
     '[{"lat": 49.7581, "lng": 0.3742, "label": "Start: Fécamp"}, {"lat": 49.7069, "lng": 0.2050, "label": "Étretat"}, {"lat": 49.4325, "lng": 0.2747, "label": "Pont de Normandie"}, {"lat": 49.4194, "lng": 0.2331, "label": "Honfleur"}, {"lat": 49.3600, "lng": 0.0750, "label": "Cíl: Deauville"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.7581,0.3742&destination=49.3600,0.0750&travelmode=driving&waypoints=49.7069,0.2050%7C49.4325,0.2747%7C49.4194,0.2331', 'https://commons.wikimedia.org/wiki/Special:FilePath/Etretat.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palais%20B%C3%A9n%C3%A9dictine.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Etretat.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20de%20Normandie.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%20Vieux%20Bassin.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%20Vieux%20Bassin.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Deauville.jpg"}'::text[], '{"Fécamp – Palais Bénédictine","Étretat – útesy a oblouk Aval","Pont de Normandie","Honfleur – Vieux Bassin","Restaurace: Le Bréard (Honfleur)","Deauville – Les Planches"}'::text[], '{"FR"}'::text[], false, 3880, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Fécamp – Palais Bénédictine', 'Extravagantní novogotický palác, kde se dodnes vyrábí bylinný likér Bénédictine z 27 bylin a koření. Prohlídka provede palácem, muzeem i destilerií; degustaci si jezdec schová na večer. Fécamp je zároveň starý rybářský přístav pod nejvyššími útesy Alabastrového pobřeží.', 49.7581, 0.3742, 'https://commons.wikimedia.org/wiki/Special:FilePath/Palais%20B%C3%A9n%C3%A9dictine.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palais%20B%C3%A9n%C3%A9dictine.jpg"}'::text[], 0),
    (v_route, 'Étretat – útesy a oblouk Aval', 'Křídové útesy s obloukem Porte d''Aval a osamělou jehlou Aiguille, které maloval Monet i Courbet. Nejlepší výhled je z útesu Amont u kapličky námořníků, kam se dá vyjít pěšky z města. Ráno a večer patří scenérie k nejfotogeničtějším místům celé Francie.', 49.7069, 0.2050, 'https://commons.wikimedia.org/wiki/Special:FilePath/Etretat.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Etretat.jpg"}'::text[], 1),
    (v_route, 'Pont de Normandie', 'Elegantní zavěšený most přes ústí Seiny s rozpětím 856 metrů, při otevření v roce 1995 nejdelší svého druhu na světě. Přejezd po mostě 60 metrů nad řekou je zážitek sám o sobě — při bočním větru držte pevně řídítka. Mýtné pro motocykly je snížené.', 49.4325, 0.2747, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20de%20Normandie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20de%20Normandie.jpg"}'::text[], 2),
    (v_route, 'Honfleur – Vieux Bassin', 'Starý přístavní bazén lemovaný úzkými břidlicovými domy, jeden z nejmalebnějších přístavů Evropy a kolébka impresionismu. Za návštěvu stojí dřevěný kostel sv. Kateřiny stavěný loďaři jako obrácený trup lodi. Nábřežní kavárny jsou ideální na odpolední pauzu.', 49.4194, 0.2331, 'https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%20Vieux%20Bassin.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%20Vieux%20Bassin.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Le Bréard (Honfleur)', 'Elegantní gastronomická restaurace v dlážděné uličce kousek od kostela sv. Kateřiny. Šéfkuchař staví na normandských surovinách — mušle svatého Jakuba, ryby z Kanálu a sýry z okolních farem — v moderním podání. Patří k nejlépe hodnoceným podnikům v Honfleur, rezervace nutná.', 49.4189, 0.2336, 'https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%20Vieux%20Bassin.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%20Vieux%20Bassin.jpg"}'::text[], 4),
    (v_route, 'Deauville – Les Planches', 'Mondénní přímořské letovisko s proslulou prkennou promenádou Les Planches, plážovými slunečníky a kabinkami se jmény filmových hvězd amerického festivalu. Belle époque vily, kasino a dostihová dráha dotvářejí atmosféru „pařížského 21. obvodu". Stylová tečka za projížďkou Normandií.', 49.3600, 0.0750, 'https://commons.wikimedia.org/wiki/Special:FilePath/Deauville.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Deauville.jpg"}'::text[], 5);

  -- Route Napoléon – z Grasse do Grenoblu
  delete from public.routes where name = 'Route Napoléon – z Grasse do Grenoblu' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Route Napoléon – z Grasse do Grenoblu', 'Slavná N85 sleduje cestu, kterou Napoleon v březnu 1815 táhl z Elby na Paříž — a dnes je to jedna z nejlepších motorkářských dálkových silnic Evropy. Z voňavého města parfémů Grasse stoupá přes provensálské vápencové hřebeny ke Castellane, pokračuje levandulovým krajem kolem Digne-les-Bains a pod citadelou v Sisteronu vjíždí do alpského předhůří k Gapu a jezerům u Laffrey. Široké oblouky, kvalitní asfalt a věčné střídání scenérií od olivovníků po alpské štíty dělají z celodenní jízdy zážitek bez jediného nudného kilometru. Ideální období je květen až říjen; v létě se vyhněte přehřátému odpoledni na jihu a víkendovým kolonám u Grenoblu. Orlí siluety na značkách podél cesty připomínají císařův let na sever.', 'poi', 330, 420, 'medium',
     '[{"lat": 43.6589, "lng": 6.9256, "label": "Start: Grasse"}, {"lat": 43.8469, "lng": 6.5128, "label": "Castellane"}, {"lat": 44.0919, "lng": 6.2358, "label": "Digne-les-Bains"}, {"lat": 44.1950, "lng": 5.9433, "label": "Sisteron"}, {"lat": 44.5594, "lng": 6.0786, "label": "Gap"}, {"lat": 45.0197, "lng": 5.7736, "label": "Laffrey"}, {"lat": 45.1885, "lng": 5.7245, "label": "Cíl: Grenoble"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.6589,6.9256&destination=45.1885,5.7245&travelmode=driving&waypoints=43.8469,6.5128%7C44.0919,6.2358%7C44.1950,5.9433%7C44.5594,6.0786%7C45.0197,5.7736', 'https://commons.wikimedia.org/wiki/Special:FilePath/Grasse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grasse.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castellane.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Digne-les-Bains.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sisteron.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sisteron.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Laffrey.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grenoble.jpg"}'::text[], '{"Grasse – město parfémů","Castellane","Digne-les-Bains","Sisteron – citadela","Restaurace: Les Becs Fins (Sisteron)","Lac de Laffrey","Grenoble – Bastille"}'::text[], '{"FR"}'::text[], false, 3890, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Grasse – město parfémů', 'Světová metropole parfémů na svazích nad Azurovým pobřežím, kde Napoleonova cesta na sever začíná. Historické parfumerie Fragonard a Molinard nabízejí prohlídky zdarma a staré město voní jasmínem. Než vyrazíte, projděte si terasy s výhledem až k moři.', 43.6589, 6.9256, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grasse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grasse.jpg"}'::text[], 0),
    (v_route, 'Castellane', 'Městečko sevřené horami, nad kterým na 184 metrů vysoké skále stojí kaple Notre-Dame du Roc. Náměstíčko s platany je tradiční motorkářská zastávka na kávu — sjíždějí se sem jezdci z celé Evropy. Napoleon tudy prošel 3. března 1815, jak připomíná deska na radnici.', 43.8469, 6.5128, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castellane.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castellane.jpg"}'::text[], 1),
    (v_route, 'Digne-les-Bains', 'Lázeňské město uprostřed levandulových polí a geologicky nejbohatšího území Francie — okolní geopark UNESCO chrání stěny s tisíci zkamenělými amonity. Každý srpen tu vrcholí levandulové slavnosti Corso de la Lavande. Příjemná zastávka na oběd ve stínu platanů.', 44.0919, 6.2358, 'https://commons.wikimedia.org/wiki/Special:FilePath/Digne-les-Bains.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Digne-les-Bains.jpg"}'::text[], 2),
    (v_route, 'Sisteron – citadela', 'Brána Provence — mohutná citadela na skále nad průrvou řeky Durance, proti níž se zvedá zvrásněný masiv Rocher de la Baume. Průjezd soutěskou pod hradbami je jedním z nejefektnějších momentů celé N85. Z hradeb citadely přehlédnete půlku trasy.', 44.1950, 5.9433, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sisteron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sisteron.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Les Becs Fins (Sisteron)', 'Tradiční rodinná restaurace v centru Sisteronu proslulá místní specialitou — jehněčím ze sisteronských pastvin, které patří k nejlepším ve Francii. Poctivá provensálská kuchyně a rozumné ceny z ní dělají ideální obědovou zastávku v půli Route Napoléon. V sezóně si rezervujte stůl na terase.', 44.1948, 5.9435, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sisteron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sisteron.jpg"}'::text[], 4),
    (v_route, 'Lac de Laffrey', 'Největší ze čtyř jezer na náhorní plošině Matheysine, kde se 7. března 1815 odehrálo slavné setkání: Napoleon se tu postavil vojsku vyslanému ho zatknout — a vojáci přeběhli k němu. Událost připomíná jezdecká socha císaře na Prairie de la Rencontre nad jezerem. Chladná voda jezera láká v létě ke koupání.', 45.0264, 5.7758, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Laffrey.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Laffrey.jpg"}'::text[], 5),
    (v_route, 'Grenoble – Bastille', 'Alpská metropole obklopená třemi horskými masivy, kde Route Napoléon končí. Bublinové lanovky vyvezou z centra na pevnost Bastille s výhledem na město a za jasného dne až na Mont Blanc. Staré město s kavárnami je příjemným místem na závěrečnou večeři.', 45.1885, 5.7245, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grenoble.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grenoble.jpg"}'::text[], 6);

  -- Cévennes – Corniche a viadukt Millau
  delete from public.routes where name = 'Cévennes – Corniche a viadukt Millau' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Cévennes – Corniche a viadukt Millau', 'Přejezd divokým národním parkem Cévennes po hřebenové Corniche des Cévennes — historické cestě táhnoucí se po rozvodí mezi kaštanovými údolími, kterou proslavil už R. L. Stevenson s oslicí Modestine. Z Anduze stoupáte na korniš s výhledy na moře hřebenů, sjedete do Floraku na okraji vápencových planin a přes větrný vrchol Mont Aigoual (1567 m) pokračujete do Meyrueis a kaňonem řeky Jonte k velkolepému finále — viaduktu Millau, nejvyššímu mostu světa. Silnice jsou úzké, prázdné a nekonečně zatáčkovité; tankujte průběžně, benzinek je tu málo. Nejlepší období je květen až říjen, na podzim kraj hraje barvami kaštanů. Na Aigoualu počítejte s větrem a mlhou i uprostřed léta.', 'poi', 185, 300, 'medium',
     '[{"lat": 44.0536, "lng": 3.9856, "label": "Start: Anduze"}, {"lat": 44.1044, "lng": 3.8858, "label": "Saint-Jean-du-Gard"}, {"lat": 44.2036, "lng": 3.7025, "label": "Corniche des Cévennes"}, {"lat": 44.3242, "lng": 3.5936, "label": "Florac"}, {"lat": 44.1214, "lng": 3.5817, "label": "Mont Aigoual"}, {"lat": 44.1800, "lng": 3.4297, "label": "Meyrueis"}, {"lat": 44.0986, "lng": 3.0783, "label": "Cíl: Millau"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=44.0536,3.9856&destination=44.0986,3.0783&travelmode=driving&waypoints=44.1044,3.8858%7C44.2036,3.7025%7C44.3242,3.5936%7C44.1214,3.5817%7C44.1800,3.4297', 'https://commons.wikimedia.org/wiki/Special:FilePath/ViaducdeMillau.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Anduze.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Corniche%20des%20C%C3%A9vennes.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Florac.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Florac.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mont%20Aigoual.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Meyrueis.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/ViaducdeMillau.jpg"}'::text[], '{"Anduze – brána Cévenn","Corniche des Cévennes","Florac","Restaurace: L''Adonis (Florac)","Mont Aigoual","Meyrueis","Viaduc de Millau"}'::text[], '{"FR"}'::text[], false, 3900, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Anduze – brána Cévenn', 'Městečko sevřené skalní branou řeky Gardon, odkud začíná stoupání do hor. Za návštěvu stojí obří bambusový park Bambouseraie, největší v Evropě, a keramické trhy proslulé vázami z Anduze. Poslední pořádné zásobovací místo před horami.', 44.0536, 3.9856, 'https://commons.wikimedia.org/wiki/Special:FilePath/Anduze.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Anduze.jpg"}'::text[], 0),
    (v_route, 'Corniche des Cévennes', 'Hřebenová silnice D9 mezi Saint-Jean-du-Gard a Florakem, vedoucí desítky kilometrů po rozvodí s výhledy do kaštanových údolí na obě strany. Vinula se tudy královská cesta z dob válek s kamizardy a dnes je to motorkářský klenot — prázdná, plynulá, s panoramaty na každém kilometru. Zastavte na sedle Col des Faïsses.', 44.2036, 3.7025, 'https://commons.wikimedia.org/wiki/Special:FilePath/Corniche%20des%20C%C3%A9vennes.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Corniche%20des%20C%C3%A9vennes.jpg"}'::text[], 1),
    (v_route, 'Florac', 'Městečko na soutoku tří řek pod vápencovou stěnou planiny Causse Méjean, sídlo správy národního parku Cévennes. Zámeček s expozicí parku a uličky podél kanálů stojí za krátkou procházku. Strategické místo na oběd uprostřed přejezdu.', 44.3242, 3.5936, 'https://commons.wikimedia.org/wiki/Special:FilePath/Florac.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Florac.jpg"}'::text[], 2),
    (v_route, 'Restaurace: L''Adonis (Florac)', 'Restaurace rodinného hotelu Gorges du Tarn ve Floraku, oceňovaná za moderní kuchyni z lokálních surovin Lozère — pstruzi z horských řek, jehněčí z planin a cévennská cibule. Slunná terasa a milá obsluha z ní dělají nejlepší obědovou zastávku trasy. Mimo sezónu ověřte otevírací dobu.', 44.3245, 3.5931, 'https://commons.wikimedia.org/wiki/Special:FilePath/Florac.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Florac.jpg"}'::text[], 3),
    (v_route, 'Mont Aigoual', 'Nejvyšší hora jižních Cévenn (1567 m) s poslední obsazenou horskou meteorologickou observatoří Francie na vrcholu. Za jasného dne dohlédnete od Alp přes Středozemní moře až k Pyrenejím — a vane tu vítr, který láme rekordy. Silnice na vrchol je plynulá a vede až k observatoři s muzeem počasí.', 44.1214, 3.5817, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mont%20Aigoual.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mont%20Aigoual.jpg"}'::text[], 4),
    (v_route, 'Meyrueis', 'Horské městečko na dně kaňonu řeky Jonte, ideální základna mezi planinami Causses a Cévennami. Odtud vede sjezd soutěskou Gorges de la Jonte, nad kterou krouží supi bělohlaví z nedaleké rezervace. Náměstíčko s kavárnami u řeky je stvořené na poslední kávu před Millau.', 44.1800, 3.4297, 'https://commons.wikimedia.org/wiki/Special:FilePath/Meyrueis.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Meyrueis.jpg"}'::text[], 5),
    (v_route, 'Viaduc de Millau', 'Nejvyšší most světa — mistrovské dílo Normana Fostera a Michela Virlogeuxe, jehož pylony ční 343 metrů nad údolím Tarnu. Nejlepší pohled je z vyhlídky u informačního centra pod mostem nebo z městečka Peyre na břehu Tarnu. Velkolepá tečka za přejezdem Cévenn.', 44.0789, 3.0225, 'https://commons.wikimedia.org/wiki/Special:FilePath/ViaducdeMillau.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/ViaducdeMillau.jpg"}'::text[], 6);

end $$;
