-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — VYSOČINA 2026 (10 tras, sort 2100+)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Zámky na Oslavě – Velké Meziříčí a Náměšť
  delete from public.routes where name = 'Zámky na Oslavě – Velké Meziříčí a Náměšť' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Zámky na Oslavě – Velké Meziříčí a Náměšť', 'Pohodový zámecký okruh sleduje údolí řeky Oslavy a spojuje dvě velkolepá šlechtická sídla — renesanční Velké Meziříčí pod obřím dálničním mostem a majestátní Náměšť nad Oslavou na kopci nad barokním mostem se sochami. Jede se po klidných silnicích II. a III. třídy zvlněnou krajinou mezi rybníky, lesy a poli, s příjemně svižnými pasážemi mezi Budišovem a Náměští. Cestou zpět si užijete táhlé zatáčky podél Třebíčska přes Vladislav. Trasa je vhodná i pro méně zkušené jezdce a nejlépe chutná od jara do podzimu. Pozor na zemědělskou techniku na okreskách a na dlážděné úseky v centrech měst.', 'loop', 195, 255, 'medium',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.3556, "lng": 16.0135, "label": "Velké Meziříčí – zámek"}, {"lat": 49.2716, "lng": 16.0010, "label": "Zámek Budišov"}, {"lat": 49.2075, "lng": 16.1594, "label": "Zámek Náměšť nad Oslavou"}, {"lat": 49.2103, "lng": 15.9895, "label": "Vladislav"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.3556,16.0135%7C49.2716,16.0010%7C49.2075,16.1594%7C49.2103,15.9895', 'https://commons.wikimedia.org/wiki/Special:FilePath/Overview_of_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou_castle_in_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/D%C3%A1lni%C4%8Dn%C3%AD_most_Vyso%C4%8Dina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Budi%C5%A1ov%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Overview_of_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou_castle_in_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_kamenn%C3%BD_most.jpg"}'::text[], '{"Zámek Velké Meziříčí","Dálniční most Vysočina","Restaurace: Jelínkova vila (Velké Meziříčí)","Zámek Budišov","Zámek Náměšť nad Oslavou","Barokní kamenný most v Náměšti nad Oslavou"}'::text[], '{"CZ"}'::text[], false, 2110, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Velké Meziříčí', 'Renesanční zámek rodu Podstatzky-Lichtenstein se tyčí na skále přímo nad centrem města, v místě, kde se stéká Oslava s Balinkou. Prohlídkové okruhy vedou zařízenými salony a muzeem, z terasy je pěkný pohled na město sevřené v hlubokém údolí. Motorku pohodlně zaparkujete pod zámkem a centrum projdete pěšky.', 49.3556, 16.0135, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD%2C_z%C3%A1mek.jpg"}'::text[], 0),
    (v_route, 'Dálniční most Vysočina', 'Ikonický ocelový most dálnice D1 překlenuje údolí Oslavy ve výšce přes 75 metrů přímo nad městem a patří k největším mostům v Česku. Pohled zespodu od řeky na obří konstrukci nad střechami Velkého Meziříčí je nezapomenutelný. Skvělé místo na rychlou fotozastávku hned na začátku okruhu.', 49.3520, 16.0037, 'https://commons.wikimedia.org/wiki/Special:FilePath/D%C3%A1lni%C4%8Dn%C3%AD_most_Vyso%C4%8Dina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/D%C3%A1lni%C4%8Dn%C3%AD_most_Vyso%C4%8Dina.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Jelínkova vila (Velké Meziříčí)', 'Stylová restaurace v prvorepublikové vile u řeky Oslavy s vlastním rodinným pivovarem Harrach. Nabízí poctivou českou i moderní kuchyni a čerstvě uvařené nefiltrované pivo, hosté ji dlouhodobě řadí k nejlépe hodnoceným podnikům ve městě. Ideální zastávka na oběd hned v první třetině okruhu.', 49.3546, 16.0089, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg"}'::text[], 2),
    (v_route, 'Zámek Budišov', 'Barokně upravený zámek obklopený anglickým parkem s rybníkem ukrývá unikátní zoologický depozitář Moravského zemského muzea — tisíce vycpanin zvířat z celého světa v historických sálech. Prohlídka je nečekaný zážitek, jaký jinde na Vysočině nenajdete. Klidná zastávka uprostřed tiché vesnické krajiny mezi Meziříčím a Náměští.', 49.2716, 16.0010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Budi%C5%A1ov%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Budi%C5%A1ov%2C_z%C3%A1mek.jpg"}'::text[], 3),
    (v_route, 'Zámek Náměšť nad Oslavou', 'Renesanční zámek Žerotínů na zalesněném kopci nad městem býval letním sídlem prezidenta Beneše a dnes je národní kulturní památkou. Prohlídky nabízejí vzácnou sbírku tapiserií, knihovnu a kapli, z nádvoří se otevírá výhled do údolí Oslavy. Příjezdová alej a serpentina pod zámkem je hezkou tečkou pro motorkáře.', 49.2075, 16.1594, 'https://commons.wikimedia.org/wiki/Special:FilePath/Overview_of_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou_castle_in_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Overview_of_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou_castle_in_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg"}'::text[], 4),
    (v_route, 'Barokní kamenný most v Náměšti nad Oslavou', 'Kamenný most přes Oslavu z roku 1737 zdobí dvacet barokních soch světců — po pražském Karlově mostě jde o nejcennější sochařsky zdobený most v Česku. Stojí přímo pod zámkem v centru města a je ideálním místem na závěrečnou fotku před zpáteční cestou. Přes most se dnes jezdí jen jedním směrem, choďte raději pěšky.', 49.2060, 16.1585, 'https://commons.wikimedia.org/wiki/Special:FilePath/N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_kamenn%C3%BD_most.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_kamenn%C3%BD_most.jpg"}'::text[], 5);

  -- Polná, Brtnice a zřícenina Rokštejn
  delete from public.routes where name = 'Polná, Brtnice a zřícenina Rokštejn' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Polná, Brtnice a zřícenina Rokštejn', 'Kratší okruh kolem Jihlavy propojuje tři méně známé perly Vysočiny — hradozámecký areál v Polné s jednou z nejcennějších synagog v Česku, romantickou zříceninu Rokštejn v údolí řeky Brtnice a renesanční městečko Brtnici, rodiště architekta Josefa Hoffmanna. Silnice třetí třídy se vinou mezi rybníky, remízky a lesíky typické vrchovinné krajiny a nabízejí pohodovou, nenáročnou jízdu. Závěr patří zámku v Třešti a návratu přes lesnaté hřebeny. Ideální půldenní vyjížďka pro každého, nejhezčí od května do října. Pozor na úzkou asfaltku k Rokštejnu a na dlažbu na náměstích.', 'loop', 135, 190, 'easy',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.4879, "lng": 15.7166, "label": "Polná"}, {"lat": 49.3399, "lng": 15.7124, "label": "Zřícenina Rokštejn"}, {"lat": 49.3070, "lng": 15.6763, "label": "Brtnice"}, {"lat": 49.2938, "lng": 15.4803, "label": "Třešť"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.4879,15.7166%7C49.3399,15.7124%7C49.3070,15.6763%7C49.2938,15.4803', 'https://commons.wikimedia.org/wiki/Special:FilePath/Poln%C3%A1%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Poln%C3%A1%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Poln%C3%A1%2C_synagoga.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Rok%C5%A1tejn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brtnice%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/T%C5%99e%C5%A1%C5%A5%2C_z%C3%A1mek.jpg"}'::text[], '{"Hrad a zámek Polná","Synagoga a rabínský dům v Polné","Zřícenina hradu Rokštejn","Zámek Brtnice","Zámek Třešť"}'::text[], '{"CZ"}'::text[], false, 2120, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad a zámek Polná', 'Rozlehlý hradozámecký areál nad Peklem, jak se říká údolí pod hradbami, dnes hostí muzeum s expozicí lékárny, školní třídy a měšťanského bydlení. Gotický hrad přestavěný na zámek dominuje malebnému městečku s obřím Husovým náměstím. Příjemná první zastávka s parkováním přímo u brány areálu.', 49.4879, 15.7166, 'https://commons.wikimedia.org/wiki/Special:FilePath/Poln%C3%A1%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Poln%C3%A1%2C_z%C3%A1mek.jpg"}'::text[], 0),
    (v_route, 'Synagoga a rabínský dům v Polné', 'Barokní synagoga z roku 1684 s rabínským domem patří k nejcennějším židovským památkám v Česku a připomíná i neblaze proslulou hilsneriádu. Expozice Regionálního muzea vypráví o životě židovské komunity na malém městě. Stojí v dochovaném ghettu pár kroků od náměstí, prohlídka zabere půl hodinky.', 49.4869, 15.7146, 'https://commons.wikimedia.org/wiki/Special:FilePath/Poln%C3%A1%2C_synagoga.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Poln%C3%A1%2C_synagoga.jpg"}'::text[], 1),
    (v_route, 'Zřícenina hradu Rokštejn', 'Rozeklaná zřícenina gotického hradu ze 13. století se zvedá na skále přímo nad meandrem říčky Brtnice u Přímělkova. Patří k nejstarším hradům na Moravě a díky dochované hranolové věži je vděčným cílem fotografů. Od silnice je to k hradu jen krátká procházka údolím.', 49.3399, 15.7124, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Rok%C5%A1tejn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_Rok%C5%A1tejn.jpg"}'::text[], 2),
    (v_route, 'Zámek Brtnice', 'Renesanční zámek Collaltů shlíží na městečko s malebným náměstím, barokními mosty se sochami a rodným domem světoznámého architekta Josefa Hoffmanna. Průjezd Brtnicí údolím stejnojmenné říčky patří k nejhezčím pasážím okruhu. Zámek je postupně opravován, kouzlo místa ale funguje i zvenčí.', 49.3070, 15.6763, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brtnice%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brtnice%2C_z%C3%A1mek.jpg"}'::text[], 3),
    (v_route, 'Zámek Třešť', 'Klasicistně upravený zámek s anglickým parkem v městečku proslulém výrobou betlémů — místní betlémářská tradice trvá přes dvě stě let. Dnes zámek slouží jako hotel a konferenční centrum Akademie věd, park je volně přístupný. Poslední zastávka před návratem přes lesy Javořické vrchoviny.', 49.2938, 15.4803, 'https://commons.wikimedia.org/wiki/Special:FilePath/T%C5%99e%C5%A1%C5%A5%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/T%C5%99e%C5%A1%C5%A5%2C_z%C3%A1mek.jpg"}'::text[], 4);

  -- Údolím Želetavky – Police, Jemnice a Uherčice
  delete from public.routes where name = 'Údolím Želetavky – Police, Jemnice a Uherčice' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolím Želetavky – Police, Jemnice a Uherčice', 'Objevitelský okruh nejjižnějším cípem Vysočiny míří do kraje, kam běžný turista skoro nezabloudí — do údolí říčky Želetavky mezi Jemnicí a moravsko-rakouským pomezím. Čekají vás prázdné okresky se svižnými zatáčkami, hrad Sádek nad vinicí, zámek v Polici s leteckým muzeem i monumentální, zvolna ožívající zámek Uherčice. Historická Jemnice s hradbami je ideální na kávu v polovině cesty. Trasa je středně náročná délkou, nikoli technikou, a nejlépe si ji užijete od jara do podzimu. Pozor na zvěř v lesních úsecích a místy hrubší asfalt na třetitřídkách.', 'loop', 195, 260, 'medium',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.1866, "lng": 15.8366, "label": "Hrad Sádek"}, {"lat": 49.0522, "lng": 15.8093, "label": "Moravské Budějovice"}, {"lat": 48.9690, "lng": 15.7091, "label": "Zámek Police"}, {"lat": 48.9153, "lng": 15.6413, "label": "Zámek Uherčice"}, {"lat": 49.0190, "lng": 15.5699, "label": "Jemnice"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.1866,15.8366%7C49.0522,15.8093%7C48.9690,15.7091%7C48.9153,15.6413%7C49.0190,15.5699', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_S%C3%A1dek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_S%C3%A1dek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Moravsk%C3%A9_Bud%C4%9Bjovice%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Police%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Uher%C4%8Dice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jemnice%2C_n%C3%A1m%C4%9Bst%C3%AD_Svobody.jpg"}'::text[], '{"Hrad Sádek","Zámek Moravské Budějovice","Zámek Police a letecké muzeum","Zámek Uherčice","Jemnice – historické město nad Želetavkou"}'::text[], '{"CZ"}'::text[], false, 2130, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Sádek', 'Hrad přestavěný na zámek stojí na výrazném kopci u Kojetic a pod jeho zdmi se rozkládá nejstarší moravská vinice mimo tradiční vinařské oblasti. Místní vinařství nabízí degustace a z vrchu je krásný rozhled po Třebíčsku. Nezvyklé spojení hradu a vína je skvělým zahájením okruhu.', 49.1866, 15.8366, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_S%C3%A1dek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad_S%C3%A1dek.jpg"}'::text[], 0),
    (v_route, 'Zámek Moravské Budějovice', 'Renesanční zámek na náměstí v Moravských Budějovicích ukrývá muzeum s unikátní expozicí starých řemesel — uvidíte dílny bednáře, koláře, provazníka i perníkáře v původním vybavení. Město je přirozenou branou do kraje mezi Vysočinou a Podyjím. Parkování přímo na náměstí, zastávka na kávu se nabízí.', 49.0522, 15.8093, 'https://commons.wikimedia.org/wiki/Special:FilePath/Moravsk%C3%A9_Bud%C4%9Bjovice%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Moravsk%C3%A9_Bud%C4%9Bjovice%2C_z%C3%A1mek.jpg"}'::text[], 1),
    (v_route, 'Zámek Police a letecké muzeum', 'Renesanční zámek v malé vsi nad údolím Želetavky překvapí nečekaným obsahem — sídlí tu letecké muzeum s desítkami strojů včetně stíhaček MiG a vrtulníků, věnované osudům letců z regionu. Kombinace starých zdí a proudových letadel je zážitek, který jinde nezažijete. Otevírací dobu si raději ověřte předem.', 48.9690, 15.7091, 'https://commons.wikimedia.org/wiki/Special:FilePath/Police%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Police%2C_z%C3%A1mek.jpg"}'::text[], 2),
    (v_route, 'Zámek Uherčice', 'Obrovský renesančně-barokní komplex na samé hranici s Rakouskem patřil k nejzanedbanějším památkám země a dnes se po rozsáhlé obnově vrací do života. Prohlídka syrových i obnovených sálů ukazuje, jak se zámek zachraňuje, okolní anglický park zve k procházce. Silnice sem vedou liduprázdnou krajinou bývalé železné opony.', 48.9153, 15.6413, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Uher%C4%8Dice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek_Uher%C4%8Dice.jpg"}'::text[], 3),
    (v_route, 'Jemnice – historické město nad Želetavkou', 'Jedno z nejstarších moravských měst se pyšní zachovalými hradbami, židovskou čtvrtí a tradicí slavnosti Barchan, která se koná už přes šest set let. Náměstí Svobody s podloubím je příjemné místo na oběd či kávu v druhé polovině okruhu. Z hradebního okruhu jsou hezké výhledy do údolí Želetavky.', 49.0190, 15.5699, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jemnice%2C_n%C3%A1m%C4%9Bst%C3%AD_Svobody.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jemnice%2C_n%C3%A1m%C4%9Bst%C3%AD_Svobody.jpg"}'::text[], 4);

  -- Dalešice a Mohelno – přehrady v údolí Jihlavy
  delete from public.routes where name = 'Dalešice a Mohelno – přehrady v údolí Jihlavy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Dalešice a Mohelno – přehrady v údolí Jihlavy', 'Okruh kolem dvojice přehrad v hlubokém kaňonu řeky Jihlavy kombinuje velkou vodu, technické zajímavosti a slavný filmový pivovar. Z Třebíčska se spustíte k obloukovému Stropešínskému mostu, po hrázi nejvyšší sypané přehrady v Česku přejedete nad stometrovou hloubkou a od vyrovnávací nádrže Mohelno dohlédnete až k chladicím věžím Dukovan. Cestou zpět čeká zasloužená zastávka v pivovaru Dalešice, kde se točily Postřižiny. Silnice kolem přehrad jsou samá zatáčka a v sezóně láká i koupání. Pozor na cyklisty na hrázích a o víkendech na hustší provoz u pivovaru.', 'loop', 205, 270, 'medium',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.2160, "lng": 15.8820, "label": "Třebíč – průjezd"}, {"lat": 49.1450, "lng": 16.0760, "label": "Stropešínský most"}, {"lat": 49.1320, "lng": 16.1200, "label": "Hráz Dalešické přehrady"}, {"lat": 49.1093, "lng": 16.1743, "label": "Vodní nádrž Mohelno"}, {"lat": 49.0866, "lng": 16.1465, "label": "Infocentrum JE Dukovany"}, {"lat": 49.1290, "lng": 16.0820, "label": "Pivovar Dalešice"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.2160,15.8820%7C49.1450,16.0760%7C49.1320,16.1200%7C49.1093,16.1743%7C49.0866,16.1465%7C49.1290,16.0820', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C5%A1ick%C3%A1_p%C5%99ehrada.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Strope%C5%A1%C3%ADnsk%C3%BD_most.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C5%A1ick%C3%A1_p%C5%99ehrada.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vodn%C3%AD_n%C3%A1dr%C5%BE_Mohelno.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dukovany_Nuclear_Power_Station.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C5%A1ice%2C_pivovar.jpg"}'::text[], '{"Stropešínský most","Dalešická přehrada – hráz Kramolín","Vodní nádrž Mohelno","Infocentrum JE Dukovany","Restaurace: Pivovar Dalešice (Dalešice)"}'::text[], '{"CZ"}'::text[], false, 2140, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Stropešínský most', 'Elegantní obloukový most překlenuje boční rameno Dalešické přehrady u Stropešína a patří k nejfotogeničtějším stavbám na celé nádrži. Z mostu i z břehů se otevírají výhledy na klikatící se hladinu sevřenou lesnatými stráněmi. Ideální první fotozastávka u velké vody.', 49.1450, 16.0760, 'https://commons.wikimedia.org/wiki/Special:FilePath/Strope%C5%A1%C3%ADnsk%C3%BD_most.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Strope%C5%A1%C3%ADnsk%C3%BD_most.jpg"}'::text[], 0),
    (v_route, 'Dalešická přehrada – hráz Kramolín', 'Sypaná hráz vysoká sto metrů je nejvyšší svého druhu v Česku a zadržuje dvaadvacet kilometrů dlouhé jezero v kaňonu Jihlavy. Přehrada slouží přečerpávací elektrárně spolupracující s Dukovany a z koruny hráze je závratný pohled do hloubky údolí. U hráze funguje vyhlídka i občerstvení, v létě jezdí po jezeře výletní loď.', 49.1320, 16.1200, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C5%A1ick%C3%A1_p%C5%99ehrada.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C5%A1ick%C3%A1_p%C5%99ehrada.jpg"}'::text[], 1),
    (v_route, 'Vodní nádrž Mohelno', 'Vyrovnávací nádrž pod dalešickou hrází se vine hlubokým skalnatým kaňonem a její tyrkysová hladina kontrastuje s divokými stráněmi nad ní. Z vyhlídek na okraji Mohelna je jeden z nejdramatičtějších pohledů na říční krajinu Vysočiny. Krátká odbočka, která rozhodně stojí za to.', 49.1093, 16.1743, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vodn%C3%AD_n%C3%A1dr%C5%BE_Mohelno.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vodn%C3%AD_n%C3%A1dr%C5%BE_Mohelno.jpg"}'::text[], 2),
    (v_route, 'Infocentrum JE Dukovany', 'Bezplatné návštěvnické centrum největší tuzemské jaderné elektrárny vysvětluje na modelech a simulátorech, jak se z atomu vyrábí elektřina. Pohled na čtveřici chladicích věží zblízka je působivý a expozice zabere příjemnou hodinku. Motorkáři tu najdou stín, občerstvení a téma k hovoru na zbytek cesty.', 49.0866, 16.1465, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dukovany_Nuclear_Power_Station.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dukovany_Nuclear_Power_Station.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Pivovar Dalešice (Dalešice)', 'Legendární pivovar, kde Jiří Menzel natáčel Postřižiny, dnes vaří nefiltrovaná piva a v pivovarské hospodě servíruje poctivou českou kuchyni. Hosté chválí tankové pivo, vepřové speciality i atmosféru starých spilek, hodnocení se dlouhodobě drží vysoko. Perfektní pozdní oběd před zpáteční cestou — řidič samozřejmě jen nealko.', 49.1290, 16.0820, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C5%A1ice%2C_pivovar.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C5%A1ice%2C_pivovar.jpg"}'::text[], 4);

  -- Vírská přehrada a horní Svratka
  delete from public.routes where name = 'Vírská přehrada a horní Svratka' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Vírská přehrada a horní Svratka', 'Celodenní výprava do nejhornatějšího kouta Vysočiny sleduje divoké údolí horní Svratky, kterému vévodí štíhlá betonová hráz Vírské přehrady. Kolem vodní nádrže se na skalních ostrozích krčí hned tři romantické zříceniny — Aueršperk, Pyšolec a hrad v Dalečíně přímo u řeky. Silnice se tu kroutí serpentinami po stráních, střídají hluboké lesy a výhledy na hladinu, závěr patří malebnému Jimramovu, rodišti bratří Mrštíků. Nejkrásnější je trasa na přelomu září a října, kdy údolí hraje barvami. Pozor na vlhký asfalt ve stinných úsecích a úzké silničky kolem přehrady.', 'loop', 220, 290, 'medium',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.5545, "lng": 16.2960, "label": "Zřícenina Aueršperk"}, {"lat": 49.5486, "lng": 16.3115, "label": "Zřícenina Pyšolec"}, {"lat": 49.5697, "lng": 16.3226, "label": "Vírská přehrada"}, {"lat": 49.5901, "lng": 16.2542, "label": "Dalečín"}, {"lat": 49.6366, "lng": 16.2258, "label": "Jimramov"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.5545,16.2960%7C49.5486,16.3115%7C49.5697,16.3226%7C49.5901,16.2542%7C49.6366,16.2258', 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADrsk%C3%A1_p%C5%99ehrada.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Auer%C5%A1perk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Py%C5%A1olec.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADrsk%C3%A1_p%C5%99ehrada.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C4%8D%C3%ADn%2C_hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jimramov%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg"}'::text[], '{"Zřícenina hradu Aueršperk","Zřícenina hradu Pyšolec","Vírská přehrada","Zřícenina hradu Dalečín","Jimramov"}'::text[], '{"CZ"}'::text[], false, 2150, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zřícenina hradu Aueršperk', 'Tajemné zbytky hradu ze 13. století se skrývají v lesích nad údolím Bystřice nedaleko Dvořišť. Dochovaly se mohutné valy a torza zdí, které obrostl mech — místo má syrovou atmosféru dávno zaniklé pevnosti. Od silnice sem vede krátká lesní procházka, ideální na protažení nohou.', 49.5545, 16.2960, 'https://commons.wikimedia.org/wiki/Special:FilePath/Auer%C5%A1perk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Auer%C5%A1perk.jpg"}'::text[], 0),
    (v_route, 'Zřícenina hradu Pyšolec', 'Zřícenina na strmém ostrohu vysoko nad zákrutem Svratky, z jejíhož okruží zbylo torzo válcového bergfritu a hradby. Výstup od řeky je strmější, odměnou jsou ale výhledy do zalesněného údolí pod Vírskou přehradou. Jeden z nejromantičtějších hradů Vysočiny, o kterém většina lidí nikdy neslyšela.', 49.5486, 16.3115, 'https://commons.wikimedia.org/wiki/Special:FilePath/Py%C5%A1olec.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Py%C5%A1olec.jpg"}'::text[], 1),
    (v_route, 'Vírská přehrada', 'Betonová tížná hráz z padesátých let se zvedá do výšky přes sedmdesát metrů a zadržuje pitnou vodu pro Brněnsko v deset kilometrů dlouhém jezeře. Pohled z vyhlídky na štíhlou korunu hráze sevřenou lesnatými srázy patří k nejpůsobivějším na Moravě. Kolem přehrady vede krásná vyhlídková silnice do obce Vír.', 49.5697, 16.3226, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADrsk%C3%A1_p%C5%99ehrada.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADrsk%C3%A1_p%C5%99ehrada.jpg"}'::text[], 2),
    (v_route, 'Zřícenina hradu Dalečín', 'Neobvyklá zřícenina stojí přímo v obci na břehu Svratky — z hradu se dochovala výrazná okrouhlá stěna paláce, která se zrcadlí v řece. Podle pověsti hrad dobýval i Jan Žižka. Zastávka je pohodlná, hrad je pár metrů od silnice u mostu.', 49.5901, 16.2542, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C4%8D%C3%ADn%2C_hrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C4%8D%C3%ADn%2C_hrad.jpg"}'::text[], 3),
    (v_route, 'Jimramov', 'Malebný městys na soutoku Svratky a Fryšávky je rodištěm bratří Mrštíků i Jana Karafiáta, autora Broučků. Náměstíčko s barokními domy a zámkem působí, jako by se tu zastavil čas. Příjemné místo na kávu a poslední fotky před zpáteční cestou přes hřebeny Žďárských vrchů.', 49.6366, 16.2258, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jimramov%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jimramov%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg"}'::text[], 4);

  -- Rozhledny Havlíčkobrodska
  delete from public.routes where name = 'Rozhledny Havlíčkobrodska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rozhledny Havlíčkobrodska', 'Vyhlídkový okruh severní Vysočinou spojuje tři rozhledny, ze kterých přehlédnete kraj mezi Sázavou a Doubravou jako na dlani — dřevěnou Bohdanku, ocelovou Vysokou u Havlíčkova Brodu a kamennou Rosičku u Sázavy. Mezi věžemi se jede po zvlněných okreskách s dlouhými výhledy, stoupáními a sjezdy typickými pro Havlíčkobrodsko. Cestou přibude zámek v Přibyslavi a tichá mohyla připomínající místo, kde zemřel Jan Žižka. Trasa je nenáročná na techniku, ale dlouhá na kilometry — počítejte s celým dnem včetně výstupů na věže. Nejlepší viditelnost bývá na jaře a na podzim, pozor na větrné hřebeny.', 'loop', 195, 260, 'medium',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.7770, "lng": 15.2170, "label": "Rozhledna Bohdanka"}, {"lat": 49.5770, "lng": 15.5230, "label": "Rozhledna Vysoká"}, {"lat": 49.5769, "lng": 15.7387, "label": "Přibyslav"}, {"lat": 49.5992, "lng": 15.7169, "label": "Žižkova mohyla"}, {"lat": 49.5288, "lng": 15.8570, "label": "Rozhledna Rosička"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.7770,15.2170%7C49.5770,15.5230%7C49.5769,15.7387%7C49.5992,15.7169%7C49.5288,15.8570', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Bohdanka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Bohdanka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Vysok%C3%A1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/P%C5%99ibyslav%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C5%BEkova_mohyla.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Rosi%C4%8Dka.jpg"}'::text[], '{"Rozhledna Bohdanka","Rozhledna Vysoká","Zámek Přibyslav","Žižkova mohyla","Rozhledna Rosička"}'::text[], '{"CZ"}'::text[], false, 2160, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Rozhledna Bohdanka', 'Dřevěná rozhledna nad obcí Bohdaneč nabízí z ochozu kruhový výhled na Železné hory, údolí Sázavy a za dobré viditelnosti až na Krkonoše. Věž stojí uprostřed lesů stranou hlavních tahů, takže tu často budete úplně sami. Od parkoviště je to na vrchol jen pár minut chůze.', 49.7770, 15.2170, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Bohdanka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Bohdanka.jpg"}'::text[], 0),
    (v_route, 'Rozhledna Vysoká', 'Štíhlá věž na stejnojmenném kopci jihozápadně od Havlíčkova Brodu vyrostla nad lesy v nadmořské výšce přes 600 metrů. Z ochozu dohlédnete na Žďárské vrchy, Železné hory i hluboké lesy nad Sázavou. Krátká odbočka z okresky, která spolehlivě provětrá nohy po sedle.', 49.5770, 15.5230, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Vysok%C3%A1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Vysok%C3%A1.jpg"}'::text[], 1),
    (v_route, 'Zámek Přibyslav', 'Renesanční zámek nad údolím Sázavy hostí kuriózní Centrum hasičského hnutí — největší hasičské muzeum v zemi s historickými stříkačkami a technikou. Městečko s podloubím na náměstí je příjemnou zastávkou na kávu. Kolem zámku vede hezká vyhlídková cesta nad řekou.', 49.5769, 15.7387, 'https://commons.wikimedia.org/wiki/Special:FilePath/P%C5%99ibyslav%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P%C5%99ibyslav%2C_z%C3%A1mek.jpg"}'::text[], 2),
    (v_route, 'Žižkova mohyla', 'Kamenná mohyla u Žižkova Pole označuje místo, kde podle tradice 11. října 1424 zemřel při obléhání Přibyslavi Jan Žižka z Trocnova. Památník z 19. století stojí uprostřed polí s dalekým výhledem a působí tichou, skoro poutní atmosférou. Zastávka na pět minut, na kterou budete vzpomínat.', 49.5992, 15.7169, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C5%BEkova_mohyla.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDi%C5%BEkova_mohyla.jpg"}'::text[], 3),
    (v_route, 'Rozhledna Rosička', 'Kamenno-dřevěná rozhledna na vrchu Rosička u Sázavy stojí v nejvyšším bodě širokého okolí a nabízí jeden z nejhezčích kruhových výhledů na Žďárské vrchy. Za jasného počasí dohlédnete od Javořice až po Devět skal. Důstojná tečka za vyhlídkovým okruhem před návratem na základnu.', 49.5288, 15.8570, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Rosi%C4%8Dka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Rosi%C4%8Dka.jpg"}'::text[], 4);

  -- Rozhledny Třebíčska – Mařenka a Babylon
  delete from public.routes where name = 'Rozhledny Třebíčska – Mařenka a Babylon' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rozhledny Třebíčska – Mařenka a Babylon', 'Vyhlídkový okruh jižní Vysočinou spojuje nejvyšší bod Třebíčska s nejstarší rozhlednou na Moravě. Z rozhledny Mařenka u Štěměch přehlédnete půl kraje, u Třebíče vystoupáte na Pekelný kopec s moderní věží inspirovanou židovskou hvězdou a závěr obstará klasicistní Babylon u Kramolína, odkud se rozhlíželi zeměměřiči už v 19. století. Mezi věžemi se jede po prázdných okreskách se svižným rytmem zatáček, cestou přibude větrný mlýn v Třebíči a zámek ve Valči. Trasa je středně dlouhá a technicky nenáročná, nejlépe si ji vychutnáte za jasného dne s dobrou viditelností. Pozor na lesní úseky s možným štěrkem u krajnic.', 'loop', 190, 250, 'medium',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.1919, "lng": 15.7391, "label": "Rozhledna Mařenka"}, {"lat": 49.2202, "lng": 15.8688, "label": "Třebíč – větrný mlýn"}, {"lat": 49.1950, "lng": 15.8700, "label": "Pekelný kopec"}, {"lat": 49.1707, "lng": 16.0316, "label": "Zámek Valeč"}, {"lat": 49.1112, "lng": 16.1700, "label": "Rozhledna Babylon"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.1919,15.7391%7C49.2202,15.8688%7C49.1950,15.8700%7C49.1707,16.0316%7C49.1112,16.1700', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Ma%C5%99enka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Ma%C5%99enka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/T%C5%99eb%C3%AD%C4%8D%2C_v%C4%9Btrn%C3%BD_ml%C3%BDn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Pekeln%C3%BD_kopec.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vale%C4%8D%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Babylon.jpg"}'::text[], '{"Rozhledna Mařenka","Větrný mlýn v Třebíči","Rozhledna Pekelný kopec","Zámek Valeč","Rozhledna Babylon"}'::text[], '{"CZ"}'::text[], false, 2170, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Rozhledna Mařenka', 'Rozhledna na vrchu Mařenka u Štěměch stojí na nejvyšším bodě celého Třebíčska ve výšce 711 metrů. Z ochozu se otevírá kruhový výhled od Javořice přes Třebíč až k rakouským Alpám, které za ideálních podmínek vykreslí obzor. K věži vede krátká lesní procházka od parkoviště.', 49.1919, 15.7391, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Ma%C5%99enka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Ma%C5%99enka.jpg"}'::text[], 0),
    (v_route, 'Větrný mlýn v Třebíči', 'Zděný větrný mlýn holandského typu na kopci nad třebíčskou čtvrtí Zámostí je poslední svého druhu ve městě — kdysi nemlel mouku, ale tříslo pro koželuhy. Od mlýna je pěkný výhled na střechy Třebíče. Rychlá a fotogenická zastávka stranou turistického ruchu.', 49.2202, 15.8688, 'https://commons.wikimedia.org/wiki/Special:FilePath/T%C5%99eb%C3%AD%C4%8D%2C_v%C4%9Btrn%C3%BD_ml%C3%BDn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/T%C5%99eb%C3%AD%C4%8D%2C_v%C4%9Btrn%C3%BD_ml%C3%BDn.jpg"}'::text[], 1),
    (v_route, 'Rozhledna Pekelný kopec', 'Moderní rozhledna jižně od Třebíče má půdorys šesticípé hvězdy a odkazuje tak na židovské památky města zapsané v UNESCO. Dřevěná konstrukce s ocelovým jádrem měří přes 26 metrů a nabízí výhled na Třebíč, Dukovany i Mařenku. Od parkoviště u silnice vede na vrchol pohodlná cesta lesem.', 49.1950, 15.8700, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Pekeln%C3%BD_kopec.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Pekeln%C3%BD_kopec.jpg"}'::text[], 2),
    (v_route, 'Zámek Valeč', 'Barokně upravený zámek ve Valči u Hrotovic prošel velkorysou obnovou a dnes funguje jako zámecký resort s restaurací a muzeem veteránů. Nádvoří a park jsou přístupné, sbírka historických aut potěší každého, kdo má rád stroje. Pohodlná zastávka na kávu v poslední třetině okruhu.', 49.1707, 16.0316, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vale%C4%8D%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vale%C4%8D%2C_z%C3%A1mek.jpg"}'::text[], 3),
    (v_route, 'Rozhledna Babylon', 'Klasicistní kamenná věž z roku 1831 u Kramolína je považována za nejstarší rozhlednu na Moravě — původně sloužila zeměměřičům při triangulaci monarchie. Z ochozu je výhled na Dalešickou přehradu, chladicí věže Dukovan i hluboké lesy nad Jihlavou. Důstojné zakončení vyhlídkového okruhu.', 49.1112, 16.1700, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Babylon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna_Babylon.jpg"}'::text[], 4);

  -- Mohelenská hadcová step a údolí Oslavy
  delete from public.routes where name = 'Mohelenská hadcová step a údolí Oslavy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mohelenská hadcová step a údolí Oslavy', 'Přírodní okruh na jihovýchodě Vysočiny vede krajinou hlubokých říčních kaňonů, které tu vyhlodaly Oslava s Jihlavou. Vrcholem je Mohelenská hadcová step — národní rezervace nad obří smyčkou řeky, kde na hadcovém podloží přežívá stepní fauna a flóra jako nikde jinde ve střední Evropě. Cestou navštívíte památník Bible kralické, divoké údolí Oslavy a Chvojnice se zříceninou Levnov i tajemný templářský Templštejn nad Jihlavou. Mezi zastávkami si užijete prázdné okresky se svižnými zatáčkami a minimem provozu. Ke zříceninám se chodí kus pěšky po lesních stezkách, počítejte s pevnou obuví; nejkrásněji je tu na jaře a začátkem léta.', 'loop', 215, 285, 'medium',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.1985, "lng": 16.2015, "label": "Kralice nad Oslavou"}, {"lat": 49.1650, "lng": 16.2350, "label": "Údolí Oslavy a Chvojnice"}, {"lat": 49.1585, "lng": 16.2646, "label": "Zřícenina Levnov"}, {"lat": 49.0946, "lng": 16.2477, "label": "Zřícenina Templštejn"}, {"lat": 49.1067, "lng": 16.1878, "label": "Mohelenská hadcová step"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.1985,16.2015%7C49.1650,16.2350%7C49.1585,16.2646%7C49.0946,16.2477%7C49.1067,16.1878', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mohelensk%C3%A1_hadcov%C3%A1_step.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kralice_nad_Oslavou%2C_pam%C3%A1tn%C3%ADk_Bible_kralick%C3%A9.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Adol%C3%AD_Oslavy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Levnov.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Templ%C5%A1tejn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mohelensk%C3%A1_hadcov%C3%A1_step.jpg"}'::text[], '{"Památník Bible kralické","Údolí Oslavy a Chvojnice","Zřícenina Levnov (Ketkovický hrad)","Zřícenina Templštejn","Mohelenská hadcová step"}'::text[], '{"CZ"}'::text[], false, 2180, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Památník Bible kralické', 'Muzeum v Kralicích nad Oslavou připomíná místo, kde bratrská tiskárna na konci 16. století vytiskla slavnou Bibli kralickou — základní kámen spisovné češtiny. Expozice ukazuje dobové tisky i archeologické nálezy z tvrze, kde se tajně tisklo. Krátká, ale silná kulturní zastávka na začátku okruhu.', 49.1985, 16.2015, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kralice_nad_Oslavou%2C_pam%C3%A1tn%C3%ADk_Bible_kralick%C3%A9.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kralice_nad_Oslavou%2C_pam%C3%A1tn%C3%ADk_Bible_kralick%C3%A9.jpg"}'::text[], 0),
    (v_route, 'Údolí Oslavy a Chvojnice', 'Rozlehlá přírodní rezervace chrání divoké, hluboko zaříznuté kaňony obou řek s prudkými skalnatými stráněmi, suťovými lesy a vzácnými druhy rostlin. Od Senorad se dá sejít k soutoku a projít se po hraně údolí s výhledy do zeleného moře korun. Jedno z posledních skutečně divokých říčních údolí na Moravě.', 49.1650, 16.2350, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Adol%C3%AD_Oslavy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Adol%C3%AD_Oslavy.jpg"}'::text[], 1),
    (v_route, 'Zřícenina Levnov (Ketkovický hrad)', 'Zřícenina zvaná také Ketkovický hrad korunuje strmý ostroh vysoko nad soutokem Oslavy a Chvojnice. Z hradu zbyly části paláce a hradeb, hlavním lákadlem je ale závratný výhled do kaňonu, který patří k nejhezčím na Vysočině. Od Ketkovic vede k hradu pohodová lesní stezka.', 49.1585, 16.2646, 'https://commons.wikimedia.org/wiki/Special:FilePath/Levnov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Levnov.jpg"}'::text[], 2),
    (v_route, 'Zřícenina Templštejn', 'Rozsáhlá zřícenina hradu templářů z konce 13. století se skrývá v lesích nad kaňonem Jihlavy u Jamolic. Dochované zdi z netradičně kladeného kamene a tajemná pověst řádu dodávají místu zvláštní atmosféru. Krátká procházka po červené značce od lesního parkoviště.', 49.0946, 16.2477, 'https://commons.wikimedia.org/wiki/Special:FilePath/Templ%C5%A1tejn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Templ%C5%A1tejn.jpg"}'::text[], 3),
    (v_route, 'Mohelenská hadcová step', 'Národní přírodní rezervace na hadcovém podloží nad obří smyčkou řeky Jihlavy je domovem stepní vegetace, kudlanek a desítek druhů, které jinde v Česku nenajdete. Z vyhlídky na hraně stepi se otevírá jeden z nejslavnějších pohledů Moravy — meandr řeky sevřený skalami sto metrů pod vámi. Nezapomenutelný vrchol celé trasy.', 49.1067, 16.1878, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mohelensk%C3%A1_hadcov%C3%A1_step.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mohelensk%C3%A1_hadcov%C3%A1_step.jpg"}'::text[], 4);

  -- Údolí Doubravy a Stvořidla
  delete from public.routes where name = 'Údolí Doubravy a Stvořidla' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí Doubravy a Stvořidla', 'Přírodní okruh severní Vysočinou spojuje dva nejdivočejší říční úseky kraje — skalnatý kaňon Doubravy u Chotěboře a peřeje Stvořidla na Sázavě, kde řeka duní mezi balvany jako na horách. Mezi nimi se jede po klidných okreskách zvlněnou krajinou polí a lesů, s příjemnou zastávkou u zámku v Chotěboři a u prastarého tisu ve Vilémovicích, kterému botanici hádají až dva tisíce let. Závěrečná smyčka obchází horu Melechov, bájný střed Evropy. K oběma údolím se od silnice chodí kus pěšky, hezčí zážitek si odnesete v pevných botách. Trasa je krátká a pohodová, ideální na půlden s dlouhými zastávkami v přírodě.', 'loop', 155, 210, 'easy',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.6880, "lng": 15.6950, "label": "Bílek – Údolí Doubravy"}, {"lat": 49.7200, "lng": 15.6740, "label": "Chotěboř"}, {"lat": 49.7107, "lng": 15.3454, "label": "Vilémovice"}, {"lat": 49.6650, "lng": 15.3500, "label": "Stvořidla"}, {"lat": 49.6486, "lng": 15.3103, "label": "Melechov"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.6880,15.6950%7C49.7200,15.6740%7C49.7107,15.3454%7C49.6650,15.3500%7C49.6486,15.3103', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Adol%C3%AD_Doubravy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Adol%C3%AD_Doubravy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vil%C3%A9movick%C3%BD_tis.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stvo%C5%99idla.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Melechov.jpg"}'::text[], '{"Údolí Doubravy","Zámek Chotěboř","Restaurace: Panský dům (Chotěboř)","Vilémovický tis","Stvořidla","Melechov"}'::text[], '{"CZ"}'::text[], false, 2190, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Údolí Doubravy', 'Přírodní rezervace u Bílku chrání divoký kaňon říčky Doubravy s vodopádem, skalními útvary a vyhlídkou Čertův stolek. Okruh soutěskou Koryto patří k nejkrásnějším krátkým túrám na Vysočině — počítejte s hodinkou chůze. Motorku necháte na parkovišti u silnice v Bílku.', 49.6880, 15.6950, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Adol%C3%AD_Doubravy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%9Adol%C3%AD_Doubravy.jpg"}'::text[], 0),
    (v_route, 'Zámek Chotěboř', 'Barokní zámek rodu Dobrzenských s kaplí a parkem stojí na okraji města nad údolím Doubravy a hostí městské muzeum. Interiéry s rodovými sbírkami se prohlížejí s průvodcem, park je volně přístupný. Klidná kulturní zastávka po túře divokým údolím.', 49.7200, 15.6740, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_z%C3%A1mek.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Panský dům (Chotěboř)', 'Tradiční hotel s restaurací přímo na chotěbořském náměstí vaří poctivou českou kuchyni a polední menu, na čepu bývá pivo z místního pivovaru Chotěboř. Hosté oceňují rychlou obsluhu a férové ceny. Praktická zastávka na oběd zhruba v třetině okruhu.', 49.7207, 15.6702, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_n%C3%A1m%C4%9Bst%C3%AD.jpg"}'::text[], 2),
    (v_route, 'Vilémovický tis', 'Památný tis červený na návsi ve Vilémovicích patří k nejstarším stromům v Česku — odhady jeho věku sahají od patnácti set do dvou tisíc let. Mohutný strom s obvodem přes tři metry přežil generace a stále plodí. Kuriózní pětiminutová zastávka, kterou si nenechte ujít.', 49.7107, 15.3454, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vil%C3%A9movick%C3%BD_tis.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vil%C3%A9movick%C3%BD_tis.jpg"}'::text[], 3),
    (v_route, 'Stvořidla', 'Legendární peřejnatý úsek Sázavy mezi Světlou a Ledčí, kde řeka hučí přes žulové balvany sevřená strmými lesnatými stráněmi. Přírodní rezervace je rájem vodáků při jarní vodě a Jaroslav Foglar sem zasadil tábor Hochů od Bobří řeky. Od parkoviště u trati vede k řece krátká stezka.', 49.6650, 15.3500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stvo%C5%99idla.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stvo%C5%99idla.jpg"}'::text[], 4),
    (v_route, 'Melechov', 'Zalesněná hora nad Ledčí nad Sázavou bývá označována za pomyslný střed Evropy a její žulové vrcholové partie ukrývají skalní útvary i bývalou vojenskou pozorovatelnu. Silnice po úbočí nabízejí pěkné výhledy na kraj kolem Sázavy. Poslední zastávka před návratem do Mezné.', 49.6486, 15.3103, 'https://commons.wikimedia.org/wiki/Special:FilePath/Melechov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Melechov.jpg"}'::text[], 5);

  -- Za muzei a podzemím Jihlavska
  delete from public.routes where name = 'Za muzei a podzemím Jihlavska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Za muzei a podzemím Jihlavska', 'Muzejní okruh středem Vysočiny je ideální volbou pro dny, kdy chcete střídat jízdu s poznáváním. Začíná v hornické Jihlavě, kde sestoupíte do druhého největšího podzemního labyrintu v Česku, projdete expozice Muzea Vysočiny na náměstí a vyfotíte si hradební bránu Matky Boží. Pak trasa uhne na sever k technické památce Šlakhamr, vodnímu hamru u Sázavy, a přes Havlíčkův Brod s rodným domem Karla Havlíčka Borovského dorazí na středověký selský statek v Pohledi. Jede se po pohodových silnicích druhé a třetí třídy bez technických záludností. Počítejte s celým dnem — samotné prohlídky zaberou víc času než jízda; v pondělí bývá většina expozic zavřená.', 'loop', 160, 215, 'easy',
     '[{"lat": 49.3464, "lng": 15.2119, "label": "Start: Mezná u Pelhřimova"}, {"lat": 49.3956, "lng": 15.5907, "label": "Jihlava"}, {"lat": 49.5570, "lng": 15.8890, "label": "Šlakhamr"}, {"lat": 49.6079, "lng": 15.5806, "label": "Havlíčkův Brod"}, {"lat": 49.6550, "lng": 15.4570, "label": "Pohleď"}, {"lat": 49.3464, "lng": 15.2119, "label": "Cíl: Mezná u Pelhřimova"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3464,15.2119&destination=49.3464,15.2119&travelmode=driving&waypoints=49.3956,15.5907%7C49.5570,15.8890%7C49.6079,15.5806%7C49.6550,15.4570', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_br%C3%A1na_Matky_Bo%C5%BE%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jihlavsk%C3%A9_podzem%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_Masarykovo_n%C3%A1m%C4%9Bst%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_br%C3%A1na_Matky_Bo%C5%BE%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_radnice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0lakhamr.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Havl%C3%AD%C4%8Dk%C5%AFv_Brod%2C_Havl%C3%AD%C4%8Dk%C5%AFv_d%C5%AFm.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pohle%C4%8F%2C_Michal%C5%AFv_statek.jpg"}'::text[], '{"Jihlavské podzemí","Muzeum Vysočiny Jihlava","Brána Matky Boží","Restaurace: Radniční restaurace (Jihlava)","Šlakhamr","Havlíčkův dům (Havlíčkův Brod)","Michalův statek v Pohledi"}'::text[], '{"CZ"}'::text[], false, 2200, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Jihlavské podzemí', 'Labyrint chodeb vytesaných ve skále pod historickým centrem Jihlavy měří přes dvacet kilometrů a je po Znojmu druhým největším podzemím v Česku. Prohlídka vede i tajemnou svítící chodbou, jejíž fosforeskující stěny dodnes vzbuzují otázky. V podzemí je stálých deset stupňů, vezměte si něco teplého.', 49.3961, 15.5906, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jihlavsk%C3%A9_podzem%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jihlavsk%C3%A9_podzem%C3%AD.jpg"}'::text[], 0),
    (v_route, 'Muzeum Vysočiny Jihlava', 'Hlavní muzeum kraje sídlí v renesančních domech přímo na Masarykově náměstí a vypráví příběh stříbrné horečky, která ve 13. století udělala z Jihlavy jedno z nejbohatších měst království. Expozice přibližují hornictví, přírodu i řemesla Vysočiny. Ideální start pro pochopení kraje, kterým celý den jezdíte.', 49.3956, 15.5907, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_Masarykovo_n%C3%A1m%C4%9Bst%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_Masarykovo_n%C3%A1m%C4%9Bst%C3%AD.jpg"}'::text[], 1),
    (v_route, 'Brána Matky Boží', 'Poslední dochovaná brána jihlavského městského opevnění s vyhlídkovým ochozem je symbolem města. Z věže vysoké přes dvacet metrů přehlédnete červené střechy historického jádra i okolní vrchovinu. Výstup spojte s procházkou po přilehlých hradbách a parkánech.', 49.3946, 15.5876, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_br%C3%A1na_Matky_Bo%C5%BE%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_br%C3%A1na_Matky_Bo%C5%BE%C3%AD.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Radniční restaurace (Jihlava)', 'Restaurace s vlastním minipivovarem v historických prostorách radničního domu na Masarykově náměstí patří k jihlavské klasice. Vaří poctivou českou kuchyni k čepovanému radničnímu pivu a hosté dlouhodobě chválí kuchyni i klenuté sály. Pohodlný oběd, než vyrazíte z Jihlavy na sever.', 49.3963, 15.5910, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_radnice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jihlava%2C_radnice.jpg"}'::text[], 3),
    (v_route, 'Šlakhamr', 'Středověký vodní hamr na řece Sázavě v Hamrech u Žďáru dodnes předvádí, jak obří kladiva poháněná vodním kolem kovala železo. Technické muzeum v Brně tu o víkendech pořádá ukázky kování, které stojí za načasování zastávky. Krásná技 památka v zeleném údolí přímo u silnice.', 49.5570, 15.8890, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0lakhamr.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0lakhamr.jpg"}'::text[], 4),
    (v_route, 'Havlíčkův dům (Havlíčkův Brod)', 'Renesanční dům na náměstí, kde žil novinář a buřič Karel Havlíček Borovský, dnes patří Muzeu Vysočiny a vypráví jeho příběh od Borové po vyhnanství v Brixenu. Expozice je moderní a vtipná, přesně v duchu Havlíčkových epigramů. Náměstí kolem nabízí kavárny na rychlé doplnění kofeinu.', 49.6079, 15.5806, 'https://commons.wikimedia.org/wiki/Special:FilePath/Havl%C3%AD%C4%8Dk%C5%AFv_Brod%2C_Havl%C3%AD%C4%8Dk%C5%AFv_d%C5%AFm.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Havl%C3%AD%C4%8Dk%C5%AFv_Brod%2C_Havl%C3%AD%C4%8Dk%C5%AFv_d%C5%AFm.jpg"}'::text[], 5),
    (v_route, 'Michalův statek v Pohledi', 'Živý skanzen v malé vsi u Světlé nad Sázavou ukazuje selské hospodářství, jak vypadalo před staletími — roubenky, černou kuchyni, dobytek i políčka obdělávaná historickými postupy. Expozice Muzea Vysočiny přenese návštěvníka do života poddaného sedláka za časů roboty. Nečekaně silná tečka za muzejním okruhem.', 49.6550, 15.4570, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pohle%C4%8F%2C_Michal%C5%AFv_statek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pohle%C4%8F%2C_Michal%C5%AFv_statek.jpg"}'::text[], 6);

end $$;
