-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — Itálie II: Apeniny, jih a ostrovy (IT)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Apeniny – Passo della Futa a Raticosa
  delete from public.routes where name = 'Apeniny – Passo della Futa a Raticosa' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Apeniny – Passo della Futa a Raticosa', 'Nedělní svatyně italských motorkářů: legendární průsmyky Futa a Raticosa na staré silnici SS65 mezi Florencií a Bolognou. Čeká tě nekonečný sled plynulých zatáček s výborným asfaltem, výhledy na zelené hřebeny Apenin a zastávka u okruhu Mugello, kde jezdí MotoGP. Okruh doplňuje klikatý průsmyk Giogo a kamenné městečko Firenzuola. Nejlépe od dubna do října; o víkendech počítej s hustým provozem motorek a občasným měřením rychlosti. Na Raticose nevynechej kultovní motorkářský Chalet.', 'loop', 115, 210, 'medium',
     '[{"lat": 43.9954, "lng": 11.3541, "label": "Start: Scarperia"}, {"lat": 43.9975, "lng": 11.3719, "label": "Autodromo del Mugello"}, {"lat": 44.0480, "lng": 11.3540, "label": "Passo del Giogo"}, {"lat": 44.1190, "lng": 11.3810, "label": "Firenzuola"}, {"lat": 44.1611, "lng": 11.3536, "label": "Passo della Raticosa"}, {"lat": 44.0940, "lng": 11.2860, "label": "Passo della Futa"}, {"lat": 43.9800, "lng": 11.2670, "label": "Lago di Bilancino"}, {"lat": 43.9954, "lng": 11.3541, "label": "Cíl: Scarperia"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.9954,11.3541&destination=43.9954,11.3541&travelmode=driving&waypoints=43.9975,11.3719%7C44.0480,11.3540%7C44.1190,11.3810%7C44.1611,11.3536%7C44.0940,11.2860%7C43.9800,11.2670', 'https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20della%20Futa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palazzo%20dei%20Vicari%2C%20Scarperia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Autodromo%20del%20Mugello.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20della%20Raticosa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20della%20Futa.jpg"}'::text[], '{"Scarperia – Palazzo dei Vicari","Autodromo del Mugello","Passo della Raticosa","Passo della Futa"}'::text[], '{"IT"}'::text[], false, 4410, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Scarperia – Palazzo dei Vicari', 'Renesanční městečko proslulé výrobou nožů a hradem Palazzo dei Vicari s erby na fasádě. Ideální start okruhu — káva na náměstí a pár kroků od historického centra k okruhu Mugello.', 43.9954, 11.3541, 'https://commons.wikimedia.org/wiki/Special:FilePath/Palazzo%20dei%20Vicari%2C%20Scarperia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palazzo%20dei%20Vicari%2C%20Scarperia.jpg"}'::text[], 0),
    (v_route, 'Autodromo del Mugello', 'Jeden z nejkrásnějších okruhů světa, dějiště MotoGP Itálie. Z okolních kopců je výhled na trať a v areálu bývají volné jízdy — stojí za to zkontrolovat kalendář předem.', 43.9975, 11.3719, 'https://commons.wikimedia.org/wiki/Special:FilePath/Autodromo%20del%20Mugello.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Autodromo%20del%20Mugello.jpg"}'::text[], 1),
    (v_route, 'Passo del Giogo', 'Méně známý, o to prázdnější průsmyk (882 m) se sevřenými serpentinami v lese. Technická rozcvička před Futou — pozor na listí a vlhký povrch ve stínu.', 44.0480, 11.3540, 'https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20del%20Giogo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20del%20Giogo.jpg"}'::text[], 2),
    (v_route, 'Firenzuola', 'Kamenné městečko z šedého pískovce "pietra serena", po válce znovu vystavěné. Dobrá zastávka na doplnění paliva a vody uprostřed apeninských hřebenů.', 44.1190, 11.3810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Firenzuola.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Firenzuola.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Chalet Raticosa (Passo della Raticosa)', 'Kultovní motorkářský srub přímo na vrcholu průsmyku Raticosa (968 m). O víkendu stovky motorek, výborné panini, domácí koláče a benzínkové historky — povinná zastávka každého, kdo jede SS65.', 44.1611, 11.3536, 'https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20della%20Raticosa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20della%20Raticosa.jpg"}'::text[], 4),
    (v_route, 'Passo della Futa', 'Hlavní vrchol trasy (903 m) s výhledy na hřebeny Apenin a největším německým vojenským hřbitovem v Itálii. Plynulé, rychlé zatáčky s kvalitním asfaltem — ráj pro čistou stopu.', 44.0940, 11.2860, 'https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20della%20Futa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Passo%20della%20Futa.jpg"}'::text[], 5),
    (v_route, 'Lago di Bilancino', 'Přehradní jezero s plážemi na dohled od dálnice — příjemné zklidnění na závěr okruhu. V létě možnost koupání a občerstvení u vody.', 43.9800, 11.2670, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lago%20di%20Bilancino.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lago%20di%20Bilancino.jpg"}'::text[], 6);

  -- Umbrie – Assisi, Spoleto a vodopády Marmore
  delete from public.routes where name = 'Umbrie – Assisi, Spoleto a vodopády Marmore' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Umbrie – Assisi, Spoleto a vodopády Marmore', 'Zelené srdce Itálie bez davů Toskánska: poutní Assisi s bazilikou sv. Františka, růžové Spello, vinařské Montefalco a Spoleto s monumentálním akvaduktem. Velkolepé finále obstarají vodopády Marmore — nejvyšší umělé vodopády Evropy, které Římané postavili už před dvěma tisíci lety. Silnice se vlní mezi olivovými háji a vinicemi, provoz je mírný a asfalt slušný. Ideální od jara do podzimu; u Marmore si ohlídej časy pouštění vody. V létě počítej v Assisi s poutníky a placeným parkováním.', 'loop', 205, 300, 'easy',
     '[{"lat": 43.1107, "lng": 12.3908, "label": "Start: Perugia"}, {"lat": 43.0748, "lng": 12.6054, "label": "Assisi"}, {"lat": 42.9910, "lng": 12.6710, "label": "Spello"}, {"lat": 42.8930, "lng": 12.6540, "label": "Montefalco"}, {"lat": 42.7400, "lng": 12.7370, "label": "Spoleto"}, {"lat": 42.5510, "lng": 12.7150, "label": "Cascata delle Marmore"}, {"lat": 43.1107, "lng": 12.3908, "label": "Cíl: Perugia"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.1107,12.3908&destination=43.1107,12.3908&travelmode=driving&waypoints=43.0748,12.6054%7C42.9910,12.6710%7C42.8930,12.6540%7C42.7400,12.7370%7C42.5510,12.7150', 'https://commons.wikimedia.org/wiki/Special:FilePath/Assisi%20San%20Francesco%20BW%202.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fontana%20Maggiore.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Assisi%20San%20Francesco%20BW%202.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Spoleto%20Ponte%20delle%20Torri.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cascata%20delle%20Marmore.jpg"}'::text[], '{"Perugia – Fontana Maggiore","Assisi – bazilika sv. Františka","Spoleto – Ponte delle Torri","Cascata delle Marmore"}'::text[], '{"IT"}'::text[], false, 4420, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Perugia – Fontana Maggiore', 'Hlavní město Umbrie s gotickou kašnou Fontana Maggiore a promenádou Corso Vannucci. Ranní espresso na Piazza IV Novembre je perfektní start dne.', 43.1107, 12.3908, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fontana%20Maggiore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fontana%20Maggiore.jpg"}'::text[], 0),
    (v_route, 'Assisi – bazilika sv. Františka', 'Poutní město UNESCO na svahu hory Subasio. Dvoupatrová bazilika s Giottovými freskami patří k nejvýznamnějším stavbám Itálie; parkuj pod hradbami a nahoru dojdi pěšky.', 43.0748, 12.6054, 'https://commons.wikimedia.org/wiki/Special:FilePath/Assisi%20San%20Francesco%20BW%202.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Assisi%20San%20Francesco%20BW%202.JPG"}'::text[], 1),
    (v_route, 'Spello', 'Růžové kamenné uličky plné květináčů, římské brány a výhledy do údolí. Krátká procházka od Porta Consolare nahoru městem stojí za každý krok.', 42.9910, 12.6710, 'https://commons.wikimedia.org/wiki/Special:FilePath/Spello.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Spello.jpg"}'::text[], 2),
    (v_route, 'Montefalco', 'Vinařské městečko přezdívané "balkon Umbrie" — domov mohutného červeného Sagrantina. Z hradeb dohlédneš přes celé údolí od Perugie po Spoleto.', 42.8930, 12.6540, 'https://commons.wikimedia.org/wiki/Special:FilePath/Montefalco.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Montefalco.jpg"}'::text[], 3),
    (v_route, 'Spoleto – Ponte delle Torri', 'Středověký akvadukt vysoký 80 metrů, klenoucí se přes rokli pod pevností Rocca Albornoziana. Jedna z nejfotogeničtějších staveb Umbrie.', 42.7400, 12.7370, 'https://commons.wikimedia.org/wiki/Special:FilePath/Spoleto%20Ponte%20delle%20Torri.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Spoleto%20Ponte%20delle%20Torri.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Il Tempio del Gusto (Spoleto)', 'Vyhlášená rodinná restaurace v historickém centru Spoleta — umbrijské lanýže, čerstvá pasta strangozzi a skvělý místní vinný lístek. V sezóně rezervuj předem.', 42.7400, 12.7390, 'https://commons.wikimedia.org/wiki/Special:FilePath/Spoleto.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Spoleto.jpg"}'::text[], 5),
    (v_route, 'Cascata delle Marmore', 'Umělé vodopády z dob starého Říma, celkem 165 metrů ve třech kaskádách. Voda se pouští podle harmonogramu elektrárny — zkontroluj časy, plný průtok je ohromující zážitek.', 42.5510, 12.7150, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cascata%20delle%20Marmore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cascata%20delle%20Marmore.jpg"}'::text[], 6);

  -- Marche – Riviera del Conero a Loreto
  delete from public.routes where name = 'Marche – Riviera del Conero a Loreto' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Marche – Riviera del Conero a Loreto', 'Bílé vápencové útesy hory Conero padající do tyrkysového Jadranu — nejkrásnější kus pobřeží mezi Terstem a Gargánem. Pobřežní silnice provoněná borovicemi spojuje zátoku Portonovo s výletními městečky Sirolo a Numana, pak se stočíš do vnitrozemí k poutnímu Loretu a básníkovu Recanati. Krátká, pohodová trasa s lehkými zatáčkami a spoustou vyhlídek, ideální i na půlden. Nejhezčí je mimo červencové a srpnové špičky, kdy pobřeží houstne. Pozor na cyklisty a víkendový provoz u pláží.', 'loop', 110, 180, 'easy',
     '[{"lat": 43.6169, "lng": 13.5189, "label": "Start: Ancona"}, {"lat": 43.5640, "lng": 13.5900, "label": "Portonovo"}, {"lat": 43.5230, "lng": 13.6210, "label": "Sirolo"}, {"lat": 43.5130, "lng": 13.6220, "label": "Numana"}, {"lat": 43.4400, "lng": 13.6100, "label": "Loreto"}, {"lat": 43.4030, "lng": 13.5490, "label": "Recanati"}, {"lat": 43.6169, "lng": 13.5189, "label": "Cíl: Ancona"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.6169,13.5189&destination=43.6169,13.5189&travelmode=driving&waypoints=43.5640,13.5900%7C43.5230,13.6210%7C43.5130,13.6220%7C43.4400,13.6100%7C43.4030,13.5490', 'https://commons.wikimedia.org/wiki/Special:FilePath/Spiaggia%20delle%20Due%20Sorelle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Ancona.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Portonovo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Spiaggia%20delle%20Due%20Sorelle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Basilica%20di%20Loreto.jpg"}'::text[], '{"Ancona – katedrála San Ciriaco","Portonovo","Sirolo a pláž Due Sorelle","Loreto – Basilica della Santa Casa"}'::text[], '{"IT"}'::text[], false, 4430, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Ancona – katedrála San Ciriaco', 'Románská katedrála na kopci nad přístavem s výhledem na celý záliv. Od Římanů po Traianův oblouk — Ancona je starší, než vypadá z dálnice.', 43.6169, 13.5189, 'https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Ancona.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Ancona.jpg"}'::text[], 0),
    (v_route, 'Portonovo', 'Divoká zátoka pod útesy Conera s oblázkovou pláží, pevnůstkou a románským kostelíkem u vody. Sjezd dolů je úzký a strmý — v sezóně jezdí kyvadlová doprava.', 43.5640, 13.5900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Portonovo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Portonovo.jpg"}'::text[], 1),
    (v_route, 'Sirolo a pláž Due Sorelle', 'Bílé městečko na útesu s náměstíčkem-balkonem nad mořem. Pod ním ikonická pláž Due Sorelle se dvěma vápencovými věžemi — dostupná jen lodí nebo pěšky.', 43.5230, 13.6210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sirolo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sirolo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Spiaggia%20delle%20Due%20Sorelle.jpg"}'::text[], 2),
    (v_route, 'Restaurace: La Torre (Numana)', 'Restaurace s terasou nad přístavem v Numaně — čerstvé jadranské ryby, moscioli (divoké slávky z Conera) a bílé Verdicchio. Jedno z nejlépe hodnocených míst riviéry.', 43.5130, 13.6220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Numana.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Numana.jpg"}'::text[], 3),
    (v_route, 'Loreto – Basilica della Santa Casa', 'Jedno z nejvýznamnějších mariánských poutních míst Evropy: bazilika ukrývající Svatou chýši z Nazaretu. Opevněný chrámový komplex je vidět z celého okolí.', 43.4400, 13.6100, 'https://commons.wikimedia.org/wiki/Special:FilePath/Basilica%20di%20Loreto.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Basilica%20di%20Loreto.jpg"}'::text[], 4),
    (v_route, 'Recanati', 'Rodiště básníka Giacoma Leopardiho na hřebeni mezi dvěma údolími. Vyhlídka "Colle dell''Infinito" inspirovala nejslavnější italskou báseň — a nabízí výhled až k moři.', 43.4030, 13.5490, 'https://commons.wikimedia.org/wiki/Special:FilePath/Recanati.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Recanati.jpg"}'::text[], 5);

  -- Abruzzo – Gran Sasso a Campo Imperatore
  delete from public.routes where name = 'Abruzzo – Gran Sasso a Campo Imperatore' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Abruzzo – Gran Sasso a Campo Imperatore', 'Malé italské Tibety: náhorní planina Campo Imperatore v 1800 metrech, kde se pod nejvyšší horou Apenin Corno Grande (2912 m) pasou polodivocí koně a natáčely se westerny. Silnice bez svodidel se vlní otevřenou krajinou, jakou jinde v Itálii nenajdeš. Cestou zpět středověké perly — hradní zřícenina Rocca Calascio z filmu Ladyhawke a kamenná vesnice Santo Stefano di Sessanio. Jezdi od června do září, planina je vysoko a počasí se mění rychle; brzy na jaře a na podzim hrozí sníh. Vezmi teplou vrstvu i v létě.', 'loop', 150, 240, 'medium',
     '[{"lat": 42.3499, "lng": 13.3995, "label": "Start: L''Aquila"}, {"lat": 42.4422, "lng": 13.5589, "label": "Campo Imperatore"}, {"lat": 42.3650, "lng": 13.7260, "label": "Castel del Monte"}, {"lat": 42.3280, "lng": 13.6880, "label": "Rocca Calascio"}, {"lat": 42.3430, "lng": 13.6460, "label": "Santo Stefano di Sessanio"}, {"lat": 42.3499, "lng": 13.3995, "label": "Cíl: L''Aquila"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.3499,13.3995&destination=42.3499,13.3995&travelmode=driving&waypoints=42.4422,13.5589%7C42.3650,13.7260%7C42.3280,13.6880%7C42.3430,13.6460', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rocca%20Calascio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Basilica%20di%20Santa%20Maria%20di%20Collemaggio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Campo%20Imperatore.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rocca%20Calascio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Santo%20Stefano%20di%20Sessanio.jpg"}'::text[], '{"L''Aquila – bazilika Collemaggio","Campo Imperatore","Rocca Calascio","Santo Stefano di Sessanio"}'::text[], '{"IT"}'::text[], false, 4440, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'L''Aquila – bazilika Collemaggio', 'Hlavní město Abruzza s románskou bazilikou s růžovo-bílou šachovnicovou fasádou. Město se po zemětřesení 2009 vrací k životu a centrum opět žije.', 42.3499, 13.3995, 'https://commons.wikimedia.org/wiki/Special:FilePath/Basilica%20di%20Santa%20Maria%20di%20Collemaggio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Basilica%20di%20Santa%20Maria%20di%20Collemaggio.jpg"}'::text[], 0),
    (v_route, 'Campo Imperatore', 'Šestnáct kilometrů dlouhá náhorní planina pod Corno Grande, přezdívaná "malý Tibet". Nahoře observatoř a horský hotel, kde byl vězněn Mussolini. Jedna z nejpůsobivějších silnic Itálie.', 42.4422, 13.5589, 'https://commons.wikimedia.org/wiki/Special:FilePath/Campo%20Imperatore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Campo%20Imperatore.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Corno%20Grande.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Ristoro Mucciante (Campo Imperatore)', 'Legendární řeznictví s grily u silnice na planině: koupíš arrosticini (ovčí špízy), sám si je opečeš na žhavém uhlí a sníš s výhledem na hory. Motorkářská klasika Abruzza.', 42.4080, 13.7150, 'https://commons.wikimedia.org/wiki/Special:FilePath/Campo%20Imperatore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Campo%20Imperatore.jpg"}'::text[], 2),
    (v_route, 'Castel del Monte', 'Kamenná pastevecká vesnice na skále v 1300 metrech, členěná do středověkých pater a průchodů. Jedna z nejzachovalejších horských vesnic Apenin.', 42.3650, 13.7260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castel%20del%20Monte%20%28AQ%29.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castel%20del%20Monte%20%28AQ%29.jpg"}'::text[], 3),
    (v_route, 'Rocca Calascio', 'Nejvýše položená hradní zřícenina Apenin (1460 m), kulisa filmů Ladyhawke i Jméno růže. Od parkoviště 20 minut pěšky; západ slunce odsud je nezapomenutelný.', 42.3280, 13.6880, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rocca%20Calascio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rocca%20Calascio.jpg"}'::text[], 4),
    (v_route, 'Santo Stefano di Sessanio', 'Dokonale zachovaná středověká vesnice z medově zbarveného kamene, citlivě oživená jako "rozptýlený hotel". Úzké uličky, klenuté průchody a ticho hor.', 42.3430, 13.6460, 'https://commons.wikimedia.org/wiki/Special:FilePath/Santo%20Stefano%20di%20Sessanio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Santo%20Stefano%20di%20Sessanio.jpg"}'::text[], 5);

  -- Piemont – vinice Langhe a Barolo
  delete from public.routes where name = 'Piemont – vinice Langhe a Barolo' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Piemont – vinice Langhe a Barolo', 'Vlnící se kopce Langhe (UNESCO) — nekonečné vinice nebbiola, hrady na hřebenech a vesnice, jejichž jména zná každý milovník vína: Barolo, La Morra, Barbaresco. Silničky třetí třídy se kroutí po hřebenech vinic s výhledy na zasněžené Alpy na obzoru. Krátká vzdálenost, ale počítej s celým dnem — každá zastávka svádí k ochutnávce a lanýžové kuchyni (řidič samozřejmě střídmě). Nejkrásnější je podzim, kdy vinice zezlátnou a v Albě voní lanýže. Pozor na úzké silnice mezi vinicemi a traktory ve špičce vinobraní.', 'loop', 95, 180, 'easy',
     '[{"lat": 44.7009, "lng": 8.0353, "label": "Start: Alba"}, {"lat": 44.6560, "lng": 8.0090, "label": "Grinzane Cavour"}, {"lat": 44.6370, "lng": 7.9330, "label": "La Morra"}, {"lat": 44.6110, "lng": 7.9430, "label": "Barolo"}, {"lat": 44.6100, "lng": 8.0000, "label": "Serralunga d''Alba"}, {"lat": 44.7260, "lng": 8.0810, "label": "Barbaresco"}, {"lat": 44.7009, "lng": 8.0353, "label": "Cíl: Alba"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=44.7009,8.0353&destination=44.7009,8.0353&travelmode=driving&waypoints=44.6560,8.0090%7C44.6370,7.9330%7C44.6110,7.9430%7C44.6100,8.0000%7C44.7260,8.0810', 'https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Grinzane%20Cavour.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Alba.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Grinzane%20Cavour.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/La%20Morra.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Barolo.jpg"}'::text[], '{"Alba","Castello di Grinzane Cavour","La Morra – vyhlídka Belvedere","Barolo – Castello Falletti"}'::text[], '{"IT"}'::text[], false, 4450, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Alba', 'Hlavní město Langhe, metropole bílých lanýžů a čokolády (rodiště Nutelly). Středověké věže, sobotní trh a na podzim slavný lanýžový veletrh.', 44.7009, 8.0353, 'https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Alba.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Alba.jpg"}'::text[], 0),
    (v_route, 'Castello di Grinzane Cavour', 'Pohádkový hrad hraběte Cavoura uprostřed vinic, dnes UNESCO, muzeum vína a dějiště světové aukce lanýžů. Nejfotografovanější silueta Langhe.', 44.6560, 8.0090, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Grinzane%20Cavour.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Grinzane%20Cavour.jpg"}'::text[], 1),
    (v_route, 'La Morra – vyhlídka Belvedere', 'Vesnice na nejvyšším kopci oblasti s vyhlídkovou terasou nad mořem vinic — za jasného dne vidíš Monviso i Monte Rosu. Srdce apelace Barolo.', 44.6370, 7.9330, 'https://commons.wikimedia.org/wiki/Special:FilePath/La%20Morra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/La%20Morra.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Ristorante Bovio (La Morra)', 'Rodinná restaurace s panoramatickou terasou nad vinicemi — piemontská klasika: tajarin s lanýžem, vitello tonnato, carne cruda. Jedno z nejoblíbenějších míst Langhe, rezervuj.', 44.6360, 7.9350, 'https://commons.wikimedia.org/wiki/Special:FilePath/La%20Morra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/La%20Morra.jpg"}'::text[], 3),
    (v_route, 'Barolo – Castello Falletti', 'Vesnička, která dala jméno "králi vín". Na hradě Falletti sídlí interaktivní muzeum vína WiMu a v podhradí desítky enoték na ochutnávku (pro spolujezdce).', 44.6110, 7.9430, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Barolo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Barolo.jpg"}'::text[], 4),
    (v_route, 'Serralunga d''Alba', 'Nejštíhlejší hrad Piemontu — gotická věžová pevnost ze 14. století trčící nad vesnicí jako maják vinic. Krásný okruh uličkami kolem hradního návrší.', 44.6100, 8.0000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Serralunga%20d%27Alba.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Serralunga%20d%27Alba.jpg"}'::text[], 5),
    (v_route, 'Barbaresco', 'Druhá velká apelace nebbiola s charakteristickou středověkou věží nad řekou Tanaro. Z vrcholu věže panoráma celých Langhe — důstojná tečka okruhu.', 44.7260, 8.0810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Barbaresco.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Barbaresco.jpg"}'::text[], 6);

  -- Údolí Aosty – hrady pod Mont Blankem
  delete from public.routes where name = 'Údolí Aosty – hrady pod Mont Blankem' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí Aosty – hrady pod Mont Blankem', 'Projížďka nejmenším italským regionem od pevnosti Bard až pod stěnu Mont Blanku. Údolím Dora Baltea se řadí hrad za hradem — Bard, Fénis, Saint-Pierre — mezi nimi římská Aosta s triumfálním obloukem a divadlem. Finále patří Courmayeur a lanovce Skyway, která tě otočnou kabinou vyveze do 3466 metrů na Punta Helbronner. Jeď po staré silnici SS26, dálnici nech kamionům; stoupání je pozvolné a zvládne ho každý. Ideální červen až září; nad 2000 metrů bývá chladno i v létě.', 'poi', 100, 150, 'easy',
     '[{"lat": 45.5980, "lng": 7.7960, "label": "Start: Pont-Saint-Martin"}, {"lat": 45.6080, "lng": 7.7440, "label": "Forte di Bard"}, {"lat": 45.7360, "lng": 7.4900, "label": "Castello di Fénis"}, {"lat": 45.7390, "lng": 7.3260, "label": "Aosta"}, {"lat": 45.7100, "lng": 7.2230, "label": "Castello di Saint-Pierre"}, {"lat": 45.7920, "lng": 6.9720, "label": "Courmayeur"}, {"lat": 45.8140, "lng": 6.9660, "label": "Cíl: Skyway Monte Bianco"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.5980,7.7960&destination=45.8140,6.9660&travelmode=driving&waypoints=45.6080,7.7440%7C45.7360,7.4900%7C45.7390,7.3260%7C45.7100,7.2230%7C45.7920,6.9720', 'https://commons.wikimedia.org/wiki/Special:FilePath/Forte%20di%20Bard.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Forte%20di%20Bard.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20F%C3%A9nis.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Arco%20di%20Augusto%20Aosta.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skyway%20Monte%20Bianco.jpg"}'::text[], '{"Forte di Bard","Castello di Fénis","Aosta – Arco di Augusto","Skyway Monte Bianco"}'::text[], '{"IT"}'::text[], false, 4460, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Forte di Bard', 'Mohutná napoleonská pevnost přehrazující celé údolí — dnes muzeum Alp a kulisa z filmu Avengers 2. Nahoru vedou prosklené šikmé výtahy, výhled je velkolepý.', 45.6080, 7.7440, 'https://commons.wikimedia.org/wiki/Special:FilePath/Forte%20di%20Bard.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Forte%20di%20Bard.jpg"}'::text[], 0),
    (v_route, 'Castello di Fénis', 'Nejslavnější hrad údolí: dokonalá středověká pevnost s dvojitými hradbami, věžičkami a freskami na nádvoří. Vypadá přesně tak, jak si hrad představuje každé dítě.', 45.7360, 7.4900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20F%C3%A9nis.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20F%C3%A9nis.jpg"}'::text[], 1),
    (v_route, 'Aosta – Arco di Augusto', 'Řím v Alpách: triumfální oblouk, městské brány a divadlo z dob císaře Augusta. Kompaktní centrum projdeš za hodinu, kavárny na Piazza Chanoux svádějí k delší pauze.', 45.7390, 7.3260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arco%20di%20Augusto%20Aosta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arco%20di%20Augusto%20Aosta.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Osteria da Nando (Aosta)', 'Rodinná osteria v centru Aosty fungující od roku 1957 — fondue, polenta s dušeným masem a valdostánská vína. Poctivá horská kuchyně za férové ceny.', 45.7370, 7.3200, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arco%20di%20Augusto%20Aosta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arco%20di%20Augusto%20Aosta.jpg"}'::text[], 3),
    (v_route, 'Castello di Saint-Pierre', 'Nejfotogeničtější hrad regionu — pohádková silueta se čtyřmi věžičkami na skále přímo nad silnicí SS26. Uvnitř přírodovědné muzeum, zvenku povinná fotka.', 45.7100, 7.2230, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Saint-Pierre.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castello%20di%20Saint-Pierre.jpg"}'::text[], 4),
    (v_route, 'Courmayeur', 'Elegantní horské středisko na úpatí Mont Blanku, konec italské strany masivu. Pěší zóna s horskými butiky a výhledy na ledovce Brenvy.', 45.7920, 6.9720, 'https://commons.wikimedia.org/wiki/Special:FilePath/Courmayeur.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Courmayeur.jpg"}'::text[], 5),
    (v_route, 'Skyway Monte Bianco', 'Futuristická lanovka s otočnými kabinami na Punta Helbronner (3466 m) — terasa s výhledem na Mont Blanc, Matterhorn i Gran Paradiso. Motorku nech na hlídaném parkovišti u dolní stanice.', 45.8140, 6.9660, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skyway%20Monte%20Bianco.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skyway%20Monte%20Bianco.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monte%20Bianco.jpg"}'::text[], 6);

  -- Ligurské vnitrozemí – Dolceacqua a Triora
  delete from public.routes where name = 'Ligurské vnitrozemí – Dolceacqua a Triora' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Ligurské vnitrozemí – Dolceacqua a Triora', 'Zapomenutá Ligurie pár kilometrů od riviéry: kamenné vesnice přilepené na skalách, jednopruhé silničky v roklích a středověké mosty, které maloval Monet. Z Ventimiglie stoupáš údolím Nervia přes Dolceacquu a orlí hnízdo Apricale, pak přes horské sedlo do údolí Argentina k "vesnici čarodějnic" Triora. Zpátky k moři podél řeky do Taggie a po pobřeží přes Sanremo. Úzké serpentiny vyžadují soustředění a čistou techniku — trasa pro zkušenější jezdce. Nejlépe na jaře a na podzim; v létě je u pobřeží rušno, ale vnitrozemí zůstává liduprázdné.', 'loop', 130, 270, 'hard',
     '[{"lat": 43.7900, "lng": 7.6070, "label": "Start: Ventimiglia"}, {"lat": 43.8480, "lng": 7.6220, "label": "Dolceacqua"}, {"lat": 43.8800, "lng": 7.6600, "label": "Apricale"}, {"lat": 43.9320, "lng": 7.6620, "label": "Pigna"}, {"lat": 44.0000, "lng": 7.7640, "label": "Triora"}, {"lat": 43.8620, "lng": 7.8510, "label": "Taggia"}, {"lat": 43.8160, "lng": 7.7760, "label": "Sanremo"}, {"lat": 43.7900, "lng": 7.6070, "label": "Cíl: Ventimiglia"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.7900,7.6070&destination=43.7900,7.6070&travelmode=driving&waypoints=43.8480,7.6220%7C43.8800,7.6600%7C43.9320,7.6620%7C44.0000,7.7640%7C43.8620,7.8510%7C43.8160,7.7760', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dolceacqua.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dolceacqua.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Apricale.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Triora.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sanremo.jpg"}'::text[], '{"Dolceacqua","Apricale","Triora","Sanremo"}'::text[], '{"IT"}'::text[], false, 4470, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Dolceacqua', 'Vesnice s hrbatým středověkým mostem a hradem Doria, kterou Claude Monet označil za "klenot lehkosti". Ochutnej místní červené Rossese — a pozor, most je jen pro pěší.', 43.8480, 7.6220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dolceacqua.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dolceacqua.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Ristorante Apricale da Delio (Apricale)', 'Rodinný podnik na náměstíčku v Apricale — králík po ligursku, domácí ravioli a olivový olej z vlastního háje. Jedna z nejlepších tradičních kuchyní vnitrozemí.', 43.8800, 7.6600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Apricale.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Apricale.jpg"}'::text[], 1),
    (v_route, 'Apricale', 'Orlí hnízdo z kamene rozlévající se po hřebeni — jedna z oficiálně nejkrásnějších vesnic Itálie. Auta zůstávají venku, uličkami se jen chodí.', 43.8800, 7.6600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Apricale.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Apricale.jpg"}'::text[], 2),
    (v_route, 'Pigna', 'Terasovitá vesnice nad údolím Nervia se středověkým jádrem a termálními prameny. Odsud začíná nejdivočejší úsek trasy přes sedlo do údolí Argentina.', 43.9320, 7.6620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pigna%20%28Imperia%29.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pigna%20%28Imperia%29.jpg"}'::text[], 3),
    (v_route, 'Triora', '"Vesnice čarodějnic" — dějiště největšího čarodějnického procesu Itálie (1587). Tajemné kamenné uličky, muzeum čarodějnictví a výhledy na hřebeny Ligurských Alp.', 44.0000, 7.7640, 'https://commons.wikimedia.org/wiki/Special:FilePath/Triora.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Triora.jpg"}'::text[], 4),
    (v_route, 'Taggia', 'Městečko oliv taggiasca s monumentálním středověkým mostem o šestnácti obloucích. Tady se rodí nejslavnější italský olivový olej — kup lahev do kufru.', 43.8620, 7.8510, 'https://commons.wikimedia.org/wiki/Special:FilePath/Taggia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Taggia.jpg"}'::text[], 5),
    (v_route, 'Sanremo', 'Město květin, kasina a slavného hudebního festivalu. Projeď po pobřežní promenádě Imperatrice a dej si kávu v přístavu — návrat do civilizace po horských samotách.', 43.8160, 7.7760, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sanremo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sanremo.jpg"}'::text[], 6);

  -- Sicílie – barokní Val di Noto
  delete from public.routes where name = 'Sicílie – barokní Val di Noto' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sicílie – barokní Val di Noto', 'Jihovýchod Sicílie, kde po zemětřesení 1693 vyrostla nejkrásnější barokní města Evropy — dnes všechna na seznamu UNESCO. Ze Syrakus a ostrova Ortigia vede trasa medově zlatým Notem k rybářskému Marzamemi na samém jihu, pak vápencovými kaňony k filmovému Scicli, čokoládové Modice a velkolepé Ragusa Ibla. Silnice se vlní mezi kamennými zídkami, rohovníky a olivami; provoz je mimo města minimální. Ideální březen až červen a září až listopad — v létě tu bývá přes 35 °C. Ve městech parkuj ve stínu a hlídej si úzké jednosměrky.', 'loop', 225, 330, 'easy',
     '[{"lat": 37.0590, "lng": 15.2930, "label": "Start: Syrakusy (Ortigia)"}, {"lat": 36.8910, "lng": 15.0690, "label": "Noto"}, {"lat": 36.7370, "lng": 15.1180, "label": "Marzamemi"}, {"lat": 36.7900, "lng": 14.7060, "label": "Scicli"}, {"lat": 36.8590, "lng": 14.7610, "label": "Modica"}, {"lat": 36.9210, "lng": 14.7400, "label": "Ragusa Ibla"}, {"lat": 37.0590, "lng": 15.2930, "label": "Cíl: Syrakusy (Ortigia)"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.0590,15.2930&destination=37.0590,15.2930&travelmode=driving&waypoints=36.8910,15.0690%7C36.7370,15.1180%7C36.7900,14.7060%7C36.8590,14.7610%7C36.9210,14.7400', 'https://commons.wikimedia.org/wiki/Special:FilePath/Noto%20Cathedral.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Siracusa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Noto%20Cathedral.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Marzamemi.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ragusa%20Ibla.jpg"}'::text[], '{"Syrakusy – Ortigia","Noto – katedrála","Marzamemi","Ragusa Ibla"}'::text[], '{"IT"}'::text[], false, 4480, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Syrakusy – Ortigia', 'Ostrovní stará čtvrť Syrakus: katedrála vestavěná do antického Athénina chrámu, barokní náměstí a pramen Aretusa u moře. Kdysi největší město antického světa.', 37.0590, 15.2930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Siracusa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duomo%20di%20Siracusa.jpg"}'::text[], 0),
    (v_route, 'Noto – katedrála', 'Hlavní město sicilského baroka — celé postavené z medového vápence, který při západu slunce hoří zlatem. Monumentální schodiště katedrály a korzo Vittorio Emanuele jsou povinnost.', 36.8910, 15.0690, 'https://commons.wikimedia.org/wiki/Special:FilePath/Noto%20Cathedral.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Noto%20Cathedral.jpg"}'::text[], 1),
    (v_route, 'Marzamemi', 'Bývalá tuňáková osada s náměstíčkem přímo u vody — dnes nejfotogeničtější rybářská vesnice Sicílie. Ochutnej bottargu nebo granitu u přístavu.', 36.7370, 15.1180, 'https://commons.wikimedia.org/wiki/Special:FilePath/Marzamemi.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Marzamemi.jpg"}'::text[], 2),
    (v_route, 'Scicli', 'Barokní městečko sevřené v kaňonu, známé jako "Vigàta" ze seriálu Komisař Montalbano. Via Mormino Penna patří k nejhezčím barokním ulicím Itálie.', 36.7900, 14.7060, 'https://commons.wikimedia.org/wiki/Special:FilePath/Scicli.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Scicli.jpg"}'::text[], 3),
    (v_route, 'Modica', 'Město čokolády vyráběné za studena podle aztécké receptury a barokního chrámu San Giorgio na 250 schodech. Domy tu šplhají po stěnách kaňonu jedno nad druhým.', 36.8590, 14.7610, 'https://commons.wikimedia.org/wiki/Special:FilePath/Modica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Modica.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Antica Dolceria Bonajuto (Modica)', 'Nejstarší čokoládovna Sicílie (1880) v uličce pod chrámem San Giorgio — křupavá modická čokoláda s vanilkou či chilli a legendární "mpanatigghi" s masem a kakaem. Sladká povinná zastávka.', 36.8580, 14.7600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Modica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Modica.jpg"}'::text[], 5),
    (v_route, 'Ragusa Ibla', 'Barokní stará čtvrť na skalním ostrohu — labyrint schodišť a paláců korunovaný kupolí chrámu San Giorgio. Nejkrásnější pohled je z vyhlídky u kostela Santa Maria delle Scale.', 36.9210, 14.7400, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ragusa%20Ibla.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ragusa%20Ibla.jpg"}'::text[], 6);

  -- Sardinie – Orientale Sarda a Supramonte
  delete from public.routes where name = 'Sardinie – Orientale Sarda a Supramonte' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sardinie – Orientale Sarda a Supramonte', 'Legendární silnice SS125 Orientale Sarda — divoký východ Sardinie mezi červenými skalami Arbataxu a vápencovými masivy Supramonte. Stará trasa přes sedlo Genna Silana (1017 m) je považována za nejkrásnější motorkářskou silnici ostrova: kilometry zatáček nad kaňonem Gorropu, nejhlubší soutěskou Evropy. Sjezd do Cala Gonone odmění tyrkysovým mořem a na závěr čekají slavné murály pastevecké vesnice Orgosolo. Jeď po staré SS125, ne po nové rychlostní silnici. Ideální květen, červen a září; v létě horko a plné pláže. Pozor na volně se pasoucí kozy a prasata na silnici.', 'poi', 160, 270, 'medium',
     '[{"lat": 39.9410, "lng": 9.7070, "label": "Start: Arbatax"}, {"lat": 40.0310, "lng": 9.6660, "label": "Baunei"}, {"lat": 40.1450, "lng": 9.4890, "label": "Genna Silana (Gorropu)"}, {"lat": 40.2910, "lng": 9.5900, "label": "Dorgali"}, {"lat": 40.2820, "lng": 9.6350, "label": "Cala Gonone"}, {"lat": 40.2050, "lng": 9.3540, "label": "Orgosolo"}, {"lat": 40.3210, "lng": 9.3300, "label": "Cíl: Nuoro"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=39.9410,9.7070&destination=40.3210,9.3300&travelmode=driving&waypoints=40.0310,9.6660%7C40.1450,9.4890%7C40.2910,9.5900%7C40.2820,9.6350%7C40.2050,9.3540', 'https://commons.wikimedia.org/wiki/Special:FilePath/Gola%20di%20Gorropu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arbatax.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gola%20di%20Gorropu.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cala%20Gonone.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Orgosolo.jpg"}'::text[], '{"Arbatax – Rocce Rosse","Gola di Gorropu","Cala Gonone","Orgosolo – murály"}'::text[], '{"IT"}'::text[], false, 4490, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Arbatax – Rocce Rosse', 'Červené porfyrové skály trčící přímo z moře u přístavu Arbatax — ikonický start východosardinské cesty. Ráno tu bývá klid a nejlepší světlo na fotku.', 39.9410, 9.7070, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arbatax.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arbatax.jpg"}'::text[], 0),
    (v_route, 'Baunei', 'Horská vesnice přilepená na svahu 500 metrů nad mořem, brána k zázračným plážím zálivu Orosei. Z terasy u kostela přehlédneš celé pobřeží.', 40.0310, 9.6660, 'https://commons.wikimedia.org/wiki/Special:FilePath/Baunei.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Baunei.jpg"}'::text[], 1),
    (v_route, 'Gola di Gorropu', 'Nejhlubší kaňon Evropy — vápencové stěny až 500 metrů vysoké. Od sedla Genna Silana na SS125 vede k okraji soutěsky stezka; i samotná vyhlídka od silnice bere dech.', 40.1450, 9.4890, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gola%20di%20Gorropu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gola%20di%20Gorropu.jpg"}'::text[], 2),
    (v_route, 'Dorgali', 'Živé městečko pod masivem Supramonte, centrum řemesel — kůže, keramika, filigrán a víno Cannonau. Dobrá zastávka na kávu a doplnění zásob.', 40.2910, 9.5900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dorgali.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dorgali.jpg"}'::text[], 3),
    (v_route, 'Cala Gonone', 'Přímořské letovisko v amfiteátru hor, výchozí bod k plážím Cala Luna a jeskyni Bue Marino. Sjezd z tunelu nad městem patří k nejhezčím kilometrům trasy.', 40.2820, 9.6350, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cala%20Gonone.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cala%20Gonone.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Il Pescatore (Cala Gonone)', 'Rybí restaurace u přístavu v Cala Gonone — čerstvý úlovek dne, špagety s mořskými plody a sardinské Vermentino s výhledem na záliv Orosei.', 40.2830, 9.6360, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cala%20Gonone.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cala%20Gonone.jpg"}'::text[], 5),
    (v_route, 'Orgosolo – murály', 'Pastevecká vesnice v srdci Barbagie proslulá stovkami politických murálů na fasádách domů. Syrová, opravdová Sardinie daleko od plážových letovisek.', 40.2050, 9.3540, 'https://commons.wikimedia.org/wiki/Special:FilePath/Orgosolo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Orgosolo.jpg"}'::text[], 6);

  -- Gargano – Vieste a Foresta Umbra
  delete from public.routes where name = 'Gargano – Vieste a Foresta Umbra' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Gargano – Vieste a Foresta Umbra', 'Ostruha italské boty: vápencový poloostrov Gargano, kde se pobřežní silnice SS89 mezi Vieste a Mattinatou počítá k nejkrásnějším přímořským cestám Itálie. Bílé útesy, skalní oblouky, zátoky s věžemi trabucchi a uprostřed poloostrova pralesovitá Foresta Umbra — buková rezervace UNESCO s chladivými serpentinami. K tomu poutní Monte Sant''Angelo s jeskynní svatyní archanděla Michaela. Zatáček je nepočítaně a tempo pomalé — na 185 km si nech celý den. Ideální květen, červen a září; v srpnu je pobřeží přeplněné. Pozor na písek v zatáčkách u pláží.', 'loop', 185, 300, 'medium',
     '[{"lat": 41.6260, "lng": 15.9110, "label": "Start: Manfredonia"}, {"lat": 41.7080, "lng": 15.9550, "label": "Monte Sant''Angelo"}, {"lat": 41.8215, "lng": 16.0090, "label": "Foresta Umbra"}, {"lat": 41.9450, "lng": 16.0140, "label": "Peschici"}, {"lat": 41.8820, "lng": 16.1760, "label": "Vieste"}, {"lat": 41.7230, "lng": 16.1180, "label": "Baia delle Zagare"}, {"lat": 41.7100, "lng": 16.0500, "label": "Mattinata"}, {"lat": 41.6260, "lng": 15.9110, "label": "Cíl: Manfredonia"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=41.6260,15.9110&destination=41.6260,15.9110&travelmode=driving&waypoints=41.7080,15.9550%7C41.8215,16.0090%7C41.9450,16.0140%7C41.8820,16.1760%7C41.7230,16.1180%7C41.7100,16.0500', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vieste.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monte%20Sant%27Angelo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Peschici.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vieste.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Baia%20delle%20Zagare.jpg"}'::text[], '{"Monte Sant''Angelo","Peschici","Vieste","Baia delle Zagare"}'::text[], '{"IT"}'::text[], false, 4500, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Monte Sant''Angelo', 'Poutní město v 800 metrech s jeskynní svatyní archanděla Michaela (UNESCO), kam mířili poutníci už od 5. století. Z hradeb výhled přes celý Manfredonský záliv.', 41.7080, 15.9550, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monte%20Sant%27Angelo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monte%20Sant%27Angelo.jpg"}'::text[], 0),
    (v_route, 'Foresta Umbra', 'Prastarý bukový prales v srdci Gargana, zapsaný na seznamu UNESCO. Stinné serpentiny rezervací jsou v letním vedru balzám — u návštěvnického centra jezírko s daňky.', 41.8215, 16.0090, 'https://commons.wikimedia.org/wiki/Special:FilePath/Foresta%20Umbra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Foresta%20Umbra.jpg"}'::text[], 1),
    (v_route, 'Peschici', 'Bílé městečko na útesu nad vlastní zátokou s plážemi. Labyrint arabsky působících uliček a výhledy na dřevěné rybářské konstrukce trabucchi pod útesy.', 41.9450, 16.0140, 'https://commons.wikimedia.org/wiki/Special:FilePath/Peschici.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Peschici.jpg"}'::text[], 2),
    (v_route, 'Vieste', 'Hlavní město Gargana s monolitem Pizzomunno u pláže — 25 metrů vysokou vápencovou věží opředenou legendou. Stará čtvrť na skále nad mořem je stvořená k večerní procházce.', 41.8820, 16.1760, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vieste.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vieste.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Osteria al Duomo (Vieste)', 'Osteria v kamenném sklepení ve staré čtvrti Vieste — orecchiette s mořskými plody, grilované ryby a apulské Primitivo. Výborně hodnocená klasika u katedrály.', 41.8830, 16.1770, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vieste.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vieste.jpg"}'::text[], 4),
    (v_route, 'Baia delle Zagare', 'Nejfotografovanější zátoka Jadranu: dva vápencové skalní oblouky vystupující z tyrkysové vody pod bílými útesy. Vyhlídka přímo u silnice SS89.', 41.7230, 16.1180, 'https://commons.wikimedia.org/wiki/Special:FilePath/Baia%20delle%20Zagare.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Baia%20delle%20Zagare.jpg"}'::text[], 5),
    (v_route, 'Mattinata', '"Bílý motýl" Gargana — městečko rozložené na dvou kopcích mezi olivovými háji nad mořem. Poslední kávová zastávka před návratem do Manfredonie.', 41.7100, 16.0500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mattinata.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mattinata.jpg"}'::text[], 6);

end $$;
