-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — FINSKO (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Saariston rengastie – okruh Turkuským souostrovím
  delete from public.routes where name = 'Saariston rengastie – okruh Turkuským souostrovím' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Saariston rengastie – okruh Turkuským souostrovím', 'Legendární Okružní cesta souostrovím je nejslavnější finská letní vyjížďka: z Turku vede po klidných, dokonale asfaltovaných silničkách přes ostrovy Parainen, Nauvo, Korppoo a Houtskari a zpět přes Kustavi. Mezi ostrovy vás přepraví žluté silniční trajekty, které jsou z velké části zdarma a jsou zážitkem samy o sobě. Jede se mezi žulovými skalisky, rudými dřevěnicemi a zátokami Baltu, provoz je minimální a tempo pohodové. Trasa je sjízdná od poloviny června do srpna, kdy jezdí všechny trajektové linky — mimo sezónu okruh nejde uzavřít. Počítejte s celodenním výletem a časem na čekání na trajekty; pozor na hladké žulové nájezdy na přívozy za mokra.', 'loop', 250, 480, 'medium',
     '[{"lat": 60.4518, "lng": 22.2666, "label": "Start: Turku"}, {"lat": 60.3103, "lng": 22.3023, "label": "Parainen"}, {"lat": 60.1946, "lng": 21.9105, "label": "Nauvo"}, {"lat": 60.1610, "lng": 21.5680, "label": "Korppoo"}, {"lat": 60.2225, "lng": 21.3705, "label": "Houtskari"}, {"lat": 60.5462, "lng": 21.3583, "label": "Kustavi"}, {"lat": 60.4518, "lng": 22.2666, "label": "Cíl: Turku"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=60.4518,22.2666&destination=60.4518,22.2666&travelmode=driving&waypoints=60.3103,22.3023%7C60.1946,21.9105%7C60.1610,21.5680%7C60.2225,21.3705%7C60.5462,21.3583', 'https://commons.wikimedia.org/wiki/Special:FilePath/Turun%20tuomiokirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turun%20tuomiokirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Paraisten%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nauvon%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nauvon%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Korppoon%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Houtskarin%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kustavin%20kirkko.jpg"}'::text[], '{"Katedrála v Turku","Parainen","Nauvo – přístav","Restaurace: L''Escale (Nauvo)","Korppoo","Houtskari","Kustavi"}'::text[], '{"FI"}'::text[], false, 3710, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Katedrála v Turku', 'Národní svatyně Finska ze 13. století je nejvýznamnější středověkou stavbou země a dominantou nejstaršího finského města. Před startem okruhu stojí za to projít se po nábřeží řeky Aury, kde kotví historické lodě a žijí kavárny. Motorku pohodlně zaparkujete u katedrály.', 60.4525, 22.2783, 'https://commons.wikimedia.org/wiki/Special:FilePath/Turun%20tuomiokirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turun%20tuomiokirkko.jpg"}'::text[], 0),
    (v_route, 'Parainen', 'Brána do souostroví a městečko vyrostlé kolem obřího vápencového lomu, jednoho z největších v severní Evropě. Od středověkého kamenného kostela se silnice noří mezi mosty a hráze spojující první ostrovy. Odtud už jedete ostrovní rytmus — klid, moře a žula.', 60.3020, 22.3005, 'https://commons.wikimedia.org/wiki/Special:FilePath/Paraisten%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Paraisten%20kirkko.jpg"}'::text[], 1),
    (v_route, 'Nauvo – přístav', 'Nejživější zastávka okruhu: malebný jachtařský přístav s dřevěnými domky, zmrzlinou a promenádou, v létě plný lodí z celého Baltu. Nad přístavem stojí středověký kamenný kostel svatého Olafa. Ideální místo na první delší pauzu a fotku s motorkou u mola.', 60.1946, 21.9105, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nauvon%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nauvon%20kirkko.jpg"}'::text[], 2),
    (v_route, 'Restaurace: L''Escale (Nauvo)', 'Vyhlášená restaurace přímo v přístavu Nauvo s francouzsko-ostrovní kuchyní, čerstvými rybami a výhledem na kotvící plachetnice. Patří k nejlépe hodnoceným podnikům celého souostroví a v sezóně bývá plno, přijeďte raději mimo poledne. Skvělé místo na oběd v půlce prvního ostrovního úseku.', 60.1950, 21.9120, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nauvon%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nauvon%20kirkko.jpg"}'::text[], 3),
    (v_route, 'Korppoo', 'Ostrov s hlubokými lesy a středověkým kostelem svatého Michala, kde silnice kličkuje mezi skalisky a zálivy. Z Korppoo odplouvá delší trajekt do Houtskari — plavba mezi stovkami ostrůvků je jedním z vrcholů celé trasy. V přístavu Galtby si dejte kávu, než loď připluje.', 60.1610, 21.5680, 'https://commons.wikimedia.org/wiki/Special:FilePath/Korppoon%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Korppoon%20kirkko.jpg"}'::text[], 4),
    (v_route, 'Houtskari', 'Nejodlehlejší obydlený kout okruhu, kde se mluví převážně švédsky a čas plyne pomaleji. Dřevěný kostel, drobné farmy a jednoproudé silničky mezi pastvinami dávají jízdě úplně jiný rozměr. Odtud pokračuje dlouhý trajekt přes Iniö směrem na Kustavi.', 60.2225, 21.3705, 'https://commons.wikimedia.org/wiki/Special:FilePath/Houtskarin%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Houtskarin%20kirkko.jpg"}'::text[], 5),
    (v_route, 'Kustavi', 'Poslední ostrovní obec okruhu, proslulá dřevěným kostelem a v červenci humornými slavnostmi lososa. Zpáteční úsek do Turku po silnici 192 je svižný, s dlouhými plynulými zatáčkami mezi lesy a zálivy. Dobré místo doplnit palivo před závěrečnou stovkou kilometrů.', 60.5462, 21.3583, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kustavin%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kustavin%20kirkko.jpg"}'::text[], 6);

  -- Åland – Kastelholm, Bomarsund a Geta
  delete from public.routes where name = 'Åland – Kastelholm, Bomarsund a Geta' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Åland – Kastelholm, Bomarsund a Geta', 'Ostrovní okruh po autonomních Ålandách, švédsky mluvícím souostroví mezi Finskem a Švédskem, kam se s motorkou dostanete trajektem z Turku nebo Helsinek. Silnice jsou úzké, perfektně udržované a téměř prázdné, vedou mezi rudými skalami, poli a stovkami zátok. Okruh z Mariehamnu spojuje středověký hrad Kastelholm, ruiny ruské pevnosti Bomarsund a žulové kopce Getabergen na severu. Nejlepší je červen až srpen, kdy je otevřeno vše včetně vyhlídkových kaváren. Pozor na srnky a jeleny na silnici za šera a na pomalé tempo místní dopravy — na Ålandech nikdo nespěchá.', 'loop', 150, 240, 'easy',
     '[{"lat": 60.0971, "lng": 19.9348, "label": "Start: Mariehamn"}, {"lat": 60.2318, "lng": 20.0743, "label": "Kastelholm"}, {"lat": 60.2122, "lng": 20.2373, "label": "Bomarsund"}, {"lat": 60.3819, "lng": 19.8459, "label": "Geta"}, {"lat": 60.2242, "lng": 19.5479, "label": "Eckerö"}, {"lat": 60.0971, "lng": 19.9348, "label": "Cíl: Mariehamn"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=60.0971,19.9348&destination=60.0971,19.9348&travelmode=driving&waypoints=60.2318,20.0743%7C60.2122,20.2373%7C60.3819,19.8459%7C60.2242,19.5479', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pommern%20Mariehamn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pommern%20Mariehamn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kastelholms%20slott.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kastelholms%20slott.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bomarsund.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Geta%20kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ecker%C3%B6%20post-%20och%20tullhus.jpg"}'::text[], '{"Mariehamn – plachetnice Pommern","Hrad Kastelholm","Restaurace: Smakbyn (Kastelholm)","Pevnost Bomarsund","Geta a Getabergen","Eckerö – Pošta a celnice"}'::text[], '{"FI"}'::text[], false, 3720, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Mariehamn – plachetnice Pommern', 'Hlavní město Åland je město námořníků: v západním přístavu kotví čtyřstěžňová plachetnice Pommern, jediná loď svého druhu na světě dochovaná v původním stavu, dnes muzeum. Lipami lemovaná třída Esplanadi zve na kávu před startem okruhu. Odtud vyrážíte na sever do vnitrozemí souostroví.', 60.0940, 19.9280, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pommern%20Mariehamn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pommern%20Mariehamn.jpg"}'::text[], 0),
    (v_route, 'Hrad Kastelholm', 'Jediný středověký hrad Åland, sídlo švédských správců souostroví ze 14. století, malebně posazený u mořské zátoky v Sundu. Prohlídka nádvoří a věží zabere hodinku, hned vedle je skanzen Jan Karlsgården s větrnými mlýny. Silnice k hradu se vlní mezi poli a patří k nejhezčím úsekům okruhu.', 60.2318, 20.0743, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kastelholms%20slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kastelholms%20slott.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Smakbyn (Kastelholm)', 'Gastronomická vesnička slavného ålandského šéfkuchaře Michaela Björklunda hned u hradu Kastelholm. Poctivá severská kuchyně z místních surovin, vlastní palírna a skvělé hodnocení — jedna z nejlepších kuchyní celého souostroví. Ideální oběd v první třetině okruhu.', 60.2300, 20.0700, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kastelholms%20slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kastelholms%20slott.jpg"}'::text[], 2),
    (v_route, 'Pevnost Bomarsund', 'Monumentální ruiny ruské pevnosti z 19. století, kterou v Krymské válce dobyla a vyhodila do povětří britsko-francouzská flotila. Rozlehlé hradby nad mořskou úžinou jsou volně přístupné a nabízejí krásné výhledy i kus dramatické historie. Silnice prochází přímo mezi zbytky opevnění.', 60.2122, 20.2373, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bomarsund.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bomarsund.jpg"}'::text[], 3),
    (v_route, 'Geta a Getabergen', 'Nejsevernější obec hlavního ostrova pod žulovými kopci Getabergen, odkud se otevírá nejlepší výhled na Ålandech — červené skály, borovice a nekonečné moře ostrůvků. Na vrchol vede úzká asfaltka ke kavárně s vyhlídkou. Cestou na sever si užijete nejzatáčkovitější kilometry souostroví.', 60.3819, 19.8459, 'https://commons.wikimedia.org/wiki/Special:FilePath/Geta%20kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Geta%20kyrka.jpg"}'::text[], 4),
    (v_route, 'Eckerö – Pošta a celnice', 'Empírový Poštovní a celní dům v Eckerö od architekta Engela byl kdysi západní výspou ruského impéria — tady končila pošta z Petrohradu a začínala plavba do Švédska. Dnes v něm sídlí galerie a muzeum, kolem jsou písečné pláže. Poslední zastávka před návratem do Mariehamnu.', 60.2200, 19.5460, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ecker%C3%B6%20post-%20och%20tullhus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ecker%C3%B6%20post-%20och%20tullhus.jpg"}'::text[], 5);

  -- Saimaa – Lappeenranta, Imatra a Puumala
  delete from public.routes where name = 'Saimaa – Lappeenranta, Imatra a Puumala' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Saimaa – Lappeenranta, Imatra a Puumala', 'Okruh kolem jižního břehu Saimay, největšího finského jezera, spojuje pevnostní město Lappeenranta, slavné peřeje v Imatře a jednu z nejkrásnějších jezerních silnic země přes Puumalu. Silnice 62 mezi Imatrou a Puumalou se vlní po úzkých šíjích mezi jezerními zálivy — plynulé zatáčky, výhledy na vodu z obou stran a minimum provozu. Cestou potkáte architekturu od secese po Alvara Aalta i ruskou vojenskou historii. Nejlepší období je červen až září; v červenci počítejte s chatařským provozem. Pozor na losy, zvlášť za soumraku, a na občasné remízky s hrubším asfaltem.', 'loop', 240, 330, 'easy',
     '[{"lat": 61.0587, "lng": 28.1887, "label": "Start: Lappeenranta"}, {"lat": 61.1719, "lng": 28.7724, "label": "Imatra"}, {"lat": 61.5262, "lng": 28.1762, "label": "Puumala"}, {"lat": 61.1590, "lng": 28.0570, "label": "Taipalsaari"}, {"lat": 61.0587, "lng": 28.1887, "label": "Cíl: Lappeenranta"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=61.0587,28.1887&destination=61.0587,28.1887&travelmode=driving&waypoints=61.1719,28.7724%7C61.5262,28.1762%7C61.1590,28.0570', 'https://commons.wikimedia.org/wiki/Special:FilePath/Imatrankoski.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lappeenrannan%20linnoitus.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Imatrankoski.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Imatran%20valtionhotelli.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kolmen%20ristin%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Puumalansalmen%20silta.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Puumalansalmen%20silta.jpg"}'::text[], '{"Pevnost Lappeenranta","Peřeje Imatrankoski","Imatran Valtionhotelli","Kostel tří křížů (Vuoksenniska)","Most Puumalansalmi","Restaurace: Sahanlahti (Puumala)"}'::text[], '{"FI"}'::text[], false, 3730, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Pevnost Lappeenranta', 'Historická pevnost na návrší nad přístavem Saimay, kterou postupně budovali Švédové i Rusové. Uvnitř hradeb najdete nejstarší pravoslavný kostel Finska, muzea a dílny řemeslníků, dole v přístavu kotví výletní parníky. Skvělé místo na procházku před startem okruhu.', 61.0665, 28.1849, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lappeenrannan%20linnoitus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lappeenrannan%20linnoitus.jpg"}'::text[], 0),
    (v_route, 'Peřeje Imatrankoski', 'Nejslavnější finské peřeje v korytě řeky Vuoksy, kam jezdila obdivovat divokou vodu i ruská carevna Kateřina II. Řeka je dnes přehrazená a burácivá show se pouští v letních podvečerech za doprovodu hudby — časy si ověřte předem. Kamenné koryto a park kolem stojí za zastávku i mimo představení.', 61.1719, 28.7787, 'https://commons.wikimedia.org/wiki/Special:FilePath/Imatrankoski.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Imatrankoski.jpg"}'::text[], 1),
    (v_route, 'Imatran Valtionhotelli', 'Pohádkový secesní hotel z roku 1903 ve stylu hradu s věžičkami, postavený pro movité návštěvníky peřejí. I když nebudete nocovat, nahlédněte do haly a dejte si kávu na terase — patří k nejfotogeničtějším budovám Finska. Stojí přímo u peřejí Imatrankoski.', 61.1735, 28.7770, 'https://commons.wikimedia.org/wiki/Special:FilePath/Imatran%20valtionhotelli.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Imatran%20valtionhotelli.jpg"}'::text[], 2),
    (v_route, 'Kostel tří křížů (Vuoksenniska)', 'Mistrovské dílo Alvara Aalta z roku 1958 s asymetrickými bílými klenbami a 103 okny, z nichž žádná dvě nejsou stejná. Ikona moderní sakrální architektury, kterou jezdí obdivovat architekti z celého světa. Leží kousek od silnice 62 na severním okraji Imatry.', 61.2065, 28.7870, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kolmen%20ristin%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kolmen%20ristin%20kirkko.jpg"}'::text[], 3),
    (v_route, 'Most Puumalansalmi', 'Elegantní obloukový most klenoucí se vysoko nad úžinou Puumalansalmi, kudy proplouvají lodě mezi jižní a severní Saimaou. Z vyhlídkové plošiny je jeden z nejhezčích jezerních výhledů Finska. Městečko Puumala pod mostem žije v létě přístavem a je přirozenou pauzou v půlce okruhu.', 61.5262, 28.1762, 'https://commons.wikimedia.org/wiki/Special:FilePath/Puumalansalmen%20silta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puumalansalmen%20silta.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Sahanlahti (Puumala)', 'Oblíbený letní resort v zátoce staré pily kousek od Puumaly s restaurací zaměřenou na místní ryby ze Saimay a poctivou finskou kuchyni. Hosté chválí polohu přímo u vody i domácí dezerty. Ideální oběd před zpáteční jízdou po západním břehu přes Taipalsaari.', 61.5560, 28.2360, 'https://commons.wikimedia.org/wiki/Special:FilePath/Puumalansalmen%20silta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Puumalansalmen%20silta.jpg"}'::text[], 5);

  -- Punkaharju a hrad Olavinlinna
  delete from public.routes where name = 'Punkaharju a hrad Olavinlinna' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Punkaharju a hrad Olavinlinna', 'Kompaktní okruh srdcem Jezerního Finska kolem Savonlinny spojuje dva národní poklady: středověký vodní hrad Olavinlinna a hřeben Punkaharju, sedm kilometrů dlouhou písečnou šíji mezi jezery, po níž vede stará silnice považovaná za nejkrásnější kilometry Finska. Cestou navíc největší dřevěný kostel světa v Kerimäki a muzeum lesa Lusto. Silnice jsou klidné, vlnité a s výhledy na vodu prakticky pořád. Nejlépe v červnu až září; v červenci má Savonlinna operní festival na hradě a je plnější. Na hřebeni Punkaharju jeďte pomalu — úzká historická silnice se sdílí s cyklisty a chodci.', 'loop', 180, 240, 'easy',
     '[{"lat": 61.8681, "lng": 28.8862, "label": "Start: Savonlinna"}, {"lat": 61.9128, "lng": 29.2831, "label": "Kerimäki"}, {"lat": 61.8047, "lng": 29.3179, "label": "Lusto"}, {"lat": 61.7576, "lng": 29.3866, "label": "Punkaharju"}, {"lat": 61.7860, "lng": 28.3700, "label": "Sulkava"}, {"lat": 61.8681, "lng": 28.8862, "label": "Cíl: Savonlinna"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=61.8681,28.8862&destination=61.8681,28.8862&travelmode=driving&waypoints=61.9128,29.2831%7C61.8047,29.3179%7C61.7576,29.3866%7C61.7860,28.3700', 'https://commons.wikimedia.org/wiki/Special:FilePath/Olavinlinna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Olavinlinna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kerim%C3%A4en%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lusto.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Punkaharju.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Punkaharjun%20valtionhotelli.jpg"}'::text[], '{"Hrad Olavinlinna","Kostel v Kerimäki","Lusto – muzeum lesa","Hřeben Punkaharju","Restaurace: Hotelli Punkaharju"}'::text[], '{"FI"}'::text[], false, 3740, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Olavinlinna', 'Nejzachovalejší středověký hrad severní Evropy z roku 1475 stojí na skalnatém ostrůvku uprostřed jezerní úžiny a je symbolem celého Savonska. V létě hostí světoznámý operní festival, mimo představení se prochází věže a hradby s výhledy na Saimau. K hradu se jde po pontonovém mostě přímo z centra Savonlinny.', 61.8642, 28.9004, 'https://commons.wikimedia.org/wiki/Special:FilePath/Olavinlinna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Olavinlinna.jpg"}'::text[], 0),
    (v_route, 'Kostel v Kerimäki', 'Největší dřevěný kostel na světě: 45 metrů dlouhý, 27 metrů vysoký a s místem pro více než tři tisíce věřících. Postavili ho v roce 1847 a dodnes se vedou legendy o tom, zda za jeho rozměry nemůže záměna stop a metrů. Interiér z holého dřeva je nezapomenutelný.', 61.9128, 29.2831, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kerim%C3%A4en%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kerim%C3%A4en%20kirkko.jpg"}'::text[], 1),
    (v_route, 'Lusto – muzeum lesa', 'Národní muzeum lesa a lesnictví na kraji hřebene Punkaharju vypráví, proč je les duší Finska — od těžby dřeva po motorové pily a savotské sruby. Moderní expozice zaujme i nelesníky a kavárna je příjemnou pauzou. Odtud už začíná slavná hřebenová silnice.', 61.8047, 29.3179, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lusto.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lusto.jpg"}'::text[], 2),
    (v_route, 'Hřeben Punkaharju', 'Sedmikilometrová písečná šíje z doby ledové mezi jezery Puruvesi a Pihlajavesi, po níž vede historická silnička mezi staletými borovicemi — voda se leskne po obou stranách jen pár metrů od kol. Finové ji volí za svou národní krajinu a chránili ji už carové. Jeďte pomalu a zastavte na některé z vyhlídek.', 61.7623, 29.3777, 'https://commons.wikimedia.org/wiki/Special:FilePath/Punkaharju.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Punkaharju.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Hotelli Punkaharju', 'Nejstarší hotel Finska z roku 1845, bývalý carský lesnický dům přímo na hřebeni, dnes stylový podnik se špičkovou kuchyní z lokálních surovin — ryby z Puruvesi, houby a lesní plody. Terasa s výhledem na jezero je ideální na oběd. V sezóně doporučujeme rezervaci.', 61.7729, 29.3450, 'https://commons.wikimedia.org/wiki/Special:FilePath/Punkaharjun%20valtionhotelli.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Punkaharjun%20valtionhotelli.jpg"}'::text[], 4);

  -- Koli a jezero Pielinen
  delete from public.routes where name = 'Koli a jezero Pielinen' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Koli a jezero Pielinen', 'Velký okruh kolem jezera Pielinen v Severní Karélii s vrcholem na Ukko-Koli — nejslavnější vyhlídce Finska, která inspirovala Sibelia i národní malíře. Z Joensuu vede trasa na sever po západním břehu přes vrchy národního parku Koli, dál karelskou krajinou přes Juuku do Nurmesu a zpět po východním břehu přes Lieksu. Silnice 73 a 6 jsou rychlé a plynulé, okresky kolem Koli odmění zatáčkami a stoupáními, na finské poměry vzácnými. Nejlepší je červen až září, na podzim hoří listnaté stráně barvami. Pozor na losy a soby, na severu úseku i na štěrkové vjezdy k vyhlídkám.', 'loop', 330, 420, 'medium',
     '[{"lat": 62.6010, "lng": 29.7636, "label": "Start: Joensuu"}, {"lat": 63.0966, "lng": 29.8065, "label": "Koli"}, {"lat": 63.2420, "lng": 29.2520, "label": "Juuka"}, {"lat": 63.5420, "lng": 29.1390, "label": "Nurmes"}, {"lat": 63.3167, "lng": 30.0264, "label": "Lieksa"}, {"lat": 63.1547, "lng": 29.9862, "label": "Vuonislahti – Paateri"}, {"lat": 62.6010, "lng": 29.7636, "label": "Cíl: Joensuu"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=62.6010,29.7636&destination=62.6010,29.7636&travelmode=driving&waypoints=63.0966,29.8065%7C63.2420,29.2520%7C63.5420,29.1390%7C63.3167,30.0264%7C63.1547,29.9862', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ukko-Koli.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ukko-Koli.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Juuan%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bomban%20talo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pielisen%20museo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Paaterin%20kirkko.jpg"}'::text[], '{"Vyhlídka Ukko-Koli","Juuka","Restaurace: Bomban talo (Nurmes)","Lieksa – Pielisen museo","Paateri – ateliér Evy Ryynänen"}'::text[], '{"FI"}'::text[], false, 3750, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vyhlídka Ukko-Koli', 'Nejikoničtější výhled Finska: z bílých křemencových skal Ukko-Koli se otevírá panorama jezera Pielinen s ostrůvky až k obzoru, které maloval Gallen-Kallela a skládal podle něj Sibelius. Od horního parkoviště u hotelu je to na vrchol deset minut pěšky po chodníku. Ranní světlo a podzimní barvy jsou nejpůsobivější.', 63.0966, 29.8065, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ukko-Koli.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ukko-Koli.jpg"}'::text[], 0),
    (v_route, 'Juuka', 'Karelské městečko proslulé těžbou mastku a starou dřevěnou čtvrtí Puu-Juuka kolem kostela, kde řemeslníci dodnes drží tradiční živnosti. Příjemná krátká zastávka na kávu v půlce západního břehu. Odtud pokračuje silnice 6 svižně na sever do Nurmesu.', 63.2420, 29.2520, 'https://commons.wikimedia.org/wiki/Special:FilePath/Juuan%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Juuan%20kirkko.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Bomban talo (Nurmes)', 'Mohutný vyřezávaný karelský dům postavený podle statku z ruské Karélie, dnes vyhlášená restaurace s karelským bufetem — pirohy kalitt, pečené maso z pece a lesní plody. U jezera vedle stojí celá karelská vesnička a lázně. Nejlepší oběd na severní špici okruhu.', 63.5410, 29.1793, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bomban%20talo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bomban%20talo.jpg"}'::text[], 2),
    (v_route, 'Lieksa – Pielisen museo', 'Druhý největší skanzen Finska s takřka stovkou dřevěných staveb od kuřných chalup po savotské sruby dřevorubců vypráví o drsném životě na východní hranici. Leží u řeky přímo v Liekse na východním břehu Pielinen. Dobrá protahovací pauza na zpáteční cestě.', 63.3130, 30.0430, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pielisen%20museo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pielisen%20museo.jpg"}'::text[], 3),
    (v_route, 'Paateri – ateliér Evy Ryynänen', 'Lesní ateliér a dřevěný kostelík sochařky Evy Ryynänen ve Vuonislahti, celý vyřezaný z borového dřeva včetně oltáře z kořenů. Místo má zvláštní tichou atmosféru a patří k nejpůsobivějším zastávkám Severní Karélie. Ke kostelíku vede krátká odbočka po užší silničce.', 63.1547, 29.9862, 'https://commons.wikimedia.org/wiki/Special:FilePath/Paaterin%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Paaterin%20kirkko.jpg"}'::text[], 4);

  -- Hrady a ateliéry kraje Häme
  delete from public.routes where name = 'Hrady a ateliéry kraje Häme' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Hrady a ateliéry kraje Häme', 'Pohodový okruh nejstarší kulturní krajinou Finska kolem Hämeenlinny, po stopách středověké Volské cesty (Hämeen Härkätie). Cihlový hrad Häme, středověký kostel v Hattule s unikátními freskami, sklárna Iittala i ateliér sochaře Emila Wikströma na Visavuori — to vše spojují klidné okresky mezi jezery Vanajavesi a poli. Trasa je krátká a nenáročná, ideální na půlden s dlouhými zastávkami. Nejlépe od května do září. Pozor na hustší provoz u Hämeenlinny a na zpomalovací ostrůvky v obcích; jinak jde o čistý relax.', 'loop', 130, 210, 'easy',
     '[{"lat": 60.9959, "lng": 24.4643, "label": "Start: Hämeenlinna"}, {"lat": 61.0570, "lng": 24.3710, "label": "Hattula"}, {"lat": 61.0740, "lng": 24.1210, "label": "Iittala"}, {"lat": 61.1836, "lng": 24.0446, "label": "Visavuori"}, {"lat": 60.9760, "lng": 24.5760, "label": "Vanajanlinna"}, {"lat": 60.9959, "lng": 24.4643, "label": "Cíl: Hämeenlinna"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=60.9959,24.4643&destination=60.9959,24.4643&travelmode=driving&waypoints=61.0570,24.3710%7C61.0740,24.1210%7C61.1836,24.0446%7C60.9760,24.5760', 'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4meen%20linna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4meen%20linna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Aulangon%20n%C3%A4k%C3%B6torni.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hattulan%20Pyh%C3%A4n%20Ristin%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Iittalan%20lasitehdas.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Visavuori.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vanajanlinna.jpg"}'::text[], '{"Hrad Häme","Park a rozhledna Aulanko","Kostel svatého Kříže v Hattule","Sklárna Iittala","Visavuori – ateliér Emila Wikströma","Restaurace: Vanajanlinna"}'::text[], '{"FI"}'::text[], false, 3760, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Häme', 'Červený cihlový hrad ze 13. století na břehu jezera Vanajavesi, jeden ze tří středověkých královských hradů Finska. Švédové z něj spravovali celé vnitrozemí, později sloužil jako vězení. Prohlídka nádvoří a sálů zabere hodinku, kolem hradu je příjemné nábřeží.', 61.0039, 24.4620, 'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4meen%20linna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4meen%20linna.jpg"}'::text[], 0),
    (v_route, 'Park a rozhledna Aulanko', 'Anglický krajinářský park z přelomu století s žulovou rozhlednou, odkud se otevírá klasický pohled na lesnaté hřbety a jezero — další z finských národních krajin. Nahoru k věži vede úzká parková asfaltka. Ráno tu bývá liduprázdno a světlo na fotky nejlepší.', 61.0225, 24.4580, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aulangon%20n%C3%A4k%C3%B6torni.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aulangon%20n%C3%A4k%C3%B6torni.jpg"}'::text[], 1),
    (v_route, 'Kostel svatého Kříže v Hattule', 'Nejcennější středověký kostel Finska z cihel, jehož klenby pokrývá přes 180 dochovaných fresek z počátku 16. století — biblický komiks, který věřícím vyprávěl písmo. Otevřeno bývá v létě, mimo sezónu se dívejte aspoň zvenku. Stojí kousek od staré Volské cesty.', 61.0570, 24.3710, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hattulan%20Pyh%C3%A4n%20Ristin%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hattulan%20Pyh%C3%A4n%20Ristin%20kirkko.jpg"}'::text[], 2),
    (v_route, 'Sklárna Iittala', 'Vesnice, kde se od roku 1881 fouká nejslavnější finské sklo — vázy Alvara Aalta i skleničky, které zná celý svět. V hutní hale sledujete skláře při práci, vedle je muzeum a podnikový obchod s outletem. Povinná zastávka pro každého, kdo veze domů dárek.', 61.0740, 24.1210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Iittalan%20lasitehdas.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Iittalan%20lasitehdas.jpg"}'::text[], 3),
    (v_route, 'Visavuori – ateliér Emila Wikströma', 'Ateliér a vila sochaře Emila Wikströma na šíji mezi jezery u Sääksmäki, postavené v národně romantickém stylu s karelskými srubovými prvky. Sochy, sauna u vody a výhledy na Vanajavesi tvoří jedno z nejpůvabnějších uměleckých míst Finska. Cesta k němu vede přes elegantní most Sääksmäen silta.', 61.1836, 24.0446, 'https://commons.wikimedia.org/wiki/Special:FilePath/Visavuori.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Visavuori.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Vanajanlinna', 'Honosný lovecký zámek tabákového magnáta Rosenlewa z 20. let dnes slouží jako hotel s vyhlášenou restaurací — moderní severská kuchyně, zvěřina a vinný sklep patří k nejlepším v kraji. Zámek stojí v golfovém areálu u jezera kousek od Hämeenlinny. Skvělá tečka okruhu.', 60.9760, 24.5760, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vanajanlinna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vanajanlinna.jpg"}'::text[], 5);

  -- Pobřeží Pohjanmaa – Vaasa a Kvarken
  delete from public.routes where name = 'Pobřeží Pohjanmaa – Vaasa a Kvarken' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Pobřeží Pohjanmaa – Vaasa a Kvarken', 'Pobřežní jízda ze severské Vaasy do Kokkoly podél Botnického zálivu, krajem, kde se mluví švédsky a moře pomalu ustupuje zvedající se pevnině. Odbočka přes nejdelší most Finska na souostroví Kvarken (UNESCO) s rybářským přístavem Svedjehamn je vrcholem trasy. Dál se jede po staré pobřežní silnici 749 přes idylické Nykarleby a dřevěné čtvrti Jakobstadu a Kokkoly — rovinaté, plynulé, s vůní moře. Nejlepší je červen až srpen, kdy je souostroví plné světla dlouho do noci. Pozor na boční vítr na mostě a na srnky v pobřežních lesích.', 'poi', 230, 300, 'easy',
     '[{"lat": 63.0951, "lng": 21.6165, "label": "Start: Vaasa"}, {"lat": 63.2295, "lng": 21.4400, "label": "Replotský most"}, {"lat": 63.3560, "lng": 21.2210, "label": "Svedjehamn"}, {"lat": 63.5225, "lng": 22.5305, "label": "Nykarleby"}, {"lat": 63.6746, "lng": 22.7020, "label": "Jakobstad"}, {"lat": 63.8385, "lng": 23.1310, "label": "Cíl: Kokkola"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=63.0951,21.6165&destination=63.8385,23.1310&travelmode=driving&waypoints=63.2295,21.4400%7C63.3560,21.2210%7C63.5225,22.5305%7C63.6746,22.7020', 'https://commons.wikimedia.org/wiki/Special:FilePath/Raippaluodon%20silta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vaasan%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Raippaluodon%20silta.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svedjehamn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svedjehamn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nykarleby%20kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skata,%20Jakobstad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Neristan,%20Kokkola.jpg"}'::text[], '{"Vaasa","Replotský most","Svedjehamn a Kvarken (UNESCO)","Restaurace: Salteriet (Svedjehamn)","Nykarleby","Jakobstad – čtvrť Skata","Kokkola – Neristan"}'::text[], '{"FI"}'::text[], false, 3770, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vaasa', 'Slunečné přístavní město obnovené po požáru v empírovém stylu, dnes centrum dvojjazyčného pobřeží. Před startem stojí za to projet nábřežní promenádu a náměstí s kostelem. Odtud vede silnice 724 rovnou na sever k souostroví.', 63.0956, 21.6127, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaasan%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vaasan%20kirkko.jpg"}'::text[], 0),
    (v_route, 'Replotský most', 'Nejdelší most Finska (1045 m) elegantně překlenuje úžinu na ostrov Raippaluoto a je sám o sobě zážitkem — z vozovky vidíte mělké moře poseté kamennými ostrůvky. U mostu je vyhlídkové parkoviště a infocentrum Kvarkenu. Za silnějšího větru jeďte plynule a počítejte s poryvy.', 63.2295, 21.4400, 'https://commons.wikimedia.org/wiki/Special:FilePath/Raippaluodon%20silta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Raippaluodon%20silta.jpg"}'::text[], 1),
    (v_route, 'Svedjehamn a Kvarken (UNESCO)', 'Rybářský přístav v Björköby na konci ostrovní silničky, srdce souostroví Kvarken zapsaného na seznam UNESCO — pevnina se tu po době ledové stále zvedá téměř centimetr ročně a moře se mění v louky. Vystoupejte na vyhlídkovou věž Saltkaret nad valy morénových hřbetů. Jedno z nejzvláštnějších pobřeží Evropy.', 63.3560, 21.2210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svedjehamn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svedjehamn.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Salteriet (Svedjehamn)', 'Letní restaurace ve staré solírně sleďů přímo na molu ve Svedjehamnu, vyhlášená čerstvými rybami z Kvarkenu a domácími moučníky. Hosté milují polohu i atmosféru rybářské osady. Ideální oběd před návratem na pevninu — v sezóně bývá plno.', 63.3565, 21.2215, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svedjehamn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svedjehamn.jpg"}'::text[], 3),
    (v_route, 'Nykarleby', 'Půvabné švédskojazyčné městečko na řece s empírovým kostelem a dřevěnými domky, rodiště spisovatele Zachariase Topelia. Stará pobřežní silnice sem přivádí klidným tempem mezi poli a březovými alejemi. Příjemná krátká pauza na kávu.', 63.5225, 22.5305, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nykarleby%20kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nykarleby%20kyrka.jpg"}'::text[], 4),
    (v_route, 'Jakobstad – čtvrť Skata', 'Historická dřevěná čtvrť s třemi stovkami pestrobarevných domků námořníků a dělníků tabákové továrny, jedna z nejzachovalejších ve Finsku. Úzkými uličkami se projděte pěšky, motorku nechte u přístavu. Město založené na námořním obchodu dodnes staví plachetnice.', 63.6790, 22.7010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skata,%20Jakobstad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skata,%20Jakobstad.jpg"}'::text[], 5),
    (v_route, 'Kokkola – Neristan', 'Cíl trasy v Kokkole korunuje Neristan — Dolní město s mřížkou ulic plných dřevěných kupeckých domů ze 17. a 18. století. V anglickém parku u přístavu je vystavena dělová šalupa ukořistěná Britům v Krymské válce, jediná svého druhu. Kavárny v dřevěných domech jsou ideální tečkou.', 63.8385, 23.1310, 'https://commons.wikimedia.org/wiki/Special:FilePath/Neristan,%20Kokkola.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Neristan,%20Kokkola.jpg"}'::text[], 6);

  -- Kuusamo, Ruka a národní park Oulanka
  delete from public.routes where name = 'Kuusamo, Ruka a národní park Oulanka' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kuusamo, Ruka a národní park Oulanka', 'Severský okruh na dohled polárnímu kruhu: z Kuusama kolem lyžařské hory Ruka a dál k divokým řekám národního parku Oulanka, kde burácí vodopád Kiutaköngäs mezi rudými skalami. Silnice 5 a okresky ke Käylä a Juumě se vlní mezi kopci, jezery a hlubokou tajgou — na finské poměry nadprůměrně zábavné kilometry. V červnu a červenci se tu skoro nesetmí, na přelomu září bývá ruska — podzimní barvy, kvůli kterým sem Finové jezdí přes celou zemi. Pozor na soby na silnici, jsou tu doslova všude, a na štěrkové dojezdy k parkovištím v národním parku.', 'loop', 180, 270, 'medium',
     '[{"lat": 65.9646, "lng": 29.1886, "label": "Start: Kuusamo"}, {"lat": 66.1650, "lng": 29.1478, "label": "Ruka"}, {"lat": 66.3050, "lng": 29.0700, "label": "Käylä"}, {"lat": 66.3705, "lng": 29.3134, "label": "Kiutaköngäs"}, {"lat": 66.2565, "lng": 29.3222, "label": "Juuma"}, {"lat": 65.9646, "lng": 29.1886, "label": "Cíl: Kuusamo"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=65.9646,29.1886&destination=65.9646,29.1886&travelmode=driving&waypoints=66.1650,29.1478%7C66.3050,29.0700%7C66.3705,29.3134%7C66.2565,29.3222', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rukatunturi.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rukatunturi.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rukatunturi.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kiutak%C3%B6ng%C3%A4s.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Oulanka%20National%20Park.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Myllykoski%20Juuma.jpg"}'::text[], '{"Rukatunturi","Restaurace: Riipisen Riistaravintola (Ruka)","Vodopád Kiutaköngäs","Národní park Oulanka","Juuma a Myllykoski"}'::text[], '{"FI"}'::text[], false, 3780, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Rukatunturi', 'Nejznámější lyžařská hora východního Finska se v létě mění v tichý fjell s gondolou na vrchol a výhledy přes nekonečnou tajgu až do Ruska. Horská vesnice pod sjezdovkami žije i mimo zimu — kavárny, vyhlídky a startovní bod slavného treku Karhunkierros. Krátká odbočka ze silnice 5 stojí za to.', 66.1650, 29.1478, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rukatunturi.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rukatunturi.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Riipisen Riistaravintola (Ruka)', 'Legendární zvěřinová restaurace ve vesnici Ruka, kde ochutnáte medvěda, soba i sníh polárky — tedy speciality, které jinde v Evropě nenajdete. Sobí filet s brusinkami je klasika, hodnocení má podnik dlouhodobě vynikající. Ideální vydatný oběd před národním parkem.', 66.1656, 29.1490, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rukatunturi.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rukatunturi.jpg"}'::text[], 1),
    (v_route, 'Vodopád Kiutaköngäs', 'Nejfotografovanější místo parku Oulanka: řeka Oulankajoki se tu valí přes skalní práh mezi tmavě rudými dolomitovými stěnami. Od návštěvnického centra k vodopádu dojdete pohodlně za deset minut po rovné cestě. Hukot vody a barvy skal si zapamatujete nadlouho.', 66.3705, 29.3134, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kiutak%C3%B6ng%C3%A4s.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kiutak%C3%B6ng%C3%A4s.jpg"}'::text[], 2),
    (v_route, 'Národní park Oulanka', 'Divoké údolí řeky Oulankajoki s borovými lesy, písečnými břehy a visutými mosty patří k nejcennějším kouskům finské přírody a navazuje na ruský park Paanajärvi. Návštěvnické centrum u Kiutaköngäs nabízí expozici a kávu. Vede tudy i osmdesátikilometrový trek Karhunkierros — Medvědí stezka.', 66.3690, 29.3100, 'https://commons.wikimedia.org/wiki/Special:FilePath/Oulanka%20National%20Park.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oulanka%20National%20Park.jpg"}'::text[], 3),
    (v_route, 'Juuma a Myllykoski', 'Osada Juuma je bránou k Malému medvědímu okruhu (Pieni Karhunkierros): po pár stech metrech pěšky stojíte u starého mlýna na peřejích Myllykoski, jednoho z nejromantičtějších míst parku. Visuté mosty nad divokou vodou jsou zážitek i pro neturisty. K Juumě vede pěkná zvlněná silnička ze silnice 950.', 66.2565, 29.3222, 'https://commons.wikimedia.org/wiki/Special:FilePath/Myllykoski%20Juuma.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Myllykoski%20Juuma.jpg"}'::text[], 4);

  -- Údolí řeky Tornio – hranicí dvou zemí
  delete from public.routes where name = 'Údolí řeky Tornio – hranicí dvou zemí' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí řeky Tornio – hranicí dvou zemí', 'Okruh jižním Laponskem podél řeky Tornionjoki, která tvoří nejklidnější hranici světa: nahoru se jede po finském břehu po silnici 21 přes peřeje Kukkolankoski až k hoře Aavasaksa, zpět po švédském břehu po silnici 99 přes Övertorneå do Haparandy. Dvě země, dvě časová pásma a jedna řeka plná lososů — a v červnu půlnoční slunce, kvůli kterému se na Aavasaksu jezdí už od 19. století. Silnice jsou rovné a rychlé, provoz minimální, hraniční mosty se přejíždějí bez zastavení. Nejlepší je červen až srpen. Pozor na soby na finské straně a na měnící se limity po přejezdu do Švédska.', 'loop', 280, 330, 'easy',
     '[{"lat": 65.7360, "lng": 24.5637, "label": "Start: Kemi"}, {"lat": 65.8480, "lng": 24.1466, "label": "Tornio"}, {"lat": 65.9760, "lng": 24.0620, "label": "Kukkolankoski"}, {"lat": 66.3833, "lng": 23.7333, "label": "Aavasaksa"}, {"lat": 66.3880, "lng": 23.6520, "label": "Övertorneå (SE)"}, {"lat": 65.8355, "lng": 24.1180, "label": "Haparanda (SE)"}, {"lat": 65.7360, "lng": 24.5637, "label": "Cíl: Kemi"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=65.7360,24.5637&destination=65.7360,24.5637&travelmode=driving&waypoints=65.8480,24.1466%7C65.9760,24.0620%7C66.3833,23.7333%7C66.3880,23.6520%7C65.8355,24.1180', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kukkolankoski.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kemin%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tornion%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tornion%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kukkolankoski.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Aavasaksa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Haparanda%20kyrka.jpg"}'::text[], '{"Kemi","Dřevěný kostel v Torniu","Restaurace: Umpitunneli (Tornio)","Peřeje Kukkolankoski","Hora Aavasaksa","Haparanda"}'::text[], '{"FI","SE"}'::text[], false, 3790, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kemi', 'Přístavní město u Botnického zálivu, známé zimním sněhovým hradem a mohutným novogotickým kostelem, který dominuje panoramatu. V létě odtud vyplouvá ledoborec Sampo na vyhlídkové plavby. Praktický start okruhu s dobrým zázemím.', 65.7365, 24.5610, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kemin%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kemin%20kirkko.jpg"}'::text[], 0),
    (v_route, 'Dřevěný kostel v Torniu', 'Nejkrásnější dřevěný kostel finského severu z roku 1686 se šindelovou střechou a zvonicí přežil všechny války, které se přes hraniční město přehnaly. Tornio srostlé se švédskou Haparandou je kuriozita sama o sobě — hranici tu přecházíte uprostřed města. Zastavte i u pravoslavného kostelíku z dob cara.', 65.8455, 24.1520, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tornion%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tornion%20kirkko.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Umpitunneli (Tornio)', 'Pivovarská restaurace v centru Tornia navazující na zdejší pivní tradici — vaří se tu poctivá severská jídla k vlastnímu pivu a hodnocení patří k nejlepším ve městě. Sobí speciality a burgery jsou sázka na jistotu. Dobrý oběd před cestou na sever podél řeky.', 65.8470, 24.1440, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tornion%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tornion%20kirkko.jpg"}'::text[], 2),
    (v_route, 'Peřeje Kukkolankoski', 'Nejdelší volně tekoucí peřeje Finska, kde se už od středověku loví síhové do podběráků z dřevěných lávek nad divokou vodou. V létě tu rybáři úlovek rovnou grilují na otevřeném ohni — čerstvě uzený síh je místní pochoutka, kterou nikde jinde nedostanete. Peřeje jsou hned u silnice 21.', 65.9760, 24.0620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kukkolankoski.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kukkolankoski.jpg"}'::text[], 3),
    (v_route, 'Hora Aavasaksa', 'Legendární vyhlídková hora přímo na polárním kruhu, kam se od 19. století jezdí za půlnočním sluncem — kolem svatojánské noci tu slunce nezapadá vůbec. Na vrchol vede asfaltka, nahoře stojí císařský lovecký pavilon a výhled na údolí řeky do Švédska je fantastický. Patří k měřicím bodům Struveho oblouku (UNESCO).', 66.3833, 23.7333, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aavasaksa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aavasaksa.jpg"}'::text[], 4),
    (v_route, 'Haparanda', 'Švédské hraniční město srostlé s finským Torniem, kdysi jediná legální brána mezi Ruskem a Západem — za první světové války tudy proudili diplomaté, špioni i Lenin. Mohutný měděný kostel a nádraží s dvojím rozchodem kolejí připomínají zvláštní historii. Odtud je to po E4 zpět do Kemi chvilka.', 65.8355, 24.1080, 'https://commons.wikimedia.org/wiki/Special:FilePath/Haparanda%20kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Haparanda%20kyrka.jpg"}'::text[], 5);

  -- Päijänne a hřebenovka Pulkkilanharju
  delete from public.routes where name = 'Päijänne a hřebenovka Pulkkilanharju' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Päijänne a hřebenovka Pulkkilanharju', 'Okruh kolem jižní části jezera Päijänne, druhého největšího ve Finsku, s vrcholem na hřebeni Pulkkilanharju — úzké šíji z doby ledové, po níž silnice 314 přeskakuje z ostrůvku na ostrůvek mezi hladinami. Z Lahti se jede přes kanál Vääksy s nejrušnější plavební komorou země, dál po hřebeni na sever do Sysmä a zpět po západním břehu přes Padasjoki. Kombinace jezerních výhledů, plynulých zatáček a dřevěných kostelů je ideální jednodenní dávka Jezerního Finska. Nejlépe od května do září. Pozor na cyklisty na hřebenovce a hustší víkendový chatařský provoz kolem Lahti.', 'loop', 230, 300, 'easy',
     '[{"lat": 60.9827, "lng": 25.6612, "label": "Start: Lahti"}, {"lat": 61.1770, "lng": 25.5520, "label": "Vääksy"}, {"lat": 61.2790, "lng": 25.5220, "label": "Pulkkilanharju"}, {"lat": 61.5030, "lng": 25.6840, "label": "Sysmä"}, {"lat": 61.3500, "lng": 25.2790, "label": "Padasjoki"}, {"lat": 60.9827, "lng": 25.6612, "label": "Cíl: Lahti"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=60.9827,25.6612&destination=60.9827,25.6612&travelmode=driving&waypoints=61.1770,25.5520%7C61.2790,25.5220%7C61.5030,25.6840%7C61.3500,25.2790', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pulkkilanharju.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sibeliustalo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A4%C3%A4ksyn%20kanava.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A4%C3%A4ksyn%20kanava.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pulkkilanharju.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sysm%C3%A4n%20kirkko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Padasjoen%20kirkko.jpg"}'::text[], '{"Lahti – přístav a Sibeliova hala","Kanál Vääksy","Restaurace: Kanavan Panimo (Vääksy)","Pulkkilanharju","Sysmä","Padasjoki"}'::text[], '{"FI"}'::text[], false, 3800, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lahti – přístav a Sibeliova hala', 'Přístav v Lahti s dřevěnou koncertní halou Sibeliustalo, jednou z největších dřevostaveb Finska, je příjemným startem okruhu. Nad městem se tyčí trojice skokanských můstků — symbol města zimních sportů. Promenáda u jezera Vesijärvi zve na ranní kávu.', 60.9772, 25.6547, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sibeliustalo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sibeliustalo.jpg"}'::text[], 0),
    (v_route, 'Kanál Vääksy', 'Nejrušnější plavební kanál Finska spojuje jezera Vesijärvi a Päijänne uprostřed městečka Asikkala. V létě je radost sledovat, jak komorou proplouvají desítky lodí denně, kolem jsou kavárny, mlýn a muzeum. Klasická motorkářská zastávka na půl cesty k hřebenovce.', 61.1770, 25.5520, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A4%C3%A4ksyn%20kanava.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A4%C3%A4ksyn%20kanava.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Kanavan Panimo (Vääksy)', 'Malý řemeslný pivovar s restaurací ve starých mlýnských budovách přímo u kanálu Vääksy. Vaří tu oceňovaná piva a k nim poctivé jídlo, terasa nad vodou má skvělou atmosféru i hodnocení. Pro řidiče mají nealko speciály — ochutnávku piv si nechte na večer.', 61.1780, 25.5540, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A4%C3%A4ksyn%20kanava.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A4%C3%A4ksyn%20kanava.jpg"}'::text[], 2),
    (v_route, 'Pulkkilanharju', 'Osm kilometrů dlouhá šíje z doby ledové, po níž silnice 314 doslova tančí přes jezero Päijänne — voda z obou stran, borovice, mostky mezi ostrůvky a vyhlídka na každém kroku. Jeden z nejhezčích silničních úseků jižního Finska a ráj fotografů. Zastavte na odpočívadle uprostřed hřebene.', 61.2790, 25.5220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pulkkilanharju.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pulkkilanharju.jpg"}'::text[], 3),
    (v_route, 'Sysmä', 'Klidné městečko na severovýchodním břehu Päijänne se středověkým kamenným kostelem svatého Olafa z 15. století. V létě žije letními slavnostmi a knižním festivalem, u přístavu je pláž a kavárny. Nejsevernější bod okruhu — odtud se stáčíte po mostech přes úžiny na západní břeh.', 61.5030, 25.6840, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sysm%C3%A4n%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sysm%C3%A4n%20kirkko.jpg"}'::text[], 4),
    (v_route, 'Padasjoki', 'Obec na západním břehu Päijänne s přístavem, odkud vyplouvají lodě k ostrovům národního parku Päijänne včetně proslulé písečné kosy ostrova Kelvenne. Silnice 24 zpět do Lahti se vlní lesy podél jezera a nabízí poslední porci zatáček. Dobrá zastávka na zmrzlinu u přístavu.', 61.3500, 25.2790, 'https://commons.wikimedia.org/wiki/Special:FilePath/Padasjoen%20kirkko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Padasjoen%20kirkko.jpg"}'::text[], 5);

end $$;
