-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — ŠVÝCARSKO II (10 tras, sort 3310–3400)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Klausenpass a Pragelpass – srdce Švýcarska
  delete from public.routes where name = 'Klausenpass a Pragelpass – srdce Švýcarska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Klausenpass a Pragelpass – srdce Švýcarska', 'Okruh kolem dvou nejkrásnějších průsmyků centrálního Švýcarska, který začíná pod sochou Viléma Tella v Altdorfu. Klausenpass nabízí širokou, výborně asfaltovanou silnici s dlouhými serpentinami a výhledy na vodopády kolem náhorní pastviny Urnerboden. Pragelpass je jeho pravý opak — úzká jednoproudá horská cesta lesem a přes alpské louky, kde potkáš víc krav než aut. Pozor: glarská strana Pragelu je o víkendech pro motorová vozidla uzavřená, jeď proto ve všední den. Oba průsmyky bývají sjízdné zhruba od června do října; ráno počítej s chladem a vlhkými stíny v lese.', 'loop', 130, 240, 'hard',
     '[{"lat": 46.8805, "lng": 8.6440, "label": "Start: Altdorf"}, {"lat": 46.8676, "lng": 8.8558, "label": "Klausenpass"}, {"lat": 46.9217, "lng": 8.9976, "label": "Linthal"}, {"lat": 47.0404, "lng": 9.0679, "label": "Glarus"}, {"lat": 47.0244, "lng": 8.9760, "label": "Klöntalersee"}, {"lat": 46.9770, "lng": 8.8930, "label": "Pragelpass"}, {"lat": 47.0207, "lng": 8.6530, "label": "Schwyz"}, {"lat": 46.8805, "lng": 8.6440, "label": "Cíl: Altdorf"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.8805,8.6440&destination=46.8805,8.6440&travelmode=driving&waypoints=46.8676,8.8558%7C47.0404,9.0679%7C46.9770,8.8930%7C47.0207,8.6530', 'https://commons.wikimedia.org/wiki/Special:FilePath/Telldenkmal%20Altdorf.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Telldenkmal%20Altdorf.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Klausenpass%2C%20Uri%2C%20Switzerland.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Urnerboden2.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Glarus%20Panorama.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%B6ntalersee%20in%20der%20Gemeinde%20Glarus%2C%20Kanton%20Glarus%20-%2019309679699.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pragelpass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schwyz%20Hauptplatz%20mit%20Rathaus.JPG"}'::text[], '{"Altdorf – Telldenkmal","Klausenpass","Urnerboden","Glarus","Klöntalersee","Pragelpass","Schwyz – Hauptplatz"}'::text[], '{"CH"}'::text[], false, 3310, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Altdorf – Telldenkmal', 'Hlavní město kantonu Uri s legendárním pomníkem Viléma Tella na náměstí — právě tady měl podle pověsti sestřelit jablko z hlavy svého syna. Ideální místo na kávu před stoupáním na Klausen.', 46.8805, 8.6440, 'https://commons.wikimedia.org/wiki/Special:FilePath/Telldenkmal%20Altdorf.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Telldenkmal%20Altdorf.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Telldenkmal%20Altdorf%2001%2011.jpg"}'::text[], 0),
    (v_route, 'Klausenpass', 'Průsmyk ve výšce 1 948 m s jedním z nejplynulejších stoupání v Alpách — široké zatáčky, dobrý asfalt a výhledy na štíty Glarnských Alp. Na vrcholu stojí horský hotel s terasou přímo u silnice.', 46.8676, 8.8558, 'https://commons.wikimedia.org/wiki/Special:FilePath/Klausenpass%2C%20Uri%2C%20Switzerland.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Klausenpass%2C%20Uri%2C%20Switzerland.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Uri-Glarus%20Klausenpass%2009.JPG"}'::text[], 1),
    (v_route, 'Urnerboden', 'Největší alpská pastvina Švýcarska — kilometry dlouhá náhorní louka mezi skalními stěnami, po které se silnice line jako podle pravítka. V létě tu žije přes tisíc krav a čas tu plyne pomaleji.', 46.8890, 8.9130, 'https://commons.wikimedia.org/wiki/Special:FilePath/Urnerboden2.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Urnerboden2.jpg"}'::text[], 2),
    (v_route, 'Glarus', 'Kantonální metropole sevřená horami, známá tím, že o zákonech tu dodnes hlasují občané zvednutím ruky na náměstí. Hezká zastávka na doplnění paliva i energie před Pragelem.', 47.0404, 9.0679, 'https://commons.wikimedia.org/wiki/Special:FilePath/Glarus%20Panorama.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Glarus%20Panorama.jpg"}'::text[], 3),
    (v_route, 'Klöntalersee', 'Tyrkysové jezero v hlubokém údolí pod stěnou Glärnische — jedno z nejfotogeničtějších míst kantonu Glarus. Silnice vede přímo po břehu a láká k zastávce na koupání či piknik.', 47.0244, 8.9760, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%B6ntalersee%20in%20der%20Gemeinde%20Glarus%2C%20Kanton%20Glarus%20-%2019309679699.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%B6ntalersee%20in%20der%20Gemeinde%20Glarus%2C%20Kanton%20Glarus%20-%2019309679699.jpg"}'::text[], 4),
    (v_route, 'Pragelpass', 'Úzký, divoký průsmyk (1 550 m) mezi Klöntalem a Muotathalem — jednoproudá silnička, výhybny a naprosté ticho. O víkendech je glarská strana pro motorová vozidla uzavřena, ve všední den je to ale motorkářský klenot.', 46.9770, 8.8930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pragelpass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pragelpass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pragel03.jpg"}'::text[], 5),
    (v_route, 'Schwyz – Hauptplatz', 'Městečko, které dalo Švýcarsku jméno. Barokní náměstí s radnicí zdobenou freskami z bitvy u Morgartenu je důstojná tečka za okruhem — kavárny s výhledem na štíty Mythen.', 47.0207, 8.6530, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schwyz%20Hauptplatz%20mit%20Rathaus.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schwyz%20Hauptplatz%20mit%20Rathaus.JPG"}'::text[], 6);

  -- Albula a Julier – graubündenský okruh
  delete from public.routes where name = 'Albula a Julier – graubündenský okruh' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Albula a Julier – graubündenský okruh', 'Elegantní okruh horním Engadinem přes dva průsmyky, které se skvěle doplňují: Julier je rychlý a otevřený, Albula úzká,技 technická a romantická. Cestou projedeš kolem jezer u Silvaplany, mondénního St. Moritz i vesničky Bergün s rhétorománskými domy. Silnice kopíruje trať slavné Albulské dráhy (UNESCO), takže serpentiny střídají pohledy na viadukty a kroužící vlaky — vrcholem je Landwasserviadukt. Asfalt je vesměs výborný, provoz mimo špičku mírný. Nejlepší období je červen až říjen; Albula se na zimu uzavírá a brzy ráno tu bývá pod nulou i v létě.', 'loop', 115, 195, 'medium',
     '[{"lat": 46.6600, "lng": 9.5789, "label": "Start: Tiefencastel"}, {"lat": 46.4718, "lng": 9.7292, "label": "Julierpass"}, {"lat": 46.4908, "lng": 9.8355, "label": "St. Moritz"}, {"lat": 46.5789, "lng": 9.9250, "label": "La Punt"}, {"lat": 46.5837, "lng": 9.8390, "label": "Albulapass"}, {"lat": 46.6297, "lng": 9.7466, "label": "Bergün"}, {"lat": 46.6748, "lng": 9.6884, "label": "Filisur"}, {"lat": 46.6600, "lng": 9.5789, "label": "Cíl: Tiefencastel"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.6600,9.5789&destination=46.6600,9.5789&travelmode=driving&waypoints=46.4718,9.7292%7C46.4908,9.8355%7C46.5837,9.8390%7C46.6297,9.7466', 'https://commons.wikimedia.org/wiki/Special:FilePath/Julia%20Julierpass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Julia%20Julierpass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Silvaplanersee.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lake%20St.%20Moritz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Albulapass%20In%20Switzerland%20(110510259).jpeg","https://commons.wikimedia.org/wiki/Special:FilePath/Palpuognasee%20(Albulapass).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kurhaus%20Berg%C3%BCn%20S%C3%BCdseite2.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Landwasserviadukt.jpg"}'::text[], '{"Julierpass","Silvaplanersee","St. Moritz","Albulapass","Palpuognasee","Bergün a Kurhaus","Landwasserviadukt"}'::text[], '{"CH"}'::text[], false, 3320, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Julierpass', 'Průsmyk (2 284 m) po stopách římské obchodní cesty — u silnice dodnes stojí zbytky římských sloupů. Otevřený, přehledný a rychlý; jedna z mála alpských silnic udržovaných celoročně.', 46.4718, 9.7292, 'https://commons.wikimedia.org/wiki/Special:FilePath/Julia%20Julierpass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Julia%20Julierpass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Julierpass%2C%20Switzerland%20(6011000466).jpg"}'::text[], 0),
    (v_route, 'Silvaplanersee', 'Smaragdové jezero pod sjezdem z Julieru, ráj kitesurfařů díky spolehlivému malojskému větru. Krátká fotopauza s Piz Corvatsch v pozadí stojí za to.', 46.4500, 9.7900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Silvaplanersee.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Silvaplanersee.jpg"}'::text[], 1),
    (v_route, 'St. Moritz', 'Nejslavnější alpské lázně světa u jezera ve výšce 1 800 m — dvakrát hostily zimní olympiádu. Projížďka po promenádě mezi luxusními hotely je zážitek sám o sobě, espresso tu ale chutná stejně jako jinde.', 46.4908, 9.8355, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lake%20St.%20Moritz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lake%20St.%20Moritz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lake%20St.%20Moritz%20and%20St.%20Moritz%20town%20in%20Switzerland.jpg"}'::text[], 2),
    (v_route, 'Albulapass', 'Tišší a divočejší soused Julieru (2 312 m): úzká silnice mezi žulovými balvany, minimum svodidel a technické pasáže, které si vychutná každý, kdo má rád práci s řídítky. Sjízdný zhruba od června do konce října.', 46.5837, 9.8390, 'https://commons.wikimedia.org/wiki/Special:FilePath/Albulapass%20In%20Switzerland%20(110510259).jpeg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Albulapass%20In%20Switzerland%20(110510259).jpeg"}'::text[], 3),
    (v_route, 'Palpuognasee', 'Drobné horské jezírko u Predy, vyhlášené v celošvýcarské anketě nejkrásnějším místem země. Od parkoviště je to k vodě pár minut pěšky — dokonalá svačinová zastávka.', 46.5946, 9.8083, 'https://commons.wikimedia.org/wiki/Special:FilePath/Palpuognasee%20(Albulapass).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palpuognasee%20(Albulapass).jpg"}'::text[], 4),
    (v_route, 'Bergün a Kurhaus', 'Vesnice jako z pohlednice: sgrafitové engadinské domy a secesní Kurhaus z roku 1906, kde se v historické jídelně dobře naobědváš. Bergün je také zastávkou slavné Albulské dráhy.', 46.6297, 9.7466, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kurhaus%20Berg%C3%BCn%20S%C3%BCdseite2.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kurhaus%20Berg%C3%BCn%20S%C3%BCdseite2.JPG"}'::text[], 5),
    (v_route, 'Landwasserviadukt', 'Ikona švýcarských železnic — 65 m vysoký zakřivený viadukt, po němž vlaky mizí přímo do tunelu ve skále. Vyhlídka je kousek od silnice u Filisuru; s trochou štěstí chytíš projíždějící červený vlak Rhétské dráhy.', 46.6805, 9.6764, 'https://commons.wikimedia.org/wiki/Special:FilePath/Landwasserviadukt.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Landwasserviadukt.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/RhB%20Ge%204-4%20III%20UNESCO%20Weltkulturerbe%20auf%20Landwasserviadukt%20showing%20the%20tunnel.jpg"}'::text[], 6);

  -- Ticino – Verzasca, Locarno a Val Bavona
  delete from public.routes where name = 'Ticino – Verzasca, Locarno a Val Bavona' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Ticino – Verzasca, Locarno a Val Bavona', 'Itálie se švýcarskou precizností: palmy, žulové vesničky a smaragdová řeka Verzasca. Z Bellinzony s třemi hrady UNESCO vyjedeš na hráz přehrady Verzasca, z níž skákal James Bond, a pokračuješ úzkým údolím ke kamennému mostu v Lavertezzu. Po kávě na Piazza Grande v Locarnu tě čeká divoká Val Bavona s vodopádem Foroglio a závěr na promenádě v Asconě. Silnice v údolích jsou úzké a o летních víkendech plné — vyjeď brzy ráno. Sezóna je tu dlouhá, od dubna do listopadu; v létě počítej s vedrem na jihu a chladem v horních patrech údolí.', 'poi', 150, 270, 'medium',
     '[{"lat": 46.1927, "lng": 9.0170, "label": "Start: Bellinzona"}, {"lat": 46.1830, "lng": 8.8430, "label": "Přehrada Verzasca"}, {"lat": 46.2578, "lng": 8.8377, "label": "Lavertezzo"}, {"lat": 46.1670, "lng": 8.7943, "label": "Locarno"}, {"lat": 46.3747, "lng": 8.5940, "label": "Foroglio"}, {"lat": 46.1550, "lng": 8.7695, "label": "Cíl: Ascona"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.1927,9.0170&destination=46.1550,8.7695&travelmode=driving&waypoints=46.1830,8.8430%7C46.2578,8.8377%7C46.1670,8.7943%7C46.3747,8.5940', 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelgrande%20Bellinzona.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelgrande%20Bellinzona.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Valle%20Verzasca%20Staumauer.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ponte%20dei%20Salti%2C%20Lavertezzo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Piazza%20Grande%20Locarno.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Foroglio%20im%20Val%20Bavona.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ascona%20Lago%20Maggiore.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ascona%20Promenade.jpg"}'::text[], '{"Bellinzona – Castelgrande","Přehrada Verzasca","Lavertezzo – Ponte dei Salti","Locarno – Piazza Grande","Vodopád Foroglio","Ascona","Restaurace: Osteria Nostrana (Ascona)"}'::text[], '{"CH"}'::text[], false, 3330, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Bellinzona – Castelgrande', 'Trojice středověkých hradů na seznamu UNESCO střeží vstup do Ticina; Castelgrande se tyčí přímo nad starým městem. Výjezd k hradbám nabídne první výhled na kraj, kterým pojedeš celý den.', 46.1927, 9.0170, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelgrande%20Bellinzona.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelgrande%20Bellinzona.JPG"}'::text[], 0),
    (v_route, 'Přehrada Verzasca', '220 m vysoká hráz, z níž v úvodu filmu GoldenEye skočil James Bond — dodnes tu funguje jeden z nejvyšších bungee jumpů světa. Přejezd po koruně hráze s pohledem do hlubiny bere dech.', 46.1830, 8.8430, 'https://commons.wikimedia.org/wiki/Special:FilePath/Valle%20Verzasca%20Staumauer.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Valle%20Verzasca%20Staumauer.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Verzasca%20Bungee.JPG"}'::text[], 1),
    (v_route, 'Lavertezzo – Ponte dei Salti', 'Dvojobloukový kamenný most ze 17. století nad smaragdovými tůněmi řeky Verzascy. V létě sem místní chodí skákat do křišťálové vody; brzy ráno budeš mít tohle kouzelné místo skoro pro sebe.', 46.2578, 8.8377, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ponte%20dei%20Salti%2C%20Lavertezzo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ponte%20dei%20Salti%2C%20Lavertezzo.jpg"}'::text[], 2),
    (v_route, 'Locarno – Piazza Grande', 'Srdce města u Lago Maggiore, dlážděné náměstí lemované podloubími, kde se každé léto koná slavný filmový festival pod širým nebem. Ideální na espresso a gelato v půlce dne.', 46.1670, 8.7943, 'https://commons.wikimedia.org/wiki/Special:FilePath/Piazza%20Grande%20Locarno.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piazza%20Grande%20Locarno.jpg"}'::text[], 3),
    (v_route, 'Vodopád Foroglio', 'Nejfotografovanější vodopád Ticina padá 110 metrů přímo za kamennou vesničkou ve Val Bavoně — údolí bez elektrické sítě, kde se čas zastavil. Úzká silnička údolím je zážitek sama o sobě.', 46.3747, 8.5940, 'https://commons.wikimedia.org/wiki/Special:FilePath/Foroglio%20im%20Val%20Bavona.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Foroglio%20im%20Val%20Bavona.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cascata%20del%20fiume%20Caln%C3%A8gia%20a%20Foroglio%20(Val%20Bavona).jpg"}'::text[], 4),
    (v_route, 'Ascona', 'Nejníže položené město Švýcarska s pastelovou promenádou u Lago Maggiore — palmami lemované molo, výhled na ostrovy Brissago a středomořská nálada na rozloučenou s jihem.', 46.1550, 8.7695, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ascona%20Lago%20Maggiore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ascona%20Lago%20Maggiore.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Osteria Nostrana (Ascona)', 'Oblíbená osteria přímo na asconské promenádě: domácí těstoviny, pizza z pece a ticinská polenta s výhledem na jezero. Večer bývá plno, ale fronta odsýpá rychle.', 46.1543, 8.7690, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ascona%20Promenade.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ascona%20Promenade.jpg"}'::text[], 6);

  -- Švýcarská Jura – Creux du Van a údolí Doubs
  delete from public.routes where name = 'Švýcarská Jura – Creux du Van a údolí Doubs' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švýcarská Jura – Creux du Van a údolí Doubs', 'Úplně jiné Švýcarsko: místo ledovců zvlněné hřebeny Jury, hluboké lesy, pastviny s koňmi a silnice s plynulými zatáčkami skoro bez provozu. Od jezera v Neuchâtelu vystoupáš na Vue des Alpes s panoramatem od Mont Blancu po Eiger, projedeš hodinářskou metropolí La Chaux-de-Fonds a podél hranice s Francií sjedeš k vodopádu Saut du Doubs. Zpáteční cesta vede údolím Val-de-Travers, kolébkou absintu, a končí u skalního amfiteátru Creux du Van. Trasa je ideální na jaře a na podzim, kdy jsou Alpy ještě pod sněhem. Pozor na ranní mlhy a zvěř v lesních úsecích.', 'loop', 155, 250, 'medium',
     '[{"lat": 46.9900, "lng": 6.9293, "label": "Start: Neuchâtel"}, {"lat": 47.0797, "lng": 6.8756, "label": "Vue des Alpes"}, {"lat": 47.1035, "lng": 6.8328, "label": "La Chaux-de-Fonds"}, {"lat": 47.0692, "lng": 6.7108, "label": "Les Brenets"}, {"lat": 46.9130, "lng": 6.6132, "label": "Môtiers"}, {"lat": 46.9560, "lng": 6.7240, "label": "Noiraigue"}, {"lat": 46.9900, "lng": 6.9293, "label": "Cíl: Neuchâtel"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.9900,6.9293&destination=46.9900,6.9293&travelmode=driving&waypoints=47.0797,6.8756%7C47.1035,6.8328%7C47.0692,6.7108%7C46.9130,6.6132%7C46.9560,6.7240', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Neuch%C3%A2tel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Neuch%C3%A2tel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/La%20vue%20des%20alpes%20suisse.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/La%20Chaux-de-Fonds.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bateaux%20du%20saut%20du%20Doubs%20Odyss%C3%A9e.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Motiers.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/2007-08-31%20Creux%20du%20Van%2002.jpg"}'::text[], '{"Neuchâtel – zámek","Col de la Vue des Alpes","La Chaux-de-Fonds","Saut du Doubs","Môtiers – domov absintu","Creux du Van"}'::text[], '{"CH"}'::text[], false, 3340, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Neuchâtel – zámek', 'Město ze žlutého pískovce nad jezerem, kterému vévodí středověký zámek a kolegiátní kostel. Ranní projížďka po nábřeží s výhledem na Alpy na protějším břehu je skvělý start dne.', 46.9900, 6.9293, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Neuch%C3%A2tel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Neuch%C3%A2tel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Coll%C3%A9giale%20de%20Neuch%C3%A2tel.JPG"}'::text[], 0),
    (v_route, 'Col de la Vue des Alpes', 'Průsmyk s vypovídajícím jménem: za jasného dne odsud přehlédneš celý alpský oblouk od Mont Blancu po Bernské Alpy. Stoupání od Neuchâtelu je široké a rytmické — oblíbený úsek místních motorkářů.', 47.0797, 6.8756, 'https://commons.wikimedia.org/wiki/Special:FilePath/La%20vue%20des%20alpes%20suisse.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/La%20vue%20des%20alpes%20suisse.JPG"}'::text[], 1),
    (v_route, 'La Chaux-de-Fonds', 'Hodinářská metropole s šachovnicovým urbanismem na seznamu UNESCO — rodiště Le Corbusiera i značek jako Omega či TAG Heuer. Milovníci strojků by neměli minout Mezinárodní hodinářské muzeum.', 47.1035, 6.8328, 'https://commons.wikimedia.org/wiki/Special:FilePath/La%20Chaux-de-Fonds.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/La%20Chaux-de-Fonds.jpg"}'::text[], 2),
    (v_route, 'Saut du Doubs', '27 metrů vysoký vodopád na hraniční řece Doubs, k němuž se od Les Brenets dojde procházkou podél jezera Lac des Brenets nebo doplutím na vyhlídkové lodi. Osvěžující pauza uprostřed lesů.', 47.0793, 6.6947, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bateaux%20du%20saut%20du%20Doubs%20Odyss%C3%A9e.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bateaux%20du%20saut%20du%20Doubs%20Odyss%C3%A9e.JPG"}'::text[], 3),
    (v_route, 'Môtiers – domov absintu', 'Vesnice ve Val-de-Travers, kde se zrodila zelená víla — absint se tu po století pálil tajně a dnes ho ochutnáš legálně v Maison de l''Absinthe. Řidič degustaci samozřejmě odloží na večer.', 46.9130, 6.6132, 'https://commons.wikimedia.org/wiki/Special:FilePath/Motiers.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Motiers.jpg"}'::text[], 4),
    (v_route, 'Creux du Van', 'Obří skalní amfiteátr — vápencová stěna dlouhá čtyři kilometry a hluboká 160 metrů, kterou vymodeloval ledovec. Od parkoviště nad Noiraigue je to k hraně krátká procházka; na skalách žijí kozorožci.', 46.9333, 6.7290, 'https://commons.wikimedia.org/wiki/Special:FilePath/2007-08-31%20Creux%20du%20Van%2002.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/2007-08-31%20Creux%20du%20Van%2002.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bouquetin-creux-du-van.jpg"}'::text[], 5);

  -- Emmental – kraj sýra a serpentin
  delete from public.routes where name = 'Emmental – kraj sýra a serpentin' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Emmental – kraj sýra a serpentin', 'Pohodová projížďka krajinou jak z reklamy na čokoládu: zelené kopce, mohutné selské statky s pelargóniemi a silničky, které se vlní od údolí k údolí. Z Burgdorfu se stavíš v ukázkové sýrárně v Affoltern, vystoupáš na vyhlídkovou Lüderenalp a přes sušenkové Trubschachen dojedeš k legendárním pusinkám v Kemmeriboden-Bad. Zpět tě vrátí Schallenbergpass — nejoblíbenější motorkářský kopec bernského kraje s vlastní vyhlášenou zatáčkovou rytmikou. Trasa je nenáročná a krásná od jara do podzimu; o víkendech počítej u Schallenbergu s větším počtem jednostopých kolegů.', 'loop', 125, 210, 'easy',
     '[{"lat": 47.0570, "lng": 7.6280, "label": "Start: Burgdorf"}, {"lat": 47.0620, "lng": 7.7350, "label": "Affoltern im Emmental"}, {"lat": 46.9940, "lng": 7.8080, "label": "Lüderenalp"}, {"lat": 46.9220, "lng": 7.8460, "label": "Trubschachen"}, {"lat": 46.7797, "lng": 7.9075, "label": "Kemmeriboden"}, {"lat": 46.8253, "lng": 7.7900, "label": "Schallenbergpass"}, {"lat": 47.0570, "lng": 7.6280, "label": "Cíl: Burgdorf"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.0570,7.6280&destination=47.0570,7.6280&travelmode=driving&waypoints=47.0620,7.7350%7C46.9220,7.8460%7C46.7797,7.9075%7C46.8253,7.7900', 'https://commons.wikimedia.org/wiki/Special:FilePath/Burgdorf%20Schloss%20im%20Abendlicht.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Burgdorf%20Schloss%20im%20Abendlicht.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Affoltern%20im%20Emmental.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bauernhof%20auf%20L%C3%BCderenalp%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Trubschachen-Kambly.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kemmeriboden-Bad%2C%20Meringue%2001%2011.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schallenberg%20Pass%2C%201160%20M%2C%20at%20Eggiwil%20-%20panoramio.jpg"}'::text[], '{"Hrad Burgdorf","Emmentaler Schaukäserei (Affoltern)","Lüderenalp","Trubschachen – Kambly","Restaurace: Kemmeriboden-Bad (Schangnau)","Schallenbergpass"}'::text[], '{"CH"}'::text[], false, 3350, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Burgdorf', 'Mohutný hrad Zähringenů z 12. století nad branou do Emmentalu — dnes muzeum a kavárna s výhledem na střechy starého města. Dobré místo na první kafe okruhu.', 47.0570, 7.6280, 'https://commons.wikimedia.org/wiki/Special:FilePath/Burgdorf%20Schloss%20im%20Abendlicht.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Burgdorf%20Schloss%20im%20Abendlicht.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Altstadt%20Burgdorf%20BE.jpg"}'::text[], 0),
    (v_route, 'Emmentaler Schaukäserei (Affoltern)', 'Ukázková sýrárna, kde se přímo před tebou vyrábí pravý ementál — včetně dozrávacího sklepa s bochníky velkými jako kolo od traktoru. Degustace a obchod se sýrem na cestu jsou samozřejmost.', 47.0620, 7.7350, 'https://commons.wikimedia.org/wiki/Special:FilePath/Affoltern%20im%20Emmental.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Affoltern%20im%20Emmental.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Emmentaler.jpg"}'::text[], 1),
    (v_route, 'Lüderenalp', 'Vyhlídkové sedlo na hřebeni mezi údolími: za dobré viditelnosti se odsud rozprostírá celý řetěz Bernských Alp od Eigeru po Jungfrau. Serpentiny nahoru patří k nejhezčím v Emmentalu.', 46.9940, 7.8080, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bauernhof%20auf%20L%C3%BCderenalp%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bauernhof%20auf%20L%C3%BCderenalp%20-%20panoramio.jpg"}'::text[], 2),
    (v_route, 'Trubschachen – Kambly', 'Vesnice, kterou proslavily máslové sušenky Kambly — v podnikové prodejně se ochutnává zdarma a vybírá z desítek druhů. Ideální doplnění zásob do kufru.', 46.9220, 7.8460, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trubschachen-Kambly.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trubschachen-Kambly.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Kemmeriboden-Bad (Schangnau)', 'Historický zájezdní hostinec na konci údolí Emme, vyhlášený obřími pusinkami „Merängge" se šlehačkou — jezdí se sem na ně z celého Švýcarska. Vydatná kuchyně a zahrada u řeky.', 46.7797, 7.9075, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kemmeriboden-Bad%2C%20Meringue%2001%2011.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kemmeriboden-Bad%2C%20Meringue%2001%2011.jpg"}'::text[], 4),
    (v_route, 'Schallenbergpass', 'Nevysoký (1 167 m), ale zábavný průsmyk s perfektním asfaltem a rychlým sledem zatáček — víkendový sraz bernských motorkářů s kioskem na vrcholu. Poslední porce serpentin před návratem do Burgdorfu.', 46.8253, 7.7900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schallenberg%20Pass%2C%201160%20M%2C%20at%20Eggiwil%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schallenberg%20Pass%2C%201160%20M%2C%20at%20Eggiwil%20-%20panoramio.jpg"}'::text[], 5);

  -- Appenzell a Säntis
  delete from public.routes where name = 'Appenzell a Säntis' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Appenzell a Säntis', 'Krátký, ale vydatný okruh nejmalebnějším koutem východního Švýcarska. Od barokní klášterní knihovny v St. Gallenu (UNESCO) se silnice vlní pastvinami Appenzellerlandu k malovaným fasádám městečka Appenzell a dál pod zubaté štíty Alpsteinu. Z Wasserauen vyjíždí lanovka na Ebenalp ke slavné hospůdce Äscher přilepené ke skále, ze Schwägalp zase kabina přímo na vrchol Säntisu. Silnice jsou úzké, zvlněné a plné krátkých zatáček — žádné vysoké průsmyky, zato nekonečná rytmika. Jezdit se dá od jara do podzimu; o slunečných víkendech je u Schwägalp živo.', 'loop', 95, 170, 'easy',
     '[{"lat": 47.4239, "lng": 9.3748, "label": "Start: St. Gallen"}, {"lat": 47.3306, "lng": 9.4088, "label": "Appenzell"}, {"lat": 47.2860, "lng": 9.4270, "label": "Wasserauen"}, {"lat": 47.2545, "lng": 9.3170, "label": "Schwägalp"}, {"lat": 47.3170, "lng": 9.2790, "label": "Urnäsch"}, {"lat": 47.4239, "lng": 9.3748, "label": "Cíl: St. Gallen"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.4239,9.3748&destination=47.4239,9.3748&travelmode=driving&waypoints=47.3306,9.4088%7C47.2860,9.4270%7C47.2545,9.3170%7C47.3170,9.2790', 'https://commons.wikimedia.org/wiki/Special:FilePath/Stiftsbibliothek%20St.%20Gallen-Bibliothekssaal-13.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stiftsbibliothek%20St.%20Gallen-Bibliothekssaal-13.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hauptgasse%20Appenzell.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Seealpsee%20in%20Appenzell.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Berggasthaus%20Aescher-Wildkirchli.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A4ntis-Swiss.JPG"}'::text[], '{"St. Gallen – klášterní knihovna","Appenzell – Hauptgasse","Seealpsee a Wasserauen","Restaurace: Berggasthaus Äscher (Ebenalp)","Schwägalp a Säntis"}'::text[], '{"CH"}'::text[], false, 3360, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'St. Gallen – klášterní knihovna', 'Rokoková klášterní knihovna s 170 000 svazky patří k nejkrásnějším sálům světa a celý klášterní okrsek je na seznamu UNESCO. Nad vstupem stojí řecky „lékárna duše" — a opravdu funguje.', 47.4239, 9.3748, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stiftsbibliothek%20St.%20Gallen-Bibliothekssaal-13.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stiftsbibliothek%20St.%20Gallen-Bibliothekssaal-13.jpg"}'::text[], 0),
    (v_route, 'Appenzell – Hauptgasse', 'Hlavní ulice plná ručně malovaných fasád, řeznictví s appenzellskou klobásou a cukráren s medovým perníkem Biber. Městečko, kde se o zákonech dodnes hlasuje na náměstí zvednutím ruky.', 47.3306, 9.4088, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hauptgasse%20Appenzell.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hauptgasse%20Appenzell.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Appenzell-Hauptgasse.jpg"}'::text[], 1),
    (v_route, 'Seealpsee a Wasserauen', 'Z konečné ve Wasserauen vede hodinová procházka k horskému jezeru Seealpsee, v jehož hladině se zrcadlí štíty Alpsteinu. Kdo nechce šlapat, dá si aspoň limonádu u dolní stanice lanovky.', 47.2860, 9.4270, 'https://commons.wikimedia.org/wiki/Special:FilePath/Seealpsee%20in%20Appenzell.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Seealpsee%20in%20Appenzell.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Seealpsee%20autumn.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Berggasthaus Äscher (Ebenalp)', 'Legendární horská hospoda přilepená 170 let ke skalní stěně pod Ebenalp — proslavila ji obálka průvodce National Geographic. Nahoru vyjedeš lanovkou z Wasserauen a dojdeš 15 minut pěšky; rösti s výhledem do údolí nemá konkurenci.', 47.2837, 9.4142, 'https://commons.wikimedia.org/wiki/Special:FilePath/Berggasthaus%20Aescher-Wildkirchli.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Berggasthaus%20Aescher-Wildkirchli.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gasthaus%20Aescher%2C%20Wildkirchli%2C%20Ebenalp.jpg"}'::text[], 3),
    (v_route, 'Schwägalp a Säntis', 'Sedlo pod nejvyšší horou východního Švýcarska (2 502 m); kabinová lanovka tě za deset minut vyveze na vrchol s výhledem na šest zemí. Samotný přejezd Schwägalp je nejhezčí silniční úsek okruhu.', 47.2545, 9.3170, 'https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A4ntis-Swiss.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A4ntis-Swiss.JPG"}'::text[], 4);

  -- Valais – údolí Hérens a Anniviers
  delete from public.routes where name = 'Valais – údolí Hérens a Anniviers' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Valais – údolí Hérens a Anniviers', 'Dvě slepá údolí nad údolím Rhôny, kam většina turistů nikdy nezabočí — a právě proto patří k nejlepším motorkářským terénům Valais. Od hradů v Sionu vystoupáš kolem bizarních zemních pyramid v Euseigne k 285 m vysoké hrázi Grande Dixence, nejvyšší gravitační přehradě světa. Poté tě čeká Val d''Anniviers: galerie vytesané ve skále, tmavé modřínové chalupy v Grimentz a smaragdový Lac de Moiry ve výšce 2 250 m. Silnice jsou úzké, plné vlásenek a místy s tunely bez osvětlení — jeď s rozvahou a rozsviť dálková. Nejlépe od června do října, výše položené úseky mohou být na jaře a na podzim namrzlé.', 'poi', 160, 300, 'hard',
     '[{"lat": 46.2331, "lng": 7.3606, "label": "Start: Sion"}, {"lat": 46.1690, "lng": 7.4230, "label": "Euseigne"}, {"lat": 46.0806, "lng": 7.4033, "label": "Grande Dixence"}, {"lat": 46.2160, "lng": 7.5860, "label": "Vissoie"}, {"lat": 46.1790, "lng": 7.5740, "label": "Grimentz"}, {"lat": 46.1385, "lng": 7.5645, "label": "Lac de Moiry"}, {"lat": 46.2920, "lng": 7.5320, "label": "Cíl: Sierre"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.2331,7.3606&destination=46.2920,7.5320&travelmode=driving&waypoints=46.1690,7.4230%7C46.0806,7.4033%7C46.1790,7.5740%7C46.1385,7.5645', 'https://commons.wikimedia.org/wiki/Special:FilePath/Val%C3%A8re%20et%20Tourbillon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Val%C3%A8re%20et%20Tourbillon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Erdpyramiden%20von%20Euseigne.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Barrage%20de%20la%20Grande-Dixence.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grimentz-Moiry.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Barrage%20de%20Moiry%20(2).jpg"}'::text[], '{"Sion – Valère a Tourbillon","Pyramidy v Euseigne","Přehrada Grande Dixence","Grimentz","Lac de Moiry"}'::text[], '{"CH"}'::text[], false, 3370, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Sion – Valère a Tourbillon', 'Hlavní město Valais se dvěma hradními vrchy: v bazilice Valère hrají na nejstarší hratelné varhany světa (kolem roku 1435), z ruin Tourbillonu je panoráma vinic a čtyřtisícovek. Start mezi vinohrady nejsuššího kantonu Švýcarska.', 46.2331, 7.3606, 'https://commons.wikimedia.org/wiki/Special:FilePath/Val%C3%A8re%20et%20Tourbillon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Val%C3%A8re%20et%20Tourbillon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Tourbillon%2C%20Sion.jpg"}'::text[], 0),
    (v_route, 'Pyramidy v Euseigne', 'Skupina zemních pyramid s balvany na špici, kterou silnice do Val d''Hérens projíždí přímo tunelem — geologická kuriozita evropského formátu. Zastav na odstavném parkovišti hned za tunelem.', 46.1690, 7.4230, 'https://commons.wikimedia.org/wiki/Special:FilePath/Erdpyramiden%20von%20Euseigne.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Erdpyramiden%20von%20Euseigne.JPG"}'::text[], 1),
    (v_route, 'Přehrada Grande Dixence', 'Nejvyšší gravitační přehrada světa: 285 metrů betonu, víc materiálu než Cheopsova pyramida. Slepá silnice údolím Hérémence končí přímo pod hrází — lanovkou nebo pěšky se dá vystoupat na korunu s výhledem na Lac des Dix.', 46.0806, 7.4033, 'https://commons.wikimedia.org/wiki/Special:FilePath/Barrage%20de%20la%20Grande-Dixence.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Barrage%20de%20la%20Grande-Dixence.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grande%20Dixence%20Dam.jpg"}'::text[], 2),
    (v_route, 'Grimentz', 'Vesnice černých modřínových chalup spálených sluncem, v létě doslova zavalená muškáty — pravidelný vítěz soutěží o nejkrásnější švýcarskou vesnici. Úzké uličky projdi pěšky, motorku nech na parkovišti u vjezdu.', 46.1790, 7.5740, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grimentz-Moiry.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grimentz-Moiry.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grimentz-pierre-06.jpg"}'::text[], 3),
    (v_route, 'Lac de Moiry', 'Tyrkysová přehradní nádrž ve výšce 2 250 m na konci divokých serpentin nad Grimentz; nad hladinou visí ledovec Moiry. Jedna z nejvýše položených silnic, kam se ve Švýcarsku legálně dostaneš na motorce.', 46.1385, 7.5645, 'https://commons.wikimedia.org/wiki/Special:FilePath/Barrage%20de%20Moiry%20(2).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Barrage%20de%20Moiry%20(2).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Moiry%2C%20(2250%20m)%20Grimentz%2C%20Zwitserland.%20Bewolkte%20gletsers%20boven%20Lac%20de%20Moiry.JPG"}'::text[], 4);

  -- Lauterbrunnen a Grindelwald – údolí vodopádů
  delete from public.routes where name = 'Lauterbrunnen a Grindelwald – údolí vodopádů' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Lauterbrunnen a Grindelwald – údolí vodopádů', 'Komorní okruh Bernskou vysočinou pod severními stěnami Eigeru, Mönchu a Jungfrau. Z Interlakenu zajedeš do údolí Lauterbrunnen, kde ze skal padá 72 vodopádů včetně ikonického Staubbachu, a k Trümmelbachu burácejícímu uvnitř hory. Následuje výšvih do Grindelwaldu přímo pod stěnu Eigeru a po návratu pokračuješ po břehu tyrkysového Brienzersee do řezbářské vesnice Brienz a k vodopádům Giessbach. Kilometrů málo, zážitků na celý den — trasa je vhodná i pro méně zkušené jezdce. V hlavní sezóně vyjeď brzy, парковání v Lauterbrunnen se rychle plní.', 'loop', 85, 150, 'easy',
     '[{"lat": 46.6863, "lng": 7.8632, "label": "Start: Interlaken"}, {"lat": 46.5936, "lng": 7.9081, "label": "Lauterbrunnen"}, {"lat": 46.5709, "lng": 7.9033, "label": "Trümmelbachfälle"}, {"lat": 46.6244, "lng": 8.0414, "label": "Grindelwald"}, {"lat": 46.7565, "lng": 8.0327, "label": "Brienz"}, {"lat": 46.7345, "lng": 8.0230, "label": "Giessbach"}, {"lat": 46.6863, "lng": 7.8632, "label": "Cíl: Interlaken"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.6863,7.8632&destination=46.6863,7.8632&travelmode=driving&waypoints=46.5936,7.9081%7C46.6244,8.0414%7C46.7565,8.0327%7C46.7345,8.0230', 'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6heweg%2C%20Interlaken.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6heweg%2C%20Interlaken.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Iconic%20Lauterbrunnen%20waterfall.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/4849%20-%20Tr%C3%BCmmelbachf%C3%A4lle.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Grindelwald%20View.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brienz%202020.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grandhotel%20Giessbach.jpg"}'::text[], '{"Interlaken – Höheweg","Staubbachfall (Lauterbrunnen)","Trümmelbachfälle","Grindelwald pod Eigerem","Brienz – vesnice řezbářů","Giessbachfälle a Grandhotel"}'::text[], '{"CH"}'::text[], false, 3380, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Interlaken – Höheweg', 'Promenáda mezi dvěma jezery s přímým výhledem na trojici Eiger–Mönch–Jungfrau; nad loukou Höhematte se celý den snášejí paraglidisté. Startovní espresso s nejdražším výhledem Švýcarska zdarma.', 46.6863, 7.8632, 'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6heweg%2C%20Interlaken.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6heweg%2C%20Interlaken.jpg"}'::text[], 0),
    (v_route, 'Staubbachfall (Lauterbrunnen)', 'Vodopád padající volným pádem 297 metrů přímo za kostelem v Lauterbrunnen — vodní tříšť, která mu dala jméno, inspirovala i Goetha. Nejhezčí pohled je od jižního konce vesnice.', 46.5936, 7.9081, 'https://commons.wikimedia.org/wiki/Special:FilePath/Iconic%20Lauterbrunnen%20waterfall.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Iconic%20Lauterbrunnen%20waterfall.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lauterbrunnen%20Waterfall.jpg"}'::text[], 1),
    (v_route, 'Trümmelbachfälle', 'Deset ledovcových vodopádů burácejících v útrobách hory — tunelovým výtahem vyjedeš přímo do skály, kudy protéká voda z ledovců Jungfrau rychlostí až 20 000 litrů za sekundu. Nezapomeň nepromokavou vrstvu.', 46.5709, 7.9033, 'https://commons.wikimedia.org/wiki/Special:FilePath/4849%20-%20Tr%C3%BCmmelbachf%C3%A4lle.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/4849%20-%20Tr%C3%BCmmelbachf%C3%A4lle.JPG"}'::text[], 2),
    (v_route, 'Grindelwald pod Eigerem', 'Horská vesnice přímo pod proslulou severní stěnou Eigeru, o kterou se psaly knihy i filmy. Stoupání z Zweilütschinen je plynulé a výhledové; na terase v centru se skvěle obědvá s ledovcem nad hlavou.', 46.6244, 8.0414, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grindelwald%20View.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grindelwald%20View.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/00%203442%20Grindelwald%20-%20Eiger%20(Schweiz).jpg"}'::text[], 3),
    (v_route, 'Brienz – vesnice řezbářů', 'Dřevěné domky s vyřezávanými štíty na břehu nejčistšího švýcarského jezera; místní řezbářská škola zásobuje betlémy půl Evropy. Silnice po severním břehu Brienzersee je jedna dlouhá vyhlídka.', 46.7565, 8.0327, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brienz%202020.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brienz%202020.jpg"}'::text[], 4),
    (v_route, 'Giessbachfälle a Grandhotel', 'Čtrnáct kaskád padajících 500 metrů do jezera přímo pod okny pohádkového Grandhotelu Giessbach z 19. století. Ke slavné vyhlídce s hotelem v pozadí dojdeš od parkoviště za pár minut; funguje tu i nejstarší horská zubačka Evropy.', 46.7345, 8.0230, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grandhotel%20Giessbach.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grandhotel%20Giessbach.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hotel%20Giessbach.JPG"}'::text[], 5);

  -- Gruyères, Lavaux a Ženevské jezero
  delete from public.routes where name = 'Gruyères, Lavaux a Ženevské jezero' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Gruyères, Lavaux a Ženevské jezero', 'Nejchutnější okruh Švýcarska: sýr, čokoláda a víno v jednom dni. Od vodního hradu Chillon projedeš po břehu Ženevského jezera do Vevey a terasovitými vinicemi Lavaux (UNESCO), kde se silnička proplétá mezi vinohrady vysoko nad hladinou. Přes zelený kraj Fribourg dojedeš do středověkého městečka Gruyères na fondue a do čokoládovny Cailler v Brocu. Návrat vede alpským údolím přes balónové městečko Château-d''Oex a průsmyk Col des Mosses zpět k jezeru. Trasa je nenáročná, s krásným asfaltem — ideální od května do října. O víkendech je pobřežní silnice u Montreux pomalá, vinice si ale bez pomalé jízdy stejně nevychutnáš.', 'loop', 160, 250, 'easy',
     '[{"lat": 46.4312, "lng": 6.9107, "label": "Start: Montreux"}, {"lat": 46.4142, "lng": 6.9273, "label": "Hrad Chillon"}, {"lat": 46.4603, "lng": 6.8419, "label": "Vevey"}, {"lat": 46.4700, "lng": 6.7960, "label": "St-Saphorin (Lavaux)"}, {"lat": 46.5836, "lng": 7.0822, "label": "Gruyères"}, {"lat": 46.6060, "lng": 7.1000, "label": "Broc"}, {"lat": 46.4745, "lng": 7.1310, "label": "Château-d''Oex"}, {"lat": 46.4312, "lng": 6.9107, "label": "Cíl: Montreux"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.4312,6.9107&destination=46.4312,6.9107&travelmode=driving&waypoints=46.4142,6.9273%7C46.4700,6.7960%7C46.5836,7.0822%7C46.6060,7.1000%7C46.4745,7.1310', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chateau%20de%20Chillon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chateau%20de%20Chillon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fork%20of%20Vevey.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lavaux%20Patrimoine%20mondial%202007%2010%2006.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Gruy%C3%A8res.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Gruy%C3%A8res%20from%20Le%20P%C3%A2quier-Montbarry%20(Le%20P%C3%A2quier%20(Fribourg))%20(autumn)%205.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Broc%20Chocolaterie%20Maison%20Cailler.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20d%27Oex%20(veduta%20generale).JPG"}'::text[], '{"Hrad Chillon","Vevey – vidlička a Chaplin","Vinice Lavaux (UNESCO)","Gruyères – hrad a městečko","Restaurace: Le Chalet de Gruyères","Maison Cailler (Broc)","Château-d''Oex – městečko balonů"}'::text[], '{"CH"}'::text[], false, 3390, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Chillon', 'Nejnavštěvovanější hrad Švýcarska stojí na skalce přímo v Ženevském jezeře — vodní pevnost, jejíž sklepení proslavil Byron poemou Vězeň chillonský. Ranní světlo na hradbách s Dents du Midi v pozadí je fotka dne.', 46.4142, 6.9273, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chateau%20de%20Chillon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chateau%20de%20Chillon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Chillon%20et%20Dents%20du%20Midi.jpg"}'::text[], 0),
    (v_route, 'Vevey – vidlička a Chaplin', 'Elegantní město na jezeře, kde prožil poslední čtvrtstoletí Charlie Chaplin — jeho socha stojí na promenádě kousek od osmimetrové vidličky zapíchnuté v hladině, symbolu muzea jídla Alimentarium.', 46.4603, 6.8419, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fork%20of%20Vevey.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fork%20of%20Vevey.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Chaplin%20Vevey%2023.12.2006.jpg"}'::text[], 1),
    (v_route, 'Vinice Lavaux (UNESCO)', 'Osm set let staré vinařské terasy spadající k hladině Ženevského jezera; úzká Route de la Corniche mezi vesničkami St-Saphorin a Epesses patří k nejkrásnějším kilometrům Švýcarska. Degustaci chasselas nech spolujezdci.', 46.4700, 6.7960, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lavaux%20Patrimoine%20mondial%202007%2010%2006.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lavaux%20Patrimoine%20mondial%202007%2010%2006.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Lavaux%20c%C3%B4t%C3%A9%20Vevey%204.JPG"}'::text[], 2),
    (v_route, 'Gruyères – hrad a městečko', 'Dokonale zachované středověké městečko na kopci s hradem z 13. století, kolébka slavného sýra Gruyère. Kuriozita: v hradbách sídlí i muzeum H. R. Gigera, tvůrce Vetřelce — kontrast, který funguje.', 46.5836, 7.0822, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Gruy%C3%A8res.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Gruy%C3%A8res.JPG"}'::text[], 3),
    (v_route, 'Restaurace: Le Chalet de Gruyères', 'Vyhlášená fondue restaurace v dřevěném chalet přímo na hlavní uličce městečka — moitié-moitié z místního gruyèru a vacherinu je povinnost. V sezóně si rezervuj stůl, nebo přijeď před polednem.', 46.5832, 7.0820, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Gruy%C3%A8res%20from%20Le%20P%C3%A2quier-Montbarry%20(Le%20P%C3%A2quier%20(Fribourg))%20(autumn)%205.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Gruy%C3%A8res%20from%20Le%20P%C3%A2quier-Montbarry%20(Le%20P%C3%A2quier%20(Fribourg))%20(autumn)%205.JPG"}'::text[], 4),
    (v_route, 'Maison Cailler (Broc)', 'Nejstarší dosud vyráběná čokoládová značka Švýcarska otevřela ve své továrně interaktivní prohlídku s neomezenou ochutnávkou na konci. Vůně čokolády je cítit už na parkovišti.', 46.6060, 7.1000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Broc%20Chocolaterie%20Maison%20Cailler.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Broc%20Chocolaterie%20Maison%20Cailler.jpg"}'::text[], 5),
    (v_route, 'Château-d''Oex – městečko balonů', 'Alpské městečko v údolí Sarine, světová metropole horkovzdušných balonů — odsud odstartoval i první balonový oblet Země. Z návrší nad городečkem je hezký výhled do celého Pays-d''Enhaut; následuje svezení přes Col des Mosses zpět k jezeru.', 46.4745, 7.1310, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20d%27Oex%20(veduta%20generale).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20d%27Oex%20(veduta%20generale).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Balloons%20Festival%20-%20Chateaux%20d%27Oex.jpg"}'::text[], 6);

  -- Engadin a Val Müstair – Flüela a Ofenpass
  delete from public.routes where name = 'Engadin a Val Müstair – Flüela a Ofenpass' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Engadin a Val Müstair – Flüela a Ofenpass', 'Přejezd nejodlehlejším koutem Švýcarska: z Davosu přes měsíční krajinu Flüelapassu do dolního Engadinu a dál Ofenpassem skrz jediný švýcarský národní park až ke karolinskému klášteru v Müstairu. Silnice jsou široké a přehledné, provoz minimální — o to víc si užiješ dlouhé oblouky mezi borovicovými lesy, kde není výjimkou spatřit kamzíky nebo jeleny. V národním parku platí zákaz zastavování mimo značená parkoviště, tak si výhledy dávkuj na odpočívkách. Flüela bývá otevřená zhruba od května do listopadu; brzy ráno a večer tu i v létě mrzne. Trasa krásně navazuje na přejezd do Itálie či Rakouska.', 'poi', 95, 160, 'medium',
     '[{"lat": 46.8003, "lng": 9.8370, "label": "Start: Davos"}, {"lat": 46.7503, "lng": 9.9463, "label": "Flüelapass"}, {"lat": 46.7500, "lng": 10.0810, "label": "Susch"}, {"lat": 46.6990, "lng": 10.0920, "label": "Zernez"}, {"lat": 46.6398, "lng": 10.2923, "label": "Ofenpass"}, {"lat": 46.6290, "lng": 10.4620, "label": "Cíl: Müstair"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.8003,9.8370&destination=46.6290,10.4620&travelmode=driving&waypoints=46.7503,9.9463%7C46.6990,10.0920%7C46.6398,10.2923', 'https://commons.wikimedia.org/wiki/Special:FilePath/Davos-See.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Davos-See.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hotel%20Fl%C3%BCela%20Hospiz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zernez-Engadin-Munt-Baselgia-20220905.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Swiss%20National%20Park%20303.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Pass%20dal%20Fuorn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kloster%20M%C3%BCstair%20April11.JPG"}'::text[], '{"Davos a Davosersee","Flüelapass","Zernez","Švýcarský národní park","Ofenpass (Pass dal Fuorn)","Klášter sv. Jana v Müstairu"}'::text[], '{"CH"}'::text[], false, 3400, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Davos a Davosersee', 'Nejvýše položené město Evropy (1 560 m), známé Světovým ekonomickým fórem i Kouzelným vrchem Thomase Manna. Před stoupáním na Flüelu stojí za krátkou zastávku jezero Davosersee na severním okraji.', 46.8003, 9.8370, 'https://commons.wikimedia.org/wiki/Special:FilePath/Davos-See.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Davos-See.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/City%20of%20Davos.jpg"}'::text[], 0),
    (v_route, 'Flüelapass', 'Průsmyk (2 383 m) s měsíční krajinou kamenných polí a dvou černých jezer u historického hospicu na vrcholu. Dlouhé přehledné oblouky bez svodidel — jeden z nejplynulejších vysokých přejezdů v Alpách.', 46.7503, 9.9463, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hotel%20Fl%C3%BCela%20Hospiz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hotel%20Fl%C3%BCela%20Hospiz.jpg"}'::text[], 1),
    (v_route, 'Zernez', 'Engadinská vesnice se silnými zdmi a sgrafity, hlavní brána do Švýcarského národního parku — v moderním návštěvnickém centru zjistíš, kde máš největší šanci na medvěda, orla či kamzíka.', 46.6990, 10.0920, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zernez-Engadin-Munt-Baselgia-20220905.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zernez-Engadin-Munt-Baselgia-20220905.jpg"}'::text[], 2),
    (v_route, 'Švýcarský národní park', 'Nejstarší národní park Alp (1914) a jediný ve Švýcarsku — silnice Ofenpassu jím projíždí jako jediná v celé zemi. Divočina bez zásahu člověka přes sto let; zastavuj jen na značených odpočívkách a vyhlížej jeleny na protějších svazích.', 46.6600, 10.2260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Swiss%20National%20Park%20303.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Swiss%20National%20Park%20303.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Swiss%20National%20Park%20045.JPG"}'::text[], 3),
    (v_route, 'Ofenpass (Pass dal Fuorn)', 'Klidný průsmyk (2 149 m) mezi Engadinem a Val Müstair, obklopený borovicemi a limbami národního parku. Na vrcholu stojí horský hostinec s terasou — poslední káva před sjezdem do rétorománského údolí.', 46.6398, 10.2923, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pass%20dal%20Fuorn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pass%20dal%20Fuorn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fuorn%20P1110622.jpg"}'::text[], 4),
    (v_route, 'Klášter sv. Jana v Müstairu', 'Benediktinský klášter založený podle legendy Karlem Velikým roku 780, s největším dochovaným cyklem karolinských fresek na světě — památka UNESCO na samém konci Švýcarska, pár kilometrů před italskou hranicí.', 46.6290, 10.4620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kloster%20M%C3%BCstair%20April11.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kloster%20M%C3%BCstair%20April11.JPG"}'::text[], 5);

end $$;
