-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — Rakousko II (AT, 10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Waldviertel – hrady na Kamp a přehrada Ottenstein
  delete from public.routes where name = 'Waldviertel – hrady na Kampu a přehrada Ottenstein' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Waldviertel – hrady na Kampu a přehrada Ottenstein', 'Waldviertel leží jen kousek za českou hranicí, a přesto ho většina motorkářů mine cestou do Alp — velká škoda. Okruh ze Zwettlu vede prázdnými okresními silničkami mezi žulovými balvany, lesy a rybníky, přes středověký hrad Rappottenstein až k meandrům řeky Kamp s přehradou Ottenstein a pohádkovým zámkem Rosenburg. Silnice jsou úzké, zvlněné a téměř bez provozu, ideální na pohodové tempo a nácvik plynulé jízdy zatáčkami. Nejhezčí je trasa od května do října; brzy zjara pozor na zbytky posypu ve stinných lesních úsecích. Kamptal mezi Rosenburgem a Gars am Kamp patří k nejkrásnějším říčním údolím Dolního Rakouska. Počítejte s celodenním výletem s koupáním u Ottensteinu.', 'loop', 165, 240, 'easy',
     '[{"lat": 48.6036, "lng": 15.1689, "label": "Start: Zwettl"}, {"lat": 48.5236, "lng": 15.0808, "label": "Burg Rappottenstein"}, {"lat": 48.6072, "lng": 15.3236, "label": "Stausee Ottenstein"}, {"lat": 48.6319, "lng": 15.6392, "label": "Rosenburg"}, {"lat": 48.5942, "lng": 15.6564, "label": "Gars am Kamp"}, {"lat": 48.6036, "lng": 15.1689, "label": "Cíl: Zwettl"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.6036,15.1689&destination=48.6036,15.1689&travelmode=driving&waypoints=48.5236,15.0808%7C48.6072,15.3236%7C48.6319,15.6392%7C48.5942,15.6564', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rappottenstein%20-%20Burg.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rappottenstein%20-%20Burg.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Stift%20Zwettl.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stausee%20Ottenstein.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Rosenburg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gars%20am%20Kamp%20-%20Burgruine.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Zwettl%20-%20Hauptplatz.JPG"}'::text[], '{"Hrad Rappottenstein","Klášter Zwettl","Přehrada Ottenstein","Zámek Rosenburg","Zřícenina Gars am Kamp","Restaurace: Bräuhaus Zwettl (Zwettl)"}'::text[], '{"AT"}'::text[], false, 3010, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Rappottenstein', 'Jeden z nejzachovalejších středověkých hradů Rakouska nebyl nikdy dobyt a dodnes patří rodu Abensperg-Traun. Mohutná románsko-gotická pevnost na žulovém ostrohu nad říčkou Kamp nabízí komentované prohlídky i výhled na lesy Waldviertelu. Příjezdová silnička od Zwettlu je samá zatáčka mezi balvany.', 48.5236, 15.0808, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rappottenstein%20-%20Burg.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rappottenstein%20-%20Burg.JPG"}'::text[], 0),
    (v_route, 'Klášter Zwettl', 'Cisterciácký klášter z roku 1138 patří k nejstarším v Rakousku a dodnes v něm žije řádová komunita. Za prohlídku stojí gotický křížový chodba, barokní věž kostela a klášterní zahrady u řeky Kamp. Ideální krátká zastávka hned na začátku okruhu.', 48.6167, 15.2039, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stift%20Zwettl.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stift%20Zwettl.jpg"}'::text[], 1),
    (v_route, 'Přehrada Ottenstein', 'Přehradní jezero na Kampu s členitými zátokami, žulovými ostrůvky a vodou vhodnou ke koupání. Nad hladinou trůní zřícenina Lichtenfels, kterou je z hráze krásně vidět. Silnice kolem nádrže se vlní nad vodou a patří k jízdním vrcholům trasy.', 48.6072, 15.3236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stausee%20Ottenstein.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stausee%20Ottenstein.jpg"}'::text[], 2),
    (v_route, 'Zámek Rosenburg', 'Renesanční zámek nad údolím Kampu je proslulý dochovaným turnajovým nádvořím a ukázkami sokolnictví — dravci tu létají divákům přímo nad hlavami. Interiéry ukrývají zbrojnici a bohaté sbírky. Z parkoviště je pěkný výhled do kaňonu řeky.', 48.6319, 15.6392, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Rosenburg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Rosenburg.jpg"}'::text[], 3),
    (v_route, 'Zřícenina Gars am Kamp', 'Nad městečkem Gars se zvedá rozlehlá zřícenina babenberského hradu z 11. století, jednoho z nejstarších panovnických sídel Rakouska. Volně přístupný areál nabízí výhled na údolí Kampu a vinice. Dole ve městě je příjemná náves na kávu.', 48.5942, 15.6564, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gars%20am%20Kamp%20-%20Burgruine.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gars%20am%20Kamp%20-%20Burgruine.JPG"}'::text[], 4),
    (v_route, 'Restaurace: Bräuhaus Zwettl (Zwettl)', 'Restaurace zwettlského rodinného pivovaru, který vaří pivo už od roku 1708. Poctivá rakouská kuchyně — Zwiebelrostbraten, řízek i sezónní speciality — a čepované Zwettler přímo od zdroje. Ideální zakončení okruhu na náměstí ve Zwettlu.', 48.6039, 15.1683, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zwettl%20-%20Hauptplatz.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zwettl%20-%20Hauptplatz.JPG"}'::text[], 5);

  -- Mühlviertel a dunajská smyčka Schlögen
  delete from public.routes where name = 'Mühlviertel a dunajská smyčka Schlögen' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mühlviertel a dunajská smyčka Schlögen', 'Mühlviertel je kopcovitá krajina hned za jihočeskou hranicí — žulové vrchy, lesy a klikaté silničky téměř bez aut. Okruh z renesančního Freistadtu vede přes gotický skvost v Kefermarktu a lázeňské městečko Bad Leonfelden k premonstrátskému klášteru Schlägl a vrcholí u vyhlídky na Schlögener Schlinge, kde se Dunaj otáčí o 180 stupňů mezi zalesněnými srázy. Jízdně jde o nekonečný sled třetírychlostních zatáček s krátkými rovinkami, technicky nenáročný, ale zábavný. Nejlepší je od jara do podzimu; v létě počítejte u vyhlídek s turisty. Pozor na zvěř v lesních úsecích a na úzké obousměrné silničky kolem Dunaje. Trasa se dá pohodlně stihnout za den včetně zastávek.', 'loop', 220, 320, 'medium',
     '[{"lat": 48.5114, "lng": 14.5047, "label": "Start: Freistadt"}, {"lat": 48.4433, "lng": 14.5386, "label": "Kefermarkt"}, {"lat": 48.5253, "lng": 14.2942, "label": "Bad Leonfelden"}, {"lat": 48.6394, "lng": 13.9625, "label": "Stift Schlägl"}, {"lat": 48.4494, "lng": 13.9439, "label": "Schlögener Schlinge"}, {"lat": 48.5114, "lng": 14.5047, "label": "Cíl: Freistadt"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.5114,14.5047&destination=48.5114,14.5047&travelmode=driving&waypoints=48.4433,14.5386%7C48.5253,14.2942%7C48.6394,13.9625%7C48.4494,13.9439', 'https://commons.wikimedia.org/wiki/Special:FilePath/Schl%C3%B6gener%20Schlinge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Freistadt%20Hauptplatz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kefermarkt%20Fl%C3%BCgelaltar.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bad%20Leonfelden.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stift%20Schl%C3%A4gl.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schl%C3%B6gener%20Schlinge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Freistadt.jpg"}'::text[], '{"Freistadt — historické centrum","Kefermarkt — gotický oltář","Bad Leonfelden","Klášter Schlägl","Schlögener Schlinge — vyhlídka","Restaurace: Freistädter Brauhaus (Freistadt)"}'::text[], '{"AT"}'::text[], false, 3020, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Freistadt — historické centrum', 'Dokonale zachované středověké město s kompletními hradbami, dvěma branami a podloubím kolem náměstí. Freistadt je zároveň pivovarské město — místní Braucommune vlastní měšťané už od roku 1777. Skvělý výchozí bod okruhu s parkováním hned za hradbami.', 48.5114, 14.5047, 'https://commons.wikimedia.org/wiki/Special:FilePath/Freistadt%20Hauptplatz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Freistadt%20Hauptplatz.jpg"}'::text[], 0),
    (v_route, 'Kefermarkt — gotický oltář', 'V nenápadném kostele sv. Wolfganga stojí jeden z největších pokladů střední Evropy — třináct metrů vysoký pozdně gotický křídlový oltář vyřezaný z lipového dřeva kolem roku 1497. Jemnost řezby bere dech i lidem, kteří do kostelů běžně nechodí. Zastávka na dvacet minut, které stojí za to.', 48.4433, 14.5386, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kefermarkt%20Fl%C3%BCgelaltar.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kefermarkt%20Fl%C3%BCgelaltar.jpg"}'::text[], 1),
    (v_route, 'Bad Leonfelden', 'Lázeňské městečko na staré solné stezce z Lince do Čech, známé perníkářskou tradicí rodiny Kastner (pekárna funguje od roku 1559). Podél malebného náměstí se dá koupit perník na cestu. Odsud se silnice stáčí na západ do nejhezčí, zvlněné části Mühlviertelu.', 48.5253, 14.2942, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bad%20Leonfelden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bad%20Leonfelden.jpg"}'::text[], 2),
    (v_route, 'Klášter Schlägl', 'Premonstrátský klášter z 13. století pod šumavským hřebenem, jediný klášterní pivovar Horního Rakouska. Barokní kostel, obrazárna a klášterní pivnice s výborným tmavým ležákem. Okolní silničky pod Hochfichtem se jezdí skvěle a je odtud vidět na českou stranu Šumavy.', 48.6394, 13.9625, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stift%20Schl%C3%A4gl.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stift%20Schl%C3%A4gl.jpg"}'::text[], 3),
    (v_route, 'Schlögener Schlinge — vyhlídka', 'Nejslavnější říční meandr Rakouska: Dunaj se u Schlögenu otočí o 180 stupňů mezi strmými zalesněnými srázy. Z vyhlídky Schlögener Blick nad pravým břehem je celá smyčka jako na dlani — k plošině se jde od parkoviště asi 20 minut pěšky. Jedno z nejfotografovanějších míst Horního Rakouska.', 48.4494, 13.9439, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schl%C3%B6gener%20Schlinge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schl%C3%B6gener%20Schlinge.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Freistädter Brauhaus (Freistadt)', 'Restaurace městského pivovaru Freistädter Bier, kde se vaří už přes dvě stě let. Vydatná hornorakouská kuchyně a pivní speciály z tanků pár metrů od výčepu. Perfektní tečka za okruhem po návratu do Freistadtu.', 48.5108, 14.5031, 'https://commons.wikimedia.org/wiki/Special:FilePath/Freistadt.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Freistadt.jpg"}'::text[], 5);

  -- Bregenzerwald a průsmyk Hochtannberg
  delete from public.routes where name = 'Bregenzerwald a průsmyk Hochtannberg' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Bregenzerwald a průsmyk Hochtannberg', 'Bregenzerwald je nejzelenější kout Vorarlberska — kraj dřevěných vesnic, sýrových mlékáren a silnic, které se vlní mezi loukami s kulisou vápencových štítů. Trasa startuje u Bodamského jezera v Bregenzi, stoupá přes Egg a Bezau pod mohutnou stěnu Kanisfluh, odbočí do nejvýše položené vesnice Damüls a přes průsmyk Hochtannberg (1676 m) sjíždí do slavného Lechu. Jízdně jde o kombinaci rychlých údolních pasáží a serpentin nad hranicí lesa. Průsmyk je sjízdný zhruba od května do listopadu, brzy ráno bývá prázdný. Pozor na cyklisty o víkendech a na dobytek na horských úsecích. Půldenní až celodenní výlet, který se dá spojit s návratem přes Lechtal.', 'poi', 90, 160, 'medium',
     '[{"lat": 47.5031, "lng": 9.7471, "label": "Start: Bregenz"}, {"lat": 47.3856, "lng": 9.9003, "label": "Bezau"}, {"lat": 47.3236, "lng": 9.9364, "label": "Kanisfluh (Au)"}, {"lat": 47.2806, "lng": 9.8919, "label": "Damüls"}, {"lat": 47.2589, "lng": 10.0089, "label": "Hochtannbergpass"}, {"lat": 47.2081, "lng": 10.1419, "label": "Cíl: Lech am Arlberg"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.5031,9.7471&destination=47.2081,10.1419&travelmode=driving&waypoints=47.3856,9.9003%7C47.3236,9.9364%7C47.2806,9.8919%7C47.2589,10.0089', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bregenz%20vom%20Pf%C3%A4nder.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bregenz%20vom%20Pf%C3%A4nder.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bezau.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kanisfluh.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dam%C3%BCls.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hochtannbergpass.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lech%20am%20Arlberg.jpg"}'::text[], '{"Bregenz a Pfänder","Bezau","Kanisfluh — vyhlídka","Damüls","Hochtannbergpass","Lech am Arlberg"}'::text[], '{"AT"}'::text[], false, 3030, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Bregenz a Pfänder', 'Hlavní město Vorarlberska leží přímo na břehu Bodamského jezera, proslulé je operní scénou na vodě. Nad městem se zvedá Pfänder (1064 m) — lanovkou nebo silničkou se dá vyjet k vyhlídce, ze které je vidět jezero, Rýnská delta a prý až 240 alpských vrcholů. Skvělý start dne.', 47.5031, 9.7471, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bregenz%20vom%20Pf%C3%A4nder.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bregenz%20vom%20Pf%C3%A4nder.jpg"}'::text[], 0),
    (v_route, 'Bezau', 'Srdce Bregenzerwaldu a ukázka místní dřevěné architektury — šindelové fasády tu mají i moderní domy. Vesnice je centrem sýrařské stezky KäseStrasse, takže ochutnávka horského sýra je povinnost. Odsud začíná nejhezčí horská část trasy.', 47.3856, 9.9003, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bezau.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bezau.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Gasthof Gams (Bezau)', 'Tradiční hostinec v centru Bezau vaří moderní vorarlberskou kuchyni z regionálních surovin — sýrové Kässpätzle jsou tu zážitek. Příjemná zahrada a rychlá obsluha i pro motorkáře v kombinéze. Dobré místo na oběd před stoupáním do hor.', 47.3861, 9.8994, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bezau.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bezau.jpg"}'::text[], 2),
    (v_route, 'Kanisfluh — vyhlídka', 'Mohutný vápencový masiv Kanisfluh (2044 m) je symbolem Bregenzerwaldu — z údolí mezi Mellau a Au působí jako obří kamenná vlna nad loukami. U silnice je několik míst na fotku. Jeden z nejfotogeničtějších úseků celé trasy.', 47.3236, 9.9364, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kanisfluh.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kanisfluh.jpg"}'::text[], 3),
    (v_route, 'Damüls', 'Nejvýše položená vesnice Bregenzerwaldu (1428 m) drží evropský rekord v průměrném úhrnu sněhu, v létě je to ale rozkvetlá horská terasa s výhledem na Damülser Mittagspitze. Stoupání z Au nabízí sérii pěkných serpentin. Krátká odbočka, která stojí za to.', 47.2806, 9.8919, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dam%C3%BCls.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dam%C3%BCls.jpg"}'::text[], 4),
    (v_route, 'Hochtannbergpass', 'Průsmyk ve výšce 1676 metrů spojuje Bregenzerwald s údolím Lechu. Nad sedlem se tyčí zubatý Widderstein a kousek pod vrcholem leží idylické jezírko Körbersee, přístupné pěšky. Otevřená horská krajina nad hranicí lesa s výhledy na všechny strany.', 47.2589, 10.0089, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hochtannbergpass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hochtannbergpass.jpg"}'::text[], 5),
    (v_route, 'Lech am Arlberg', 'Světoznámá horská vesnice na mladé řece Lech, v zimě hřiště královských rodin, v létě překvapivě klidné místo s trávou porostlými sjezdovkami. Cíl trasy s řadou kaváren a teras u řeky. Kdo chce pokračovat, může sjet do Warthu a dál Lechtalem.', 47.2081, 10.1419, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lech%20am%20Arlberg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lech%20am%20Arlberg.jpg"}'::text[], 6);

  -- Kaunertal – ledovcová silnice
  delete from public.routes where name = 'Kaunertal – ledovcová silnice' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kaunertal – ledovcová silnice', 'Kaunertaler Gletscherstraße je jedna z nejvýše vedoucích silnic Alp — z Landeck vystoupá až do 2750 metrů k okraji ledovce Weißseeferner. Mýtná silnice s 29 serpentinami vede podél tyrkysové přehrady Gepatsch a končí přímo pod ledovcem, kam se běžný smrtelník jinak nedostane. Kvalitní asfalt, přehledné zatáčky a minimum provozu mimo hlavní sezónu z ní dělají motorkářský klenot. Silnice je otevřená celoročně (ledovcové lyžování), pro motorky je ideální červen až září; nahoře bývá o 15 stupňů chladněji než v údolí, teplé vrstvy s sebou. Pozor na skot u silnice a náhlé změny počasí ve výšce. Zpáteční cesta stejnou trasou nabízí úplně jiné výhledy.', 'poi', 65, 140, 'hard',
     '[{"lat": 47.1392, "lng": 10.5647, "label": "Start: Landeck"}, {"lat": 47.0794, "lng": 10.6647, "label": "Prutz"}, {"lat": 47.0072, "lng": 10.7181, "label": "Feichten im Kaunertal"}, {"lat": 46.9631, "lng": 10.7392, "label": "Gepatsch-Stausee"}, {"lat": 46.8703, "lng": 10.7108, "label": "Cíl: Kaunertaler Gletscher"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.1392,10.5647&destination=46.8703,10.7108&travelmode=driving&waypoints=47.0794,10.6647%7C47.0072,10.7181%7C46.9631,10.7392', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertaler%20Gletscher.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Landeck.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prutz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertal.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gepatschspeicher.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertaler%20Gletscher.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertaler%20Gletscherstra%C3%9Fe.jpg"}'::text[], '{"Zámek Landeck","Prutz","Kaunertal — Feichten","Gepatsch-Stausee","Kaunertaler Gletscher","Restaurace: Gletscherrestaurant Weißsee (Kaunertal)"}'::text[], '{"AT"}'::text[], false, 3040, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Landeck', 'Středověký zámek na skále nad soutokem Innu a Sanny střeží křižovatku cest mezi Arlbergem, Reschenpassem a Fernpassem. Dnes v něm sídlí muzeum regionu a galerie, z věže je výhled na celé město. Dobré místo na kávu před odbočením do Kaunertalu.', 47.1392, 10.5647, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Landeck.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Landeck.jpg"}'::text[], 0),
    (v_route, 'Prutz', 'Vesnice v širokém údolí horního Innu, kde začíná odbočka do Kaunertalu i serpentiny na vyhlídku Gachen Blick nad Naturparkem Kaunergrat. Poslední pohodlné tankování před ledovcovou silnicí. Kolem obce rostou nejvýše položené vinice Tyrolska.', 47.0794, 10.6647, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prutz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prutz.jpg"}'::text[], 1),
    (v_route, 'Kaunertal — Feichten', 'Hlavní vesnice úzkého ledovcového údolí a vstupní brána mýtné Gletscherstraße. Tradiční tyrolské statky, kostelík a informační centrum Naturparku Kaunergrat. Odsud začíná souvislé stoupání — 29 serpentin a přes 1500 výškových metrů.', 47.0072, 10.7181, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertal.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertal.jpg"}'::text[], 2),
    (v_route, 'Gepatsch-Stausee', 'Šest kilometrů dlouhá přehrada s tyrkysovou ledovcovou vodou, sevřená třítisícovkami Kaunergratu. Silnice se vine přímo nad hladinou a nabízí jedny z nejkrásnějších kilometrů celé trasy. U hráze je vyhlídkové parkoviště.', 46.9631, 10.7392, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gepatschspeicher.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gepatschspeicher.jpg"}'::text[], 3),
    (v_route, 'Kaunertaler Gletscher', 'Konec silnice ve výšce 2750 metrů, pár kroků od splazu ledovce Weißseeferner. I v červenci tu leží sníh a panorama Ötztalských Alp je na dosah ruky. Jedno z mála míst v Alpách, kam se dá k ledovci dojet po asfaltu — zážitek, který se neokouká.', 46.8703, 10.7108, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertaler%20Gletscher.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertaler%20Gletscher.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Gletscherrestaurant Weißsee (Kaunertal)', 'Samoobslužná horská restaurace přímo na konci ledovcové silnice ve 2750 metrech. Polévky, tyrolská klasika a horký čaj s výhledem na ledovec z prosklené terasy. Nejvýše položený oběd, jaký si v Rakousku na motorce dopřejete.', 46.8710, 10.7115, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertaler%20Gletscherstra%C3%9Fe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kaunertaler%20Gletscherstra%C3%9Fe.jpg"}'::text[], 5);

  -- Gesäuse a Erzberg – štýrská železná cesta
  delete from public.routes where name = 'Gesäuse a Erzberg – štýrská železná cesta' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Gesäuse a Erzberg – štýrská železná cesta', 'Divoká vápencová soutěska Gesäuse, kde řeka Enns hučí mezi kolmými stěnami, a rezavě rudá hora Erzberg, na které se koná legendární motocyklový Erzbergrodeo — to je den plný kontrastů v srdci Štýrska. Trasa začíná u kláštera Admont s nejkrásnější klášterní knihovnou světa, projede národním parkem Gesäuse podél Ennsu a přes Hieflau zamíří k jezeru Leopoldsteiner See a hornickému Eisenerzu, odkud vystoupá do sedla Präbichl. Silnice B146 soutěskou patří k nejhezčím říčním úsekům Rakouska — plynulé zatáčky, skály nad hlavou a minimum křižovatek. Ideální období květen až říjen; o prázdninových víkendech tu bývá živěji. Pozor na tunely u Hieflau a štěrk po deštích. Půldenní trasa, kterou lze protáhnout přes Eisenwurzen zpět.', 'poi', 85, 150, 'medium',
     '[{"lat": 47.5758, "lng": 14.4611, "label": "Start: Admont"}, {"lat": 47.5875, "lng": 14.5378, "label": "Gesäuseeingang"}, {"lat": 47.6058, "lng": 14.7447, "label": "Hieflau"}, {"lat": 47.5647, "lng": 14.8681, "label": "Leopoldsteiner See"}, {"lat": 47.5333, "lng": 14.8931, "label": "Erzberg"}, {"lat": 47.5158, "lng": 14.9481, "label": "Cíl: Präbichl"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.5758,14.4611&destination=47.5158,14.9481&travelmode=driving&waypoints=47.5875,14.5378%7C47.6058,14.7447%7C47.5647,14.8681%7C47.5333,14.8931', 'https://commons.wikimedia.org/wiki/Special:FilePath/Austria%20-%20Admont%20Abbey%20Library%20-%201407.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Austria%20-%20Admont%20Abbey%20Library%20-%201407.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ges%C3%A4useeingang.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Leopoldsteiner%20See.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Steirischer%20Erzberg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Eisenerz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A4bichl.jpg"}'::text[], '{"Klášter Admont — knihovna","NP Gesäuse — Gesäuseeingang","Leopoldsteiner See","Erzberg — rudná hora","Restaurace: Erzbergbräu (Eisenerz)","Präbichl"}'::text[], '{"AT"}'::text[], false, 3050, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Klášter Admont — knihovna', 'Benediktinský klášter Admont ukrývá největší klášterní knihovní sál světa — 70 metrů bílé a zlaté barokní nádhery se 70 000 svazky a freskami. Vedle knihovny stojí za vidění přírodovědné muzeum. Otvírá v deset, naplánujte si start podle toho.', 47.5758, 14.4611, 'https://commons.wikimedia.org/wiki/Special:FilePath/Austria%20-%20Admont%20Abbey%20Library%20-%201407.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Austria%20-%20Admont%20Abbey%20Library%20-%201407.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stift%20Admont.jpg"}'::text[], 0),
    (v_route, 'NP Gesäuse — Gesäuseeingang', 'Vstup do soutěsky, kde se Enns zařezává mezi kolmé stěny Hochtoru a Buchsteinu — název Gesäuse znamená "hučení". Národní park je rájem vodáků a horolezců, silnice B146 jím vede přímo podél řeky. Vyhlídkové zálivy zvou k zastávce na fotku.', 47.5875, 14.5378, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ges%C3%A4useeingang.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ges%C3%A4useeingang.jpg"}'::text[], 1),
    (v_route, 'Leopoldsteiner See', 'Smaragdové jezero pod kolmou stěnou Seemauer, jedno z nejchladnějších a nejčistších v Rakousku. Od parkoviště je to k břehu pár minut pěšky a scenérie připomíná spíš Norsko než Štýrsko. Ideální krátká pauza před Eisenerzem.', 47.5647, 14.8681, 'https://commons.wikimedia.org/wiki/Special:FilePath/Leopoldsteiner%20See.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Leopoldsteiner%20See.jpg"}'::text[], 2),
    (v_route, 'Erzberg — rudná hora', 'Největší povrchový důl na železnou rudu ve střední Evropě — rezavě rudá pyramida s terasami, na kterých se každoročně jezdí extrémní enduro Erzbergrodeo. Vyhlídka od silnice ukazuje celé "štýrské schodiště", v sezóně jezdí po dole vyhlídkový obří truck Hauly. Pro motorkáře skoro poutní místo.', 47.5333, 14.8931, 'https://commons.wikimedia.org/wiki/Special:FilePath/Steirischer%20Erzberg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Steirischer%20Erzberg.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Erzbergbräu (Eisenerz)', 'Minipivovar s restaurací v historickém centru hornického Eisenerzu. Nefiltrované pivo vařené z místní horské vody a poctivá štýrská kuchyně — vydatný oběd před stoupáním do Präbichlu. Středověké uličky města stojí za krátkou procházku.', 47.5406, 14.8853, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eisenerz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eisenerz.jpg"}'::text[], 4),
    (v_route, 'Präbichl', 'Horské sedlo (1226 m) nad Eisenerzem s výhledem zpět na Erzberg a na vápencové stěny Hochschwabského masivu. Stoupání od Eisenerzu je série širokých, rychlých serpentin. Z sedla lze sjet do Vordernbergu a pokračovat údolím Muru, nebo se vrátit soutěskou zpět.', 47.5158, 14.9481, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A4bichl.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A4bichl.jpg"}'::text[], 5);

  -- Jižní Štýrsko – vinice a Sausal
  delete from public.routes where name = 'Jižní Štýrsko – vinice a Sausal' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Jižní Štýrsko – vinice a Sausal', 'Jižnímu Štýrsku se říká rakouské Toskánsko — a silničky vlnící se po hřebenech vinic podél slovinské hranice tomu dávají za pravdu. Okruh z Leibnitzu stoupá do Sausalu s nejvýše položenými vinicemi Rakouska, pokračuje do vinařského Gamlitzu a po slavné Jihoštýrské vinné stezce s klapajícími větrnými plašiči "klapotetz" se vrací přes renesanční mauzoleum v Ehrenhausenu. Jízdně jde o úzké, ale výborně asfaltované cesty s nekonečnou sekvencí zatáček a výhledů na obě strany hřebenů. Nejkrásnější je září a říjen v době vinobraní, kdy ale počítejte s provozem u vináren. Pozor na traktory a rosou vlhký asfalt ve stinných úsecích. Ochutnávku vína nechte spolujezdci — nulová tolerance platí i tady.', 'loop', 115, 210, 'easy',
     '[{"lat": 46.7811, "lng": 15.5450, "label": "Start: Leibnitz"}, {"lat": 46.7717, "lng": 15.5236, "label": "Schloss Seggau"}, {"lat": 46.7789, "lng": 15.4592, "label": "Kitzeck im Sausal"}, {"lat": 46.6797, "lng": 15.5556, "label": "Gamlitz"}, {"lat": 46.6486, "lng": 15.5364, "label": "Ratsch an der Weinstraße"}, {"lat": 46.7231, "lng": 15.5906, "label": "Ehrenhausen"}, {"lat": 46.7811, "lng": 15.5450, "label": "Cíl: Leibnitz"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.7811,15.5450&destination=46.7811,15.5450&travelmode=driving&waypoints=46.7717,15.5236%7C46.7789,15.4592%7C46.6797,15.5556%7C46.6486,15.5364%7C46.7231,15.5906', 'https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%BCdsteirische%20Weinstra%C3%9Fe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Leibnitz%20Hauptplatz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Seggau.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kitzeck%20im%20Sausal.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gamlitz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%BCdsteirische%20Weinstra%C3%9Fe.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mausoleum%20Ehrenhausen.jpg"}'::text[], '{"Leibnitz","Zámek Seggau","Kitzeck im Sausal","Restaurace: Sattlerhof (Gamlitz)","Jihoštýrská vinná stezka — Ratsch","Mauzoleum Ehrenhausen"}'::text[], '{"AT"}'::text[], false, 3060, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Leibnitz', 'Pohodové okresní město mezi řekami Mur a Sulm, přirozené centrum jihoštýrského vinařství. Náměstí s kavárnami je ideální na ranní kávu před okruhem. Všude kolem se zvedají první vinorodé kopce.', 46.7811, 15.5450, 'https://commons.wikimedia.org/wiki/Special:FilePath/Leibnitz%20Hauptplatz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Leibnitz%20Hauptplatz.jpg"}'::text[], 0),
    (v_route, 'Zámek Seggau', 'Bývalá rezidence štýrských biskupů na kopci nad Leibnitzem, s renesančními arkádami a jednou z nejstarších vinoték Rakouska ve sklepích ze 17. století. Z nádvoří je výhled na celé údolí Sulmu. Krátká zastávka hned na začátku trasy.', 46.7717, 15.5236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Seggau.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Seggau.jpg"}'::text[], 1),
    (v_route, 'Kitzeck im Sausal', 'Nejvýše položená vinařská obec Rakouska (564 m) trůní na hřebeni Sausalu mezi strmými vinicemi. Cesta nahoru je řetěz serpentin mezi réví a výhled sahá od Koralpe po slovinské hory. V obci je malé vinařské muzeum a řada vináren s terasami.', 46.7789, 15.4592, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitzeck%20im%20Sausal.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kitzeck%20im%20Sausal.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Sattlerhof (Gamlitz)', 'Rodinný vinařský hotel s vyhlášenou restaurací nad Gamlitzem — moderní štýrská kuchyně ze surovin od okolních farmářů, degustační sklo Sauvignonu pro spolujezdce. Rezervace se o víkendech vyplatí. Jedna z nejlepších kuchyní jižního Štýrska.', 46.6858, 15.5433, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gamlitz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gamlitz.jpg"}'::text[], 3),
    (v_route, 'Jihoštýrská vinná stezka — Ratsch', 'Nejslavnější úsek vinné stezky se vlní po hřebeni přímo nad slovinskou hranicí — vinice padají do údolí na obě strany a mezi řadami réví klapou dřevěné větrné plašiče klapotetz. Každých pár set metrů je vyhlídka nebo buschenschank. Silničářský i fotografický vrchol okruhu.', 46.6486, 15.5364, 'https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%BCdsteirische%20Weinstra%C3%9Fe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%BCdsteirische%20Weinstra%C3%9Fe.jpg"}'::text[], 4),
    (v_route, 'Mauzoleum Ehrenhausen', 'Nad městečkem Ehrenhausen stojí manýristické mauzoleum vojevůdce Ruprechta von Eggenberg z počátku 17. století — bílá stavba s kopulí viditelná z celého údolí Muru. Ke stavbě se stoupá alejí od náměstí. Poslední kulturní zastávka před návratem do Leibnitzu.', 46.7231, 15.5906, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mausoleum%20Ehrenhausen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mausoleum%20Ehrenhausen.jpg"}'::text[], 5);

  -- Villacher Alpenstraße a korutanská jezera
  delete from public.routes where name = 'Villacher Alpenstraße a korutanská jezera' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Villacher Alpenstraße a korutanská jezera', 'Kombinace panoramatické horské silnice a nejteplejších alpských jezer — to je pohodový korutanský den. Z Villachu nejprve vystoupáte po mýtné Villacher Alpenstraße na Dobratsch do výšky přes 1700 metrů, kde se pod vámi rozprostřou Julské Alpy i Karavanky, a po sjezdu vás čeká tyrkysový Faaker See, promenáda ve Veldenu na Wörthersee a výjezd k rozhledně Pyramidenkogel, nejvyšší dřevěné vyhlídkové věži světa. Alpenstraße má perfektní asfalt, široké serpentiny a vyhlídky s parkovišti každých pár kilometrů. Trasa je sjízdná od jara do podzimu, jezera lákají ke koupání od června do září. O letních víkendech počítejte kolem Wörthersee s hustším provozem. Nenáročný okruh ideální i pro dvojice.', 'loop', 135, 240, 'medium',
     '[{"lat": 46.6111, "lng": 13.8558, "label": "Start: Villach"}, {"lat": 46.6019, "lng": 13.6772, "label": "Villacher Alpenstraße — Rosstratte"}, {"lat": 46.5794, "lng": 13.9236, "label": "Faaker See"}, {"lat": 46.6122, "lng": 14.0386, "label": "Velden am Wörthersee"}, {"lat": 46.6103, "lng": 14.1439, "label": "Pyramidenkogel"}, {"lat": 46.6417, "lng": 13.8969, "label": "Burg Landskron"}, {"lat": 46.6111, "lng": 13.8558, "label": "Cíl: Villach"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.6111,13.8558&destination=46.6111,13.8558&travelmode=driving&waypoints=46.6019,13.6772%7C46.5794,13.9236%7C46.6122,14.0386%7C46.6103,14.1439%7C46.6417,13.8969', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dobratsch.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Villach%20Hauptplatz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dobratsch.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Faaker%20See.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Velden.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pyramidenkogel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Burg%20Landskron.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ossiacher%20See.jpg"}'::text[], '{"Villach","Villacher Alpenstraße — Dobratsch","Faaker See","Velden am Wörthersee","Pyramidenkogel","Burg Landskron","Restaurace: Burgrestaurant Landskron (Villach)"}'::text[], '{"AT"}'::text[], false, 3070, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Villach', 'Živé město na Drávě s italsky uvolněnou atmosférou — do Itálie i Slovinska je to odsud pár desítek kilometrů. Hlavní náměstí s kostelem sv. Jakuba je plné kaváren. Praktický start okruhu s dobrým zázemím.', 46.6111, 13.8558, 'https://commons.wikimedia.org/wiki/Special:FilePath/Villach%20Hauptplatz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Villach%20Hauptplatz.jpg"}'::text[], 0),
    (v_route, 'Villacher Alpenstraße — Dobratsch', 'Šestnáct kilometrů mýtné panoramatické silnice končí na Rosstratte v 1732 metrech pod vrcholem Dobratsche. Cestou je řada vyhlídek na Julské Alpy, Karavanky a obří skalní zřícení z roku 1348. Dobratsch je dnes přírodní park, nahoře se dá dojít k vysílači s kruhovým rozhledem.', 46.6019, 13.6772, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dobratsch.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dobratsch.jpg"}'::text[], 1),
    (v_route, 'Faaker See', 'Tyrkysové jezero pod horou Mittagskogel, jehož barvu nezachytí žádná fotka věrně. Kolem břehů vedou stinné silničky a je tu spousta pláží na rychlé osvěžení. Motorkářům je kraj důvěrně známý — u jezera se každoročně koná obří sraz European Bike Week.', 46.5794, 13.9236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Faaker%20See.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Faaker%20See.jpg"}'::text[], 2),
    (v_route, 'Velden am Wörthersee', 'Mondénní letovisko na západním břehu Wörthersee se žlutým zámkem známým z televizní obrazovky a promenádou plnou života. Jezero je nejteplejší velké alpské jezero, v létě má i 26 stupňů. Ideální na zmrzlinu a korzo podél mol.', 46.6122, 14.0386, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Velden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schloss%20Velden.jpg"}'::text[], 3),
    (v_route, 'Pyramidenkogel', 'Nejvyšší dřevěná rozhledna světa (100 m) na kopci nad jižním břehem Wörthersee. Elipsovitá věž z lepených modřínových sloupů nabízí kruhový výhled na jezera, Karavanky a Alpy — dolů se dá sjet krytou skluzavkou. Výjezd na kopec je pěkná serpentinová tečka.', 46.6103, 14.1439, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pyramidenkogel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pyramidenkogel.jpg"}'::text[], 4),
    (v_route, 'Burg Landskron', 'Hrad na skále mezi Villachem a Ossiacher See, proslulý letovými ukázkami dravců Adlerarena — orli a supi tu plachtí nad hlavami diváků s kulisou jezera. Příjezdová cesta serpentinami je krátká, ale šťavnatá. Z teras je jeden z nejhezčích výhledů Korutan.', 46.6417, 13.8969, 'https://commons.wikimedia.org/wiki/Special:FilePath/Burg%20Landskron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Burg%20Landskron.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Burgrestaurant Landskron (Villach)', 'Restaurace přímo v areálu hradu Landskron s terasou nad Ossiacher See. Korutanské speciality jako Kasnudeln a čerstvé ryby z jezera, západ slunce nad hladinou jako bonus. Důstojné zakončení okruhu pár kilometrů před Villachem.', 46.6420, 13.8975, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ossiacher%20See.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ossiacher%20See.jpg"}'::text[], 6);

  -- Wilder Kaiser a Kitzbühel
  delete from public.routes where name = 'Wilder Kaiser a Kitzbühel' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Wilder Kaiser a Kitzbühel', 'Okruh kolem zubatého masivu Wilder Kaiser spojuje pevnost nad Kufsteinem, koupání ve Walchsee a flanění po slavné barevné Vorderstadt v Kitzbühelu s výjezdem do sedla Pass Thurn nad Vysokými Taurami. Silnice jsou široké a rychlé, s plynulými oblouky podhůřím — ideální na svezení i pro méně zkušené. Zpáteční cesta přes Ellmau a Söll nabízí nejkrásnější pohledy na vápencové stěny Kaisergebirge v odpoledním světle. Trasa je sjízdná od jara do podzimu, v zimní sezóně počítejte v Kitzbühelu s davy. O víkendech bývá na B178 hustší provoz — vyplatí se vyjet brzy. Pohodový celodenní okruh s množstvím zastávek.', 'loop', 160, 240, 'medium',
     '[{"lat": 47.5847, "lng": 12.1706, "label": "Start: Kufstein"}, {"lat": 47.6511, "lng": 12.3194, "label": "Walchsee"}, {"lat": 47.5236, "lng": 12.4278, "label": "St. Johann in Tirol"}, {"lat": 47.4464, "lng": 12.3922, "label": "Kitzbühel"}, {"lat": 47.3006, "lng": 12.4200, "label": "Pass Thurn"}, {"lat": 47.5150, "lng": 12.3006, "label": "Ellmau — Wilder Kaiser"}, {"lat": 47.5847, "lng": 12.1706, "label": "Cíl: Kufstein"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.5847,12.1706&destination=47.5847,12.1706&travelmode=driving&waypoints=47.6511,12.3194%7C47.5236,12.4278%7C47.4464,12.3922%7C47.3006,12.4200%7C47.5150,12.3006', 'https://commons.wikimedia.org/wiki/Special:FilePath/Festung%20Kufstein.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Festung%20Kufstein.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Walchsee.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/St.%20Johann%20in%20Tirol.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kitzb%C3%BChel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pass%20Thurn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Wilder%20Kaiser.jpg"}'::text[], '{"Pevnost Kufstein","Walchsee","St. Johann in Tirol","Kitzbühel — Vorderstadt","Pass Thurn","Ellmau — Wilder Kaiser"}'::text[], '{"AT"}'::text[], false, 3080, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Pevnost Kufstein', 'Mohutná pevnost na skále nad Innem střeží tyrolsko-bavorskou hranici už od 13. století. Uvnitř je muzeum a Heldenorgel — největší venkovní varhany světa, které hrají každý den v poledne a jsou slyšet po celém městě. Nahoru vede šikmý výtah z centra.', 47.5847, 12.1706, 'https://commons.wikimedia.org/wiki/Special:FilePath/Festung%20Kufstein.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Festung%20Kufstein.jpg"}'::text[], 0),
    (v_route, 'Walchsee', 'Teplé rekreační jezero pod severními stěnami Zahmer Kaiser s plážemi a promenádou. Voda má v létě přes 23 stupňů, takže rychlá koupel do okruhu klidně patří. Silnice kolem jezera směrem na Kössen je příjemně zvlněná.', 47.6511, 12.3194, 'https://commons.wikimedia.org/wiki/Special:FilePath/Walchsee.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Walchsee.jpg"}'::text[], 1),
    (v_route, 'St. Johann in Tirol', 'Městečko s malovanými barokními fasádami na křižovatce údolí mezi Wilder Kaiser a Kitzbühelskými Alpami. Náměstí s kostelem Nanebevzetí Panny Marie je jako z pohlednice. Dobrá zastávka na kávu v půlce dopolední etapy.', 47.5236, 12.4278, 'https://commons.wikimedia.org/wiki/Special:FilePath/St.%20Johann%20in%20Tirol.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/St.%20Johann%20in%20Tirol.jpg"}'::text[], 2),
    (v_route, 'Kitzbühel — Vorderstadt', 'Legendární zimní metropole s barevnou středověkou Vorderstadt, kde se v lednu chodí slavit vítězství ze sjezdovky Streif na Hahnenkammu. V létě je město příjemně klidné a butiky střídají terasy kaváren. Gondolou se dá vyjet k výhledům na Kaisergebirge.', 47.4464, 12.3922, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitzb%C3%BChel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kitzb%C3%BChel.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Huberbräu Stüberl (Kitzbühel)', 'Nefalšovaná tyrolská hospoda přímo ve Vorderstadt — řízek přes talíř, gulášová polévka a čepovaný Huberbräu za ceny, které v Kitzbühelu nečekáte. Mezi místními i lyžařskými legendami jde o instituci. V poledne bývá plno, ale fronta odsýpá.', 47.4468, 12.3917, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitzb%C3%BChel%20Vorderstadt.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kitzb%C3%BChel%20Vorderstadt.jpg"}'::text[], 4),
    (v_route, 'Pass Thurn', 'Sedlo v 1274 metrech na hranici Tyrolska a Salcburska, odkud se poprvé otevře panorama zasněžených Vysokých Taur. Stoupání od Jochbergu je plynulé a rychlé, nahoře je parkoviště s výhledem. Obratiště okruhu — zpět se sjíždí stejným směrem s výhledem na Kaisergebirge.', 47.3006, 12.4200, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pass%20Thurn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pass%20Thurn.jpg"}'::text[], 5),
    (v_route, 'Ellmau — Wilder Kaiser', 'Vesnice pod jižními stěnami Wilder Kaiser, proslulá seriálem Doktor z hor. Z luk nad obcí je nejslavnější pohled na celý masiv — kolmé vápencové věže nad zelenými pastvinami. Zpáteční silnice přes Söll a Scheffau je scénická tečka okruhu.', 47.5150, 12.3006, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wilder%20Kaiser.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wilder%20Kaiser.jpg"}'::text[], 6);

  -- Mostviertel – Ötscher a Lunz am See
  delete from public.routes where name = 'Mostviertel – Ötscher a Lunz am See' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mostviertel – Ötscher a Lunz am See', 'Mostviertel, kraj moštových hrušní a železářské historie, přechází na jihu do vápencových předhůří s dominantou Ötscheru (1893 m) — a právě tímto pomezím vede tenhle okruh. Z historického Waidhofenu an der Ybbs se jede přes kovářský Ybbsitz údolím Ybbsu k jezeru Lunzer See, dál do horské vesničky Lackenhof pod Ötscherem a k bývalé kartouze v Gamingu. Silnice jsou úzké, stinné a zábavně točité, zvlášť úsek mezi Lunzem a Gamingem přes sedlo Grubberg. Nejlepší období je květen až říjen; na jaře pozor na vlhký asfalt v zářezech kolem řeky. Provoz je tu i o víkendech minimální — Mostviertel zůstává motorkářským tajným tipem. Zpět do Waidhofenu se vrací přes Scheibbs a Gresten.', 'loop', 150, 240, 'medium',
     '[{"lat": 47.9603, "lng": 14.7717, "label": "Start: Waidhofen an der Ybbs"}, {"lat": 47.9469, "lng": 14.8925, "label": "Ybbsitz"}, {"lat": 47.8531, "lng": 15.0475, "label": "Lunzer See"}, {"lat": 47.8631, "lng": 15.1417, "label": "Lackenhof am Ötscher"}, {"lat": 47.9294, "lng": 15.0894, "label": "Gaming"}, {"lat": 47.9603, "lng": 14.7717, "label": "Cíl: Waidhofen an der Ybbs"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.9603,14.7717&destination=47.9603,14.7717&travelmode=driving&waypoints=47.9469,14.8925%7C47.8531,15.0475%7C47.8631,15.1417%7C47.9294,15.0894', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lunzer%20See.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Waidhofen%20an%20der%20Ybbs.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ybbsitz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lunzer%20See.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%96tscher.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kartause%20Gaming.jpg"}'::text[], '{"Waidhofen an der Ybbs","Ybbsitz","Lunzer See","Ötscher — Lackenhof","Kartouza Gaming"}'::text[], '{"AT"}'::text[], false, 3090, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Waidhofen an der Ybbs', 'Středověké město železářů s věžemi, zamračenými měšťanskými domy a moderně zrekonstruovaným zámkem Rothschildů. Historické centrum nad řekou Ybbs patří k nejhezčím v Dolním Rakousku. Ideální start s kávou na náměstí Oberer Stadtplatz.', 47.9603, 14.7717, 'https://commons.wikimedia.org/wiki/Special:FilePath/Waidhofen%20an%20der%20Ybbs.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Waidhofen%20an%20der%20Ybbs.jpg"}'::text[], 0),
    (v_route, 'Ybbsitz', 'Vesnice na železné stezce Eisenstraße, po staletí centrum kovářského řemesla — dodnes tu fungují historické hamry a muzeum kování FeRRUM. Každé dva roky se koná mezinárodní setkání kovářů. Krátká zastávka s vůní uhlí a železa.', 47.9469, 14.8925, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ybbsitz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ybbsitz.jpg"}'::text[], 1),
    (v_route, 'Lunzer See', 'Jediné přírodní jezero Dolního Rakouska leží v tichém kotli pod Dürrensteinem. Křišťálová voda, dřevěné lázně z roku 1928 a plovoucí jeviště letního festivalu — atmosféra jak z první republiky. Osvěžující koupel v půlce trasy přijde vhod.', 47.8531, 15.0475, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lunzer%20See.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lunzer%20See.jpg"}'::text[], 2),
    (v_route, 'Ötscher — Lackenhof', 'Horská vesnička na úpatí Ötscheru, osamělého vápencového kužele, kterému se říká strážce Mostviertelu. Sedačkovou lanovkou se dá vyvézt pod vrchol; výhled sahá od Dunaje po Hochschwab. Silnička ze sedla Grubberg do Lackenhofu je řetěz lesních zatáček.', 47.8631, 15.1417, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%96tscher.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%96tscher.jpg"}'::text[], 3),
    (v_route, 'Kartouza Gaming', 'Největší kartuziánský klášter střední Evropy, založený roku 1330 habsburským vévodou Albrechtem II., dnes ožívá hotelem, muzeem a letním hudebním festivalem. Gotický kostel a rozlehlé nádvoří stojí za procházku. V klášterní restauraci Kartausenkeller vaří poctivou rakouskou klasiku — dobrá pozdní zastávka na jídlo.', 47.9294, 15.0894, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kartause%20Gaming.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kartause%20Gaming.jpg"}'::text[], 4);

  -- Lesachtal a Plöckenpass – Osttirol a Korutany
  delete from public.routes where name = 'Lesachtal a Plöckenpass – Osttirol a Korutany' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Lesachtal a Plöckenpass – Osttirol a Korutany', 'Lesachtal je nejodlehlejší údolí Rakouska — žádná železnice, žádný tranzit, jen úzká silnice vlnící se vysoko nad řekou Gail mezi Lienzskými Dolomity a Karnskými Alpami. Trasa vede z Lienzu přes sedlo u Kartitsche do bondovské vesničky Obertilliach, kolem poutní baziliky Maria Luggau a dál nekonečnou sérií zatáček, mostů a protistoupání do Kötschach-Mauthen, odkud se stoupá na hraniční Plöckenpass. Jízdně jde o technickou lahůdku — silnice je místy jen na jedno a půl auta, se slepými horizonty a spádem k řece, odměnou je naprostý klid a divoká scenérie. Nejlepší je červen až září, sedla bývají čistá od května. Pozor na protijedoucí autobusy a zemědělskou techniku. Trasa se dá vrátit údolím Gailu, nebo z Plöckenpassu pokračovat do Itálie.', 'poi', 95, 180, 'hard',
     '[{"lat": 46.8289, "lng": 12.7692, "label": "Start: Lienz"}, {"lat": 46.7261, "lng": 12.5006, "label": "Kartitsch"}, {"lat": 46.7069, "lng": 12.6156, "label": "Obertilliach"}, {"lat": 46.7169, "lng": 12.7369, "label": "Maria Luggau"}, {"lat": 46.6772, "lng": 13.0044, "label": "Kötschach-Mauthen"}, {"lat": 46.6019, "lng": 12.9439, "label": "Cíl: Plöckenpass"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.8289,12.7692&destination=46.6019,12.9439&travelmode=driving&waypoints=46.7261,12.5006%7C46.7069,12.6156%7C46.7169,12.7369%7C46.6772,13.0044', 'https://commons.wikimedia.org/wiki/Special:FilePath/Obertilliach.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lienz%20Hauptplatz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kartitsch.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Obertilliach.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Maria%20Luggau.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6tschach-Mauthen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pl%C3%B6ckenpass.jpg"}'::text[], '{"Lienz","Kartitsch a Kartitscher Sattel","Obertilliach","Maria Luggau — bazilika","Restaurace: Landhaus Kellerwand (Kötschach-Mauthen)","Plöckenpass"}'::text[], '{"AT"}'::text[], false, 3100, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lienz', 'Slunečné hlavní město Východního Tyrolska pod stěnami Lienzských Dolomit, s jižansky živým náměstím a zámkem Bruck nad městem. Poslední větší město s plným zázemím před odlehlým Lesachtalem — doplňte palivo. Kavárny na Hauptplatzu mají italské espresso.', 46.8289, 12.7692, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lienz%20Hauptplatz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lienz%20Hauptplatz.jpg"}'::text[], 0),
    (v_route, 'Kartitsch a Kartitscher Sattel', 'Přes sedlo u Kartitsche (1525 m) se z Pustertalu vjíždí do zapadlého Tiroler Gailtalu. Vesnice je první zastávkou rakouské "vesnice pomalosti" — kraje, kde se čas měří jinak. Louky, seníky a panorama Karnských Alp přes údolí.', 46.7261, 12.5006, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kartitsch.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kartitsch.jpg"}'::text[], 1),
    (v_route, 'Obertilliach', 'Dokonale zachovaná horská vesnice s dřevěnými srubovými domy, kde se natáčely scény bondovky Spectre. Památkově chráněné centrum vypadá stejně jako před sto lety. Krátká procházka mezi statky voní dřevem a senem.', 46.7069, 12.6156, 'https://commons.wikimedia.org/wiki/Special:FilePath/Obertilliach.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Obertilliach.jpg"}'::text[], 2),
    (v_route, 'Maria Luggau — bazilika', 'Poutní bazilika Panny Marie Sněžné z 16. století s cibulovou věží je duchovním srdcem Lesachtalu — poutníci sem po staletí přicházejí pěšky i z Itálie. Vedle kláštera stojí obnovené vodní mlýny na strmé stráni. Nejfotogeničtější místo údolí.', 46.7169, 12.7369, 'https://commons.wikimedia.org/wiki/Special:FilePath/Maria%20Luggau.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Maria%20Luggau.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Landhaus Kellerwand (Kötschach-Mauthen)', 'Gurmánská instituce Korutan — rodina Sonnleitner tu desítky let vaří alpsko-adrijskou kuchyni, která posbírala řadu ocenění. Kdo nechce degustační menu, najde v bistru i lehčí polední klasiku. Rezervace doporučena, zážitek zaručen.', 46.6778, 13.0036, 'https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6tschach-Mauthen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6tschach-Mauthen.jpg"}'::text[], 4),
    (v_route, 'Plöckenpass', 'Hraniční průsmyk (1357 m) mezi Korutany a italským Furlanskem, vybojovaný v horských bitvách první světové války — okolní vrcholy jsou protkané zákopy a muzejní stezkou. Stoupání z Mauthen je série ostrých serpentin s výhledy na Kellerwand. Cíl trasy; dolů do Itálie je to už jen z kopce.', 46.6019, 12.9439, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pl%C3%B6ckenpass.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pl%C3%B6ckenpass.jpg"}'::text[], 5);

end $$;
