-- MotoGo24 — katalog míst: vrcholy, rozhledny a vyhlídky (CZ/SK, Wikidata 2026-09-20)
-- ---------------------------------------------------------------------------
-- Zadání uživatele (2026-09-20): „chybí většina významných kopců, chybí
-- studánky … málo zajímavých míst v ČR a SR".
--
-- PROČ TO V KATALOGU CHYBĚLO: dávka hor z 19. 9. (20260919_poi_hills_cz_sk_*)
-- vkládala bod jen tehdy, když v okruhu ~70 m NEBYLO VŮBEC NIC. Jenže
-- u významných vrcholů skoro vždy něco je — u Sněžky leží 50 m vedle
-- wikidatový bod „Krkonošský národní park", u Klínovce rozhledna 18 m,
-- u Čerchova Kurzova rozhledna 56 m. Sněžka, Klínovec, Kralický Sněžník,
-- Blaník, Čerchov, Velká Deštná, Děčínský Sněžník ani Zvičina se proto
-- do katalogu NIKDY nedostaly.
--
-- Tahle dávka má guard postavený obráceně a správně:
--   * přeskočí bod, u kterého je v katalogu něco se STEJNÝM normalizovaným
--     názvem (public.poi_norm_name) do 250 m — tj. skutečný dvojník,
--   * přeskočí bod, u kterého je cokoli do 40 m — dva špendlíky přes sebe,
--   * body v rámci dávky jsou proti sobě odduplikované už při generování
--     (staré dávky to nedělaly vůbec — odtud „Pípalka" vedle „Křemešníku").
-- Souřadnice, foto (P18) i nadmořská výška (P2044) jsou z Wikidat; `wikidata_id`
-- se ukládá, aby šlo fotku později dohledat podle IDENTITY bodu, ne podle
-- „co je do 600 m a jmenuje se podobně".
-- Idempotentní: `delete from … where source = '<dávka>'` + vložení znovu.

delete from public.points_of_interest where source like 'wikidata-peaks-cz-sk%';

insert into public.points_of_interest
  (category, name, description, lat, lng, country, source, sort_order,
   image_url, wikidata_id, translations)
select v.category, v.name, v.description, v.lat, v.lng, v.country, v.source,
       v.sort_order, v.image_url, v.wikidata_id, v.translations::jsonb
from (values
('lookout', 'Ľadový štít', 'Vrchol na Slovensku, 2 627 m n. m..', 49.19889, 20.18222, 'SK', 'wikidata-peaks-cz-sk-peak', 7373, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%BDadov%C3%BD%20%C5%A1t%C3%ADt.jpg', 'Q344647', '{"en": {"description": "Mountain summit in Slovakia, 2 627 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 627 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 627 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 627 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 627 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 627 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 627 м над рівнем моря."}}'),
('lookout', 'Zadný Gerlach', 'Vrchol na Slovensku, 2 616 m n. m..', 49.16583, 20.13222, 'SK', 'wikidata-peaks-cz-sk-peak', 7384, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gerlach1.JPG', 'Q723698', '{"en": {"description": "Mountain summit in Slovakia, 2 616 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 616 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 616 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 616 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 616 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 616 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 616 м над рівнем моря."}}'),
('lookout', 'Posledná veža', 'Vrchol na Slovensku, 2 560 m n. m..', 49.19528, 20.20972, 'SK', 'wikidata-peaks-cz-sk-peak', 7440, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%81omnica%20a14.jpg', 'Q11826343', '{"en": {"description": "Mountain summit in Slovakia, 2 560 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 560 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 560 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 560 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 560 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 560 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 560 м над рівнем моря."}}'),
('lookout', 'Baranie rohy', 'Vrchol na Slovensku, 2 526 m n. m..', 49.20194, 20.19694, 'SK', 'wikidata-peaks-cz-sk-peak', 7474, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wielki%20Staw%20Spiski.jpg', 'Q720919', '{"en": {"description": "Mountain summit in Slovakia, 2 526 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 526 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 526 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 526 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 526 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 526 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 526 м над рівнем моря."}}'),
('lookout', 'Spišský štít', 'Vrchol na Slovensku, 2 483 m n. m..', 49.1992, 20.2006, 'SK', 'wikidata-peaks-cz-sk-peak', 7517, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wielki%20Staw%20Spiski.jpg', 'Q3493639', '{"en": {"description": "Mountain summit in Slovakia, 2 483 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 483 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 483 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 483 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 483 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 483 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 483 м над рівнем моря."}}'),
('lookout', 'Snehový štít', 'Vrchol na Slovensku, 2 465 m n. m..', 49.2024, 20.18738, 'SK', 'wikidata-peaks-cz-sk-peak', 7536, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sniezny%20Szczyt.jpg', 'Q9395715', '{"en": {"description": "Mountain summit in Slovakia, 2 465 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 465 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 465 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 465 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 465 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 465 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 465 м над рівнем моря."}}'),
('lookout', 'Prostredný hrot', 'Vrchol na Slovensku, 2 441 m n. m..', 49.18497, 20.19428, 'SK', 'wikidata-peaks-cz-sk-peak', 7559, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prostredn%C3%BD%20hrot%2C%20Vysok%C3%A9%20Tatry.JPG', 'Q3502652', '{"en": {"description": "Mountain summit in Slovakia, 2 441 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 441 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 441 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 441 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 441 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 441 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 441 м над рівнем моря."}}'),
('lookout', 'Čierny štít', 'Vrchol na Slovensku, 2 429 m n. m..', 49.20528, 20.20083, 'SK', 'wikidata-peaks-cz-sk-peak', 7571, 'https://commons.wikimedia.org/wiki/Special:FilePath/Czarny%20Szczyt.jpg', 'Q11691997', '{"en": {"description": "Mountain summit in Slovakia, 2 429 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 429 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 429 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 429 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 429 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 429 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 429 м над рівнем моря."}}'),
('lookout', 'Litvorový štít', 'Vrchol na Slovensku, 2 423 m n. m..', 49.17083, 20.12944, 'SK', 'wikidata-peaks-cz-sk-peak', 7577, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velicky%20stit%20from%20Polsky%20hreben.jpg', 'Q11762037', '{"en": {"description": "Mountain summit in Slovakia, 2 423 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 423 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 423 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 423 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 423 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 423 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 423 м над рівнем моря."}}'),
('lookout', 'Kačací štít', 'Vrchol na Slovensku, 2 401 m n. m..', 49.16611, 20.11889, 'SK', 'wikidata-peaks-cz-sk-peak', 7600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Batizovsky%20stit%20over%20Batizovske%20pleso.jpg', 'Q11733230', '{"en": {"description": "Mountain summit in Slovakia, 2 401 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 401 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 401 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 401 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 401 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 401 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 401 м над рівнем моря."}}'),
('lookout', 'Diablovina', 'Vrchol na Slovensku, 2 390 m n. m..', 49.16508, 20.05083, 'SK', 'wikidata-peaks-cz-sk-peak', 7610, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gra%C5%84%20Baszt%20a2.jpg', 'Q9206849', '{"en": {"description": "Mountain summit in Slovakia, 2 390 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 390 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 390 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 390 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 390 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 390 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 390 м над рівнем моря."}}'),
('lookout', 'Zadná Bašta', 'Vrchol na Slovensku, 2 379 m n. m..', 49.16574, 20.05138, 'SK', 'wikidata-peaks-cz-sk-peak', 7621, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gra%C5%84%20Baszt%20a6.jpg', 'Q9385716', '{"en": {"description": "Mountain summit in Slovakia, 2 379 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 379 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 379 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 379 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 379 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 379 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 379 м над рівнем моря."}}'),
('lookout', 'Divá veža', 'Vrchol na Slovensku, 2 373 m n. m..', 49.17833, 20.14417, 'SK', 'wikidata-peaks-cz-sk-peak', 7627, 'https://commons.wikimedia.org/wiki/Special:FilePath/Diva%20veza%20from%20Polsky%20hreben.jpg', 'Q9248893', '{"en": {"description": "Mountain summit in Slovakia, 2 373 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 373 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 373 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 373 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 373 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 373 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 373 м над рівнем моря."}}'),
('lookout', 'Kôprovský štít', 'Vrchol na Slovensku, 2 363 m n. m..', 49.18222, 20.04833, 'SK', 'wikidata-peaks-cz-sk-peak', 7637, 'https://commons.wikimedia.org/wiki/Special:FilePath/Koprowy.jpg', 'Q723092', '{"en": {"description": "Mountain summit in Slovakia, 2 363 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 363 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 363 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 363 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 363 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 363 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 363 м над рівнем моря."}}'),
('lookout', 'Ostrý štít', 'Vrchol na Slovensku, 2 360 m n. m..', 49.18889, 20.17556, 'SK', 'wikidata-peaks-cz-sk-peak', 7640, 'https://commons.wikimedia.org/wiki/Special:FilePath/Staw%20w%20Dolinie%20Starole%C5%9Bnej%20a1.jpg', 'Q11800791', '{"en": {"description": "Mountain summit in Slovakia, 2 360 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 360 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 360 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 360 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 360 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 360 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 360 м над рівнем моря."}}'),
('lookout', 'Huncovský štít', 'Vrchol na Slovensku, 2 359 m n. m..', 49.1979, 20.2261, 'SK', 'wikidata-peaks-cz-sk-peak', 7641, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lomnicky%20stit%20001.jpg', 'Q9294978', '{"en": {"description": "Mountain summit in Slovakia, 2 359 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 359 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 359 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 359 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 359 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 359 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 359 м над рівнем моря."}}'),
('lookout', 'Hlinská veža', 'Vrchol na Slovensku, 2 330 m n. m..', 49.1708, 20.0475, 'SK', 'wikidata-peaks-cz-sk-peak', 7670, 'https://commons.wikimedia.org/wiki/Special:FilePath/Koprowa%20Prze%C5%82%C4%99cz%20a3.jpg', 'Q9293142', '{"en": {"description": "Mountain summit in Slovakia, 2 330 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 330 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 330 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 330 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 330 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 330 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 330 м над рівнем моря."}}'),
('lookout', 'Svinica', 'Vrchol na Slovensku, 2 302 m n. m..', 49.21961, 20.00875, 'SK', 'wikidata-peaks-cz-sk-peak', 7698, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%9Awinica%20a3.jpg', 'Q2741323', '{"en": {"description": "Mountain summit in Slovakia, 2 302 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 302 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 302 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 302 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 302 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 302 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 302 м над рівнем моря."}}'),
('lookout', 'Spádová kopa', 'Vrchol na Slovensku, 2 251 m n. m..', 49.1858, 20.0872, 'SK', 'wikidata-peaks-cz-sk-peak', 7749, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dolina%20Spadowa%20a3.jpg', 'Q9340000', '{"en": {"description": "Mountain summit in Slovakia, 2 251 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 251 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 251 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 251 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 251 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 251 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 251 м над рівнем моря."}}'),
('lookout', 'Žltá stena', 'Vrchol na Slovensku, 2 169 m n. m..', 49.1875, 20.1969, 'SK', 'wikidata-peaks-cz-sk-peak', 7831, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BB%C3%B3%C5%82ta%20%C5%9Aciana%20a2.jpg', 'Q9397945', '{"en": {"description": "Mountain summit in Slovakia, 2 169 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 169 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 169 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 169 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 169 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 169 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 169 м над рівнем моря."}}'),
('lookout', 'Hrubá kopa', 'Vrchol na Slovensku, 2 166 m n. m..', 49.2, 19.72383, 'SK', 'wikidata-peaks-cz-sk-peak', 7834, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hruba%20Kopa%20a1.jpg', 'Q3281051', '{"en": {"description": "Mountain summit in Slovakia, 2 166 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 166 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 166 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 166 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 166 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 166 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 166 м над рівнем моря."}}'),
('lookout', 'Salatín', 'Vrchol na Slovensku, 2 048 m n. m..', 49.21361, 19.68583, 'SK', 'wikidata-peaks-cz-sk-peak', 7953, 'https://commons.wikimedia.org/wiki/Special:FilePath/Salatyny%20a1.jpg', 'Q2855194', '{"en": {"description": "Mountain summit in Slovakia, 2 048 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 2 048 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 2 048 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 2 048 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 2 048 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 2 048 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 2 048 м над рівнем моря."}}'),
('lookout', 'Sivý vrch', 'Vrchol na Slovensku, 1 804 m n. m..', 49.21109, 19.64188, 'SK', 'wikidata-peaks-cz-sk-peak', 8196, 'https://commons.wikimedia.org/wiki/Special:FilePath/Path%20to%20the%20Siv%C3%BD%20vrch%20-%20panoramio%20%282%29.jpg', 'Q3509435', '{"en": {"description": "Mountain summit in Slovakia, 1 804 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 804 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 804 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 804 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 804 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 804 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 804 м над рівнем моря."}}'),
('lookout', 'Hromové', 'Vrchol na Slovensku, 1 636 m n. m..', 49.19083, 19.06, 'SK', 'wikidata-peaks-cz-sk-peak', 8364, 'https://commons.wikimedia.org/wiki/Special:FilePath/N%C3%A1rodn%C3%AD%20park%20Mal%C3%A1%20Fatra%2C%20v%C3%BDhled%20z%20Chlebu%20%282%29.JPG', 'Q9294458', '{"en": {"description": "Mountain summit in Slovakia, 1 636 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 636 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 636 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 636 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 636 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 636 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 636 м над рівнем моря."}}'),
('lookout', 'Lysec', 'Vrchol na Slovensku, 1 381 m n. m..', 48.99636, 19.06917, 'SK', 'wikidata-peaks-cz-sk-peak', 8620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lysec%20-%20vrchol%201381%20m.n.m%20-%20panoramio.jpg', 'Q3493793', '{"en": {"description": "Mountain summit in Slovakia, 1 381 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 381 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 381 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 381 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 381 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 381 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 381 м над рівнем моря."}}'),
('lookout', 'Kľak', 'Vrchol na Slovensku, 1 352 m n. m..', 48.98139, 18.64083, 'SK', 'wikidata-peaks-cz-sk-peak', 8649, 'https://commons.wikimedia.org/wiki/Special:FilePath/Klak%20summit.jpg', 'Q1982470', '{"en": {"description": "Mountain summit in Slovakia, 1 352 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 352 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 352 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 352 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 352 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 352 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 352 м над рівнем моря."}}'),
('lookout', 'Hrčova Kečka', 'Vrchol na Slovensku, 1 226 m n. m..', 49.25, 19.18333, 'SK', 'wikidata-peaks-cz-sk-peak', 8775, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hr%C4%8Dova%20Ke%C4%8Dka%20MF3.jpg', 'Q15919629', '{"en": {"description": "Mountain summit in Slovakia, 1 226 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 226 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 226 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 226 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 226 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 226 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 226 м над рівнем моря."}}'),
('lookout', 'Jarabá skala', 'Vrchol na Slovensku, 1 199 m n. m..', 49.1028, 22.4439, 'SK', 'wikidata-peaks-cz-sk-peak', 8801, 'https://commons.wikimedia.org/wiki/Special:FilePath/Riaba%20skala%2003.JPG', 'Q9310198', '{"en": {"description": "Mountain summit in Slovakia, 1 199 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 199 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 199 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 199 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 199 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 199 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 199 м над рівнем моря."}}'),
('lookout', 'Kozol', 'Vrchol na Slovensku, 1 119 m n. m..', 49.11407, 18.76263, 'SK', 'wikidata-peaks-cz-sk-peak', 8881, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kozol%20-%20panoramio.jpg', 'Q12769627', '{"en": {"description": "Mountain summit in Slovakia, 1 119 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 119 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 119 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 119 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 119 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 119 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 119 м над рівнем моря."}}'),
('lookout', 'Kruhliak', 'Vrchol na Slovensku, 1 101 m n. m..', 49.1469, 22.3692, 'SK', 'wikidata-peaks-cz-sk-peak', 8899, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kruhliak%2008.jpg', 'Q11797129', '{"en": {"description": "Mountain summit in Slovakia, 1 101 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 101 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 101 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 101 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 101 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 101 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 101 м над рівнем моря."}}'),
('lookout', 'Veľký Polom', 'Vrchol na Slovensku, 1 067 m n. m..', 49.5058, 18.6711, 'SK', 'wikidata-peaks-cz-sk-peak', 8933, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%BD%20Polom.jpg', 'Q3507306', '{"en": {"description": "Mountain summit in Slovakia, 1 067 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 067 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 067 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 067 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 067 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 067 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 067 м над рівнем моря."}}'),
('lookout', 'Malý Polom', 'Vrchol na Slovensku, 1 061 m n. m..', 49.5097, 18.5981, 'SK', 'wikidata-peaks-cz-sk-peak', 8939, 'https://commons.wikimedia.org/wiki/Special:FilePath/Maly%20Polom.jpg', 'Q10954288', '{"en": {"description": "Mountain summit in Slovakia, 1 061 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 061 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 061 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 061 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 061 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 061 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 061 м над рівнем моря."}}'),
('lookout', 'Sninský kameň', 'Vrchol na Slovensku, 1 006 m n. m..', 48.92949, 22.18959, 'SK', 'wikidata-peaks-cz-sk-peak', 8994, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sninsk%C3%BD%20kame%C5%88%20047.jpg', 'Q2975694', '{"en": {"description": "Mountain summit in Slovakia, 1 006 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 006 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 006 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 006 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 006 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 006 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 006 м над рівнем моря."}}'),
('lookout', 'Katova skala', 'Vrchol na Slovensku, 927 m n. m..', 49.0575, 19.04056, 'SK', 'wikidata-peaks-cz-sk-peak', 9073, 'https://commons.wikimedia.org/wiki/Special:FilePath/Katova%20skala%20WF10%20%282%29.jpg', 'Q86672892', '{"en": {"description": "Mountain summit in Slovakia, 927 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 927 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 927 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 927 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 927 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 927 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 927 м над рівнем моря."}}'),
('lookout', 'Makyta', 'Vrchol na Slovensku, 923 m n. m..', 49.26083, 18.16306, 'SK', 'wikidata-peaks-cz-sk-peak', 9077, 'https://commons.wikimedia.org/wiki/Special:FilePath/Makyta.jpg', 'Q1886573', '{"en": {"description": "Mountain summit in Slovakia, 923 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 923 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 923 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 923 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 923 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 923 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 923 м над рівнем моря."}}'),
('lookout', 'Javorské', 'Vrchol na Slovensku, 860 m n. m..', 49.45242, 18.86363, 'SK', 'wikidata-peaks-cz-sk-peak', 9140, 'https://commons.wikimedia.org/wiki/Special:FilePath/Javorsk%C3%A9%2C%20Slovakia%2C%20spruce%20in%20December%202015.jpg', 'Q21708778', '{"en": {"description": "Mountain summit in Slovakia, 860 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 860 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 860 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 860 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 860 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 860 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 860 м над рівнем моря."}}'),
('lookout', 'Sivec', 'Vrchol na Slovensku, 781 m n. m..', 48.84833, 21.1, 'SK', 'wikidata-peaks-cz-sk-peak', 9220, 'https://commons.wikimedia.org/wiki/Special:FilePath/%28ms%29VNR14.jpg', 'Q31566934', '{"en": {"description": "Mountain summit in Slovakia, 781 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 781 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 781 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 781 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 781 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 781 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 781 м над рівнем моря."}}'),
('lookout', 'Ostrý vrch', 'Vrchol na Slovensku, 768 m n. m..', 48.84772, 18.12495, 'SK', 'wikidata-peaks-cz-sk-peak', 9233, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ostry%20vrch%20pano.jpg', 'Q12773212', '{"en": {"description": "Mountain summit in Slovakia, 768 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 768 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 768 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 768 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 768 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 768 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 768 м над рівнем моря."}}'),
('lookout', 'Vysoká', 'Vrchol na Slovensku, 754 m n. m..', 48.41611, 17.2175, 'SK', 'wikidata-peaks-cz-sk-peak', 9246, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vysoka%20from%20Plavecky%20hrad%2002.jpg', 'Q2031115', '{"en": {"description": "Mountain summit in Slovakia, 754 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 754 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 754 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 754 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 754 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 754 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 754 м над рівнем моря."}}'),
('lookout', 'Vitkuľa', 'Vrchol na Slovensku, 736 m n. m..', 49.4117, 20.4785, 'SK', 'wikidata-peaks-cz-sk-peak', 9264, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szafran%C3%B3wka%20P28.jpg', 'Q9375571', '{"en": {"description": "Mountain summit in Slovakia, 736 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 736 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 736 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 736 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 736 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 736 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 736 м над рівнем моря."}}'),
('lookout', 'Klokoč', 'Vrchol na Slovensku, 661 m n. m..', 48.47441, 17.31208, 'SK', 'wikidata-peaks-cz-sk-peak', 9339, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kloko%C4%8D%2C%20Mal%C3%A9%20Karpaty.jpg', 'Q31267043', '{"en": {"description": "Mountain summit in Slovakia, 661 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 661 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 661 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 661 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 661 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 661 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 661 м над рівнем моря."}}'),
('lookout', 'Jankov vŕšok', 'Vrchol na Slovensku, 533 m n. m..', 48.73917, 18.36611, 'SK', 'wikidata-peaks-cz-sk-peak', 9467, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pam%C3%A4tn%C3%ADk%20SNP%20Jankov%20V%C5%95%C5%A1ok.jpg', 'Q116986470', '{"en": {"description": "Mountain summit in Slovakia, 533 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 533 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 533 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 533 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 533 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 533 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 533 м над рівнем моря."}}'),
('lookout', 'Dúň', 'Vrchol na Slovensku, 514 m n. m..', 48.41083, 18.22222, 'SK', 'wikidata-peaks-cz-sk-peak', 9487, 'https://commons.wikimedia.org/wiki/Special:FilePath/G%C3%ADmes%202014%20-040.JPG', 'Q110221547', '{"en": {"description": "Mountain summit in Slovakia, 514 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 514 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 514 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 514 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 514 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 514 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 514 м над рівнем моря."}}'),
('lookout', 'Kamzík', 'Vrchol na Slovensku, 439 m n. m..', 48.18167, 17.09361, 'SK', 'wikidata-peaks-cz-sk-peak', 9561, 'https://commons.wikimedia.org/wiki/Special:FilePath/NA%20KOLIBE%20SI%20ASI%20ZAPLATILI%20SLNE%C4%8CN%C3%89%20L%C3%9A%C4%8CE%20-%20panoramio.jpg', 'Q848283', '{"en": {"description": "Mountain summit in Slovakia, 439 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 439 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 439 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 439 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 439 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 439 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 439 м над рівнем моря."}}'),
('lookout', 'Brdárova zvonica', 'Vrchol na Slovensku.', 49.1903, 19.9303, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dolina%20Cicha%20a%2011.jpg', 'Q9179135', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Chmelový maják v Žatci', 'Rozhledna v Česku.', 50.32469, 13.54544, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDatec%20Chmela%C5%99sk%C3%A9%20muzeum%20v%C4%9B%C5%BE.jpg', 'Q141500508', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'Chmúrna ihla', 'Vrchol na Slovensku.', 49.1825, 20.1986, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tatry%20Koscioly.jpg', 'Q9192455', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Chmúrna veža', 'Vrchol na Slovensku.', 49.1831, 20.1969, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tatry%20Koscioly.jpg', 'Q11690581', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Diel (Javorníky)', 'Vrchol na Slovensku.', 49.38642, 18.82495, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozh%C4%BEad%C5%88a%20u%20Jantov%2C%20Kr%C3%A1sno%20nad%20Kysucou%2C%20Slovensko%2006.jpg', 'Q117286096', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Dromedárov chrbát', 'Vrchol na Slovensku.', 49.1589, 20.1361, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Slovakia%20High%20Tatras%2075.jpg', 'Q9367020', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Dvojitá veža', 'Vrchol na Slovensku.', 49.1617, 20.1586, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Granaty%20Wielickie%202.jpg', 'Q9213191', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Hrubá kopa', 'Vrchol na Slovensku.', 49.1794, 20.00563, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mur%20Hrubego%20a1.jpg', 'Q9265869', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Humenec', 'Vrchol na Slovensku.', 48.86222, 21.17056, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Poh%C4%BEad%20na%20Humenec%20-%20panoramio.jpg', 'Q31567217', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Hýlačka', 'Rozhledna v Česku.', 49.39, 14.64, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hylacka%202015.JPG', 'Q113949957', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'Jamská kopa', 'Vrchol na Slovensku.', 49.1545, 20.0121, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skryty%20Stawek.jpg', 'Q16978676', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Javorinka', 'Vrchol na Slovensku.', 49.30972, 19.14889, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Javorinka%20MF4.jpg', 'Q108745015', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Kamenný vrch', 'Rozhledna v Česku.', 49.18284, 16.55599, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Kamenny%20vrch%201.jpg', 'Q12027847', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'Liptovská veža', 'Vrchol na Slovensku.', 49.1585, 20.02117, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ostra%20and%20Ostra%20veza%20from%20Furkotska%20dolina.jpg', 'Q16572292', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Malá Granátová veža', 'Vrchol na Slovensku.', 49.1661, 20.1575, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Granaty%20Wielickie%201.jpg', 'Q11772049', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Malá Končistá', 'Vrchol na Slovensku.', 49.1589, 20.1144, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gran%20Konczystej.jpg', 'Q11772066', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Malý Baboš', 'Vrchol na Slovensku.', 49.245, 20.1472, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Babos.jpg', 'Q9163805', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Malý Kolový štít', 'Vrchol na Slovensku.', 49.2125, 20.2046, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jastrzebia%20Dolina.jpg', 'Q11772559', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Malý Mlynár', 'Vrchol na Slovensku.', 49.1992, 20.1017, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ma%C5%82y%20M%C5%82ynarz%20a1.jpg', 'Q11772569', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Pekelník', 'Vrchol na Slovensku.', 49.1644, 20.0517, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gra%C5%84%20Baszt%20a12.jpg', 'Q11816524', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Piesočná', 'Vrchol na Slovensku.', 49.09214, 19.34338, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pieso%C4%8Dn%C3%A1%2C%20Liskovsk%C3%A1%20jasky%C5%88a.jpg', 'Q106341605', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Predná bašta', 'Vrchol na Slovensku.', 49.1587, 20.0549, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Satan%20and%20Predna%20Basta%20and%20Mala%20Basta.jpg', 'Q11826378', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Rozhledna Vysoká', 'Rozhledna v Česku.', 49.94266, 15.18961, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Vysok%C3%A1%20u%20Miskovic%20%281%29.jpg', 'Q110292191', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'Snehová strážnica', 'Vrchol na Slovensku.', 49.2028, 20.1876, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dolina%20Pieciu%20Stawow%20Spiskich%2C%20Sniezny%20Szczyt%20podpisany.jpg', 'Q17619438', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Snežné kopy', 'Vrchol na Slovensku.', 49.1689, 20.1122, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dolina%20Kacza%20a2.jpg', 'Q260733', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Strelecké polia', 'Vrchol na Slovensku.', 49.18639, 20.18111, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ni%C5%BEn%C3%A9%20Streleck%C3%A9%20ples%C3%A1.JPG', 'Q9347136', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Stávok', 'Vrchol na Slovensku.', 49.4372, 21.5964, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Baranie%20Stavok%2C%20na%20szczycie.jpg', 'Q9165204', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Tatarkova próba', 'Vrchol na Slovensku.', 49.16546, 20.13216, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Altaj%20Tatroj%20Gerlach.JPG', 'Q65249833', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Tichý vrch', 'Vrchol na Slovensku.', 49.20097, 20.00516, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cichy%20Wierch.jpg', 'Q11690548', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Vyhlídkový pavilon v Malé Fürstenberské zahradě', 'Rozhledna v Česku.', 50.09161, 14.40608, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praha%20Mala%20Strana%20Mala%20Furstenberska%20zahrada%20vezicka.jpg', 'Q123245038', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'Vyšná Barania strážnica', 'Vrchol na Slovensku.', 49.2025, 20.1964, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jastrzebia%20Dolina.jpg', 'Q9380614', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Zlomisková veža', 'Vrchol na Slovensku.', 49.1636, 20.0958, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Siarka%C5%84ska%20Gra%C5%84%20a2.jpg', 'Q9393326', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Západná Slavkovská veža', 'Vrchol na Slovensku.', 49.1717, 20.1611, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dolina%20Starole%C5%9Bna%2C%20Nowole%C5%9Bna%20Gra%C5%84%20podpisana.jpg', 'Q9385723', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'vyhlídková věž Mikulčice', 'Rozhledna v Česku.', 48.80433, 17.08564, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mikul%C4%8Dice%20-%20velkomoravsk%C3%A9%20hradisko%20%28stav%20duben%202023%29%20%2812%29.jpg', 'Q131763295', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'vyhlídková věž v Lesůňkách', 'Rozhledna v Česku.', 49.10719, 15.84473, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Overview%202%20of%20observation%20tower%20in%20Les%C5%AF%C5%88ky%2C%20T%C5%99eb%C3%AD%C4%8D%20District.jpg', 'Q123258654', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'věž kostela svatého Ducha', 'Rozhledna v Česku.', 49.18301, 15.45454, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tower%20of%20the%20Holy%20Spirit%2C%20Telc%20%E6%B3%B0%E7%88%BE%E5%A5%87%E8%81%96%E9%9D%88%E9%90%98%E5%A1%94%20-%20panoramio.jpg', 'Q136722483', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'Ľadový hrebeň', 'Vrchol na Slovensku.', 49.19214, 20.19024, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Widok%20z%20Czerwonej%20%C5%81awki%20a1.jpg', 'Q11762343', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Řežabinec', 'Rozhledna v Česku.', 49.25348, 14.09759, 'CZ', 'wikidata-peaks-cz-sk-tower', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98e%C5%BEabinec2009-pozorovatelna1.jpg', 'Q96328974', '{"en": {"description": "Observation tower in Czechia."}, "de": {"description": "Aussichtsturm in Tschechien."}, "pl": {"description": "Wieża widokowa w Czechach."}, "nl": {"description": "Uitkijktoren in Tsjechië."}, "es": {"description": "Torre mirador en Chequia."}, "fr": {"description": "Tour panoramique en Tchéquie."}, "uk": {"description": "Оглядова вежа у Чехії."}}'),
('lookout', 'Šarkanica', 'Vrchol na Slovensku.', 48.71278, 19.96556, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mur%C3%A1nska%20planina%2C%20%C5%A0arkanica%2C%20v%C3%BDchod%2001.jpg', 'Q121260462', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Tlstý javor', 'Vrchol na Slovensku, 1 068 m n. m..', 48.68389, 19.64083, 'SK', 'wikidata-peaks-cz-sk-peak', 8932, null, 'Q12777575', '{"en": {"description": "Mountain summit in Slovakia, 1 068 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 1 068 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 1 068 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 1 068 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 1 068 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 1 068 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 1 068 м над рівнем моря."}}'),
('lookout', 'Gerlašská skala', 'Vrchol na Slovensku, 752 m n. m..', 48.65778, 20.42306, 'SK', 'wikidata-peaks-cz-sk-peak', 9248, null, 'Q122680444', '{"en": {"description": "Mountain summit in Slovakia, 752 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 752 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 752 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 752 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 752 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 752 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 752 м над рівнем моря."}}'),
('lookout', 'Jurčová', 'Vrchol na Slovensku, 670 m n. m..', 49.38864, 19.62472, 'SK', 'wikidata-peaks-cz-sk-peak', 9330, null, 'Q48841541', '{"en": {"description": "Mountain summit in Slovakia, 670 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 670 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 670 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 670 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 670 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 670 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 670 м над рівнем моря."}}'),
('lookout', 'Malkovská hôrka', 'Vrchol na Slovensku, 481 m n. m..', 48.96959, 21.21336, 'SK', 'wikidata-peaks-cz-sk-peak', 9519, null, 'Q88164487', '{"en": {"description": "Mountain summit in Slovakia, 481 m above sea level."}, "de": {"description": "Berggipfel in der Slowakei, 481 m ü. M.."}, "pl": {"description": "Szczyt w Słowacji, 481 m n.p.m.."}, "nl": {"description": "Bergtop in Slowakije, 481 m boven zeeniveau."}, "es": {"description": "Cumbre en Eslovaquia, 481 m sobre el nivel del mar."}, "fr": {"description": "Sommet en Slovaquie, 481 m d’altitude."}, "uk": {"description": "Вершина у Словаччині, 481 м над рівнем моря."}}'),
('lookout', 'Babia hora', 'Vrchol na Slovensku.', 48.74418, 17.97715, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q134608976', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Bieličie', 'Vrchol na Slovensku.', 49.0967, 19.0558, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31565539', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Drža', 'Vrchol na Slovensku.', 48.445, 18.20083, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31562106', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Ipeľ', 'Vrchol na Slovensku.', 48.6, 19.65, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31563321', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Kačacia veža', 'Vrchol na Slovensku.', 49.17839, 20.10507, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q11733191', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Klin', 'Vrchol na Slovensku.', 49.21139, 19.5325, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31562704', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Kosmatec', 'Vrchol na Slovensku.', 48.8768, 22.3944, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31554824', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Kozlisko', 'Vrchol na Slovensku.', 48.2725, 17.09333, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31266953', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Ploská', 'Vrchol na Slovensku.', 48.4314, 18.2532, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31560305', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Rožok', 'Vrchol na Slovensku.', 48.96667, 22.46667, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31553173', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Strčihlava', 'Vrchol na Slovensku.', 49.19854, 18.14927, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q23806672', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Tegart', 'Vrchol na Slovensku.', 48.6158, 20.7158, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31552198', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Vartovka', 'Vrchol na Slovensku.', 48.71667, 19.15, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31557876', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}'),
('lookout', 'Čierna hora', 'Vrchol na Slovensku.', 49.16389, 20.80278, 'SK', 'wikidata-peaks-cz-sk-peak', 10000, null, 'Q31556033', '{"en": {"description": "Mountain summit in Slovakia."}, "de": {"description": "Berggipfel in der Slowakei."}, "pl": {"description": "Szczyt w Słowacji."}, "nl": {"description": "Bergtop in Slowakije."}, "es": {"description": "Cumbre en Eslovaquia."}, "fr": {"description": "Sommet en Slovaquie."}, "uk": {"description": "Вершина у Словаччині."}}')
) as v(category, name, description, lat, lng, country, source, sort_order,
       image_url, wikidata_id, translations)
where not exists (
  select 1 from public.points_of_interest p
   where p.lat between v.lat - 0.00225 and v.lat + 0.00225
     and p.lng between v.lng - 0.0035 and v.lng + 0.0035
     and ( -- dvojník: stejný normalizovaný název do ~250 m
           (p.norm_name = public.poi_norm_name(v.name)
            and 111320.0 * sqrt(power(p.lat - v.lat, 2)
                + power((p.lng - v.lng) * cos(radians(v.lat)), 2)) <= 250)
        or -- cokoli prakticky na stejném pixelu
           (111320.0 * sqrt(power(p.lat - v.lat, 2)
                + power((p.lng - v.lng) * cos(radians(v.lat)), 2)) <= 40)
     )
);
