-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — Jižní Čechy (CZ)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Zámek Hluboká a Vltavotýnsko
  delete from public.routes where name = 'Zámek Hluboká a Vltavotýnsko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Zámek Hluboká a Vltavotýnsko', 'Pohodový okruh z Českých Budějovic k nejromantičtějšímu zámku Čech a dál po pravém břehu Vltavy na sever. Silnice podél řeky přes Purkarec do Týna nad Vltavou se vlní mezi lesy a nabízí plynulé, nenáročné tempo — ideální první vyjížďka sezóny nebo podvečerní okruh. Po prohlídce hluboké bílé pohádky si dopřejte klid loveckého zámečku Ohrada a v Kolodějích nad Lužnicí barokní perlu Mitrowicz. Nejlépe od dubna do října; v létě počítejte kolem Hluboké s hustším provozem a cyklisty u řeky. Povrch je vesměs kvalitní, jen okreska přes Purkarec má pár záplatovaných úseků.', 'loop', 85, 150, 'easy',
     '[{"lat": 48.9745, "lng": 14.4743, "label": "Start: České Budějovice"}, {"lat": 49.0510, "lng": 14.4444, "label": "Hluboká nad Vltavou"}, {"lat": 49.1224, "lng": 14.4536, "label": "Purkarec"}, {"lat": 49.2235, "lng": 14.4208, "label": "Týn nad Vltavou"}, {"lat": 49.2110, "lng": 14.4670, "label": "Koloděje nad Lužnicí"}, {"lat": 48.9745, "lng": 14.4743, "label": "Cíl: České Budějovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9745,14.4743&destination=48.9745,14.4743&travelmode=driving&waypoints=49.0510,14.4444%7C49.1224,14.4536%7C49.2235,14.4208%7C49.2110,14.4670', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hluboka%20castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hluboka%20castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Loveck%C3%BD%20z%C3%A1mek%20Ohrada%20-%20pr%C5%AF%C4%8Del%C3%AD.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%BDn%20nad%20Vltavou.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek%20Mitrowicz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%20Samson-Brunnen%20159.jpg"}'::text[], '{"Zámek Hluboká nad Vltavou","Lovecký zámek Ohrada","Týn nad Vltavou – náměstí Míru","Zámek Mitrowicz (Koloděje nad Lužnicí)","Restaurace: Masné krámy (České Budějovice)"}'::text[], '{"CZ"}'::text[], false, 2010, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Hluboká nad Vltavou', 'Bílý novogotický zámek po vzoru anglického Windsoru, nejnavštěvovanější v Česku. Ze zámecké terasy je krásný výhled do vltavské nivy a parkoviště pod zámkem zvládne i plně naložený stroj. Prohlídku stihnete za hodinu, procházku parkem za dvacet minut.', 49.0510, 14.4444, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hluboka%20castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hluboka%20castle.jpg"}'::text[], 0),
    (v_route, 'Lovecký zámek Ohrada', 'Barokní lovecký zámeček kousek pod Hlubokou, dnes muzeum lesnictví, myslivosti a rybářství. Tiché místo u Munického rybníka s výhledem na hlubocký zámek nad hladinou. Ideální krátká zastávka na protažení nohou hned na začátku okruhu.', 49.0430, 14.4396, 'https://commons.wikimedia.org/wiki/Special:FilePath/Loveck%C3%BD%20z%C3%A1mek%20Ohrada%20-%20pr%C5%AF%C4%8Del%C3%AD.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Loveck%C3%BD%20z%C3%A1mek%20Ohrada%20-%20pr%C5%AF%C4%8Del%C3%AD.jpg"}'::text[], 1),
    (v_route, 'Týn nad Vltavou – náměstí Míru', 'Malebné městečko na soutoku Vltavy a Lužnice s renesančními štíty na náměstí a nábřežní promenádou. Po klikaté okresce od Purkarce sem dojedete lesy prakticky bez provozu. Zaparkujte přímo na náměstí a dejte si kávu s výhledem na řeku.', 49.2235, 14.4208, 'https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%BDn%20nad%20Vltavou.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%BDn%20nad%20Vltavou.JPG"}'::text[], 2),
    (v_route, 'Zámek Mitrowicz (Koloděje nad Lužnicí)', 'Citlivě zrekonstruovaný barokní zámeček na břehu Lužnice, kulisa mnoha filmů a svateb. Areál s kaplí a zahradou je přístupný sezónně, i zvenku ale stojí za krátkou fotopauzu. Od Týna jsou to jen tři kilometry.', 49.2110, 14.4670, 'https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek%20Mitrowicz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Z%C3%A1mek%20Mitrowicz.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Masné krámy (České Budějovice)', 'Legendární budějovická pivnice v gotické tržnici pár kroků od náměstí Přemysla Otakara II. Poctivá česká kuchyně a dokonale ošetřený Budvar — důstojná tečka za okruhem. V sezóně počítejte s plno, rezervace se vyplatí.', 48.9750, 14.4712, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%20Samson-Brunnen%20159.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%20Samson-Brunnen%20159.jpg"}'::text[], 4);

  -- Perly Vltavy – Český Krumlov a Rožmberk
  delete from public.routes where name = 'Perly Vltavy – Český Krumlov a Rožmberk' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Perly Vltavy – Český Krumlov a Rožmberk', 'Nejkrásnější říční údolí jižních Čech v jednom okruhu: gotický klášter Zlatá Koruna, renesanční Český Krumlov zapsaný na seznamu UNESCO, hrad Rožmberk vysoko nad meandrem Vltavy a cisterciácký Vyšší Brod. Silnice číslo 160 z Krumlova na Rožmberk kopíruje řeku a patří k nejhezčím motorkářským úsekům v Čechách — plynulé zatáčky, minimum rovinek. Zpět se vracíte přes Kaplici po rychlejší sto padesát sedmičce. Nejlepší je všední den mimo hlavní sezónu, o prázdninách je Krumlov turisticky našlapaný a parkování chvíli zabere. Pozor na vodáky přebíhající u kempů podél řeky a na stín v údolí, kde silnice zjara pomalu osychá.', 'loop', 135, 210, 'medium',
     '[{"lat": 48.9745, "lng": 14.4743, "label": "Start: České Budějovice"}, {"lat": 48.8551, "lng": 14.3714, "label": "Zlatá Koruna"}, {"lat": 48.8127, "lng": 14.3149, "label": "Český Krumlov"}, {"lat": 48.6539, "lng": 14.3660, "label": "Rožmberk nad Vltavou"}, {"lat": 48.6157, "lng": 14.3110, "label": "Vyšší Brod"}, {"lat": 48.7387, "lng": 14.4956, "label": "Kaplice"}, {"lat": 48.9745, "lng": 14.4743, "label": "Cíl: České Budějovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9745,14.4743&destination=48.9745,14.4743&travelmode=driving&waypoints=48.8551,14.3714%7C48.8127,14.3149%7C48.6539,14.3660%7C48.6157,14.3110%7C48.7387,14.4956', 'https://commons.wikimedia.org/wiki/Special:FilePath/St%C3%A1tn%C3%AD%20hrad%20a%20z%C3%A1mek%20%C4%8Cesk%C3%BD%20Krumlov.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter%20Zlat%C3%A1%20Koruna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/St%C3%A1tn%C3%AD%20hrad%20a%20z%C3%A1mek%20%C4%8Cesk%C3%BD%20Krumlov.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/View%20over%20%C4%8Cesk%C3%BD%20Krumlov%20in%202012.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20rozmberk.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter%20Vy%C5%A1%C5%A1%C3%AD%20Brod.JPG"}'::text[], '{"Klášter Zlatá Koruna","Státní hrad a zámek Český Krumlov","Restaurace: Krčma v Šatlavské ulici (Český Krumlov)","Hrad Rožmberk nad Vltavou","Klášter Vyšší Brod"}'::text[], '{"CZ"}'::text[], false, 2020, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Klášter Zlatá Koruna', 'Jeden z nejzachovalejších gotických klášterů ve střední Evropě, schovaný v meandru Vltavy. Založil ho Přemysl Otakar II. roku 1263 a dodnes dýchá klidem — mimo prohlídky projdete nádvoří zdarma. Sjezd z hlavní silnice je krátký a parkuje se přímo u areálu.', 48.8551, 14.3714, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter%20Zlat%C3%A1%20Koruna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter%20Zlat%C3%A1%20Koruna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zlata%20Koruna%20Monastery.jpg"}'::text[], 0),
    (v_route, 'Státní hrad a zámek Český Krumlov', 'Druhý největší hradní komplex v Česku s ikonickou malovanou věží nad meandrem Vltavy, srdce města zapsaného na seznamu UNESCO. Z hradebních teras a plášťového mostu jsou nejfotografovanější výhledy v jižních Čechách. Motorku nechte na záchytném parkovišti P1 a centrum projděte pěšky.', 48.8127, 14.3149, 'https://commons.wikimedia.org/wiki/Special:FilePath/St%C3%A1tn%C3%AD%20hrad%20a%20z%C3%A1mek%20%C4%8Cesk%C3%BD%20Krumlov.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/St%C3%A1tn%C3%AD%20hrad%20a%20z%C3%A1mek%20%C4%8Cesk%C3%BD%20Krumlov.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/View%20over%20%C4%8Cesk%C3%BD%20Krumlov%20in%202012.JPG"}'::text[], 1),
    (v_route, 'Restaurace: Krčma v Šatlavské ulici (Český Krumlov)', 'Vyhlášená středověká krčma v bývalé městské šatlavě — maso z otevřeného ohně, svíčky a klenby. Jedno z nejlépe hodnocených míst ve městě, v sezóně je nutná rezervace. Perfektní oběd v půlce okruhu, než se vydáte údolím na jih.', 48.8103, 14.3160, 'https://commons.wikimedia.org/wiki/Special:FilePath/View%20over%20%C4%8Cesk%C3%BD%20Krumlov%20in%202012.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/View%20over%20%C4%8Cesk%C3%BD%20Krumlov%20in%202012.JPG"}'::text[], 2),
    (v_route, 'Hrad Rožmberk nad Vltavou', 'Rodový hrad pánů z Růže na skále vysoko nad vltavským meandrem. Příjezd po silnici 160 podél řeky je zážitek sám o sobě a od hradu se otevírá výhled na celé údolí. Legenda o Bílé paní tu má svůj domov.', 48.6539, 14.3660, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20rozmberk.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20rozmberk.JPG"}'::text[], 3),
    (v_route, 'Klášter Vyšší Brod', 'Cisterciácké opatství ze 13. století, domov Závišova kříže — jedné z nejcennějších zlatnických památek Evropy. Rozlehlý areál s gotickým kostelem a klášterním pivovarem leží hned u silnice před městečkem. Odtud už vede zpáteční cesta přes Kaplici svižnými oblouky k Budějovicím.', 48.6157, 14.3110, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter%20Vy%C5%A1%C5%A1%C3%AD%20Brod.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A1%C5%A1ter%20Vy%C5%A1%C5%A1%C3%AD%20Brod.JPG"}'::text[], 4);

  -- Renesanční Kratochvíle a Zlatá stezka
  delete from public.routes where name = 'Renesanční Kratochvíle a Zlatá stezka' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Renesanční Kratochvíle a Zlatá stezka', 'Okruh Prácheňskem po stopách rožmberské renesance a středověké Zlaté stezky, po níž se ze Solné komory vozila sůl. Vodní zámek Kratochvíle je italská vila uprostřed jihočeských luk, poutní Lomec zase barokní klenot ukrytý v lesích. Okresky mezi Netolicemi, Bavorovem a Prachaticemi jsou úzké, zvlněné a téměř prázdné — přesně to, co motorkář hledá. Výšlap na zříceninu Helfenburk (20 minut pěšky z parkoviště) odmění kruhový rozhled z hradní věže. Jarní a podzimní jízdě sluší nejvíc; po dešti pozor na listí a štěrk v lesních zatáčkách.', 'loop', 120, 195, 'medium',
     '[{"lat": 48.9745, "lng": 14.4743, "label": "Start: České Budějovice"}, {"lat": 49.0637, "lng": 14.1701, "label": "Zámek Kratochvíle"}, {"lat": 49.1010, "lng": 14.2078, "label": "Lomec"}, {"lat": 49.1220, "lng": 14.0787, "label": "Bavorov"}, {"lat": 49.1367, "lng": 14.0064, "label": "Helfenburk"}, {"lat": 49.0119, "lng": 13.9975, "label": "Prachatice"}, {"lat": 48.9745, "lng": 14.4743, "label": "Cíl: České Budějovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9745,14.4743&destination=48.9745,14.4743&travelmode=driving&waypoints=49.0637,14.1701%7C49.1010,14.2078%7C49.1220,14.0787%7C49.1367,14.0064%7C49.0119,13.9975', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek%20Kratochvile.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek%20Kratochvile.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Lomec%2C%20kostel%20Jm%C3%A9na%20Panny%20Marie.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bavorov%20z%C3%A1mek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Helfenburk%2C%20obytn%C3%A1%20v%C4%9B%C5%BE%2C%20vstupn%C3%AD%20%C4%8D%C3%A1st.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prachatice%2C%20Velk%C3%A9%20n%C3%A1m%C4%9Bst%C3%AD%20(1).jpg"}'::text[], '{"Zámek Kratochvíle","Poutní kostel Lomec","Bavorov – zámek a kostel","Zřícenina hradu Helfenburk u Bavorova","Prachatice – Velké náměstí"}'::text[], '{"CZ"}'::text[], false, 2030, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zámek Kratochvíle', 'Renesanční vodní letohrádek Viléma z Rožmberka, postavený italskými mistry jako vila uprostřed obory. Bílá stavba obklopená vodním příkopem a zahradou je nejčistší ukázkou italské renesance v Čechách. Leží kousek od Netolic na klidné okresce, parkování přímo u zdi areálu.', 49.0637, 14.1701, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek%20Kratochvile.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek%20Kratochvile.JPG"}'::text[], 0),
    (v_route, 'Poutní kostel Lomec', 'Barokní poutní kostel Jména Panny Marie na zalesněném návrší mezi Vodňany a Netolicemi. Unikátní centrální stavba s baldachýnovým oltářem po vzoru svatopetrského v Římě, kolem ticho a vzrostlé lípy. Krátká odbočka po úzké lesní silničce stojí za to.', 49.1010, 14.2078, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lomec%2C%20kostel%20Jm%C3%A9na%20Panny%20Marie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lomec%2C%20kostel%20Jm%C3%A9na%20Panny%20Marie.jpg"}'::text[], 1),
    (v_route, 'Bavorov – zámek a kostel', 'Ospalé městečko pod Helfenburkem s renesančním zámkem Rožmberků a mohutným gotickým kostelem Nanebevzetí Panny Marie. Dobré místo na doplnění paliva a kávu na náměstí, než se pustíte do lesních serpentin k hradu. Okreska z Bavorova na Helfenburk patří k nejhezčím v okolí.', 49.1220, 14.0787, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bavorov%20z%C3%A1mek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bavorov%20z%C3%A1mek.jpg"}'::text[], 2),
    (v_route, 'Zřícenina hradu Helfenburk u Bavorova', 'Rozsáhlá zřícenina rožmberského hradu ze 14. století ukrytá v hlubokých lesích. Z upravené vyhlídkové věže je kruhový rozhled od Šumavy po Písecké hory. Od lesního parkoviště počítejte s dvacetiminutovou procházkou do kopce.', 49.1367, 14.0064, 'https://commons.wikimedia.org/wiki/Special:FilePath/Helfenburk%2C%20obytn%C3%A1%20v%C4%9B%C5%BE%2C%20vstupn%C3%AD%20%C4%8D%C3%A1st.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Helfenburk%2C%20obytn%C3%A1%20v%C4%9B%C5%BE%2C%20vstupn%C3%AD%20%C4%8D%C3%A1st.jpg"}'::text[], 3),
    (v_route, 'Prachatice – Velké náměstí', 'Renesanční město, které zbohatlo na solné Zlaté stezce — sgrafitové fasády Velkého náměstí patří k nejkrásnějším v zemi. Zachovalé hradby, Písecká brána a desítky měšťanských domů s výmalbou. Zaparkujte před hradbami a projděte historické jádro pěšky, zabere to půl hodiny.', 49.0119, 13.9975, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prachatice%2C%20Velk%C3%A9%20n%C3%A1m%C4%9Bst%C3%AD%20(1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prachatice%2C%20Velk%C3%A9%20n%C3%A1m%C4%9Bst%C3%AD%20(1).jpg"}'::text[], 4);

  -- Okolo Lipna – jihočeské moře
  delete from public.routes where name = 'Okolo Lipna – jihočeské moře' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Okolo Lipna – jihočeské moře', 'Okruh kolem největší vodní plochy Česka: po pravém břehu přes hráz a Loučovice na Přední Výtoň, po levém zpět přes Frymburk a Horní Planou. Střídají se výhledy na hladinu, šumavské lesy a žulová skaliska Čertovy stěny, k tomu vyhlídková zřícenina Vítkův hrádek — nejvýše položený hrad v Čechách s výhledem až na Alpy. Silnice jsou dobře udržované a zatáčkovité, mezi Frymburkem a Černou v Pošumaví vedou přímo u vody. Ideální od května do října; o letních víkendech počítejte s rekreačním provozem a u Frymburka s frontou na přívoz. Ráno bývá nad hladinou mlha a chladno i v létě — vezměte vrstvu navíc.', 'loop', 130, 225, 'medium',
     '[{"lat": 48.8107, "lng": 14.3153, "label": "Start: Český Krumlov"}, {"lat": 48.6270, "lng": 14.2390, "label": "Lipno nad Vltavou – hráz"}, {"lat": 48.6210, "lng": 14.2860, "label": "Čertova stěna"}, {"lat": 48.6297, "lng": 14.1935, "label": "Svatý Tomáš – Vítkův hrádek"}, {"lat": 48.6592, "lng": 14.1657, "label": "Frymburk"}, {"lat": 48.7683, "lng": 14.0326, "label": "Horní Planá"}, {"lat": 48.7370, "lng": 14.1070, "label": "Černá v Pošumaví"}, {"lat": 48.8107, "lng": 14.3153, "label": "Cíl: Český Krumlov"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.8107,14.3153&destination=48.8107,14.3153&travelmode=driving&waypoints=48.6270,14.2390%7C48.6210,14.2860%7C48.6297,14.1935%7C48.6592,14.1657%7C48.7683,14.0326%7C48.7370,14.1070', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lipno%20nad%20Vltavou%2C%20p%C5%99ehradn%C3%AD%20hr%C3%A1z%2C%20p%C5%99ehrada.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lipno%20nad%20Vltavou%2C%20p%C5%99ehradn%C3%AD%20hr%C3%A1z%2C%20p%C5%99ehrada.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Certova-st%C4%9Bna-Vyhl%C3%ADdka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADtk%C5%AFv%20k%C3%A1men%2Cz%C5%99icenina.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Frymburk%2C%20p%C5%99%C3%ADvoz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/A%20Stifter-statue.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Frymburk%2C%20kostel%20a%20fara.jpg"}'::text[], '{"Hráz Lipna a vodní elektrárna","NPR Čertova stěna-Luč","Vítkův hrádek (Svatý Tomáš)","Frymburk a přívoz do Frýdavy","Horní Planá – rodiště Adalberta Stiftera","Restaurace: Hotel Maxant (Frymburk)"}'::text[], '{"CZ"}'::text[], false, 2040, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hráz Lipna a vodní elektrárna', 'Přes 280 metrů dlouhá hráz jihočeského moře s podzemní elektrárnou vytesanou 160 metrů hluboko v žule. Ze silnice vedoucí po koruně hráze je výhled na celé jezero i do údolí Vltavy pod ním. Hned vedle začíná kaskáda Čertových proudů.', 48.6270, 14.2390, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lipno%20nad%20Vltavou%2C%20p%C5%99ehradn%C3%AD%20hr%C3%A1z%2C%20p%C5%99ehrada.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lipno%20nad%20Vltavou%2C%20p%C5%99ehradn%C3%AD%20hr%C3%A1z%2C%20p%C5%99ehrada.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Lipno%20nad%20Vltavou%2C%20p%C5%99ehradn%C3%AD%20hr%C3%A1z%2C%20elektr%C3%A1rna.JPG"}'::text[], 0),
    (v_route, 'NPR Čertova stěna-Luč', 'Národní přírodní rezervace s obřím žulovým kamenným mořem padajícím do údolí Vltavy — podle pověsti dílo samotného čerta. Vyhlídka na skalní srub je pár minut chůze od parkoviště u silnice Loučovice–Vyšší Brod. Divoké Čertovy proudy pod stěnou inspirovaly Smetanu i Wagnera.', 48.6210, 14.2860, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Certova-st%C4%9Bna-Vyhl%C3%ADdka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Certova-st%C4%9Bna-Vyhl%C3%ADdka.jpg"}'::text[], 1),
    (v_route, 'Vítkův hrádek (Svatý Tomáš)', 'Nejvýše položený hrad v Čechách (1035 m) nad osadou Svatý Tomáš. Z opravené obytné věže je za dobré viditelnosti vidět celé Lipno, Šumava i řetěz Alp na obzoru. Poslední kilometr se jde pěšky lesem, motorku necháte na parkovišti u osady.', 48.6297, 14.1935, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADtk%C5%AFv%20k%C3%A1men%2Cz%C5%99icenina.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%ADtk%C5%AFv%20k%C3%A1men%2Cz%C5%99icenina.JPG"}'::text[], 2),
    (v_route, 'Frymburk a přívoz do Frýdavy', 'Malebné městečko na poloostrově s dlouhou návsí, gotickým kostelem a promenádou u vody. Přes jezero odtud jezdí legendární přívoz do Frýdavy, který převeze i motorku — zkratka na pravý břeh a malé dobrodružství k tomu. Ideální místo na zmrzlinu s výhledem na hladinu.', 48.6592, 14.1657, 'https://commons.wikimedia.org/wiki/Special:FilePath/Frymburk%2C%20p%C5%99%C3%ADvoz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Frymburk%2C%20p%C5%99%C3%ADvoz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Frymburk%2C%20kostel%20a%20fara.jpg"}'::text[], 3),
    (v_route, 'Horní Planá – rodiště Adalberta Stiftera', 'Městečko na levém břehu Lipna, rodiště šumavského básníka Adalberta Stiftera — jeho rodný dům je dnes památník a nad městem stojí spisovatelova socha s výhledem na jezero. Náměstí s podloubím zve na kávu, pláž u přívozu na krátkou pauzu u vody.', 48.7683, 14.0326, 'https://commons.wikimedia.org/wiki/Special:FilePath/A%20Stifter-statue.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/A%20Stifter-statue.JPG"}'::text[], 4),
    (v_route, 'Restaurace: Hotel Maxant (Frymburk)', 'Rodinný hotel s vyhlášenou restaurací přímo na frymburské návsi, pár kroků od vody. Poctivá jihočeská kuchyně, ryby z Lipna a domácí dezerty — nejjistější oběd na celém okruhu. V létě příjemná zahrádka s výhledem na kostel.', 48.6597, 14.1650, 'https://commons.wikimedia.org/wiki/Special:FilePath/Frymburk%2C%20kostel%20a%20fara.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Frymburk%2C%20kostel%20a%20fara.jpg"}'::text[], 5);

  -- Přehrady Malše a Vltavy – Římov a Hněvkovice
  delete from public.routes where name = 'Přehrady Malše a Vltavy – Římov a Hněvkovice' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Přehrady Malše a Vltavy – Římov a Hněvkovice', 'Vodohospodářský okruh Budějovickem od pitné rezervy na Malši po vltavskou kaskádu u Temelína. Začíná se u římovské přehrady a barokní Lorety s pašijovou cestou, pokračuje přes rodiště Jana Žižky v Trocnově a končí u hněvkovické hráze, která napájí chladicí věže největší české elektrárny. Trasa vede po klidných okreskách mezi rybníky a lesy, bez náročných pasáží — vhodná i pro méně zkušené jezdce. Infocentrum Temelína v zámečku Vysoký Hrádek nabízí zdarma expozici i vyhlídku na věže. Jezdit se dá od jara do podzimu, provoz je slabý po celý rok.', 'loop', 140, 210, 'easy',
     '[{"lat": 48.9745, "lng": 14.4743, "label": "Start: České Budějovice"}, {"lat": 48.8486, "lng": 14.4897, "label": "Římov – přehrada"}, {"lat": 48.8980, "lng": 14.5990, "label": "Trocnov"}, {"lat": 49.1830, "lng": 14.4470, "label": "Hněvkovice – hráz"}, {"lat": 49.1770, "lng": 14.3690, "label": "Temelín – Vysoký Hrádek"}, {"lat": 48.9745, "lng": 14.4743, "label": "Cíl: České Budějovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9745,14.4743&destination=48.9745,14.4743&travelmode=driving&waypoints=48.8486,14.4897%7C48.8980,14.5990%7C49.1830,14.4470%7C49.1770,14.3690', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98%C3%ADmov%2C%20vodn%C3%AD%20n%C3%A1dr%C5%BE%20%C5%98%C3%ADmov%2C%20pohled%20k%20hr%C3%A1zi.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98%C3%ADmov%2C%20vodn%C3%AD%20n%C3%A1dr%C5%BE%20%C5%98%C3%ADmov%2C%20pohled%20k%20hr%C3%A1zi.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98%C3%ADmov%2C%20Loreta%203.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Jan%20%C5%BDi%C5%BEka%20z%20Trocnova%20(03).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Vodn%C3%AD%20n%C3%A1dr%C5%BE%20Hn%C4%9Bvkovice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Chlad%C3%ADc%C3%AD%20v%C4%9B%C5%BEe%20JETE.JPG"}'::text[], '{"Vodní nádrž Římov","Římov – Loreta a pašijová cesta","Trocnov – památník Jana Žižky","Vodní nádrž Hněvkovice – hráz","Infocentrum JE Temelín – zámeček Vysoký Hrádek"}'::text[], '{"CZ"}'::text[], false, 2050, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vodní nádrž Římov', 'Přehrada na Malši ze sedmdesátých let zásobuje pitnou vodou většinu jižních Čech. Sypaná hráz vysoká 47 metrů je vidět z vyhlídky nad údolím; samotná nádrž je jako vodárenská chráněná, o to divočejší je okolní příroda. Kolem vede příjemná okreska s minimem aut.', 48.8486, 14.4897, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98%C3%ADmov%2C%20vodn%C3%AD%20n%C3%A1dr%C5%BE%20%C5%98%C3%ADmov%2C%20pohled%20k%20hr%C3%A1zi.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98%C3%ADmov%2C%20vodn%C3%AD%20n%C3%A1dr%C5%BE%20%C5%98%C3%ADmov%2C%20pohled%20k%20hr%C3%A1zi.jpg"}'::text[], 0),
    (v_route, 'Římov – Loreta a pašijová cesta', 'Barokní poutní areál s loretánskou kaplí a unikátní pašijovou cestou s 25 zastaveními, která obchází vesnici jako malý jeruzalémský okruh. Ambity zdobí fresky a areál je volně přístupný. Klidné místo na protažení po prvních kilometrech.', 48.8563, 14.4855, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98%C3%ADmov%2C%20Loreta%203.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%98%C3%ADmov%2C%20Loreta%203.JPG"}'::text[], 1),
    (v_route, 'Trocnov – památník Jana Žižky', 'Rodiště nejslavnějšího husitského vojevůdce s monumentální žulovou sochou, muzeem a nově i archeoskanzenem středověké vesnice. Areál v lesích u Borovan je příjemnou zastávkou s dostatkem parkování. Expozice zabere půl hodiny, skanzen o něco víc.', 48.8980, 14.5990, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jan%20%C5%BDi%C5%BEka%20z%20Trocnova%20(03).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jan%20%C5%BDi%C5%BEka%20z%20Trocnova%20(03).JPG"}'::text[], 2),
    (v_route, 'Vodní nádrž Hněvkovice – hráz', 'Přehrada vltavské kaskády postavená v osmdesátých letech jako zdroj chladicí vody pro Temelín. Betonová hráz s mostovkou nabízí výhled na jezero rámované lesy; pod hrází pokračuje Vltava k Týnu. Silnice po hrázi spojuje oba břehy a je volně průjezdná.', 49.1830, 14.4470, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vodn%C3%AD%20n%C3%A1dr%C5%BE%20Hn%C4%9Bvkovice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vodn%C3%AD%20n%C3%A1dr%C5%BE%20Hn%C4%9Bvkovice.jpg"}'::text[], 3),
    (v_route, 'Infocentrum JE Temelín – zámeček Vysoký Hrádek', 'Návštěvnické centrum největší české elektrárny sídlí v renesančním zámečku Vysoký Hrádek přímo u areálu. Interaktivní expozice o jaderné energetice je zdarma a z parku je nejlepší pohled na čtveřici 155metrových chladicích věží. Technika, která bere dech i z motorkářského sedla.', 49.1770, 14.3690, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chlad%C3%ADc%C3%AD%20v%C4%9B%C5%BEe%20JETE.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chlad%C3%ADc%C3%AD%20v%C4%9B%C5%BEe%20JETE.JPG"}'::text[], 4);

  -- Blanský les a rozhledna Kleť
  delete from public.routes where name = 'Blanský les a rozhledna Kleť' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Blanský les a rozhledna Kleť', 'Kompaktní okruh chráněnou krajinnou oblastí Blanský les kolem nejstarší kamenné rozhledny v Čechách. Z Budějovic přes selské baroko Holašovic (UNESCO) do Křemžské kotliny, kde se nad krajinou zvedá tisícovka Kleť s rozhlednou z roku 1825 a hvězdárnou — nahoru vede sedačková lanovka z Krasetína nebo hodinová procházka. Na zpáteční cestě čeká tajemná zřícenina Dívčí Kámen nad soutokem Vltavy a Křemžského potoka. Okresky v kotlině jsou úzké, zvlněné a překvapivě zábavné, provoz minimální. Za jasného počasí je z Kleti vidět celý řetěz Alp — vyplatí se vyjet brzy ráno na podzim.', 'loop', 95, 180, 'medium',
     '[{"lat": 48.9745, "lng": 14.4743, "label": "Start: České Budějovice"}, {"lat": 48.9700, "lng": 14.2726, "label": "Holašovice"}, {"lat": 48.9053, "lng": 14.3057, "label": "Křemže"}, {"lat": 48.8800, "lng": 14.3050, "label": "Krasetín – lanovka na Kleť"}, {"lat": 48.8888, "lng": 14.3630, "label": "Dívčí Kámen"}, {"lat": 48.9745, "lng": 14.4743, "label": "Cíl: České Budějovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9745,14.4743&destination=48.9745,14.4743&travelmode=driving&waypoints=48.9700,14.2726%7C48.9053,14.3057%7C48.8800,14.3050%7C48.8888,14.3630', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Kle%C5%A5%201.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hola%C5%A1ovice%20Historic%20Village-112772.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Kle%C5%A5%201.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Kle%C5%A5%20lanovka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Burg%20D%C3%ADv%C4%8D%C3%AD%20K%C3%A1men%202.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kuklov%2C%20z%C5%99%C3%ADcenina%20kl%C3%A1%C5%A1tera.jpg"}'::text[], '{"Holašovice – selské baroko (UNESCO)","Rozhledna Kleť","Lanová dráha Krasetín–Kleť","Zřícenina hradu Dívčí Kámen","Kuklov – zřícenina kláštera"}'::text[], '{"CZ"}'::text[], false, 2060, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Holašovice – selské baroko (UNESCO)', 'Dokonale dochovaná jihočeská náves obklopená štíty selského baroka, od roku 1998 na seznamu UNESCO. Dvaadvacet usedlostí kolem rybníčku s kapličkou vypadá jako kulisa, ale žije se tu normálně dál. Zastavte na parkovišti před vsí a projděte náves pěšky.', 48.9700, 14.2726, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hola%C5%A1ovice%20Historic%20Village-112772.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hola%C5%A1ovice%20Historic%20Village-112772.jpg"}'::text[], 0),
    (v_route, 'Rozhledna Kleť', 'Nejstarší kamenná rozhledna v Čechách (1825) na nejvyšším vrcholu Blanského lesa (1084 m). Za dobré viditelnosti dohlédnete přes Šumavu až na zasněžené vrcholy Alp vzdálené přes 150 kilometrů. Hned vedle stojí známá hvězdárna, která objevila stovky planetek.', 48.8645, 14.2834, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Kle%C5%A5%201.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Kle%C5%A5%201.JPG"}'::text[], 1),
    (v_route, 'Lanová dráha Krasetín–Kleť', 'Nejstarší sedačková lanovka v Česku (1961) vyveze líné i unavené z Krasetína na vrchol Kleti za čtvrt hodiny. Motorku pohodlně necháte na parkovišti u dolní stanice. Kdo chce, může nahoru pěšky lesem — nahoře čeká chata s výčepem a terasou.', 48.8800, 14.3050, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kle%C5%A5%20lanovka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kle%C5%A5%20lanovka.jpg"}'::text[], 2),
    (v_route, 'Zřícenina hradu Dívčí Kámen', 'Jedna z největších hradních zřícenin v Čechách na skalnatém ostrohu nad soutokem Vltavy a Křemžského potoka. Rožmberský hrad ze 14. století je opředený pověstmi a obklopený přírodní rezervací. Od parkoviště v Třísově je to příjemných dvacet minut pěšky.', 48.8888, 14.3630, 'https://commons.wikimedia.org/wiki/Special:FilePath/Burg%20D%C3%ADv%C4%8D%C3%AD%20K%C3%A1men%202.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Burg%20D%C3%ADv%C4%8D%C3%AD%20K%C3%A1men%202.jpg"}'::text[], 3),
    (v_route, 'Kuklov – zřícenina kláštera', 'Nedostavěný pavlánský klášter z 15. století srostlý se stavením vesničky Kuklov — gotické zdi kostela stojí přímo mezi chalupami. Málo známé, o to působivější místo na dohled od Kleti. Krátká odbočka z Brloha po úzké silničce.', 48.9390, 14.2050, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kuklov%2C%20z%C5%99%C3%ADcenina%20kl%C3%A1%C5%A1tera.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kuklov%2C%20z%C5%99%C3%ADcenina%20kl%C3%A1%C5%A1tera.jpg"}'::text[], 4);

  -- Rozhledny Píseckých hor
  delete from public.routes where name = 'Rozhledny Píseckých hor' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rozhledny Píseckých hor', 'Nenáročný okruh kolem zlatonosné Otavy a zalesněnými hřbety Píseckých hor za dvěma rozhlednami s výhledem od Šumavy po Brdy. Startuje se u nejstaršího kamenného mostu v Česku, pak lesními silničkami na věž Jarník a přes hřeben k rozhledně Velký Kamýk. Cestou zpět stojí za zastávku secesní areál Zemského hřebčince, technická i architektonická památka. Okresky v Píseckých horách jsou úzké a stinné, na jaře a po dešti počítejte s vlhkými úseky a jehličím ve stopě. Ideální polodenní vyjížďka, kterou zvládne i začátečník.', 'loop', 90, 165, 'easy',
     '[{"lat": 49.3088, "lng": 14.1469, "label": "Start: Písek – Kamenný most"}, {"lat": 49.3006, "lng": 14.1934, "label": "Rozhledna Jarník"}, {"lat": 49.2758, "lng": 14.2040, "label": "Velký Kamýk"}, {"lat": 49.2600, "lng": 14.1500, "label": "Smrkovice"}, {"lat": 49.3149, "lng": 14.1360, "label": "Zemský hřebčinec"}, {"lat": 49.3088, "lng": 14.1469, "label": "Cíl: Písek – Kamenný most"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.3088,14.1469&destination=49.3088,14.1469&travelmode=driving&waypoints=49.3006,14.1934%7C49.2758,14.2040%7C49.2600,14.1500%7C49.3149,14.1360', 'https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20kamenn%C3%BD%20most.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20kamenn%C3%BD%20most.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Jarn%C3%ADk%20(1).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Velk%C3%BD%20Kam%C3%BDk.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Zemsk%C3%BD%20h%C5%99eb%C4%8Dinec%20P%C3%ADsek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20the%20Stone%20Bridge-2.JPG"}'::text[], '{"Písek – Kamenný most","Rozhledna Jarník","Rozhledna Velký Kamýk","Zemský hřebčinec Písek","Restaurace: U Reinerů (Písek)"}'::text[], '{"CZ"}'::text[], false, 2070, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Písek – Kamenný most', 'Nejstarší dochovaný kamenný most v Česku, o generaci starší než pražský Karlův. Gotický most přes Otavu z 13. století je dnes pěší zónou s barokními sochami a výhledem na nábřeží. Zaparkujte na nábřeží a projděte si i blízké Velké náměstí.', 49.3088, 14.1469, 'https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20kamenn%C3%BD%20most.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20kamenn%C3%BD%20most.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20the%20Stone%20Bridge-2.JPG"}'::text[], 0),
    (v_route, 'Rozhledna Jarník', 'Šedesátimetrová věž na kopci Jarník dva kilometry od Písku, kombinace rozhledny a vysílače. Z ochozu ve výšce 30 metrů přehlédnete Otavu, Písecké hory a za dobrého počasí i šumavské hřebeny. Přístup po zpevněné lesní cestě až k patě věže.', 49.3006, 14.1934, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Jarn%C3%ADk%20(1).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Jarn%C3%ADk%20(1).JPG"}'::text[], 1),
    (v_route, 'Rozhledna Velký Kamýk', 'Dřevěná rozhledna na nejvyšším bodě Píseckých hor (627 m) uprostřed hlubokých lesů. Tiché místo, kam trefí jen málokdo — výhled na Otavskou nivu, Temelín i Šumavu. Od lesního parkoviště pár minut pěšky po hřebeni.', 49.2758, 14.2040, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Velk%C3%BD%20Kam%C3%BDk.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhledna%20Velk%C3%BD%20Kam%C3%BDk.JPG"}'::text[], 2),
    (v_route, 'Zemský hřebčinec Písek', 'Secesní areál zemského hřebčince z roku 1902, národní kulturní památka a dodnes fungující chov plemenných hřebců. Monumentální stáje s věžičkami připomínají spíš zámek než hospodářský dvůr. Prohlídky v návštěvních hodinách, zvenku volně k vidění.', 49.3149, 14.1360, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zemsk%C3%BD%20h%C5%99eb%C4%8Dinec%20P%C3%ADsek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zemsk%C3%BD%20h%C5%99eb%C4%8Dinec%20P%C3%ADsek.jpg"}'::text[], 3),
    (v_route, 'Restaurace: U Reinerů (Písek)', 'Tradiční měšťanská restaurace na Velkém náměstí, píseckou klasiku tu vaří už desítky let. Poctivé polední menu, jihočeské ryby i pivo z místního minipivovaru. Po okruhu ideální místo na pozdní oběd dvě minuty chůze od Kamenného mostu.', 49.3084, 14.1475, 'https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20the%20Stone%20Bridge-2.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%ADsek%2C%20the%20Stone%20Bridge-2.JPG"}'::text[], 4);

  -- Novohradské hory a Terčino údolí
  delete from public.routes where name = 'Novohradské hory a Terčino údolí' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Novohradské hory a Terčino údolí', 'Nejtišší pohoří Čech: bývalé pohraniční pásmo, kam desítky let nesměl nikdo vkročit, dnes nabízí prázdné silnice, hluboké lesy a zaniklé vesnice. Okruh spojuje středověké Nové Hrady s romantickým Terčiným údolím, poutní Dobrou Vodu s rozhlednou na Kraví hoře a končí až u kostela zaniklé osady Pohoří na Šumavě na rakouské hranici. Silničky za Benešovem nad Černou jsou úzké, místy s horším povrchem, ale provoz se blíží nule — jen pozor na zvěř, hlavně za soumraku. Nejkrásněji je tu na přelomu září a října, kdy bučiny hrají barvami. Tankujte předem, benzínka je až v Kaplici nebo Trhových Svinech.', 'loop', 160, 255, 'medium',
     '[{"lat": 48.9745, "lng": 14.4743, "label": "Start: České Budějovice"}, {"lat": 48.7896, "lng": 14.7786, "label": "Nové Hrady"}, {"lat": 48.7830, "lng": 14.7560, "label": "Terčino údolí"}, {"lat": 48.7423, "lng": 14.7290, "label": "Dobrá Voda"}, {"lat": 48.7290, "lng": 14.6280, "label": "Benešov nad Černou"}, {"lat": 48.6000, "lng": 14.6940, "label": "Pohoří na Šumavě"}, {"lat": 48.7387, "lng": 14.4956, "label": "Kaplice"}, {"lat": 48.9745, "lng": 14.4743, "label": "Cíl: České Budějovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9745,14.4743&destination=48.9745,14.4743&travelmode=driving&waypoints=48.7896,14.7786%7C48.7830,14.7560%7C48.7423,14.7290%7C48.7290,14.6280%7C48.6000,14.6940%7C48.7387,14.4956', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Nov%C3%A9%20Hrady.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Nov%C3%A9%20Hrady.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tercino-udoli-vodopad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nov%C3%A9%20Hrady%2C%20%C3%9Adol%C3%AD%2C%20Cukn%C5%A1tejn%20(01).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dobr%C3%A1%20voda%20kostel%204.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Krav%C3%AD%20hora%20rozhledna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Poho%C5%99%C3%AD%20na%20%C5%A0umav%C4%9B.jpg"}'::text[], '{"Hrad Nové Hrady","Terčino údolí – umělý vodopád","Tvrz Cuknštejn","Dobrá Voda u Nových Hradů","Rozhledna Kraví hora","Pohoří na Šumavě – zaniklá osada"}'::text[], '{"CZ"}'::text[], false, 2080, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Nové Hrady', 'Gotický hrad ze 13. století obklopený nejhlubším suchým příkopem v Čechách. Strážil zemskou stezku do Rakouska a dodnes vévodí náměstíčku pohraničního městečka s buquoyskou rezidencí a klášterem. Prohlídka zabere hodinu, výhled z valů je zdarma.', 48.7896, 14.7786, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Nov%C3%A9%20Hrady.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Nov%C3%A9%20Hrady.jpg"}'::text[], 0),
    (v_route, 'Terčino údolí – umělý vodopád', 'Romantický krajinný park z 18. století, který nechala založit hraběnka Terezie Buquoyová v údolí Stropnice. Procházka kolem Modrého domu a lázniček vede k umělému vodopádu napájenému náhonem — nejfotogeničtějšímu místu parku. Od parkoviště u vstupu počítejte s půlhodinovou procházkou.', 48.7830, 14.7560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tercino-udoli-vodopad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tercino-udoli-vodopad.jpg"}'::text[], 1),
    (v_route, 'Tvrz Cuknštejn', 'Pozdně gotická tvrz z konce 15. století na okraji Terčina údolí, jedna z nejzachovalejších v Čechách. Kamenný čtyřkřídlý objekt s věží prošel citlivou obnovou a hraje ve filmech i seriálech. Stojí přímo u cesty do údolí — fotka bez sesedání.', 48.7770, 14.7620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nov%C3%A9%20Hrady%2C%20%C3%9Adol%C3%AD%2C%20Cukn%C5%A1tejn%20(01).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nov%C3%A9%20Hrady%2C%20%C3%9Adol%C3%AD%2C%20Cukn%C5%A1tejn%20(01).jpg"}'::text[], 2),
    (v_route, 'Dobrá Voda u Nových Hradů', 'Barokní poutní kostel Nanebevzetí Panny Marie přilepený na svahu pod Kraví horou, se zázračným pramenem a výhledem do rakouského podhůří. Bílé průčelí září do kraje na desítky kilometrů. Serpentiny z Horní Stropnice nahoru jsou krátké, ale šťavnaté.', 48.7423, 14.7290, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dobr%C3%A1%20voda%20kostel%204.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dobr%C3%A1%20voda%20kostel%204.jpg"}'::text[], 3),
    (v_route, 'Rozhledna Kraví hora', 'Kamenno-dřevěná rozhledna na žulovém vrcholu Kraví hory (953 m) nad Hojnou Vodou. Výhled na celé Novohradské hory, Lipno i alpské vrcholy na jihu; kolem vrcholu bizarní žulové skalní útvary. Z parkoviště v Hojné Vodě nahoru zhruba půl hodiny pěšky.', 48.7280, 14.7220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Krav%C3%AD%20hora%20rozhledna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Krav%C3%AD%20hora%20rozhledna.jpg"}'::text[], 4),
    (v_route, 'Pohoří na Šumavě – zaniklá osada', 'Kdysi živé pohraniční městečko, po roce 1955 srovnané se zemí — zůstal jen obnovovaný kostel Panny Marie Dobré Rady a pár chalup uprostřed luk. Jedno z nejmelancholičtějších míst Čech, na dohled od rakouské hranice. Poslední kilometry vedou po úzké silničce zaniklou krajinou, jeďte opatrně.', 48.6000, 14.6940, 'https://commons.wikimedia.org/wiki/Special:FilePath/Poho%C5%99%C3%AD%20na%20%C5%A0umav%C4%9B.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Poho%C5%99%C3%AD%20na%20%C5%A0umav%C4%9B.jpg"}'::text[], 5);

  -- Šumavský Stožec a Schwarzenberský kanál
  delete from public.routes where name = 'Šumavský Stožec a Schwarzenberský kanál' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Šumavský Stožec a Schwarzenberský kanál', 'Jihovýchodní cíp Národního parku Šumava, kam většina návštěvníků nedojede: údolí Teplé Vltavy mezi Lenorou a Stožcem a technický zázrak osvícenství — Schwarzenberský plavební kanál, který přes rozvodí spojil Vltavu s Dunajem. Trasa vede po parkových silnicích mezi rašeliništi a horskými loukami, s odbočkou k Jelením Vrchům, kde kanál vtéká do portálu plavebního tunelu. Zastavíte u krytého dřevěného mostu v Lenoře, u vyhlídkové věže nad Soumarským rašeliništěm i u horské kaple nad Stožcem. Provoz je slabý, ale v NP platí přísné rychlostní limity a časté kontroly — jeďte v klidu a užívejte scenérii. Nejlepší od června do října, brzy zjara bývají silnice po zimě posypané štěrkem.', 'loop', 120, 210, 'medium',
     '[{"lat": 48.9090, "lng": 13.8870, "label": "Start: Volary"}, {"lat": 48.9210, "lng": 13.7930, "label": "Lenora"}, {"lat": 48.9040, "lng": 13.8270, "label": "Soumarský most"}, {"lat": 48.8580, "lng": 13.8280, "label": "Stožec"}, {"lat": 48.7920, "lng": 13.9370, "label": "Nová Pec"}, {"lat": 48.7740, "lng": 13.8950, "label": "Jelení Vrchy"}, {"lat": 48.9090, "lng": 13.8870, "label": "Cíl: Volary"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9090,13.8870&destination=48.9090,13.8870&travelmode=driving&waypoints=48.9210,13.7930%7C48.9040,13.8270%7C48.8580,13.8280%7C48.7920,13.9370%7C48.7740,13.8950', 'https://commons.wikimedia.org/wiki/Special:FilePath/Schwarzenbersk%C3%BD%20plavebn%C3%AD%20kan%C3%A1l.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lenora%2C%20rechle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Soumarsk%C3%BD%20most.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sto%C5%BEeck%C3%A1%20kaple.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Nov%C3%A1%20Pec.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schwarzenbersk%C3%BD%20plavebn%C3%AD%20kan%C3%A1l.jpg"}'::text[], '{"Lenora – rechle","Soumarský most a rašeliniště","Stožecká kaple","Nová Pec","Schwarzenberský plavební kanál (Jelení Vrchy)"}'::text[], '{"CZ"}'::text[], false, 2090, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lenora – rechle', 'Krytý dřevěný most přes Teplou Vltavu, kterým se kdysi hradilo plavené dříví — poslední svého druhu na Šumavě. Sklářská obec Lenora nabízí i historickou obecní pec, kde se o víkendech peče chleba. Fotogenická zastávka hned u silnice.', 48.9210, 13.7930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lenora%2C%20rechle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lenora%2C%20rechle.jpg"}'::text[], 0),
    (v_route, 'Soumarský most a rašeliniště', 'Vrchovištní rašeliniště v nivě Teplé Vltavy s naučnou stezkou po povalovém chodníku a vyhlídkovou věží nad meandry řeky. Místo, kudy soumaři po Zlaté stezce brodili náklady soli. Půlhodinový okruh pěšky od parkoviště u mostu.', 48.9040, 13.8270, 'https://commons.wikimedia.org/wiki/Special:FilePath/Soumarsk%C3%BD%20most.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Soumarsk%C3%BD%20most.jpg"}'::text[], 1),
    (v_route, 'Stožecká kaple', 'Dřevěná poutní kaple z roku 1791 přilepená pod skalní stěnou nad osadou Stožec, symbol smíření na česko-bavorském pomezí. Od parkoviště ve Stožci vede nahoru pohodlná lesní cesta, tam a zpět hodina chůze. Odměnou je ticho horského lesa a pramen s údajně léčivou vodou.', 48.8650, 13.8210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sto%C5%BEeck%C3%A1%20kaple.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sto%C5%BEeck%C3%A1%20kaple.JPG"}'::text[], 2),
    (v_route, 'Nová Pec', 'Horská obec na horním konci Lipna, kde jezero přechází v divokou Vltavu a nad krajinou se zvedá hraniční hřeben s Plechým, nejvyšší horou české Šumavy. Poslední občerstvení a palivo před odbočkou k Jelením Vrchům. Od nádraží pěkný výhled na Trojmezenskou hornatinu.', 48.7920, 13.9370, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nov%C3%A1%20Pec.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nov%C3%A1%20Pec.jpg"}'::text[], 3),
    (v_route, 'Schwarzenberský plavební kanál (Jelení Vrchy)', 'Technický div z konce 18. století: 44 kilometrů dlouhý kanál, který plavil šumavské dřevo přes evropské rozvodí až do Vídně. U osady Jelení Vrchy vtéká do 400 metrů dlouhého plavebního tunelu; v létě se tu konají ukázky plavení dříví. Silnička z Nové Pece končí parkovištěm přímo u kanálu.', 48.7740, 13.8950, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schwarzenbersk%C3%BD%20plavebn%C3%AD%20kan%C3%A1l.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schwarzenbersk%C3%BD%20plavebn%C3%AD%20kan%C3%A1l.jpg"}'::text[], 4);

  -- Českobudějovická muzea a koněspřežka
  delete from public.routes where name = 'Českobudějovická muzea a koněspřežka' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Českobudějovická muzea a koněspřežka', 'Krátký okruh pro dny, kdy počasí nepřeje dálkám: nejstarší železnice kontinentální Evropy a budějovická muzea v jednom balíčku. Koněspřežná dráha z Budějovic do Lince vyjela už roku 1827 a její stopu dodnes značí strážní domky — jeden z nich je muzeem přímo ve městě a v Holkově u Velešína se dochovala přepřahací stanice. K tomu Jihočeské muzeum, motocyklová sbírka v renesanční Solnici na Piaristickém náměstí a Černá věž s výhledem na celé město. Jede se po nenáročných silnicích druhé třídy s běžným provozem. Celoroční trasa — většina zastávek funguje i mimo sezónu.', 'loop', 70, 135, 'easy',
     '[{"lat": 48.9745, "lng": 14.4743, "label": "Start: České Budějovice"}, {"lat": 48.9663, "lng": 14.4695, "label": "Strážní domek koněspřežky"}, {"lat": 48.9000, "lng": 14.4550, "label": "Kamenný Újezd"}, {"lat": 48.8335, "lng": 14.4595, "label": "Holkov"}, {"lat": 48.8300, "lng": 14.4900, "label": "Velešín"}, {"lat": 48.9745, "lng": 14.4743, "label": "Cíl: České Budějovice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9745,14.4743&destination=48.9745,14.4743&travelmode=driving&waypoints=48.9663,14.4695%7C48.9000,14.4550%7C48.8335,14.4595%7C48.8300,14.4900', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cern%C3%A1%20v%C4%9B%C5%BE%2001.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cern%C3%A1%20v%C4%9B%C5%BE%2001.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Jiho%C4%8Desk%C3%A9%20muzeum%20v%20%C4%8Cesk%C3%BDch%20Bud%C4%9Bjovic%C3%ADch.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%2C%20Solnice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kon%C4%9Bsp%C5%99e%C5%BEn%C3%AD%20dr%C3%A1ha%20%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%2C%20str%C3%A1%C5%BEn%C3%AD%20domek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Holkov%2C%20p%C5%99ep%C5%99ahac%C3%AD%20stanice%20kon%C4%9Bsp%C5%99e%C5%BEky.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cerna%20vez.jpg"}'::text[], '{"Náměstí Přemysla Otakara II. a Černá věž","Jihočeské muzeum","Jihočeské motocyklové muzeum (Solnice)","Muzeum koněspřežky – strážní domek","Holkov – přepřahací stanice koněspřežky","Restaurace: Krajinská 27 (České Budějovice)"}'::text[], '{"CZ"}'::text[], false, 2100, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Náměstí Přemysla Otakara II. a Černá věž', 'Jedno z největších čtvercových náměstí v Evropě se Samsonovou kašnou a podloubím ze všech stran. Z ochozu 72 metrů vysoké Černé věže je celé město i Kleť jako na dlani — 225 schodů stojí za to. Parkování v modrých zónách kolem centra nebo v domě u Dlouhé louky.', 48.9745, 14.4743, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cern%C3%A1%20v%C4%9B%C5%BE%2001.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cern%C3%A1%20v%C4%9B%C5%BE%2001.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%20Samson-Brunnen%20159.jpg"}'::text[], 0),
    (v_route, 'Jihočeské muzeum', 'Nejstarší a největší muzeum v jižních Čechách v honosné novorenesanční budově z roku 1903. Stálé expozice přírody i historie regionu a především unikátní sbírka ke koněspřežní dráze Budějovice–Linec. Ideální start okruhu — vše ostatní dává po návštěvě větší smysl.', 48.9718, 14.4767, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jiho%C4%8Desk%C3%A9%20muzeum%20v%20%C4%8Cesk%C3%BDch%20Bud%C4%9Bjovic%C3%ADch.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jiho%C4%8Desk%C3%A9%20muzeum%20v%20%C4%8Cesk%C3%BDch%20Bud%C4%9Bjovic%C3%ADch.jpg"}'::text[], 1),
    (v_route, 'Jihočeské motocyklové muzeum (Solnice)', 'Sbírka více než stovky historických motocyklů — Jawy, ČZ, Laurin & Klement i váleční veteráni — v gotické Solnici na Piaristickém náměstí. Povinná zastávka každého motorkáře: stroje, vůně benzínu a příběhy československého motocyklismu. Otevřeno v sezóně denně.', 48.9748, 14.4712, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%2C%20Solnice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%2C%20Solnice.jpg"}'::text[], 2),
    (v_route, 'Muzeum koněspřežky – strážní domek', 'Expozice v původním strážním domku č. 1 v Mánesově ulici připomíná první železnici kontinentální Evropy, po níž koně tahali vagóny se solí do Lince. Malé, ale poctivé muzeum s modely a dobovými plány. Odtud vyrazíte přesně po stopě staré dráhy na jih.', 48.9663, 14.4695, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kon%C4%9Bsp%C5%99e%C5%BEn%C3%AD%20dr%C3%A1ha%20%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%2C%20str%C3%A1%C5%BEn%C3%AD%20domek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kon%C4%9Bsp%C5%99e%C5%BEn%C3%AD%20dr%C3%A1ha%20%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%2C%20str%C3%A1%C5%BEn%C3%AD%20domek.jpg"}'::text[], 3),
    (v_route, 'Holkov – přepřahací stanice koněspřežky', 'Nejzachovalejší přepřahací stanice koněspřežní dráhy s formanskou hospodou a stájemi, kde se měnila spřežení na trase do Lince. Areál u Velešína stojí přímo u staré císařské silnice; násep dráhy je v terénu dodnes čitelný. Kousek odtud se klikatí hezká okreska zpět k Budějovicím podél Malše.', 48.8335, 14.4595, 'https://commons.wikimedia.org/wiki/Special:FilePath/Holkov%2C%20p%C5%99ep%C5%99ahac%C3%AD%20stanice%20kon%C4%9Bsp%C5%99e%C5%BEky.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Holkov%2C%20p%C5%99ep%C5%99ahac%C3%AD%20stanice%20kon%C4%9Bsp%C5%99e%C5%BEky.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Krajinská 27 (České Budějovice)', 'Řemeslný minipivovar s výborně hodnocenou restaurací v historickém domě v Krajinské ulici. Vlastní nefiltrovaná piva, burgery i česká klasika z lokálních surovin. Dvě minuty od náměstí — perfektní zakončení městského okruhu.', 48.9761, 14.4726, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cerna%20vez.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cerna%20vez.jpg"}'::text[], 5);

end $$;
