-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — BELGIE 2026 (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Údolí Semois – Rochehaut a Tombeau du Géant
  delete from public.routes where name = 'Údolí Semois – Rochehaut a Tombeau du Géant' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí Semois – Rochehaut a Tombeau du Géant', 'Okruh nejkrásnějším říčním údolím Belgie sleduje divoké meandry Semois po úzkých okreskách, které se vlní mezi lesy, tabákovými vesničkami a skalními vyhlídkami. Z Florenville projedete přes malířské Chassepierre a zříceninu Herbeumont k legendárnímu meandru Tombeau du Géant a vyhlídkám u Rochehaut, odkud se otevírá jeden z nejfotografovanějších pohledů celé země. Serpentiny mezi Bouillonem a Vresse jsou pastvou pro motorku i oči, ale silnice jsou úzké a v lese často vlhké, s listím a mechem v zatáčkách. Nejlépe si trasu užijete od května do října, ráno navíc s mlhami nad řekou. Počítejte s pomalejším tempem a nabitou kartou ve foťáku; tankujte ve Florenville nebo Bouillonu.', 'loop', 120, 210, 'medium',
     '[{"lat": 49.6997, "lng": 5.3062, "label": "Start: Florenville"}, {"lat": 49.7108, "lng": 5.2536, "label": "Chassepierre"}, {"lat": 49.7789, "lng": 5.2364, "label": "Herbeumont"}, {"lat": 49.8069, "lng": 5.0286, "label": "Botassart – Tombeau du Géant"}, {"lat": 49.8339, "lng": 5.0129, "label": "Rochehaut"}, {"lat": 49.8747, "lng": 4.9345, "label": "Vresse-sur-Semois"}, {"lat": 49.6997, "lng": 5.3062, "label": "Cíl: Florenville"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.6997,5.3062&destination=49.6997,5.3062&travelmode=driving&waypoints=49.7108,5.2536%7C49.7789,5.2364%7C49.8069,5.0286%7C49.8339,5.0129%7C49.8747,4.9345', 'https://commons.wikimedia.org/wiki/Special:FilePath/0%20Botassart%20-%20Tombeau%20du%20G%C3%A9ant%20(1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chassepierre.%20%C3%A9glise%20Saint-Martin.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20d''Herbeumont%203.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/0%20Botassart%20-%20Tombeau%20du%20G%C3%A9ant%20(1).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Frahan%20viewed%20from%20Route%20d''Alle%20(DSCF5187-5197).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Frahan%20viewed%20from%20Route%20d''Alle%20(DSCF5187-5197).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20de%20Claies,%20Lafor%C3%AAt.jpg"}'::text[], '{"Chassepierre","Château d''Herbeumont","Tombeau du Géant (Botassart)","Rochehaut – vyhlídka na Frahan","Restaurace: L''Auberge de la Ferme (Rochehaut)","Laforêt – Pont de Claies"}'::text[], '{"BE"}'::text[], false, 3110, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Chassepierre', 'Malebná vesnička nad břehem Semois, kterou si zamilovali malíři i pořadatelé slavného festivalu pouličního umění. Kostel sv. Martina s vesnicí na skalním ostrohu tvoří jeden z nejromantičtějších obrázků Gaume. Ideální první fotozastávka pár minut od startu.', 49.7108, 5.2536, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chassepierre.%20%C3%A9glise%20Saint-Martin.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chassepierre.%20%C3%A9glise%20Saint-Martin.JPG"}'::text[], 0),
    (v_route, 'Château d''Herbeumont', 'Zřícenina středověkého hradu ze 13. století na hřebeni vysoko nad meandrem Semois. Krátká procházka od parkoviště vás odmění výhledem na dvojitou říční smyčku zvanou Tombeau du Chevalier. Přístupová silnice z údolí nahoru je řetěz utažených zatáček, které si říkají o druhý průjezd.', 49.7789, 5.2364, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20d''Herbeumont%203.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20d''Herbeumont%203.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/HerbeumontChateau201207061705.jpg"}'::text[], 1),
    (v_route, 'Tombeau du Géant (Botassart)', 'Obří meandr Semois obtékající zalesněný kopec, který připomíná obrův hrob – nejslavnější přírodní scenérie belgických Arden. Vyhlídka u Botassart je přímo u silnice, s lavičkami a dostatkem místa pro motorky. Nejpůsobivější je ráno, kdy se z údolí zvedá mlha.', 49.8069, 5.0286, 'https://commons.wikimedia.org/wiki/Special:FilePath/0%20Botassart%20-%20Tombeau%20du%20G%C3%A9ant%20(1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/0%20Botassart%20-%20Tombeau%20du%20G%C3%A9ant%20(1).jpg"}'::text[], 2),
    (v_route, 'Rochehaut – vyhlídka na Frahan', 'Z terasy nad vesnicí Rochehaut se díváte přímo na podkovu Semois s vesničkou Frahan uprostřed – druhý ikonický pohled tohoto údolí. Na místě je parkoviště, panoramatické tabule i několik teras s kávou. Silnice z Rochehaut dolů k řece a zpět je oblíbená motorkářská hračka.', 49.8339, 5.0129, 'https://commons.wikimedia.org/wiki/Special:FilePath/Frahan%20viewed%20from%20Route%20d''Alle%20(DSCF5187-5197).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Frahan%20viewed%20from%20Route%20d''Alle%20(DSCF5187-5197).jpg"}'::text[], 3),
    (v_route, 'Restaurace: L''Auberge de la Ferme (Rochehaut)', 'Rodinný hotel s vyhlášenou restaurací přímo v Rochehaut, který staví na zvěřině, ardenské šunce a surovinách z vlastní farmy. Patří k nejlépe hodnoceným podnikům v celém údolí Semois a k obědu nabízí i jednodušší bistro menu. Rezervace se o víkendu vyplatí.', 49.8341, 5.0136, 'https://commons.wikimedia.org/wiki/Special:FilePath/Frahan%20viewed%20from%20Route%20d''Alle%20(DSCF5187-5197).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Frahan%20viewed%20from%20Route%20d''Alle%20(DSCF5187-5197).jpg"}'::text[], 4),
    (v_route, 'Laforêt – Pont de Claies', 'Laforêt patří mezi nejkrásnější vesnice Valonska a v létě tu přes Semois vede unikátní proutěný most Pont de Claies, který se každý rok staví znovu. Břidlicové domky a klid u řeky jsou příjemnou tečkou před návratem přes lesy zpět do Florenville. Mimo sezónu most nahrazuje brod – k vidění je od července do září.', 49.8617, 4.9394, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20de%20Claies,%20Lafor%C3%AAt.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pont%20de%20Claies,%20Lafor%C3%AAt.jpg"}'::text[], 5);

  -- Okolí Spa – Franchimont, Remouchamps a Stavelot
  delete from public.routes where name = 'Okolí Spa – Franchimont, Remouchamps a Stavelot' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Okolí Spa – Franchimont, Remouchamps a Stavelot', 'Kompaktní okruh kolem lázeňského města Spa, které dalo jméno lázním po celém světě a je zapsané na seznamu UNESCO. Trasa spojuje jezero Warfaaz, mohutnou pevnost Franchimont nad Theux, podzemní plavbu v jeskyních Remouchamps a tisícileté opatství ve Stavelot. Silnice v zalesněných údolích Hoëgne a Amblève jsou skvěle asfaltované a plné plynulých zatáček, stoupání od Remouchamps ke Spa patří k nejhezčím v kraji. Vhodné i pro méně zkušené jezdce; pozor jen na cyklisty, kterých tu o víkendech jezdí spousta. Ideální od jara do podzimu, v okolí Spa počítejte s častějšími přeháňkami.', 'loop', 95, 150, 'easy',
     '[{"lat": 50.4922, "lng": 5.8628, "label": "Start: Spa"}, {"lat": 50.5006, "lng": 5.8933, "label": "Lac de Warfaaz"}, {"lat": 50.5333, "lng": 5.8203, "label": "Château de Franchimont"}, {"lat": 50.4794, "lng": 5.7136, "label": "Grottes de Remouchamps"}, {"lat": 50.3947, "lng": 5.9308, "label": "Stavelot"}, {"lat": 50.4922, "lng": 5.8628, "label": "Cíl: Spa"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.4922,5.8628&destination=50.4922,5.8628&travelmode=driving&waypoints=50.5006,5.8933%7C50.5333,5.8203%7C50.4794,5.7136%7C50.3947,5.9308', 'https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon-Pierre-Le-Grand%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon-Pierre-Le-Grand%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Lac%20Warfaaz%20R01.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/0%20Theux%20-%20Ch%C3%A2teau%20de%20Franchimont%20(3).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grottes%20de%20Remouchamps%2001.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20de%20Stavelot%2003.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon%20PLG%20R01.jpg"}'::text[], '{"Spa – Pouhon Pierre le Grand","Lac de Warfaaz","Château de Franchimont","Grottes de Remouchamps","Stavelot – opatství","Restaurace: Brasserie du Grand Maur (Spa)"}'::text[], '{"BE"}'::text[], false, 3120, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Spa – Pouhon Pierre le Grand', 'Hlavní minerální pramen lázeňského města Spa, pojmenovaný po caru Petru Velikém, který se tu léčil v roce 1717. Elegantní pavilon uprostřed města je symbolem lázní zapsaných na seznam UNESCO. Před startem ochutnejte železitou vodu a projděte si secesní kolonády.', 50.4925, 5.8631, 'https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon-Pierre-Le-Grand%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon-Pierre-Le-Grand%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon%20PLG%20R01.jpg"}'::text[], 0),
    (v_route, 'Lac de Warfaaz', 'Klidné jezero v lesích kousek nad Spa, obklíbené promenádou, loďkami a několika terasami u vody. Krátká odbočka hned na začátku okruhu, ideální na ranní kávu s výhledem na hladinu. Silnička kolem jezera pokračuje pěkným stoupáním do lesů směrem na Theux.', 50.5006, 5.8933, 'https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Lac%20Warfaaz%20R01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Lac%20Warfaaz%20R01.jpg"}'::text[], 1),
    (v_route, 'Château de Franchimont', 'Mohutná zřícenina hradu lutyšských knížat-biskupů nad městečkem Theux, přestavěná v 16. století na dělostřeleckou pevnost. Z hradeb je krásný výhled do údolí Hoëgne a expozice ukazuje, jak se hrad bránil. Parkoviště je hned u vstupu, prohlídka zabere příjemnou hodinku.', 50.5333, 5.8203, 'https://commons.wikimedia.org/wiki/Special:FilePath/0%20Theux%20-%20Ch%C3%A2teau%20de%20Franchimont%20(3).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/0%20Theux%20-%20Ch%C3%A2teau%20de%20Franchimont%20(3).jpg"}'::text[], 2),
    (v_route, 'Grottes de Remouchamps', 'Jeskynní systém na řece Rubicon, kde vás čeká nejdelší podzemní plavba na loďce v Evropě – téměř kilometr tichého klouzání pod krápníky. Prohlídka trvá zhruba hodinu a čtvrt a je skvělým zpestřením motorkářského dne. Vstup je přímo u hlavní silnice v Remouchamps, kavárna přes ulici.', 50.4794, 5.7136, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grottes%20de%20Remouchamps%2001.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grottes%20de%20Remouchamps%2001.JPG"}'::text[], 3),
    (v_route, 'Stavelot – opatství', 'Bývalé knížecí opatství založené už v 7. století dnes ukrývá tři muzea, mimo jiné slavné muzeum okruhu Spa-Francorchamps s historickými závodními stroji. Náměstíčko před opatstvím lemují kavárny a v místním pivovaru se vaří klášterní pivo. Cesta ze Stavelot zpět do Spa lesem přes Malchamps je krásná svižná pasáž.', 50.3947, 5.9308, 'https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20de%20Stavelot%2003.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20de%20Stavelot%2003.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Abdij%20van%20Stavelot.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Brasserie du Grand Maur (Spa)', 'Stylová brasserie v historickém domě v centru Spa s poctivou valonskou kuchyní – ardenskou šunkou, masem na pivu a sezónními specialitami. Hosté ji dlouhodobě řadí mezi nejlepší podniky ve městě. Perfektní závěrečná večeře po okruhu, pár kroků od pramene Pouhon.', 50.4930, 5.8654, 'https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon%20PLG%20R01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Spa%20Pouhon%20PLG%20R01.jpg"}'::text[], 5);

  -- Hautes Fagnes – Signal de Botrange a Robertville
  delete from public.routes where name = 'Hautes Fagnes – Signal de Botrange a Robertville' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Hautes Fagnes – Signal de Botrange a Robertville', 'Okruh po střeše Belgie vede otevřenými vřesovišti a rašeliništi národního parku Hautes Fagnes, kde silnice běží po náhorní plošině s výhledy na desítky kilometrů. Z Malmedy vystoupáte k Baraque Michel a na Signal de Botrange (694 m), nejvyšší bod země, a přes hráz přehrady na Vesdre u Eupenu se vrátíte kolem jezera Robertville a pohádkového hradu Reinhardstein. Kombinace rychlých přehledných úseků nahoře a lesních serpentin v údolí Warche je jízdně velmi pestrá. Nahoře bývá větrno, chladněji a rychlé změny počasí – přibalte vrstvu navíc i v létě. Nejkrásněji je tu na přelomu léta, kdy vřesoviště fialově kvetou.', 'loop', 90, 150, 'easy',
     '[{"lat": 50.4258, "lng": 6.0281, "label": "Start: Malmedy"}, {"lat": 50.5203, "lng": 6.0631, "label": "Baraque Michel"}, {"lat": 50.5017, "lng": 6.0939, "label": "Signal de Botrange"}, {"lat": 50.5989, "lng": 6.0761, "label": "Barrage de la Vesdre (Eupen)"}, {"lat": 50.4569, "lng": 6.1114, "label": "Lac de Robertville"}, {"lat": 50.4433, "lng": 6.1114, "label": "Château de Reinhardstein"}, {"lat": 50.4258, "lng": 6.0281, "label": "Cíl: Malmedy"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.4258,6.0281&destination=50.4258,6.0281&travelmode=driving&waypoints=50.5203,6.0631%7C50.5017,6.0939%7C50.5989,6.0761%7C50.4569,6.1114%7C50.4433,6.1114', 'https://commons.wikimedia.org/wiki/Special:FilePath/Signal%20de%20Botrange%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20de%20Malmedy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Baraque%20Michel,%20restaurant%20Baraque%20Michel%20foto3%202011-06-04%2013.19.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Signal%20de%20Botrange%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Wesertalsperre%20Eupen.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Robertville%20JPG01.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Robertville%20-%20Ch%C3%A2teau%20de%20Reinhardstein.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20de%20Malmedy.jpg"}'::text[], '{"Malmedy – katedrála","Baraque Michel","Signal de Botrange","Barrage de la Vesdre (Eupen)","Lac de Robertville","Château de Reinhardstein","Restaurace: Plein Vent (Bévercé u Malmedy)"}'::text[], '{"BE"}'::text[], false, 3130, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Malmedy – katedrála', 'Barokní dvouvěžová katedrála sv. Petra, Pavla a Quirina je dominantou příjemného městečka na okraji Hautes Fagnes. Malmedy je známé karnevalem, papírenskou historií a dobrými kavárnami na náměstí – ideální místo na start a tankování. Odtud silnice stoupá rovnou do vřesovišť.', 50.4262, 6.0269, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20de%20Malmedy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20de%20Malmedy.jpg"}'::text[], 0),
    (v_route, 'Baraque Michel', 'Historický zájezdní hostinec z roku 1811 uprostřed pustiny Hautes Fagnes, kdysi záchrana pro poutníky bloudící v mlze a sněhu. Dnes oblíbená motorkářská zastávka na kávu a palačinky, od které vedou povalové chodníky do rašelinišť. Kaple Fischbach hned vedle připomíná zachráněné poutníky.', 50.5203, 6.0631, 'https://commons.wikimedia.org/wiki/Special:FilePath/Baraque%20Michel,%20restaurant%20Baraque%20Michel%20foto3%202011-06-04%2013.19.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Baraque%20Michel,%20restaurant%20Baraque%20Michel%20foto3%202011-06-04%2013.19.JPG"}'::text[], 1),
    (v_route, 'Signal de Botrange', 'Nejvyšší bod Belgie (694 m) s kamennou vyhlídkovou věží a rozlehlým výhledem přes vřesoviště až do Německa. Přímo u silnice je velké parkoviště, restaurace a návštěvnické centrum parku. Povinná fotka u cedule s nadmořskou výškou – výš už se v Belgii na motorce nedostanete.', 50.5017, 6.0939, 'https://commons.wikimedia.org/wiki/Special:FilePath/Signal%20de%20Botrange%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Signal%20de%20Botrange%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Belgium,%20Botrange,%20Communication%20tower.JPG"}'::text[], 2),
    (v_route, 'Barrage de la Vesdre (Eupen)', 'Přehrada na říčce Vesdre nad Eupenem zásobuje pitnou vodou celý východ Belgie a její kamenná hráz s věžemi patří k největším v zemi. Po koruně hráze se dá projít a z vyhlídky je pěkný pohled na jezero sevřené smrkovými lesy. Příjezd lesem od Ternell je krásná plynulá pasáž.', 50.5989, 6.0761, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wesertalsperre%20Eupen.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wesertalsperre%20Eupen.JPG"}'::text[], 3),
    (v_route, 'Lac de Robertville', 'Přehradní jezero na řece Warche s průzračnou vodou, pláží a půjčovnou loděk, obklopené loukami a lesy. V létě láká ke koupání, po zbytek roku ke klidné zastávce s výhledem na hladinu. Silnice kolem jezera a dolů do údolí Warche nabízí sled pěkných zatáček.', 50.4569, 6.1114, 'https://commons.wikimedia.org/wiki/Special:FilePath/Robertville%20JPG01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Robertville%20JPG01.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lac%20de%20Robertville%20bei%20Outrewarche.jpg"}'::text[], 4),
    (v_route, 'Château de Reinhardstein', 'Nejvýše položený hrad Belgie se tyčí na skále v divokém údolí Warche pod hrází Robertville. Věrně obnovená středověká pevnost s rytířskými sály a zbrojnicí vypadá jako z pohádky; k hradu se jde 15 minut pěšky lesem. Kousek pod hradem je nejvyšší vodopád země.', 50.4433, 6.1114, 'https://commons.wikimedia.org/wiki/Special:FilePath/Robertville%20-%20Ch%C3%A2teau%20de%20Reinhardstein.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Robertville%20-%20Ch%C3%A2teau%20de%20Reinhardstein.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Plein Vent (Bévercé u Malmedy)', 'Restaurace s panoramatickou terasou na silnici ze Spa do Malmedy, odkud se díváte přes celé údolí až na hřebeny Arden. Vyhlášená je poctivou regionální kuchyní a jedním z nejhezčích výhledů, u kterých se dá v Belgii obědvat. Skvělé zakončení okruhu před sjezdem do Malmedy.', 50.4489, 6.0339, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20de%20Malmedy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cath%C3%A9drale%20de%20Malmedy.jpg"}'::text[], 6);

  -- Údolí Mázy – Namur, Dinant a Freÿr
  delete from public.routes where name = 'Údolí Mázy – Namur, Dinant a Freÿr' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí Mázy – Namur, Dinant a Freÿr', 'Pohodová jízda nejkrásnějším úsekem údolí Mázy (Meuse), kde řeku svírají vápencové stěny a silnice N92 a N96 kopírují každý její záhyb těsně u hladiny. Z citadely v Namuru pojedete přes vodní zahrady v Annevoie do Dinantu, města rodáka Adolpha Saxe s citadelou na skále, a dál kolem jehly Rocher Bayard k renesančnímu zámku Freÿr. Závěr obstará pohádkový hrad Vêves a návrat zvlněnou krajinou Condroz. Provoz u řeky je mírný, povrch výborný, jen o letních víkendech počítejte s turisty v Dinantu. Ideální trasa na první seznámení s Valonskem.', 'loop', 110, 165, 'easy',
     '[{"lat": 50.4633, "lng": 4.8650, "label": "Start: Namur"}, {"lat": 50.3444, "lng": 4.8506, "label": "Jardins d''Annevoie"}, {"lat": 50.2606, "lng": 4.9122, "label": "Dinant"}, {"lat": 50.2508, "lng": 4.9086, "label": "Rocher Bayard"}, {"lat": 50.2222, "lng": 4.8894, "label": "Château de Freÿr"}, {"lat": 50.2258, "lng": 5.0072, "label": "Celles – Château de Vêves"}, {"lat": 50.4633, "lng": 4.8650, "label": "Cíl: Namur"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.4633,4.8650&destination=50.4633,4.8650&travelmode=driving&waypoints=50.3444,4.8506%7C50.2606,4.9122%7C50.2508,4.9086%7C50.2222,4.8894%7C50.2258,5.0072', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dinant%20Coll%C3%A9giale%20Notre%20Dame%2001.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/La%20Citadelle%20de%20Namur.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Les%20jardins%20d''Annevoie%20-%20Le%20petit%20canal.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Dinant%20Coll%C3%A9giale%20Notre%20Dame%2001.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Dinant%20Coll%C3%A9giale%20Notre%20Dame%2001.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/RocherBayardDinant.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Fre%C3%BFr%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Celles%20(Houyet)%20-%20Ch%C3%A2teau%20de%20V%C3%AAves%20(1).jpg"}'::text[], '{"Citadela Namur","Jardins d''Annevoie","Dinant – Collégiale a citadela","Restaurace: La Broche (Dinant)","Rocher Bayard","Château de Freÿr","Château de Vêves"}'::text[], '{"BE"}'::text[], false, 3140, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Citadela Namur', 'Rozlehlá pevnost nad soutokem Mázy a Sambry, kterou Napoleon nazval termitištěm Evropy kvůli kilometrům podzemních chodeb. Na vrchol vede krásná okresní silnička Route Merveilleuse plná vlásenek – z hradeb je nejhezčí výhled na hlavní město Valonska. Ideální rozjezd celého okruhu.', 50.4592, 4.8631, 'https://commons.wikimedia.org/wiki/Special:FilePath/La%20Citadelle%20de%20Namur.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/La%20Citadelle%20de%20Namur.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Namur%20Citadelle%2007.JPG"}'::text[], 0),
    (v_route, 'Jardins d''Annevoie', 'Vodní zahrady z 18. století, kde desítky fontán, kaskád a kanálů fungují dodnes bez jediného čerpadla – jen díky důmyslnému spádu pramenů. Procházka mezi vodotrysky a starými buky zabere hodinku a krásně rozbije jízdu podél řeky. Parkování přímo u vstupu.', 50.3444, 4.8506, 'https://commons.wikimedia.org/wiki/Special:FilePath/Les%20jardins%20d''Annevoie%20-%20Le%20petit%20canal.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Les%20jardins%20d''Annevoie%20-%20Le%20petit%20canal.JPG"}'::text[], 1),
    (v_route, 'Dinant – Collégiale a citadela', 'Nejfotogeničtější město na Máze: cibulová věž gotické kolegiáty Notre-Dame přilepené ke skále, nad ní citadela a před ní řada barevných domů zrcadlících se v řece. Nahoru vede 408 schodů nebo lanovka a město je plné odkazů na rodáka Adolpha Saxe, vynálezce saxofonu. Motorku zaparkujete na nábřeží.', 50.2606, 4.9122, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dinant%20Coll%C3%A9giale%20Notre%20Dame%2001.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dinant%20Coll%C3%A9giale%20Notre%20Dame%2001.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Church%20La%20Col%C3%A9giale%20in%20Dinant.JPG"}'::text[], 2),
    (v_route, 'Restaurace: La Broche (Dinant)', 'Útulná restaurace v uličce u kolegiáty patří dlouhodobě k nejlépe hodnoceným v Dinantu. Francouzská kuchyně ze sezónních surovin, rozumné polední menu a ochotná obsluha – přesně to, co po dopoledni v sedle potřebujete. V sezóně doporučujeme rezervaci.', 50.2617, 4.9114, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dinant%20Coll%C3%A9giale%20Notre%20Dame%2001.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dinant%20Coll%C3%A9giale%20Notre%20Dame%2001.JPG"}'::text[], 3),
    (v_route, 'Rocher Bayard', 'Čtyřicetimetrová skalní jehla na břehu Mázy, kterou podle legendy rozťal kopytem kouzelný kůň Bayard prchající před Karlem Velikým. Silnice projíždí přímo úzkou soutěskou mezi jehlou a masivem – zpomalte a vychutnejte si ten průjezd. Hned za skálou je odstavný pruh na fotku.', 50.2508, 4.9086, 'https://commons.wikimedia.org/wiki/Special:FilePath/RocherBayardDinant.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/RocherBayardDinant.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Dinant,%20le%20rocher%20Bayard%20foto13%202012-06-30%2014.16.JPG"}'::text[], 4),
    (v_route, 'Château de Freÿr', 'Renesanční zámek s barokními terasovými zahradami přímo na břehu Mázy, naproti slavným lezeckým stěnám Rochers de Freÿr. Kdysi tu odpočívala i Marie Terezie; oranžerie ukrývá tři sta let staré pomerančovníky. Jeden z nejromantičtějších pohledů celého údolí.', 50.2222, 4.8894, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Fre%C3%BFr%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Fre%C3%BFr%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Freyr%20R01.jpg"}'::text[], 5),
    (v_route, 'Château de Vêves', 'Pohádkový hrad s pěti špičatými věžemi u vesnice Celles, jedné z nejkrásnějších vesnic Valonska. Patří k nejzachovalejším ukázkám středověké hradní architektury v Belgii a interiéry obývá stejný rod už přes 800 let. Silničky v okolí Celles jsou příjemným zakončením před návratem do Namuru.', 50.2258, 5.0072, 'https://commons.wikimedia.org/wiki/Special:FilePath/Celles%20(Houyet)%20-%20Ch%C3%A2teau%20de%20V%C3%AAves%20(1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Celles%20(Houyet)%20-%20Ch%C3%A2teau%20de%20V%C3%AAves%20(1).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20V%C3%AAves%20Belgique%2026.jpg"}'::text[], 6);

  -- Flandry – Brugy, Damme a pobřeží
  delete from public.routes where name = 'Flandry – Brugy, Damme a pobřeží' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Flandry – Brugy, Damme a pobřeží', 'Rovinatý, ale nesmírně malebný okruh západními Flandrami: středověké Brugy se zvonicí a kanály, alej podél kanálu do hanzovního Damme, slaniska rezervace Zwin u hranice s Nizozemskem a návrat po pobřeží Severního moře přes belle époque lázně De Haan do Ostende. Jezdí se po úzkých silničkách po korunách hrází, mezi poldery a řadami topolů, kde je zážitkem samotné světlo a vítr od moře. Technicky nenáročné, ideální i pro spolujezdce; pozor na boční vítr na hrázích, cyklisty a koleje pobřežní tramvaje. Nejlepší od dubna do září, ryby a hranolky u moře jsou povinnost.', 'loop', 85, 150, 'easy',
     '[{"lat": 51.2093, "lng": 3.2247, "label": "Start: Brugy"}, {"lat": 51.2511, "lng": 3.2814, "label": "Damme"}, {"lat": 51.3583, "lng": 3.3592, "label": "Zwin (Knokke-Heist)"}, {"lat": 51.2725, "lng": 3.0347, "label": "De Haan"}, {"lat": 51.2326, "lng": 2.9126, "label": "Oostende"}, {"lat": 51.2093, "lng": 3.2247, "label": "Cíl: Brugy"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.2093,3.2247&destination=51.2093,3.2247&travelmode=driving&waypoints=51.2511,3.2814%7C51.3583,3.3592%7C51.2725,3.0347%7C51.2326,2.9126', 'https://commons.wikimedia.org/wiki/Special:FilePath/Brugge-CanalRozenhoedkaai.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brugge-CanalRozenhoedkaai.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Brauerei%20De%20Halve%20Maan%20(Brouwerij%20De%20Halve%20Maan)%20in%20Br%C3%BCgge,%20Belgien%20-%20Eingangsbereich.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Damme%20town%20hall,%20Belgium.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/20110522%20Zwin%20(7).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/De%20Haan%20tramstation.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Oostende%20Albert%20I%20Promenade%20R01.jpg"}'::text[], '{"Brugy – Rozenhoedkaai a Belfort","Pivovar De Halve Maan (Brugy)","Damme","Přírodní rezervace Zwin","De Haan – belle époque","Oostende – Albert I. promenáda"}'::text[], '{"BE"}'::text[], false, 3150, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Brugy – Rozenhoedkaai a Belfort', 'Nejslavnější pohled Belgie: nábřeží Rozenhoedkaai, kde se středověké domy a 83 metrů vysoká zvonice Belfort zrcadlí v kanálu. Historické centrum je na seznamu UNESCO a nejlépe se projde pěšky – motorku nechte na parkovišti u okruhu. Ranní Brugy před příjezdem autobusů jsou kouzelné.', 51.2081, 3.2270, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brugge-CanalRozenhoedkaai.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brugge-CanalRozenhoedkaai.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Rozenhoedkaai%20Brugge.jpg"}'::text[], 0),
    (v_route, 'Pivovar De Halve Maan (Brugy)', 'Rodinný pivovar v centru Brug, kde se od roku 1856 vaří slavné pivo Brugse Zot a Straffe Hendrik. Prohlídka končí na střešní terase s výhledem na město a v restauraci vaří poctivou vlámskou kuchyni – karbonádu na pivu nebo severomořské ryby. Pro řidiče mají nealko variantu, plnou verzi si schovejte na večer.', 51.2029, 3.2245, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brauerei%20De%20Halve%20Maan%20(Brouwerij%20De%20Halve%20Maan)%20in%20Br%C3%BCgge,%20Belgien%20-%20Eingangsbereich.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brauerei%20De%20Halve%20Maan%20(Brouwerij%20De%20Halve%20Maan)%20in%20Br%C3%BCgge,%20Belgien%20-%20Eingangsbereich.jpg"}'::text[], 1),
    (v_route, 'Damme', 'Bývalý hanzovní přístav Brug, dnes ospalé městečko s gotickou radnicí, větrným mlýnem a knihkupectvími. Vede sem jedna z nejkrásnějších silniček Flander – alej podél kanálu Damse Vaart lemovaná topoly. Ideální krátká zastávka na kávu na náměstí.', 51.2511, 3.2814, 'https://commons.wikimedia.org/wiki/Special:FilePath/Damme%20town%20hall,%20Belgium.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Damme%20town%20hall,%20Belgium.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Book%20market%20in%20front%20of%20the%20Damme%20town%20hall,%20Belgium.jpg"}'::text[], 2),
    (v_route, 'Přírodní rezervace Zwin', 'Slaniska a laguny při ústí bývalého mořského ramene, kterému se říká mezinárodní letiště ptáků – zastávka tisíců čápů, rybáků a bahňáků. Vyhlídkové lávky vedou přímo mezi kanály zaplavovanými přílivem. Nezapomeňte na dalekohled, na jaře a na podzim je tu ptačí špička.', 51.3583, 3.3592, 'https://commons.wikimedia.org/wiki/Special:FilePath/20110522%20Zwin%20(7).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/20110522%20Zwin%20(7).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/20110522%20Zwin%20(32).jpg"}'::text[], 3),
    (v_route, 'De Haan – belle époque', 'Nejzachovalejší lázeňské letovisko belgického pobřeží, kde je celá čtvrť vil z přelomu století památkově chráněná – včetně půvabné tramvajové zastávky, u níž kdysi vystupoval Albert Einstein. Široká pláž je pár kroků od centra. Projížďka mezi vilami je jako cesta časem o sto let zpět.', 51.2725, 3.0347, 'https://commons.wikimedia.org/wiki/Special:FilePath/De%20Haan%20tramstation.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/De%20Haan%20tramstation.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/De%20Haan%20Hotel%20Belle%20Epoque%20R01.jpg"}'::text[], 4),
    (v_route, 'Oostende – Albert I. promenáda', 'Královna belgických plážových měst s širokou promenádou, přístavem a nejlepšími stánky s čerstvými rybami a garnáty na celém pobřeží. Projděte se po molu, dejte si kornout hranolek nebo rybí polévku ve Visserskaai. Odtud se vracíte poldery zpět do Brug.', 51.2326, 2.9126, 'https://commons.wikimedia.org/wiki/Special:FilePath/Oostende%20Albert%20I%20Promenade%20R01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oostende%20Albert%20I%20Promenade%20R01.jpg"}'::text[], 5);

  -- Gent a Flanderské Ardeny – Koppenberg a Muur
  delete from public.routes where name = 'Gent a Flanderské Ardeny – Koppenberg a Muur' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Gent a Flanderské Ardeny – Koppenberg a Muur', 'Okruh z Gentu do kopcovitého jihu Východních Flander, kterému se říká Flanderské Ardeny – kraj proslavený jarní cyklistickou klasikou Kolem Flander. Po prohlídce hradu Gravensteen zamíříte podél řeky Šeldy do Oudenaarde s nejkrásnější gotickou radnicí Belgie a pak na legendární kostkované stěny Koppenberg, Oude Kwaremont a Muur van Geraardsbergen, které na motorce vychutnáte úplně jinak než cyklisté. Mezi kopci se jezdí po úzkých silničkách mezi poli a chmelnicemi s výhledy do kraje. Na kostkách jeďte plynule a opatrně, za mokra jsou zrádné jak led. Nejhezčí od jara do podzimu; v dubnu o víkendu závodů kraj ožívá.', 'loop', 120, 180, 'medium',
     '[{"lat": 51.0543, "lng": 3.7174, "label": "Start: Gent"}, {"lat": 50.8442, "lng": 3.6072, "label": "Oudenaarde"}, {"lat": 50.8256, "lng": 3.5744, "label": "Koppenberg"}, {"lat": 50.7789, "lng": 3.5219, "label": "Oude Kwaremont"}, {"lat": 50.7658, "lng": 3.8811, "label": "Geraardsbergen"}, {"lat": 51.0543, "lng": 3.7174, "label": "Cíl: Gent"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.0543,3.7174&destination=51.0543,3.7174&travelmode=driving&waypoints=50.8442,3.6072%7C50.8256,3.5744%7C50.7789,3.5219%7C50.7658,3.8811', 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Gravensteen%20Castle%20-%20Ghent,%20Belgium%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/The%20Gravensteen%20Castle%20-%20Ghent,%20Belgium%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Oudenaarde%20(East%20Flanders,%20Belgium)%20late%20Gothic%20town%20hall%20and%20belfry%20tower.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monument%20Markt%201%20(stadhuis)%20Oudenaarde.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Koppenberg%20cobbles.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/De%20Sint-Amanduskerk%20gezien%20van%20op%20de%20Oude%20Kwaremont%20-%202020.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Muur%20van%20Geraardsbergen%20116.jpg"}'::text[], '{"Gravensteen (Gent)","Oudenaarde – radnice","Restaurace: Margaretha''s (Oudenaarde)","Koppenberg","Oude Kwaremont","Muur van Geraardsbergen (Kapelmuur)"}'::text[], '{"BE"}'::text[], false, 3160, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Gravensteen (Gent)', 'Vodní hrad flanderských hrabat z 12. století přímo uprostřed Gentu, s hradbami, věžemi a vodním příkopem jako z učebnice. Z ochozu je nejlepší výhled na věže a kanály města, které večer krásně nasvěcují. Před odjezdem stihněte aspoň krátkou procházku po nábřeží Graslei.', 51.0573, 3.7208, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Gravensteen%20Castle%20-%20Ghent,%20Belgium%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/The%20Gravensteen%20Castle%20-%20Ghent,%20Belgium%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gravensteen,%20Ghent%20(DSCF0191).jpg"}'::text[], 0),
    (v_route, 'Oudenaarde – radnice', 'Pozdně gotická radnice se zvonicí na seznamu UNESCO je klenotem městečka, které žije cyklistikou a pivem – sídlí tu muzeum závodu Kolem Flander i pivovar hnědých piv Liefmans. Náměstí lemují kavárny s terasami, ideální na pauzu před útokem na okolní kopce.', 50.8442, 3.6072, 'https://commons.wikimedia.org/wiki/Special:FilePath/Oudenaarde%20(East%20Flanders,%20Belgium)%20late%20Gothic%20town%20hall%20and%20belfry%20tower.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oudenaarde%20(East%20Flanders,%20Belgium)%20late%20Gothic%20town%20hall%20and%20belfry%20tower.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monument%20Markt%201%20(stadhuis)%20Oudenaarde.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Margaretha''s (Oudenaarde)', 'Elegantní restaurace přímo na náměstí v Oudenaarde s výhledem na radnici, vyhlášená moderní flanderskou kuchyní z lokálních surovin a skvělou kartou belgických piv. Patří k nejlépe hodnoceným podnikům ve městě. Polední menu je výhodné a rychlé, přesně do motorkářského dne.', 50.8444, 3.6069, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monument%20Markt%201%20(stadhuis)%20Oudenaarde.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monument%20Markt%201%20(stadhuis)%20Oudenaarde.jpg"}'::text[], 2),
    (v_route, 'Koppenberg', 'Nejobávanější stěna cyklistických Flander: 600 metrů kostek se sklonem až 22 procent v úvozu mezi stromy. Na motorce vyžaduje plynulý průjezd na jedničku a pevnou ruku, za mokra kostky raději objeďte. Nahoře se otevře výhled na zvlněný kraj, kterému se právem říká Flanderské Ardeny.', 50.8256, 3.5744, 'https://commons.wikimedia.org/wiki/Special:FilePath/Koppenberg%20cobbles.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Koppenberg%20cobbles.jpg"}'::text[], 3),
    (v_route, 'Oude Kwaremont', 'Nejdelší kostkované stoupání Flander vede kolem kostelíka sv. Amanda do vesničky Kwaremont, kde závod Kolem Flander každé jaro rozhoduje o vítězi. V místní hospodě čepují stejnojmenné pivo a stěny zdobí fotky legend. Výhledy z hřebene stojí za krátkou pěší procházku.', 50.7789, 3.5219, 'https://commons.wikimedia.org/wiki/Special:FilePath/De%20Sint-Amanduskerk%20gezien%20van%20op%20de%20Oude%20Kwaremont%20-%202020.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/De%20Sint-Amanduskerk%20gezien%20van%20op%20de%20Oude%20Kwaremont%20-%202020.jpg"}'::text[], 4),
    (v_route, 'Muur van Geraardsbergen (Kapelmuur)', 'Legendární kostkovaná zeď stoupající z náměstí v Geraardsbergen ke kapli Panny Marie na vrcholu Oudenberg. Z vrcholu je kruhový výhled na Flanderské Ardeny a Pajottenland; dole ve městě ochutnejte místní specialitu mattentaart. Důstojná tečka za okruhem před návratem do Gentu.', 50.7658, 3.8811, 'https://commons.wikimedia.org/wiki/Special:FilePath/Muur%20van%20Geraardsbergen%20116.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Muur%20van%20Geraardsbergen%20116.jpg"}'::text[], 5);

  -- Hageland – Leuven, Scherpenheuvel a Averbode
  delete from public.routes where name = 'Hageland – Leuven, Scherpenheuvel a Averbode' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Hageland – Leuven, Scherpenheuvel a Averbode', 'Pohodový okruh vinařským Hagelandem, nejstarším vinařským krajem Flander mezi Leuvenem a Diestem. Od nejzdobnější gotické radnice světa v Leuvenu pojedete kolem opatství Park přes železité vrchy s vinicemi k barokní poutní bazilice ve Scherpenheuvel a bílému opatství Averbode uprostřed borových lesů. Závěr patří Diestu s tichým bekinážním dvorem na seznamu UNESCO. Silničky mezi ovocnými sady a vinicemi jsou úzké, zvlněné a téměř prázdné – ideální na klidné tempo a časté zastávky. Trasa je nenáročná a krásná hlavně v dubnu, kdy kvetou sady, a na podzim při vinobraní.', 'loop', 95, 150, 'easy',
     '[{"lat": 50.8792, "lng": 4.7009, "label": "Start: Leuven"}, {"lat": 50.8631, "lng": 4.7181, "label": "Opatství Park"}, {"lat": 50.9800, "lng": 4.9772, "label": "Scherpenheuvel"}, {"lat": 51.0236, "lng": 4.9808, "label": "Averbode"}, {"lat": 50.9886, "lng": 5.0508, "label": "Diest"}, {"lat": 50.8792, "lng": 4.7009, "label": "Cíl: Leuven"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.8792,4.7009&destination=50.8792,4.7009&travelmode=driving&waypoints=50.8631,4.7181%7C50.9800,4.9772%7C51.0236,4.9808%7C50.9886,5.0508', 'https://commons.wikimedia.org/wiki/Special:FilePath/Leuven,%20stadhuis.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Leuven,%20stadhuis.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Abdij%20van%20''t%20Park.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Onze-Lieve-Vrouwebasiliek%20in%20Scherpenheuvel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Averbode%20Abdij%20R01.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Diest-begijnhof.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stadhuis%20Leuven.JPG"}'::text[], '{"Leuven – radnice","Opatství Park (Heverlee)","Bazilika Scherpenheuvel","Opatství Averbode","Diest – bekináž","Restaurace: Zarza (Leuven)"}'::text[], '{"BE"}'::text[], false, 3170, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Leuven – radnice', 'Pozdně gotická radnice na Grote Markt je pokrytá 236 sochami a považuje se za nejzdobnější na světě. Univerzitní Leuven žije studenty a pivem – na Oude Markt, nejdelším baru Evropy, sídlí desítky hospod a nedaleko stojí pivovar Stella Artois. Ranní káva na náměstí je skvělý start dne.', 50.8792, 4.7009, 'https://commons.wikimedia.org/wiki/Special:FilePath/Leuven,%20stadhuis.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Leuven,%20stadhuis.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stadhuis%20Leuven.JPG"}'::text[], 0),
    (v_route, 'Opatství Park (Heverlee)', 'Premonstrátské opatství ze 12. století na jižním okraji Leuvenu, obklopené rybníky, sady a poli – jeden z nejzachovalejších klášterních areálů Beneluxu. Sídlí tu muzeum náboženského umění PARCUM a kolem vodních ploch vede krásná okružní cesta. Klidná zastávka pár minut od centra.', 50.8631, 4.7181, 'https://commons.wikimedia.org/wiki/Special:FilePath/Abdij%20van%20''t%20Park.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Abdij%20van%20''t%20Park.JPG"}'::text[], 1),
    (v_route, 'Bazilika Scherpenheuvel', 'Nejvýznamnější poutní místo Belgie: raně barokní bazilika s hvězdami posetou kopulí stojí na kopci, kam už staletí míří poutníci za sochou Panny Marie. Sedmiúhelníkový půdorys a výhled z návrší dělají ze zastávky zážitek i pro nevěřící. Kolem baziliky voní stánky s poutními oplatkami.', 50.9800, 4.9772, 'https://commons.wikimedia.org/wiki/Special:FilePath/Onze-Lieve-Vrouwebasiliek%20in%20Scherpenheuvel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Onze-Lieve-Vrouwebasiliek%20in%20Scherpenheuvel.jpg"}'::text[], 2),
    (v_route, 'Opatství Averbode', 'Bílé premonstrátské opatství ze 12. století na rozhraní tří provincií, ukryté v borových lesích Kempenu. Barokní kostel patří k nejkrásnějším ve Flandrech a v klášterním obchodě koupíte pivo Averbode, sýry i chleba z vlastní pekárny. Terasa u brány je oblíbenou zastávkou motorkářů i cyklistů.', 51.0236, 4.9808, 'https://commons.wikimedia.org/wiki/Special:FilePath/Averbode%20Abdij%20R01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Averbode%20Abdij%20R01.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Abdij%20Averbode%20-%20Belgi%C3%AB.jpg"}'::text[], 3),
    (v_route, 'Diest – bekináž', 'Bekinážní dvůr z 13. století v Diestu je jedním z nejzachovalejších v Belgii a patří na seznam UNESCO – brána s Madonou, brukvové uličky a domky s bílenými fasádami působí, jako by se tu zastavil čas. Městečko nabízí i pěkné náměstí a pivo Gildenbier. Klidná tečka před návratem do Leuvenu.', 50.9886, 5.0508, 'https://commons.wikimedia.org/wiki/Special:FilePath/Diest-begijnhof.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Diest-begijnhof.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Begijnhof%20Diest%20-%20Kerkstraat.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Zarza (Leuven)', 'Moderní bistro-restaurace kousek od radnice v Leuvenu, která patří k nejlépe hodnoceným podnikům města. Otevřená kuchyně servíruje kreativní evropské menu ze sezónních surovin za férové ceny. Ideální večeře po okruhu; večer bývá plno, rezervujte předem.', 50.8781, 4.7031, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stadhuis%20Leuven.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stadhuis%20Leuven.JPG"}'::text[], 5);

  -- Condroz – Huy, Modave a zámek Jehay
  delete from public.routes where name = 'Condroz – Huy, Modave a zámek Jehay' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Condroz – Huy, Modave a zámek Jehay', 'Objevitelský okruh krajem Condroz – vlnící se krajinou vápencových hřbetů a úrodných údolí mezi Mázou a Ardenami, kterou turisté zatím míjejí. Z Huy s mohutnou citadelou nad řekou zamíříte k šachovnicovému zámku Jehay, pak do údolí říčky Hoyoux k baroknímu zámku Modave na skále a přes tiché vesnice z modrošedého kamene až do Crupet, jedné z nejkrásnějších vesnic Valonska. Silnice druhé a třetí třídy se tu neustále vlní nahoru a dolů, s rytmem dlouhých zatáček mezi poli a lesíky. Provoz minimální, povrch většinou dobrý; pozor na zemědělskou techniku a bláto u polí po dešti. Krásné od jara do zlatého podzimu.', 'loop', 100, 160, 'medium',
     '[{"lat": 50.5186, "lng": 5.2397, "label": "Start: Huy"}, {"lat": 50.5644, "lng": 5.2914, "label": "Château de Jehay"}, {"lat": 50.4453, "lng": 5.2958, "label": "Château de Modave"}, {"lat": 50.3494, "lng": 4.9528, "label": "Crupet"}, {"lat": 50.4894, "lng": 5.0964, "label": "Andenne"}, {"lat": 50.5186, "lng": 5.2397, "label": "Cíl: Huy"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.5186,5.2397&destination=50.5186,5.2397&travelmode=driving&waypoints=50.5644,5.2914%7C50.4453,5.2958%7C50.3494,4.9528%7C50.4894,5.0964', 'https://commons.wikimedia.org/wiki/Special:FilePath/Citadelle%20de%20Huy%20006.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Citadelle%20de%20Huy%20006.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Coll%C3%A9giale%20Notre-Dame,%20Huy-1130.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/0%20Jehay%20-%20Ch%C3%A2teau%20(1).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Modave-Ch%C3%A2teau%20de%20Modave%20(4).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Crupet%20Castle%20donjon%2002.JPG"}'::text[], '{"Huy – citadela a kolegiáta","Restaurace: Li Cwerneu (Huy)","Château de Jehay","Château de Modave","Crupet – donjon"}'::text[], '{"BE"}'::text[], false, 3180, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Huy – citadela a kolegiáta', 'Nad městem Huy se z vápencové skály zvedá pevnost z roku 1818 a pod ní gotická kolegiáta Notre-Dame se slavnou rozetou Rondia. Na citadelu vyjedete lanovkou nebo vystoupáte pěšky – výhled na údolí Mázy je nejlepší v okolí. Náměstí s fontánou Li Bassinia je příjemné na kávu.', 50.5186, 5.2372, 'https://commons.wikimedia.org/wiki/Special:FilePath/Citadelle%20de%20Huy%20006.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Citadelle%20de%20Huy%20006.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Coll%C3%A9giale%20Notre-Dame,%20Huy-1130.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Li Cwerneu (Huy)', 'Drobná gastronomická restaurace v historickém domku přímo na Grand-Place v Huy, oceňovaná za kreativní valonskou kuchyni ze surovin od okolních farmářů. Patří k nejlépe hodnoceným podnikům v kraji; polední menu je překvapivě dostupné. Ideální posila před zvlněnými silničkami Condroz.', 50.5178, 5.2394, 'https://commons.wikimedia.org/wiki/Special:FilePath/Coll%C3%A9giale%20Notre-Dame,%20Huy-1130.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Coll%C3%A9giale%20Notre-Dame,%20Huy-1130.jpg"}'::text[], 1),
    (v_route, 'Château de Jehay', 'Renesanční vodní zámek s nezaměnitelnou šachovnicovou fasádou z bílého a hnědého kamene, obklopený vodním příkopem a zahradami se sochami. Patří provincii Lutych a v sezóně se otevírá veřejnosti. Krátká odbočka z údolí Mázy, která stojí za každý kilometr.', 50.5644, 5.2914, 'https://commons.wikimedia.org/wiki/Special:FilePath/0%20Jehay%20-%20Ch%C3%A2teau%20(1).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/0%20Jehay%20-%20Ch%C3%A2teau%20(1).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A2teau%20de%20Jehay.JPG"}'::text[], 2),
    (v_route, 'Château de Modave', 'Barokní zámek na šedesátimetrové skále nad údolím Hoyoux, s bohatými štukovými interiéry a výhledem, který patří k nejhezčím ve Valonsku. Právě zde vzniklo vodní kolo, které později pohánělo fontány ve Versailles. Údolí Hoyoux pod zámkem je jedna z nejhezčích motorkářských silniček kraje.', 50.4453, 5.2958, 'https://commons.wikimedia.org/wiki/Special:FilePath/Modave-Ch%C3%A2teau%20de%20Modave%20(4).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Modave-Ch%C3%A2teau%20de%20Modave%20(4).jpg"}'::text[], 3),
    (v_route, 'Crupet – donjon', 'Vesnička Crupet patří mezi nejkrásnější vesnice Valonska a její středověká obytná věž obklopená vodním příkopem je jako z ilustrované kroniky. Kamenné domky, jeskyně sv. Antonína a hospůdka s místním pivem zvou k procházce. Silničky v okolí se krásně kroutí údolími potoků Bocq a Crupet.', 50.3494, 4.9528, 'https://commons.wikimedia.org/wiki/Special:FilePath/Crupet%20Castle%20donjon%2002.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Crupet%20Castle%20donjon%2002.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Crupet%20Castle%20donjon%2003.JPG"}'::text[], 4);

  -- Gaume – opatství Orval a Torgny
  delete from public.routes where name = 'Gaume – opatství Orval a Torgny' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Gaume – opatství Orval a Torgny', 'Okruh nejjižnějším cípem Belgie, slunečnou Gaume, které se pro mírné klima říká belgická Provence. Z Virtonu vyrazíte na sever k Semois u Chiny, pak k legendárnímu trapistickému opatství Orval, kde se vaří jedno z nejceněnějších piv světa, a zpět přes vinařskou vesničku Torgny s okrovými fasádami a zříceninu Montquintin na kopci. Silnice se vlní mezi loukami, lesíky a vápencovými hřbety, provoz je minimální a tempo si diktujete sami. Trasa je nenáročná a krásná od jara do pozdního podzimu. Pivo Orval si kupte s sebou – řízení a degustace počká na večer.', 'loop', 105, 165, 'easy',
     '[{"lat": 49.5675, "lng": 5.5325, "label": "Start: Virton"}, {"lat": 49.7369, "lng": 5.3411, "label": "Chiny"}, {"lat": 49.6389, "lng": 5.3494, "label": "Opatství Orval"}, {"lat": 49.5064, "lng": 5.4772, "label": "Torgny"}, {"lat": 49.5300, "lng": 5.4750, "label": "Montquintin"}, {"lat": 49.5675, "lng": 5.5325, "label": "Cíl: Virton"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.5675,5.5325&destination=49.5675,5.5325&travelmode=driving&waypoints=49.7369,5.3411%7C49.6389,5.3494%7C49.5064,5.4772%7C49.5300,5.4750', 'https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20d''Orval%20-%20Ruins%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P1090022%20Chiny.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20d''Orval%20-%20Ruins%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/BE-LX-Orval%20Abbaye%20hostellerie.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Torgny%20-%20Clos%20de%20l''Epinette.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Montquintin%20JPG00.JPG"}'::text[], '{"Chiny – brána Semois","Opatství Orval","Restaurace: À l''Ange Gardien (Orval)","Torgny","Montquintin – zřícenina"}'::text[], '{"BE"}'::text[], false, 3190, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Chiny – brána Semois', 'Kamenná vesnice na horním toku Semois, odkud řeka vstupuje do hlubokých ardenských lesů. V létě odsud vyplouvají tradiční pramice s převozníky do Lacuisine – nejromantičtější způsob, jak poznat řeku. Most a nábřeží jsou příjemnou první zastávkou okruhu.', 49.7369, 5.3411, 'https://commons.wikimedia.org/wiki/Special:FilePath/P1090022%20Chiny.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P1090022%20Chiny.JPG"}'::text[], 0),
    (v_route, 'Opatství Orval', 'Trapistické opatství v zeleném údolí, kde se vaří legendární pivo Orval a zraje stejnojmenný sýr. Prohlédnout si můžete rozsáhlé středověké ruiny se studánkou Mathildy, jejíž legenda o navráceném prstenu zdobí každou lahev. Nový klášter slouží mnichům, obchod u brány prodává pivo i sýr.', 49.6389, 5.3494, 'https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20d''Orval%20-%20Ruins%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Abbaye%20d''Orval%20-%20Ruins%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Abdij%20van%20Orval.jpg"}'::text[], 1),
    (v_route, 'Restaurace: À l''Ange Gardien (Orval)', 'Hostinec u brány opatství Orval, jediné místo na světě, kde se dá ochutnat vzácný Orval Vert – mladší, slabší verze klášterního piva čepovaná jen zde. K tomu poctivá venkovská kuchyně se sýrem z opatství a paštikami z Gaume. Terasa s výhledem do lesů je v sezóně plná motorkářů.', 49.6394, 5.3486, 'https://commons.wikimedia.org/wiki/Special:FilePath/BE-LX-Orval%20Abbaye%20hostellerie.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/BE-LX-Orval%20Abbaye%20hostellerie.JPG"}'::text[], 2),
    (v_route, 'Torgny', 'Nejjižnější vesnice Belgie a členka klubu nejkrásnějších vesnic Valonska: okrové kamenné domy s prejzovými střechami, jižní stráň s vinicí Clos de l''Epinette a mikroklima, ve kterém rostou i ještěrky a orchideje. Působí spíš jako Burgundsko než Belgie. Projděte se vinicí a ochutnejte místní víno.', 49.5064, 5.4772, 'https://commons.wikimedia.org/wiki/Special:FilePath/Torgny%20-%20Clos%20de%20l''Epinette.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Torgny%20-%20Clos%20de%20l''Epinette.jpg"}'::text[], 3),
    (v_route, 'Montquintin – zřícenina', 'Zřícenina hradu z 12. století na jednom z nejvyšších kopců Gaume, s výhledem přes údolí Tonu až do Francie. U hradu stojí románský kostelík a muzeum venkovského života ve staré faře. Silnička nahoru je úzká a strmá – přesně taková, jaké máme rádi.', 49.5300, 5.4750, 'https://commons.wikimedia.org/wiki/Special:FilePath/Montquintin%20JPG00.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Montquintin%20JPG00.JPG"}'::text[], 4);

  -- Údolí Ourthe – Le Hérou, Nisramont a Achouffe
  delete from public.routes where name = 'Údolí Ourthe – Le Hérou, Nisramont a Achouffe' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí Ourthe – Le Hérou, Nisramont a Achouffe', 'Okruh divokým srdcem Arden kolem Houffalize, mekky evropských bikerů na břehu Ourthe. Čeká vás pivovar Achouffe s ikonickým skřítkem, stoupání na Baraque de Fraiture – třetí nejvyšší bod Belgie, skalní vyhlídka Le Hérou nad sevřenými meandry řeky a hráz přehrady Nisramont, kde se obě Ourthe potkávají v jednom jezeře. Silnice se střídají od rychlých hřebenových pasáží po utažené serpentiny do údolí; asfalt je vesměs výborný. V lesích pozor na zvěř za soumraku a vlhké úseky ve stínu. Nejkrásněji je tu v říjnu, kdy ardenské lesy hrají všemi barvami.', 'loop', 85, 145, 'medium',
     '[{"lat": 50.1325, "lng": 5.7897, "label": "Start: Houffalize"}, {"lat": 50.1614, "lng": 5.7758, "label": "Achouffe"}, {"lat": 50.2489, "lng": 5.7364, "label": "Baraque de Fraiture"}, {"lat": 50.1592, "lng": 5.6733, "label": "Nadrin – Le Hérou"}, {"lat": 50.1300, "lng": 5.6903, "label": "Barrage de Nisramont"}, {"lat": 50.1325, "lng": 5.7897, "label": "Cíl: Houffalize"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.1325,5.7897&destination=50.1325,5.7897&travelmode=driving&waypoints=50.1614,5.7758%7C50.2489,5.7364%7C50.1592,5.6733%7C50.1300,5.6903', 'https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Herou01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Houffalize%200011.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20van%20Achouffe.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20van%20Achouffe.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Skipiste%20Baraque%20Fraiture.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Herou01.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/0%20Nisramont%20-%20Barrage%20(1).JPG"}'::text[], '{"Houffalize","Pivovar Achouffe (La Chouffe)","Restaurace: La Petite Fontaine (Achouffe)","Baraque de Fraiture","Le Hérou (Nadrin)","Barrage de Nisramont"}'::text[], '{"BE"}'::text[], false, 3200, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Houffalize', 'Městečko v hlubokém údolí Ourthe, přezdívané srdce Arden, s tankem Panther na náměstí jako připomínkou bitvy v Ardenách. Dnes je Houffalize hlavně rájem horských kol a motorek – kavárny na náměstí jsou ideální na ranní kávu před startem. Sjezd do města a výjezd ven jsou samy o sobě pěkné serpentiny.', 50.1325, 5.7897, 'https://commons.wikimedia.org/wiki/Special:FilePath/Houffalize%200011.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Houffalize%200011.JPG"}'::text[], 0),
    (v_route, 'Pivovar Achouffe (La Chouffe)', 'Kultovní pivovar v údolíčku u Achouffe, jehož pivo se skřítkem v červené čepici zná celý svět. Návštěvnické centrum nabízí prohlídky s ochutnávkou a obchod se vším od piva po ponožky se skřítkem. Řidiči si odvezou lahve na večer – nebo nealko verzi Chouffe 0,4 %.', 50.1614, 5.7758, 'https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20van%20Achouffe.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20van%20Achouffe.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Chouffe-Zwerg%202014.JPG"}'::text[], 1),
    (v_route, 'Restaurace: La Petite Fontaine (Achouffe)', 'Vyhlášená hospůdka pár kroků od pivovaru v Achouffe, kde vaří ardenskou klasiku – zvěřinu, pstruhy a slavné pivní tlačenky – a čepují celou rodinu piv Chouffe. Mezi motorkáři jde o jednu z nejoblíbenějších zastávek v Ardenách, o víkendech počítejte s plnou terasou.', 50.1611, 5.7761, 'https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20van%20Achouffe.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20van%20Achouffe.JPG"}'::text[], 2),
    (v_route, 'Baraque de Fraiture', 'Třetí nejvyšší bod Belgie (652 m) na náhorní plošině mezi Vielsalm a La Roche, v zimě lyžařské středisko, po zbytek roku křižovatka výletních tras s výhledy přes ardenské hřebeny. U silnice stojí památník bitvy v Ardenách s houfnicí. Hřebenová silnice N89 odsud dolů je rychlá a plynulá radost.', 50.2489, 5.7364, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skipiste%20Baraque%20Fraiture.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skipiste%20Baraque%20Fraiture.JPG"}'::text[], 3),
    (v_route, 'Le Hérou (Nadrin)', 'Skalnatý ostroh nad nejdivočejším úsekem Ourthe, kde řeka kreslí šest meandrů hluboko v lesích – podle mnohých nejkrásnější přírodní vyhlídka Arden. Od parkoviště u Nadrin je to krátká procházka k belvedéru s kruhovým rozhledem. Silnička z Nadrin dolů k řece je úzká, strmá a zábavná.', 50.1592, 5.6733, 'https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Herou01.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Le%20Herou01.jpg"}'::text[], 4),
    (v_route, 'Barrage de Nisramont', 'Hráz na Ourthe kousek pod soutokem obou pramenných řek vytváří klidné jezero sevřené zalesněnými svahy. Po koruně hráze se dá projít a kolem jezera vede okružní stezka s lávkami nad hladinou. Tichá tečka okruhu před posledními kilometry zpět do Houffalize.', 50.1300, 5.6903, 'https://commons.wikimedia.org/wiki/Special:FilePath/0%20Nisramont%20-%20Barrage%20(1).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/0%20Nisramont%20-%20Barrage%20(1).JPG"}'::text[], 5);

end $$;
