-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — BULHARSKO (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Rilský klášter a hory Rila
  delete from public.routes where name = 'Rilský klášter a hory Rila' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rilský klášter a hory Rila', 'Okruh nejvyšším pohořím Balkánu k proslulému Rilskému klášteru. Serpentiny mezi štíty, ledovcová jezera a nejposvátnější místo Bulharska nabízí horské zážitky i duchovní klid. Nejlepší od června do září; pozor na horské silnice a mlhy ve výškách.', 'loop', 170, 240, 'medium',
     '[{"lat": 42.1333, "lng": 23.34, "label": "Start: Rilský klášter"}, {"lat": 42.19, "lng": 23.36, "label": "Kirilova poljana"}, {"lat": 42.1789, "lng": 23.3556, "label": "Maljovica"}, {"lat": 42.1333, "lng": 23.34, "label": "Cíl: Rilský klášter"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.1333,23.34&destination=42.1333,23.34&travelmode=driving&waypoints=42.19,23.36%7C42.1789,23.3556', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Malyovitsa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Seven_Rila_Lakes.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stob_Pyramids.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery.jpg"}'::text[], '{"Rilský klášter","Maljovica","Sedm rilských jezer","Stob – pyramidy","Jeskyně Svatého Ivana"}'::text[], '{"BG"}'::text[], false, 3210, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Rilský klášter', 'Největší a nejposvátnější klášter Bulharska s pruhovanými arkádami a freskami, UNESCO památka. Duchovní srdce země ukryté v horách.', 42.1333, 23.34, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery.jpg"}'::text[], 0),
    (v_route, 'Maljovica', 'Horské středisko pod skalnatými štíty Rily, výchozí bod k jezerům a vrcholům. Ráj horských scenérií.', 42.1789, 23.3556, 'https://commons.wikimedia.org/wiki/Special:FilePath/Malyovitsa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Malyovitsa.jpg"}'::text[], 1),
    (v_route, 'Sedm rilských jezer', 'Skupina ledovcových jezer v nejvyšších partiích Rily, jeden z nejkrásnějších přírodních útvarů Balkánu. Ikonická scenérie.', 42.21, 23.32, 'https://commons.wikimedia.org/wiki/Special:FilePath/Seven_Rila_Lakes.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Seven_Rila_Lakes.jpg"}'::text[], 2),
    (v_route, 'Stob – pyramidy', 'Bizarní erozní věže z červené horniny nad vesnicí Stob u Rily. Ojedinělý geologický úkaz.', 42.15, 23.13, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stob_Pyramids.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stob_Pyramids.jpg"}'::text[], 3),
    (v_route, 'Jeskyně Svatého Ivana', 'Poustevnická jeskyně zakladatele kláštera Ivana Rilského nedaleko areálu. Poutní zastávka.', 42.13, 23.3556, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rila_Monastery.jpg"}'::text[], 4);

  -- Pirin, Bansko a Melnik
  delete from public.routes where name = 'Pirin, Bansko a Melnik' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Pirin, Bansko a Melnik', 'Trasa jihozápadem Bulharska pod štíty Pirinu k nejmenšímu městu země. Horské Bansko, pískovcové pyramidy Melniku a vinařská tradice nabízí zážitkovou jízdu i skvělé víno. Nejlepší od jara do podzimu; pozor na horské silnice a horko na jihu.', 'poi', 160, 225, 'medium',
     '[{"lat": 41.8375, "lng": 23.4881, "label": "Start: Bansko"}, {"lat": 41.5228, "lng": 23.3931, "label": "Melnik"}, {"lat": 41.53, "lng": 23.43, "label": "Rožen"}, {"lat": 41.8375, "lng": 23.4881, "label": "Cíl: Bansko"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=41.8375,23.4881&destination=41.8375,23.4881&travelmode=driving&waypoints=41.5228,23.3931%7C41.53,23.43', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bansko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bansko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Melnik.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Melnik_Pyramids.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozhen_Monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pirin_National_Park.jpg"}'::text[], '{"Bansko","Melnik","Melnické pyramidy","Rožen – klášter","Národní park Pirin"}'::text[], '{"BG"}'::text[], false, 3220, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Bansko', 'Horské středisko pod štíty Pirinu s kamennou architekturou a živou mehanou. Brána do národního parku.', 41.8375, 23.4881, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bansko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bansko.jpg"}'::text[], 0),
    (v_route, 'Melnik', 'Nejmenší město Bulharska ukryté mezi pískovcovými pyramidami, proslulé silným vínem. Půvabná zastávka mimo čas.', 41.5228, 23.3931, 'https://commons.wikimedia.org/wiki/Special:FilePath/Melnik.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Melnik.jpg"}'::text[], 1),
    (v_route, 'Melnické pyramidy', 'Bizarní pískovcové věže obklopující městečko, výtvor eroze. Ojedinělá scenérie jihu.', 41.525, 23.4, 'https://commons.wikimedia.org/wiki/Special:FilePath/Melnik_Pyramids.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Melnik_Pyramids.jpg"}'::text[], 2),
    (v_route, 'Rožen – klášter', 'Největší středověký klášter v Pirinu s freskami a vinicemi v okolí. Klidná zastávka nad pyramidami.', 41.5306, 23.4297, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozhen_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozhen_Monastery.jpg"}'::text[], 3),
    (v_route, 'Národní park Pirin', 'Divoké pohoří s ledovcovými jezery a starými borovicemi, UNESCO památka. Ráj horské přírody.', 41.73, 23.46, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pirin_National_Park.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pirin_National_Park.jpg"}'::text[], 4);

  -- Rodopy a soutěska Trigrad
  delete from public.routes where name = 'Rodopy a soutěska Trigrad' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rodopy a soutěska Trigrad', 'Náročný okruh divokými Rodopy plnými soutěsek a jeskyní. Dramatická soutěska Trigrad, Ďáblovo hrdlo a horské vesnice nabízí adrenalinovou jízdu a tajuplnou atmosféru. Nejlepší od května do října; pozor na úzké skalní silnice a tunely.', 'loop', 180, 255, 'hard',
     '[{"lat": 41.5764, "lng": 24.7106, "label": "Start: Smoljan"}, {"lat": 41.6144, "lng": 24.3789, "label": "Trigrad"}, {"lat": 41.7431, "lng": 24.4, "label": "Devín"}, {"lat": 41.5764, "lng": 24.7106, "label": "Cíl: Smoljan"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=41.5764,24.7106&destination=41.5764,24.7106&travelmode=driving&waypoints=41.6144,24.3789%7C41.7431,24.4', 'https://commons.wikimedia.org/wiki/Special:FilePath/Trigrad_Gorge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trigrad_Gorge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Smolyan.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Devin.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Devil%27s_Throat_Cave.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Shiroka_Laka.jpg"}'::text[], '{"Soutěska Trigrad","Smoljan","Devín","Ďáblovo hrdlo","Vesnice Široka Laka"}'::text[], '{"BG"}'::text[], false, 3230, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Soutěska Trigrad', 'Dramatická skalní soutěska s kolmými stěnami a jeskyní Ďáblovo hrdlo, kam podle legendy sestoupil Orfeus. Nejtajemnější místo Rodop.', 41.6144, 24.3789, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trigrad_Gorge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trigrad_Gorge.jpg"}'::text[], 0),
    (v_route, 'Smoljan', 'Horské město roztažené v údolí pod nejvyššími štíty Rodop, výchozí bod do hor. Brána do divokého kraje.', 41.5764, 24.7106, 'https://commons.wikimedia.org/wiki/Special:FilePath/Smolyan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Smolyan.jpg"}'::text[], 1),
    (v_route, 'Devín', 'Lázeňské městečko proslulé minerální vodou v hlubokém říčním údolí. Osvěžující zastávka mezi horami.', 41.7431, 24.4, 'https://commons.wikimedia.org/wiki/Special:FilePath/Devin.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Devin.jpg"}'::text[], 2),
    (v_route, 'Ďáblovo hrdlo', 'Podzemní jeskyně s hučícím vodopádem, kde řeka mizí ve skále. Legendární brána do podsvětí.', 41.6144, 24.3789, 'https://commons.wikimedia.org/wiki/Special:FilePath/Devil%27s_Throat_Cave.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Devil%27s_Throat_Cave.jpg"}'::text[], 3),
    (v_route, 'Vesnice Široka Laka', 'Malebná horská vesnice s kamennou architekturou a školou lidové hudby. Ukázka rodopské kultury.', 41.63, 24.55, 'https://commons.wikimedia.org/wiki/Special:FilePath/Shiroka_Laka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Shiroka_Laka.jpg"}'::text[], 4);

  -- Šipka a pohoří Stara planina
  delete from public.routes where name = 'Šipka a pohoří Stara planina' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Šipka a pohoří Stara planina', 'Okruh přes průsmyk Šipka v srdci Balkánu, kde se psaly dějiny Bulharska. Zlatý chrám, památník svobody a bizarní pomník Buzludža nabízí historii i horské výhledy. Nejlepší od května do října; pozor na mlhy v průsmyku.', 'loop', 170, 225, 'medium',
     '[{"lat": 42.62, "lng": 25.3931, "label": "Start: Kazanlak"}, {"lat": 42.7194, "lng": 25.32, "label": "Šipka – chrám"}, {"lat": 42.7357, "lng": 25.3931, "label": "Buzludža"}, {"lat": 42.62, "lng": 25.3931, "label": "Cíl: Kazanlak"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.62,25.3931&destination=42.62,25.3931&travelmode=driving&waypoints=42.7194,25.32%7C42.7357,25.3931', 'https://commons.wikimedia.org/wiki/Special:FilePath/Shipka_Memorial_Church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Shipka_Memorial_Church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Shipka_Monument.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Buzludzha.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kazanlak.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Etar.jpg"}'::text[], '{"Chrám Šipka","Památník svobody na Šipce","Pomník Buzludža","Kazanlak – Údolí růží","Etar – skanzen"}'::text[], '{"BG"}'::text[], false, 3240, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Chrám Šipka', 'Zlatě zdobený ruský pravoslavný chrám na úpatí průsmyku, památník padlým v osvobozenecké válce. Nejfotogeničtější kostel Bulharska.', 42.7194, 25.32, 'https://commons.wikimedia.org/wiki/Special:FilePath/Shipka_Memorial_Church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Shipka_Memorial_Church.jpg"}'::text[], 0),
    (v_route, 'Památník svobody na Šipce', 'Kamenná věž na vrcholu průsmyku připomínající obranu proti Osmanům. Ikona bulharské nezávislosti a daleké výhledy.', 42.7458, 25.3306, 'https://commons.wikimedia.org/wiki/Special:FilePath/Shipka_Monument.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Shipka_Monument.jpg"}'::text[], 1),
    (v_route, 'Pomník Buzludža', 'Monumentální opuštěný komunistický památník ve tvaru UFO na vrcholu hory. Surreální kulisa a symbol minulé éry.', 42.7357, 25.3931, 'https://commons.wikimedia.org/wiki/Special:FilePath/Buzludzha.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Buzludzha.jpg"}'::text[], 2),
    (v_route, 'Kazanlak – Údolí růží', 'Město uprostřed proslulého Údolí růží s thráckou hrobkou UNESCO. Voňavá zastávka pod horami.', 42.6178, 25.3936, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kazanlak.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kazanlak.jpg"}'::text[], 3),
    (v_route, 'Etar – skanzen', 'Živý skanzen řemesel s vodními mlýny a dílnami u Gabrova. Ukázka bulharské tradice.', 42.83, 25.32, 'https://commons.wikimedia.org/wiki/Special:FilePath/Etar.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Etar.jpg"}'::text[], 4);

  -- Veliko Tarnovo a středověké památky
  delete from public.routes where name = 'Veliko Tarnovo a středověké památky' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Veliko Tarnovo a středověké památky', 'Okruh kolem bývalé carské metropole Bulharska. Pevnost Carevec nad meandrem řeky, malebné Arbanasi a klidné silnice nabízí koncentraci středověké historie. Nejlepší od jara do podzimu; pozor na turisty ve městě.', 'loop', 140, 195, 'easy',
     '[{"lat": 43.0813, "lng": 25.655, "label": "Start: Veliko Tarnovo"}, {"lat": 43.0778, "lng": 25.67, "label": "Arbanasi"}, {"lat": 43.11, "lng": 25.65, "label": "Preobraženský klášter"}, {"lat": 43.0813, "lng": 25.655, "label": "Cíl: Veliko Tarnovo"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.0813,25.655&destination=43.0813,25.655&travelmode=driving&waypoints=43.0778,25.67%7C43.11,25.65', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tsarevets.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tsarevets.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Veliko_Tarnovo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Arbanasi.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Preobrazhenski_Monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nicopolis_ad_Istrum.jpg"}'::text[], '{"Pevnost Carevec","Staré město Veliko Tarnovo","Arbanasi","Preobraženský klášter","Nikopolis ad Istrum"}'::text[], '{"BG"}'::text[], false, 3250, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Pevnost Carevec', 'Mohutná středověká pevnost na kopci nad meandrem Jantry, sídlo bulharských carů. Nejpůsobivější hrad země.', 43.0817, 25.6558, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tsarevets.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tsarevets.jpg"}'::text[], 0),
    (v_route, 'Staré město Veliko Tarnovo', 'Malebné domy nalepené na strmém svahu nad řekou s řemeslnou ulicí Samovodska čaršija. Srdce bývalé metropole.', 43.0813, 25.655, 'https://commons.wikimedia.org/wiki/Special:FilePath/Veliko_Tarnovo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Veliko_Tarnovo.jpg"}'::text[], 1),
    (v_route, 'Arbanasi', 'Vesnice nad městem s kamennými domy-pevnostmi a kostely plnými fresek. Klidná zastávka s výhledem.', 43.0778, 25.67, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arbanasi.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arbanasi.jpg"}'::text[], 2),
    (v_route, 'Preobraženský klášter', 'Největší klášter regionu zavěšený pod skalami severně od města. Freskami zdobený klenot.', 43.11, 25.65, 'https://commons.wikimedia.org/wiki/Special:FilePath/Preobrazhenski_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Preobrazhenski_Monastery.jpg"}'::text[], 3),
    (v_route, 'Nikopolis ad Istrum', 'Ruiny římského města s dochovaným náměstím a ulicemi severně od Tarnova. Cesta do antiky.', 43.22, 25.61, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nicopolis_ad_Istrum.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nicopolis_ad_Istrum.jpg"}'::text[], 4);

  -- Severní Černomoří – Kaliakra a Balčik
  delete from public.routes where name = 'Severní Černomoří – Kaliakra a Balčik' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Severní Černomoří – Kaliakra a Balčik', 'Trasa podél severního bulharského pobřeží Černého moře. Červené útesy mysu Kaliakra, romantický palác v Balčiku a stepní rezervace nabízí moře, historii a mírné silnice. Nejlepší od května do září; pozor na letní provoz u letovisek.', 'poi', 150, 195, 'easy',
     '[{"lat": 43.4181, "lng": 28.16, "label": "Start: Balčik"}, {"lat": 43.3644, "lng": 28.46, "label": "Kaliakra"}, {"lat": 43.43, "lng": 28.34, "label": "Kavarna"}, {"lat": 43.4181, "lng": 28.16, "label": "Cíl: Balčik"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.4181,28.16&destination=43.4181,28.16&travelmode=driving&waypoints=43.3644,28.46%7C43.43,28.34', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cape_Kaliakra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cape_Kaliakra.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Balchik_Palace.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kavarna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Yailata.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Balchik_Botanical_Garden.jpg"}'::text[], '{"Mys Kaliakra","Palác v Balčiku","Kavarna","Rezervace Jajlata","Botanická zahrada Balčik"}'::text[], '{"BG"}'::text[], false, 3260, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Mys Kaliakra', 'Dlouhý červený útes zabíhající do moře s pevností a legendou o 40 dívkách. Nejdramatičtější místo bulharského pobřeží.', 43.3644, 28.465, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cape_Kaliakra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cape_Kaliakra.jpg"}'::text[], 0),
    (v_route, 'Palác v Balčiku', 'Romantický rumunský palác královny Marie s botanickou zahradou nad mořem. Idylická zastávka mezi květinami.', 43.4181, 28.16, 'https://commons.wikimedia.org/wiki/Special:FilePath/Balchik_Palace.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Balchik_Palace.jpg"}'::text[], 1),
    (v_route, 'Kavarna', 'Přístavní městečko proslulé rockovými festivaly na útesech nad mořem. Živá zastávka na pobřeží.', 43.4331, 28.34, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kavarna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kavarna.jpg"}'::text[], 2),
    (v_route, 'Rezervace Jajlata', 'Skalnaté pobřeží s jeskynními obydlími a hnízdišti ptáků. Divoká zastávka pro milovníky přírody.', 43.4344, 28.51, 'https://commons.wikimedia.org/wiki/Special:FilePath/Yailata.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Yailata.jpg"}'::text[], 3),
    (v_route, 'Botanická zahrada Balčik', 'Rozlehlá zahrada s kaktusy a středomořskými rostlinami obklopující palác. Klidné bloudění nad mořem.', 43.4181, 28.16, 'https://commons.wikimedia.org/wiki/Special:FilePath/Balchik_Botanical_Garden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Balchik_Botanical_Garden.jpg"}'::text[], 4);

  -- Belogradčické skály a Vraca
  delete from public.routes where name = 'Belogradčické skály a Vraca' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Belogradčické skály a Vraca', 'Okruh severozápadem Bulharska mezi bizarními skalami a soutěskami. Červené věže Belogradčiku, jeskyně Magura a soutěska Vraca nabízí dramatickou přírodu daleko od davů. Nejlepší od jara do podzimu; pozor na řidší zázemí.', 'loop', 180, 240, 'medium',
     '[{"lat": 43.63, "lng": 22.68, "label": "Start: Belogradčik"}, {"lat": 43.73, "lng": 22.58, "label": "Jeskyně Magura"}, {"lat": 43.21, "lng": 23.55, "label": "Vraca"}, {"lat": 43.63, "lng": 22.68, "label": "Cíl: Belogradčik"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=43.63,22.68&destination=43.63,22.68&travelmode=driving&waypoints=43.73,22.58%7C43.21,23.55', 'https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Rocks.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Rocks.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Magura_Cave.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vratsata.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vratsa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Fortress.jpg"}'::text[], '{"Belogradčické skály","Jeskyně Magura","Vračanský Balkán","Vodopád Skaklja","Pevnost Belogradčik"}'::text[], '{"BG"}'::text[], false, 3270, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Belogradčické skály', 'Fantastické červené skalní věže táhnoucí se kilometry, s pevností vklíněnou mezi útesy. Jeden z divů Bulharska.', 43.625, 22.68, 'https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Rocks.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Rocks.jpg"}'::text[], 0),
    (v_route, 'Jeskyně Magura', 'Rozlehlá jeskyně s pravěkými nástěnnými malbami netopýřím guánem. Podzemní zážitek severozápadu.', 43.7333, 22.5833, 'https://commons.wikimedia.org/wiki/Special:FilePath/Magura_Cave.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Magura_Cave.jpg"}'::text[], 1),
    (v_route, 'Vračanský Balkán', 'Dramatická vápencová soutěska a jeskyně Ledenika nad městem Vraca. Ráj skalní scenérie.', 43.19, 23.53, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vratsata.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vratsata.jpg"}'::text[], 2),
    (v_route, 'Vodopád Skaklja', 'Sezonní vodopád padající ze skal nad Vracou, jeden z nejvyšších v zemi. Působivá zastávka za deště.', 43.21, 23.55, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vratsa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vratsa.jpg"}'::text[], 3),
    (v_route, 'Pevnost Belogradčik', 'Antická pevnost důmyslně vestavěná mezi skalní věže nad městem. Výhledy do skalního města.', 43.6222, 22.68, 'https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Fortress.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Fortress.jpg"}'::text[], 4);

  -- Plovdiv a klášter Bačkovo
  delete from public.routes where name = 'Plovdiv a klášter Bačkovo' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Plovdiv a klášter Bačkovo', 'Okruh od nejstaršího nepřetržitě obývaného města Evropy k druhému největšímu klášteru Bulharska. Antické památky Plovdivu, freskami zdobené Bačkovo a Rodopské předhůří nabízí kulturu i klidnou jízdu. Nejlepší od jara do podzimu; pozor na provoz v Plovdivu.', 'loop', 150, 195, 'easy',
     '[{"lat": 42.1354, "lng": 24.7453, "label": "Start: Plovdiv"}, {"lat": 41.9411, "lng": 24.8497, "label": "Bačkovo"}, {"lat": 41.98, "lng": 24.86, "label": "Asenova pevnost"}, {"lat": 42.1354, "lng": 24.7453, "label": "Cíl: Plovdiv"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.1354,24.7453&destination=42.1354,24.7453&travelmode=driving&waypoints=41.9411,24.8497%7C41.98,24.86', 'https://commons.wikimedia.org/wiki/Special:FilePath/Plovdiv_Old_Town.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plovdiv_Old_Town.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bachkovo_Monastery.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Asen%27s_Fortress.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ancient_Theatre_of_Philippopolis.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Plovdiv.jpg"}'::text[], '{"Staré město Plovdiv","Klášter Bačkovo","Asenova pevnost","Antické divadlo Plovdiv","Vrch Bunardžik"}'::text[], '{"BG"}'::text[], false, 3280, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Staré město Plovdiv', 'Nejstarší nepřetržitě obývané město Evropy s antickým divadlem a barevnými domy obrození. Kulturní klenot Balkánu.', 42.1486, 24.7517, 'https://commons.wikimedia.org/wiki/Special:FilePath/Plovdiv_Old_Town.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plovdiv_Old_Town.jpg"}'::text[], 0),
    (v_route, 'Klášter Bačkovo', 'Druhý největší klášter Bulharska s nádhernými freskami v horách jižně od Plovdivu. Duchovní zastávka mezi kopci.', 41.9411, 24.8497, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bachkovo_Monastery.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bachkovo_Monastery.jpg"}'::text[], 1),
    (v_route, 'Asenova pevnost', 'Dramatická středověká pevnost s kostelem na skále nad říčním údolím. Nejfotogeničtější hrad regionu.', 41.985, 24.866, 'https://commons.wikimedia.org/wiki/Special:FilePath/Asen%27s_Fortress.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Asen%27s_Fortress.jpg"}'::text[], 2),
    (v_route, 'Antické divadlo Plovdiv', 'Skvěle zachovalé římské divadlo s výhledem na město, dodnes sloužící představením. Skvost antiky.', 42.1467, 24.7508, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ancient_Theatre_of_Philippopolis.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ancient_Theatre_of_Philippopolis.jpg"}'::text[], 3),
    (v_route, 'Vrch Bunardžik', 'Jeden z pahorků Plovdivu s pomníkem Aljoša a výhledem na město. Klidná zastávka nad střechami.', 42.1494, 24.7375, 'https://commons.wikimedia.org/wiki/Special:FilePath/Plovdiv.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plovdiv.jpg"}'::text[], 4);

  -- Sozopol a jižní Černomoří
  delete from public.routes where name = 'Sozopol a jižní Černomoří' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sozopol a jižní Černomoří', 'Trasa jižním bulharským pobřežím Černého moře. Starobylé Sozopol na poloostrově, přírodní rezervace Ropotamo a písečné pláže nabízí moře, antiku i klid. Nejlepší od května do září; pozor na letní provoz.', 'poi', 130, 180, 'easy',
     '[{"lat": 42.4181, "lng": 27.6953, "label": "Start: Sozopol"}, {"lat": 42.32, "lng": 27.72, "label": "Ropotamo"}, {"lat": 42.1, "lng": 27.95, "label": "Ahtopol"}, {"lat": 42.4181, "lng": 27.6953, "label": "Cíl: Sozopol"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.4181,27.6953&destination=42.4181,27.6953&travelmode=driving&waypoints=42.32,27.72%7C42.1,27.95', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sozopol.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sozopol.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ropotamo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ahtopol.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dyuni.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nessebar.jpg"}'::text[], '{"Staré město Sozopol","Rezervace Ropotamo","Ahtopol","Pláž Djuni","Nesebar"}'::text[], '{"BG"}'::text[], false, 3290, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Staré město Sozopol', 'Antické město na skalnatém poloostrově s dřevěnými domy a úzkými uličkami nad mořem. Nejromantičtější letovisko jihu.', 42.4181, 27.6953, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sozopol.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sozopol.jpg"}'::text[], 0),
    (v_route, 'Rezervace Ropotamo', 'Ústí řeky s lužními lesy, lekníny a útesy, ráj ptactva a lodních vyjížděk. Divoká oáza mezi letovisky.', 42.32, 27.72, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ropotamo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ropotamo.jpg"}'::text[], 1),
    (v_route, 'Ahtopol', 'Klidné rybářské městečko na jihu blízko turecké hranice s divokými plážemi. Konec cesty daleko od davů.', 42.1, 27.95, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ahtopol.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ahtopol.jpg"}'::text[], 2),
    (v_route, 'Pláž Djuni', 'Rozlehlá písečná pláž s dunami jižně od Sozopolu. Zastávka na koupání a klid.', 42.35, 27.68, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dyuni.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dyuni.jpg"}'::text[], 3),
    (v_route, 'Nesebar', 'Starobylé město na poloostrově s množstvím byzantských kostelů, UNESCO památka. Klenot severně od Burgasu.', 42.66, 27.73, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nessebar.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nessebar.jpg"}'::text[], 4);

  -- Sofie a hora Vitoša
  delete from public.routes where name = 'Sofie a hora Vitoša' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sofie a hora Vitoša', 'Okruh od bulharské metropole na horu Vitoša, jež se tyčí přímo nad městem. Katedrála Alexandra Něvského, horské silnice a kamenná moře nabízí kulturu i rychlý únik do přírody. Nejlepší od jara do podzimu; pozor na provoz v Sofii.', 'loop', 120, 165, 'easy',
     '[{"lat": 42.6977, "lng": 23.3219, "label": "Start: Sofie"}, {"lat": 42.635, "lng": 23.28, "label": "Vitoša – Zlaté mosty"}, {"lat": 42.64, "lng": 23.27, "label": "Boyana"}, {"lat": 42.6977, "lng": 23.3219, "label": "Cíl: Sofie"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=42.6977,23.3219&destination=42.6977,23.3219&travelmode=driving&waypoints=42.635,23.28%7C42.64,23.27', 'https://commons.wikimedia.org/wiki/Special:FilePath/Alexander_Nevsky_Cathedral_Sofia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Alexander_Nevsky_Cathedral_Sofia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vitosha.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Boyana_Church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sofia_Church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cherni_Vrah.jpg"}'::text[], '{"Katedrála Alexandra Něvského","Vitoša – Zlaté mosty","Boyanský kostel","Chrám svaté Sofie","Cherni Vrah"}'::text[], '{"BG"}'::text[], false, 3300, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Katedrála Alexandra Něvského', 'Monumentální pravoslavná katedrála se zlatými kupolemi, symbol Sofie. Srdce bulharské metropole.', 42.6957, 23.3327, 'https://commons.wikimedia.org/wiki/Special:FilePath/Alexander_Nevsky_Cathedral_Sofia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Alexander_Nevsky_Cathedral_Sofia.jpg"}'::text[], 0),
    (v_route, 'Vitoša – Zlaté mosty', 'Kamenné moře balvanů táhnoucí se svahem hory nad Sofií, oblíbený cíl výletů. Rychlý únik z města do přírody.', 42.635, 23.28, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vitosha.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vitosha.jpg"}'::text[], 1),
    (v_route, 'Boyanský kostel', 'Malý středověký kostel s vynikajícími freskami, UNESCO památka na úpatí Vitoše. Klenot bulharského malířství.', 42.6444, 23.265, 'https://commons.wikimedia.org/wiki/Special:FilePath/Boyana_Church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Boyana_Church.jpg"}'::text[], 2),
    (v_route, 'Chrám svaté Sofie', 'Starobylý cihlový kostel, podle nějž dostalo město jméno. Klidná zastávka v centru.', 42.6958, 23.3222, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sofia_Church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sofia_Church.jpg"}'::text[], 3),
    (v_route, 'Cherni Vrah', 'Nejvyšší vrchol Vitoše (2290 m) s výhledem na Sofii a okolní pohoří. Cíl horského výjezdu nad metropolí.', 42.5636, 23.2789, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cherni_Vrah.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cherni_Vrah.jpg"}'::text[], 4);

end $$;
