-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — PORTUGALSKO (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Údolí Doura po silnici N222
  delete from public.routes where name = 'Údolí Doura po silnici N222' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Údolí Doura po silnici N222', 'Legendární silnice N222 podél řeky Douro, opakovaně volená nejkrásnější silnicí světa. Terasovité vinice portského vína, klikaté zatáčky nad řekou a půvabná města lákají k pomalé, zážitkové jízdě. Nejlepší od jara do podzimu; pozor na úzké úseky a turisty ve vinařských městečkách.', 'poi', 140, 210, 'medium',
     '[{"lat": 41.1614, "lng": -7.7897, "label": "Start: Peso da Régua"}, {"lat": 41.1861, "lng": -7.5342, "label": "Pinhão"}, {"lat": 41.2631, "lng": -7.5772, "label": "Sabrosa"}, {"lat": 41.1861, "lng": -7.5342, "label": "Cíl: Pinhão"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=41.1614,-7.7897&destination=41.1861,-7.5342&travelmode=driving&waypoints=41.1861,-7.5342%7C41.2631,-7.5772', 'https://commons.wikimedia.org/wiki/Special:FilePath/Peso_da_R%C3%A9gua.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Peso_da_R%C3%A9gua.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pinh%C3%A3o.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Miradouro_de_S%C3%A3o_Leonardo_de_Galafura.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sabrosa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Douro_Valley.jpg"}'::text[], '{"Peso da Régua","Pinhão","Vyhlídka São Leonardo de Galafura","Sabrosa","Vinice Doura"}'::text[], '{"PT"}'::text[], false, 4810, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Peso da Régua', 'Hlavní město portského vína na břehu Doura s muzeem vína a přístavištěm rabelos. Brána do vinařského údolí.', 41.1614, -7.7897, 'https://commons.wikimedia.org/wiki/Special:FilePath/Peso_da_R%C3%A9gua.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Peso_da_R%C3%A9gua.jpg"}'::text[], 0),
    (v_route, 'Pinhão', 'Srdce portské oblasti s nádražím zdobeným azulejos a vinicemi na strmých svazích. Nejfotogeničtější zastávka na Douru.', 41.1861, -7.5342, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pinh%C3%A3o.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pinh%C3%A3o.jpg"}'::text[], 1),
    (v_route, 'Vyhlídka São Leonardo de Galafura', 'Slavná vyhlídka vysoko nad zákrutem Doura s panoramatem teras a řeky. Nezapomenutelný rozhled nad údolím.', 41.1817, -7.6236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Miradouro_de_S%C3%A3o_Leonardo_de_Galafura.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Miradouro_de_S%C3%A3o_Leonardo_de_Galafura.jpg"}'::text[], 2),
    (v_route, 'Sabrosa', 'Rodiště mořeplavce Fernão de Magalhães uprostřed vinic. Klidné městečko s výhledy do kraje.', 41.2631, -7.5772, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sabrosa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sabrosa.jpg"}'::text[], 3),
    (v_route, 'Vinice Doura', 'Terasovité vinice na strmých svazích nad řekou, zapsané na seznam UNESCO. Ukázka portského terroir.', 41.1789, -7.55, 'https://commons.wikimedia.org/wiki/Special:FilePath/Douro_Valley.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Douro_Valley.jpg"}'::text[], 4);

  -- Serra da Estrela – střecha Portugalska
  delete from public.routes where name = 'Serra da Estrela – střecha Portugalska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Serra da Estrela – střecha Portugalska', 'Okruh nejvyšším pohořím pevninského Portugalska. Serpentiny k vrcholu Torre, ledovcová údolí a horské vesnice nabízí svěží vzduch a nekonečné výhledy. Nejlepší od května do října; pozor na mlhy, dobytek a v zimě sníh na hřebeni.', 'loop', 180, 255, 'medium',
     '[{"lat": 40.4008, "lng": -7.5344, "label": "Start: Manteigas"}, {"lat": 40.3225, "lng": -7.6153, "label": "Torre"}, {"lat": 40.4158, "lng": -7.7086, "label": "Seia"}, {"lat": 40.4008, "lng": -7.5344, "label": "Cíl: Manteigas"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=40.4008,-7.5344&destination=40.4008,-7.5344&travelmode=driving&waypoints=40.3225,-7.6153%7C40.4158,-7.7086', 'https://commons.wikimedia.org/wiki/Special:FilePath/Torre_Serra_da_Estrela.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Torre_Serra_da_Estrela.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Manteigas.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vale_do_Z%C3%AAzere.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Po%C3%A7o_do_Inferno.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Linhares_da_Beira.jpg"}'::text[], '{"Torre – vrchol","Manteigas","Ledovcové údolí Zêzere","Poço do Inferno","Linhares da Beira"}'::text[], '{"PT"}'::text[], false, 4820, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Torre – vrchol', 'Nejvyšší bod pevninského Portugalska (1993 m) s kamennou věží a výhledy do všech stran. Cíl slavného horského výjezdu.', 40.3225, -7.6153, 'https://commons.wikimedia.org/wiki/Special:FilePath/Torre_Serra_da_Estrela.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Torre_Serra_da_Estrela.jpg"}'::text[], 0),
    (v_route, 'Manteigas', 'Půvabné horské městečko v ledovcovém údolí Zêzere, výchozí bod do hor. Klidná zastávka mezi štíty.', 40.4008, -7.5344, 'https://commons.wikimedia.org/wiki/Special:FilePath/Manteigas.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Manteigas.jpg"}'::text[], 1),
    (v_route, 'Ledovcové údolí Zêzere', 'Impozantní údolí ve tvaru U vyhloubené ledovcem, jedno z nejkrásnějších v Iberii. Dechberoucí scenérie za každého počasí.', 40.36, -7.56, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vale_do_Z%C3%AAzere.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vale_do_Z%C3%AAzere.jpg"}'::text[], 2),
    (v_route, 'Poço do Inferno', 'Malebný vodopád v lesích Serry da Estrela ukrytý v soutěsce. Osvěžující zastávka v přírodě.', 40.365, -7.51, 'https://commons.wikimedia.org/wiki/Special:FilePath/Po%C3%A7o_do_Inferno.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Po%C3%A7o_do_Inferno.jpg"}'::text[], 3),
    (v_route, 'Linhares da Beira', 'Historická vesnice s hradem na okraji pohoří, jedna z nejkrásnějších v zemi. Kamenné uličky a výhledy.', 40.5253, -7.4589, 'https://commons.wikimedia.org/wiki/Special:FilePath/Linhares_da_Beira.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Linhares_da_Beira.jpg"}'::text[], 4);

  -- Národní park Peneda-Gerês
  delete from public.routes where name = 'Národní park Peneda-Gerês' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Národní park Peneda-Gerês', 'Okruh jediným národním parkem Portugalska na severu u španělské hranice. Horské silnice mezi žulovými štíty, přehrady, vodopády a divocí koně provázejí zážitkovou jízdu. Nejlepší od jara do podzimu; pozor na úzké silnice, dobytek a mlhy.', 'loop', 170, 240, 'medium',
     '[{"lat": 41.7333, "lng": -8.1614, "label": "Start: Terras de Bouro"}, {"lat": 41.7256, "lng": -8.1594, "label": "Gerês"}, {"lat": 41.8106, "lng": -8.12, "label": "Portela do Homem"}, {"lat": 41.7333, "lng": -8.1614, "label": "Cíl: Terras de Bouro"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=41.7333,-8.1614&destination=41.7333,-8.1614&travelmode=driving&waypoints=41.7256,-8.1594%7C41.8106,-8.12', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ger%C3%AAs.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ger%C3%AAs.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Portela_do_Homem.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vilarinho_das_Furnas.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Soajo_espigueiros.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Miradouro_Pedra_Bela.jpg"}'::text[], '{"Lázně Gerês","Portela do Homem","Přehrada Vilarinho das Furnas","Soajo – sýpky","Pedra Bela – vyhlídka"}'::text[], '{"PT"}'::text[], false, 4830, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lázně Gerês', 'Termální lázeňské městečko v srdci národního parku, obklopené horami a lesy. Výchozí bod k vodopádům a přehradám.', 41.7256, -8.1594, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ger%C3%AAs.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ger%C3%AAs.jpg"}'::text[], 0),
    (v_route, 'Portela do Homem', 'Horský průsmyk na hranici se Španělskem s vodopády a starou římskou cestou. Nejvyšší bod okruhu s výhledy.', 41.8106, -8.12, 'https://commons.wikimedia.org/wiki/Special:FilePath/Portela_do_Homem.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Portela_do_Homem.jpg"}'::text[], 1),
    (v_route, 'Přehrada Vilarinho das Furnas', 'Nádrž ukrývající zatopenou vesnici, jejíž ruiny se za sucha vynoří. Působivé místo obklopené horami.', 41.7794, -8.2011, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vilarinho_das_Furnas.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vilarinho_das_Furnas.jpg"}'::text[], 2),
    (v_route, 'Soajo – sýpky', 'Vesnice proslulá skupinou kamenných obilných sýpek espigueiros na skále. Ojedinělá lidová památka severu.', 41.813, -8.2667, 'https://commons.wikimedia.org/wiki/Special:FilePath/Soajo_espigueiros.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Soajo_espigueiros.jpg"}'::text[], 3),
    (v_route, 'Pedra Bela – vyhlídka', 'Vyhlídka nad údolím s panoramatem hor a přehrady Caniçada. Odměna za výjezd horskou silnicí.', 41.7658, -8.175, 'https://commons.wikimedia.org/wiki/Special:FilePath/Miradouro_Pedra_Bela.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Miradouro_Pedra_Bela.jpg"}'::text[], 4);

  -- Sintra a mys Cabo da Roca
  delete from public.routes where name = 'Sintra a mys Cabo da Roca' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sintra a mys Cabo da Roca', 'Krátká, ale nabitá trasa pohořím Sintra k nejzápadnějšímu bodu kontinentální Evropy. Pohádkové paláce v mlžných lesích, klikaté silnice a útesy nad Atlantikem tvoří nezapomenutelný zážitek. Nejlepší od jara do podzimu; pozor na hustý provoz a mlhu v kopcích.', 'poi', 90, 165, 'easy',
     '[{"lat": 38.7975, "lng": -9.3903, "label": "Start: Sintra"}, {"lat": 38.7872, "lng": -9.3908, "label": "Palác Pena"}, {"lat": 38.7803, "lng": -9.4989, "label": "Cabo da Roca"}, {"lat": 38.6975, "lng": -9.4211, "label": "Cascais"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=38.7975,-9.3903&destination=38.6975,-9.4211&travelmode=driving&waypoints=38.7872,-9.3908%7C38.7803,-9.4989', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pal%C3%A1cio_da_Pena.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pal%C3%A1cio_da_Pena.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sintra.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_da_Roca.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Quinta_da_Regaleira.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cascais.jpg"}'::text[], '{"Palác Pena","Historické centrum Sintry","Cabo da Roca","Quinta da Regaleira","Cascais"}'::text[], '{"PT"}'::text[], false, 4840, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Palác Pena', 'Barevný romantický palác na vrcholu Sintry, jeden z divů Portugalska. Kýčovitě krásná stavba nad mlžnými lesy.', 38.7872, -9.3908, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pal%C3%A1cio_da_Pena.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pal%C3%A1cio_da_Pena.jpg"}'::text[], 0),
    (v_route, 'Historické centrum Sintry', 'Pohádkové městečko s národním palácem a kavárnami pod zalesněnými kopci. UNESCO klenot plný atmosféry.', 38.7975, -9.3903, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sintra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sintra.jpg"}'::text[], 1),
    (v_route, 'Cabo da Roca', 'Nejzápadnější bod kontinentální Evropy s majákem na útesech nad Atlantikem. Symbolický konec pevniny.', 38.7803, -9.4989, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_da_Roca.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_da_Roca.jpg"}'::text[], 2),
    (v_route, 'Quinta da Regaleira', 'Tajemná usedlost se zahradami, věžemi a hlubokou zasvěcovací studnou. Magické místo plné symboliky.', 38.7964, -9.3964, 'https://commons.wikimedia.org/wiki/Special:FilePath/Quinta_da_Regaleira.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Quinta_da_Regaleira.jpg"}'::text[], 3),
    (v_route, 'Cascais', 'Elegantní přímořské letovisko s přístavem, plážemi a útesem Boca do Inferno. Příjemný cíl u moře.', 38.6975, -9.4211, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cascais.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cascais.jpg"}'::text[], 4);

  -- Alentejem přes Évoru a Monsaraz
  delete from public.routes where name = 'Alentejem přes Évoru a Monsaraz' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Alentejem přes Évoru a Monsaraz', 'Klidná trasa zvlněnými pláněmi Alenteja plnými korkových dubů a olivovníků. Římská Évora, opevněné Monsaraz nad přehradou a bílá městečka nabízí historii i prázdné silnice. Nejlepší na jaře a na podzim; pozor na letní vedra a řidší zázemí.', 'poi', 160, 210, 'easy',
     '[{"lat": 38.5714, "lng": -7.9135, "label": "Start: Évora"}, {"lat": 38.4436, "lng": -7.3811, "label": "Monsaraz"}, {"lat": 38.8442, "lng": -7.5864, "label": "Estremoz"}, {"lat": 38.5714, "lng": -7.9135, "label": "Cíl: Évora"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=38.5714,-7.9135&destination=38.5714,-7.9135&travelmode=driving&waypoints=38.4436,-7.3811%7C38.8442,-7.5864', 'https://commons.wikimedia.org/wiki/Special:FilePath/Templo_romano_de_%C3%89vora.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Templo_romano_de_%C3%89vora.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monsaraz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Estremoz.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Barragem_do_Alqueva.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Arraiolos.jpg"}'::text[], '{"Évora – Dianin chrám","Monsaraz","Estremoz","Přehrada Alqueva","Arraiolos"}'::text[], '{"PT"}'::text[], false, 4850, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Évora – Dianin chrám', 'Historické město UNESCO s dochovaným římským chrámem, katedrálou a kaplí kostí. Srdce Alenteja plné památek.', 38.5714, -7.908, 'https://commons.wikimedia.org/wiki/Special:FilePath/Templo_romano_de_%C3%89vora.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Templo_romano_de_%C3%89vora.jpg"}'::text[], 0),
    (v_route, 'Monsaraz', 'Opevněné středověké městečko na kopci nad přehradou Alqueva s dechberoucím výhledem. Bílé uličky a hradby.', 38.4436, -7.3811, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monsaraz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monsaraz.jpg"}'::text[], 1),
    (v_route, 'Estremoz', 'Mramorové město s hradem, mramorovým náměstím a slavným keramickým trhem. Elegantní zastávka Alenteja.', 38.8442, -7.5864, 'https://commons.wikimedia.org/wiki/Special:FilePath/Estremoz.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Estremoz.jpg"}'::text[], 2),
    (v_route, 'Přehrada Alqueva', 'Největší umělé jezero v západní Evropě, ráj temné oblohy a hvězd. Klidná vodní plocha uprostřed plání.', 38.3961, -7.4544, 'https://commons.wikimedia.org/wiki/Special:FilePath/Barragem_do_Alqueva.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Barragem_do_Alqueva.jpg"}'::text[], 3),
    (v_route, 'Arraiolos', 'Kruhové městečko proslulé ručně vyšívanými koberci a hradem na kopci. Klidná zastávka mezi olivami.', 38.7239, -7.9836, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arraiolos.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arraiolos.jpg"}'::text[], 4);

  -- Algarve – hory Monchique a Silves
  delete from public.routes where name = 'Algarve – hory Monchique a Silves' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Algarve – hory Monchique a Silves', 'Okruh vnitrozemím Algarve mimo přeplněné pláže. Klikaté silnice k nejvyššímu vrcholu Foia, maurský hrad v Silves a lázeňské Caldas de Monchique nabízí zeleň, vůni eukalyptů a výhledy až k moři. Nejlepší od jara do podzimu; pozor na úzké horské silnice.', 'loop', 150, 210, 'medium',
     '[{"lat": 37.3186, "lng": -8.5556, "label": "Start: Monchique"}, {"lat": 37.3147, "lng": -8.5992, "label": "Fóia"}, {"lat": 37.1897, "lng": -8.4389, "label": "Silves"}, {"lat": 37.3186, "lng": -8.5556, "label": "Cíl: Monchique"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.3186,-8.5556&destination=37.3186,-8.5556&travelmode=driving&waypoints=37.3147,-8.5992%7C37.1897,-8.4389', 'https://commons.wikimedia.org/wiki/Special:FilePath/F%C3%B3ia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/F%C3%B3ia.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monchique.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Silves.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Caldas_de_Monchique.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Barragem_da_Bravura.jpg"}'::text[], '{"Fóia – nejvyšší vrchol Algarve","Monchique","Hrad Silves","Caldas de Monchique","Barragem da Bravura"}'::text[], '{"PT"}'::text[], false, 4860, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Fóia – nejvyšší vrchol Algarve', 'Nejvyšší bod Algarve (902 m) s výhledem přes hory až k Atlantiku. Cíl oblíbeného horského výjezdu.', 37.3147, -8.5992, 'https://commons.wikimedia.org/wiki/Special:FilePath/F%C3%B3ia.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/F%C3%B3ia.jpg"}'::text[], 0),
    (v_route, 'Monchique', 'Horské městečko proslulé lázněmi, medovinou a řemesly, obklopené zelenými kopci. Svěží protipól pobřeží.', 37.3186, -8.5556, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monchique.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monchique.jpg"}'::text[], 1),
    (v_route, 'Hrad Silves', 'Mohutný červený maurský hrad nad bývalým hlavním městem Algarve. Nejlépe zachovaná maurská pevnost v regionu.', 37.1897, -8.4389, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Silves.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Silves.jpg"}'::text[], 2),
    (v_route, 'Caldas de Monchique', 'Půvabná lázeňská osada ukrytá v eukalyptovém údolí s termálními prameny. Klidná zastávka mezi stromy.', 37.2894, -8.5581, 'https://commons.wikimedia.org/wiki/Special:FilePath/Caldas_de_Monchique.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Caldas_de_Monchique.jpg"}'::text[], 3),
    (v_route, 'Barragem da Bravura', 'Klidná přehrada v kopcích nad Lagosem obklopená borovicemi. Osvěžující zastávka daleko od davů.', 37.2158, -8.682, 'https://commons.wikimedia.org/wiki/Special:FilePath/Barragem_da_Bravura.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Barragem_da_Bravura.jpg"}'::text[], 4);

  -- Divoké pobřeží Costa Vicentina
  delete from public.routes where name = 'Divoké pobřeží Costa Vicentina' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Divoké pobřeží Costa Vicentina', 'Trasa podél nejdivočejšího atlantického pobřeží Portugalska v přírodním parku Costa Vicentina. Útesy, opuštěné pláže, konec světa u Sagresu a bílá městečka nabízí syrovou krásu oceánu. Nejlepší od jara do podzimu; pozor na vítr a mlhu na útesech.', 'poi', 130, 195, 'easy',
     '[{"lat": 37.0119, "lng": -8.9411, "label": "Start: Sagres"}, {"lat": 37.0209, "lng": -8.9964, "label": "Cabo de São Vicente"}, {"lat": 37.3152, "lng": -8.7929, "label": "Aljezur"}, {"lat": 37.4335, "lng": -8.7645, "label": "Odeceixe"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.0119,-8.9411&destination=37.4335,-8.7645&travelmode=driving&waypoints=37.0209,-8.9964%7C37.3152,-8.7929', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_de_S%C3%A3o_Vicente.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_de_S%C3%A3o_Vicente.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sagres.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Praia_da_Amoreira.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Aljezur.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Odeceixe.jpg"}'::text[], '{"Cabo de São Vicente","Sagres","Praia da Amoreira","Aljezur","Odeceixe"}'::text[], '{"PT"}'::text[], false, 4870, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Cabo de São Vicente', 'Dramatický mys na jihozápadním konci Evropy s majákem na útesech nad Atlantikem. Kdysi považován za konec světa.', 37.0209, -8.9964, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_de_S%C3%A3o_Vicente.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cabo_de_S%C3%A3o_Vicente.jpg"}'::text[], 0),
    (v_route, 'Sagres', 'Větrné městečko s pevností na útesu, kolébka portugalských objevných plaveb. Surfařská a rybářská atmosféra.', 37.0119, -8.9411, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sagres.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sagres.jpg"}'::text[], 1),
    (v_route, 'Praia da Amoreira', 'Nádherná divoká pláž u ústí řeky s útesy a dunami. Ukázka syrové krásy Costa Vicentina.', 37.3242, -8.8811, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praia_da_Amoreira.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Praia_da_Amoreira.jpg"}'::text[], 2),
    (v_route, 'Aljezur', 'Bílé městečko s maurským hradem na kopci nedaleko divokých pláží. Klidná zastávka na severu pobřeží.', 37.3152, -8.7929, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aljezur.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aljezur.jpg"}'::text[], 3),
    (v_route, 'Odeceixe', 'Malebná vesnice nad meandrem řeky s plážou na hranici Alenteja a Algarve. Oblíbené místo surfařů.', 37.4335, -8.7645, 'https://commons.wikimedia.org/wiki/Special:FilePath/Odeceixe.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Odeceixe.jpg"}'::text[], 4);

  -- Trás-os-Montes a Miranda do Douro
  delete from public.routes where name = 'Trás-os-Montes a Miranda do Douro' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Trás-os-Montes a Miranda do Douro', 'Trasa nejodlehlejším a nejautentičtějším koutem Portugalska na severovýchodě u španělské hranice. Hrad v Bragançe, kaňon Doura a starobylá Miranda se svým vlastním jazykem nabízí divokou přírodu a dávné tradice. Nejlepší od jara do podzimu; pozor na řidší zázemí a horko.', 'poi', 180, 240, 'medium',
     '[{"lat": 41.8072, "lng": -6.7592, "label": "Start: Bragança"}, {"lat": 41.4956, "lng": -6.2723, "label": "Miranda do Douro"}, {"lat": 41.308, "lng": -7.7378, "label": "Vila Real"}, {"lat": 41.8072, "lng": -6.7592, "label": "Cíl: Bragança"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=41.8072,-6.7592&destination=41.8072,-6.7592&travelmode=driving&waypoints=41.4956,-6.2723%7C41.308,-7.7378', 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Bragan%C3%A7a.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Bragan%C3%A7a.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Miranda_do_Douro.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Parque_Natural_de_Montesinho.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Douro_Internacional.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Casa_de_Mateus.jpg"}'::text[], '{"Hrad Bragança","Miranda do Douro","Přírodní park Montesinho","Kaňon Doura – Douro Internacional","Vila Real – Mateus"}'::text[], '{"PT"}'::text[], false, 4880, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Bragança', 'Výborně zachovaný středověký hrad s citadelou a domky uvnitř hradeb. Symbol nejsevernějšího portugalského kraje.', 41.8072, -6.7592, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Bragan%C3%A7a.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Bragan%C3%A7a.jpg"}'::text[], 0),
    (v_route, 'Miranda do Douro', 'Starobylé hraniční město nad kaňonem Doura, kde se dodnes mluví vlastním jazykem mirandštinou. Katedrála a dramatické útesy.', 41.4956, -6.2723, 'https://commons.wikimedia.org/wiki/Special:FilePath/Miranda_do_Douro.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Miranda_do_Douro.jpg"}'::text[], 1),
    (v_route, 'Přírodní park Montesinho', 'Divoká horská krajina s vesnicemi, kde přežívají dávné tradice a vlci. Ryzí příroda severovýchodu.', 41.9302, -6.7965, 'https://commons.wikimedia.org/wiki/Special:FilePath/Parque_Natural_de_Montesinho.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Parque_Natural_de_Montesinho.jpg"}'::text[], 2),
    (v_route, 'Kaňon Doura – Douro Internacional', 'Hluboký kaňon, kterým řeka tvoří hranici se Španělskem, ráj dravců a divokých scenérií. Vyhlídky nad soutěskou.', 41.3675, -6.4258, 'https://commons.wikimedia.org/wiki/Special:FilePath/Douro_Internacional.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Douro_Internacional.jpg"}'::text[], 3),
    (v_route, 'Vila Real – Mateus', 'Město na úpatí hor s proslulým barokním palácem Mateus obklopeným zahradami. Elegantní zastávka na západě.', 41.308, -7.7378, 'https://commons.wikimedia.org/wiki/Special:FilePath/Casa_de_Mateus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Casa_de_Mateus.jpg"}'::text[], 4);

  -- Historické vesnice středního Portugalska
  delete from public.routes where name = 'Historické vesnice středního Portugalska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Historické vesnice středního Portugalska', 'Trasa vnitrozemím středního Portugalska přes opevněné vesnice a templářské památky. Óbidos v hradbách, klášter v Tomaru a horská Marvão nad pláněmi nabízí kamennou historii a klidné silnice. Nejlepší od jara do podzimu; pozor na úzké dlážděné uličky.', 'poi', 160, 225, 'medium',
     '[{"lat": 39.3606, "lng": -9.1572, "label": "Start: Óbidos"}, {"lat": 39.6039, "lng": -8.4189, "label": "Tomar"}, {"lat": 39.3936, "lng": -7.3778, "label": "Marvão"}, {"lat": 39.3606, "lng": -9.1572, "label": "Cíl: Óbidos"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=39.3606,-9.1572&destination=39.3606,-9.1572&travelmode=driving&waypoints=39.6039,-8.4189%7C39.3936,-7.3778', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%93bidos.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%93bidos.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Convento_de_Cristo_Tomar.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Marv%C3%A3o.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Vide.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Almourol.jpg"}'::text[], '{"Óbidos","Templářský klášter v Tomaru","Marvão","Castelo de Vide","Almourol"}'::text[], '{"PT"}'::text[], false, 4890, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Óbidos', 'Kouzelné městečko obepnuté středověkými hradbami s bílými domky a květinami. Jedna z nejhezčích vesnic Portugalska.', 39.3606, -9.1572, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%93bidos.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%93bidos.jpg"}'::text[], 0),
    (v_route, 'Templářský klášter v Tomaru', 'Convento de Cristo, sídlo templářů a UNESCO památka s proslulým oknem Manuelino. Klenot portugalské historie.', 39.6039, -8.4189, 'https://commons.wikimedia.org/wiki/Special:FilePath/Convento_de_Cristo_Tomar.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Convento_de_Cristo_Tomar.jpg"}'::text[], 1),
    (v_route, 'Marvão', 'Orlí hnízdo na skalním vrcholu u španělské hranice s hradbami a nekonečnými výhledy do plání. Nezapomenutelná scenérie.', 39.3936, -7.3778, 'https://commons.wikimedia.org/wiki/Special:FilePath/Marv%C3%A3o.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Marv%C3%A3o.jpg"}'::text[], 2),
    (v_route, 'Castelo de Vide', 'Půvabné městečko s hradem a starou židovskou čtvrtí na svahu pod Marvãem. Kamenné uličky a prameny.', 39.4147, -7.4553, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Vide.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Vide.jpg"}'::text[], 3),
    (v_route, 'Almourol', 'Pohádkový templářský hrad na ostrůvku uprostřed řeky Tejo. Jeden z nejromantičtějších hradů Iberie.', 39.4614, -8.3814, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Almourol.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Almourol.jpg"}'::text[], 4);

  -- Coimbra a Serra da Lousã
  delete from public.routes where name = 'Coimbra a Serra da Lousã' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Coimbra a Serra da Lousã', 'Okruh od univerzitní Coimbry do břidlicových hor Serra da Lousã. Historické památky, klikaté lesní silnice a malebné břidlicové vesnice nabízí kulturu i pohodovou jízdu. Nejlepší od jara do podzimu; pozor na úzké horské silnice.', 'loop', 140, 210, 'medium',
     '[{"lat": 40.2056, "lng": -8.4194, "label": "Start: Coimbra"}, {"lat": 40.0958, "lng": -8.2242, "label": "Lousã"}, {"lat": 40.081, "lng": -8.238, "label": "Talasnal"}, {"lat": 40.2056, "lng": -8.4194, "label": "Cíl: Coimbra"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=40.2056,-8.4194&destination=40.2056,-8.4194&travelmode=driving&waypoints=40.0958,-8.2242%7C40.081,-8.238', 'https://commons.wikimedia.org/wiki/Special:FilePath/University_of_Coimbra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/University_of_Coimbra.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Lous%C3%A3.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Talasnal.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Penela.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Con%C3%ADmbriga.jpg"}'::text[], '{"Univerzita Coimbra","Hrad Lousã","Talasnal","Penela – hrad","Conímbriga"}'::text[], '{"PT"}'::text[], false, 4900, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Univerzita Coimbra', 'Nejstarší univerzita Portugalska s ohromující barokní knihovnou Joanina, památka UNESCO. Srdce historického města nad řekou Mondego.', 40.2076, -8.4256, 'https://commons.wikimedia.org/wiki/Special:FilePath/University_of_Coimbra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/University_of_Coimbra.jpg"}'::text[], 0),
    (v_route, 'Hrad Lousã', 'Malebný hrad ukrytý v břidlicové soutěsce u říčky s pláží. Výchozí bod do hor obklopený zelení.', 40.0958, -8.2242, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Lous%C3%A3.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Lous%C3%A3.jpg"}'::text[], 1),
    (v_route, 'Talasnal', 'Kouzelná břidlicová vesnice zavěšená na svahu Serry da Lousã, kdysi opuštěná a znovu oživlá. Kamenné domky mimo čas.', 40.081, -8.238, 'https://commons.wikimedia.org/wiki/Special:FilePath/Talasnal.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Talasnal.jpg"}'::text[], 2),
    (v_route, 'Penela – hrad', 'Dobře zachovalý hrad nad městečkem na okraji vápencových kopců. Rozhled do kraje a klidná zastávka.', 40.0322, -8.3903, 'https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Penela.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Castelo_de_Penela.jpg"}'::text[], 3),
    (v_route, 'Conímbriga', 'Nejlépe dochované římské ruiny v Portugalsku s mozaikami a lázněmi. Fascinující výlet do antiky.', 40.0994, -8.4919, 'https://commons.wikimedia.org/wiki/Special:FilePath/Con%C3%ADmbriga.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Con%C3%ADmbriga.jpg"}'::text[], 4);

end $$;
