-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — RUMUNSKO (10 tras, červenec 2026)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Maramureš – dřevěné kostely a Veselý hřbitov
  delete from public.routes where name = 'Maramureš – dřevěné kostely a Veselý hřbitov' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Maramureš – dřevěné kostely a Veselý hřbitov', 'Okruh nejseverovýchodnějším koutem Rumunska, kde se čas zastavil: dřevěné kostely UNESCO, vyřezávané brány a senoseče jako z 19. století. Z Baia Mare vystoupáte serpentinami přes průsmyk Gutâi pod skalní hřeben Creasta Cocoșului a sjedete do údolí Mary a Izy. Vrcholem je světově proslulý Veselý hřbitov v Săpânțě s malovanými náhrobky a štíhlá věž kláštera Bârsana. Silnice jsou vesměs v dobrém stavu, ale počítejte s koňskými povozy, drůbeží na vozovce a pomalejším tempem přes vesnice. Nejlépe od května do října; odpoledne bývají v horách bouřky.', 'loop', 200, 300, 'medium',
     '[{"lat": 47.6573, "lng": 23.5681, "label": "Start: Baia Mare"}, {"lat": 47.7092, "lng": 23.7803, "label": "Pasul Gutâi"}, {"lat": 47.9686, "lng": 23.6941, "label": "Săpânța"}, {"lat": 47.9284, "lng": 23.8871, "label": "Sighetu Marmației"}, {"lat": 47.7950, "lng": 24.0710, "label": "Bârsana"}, {"lat": 47.7286, "lng": 23.9522, "label": "Budești"}, {"lat": 47.6667, "lng": 23.8631, "label": "Cavnic"}, {"lat": 47.6573, "lng": 23.5681, "label": "Cíl: Baia Mare"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.6573,23.5681&destination=47.6573,23.5681&travelmode=driving&waypoints=47.7092,23.7803%7C47.9686,23.6941%7C47.9284,23.8871%7C47.7950,24.0710%7C47.7286,23.9522%7C47.6667,23.8631', 'https://commons.wikimedia.org/wiki/Special:FilePath/Merry%20Cemetery,%20Sapanta,%20Maramures,%20Romania.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Creasta%20Cocosului%202011.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Merry%20Cemetery,%20Sapanta,%20Maramures,%20Romania.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sighetu%20Marmatiei%20Centrul%20istoric%20(2).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Barsana%20-%20Maramures.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20de%20lemn%20din%20Budesti%20Josani.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Breb%20village%20in%20Maramure%C5%9F%20County,%20Romania.jpg"}'::text[], '{"Creasta Cocoșului (Pasul Gutâi)","Veselý hřbitov v Săpânțě","Restaurace: Casa Iurca de Călinești (Sighetu Marmației)","Klášter Bârsana","Dřevěný kostel Budești Josani","Vesnice Breb"}'::text[], '{"RO"}'::text[], false, 4910, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Creasta Cocoșului (Pasul Gutâi)', 'Zubatý sopečný hřeben Kohoutí hřebínek se tyčí přímo nad průsmykem Gutâi (987 m) na staré silnici DN18. Serpentiny s výhledy na obě strany jsou nejhezčím úsekem cesty mezi Baia Mare a Sighetem. U silnice stojí kultovní hospůdka Hanul lui Pintea spojená s legendárním zbojníkem Pintea Viteazul.', 47.7092, 23.7803, 'https://commons.wikimedia.org/wiki/Special:FilePath/Creasta%20Cocosului%202011.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Creasta%20Cocosului%202011.jpg"}'::text[], 0),
    (v_route, 'Veselý hřbitov v Săpânțě', 'Světový unikát: stovky modrých vyřezávaných křížů s naivními malbami a veršovanými, často velmi vtipnými epitafy o životě zesnulých. Dílo řezbáře Stana Ioana Pătrașe z 30. let dnes patří na seznam UNESCO. Přijeďte dopoledne, než dorazí autobusy; parkování pro motorky přímo u vstupu.', 47.9686, 23.6941, 'https://commons.wikimedia.org/wiki/Special:FilePath/Merry%20Cemetery,%20Sapanta,%20Maramures,%20Romania.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Merry%20Cemetery,%20Sapanta,%20Maramures,%20Romania.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Merry%20Cemetery%20-%20Sapanta%20-%20Romania%2002.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Casa Iurca de Călinești (Sighetu Marmației)', 'Vyhlášená rodinná restaurace v historickém šlechtickém domě v centru Sighetu. Poctivá maramurešská kuchyně — sarmale, mămăligă s brynzou a domácí horincă. Ideální zastávka na oběd v půlce okruhu, dvůr je klidný a bezpečný i pro plně naložené motorky.', 47.9284, 23.8871, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sighetu%20Marmatiei%20Centrul%20istoric%20(2).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sighetu%20Marmatiei%20Centrul%20istoric%20(2).JPG"}'::text[], 2),
    (v_route, 'Klášter Bârsana', 'Rozlehlý dřevěný klášterní areál v údolí Izy, jehož kostelní věž patří k nejvyšším dřevěným stavbám Evropy. Všechno je vyřezáváno ručně z dubu a šindele, zahrady jsou udržované jako klenotnice. Krásná ukázka živé maramurešské tesařské tradice, vstup volný.', 47.7950, 24.0710, 'https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Barsana%20-%20Maramures.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Barsana%20-%20Maramures.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Barsana%20Maramures%20-%20vedere%20de%20ansamblu.jpg"}'::text[], 3),
    (v_route, 'Dřevěný kostel Budești Josani', 'Kostel sv. Mikuláše z roku 1643 zapsaný na seznamu UNESCO, se čtyřmi vížkami a vzácnými interiérovými malbami. Uvnitř je uložena drátěná košile zbojníka Pintey. Klidná vesnice bez turistického ruchu — zastávka na pár minut ticha.', 47.7286, 23.9522, 'https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20de%20lemn%20din%20Budesti%20Josani.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20de%20lemn%20din%20Budesti%20Josani.JPG"}'::text[], 4),
    (v_route, 'Vesnice Breb', 'Nejfotogeničtější vesnice Maramureše: doškové stodoly, vyřezávané brány a výhled na Creasta Cocoșului. Vesnici si oblíbil i britský král Karel III., který tu koupil usedlost. Úzká asfaltka do vsi je místy hrbolatá — v klidu, stojí to za to.', 47.7461, 23.9089, 'https://commons.wikimedia.org/wiki/Special:FilePath/Breb%20village%20in%20Maramure%C5%9F%20County,%20Romania.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Breb%20village%20in%20Maramure%C5%9F%20County,%20Romania.jpg"}'::text[], 5);

  -- Bukovina – malované kláštery UNESCO
  delete from public.routes where name = 'Bukovina – malované kláštery UNESCO' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Bukovina – malované kláštery UNESCO', 'Pohodový okruh zvlněnou Bukovinou mezi pěti malovanými kláštery, jejichž vnější fresky z 16. století přežily půl tisíciletí dešťů a mrazů. Silnice DN17A přes průsmyk Ciumârna nabízí sled dokonale klopených zatáček lesem — motorkáři jí přezdívají bukovinská Transfăgărășan v kapesním vydání. Mezi klášery projíždíte vesnicemi s malovanými štíty a dílnami na černou keramiku v Marginee. Provoz je slabý, asfalt převážně výborný, převýšení mírné. Ideální jarní a podzimní trasa; fresky nejlépe vyniknou v ranním světle.', 'loop', 160, 240, 'easy',
     '[{"lat": 47.5539, "lng": 25.8896, "label": "Start: Gura Humorului"}, {"lat": 47.5172, "lng": 25.8636, "label": "Voroneț"}, {"lat": 47.6070, "lng": 25.8433, "label": "Mănăstirea Humorului"}, {"lat": 47.6850, "lng": 25.5709, "label": "Vatra Moldoviței"}, {"lat": 47.6544, "lng": 25.4750, "label": "Pasul Ciumârna (1100 m)"}, {"lat": 47.7781, "lng": 25.7099, "label": "Sucevița"}, {"lat": 47.8092, "lng": 25.8225, "label": "Marginea"}, {"lat": 47.5539, "lng": 25.8896, "label": "Cíl: Gura Humorului"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.5539,25.8896&destination=47.5539,25.8896&travelmode=driving&waypoints=47.5172,25.8636%7C47.6070,25.8433%7C47.6850,25.5709%7C47.6544,25.4750%7C47.7781,25.7099%7C47.8092,25.8225', 'https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Voronet.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Voronet.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/M%C4%83n%C4%83stirea%20Humor%20-%20vedere%20lateral%C4%83.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Moldovi%C8%9Ba%20Monastery%20(Romania).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sucevi%C8%9Ba%20Monastery,%20Romania.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ceramica%20Marginea.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Arbore.jpg"}'::text[], '{"Klášter Voroneț","Klášter Humor","Klášter Moldovița","Klášter Sucevița","Marginea – černá keramika","Kostel Arbore"}'::text[], '{"RO"}'::text[], false, 4920, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Klášter Voroneț', 'Sixtinská kaple Východu — vnější freska Posledního soudu na západní stěně září unikátní voronețskou modří, jejíž receptura se dodnes nepodařilo rozluštit. Klášter založil Štěpán Veliký roku 1488 za pouhé tři měsíce. Parkoviště 200 m od brány, vstup pár lei.', 47.5172, 25.8636, 'https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Voronet.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Voronet.JPG"}'::text[], 0),
    (v_route, 'Klášter Humor', 'Nejkomornější z malovaných klášterů, beze zdí a věží, zato s freskami v teplých červených tónech z roku 1535. Z dřevěné obranné věže za kostelem je pěkný výhled na celý areál. Bývá tu výrazně méně lidí než ve Voroneți.', 47.6070, 25.8433, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C4%83n%C4%83stirea%20Humor%20-%20vedere%20lateral%C4%83.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C4%83n%C4%83stirea%20Humor%20-%20vedere%20lateral%C4%83.JPG"}'::text[], 1),
    (v_route, 'Klášter Moldovița', 'Opevněný klášter z roku 1532 s proslulou freskou Obléhání Konstantinopole na jižní stěně. Areál obklopený hradbami působí jako malá pevnost uprostřed květinových zahrad. Odtud začíná nejlepší motorkářský úsek trasy — stoupání na Ciumârnu.', 47.6850, 25.5709, 'https://commons.wikimedia.org/wiki/Special:FilePath/Moldovi%C8%9Ba%20Monastery%20(Romania).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Moldovi%C8%9Ba%20Monastery%20(Romania).jpg"}'::text[], 2),
    (v_route, 'Klášter Sucevița', 'Největší a nejmohutněji opevněný malovaný klášter se slavnou freskou Žebřík ctností na severní stěně. Zelené tóny frescek a bílé hradby s věžemi v rohu údolí tvoří jeden z nejkrásnějších obrazů Bukoviny. Sjíždí se k němu přímo z průsmyku Ciumârna.', 47.7781, 25.7099, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sucevi%C8%9Ba%20Monastery,%20Romania.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sucevi%C8%9Ba%20Monastery,%20Romania.jpg"}'::text[], 3),
    (v_route, 'Marginea – černá keramika', 'Vesnice proslulá jedinečnou černou keramikou vypalovanou bez přístupu vzduchu — technika stará přes 500 let. V hrnčířské dílně u hlavní silnice můžete sledovat práci na kruhu a koupit si misku, která se vejde do kufru. Milá krátká zastávka mezi kláštery.', 47.8092, 25.8225, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ceramica%20Marginea.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ceramica%20Marginea.jpg"}'::text[], 4),
    (v_route, 'Kostel Arbore', 'Nejstarší z malovaných kostelů (1502) a jediný, který nebyl klášterem — postavil ho dvořan Luca Arbore jako rodovou nekropoli. Fresky v odstínech zelené jsou dílem mistra Dragoșe Comana. Leží kousek stranou hlavního okruhu na zpáteční cestě přes Solcu.', 47.7350, 25.9260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Arbore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Arbore.jpg"}'::text[], 5);

  -- Apuseni – Salina Turda, soutěsky a ledová jeskyně
  delete from public.routes where name = 'Apuseni – Salina Turda, soutěsky a ledová jeskyně' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Apuseni – Salina Turda, soutěsky a ledová jeskyně', 'Celodenní okruh Západními Rumunskými horami: podzemní katedrála solného dolu Turda, vápencové věže soutěsky Cheile Turzii a maďarská vesnice Rimetea pod monolitem Piatra Secuiului. Údolím řeky Arieș pak vystoupáte do srdce Apusenských hor k ledové jeskyni Scărișoara, kde i v létě drží tisíce let starý ledovec. Zpáteční cesta vede přes zlatokopecké městečko Roșia Montană s římskými štolami. Silnice v údolí Arieș je zábavná a zatáčkovitá, místy s horším povrchem — jeďte s rezervou. Nejlepší od června do září, v horách bývá chladno i v létě.', 'loop', 250, 390, 'medium',
     '[{"lat": 46.5733, "lng": 23.7855, "label": "Start: Turda"}, {"lat": 46.5628, "lng": 23.6810, "label": "Cheile Turzii"}, {"lat": 46.4550, "lng": 23.5680, "label": "Rimetea"}, {"lat": 46.3644, "lng": 23.0464, "label": "Câmpeni"}, {"lat": 46.4879, "lng": 22.8087, "label": "Ghețar (Scărișoara)"}, {"lat": 46.2733, "lng": 23.0622, "label": "Abrud"}, {"lat": 46.3061, "lng": 23.1319, "label": "Roșia Montană"}, {"lat": 46.5733, "lng": 23.7855, "label": "Cíl: Turda"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.5733,23.7855&destination=46.5733,23.7855&travelmode=driving&waypoints=46.5628,23.6810%7C46.4550,23.5680%7C46.3644,23.0464%7C46.4879,22.8087%7C46.2733,23.0622%7C46.3061,23.1319', 'https://commons.wikimedia.org/wiki/Special:FilePath/Salina%20Turda%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Salina%20Turda%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cheile%20Turzii%20(Turda%20Gorges).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rimetea.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Pestera%20Scarisoara%20-%20Sala%20Biserica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rosia%20Montana%20Roman%20Gold%20Mines%202011%20-%20Galleries.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Salina%20Turda%205.jpg"}'::text[], '{"Salina Turda","Soutěska Cheile Turzii","Rimetea a Piatra Secuiului","Ledová jeskyně Scărișoara","Roșia Montană – římské zlaté doly","Restaurace: Sarea''n Bucate (Turda)"}'::text[], '{"RO"}'::text[], false, 4930, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Salina Turda', 'Solný důl s historií od středověku, proměněný v surrealistický podzemní zábavní park: ruské kolo, jezírko s loďkami a amfiteátr 120 metrů pod zemí. Stálých 11 °C — vezměte si vrstvu navíc. Počítejte s hodinou a půl na prohlídku, motorku nechte na hlídaném parkovišti u vstupu Salina Durgău.', 46.5877, 23.7875, 'https://commons.wikimedia.org/wiki/Special:FilePath/Salina%20Turda%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Salina%20Turda%201.jpg"}'::text[], 0),
    (v_route, 'Soutěska Cheile Turzii', 'Skoro tři sta metrů vysoké vápencové stěny nad potokem Hășdate, ráj horolezců a jedna z přírodních ikon Transylvánie. Od parkoviště vede kaňonem pohodová stezka — na protažení nohou stačí půlhodina k prvním mostkům. Výhled na soutěsku je krásný už z příjezdové silnice od Petreștii de Jos.', 46.5628, 23.6810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cheile%20Turzii%20(Turda%20Gorges).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cheile%20Turzii%20(Turda%20Gorges).jpg"}'::text[], 1),
    (v_route, 'Rimetea a Piatra Secuiului', 'Bělostná vesnice s maďarskou historií, kde nad náměstím s kostelem trůní vápencový monolit Piatra Secuiului (Székelykő, 1129 m). Díky orientaci údolí tu slunce vychází dvakrát — schová se za skálu a znovu se vyhoupne. Jedno z nejmalebnějších míst v celém Sedmihradsku, ideální na kávu na návsi.', 46.4550, 23.5680, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rimetea.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rimetea.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Piatra%20Secuiului%20seen%20from%20west.JPG"}'::text[], 2),
    (v_route, 'Ledová jeskyně Scărișoara', 'Podzemní ledovec o objemu přes 75 000 kubíků, starý zhruba 10 500 let — jeden z největších jeskynních ledovců Evropy. Sestup po schodech do 50 m hluboké vstupní šachty vyžaduje pevné boty a teplou vrstvu, uvnitř je kolem nuly. Od parkoviště v osadě Ghețar je to pěšky asi 10 minut.', 46.4879, 22.8087, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pestera%20Scarisoara%20-%20Sala%20Biserica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pestera%20Scarisoara%20-%20Sala%20Biserica.jpg"}'::text[], 3),
    (v_route, 'Roșia Montană – římské zlaté doly', 'Nejstarší doložené hornické město Rumunska (Alburnus Maior, r. 131) a od roku 2021 památka UNESCO. V podzemí se dochovaly kilometry ručně tesaných římských štol, nahoře historické náměstí těžařských domů. Prohlídka štol s průvodcem trvá asi hodinu.', 46.3061, 23.1319, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rosia%20Montana%20Roman%20Gold%20Mines%202011%20-%20Galleries.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rosia%20Montana%20Roman%20Gold%20Mines%202011%20-%20Galleries.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Sarea''n Bucate (Turda)', 'Výborně hodnocená restaurace přímo u areálu solného dolu, jejíž název je slovní hříčkou se solí. Moderní rumunská kuchyně z lokálních surovin, poctivé polévky a domácí limonády — ideální tečka za okruhem. V sezóně je lepší rezervace.', 46.5867, 23.7838, 'https://commons.wikimedia.org/wiki/Special:FilePath/Salina%20Turda%205.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Salina%20Turda%205.jpg"}'::text[], 5);

  -- Banát – vodopád Bigăr a soutěska Nery
  delete from public.routes where name = 'Banát – vodopád Bigăr a soutěska Nery' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Banát – vodopád Bigăr a soutěska Nery', 'Divoký jihozápad Rumunska, kraj českých krajanských vesnic a nejzelenějších hor Banátu. Z Reșițy vystoupáte k přehradám nad Văliugem, kolem semenických lesů sjedete do hornické Aniny a dál po DN57B k pohádkovému vodopádu Bigăr, kde voda stéká přes mechový převis. Národním parkem Cheile Nerei pokračujete k tyrkysovému jezírku Ochiul Beiului a do Oravițy s nejstarším divadlem v zemi. Silnice jsou úzké, zatáčkovité a místy záplatované — typický banátský mix, který si žádá pozornost, ale odmění samotou a přírodou. Nejlépe květen až říjen.', 'loop', 220, 330, 'medium',
     '[{"lat": 45.3009, "lng": 21.8892, "label": "Start: Reșița"}, {"lat": 45.2422, "lng": 22.0155, "label": "Văliug"}, {"lat": 45.0794, "lng": 21.8570, "label": "Anina"}, {"lat": 44.9247, "lng": 21.9536, "label": "Vodopád Bigăr"}, {"lat": 44.8850, "lng": 21.7083, "label": "Sasca Montană"}, {"lat": 45.0339, "lng": 21.6903, "label": "Oravița"}, {"lat": 45.3009, "lng": 21.8892, "label": "Cíl: Reșița"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.3009,21.8892&destination=45.3009,21.8892&travelmode=driving&waypoints=45.2422,22.0155%7C45.0794,21.8570%7C44.9247,21.9536%7C44.8850,21.7083%7C45.0339,21.6903', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cascada%20Big%C4%83r.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/RO%20CS%20Lacul%20de%20acumulare%20Valiug%20(3).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Cascada%20Big%C4%83r.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Cascadele%20Beu%C8%99ni%C8%9Bei.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Lacul%20Ochiul%20Beiului.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Teatrul%201.JPG"}'::text[], '{"Přehrada Văliug","Vodopád Bigăr","Vodopády Beușnița (Cheile Nerei)","Jezírko Ochiul Beiului","Divadlo Mihai Eminescu (Oravița)"}'::text[], '{"RO"}'::text[], false, 4940, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Přehrada Văliug', 'Horská nádrž na řece Bârzavě obklopená semenickými lesy, oblíbené letovisko obyvatel Reșițy. Silnice podél břehu nabízí pěkné výhledy a několik teras na kávu u vody. Odtud se dá odbočit i na horskou cestu Transsemenic.', 45.2422, 22.0155, 'https://commons.wikimedia.org/wiki/Special:FilePath/RO%20CS%20Lacul%20de%20acumulare%20Valiug%20(3).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/RO%20CS%20Lacul%20de%20acumulare%20Valiug%20(3).JPG"}'::text[], 0),
    (v_route, 'Vodopád Bigăr', 'Ikona rumunských kalendářů: krasový pramen padá přes osm metrů vysoký mechem obrostlý převis přímo u silnice DN57B, přesně na 45. rovnoběžce. Hlavní kaskáda se v roce 2021 částečně utrhla, místo ale zůstává kouzelné a zastávka zabere jen chvíli. Parkoviště hned u silnice.', 44.9247, 21.9536, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cascada%20Big%C4%83r.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cascada%20Big%C4%83r.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Izvorul%20Big%C4%83r.JPG"}'::text[], 1),
    (v_route, 'Vodopády Beușnița (Cheile Nerei)', 'Kaskády potoka Beu v národním parku Cheile Nerei-Beușnița, kde voda přepadá přes travertinové stupně v několika bílých závojích. Od parkoviště u Ochiul Beiului je to nenáročná procházka bukovým lesem. Nejvodnatější jsou na jaře po tání.', 44.9075, 21.8858, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cascadele%20Beu%C8%99ni%C8%9Bei.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cascadele%20Beu%C8%99ni%C8%9Bei.JPG"}'::text[], 2),
    (v_route, 'Jezírko Ochiul Beiului', 'Smaragdově tyrkysové krasové oko hluboké 3,6 metru, které nikdy nezamrzá. Barva vody je nejintenzivnější kolem poledne, kdy do jezírka svítí slunce. Přístup po lesní cestě z údolí Beu — část se dá opatrně dojet, zbytek pěšky.', 44.9036, 21.8894, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lacul%20Ochiul%20Beiului.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lacul%20Ochiul%20Beiului.jpg"}'::text[], 3),
    (v_route, 'Divadlo Mihai Eminescu (Oravița)', 'Nejstarší kamenné divadlo Rumunska (1817), postavené podle vzoru vídeňského Burgtheatru — hrál tu i císař František I. hostem. Oravița byla také výchozím bodem nejstarší horské železnice v zemi do Aniny, banátského Semmeringu. Příjemná kávová zastávka před závěrečným úsekem do Reșițy.', 45.0339, 21.6903, 'https://commons.wikimedia.org/wiki/Special:FilePath/Teatrul%201.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Teatrul%201.JPG"}'::text[], 4);

  -- Cazanele Dunării – rumunský břeh Železných vrat
  delete from public.routes where name = 'Cazanele Dunării – rumunský břeh Železných vrat' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Cazanele Dunării – rumunský břeh Železných vrat', 'Silnice DN57 podél rumunského břehu Dunaje patří k nejkrásnějším říčním vyjížďkám Evropy: veletok se mezi vápencovými stěnami Ciucaru Mare zužuje do dunajských kotlů Cazanele, kde se asfalt vine těsně nad hladinou. Trasa začíná u ruin Trajánova mostu v Drobetě a končí v秘lázních Băile Herculane hluboko v údolí Cerny. Cestou vás čeká klášter Mraconia nad vodou, vyhlídky na kotle a přístavní promenáda v Orșově. Zatáčky jsou rychlé a přehledné, provoz mírný, povrch výborný. Jarní a podzimní světlo nad řekou je odměna sama o sobě; v létě počítejte s vedrem.', 'poi', 135, 210, 'easy',
     '[{"lat": 44.6318, "lng": 22.6561, "label": "Start: Drobeta-Turnu Severin"}, {"lat": 44.7253, "lng": 22.3961, "label": "Orșova"}, {"lat": 44.6942, "lng": 22.3608, "label": "Eșelnița"}, {"lat": 44.6103, "lng": 22.2565, "label": "Mraconia"}, {"lat": 44.6183, "lng": 22.2647, "label": "Dubova"}, {"lat": 44.8794, "lng": 22.4128, "label": "Cíl: Băile Herculane"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=44.6318,22.6561&destination=44.8794,22.4128&travelmode=driving&waypoints=44.7253,22.3961%7C44.6942,22.3608%7C44.6103,22.2565%7C44.6183,22.2647', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cazanele%20Dun%C4%83rii.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turnu%20Severin%20Drobeta.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Orsova,%20Romania%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mraconia%20Monastery.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Cazanele%20Dun%C4%83rii.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cazinoul,%20Baile%20Herculane.JPG"}'::text[], '{"Drobeta – ruiny Trajánova mostu","Orșova – dunajský přístav","Klášter Mraconia","Velké kotle (Cazanele Mari)","Băile Herculane"}'::text[], '{"RO"}'::text[], false, 4950, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Drobeta – ruiny Trajánova mostu', 'U Drobety stál největší most antického světa — přes kilometr dlouhé dílo Apollodóra z Damašku, po němž římské legie roku 105 vtrhly do Dácie. Dodnes z něj na břehu trčí mohutné pilíře, hned vedle jsou ruiny římského kastra a lapidárium muzea Železných vrat. Symbolický start trasy po stopách Římanů.', 44.6244, 22.6683, 'https://commons.wikimedia.org/wiki/Special:FilePath/Turnu%20Severin%20Drobeta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turnu%20Severin%20Drobeta.jpg"}'::text[], 0),
    (v_route, 'Orșova – dunajský přístav', 'Městečko v zátoce na soutoku Cerny s Dunajem, celé přestavěné v 60. letech, kdy původní Orșovu zatopila přehrada. Promenáda s výhledem na kilometr širokou hladinu je ideální na první kávu; za pozornost stojí i moderní katolický kostel ve tvaru stanu. Odtud začíná nejhezčí úsek podél kotlů.', 44.7253, 22.3961, 'https://commons.wikimedia.org/wiki/Special:FilePath/Orsova,%20Romania%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Orsova,%20Romania%20-%20panoramio.jpg"}'::text[], 1),
    (v_route, 'Klášter Mraconia', 'Klášter přímo na hladině Dunaje v ústí zatopeného údolí Mraconia — původní svatyni pohltila přehrada, nová stavba z 90. let stojí na skalní terase u silnice. Jedno z nejfotografovanějších míst rumunského Podunají. Malé parkoviště bývá o víkendech plné, v týdnu je tu klid.', 44.6103, 22.2565, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mraconia%20Monastery.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mraconia%20Monastery.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Mraconia%20,%20Parcul%20Portile%20de%20Fier.jpg"}'::text[], 2),
    (v_route, 'Velké kotle (Cazanele Mari)', 'Nejužší místo dolního Dunaje: mezi stěnami Ciucaru Mare a srbského Velikého Štrbce se řeka svírá do pouhých pár set metrů a proudí jako v kotli. Od Dubové vede na hranu Ciucaru Mare značená stezka s výhledem, který bere dech. Z přístaviště v zátoce vyplouvají lodičky přímo do soutěsky i k jeskyni Ponicova.', 44.6183, 22.2647, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cazanele%20Dun%C4%83rii.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cazanele%20Dun%C4%83rii.jpg"}'::text[], 3),
    (v_route, 'Băile Herculane', 'Nejstarší lázně Evropy — horké sirné prameny tu využívali už římští legionáři a Herkulovy lázně zbožňovala i císařovna Sissi. Habsburská lázeňská架 architektura kolem Herkulova náměstí chátrá s morbidním půvabem, ale termální voda teče dál. Údolí Cerny nad městem je bránou do národního parku Domogled.', 44.8794, 22.4128, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cazinoul,%20Baile%20Herculane.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cazinoul,%20Baile%20Herculane.JPG"}'::text[], 4);

  -- Dobrudža – hory Măcin, Enisala a antická Histria
  delete from public.routes where name = 'Dobrudža – hory Măcin, Enisala a antická Histria' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Dobrudža – hory Măcin, Enisala a antická Histria', 'Okruh krajem mezi Dunajem a Černým mořem, na dohled od dunajské delty: nejstarší pohoří Rumunska Munții Măcinului se žulovými hřebeny jako z Provence, osmanský Babadag s nejstarší mešitou v zemi a středověká pevnost Enisala na kopci nad lagunou Razim. Tečkou je antická Histria, nejstarší řecké město na rumunském území. Silnice se vlní otevřenou stepní krajinou s minimem provozu — rychlé, přehledné oblouky a všudypřítomný vítr. Na jaře je Dobrudža zelená a plná ptáků z delty, v létě spálená do zlatova; vyhněte se poledním vedrům a hlídejte si benzín, pumpy jsou dál od sebe.', 'loop', 280, 360, 'easy',
     '[{"lat": 45.1786, "lng": 28.8047, "label": "Start: Tulcea"}, {"lat": 45.1892, "lng": 28.2286, "label": "Greci (Munții Măcinului)"}, {"lat": 45.0333, "lng": 28.4667, "label": "Horia"}, {"lat": 44.8931, "lng": 28.7128, "label": "Babadag"}, {"lat": 44.8828, "lng": 28.8367, "label": "Enisala"}, {"lat": 44.5486, "lng": 28.7756, "label": "Histria"}, {"lat": 45.1786, "lng": 28.8047, "label": "Cíl: Tulcea"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.1786,28.8047&destination=45.1786,28.8047&travelmode=driving&waypoints=45.1892,28.2286%7C45.0333,28.4667%7C44.8931,28.7128%7C44.8828,28.8367%7C44.5486,28.7756', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Enisala.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monumentul%20Independentei%20din%20Tulcea.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mun%C8%9Bii%20M%C4%83cinului.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Geamia%20Ali-Gazi%20Pa%C8%99a%20din%20Babadag.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Enisala.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Histria%20Constanta.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Danube%20Delta%20Biosphere%20Authority%20Head%20Office,%20Tulcea..JPG"}'::text[], '{"Tulcea – brána do delty Dunaje","Munții Măcinului","Mešita Gazi Ali Paši (Babadag)","Pevnost Enisala","Antická Histria","Restaurace: Ivan Pescar (Tulcea)"}'::text[], '{"RO"}'::text[], false, 4960, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Tulcea – brána do delty Dunaje', 'Přístavní město, odkud vyplouvají lodě do všech tří ramen dunajské delty. Nábřeží s Monumentem nezávislosti na návrší Colnicul Hora nabízí výhled na řeku i střechy města. Před vyjížďkou stojí za to koupit si mapu delty — třeba se sem vrátíte na lodní výlet.', 45.1786, 28.8047, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monumentul%20Independentei%20din%20Tulcea.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monumentul%20Independentei%20din%20Tulcea.jpg"}'::text[], 0),
    (v_route, 'Munții Măcinului', 'Nejstarší pohoří Rumunska — žulové hřebeny hercynského stáří obroušené na oblé rulíky a věžičky, dnes národní park. Hřeben Pricopan nad vesnicí Greci připomíná středomořskou macchii a žijí tu želvy i supi mrchožraví na tahu. Krátký výšlap od silnice nabídne výhled až k Dunaji.', 45.1892, 28.2286, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mun%C8%9Bii%20M%C4%83cinului.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mun%C8%9Bii%20M%C4%83cinului.jpg"}'::text[], 1),
    (v_route, 'Mešita Gazi Ali Paši (Babadag)', 'Nejstarší mešita Rumunska (1610) s kamenným minaretem, památka na tři století osmanské Dobrudže. Babadag byl kdysi významným městem na cestě z Istanbulu k dunajským pevnostem. Rychlá kulturní zastávka s výbornou tureckou kávou v okolí.', 44.8931, 28.7128, 'https://commons.wikimedia.org/wiki/Special:FilePath/Geamia%20Ali-Gazi%20Pa%C8%99a%20din%20Babadag.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Geamia%20Ali-Gazi%20Pa%C8%99a%20din%20Babadag.jpg"}'::text[], 2),
    (v_route, 'Pevnost Enisala', 'Jediná středověká pevnost v Rumunsku postavená Janovany — na vápencovém ostrohu nad lagunou Razim hlídala obchodní cestu k Černému moři. Zřícenina s obnovenou vstupní branou nabízí kruhový výhled na laguny, rákosiny a vinice, při západu slunce naprosto magický. Krátká odbočka z hlavní silnice, vstup pár lei.', 44.8828, 28.8367, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Enisala.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Enisala.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Enisala%202.jpg"}'::text[], 3),
    (v_route, 'Antická Histria', 'Nejstarší město na území Rumunska — milétská kolonie založená kolem roku 657 př. n. l. na břehu laguny Sinoe. Rozlehlé vykopávky chrámů, bazilik a hradeb doplňuje moderní muzeum. Po sedmi stoletích řecko-římského života město pohřbily nánosy Dunaje; dnes je to tiché místo mezi vodou a stepí.', 44.5486, 28.7756, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Histria%20Constanta.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Histria%20Constanta.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Ivan Pescar (Tulcea)', 'Nejznámější rybí podnik v Tulcei přímo na nábřeží — moderní pojetí lipovanské rybářské kuchyně, vyhlášená rybí polévka storceag a čerstvé úlovky z delty. Perfektní večeře po okruhu; v sezóně rezervujte předem.', 45.1772, 28.8000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Danube%20Delta%20Biosphere%20Authority%20Head%20Office,%20Tulcea..JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Danube%20Delta%20Biosphere%20Authority%20Head%20Office,%20Tulcea..JPG"}'::text[], 5);

  -- Saská Transylvánie – Sighișoara, Biertan a Viscri
  delete from public.routes where name = 'Saská Transylvánie – Sighișoara, Biertan a Viscri' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Saská Transylvánie – Sighișoara, Biertan a Viscri', 'Okruh krajinou sedmihradských Sasů: středověká Sighișoara s hodinovou věží, opevněné kostely UNESCO v Biertanu, Saschizu a Viscri a mohutná pevnost Rupea na čedičovém kopci. Mezi vesnicemi se silnice vlní pastvinami a dubovými háji, kde se od středověku mnoho nezměnilo — pastevci, ovce a čapí hnízda na komínech. Hlavní tahy mají dobrý asfalt, odbočka do Viscri je úzká a záplatovaná, tam zvolněte. Pozor na povozy a traktory za horizontem. Nejkrásnější v květnu a červnu, kdy kvetou louky, a v září ve zlatém světle.', 'loop', 195, 300, 'medium',
     '[{"lat": 46.2197, "lng": 24.7925, "label": "Start: Sighișoara"}, {"lat": 46.1353, "lng": 24.5136, "label": "Biertan"}, {"lat": 46.1647, "lng": 24.3486, "label": "Mediaș"}, {"lat": 46.2286, "lng": 24.5764, "label": "Dumbrăveni"}, {"lat": 46.1939, "lng": 24.9628, "label": "Saschiz"}, {"lat": 46.0553, "lng": 25.0889, "label": "Viscri"}, {"lat": 46.0392, "lng": 25.2192, "label": "Rupea"}, {"lat": 46.2197, "lng": 24.7925, "label": "Cíl: Sighișoara"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.2197,24.7925&destination=46.2197,24.7925&travelmode=driving&waypoints=46.1353,24.5136%7C46.1647,24.3486%7C46.2286,24.5764%7C46.1939,24.9628%7C46.0553,25.0889%7C46.0392,25.2192', 'https://commons.wikimedia.org/wiki/Special:FilePath/Turnul%20cu%20Ceas%20din%20Sighisoara%2005.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turnul%20cu%20Ceas%20din%20Sighisoara%2005.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Biertan%20Biserica%20fortificata.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Regele%20Ferdinand,%20Medias.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/RO%20MS%20Fortified%20Church%20Saschiz,%20Mures%20County.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Viscri%20fortified%20church%20in%20Brasov%20county,%20Romania.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rupea%20Fortress,%20Romania.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Strada%20Turnului,%20Cetatea%20Sighisoara.JPG"}'::text[], '{"Sighișoara – hodinová věž","Opevněný kostel Biertan","Mediaș","Opevněný kostel Saschiz","Viscri","Pevnost Rupea","Restaurace: Casa cu Cerb (Sighișoara)"}'::text[], '{"RO"}'::text[], false, 4970, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Sighișoara – hodinová věž', 'Jediná trvale obydlená středověká citadela Evropy a rodiště Vlada Țepeșe, předobrazu Drákuly. Vystoupejte na hodinovou věž s orlojem a barevnou glazovanou střechou — výhled na věže a uličky je nejlepší v celém Sedmihradsku. Motorku nechte pod hradbami, do citadely se jde pěšky po dlažbě.', 46.2197, 24.7925, 'https://commons.wikimedia.org/wiki/Special:FilePath/Turnul%20cu%20Ceas%20din%20Sighisoara%2005.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turnul%20cu%20Ceas%20din%20Sighisoara%2005.jpg"}'::text[], 0),
    (v_route, 'Opevněný kostel Biertan', 'Nejmohutnější saský opevněný kostel, tři prstence hradeb na kopci uprostřed vesnice a památka UNESCO. Sakristie má proslulý zámek s devatenácti západkami, div středověkého zámečnictví. Z ochozů je krásný výhled na vinice, kterými sem přijíždíte.', 46.1353, 24.5136, 'https://commons.wikimedia.org/wiki/Special:FilePath/Biertan%20Biserica%20fortificata.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biertan%20Biserica%20fortificata.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Biertan%20fortified%20church%20entrance.jpg"}'::text[], 1),
    (v_route, 'Mediaș', 'Saské královské město s křivou věží Turnul Trompeților, která se naklání skoro jako ta v Pise. Náměstí Regele Ferdinand lemují měšťanské domy s podloubími a pastelovými fasádami. Dobrá zastávka na kávu v půli západní smyčky okruhu.', 46.1647, 24.3486, 'https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Regele%20Ferdinand,%20Medias.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Regele%20Ferdinand,%20Medias.jpg"}'::text[], 2),
    (v_route, 'Opevněný kostel Saschiz', 'Památka UNESCO s věží inspirovanou sighișoarskou hodinovou věží, přímo u hlavní silnice. Nad vesnicí se navíc krčí zřícenina selské pevnosti, kam se Sasové stahovali při nájezdech. Ve vsi ochutnejte místní specialitu — džem a šťávu z rebarbory.', 46.1939, 24.9628, 'https://commons.wikimedia.org/wiki/Special:FilePath/RO%20MS%20Fortified%20Church%20Saschiz,%20Mures%20County.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/RO%20MS%20Fortified%20Church%20Saschiz,%20Mures%20County.jpg"}'::text[], 3),
    (v_route, 'Viscri', 'Nejslavnější saská vesnice — bílý opevněný kostel UNESCO na kopci, modré štíty domů a jediná prašná náves, kde chodí husy středem. Dům číslo 63 patří králi Karlu III., který sem jezdí desítky let. Příjezdová silnice je úzká s výmoly; pomalu, ať si užijete i výhledy.', 46.0553, 25.0889, 'https://commons.wikimedia.org/wiki/Special:FilePath/Viscri%20fortified%20church%20in%20Brasov%20county,%20Romania.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Viscri%20fortified%20church%20in%20Brasov%20county,%20Romania.jpg"}'::text[], 4),
    (v_route, 'Pevnost Rupea', 'Mohutná spirála hradeb na čedičovém suku nad silnicí Sighișoara–Brašov, osídleném už v pravěku. Rekonstruovaná pevnost má tři nádvoří a věže s výhledem na celé Podhůří Perșan. Od parkoviště pod hradem je to nahoru pár minut pěšky.', 46.0392, 25.2192, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rupea%20Fortress,%20Romania.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rupea%20Fortress,%20Romania.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Casa cu Cerb (Sighișoara)', 'Legendární Dům s jelenem na rohu citadelního náměstí, renesanční hostinec s freskou jelena na fasádě. Sedmihradská kuchyně s německými kořeny — jelení guláš, kysané zelí, místní vína. Po večeři si projděte hradby, večer patří citadela jen místním.', 46.2194, 24.7920, 'https://commons.wikimedia.org/wiki/Special:FilePath/Strada%20Turnului,%20Cetatea%20Sighisoara.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Strada%20Turnului,%20Cetatea%20Sighisoara.JPG"}'::text[], 6);

  -- Soutěska Bicaz, Rudé jezero a Ceahlău
  delete from public.routes where name = 'Soutěska Bicaz, Rudé jezero a Ceahlău' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Soutěska Bicaz, Rudé jezero a Ceahlău', 'Okruh kolem posvátné hory Moldavska: silnice DN12C se v soutěsce Bicaz doslova zařezává pod třistametrové převisy — nejdramatičtější kilometry asfaltu v Karpatech. Nahoře čeká Rudé jezero s uschlými kmeny trčícími z hladiny a sjezd do sikulského Gheorgheni. Zpět se vracíte údolím Bistrițy kolem přehrady Izvorul Muntelui, rumunského moře mezi horami, s výhledy na štíty Ceahlău. V soutěsce pozor na mokré pásy pod skalami, padající kamínky a autobusy v zúžených hrdlech. Nejlépe červen až září; brzy ráno projedete soutěsku skoro sami.', 'loop', 240, 360, 'medium',
     '[{"lat": 46.9275, "lng": 26.3708, "label": "Start: Piatra Neamț"}, {"lat": 46.9139, "lng": 26.0906, "label": "Bicaz"}, {"lat": 46.8103, "lng": 25.8236, "label": "Cheile Bicazului"}, {"lat": 46.7886, "lng": 25.7908, "label": "Lacu Roșu"}, {"lat": 46.7220, "lng": 25.6003, "label": "Gheorgheni"}, {"lat": 46.9394, "lng": 25.7550, "label": "Tulgheș"}, {"lat": 47.0364, "lng": 25.9367, "label": "Durău"}, {"lat": 46.9275, "lng": 26.3708, "label": "Cíl: Piatra Neamț"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.9275,26.3708&destination=46.9275,26.3708&travelmode=driving&waypoints=46.9139,26.0906%7C46.8103,25.8236%7C46.7886,25.7908%7C46.7220,25.6003%7C46.9394,25.7550%7C47.0364,25.9367', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cheile%20Bicazului,%20(gorges%20de%20bicaz)%20(1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cheile%20Bicazului,%20(gorges%20de%20bicaz)%20(1).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lacul%20Ro%C8%99u%20-%20lac%20de%20baraj%20natural%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ceahlau%20Toaca.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Baraj%20Bicaz%20vedere%20spre%20lacul%20Izvorul%20Muntelui.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Piatra%20Neamt%20Turnul%20lui%20Stefan%20,.jpg"}'::text[], '{"Soutěska Bicaz (Cheile Bicazului)","Rudé jezero (Lacu Roșu)","Masiv Ceahlău","Přehrada Izvorul Muntelui (Barajul Bicaz)","Piatra Neamț"}'::text[], '{"RO"}'::text[], false, 4980, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Soutěska Bicaz (Cheile Bicazului)', 'Osm kilometrů silnice sevřené mezi kolmými vápencovými stěnami až 300 metrů vysokými — v úseku Gât Iadului (Hrdlo pekla) se skály nad vozovkou téměř dotýkají. Jedna z nejikoničtějších motorkářských fotek Rumunska vzniká právě tady. Zastavujte jen na vyznačených místech, v sezóně tu bývají stánky a hodně lidí.', 46.8103, 25.8236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cheile%20Bicazului,%20(gorges%20de%20bicaz)%20(1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cheile%20Bicazului,%20(gorges%20de%20bicaz)%20(1).jpg"}'::text[], 0),
    (v_route, 'Rudé jezero (Lacu Roșu)', 'Jezero vzniklé roku 1837 sesuvem, který zahradil údolí — z hladiny dodnes trčí pahýly zatopených smrků jako les duchů. Kolem jezera vede promenáda s výhledem na skalní věž Suhardul Mic. Ochutnejte pstruha z místních udíren, jezerní klasiku.', 46.7886, 25.7908, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lacul%20Ro%C8%99u%20-%20lac%20de%20baraj%20natural%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lacul%20Ro%C8%99u%20-%20lac%20de%20baraj%20natural%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lacu%20Rosu%20walkpath%202007.JPG"}'::text[], 1),
    (v_route, 'Masiv Ceahlău', 'Posvátná hora Moldavska s věží Toaca (1904 m), opředená legendami o dáckém bohu Zalmoxidovi. Z letoviska Durău vede na vrchol nejkratší značená cesta; i bez výstupu stojí serpentiny k Durău za odbočku kvůli výhledům. Za jasného rána se masiv zrcadlí v hladině přehrady.', 47.0364, 25.9367, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ceahlau%20Toaca.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ceahlau%20Toaca.JPG"}'::text[], 2),
    (v_route, 'Přehrada Izvorul Muntelui (Barajul Bicaz)', 'Betonová hráz z roku 1960, ve své době jedna z největších v Evropě, zadržuje 35 km dlouhé jezero mezi horami. Silnice po západním břehu patří k nejhezčím jezerním úsekům v zemi. U hráze je vyhlídka a v přístavišti Potoci půjčovna lodí.', 46.9531, 26.0894, 'https://commons.wikimedia.org/wiki/Special:FilePath/Baraj%20Bicaz%20vedere%20spre%20lacul%20Izvorul%20Muntelui.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Baraj%20Bicaz%20vedere%20spre%20lacul%20Izvorul%20Muntelui.jpg"}'::text[], 3),
    (v_route, 'Piatra Neamț', 'Podhorské město přezdívané perla Moldavska, s knížecím dvorem Štěpána Velikého a kamennou zvonicí z roku 1499 přímo v centru. Lanovka na kopec Cozla nabízí výhled na město sevřené zalesněnými vrchy. Dobré místo na večeři a přespání po okruhu.', 46.9275, 26.3708, 'https://commons.wikimedia.org/wiki/Special:FilePath/Piatra%20Neamt%20Turnul%20lui%20Stefan%20,.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piatra%20Neamt%20Turnul%20lui%20Stefan%20,.jpg"}'::text[], 4);

  -- Brašov, Bran a Peleș – hrady pod Karpaty
  delete from public.routes where name = 'Brašov, Bran a Peleș – hrady pod Karpaty' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Brašov, Bran a Peleș – hrady pod Karpaty', 'Klasika mezi rumunskými okruhy: gotický Brašov s Černým kostelem, pohádkový zámek Peleș v Sinaii, selská pevnost Râșnov na skále a samozřejmě Bran, hrad spojovaný s Drákulou. Mezi nimi se jezdí pod stěnami pohoří Bucegi a Piatra Craiului, závěr obstará lesní stoupání do Poiany Brașov. Silnice jsou kvalitní, ale DN1 u Sinaie patří k nejvytíženějším v zemi — o víkendech počítejte s kolonami, hrady i silnice jsou nejpříjemnější ve všední den brzy ráno. Vhodné od jara do podzimu, na Peleș si vyhraďte aspoň dvě hodiny.', 'loop', 155, 240, 'easy',
     '[{"lat": 45.6427, "lng": 25.5887, "label": "Start: Brašov"}, {"lat": 45.3553, "lng": 25.5481, "label": "Sinaia"}, {"lat": 45.4964, "lng": 25.5750, "label": "Predeal"}, {"lat": 45.5883, "lng": 25.4606, "label": "Râșnov"}, {"lat": 45.5150, "lng": 25.3672, "label": "Bran"}, {"lat": 45.5958, "lng": 25.5556, "label": "Poiana Brașov"}, {"lat": 45.6427, "lng": 25.5887, "label": "Cíl: Brašov"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.6427,25.5887&destination=45.6427,25.5887&travelmode=driving&waypoints=45.3553,25.5481%7C45.4964,25.5750%7C45.5883,25.4606%7C45.5150,25.3672%7C45.5958,25.5556', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bran%20Castle%20TB1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Neagra%20(Black%20Church),%20Brasov,%20Romania,%20Oct.%202012.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Peles-Castle-Sinaia-Romania.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Sinaia.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Rasnov%20si%20orasul.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Bran%20Castle%20TB1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Sfatului%20Brasov%20Ro.jpg"}'::text[], '{"Černý kostel (Brašov)","Zámek Peleș","Klášter Sinaia","Pevnost Râșnov","Hrad Bran","Restaurace: Sergiana (Brašov)"}'::text[], '{"RO"}'::text[], false, 4990, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Černý kostel (Brašov)', 'Největší gotický kostel mezi Vídní a Istanbulem, začernalý požárem roku 1689, s unikátní sbírkou anatolských koberců a šestitunovým zvonem. Stojí hned vedle náměstí Piața Sfatului s podloubími a kavárnami. Projděte si i uličku Strada Sforii, jednu z nejužších v Evropě.', 45.6410, 25.5884, 'https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Neagra%20(Black%20Church),%20Brasov,%20Romania,%20Oct.%202012.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20Neagra%20(Black%20Church),%20Brasov,%20Romania,%20Oct.%202012.jpg"}'::text[], 0),
    (v_route, 'Zámek Peleș', 'Letní rezidence krále Karla I., dokončená 1914 — neorenesanční skvost se 160 pokoji, vyřezávanými interiéry a prvním elektrickým osvětlením v zemi. Mnozí ho řadí mezi nejkrásnější zámky Evropy. Od parkoviště v Sinaii se jde ke vstupu asi deset minut lesní alejí.', 45.3600, 25.5426, 'https://commons.wikimedia.org/wiki/Special:FilePath/Peles-Castle-Sinaia-Romania.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Peles-Castle-Sinaia-Romania.jpg"}'::text[], 1),
    (v_route, 'Klášter Sinaia', 'Klášter ze 17. století, podle něhož dostalo jméno celé město — zakladatel ho pojmenoval po hoře Sinaj. Starý kostelík s freskami a klidný rajský dvůr jsou příjemným kontrastem k ruchu kolem Peleșe, který je odsud pár minut pěšky. Vstup za symbolické vstupné.', 45.3553, 25.5481, 'https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Sinaia.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Manastirea%20Sinaia.JPG"}'::text[], 2),
    (v_route, 'Pevnost Râșnov', 'Selská pevnost ze 13. století na skále 150 metrů nad městem, kam se vešla celá vesnice i se zvířaty. Podle pověsti kopali obležení studnu ve skále třicet let. Nahoru vede silnička i lanovka; výhled na Bucegi a Piatra Craiului je velkolepý.', 45.5883, 25.4606, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Rasnov%20si%20orasul.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cetatea%20Rasnov%20si%20orasul.JPG"}'::text[], 3),
    (v_route, 'Hrad Bran', 'Nejslavnější hrad Rumunska na skále nad průsmykem mezi Valašskem a Sedmihradskem, marketingově spojený s Drákulou — Bram Stoker ho nikdy neviděl, atmosféře věžiček a tajných schodišť to ale neubírá. Uvnitř je muzeum královny Marie, která hrad milovala. Dorazte před desátou, než přijedou autobusy.', 45.5150, 25.3672, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bran%20Castle%20TB1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bran%20Castle%20TB1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Castelul%20Bran.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Sergiana (Brašov)', 'Vyhlášený sklepní podnik pár kroků od Piața Sfatului — sedmihradská a saská kuchyně v cihlových klenbách, vlastní řeznictví a porce, po kterých se dobře spí. Vyzkoušejte polévku v chlebu a plăcintu. Večer bývá plno, rezervujte.', 45.6421, 25.5896, 'https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Sfatului%20Brasov%20Ro.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Sfatului%20Brasov%20Ro.jpg"}'::text[], 5);

  -- Mărginimea Sibiului a Păltiniș
  delete from public.routes where name = 'Mărginimea Sibiului a Păltiniș' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mărginimea Sibiului a Păltiniș', 'Kratší požitkářský okruh kolem Sibiu, evropského hlavního města kultury 2007: renesanční Piața Mare s domy s očima ve střechách, skanzen ASTRA v dubovém lese a pastevecké vesnice Mărginimie, kraje sedmihradských salašníků. Sportovní vložkou je hladké serpentinové stoupání do Păltiniș, nejvýše položeného horského letoviska v zemi (1440 m). Provoz mimo město minimální, asfalt na stoupání výborný — ideální odpolední trasa po příjezdu do Sibiu. Sjízdné od jara do pozdního podzimu, v Păltiniș bývá i v létě o deset stupňů chladněji.', 'loop', 130, 210, 'easy',
     '[{"lat": 45.7969, "lng": 24.1519, "label": "Start: Sibiu"}, {"lat": 45.7083, "lng": 24.1236, "label": "Cisnădioara"}, {"lat": 45.7000, "lng": 24.0630, "label": "Rășinari"}, {"lat": 45.6636, "lng": 23.9260, "label": "Păltiniș"}, {"lat": 45.7553, "lng": 23.9422, "label": "Sibiel"}, {"lat": 45.7644, "lng": 24.1447, "label": "Muzeum ASTRA"}, {"lat": 45.7969, "lng": 24.1519, "label": "Cíl: Sibiu"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=45.7969,24.1519&destination=45.7969,24.1519&travelmode=driving&waypoints=45.7083,24.1236%7C45.7000,24.0630%7C45.6636,23.9260%7C45.7553,23.9422%7C45.7644,24.1447', 'https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Mare%20din%20Sibiu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Mare%20din%20Sibiu.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20fortificat%C4%83%20din%20cisn%C4%83dioara.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rasinari%2003.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Paltinis.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/ASTRA%20National%20Museum%20Complex%20,%20main%20entrance%20of%20the%20Open%20air%20museum,%20Sibiu.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sibiu,%20Turnul%20Sfatului.jpg"}'::text[], '{"Sibiu – Piața Mare","Cisnădioara – románský kostelík","Rășinari","Păltiniș (1440 m)","Skanzen ASTRA","Restaurace: Crama Sibiul Vechi (Sibiu)"}'::text[], '{"RO"}'::text[], false, 5000, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Sibiu – Piața Mare', 'Velké náměstí bývalého Hermannstadtu lemují barokní paláce a domy, jejichž střešní vikýře vypadají jako přivřené oči — místní říkají, že vás Sibiu pořád pozoruje. Kousek odtud je Most lhářů a věž Turnul Sfatului s vyhlídkou. Jedno z nejhezčích historických center Rumunska.', 45.7969, 24.1519, 'https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Mare%20din%20Sibiu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Piata%20Mare%20din%20Sibiu.jpg"}'::text[], 0),
    (v_route, 'Cisnădioara – románský kostelík', 'Na strmém kopci nad vesnicí stojí jeden z nejstarších románských kostelů Rumunska (kolem 1200) obehnaný hradbou. Mladíci prý směli k oltáři donést valoun jen tehdy, když ho vynesli na kopec — zásoba střeliva pro obránce. Výstup od parkoviště zabere deset minut a odmění výhledem na Cindrel.', 45.7083, 24.1236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20fortificat%C4%83%20din%20cisn%C4%83dioara.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Biserica%20fortificat%C4%83%20din%20cisn%C4%83dioara.jpg"}'::text[], 1),
    (v_route, 'Rășinari', 'Jedna z nejstarších a největších pasteveckých vesnic Mărginimie, rodiště filozofa Emila Ciorana a básníka Octaviana Gogy. Malované domy, kamenné uličky a kostel s freskami; ze Sibiu sem dřív jezdila i tramvaj lesem. Odtud začíná serpentinové stoupání na Păltiniș.', 45.7000, 24.0630, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rasinari%2003.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rasinari%2003.jpg"}'::text[], 2),
    (v_route, 'Păltiniș (1440 m)', 'Nejvýše položené horské letovisko Rumunska, založené roku 1894 sedmihradskými Sasy v smrkových lesích pohoří Cindrel. Dřevěné vily Hohe Rinne, čistý vzduch a v zimě lyžování; filozof Constantin Noica tu vedl svou proslulou horskou školu myšlení. Stoupání ze Rășinari je řidičská lahůdka s výhledy na kotlinu Sibiu.', 45.6636, 23.9260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Paltinis.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Paltinis.jpg"}'::text[], 3),
    (v_route, 'Skanzen ASTRA', 'Největší muzeum v přírodě v Evropě: 96 hektarů dubového lesa Dumbrava s třemi stovkami mlýnů, salaší, lisoven a chalup ze všech koutů Rumunska, propojených jezerem a alejemi. Na obhlídku toho hlavního počítejte s dobrou hodinou. Velké parkoviště přímo u vstupu.', 45.7644, 24.1447, 'https://commons.wikimedia.org/wiki/Special:FilePath/ASTRA%20National%20Museum%20Complex%20,%20main%20entrance%20of%20the%20Open%20air%20museum,%20Sibiu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/ASTRA%20National%20Museum%20Complex%20,%20main%20entrance%20of%20the%20Open%20air%20museum,%20Sibiu.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Crama Sibiul Vechi (Sibiu)', 'Nejstarší sklepní restaurace v Sibiu v bývalém vinném sklepě — obsluha v krojích, cimbál a poctivé sedmihradské klasiky jako bulz, sarmale a pastevecký guláš. Pár kroků od Piața Mare, ideální večeře po okruhu. Večer rezervujte, sklep je malý a oblíbený.', 45.7952, 24.1497, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sibiu,%20Turnul%20Sfatului.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sibiu,%20Turnul%20Sfatului.jpg"}'::text[], 5);

end $$;
