-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — NIZOZEMSKO (2. dávka, 10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Nizozemsko – Zeeland a Delta Works
  delete from public.routes where name = 'Nizozemsko – Zeeland a Delta Works' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – Zeeland a Delta Works', 'Okruh po ostrovech Zeelandu, kde se jezdí doslova po moři — silnice vedou po hrázích a přehradních tělesech největšího protipovodňového díla světa. Vrcholem je přejezd bariéry Oosterscheldekering, devět kilometrů betonových pilířů mezi Severním mořem a deltou. Cestou vás čekají pohádkové přístavní městečko Veere, hanzovní Zierikzee i maják ve Westkapelle na nejzápadnějším cípu Walcherenu. Silnice jsou perfektní, provoz mimo sezónu minimální, zatáčky nahrazuje neskutečný pocit jízdy mezi dvěma vodními hladinami. Nejlepší je jaro a začátek podzimu; celoročně počítejte se silným bočním větrem na hrázích — v Zeelandu fouká prakticky pořád.', 'loop', 120, 200, 'easy',
     '[{"lat": 51.4988, "lng": 3.6136, "label": "Start: Middelburg"}, {"lat": 51.5470, "lng": 3.6670, "label": "Veere"}, {"lat": 51.6218, "lng": 3.6870, "label": "Oosterscheldekering"}, {"lat": 51.6500, "lng": 3.9167, "label": "Zierikzee"}, {"lat": 51.5280, "lng": 3.4430, "label": "Westkapelle"}, {"lat": 51.5620, "lng": 3.4970, "label": "Domburg"}, {"lat": 51.4988, "lng": 3.6136, "label": "Cíl: Middelburg"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.4988,3.6136&destination=51.4988,3.6136&travelmode=driving&waypoints=51.5470,3.6670%7C51.6218,3.6870%7C51.6500,3.9167%7C51.5280,3.4430%7C51.5620,3.4970', 'https://commons.wikimedia.org/wiki/Special:FilePath/Oosterscheldekering-pohled.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grote%20Kerk%20Veere.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Campveerse%20Toren.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Oosterscheldekering-pohled.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zierikzee.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Westkapelle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Domburg.jpg"}'::text[], '{"Veere – přístav a Grote Kerk","Restaurace: De Campveerse Toren (Veere)","Oosterscheldekering","Zierikzee","Westkapelle – maják","Domburg"}'::text[], '{"NL"}'::text[], false, 4510, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Veere – přístav a Grote Kerk', 'Kdysi bohaté obchodní město, dnes jedno z nejmalebnějších míst Zeelandu. Přístav s historickými plachetnicemi hlídá mohutná Grote Kerk a gotická radnice. Ideální první zastávka na kávu hned po startu.', 51.5470, 3.6670, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grote%20Kerk%20Veere.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grote%20Kerk%20Veere.jpg"}'::text[], 0),
    (v_route, 'Restaurace: De Campveerse Toren (Veere)', 'Restaurace v obranné věži z 15. století přímo nad vodou — jeden z nejstarších hostinců v Nizozemsku, kde se hodovalo už na svatbě Viléma Oranžského. Výborné mořské plody a výhled na jezero Veerse Meer. Rezervace se v sezóně vyplatí.', 51.5490, 3.6690, 'https://commons.wikimedia.org/wiki/Special:FilePath/Campveerse%20Toren.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Campveerse%20Toren.jpg"}'::text[], 1),
    (v_route, 'Oosterscheldekering', 'Největší z Delta Works — devět kilometrů dlouhá vzdouvací bariéra s 62 ocelovými vraty, po které vede silnice N57. Jízda po ní je zeelandský zážitek číslo jedna: vlevo moře, vpravo delta, nad hlavou racci. Na umělém ostrově Neeltje Jans je návštěvnické centrum Deltaparku.', 51.6218, 3.6870, 'https://commons.wikimedia.org/wiki/Special:FilePath/Oosterscheldekering-pohled.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oosterscheldekering-pohled.jpg"}'::text[], 2),
    (v_route, 'Zierikzee', 'Hanzovní městečko s více než pěti sty památkami, přístavními branami a nedostavěnou obří věží Sint-Lievensmonstertoren. Historické centrum je kompaktní — motorku nechte u přístavu a projděte se. Cestou zpět přejedete další z hrází Delta Works.', 51.6500, 3.9167, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zierikzee.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zierikzee.jpg"}'::text[], 3),
    (v_route, 'Westkapelle – maják', 'Nejzápadnější bod ostrova Walcheren s majákem stojícím na mohutné mořské hrázi, kterou za války prorazili Spojenci při osvobozování Zeelandu. Z hráze je výhled na lodní trasu do Antverp. Větrné, syrové a krásné místo.', 51.5280, 3.4430, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Westkapelle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Westkapelle.jpg"}'::text[], 4),
    (v_route, 'Domburg', 'Nejstarší mořské lázně Zeelandu s dlouhou písečnou pláží a promenádou v dunách. Na zmrzlinu nebo rychlé osvěžení před závěrečným úsekem zpět do Middelburgu je to ideální zastávka. V létě tu bývá živo, mimo sezónu klid.', 51.5620, 3.4970, 'https://commons.wikimedia.org/wiki/Special:FilePath/Domburg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Domburg.jpg"}'::text[], 5);

  -- Nizozemsko – Friesland a města Elfstedentocht
  delete from public.routes where name = 'Nizozemsko – Friesland a města Elfstedentocht' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – Friesland a města Elfstedentocht', 'Okruh po stopách legendárního bruslařského závodu Elfstedentocht, který spojuje historická fríská města. Na motorce si projedete jeho jihozápadní polovinu: Leeuwarden se šikmou věží Oldehove, Sneek s ikonickou vodní bránou a řadu miniaturních přístavních měst na břehu IJsselmeeru. Silnice se vinou mezi kanály, pastvinami a zvedacími mosty — typická fríská krajina, kde je víc vody než pevniny. Provoz je řídký, tempo poklidné, zážitek maximální. Nejhezčí je od května do září; na hrázích IJsselmeeru počítejte s větrem a v ranních hodinách s mlhou nad kanály.', 'loop', 130, 210, 'easy',
     '[{"lat": 53.2028, "lng": 5.7889, "label": "Start: Leeuwarden"}, {"lat": 53.0330, "lng": 5.6580, "label": "Sneek"}, {"lat": 52.8830, "lng": 5.3610, "label": "Stavoren"}, {"lat": 52.9420, "lng": 5.4030, "label": "Hindeloopen"}, {"lat": 52.9790, "lng": 5.4470, "label": "Workum"}, {"lat": 53.0630, "lng": 5.5280, "label": "Bolsward"}, {"lat": 53.2028, "lng": 5.7889, "label": "Cíl: Leeuwarden"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=53.2028,5.7889&destination=53.2028,5.7889&travelmode=driving&waypoints=53.0330,5.6580%7C52.8830,5.3610%7C52.9420,5.4030%7C52.9790,5.4470%7C53.0630,5.5280', 'https://commons.wikimedia.org/wiki/Special:FilePath/Waterpoort%20Sneek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oldehove%20Leeuwarden.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Waterpoort%20Sneek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stavoren.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hindeloopen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Workum.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stadhuis%20Bolsward.jpg"}'::text[], '{"Leeuwarden – Oldehove","Sneek – Waterpoort","Stavoren","Hindeloopen","Workum","Bolsward – radnice"}'::text[], '{"NL"}'::text[], false, 4520, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Leeuwarden – Oldehove', 'Hlavní město Fríska a jeho šikmá věž Oldehove — nakloněná víc než ta v Pise a nikdy nedostavěná. Z ochozu je výhled na celé město i okolní polders. Před startem stojí za to projít historické centrum s kanály.', 53.2028, 5.7889, 'https://commons.wikimedia.org/wiki/Special:FilePath/Oldehove%20Leeuwarden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oldehove%20Leeuwarden.jpg"}'::text[], 0),
    (v_route, 'Sneek – Waterpoort', 'Vodní brána z roku 1613 s dvojicí věžiček je symbolem fríské vodní turistiky a nejfotografovanější stavbou provincie. Sneek je centrem jachtingu — v přístavu to žije celé léto. Kavárny u vody přímo vybízejí k zastávce.', 53.0330, 5.6580, 'https://commons.wikimedia.org/wiki/Special:FilePath/Waterpoort%20Sneek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Waterpoort%20Sneek.jpg"}'::text[], 1),
    (v_route, 'Stavoren', 'Nejstarší město Fríska na samém břehu IJsselmeeru, spojené s pověstí o Paní ze Stavorenu. Z mola u majáku je výhled přes celé vnitrozemské moře. Odtud vede trasa po hrázi na sever — nejhezčí úsek okruhu.', 52.8830, 5.3610, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stavoren.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stavoren.jpg"}'::text[], 2),
    (v_route, 'Hindeloopen', 'Miniaturní přístavní městečko proslulé malovaným nábytkem a vlastním krojem i dialektem. Dřevěné můstky přes kanály, kapitánské domky a muzeum bruslení — Elfstedentocht tu má jednu z nejromantičtějších zastávek. Motorku zaparkujte před centrem, uličky jsou pro pěší.', 52.9420, 5.4030, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hindeloopen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hindeloopen.jpg"}'::text[], 3),
    (v_route, 'Workum', 'Protáhlé městečko s dřevěnou zvonicí, historickou váhou a keramickou tradicí. Sídlí tu muzeum naivního malíře Jopieho Huismana, jednoho z nejnavštěvovanějších ve Frísku. Příjemná zastávka na kávu na hlavním náměstí Merk.', 52.9790, 5.4470, 'https://commons.wikimedia.org/wiki/Special:FilePath/Workum.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Workum.jpg"}'::text[], 4),
    (v_route, 'Bolsward – radnice', 'Renesanční radnice z roku 1617 patří k nejkrásnějším v Nizozemsku — bohatě zdobené průčelí s dvojitým schodištěm je chloubou města. Bolsward je také domovem pivovaru Us Heit s frískou whisky. Poslední zastávka před návratem do Leeuwardenu.', 53.0630, 5.5280, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stadhuis%20Bolsward.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stadhuis%20Bolsward.jpg"}'::text[], 5);

  -- Nizozemsko – Veluwezoom, Posbank a Arnhem
  delete from public.routes where name = 'Nizozemsko – Veluwezoom, Posbank a Arnhem' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – Veluwezoom, Posbank a Arnhem', 'Nejzatáčkovitější kousek Nizozemska: národní park Veluwezoom s vyhlídkou Posbank je nedělní mekkou holandských motorkářů — vlnitá silnička stoupá vřesovišti do „závratných" 90 metrů nad mořem. Okruh přidává nejmenší město země Bronkhorst, barokní královský palác Het Loo a katedrálu vysílací techniky Radio Kootwijk uprostřed písečných dun. Závěr patří válečné historii: Oosterbeek a arnhemský most, o který se bojovalo v operaci Market Garden. Lesní úseky svádějí k tempu, ale pozor na zvěř, cyklisty a víkendové kontroly rychlosti. Nejkrásněji je tu v srpnu a září, kdy kvete vřes.', 'loop', 140, 220, 'medium',
     '[{"lat": 51.9770, "lng": 5.9110, "label": "Start: Arnhem"}, {"lat": 52.0330, "lng": 6.0210, "label": "Posbank"}, {"lat": 52.0700, "lng": 6.1930, "label": "Bronkhorst"}, {"lat": 52.2333, "lng": 5.9450, "label": "Paleis Het Loo"}, {"lat": 52.1730, "lng": 5.8140, "label": "Radio Kootwijk"}, {"lat": 51.9880, "lng": 5.8320, "label": "Oosterbeek"}, {"lat": 51.9770, "lng": 5.9110, "label": "Cíl: Arnhem"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.9770,5.9110&destination=51.9770,5.9110&travelmode=driving&waypoints=52.0330,6.0210%7C52.0700,6.1930%7C52.2333,5.9450%7C52.1730,5.8140%7C51.9880,5.8320', 'https://commons.wikimedia.org/wiki/Special:FilePath/Posbank.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/John%20Frostbrug.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Posbank.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bronkhorst.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Paleis%20Het%20Loo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Radio%20Kootwijk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Airborne%20Museum%20Hartenstein.jpg"}'::text[], '{"Arnhem – John Frostbrug","Posbank","Bronkhorst","Paleis Het Loo","Radio Kootwijk","Airborne Museum Hartenstein (Oosterbeek)"}'::text[], '{"NL"}'::text[], false, 4530, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Arnhem – John Frostbrug', 'Ten „most příliš vzdálený" z operace Market Garden 1944, pojmenovaný po veliteli britských výsadkářů Johnu Frostovi. Přejedete ho hned na startu — u severního předmostí je památník a expozice. Silný začátek trasy plné historie.', 51.9770, 5.9110, 'https://commons.wikimedia.org/wiki/Special:FilePath/John%20Frostbrug.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/John%20Frostbrug.jpg"}'::text[], 0),
    (v_route, 'Posbank', 'Vyhlídka nad zvlněnými vřesovišti národního parku Veluwezoom a kultovní motorkářský sraz — v neděli dopoledne tu parkují stovky strojů. Silnička přes kopce je nejblíž horské jízdě, co v Nizozemsku najdete. V paviliónu na vrcholu se dá posedět s výhledem.', 52.0330, 6.0210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Posbank.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Posbank.jpg"}'::text[], 1),
    (v_route, 'Bronkhorst', 'Oficiálně nejmenší město Nizozemska — pár dlážděných uliček, hrázděné domky a kaple mezi poli u řeky IJssel. Městská práva má od roku 1482, obyvatel ani dvě stovky. Kouzelná zastávka, kterou projdete za dvacet minut.', 52.0700, 6.1930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bronkhorst.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bronkhorst.jpg"}'::text[], 2),
    (v_route, 'Paleis Het Loo', 'Barokní palác oranžské dynastie u Apeldoornu, přezdívaný „Versailles severu". Symetrické zahrady s fontánami a královské interiéry po velké rekonstrukci znovu září. I krátká zastávka u zahrad stojí za to.', 52.2333, 5.9450, 'https://commons.wikimedia.org/wiki/Special:FilePath/Paleis%20Het%20Loo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Paleis%20Het%20Loo.jpg"}'::text[], 3),
    (v_route, 'Radio Kootwijk', 'Monumentální betonová „katedrála éteru" z roku 1923 uprostřed písečných přesypů Veluwe — odtud se telegrafovalo s Nizozemskou východní Indií. Art deco budova A vypadá jako kulisa sci-fi filmu. Příjezdová silnice dunami je zážitek sama o sobě.', 52.1730, 5.8140, 'https://commons.wikimedia.org/wiki/Special:FilePath/Radio%20Kootwijk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Radio%20Kootwijk.jpg"}'::text[], 4),
    (v_route, 'Airborne Museum Hartenstein (Oosterbeek)', 'Vila Hartenstein sloužila v září 1944 jako štáb britské 1. výsadkové divize; dnes je z ní strhující muzeum bitvy o Arnhem. Interaktivní expozice Airborne Experience vás vtáhne přímo do bojů. Důstojná tečka před návratem do města.', 51.9880, 5.8320, 'https://commons.wikimedia.org/wiki/Special:FilePath/Airborne%20Museum%20Hartenstein.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Airborne%20Museum%20Hartenstein.jpg"}'::text[], 5);

  -- Nizozemsko – kopce jižního Limburgu
  delete from public.routes where name = 'Nizozemsko – kopce jižního Limburgu' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – kopce jižního Limburgu', 'Jediný kout Nizozemska, kde se opravdu jezdí do kopce: Heuvelland mezi Maastrichtem a Cáchami nabízí úzké silničky mezi hrázděnými statky, sady a vinicemi, stoupání s výhledy do tří zemí a legendární cyklistický Cauberg. Na Vaalserbergu se u Drielandenpuntu potkávají hranice Nizozemska, Belgie a Německa — zároveň nejvyšší bod evropské části země. Cestou zpět vás čeká hradní zřícenina nad Valkenburgem a náměstí Vrijthof v Maastrichtu. Serpentiny jsou krátké, ale šťavnaté; pozor na hejna cyklistů, o víkendech jich tu jsou tisíce. Ideální od jara do podzimu, silnice jsou úzké a po dešti kluzké od bláta z polí.', 'loop', 95, 180, 'medium',
     '[{"lat": 50.8490, "lng": 5.6880, "label": "Start: Maastricht"}, {"lat": 50.7540, "lng": 6.0210, "label": "Drielandenpunt (Vaals)"}, {"lat": 50.7710, "lng": 5.9130, "label": "Epen"}, {"lat": 50.8140, "lng": 5.8900, "label": "Gulpen"}, {"lat": 50.8620, "lng": 5.8320, "label": "Valkenburg"}, {"lat": 50.8490, "lng": 5.6880, "label": "Cíl: Maastricht"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.8490,5.6880&destination=50.8490,5.6880&travelmode=driving&waypoints=50.7540,6.0210%7C50.7710,5.9130%7C50.8140,5.8900%7C50.8620,5.8320', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vrijthof%20Maastricht.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Drielandenpunt.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Epen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gulpen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kasteel%20Valkenburg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cauberg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vrijthof%20Maastricht.jpg"}'::text[], '{"Drielandenpunt (Vaals)","Epen – hrázděný Heuvelland","Restaurace: Gulpener Brouwlokaal (Gulpen)","Kasteel Valkenburg","Cauberg","Maastricht – Vrijthof"}'::text[], '{"NL"}'::text[], false, 4540, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Drielandenpunt (Vaals)', 'Trojmezí Nizozemska, Belgie a Německa na vrcholu Vaalserbergu (322 m) — nejvyšší bod evropského Nizozemska. Stoupání z Vaalsu je nejdelší souvislé „horské" stoupání v zemi a motorkáři si ho užívají po obou stranách hranice. Nahoře rozhledna, labyrint a výhled do tří států.', 50.7540, 6.0210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Drielandenpunt.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Drielandenpunt.jpg"}'::text[], 0),
    (v_route, 'Epen – hrázděný Heuvelland', 'Vesnička v nejjižnějším cípu země, obklopená loukami, potoky a hrázděnými statky — krajina, která připomíná spíš Ardeny než Holandsko. Silničky kolem Epenu patří k nejhezčím v Limburgu. Vyhlídka nad údolím říčky Geul je povinná fotozastávka.', 50.7710, 5.9130, 'https://commons.wikimedia.org/wiki/Special:FilePath/Epen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Epen.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Gulpener Brouwlokaal (Gulpen)', 'Podniková restaurace nezávislého pivovaru Gulpener přímo na náměstí v Gulpenu — čepují tu celou paletu limburských piv a vaří poctivou regionální kuchyni ze surovin od okolních farmářů. Skvělé místo na oběd v půlce okruhu. Pro řidiče mají i nealko speciály.', 50.8140, 5.8900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gulpen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gulpen.jpg"}'::text[], 2),
    (v_route, 'Kasteel Valkenburg', 'Jediná výšinná hradní zřícenina v Nizozemsku, trůnící na skále nad lázeňským Valkenburgem. Pod hradem se táhnou kilometry chodeb v pískovcových lomech Fluweelengrot. Městečko pod hradem žije turistikou — kavárny na každém rohu.', 50.8620, 5.8320, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kasteel%20Valkenburg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kasteel%20Valkenburg.jpg"}'::text[], 3),
    (v_route, 'Cauberg', 'Nejslavnější kopec nizozemské cyklistiky — cíl klasiky Amstel Gold Race a několika mistrovství světa. Krátké prudké stoupání z centra Valkenburgu si vychutnáte i na motorce, jen s respektem k cyklistům, kteří si tu dávají osobáky. Nahoře stojí lázeňský park a kasino.', 50.8590, 5.8210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cauberg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cauberg.jpg"}'::text[], 4),
    (v_route, 'Maastricht – Vrijthof', 'Nejstarší město Nizozemska a jeho nejslavnější náměstí s dvojicí kostelů a řadou kaváren, kde končí každá pořádná limburská vyjížďka. Anděl Páně tu zvoní nad terasami plnými života. Projděte si i středověkou bránu Helpoort a nábřeží Maasy.', 50.8490, 5.6880, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vrijthof%20Maastricht.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vrijthof%20Maastricht.jpg"}'::text[], 5);

  -- Nizozemsko – pobřeží Waddenzee
  delete from public.routes where name = 'Nizozemsko – pobřeží Waddenzee' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – pobřeží Waddenzee', 'Jízda podél Waddenského moře, jediné nizozemské přírodní památky UNESCO: po vnitřní straně mořských hrází vedou prázdné silničky, za nimi se při odlivu obnažují kilometry bahnitých plání plných ptactva. Trasa spojuje přístavní Harlingen, nejstarší funkční planetárium světa ve Franekeru a poutní Dokkum s národním parkem Lauwersmeer. Závěr patří rybářskému Zoutkampu a Pieterburenu se známou tulení záchrannou stanicí. Rovinatá, meditativní jízda s nekonečným horizontem — tohle je Nizozemsko bez turistů. Kdykoli od jara do podzimu; na hrázích fouká a v ptačí sezóně platí místy omezení rychlosti.', 'poi', 115, 185, 'easy',
     '[{"lat": 53.1740, "lng": 5.4210, "label": "Start: Harlingen"}, {"lat": 53.1870, "lng": 5.5420, "label": "Franeker"}, {"lat": 53.3260, "lng": 5.9990, "label": "Dokkum"}, {"lat": 53.4000, "lng": 6.2200, "label": "Lauwersoog"}, {"lat": 53.3370, "lng": 6.2940, "label": "Zoutkamp"}, {"lat": 53.3960, "lng": 6.4400, "label": "Cíl: Pieterburen"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=53.1740,5.4210&destination=53.3960,6.4400&travelmode=driving&waypoints=53.1870,5.5420%7C53.3260,5.9990%7C53.4000,6.2200%7C53.3370,6.2940', 'https://commons.wikimedia.org/wiki/Special:FilePath/Harlingen%20haven.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Harlingen%20haven.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Eise%20Eisinga%20Planetarium.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dokkum.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lauwersmeer.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zoutkamp.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pieterburen.jpg"}'::text[], '{"Harlingen","Franeker – planetárium Eise Eisingy","Dokkum","Nationaal Park Lauwersmeer","Zoutkamp","Pieterburen"}'::text[], '{"NL"}'::text[], false, 4550, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Harlingen', 'Jediný fríský námořní přístav — odsud vyplouvají trajekty na ostrovy Vlieland a Terschelling. Nábřeží Noorderhaven lemují kapitánské domy a stěžně historických plachetnic. Nadechněte se moře, než vyrazíte po hrázi na východ.', 53.1740, 5.4210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Harlingen%20haven.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Harlingen%20haven.jpg"}'::text[], 0),
    (v_route, 'Franeker – planetárium Eise Eisingy', 'Nejstarší dosud funkční planetárium světa (1781), které si vlnař Eise Eisinga postavil ve vlastním obýváku — oběžnice se otáčejí na stropě dodnes a od roku 2023 je památkou UNESCO. Geniální stroj poháněný jediným kyvadlem. Krátká odbočka, kterou si nesmíte nechat ujít.', 53.1870, 5.5420, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eise%20Eisinga%20Planetarium.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eise%20Eisinga%20Planetarium.jpg"}'::text[], 1),
    (v_route, 'Dokkum', 'Nejsevernější z jedenácti fríských měst, kde byl roku 754 zabit svatý Bonifác. Hvězdicové hradby s větrnými mlýny na bastionech obepínají kompaktní historické jádro. Ideální zastávka na kávu v půlce trasy.', 53.3260, 5.9990, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dokkum.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dokkum.jpg"}'::text[], 2),
    (v_route, 'Nationaal Park Lauwersmeer', 'Bývalý mořský záliv, po přehrazení v roce 1969 proměněný v jezerní divočinu — dnes ptačí ráj a park tmavé oblohy. Silnice po hrázi kolem přístavu Lauwersoog odděluje sladkou a slanou vodu. Na obzoru se rýsuje ostrov Schiermonnikoog.', 53.4000, 6.2200, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lauwersmeer.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lauwersmeer.jpg"}'::text[], 3),
    (v_route, 'Zoutkamp', 'Bývalá rybářská vesnice s flotilou krevetových kutrů a pestrobarevnými domky u přístavu. Místní uzené krevety jsou pojem — kupte si kornout přímo od rybáře. Groningenský venkov v nejryzejší podobě.', 53.3370, 6.2940, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zoutkamp.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zoutkamp.jpg"}'::text[], 4),
    (v_route, 'Pieterburen', 'Vesnička proslulá záchrannou stanicí pro tuleně ze sousedního Waddenského moře — uzdravené kusy se tu vypouštějí zpátky. Začíná zde i slavná pouť bahnem wadlopen, chůze po mořském dně při odlivu. Důstojný cíl trasy na konci světa.', 53.3960, 6.4400, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pieterburen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pieterburen.jpg"}'::text[], 5);

  -- Nizozemsko – ostrov Texel
  delete from public.routes where name = 'Nizozemsko – ostrov Texel' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – ostrov Texel', 'Největší z Waddenských ostrovů je stvořený pro jednodenní ostrovní výpravu: z Den Helderu vás dvacetiminutový trajekt TESO přepraví i s motorkou a pak už následují prázdné silničky mezi ovčími pastvinami, dunami a majáky. Trasa vede přes hlavní městečko Den Burg a rybářský Oudeschild podél východního pobřeží až k červenému majáku Eierland na severním cípu. Národní park Duinen van Texel s centrem Ecomare ukazuje tuleně i ptačí kolonie. Ostrovní tempo je pomalé a předjíždění ovcí patří ke koloritu — spěch nechte na pevnině. Nejlépe od dubna do října; trajekty jezdí celoročně každou hodinu, v létě častěji.', 'poi', 60, 150, 'easy',
     '[{"lat": 52.9600, "lng": 4.7910, "label": "Start: Den Helder (trajekt)"}, {"lat": 53.0540, "lng": 4.7970, "label": "Den Burg"}, {"lat": 53.0390, "lng": 4.8500, "label": "Oudeschild"}, {"lat": 53.0930, "lng": 4.7560, "label": "Ecomare"}, {"lat": 53.1790, "lng": 4.8550, "label": "Cíl: maják Eierland"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=52.9600,4.7910&destination=53.1790,4.8550&travelmode=driving&waypoints=53.0540,4.7970%7C53.0390,4.8500%7C53.0930,4.7560', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Eierland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Den%20Burg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Oudeschild.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ecomare.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Duinen%20van%20Texel.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Eierland.jpg"}'::text[], '{"Restaurace: De Twaalf Balcken (Den Burg)","Oudeschild – muzeum Kaap Skil","Ecomare","Nationaal Park Duinen van Texel","Maják Eierland"}'::text[], '{"NL"}'::text[], false, 4560, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Restaurace: De Twaalf Balcken (Den Burg)', 'Historická hospoda s dvanácti trámy v centru Den Burgu, kde se schází ostrovani i výletníci. Na talíři texelské jehněčí a ryby z Waddenského moře, k tomu místní pivo z ostrovního pivovaru. Poctivý ostrovní oběd hned po trajektu.', 53.0540, 4.7970, 'https://commons.wikimedia.org/wiki/Special:FilePath/Den%20Burg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Den%20Burg.jpg"}'::text[], 0),
    (v_route, 'Oudeschild – muzeum Kaap Skil', 'Rybářský přístav s muzeem námořních nálezů — texelská rejda bývala kotvištěm lodí Východoindické společnosti a mořské dno kolem je archiv vraků. Maketa vesnice, mlýn a kutry přímo za oknem. U přístavu se suší sítě a smaží ryby.', 53.0390, 4.8500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Oudeschild.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Oudeschild.jpg"}'::text[], 1),
    (v_route, 'Ecomare', 'Záchranná stanice tuleňů a centrum přírody Waddenského moře na kraji dun u De Koog. Krmení tuleňů je zážitek pro každého, expozice vysvětlí, proč je wadden UNESCO. Odtud vede pěšina rovnou do dun národního parku.', 53.0930, 4.7560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ecomare.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ecomare.jpg"}'::text[], 2),
    (v_route, 'Nationaal Park Duinen van Texel', 'Pás dun, vřesovišť a slaných luk podél celého západního pobřeží ostrova. Silnička mezi De Koog a severním cípem patří k nejhezčím úsekům trasy — duny po levici, pastviny po pravici. Na jaře tu hnízdí kolonie racků a rybáků.', 53.1000, 4.7660, 'https://commons.wikimedia.org/wiki/Special:FilePath/Duinen%20van%20Texel.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duinen%20van%20Texel.jpg"}'::text[], 3),
    (v_route, 'Maják Eierland', 'Červený maják z roku 1864 na písečné výspě úplně na severu Texelu — symbol ostrova a cíl trasy. Z ochozu dohlédnete na sousední Vlieland, dole duní příboj Severního moře. Ideální místo na západ slunce před zpátečním trajektem.', 53.1790, 4.8550, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Eierland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Eierland.jpg"}'::text[], 4);

  -- Nizozemsko – tulipánová pole a Zandvoort
  delete from public.routes where name = 'Nizozemsko – tulipánová pole a Zandvoort' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – tulipánová pole a Zandvoort', 'Krátký okruh s největší barevnou koncentrací na světě: od poloviny dubna do začátku května kvetou v Bollenstreeku mezi Haarlemem a Leidenem miliony tulipánů a silničky mezi lány připomínají jízdu obřím pruhovaným kobercem. K tomu legendární okruh Zandvoort v dunách, kde se jezdí Velká cena Nizozemska F1, přímořský Noordwijk s majákem a květinový park Keukenhof. Návrat vede přes Haarlem s grandiózním náměstím u katedrály. Mimo tulipánovou sezónu je trasa příjemnou přímořskou vyjížďkou dunami. V dubnu počítejte s hustým provozem kolem Keukenhofu — vyjeďte brzy ráno, kdy jsou pole nejkrásnější a silnice prázdné.', 'loop', 85, 160, 'easy',
     '[{"lat": 52.3810, "lng": 4.6360, "label": "Start: Haarlem"}, {"lat": 52.3888, "lng": 4.5409, "label": "Zandvoort"}, {"lat": 52.2420, "lng": 4.4320, "label": "Noordwijk"}, {"lat": 52.2700, "lng": 4.5460, "label": "Keukenhof"}, {"lat": 52.2580, "lng": 4.5570, "label": "Lisse"}, {"lat": 52.3810, "lng": 4.6360, "label": "Cíl: Haarlem"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=52.3810,4.6360&destination=52.3810,4.6360&travelmode=driving&waypoints=52.3888,4.5409%7C52.2420,4.4320%7C52.2700,4.5460%7C52.2580,4.5570', 'https://commons.wikimedia.org/wiki/Special:FilePath/Keukenhof.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Circuit%20Zandvoort.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Noordwijk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Keukenhof.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bollenvelden%20bij%20Lisse.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grote%20Markt%20Haarlem.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jopenkerk%20Haarlem.jpg"}'::text[], '{"Circuit Zandvoort","Noordwijk – maják","Keukenhof","Tulipánová pole u Lisse","Haarlem – Grote Markt","Restaurace: Jopenkerk (Haarlem)"}'::text[], '{"NL"}'::text[], false, 4570, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Circuit Zandvoort', 'Legendární okruh v dunách u Severního moře, od roku 2021 opět dějiště Velké ceny Nizozemska F1 s klopenou zatáčkou Arie Luyendyk. V kalendáři bývají i motorkářské track days a veřejné jízdy. I bez vjezdu na trať stojí za zastávku — tribuny se zvedají přímo z dun.', 52.3888, 4.5409, 'https://commons.wikimedia.org/wiki/Special:FilePath/Circuit%20Zandvoort.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Circuit%20Zandvoort.jpg"}'::text[], 0),
    (v_route, 'Noordwijk – maják', 'Elegantní přímořské letovisko s bílým majákem a širokou promenádou nad pláží. Silnice sem vede dunovou rezervací — nejhezčí přímořský úsek okruhu. Na boulevardu si dejte čerstvého sledě nebo kibbeling.', 52.2420, 4.4320, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Noordwijk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vuurtoren%20Noordwijk.jpg"}'::text[], 1),
    (v_route, 'Keukenhof', 'Nejslavnější květinový park světa: sedm milionů cibulovin na 32 hektarech, otevřeno jen od poloviny března do poloviny května. Přehlídka toho nejlepšího, co nizozemské šlechtitelství dokáže. Parkování u vstupu, ve špičce přijeďte před desátou.', 52.2700, 4.5460, 'https://commons.wikimedia.org/wiki/Special:FilePath/Keukenhof.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Keukenhof.jpg"}'::text[], 2),
    (v_route, 'Tulipánová pole u Lisse', 'Lány tulipánů, hyacintů a narcisů kolem Lisse jsou v dubnu barevnější než cokoliv, co jste kdy viděli — pruhy červené, žluté a fialové až k obzoru. Polními silničkami se dá mezi lány projíždět, jen nevstupujte do polí. Vůně hyacintů je cítit i přes helmu.', 52.2580, 4.5570, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bollenvelden%20bij%20Lisse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bollenvelden%20bij%20Lisse.jpg"}'::text[], 3),
    (v_route, 'Haarlem – Grote Markt', 'Jedno z nejkrásnějších náměstí Nizozemska pod věží katedrály Sint-Bavo, obklopené renesančními štíty a terasami. Haarlem je menší a klidnější sestra Amsterdamu — atmosféra stejná, davy poloviční. Skvělé místo na závěrečnou kávu.', 52.3810, 4.6360, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grote%20Markt%20Haarlem.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grote%20Markt%20Haarlem.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Jopenkerk (Haarlem)', 'Pivovar a restaurace v odsvěceném kostele z roku 1910 — haarlemská značka Jopen tu vaří piva podle receptur z 15. století a kuchyně k nim ladí menu. Industriálně-gotický interiér s měděnými tanky pod vitrážemi je zážitek sám o sobě. Po vyjížďce ideální tečka, pro jezdce nealko Jopen.', 52.3820, 4.6320, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jopenkerk%20Haarlem.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jopenkerk%20Haarlem.jpg"}'::text[], 5);

  -- Nizozemsko – Waterland a sýrový Edam
  delete from public.routes where name = 'Nizozemsko – Waterland a sýrový Edam' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – Waterland a sýrový Edam', 'Pohlednicové Holandsko na dosah Amsterdamu, ale bez jeho davů: okruh krajinou Waterlandu spojuje bývalý ostrov Marken s dřevěnými domky na kůlech, rybářský Volendam, sýrový Edam a trojici mlýnů u Schermerhornu. Jezdí se po úzkých silničkách na hrázích mezi kanály, kde je člověk pořád pár desítek centimetrů nad vodou. Slavný maják Paard van Marken na východním cípu ostrova je nejfotogeničtější stavba Markermeeru. Trasa je krátká a pohodová, ideální na půlden s dlouhými zastávkami na sýr a uzené úhoře. Celoročně sjízdná; na hrázových silničkách pozor na protijedoucí cyklisty a silný vítr od jezera.', 'loop', 85, 160, 'easy',
     '[{"lat": 52.4570, "lng": 5.0380, "label": "Start: Monnickendam"}, {"lat": 52.4580, "lng": 5.1090, "label": "Marken"}, {"lat": 52.4950, "lng": 5.0700, "label": "Volendam"}, {"lat": 52.5130, "lng": 5.0480, "label": "Edam"}, {"lat": 52.6060, "lng": 4.8890, "label": "Schermerhorn"}, {"lat": 52.4350, "lng": 5.0000, "label": "Broek in Waterland"}, {"lat": 52.4570, "lng": 5.0380, "label": "Cíl: Monnickendam"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=52.4570,5.0380&destination=52.4570,5.0380&travelmode=driving&waypoints=52.4580,5.1090%7C52.4950,5.0700%7C52.5130,5.0480%7C52.6060,4.8890%7C52.4350,5.0000', 'https://commons.wikimedia.org/wiki/Special:FilePath/Paard%20van%20Marken.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Paard%20van%20Marken.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Volendam%20haven.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kaasmarkt%20Edam.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Museummolen%20Schermerhorn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Broek%20in%20Waterland.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Monnickendam.jpg"}'::text[], '{"Marken – Paard van Marken","Volendam","Edam – sýrový trh","Museummolen Schermerhorn","Broek in Waterland","Monnickendam"}'::text[], '{"NL"}'::text[], false, 4580, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Marken – Paard van Marken', 'Bývalý ostrov s dřevěnými domky na kůlech, dnes spojený s pevninou hrází, po které se na motorce krásně jede. Na východním cípu stojí maják Paard van Marken — „markenský kůň" z roku 1839, k němuž vede krátká procházka po hrázi. Vesnice si drží starosvětský ráz včetně krojů při slavnostech.', 52.4580, 5.1090, 'https://commons.wikimedia.org/wiki/Special:FilePath/Paard%20van%20Marken.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Paard%20van%20Marken.jpg"}'::text[], 0),
    (v_route, 'Volendam', 'Nejslavnější rybářská vesnice Nizozemska s přístavní promenádou plnou stánků s uzeným úhořem a sleděm. Turistický ruch k Volendamu patří, ale atmosféra starého přístavu funguje pořád. Ochutnejte paling — uzeného úhoře — přímo u vody.', 52.4950, 5.0700, 'https://commons.wikimedia.org/wiki/Special:FilePath/Volendam%20haven.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Volendam%20haven.jpg"}'::text[], 1),
    (v_route, 'Edam – sýrový trh', 'Městečko, které dalo jméno nejexportovanějšímu sýru světa. V létě se na náměstí u váhy koná tradiční sýrový trh s nosiči a dřevěnými čluny plnými bochníků. Mimo trh je Edam tichý labyrint kanálů, mostků a sýráren s ochutnávkami.', 52.5130, 5.0480, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kaasmarkt%20Edam.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kaasmarkt%20Edam.jpg"}'::text[], 2),
    (v_route, 'Museummolen Schermerhorn', 'Trojice poldrových mlýnů z roku 1635 v řadě u kanálu — jeden slouží jako muzeum, kde uvidíte, jak mlýny přečerpávaly vodu a odvodnily celou Schermer. Mlynářská rodina tu žila mezi převody a lopatkami. Autentičtější mlýnský zážitek než na přeplněných slavných místech.', 52.6060, 4.8890, 'https://commons.wikimedia.org/wiki/Special:FilePath/Museummolen%20Schermerhorn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Museummolen%20Schermerhorn.jpg"}'::text[], 3),
    (v_route, 'Broek in Waterland', 'Vesnice dřevěných domů natřených typickou šedozelenou „broekskou" barvou, se zamrzajícím jezírkem uprostřed. V 17. století tu bohatí amsterdamští kupci stavěli letní sídla. Pět minut zastávky, sto let zpátky v čase.', 52.4350, 5.0000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Broek%20in%20Waterland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Broek%20in%20Waterland.jpg"}'::text[], 4),
    (v_route, 'Monnickendam', 'Přístavní městečko se zvonkohrou ve věži Speeltoren a udírnami ryb u kotviště plachetnic. Menší a klidnější než Volendam, o to autentičtější. Start i cíl okruhu — večer tu u přístavu příjemně posedíte.', 52.4570, 5.0380, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monnickendam.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Monnickendam.jpg"}'::text[], 5);

  -- Nizozemsko – Weerribben-Wieden a hanzovní Kampen
  delete from public.routes where name = 'Nizozemsko – Weerribben-Wieden a hanzovní Kampen' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – Weerribben-Wieden a hanzovní Kampen', 'Okruh největším mokřadem severozápadní Evropy a městy hanzovní slávy: národní park Weerribben-Wieden je bludiště rákosin, kanálů a plovoucích luk, kterým se silnice proplétají po úzkých náspech mezi vodou. Cestou historický přístav Blokzijl se zdymadlem uprostřed náměstí, bývalé hanzovní městečko Vollenhove a monumentální Kampen s branami a věžemi nad řekou IJssel. Start i cíl v Zwolle, jehož gotická brána Sassenpoort patří k nejhezčím v zemi. Rovinatá, ale nesmírně malebná jízda — vodní krajina se mění každým kilometrem. Nejlépe od května do října; v rákosí bývá zrádný boční vítr a silničky jsou úzké, s výhybnami.', 'loop', 120, 190, 'easy',
     '[{"lat": 52.5090, "lng": 6.0950, "label": "Start: Zwolle"}, {"lat": 52.5560, "lng": 5.9110, "label": "Kampen"}, {"lat": 52.6820, "lng": 5.9530, "label": "Vollenhove"}, {"lat": 52.7270, "lng": 5.9600, "label": "Blokzijl"}, {"lat": 52.7810, "lng": 5.9020, "label": "Ossenzijl (Weerribben)"}, {"lat": 52.5090, "lng": 6.0950, "label": "Cíl: Zwolle"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=52.5090,6.0950&destination=52.5090,6.0950&travelmode=driving&waypoints=52.5560,5.9110%7C52.6820,5.9530%7C52.7270,5.9600%7C52.7810,5.9020', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sassenpoort%20Zwolle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Koornmarktspoort%20Kampen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vollenhove.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Blokzijl.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Weerribben.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sassenpoort%20Zwolle.jpg"}'::text[], '{"Kampen – Koornmarktspoort","Vollenhove","Blokzijl","Nationaal Park Weerribben-Wieden","Zwolle – Sassenpoort"}'::text[], '{"NL"}'::text[], false, 4590, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kampen – Koornmarktspoort', 'Hanzovní veterán na břehu IJsselu: panorama věží, tří městských bran a nábřeží patřilo ve středověku k nejbohatším pohledům Evropy. Koornmarktspoort u řeky je nejstarší z bran. Přejezd mostu přes IJssel s výhledem na město je zážitek.', 52.5560, 5.9110, 'https://commons.wikimedia.org/wiki/Special:FilePath/Koornmarktspoort%20Kampen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Koornmarktspoort%20Kampen.jpg"}'::text[], 0),
    (v_route, 'Vollenhove', 'Bývalé „město paláců", kde šlechta stavěla sídla u dnes zaniklého moře Zuiderzee. Přístav, zámecké zahrady a kostely připomínají zašlou slávu. Odtud začíná nejhezčí úsek podél okraje mokřadů.', 52.6820, 5.9530, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vollenhove.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vollenhove.jpg"}'::text[], 1),
    (v_route, 'Blokzijl', 'Miniaturní přístavní město se zdymadlem přímo uprostřed náměstí a domy zlatého věku kolem kotviště. Kdysi rušný přístav Zuiderzee, dnes brána do vodního světa Weerribben. Kavárny u přístavu jsou stvořené pro pauzu.', 52.7270, 5.9600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Blokzijl.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Blokzijl.jpg"}'::text[], 2),
    (v_route, 'Nationaal Park Weerribben-Wieden', 'Největší souvislý rašelinný mokřad severozápadní Evropy, vzniklý staletími těžby rašeliny — dnes ráj vyder, orlovců a černých rybáků. Silnička z Blokzijlu přes Ossenzijl vede přímo skrz rákosové moře. U návštěvnického centra se dá půjčit šlapací člun na rychlou vodní odbočku.', 52.7810, 5.9020, 'https://commons.wikimedia.org/wiki/Special:FilePath/Weerribben.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Weerribben.jpg"}'::text[], 3),
    (v_route, 'Zwolle – Sassenpoort', 'Gotická městská brána z roku 1409 se čtyřmi věžičkami je symbolem hanzovního Zwolle. Historické jádro v hradebním prstenci má hvězdicový půdorys a skvělé podniky na závěrečné jídlo. Důstojné zakončení hanzovního okruhu.', 52.5090, 6.0950, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sassenpoort%20Zwolle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sassenpoort%20Zwolle.jpg"}'::text[], 4);

  -- Nizozemsko – Drenthe a okruh TT Assen
  delete from public.routes where name = 'Nizozemsko – Drenthe a okruh TT Assen' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Nizozemsko – Drenthe a okruh TT Assen', 'Pouť do „katedrály rychlosti": TT Circuit Assen hostí Velkou cenu motocyklů nepřetržitě od roku 1949 a pro každého motorkáře je to svaté místo. Okolní Drenthe k tomu přidává pravěké megality hunebedden, skanzen Orvelte, památník tábora Westerbork a vřesoviště národního parku Dwingelderveld s obřím radioteleskopem. Jezdí se po klidných alejích mezi lesíky a poli — žádný stres, jen čistá pohoda severního Nizozemska. Trasa je ideální na kombinaci s návštěvou závodů nebo track day na okruhu. Celoročně sjízdná, nejhezčí v srpnu, kdy kvetou vřesoviště; kolem závodního víkendu TT na konci června počítejte s plnými silnicemi i hotely.', 'loop', 130, 200, 'easy',
     '[{"lat": 52.9930, "lng": 6.5620, "label": "Start: Assen"}, {"lat": 52.9620, "lng": 6.5230, "label": "TT Circuit Assen"}, {"lat": 52.9160, "lng": 6.6070, "label": "Kamp Westerbork"}, {"lat": 52.8480, "lng": 6.6730, "label": "Orvelte"}, {"lat": 52.9250, "lng": 6.7920, "label": "Borger"}, {"lat": 52.8120, "lng": 6.4180, "label": "Dwingelderveld"}, {"lat": 52.9930, "lng": 6.5620, "label": "Cíl: Assen"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=52.9930,6.5620&destination=52.9930,6.5620&travelmode=driving&waypoints=52.9620,6.5230%7C52.9160,6.6070%7C52.8480,6.6730%7C52.9250,6.7920%7C52.8120,6.4180', 'https://commons.wikimedia.org/wiki/Special:FilePath/TT%20Circuit%20Assen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/TT%20Circuit%20Assen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kamp%20Westerbork.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Orvelte.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hunebed%20D27%20Borger.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dwingelderveld.jpg"}'::text[], '{"TT Circuit Assen","Kamp Westerbork","Orvelte","Hunebedcentrum Borger","Nationaal Park Dwingelderveld"}'::text[], '{"NL"}'::text[], false, 4600, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'TT Circuit Assen', 'Jediný okruh, který hostí motocyklovou Grand Prix bez přerušení od založení šampionátu — Dutch TT je pro motorkáře totéž co Wimbledon pro tenisty. Mimo závodní víkendy fungují track days, vyhlídkové jízdy i prohlídky zázemí. U brány stojí pomník vítězů a fanouškovský obchod.', 52.9620, 6.5230, 'https://commons.wikimedia.org/wiki/Special:FilePath/TT%20Circuit%20Assen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/TT%20Circuit%20Assen.jpg"}'::text[], 0),
    (v_route, 'Kamp Westerbork', 'Památník tranzitního tábora, odkud za okupace odjížděly transporty do vyhlazovacích táborů — mezi deportovanými byla i Anne Franková. Zvednuté koleje památníku patří k nejpůsobivějším pietním místům Evropy. Zastávka, která dá celé vyjížďce hloubku.', 52.9160, 6.6070, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kamp%20Westerbork.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kamp%20Westerbork.jpg"}'::text[], 1),
    (v_route, 'Orvelte', 'Živý skanzen — památkově chráněná vesnice, kde se dodnes normálně žije, ale auta musí zůstat venku. Doškové statky, kovárna, sýrárna a řemeslné dílny podél dlážděné návsi. Motorku zaparkujete na kraji a projdete se stoletím zpět.', 52.8480, 6.6730, 'https://commons.wikimedia.org/wiki/Special:FilePath/Orvelte.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Orvelte.jpg"}'::text[], 2),
    (v_route, 'Hunebedcentrum Borger', 'Největší nizozemský dolmen — hunebed D27 z doby před 5000 lety — leží hned u muzea megalitické kultury. Obří balvany sem dotlačil ledovec ze Skandinávie, hroby z nich poskládali první zemědělci Evropy. Podél trasy potkáte hunebedů víc, Drenthe jich má přes padesát.', 52.9250, 6.7920, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hunebed%20D27%20Borger.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hunebed%20D27%20Borger.jpg"}'::text[], 3),
    (v_route, 'Nationaal Park Dwingelderveld', 'Největší vlhké vřesoviště západní Evropy s bludnými balvany, jalovci a stády ovcí — v srpnu celé fialové. Nad krajinou se otáčí historický radioteleskop, který kdysi jako první zmapoval spirální ramena Galaxie. Tichá silnička po okraji parku je krásné zakončení okruhu.', 52.8120, 6.4180, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dwingelderveld.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dwingelderveld.jpg"}'::text[], 4);

end $$;
