-- ==================================================================
-- MotoGo24 — KATALOG BODŮ ZÁJMU: DÁVKA 1 (flagship CZ/SK/PL/AT)
-- Ověřené souřadnice + vícejazyčné popisy (cs kanonicky + en/de/pl/nl/es/fr/uk
-- v translations). Kategorie je EXPLICITNÍ → filtr je 100% spolehlivý
-- (hrad = 'castle', přehrada/jezero = 'water', … nikdy se neplete do „jídla").
-- Idempotentní: mazání dle (name, source) před vložením.
-- Další dávky přidávej stejným vzorem (viz TRASY / POI přehled).
-- ==================================================================

delete from public.points_of_interest where source = 'curated-batch1';

insert into public.points_of_interest
  (category, name, description, lat, lng, country, source, sort_order, translations)
values
-- == VODA: přehrady, jezera, velké rybníky =======================
('water', 'Lipno – přehrada a jezero',
 'Největší vodní plocha v Česku na Šumavě; okolní silnice nabízejí plynulé zatáčky a výhledy na hladinu.',
 48.6408, 14.2233, 'CZ', 'curated-batch1', 10,
 '{"en":{"name":"Lipno Reservoir & Lake","description":"Czechia''s largest body of water in the Šumava mountains; the shoreline roads offer flowing curves and lake views."},
   "de":{"name":"Lipno – Stausee","description":"Tschechiens größte Wasserfläche im Böhmerwald; die Uferstraßen bieten fließende Kurven und Seeblicke."},
   "pl":{"name":"Zbiornik Lipno","description":"Największy akwen w Czechach na Szumawie; nadbrzeżne drogi kuszą płynnymi zakrętami i widokami na jezioro."},
   "nl":{"name":"Stuwmeer Lipno","description":"Het grootste water van Tsjechië in de Šumava; de oeverwegen bieden vloeiende bochten en uitzicht op het meer."},
   "es":{"name":"Embalse de Lipno","description":"La mayor masa de agua de Chequia en la Selva de Bohemia; las carreteras de la orilla regalan curvas fluidas y vistas al lago."},
   "fr":{"name":"Lac de barrage de Lipno","description":"Le plus grand plan d''eau de Tchéquie dans la Forêt de Bohême ; les routes du rivage offrent des virages fluides et des vues sur le lac."},
   "uk":{"name":"Ліпно – водосховище","description":"Найбільша водойма Чехії в Шумаві; прибережні дороги дарують плавні повороти й краєвиди на озеро."}}'::jsonb),

('water', 'Orlická přehrada',
 'Rozlehlá přehrada na Vltavě sevřená lesnatými stráněmi; oblíbený cíl vyjížděk středními Čechami.',
 49.4319, 14.1683, 'CZ', 'curated-batch1', 11,
 '{"en":{"name":"Orlík Reservoir","description":"A sprawling Vltava dam hemmed by wooded slopes; a favourite ride destination in central Bohemia."},
   "de":{"name":"Stausee Orlík","description":"Ein weitläufiger Moldaustausee zwischen bewaldeten Hängen; ein beliebtes Ausflugsziel in Mittelböhmen."},
   "pl":{"name":"Zbiornik Orlík","description":"Rozległy zbiornik na Wełtawie wśród zalesionych zboczy; ulubiony cel wypraw po środkowych Czechach."},
   "nl":{"name":"Stuwmeer Orlík","description":"Een uitgestrekt Moldau-stuwmeer tussen beboste hellingen; een geliefd ritdoel in Midden-Bohemen."},
   "es":{"name":"Embalse de Orlík","description":"Un extenso embalse del Moldava entre laderas boscosas; destino favorito para rutas por Bohemia central."},
   "fr":{"name":"Lac de barrage d''Orlík","description":"Un vaste barrage sur la Vltava entre des coteaux boisés ; destination prisée en Bohême centrale."},
   "uk":{"name":"Орлицьке водосховище","description":"Велике водосховище на Влтаві серед лісистих схилів; улюблена мета поїздок центральною Богемією."}}'::jsonb),

('water', 'Máchovo jezero',
 'Malebné jezero u Doksů s písčitými plážemi a hradem Bezděz na obzoru.',
 50.5883, 14.6466, 'CZ', 'curated-batch1', 12,
 '{"en":{"name":"Mácha Lake","description":"A picturesque lake near Doksy with sandy beaches and Bezděz castle on the horizon."},
   "de":{"name":"Machasee","description":"Ein malerischer See bei Doksy mit Sandstränden und der Burg Bösig am Horizont."},
   "pl":{"name":"Jezioro Machy","description":"Malownicze jezioro koło Doks z piaszczystymi plażami i zamkiem Bezděz na horyzoncie."},
   "nl":{"name":"Máchameer","description":"Een schilderachtig meer bij Doksy met zandstranden en kasteel Bezděz aan de horizon."},
   "es":{"name":"Lago de Mácha","description":"Un lago pintoresco junto a Doksy con playas de arena y el castillo de Bezděz en el horizonte."},
   "fr":{"name":"Lac de Mácha","description":"Un lac pittoresque près de Doksy avec des plages de sable et le château de Bezděz à l''horizon."},
   "uk":{"name":"Махове озеро","description":"Мальовниче озеро біля Докси з піщаними пляжами та замком Бездєз на обрії."}}'::jsonb),

('water', 'Oravská priehrada',
 'Rozsáhlá horská přehrada na severu Slovenska s ostrovem Slanica; skvělá zastávka při cestě do Tater.',
 49.4200, 19.5200, 'SK', 'curated-batch1', 13,
 '{"en":{"name":"Orava Reservoir","description":"A vast mountain reservoir in northern Slovakia with Slanica island; a great stop en route to the Tatras."},
   "de":{"name":"Stausee Orava","description":"Ein weitläufiger Bergstausee im Norden der Slowakei mit der Insel Slanica; ein toller Halt auf dem Weg in die Tatra."},
   "pl":{"name":"Jezioro Orawskie","description":"Rozległy górski zbiornik na północy Słowacji z wyspą Slanica; świetny przystanek w drodze w Tatry."},
   "nl":{"name":"Stuwmeer Orava","description":"Een uitgestrekt bergstuwmeer in Noord-Slowakije met het eiland Slanica; een mooie stop op weg naar de Tatra."},
   "es":{"name":"Embalse de Orava","description":"Un vasto embalse de montaña en el norte de Eslovaquia con la isla Slanica; gran parada camino de los Tatras."},
   "fr":{"name":"Lac de barrage d''Orava","description":"Un vaste réservoir de montagne au nord de la Slovaquie avec l''île de Slanica ; belle halte vers les Tatras."},
   "uk":{"name":"Оравське водосховище","description":"Велике гірське водосховище на півночі Словаччини з островом Сланиця; чудова зупинка дорогою в Татри."}}'::jsonb),

('water', 'Jezioro Solińskie (zapora Solina)',
 'Největší polská přehrada v Bieszczadech s monumentální hrází a klikatými horskými silnicemi.',
 49.3975, 22.4569, 'PL', 'curated-batch1', 14,
 '{"en":{"name":"Lake Solina (Solina Dam)","description":"Poland''s largest reservoir in the Bieszczady with a monumental dam and winding mountain roads."},
   "de":{"name":"Solina-See (Talsperre Solina)","description":"Polens größter Stausee im Bieszczady-Gebirge mit monumentaler Staumauer und kurvigen Bergstraßen."},
   "pl":{"name":"Jezioro Solińskie (zapora Solina)","description":"Największy zbiornik w Polsce w Bieszczadach z monumentalną zaporą i krętymi górskimi drogami."},
   "nl":{"name":"Solina-meer (stuwdam Solina)","description":"Polens grootste stuwmeer in de Bieszczady met een monumentale dam en kronkelende bergwegen."},
   "es":{"name":"Lago Solina (presa de Solina)","description":"El mayor embalse de Polonia en los Bieszczady, con una presa monumental y sinuosas carreteras de montaña."},
   "fr":{"name":"Lac de Solina (barrage de Solina)","description":"Le plus grand réservoir de Pologne dans les Bieszczady, avec un barrage monumental et des routes de montagne sinueuses."},
   "uk":{"name":"Озеро Соліна (гребля Соліна)","description":"Найбільше водосховище Польщі в Бещадах з монументальною греблею та звивистими гірськими дорогами."}}'::jsonb),

('water', 'Hallstätter See',
 'Alpské jezero v rakouském Solné komoře pod horami; jedna z nejfotogeničtějších zastávek regionu.',
 47.5622, 13.6493, 'AT', 'curated-batch1', 15,
 '{"en":{"name":"Lake Hallstatt","description":"An Alpine lake in Austria''s Salzkammergut beneath the peaks; one of the region''s most photogenic stops."},
   "de":{"name":"Hallstätter See","description":"Ein Alpensee im österreichischen Salzkammergut unter den Bergen; einer der fotogensten Stopps der Region."},
   "pl":{"name":"Jezioro Hallstätter","description":"Alpejskie jezioro w austriackim Salzkammergut u stóp gór; jeden z najbardziej fotogenicznych przystanków regionu."},
   "nl":{"name":"Hallstätter See","description":"Een Alpenmeer in het Oostenrijkse Salzkammergut onder de bergen; een van de fotogeniekste stops van de regio."},
   "es":{"name":"Lago de Hallstatt","description":"Un lago alpino en el Salzkammergut austriaco bajo las cumbres; una de las paradas más fotogénicas de la región."},
   "fr":{"name":"Lac de Hallstatt","description":"Un lac alpin dans le Salzkammergut autrichien au pied des sommets ; l''un des arrêts les plus photogéniques de la région."},
   "uk":{"name":"Гальштатське озеро","description":"Альпійське озеро в австрійському Зальцкаммергуті під вершинами; одна з найфотогенічніших зупинок регіону."}}'::jsonb),

-- == HRADY A ZÁMKY ===============================================
('castle', 'Hrad Karlštejn',
 'Slavný gotický hrad Karla IV. nad údolím Berounky; ikonická zastávka kousek od Prahy.',
 49.9395, 14.1881, 'CZ', 'curated-batch1', 20,
 '{"en":{"name":"Karlštejn Castle","description":"Charles IV''s famous Gothic castle above the Berounka valley; an iconic stop near Prague."},
   "de":{"name":"Burg Karlstein","description":"Die berühmte gotische Burg Karls IV. über dem Berounka-Tal; ein ikonischer Halt nahe Prag."},
   "pl":{"name":"Zamek Karlštejn","description":"Słynny gotycki zamek Karola IV nad doliną Berounki; kultowy przystanek niedaleko Pragi."},
   "nl":{"name":"Kasteel Karlštejn","description":"De beroemde gotische burcht van Karel IV boven het Berounka-dal; een iconische stop bij Praag."},
   "es":{"name":"Castillo de Karlštejn","description":"El famoso castillo gótico de Carlos IV sobre el valle del Berounka; parada icónica cerca de Praga."},
   "fr":{"name":"Château de Karlštejn","description":"Le célèbre château gothique de Charles IV au-dessus de la vallée de la Berounka ; arrêt emblématique près de Prague."},
   "uk":{"name":"Замок Карлштейн","description":"Знаменитий готичний замок Карла IV над долиною Бероунки; культова зупинка неподалік Праги."}}'::jsonb),

('castle', 'Zámek Hluboká nad Vltavou',
 'Romantický novogotický zámek nad Vltavou inspirovaný anglickým Windsorem; skvost jižních Čech.',
 49.0508, 14.4419, 'CZ', 'curated-batch1', 21,
 '{"en":{"name":"Hluboká Chateau","description":"A romantic neo-Gothic chateau above the Vltava inspired by Windsor; a gem of South Bohemia."},
   "de":{"name":"Schloss Frauenberg (Hluboká)","description":"Ein romantisches neugotisches Schloss über der Moldau nach dem Vorbild von Windsor; ein Juwel Südböhmens."},
   "pl":{"name":"Zamek Hluboká nad Wełtawą","description":"Romantyczny neogotycki pałac nad Wełtawą wzorowany na Windsorze; perła południowych Czech."},
   "nl":{"name":"Kasteel Hluboká","description":"Een romantisch neogotisch kasteel boven de Moldau, geïnspireerd op Windsor; een parel van Zuid-Bohemen."},
   "es":{"name":"Castillo de Hluboká","description":"Un romántico palacio neogótico sobre el Moldava inspirado en Windsor; joya de Bohemia del Sur."},
   "fr":{"name":"Château de Hluboká","description":"Un romantique château néogothique au-dessus de la Vltava inspiré de Windsor ; joyau de la Bohême du Sud."},
   "uk":{"name":"Замок Глибока-над-Влтавою","description":"Романтичний неоготичний замок над Влтавою в стилі Віндзора; перлина Південної Богемії."}}'::jsonb),

('castle', 'Bojnický zámok',
 'Pohádkový romantický zámek na Slovensku obklopený parkem; jeden z nejnavštěvovanějších v zemi.',
 48.7803, 18.5787, 'SK', 'curated-batch1', 22,
 '{"en":{"name":"Bojnice Castle","description":"A fairy-tale romantic castle in Slovakia set in a park; one of the country''s most visited sights."},
   "de":{"name":"Schloss Bojnice","description":"Ein märchenhaftes romantisches Schloss in der Slowakei inmitten eines Parks; eines der meistbesuchten des Landes."},
   "pl":{"name":"Zamek w Bojnicach","description":"Bajkowy romantyczny zamek na Słowacji otoczony parkiem; jeden z najczęściej odwiedzanych w kraju."},
   "nl":{"name":"Kasteel Bojnice","description":"Een sprookjesachtig romantisch kasteel in Slowakije in een park; een van de best bezochte van het land."},
   "es":{"name":"Castillo de Bojnice","description":"Un castillo romántico de cuento en Eslovaquia rodeado de un parque; uno de los más visitados del país."},
   "fr":{"name":"Château de Bojnice","description":"Un château romantique de conte de fées en Slovaquie entouré d''un parc ; l''un des plus visités du pays."},
   "uk":{"name":"Бойницький замок","description":"Казковий романтичний замок у Словаччині серед парку; один із найвідвідуваніших у країні."}}'::jsonb),

('castle', 'Zamek w Malborku',
 'Největší cihlový hrad na světě, sídlo řádu německých rytířů a památka UNESCO na severu Polska.',
 54.0399, 19.0279, 'PL', 'curated-batch1', 23,
 '{"en":{"name":"Malbork Castle","description":"The world''s largest brick castle, seat of the Teutonic Order and a UNESCO site in northern Poland."},
   "de":{"name":"Marienburg (Malbork)","description":"Die größte Backsteinburg der Welt, Sitz des Deutschen Ordens und UNESCO-Welterbe im Norden Polens."},
   "pl":{"name":"Zamek w Malborku","description":"Największy ceglany zamek na świecie, siedziba zakonu krzyżackiego i obiekt UNESCO na północy Polski."},
   "nl":{"name":"Kasteel Malbork","description":"Het grootste bakstenen kasteel ter wereld, zetel van de Duitse Orde en UNESCO-erfgoed in Noord-Polen."},
   "es":{"name":"Castillo de Malbork","description":"El mayor castillo de ladrillo del mundo, sede de la Orden Teutónica y sitio UNESCO en el norte de Polonia."},
   "fr":{"name":"Château de Malbork","description":"Le plus grand château en briques du monde, siège de l''ordre Teutonique et site UNESCO au nord de la Pologne."},
   "uk":{"name":"Замок у Мальборку","description":"Найбільший цегляний замок світу, резиденція Тевтонського ордену та об''єкт ЮНЕСКО на півночі Польщі."}}'::jsonb),

('castle', 'Festung Hohensalzburg',
 'Mohutná středověká pevnost nad Salcburkem s panoramatem Alp; jeden z nejzachovalejších hradů Evropy.',
 47.7949, 13.0477, 'AT', 'curated-batch1', 24,
 '{"en":{"name":"Hohensalzburg Fortress","description":"A mighty medieval fortress above Salzburg with Alpine panoramas; one of Europe''s best-preserved castles."},
   "de":{"name":"Festung Hohensalzburg","description":"Eine mächtige mittelalterliche Festung über Salzburg mit Alpenpanorama; eine der besterhaltenen Burgen Europas."},
   "pl":{"name":"Twierdza Hohensalzburg","description":"Potężna średniowieczna twierdza nad Salzburgiem z panoramą Alp; jeden z najlepiej zachowanych zamków Europy."},
   "nl":{"name":"Vesting Hohensalzburg","description":"Een machtige middeleeuwse vesting boven Salzburg met Alpenpanorama; een van de best bewaarde burchten van Europa."},
   "es":{"name":"Fortaleza de Hohensalzburg","description":"Una poderosa fortaleza medieval sobre Salzburgo con panorámicas alpinas; uno de los castillos mejor conservados de Europa."},
   "fr":{"name":"Forteresse de Hohensalzburg","description":"Une puissante forteresse médiévale au-dessus de Salzbourg avec panorama alpin ; l''un des châteaux les mieux conservés d''Europe."},
   "uk":{"name":"Фортеця Гогензальцбург","description":"Могутня середньовічна фортеця над Зальцбургом з панорамою Альп; одна з найкраще збережених у Європі."}}'::jsonb),

-- == ROZHLEDNY A VYHLÍDKY ========================================
('lookout', 'Ještěd',
 'Ikonická horská vysílač-hotel nad Libercem s kruhovým výhledem na severní Čechy.',
 50.7328, 14.9849, 'CZ', 'curated-batch1', 30,
 '{"en":{"name":"Ještěd","description":"An iconic mountain tower-hotel above Liberec with a 360° view over northern Bohemia."},
   "de":{"name":"Ještěd (Jeschken)","description":"Ein ikonischer Bergturm mit Hotel über Liberec und Rundblick über Nordböhmen."},
   "pl":{"name":"Jesztied","description":"Kultowa górska wieża-hotel nad Libercem z panoramą północnych Czech."},
   "nl":{"name":"Ještěd","description":"Een iconische bergtoren met hotel boven Liberec en rondzicht over Noord-Bohemen."},
   "es":{"name":"Ještěd","description":"Una icónica torre-hotel de montaña sobre Liberec con vistas de 360° del norte de Bohemia."},
   "fr":{"name":"Ještěd","description":"Une tour-hôtel de montagne emblématique au-dessus de Liberec, avec vue à 360° sur la Bohême du Nord."},
   "uk":{"name":"Єштєд","description":"Культова гірська вежа-готель над Ліберцем з круговим краєвидом на північ Чехії."}}'::jsonb),

('lookout', 'Rozhledna Kleť',
 'Nejstarší kamenná rozhledna v Česku na vrcholu Kleti; za jasného dne dohlédnete až na Alpy.',
 48.8635, 14.2861, 'CZ', 'curated-batch1', 31,
 '{"en":{"name":"Kleť Lookout Tower","description":"Czechia''s oldest stone lookout tower atop Kleť; on a clear day you can see the Alps."},
   "de":{"name":"Aussichtsturm Kleť","description":"Der älteste steinerne Aussichtsturm Tschechiens auf dem Kleť; bei klarem Wetter bis zu den Alpen."},
   "pl":{"name":"Wieża widokowa Kleť","description":"Najstarsza kamienna wieża widokowa w Czechach na szczycie Kleť; w pogodny dzień widać Alpy."},
   "nl":{"name":"Uitkijktoren Kleť","description":"De oudste stenen uitkijktoren van Tsjechië op de Kleť; op een heldere dag zie je de Alpen."},
   "es":{"name":"Mirador de Kleť","description":"La torre-mirador de piedra más antigua de Chequia en la cima de Kleť; en un día claro se ven los Alpes."},
   "fr":{"name":"Tour panoramique de Kleť","description":"La plus ancienne tour panoramique en pierre de Tchéquie au sommet du Kleť ; par temps clair, on voit les Alpes."},
   "uk":{"name":"Оглядова вежа Клеть","description":"Найстаріша кам''яна оглядова вежа Чехії на вершині Клеть; ясного дня видно Альпи."}}'::jsonb),

('lookout', 'Pyramidenkogel',
 'Nejvyšší dřevěná rozhledna světa nad jezerem Wörthersee v Korutanech s tobogánem dolů.',
 46.6086, 14.1300, 'AT', 'curated-batch1', 32,
 '{"en":{"name":"Pyramidenkogel","description":"The world''s tallest wooden tower above Lake Wörthersee in Carinthia, with a slide back down."},
   "de":{"name":"Pyramidenkogel","description":"Der höchste Holzaussichtsturm der Welt über dem Wörthersee in Kärnten, mit Rutsche nach unten."},
   "pl":{"name":"Pyramidenkogel","description":"Najwyższa drewniana wieża widokowa świata nad jeziorem Wörthersee w Karyntii, ze zjeżdżalnią w dół."},
   "nl":{"name":"Pyramidenkogel","description":"De hoogste houten uitkijktoren ter wereld boven de Wörthersee in Karinthië, met een glijbaan naar beneden."},
   "es":{"name":"Pyramidenkogel","description":"La torre-mirador de madera más alta del mundo sobre el lago Wörthersee en Carintia, con tobogán de bajada."},
   "fr":{"name":"Pyramidenkogel","description":"La plus haute tour panoramique en bois du monde au-dessus du Wörthersee en Carinthie, avec toboggan pour redescendre."},
   "uk":{"name":"Пірамідекогель","description":"Найвища дерев''яна оглядова вежа світу над озером Вертерзе в Каринтії, зі спуском-гіркою вниз."}}'::jsonb),

-- == PAMÁTKY =====================================================
('sights', 'Kutná Hora – chrám sv. Barbory',
 'Skvostná gotická katedrála zapsaná v UNESCO, symbol stříbrného bohatství středověké Kutné Hory.',
 49.9448, 15.2634, 'CZ', 'curated-batch1', 40,
 '{"en":{"name":"Kutná Hora – St. Barbara''s Church","description":"A magnificent Gothic UNESCO cathedral, symbol of medieval Kutná Hora''s silver wealth."},
   "de":{"name":"Kuttenberg – St.-Barbara-Kirche","description":"Eine prächtige gotische UNESCO-Kathedrale, Symbol des mittelalterlichen Silberreichtums von Kutná Hora."},
   "pl":{"name":"Kutná Hora – kościół św. Barbary","description":"Wspaniała gotycka katedra z listy UNESCO, symbol srebrnego bogactwa średniowiecznej Kutnej Hory."},
   "nl":{"name":"Kutná Hora – Sint-Barbarakerk","description":"Een schitterende gotische UNESCO-kathedraal, symbool van de middeleeuwse zilverrijkdom van Kutná Hora."},
   "es":{"name":"Kutná Hora – iglesia de Santa Bárbara","description":"Una magnífica catedral gótica UNESCO, símbolo de la riqueza en plata de la Kutná Hora medieval."},
   "fr":{"name":"Kutná Hora – église Sainte-Barbe","description":"Une magnifique cathédrale gothique UNESCO, symbole de la richesse en argent de la Kutná Hora médiévale."},
   "uk":{"name":"Кутна Гора – храм св. Варвари","description":"Розкішний готичний собор ЮНЕСКО, символ срібного багатства середньовічної Кутни Гори."}}'::jsonb),

('sights', 'Kalwaria Zebrzydowska',
 'Poutní klášterní komplex a manýristický park památek UNESCO na jihu Polska.',
 49.8686, 19.6733, 'PL', 'curated-batch1', 41,
 '{"en":{"name":"Kalwaria Zebrzydowska","description":"A pilgrimage monastery and Mannerist park of shrines, a UNESCO site in southern Poland."},
   "de":{"name":"Kalwaria Zebrzydowska","description":"Ein Wallfahrtskloster und manieristischer Park von Kapellen, UNESCO-Welterbe im Süden Polens."},
   "pl":{"name":"Kalwaria Zebrzydowska","description":"Pielgrzymkowy zespół klasztorny i manierystyczny park kaplic, obiekt UNESCO na południu Polski."},
   "nl":{"name":"Kalwaria Zebrzydowska","description":"Een bedevaartklooster en maniëristisch park van kapellen, UNESCO-erfgoed in Zuid-Polen."},
   "es":{"name":"Kalwaria Zebrzydowska","description":"Un monasterio de peregrinación y parque manierista de capillas, sitio UNESCO en el sur de Polonia."},
   "fr":{"name":"Kalwaria Zebrzydowska","description":"Un monastère de pèlerinage et parc maniériste de chapelles, site UNESCO au sud de la Pologne."},
   "uk":{"name":"Кальварія-Зебжидовська","description":"Паломницький монастирський комплекс і маньєристський парк каплиць, об''єкт ЮНЕСКО на півдні Польщі."}}'::jsonb),

('sights', 'Stift Melk',
 'Monumentální barokní benediktinské opatství nad Dunajem, brána do údolí Wachau.',
 48.2281, 15.3336, 'AT', 'curated-batch1', 42,
 '{"en":{"name":"Melk Abbey","description":"A monumental Baroque Benedictine abbey above the Danube, gateway to the Wachau valley."},
   "de":{"name":"Stift Melk","description":"Eine monumentale barocke Benediktinerabtei über der Donau, Tor zum Wachautal."},
   "pl":{"name":"Opactwo w Melku","description":"Monumentalne barokowe opactwo benedyktynów nad Dunajem, brama do doliny Wachau."},
   "nl":{"name":"Abdij van Melk","description":"Een monumentale barokke benedictijnenabdij boven de Donau, poort naar het Wachau-dal."},
   "es":{"name":"Abadía de Melk","description":"Una monumental abadía benedictina barroca sobre el Danubio, puerta al valle del Wachau."},
   "fr":{"name":"Abbaye de Melk","description":"Une monumentale abbaye bénédictine baroque au-dessus du Danube, porte de la vallée de la Wachau."},
   "uk":{"name":"Абатство Мельк","description":"Монументальне барокове бенедиктинське абатство над Дунаєм, брама до долини Вахау."}}'::jsonb),

-- == PŘÍRODA A REZERVACE =========================================
('nature', 'Pravčická brána',
 'Největší skalní brána v Evropě v NP České Švýcarsko; symbol pískovcových skal severu Čech.',
 50.8762, 14.2790, 'CZ', 'curated-batch1', 50,
 '{"en":{"name":"Pravčická brána","description":"Europe''s largest natural rock arch in Bohemian Switzerland NP; the emblem of the region''s sandstone cliffs."},
   "de":{"name":"Prebischtor","description":"Das größte Felsentor Europas im Nationalpark Böhmische Schweiz; Wahrzeichen der Sandsteinfelsen Nordböhmens."},
   "pl":{"name":"Pravčická brána","description":"Największa skalna brama w Europie w Parku Narodowym Czeska Szwajcaria; symbol piaskowcowych skał."},
   "nl":{"name":"Pravčická brána","description":"De grootste natuurlijke rotspoort van Europa in NP Boheems Zwitserland; symbool van de zandsteenrotsen."},
   "es":{"name":"Pravčická brána","description":"El mayor arco de roca natural de Europa en el PN de la Suiza Bohemia; emblema de sus riscos de arenisca."},
   "fr":{"name":"Pravčická brána","description":"La plus grande arche rocheuse naturelle d''Europe dans le PN de la Suisse bohémienne ; emblème des falaises de grès."},
   "uk":{"name":"Правчицька брама","description":"Найбільша скельна арка Європи в НП Чеська Швейцарія; символ пісковикових скель півночі Чехії."}}'::jsonb),

('nature', 'Morskie Oko',
 'Největší tatranské jezero v polských Vysokých Tatrách, obklopené štíty; klasický cíl výletů.',
 49.1979, 20.0705, 'PL', 'curated-batch1', 51,
 '{"en":{"name":"Morskie Oko","description":"The largest Tatra lake in Poland''s High Tatras, ringed by peaks; a classic trip destination."},
   "de":{"name":"Meerauge (Morskie Oko)","description":"Der größte Tatrasee in der polnischen Hohen Tatra, von Gipfeln umringt; ein klassisches Ausflugsziel."},
   "pl":{"name":"Morskie Oko","description":"Największe jezioro tatrzańskie w polskich Tatrach Wysokich, otoczone szczytami; klasyczny cel wycieczek."},
   "nl":{"name":"Morskie Oko","description":"Het grootste Tatrameer in de Poolse Hoge Tatra, omringd door toppen; een klassiek uitstapdoel."},
   "es":{"name":"Morskie Oko","description":"El mayor lago de los Altos Tatras polacos, rodeado de cumbres; un destino clásico de excursión."},
   "fr":{"name":"Morskie Oko","description":"Le plus grand lac des Hautes Tatras polonaises, cerné de sommets ; une destination d''excursion classique."},
   "uk":{"name":"Морське Око","description":"Найбільше татранське озеро в польських Високих Татрах, оточене вершинами; класична мета мандрівок."}}'::jsonb),

('nature', 'Grüner See (Tragöß)',
 'Smaragdové jezero ve Štýrsku, které se na jaře z tání sněhu rozlévá do lesa; klenot rakouských Alp.',
 47.5478, 15.0442, 'AT', 'curated-batch1', 52,
 '{"en":{"name":"Green Lake (Tragöß)","description":"An emerald lake in Styria that swells into the forest with spring snowmelt; a gem of the Austrian Alps."},
   "de":{"name":"Grüner See (Tragöß)","description":"Ein smaragdgrüner See in der Steiermark, der bei der Schneeschmelze in den Wald steigt; ein Juwel der Alpen."},
   "pl":{"name":"Zielone Jezioro (Tragöß)","description":"Szmaragdowe jezioro w Styrii, które wiosną z roztopów wlewa się w las; klejnot austriackich Alp."},
   "nl":{"name":"Grüner See (Tragöß)","description":"Een smaragdgroen meer in Stiermarken dat bij de smeltende sneeuw het bos in stijgt; een parel van de Alpen."},
   "es":{"name":"Lago Verde (Tragöß)","description":"Un lago esmeralda en Estiria que en primavera se adentra en el bosque con el deshielo; joya de los Alpes austriacos."},
   "fr":{"name":"Lac Vert (Tragöß)","description":"Un lac émeraude en Styrie qui, à la fonte des neiges, envahit la forêt ; joyau des Alpes autrichiennes."},
   "uk":{"name":"Зелене озеро (Трагесс)","description":"Смарагдове озеро у Штирії, що навесні від танення снігу розливається в ліс; перлина австрійських Альп."}}'::jsonb);
