-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — NORSKO (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Lysevegen a Kjerag – serpentiny nad Lysefjordem
  delete from public.routes where name = 'Lysevegen a Kjerag – serpentiny nad Lysefjordem' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Lysevegen a Kjerag – serpentiny nad Lysefjordem', 'Jedna z nejdivočejších silnic Norska: horská Lysevegen se z náhorní plošiny Sirdalu vrhá 27 serpentinami o 900 výškových metrů dolů do Lysebotnu na samém konci Lysefjordu. Z údolí Sirdal stoupáte holou skandinávskou tundrou mezi jezery a sněhovými poli až k vyhlídce Øygardstøl, odkud startuje slavná túra na skalní kouli Kjeragbolten. Pak přijde ten nejlepší kus: úzké, technické vlásenky s jedním jednosměrným tunelem vytesaným do skály, kde budete pracovat s předním kolem doslova metr po metru. Z Lysebotnu se dá pokračovat trajektem celým Lysefjordem — plavba pod kolmými tisícimetrovými stěnami je zážitek sama o sobě. Silnice je otevřená zhruba od konce května do října; i v létě počítejte s chladem, mlhou a zbytky sněhu nahoře. Pozor na úzký profil, protijedoucí karavany a štěrk v zatáčkách — jde o náročnou, ale nezapomenutelnou jízdu.', 'poi', 95, 150, 'hard',
     '[{"lat": 58.6644, "lng": 6.7147, "label": "Start: Tonstad (Sirdal)"}, {"lat": 58.9243, "lng": 6.8577, "label": "Tjørhom"}, {"lat": 58.9884, "lng": 6.8548, "label": "Ådneram"}, {"lat": 59.0339, "lng": 6.6496, "label": "Øygardstøl"}, {"lat": 59.0553, "lng": 6.6432, "label": "Cíl: Lysebotn"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=58.6644,6.7147&destination=59.0553,6.6432&travelmode=driving&waypoints=58.9243,6.8577%7C58.9884,6.8548%7C59.0339,6.6496', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kjeragbolten.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98ygardst%C3%B8l.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kjeragbolten.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lysevegen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lysebotn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lysefjorden.jpg"}'::text[], '{"Øygardstøl – Orlí hnízdo","Kjeragbolten","Lysevegen – 27 serpentin","Lysebotn","Lysefjord – plavba trajektem"}'::text[], '{"NO"}'::text[], false, 4610, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Øygardstøl – Orlí hnízdo', 'Vyhlídka a kavárna přezdívaná Ørneredet (Orlí hnízdo) na hraně tisícimetrového srázu nad Lysebotnem. Odsud startuje pěší túra na Kjerag a z terasy je vidět celá kaskáda serpentin Lysevegenu pod vámi. Povinná zastávka na fotku a kafe, než se pustíte dolů.', 59.0339, 6.6496, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98ygardst%C3%B8l.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98ygardst%C3%B8l.jpg"}'::text[], 0),
    (v_route, 'Kjeragbolten', 'Legendární balvan vklíněný ve skalní puklině tisíc metrů nad hladinou Lysefjordu — jedno z nejslavnějších fotomíst Norska. Z parkoviště Øygardstøl na něj vede náročná túra tam a zpět asi 10 km (počítejte 5–6 hodin), takže se hodí spíš jako celodenní přídavek k vyjížďce. I bez túry stojí masiv Kjeragu za pohled z vyhlídky.', 59.0336, 6.5931, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kjeragbolten.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kjeragbolten.jpg"}'::text[], 1),
    (v_route, 'Lysevegen – 27 serpentin', 'Klenot celé trasy: 27 vlásenek nad sebou, které klesají z 932 metrů prakticky na úroveň moře. Součástí sjezdu je i 1,1 km dlouhý tunel vytesaný do skály, který se uvnitř stáčí o 340 stupňů. Jeďte na jedničku až dvojku, hlídejte štěrk na vnitřních obloucích a užívejte si výhledy — něco podobného v Evropě moc nenajdete.', 59.0480, 6.6640, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lysevegen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lysevegen.jpg"}'::text[], 2),
    (v_route, 'Lysebotn', 'Maličká osada na samém konci Lysefjordu, sevřená kolmými skalními stěnami — v létě mekka motorkářů a basejumperů, kteří skáčou z okolních stěn. Je tu kemp, kiosek a přístaviště trajektu. Ideální místo, kde nechat doznít adrenalin ze sjezdu.', 59.0553, 6.6432, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lysebotn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lysebotn.jpg"}'::text[], 3),
    (v_route, 'Lysefjord – plavba trajektem', 'Z Lysebotnu vyplouvá v sezóně trajekt, který proveze vás i motorku celým 42 km dlouhým fjordem pod stěnou Kjeragu a pod skalní plošinou Preikestolen. Plavba trvá kolem dvou hodin a je to nejpohodlnější (a nejkrásnější) cesta zpět k civilizaci směrem na Stavanger. V hlavní sezóně si místo pro motorku rezervujte předem.', 59.0300, 6.3500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lysefjorden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lysefjorden.jpg"}'::text[], 4);

  -- Gamle Strynefjellsvegen – historická cesta přes hory
  delete from public.routes where name = 'Gamle Strynefjellsvegen – historická cesta přes hory' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Gamle Strynefjellsvegen – historická cesta přes hory', 'Stará silnice přes Strynefjellet z roku 1894 je národní turistická cesta a jedna z nejatmosféričtějších jízd Norska: úzká cesta lemovaná ručně skládanými kamennými patníky se vine mezi sněhovými poli, vodopády a ledovcovými jezery. Startujete ve Stryn u smaragdově zelených jezer, vystoupáte serpentinami kolem hřmícího vodopádu Videfossen k horskému hotelu Videseter a pak se po historické Rv258 přehoupnete přes náhorní plošinu do Grotli. Část cesty má zpevněný šotolinový povrch, který je ale udržovaný a na motorce v pohodě zvladatelný — jen zvolněte a užívejte si to. Silnice je otevřená zhruba od června do září a i v červenci tu můžete jet mezi několikametrovými sněhovými mantinely. Pozor na měnlivé horské počasí, ovce na cestě a protijedoucí auta v úzkých místech.', 'poi', 80, 120, 'medium',
     '[{"lat": 61.9046, "lng": 6.7114, "label": "Start: Stryn"}, {"lat": 61.8380, "lng": 6.8480, "label": "Loen"}, {"lat": 61.9727, "lng": 7.2320, "label": "Videseter"}, {"lat": 61.9950, "lng": 7.3900, "label": "Gamle Strynefjellsvegen"}, {"lat": 62.0186, "lng": 7.6569, "label": "Cíl: Grotli"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=61.9046,6.7114&destination=62.0186,7.6569&travelmode=driving&waypoints=61.8380,6.8480%7C61.9727,7.2320%7C61.9950,7.3900', 'https://commons.wikimedia.org/wiki/Special:FilePath/Gamle%20Strynefjellsvegen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stryn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lovatnet.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Videfossen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Videseter.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gamle%20Strynefjellsvegen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grotli.jpg"}'::text[], '{"Stryn","Loen a jezero Lovatnet","Videfossen","Videseter","Gamle Strynefjellsvegen","Grotli"}'::text[], '{"NO"}'::text[], false, 4620, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Stryn', 'Živé městečko mezi fjordem Nordfjord a horami, přirozená základna pro celý region. Doplňte tu palivo i zásoby — na horské části trasy už žádná pumpa není. V okolí najdete řadu kaváren a pekáren na rozjezdovou kávu.', 61.9046, 6.7114, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stryn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stryn.jpg"}'::text[], 0),
    (v_route, 'Loen a jezero Lovatnet', 'Krátká odbočka z hlavního tahu k jednomu z nejfotogeničtějších jezer Norska — ledovcová voda Lovatnetu má neuvěřitelnou tyrkysovou barvu. Podél břehu vede úzká klidná silnička ideální na pomalou vyhlídkovou jízdu. Z Loen jezdí i lanovka Loen Skylift na vrchol Hoven s výhledem na celý fjord.', 61.8380, 6.8480, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lovatnet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lovatnet.jpg"}'::text[], 1),
    (v_route, 'Videfossen', 'Mohutný vodopád přezdívaný Buldrefossen (Hřmící vodopád), který padá přímo u serpentin stoupání na Strynefjellet. Vodní tříšť často doletí až na silnici, tak pozor na mokrý asfalt v zatáčkách. Hned u cesty je vyhlídkové odpočívadlo na fotku.', 61.9640, 7.2260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Videfossen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Videfossen.jpg"}'::text[], 2),
    (v_route, 'Videseter', 'Horský hotel z 19. století vysoko nad údolím Hjelledalen, u kterého začíná historická část staré cesty. Z terasy je jeden z nejlepších výhledů celé trasy — hluboko dolů na údolí a serpentiny, kterými jste právě vyjeli. Příjemná zastávka na kávu a vafle.', 61.9727, 7.2320, 'https://commons.wikimedia.org/wiki/Special:FilePath/Videseter.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Videseter.jpg"}'::text[], 3),
    (v_route, 'Gamle Strynefjellsvegen', 'Samotná historická cesta z roku 1894: úzký pás mezi kamennými patníky, ledovcovými jezery a sněhovými poli, která tu leží celé léto. Jede se pomalu, ale právě proto si vychutnáte atmosféru staré horské silnice, po které kdysi jezdily kočáry. Jeden z nejkrásnějších úseků, jaké v Norsku na motorce potkáte.', 61.9950, 7.3900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gamle%20Strynefjellsvegen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gamle%20Strynefjellsvegen.jpg"}'::text[], 4),
    (v_route, 'Grotli', 'Osada s historickým vysokohorským hotelem Grotli Høyfjellshotell z roku 1874 na křižovatce horských cest. Cílová zastávka na oběd nebo nocleh; odsud se dá pokračovat na východ do Lomu, nebo se vrátit novou silnicí Rv15 tunely zpět do Stryn. V okolí je i letní lyžařské středisko Stryn sommerski.', 62.0186, 7.6569, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grotli.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grotli.jpg"}'::text[], 5);

  -- Sognefjellet – střecha Norska (Fv55)
  delete from public.routes where name = 'Sognefjellet – střecha Norska (Fv55)' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sognefjellet – střecha Norska (Fv55)', 'Sognefjellsvegen (Fv55) je nejvýše položený horský průsmyk severní Evropy — 1434 metrů — a vede přímo mezi ledovci národního parku Jotunheimen. Z Lomu se slavným sloupovým kostelem stoupáte údolím Bøverdalen pod nejvyšší horu Norska Galdhøpiggen, pak následuje otevřená vysokohorská plošina se sněhem i v červenci a dramatický sjezd serpentinami kolem Turtagrø pod žulové štíty Hurrungane. Dole vás čeká pohlednicový Skjolden na konci nejdelšího fjordu světa a jako třešnička trajekt k nejstaršímu sloupovému kostelu Norska v Urnes (UNESCO). Asfalt je kvalitní, zatáčky plynulé a provoz mimo špičku překvapivě mírný. Silnice je celoročně sjízdná jen omezeně — ideální okno je červen až září. Nahoře počítejte s chladem kolem 5 °C, větrem a rychlými změnami počasí.', 'poi', 135, 210, 'medium',
     '[{"lat": 61.8390, "lng": 8.5669, "label": "Start: Lom"}, {"lat": 61.5646, "lng": 7.9938, "label": "Sognefjellshytta"}, {"lat": 61.5046, "lng": 7.8010, "label": "Turtagrø"}, {"lat": 61.4839, "lng": 7.6040, "label": "Skjolden"}, {"lat": 61.2977, "lng": 7.3229, "label": "Cíl: Urnes"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=61.8390,8.5669&destination=61.2977,7.3229&travelmode=driving&waypoints=61.5646,7.9938%7C61.5046,7.8010%7C61.4839,7.6040', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lom%20stavkirke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lom%20stavkirke.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bakeriet%20i%20Lom.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sognefjellet.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hurrungane.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skjolden.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Urnes%20stavkirke.jpg"}'::text[], '{"Lom – sloupový kostel","Restaurace: Bakeriet i Lom (Lom)","Sognefjellet – vrchol průsmyku","Turtagrø a štíty Hurrungane","Skjolden a Lustrafjord","Urnes – sloupový kostel (UNESCO)"}'::text[], '{"NO"}'::text[], false, 4630, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lom – sloupový kostel', 'Dřevěný sloupový kostel (stavkirke) z 12. století s dračími hlavami na střeše je dominantou horského městečka Lom. Městečko je zároveň bránou do Jotunheimenu a poslední větší zastávkou před průsmykem — natankujte a nakupte tady. Kostel stojí hned u hlavní silnice a prohlídka zabere půl hodiny.', 61.8390, 8.5669, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lom%20stavkirke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lom%20stavkirke.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Bakeriet i Lom (Lom)', 'Slavná pekárna špičkového norského kuchaře Mortena Schakendy, kvůli které se v Lomu zastavuje celé Norsko. Skořicoví šneci, čerstvý chleba z kamenné pece a výborná káva — ideální motorkářská snídaně před výjezdem na průsmyk. Podnik má vynikající hodnocení a v sezóně tu bývá fronta, která ale stojí za to.', 61.8386, 8.5660, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bakeriet%20i%20Lom.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bakeriet%20i%20Lom.jpg"}'::text[], 1),
    (v_route, 'Sognefjellet – vrchol průsmyku', 'Nejvyšší bod silnice (1434 m) u moderní horské chaty Sognefjellshytta, obklopený ledovci Smørstabbreen a štíty Jotunheimenu. I uprostřed léta tu leží sníh a teploty padají k nule — přibalte teplé vrstvy. Chata nabízí polévku, kávu a úžasné panorama prosklenou stěnou.', 61.5646, 7.9938, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sognefjellet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sognefjellet.jpg"}'::text[], 2),
    (v_route, 'Turtagrø a štíty Hurrungane', 'Historický horolezecký hotel pod nejdivočejšími štíty Norska — žulové věže Hurrungane s vrcholem Store Skagastølstind (2405 m) jsou norský Matterhorn. Sjezd od hotelu dolů do údolí je kaskáda ostrých serpentin s výhledy, ze kterých se tají dech. Zastavte na terase hotelu na kávu s výhledem na stěny.', 61.5046, 7.8010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hurrungane.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hurrungane.jpg"}'::text[], 3),
    (v_route, 'Skjolden a Lustrafjord', 'Vesnička na samém konci Lustrafjordu — nejvnitřnějšího ramene Sognefjordu, nejdelšího a nejhlubšího fjordu světa. Po sjezdu z hor tu najednou jedete podél smaragdové hladiny mezi ovocnými sady. Ideální místo na oběd a odpočinek u vody.', 61.4839, 7.6040, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skjolden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skjolden.jpg"}'::text[], 4),
    (v_route, 'Urnes – sloupový kostel (UNESCO)', 'Nejstarší sloupový kostel Norska (kolem roku 1130) se slavnými vikingskými řezbami, zapsaný na seznamu UNESCO. Stojí nad Lustrafjordem a nejhezčí cesta k němu vede krátkým trajektem ze Solvornu — plavba přes fjord je zážitek navrch. Krásná tečka za celou trasou.', 61.2977, 7.3229, 'https://commons.wikimedia.org/wiki/Special:FilePath/Urnes%20stavkirke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Urnes%20stavkirke.jpg"}'::text[], 5);

  -- Hardanger – vodopády a ovocné sady
  delete from public.routes where name = 'Hardanger – vodopády a ovocné sady' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Hardanger – vodopády a ovocné sady', 'Hardangerfjord je ovocný sad Norska — a jeho břehy lemuje jedna z nejpříjemnějších fjordových silnic vůbec. Trasa začíná u vodopádu Steinsdalsfossen, za kterým se dá projít suchou nohou, pokračuje po Fv7 podél fjordu přes elegantní visutý most Hardangerbrua a soutěskou Måbødalen vystoupá k Vøringsfossen, nejslavnějšímu vodopádu země se 182 metry volného pádu. Zpáteční rameno vede po Rv13 podél Sørfjordenu skrz ovocné sady v Lofthus — v květnu tu kvetou statisíce jabloní, na konci léta koupíte u cesty čerstvé třešně a cider. Finále obstará dvojitý vodopád Låtefossen u Oddy, který stříká přímo na silnici. Jízdně jde o pohodovou, plynulou trasu s kvalitním asfaltem; ideální sezóna je květen až září. Pozor na turistický provoz u vyhlídek a mokrou vozovku u vodopádů.', 'poi', 165, 240, 'medium',
     '[{"lat": 60.3720, "lng": 6.1470, "label": "Start: Norheimsund"}, {"lat": 60.3739, "lng": 6.1120, "label": "Steinsdalsfossen"}, {"lat": 60.4790, "lng": 6.8330, "label": "Hardangerbrua"}, {"lat": 60.4671, "lng": 7.0716, "label": "Eidfjord"}, {"lat": 60.4269, "lng": 7.2519, "label": "Vøringsfossen"}, {"lat": 60.3330, "lng": 6.6620, "label": "Lofthus"}, {"lat": 59.9487, "lng": 6.5817, "label": "Cíl: Låtefossen"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=60.3720,6.1470&destination=59.9487,6.5817&travelmode=driving&waypoints=60.3739,6.1120%7C60.4790,6.8330%7C60.4671,7.0716%7C60.4269,7.2519%7C60.3330,6.6620', 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%B8ringsfossen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Steinsdalsfossen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hardangerbrua.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Eidfjord.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%B8ringsfossen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lofthus%20i%20Hardanger.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hotel%20Ullensvang.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5tefossen.jpg"}'::text[], '{"Steinsdalsfossen","Hardangerbrua","Eidfjord","Vøringsfossen","Lofthus – ovocné sady","Restaurace: Hotel Ullensvang (Lofthus)","Låtefossen"}'::text[], '{"NO"}'::text[], false, 4640, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Steinsdalsfossen', 'Padesátimetrový vodopád u Norheimsundu, za jehož vodní clonou vede chodník — projdete se za vodopádem, aniž byste zmokli. Parkoviště je přímo u silnice, zastávka zabere čtvrt hodiny. Skvělé zahájení fjordové etapy.', 60.3739, 6.1120, 'https://commons.wikimedia.org/wiki/Special:FilePath/Steinsdalsfossen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Steinsdalsfossen.jpg"}'::text[], 0),
    (v_route, 'Hardangerbrua', 'Jeden z nejdelších visutých mostů Evropy (1380 m) elegantně překlenuje Hardangerfjord mezi Bruravikem a Brimnes. Přejezd na motorce s fjordem sto metrů pod koly je malý svátek. Most nahradil trajekt a napojuje trasu přímo na Eidfjord.', 60.4790, 6.8330, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hardangerbrua.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hardangerbrua.jpg"}'::text[], 1),
    (v_route, 'Eidfjord', 'Půvabná obec na konci stejnojmenného ramene fjordu, obklopená horskými stěnami — vstupní brána na náhorní plošinu Hardangervidda. Dobré místo na doplnění paliva a občerstvení před stoupáním soutěskou Måbødalen. V přístavu často kotví výletní lodě, dopoledne tu proto bývá živo.', 60.4671, 7.0716, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eidfjord.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eidfjord.jpg"}'::text[], 2),
    (v_route, 'Vøringsfossen', 'Nejslavnější vodopád Norska padá 182 metrů z hrany Hardangerviddy do soutěsky Måbødalen. Nové vyhlídkové lávky včetně schodového mostu přes rokli nabízejí pohledy přímo do hloubky. Samotná silnice Rv7 soutěskou nahoru je jízdní zážitek — serpentiny a tunely vytesané ve skále.', 60.4269, 7.2519, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%B8ringsfossen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%B8ringsfossen.jpg"}'::text[], 3),
    (v_route, 'Lofthus – ovocné sady', 'Srdce hardangerského ovocnářství: svahy nad Sørfjordenem pokrývají sady jabloní, třešní a švestek s ledovcem Folgefonna v pozadí. V květnu je to nejkrásnější kvetoucí krajina Norska, koncem léta u cesty koupíte ovoce a slavný místní cider. Silnice Rv13 podél fjordu je plynulá a výhledová.', 60.3330, 6.6620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lofthus%20i%20Hardanger.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lofthus%20i%20Hardanger.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Hotel Ullensvang (Lofthus)', 'Legendární rodinný hotel na břehu Sørfjordenu, kde tvořil i skladatel Edvard Grieg. Restaurace staví na místních surovinách — fjordový losos, jehněčí a ovoce ze sadů za domem — a má výborné hodnocení hostů. Ideální oběd s výhledem na fjord a ledovec Folgefonna.', 60.3236, 6.6580, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hotel%20Ullensvang.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hotel%20Ullensvang.jpg"}'::text[], 5),
    (v_route, 'Låtefossen', 'Dvojitý vodopád, jehož dvě ramena se spojují přímo nad silničním mostem — v plné síle stříká vodní tříšť až na projíždějící motorkáře. Jeden z nejfotografovanějších vodopádů země, parkoviště je hned vedle. Důstojná tečka za trasou kousek od Oddy.', 59.9487, 6.5817, 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5tefossen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5tefossen.jpg"}'::text[], 6);

  -- Ryfylke – Preikestolen a cesta vodopádů do Saudy
  delete from public.routes where name = 'Ryfylke – Preikestolen a cesta vodopádů do Saudy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Ryfylke – Preikestolen a cesta vodopádů do Saudy', 'Národní turistická cesta Ryfylke (Rv13) vede ze Stavangeru fjordovou krajinou na sever přes trajekty, tunely a vodopády až do horského městečka Sauda. Po ránu stihnete slavnou skalní plošinu Preikestolen — kolmý sráz 604 metrů nad Lysefjordem (túra 8 km tam a zpět) — a pak se ponoříte do klidného Ryfylke: trajekt přes fjord u Hjelmelandu, dřevěné městečko Sand nad řekou Suldalslågen a vodopád Svandalsfossen, kterému vyjedete po schodech přímo do vodní tříště. Před Saudou stojí architektonický skvost Allmannajuvet — stará zinková štola s pavilonem Petera Zumthora zavěšeným v soutěsce. Silnice je kombinace plynulých fjordových pasáží a užších technických úseků, provoz je mimo Preikestolen minimální. Nejlepší období je květen až září; počítejte s časem na trajekt a s mokrým asfaltem u vodopádů.', 'poi', 175, 300, 'medium',
     '[{"lat": 58.9700, "lng": 5.7331, "label": "Start: Stavanger"}, {"lat": 58.9926, "lng": 6.1420, "label": "Preikestolen – parkoviště"}, {"lat": 59.2370, "lng": 6.1810, "label": "Hjelmeland – trajekt"}, {"lat": 59.4890, "lng": 6.2536, "label": "Sand"}, {"lat": 59.6480, "lng": 6.3170, "label": "Svandalsfossen"}, {"lat": 59.6506, "lng": 6.3540, "label": "Cíl: Sauda"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=58.9700,5.7331&destination=59.6506,6.3540&travelmode=driving&waypoints=58.9926,6.1420%7C59.2370,6.1810%7C59.4890,6.2536%7C59.6480,6.3170', 'https://commons.wikimedia.org/wiki/Special:FilePath/Preikestolen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gamle%20Stavanger.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Preikestolen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sand%20i%20Ryfylke.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svandalsfossen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Allmannajuvet.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sauda.jpg"}'::text[], '{"Restaurace: Fisketorget (Stavanger)","Preikestolen","Sand","Svandalsfossen","Allmannajuvet","Sauda"}'::text[], '{"NO"}'::text[], false, 4650, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Restaurace: Fisketorget (Stavanger)', 'Vyhlášená rybí restaurace přímo na nábřeží stavangerského přístavu Vågen s vlastním rybím pultem. Denní úlovek, polévka z mořských plodů a čerstvé ústřice — hodnocení má výborné a po ránu tu seženete i lehčí snídani. Ideální start před vyjížďkou, kousek od kolonie bílých dřevěných domků Gamle Stavanger.', 58.9720, 5.7330, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gamle%20Stavanger.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gamle%20Stavanger.jpg"}'::text[], 0),
    (v_route, 'Preikestolen', 'Kazatelna — dokonale rovná skalní plošina 604 metrů kolmo nad Lysefjordem a nejslavnější přírodní scéna Norska. Z parkoviště u Preikestolen fjellstue vede nahoru kamenná stezka, 8 km tam a zpět, počítejte 4 hodiny. Vyrazte brzy ráno, vyhnete se davům i odpolednímu vedru.', 58.9864, 6.1904, 'https://commons.wikimedia.org/wiki/Special:FilePath/Preikestolen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Preikestolen.jpg"}'::text[], 1),
    (v_route, 'Sand', 'Dřevěné městečko nad ústím lososí řeky Suldalslågen, správní centrum kraje Suldal. Bílé domky, malý přístav a lávka Høse bru přes řeku — příjemná zastávka na kávu v polovině cesty. V řece se dají v sezóně pozorovat lososi táhnoucí proti proudu.', 59.4890, 6.2536, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sand%20i%20Ryfylke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sand%20i%20Ryfylke.jpg"}'::text[], 2),
    (v_route, 'Svandalsfossen', 'Vodopád, který padá v několika stupních přímo k silnici před Saudou — z odpočívadla k němu vede 540 schodů až do vodní tříště. Při tání sněhu na jaře je jeho síla ohromující a sprcha zaručená. Parkování přímo u Rv13.', 59.6480, 6.3170, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svandalsfossen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svandalsfossen.jpg"}'::text[], 3),
    (v_route, 'Allmannajuvet', 'Areál staré zinkové štoly v hluboké soutěsce, přestavěný švýcarským architektem Peterem Zumthorem na minimalistické muzeum s kavárnou zavěšenou nad roklí. Kontrast syrové hornické historie a světové architektury je fascinující. Krátká odbočka ze silnice do Saudy, otevřeno v letní sezóně.', 59.6290, 6.3990, 'https://commons.wikimedia.org/wiki/Special:FilePath/Allmannajuvet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Allmannajuvet.jpg"}'::text[], 4),
    (v_route, 'Sauda', 'Průmyslové městečko na konci Saudafjordu, obklopené horami — cíl trasy a dobré místo na nocleh. Odsud se dá pokračovat horskou silnicí přes Røldal na Hardanger, nebo se vrátit trajektem. V centru je několik kaváren a funkcionalistická dělnická čtvrť Åbøbyen.', 59.6506, 6.3540, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sauda.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sauda.jpg"}'::text[], 5);

  -- Senja – arktický ostrov štítů a pláží
  delete from public.routes where name = 'Senja – arktický ostrov štítů a pláží' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Senja – arktický ostrov štítů a pláží', 'Senja je druhý největší ostrov Norska a mezi motorkáři platí za „Lofoty bez davů": národní turistická cesta Fv862 po jeho vnějším pobřeží střídá tunely, mosty a serpentiny mezi zubatými štíty padajícími rovnou do Atlantiku. Z Finnsnes se dostanete na západní pobřeží k vyhlídkové plošině Bergsbotn a resortu Hamn i Senja, pak následuje ikonické odpočívadlo Tungeneset s výhledem na zuby Okshornan a bílá pláž Ersfjordstranda s tyrkysovou vodou jako z Karibiku — jen o 40 stupňů severněji. Finále patří rybářské vesnici Fjordgård pod slavnou horou Segla a trajektu z Botnhamnu směr Tromsø. Za polárním kruhem se v létě jezdí pod půlnočním sluncem, které celou trasu barví do zlata. Ideální okno je červen až srpen; počítejte s úzkými úseky, ovcemi na silnici a rychlými změnami počasí od moře.', 'poi', 115, 180, 'medium',
     '[{"lat": 69.2295, "lng": 17.9811, "label": "Start: Finnsnes"}, {"lat": 69.4430, "lng": 17.2120, "label": "Bergsbotn"}, {"lat": 69.4664, "lng": 17.1746, "label": "Hamn i Senja"}, {"lat": 69.5010, "lng": 17.3550, "label": "Tungeneset"}, {"lat": 69.5486, "lng": 17.6489, "label": "Fjordgård"}, {"lat": 69.6280, "lng": 17.8340, "label": "Cíl: Botnhamn (trajekt)"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=69.2295,17.9811&destination=69.6280,17.8340&travelmode=driving&waypoints=69.4430,17.2120%7C69.4664,17.1746%7C69.5010,17.3550%7C69.5486,17.6489', 'https://commons.wikimedia.org/wiki/Special:FilePath/Segla.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bergsbotn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hamn%20i%20Senja.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tungeneset.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ersfjordstranda.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Segla.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hus%C3%B8y%20i%20Senja.jpg"}'::text[], '{"Bergsbotn – vyhlídková plošina","Hamn i Senja","Tungeneset a Okshornan","Ersfjordstranda","Fjordgård a hora Segla","Husøy"}'::text[], '{"NO"}'::text[], false, 4660, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Bergsbotn – vyhlídková plošina', 'Čtyřicetimetrová dřevěná vyhlídková lávka vysunutá nad fjord Bergsfjorden s panoramatem štítů západní Senji. Silnice sem stoupá krásnými serpentinami z vnitrozemí ostrova. Zastávka přímo u cesty, výhled patří k nejlepším na trase.', 69.4430, 17.2120, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bergsbotn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bergsbotn.jpg"}'::text[], 0),
    (v_route, 'Hamn i Senja', 'Bývalá rybářská osada na skalnatém výběžku, dnes oblíbený resort s restaurací a molem mezi ostrůvky. Skvělé místo na oběd s výhledem na otevřené moře — kuchyně staví na čerstvých rybách a arktických surovinách. V okolí se dají pozorovat orli mořští.', 69.4664, 17.1746, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hamn%20i%20Senja.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hamn%20i%20Senja.jpg"}'::text[], 1),
    (v_route, 'Tungeneset a Okshornan', 'Architektonicky řešené odpočívadlo národní turistické cesty: sibiřským modřínem obložený chodník vede přes skaliska k výhledu na zubaté štíty Okshornan, přezdívané Ďáblovy zuby. Jedno z nejfotografovanějších míst severního Norska. Za vlnobití tu Atlantik buší do skal pár metrů od vás.', 69.5010, 17.3550, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tungeneset.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tungeneset.jpg"}'::text[], 2),
    (v_route, 'Ersfjordstranda', 'Bílá písečná pláž s tyrkysovou vodou zasazená mezi divoké štíty — arktický Karibik. U pláže je zlatě obložené servisní zázemí, další z architektonických perel turistické cesty. Otužilci se můžou vykoupat, ostatní aspoň vyfotí motorku na pozadí, které nikdo neuvěří.', 69.5160, 17.4210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ersfjordstranda.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ersfjordstranda.jpg"}'::text[], 3),
    (v_route, 'Fjordgård a hora Segla', 'Rybářská vesnice pod dokonale tvarovaným štítem Segla (639 m), který se jako plachta zvedá kolmo z moře. Túra na vrchol (asi 3 hodiny tam a zpět) patří k nejslavnějším v severním Norsku, výhled z hrany je závratný. Cesta do vesnice vede tunely skrz horské hřebeny.', 69.5486, 17.6489, 'https://commons.wikimedia.org/wiki/Special:FilePath/Segla.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Segla.jpg"}'::text[], 4),
    (v_route, 'Husøy', 'Celá vesnice na jednom malém ostrůvku uprostřed fjordu Øyfjorden, spojená s Senjou jen náspem — jedno z nejmalebnějších rybářských sídel Norska. Domky tu stojí doslova jeden na druhém a život se točí kolem přístavu. Krátká odbočka, která stojí za to.', 69.6320, 17.6560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hus%C3%B8y%20i%20Senja.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hus%C3%B8y%20i%20Senja.jpg"}'::text[], 5);

  -- Helgeland – pobřežní cesta Fv17 za polární kruh
  delete from public.routes where name = 'Helgeland – pobřežní cesta Fv17 za polární kruh' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Helgeland – pobřežní cesta Fv17 za polární kruh', 'Kystriksveien (Fv17) z Brønnøysundu do Bodø je považována za jednu z nejkrásnějších pobřežních silnic světa: 440 kilometrů mezi tisíci ostrůvky, horskými hřebeny a ledovci, proložených šesti trajekty — právě plavby mezi ostrovy dělají z cesty expedici. Začíná se u hory Torghatten s dírou skrz naskrz, pokračuje pod hřebenem Sedmi sester u Sandnessjøenu a trajektem přes polární kruh k ledovci Svartisen, jehož splaz Engabreen stéká téměř k moři. Velkolepým finále je Saltstraumen — nejsilnější slapový proud světa — a přístavní Bodø. Silnice je kvalitní a provoz řídký, jde ale o dlouhou etapu: rozdělte si ji na dva až tři dny a trajekty v hlavní sezóně nepodceňujte, tvoří se u nich fronty. Nejlepší období je červen až srpen, kdy se jezdí pod půlnočním sluncem. Počítejte s větrem od moře a proměnlivým počasím.', 'poi', 440, 780, 'medium',
     '[{"lat": 65.4740, "lng": 12.2120, "label": "Start: Brønnøysund"}, {"lat": 65.3970, "lng": 12.0930, "label": "Torghatten"}, {"lat": 66.0217, "lng": 12.6316, "label": "Sandnessjøen"}, {"lat": 66.6790, "lng": 13.8500, "label": "Svartisen – Engabreen"}, {"lat": 67.2340, "lng": 14.6190, "label": "Saltstraumen"}, {"lat": 67.2804, "lng": 14.4049, "label": "Cíl: Bodø"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=65.4740,12.2120&destination=67.2804,14.4049&travelmode=driving&waypoints=65.3970,12.0930%7C66.0217,12.6316%7C66.6790,13.8500%7C67.2340,14.6190', 'https://commons.wikimedia.org/wiki/Special:FilePath/Torghatten.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Torghatten.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/De%20syv%20s%C3%B8stre.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Engabreen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Saltstraumen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bod%C3%B8.jpg"}'::text[], '{"Torghatten","De syv søstre – Sedm sester","Svartisen – ledovec Engabreen","Saltstraumen","Restaurace: Bryggerikaia (Bodø)"}'::text[], '{"NO"}'::text[], false, 4670, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Torghatten', 'Žulová hora s 160 metrů dlouhou dírou skrz celý masiv — podle legendy ji prostřelil trollí šíp. K otvoru vede z parkoviště pohodová stezka (asi 20 minut) a průhled skrz horu na moře je surrealistický zážitek. Symbol jižního Helgelandu kousek od Brønnøysundu.', 65.3970, 12.0930, 'https://commons.wikimedia.org/wiki/Special:FilePath/Torghatten.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Torghatten.jpg"}'::text[], 0),
    (v_route, 'De syv søstre – Sedm sester', 'Hřeben sedmi štítů nad Sandnessjøenem, který podle pověsti tvoří zkamenělé trollí dcery. Silnice vede přímo pod tisícimetrovými vrcholy a panorama vás doprovází desítky kilometrů. Sandnessjøen je zároveň dobrá zastávka na tankování a nocleh.', 66.0217, 12.6316, 'https://commons.wikimedia.org/wiki/Special:FilePath/De%20syv%20s%C3%B8stre.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/De%20syv%20s%C3%B8stre.jpg"}'::text[], 1),
    (v_route, 'Svartisen – ledovec Engabreen', 'Druhý největší ledovec Norska stéká splazem Engabreen téměř až k hladině Holandsfjordenu — modrý led je vidět přímo ze silnice Fv17. Z přístaviště Holand jezdí v létě lodička přes fjord, odkud je to k čelu ledovce hodinová procházka. Cestou sem navíc trajekt Kilboghamn–Jektvik protíná polární kruh.', 66.6790, 13.8500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Engabreen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Engabreen.jpg"}'::text[], 2),
    (v_route, 'Saltstraumen', 'Nejsilnější slapový proud na světě: každých šest hodin se úžinou prožene 400 milionů kubíků vody a roztočí obří víry. Nejlepší pohled je z mostu nad úžinou; časy nejsilnějšího proudu najdete v přílivové tabulce. Ráj rybářů — tresky tu loví přímo ze břehu.', 67.2340, 14.6190, 'https://commons.wikimedia.org/wiki/Special:FilePath/Saltstraumen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Saltstraumen.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Bryggerikaia (Bodø)', 'Oblíbená restaurace na nábřeží v Bodø s vlastním minipivovarem a výhledem na přístav. Na talíři severská klasika — treska skrei, rybí polévka, sobí maso — a hodnocení patří k nejlepším ve městě. Zasloužená oslava dojezdu na konci Kystriksveien.', 67.2830, 14.3780, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bod%C3%B8.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bod%C3%B8.jpg"}'::text[], 4);

  -- Valdresflye – náhorní cestou do Jotunheimenu
  delete from public.routes where name = 'Valdresflye – náhorní cestou do Jotunheimenu' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Valdresflye – náhorní cestou do Jotunheimenu', 'Národní turistická cesta Fv51 přes náhorní plošinu Valdresflye je nejpohodovější způsob, jak si na motorce vychutnat velehory Jotunheimenu: široká, plynulá silnice stoupá z Fagernes přes horské středisko Beitostølen až do 1389 metrů, kde se otevře panorama ledovcových štítů, stád ovcí a sobů a nekonečné tundry. Sjezd vás přivede k jezeru Gjende, nad kterým se táhne slavný hřeben Besseggen, a dál údolím řeky Sjoa kolem skalní soutěsky Ridderspranget do Vågåmo se středověkým kostelem. Jízdně jde o snadnou trasu s výborným asfaltem a mírným provozem — ideální i pro méně zkušené jezdce, kteří chtějí velehorskou scenérii bez vlásenek. Nejlepší období je červen až září; nahoře bývá chladno a větrno i v létě. Brzy ráno a večer pozor na volně se pasoucí ovce na silnici.', 'poi', 125, 180, 'easy',
     '[{"lat": 60.9860, "lng": 9.2320, "label": "Start: Fagernes"}, {"lat": 61.2496, "lng": 8.9070, "label": "Beitostølen"}, {"lat": 61.4370, "lng": 8.8130, "label": "Valdresflye"}, {"lat": 61.4952, "lng": 8.8069, "label": "Gjendesheim"}, {"lat": 61.5232, "lng": 9.0448, "label": "Ridderspranget"}, {"lat": 61.8754, "lng": 9.0967, "label": "Cíl: Vågåmo"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=60.9860,9.2320&destination=61.8754,9.0967&travelmode=driving&waypoints=61.2496,8.9070%7C61.4370,8.8130%7C61.4952,8.8069%7C61.5232,9.0448', 'https://commons.wikimedia.org/wiki/Special:FilePath/Valdresflya.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Beitost%C3%B8len.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Valdresflya.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Besseggen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ridderspranget.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A5g%C3%A5%20kyrkje.jpg"}'::text[], '{"Beitostølen","Valdresflye – náhorní plošina","Jezero Gjende a hřeben Besseggen","Ridderspranget","Vågåmo"}'::text[], '{"NO"}'::text[], false, 4680, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Beitostølen', 'Horské středisko na jižním okraji Jotunheimenu, poslední větší zastávka před náhorní plošinou. Kavárny, pumpa a obchody pohromadě — doplňte zásoby a teplé vrstvy. Odsud silnice stoupá do otevřené tundry.', 61.2496, 8.9070, 'https://commons.wikimedia.org/wiki/Special:FilePath/Beitost%C3%B8len.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Beitost%C3%B8len.jpg"}'::text[], 0),
    (v_route, 'Valdresflye – náhorní plošina', 'Nejvyšší bod silnice (1389 m) uprostřed nekonečné vysokohorské tundry s výhledem na ledovcové štíty Jotunheimenu. U vyhlídky Rjupa stojí originální betonové odpočívadlo národní turistické cesty. Mezi sněhovými poli se tu pasou sobi a ovce — jeďte s okem na krajnici.', 61.4370, 8.8130, 'https://commons.wikimedia.org/wiki/Special:FilePath/Valdresflya.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Valdresflya.jpg"}'::text[], 1),
    (v_route, 'Jezero Gjende a hřeben Besseggen', 'Smaragdově zelené ledovcové jezero, nad kterým se táhne Besseggen — nejslavnější hřebenová túra Norska, kterou proslavil už Ibsenův Peer Gynt. Od chaty Gjendesheim vyplouvají lodě přes jezero do Memurubu, odkud se hřeben přechází zpět (celý den). I krátká zastávka u jezera stojí za to.', 61.4952, 8.8069, 'https://commons.wikimedia.org/wiki/Special:FilePath/Besseggen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Besseggen.jpg"}'::text[], 2),
    (v_route, 'Ridderspranget', 'Rytířský skok — sevřená skalní soutěska, kterou se divoká řeka Sjoa prodírá jen pár metrů širokou průrvou. Podle pověsti ji přeskočil rytíř prchající s unesenou nevěstou. Od parkoviště krátká procházka lesem, síla vody je slyšet už z dálky.', 61.5232, 9.0448, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ridderspranget.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ridderspranget.jpg"}'::text[], 3),
    (v_route, 'Vågåmo', 'Půvabné městečko v údolí Otty se středověkým kostelem z roku 1130, roubenými domy a příjemným centrem. Cíl trasy a křižovatka dalších cest — odsud je kousek do Lomu a na Sognefjellet. Ideální místo na odpolední kávu po sjezdu z hor.', 61.8754, 9.0967, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A5g%C3%A5%20kyrkje.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A5g%C3%A5%20kyrkje.jpg"}'::text[], 4);

  -- Aurlandsfjellet – Snøvegen a vyhlídka Stegastein
  delete from public.routes where name = 'Aurlandsfjellet – Snøvegen a vyhlídka Stegastein' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Aurlandsfjellet – Snøvegen a vyhlídka Stegastein', 'Aurlandsfjellet, přezdívaný Snøvegen (Sněžná cesta), je horská alternativa k nejdelšímu silničnímu tunelu světa: místo 24,5 km tmy vás čeká 47 km úzké silnice přes holé kamenné plató, kde sněhové bariéry lemují cestu i v červenci. Start je ve Flåmu na konci Aurlandsfjordu, první vrchol přijde rychle — dřevěná vyhlídka Stegastein vybíhající 30 metrů do prázdna 650 metrů nad fjordem. Pak následuje měsíční krajina vrcholové plošiny a dlouhý sjezd do Lærdalu s uličkami starých dřevěných domů. Tečkou je Borgund, nejzachovalejší sloupový kostel Norska z roku 1180. Silnice je z velké části jednopruhová s výhybnami, takže jde spíš o pomalou vychutnávací jízdu než o stíhačku. Otevřeno zhruba od června do října podle sněhu; nahoře počítejte s mlhou, větrem a teplotami pod 10 °C.', 'poi', 90, 150, 'medium',
     '[{"lat": 60.8630, "lng": 7.1130, "label": "Start: Flåm"}, {"lat": 60.9047, "lng": 7.2110, "label": "Stegastein"}, {"lat": 60.9600, "lng": 7.3600, "label": "Aurlandsfjellet – plató"}, {"lat": 61.0996, "lng": 7.4810, "label": "Lærdalsøyri"}, {"lat": 61.0470, "lng": 7.8122, "label": "Cíl: Borgund stavkirke"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=60.8630,7.1130&destination=61.0470,7.8122&travelmode=driving&waypoints=60.9047,7.2110%7C60.9600,7.3600%7C61.0996,7.4810', 'https://commons.wikimedia.org/wiki/Special:FilePath/Stegastein.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fl%C3%A5msbana.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fl%C3%A5m.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stegastein.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Aurlandsfjellet.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A6rdals%C3%B8yri.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Borgund%20stavkirke.jpg"}'::text[], '{"Flåm","Restaurace: Ægir BryggeriPub (Flåm)","Stegastein","Aurlandsfjellet – Snøvegen","Lærdalsøyri","Borgund – sloupový kostel"}'::text[], '{"NO"}'::text[], false, 4690, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Flåm', 'Turistická vesnice na konci Aurlandsfjordu, výchozí bod slavné horské železnice Flåmsbana a náš start. Přístav, muzeum železnice a spousta kaváren — dopoledne tu bývá rušno kvůli výletním lodím. Natankujte, nahoře na plošině žádná pumpa není.', 60.8630, 7.1130, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fl%C3%A5msbana.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fl%C3%A5msbana.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Ægir BryggeriPub (Flåm)', 'Proslulý minipivovar v budově inspirované vikingskou architekturou přímo u flåmského přístavu. Vikinská ochutnávková prkna, uzené sobí maso a pivo oceňované po celém Norsku; hodnocení hostů je výborné. Skvělý oběd před výjezdem na Sněžnou cestu — s mírou, hory teprve přijdou.', 60.8622, 7.1136, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fl%C3%A5m.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fl%C3%A5m.jpg"}'::text[], 1),
    (v_route, 'Stegastein', 'Ikonická dřevěná vyhlídka vybíhající 30 metrů do prostoru 650 metrů nad Aurlandsfjordem — lávka se na konci stáčí dolů a končí jen skleněným zábradlím nad propastí. Jedno z nejfotografovanějších míst norských fjordů. Serpentiny z Aurlandu nahoru jsou samy o sobě skvělá jízda.', 60.9047, 7.2110, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stegastein.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stegastein.jpg"}'::text[], 2),
    (v_route, 'Aurlandsfjellet – Snøvegen', 'Vrcholová část Sněžné cesty: holé kamenné plató ve 1300 metrech, kde i uprostřed léta projíždíte mezi sněhovými poli a tyrkysovými jezírky. Krajina působí měsíčně a počasí se mění po minutách. Jednopruhová silnice s výhybnami — jeďte předvídavě a užívejte si ticho.', 60.9600, 7.3600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aurlandsfjellet.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aurlandsfjellet.jpg"}'::text[], 3),
    (v_route, 'Lærdalsøyri', 'Historické městečko na břehu Sognefjordu se 160 chráněnými dřevěnými domy z 18. a 19. století. Úzké uličky starého jádra jsou jako kulisy z filmu — projděte se a dejte si kávu. Odsud vede údolí Lærdal, proslulé lososí řekou, vzhůru k Borgundu.', 61.0996, 7.4810, 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A6rdals%C3%B8yri.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A6rdals%C3%B8yri.jpg"}'::text[], 4),
    (v_route, 'Borgund – sloupový kostel', 'Nejzachovalejší sloupový kostel Norska z roku 1180 — celý ze dřeva, s dračími hlavami na hřebenech střech a runovými nápisy na portálech. Vedle stojí návštěvnické centrum s expozicí o stavbě stavkirke. Důstojné zakončení trasy; zpět do Flåmu se dá vrátit tunelem za 40 minut.', 61.0470, 7.8122, 'https://commons.wikimedia.org/wiki/Special:FilePath/Borgund%20stavkirke.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Borgund%20stavkirke.jpg"}'::text[], 5);

  -- Lofoty – E10 mezi štíty a plážemi
  delete from public.routes where name = 'Lofoty – E10 mezi štíty a plážemi' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Lofoty – E10 mezi štíty a plážemi', 'Souostroví Lofoty je koncentrát toho nejlepšího z Norska na sto třiceti kilometrech: silnice E10 a její odbočky kličkují mezi žulovými štíty rostoucími přímo z moře, přes mosty spojující ostrovy a kolem rybářských vesnic s červenými chatami rorbuer na kůlech. Ze Svolværu zamíříte do galerijního Henningsvær s přístavem plným člunů, pak na bílou pláž Haukland a do časové kapsle Nusfjordu. Velkolepé finále obstará Reine s nejfotografovanějším panoramatem země a vesnička s nejkratším jménem na světě — Å, kde silnice doslova končí. V červnu a červenci se jezdí pod půlnočním sluncem, všude voní sušená treska a moře má barvu Karibiku. Jízdně jde o nenáročnou trasu; počítejte ale s letním provozem karavanů, bočním větrem na mostech a úzkými odbočkami k plážím.', 'poi', 130, 210, 'easy',
     '[{"lat": 68.2343, "lng": 14.5681, "label": "Start: Svolvær"}, {"lat": 68.1550, "lng": 14.2038, "label": "Henningsvær"}, {"lat": 68.2010, "lng": 13.5220, "label": "Hauklandstranda"}, {"lat": 68.0340, "lng": 13.3510, "label": "Nusfjord"}, {"lat": 67.9320, "lng": 13.0880, "label": "Reine"}, {"lat": 67.8790, "lng": 12.9770, "label": "Cíl: Å i Lofoten"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=68.2343,14.5681&destination=67.8790,12.9770&travelmode=driving&waypoints=68.1550,14.2038%7C68.2010,13.5220%7C68.0340,13.3510%7C67.9320,13.0880', 'https://commons.wikimedia.org/wiki/Special:FilePath/Reine.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svolv%C3%A6r.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Henningsv%C3%A6r.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Henningsv%C3%A6r%20havn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hauklandstranda.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nusfjord.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Reine.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%85%20i%20Lofoten.jpg"}'::text[], '{"Svolvær","Henningsvær","Restaurace: Fiskekrogen (Henningsvær)","Hauklandstranda","Nusfjord","Reine","Å i Lofoten"}'::text[], '{"NO"}'::text[], false, 4700, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Svolvær', 'Hlavní město Lofot s přístavem pod skalní věží Svolværgeita, na kterou horolezci skáčou mezi jejími „rohy". Dobrá základna s hotely, půjčovnami a trajektem na pevninu. Odsud startuje celá lofotská jízda na jihozápad.', 68.2343, 14.5681, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svolv%C3%A6r.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svolv%C3%A6r.jpg"}'::text[], 0),
    (v_route, 'Henningsvær', 'Rybářská vesnice roztroušená po ostrůvcích na konci úzké silničky pod stěnou hory Vågakallen — přezdívá se jí Benátky severu. Proslavil ji fotbalový plácek na skalním ostrůvku, jeden z nejfotografovanějších na světě. Galerie, kavárny a přístav plný člunů lákají ke korzování.', 68.1550, 14.2038, 'https://commons.wikimedia.org/wiki/Special:FilePath/Henningsv%C3%A6r.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Henningsv%C3%A6r.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Fiskekrogen (Henningsvær)', 'Legendární rybí restaurace přímo na molu henningsværského přístavu, oblíbená i norskou královskou rodinou. Vyhlášená rybí polévka, treska skrei a mořské plody z denního úlovku; hodnocení dlouhodobě výborné. Ideální oběd uprostřed lofotské etapy.', 68.1556, 14.2050, 'https://commons.wikimedia.org/wiki/Special:FilePath/Henningsv%C3%A6r%20havn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Henningsv%C3%A6r%20havn.jpg"}'::text[], 2),
    (v_route, 'Hauklandstranda', 'Bílá písečná pláž s průzračnou tyrkysovou vodou, pravidelně volená nejkrásnější plaží Norska. Kolem vede úzká pobřežní silnička do sousední zátoky Uttakleiv — krátký, ale nádherný vyhlídkový úsek. Zaparkujte, projděte se po písku a nechte si vyrazit dech kontrastem hor a moře.', 68.2010, 13.5220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hauklandstranda.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hauklandstranda.jpg"}'::text[], 3),
    (v_route, 'Nusfjord', 'Jedna z nejstarších a nejzachovalejších rybářských osad Norska, schovaná v úzké zátoce na konci odbočky z E10. Červené rorbuer na kůlech, stará pekárna a sušáky na tresky — časová kapsle z 19. století. Za vjezd do vesnice se v sezóně platí drobné vstupné, ale stojí za to.', 68.0340, 13.3510, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nusfjord.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nusfjord.jpg"}'::text[], 4),
    (v_route, 'Reine', 'Vesnice na skalnatém poloostrově uprostřed Reinefjordu, obklopená věncem špičatých štítů — pravděpodobně nejfotografovanější scenérie Norska. Cestou sem přejedete fotogenické mosty přes Hamnøy, kde červené chaty stojí přímo nad příbojem. Kdo má čas, vyběhne na vyhlídku Reinebringen (velmi strmé schody).', 67.9320, 13.0880, 'https://commons.wikimedia.org/wiki/Special:FilePath/Reine.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Reine.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hamn%C3%B8y.jpg"}'::text[], 5),
    (v_route, 'Å i Lofoten', 'Vesnice s nejkratším jménem na světě a doslovný konec silnice E10 — dál už je jen moře. Muzeum sušených tresek, stará pekárna s vyhlášenými skořicovými šneky a přístav s rorbuer. Symbolické místo na závěrečnou fotku: dojeli jste na konec Lofot.', 67.8790, 12.9770, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%85%20i%20Lofoten.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%85%20i%20Lofoten.jpg"}'::text[], 6);

end $$;
