-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — ŠVÉDSKO (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Švédsko – Skåne: Ales stenar a Kullaberg
  delete from public.routes where name = 'Švédsko – Skåne: Ales stenar a Kullaberg' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Skåne: Ales stenar a Kullaberg', 'Velký okruh nejjižnější švédskou provincií spojuje dvě naprosto odlišné tváře Skåne — skalnatý mys Kullaberg s majákem nad Öresundem a mystický kamenný kruh Ales stenar vysoko nad Baltem. Jede se po klidných silnicích mezi řepkovými poli, hrázděnými statky a bílými kostelíky, provoz je mimo Malmö minimální. Cestou stojí za zastávku katedrála v Lundu i středověká věž Kärnan v Helsingborgu, odkud je vidět až do Dánska. Závěr patří pobřeží Österlen, které Švédové sami považují za svou nejkrásnější krajinu. Nejlepší období je květen až září; u moře počítej s větrem a na jaře se žlutými koberci řepky, které lákají k fotopauzám. Silnice jsou v perfektním stavu, jen dodržuj přísné švédské limity.', 'loop', 360, 400, 'easy',
     '[{"lat": 55.6050, "lng": 13.0038, "label": "Start: Malmö"}, {"lat": 55.7047, "lng": 13.1932, "label": "Lund"}, {"lat": 56.0465, "lng": 12.6945, "label": "Helsingborg"}, {"lat": 56.2870, "lng": 12.4980, "label": "Mölle – Kullaberg"}, {"lat": 55.4295, "lng": 13.8204, "label": "Ystad"}, {"lat": 55.3855, "lng": 14.0533, "label": "Kåseberga"}, {"lat": 55.6050, "lng": 13.0038, "label": "Cíl: Malmö"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=55.6050,13.0038&destination=55.6050,13.0038&travelmode=driving&waypoints=55.7047,13.1932%7C56.0465,12.6945%7C56.2870,12.4980%7C55.4295,13.8204%7C55.3855,14.0533', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ales_stenar_bred.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turning_Torso.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lunds_domkyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%A4rnan.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kullens_fyr.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ales_stenar_bred.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Glimmingehus.jpg"}'::text[], '{"Turning Torso (Malmö)","Katedrála v Lundu","Věž Kärnan (Helsingborg)","Maják Kullens fyr","Ales stenar","Hrad Glimmingehus"}'::text[], '{"SE"}'::text[], false, 5110, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Turning Torso (Malmö)', 'Ikonický zkroucený mrakodrap od Santiaga Calatravy je s 190 metry nejvyšší budovou Skandinávie a symbolem moderního Malmö. Stojí ve čtvrti Västra Hamnen přímo u moře — ideální místo na první kávu s výhledem na Öresundský most.', 55.6132, 12.9758, 'https://commons.wikimedia.org/wiki/Special:FilePath/Turning_Torso.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turning_Torso.jpg"}'::text[], 0),
    (v_route, 'Katedrála v Lundu', 'Románská katedrála z 12. století je nejvýznamnější středověkou stavbou Švédska. Uvnitř nezmeškej slavný astronomický orloj Horologium mirabile Lundense, který se dvakrát denně rozehraje. Univerzitní Lund kolem katedrály má atmosféru jako Oxford v malém.', 55.7047, 13.1932, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lunds_domkyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lunds_domkyrka.jpg"}'::text[], 1),
    (v_route, 'Věž Kärnan (Helsingborg)', 'Mohutná cihlová věž ze 14. století je posledním pozůstatkem dánského hradu, který střežil nejužší místo Öresundu. Z vrcholu je za jasného dne krásně vidět dánský Helsingør s hradem Kronborg — Hamletovým Elsinorem — jen 4 kilometry přes úžinu.', 56.0489, 12.6935, 'https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%A4rnan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%A4rnan.jpg"}'::text[], 2),
    (v_route, 'Maják Kullens fyr', 'Nejjasnější maják Skandinávie stojí na dramatickém skalnatém mysu Kullaberg vysoko nad mořem. Poslední kilometry k němu vedou úzkou zatáčkovitou silničkou přírodní rezervací — motorkářská lahůdka. Dole pod útesy se dají objevovat jeskyně a v moři občas zahlédneš sviňuchy.', 56.3009, 12.4520, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kullens_fyr.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kullens_fyr.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Store Thor (Ystad)', 'Vyhlášená restaurace ve sklepení středověké radnice na hlavním náměstí v Ystadu, městě známém z detektivek o komisaři Wallanderovi. Skvělá skånská kuchyně — vyzkoušej místní rybí speciality. V létě se sedí venku na dlážděném náměstí.', 55.4296, 13.8210, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ystads_r%C3%A5dhus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ystads_r%C3%A5dhus.jpg"}'::text[], 4),
    (v_route, 'Ales stenar', 'Největší kamenná loď Skandinávie — 59 balvanů ve tvaru lodi z doby železné — stojí na travnatém útesu 30 metrů nad mořem u vesničky Kåseberga. Magické místo, zvlášť večer, kdy se nad Baltem barví nebe. Od parkoviště je to 10 minut pěšky do kopce; dole v přístavu prodávají vyhlášené uzené ryby.', 55.3831, 14.0559, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ales_stenar_bred.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ales_stenar_bred.jpg"}'::text[], 5),
    (v_route, 'Hrad Glimmingehus', 'Nejzachovalejší středověká tvrz Skandinávie z roku 1499 vypadá přesně tak, jak si představuješ severský hrad — strohý kamenný blok s metr tlustými zdmi uprostřed polí. Podle pověstí tu straší víc duchů než kdekoli jinde ve Švédsku.', 55.4880, 14.2260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Glimmingehus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Glimmingehus.jpg"}'::text[], 6);

  -- Švédsko – Öland: ostrov větrných mlýnů a majáků
  delete from public.routes where name = 'Švédsko – Öland: ostrov větrných mlýnů a majáků' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Öland: ostrov větrných mlýnů a majáků', 'Objet celý Öland od majáku k majáku je jeden z nejpohodovějších motorkářských dnů ve Švédsku. Na ostrov se dostaneš po šestikilometrovém Ölandském mostě z Kalmaru a pak už tě čekají rovné pobřežní silničky, stovky dřevěných větrných mlýnů a vápencová step Stora Alvaret zapsaná na seznamu UNESCO. Provoz je mimo červencovou špičku minimální a moře máš skoro pořád na dohled. Krajina je plochá, ale právě ta nekonečná obloha a světlo dělají z Ölandu zážitek — ne nadarmo tu má letní sídlo švédská královská rodina. Nejlépe v červnu nebo září; pozor na silný boční vítr na mostě a na srnky za soumraku.', 'loop', 340, 360, 'easy',
     '[{"lat": 56.6634, "lng": 16.3568, "label": "Start: Kalmar"}, {"lat": 56.8790, "lng": 16.6567, "label": "Borgholm"}, {"lat": 57.3300, "lng": 17.0080, "label": "Byxelkrok"}, {"lat": 56.5530, "lng": 16.5230, "label": "Stora Alvaret"}, {"lat": 56.1980, "lng": 16.3990, "label": "Ottenby"}, {"lat": 56.6634, "lng": 16.3568, "label": "Cíl: Kalmar"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=56.6634,16.3568&destination=56.6634,16.3568&travelmode=driving&waypoints=56.8790,16.6567%7C57.3300,17.0080%7C56.5530,16.5230%7C56.1980,16.3990', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kalmar_slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kalmar_slott.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C3%96landsbron.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Borgholms_slott.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5nge_Erik.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Stora_Alvaret.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5nge_Jan.jpg"}'::text[], '{"Hrad Kalmar","Ölandský most","Zřícenina Borgholm","Maják Långe Erik","Stora Alvaret","Maják Långe Jan (Ottenby)"}'::text[], '{"SE"}'::text[], false, 5120, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Kalmar', 'Renesanční vodní hrad na ostrůvku u starého města patří k nejkrásnějším ve Skandinávii — právě tady byla roku 1397 podepsána Kalmarská unie spojující Švédsko, Dánsko a Norsko. Perfektní start okruhu, hned za hradem začíná nájezd na Ölandský most.', 56.6644, 16.3550, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kalmar_slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kalmar_slott.jpg"}'::text[], 0),
    (v_route, 'Ölandský most', 'Šest kilometrů dlouhý most z roku 1972 byl kdysi nejdelší v Evropě. Přejezd nad Kalmarským průlivem s výhledem na obě pobřeží je zážitek sám o sobě — jen se pevně drž, při silném západním větru to na vrcholu mostního oblouku pořádně fouká.', 56.6790, 16.4230, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%96landsbron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C3%96landsbron.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Hotell Borgholm (Borgholm)', 'Restaurace legendární šéfkuchařky Karin Fransson je gastronomickou institucí ostrova — moderní švédská kuchyně s bylinkami z vlastní zahrady. Borgholm je zároveň příjemné letoviskové městečko na kávu a procházku po přístavu.', 56.8800, 16.6560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Borgholms_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Borgholms_kyrka.jpg"}'::text[], 2),
    (v_route, 'Zřícenina Borgholm', 'Monumentální ruina barokního zámku na vápencovém ostrohu je největší hradní zříceninou severní Evropy. Vyhořel roku 1806 a od té doby stojí jako kulisa — koncertoval tu i Roxette. Kousek vedle je letní vila královské rodiny Solliden.', 56.8730, 16.6420, 'https://commons.wikimedia.org/wiki/Special:FilePath/Borgholms_slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Borgholms_slott.jpg"}'::text[], 3),
    (v_route, 'Maják Långe Erik', 'Bílý kamenný maják z roku 1845 hlídá severní špici Ölandu u vesnice Byxelkrok. Cesta na sever vede kolem vápencových útvarů Byrums raukar a nejhezčích pláží ostrova. U majáku končí silnice — dál už je jen moře a ptáci.', 57.3690, 17.1030, 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5nge_Erik.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5nge_Erik.jpg"}'::text[], 4),
    (v_route, 'Stora Alvaret', 'Největší vápencová step Evropy pokrývá čtvrtinu ostrova a je zapsaná na seznamu UNESCO. Silnička napříč alvarem u Möckelmossenu je surreálná jízda krajinou bez jediného stromu, kde kvetou orchideje a pasou se ovce. Zastav a vypni motor — to ticho stojí za to.', 56.5530, 16.5230, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stora_Alvaret.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stora_Alvaret.jpg"}'::text[], 5),
    (v_route, 'Maják Långe Jan (Ottenby)', 'Nejvyšší maják Skandinávie (42 m) stojí na jižním cípu ostrova uprostřed ptačí rezervace Ottenby — během tahů tu protahují miliony ptáků. Vyjdi 197 schodů nahoru, výhled na celý jižní Öland je odměnou.', 56.1975, 16.3995, 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5nge_Jan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A5nge_Jan.jpg"}'::text[], 6);

  -- Švédsko – Gotland: Visby a vápencové rauky
  delete from public.routes where name = 'Švédsko – Gotland: Visby a vápencové rauky' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Gotland: Visby a vápencové rauky', 'Gotland je motorkářský ráj uprostřed Baltu — na ostrov tě z Nynäshamnu nebo Oskarshamnu přiveze trajekt (motorku vezmou bez problémů) a pak tě čekají prázdné silnice mezi vápencovými skalami, středověkými kostely a poli vlčích máků. Okruh z hanzovního Visby, města UNESCO obehnaného třiapůlkilometrovou hradbou, projede podél západního pobřeží k raukům u Lickershamnu a přes východní pláže až k jižnímu mysu Hoburgen. Rauky — bizarní vápencové věže vysoké až 12 metrů — nikde jinde v Evropě v takové koncentraci neuvidíš. Silnice jsou úzké, ale kvalitní a téměř bez provozu. Ideální je červen a začátek září; v půlce srpna počítej s návalem během týdne Medeltidsveckan.', 'loop', 250, 300, 'easy',
     '[{"lat": 57.6370, "lng": 18.2948, "label": "Start: Visby"}, {"lat": 57.7440, "lng": 18.4060, "label": "Lummelunda"}, {"lat": 57.8290, "lng": 18.5230, "label": "Lickershamn"}, {"lat": 57.3260, "lng": 18.7080, "label": "Ljugarn"}, {"lat": 56.9210, "lng": 18.1440, "label": "Hoburgen"}, {"lat": 57.6370, "lng": 18.2948, "label": "Cíl: Visby"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=57.6370,18.2948&destination=57.6370,18.2948&travelmode=driving&waypoints=57.7440,18.4060%7C57.8290,18.5230%7C57.3260,18.7080%7C56.9210,18.1440', 'https://commons.wikimedia.org/wiki/Special:FilePath/Visby_ringmur.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Visby_ringmur.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lummelundagrottan.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lickershamn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Folhammar.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hoburgsgubben.jpg"}'::text[], '{"Hradby Visby","Jeskyně Lummelunda","Rauk Jungfrun (Lickershamn)","Rauky Folhammar (Ljugarn)","Hoburgsgubben"}'::text[], '{"SE"}'::text[], false, 5130, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hradby Visby', 'Nejzachovalejší městské opevnění severní Evropy — 3,4 km hradeb s 27 věžemi obepíná hanzovní město plné růží, kostelních ruin a středověkých kupeckých domů. Celé Visby je na seznamu UNESCO. Projdi se po hradbách večer, kdy se z města vytratí denní návštěvníci.', 57.6410, 18.2920, 'https://commons.wikimedia.org/wiki/Special:FilePath/Visby_ringmur.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Visby_ringmur.jpg"}'::text[], 0),
    (v_route, 'Jeskyně Lummelunda', 'Čtyřkilometrový jeskynní systém s krápníky a podzemní řekou, jedna z nejdelších jeskyní Švédska. Objevily ji ve 50. letech tři místní kluci — jejich příběh vypráví expozice u vchodu. Příjemné ochlazení v horkém dni, uvnitř je stálých 8 °C.', 57.7440, 18.4060, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lummelundagrottan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lummelundagrottan.jpg"}'::text[], 1),
    (v_route, 'Rauk Jungfrun (Lickershamn)', 'Panna — nejvyšší rauk Gotlandu, 12 metrů vysoká vápencová věž na útesu nad rybářskou vesničkou Lickershamn. Krátká procházka po pobřežní pěšině s výhledem na celé západní pobřeží. Podle legendy tu zkameněla dívka čekající na svého milého.', 57.8330, 18.5190, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lickershamn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lickershamn.jpg"}'::text[], 2),
    (v_route, 'Rauky Folhammar (Ljugarn)', 'Nejfotogeničtější raukové pole východního pobřeží — desítky vápencových věží přímo v příboji u letoviska Ljugarn. Při západu slunce vrhají skály dlouhé stíny přes oblázkovou pláž; ideální místo na piknik z místní pekárny.', 57.3430, 18.7280, 'https://commons.wikimedia.org/wiki/Special:FilePath/Folhammar.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Folhammar.jpg"}'::text[], 3),
    (v_route, 'Hoburgsgubben', 'Stařec z Hoburgu — nejslavnější rauk Švédska na jižním mysu ostrova, který z profilu připomíná obří kamennou hlavu. Kolem útesy, maják a výhled na otevřené moře; sem už jezdí jen ti, kdo Gotland objedou celý. Silnička na mys je zábavně zvlněná.', 56.9210, 18.1440, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hoburgsgubben.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hoburgsgubben.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Bakfickan (Visby)', 'Legendární rybí bistro na hlavním náměstí Stora Torget uvnitř hradeb — čerstvé ryby a mušle z Baltu, žádné zbytečnosti. Večer si rezervuj místo, bývá plno. Perfektní tečka za okruhem ostrova.', 57.6366, 18.2932, 'https://commons.wikimedia.org/wiki/Special:FilePath/Visby_domkyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Visby_domkyrka.jpg"}'::text[], 5);

  -- Švédsko – Velký okruh kolem Vätternu
  delete from public.routes where name = 'Švédsko – Velký okruh kolem Vätternu' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Velký okruh kolem Vätternu', 'Objet druhé největší švédské jezero je klasika, kterou si každý rok dávají tisíce cyklistů — na motorce si ji ale vychutnáš mnohem víc. Východní břeh nabízí panoramatickou jízdu vysoko nad hladinou kolem Gränny a zříceniny Brahehus, západní břeh zase idylická dřevěná městečka Hjo a Askersund. Cestou potkáš klášterní Vadstenu, Göta kanál v Motale i mohutnou pevnost Karlsborg. Voda Vätternu je tak čistá, že se pije bez úpravy, a za jasného dne dohlédneš přes jezero na protější břeh vzdálený 30 kilometrů. Jede se celý den v pohodovém tempu po kvalitních silnicích; nejhezčí je červen se světlem dlouho do noci. Pozor jen na hustší provoz na E4 u Jönköpingu — co nejdřív z ní sjeď na starou pobřežní silnici.', 'loop', 300, 330, 'easy',
     '[{"lat": 57.7815, "lng": 14.1562, "label": "Start: Jönköping"}, {"lat": 58.0250, "lng": 14.4670, "label": "Gränna"}, {"lat": 58.4480, "lng": 14.8900, "label": "Vadstena"}, {"lat": 58.5370, "lng": 15.0360, "label": "Motala"}, {"lat": 58.5360, "lng": 14.5060, "label": "Karlsborg"}, {"lat": 58.3020, "lng": 14.2900, "label": "Hjo"}, {"lat": 57.7815, "lng": 14.1562, "label": "Cíl: Jönköping"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=57.7815,14.1562&destination=57.7815,14.1562&travelmode=driving&waypoints=58.0250,14.4670%7C58.4480,14.8900%7C58.5370,15.0360%7C58.5360,14.5060%7C58.3020,14.2900', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vadstena_slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gyllene_Uttern.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gr%C3%A4nna_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brahehus.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vadstena_slott.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/G%C3%B6ta_kanal.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Karlsborgs_f%C3%A4stning.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hjo_kyrka.jpg"}'::text[], '{"Restaurace: Gyllene Uttern (Gränna)","Gränna – městečko polkagrisů","Zřícenina Brahehus","Vadstena – zámek a klášter","Göta kanál (Motala)","Pevnost Karlsborg","Hjo – dřevěné městečko"}'::text[], '{"SE"}'::text[], false, 5140, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Restaurace: Gyllene Uttern (Gränna)', 'Zlatá vydra — historický hostinec z roku 1935 na útesu vysoko nad Vätternem, s nejhezčí restaurační vyhlídkou celého okruhu. Klasická švédská kuchyně a okna přímo na jezero a ostrov Visingsö. Oblíbená zastávka motorkářů už po generace.', 58.0080, 14.4560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gyllene_Uttern.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gyllene_Uttern.jpg"}'::text[], 0),
    (v_route, 'Gränna – městečko polkagrisů', 'Malebné městečko pod útesem je rodištěm červenobílých mátových tyčinek polkagris — v desítce místních manufaktur uvidíš, jak se točí ručně, a ochutnáš je ještě teplé. Z přístavu jezdí trajekt na ostrov Visingsö s ruinami hradu rodu Brahe.', 58.0250, 14.4670, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gr%C3%A4nna_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gr%C3%A4nna_kyrka.jpg"}'::text[], 1),
    (v_route, 'Zřícenina Brahehus', 'Ruina zámku ze 17. století trůní na skále 260 metrů nad jezerem — výhled na Vättern a Visingsö patří k nejfotografovanějším ve Švédsku. Přístup je z odpočívky na E4, ale krásnější je stará silnička od Gränny.', 58.0410, 14.4670, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brahehus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brahehus.jpg"}'::text[], 2),
    (v_route, 'Vadstena – zámek a klášter', 'Renesanční vodní zámek Gustava Vasy a klášter svaté Birgitty dělají z Vadsteny duchovní i historické srdce Vätternu. Středověké uličky vedou přímo k jezernímu přístavu; zámecký příkop obývají labutě. Ideální delší pauza v půlce okruhu.', 58.4485, 14.8870, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vadstena_slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vadstena_slott.jpg"}'::text[], 3),
    (v_route, 'Göta kanál (Motala)', 'V Motale, hlavním městě Göta kanálu, vplouvá slavná vodní cesta do Vätternu. Sleduj lodě v ručně obsluhovaných zdymadlech, projdi se po nábřeží, kde kanál lemují staré kapitánské vily, a mrkni do muzea motorismu s veterány.', 58.5390, 15.0300, 'https://commons.wikimedia.org/wiki/Special:FilePath/G%C3%B6ta_kanal.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/G%C3%B6ta_kanal.jpg"}'::text[], 4),
    (v_route, 'Pevnost Karlsborg', 'Gigantická pevnost z 19. století měla být záložním hlavním městem Švédska — hradby dlouhé 5 km, kasárna pro 8 000 mužů a vlastní kostel. Stavěla se 90 let a po dokončení už byla vojensky zastaralá. Projet branami pevnosti na motorce je zážitek.', 58.5360, 14.5100, 'https://commons.wikimedia.org/wiki/Special:FilePath/Karlsborgs_f%C3%A4stning.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Karlsborgs_f%C3%A4stning.jpg"}'::text[], 5),
    (v_route, 'Hjo – dřevěné městečko', 'Jedno ze tří švédských měst s ochrannou známkou za zachovalou dřevěnou zástavbu — pastelové vilky z 19. století, lázeňský park a přístav s parníkem Trafik z roku 1892. U jezera si dej zmrzlinu a kochej se výhledem přes Vättern na Omberg.', 58.3040, 14.2890, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hjo_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hjo_kyrka.jpg"}'::text[], 6);

  -- Švédsko – Bohuslän: žulové pobřeží a Smögen
  delete from public.routes where name = 'Švédsko – Bohuslän: žulové pobřeží a Smögen' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Bohuslän: žulové pobřeží a Smögen', 'Západní pobřeží mezi Göteborgem a norskou hranicí je souostroví z růžové žuly ohlazené ledovcem — tisíce holých ostrůvků, rybářské vesnice s červenými boudami na kůlech a mosty klenoucí se přes fjordy. Trasa uhýbá z hlavního tahu E6 na pobřežní silničky přes ostrovy Tjörn a Orust, kolem slavného mola ve Smögenu až k prehistorickým rytinám v Tanumu. Úzké silnice se vlní mezi skalami a zálivy, takže se nejede rychle, ale každá zatáčka otevře nový pohled na moře. Cestou ochutnáš to nejlepší ze švédských plodů moře — krevety, ústřice a humry se tu loví přímo před pobřežím. Nejkrásněji je tu v červnu a na přelomu srpna a září, kdy zmizí letní davy; počítej s větrem od moře a v sezóně s kolonami u mostů.', 'poi', 230, 300, 'medium',
     '[{"lat": 57.7089, "lng": 11.9746, "label": "Start: Göteborg"}, {"lat": 57.8880, "lng": 11.5820, "label": "Marstrand"}, {"lat": 58.0107, "lng": 11.8330, "label": "Tjörnbron"}, {"lat": 58.3550, "lng": 11.2270, "label": "Smögen"}, {"lat": 58.5990, "lng": 11.2840, "label": "Fjällbacka"}, {"lat": 58.7000, "lng": 11.3410, "label": "Vitlycke"}, {"lat": 58.9380, "lng": 11.1710, "label": "Cíl: Strömstad"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=57.7089,11.9746&destination=58.9380,11.1710&travelmode=driving&waypoints=57.8880,11.5820%7C58.0107,11.8330%7C58.3550,11.2270%7C58.5990,11.2840%7C58.7000,11.3410', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sm%C3%B6genbryggan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Carlstens_f%C3%A4stning.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tj%C3%B6rnbron.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A4desholmen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sm%C3%B6genbryggan.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fj%C3%A4llbacka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vitlyckeh%C3%A4llen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Str%C3%B6mstads_kyrka.jpg"}'::text[], '{"Pevnost Carlsten (Marstrand)","Most Tjörnbron","Restaurace: Salt & Sill (Klädesholmen)","Smögenbryggan","Fjällbacka","Skalní rytiny Vitlycke (UNESCO)","Strömstad"}'::text[], '{"SE"}'::text[], false, 5150, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Pevnost Carlsten (Marstrand)', 'Mohutná žulová pevnost ze 17. století korunuje ostrovní městečko Marstrand, kdysi nejhříšnější přístav Skandinávie. Na ostrov bez aut tě za pár minut přehoupne přívoz — motorku nech na hlídaném parkovišti. Z hradeb je výhled na celé souostroví.', 57.8860, 11.5810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Carlstens_f%C3%A4stning.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Carlstens_f%C3%A4stning.jpg"}'::text[], 0),
    (v_route, 'Most Tjörnbron', 'Elegantní zavěšený most se klene 45 metrů nad průlivem mezi ostrovy Stenungsön a Tjörn. Stojí na místě mostu, který se roku 1980 zřítil po nárazu lodi. Přejezd s výhledem na fjord plný plachetnic je jedním z vrcholů trasy.', 58.0107, 11.8330, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tj%C3%B6rnbron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tj%C3%B6rnbron.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Salt & Sill (Klädesholmen)', 'Slavná plovoucí restaurace na ostrůvku Klädesholmen, sleďovém ostrově s bílými rybářskými domky. Ochutnávkové prkénko sleďů v šesti úpravách je povinnost — sem se jezdí na oběd z celého západního pobřeží. Rezervace v sezóně nutná.', 57.9440, 11.5480, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A4desholmen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kl%C3%A4desholmen.jpg"}'::text[], 2),
    (v_route, 'Smögenbryggan', 'Kilometr dlouhé dřevěné molo lemované pestrobarevnými rybářskými boudami je nejslavnější promenádou švédského západu. Kup si kornout čerstvých krevet přímo z lodi a najdi si místo na sluncem vyhřáté žule. V červenci žije molo do pozdní noci.', 58.3546, 11.2260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sm%C3%B6genbryggan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sm%C3%B6genbryggan.jpg"}'::text[], 3),
    (v_route, 'Fjällbacka', 'Rybářská vesnice sevřená mezi mořem a 74 metrů vysokou skálou Vetteberget, proslavená detektivkami Camilly Läckberg a milovaná Ingrid Bergmanovou, která tu trávila léta. Vyšlápni si rozsedlinou Kungsklyftan na vrchol skály — výhled na souostroví je fantastický.', 58.5990, 11.2840, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fj%C3%A4llbacka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fj%C3%A4llbacka.jpg"}'::text[], 4),
    (v_route, 'Skalní rytiny Vitlycke (UNESCO)', 'Tisíce rytin z doby bronzové — lodě, lovci, býci i slavný Svatební pár — pokrývají žulové plotny u Tanumu a jsou zapsané na seznamu UNESCO. Rytiny jsou zvýrazněné červenou barvou a hned vedle stojí moderní muzeum s rekonstrukcí vesnice z doby bronzové.', 58.7000, 11.3410, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vitlyckeh%C3%A4llen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vitlyckeh%C3%A4llen.jpg"}'::text[], 5),
    (v_route, 'Strömstad', 'Sluncem zalité lázeňské městečko pár kilometrů od norské hranice je cílem etapy — přístav plný lodí, žulové ostrůvky souostroví Koster na obzoru a nejvíc slunečních hodin ve Švédsku. Odsud se dá pokračovat rovnou do norského Osla.', 58.9380, 11.1710, 'https://commons.wikimedia.org/wiki/Special:FilePath/Str%C3%B6mstads_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Str%C3%B6mstads_kyrka.jpg"}'::text[], 6);

  -- Švédsko – Dalarna: okruh kolem jezera Siljan
  delete from public.routes where name = 'Švédsko – Dalarna: okruh kolem jezera Siljan' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Dalarna: okruh kolem jezera Siljan', 'Siljan je jezero v kráteru po dopadu meteoritu a jeho objetí je koncentrát všeho, co si představíš pod pojmem Švédsko — červené chalupy se slunečnicemi, dřevění koníci dalahäst, zvonice nad jezerem a březové aleje. Okruh spojuje Moru s ateliérem malíře Zorna, manufaktury na koníky v Nusnäs, molo v Rättviku i pohlednicovou vesničku Tällberg na kopci nad hladinou. Ze západního břehu se vyplatí odbočka na vyhlídku Gesundaberget a na závěr srdce medvědího kraje v Orse. Silnice kopírují břeh a příjemně se vlní, provoz je klidný a odpočívadel s výhledem bezpočet. Nejhezčí je doba kolem midsommaru, kdy se u jezera slaví u májek v krojích — a taky nejrušnější. Pozor na losy, zvlášť za šera na lesních úsecích u Orsy.', 'loop', 190, 240, 'easy',
     '[{"lat": 61.0046, "lng": 14.5430, "label": "Start: Mora"}, {"lat": 60.9560, "lng": 14.6640, "label": "Nusnäs"}, {"lat": 60.8830, "lng": 15.1190, "label": "Rättvik"}, {"lat": 60.8230, "lng": 15.0250, "label": "Tällberg"}, {"lat": 60.7310, "lng": 14.9990, "label": "Leksand"}, {"lat": 60.9010, "lng": 14.5220, "label": "Gesunda"}, {"lat": 61.1190, "lng": 14.6180, "label": "Orsa"}, {"lat": 61.0046, "lng": 14.5430, "label": "Cíl: Mora"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=61.0046,14.5430&destination=61.0046,14.5430&travelmode=driving&waypoints=60.9560,14.6640%7C60.8830,15.1190%7C60.7310,14.9990%7C60.9010,14.5220%7C61.1190,14.6180', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dalah%C3%A4st.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zorng%C3%A5rden.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dalah%C3%A4st.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%A4ttviks_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%A4llberg.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Leksands_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gesundaberget.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Orsa_Gr%C3%B6nklitt.jpg"}'::text[], '{"Zorngården (Mora)","Dřevění koníci v Nusnäs","Rättvik – Långbryggan","Restaurace: Klockargården (Tällberg)","Leksand","Vyhlídka Gesundaberget","Medvědí park Orsa"}'::text[], '{"SE"}'::text[], false, 5160, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zorngården (Mora)', 'Dům a ateliér Anderse Zorna, nejslavnějšího švédského malíře, stojí v centru Mory přesně tak, jak ho s manželkou Emmou opustili. Vedlejší muzeum vystavuje jeho světoznámé akty a portréty — maloval i tři americké prezidenty. Mora je zároveň cílem legendárního Vasova běhu.', 61.0060, 14.5390, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zorng%C3%A5rden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zorng%C3%A5rden.jpg"}'::text[], 0),
    (v_route, 'Dřevění koníci v Nusnäs', 'Ve vesničce Nusnäs se už sto let ručně vyřezávají a malují červení koníci dalahäst — nejznámější suvenýr Švédska. V dílnách Nils Olsson Hemslöjd se můžeš dívat řezbářům přes rameno a koupit koníka rovnou od zdroje, klidně i metrového.', 60.9560, 14.6640, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dalah%C3%A4st.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dalah%C3%A4st.jpg"}'::text[], 1),
    (v_route, 'Rättvik – Långbryggan', 'Nejdelší dřevěné molo Švédska vybíhá 628 metrů do jezera — projdi se až na konec, kde kdysi přistávaly parníky. Nad břehem stojí středověký kostel obklopený sto padesáti roubenými stájemi, do kterých farníci odstavovali koně při nedělní mši.', 60.8790, 15.1120, 'https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%A4ttviks_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%A4ttviks_kyrka.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Klockargården (Tällberg)', 'Rodinný hotel s vyhlášenou kuchyní z místních surovin ve vesničce Tällberg, nejfotogeničtější obci u Siljanu — samé staleté roubenky s výhledem na jezero. Na zahradě se v létě peče chleba v kamenné peci a hraje folklor.', 60.8230, 15.0250, 'https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%A4llberg.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%A4llberg.jpg"}'::text[], 3),
    (v_route, 'Leksand', 'Městečko na jižním cípu jezera je centrem dalarnského folkloru — o midsommaru tu staví největší májku ve Švédsku a k bohoslužbám se dodnes jezdí v dlouhých kostelních veslicích. Kostel s cibulovou bání nad ústím řeky Österdalälven patří k nejmalebnějším v zemi.', 60.7310, 14.9990, 'https://commons.wikimedia.org/wiki/Special:FilePath/Leksands_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Leksands_kyrka.jpg"}'::text[], 4),
    (v_route, 'Vyhlídka Gesundaberget', 'Z vrcholu hory nad západním břehem se otevírá nejlepší panorama celého kráteru Siljanu — jezero, ostrov Sollerön i lesy až k horizontu. Nahoru vede asfaltka k horní stanici lanovky. Pod horou leží vesnice Gesunda a přes hráze se dá přejet na ostrov Sollerön.', 60.9010, 14.5220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gesundaberget.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gesundaberget.jpg"}'::text[], 5),
    (v_route, 'Medvědí park Orsa', 'Největší medvědí park Evropy na svahu nad jezerem Orsasjön — medvědi hnědí, polární vlci, rysi i sibiřští tygři v obřích přírodních výbězích. Počítej aspoň se dvěma hodinami; areál Grönklitt nabízí i výhledovou restauraci.', 61.1550, 14.5220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Orsa_Gr%C3%B6nklitt.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Orsa_Gr%C3%B6nklitt.jpg"}'::text[], 6);

  -- Švédsko – Höga Kusten: most a NP Skuleskogen
  delete from public.routes where name = 'Švédsko – Höga Kusten: most a NP Skuleskogen' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Höga Kusten: most a NP Skuleskogen', 'Vysoké pobřeží mezi Härnösandem a Örnsköldsvikem je jediné místo na světě, kde se pevnina po době ledové zvedla o 286 metrů — vznikly tak strmé žulové kopce padající přímo do Botnického zálivu, krajina zapsaná na seznamu UNESCO. Trasa startuje přejezdem majestátního visutého mostu Högakustenbron a pak uhýbá z E4 na úzké silničky poloostrova Nordingrå k rybářské vesničce Norrfällsviken. Vrcholem je národní park Skuleskogen s rozsedlinou Slåttdalsskrevan — 40 metrů hlubokou puklinou ve skále. Silnice se tu vlní a houpou jako málokde ve Švédsku, výhledy na záliv se střídají s hlubokými lesy. Nejlepší období je od června do začátku září; na vedlejších cestách počítej místy s hrubším asfaltem a v lese s losy.', 'poi', 160, 210, 'medium',
     '[{"lat": 62.6323, "lng": 17.9379, "label": "Start: Härnösand"}, {"lat": 62.7990, "lng": 17.9390, "label": "Högakustenbron"}, {"lat": 62.9640, "lng": 18.2620, "label": "Norrfällsviken"}, {"lat": 63.0570, "lng": 18.3350, "label": "Docksta"}, {"lat": 63.0970, "lng": 18.5030, "label": "Skuleskogen"}, {"lat": 63.2909, "lng": 18.7153, "label": "Cíl: Örnsköldsvik"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=62.6323,17.9379&destination=63.2909,18.7153&travelmode=driving&waypoints=62.7990,17.9390%7C62.9640,18.2620%7C63.0570,18.3350%7C63.0970,18.5030', 'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6gakustenbron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4rn%C3%B6sands_domkyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6gakustenbron.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mannaminne.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Norrf%C3%A4llsviken.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skuleberget.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sl%C3%A5ttdalsskrevan.jpg"}'::text[], '{"Härnösand","Most Högakustenbron","Mannaminne (Häggvik)","Norrfällsviken","Skuleberget","Slåttdalsskrevan (NP Skuleskogen)"}'::text[], '{"SE"}'::text[], false, 5170, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Härnösand', 'Brána Vysokého pobřeží s bílou empírovou katedrálou, nejmenší ve Švédsku. Doplň nádrž a zásoby — na poloostrovech dál na severu už je obchodů málo. Ve městě sídlí i destilerie oceňovaného ginu Hernö.', 62.6323, 17.9379, 'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4rn%C3%B6sands_domkyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%A4rn%C3%B6sands_domkyrka.jpg"}'::text[], 0),
    (v_route, 'Most Högakustenbron', 'Visutý most přes ústí řeky Ångermanälven s pylony vysokými 180 metrů je jedním z nejdelších na světě — hlavní pole měří 1210 metrů. Přejezd na motorce nad širokou řekou bere dech; nejlepší fotky jsou z vyhlídky u severního předmostí.', 62.7990, 17.9390, 'https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6gakustenbron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/H%C3%B6gakustenbron.jpg"}'::text[], 1),
    (v_route, 'Mannaminne (Häggvik)', 'Svérázný skanzen umělce Anderse Åberga na poloostrově Nordingrå — desítky budov od norrlandských statků po maďarský kostelík, plné lodí, aut a kuriozit. Kavárna s domácími koláči a výhledem na záliv je ideální dopolední pauza.', 62.9640, 18.1900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mannaminne.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mannaminne.jpg"}'::text[], 2),
    (v_route, 'Norrfällsviken', 'Rybářská vesnice na samém konci poloostrova — červené boudy z 16. století, kaple na skále a hladké žulové plotny, po kterých se dá dojít až k moři. V místní udírně kup zauzeného lososa; tady chutná Vysoké pobřeží nejlíp.', 62.9640, 18.2620, 'https://commons.wikimedia.org/wiki/Special:FilePath/Norrf%C3%A4llsviken.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Norrf%C3%A4llsviken.jpg"}'::text[], 3),
    (v_route, 'Skuleberget', 'Skalní stěna nad Docksta, symbol Vysokého pobřeží — na vrchol 295 metrů nad mořem vede sedačková lanovka i via ferrata. Kdysi to byl mořský útes; dnes z vrcholu přehlédneš celé souostroví. U paty hory je návštěvnické centrum s expozicí o zdvihu pevniny.', 63.0670, 18.3560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skuleberget.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skuleberget.jpg"}'::text[], 4),
    (v_route, 'Slåttdalsskrevan (NP Skuleskogen)', 'Čtyřicet metrů hluboká a jen sedm metrů široká skalní rozsedlina je nejslavnějším místem národního parku Skuleskogen. Od západního vstupu k ní vede značená stezka pralesem a po žulových plotnách, tam a zpět asi dvě hodiny — pohorky s sebou, odměnou je výhled na záliv z náhorní plošiny.', 63.0870, 18.5330, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sl%C3%A5ttdalsskrevan.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sl%C3%A5ttdalsskrevan.jpg"}'::text[], 5);

  -- Švédsko – Värmland: Klarälven a jezero Fryken
  delete from public.routes where name = 'Švédsko – Värmland: Klarälven a jezero Fryken' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Värmland: Klarälven a jezero Fryken', 'Värmland je kraj spisovatelů, hlubokých lesů a dlouhých jezer — a tenhle okruh z Karlstadu ho projede celý. Nejdřív podél dlouhého jezera Fryken krajinou Gösty Berlinga, kolem statku nobelistky Selmy Lagerlöfové v Mårbace a sochařského parku Rottneros, s výšlapem na vyhlídku Tossebergsklätten vysoko nad hladinou. V Torsby se okruh stočí na jih a vrací se údolím řeky Klarälven, po níž se ještě v 90. letech plavilo dřevo — silnice 62 kopíruje její meandry desítky kilometrů. Provoz je řídký, asfalt kvalitní a zatáčky plynulé, ideální na pohodové tempo. Nejhezčí je od června do září; za soumraku zpomal, údolí Klarälvenu je království losů.', 'loop', 270, 310, 'easy',
     '[{"lat": 59.3793, "lng": 13.5036, "label": "Start: Karlstad"}, {"lat": 59.7620, "lng": 13.2680, "label": "Mårbacka"}, {"lat": 59.8360, "lng": 13.1430, "label": "Sunne"}, {"lat": 60.1360, "lng": 12.9990, "label": "Torsby"}, {"lat": 60.1730, "lng": 13.4920, "label": "Ekshärad"}, {"lat": 59.7770, "lng": 13.4260, "label": "Ransäter"}, {"lat": 59.3793, "lng": 13.5036, "label": "Cíl: Karlstad"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=59.3793,13.5036&destination=59.3793,13.5036&travelmode=driving&waypoints=59.7620,13.2680%7C59.8360,13.1430%7C60.1360,12.9990%7C60.1730,13.4920%7C59.7770,13.4260', 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%A5rbacka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Karlstads_domkyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%A5rbacka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rottneros_Park.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sunne_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tossebergskl%C3%A4tten.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Eksh%C3%A4rads_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Klar%C3%A4lven.jpg"}'::text[], '{"Karlstad","Mårbacka – statek Selmy Lagerlöfové","Park Rottneros","Restaurace: Broby Gästgivaregård (Sunne)","Vyhlídka Tossebergsklätten","Kostel v Ekshäradu","Meandry řeky Klarälven"}'::text[], '{"SE"}'::text[], false, 5180, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Karlstad', 'Město u ústí Klarälvenu do Vänernu má ve znaku usměvavé slunce — je prý nejslunečnější ve Švédsku. Před startem se projdi po nábřeží k nejdelšímu kamennému mostu v zemi, dvanáctiobloukovému Östra bron z 18. století.', 59.3793, 13.5036, 'https://commons.wikimedia.org/wiki/Special:FilePath/Karlstads_domkyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Karlstads_domkyrka.jpg"}'::text[], 0),
    (v_route, 'Mårbacka – statek Selmy Lagerlöfové', 'Rodný statek první ženy s Nobelovou cenou za literaturu, autorky Podivuhodné cesty Nilse Holgerssona. Bílý dům s empírovým sloupovím si nechala přestavět z honoráře a dodnes je zařízený, jak ho roku 1940 opustila. Kavárna na zahradě peče podle jejích receptů.', 59.7620, 13.2680, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%A5rbacka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%A5rbacka.jpg"}'::text[], 1),
    (v_route, 'Park Rottneros', 'Zámecký park se čtyřiceti hektary zahrad a stovkou soch — Milles, Vigeland i antické kopie mezi rododendrony nad jezerem Fryken. Zámek Rottneros je předobrazem Ekeby z Gösty Berlinga Selmy Lagerlöfové.', 59.7940, 13.1160, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rottneros_Park.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rottneros_Park.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Broby Gästgivaregård (Sunne)', 'Historický zájezdní hostinec v centru Sunne vaří poctivou värmlandskou kuchyni — losí maso, síh z Frykenu a domácí moučníky. Hostinec tu stojí od 17. století a je ideální obědovou zastávkou v půlce okruhu.', 59.8360, 13.1430, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sunne_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sunne_kyrka.jpg"}'::text[], 3),
    (v_route, 'Vyhlídka Tossebergsklätten', 'Skalní vrch 343 metrů nad jezerem Fryken s kruhovým výhledem na celé údolí — v jasném dni dohlédneš přes tři jezera až k norské hranici. Nahoru vede úzká asfaltka plná serpentin, nejzábavnější kilometry celého okruhu. V románu Gösta Berling se vrch jmenuje Gurlita.', 59.9410, 13.0650, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tossebergskl%C3%A4tten.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tossebergskl%C3%A4tten.jpg"}'::text[], 4),
    (v_route, 'Kostel v Ekshäradu', 'Dřevěný kostel z roku 1688 nad Klarälvenem proslavil hřbitov s unikátními kovanými kříži ve tvaru stromů života — stovky jich tu zvoní ve větru. Jedno z nejzvláštnějších a nejatmosféričtějších míst Värmlandu.', 60.1730, 13.4920, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eksh%C3%A4rads_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eksh%C3%A4rads_kyrka.jpg"}'::text[], 5),
    (v_route, 'Meandry řeky Klarälven', 'Silnice 62 na jihu údolí kopíruje líné meandry řeky, po které se až do roku 1991 plavily klády — poslední splavovaná řeka Švédska. U Ransäteru stojí rodný statek skladatele a historika Erika Gustafa Geijera a v létě se tu dá půjčit vor a splout kus řeky po vzoru starých vorařů.', 59.7770, 13.4260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Klar%C3%A4lven.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Klar%C3%A4lven.jpg"}'::text[], 6);

  -- Švédsko – Stockholmské souostroví: Vaxholm a Dalarö
  delete from public.routes where name = 'Švédsko – Stockholmské souostroví: Vaxholm a Dalarö' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Stockholmské souostroví: Vaxholm a Dalarö', 'Stockholmské souostroví má 30 000 ostrovů a tenhle okruh posbírá ta nejkrásnější místa, kam se dá dojet po silnici — bez jediného trajektu. Z centra Stockholmu vede přes mosty do pevnostního městečka Vaxholm, pak na poloostrov Värmdö s porcelánkou Gustavsberg a do přístavu Stavsnäs, odkud vyplouvají lodě do vnějšího souostroví. Jižní část projede kapitánskou vesnici Dalarö a končí v přístavu Nynäshamn, odkud odplouvají trajekty na Gotland — okruh se tak dá spojit s gotlandskou trasou. Silnice se vlní mezi žulovými skalami, zálivy a borovicemi, moře je pořád na dosah. Nejlépe ve všední den mimo červencovou špičku, o víkendech tu bývá hustý výletní provoz; na jaře a na podzim počítej s kluzkým jehličím ve stínu lesa.', 'loop', 230, 300, 'easy',
     '[{"lat": 59.3293, "lng": 18.0686, "label": "Start: Stockholm"}, {"lat": 59.4030, "lng": 18.3510, "label": "Vaxholm"}, {"lat": 59.3270, "lng": 18.3860, "label": "Gustavsberg"}, {"lat": 59.2870, "lng": 18.6890, "label": "Stavsnäs"}, {"lat": 59.1320, "lng": 18.4080, "label": "Dalarö"}, {"lat": 58.9030, "lng": 17.9480, "label": "Nynäshamn"}, {"lat": 59.3293, "lng": 18.0686, "label": "Cíl: Stockholm"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=59.3293,18.0686&destination=59.3293,18.0686&travelmode=driving&waypoints=59.4030,18.3510%7C59.3270,18.3860%7C59.2870,18.6890%7C59.1320,18.4080%7C58.9030,17.9480', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_kastell.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stockholm_old_town_2002.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_kastell.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gustavsbergs_hamn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dalar%C3%B6_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nyn%C3%A4shamns_kyrka.jpg"}'::text[], '{"Gamla stan (Stockholm)","Pevnost Vaxholm","Restaurace: Hembygdsgårdens Café (Vaxholm)","Gustavsberg – porcelánka","Dalarö","Nynäshamn"}'::text[], '{"SE"}'::text[], false, 5190, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Gamla stan (Stockholm)', 'Staré město na ostrově mezi jezerem Mälaren a Baltem — křivolaké středověké uličky, královský palác a náměstí Stortorget s barevnými kupeckými domy. Vyraž brzy ráno, dokud jsou uličky prázdné, a pak už rovnou po mostech na východ do souostroví.', 59.3251, 18.0711, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stockholm_old_town_2002.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stockholm_old_town_2002.jpg"}'::text[], 0),
    (v_route, 'Pevnost Vaxholm', 'Kruhová pevnost z 19. století na ostrůvku uprostřed úžiny střežila lodní cestu do Stockholmu už od dob Gustava Vasy — odrazila Dány i ruskou flotilu. Z nábřeží Vaxholmu k ní pendluje malý přívoz; městečko samotné je plné dřevěných secesních vil a kaváren.', 59.4030, 18.3600, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_kastell.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_kastell.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Hembygdsgårdens Café (Vaxholm)', 'Kultovní kavárna ve staré rybářské usedlosti přímo u vody s výhledem na pevnost — domácí skořicoví šneci a princezdorty patří k nejlepším v okolí Stockholmu. V létě se sedí na skalách u mola.', 59.4060, 18.3560, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_kyrka.jpg"}'::text[], 2),
    (v_route, 'Gustavsberg – porcelánka', 'Přístavní čtvrť kolem slavné porcelánky z roku 1825, kde vznikal servis pro švédský královský dvůr. Dnes tu najdeš muzeum porcelánu, továrenské outlety, keramické ateliéry a kavárny ve starých tovární halách u zálivu.', 59.3270, 18.3860, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gustavsbergs_hamn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gustavsbergs_hamn.jpg"}'::text[], 3),
    (v_route, 'Dalarö', 'Bývalá celnice a kapitánská vesnice ze 17. století na skalách nad průlivem — dřevěné vily se zdobenými verandami, malý přístav a atmosféra starých časů souostroví. Ve vodách kolem leží desítky vraků včetně slavné lodi Anna Maria z roku 1709, ráj potápěčů.', 59.1320, 18.4080, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dalar%C3%B6_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dalar%C3%B6_kyrka.jpg"}'::text[], 4),
    (v_route, 'Nynäshamn', 'Přístavní město na jižním cípu souostroví, odkud vyplouvají trajekty na Gotland i do Polska. V přístavní tržnici u mola dostaneš vyhlášené uzené ryby — ideální závěr dne s výhledem na vyplouvající lodě, než se vrátíš po rychlé 73 do Stockholmu.', 58.9030, 17.9480, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nyn%C3%A4shamns_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nyn%C3%A4shamns_kyrka.jpg"}'::text[], 5);

  -- Švédsko – Vänern: Läckö, Kinnekulle a Trollhättan
  delete from public.routes where name = 'Švédsko – Vänern: Läckö, Kinnekulle a Trollhättan' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Švédsko – Vänern: Läckö, Kinnekulle a Trollhättan', 'Jižní břeh Vänernu, největšího jezera Evropské unie, schovává trojici klenotů: bílý pohádkový zámek Läckö na samém konci poloostrova Kållandsö, rozkvetlou stolovou horu Kinnekulle a průmyslovou katedrálu vodopádů a zdymadel v Trollhättanu. Okruh startuje u slavných trollhättanských vodopádů, pokračuje rovinatou krajinou k Lidköpingu a pak úzkými silničkami mezi zálivy na Kållandsö. Kinnekulle nabídne jediné pořádné stoupání široko daleko a výhled přes nekonečnou hladinu; dole pod horou stojí kostel v Husaby, kde byl pokřtěn první švédský král. Silnice jsou klidné a rychlé, ideální i pro méně zkušené jezdce. Nejkrásněji je tu v květnu, kdy na Kinnekulle kvetou třešňové sady a česnekové koberce; vodopády v Trollhättanu pouštějí naplno jen v určené časy — ověř si je předem.', 'loop', 250, 290, 'easy',
     '[{"lat": 58.2837, "lng": 12.2886, "label": "Start: Trollhättan"}, {"lat": 58.5035, "lng": 13.1577, "label": "Lidköping"}, {"lat": 58.6740, "lng": 13.2210, "label": "Zámek Läckö"}, {"lat": 58.5950, "lng": 13.3970, "label": "Kinnekulle"}, {"lat": 58.5380, "lng": 13.3820, "label": "Husaby"}, {"lat": 58.2837, "lng": 12.2886, "label": "Cíl: Trollhättan"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=58.2837,12.2886&destination=58.2837,12.2886&travelmode=driving&waypoints=58.5035,13.1577%7C58.6740,13.2210%7C58.5950,13.3970%7C58.5380,13.3820', 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A4ck%C3%B6_slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttefallen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttans_kyrka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lidk%C3%B6pings_r%C3%A5dhus.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A4ck%C3%B6_slott.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kinnekulle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Husaby_kyrka.jpg"}'::text[], '{"Vodopády a zdymadla Trollhättan","Restaurace: Albert Kök (Trollhättan)","Lidköping","Zámek Läckö","Stolová hora Kinnekulle","Kostel v Husaby"}'::text[], '{"SE"}'::text[], false, 5200, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vodopády a zdymadla Trollhättan', 'Řeka Göta älv tu padá o 32 metrů — když se v určené časy otevřou stavidla elektrárny, valí se kaňonem 300 000 litrů za sekundu a země se chvěje. Hned vedle stoupá kaskáda zdymadel Trollhätte kanálu ze tří staletí. Průmyslová romantika, jakou jinde nezažiješ.', 58.2760, 12.2720, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttefallen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttefallen.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Albert Kök (Trollhättan)', 'Restaurace ve vile z 19. století na skále přímo nad kanálem — moderní švédská kuchyně a terasa s výhledem na proplouvající lodě. Skvělé místo na pozdní oběd po návratu z okruhu, kuchyně patří k nejlepším v západním Švédsku.', 58.2700, 12.2740, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttans_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttans_kyrka.jpg"}'::text[], 1),
    (v_route, 'Lidköping', 'Město u zálivu Kinneviken s jedním z největších náměstí Švédska, kterému vévodí dřevěná radnice — původně lovecký zámeček přenesený sem roku 1672. Lidköping je domovem porcelánky Rörstrand, druhé nejstarší v Evropě, s muzeem a outletem.', 58.5035, 13.1577, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lidk%C3%B6pings_r%C3%A5dhus.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lidk%C3%B6pings_r%C3%A5dhus.jpg"}'::text[], 2),
    (v_route, 'Zámek Läckö', 'Bílý barokní zámek na skále nad hladinou Vänernu vypadá jako z pohádky — 250 komnat, hradní zahrada a přístav s plachetnicemi pod hradbami. Silnička na Kållandsö mezi zálivy a rybářskými vesničkami je zážitek sama o sobě; kousek před zámkem leží rybářský přístav Spiken s udírnami.', 58.6740, 13.2210, 'https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A4ck%C3%B6_slott.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A4ck%C3%B6_slott.jpg"}'::text[], 3),
    (v_route, 'Stolová hora Kinnekulle', 'Rozkvetlá hora — 306 metrů vysoká stolová hora nad Vänernem s vyhlídkovou věží na vrcholu, kam vede příjemná lesní asfaltka. Na jaře kvetou svahy třešněmi a medvědím česnekem; z věže přehlédneš jezero až k obzoru. Po cestě dolů stavěj u starých vápencových lomů.', 58.5950, 13.3970, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kinnekulle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kinnekulle.jpg"}'::text[], 4),
    (v_route, 'Kostel v Husaby', 'Kamenný kostel s mohutnou trojvěžovou západní věží z 11. století je kolébkou švédského křesťanství — u zdejšího pramene byl kolem roku 1000 pokřtěn první švédský král Olof Skötkonung. Jeho hrob najdeš hned u zdi kostela.', 58.5380, 13.3820, 'https://commons.wikimedia.org/wiki/Special:FilePath/Husaby_kyrka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Husaby_kyrka.jpg"}'::text[], 5);

end $$;
