-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — SLOVENSKO II (10 tras, sort 5310–5400)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Pieniny a Zamagurie – plte na Dunajci
  delete from public.routes where name = 'Pieniny a Zamagurie – plte na Dunajci' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Pieniny a Zamagurie – plte na Dunajci', 'Okruh nejsevernějším koutem Spiše vás zavede do kraje goralských roubenek, dřevěných kostelíků a divoké řeky Dunajec. Z Kežmarku stoupáte přes malebný Ždiar pod Belianskými Tatrami a po úzké silničce do Osturni, památkové rezervace lidové architektury táhnoucí se sedm kilometrů podél potoka. Následuje sjezd k Červenému Kláštoru, odkud vyplouvají tradiční vory – plte – do vápencového Prielomu Dunajca pod Tromi korunami. Zpáteční cesta vede podél polské hranice k mohutnému hradu Stará Ľubovňa a zvlněným Zamagurím zpět do Kežmarku. Nejlepší období je květen až září; počítejte s úzkými, místy záplatovanými silničkami, pomalými traktory a o víkendech s pěší turistikou kolem přístavišť plťařů.', 'loop', 130, 210, 'medium',
     '[{"lat": 49.1366, "lng": 20.4292, "label": "Start: Kežmarok"}, {"lat": 49.2717, "lng": 20.2661, "label": "Ždiar"}, {"lat": 49.3369, "lng": 20.2264, "label": "Osturňa"}, {"lat": 49.3946, "lng": 20.4224, "label": "Červený Kláštor"}, {"lat": 49.3025, "lng": 20.6903, "label": "Stará Ľubovňa"}, {"lat": 49.1366, "lng": 20.4292, "label": "Cíl: Kežmarok"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.1366,20.4292&destination=49.1366,20.4292&travelmode=driving&waypoints=49.2717,20.2661%7C49.3369,20.2264%7C49.3946,20.4224%7C49.3025,20.6903', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zdiar.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Osturna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cerven%C3%BD%20Kl%C3%A1%C5%A1tor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prielom%20Dunajca.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lubovniansky%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok.jpg"}'::text[], '{"Kežmarský hrad","Ždiar","Osturňa","Červený Kláštor","Prielom Dunajca – plte","Hrad Stará Ľubovňa","Restaurace: Hotel Hviezdoslav (Kežmarok)"}'::text[], '{"SK"}'::text[], false, 5310, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kežmarský hrad', 'Městský hrad ze 15. století přímo v centru svobodného královského města Kežmarok. Kousek od něj stojí dřevěný artikulární kostel zapsaný na seznamu UNESCO – celý z tisového a smrkového dřeva, bez jediného hřebíku. Ideální start okruhu s kávou na historickém náměstí.', 49.1394, 20.4319, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok%20hrad.jpg"}'::text[], 0),
    (v_route, 'Ždiar', 'Goralská obec pod Belianskými Tatrami proslulá malovanými roubenkami a živým folklórem. Silnice přes Ždiar patří k nejhezčím podtatranským úsekům – po pravé ruce se zvedá vápencová hradba Belianských Tater. Zastavte u vyhlídky nad obcí na jednu z nejfotografovanějších tatranských scenérií.', 49.2717, 20.2661, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zdiar.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zdiar.jpg"}'::text[], 1),
    (v_route, 'Osturňa', 'Nejzápadnější rusínská obec Slovenska a památková rezervace – sedm kilometrů dlouhá řada srubových usedlostí podél potoka. Úzká slepá silnička sem vede zvlněnou krajinou Spišské Magury a je zážitkem sama o sobě. Jeďte pomalu, potkáte tu více ovcí než aut.', 49.3369, 20.2264, 'https://commons.wikimedia.org/wiki/Special:FilePath/Osturna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Osturna.jpg"}'::text[], 2),
    (v_route, 'Červený Kláštor', 'Kartuziánský klášter ze 14. století na břehu Dunajce, spjatý s legendárním létajícím mnichem Cypriánem. Dnes je tu muzeum, bylinková zahrada a hlavní přístaviště tradičních plťí. Odsud vyplouvají vory do soutěsky – plavba trvá zhruba hodinu a půl a motorku můžete nechat na hlídaném parkovišti.', 49.3946, 20.4224, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cerven%C3%BD%20Kl%C3%A1%C5%A1tor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cerven%C3%BD%20Kl%C3%A1%C5%A1tor.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cerveny%20Klastor.jpg"}'::text[], 3),
    (v_route, 'Prielom Dunajca – plte', 'Devítikilometrový vápencový kaňon Dunajce mezi slovenskými a polskými Pieninami, nad nímž se tyčí trojzubý masiv Tri koruny. Řeka tu tvoří sedm ostrých meandrů sevřených tři sta metrů vysokými stěnami. Krátká zastávka na vyhlídce u silnice stojí za to i bez plavby na voru.', 49.3983, 20.4670, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prielom%20Dunajca.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prielom%20Dunajca.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pieniny%20Dunajec.jpg"}'::text[], 4),
    (v_route, 'Hrad Stará Ľubovňa', 'Mohutný pohraniční hrad nad údolím Popradu, kde byly za polského záboru ukrývány polské korunovační klenoty. Pod hradem leží skanzen s dřevěným řeckokatolickým kostelíkem a spišskými chalupami. Z hradeb je krásný výhled na Tatry i celé Zamagurie.', 49.3164, 20.6959, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lubovniansky%20hrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lubovniansky%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Stara%20Lubovna.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Hotel Hviezdoslav (Kežmarok)', 'Restaurace butikového hotelu v historickém domě přímo na hlavní ulici Kežmarku, pojmenovaného po básníku Hviezdoslavovi. Kuchyně kombinuje moderní gastronomii se spišskou klasikou – pirohy, jehněčí i tatranský pstruh. Hosté ji dlouhodobě řadí k nejlepším podnikům pod Tatrami, ideální tečka za okruhem.', 49.1352, 20.4276, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kezmarok.jpg"}'::text[], 6);

  -- Šariš – Bardejov a dřevěné kostelíky
  delete from public.routes where name = 'Šariš – Bardejov a dřevěné kostelíky' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Šariš – Bardejov a dřevěné kostelíky', 'Pohodový okruh krajem Šariše spojuje dvě historická města a to nejlepší z lidové sakrální architektury východního Slovenska. Z Prešova vyjedete údolím Torysy kolem zříceniny Šarišského hradu a zvlněnou pahorkatinou pokračujete do středověkého Bardejova, jehož náměstí s gotickou radnicí chrání UNESCO. Kousek za městem se schovávají lázně Bardejovské kúpele s kolonádou a skanzenem a na zpáteční cestě dřevěný kostelík v Hervartově – nejstarší a nejzachovalejší na Slovensku. Silnice jsou tu široké a klidné, ideální na uvolněnou jízdu s výhledy na Čergov. Trasa je sjízdná od jara do podzimu; pozor jen na zvěř v lesních úsecích a na letní bouřky, které se od Beskyd přiženou rychle.', 'loop', 145, 220, 'easy',
     '[{"lat": 48.9986, "lng": 21.2394, "label": "Start: Prešov"}, {"lat": 49.0378, "lng": 21.1928, "label": "Veľký Šariš"}, {"lat": 49.2937, "lng": 21.2765, "label": "Bardejov"}, {"lat": 49.3220, "lng": 21.2650, "label": "Bardejovské kúpele"}, {"lat": 49.2453, "lng": 21.2166, "label": "Hervartov"}, {"lat": 48.9986, "lng": 21.2394, "label": "Cíl: Prešov"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9986,21.2394&destination=48.9986,21.2394&travelmode=driving&waypoints=49.0378,21.1928%7C49.2937,21.2765%7C49.3220,21.2650%7C49.2453,21.2166', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20-%20Radni%C4%8Dn%C3%A9%20n%C3%A1mestie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pre%C5%A1ov%20-%20Hlavn%C3%A1%20ulica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sarissky%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20-%20Radni%C4%8Dn%C3%A9%20n%C3%A1mestie.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bardejovske%20kupele.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hervartov%20church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20radnica.jpg"}'::text[], '{"Prešov – Hlavná ulica","Šarišský hrad","Bardejov – Radničné námestie (UNESCO)","Bardejovské kúpele","Dřevěný kostelík Hervartov (UNESCO)","Restaurace: Roland (Bardejov)"}'::text[], '{"SK"}'::text[], false, 5320, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Prešov – Hlavná ulica', 'Metropole Šariše s vřetenovitým historickým náměstím, gotickou konkatedrálou svatého Mikuláše a řadou renesančních měšťanských domů. Před startem stojí za to projít si korzo a dát si kávu pod arkádami. Město je zároveň nejpohodlnějším místem na dotankování před okruhem.', 48.9977, 21.2401, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pre%C5%A1ov%20-%20Hlavn%C3%A1%20ulica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pre%C5%A1ov%20-%20Hlavn%C3%A1%20ulica.jpg"}'::text[], 0),
    (v_route, 'Šarišský hrad', 'Jedna z nejrozsáhlejších hradních zřícenin na Slovensku na výrazném sopečném kopci nad Veľkým Šarišem. Z parkoviště pod kopcem vede nahoru půlhodinová procházka odměněná kruhovým výhledem na celé údolí Torysy. Hrad býval správním centrem celé šarišské župy.', 49.0428, 21.2103, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sarissky%20hrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sarissky%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0ari%C5%A1sk%C3%BD%20hrad.jpg"}'::text[], 1),
    (v_route, 'Bardejov – Radničné námestie (UNESCO)', 'Nejzachovalejší středověké město Slovenska, zapsané na seznamu UNESCO. Náměstí lemují gotické měšťanské domy, uprostřed stojí renesanční radnice a bazilika svatého Egídia ukrývá jedenáct původních gotických křídlových oltářů. Motorku zaparkujete hned za hradbami.', 49.2937, 21.2765, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20-%20Radni%C4%8Dn%C3%A9%20n%C3%A1mestie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20-%20Radni%C4%8Dn%C3%A9%20n%C3%A1mestie.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20radnica.jpg"}'::text[], 2),
    (v_route, 'Bardejovské kúpele', 'Klidné lázně v lesích nad Bardejovem, kam jezdila císařovna Sisi i ruský car Alexandr I. Kolonádu doplňuje nejstarší skanzen na Slovensku s dřevěnými kostelíky a šarišskými chalupami. Příjemná zastávka na minerálku přímo z pramene.', 49.3220, 21.2650, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bardejovske%20kupele.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bardejovske%20kupele.jpg"}'::text[], 3),
    (v_route, 'Dřevěný kostelík Hervartov (UNESCO)', 'Nejstarší dřevěný kostel na Slovensku z konce 15. století, celý z červeného smrku a zapsaný na seznamu UNESCO. Uvnitř se dochovaly gotické nástěnné malby a original oltář. Kostelík stojí uprostřed vesničky pod lesy Čergova – klíč půjčuje místní správce.', 49.2453, 21.2166, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hervartov%20church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hervartov%20church.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Roland (Bardejov)', 'Oblíbená restaurace přímo na bardejovském náměstí s letní terasou pod gotickými štíty. Vaří poctivou šarišskou i mezinárodní kuchyni – vyhlášené jsou pirohy s bryndzou a kachní stehno. Výborné hodnocení hostů a rychlá obsluha z ní dělají ideální zastávku na oběd v polovině okruhu.', 49.2934, 21.2760, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20radnica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov%20radnica.jpg"}'::text[], 5);

  -- Poloniny a Vihorlat – nejvýchodnější Slovensko
  delete from public.routes where name = 'Poloniny a Vihorlat – nejvýchodnější Slovensko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Poloniny a Vihorlat – nejvýchodnější Slovensko', 'Výprava na úplný východní konec Slovenska, do nejřidčeji osídleného kouta země, kde se potkávají hranice tří států. Z Humenného sjedete k rekreačnímu moři východu – Zemplínské šíravě – a lesní silničkou vystoupáte k jezeru Morské oko pod sopečným Vihorlatem. Přes Sninu pak pokračujete do Parku tmavé oblohy Poloniny kolem hvězdárny na Kolonickém sedle a rusínskými vesničkami s dřevěnými kostelíky až do Nové Sedlice, nejvýchodnější obce republiky. Silnice jsou úzké, zvlněné a téměř prázdné – jízda tu má meditativní tempo. Nejlépe od června do října; počítejte s horším povrchem v zapadlých údolích, zvěří na silnici a minimem čerpacích stanic – tankujte ve Snině.', 'poi', 140, 240, 'medium',
     '[{"lat": 48.9317, "lng": 21.9067, "label": "Start: Humenné"}, {"lat": 48.7942, "lng": 22.0500, "label": "Zemplínska šírava"}, {"lat": 48.9126, "lng": 22.2833, "label": "Morské oko"}, {"lat": 48.9878, "lng": 22.1517, "label": "Snina"}, {"lat": 48.9353, "lng": 22.2764, "label": "Kolonické sedlo"}, {"lat": 49.0322, "lng": 22.3378, "label": "Topoľa"}, {"lat": 49.0511, "lng": 22.5153, "label": "Cíl: Nová Sedlica"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.9317,21.9067&destination=49.0511,22.5153&travelmode=driving&waypoints=48.7942,22.0500%7C48.9126,22.2833%7C48.9878,22.1517%7C48.9353,22.2764%7C49.0322,22.3378', 'https://commons.wikimedia.org/wiki/Special:FilePath/Morske%20oko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Humenne.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zemplinska%20sirava.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Morske%20oko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Snina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kolonica%20Observatory.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Topo%C4%BEa%20-%20dreven%C3%BD%20kostol%C3%ADk.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nova%20Sedlica.jpg"}'::text[], '{"Kaštieľ Humenné","Zemplínska šírava","Morské oko (Vihorlat)","Restaurace: Kaštieľ Snina (Snina)","Hvezdáreň Kolonica – Park tmavé oblohy","Dřevěný kostelík Topoľa","Nová Sedlica – nejvýchodnější obec"}'::text[], '{"SK"}'::text[], false, 5330, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kaštieľ Humenné', 'Renesanční zámek rodu Drugethů uprostřed parku v centru Humenného, dnes vlastivědné muzeum s expozicí šlechtického bydlení. Za zámkem leží skanzen s dřevěným kostelíkem a rusínskými chalupami z okolních Karpat. Dobré místo na první kávu před cestou na východ.', 48.9328, 21.9105, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Humenne.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Humenne.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Humenne%20kastiel.jpg"}'::text[], 0),
    (v_route, 'Zemplínska šírava', 'Druhá největší vodní plocha Slovenska, přezdívaná východoslovenské moře. Jižní břeh lemují pláže a přístaviště, severní obepíná sopečné pohoří Vihorlat. Silnice podél severního břehu nabízí příjemné zatáčky s výhledy na hladinu – ideální krátká zastávka u vody.', 48.7942, 22.0500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zemplinska%20sirava.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zemplinska%20sirava.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zempl%C3%ADnska%20%C5%A1%C3%ADrava.jpg"}'::text[], 1),
    (v_route, 'Morské oko (Vihorlat)', 'Smaragdové jezero sopečného původu ukryté v bukových pralesích Vihorlatu, součást světového dědictví UNESCO. Lesní silnička z Remetských Hámrů končí na parkovišti, odkud je to k hladině pár minut pěšky. Nad jezerem se zvedá skalnatý Sninský kameň s jedním z nejkrásnějších výhledů východu.', 48.9126, 22.2833, 'https://commons.wikimedia.org/wiki/Special:FilePath/Morske%20oko.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Morske%20oko.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vihorlat%20Morske%20oko.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Kaštieľ Snina (Snina)', 'Citlivě zrekonstruovaný klasicistní zámeček rodiny Rholl v centru Sniny s vyhlášenou restaurací a kavárnou na nádvoří. Kuchyně staví na regionálních surovinách a rusínských receptech v moderním podání. Poslední pořádné jídlo a tankování před vjezdem do liduprázdných Polonin.', 48.9884, 22.1569, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Snina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Snina.jpg"}'::text[], 3),
    (v_route, 'Hvezdáreň Kolonica – Park tmavé oblohy', 'Astronomická observatoř na Kolonickém sedle uprostřed Parku tmavé oblohy Poloniny – oblasti s nejtmavší noční oblohou ve střední Evropě. Přes den si prohlédnete největší dalekohled na Slovensku, za jasných nocí se tu konají veřejná pozorování. Ze sedla se otevírá výhled na hřebeny Bukovských vrchů.', 48.9353, 22.2764, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kolonica%20Observatory.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kolonica%20Observatory.jpg"}'::text[], 4),
    (v_route, 'Dřevěný kostelík Topoľa', 'Řeckokatolická dřevěná cerkev svatého archanděla Michala ze 17. století na kopečku nad vesničkou Topoľa. Patří k pokladům rusínské sakrální architektury Polonin – celá roubená, s šindelovou střechou a třemi věžičkami. U kostelíka je malý hřbitov s kamennými kříži.', 49.0322, 22.3378, 'https://commons.wikimedia.org/wiki/Special:FilePath/Topo%C4%BEa%20-%20dreven%C3%BD%20kostol%C3%ADk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Topo%C4%BEa%20-%20dreven%C3%BD%20kostol%C3%ADk.jpg"}'::text[], 5),
    (v_route, 'Nová Sedlica – nejvýchodnější obec', 'Nejvýchodnější obec Slovenska na konci silnice pod Kremencem, kde se stýkají hranice Slovenska, Polska a Ukrajiny. Symbolické místo pro dojezdovou fotku – dál už vede jen turistický chodník do pralesů Polonin. V obci je malý skanzen a bufet, odkud se vydávají turisté na trojmezí.', 49.0511, 22.5153, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nova%20Sedlica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nova%20Sedlica.jpg"}'::text[], 6);

  -- Zemplín a slovenský Tokaj
  delete from public.routes where name = 'Zemplín a slovenský Tokaj' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Zemplín a slovenský Tokaj', 'Vinařský okruh nejjižnějším Zemplínem začíná u jediného gejzíru střední Evropy v Herľanech a pokračuje pod zříceninu hradu Slanec, střežící průsmyk mezi Košickou kotlinou a Zemplínem. Pak už se před vámi otevřou slunečné vinice slovenské části světoznámé tokajské oblasti – rozhledna ve tvaru vinného soudku nad Veľkou Tŕňou, stovky let staré tufové sklepy v Malé Tŕni a renesanční kaštieľ v Borši, rodiště Františka II. Rákócziho. Zpět do Košic se vracíte rovinatým Zemplínem kolem kaštieľu v Trebišově. Silnice jsou klidné a přehledné, trasa je ideální na jaře a na podzim v době vinobraní. Ochutnávku vína si nechte až na večer po odstavení motorky – degustace tu berou vážně.', 'loop', 190, 270, 'easy',
     '[{"lat": 48.7164, "lng": 21.2611, "label": "Start: Košice"}, {"lat": 48.8014, "lng": 21.4767, "label": "Herľany"}, {"lat": 48.6353, "lng": 21.4750, "label": "Slanec"}, {"lat": 48.4550, "lng": 21.6850, "label": "Veľká Tŕňa"}, {"lat": 48.3944, "lng": 21.7161, "label": "Borša"}, {"lat": 48.6280, "lng": 21.7190, "label": "Trebišov"}, {"lat": 48.7164, "lng": 21.2611, "label": "Cíl: Košice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.7164,21.2611&destination=48.7164,21.2611&travelmode=driving&waypoints=48.8014,21.4767%7C48.6353,21.4750%7C48.4550,21.6850%7C48.3944,21.7161%7C48.6280,21.7190', 'https://commons.wikimedia.org/wiki/Special:FilePath/Herliansky%20gejzir.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Herliansky%20gejzir.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Slanec%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rozh%C4%BEad%C5%88a%20Tokaj.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mala%20Trna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Borsa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Trebisov.jpg"}'::text[], '{"Herliansky gejzír","Hrad Slanec","Rozhledna Tokaj (Veľká Tŕňa)","Restaurace: Tokaj Macík Winery (Malá Tŕňa)","Kaštieľ Borša","Kaštieľ Andrássyovců (Trebišov)"}'::text[], '{"SK"}'::text[], false, 5340, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Herliansky gejzír', 'Jediný studený gejzír ve střední Evropě, který v pravidelných intervalech zhruba 32 až 36 hodin tryská až patnáct metrů vysoko. Vznikl nechtěně při vrtu v 19. století a chrlí vodu už přes sto čtyřicet let. Časy erupcí zveřejňuje obec – pokud vyjde termín, je to nezapomenutelná podívaná.', 48.8014, 21.4767, 'https://commons.wikimedia.org/wiki/Special:FilePath/Herliansky%20gejzir.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Herliansky%20gejzir.jpg"}'::text[], 0),
    (v_route, 'Hrad Slanec', 'Zřícenina gotického hradu na strmém sopečném kuželu nad stejnojmennou obcí, s obnovenou věží a vyhlídkovou plošinou. Střežil obchodní stezku z Košické kotliny na Zemplín – dnes z věže dohlédnete od Slanských vrchů až k maďarské rovině. Výstup od parkoviště trvá asi dvacet minut.', 48.6353, 21.4750, 'https://commons.wikimedia.org/wiki/Special:FilePath/Slanec%20hrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slanec%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Slanec.jpg"}'::text[], 1),
    (v_route, 'Rozhledna Tokaj (Veľká Tŕňa)', 'Dřevěná rozhledna ve tvaru vinného soudku uprostřed vinic nad Veľkou Tŕňou, symbol slovenského Tokaje. Z ochozu ve výšce dvanácti metrů přehlédnete celou tokajskou oblast až k maďarskému Tokaji a řece Bodrog. Kolem vede vinařská cyklostezka a mezi vinicemi se krásně fotí.', 48.4550, 21.6850, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rozh%C4%BEad%C5%88a%20Tokaj.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rozh%C4%BEad%C5%88a%20Tokaj.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Velka%20Trna.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Tokaj Macík Winery (Malá Tŕňa)', 'Rodinné vinařství s restaurací a stovky let starými tufovými sklepy v srdci slovenského Tokaje. Podávají zemplínské speciality laděné k místním vínům – husacinu, sýry i degustační menu; podnik patří k nejlépe hodnoceným v regionu. Řidičům nalijí hroznový mošt, láhev tokajského výběru si odvezete v kufru.', 48.4392, 21.6944, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mala%20Trna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mala%20Trna.jpg"}'::text[], 3),
    (v_route, 'Kaštieľ Borša', 'Renesanční vodní kaštieľ v obci Borša u Bodrogu, rodiště sedmihradského knížete a vůdce protihabsburského povstání Františka II. Rákócziho. Po velkorysé rekonstrukci nabízí moderní expozici o rodu Rákócziů a příjemnou kavárnu v parku. Významné poutní místo maďarské historie pár kroků od hranice.', 48.3944, 21.7161, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Borsa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Borsa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Borsa%20kastiel.jpg"}'::text[], 4),
    (v_route, 'Kaštieľ Andrássyovců (Trebišov)', 'Klasicistní zámek hraběcího rodu Andrássyů v rozlehlém anglickém parku v centru Trebišova, dnes muzeum Zemplína s expozicí vinařství a tokajských sklepů. V parku najdete i mauzoleum rodu a zříceninu hradu Parič. Klidná zastávka ve stínu staletých platanů na zpáteční cestě.', 48.6280, 21.7190, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Trebisov.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kastiel%20Trebisov.jpg"}'::text[], 5);

  -- Gemer a Muránska planina
  delete from public.routes where name = 'Gemer a Muránska planina' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Gemer a Muránska planina', 'Trasa zapomenutým Gemerem spojuje unikátní podzemí, hradní romantiku a jednu z nejhezčích horských silnic středního Slovenska. Z Rožňavy zamíříte přes Štítnik k Ochtinské aragonitové jeskyni, světové raritě zapsané v UNESCO, a dál gemerskými městečky do Revúce, kolébky slovenského školství. Následuje stoupání pod majestátní zříceninu Muránského hradu a přejezd Muránské planiny přes sedlo Zbojská s vyhlášeným salašem – serpentiny mezi Muráněm a Tisovcem patří k nejoblíbenějším motorkářským úsekům v zemi. Provoz je tu minimální, krajina divoká; dávejte pozor na zvěř, lesní techniku a v zatáčkách na zbytky štěrku. Nejlepší období je květen až říjen.', 'poi', 100, 180, 'medium',
     '[{"lat": 48.6603, "lng": 20.5342, "label": "Start: Rožňava"}, {"lat": 48.6614, "lng": 20.3739, "label": "Štítnik"}, {"lat": 48.6656, "lng": 20.3011, "label": "Ochtinská aragonitová jaskyňa"}, {"lat": 48.6831, "lng": 20.1153, "label": "Revúca"}, {"lat": 48.7469, "lng": 20.0392, "label": "Muráň"}, {"lat": 48.7228, "lng": 19.8983, "label": "Sedlo Zbojská"}, {"lat": 48.6800, "lng": 19.9436, "label": "Cíl: Tisovec"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.6603,20.5342&destination=48.6800,19.9436&travelmode=driving&waypoints=48.6614,20.3739%7C48.6656,20.3011%7C48.6831,20.1153%7C48.7469,20.0392%7C48.7228,19.8983', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ochtinska%20aragonitova%20jaskyna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ochtinska%20aragonitova%20jaskyna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prve%20slovenske%20gymnazium%20Revuca.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Muransky%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Muranska%20planina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sedlo%20Zbojska.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tisovec.jpg"}'::text[], '{"Ochtinská aragonitová jaskyňa (UNESCO)","Revúca – První slovenské gymnázium","Muránský hrad","Muránska planina – Veľká lúka","Restaurace: Salaš Zbojská (sedlo Zbojská)","Tisovec – ozubnicová dráha"}'::text[], '{"SK"}'::text[], false, 5350, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Ochtinská aragonitová jaskyňa (UNESCO)', 'Jedna z pouhých tří zpřístupněných aragonitových jeskyní na světě, zapsaná na seznamu UNESCO. Místo klasických krápníků tu rostou sněhobílé trsy aragonitu připomínající korály a ledové květy. Prohlídka trvá půl hodiny a jeskyně má stálých sedm stupňů – bunda se hodí i v létě.', 48.6656, 20.3011, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ochtinska%20aragonitova%20jaskyna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ochtinska%20aragonitova%20jaskyna.jpg"}'::text[], 0),
    (v_route, 'Revúca – První slovenské gymnázium', 'Městečko pod Muránskou planinou, kde bylo roku 1862 založeno první slovenské gymnázium – budova s klasicistním průčelím dnes slouží jako národní kulturní památka s muzeem. Revúca je přirozeným centrem horního Gemeru a dobrým místem na kávu před horskou částí trasy.', 48.6836, 20.1131, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prve%20slovenske%20gymnazium%20Revuca.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prve%20slovenske%20gymnazium%20Revuca.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Revuca.jpg"}'::text[], 1),
    (v_route, 'Muránský hrad', 'Zřícenina jednoho z nejvýše položených hradů Slovenska (935 m) na vápencovém ostrohu Cigánka nad obcí Muráň. Proslavila ho krásná hradní paní Mária Séči, přezdívaná Muránská Venuše. Od parkoviště pod Velkou lúkou vede nahoru hodinová stezka s výhledy na celou planinu.', 48.7592, 20.0281, 'https://commons.wikimedia.org/wiki/Special:FilePath/Muransky%20hrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Muransky%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Muran%20hrad.jpg"}'::text[], 2),
    (v_route, 'Muránska planina – Veľká lúka', 'Rozlehlá horská louka v srdci národního parku Muránska planina, domov polodivokých koní plemene norik muránského typu. Krasová planina je protkaná závrty, roklemi a pralesy – z Velké lúky je nejhezčí pohled na hradní skálu. Silnice přes planinu je zážitkem i bez sesednutí z motorky.', 48.7597, 20.0731, 'https://commons.wikimedia.org/wiki/Special:FilePath/Muranska%20planina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Muranska%20planina.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Salaš Zbojská (sedlo Zbojská)', 'Legendární salaš přímo v sedle Zbojská na rozhraní Gemeru a Horehroní, oblíbená zastávka motorkářů z celého Slovenska. Vlastní ovčí farma zásobuje kuchyni – bryndzové halušky, žinčica, sýry a jehněčí patří k nejlepším v zemi. V ohradách se prohánějí ovce a koně, terasa voní údeným sýrem.', 48.7228, 19.8983, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sedlo%20Zbojska.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sedlo%20Zbojska.jpg"}'::text[], 4),
    (v_route, 'Tisovec – ozubnicová dráha', 'Horské městečko pod vápencovou Hradovou, kam vede z Pohronské Polhory unikátní ozubnicová železnice z roku 1896 – v letní sezóně po ní jezdí historické vlaky. Trať šplhá souběžně se silnicí přes sedlo Zbojská, takže s trochou štěstí pojedete chvíli závod s parní lokomotivou.', 48.6800, 19.9436, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tisovec.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tisovec.jpg"}'::text[], 5);

  -- Turiec a Veľká Fatra – přes zlatou Kremnici
  delete from public.routes where name = 'Turiec a Veľká Fatra – přes zlatou Kremnici' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Turiec a Veľká Fatra – přes zlatou Kremnici', 'Okruh Turčianskou kotlinou a horami kolem ní nabízí největší koncentraci serpentin na středním Slovensku. Z Martina projedete pod vápencovými srázy Veľké Fatry k Blatnici a ústí skalní Gaderské doliny, pak vás čeká legendární stoupání přes Harmanec – nejklikatější silniční úsek v zemi s desítkami vracečkových zatáček v bukovém lese a zastávkou u Harmanecké jeskyně. Přes Kremnické Bane, geografický střed Evropy, sjedete do zlatohorní Kremnice s nejstarší dosud fungující mincovnou na světě a údolím Turce se vrátíte přes lázně Turčianske Teplice zpět. Trasa je nejhezčí od května do října; na harmaneckých serpentinách počítejte s kamiony, vlhkem ve stínu lesa a dvojitou plnou čárou – předjíždějte s rozumem.', 'loop', 150, 240, 'medium',
     '[{"lat": 49.0664, "lng": 18.9217, "label": "Start: Martin"}, {"lat": 48.9367, "lng": 18.9339, "label": "Blatnica"}, {"lat": 48.8147, "lng": 19.0403, "label": "Harmanec"}, {"lat": 48.7400, "lng": 18.9130, "label": "Kremnické Bane"}, {"lat": 48.7050, "lng": 18.9183, "label": "Kremnica"}, {"lat": 48.8631, "lng": 18.8611, "label": "Turčianske Teplice"}, {"lat": 49.0664, "lng": 18.9217, "label": "Cíl: Martin"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.0664,18.9217&destination=49.0664,18.9217&travelmode=driving&waypoints=48.9367,18.9339%7C48.8147,19.0403%7C48.7400,18.9130%7C48.7050,18.9183%7C48.8631,18.8611', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kremnica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%BAzeum%20slovenskej%20dediny.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gaderska%20dolina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Harmanecka%20jaskyna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kremnicke%20Bane.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kremnica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Turcianske%20Teplice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Martin%20(Slovakia).jpg"}'::text[], '{"Múzeum slovenskej dediny (Martin)","Gaderská dolina (Blatnica)","Harmanecká jaskyňa","Kremnické Bane – střed Evropy","Kremnica – mincovna a městský hrad","Turčianske Teplice","Restaurace: Hotel Čierna pani (Martin)"}'::text[], '{"SK"}'::text[], false, 5360, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Múzeum slovenskej dediny (Martin)', 'Největší skanzen na Slovensku na okraji Martina – přes sto přenesených dřevěnic, kostelík, krčma i zvonice z celého Turce, Oravy a Kysuc. Procházka mezi chalupami zabere hodinku a krásně naladí na horskou část trasy. V areálu funguje dobová hospoda s regionálními jídly.', 49.0453, 18.9481, 'https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%BAzeum%20slovenskej%20dediny.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/M%C3%BAzeum%20slovenskej%20dediny.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Muzeum%20slovenskej%20dediny.jpg"}'::text[], 0),
    (v_route, 'Gaderská dolina (Blatnica)', 'Skalní brána Veľké Fatry u obce Blatnica – dvanáct kilometrů dlouhá krasová dolina s bílými vápencovými věžemi a potokem plným pstruhů. Nad ústím doliny se zvedá zřícenina Blatnického hradu. Motorka zůstane na parkovišti u vstupu, i krátká procházka podél potoka ale stojí za zastávku.', 48.9333, 18.9556, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gaderska%20dolina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gaderska%20dolina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Blatnicky%20hrad.jpg"}'::text[], 1),
    (v_route, 'Harmanecká jaskyňa', 'Krápníková jeskyně vysoko ve stráni nad harmaneckými serpentinami, proslulá bílými pagodovými stalagmity a největší kolonií netopýrů na Slovensku. K vchodu vede od parkoviště u silnice strmý lesní chodník – počítejte se čtyřiceti minutami stoupání. Skvělá záminka protáhnout nohy uprostřed nejklikatější silnice země.', 48.8147, 19.0403, 'https://commons.wikimedia.org/wiki/Special:FilePath/Harmanecka%20jaskyna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Harmanecka%20jaskyna.jpg"}'::text[], 2),
    (v_route, 'Kremnické Bane – střed Evropy', 'U kostelíka svatého Jana Křtitele nad hornickou obcí Kremnické Bane leží jeden z vypočtených geografických středů Evropy, označený žulovým monumentem. Ať už výpočtu věříte, nebo ne, výhled z návrší na Kremnické vrchy je krásný a fotka u středu kontinentu je povinná.', 48.7400, 18.9130, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kremnicke%20Bane.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kremnicke%20Bane.jpg"}'::text[], 3),
    (v_route, 'Kremnica – mincovna a městský hrad', 'Středověké zlatohorní město, kde se od roku 1328 nepřetržitě razí mince – kremnická mincovna je nejstarší fungující na světě a razila i české dukáty. Nad náměstím s morovým sloupem se zvedá opevněný městský hrad s kostelem svaté Kateřiny. Prohlídka mincovny s ražbou vlastní pamětní mince je originální suvenýr.', 48.7050, 18.9183, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kremnica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kremnica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kremnica%20namestie.jpg"}'::text[], 4),
    (v_route, 'Turčianske Teplice', 'Lázeňské městečko s termální vodou o teplotě přes čtyřicet stupňů, kde se léčil už uherský král Zikmund. Dominantou je modrobílý secesní lázeňský dům Modrý kúpeľ. Příjemná krátká zastávka v parku před posledním rovinatým úsekem zpět do Martina.', 48.8631, 18.8611, 'https://commons.wikimedia.org/wiki/Special:FilePath/Turcianske%20Teplice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Turcianske%20Teplice.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Hotel Čierna pani (Martin)', 'Tradiční hotelová restaurace v centru Martina, pojmenovaná podle pověsti o černé paní z martinského zámečku. Vaří poctivou turčianskou a slovenskou kuchyni – halušky, pečenou kachnu i denní menu za férové ceny, dlouhodobě s výborným hodnocením. Ideální tečka za okruhem plným serpentin.', 49.0653, 18.9203, 'https://commons.wikimedia.org/wiki/Special:FilePath/Martin%20(Slovakia).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Martin%20(Slovakia).jpg"}'::text[], 6);

  -- Rajecká dolina a zámek Bojnice
  delete from public.routes where name = 'Rajecká dolina a zámek Bojnice' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Rajecká dolina a zámek Bojnice', 'Okruh spojující malebnou Rajeckou dolinu s hornonitranskou kotlinou a nejromantičtějším zámkem Slovenska. Od lázní v Rajeckých Teplicích stoupáte dolinou k poutní bazilice v Rajecké Lesné s vyřezávaným pohyblivým Slovenským betlémem a dál na Fačkovské sedlo pod skalnatým Kľakem – stoupání i sjezd nabízejí výborný rytmus zatáček. Na Horní Nitře vás čeká pohádkový Bojnický zámek s nejstarší lípou v zemi a náměstí v Prievidzi, zpět se vracíte přes Nitrianske Pravno a znovu přes sedlo, tentokrát z druhé strany. Silnice první třídy přes Fačkov má kvalitní povrch, ale o víkendech i hustší provoz; brzy ráno si serpentiny užijete nejvíc. Ideální od dubna do října.', 'loop', 165, 250, 'medium',
     '[{"lat": 49.1264, "lng": 18.6828, "label": "Start: Rajecké Teplice"}, {"lat": 49.0361, "lng": 18.6297, "label": "Rajecká Lesná"}, {"lat": 48.9750, "lng": 18.6150, "label": "Fačkovské sedlo"}, {"lat": 48.7746, "lng": 18.6260, "label": "Prievidza"}, {"lat": 48.7800, "lng": 18.5775, "label": "Bojnice"}, {"lat": 48.9089, "lng": 18.6353, "label": "Nitrianske Pravno"}, {"lat": 49.1264, "lng": 18.6828, "label": "Cíl: Rajecké Teplice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.1264,18.6828&destination=49.1264,18.6828&travelmode=driving&waypoints=49.0361,18.6297%7C48.9750,18.6150%7C48.7746,18.6260%7C48.7800,18.5775%7C48.9089,18.6353', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bojnicky%20zamok.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rajecke%20Teplice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rajecka%20Lesna.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/K%C4%BEak%20(vrch).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bojnicky%20zamok.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bojnice.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prievidza.jpg"}'::text[], '{"Rajecké Teplice – lázně","Rajecká Lesná – Slovenský betlém","Fačkovské sedlo a Kľak","Bojnický zámek","Restaurace: Meridiana (Bojnice)","Prievidza – Námestie slobody"}'::text[], '{"SK"}'::text[], false, 5370, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Rajecké Teplice – lázně', 'Nejmenší slovenské lázeňské město s termálními prameny a elegantním lázeňským domem Aphrodite ve stylu antických lázní. Park s jezírkem přímo u kolonády je příjemným startem okruhu. Po náročnějším dni se sem vyplatí vrátit na večerní koupel v termální vodě.', 49.1264, 18.6828, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rajecke%20Teplice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rajecke%20Teplice.jpg"}'::text[], 0),
    (v_route, 'Rajecká Lesná – Slovenský betlém', 'Poutní obec s bazilikou Narození Panny Marie a proslulým Slovenským betlémem – patnáct metrů dlouhým vyřezávaným dílem mistra Pekary, kde se stovky figurek pohybují mezi miniaturami slovenských památek. Vstup je zdarma a betlém funguje po celý rok. Jedno z nejnavštěvovanějších poutních míst v zemi.', 49.0361, 18.6297, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rajecka%20Lesna.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rajecka%20Lesna.jpg"}'::text[], 1),
    (v_route, 'Fačkovské sedlo a Kľak', 'Horské sedlo (802 m) mezi Lúčanskou Malou Fatrou a pohořím Žiar, nad nímž se zvedá nápadný skalnatý vrchol Kľak. Stoupání z obou stran nabízí rytmické zatáčky a na sedle stojí motorest s parkovištěm – tradiční sraziště motorkářů. Z sedla vede na Kľak dvouhodinová hřebenovka s kruhovým výhledem.', 48.9750, 18.6150, 'https://commons.wikimedia.org/wiki/Special:FilePath/K%C4%BEak%20(vrch).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/K%C4%BEak%20(vrch).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fackovske%20sedlo.jpg"}'::text[], 2),
    (v_route, 'Bojnický zámek', 'Nejnavštěvovanější a nejromantičtější zámek Slovenska, přestavěný koncem 19. století podle francouzských loirských vzorů. Pod věžemi s modrými střechami roste sedmisetletá lípa krále Matyáše a v podzámčí sídlí nejstarší zoo v zemi. Prohlídkové okruhy vedou i do travertinové jeskyně přímo pod hradním nádvořím.', 48.7800, 18.5775, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bojnicky%20zamok.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bojnicky%20zamok.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bojnice%20Castle.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Meridiana (Bojnice)', 'Stylová restaurace kousek pod zámkem, dlouhodobě řazená k nejlepším podnikům Horní Nitry. Kuchyně kombinuje slovenskou klasiku s moderním bistro pojetím, chválené jsou steaky, domácí dezerty a víkendové menu. Po prohlídce zámku ideální místo na pořádný oběd před zpáteční cestou přes sedlo.', 48.7794, 18.5836, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bojnice.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bojnice.jpg"}'::text[], 4),
    (v_route, 'Prievidza – Námestie slobody', 'Centrum Horní Nitry s piaristickým kostelem, morovým sloupem a příjemnou pěší zónou. Město bývalo srdcem hornického regionu – o dobývání uhlí vypráví místní hornická expozice. Praktická zastávka na doplnění paliva i sil před návratem do Rajecké doliny.', 48.7746, 18.6260, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prievidza.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prievidza.jpg"}'::text[], 5);

  -- Malokarpatská vinná cesta
  delete from public.routes where name = 'Malokarpatská vinná cesta' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Malokarpatská vinná cesta', 'Nejznámější vinařská cesta Slovenska vede úpatím Malých Karpat od soutoku Dunaje s Moravou až pod Smolenický zámek. Začíná se pod majestátní zříceninou Devína, pokračuje přes vinařská městečka Svätý Jur, Pezinok a Modru, kde se rodí věhlasná frankovka i modranská majolika, a stoupá k mohutnému hradu Červený Kameň s nejzachovalejšími renesančními sklepy ve střední Evropě. Závěr patří lesům nad Smolenicemi – krápníkové jeskyni Driny a pohádkovému zámku na kopci. Silničky mezi vinicemi jsou úzké a zvlněné, s výhledy na Záhorí i Podunajskou nížinu. Trasa je krásná po celou sezónu, vrcholí ale v září při vinobraní; tehdy počítejte se zvýšeným provozem i policejními kontrolami – burčák si nechte zabalit s sebou.', 'poi', 90, 160, 'easy',
     '[{"lat": 48.1736, "lng": 16.9781, "label": "Start: Bratislava-Devín"}, {"lat": 48.2519, "lng": 17.2158, "label": "Svätý Jur"}, {"lat": 48.3339, "lng": 17.3061, "label": "Modra"}, {"lat": 48.3936, "lng": 17.3336, "label": "Červený Kameň"}, {"lat": 48.5117, "lng": 17.4308, "label": "Cíl: Smolenice"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.1736,16.9781&destination=48.5117,17.4308&travelmode=driving&waypoints=48.2519,17.2158%7C48.3339,17.3061%7C48.3936,17.3336', 'https://commons.wikimedia.org/wiki/Special:FilePath/Devin%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Devin%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Svaty%20Jur.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Modra.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Cerveny%20Kamen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jaskyna%20Driny.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Smolenicky%20zamok.jpg"}'::text[], '{"Hrad Devín","Svätý Jur","Modra – město vína a keramiky","Restaurace: Elesko Wine Park (Modra)","Hrad Červený Kameň","Jaskyňa Driny","Smolenický zámek"}'::text[], '{"SK"}'::text[], false, 5380, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Devín', 'Monumentální zřícenina na skále nad soutokem Dunaje a Moravy, jedno z nejvýznamnějších míst slovenské historie od dob Velké Moravy. Z hradeb se díváte přímo do Rakouska – za železné opony tudy vedla ostře střežená hranice, což připomíná Brána svobody pod hradem. Skvělé místo na úvodní fotku celé vinné cesty.', 48.1736, 16.9781, 'https://commons.wikimedia.org/wiki/Special:FilePath/Devin%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Devin%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Devin.jpg"}'::text[], 0),
    (v_route, 'Svätý Jur', 'Nejstarší vinařské městečko Malých Karpat s památkovou rezervací vinohradnických domů a gotickým kostelem svatého Jiří. Vinice tu obdělávají už od římských dob a místní ryzlinky patří k nejlepším v zemi. Úzkými uličkami projíždějte pomalu – o víkendech tu bývá živo.', 48.2519, 17.2158, 'https://commons.wikimedia.org/wiki/Special:FilePath/Svaty%20Jur.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Svaty%20Jur.jpg"}'::text[], 1),
    (v_route, 'Modra – město vína a keramiky', 'Srdce malokarpatského vinařství a domov proslulé modranské majoliky – ručně malované keramiky s třistaletou tradicí. Ve městě dožil národní buditel Ľudovít Štúr, jehož muzeum stojí na náměstí. Nad městem se z rozhledny na Veľké homoli otevírá výhled na moře vinic.', 48.3339, 17.3061, 'https://commons.wikimedia.org/wiki/Special:FilePath/Modra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Modra.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Elesko Wine Park (Modra)', 'Moderní vinařský areál mezi vinicemi u Modry s vyhlášenou restaurací, degustačními sklepy a galerií umění. Kuchyně staví na sezonních surovinách a párování s vlastními víny z okolních svahů; hodnocení hostů patří k nejvyšším v regionu. Řidičům ochotně nabídnou nealko variantu degustace.', 48.3489, 17.3183, 'https://commons.wikimedia.org/wiki/Special:FilePath/Modra%20vinohrady.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Modra%20vinohrady.jpg"}'::text[], 3),
    (v_route, 'Hrad Červený Kameň', 'Mohutný renesanční hrad rodu Pálffyů nad obcí Častá s nejrozsáhlejšími hradními sklepy ve střední Evropě – budovali je Fuggerové jako sklad mědi. Interiéry patří k nejzachovalejším v zemi a na nádvoří se konají sokolnické ukázky. Pod hradem je velké parkoviště a stánek s občerstvením.', 48.3936, 17.3336, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Cerveny%20Kamen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Cerveny%20Kamen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cerveny%20Kamen%20castle.jpg"}'::text[], 4),
    (v_route, 'Jaskyňa Driny', 'Jediná zpřístupněná jeskyně na západním Slovensku, ukrytá v lesích Malých Karpat nad Smolenicemi. Úzké puklinové chodby zdobí sintrové záclony a vodopády – prohlídka trvá asi 35 minut. Od parkoviště v dolině Hlboča vede k vchodu čtvrthodinová procházka bukovým lesem.', 48.4986, 17.4283, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jaskyna%20Driny.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jaskyna%20Driny.jpg"}'::text[], 5),
    (v_route, 'Smolenický zámek', 'Pohádkový zámek s kuželovitými věžemi na zalesněném kopci nad Smolenicemi, postavený začátkem 20. století rodem Pálffyů na místě staršího hradu. Dnes slouží jako kongresové centrum akademie věd, park a věž jsou v sezóně přístupné veřejnosti. Silueta nad vinicemi je důstojnou tečkou za vinnou cestou.', 48.5106, 17.4297, 'https://commons.wikimedia.org/wiki/Special:FilePath/Smolenicky%20zamok.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Smolenicky%20zamok.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Smolenice%20Castle.jpg"}'::text[], 6);

  -- Záhorie – Skalica, Holíč a Plavecký hrad
  delete from public.routes where name = 'Záhorie – Skalica, Holíč a Plavecký hrad' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Záhorie – Skalica, Holíč a Plavecký hrad', 'Pohodový okruh nejzápadnějším koutem Slovenska, krajem borových lesů, vinohradů a habánské historie. Ze Skalice s románskou rotundou a pravým trdelníkem vede trasa do barokního Holíče s císařským zámkem Františka Lotrinského a vzácným větrným mlýnem, pak borovicovými lesy Záhoří k národní bazilice v Šaštíně. Podél západního úpatí Malých Karpat dojedete pod zříceninu Plaveckého hradu na vápencovém hřebeni a přes kopanice se vrátíte kolem hradu Branč zpět. Silnice jsou rovné a rychlé, v lesních úsecích písčité krajnice – ideální nenáročná jarní či podzimní vyjížďka. Pozor na cyklisty na vinohradnických silničkách a na přeběhající zvěř v borech.', 'loop', 150, 220, 'easy',
     '[{"lat": 48.8461, "lng": 17.2264, "label": "Start: Skalica"}, {"lat": 48.8117, "lng": 17.1628, "label": "Holíč"}, {"lat": 48.6383, "lng": 17.1489, "label": "Šaštín-Stráže"}, {"lat": 48.4900, "lng": 17.2650, "label": "Plavecké Podhradie"}, {"lat": 48.6489, "lng": 17.5372, "label": "Podbranč"}, {"lat": 48.6803, "lng": 17.3667, "label": "Senica"}, {"lat": 48.8461, "lng": 17.2264, "label": "Cíl: Skalica"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.8461,17.2264&destination=48.8461,17.2264&travelmode=driving&waypoints=48.8117,17.1628%7C48.6383,17.1489%7C48.4900,17.2650%7C48.6489,17.5372%7C48.6803,17.3667', 'https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%20rotunda.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%20rotunda.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Holicsky%20zamok.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Veterny%20mlyn%20Holic.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sastin%20bazilika.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Plavecky%20hrad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Branc.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%20namestie.jpg"}'::text[], '{"Skalica – rotunda svatého Jiří","Holíčský zámek","Větrný mlýn Holíč","Bazilika Šaštín-Stráže","Plavecký hrad","Hrad Branč","Restaurace: Sv. Michal (Skalica)"}'::text[], '{"SK"}'::text[], false, 5390, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Skalica – rotunda svatého Jiří', 'Románská rotunda z 12. století na hradním návrší je symbolem svobodného královského města Skalica. Dole na trojúhelníkovém náměstí ochutnáte originální skalický trdelník – první chráněný slovenský produkt – a místní růžové víno, skalický rubín. Historické jádro s farským kostelem a jezuitskou kolejí stojí za procházku.', 48.8447, 17.2270, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%20rotunda.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%20rotunda.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Skalica.jpg"}'::text[], 0),
    (v_route, 'Holíčský zámek', 'Barokní zámek císaře Františka Štěpána Lotrinského, manžela Marie Terezie, obklopený vodním příkopem a rozlehlým parkem. Habsburská rodina sem jezdila na letní pobyty a v zámku sídlila proslulá manufaktura na fajáns. Areál s příkopy a konírnami je volně přístupný, interiéry v sezóně.', 48.8117, 17.1628, 'https://commons.wikimedia.org/wiki/Special:FilePath/Holicsky%20zamok.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Holicsky%20zamok.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Holic%20zamok.jpg"}'::text[], 1),
    (v_route, 'Větrný mlýn Holíč', 'Jediný zachovalý zděný větrný mlýn holandského typu na Slovensku, stojící na návrší nad Holíčem. Válcová stavba z 19. století sloužila k mletí obilí pro císařské panství a dnes je vyhledávaným vyhlídkovým bodem. Od mlýna přehlédnete rovinu Záhoří až k Bílým Karpatům.', 48.7997, 17.1719, 'https://commons.wikimedia.org/wiki/Special:FilePath/Veterny%20mlyn%20Holic.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Veterny%20mlyn%20Holic.jpg"}'::text[], 2),
    (v_route, 'Bazilika Šaštín-Stráže', 'Národní svatyně Slovenska s milostnou sochou Sedmibolestné Panny Marie, patronky země, kam každoročně putují statisíce poutníků. Monumentální barokní chrám s dvouvěžovým průčelím navrhli stavitelé císařského dvora a vysvěcen byl za účasti Marie Terezie. Poutní areál nabízí i stylové občerstvení.', 48.6383, 17.1489, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sastin%20bazilika.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sastin%20bazilika.jpg"}'::text[], 3),
    (v_route, 'Plavecký hrad', 'Rozeklaná zřícenina královského pohraničního hradu ze 13. století na vápencovém hřebeni Malých Karpat. Půlhodinový výstup od Plaveckého Podhradí odmění výhledem na celou rovinu Záhoří až k rakouským Alpám při dobré viditelnosti. Okolní skály jsou rájem horolezců a paraglidistů.', 48.4900, 17.2650, 'https://commons.wikimedia.org/wiki/Special:FilePath/Plavecky%20hrad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Plavecky%20hrad.jpg"}'::text[], 4),
    (v_route, 'Hrad Branč', 'Rozsáhlá zřícenina na travnatém kopci nad Podbrančem, strážící kdysi uherskou hranici proti Moravě. V 17. století sloužil hrad jako vězení protestantských kněží, což připomíná památník na nádvoří. Přístup je volný a z hradeb se otevírá kruhový výhled na myjavské kopanice.', 48.6489, 17.5372, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Branc.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%20Branc.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Branc%20hrad.jpg"}'::text[], 5),
    (v_route, 'Restaurace: Sv. Michal (Skalica)', 'Stylová restaurace a penzion v historickém domě u skalického náměstí, pojmenovaná po patronovi města. Vaří poctivou záhoráckou kuchyni – husacinu s lokšemi, zvěřinu i denní menu – a k tomu nabízejí vína místních vinařů včetně skalického rubínu. Výborně hodnocená tečka za okruhem, trdelník na cestu si zabalte z pekárny za rohem.', 48.8455, 17.2262, 'https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%20namestie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%20namestie.jpg"}'::text[], 6);

  -- Podunají – Žitný ostrov, Komárno a Štúrovo
  delete from public.routes where name = 'Podunají – Žitný ostrov, Komárno a Štúrovo' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Podunají – Žitný ostrov, Komárno a Štúrovo', 'Rovinatá jižní trasa podél Dunaje ukazuje úplně jinou tvář Slovenska – nekonečné lány největšího říčního ostrova Evropy, vodní kanály, pevnosti a maďarský temperament jihu. Z Bratislavy vede přes Žitný ostrov k monumentálnímu vodnímu dílu Gabčíkovo, kde můžete z hráze sledovat proplouvající lodě v obřích plavebních komorách, a dál k pohádkovému plovoucímu mlýnu v Kolárově. V Komárně vás čeká největší pevnostní systém bývalé monarchie a barevné Nádvoří Evropy, finále obstará jízda podél Dunaje do Štúrova s výhledem na ostřihomskou baziliku přes most Márie Valérie. Silnice jsou rovné a rychlé, ideální pro pohodové tempo i cestovní enduro s plnými kufry. Trasa je sjízdná prakticky celoročně; v létě počítejte s horkem nad rozpálenou rovinou – jezděte raději dopoledne.', 'poi', 170, 230, 'easy',
     '[{"lat": 48.1447, "lng": 17.1070, "label": "Start: Bratislava"}, {"lat": 47.8800, "lng": 17.5400, "label": "Gabčíkovo"}, {"lat": 47.9214, "lng": 18.0003, "label": "Kolárovo"}, {"lat": 47.7575, "lng": 18.1350, "label": "Komárno"}, {"lat": 47.7942, "lng": 18.7189, "label": "Cíl: Štúrovo"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.1447,17.1070&destination=47.7942,18.7189&travelmode=driving&waypoints=47.8800,17.5400%7C47.9214,18.0003%7C47.7575,18.1350', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vodne%20dielo%20Gabcikovo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vodne%20dielo%20Gabcikovo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vodny%20mlyn%20Kolarovo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Komarno%20pevnost.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nadvorie%20Europy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Komarno%20namestie.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Most%20Marie%20Valerie.jpg"}'::text[], '{"Vodní dílo Gabčíkovo","Vodní mlýn Kolárovo","Pevnost Komárno","Nádvoří Evropy (Komárno)","Restaurace: Banderium (Komárno)","Most Márie Valérie (Štúrovo)"}'::text[], '{"SK"}'::text[], false, 5400, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vodní dílo Gabčíkovo', 'Největší vodní stavba Slovenska s hrází, elektrárnou a plavebními komorami, jimiž se lodě spouštějí o více než šestnáct metrů. Z koruny hráze je působivý výhled na zdrž Hrušov i proplouvající říční soupravy. U areálu je vyhlídková terasa a informační centrum o dunajské plavbě.', 47.8800, 17.5400, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vodne%20dielo%20Gabcikovo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vodne%20dielo%20Gabcikovo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gabcikovo%20Dam.jpg"}'::text[], 0),
    (v_route, 'Vodní mlýn Kolárovo', 'Věrná replika plovoucího lodního mlýna na mrtvém rameni Malého Dunaje, k níž vede nejdelší krytý dřevěný most v Evropě. Skanzen připomíná doby, kdy na dolním toku klapaly desítky plovoucích mlýnů. Kolem je příjemný lužní háj s moly – ideální stinná zastávka uprostřed roviny.', 47.9250, 18.0080, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vodny%20mlyn%20Kolarovo.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vodny%20mlyn%20Kolarovo.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kolarovo%20mlyn.jpg"}'::text[], 1),
    (v_route, 'Pevnost Komárno', 'Největší bastionová pevnost bývalé rakousko-uherské monarchie na soutoku Váhu a Dunaje, která nebyla nikdy dobyta. Systém hradeb, kasemat a bastionů se rozrůstal od tureckých válek až do 19. století a dnes se uchází o zápis do UNESCO. Prohlídky s průvodcem vedou i do rozsáhlého podzemí.', 47.7575, 18.1350, 'https://commons.wikimedia.org/wiki/Special:FilePath/Komarno%20pevnost.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Komarno%20pevnost.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pevnost%20Komarno.jpg"}'::text[], 2),
    (v_route, 'Nádvoří Evropy (Komárno)', 'Originální náměstí v centru Komárna, kde každý dům reprezentuje architekturu jiné evropské země či regionu. Barevný soubor pětačtyřiceti staveb doplňují sochy uherských panovníků a průchody do historického jádra rodiště Mórа Jókaiho. Vděčné místo na fotku a zmrzlinu.', 47.7597, 18.1289, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nadvorie%20Europy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nadvorie%20Europy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nadvorie%20Europy%20Komarno.jpg"}'::text[], 3),
    (v_route, 'Restaurace: Banderium (Komárno)', 'Historická restaurace v měšťanském domě u hlavního náměstí Komárna, proslulá poctivou maďarsko-slovenskou kuchyní jihu. Perkelt, halászlé i husí játra tu dělají tak, jak mají – s pořádnou porcí papriky; hodnocení hostů patří k nejlepším ve městě. Zastávka na oběd před závěrečnou rovinkou do Štúrova.', 47.7586, 18.1275, 'https://commons.wikimedia.org/wiki/Special:FilePath/Komarno%20namestie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Komarno%20namestie.jpg"}'::text[], 4),
    (v_route, 'Most Márie Valérie (Štúrovo)', 'Ocelový most přes Dunaj spojující Štúrovo s maďarskou Ostřihomí, pojmenovaný po dceři císaře Františka Josefa I. Půl století ležel po válce v troskách a obnoven byl až roku 2001 jako symbol znovusblížení obou břehů. Z nábřeží ve Štúrově je nejkrásnější výhled na mohutnou ostřihomskou baziliku – důstojná závěrečná fotka trasy.', 47.7942, 18.7189, 'https://commons.wikimedia.org/wiki/Special:FilePath/Most%20Marie%20Valerie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Most%20Marie%20Valerie.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Maria%20Valeria%20Bridge.jpg"}'::text[], 5);

end $$;
