-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — IRSKO (10 tras, sort_order 4310–4400)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Irsko – poloostrov Dingle a Slea Head Drive
  delete from public.routes where name = 'Irsko – poloostrov Dingle a Slea Head Drive' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – poloostrov Dingle a Slea Head Drive', 'Okruh po nejzápadnějším poloostrově Irska kombinuje slavnou pobřežní silnici Slea Head Drive (R559) s dramatickým průsmykem Conor Pass, nejvyšší horskou silnicí v zemi. Úzká asfaltka se vine těsně nad Atlantikem kolem útesů, keltských pevností a výhledů na Blasketovy ostrovy, zpáteční cesta přidá dlouhou písečnou kosu Inch. Pozor: v Irsku se jezdí VLEVO — na jednosměrně doporučeném okruhu (po směru hodinových ručiček) se vyhnete couvání před autobusy. Nejlepší od května do září; počítejte s větrem, mlhou na Conor Passu, ovcemi na vozovce a úseky širokými sotva na jedno auto. Barevné městečko Dingle je ideální základna na kávu i čerstvé ryby.', 'loop', 135, 240, 'medium',
     '[{"lat": 52.1409, "lng": -10.264, "label": "Start: Dingle"}, {"lat": 52.0975, "lng": -10.4467, "label": "Slea Head"}, {"lat": 52.1247, "lng": -10.4603, "label": "Přístaviště Dunquin"}, {"lat": 52.1727, "lng": -10.3517, "label": "Gallarus Oratory"}, {"lat": 52.1596, "lng": -10.2038, "label": "Conor Pass"}, {"lat": 52.141, "lng": -9.977, "label": "Pláž Inch"}, {"lat": 52.1409, "lng": -10.264, "label": "Cíl: Dingle"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=52.1409,-10.264&destination=52.1409,-10.264&travelmode=driving&waypoints=52.0975,-10.4467%7C52.1247,-10.4603%7C52.1727,-10.3517%7C52.1596,-10.2038%7C52.141,-9.977', 'https://commons.wikimedia.org/wiki/Special:FilePath/Slea%20Head,%20Ireland.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slea%20Head,%20Ireland.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A9%20Dh%C3%BAn%20Chaoin%20Dunquin%20Pier.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Gallarus%20Oratory.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Dingle%20Conor%20Pass.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20at%20Inch%20in%20Dingle%20Bay%20Kerry%20Ireland.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dingle%20from%20the%20harbour%20-%20geograph.org.uk%20-%208282656.jpg"}'::text[], '{"Slea Head","Přístaviště Dunquin","Gallarus Oratory","Průsmyk Conor Pass","Pláž Inch","Restaurace: The Fish Box (Dingle)"}'::text[], '{"IE"}'::text[], false, 4310, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Slea Head', 'Nejzápadnější mys poloostrova Dingle s bílým krucifixem u silnice a výhledem na divoké Blasketovy ostrovy. Silnice R559 tu vede po římse vytesané do útesu — jedno z nejfotogeničtějších míst celé Wild Atlantic Way. Zastavte na malém odstavném pruhu a nechte si projít hlavou, že dál na západ už je jen Amerika.', 52.0975, -10.4467, 'https://commons.wikimedia.org/wiki/Special:FilePath/Slea%20Head,%20Ireland.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slea%20Head,%20Ireland.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Coumeenole%20Beach%20Dingle%20Peninsula%20Kerry%20Ireland.jpg"}'::text[], 0),
    (v_route, 'Přístaviště Dunquin', 'Ikonické mini-molo Dunquin Pier s klikatou pěšinou spadající serpentinami k moři, odkud vyplouvají lodě na Great Blasket. Patří k nejfotografovanějším místům Irska, zvlášť když po cestičce ženou ovce. Motorku nechte nahoře na parkovišti a sejděte pěšky — stojí to za to.', 52.1247, -10.4603, 'https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A9%20Dh%C3%BAn%20Chaoin%20Dunquin%20Pier.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A9%20Dh%C3%BAn%20Chaoin%20Dunquin%20Pier.jpg"}'::text[], 1),
    (v_route, 'Gallarus Oratory', 'Dokonale zachovalá kamenná modlitebna stará přes tisíc let, vyskládaná bez kapky malty do tvaru obrácené lodi. Považuje se za jednu z nejstarších dochovaných staveb Irska a uvnitř je i po staletích sucho. Krátká zastávka s velkou porcí historie, jen pár minut od hlavního okruhu.', 52.1727, -10.3517, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gallarus%20Oratory.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gallarus%20Oratory.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Gallarus%20Oratory%20-%20oldest%20church%20in%20Ireland%20-%20panoramio.jpg"}'::text[], 2),
    (v_route, 'Průsmyk Conor Pass', 'Nejvyšší horská silnice Irska (456 m) se šplhá z Dingle mezi skalami a ledovcovými jezírky — místy je tak úzká, že se dvě auta nevyhnou, motorka tu má luxusní výhodu. Z vrcholového parkoviště se za jasného dne otevírá výhled na obě strany poloostrova až k zálivu Brandon Bay. Za mlhy a silného větru jeďte extrémně opatrně, povrch bývá vlhký.', 52.1596, -10.2038, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dingle%20Conor%20Pass.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dingle%20Conor%20Pass.JPG"}'::text[], 3),
    (v_route, 'Pláž Inch', 'Pětikilometrová písečná kosa vybíhající do Dingle Bay, kterou proslavil film Ryanova dcera. Surfaři, nekonečný písek a panorama hor Kerry na druhé straně zálivu — perfektní nožky-protáhnout zastávka na zpáteční cestě. U vjezdu na pláž je kavárna s výhledem.', 52.141, -9.977, 'https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20at%20Inch%20in%20Dingle%20Bay%20Kerry%20Ireland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20at%20Inch%20in%20Dingle%20Bay%20Kerry%20Ireland.jpg"}'::text[], 4),
    (v_route, 'Restaurace: The Fish Box (Dingle)', 'Rodinný podnik rybářské rodiny Flannery přímo v centru Dingle — ryby a mořské plody jdou z vlastní lodi rovnou na talíř. Fish & chips, poke bowl i denní úlovek; na Googlu drží hodnocení kolem 4,7 hvězdy a patří k nejoblíbenějším podnikům města. Ideální oběd před vyjížďkou na Slea Head nebo po návratu z Conor Passu.', 52.1405, -10.268, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dingle%20from%20the%20harbour%20-%20geograph.org.uk%20-%208282656.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dingle%20from%20the%20harbour%20-%20geograph.org.uk%20-%208282656.jpg"}'::text[], 5);

  -- Irsko – poloostrov Beara a Healy Pass
  delete from public.routes where name = 'Irsko – poloostrov Beara a Healy Pass' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – poloostrov Beara a Healy Pass', 'Divočejší a prázdnější soused slavného Ring of Kerry: okruh Ring of Beara nabízí serpentiny průsmyku Healy Pass, jedinou lanovku v Irsku na ostrov Dursey a barevné vesničky Allihies a Eyeries. Silnice R571 a R572 jsou úzké, zvlněné a téměř bez provozu — ráj pro motorkáře, kteří chtějí Atlantik jen pro sebe. Nezapomeňte, že se jezdí VLEVO, a v zatáčkách počítejte s ovcemi a traktory. Povrch je místy hrubý a záplatovaný, ideální sezóna květen až září. Start i cíl v elegantním městečku Kenmare s výbornými restauracemi.', 'loop', 150, 250, 'medium',
     '[{"lat": 51.88, "lng": -9.583, "label": "Start: Kenmare"}, {"lat": 51.7519, "lng": -9.7345, "label": "Healy Pass"}, {"lat": 51.651, "lng": -9.911, "label": "Castletownbere"}, {"lat": 51.6086, "lng": -10.2016, "label": "Lanovka Dursey Island"}, {"lat": 51.641, "lng": -10.044, "label": "Allihies"}, {"lat": 51.687, "lng": -9.95, "label": "Eyeries"}, {"lat": 51.88, "lng": -9.583, "label": "Cíl: Kenmare"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.88,-9.583&destination=51.88,-9.583&travelmode=driving&waypoints=51.7519,-9.7345%7C51.651,-9.911%7C51.6086,-10.2016%7C51.641,-10.044%7C51.687,-9.95', 'https://commons.wikimedia.org/wiki/Special:FilePath/Healy%20Pass%2001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Healy%20Pass%2001.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dereenataggart%20Stone%20Circle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dereenataggart%20Stone%20Circle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dursey%20Island%20Cable%20Car%2009%202015%2009%2002.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Allihies%20view.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Eyeries%20Painted%20Houese.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Henry%20Street,%20Kenmare.jpg"}'::text[], '{"Healy Pass","Kamenný kruh Dereenataggart","Restaurace: MacCarthy''s Bar (Castletownbere)","Lanovka na Dursey Island","Allihies","Eyeries","Kenmare"}'::text[], '{"IE"}'::text[], false, 4320, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Healy Pass', 'Nejlepší motorkářská silnice jihozápadního Irska: R574 se serpentinami šplhá do sedla mezi hrabstvími Cork a Kerry, dole se leskne jezero Glanmore Lough. Zatáčka střídá zatáčku jako v Alpách, jen v miniaturním irském měřítku a s minimem provozu. Na vrcholu je odstavná plocha na fotku, kterou budete posílat všem.', 51.7519, -9.7345, 'https://commons.wikimedia.org/wiki/Special:FilePath/Healy%20Pass%2001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Healy%20Pass%2001.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Beara%20Peninsula%20Healy%20Pass%201996%2008%2014.jpg"}'::text[], 0),
    (v_route, 'Kamenný kruh Dereenataggart', 'Bronzový kamenný kruh nad Castletownbere, starý zhruba tři tisíce let, s výhledem na záliv Bantry Bay. Stojí kousek od hlavní silnice a je volně přístupný — tichá keltská mystika bez turistických davů. Krátká odbočka, která dodá okruhu po Bearě historickou hloubku.', 51.6553, -9.9219, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dereenataggart%20Stone%20Circle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dereenataggart%20Stone%20Circle.jpg"}'::text[], 1),
    (v_route, 'Restaurace: MacCarthy''s Bar (Castletownbere)', 'Legendární pub v rybářském přístavu Castletownbere, který se dostal i na obálku slavného bestselleru Peta McCarthyho. Vpředu funguje jako krámek, vzadu se čepuje Murphy''s a servírují se čerstvé sendviče s kraby z místní flotily. Autentické západoirské zastavení s výborným hodnocením — přesně to pravé v polovině okruhu.', 51.6512, -9.9105, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dereenataggart%20Stone%20Circle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dereenataggart%20Stone%20Circle.jpg"}'::text[], 2),
    (v_route, 'Lanovka na Dursey Island', 'Jediná kabinová lanovka v Irsku houpavě překonává úžinu Dursey Sound na ostrov, kde žije víc ovcí než lidí. Původně vozila i dobytek, dnes hlavně turisty a pár místních. I když se na ostrov nevydáte, samotný konec světa na špici Beary s výhledem na skály Bull Rock stojí za dojezd.', 51.6086, -10.2016, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dursey%20Island%20Cable%20Car%2009%202015%2009%2002.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dursey%20Island%20Cable%20Car%2009%202015%2009%2002.jpg"}'::text[], 3),
    (v_route, 'Allihies', 'Bývalá hornická vesnice s pestrobarevnými domky nad písečnou zátokou Ballydonegan — písek tu vznikl drcením rudy z měděných dolů, jejichž komíny dodnes trčí na svazích. Muzeum mědi připomíná časy, kdy odsud horníci odcházeli až na Aljašku. Jedna z nejmalebnějších zastávek celé trasy.', 51.641, -10.044, 'https://commons.wikimedia.org/wiki/Special:FilePath/Allihies%20view.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Allihies%20view.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Engine%20House%20Allihies%20Copper%20Mine%20County%20Cork%20Jun08%20DSC00429.jpg"}'::text[], 4),
    (v_route, 'Eyeries', 'Snad nejbarevnější vesnice Irska: řada domků natřených všemi odstíny duhy nad zálivem Coulagh Bay. Pravidelně vyhrává soutěže o nejupravenější obec a filmaři si ji oblíbili jako kulisu. Ideální na krátkou fotopauzu a kávu na hlavní (a jediné) ulici.', 51.687, -9.95, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eyeries%20Painted%20Houese.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eyeries%20Painted%20Houese.jpg"}'::text[], 5),
    (v_route, 'Kenmare', 'Elegantní městečko na šíji mezi poloostrovy Beara a Iveragh, plné barevných fasád, krajkářské tradice a skvělých restaurací. Trojúhelníkové centrum s ulicí Henry Street je ideální na závěrečnou večeři po okruhu. Odtud se dá druhý den pokračovat na sever do Killarney nebo na západ na Ring of Kerry.', 51.88, -9.583, 'https://commons.wikimedia.org/wiki/Special:FilePath/Henry%20Street,%20Kenmare.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Henry%20Street,%20Kenmare.jpg"}'::text[], 6);

  -- Irsko – Cliffs of Moher a kraj Burren
  delete from public.routes where name = 'Irsko – Cliffs of Moher a kraj Burren' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – Cliffs of Moher a kraj Burren', 'Okruh hrabstvím Clare spojuje dvě naprosto odlišné tváře Irska: 200 metrů vysoké útesy Cliffs of Moher a měsíční vápencovou krajinu Burrenu. Pobřežní R477 kolem Black Head patří k nejhezčím úsekům Wild Atlantic Way — moře na jedné straně, holé šedé desky vápence na druhé. Jezdí se VLEVO; u útesů počítejte s hustým turistickým provozem a autobusy, zbytek okruhu je příjemně prázdný. Serpentina Corkscrew Hill na N67 je místní lahůdka. Nejlépe květen až září, útesy si nechte na ráno nebo podvečer, kdy je nejméně lidí.', 'loop', 150, 240, 'easy',
     '[{"lat": 52.8436, "lng": -8.986, "label": "Start: Ennis"}, {"lat": 52.933, "lng": -9.348, "label": "Lahinch"}, {"lat": 52.9715, "lng": -9.4265, "label": "Cliffs of Moher"}, {"lat": 53.014, "lng": -9.378, "label": "Doolin"}, {"lat": 53.115, "lng": -9.15, "label": "Ballyvaughan"}, {"lat": 53.1425, "lng": -8.9257, "label": "Dunguaire Castle"}, {"lat": 53.0486, "lng": -9.1401, "label": "Poulnabrone"}, {"lat": 52.8436, "lng": -8.986, "label": "Cíl: Ennis"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=52.8436,-8.986&destination=52.8436,-8.986&travelmode=driving&waypoints=52.933,-9.348%7C52.9715,-9.4265%7C53.014,-9.378%7C53.115,-9.15%7C53.1425,-8.9257%7C53.0486,-9.1401', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cliffs%20of%20Moher,%20County%20Clare,%20Ireland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lahinch%20seafront%20-%20geograph.org.uk%20-%201083040.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cliffs%20of%20Moher,%20County%20Clare,%20Ireland.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fisherstreet%20Doolin%20Ireland%202005.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/The%20Burren.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dungory%20Castle%20-%20geograph.org.uk%20-%20887251.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Poulnabrone-dolmen.jpg"}'::text[], '{"Lahinch","Cliffs of Moher","Restaurace: Gus O''Connor''s Pub (Doolin)","Burren a Corkscrew Hill","Dunguaire Castle","Dolmen Poulnabrone"}'::text[], '{"IE"}'::text[], false, 4330, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lahinch', 'Surfařská metropole západního Irska s dlouhou písečnou pláží a promenádou, na které se v létě potkávají neopreny s motorkářskými kombinézami. Slavné golfové hřiště patří k nejstarším v zemi. Dobrá první zastávka na kávu s výhledem na atlantické vlny.', 52.933, -9.348, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lahinch%20seafront%20-%20geograph.org.uk%20-%201083040.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lahinch%20seafront%20-%20geograph.org.uk%20-%201083040.jpg"}'::text[], 0),
    (v_route, 'Cliffs of Moher', 'Nejnavštěvovanější přírodní památka Irska: osm kilometrů kolmých útesů spadajících až 214 metrů do Atlantiku, s věží O''Brien''s Tower na nejvyšším bodě. Za jasného dne dohlédnete na Aranské ostrovy i hory Connemary, kolem krouží papuchalci. Motorka platí na parkovišti u návštěvnického centra méně než auto; přijeďte brzy ráno, vyhnete se davům.', 52.9715, -9.4265, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cliffs%20of%20Moher,%20County%20Clare,%20Ireland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cliffs%20of%20Moher,%20County%20Clare,%20Ireland.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cliffs%20of%20Moher,%20Irland.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Gus O''Connor''s Pub (Doolin)', 'Proslulý pub z roku 1832 ve vesničce Doolin, světové metropoli irské lidové hudby. Vyhlášený seafood chowder, čerstvé ryby a večer živé „trad session" — hodnocení kolem 4,5 hvězdy a pověst, která sem táhne muzikanty z celého světa. Perfektní oběd mezi útesy a Burrenem.', 53.0125, -9.39, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fisherstreet%20Doolin%20Ireland%202005.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fisherstreet%20Doolin%20Ireland%202005.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Village%20of%20Doolin%20(Dulain),%20Co.%20Clare%20-%20geograph.org.uk%20-%20250583.jpg"}'::text[], 2),
    (v_route, 'Burren a Corkscrew Hill', 'Kraj Burren je jedna z největších krasových plošin Evropy — šedé vápencové desky, ve spárách vzácné alpské i středomořské květiny a všude pravěké památky. Serpentina Corkscrew Hill na N67 nad Ballyvaughanem nabízí sérii vraceček s výhledem na záliv Galway. Jedinečná krajina, kterou jinde v Irsku nenajdete.', 53.085, -9.166, 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Burren.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/The%20Burren.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Burren%20National%20Park.jpg"}'::text[], 3),
    (v_route, 'Dunguaire Castle', 'Věžový hrad ze 16. století na skalce nad zátokou u městečka Kinvara — údajně nejfotografovanější hrad Irska, zrcadlící se za přílivu v hladině. V létě se tu pořádají středověké bankety. Fotka z protějšího břehu s hradem nad mořem je povinnost.', 53.1425, -8.9257, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dungory%20Castle%20-%20geograph.org.uk%20-%20887251.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dungory%20Castle%20-%20geograph.org.uk%20-%20887251.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ireland%20banner-Dunguaire%20Castle%20and%20the%20lake%20in%20summer.jpg"}'::text[], 4),
    (v_route, 'Dolmen Poulnabrone', 'Portálová hrobka stará skoro šest tisíc let — starší než pyramidy — stojící uprostřed holé vápencové plošiny Burrenu. Ikonická silueta dolmenu proti nebi je jedním ze symbolů Irska. Volně přístupné pár kroků od silnice R480, ideální krátká zastávka na cestě zpět do Ennisu.', 53.0486, -9.1401, 'https://commons.wikimedia.org/wiki/Special:FilePath/Poulnabrone-dolmen.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Poulnabrone-dolmen.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Paulnabrone.jpg"}'::text[], 5);

  -- Irsko – Connemara, Sky Road a fjord Killary
  delete from public.routes where name = 'Irsko – Connemara, Sky Road a fjord Killary' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – Connemara, Sky Road a fjord Killary', 'Velký okruh Connemarou, nejromantičtější divočinou Irska: rašeliniště, hory Twelve Bens, černá jezera a jediný irský fjord Killary Harbour. Silnice N59 a R341 se vlní prázdnou krajinou, vyhlídkový okruh Sky Road nad Clifdenem patří k nejkrásnějším deseti kilometrům v zemi. Jezdí se VLEVO; hlavní pozor na ovce, které tu mají absolutní přednost, a na boční vítr na otevřených blatech. Novogotické opatství Kylemore nad jezerem je povinná fotozastávka. Ideální od května do října, po dešti krajina doslova svítí.', 'loop', 190, 280, 'medium',
     '[{"lat": 53.2707, "lng": -9.0568, "label": "Start: Galway"}, {"lat": 53.477, "lng": -9.766, "label": "Derryclare Lough"}, {"lat": 53.489, "lng": -10.02, "label": "Clifden"}, {"lat": 53.497, "lng": -10.079, "label": "Sky Road"}, {"lat": 53.5613, "lng": -9.8886, "label": "Kylemore Abbey"}, {"lat": 53.594, "lng": -9.669, "label": "Leenaun – Killary"}, {"lat": 53.2707, "lng": -9.0568, "label": "Cíl: Galway"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=53.2707,-9.0568&destination=53.2707,-9.0568&travelmode=driving&waypoints=53.477,-9.766%7C53.489,-10.02%7C53.497,-10.079%7C53.5613,-9.8886%7C53.594,-9.669', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kylemore%20Abbey2007.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Derryclare%20Lough,%20Twelve%20Bens.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Clifden,%20Market%20street.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sky%20Road%20Clifden.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kylemore%20Abbey2007.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Killary%20Fjord%20(2)%20-%20geograph.org.uk%20-%205525763.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Killary%20harbour%20-%20geograph.org.uk%20-%201037296.jpg"}'::text[], '{"Derryclare Lough","Clifden","Sky Road","Kylemore Abbey","Fjord Killary Harbour","Restaurace: Misunderstood Heron (Leenaun)"}'::text[], '{"IE"}'::text[], false, 4340, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Derryclare Lough', 'Jezero pod horami Twelve Bens s nejfotografovanějším ostrůvkem borovic v Irsku — pohlednicový záběr Connemary, který znáte z kalendářů. Vyhlídka je přímo u silnice R341 poblíž vesnice Recess. Ráno bývá hladina klidná a zrcadlí celé pohoří.', 53.477, -9.766, 'https://commons.wikimedia.org/wiki/Special:FilePath/Derryclare%20Lough,%20Twelve%20Bens.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Derryclare%20Lough,%20Twelve%20Bens.jpg"}'::text[], 0),
    (v_route, 'Clifden', '„Hlavní město" Connemary s barevnými fasádami a dvěma kostelními věžemi mezi horami a mořem. Nedaleko přistáli Alcock a Brown po prvním přeletu Atlantiku v roce 1919. Dobré místo na tankování — dál na sever už jsou pumpy vzácné.', 53.489, -10.02, 'https://commons.wikimedia.org/wiki/Special:FilePath/Clifden,%20Market%20street.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Clifden,%20Market%20street.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Clifden%20Castle.jpg"}'::text[], 1),
    (v_route, 'Sky Road', 'Jedenáctikilometrový vyhlídkový okruh nad Clifdenem, který stoupá vysoko nad zátoku a ostrovy — při západu slunce jedna z nejkrásnějších silnic Irska. Úzká jednostopá asfaltka se doporučuje projet po směru hodinových ručiček. Na vrcholu je parkoviště s výhledem na otevřený Atlantik.', 53.497, -10.079, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sky%20Road%20Clifden.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sky%20Road%20Clifden.jpg"}'::text[], 2),
    (v_route, 'Kylemore Abbey', 'Pohádkové novogotické opatství zrcadlící se v hladině jezera pod zalesněným svahem — nejfotografovanější stavba západního Irska. Postavil ho v 19. století Mitchell Henry jako důkaz lásky své ženě, dnes tu sídlí benediktinky. K areálu patří viktoriánská zahrada za hradbami a kavárna.', 53.5613, -9.8886, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kylemore%20Abbey2007.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kylemore%20Abbey2007.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kylemore%20Abbey%20Reflections.jpg"}'::text[], 3),
    (v_route, 'Fjord Killary Harbour', 'Jediný fjord Irska: šestnáct kilometrů dlouhý zářez mezi horami Mweelrea a Maumturks, po hladině šňůry bójí mušlových farem. Silnice N59 kopíruje jižní břeh a nabízí jeden výhled za druhým, u ústí řeky hučí vodopád Aasleagh Falls. Za odlivu je fjord jak norská pohlednice přenesená do Irska.', 53.61, -9.74, 'https://commons.wikimedia.org/wiki/Special:FilePath/Killary%20Fjord%20(2)%20-%20geograph.org.uk%20-%205525763.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Killary%20Fjord%20(2)%20-%20geograph.org.uk%20-%205525763.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/AASLEAGH%20FALLS-IRELAND......%20(49985449592).jpg"}'::text[], 4),
    (v_route, 'Restaurace: Misunderstood Heron (Leenaun)', 'Kultovní food truck na břehu fjordu Killary u Leenaun — pravděpodobně nejkrásněji položené rychlé občerstvení v Irsku. Mušle přímo z fjordu, chobotnice, skvělé polévky a koláče; hodnocení atakuje 4,8 hvězdy a fronta se tu stojí ráda. Otevřeno v sezóně, jídlo se jí na lavičkách s výhledem na hory.', 53.6067, -9.7167, 'https://commons.wikimedia.org/wiki/Special:FilePath/Killary%20harbour%20-%20geograph.org.uk%20-%201037296.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Killary%20harbour%20-%20geograph.org.uk%20-%201037296.jpg"}'::text[], 5);

  -- Irsko – Wicklow Mountains a Glendalough
  delete from public.routes where name = 'Irsko – Wicklow Mountains a Glendalough' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – Wicklow Mountains a Glendalough', 'Hory kousek od Dublinu: legendární Military Road (R115) stoupá přes vřesoviště a rašeliniště národního parku Wicklow Mountains k sedlu Sally Gap a dál kolem vodopádu Glenmacnass do klášterního údolí Glendalough. Prázdná úzká silnice s výhledy na jezero Lough Tay, kde se natáčeli Vikingové i Braveheart. Jezdí se VLEVO; na blatech pozor na volně se pasoucí ovce, jeleny a vlhký povrch — v horách bývá mlha i v létě. Zpět přes sedlo Wicklow Gap a jezera u Blessingtonu. Ideální jarní nebo podzimní vyjížďka, o víkendech vyjíždějí i dublinští motorkáři.', 'loop', 145, 220, 'medium',
     '[{"lat": 53.3498, "lng": -6.2603, "label": "Start: Dublin"}, {"lat": 53.19, "lng": -6.221, "label": "Glencree"}, {"lat": 53.106, "lng": -6.256, "label": "Lough Tay"}, {"lat": 53.1372, "lng": -6.3076, "label": "Sally Gap"}, {"lat": 53.048, "lng": -6.335, "label": "Vodopád Glenmacnass"}, {"lat": 53.01, "lng": -6.327, "label": "Glendalough"}, {"lat": 53.17, "lng": -6.533, "label": "Blessington"}, {"lat": 53.3498, "lng": -6.2603, "label": "Cíl: Dublin"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=53.3498,-6.2603&destination=53.3498,-6.2603&travelmode=driving&waypoints=53.19,-6.221%7C53.106,-6.256%7C53.1372,-6.3076%7C53.048,-6.335%7C53.01,-6.327%7C53.17,-6.533', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lough%20Tay%20(Guinness%20Lake)%20Wicklow%20Mountains%202.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lough%20Tay%20(Guinness%20Lake)%20Wicklow%20Mountains%202.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Scarr%20Mountain,%20Wicklow.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Glenmacnass%20waterfall%20from%20the%20south%20-%20geograph.org.uk%20-%2064540.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Glendalough%20Round%20Tower.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Glendasan%20River,%20Wicklow%20Mountains.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Poulaphouca%20Reservoir,%20County%20Kildare%20-%20geograph.org.uk%20-%201807100.jpg"}'::text[], '{"Lough Tay (Guinness Lake)","Sally Gap","Vodopád Glenmacnass","Glendalough","Restaurace: The Wicklow Heather (Laragh)","Přehrada Poulaphouca (Blessington)"}'::text[], '{"IE"}'::text[], false, 4350, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Lough Tay (Guinness Lake)', 'Tmavé jezero v hlubokém údolí pod skalní stěnou Luggala, kterému se říká Guinness Lake — patřilo rodině Guinnessů a bílá pláž s černou vodou připomíná sklenici stoutu. Kulisu si zamilovali filmaři, natáčel se tu seriál Vikingové. Vyhlídka je přímo u R759 kousek nad křižovatkou s Military Road.', 53.106, -6.256, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lough%20Tay%20(Guinness%20Lake)%20Wicklow%20Mountains%202.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lough%20Tay%20(Guinness%20Lake)%20Wicklow%20Mountains%202.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Luggala%20and%20Lough%20Tay,%20Wicklow,%20Ireland.jpg"}'::text[], 0),
    (v_route, 'Sally Gap', 'Křižovatka uprostřed ničeho: sedlo na Military Road, kterou Britové postavili roku 1800 kvůli honům na povstalce. Kolem jen vřes, rašelina a nebe — nejopuštěnější kus krajiny na dohled od Dublinu. Odtud vede nejhezčí úsek R115 na jih kolem Glenmacnassu.', 53.1372, -6.3076, 'https://commons.wikimedia.org/wiki/Special:FilePath/Scarr%20Mountain,%20Wicklow.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Scarr%20Mountain,%20Wicklow.jpg"}'::text[], 1),
    (v_route, 'Vodopád Glenmacnass', 'Řeka Glenmacnass tu sklouzává po žulových deskách do hlubokého údolí — vodopád je vidět přímo ze silnice R115, která se podél něj serpentinou spouští dolů k Laraghu. Po dešti je podívaná nejlepší. Pozor na mokré kamení, pokud se vydáte blíž.', 53.048, -6.335, 'https://commons.wikimedia.org/wiki/Special:FilePath/Glenmacnass%20waterfall%20from%20the%20south%20-%20geograph.org.uk%20-%2064540.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Glenmacnass%20waterfall%20from%20the%20south%20-%20geograph.org.uk%20-%2064540.jpg"}'::text[], 2),
    (v_route, 'Glendalough', 'Klášterní město sv. Kevina ze 6. století v údolí dvou jezer: třicetimetrová kruhová věž, kamenné kostelíky a hřbitov s keltskými kříži mezi zalesněnými svahy. Jedno z duchovních center středověké Evropy a dnes nejnavštěvovanější místo hrabství Wicklow. Krátká procházka k hornímu jezeru stojí za protažení nohou.', 53.01, -6.327, 'https://commons.wikimedia.org/wiki/Special:FilePath/Glendalough%20Round%20Tower.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Glendalough%20Round%20Tower.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Round%20tower%20of%20Glendalough.jpg"}'::text[], 3),
    (v_route, 'Restaurace: The Wicklow Heather (Laragh)', 'Rodinná restaurace v Laraghu kousek od Glendalough, proslulá poctivou irskou kuchyní z lokálních surovin — jehněčí z Wicklow, čerstvý pstruh i nedělní roast. Hodnocení kolem 4,5 hvězdy, uvnitř knihovna s prvními vydáními irských klasiků. Nejlepší oběd v celých horách Wicklow.', 53.008, -6.301, 'https://commons.wikimedia.org/wiki/Special:FilePath/Glendasan%20River,%20Wicklow%20Mountains.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Glendasan%20River,%20Wicklow%20Mountains.jpg"}'::text[], 4),
    (v_route, 'Přehrada Poulaphouca (Blessington)', 'Rozlehlá vodní nádrž na řece Liffey u Blessingtonu, které místní říkají Blessington Lakes — zásobárna vody pro Dublin obklopená lesy a zálivy. Silnice kolem západního břehu nabízí klidné zatáčky a výhledy na hladinu s horami v zádech. Příjemné zklidnění na závěr horského okruhu.', 53.144, -6.523, 'https://commons.wikimedia.org/wiki/Special:FilePath/Poulaphouca%20Reservoir,%20County%20Kildare%20-%20geograph.org.uk%20-%201807100.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Poulaphouca%20Reservoir,%20County%20Kildare%20-%20geograph.org.uk%20-%201807100.jpg"}'::text[], 5);

  -- Irsko – Donegal, útesy Slieve League
  delete from public.routes where name = 'Irsko – Donegal, útesy Slieve League' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – Donegal, útesy Slieve League', 'Nejdivočejší kout Irska: okruh jihozápadním Donegalem míří k útesům Slieve League, které jsou s 600 metry téměř třikrát vyšší než Cliffs of Moher — a přitom skoro bez turistů. Cestou rybářský přístav Killybegs, gaeltachtské údolí Glencolmcille a především průsmyk Glengesh Pass s alpskými vracečkami. Jezdí se VLEVO; silnice R263 a horské spojky jsou úzké, s ovcemi, sjezd z Glengeshe má prudké serpentiny. K vyhlídce Bunglass vede strmá jednostopá cesta — na motorce pohodlně, jen pozor na protijedoucí auta u bran. Nejlepší červen až září, za deště a mlhy útesy neuvidíte.', 'loop', 130, 220, 'medium',
     '[{"lat": 54.654, "lng": -8.11, "label": "Start: Donegal Town"}, {"lat": 54.634, "lng": -8.449, "label": "Killybegs"}, {"lat": 54.628, "lng": -8.681, "label": "Slieve League – Bunglass"}, {"lat": 54.708, "lng": -8.724, "label": "Glencolmcille"}, {"lat": 54.7285, "lng": -8.532, "label": "Glengesh Pass"}, {"lat": 54.767, "lng": -8.409, "label": "Ardara"}, {"lat": 54.654, "lng": -8.11, "label": "Cíl: Donegal Town"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.654,-8.11&destination=54.654,-8.11&travelmode=driving&waypoints=54.634,-8.449%7C54.628,-8.681%7C54.708,-8.724%7C54.7285,-8.532%7C54.767,-8.409', 'https://commons.wikimedia.org/wiki/Special:FilePath/Slieve%20League-cliffs.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Killybegs%20Harbour%202007%2008%2021.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Slieve%20League-cliffs.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Glengesh%20Pass%20ouest.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Front%20Street%20Ardara,%20Co%20Donegal.%20-%20geograph.org.uk%20-%20135931.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/ASSARANCA%20WATERFALL-DONEGAL.....%20(50472493402).jpg"}'::text[], '{"Killybegs","Útesy Slieve League","Glengesh Pass","Restaurace: Nancy''s Bar (Ardara)","Vodopád Assaranca"}'::text[], '{"IE"}'::text[], false, 4360, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Killybegs', 'Největší rybářský přístav Irska: mola plná oceánských trawlerů, křik racků a vůně moře. Ve městě dostanete nejčerstvější ryby široko daleko a naposledy tu pořádně natankujete. Odtud začíná nejhezčí úsek pobřežní R263 na západ.', 54.634, -8.449, 'https://commons.wikimedia.org/wiki/Special:FilePath/Killybegs%20Harbour%202007%2008%2021.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Killybegs%20Harbour%202007%2008%2021.jpg"}'::text[], 0),
    (v_route, 'Útesy Slieve League', 'Jedny z nejvyšších mořských útesů Evropy — hora Slieve League padá z 601 metrů přímo do Atlantiku. Z vyhlídky Bunglass se stěna barví okrovou, rezavou a šedou a pod ní se tříští oceán; hřebenová stezka One Man''s Pass je jen pro otrlé pěší. Strmou přístupovou silničku k vyhlídce si na motorce užijete, jen u samootvíracích bran jezděte krokem.', 54.628, -8.681, 'https://commons.wikimedia.org/wiki/Special:FilePath/Slieve%20League-cliffs.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Slieve%20League-cliffs.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Slieve%20League%20(15919171422).jpg"}'::text[], 1),
    (v_route, 'Glengesh Pass', 'Horský průsmyk mezi Glencolmcille a Ardarou s dvojicí alpských vraceček nad ledovcovým údolím — nejfotogeničtější silnice Donegalu. Z vyhlídky na vrcholu vidíte celou stuhu asfaltu, jak se spouští mezi zelené svahy. Sjezd je prudký a úzký, brzděte s předstihem.', 54.7285, -8.532, 'https://commons.wikimedia.org/wiki/Special:FilePath/Glengesh%20Pass%20ouest.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Glengesh%20Pass%20ouest.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Glacial%20Valley%20Ardara%20Glengesh%20Pass.jpg"}'::text[], 2),
    (v_route, 'Restaurace: Nancy''s Bar (Ardara)', 'Pub v Ardaře vedený jednou rodinou už sedm generací — malé místnosti jako v obýváku, rašelina v krbu a věhlasný seafood chowder s domácím chlebem. Pravidelně se objevuje v žebříčcích nejlepších irských hospod, hodnocení kolem 4,7 hvězdy. Ardara je zároveň centrum tkaní donegalského tvídu.', 54.767, -8.409, 'https://commons.wikimedia.org/wiki/Special:FilePath/Front%20Street%20Ardara,%20Co%20Donegal.%20-%20geograph.org.uk%20-%20135931.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Front%20Street%20Ardara,%20Co%20Donegal.%20-%20geograph.org.uk%20-%20135931.jpg"}'::text[], 3),
    (v_route, 'Vodopád Assaranca', 'Vodopád padající z převisu rovnou u silničky z Ardary k pláži Maghera — zastavíte doslova pět metrů od vody. Po dešti hřmí, za sucha je to romantický závoj; hned za ním pokračuje cesta k jeskyním a dunám Maghery. Krátká odbočka, kterou většina návštěvníků Donegalu mine.', 54.742, -8.463, 'https://commons.wikimedia.org/wiki/Special:FilePath/ASSARANCA%20WATERFALL-DONEGAL.....%20(50472493402).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/ASSARANCA%20WATERFALL-DONEGAL.....%20(50472493402).jpg"}'::text[], 4);

  -- Irsko – ostrov Achill a Atlantic Drive
  delete from public.routes where name = 'Irsko – ostrov Achill a Atlantic Drive' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – ostrov Achill a Atlantic Drive', 'Největší irský ostrov Achill je s pevninou spojený mostem, takže se na něj dá dojet po vlastní ose — a jeho okružní Atlantic Drive patří k vrcholům celé Wild Atlantic Way. Trasa z Westportu vede kolem posvátné hory Croagh Patrick a zálivu Clew Bay s údajně 365 ostrůvky, na ostrově pak k tyrkysové zátoce Keem Bay po silnici vytesané do svahu nad mořem. Jezdí se VLEVO; na Achillu počítejte se silným bočním větrem, ovcemi na vozovce a úseky bez svodidel nad útesy. Kombinace hor, plážía opuštěné vesnice Slievemore je jedinečná. Nejlépe od května do září, za bouřky Atlantic Drive raději vynechte.', 'loop', 160, 250, 'medium',
     '[{"lat": 53.801, "lng": -9.515, "label": "Start: Westport"}, {"lat": 53.783, "lng": -9.641, "label": "Murrisk – Croagh Patrick"}, {"lat": 53.904, "lng": -9.784, "label": "Mulranny"}, {"lat": 53.89, "lng": -9.943, "label": "Atlantic Drive (Achill)"}, {"lat": 53.973, "lng": -10.087, "label": "Keel"}, {"lat": 53.967, "lng": -10.194, "label": "Keem Bay"}, {"lat": 53.9946, "lng": -10.098, "label": "Slievemore"}, {"lat": 53.801, "lng": -9.515, "label": "Cíl: Westport"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=53.801,-9.515&destination=53.801,-9.515&travelmode=driving&waypoints=53.783,-9.641%7C53.904,-9.784%7C53.89,-9.943%7C53.973,-10.087%7C53.967,-10.194%7C53.9946,-10.098', 'https://commons.wikimedia.org/wiki/Special:FilePath/Keem%20Bay,%20Achill%20Island,%20Ireland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wall%20under%20Croagh%20Patrick.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Clew%20Bay%20001.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Atlantic%20Drive.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Keem%20Bay,%20Achill%20Island,%20Ireland.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Deserted%20Village%20at%20Slievemore.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Keel%20beach%20achill%20island.jpg"}'::text[], '{"Croagh Patrick (Murrisk)","Mulranny – vyhlídka na Clew Bay","Atlantic Drive (Achill)","Keem Bay","Opuštěná vesnice Slievemore","Restaurace: The Beehive (Keel)"}'::text[], '{"IE"}'::text[], false, 4370, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Croagh Patrick (Murrisk)', 'Posvátná hora Irska (764 m) s dokonale kuželovitou siluetou, na kterou podle legendy vystoupil sv. Patrik a odkud vyhnal z ostrova hady. Od parkoviště v Murrisku je nejhezčí pohled na horu i na záliv Clew Bay s roztroušenými ostrůvky. Poslední červencovou neděli sem poutníci stoupají i bosí.', 53.783, -9.641, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wall%20under%20Croagh%20Patrick.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wall%20under%20Croagh%20Patrick.JPG"}'::text[], 0),
    (v_route, 'Mulranny – vyhlídka na Clew Bay', 'Vesnice na šíji mezi zálivy Clew Bay a Blacksod, odkud se otevírá slavné panorama stovek zatopených drumlinů — kopečků, které vypadají jako hejno velryb v zálivu. Silnice N59 tudy vede po okraji svahu s výhledy na obě strany. Ideální fotopauza před nájezdem na Achill.', 53.904, -9.784, 'https://commons.wikimedia.org/wiki/Special:FilePath/Clew%20Bay%20001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Clew%20Bay%20001.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Drowned%20drumlin%20in%20Clew%20Bay.jpg"}'::text[], 1),
    (v_route, 'Atlantic Drive (Achill)', 'Okružní silnička po jižním pobřeží Achillu: asfalt přilepený ke skále, pod vámi bílá pěna Atlantiku a naproti věžový hrad pirátské královny Grace O''Malley u Kildavnetu. Krátký, ale intenzivní úsek, kde se nebudete stačit divit. Za silného větru jeďte opatrně, poryvy od moře umí zatlačit do protisměru.', 53.89, -9.943, 'https://commons.wikimedia.org/wiki/Special:FilePath/Atlantic%20Drive.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Atlantic%20Drive.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Achill%20Head.%20Co.%20Mayo%20Ireland.jpg"}'::text[], 2),
    (v_route, 'Keem Bay', 'Tyrkysová zátoka s bílým pískem sevřená útesy na samém konci ostrova — pravidelně se objevuje v žebříčcích nejkrásnějších pláží světa a natáčeli tu oscarové Víly z Inisherinu. Silnice ke Keem stoupá po hraně útesu nad mořem: krátký, nezapomenutelný a mírně adrenalinový dojezd. Dolů k pláži vede prudké klesání, brzděte včas.', 53.967, -10.194, 'https://commons.wikimedia.org/wiki/Special:FilePath/Keem%20Bay,%20Achill%20Island,%20Ireland.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Keem%20Bay,%20Achill%20Island,%20Ireland.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Keem%20Bay,%20Achill%20Island%20Co.%20Mayo,%20Ireland%20-%20geograph.org.uk%20-%20683771.jpg"}'::text[], 3),
    (v_route, 'Opuštěná vesnice Slievemore', 'Řada kamenných ruin téměř stovky domů na svahu hory Slievemore — vesnice opuštěná v době velkého hladomoru 19. století. Tiché, melancholické místo s výhledem na záliv, které vypráví o irské historii víc než učebnice. Přístup po úzké cestě kolem hřbitova, pár minut od Keelu.', 53.9946, -10.098, 'https://commons.wikimedia.org/wiki/Special:FilePath/Deserted%20Village%20at%20Slievemore.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Deserted%20Village%20at%20Slievemore.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Slievemore%20Deserted%20Village%20-%20geograph.org.uk%20-%207217474.jpg"}'::text[], 4),
    (v_route, 'Restaurace: The Beehive (Keel)', 'Oblíbená rodinná restaurace a řemeslný obchod v Keelu s výhledem na pláž a útesy Minaun. Domácí polévky, čerstvý losos, koláče a scony s marmeládou — jednoduché, poctivé a s hodnocením kolem 4,5 hvězdy nejlepší zastávka na ostrově. Po obědě si projděte tříkilometrovou pláž přímo pod terasou.', 53.9727, -10.0873, 'https://commons.wikimedia.org/wiki/Special:FilePath/Keel%20beach%20achill%20island.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Keel%20beach%20achill%20island.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Achill%20Island%20-%20Keel%20-%20Beehive%20Coffee%20Shop%20%5E%20Crafts%20-%20Stop%20for%20Lunch%20-%20geograph.org.uk%20-%203758140.jpg"}'::text[], 5);

  -- Irsko – Sligo a Downpatrick Head
  delete from public.routes where name = 'Irsko – Sligo a Downpatrick Head' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – Sligo a Downpatrick Head', 'Pohodová etapa Wild Atlantic Way krajem básníka Yeatse: od stolové hory Benbulbin přes surfařský Strandhill po severním pobřeží Maya až ke skalnímu sloupu Dún Briste u Downpatrick Head a neolitickým polím Céide Fields. Silnice R297 a R314 se drží nízko u oceánu, provoz je minimální a výhledy nekonečné. Jezdí se VLEVO — na prázdných rovinkách na to po pauze snadno zapomenete, pozor při vyjíždění ze zastávek. Trasa je nenáročná a vhodná i pro méně zkušené; větrno bývá po celý rok. Ideální od května do září, na Downpatrick Head nechoďte za vichru až k okraji útesu.', 'poi', 130, 200, 'easy',
     '[{"lat": 54.2766, "lng": -8.4761, "label": "Start: Sligo"}, {"lat": 54.327, "lng": -8.497, "label": "Drumcliff"}, {"lat": 54.27, "lng": -8.596, "label": "Strandhill"}, {"lat": 54.288, "lng": -8.963, "label": "Easkey"}, {"lat": 54.213, "lng": -9.22, "label": "Killala"}, {"lat": 54.326, "lng": -9.348, "label": "Downpatrick Head"}, {"lat": 54.308, "lng": -9.456, "label": "Cíl: Céide Fields"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.2766,-8.4761&destination=54.308,-9.456&travelmode=driving&waypoints=54.327,-8.497%7C54.27,-8.596%7C54.288,-8.963%7C54.213,-9.22%7C54.326,-9.348', 'https://commons.wikimedia.org/wiki/Special:FilePath/Benbulbenmount.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Benbulbenmount.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20Strandhill%20(cropped).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Strandhill2.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dun%20Briste,%20Downpatrick%20Head.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A9ide%20fields.jpg"}'::text[], '{"Drumcliff a Benbulbin","Strandhill","Restaurace: Shells Café (Strandhill)","Downpatrick Head (Dún Briste)","Céide Fields"}'::text[], '{"IE"}'::text[], false, 4380, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Drumcliff a Benbulbin', 'Stolová hora Benbulbin (526 m) s dramaticky zvrásněnými boky je poznávacím znamením Sliga — irský „Table Mountain". Pod ní v Drumcliffu leží u kostelíka hrob básníka W. B. Yeatse s proslulým epitafem „Cast a cold eye on life, on death". Výhled na horu přímo od silnice N15, zastávka na pět minut i na hodinu.', 54.327, -8.497, 'https://commons.wikimedia.org/wiki/Special:FilePath/Benbulbenmount.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Benbulbenmount.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Yeats%20Grave%20Drumcliffe%20Sligo.jpg"}'::text[], 0),
    (v_route, 'Strandhill', 'Surfařská vesnice pod horou Knocknarea, na jejímž vrcholu je mohyla legendární královny Maeve. Vlny tu patří k nejlepším v Irsku (koupání je kvůli proudům zakázané, surfuje se s instruktorem) a promenáda s kavárnami žije celý den. Atmosféra půl Kalifornie, půl Irska.', 54.27, -8.596, 'https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20Strandhill%20(cropped).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20Strandhill%20(cropped).jpg"}'::text[], 1),
    (v_route, 'Restaurace: Shells Café (Strandhill)', 'Kultovní kavárna přímo na promenádě ve Strandhillu: domácí pečivo, vydatné brunche a nejlepší káva na severozápadě, to vše s výhledem na surfaře. Hodnocení kolem 4,5 hvězdy a vlastní kuchařky, které si odvážejí i turisté. Ideální druhá snídaně před dlouhým pobřežním úsekem na západ.', 54.2703, -8.5972, 'https://commons.wikimedia.org/wiki/Special:FilePath/Strandhill2.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Strandhill2.jpg"}'::text[], 2),
    (v_route, 'Downpatrick Head (Dún Briste)', 'Padesátimetrový osamělý skalní sloup Dún Briste („zlomená pevnost") stojí pár desítek metrů od útesů — od pevniny ho odtrhla bouře roku 1393 i s lidmi, které pak zachraňovali po lanech. Na mysu je i dýchající puklina Poll na Seantoine, ohrazená kvůli bezpečnosti. Jedno z nejpůsobivějších míst celé Wild Atlantic Way, deset minut od silnice R314.', 54.326, -9.348, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dun%20Briste,%20Downpatrick%20Head.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dun%20Briste,%20Downpatrick%20Head.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Downpatrick%20Head%202021.jpg"}'::text[], 3),
    (v_route, 'Céide Fields', 'Nejrozsáhlejší neolitická památka světa: pod vrstvou rašeliny se skrývá systém kamenných zídek a polí starý přes pět tisíc let. Pyramidové návštěvnické centrum stojí na hraně 110metrových útesů s výhledem na otevřený Atlantik. Důstojná tečka za trasou — dál na západ už pokračuje jen prázdná R314 do Belmulletu.', 54.308, -9.456, 'https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A9ide%20fields.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A9ide%20fields.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ceide%20Fields%20Visitor%20Centre%20-%20geograph.org.uk%20-%20486592.jpg"}'::text[], 4);

  -- Irsko – West Cork, Mizen Head a Sheep's Head
  delete from public.routes where name = 'Irsko – West Cork, Mizen Head a Sheep''s Head' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – West Cork, Mizen Head a Sheep''s Head', 'Dva prsty pevniny na samém jihozápadě Irska: úzký poloostrov Sheep''s Head s jednou z nejopuštěnějších silniček v zemi a Mizen Head, „irský konec světa" s bílým mostem nad soutěskou plnou vln a tuleňů. Mezi nimi písečná Barleycove, jachtařský Crookhaven a gurmánský Schull. Jezdí se VLEVO; silničky na Sheep''s Head jsou jednostopé s výhybnami — buďte připraveni zastavit a pozdravit, tady zdraví každý. Provoz minimální, povrch místy hrubý, značení skromné. Ideální květen až září; za jasného dne uvidíte maják Fastnet, „slzu Irska", poslední kus vlasti, který viděli vystěhovalci do Ameriky.', 'loop', 160, 260, 'medium',
     '[{"lat": 51.68, "lng": -9.454, "label": "Start: Bantry"}, {"lat": 51.571, "lng": -9.713, "label": "Kilcrohane"}, {"lat": 51.5425, "lng": -9.8477, "label": "Sheep''s Head"}, {"lat": 51.493, "lng": -9.711, "label": "Goleen"}, {"lat": 51.4499, "lng": -9.81, "label": "Mizen Head"}, {"lat": 51.472, "lng": -9.728, "label": "Crookhaven"}, {"lat": 51.526, "lng": -9.546, "label": "Schull"}, {"lat": 51.68, "lng": -9.454, "label": "Cíl: Bantry"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=51.68,-9.454&destination=51.68,-9.454&travelmode=driving&waypoints=51.571,-9.713%7C51.5425,-9.8477%7C51.493,-9.711%7C51.4499,-9.81%7C51.472,-9.728%7C51.526,-9.546', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mizen%20Head.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bantry%20From%20above.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sheep%27s%20Head%20-%20end%20of%20the%20peninsula%20-%20geograph.org.uk%20-%206008888.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mizen%20Head.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/O%27Sullivan%27s%20Bar,%20Crookhaven%20-%20geograph.org.uk%20-%20243220.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Schull%20main%20street.jpg"}'::text[], '{"Bantry a Bantry House","Sheep''s Head – konec poloostrova","Mizen Head","Restaurace: O''Sullivan''s Bar (Crookhaven)","Schull"}'::text[], '{"IE"}'::text[], false, 4390, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Bantry a Bantry House', 'Přístavní městečko na konci hlubokého zálivu Bantry Bay, kam se roku 1796 pokusila (marně) vylodit francouzská flotila s irskými revolucionáři. Georgiánské sídlo Bantry House s italskými zahradami a výhledem na záliv patří k nejkrásnějším v Irsku. V pátek žije náměstí trhem s lokálními sýry a rybami.', 51.68, -9.454, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bantry%20From%20above.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bantry%20From%20above.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fountain%20at%20Bantry%20House.jpg"}'::text[], 0),
    (v_route, 'Sheep''s Head – konec poloostrova', 'Nejužší a nejtišší z jihozápadních poloostrovů: jednostopá silnička končí na parkovišti u kavárny Bernie''s Cupán Tae a dál už jen pěšina k maličkému majáku na útesu. Cestou po hřebeni vidíte současně zálivy Bantry i Dunmanus. Okruh Goat''s Path po severní straně je motorkářská meditace — jen vy, ovce a Atlantik.', 51.5425, -9.8477, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sheep%27s%20Head%20-%20end%20of%20the%20peninsula%20-%20geograph.org.uk%20-%206008888.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sheep%27s%20Head%20-%20end%20of%20the%20peninsula%20-%20geograph.org.uk%20-%206008888.jpg"}'::text[], 1),
    (v_route, 'Mizen Head', 'Nejjihozápadnější bod Irska: stanice signální služby na skalním ostrově, spojená s pevninou obloukovým mostem nad soutěskou, kde se vlny tříští o břidlicové stěny a dole odpočívají tuleni. Expozice připomíná Marconiho telegrafní pokusy i ztroskotané lodě. Vstupné se platí v návštěvnickém centru, k mostu se schází po schodech — výhledy stojí za každý krok.', 51.4499, -9.81, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mizen%20Head.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mizen%20Head.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Mizen%20Head%20Bridge%20-%20geograph.org.uk%20-%2012656.jpg"}'::text[], 2),
    (v_route, 'Restaurace: O''Sullivan''s Bar (Crookhaven)', 'Pub na molu v Crookhavenu, kde se pinta pije s nohama nad vodou přístavu — v létě sem připlouvají jachty z půlky Evropy. Vyhlášené krabí sendviče a chowder z denního úlovku, hodnocení kolem 4,6 hvězdy. Kdysi tu na poštu čekávaly transatlantické parníky, dnes je to nejpohodovější zastávka West Corku.', 51.472, -9.728, 'https://commons.wikimedia.org/wiki/Special:FilePath/O%27Sullivan%27s%20Bar,%20Crookhaven%20-%20geograph.org.uk%20-%20243220.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/O%27Sullivan%27s%20Bar,%20Crookhaven%20-%20geograph.org.uk%20-%20243220.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Crookhaven,%20Co.%20Cork,%20Ireland%20-%20panoramio.jpg"}'::text[], 3),
    (v_route, 'Schull', 'Živé přístavní městečko pod horou Mount Gabriel s gurmánskou pověstí: sýrárny, pekárny, nedělní trh a hospůdky plné jachtařů. Z přístavu vyplouvají lodě k majáku Fastnet, nejjižnějšímu bodu Irska. Příjemná předposlední zastávka před návratem do Bantry přes Ballydehob.', 51.526, -9.546, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schull%20main%20street.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Schull%20main%20street.jpg"}'::text[], 4);

  -- Irsko – Inishowen 100 a Malin Head
  delete from public.routes where name = 'Irsko – Inishowen 100 a Malin Head' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Irsko – Inishowen 100 a Malin Head', 'Značený okruh „Inis Eoghain 100" (100 mil) kolem nejsevernějšího poloostrova Irska: pevnost Fort Dunree nad zálivem Lough Swilly, poutní sedlo Gap of Mamore se sklonem přes 30 % a nakonec Malin Head — úplně nejsevernější bod ostrova s nápisem ÉIRE 80 z bílých kamenů z dob druhé světové války. Jezdí se VLEVO; stoupání na Mamore je krátké, ale extrémně prudké a jednostopé, za mokra vyžaduje jistou ruku se spojkou. Zbytek okruhu jsou širší, rytmické silnice s minimem aut a výhledy až ke skotským Hebridám. Zpáteční cestu korunuje kamenná pevnost Grianán of Aileach. Nejlépe květen až září; tady na severu počítejte s počasím všech čtyř ročních období za jeden den.', 'loop', 165, 260, 'medium',
     '[{"lat": 55.136, "lng": -7.453, "label": "Start: Buncrana"}, {"lat": 55.198, "lng": -7.556, "label": "Fort Dunree"}, {"lat": 55.2379, "lng": -7.4664, "label": "Gap of Mamore"}, {"lat": 55.276, "lng": -7.391, "label": "Ballyliffin"}, {"lat": 55.382, "lng": -7.373, "label": "Malin Head"}, {"lat": 55.257, "lng": -7.115, "label": "Kinnagoe Bay"}, {"lat": 54.989, "lng": -7.428, "label": "Grianán of Aileach"}, {"lat": 55.136, "lng": -7.453, "label": "Cíl: Buncrana"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=55.136,-7.453&destination=55.136,-7.453&travelmode=driving&waypoints=55.198,-7.556%7C55.2379,-7.4664%7C55.276,-7.391%7C55.382,-7.373%7C55.257,-7.115%7C54.989,-7.428', 'https://commons.wikimedia.org/wiki/Special:FilePath/80%20Eire%20at%20Malin%20Head.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/A%20View%20From%20Mamore%20Gap%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Strand%20Hotel,%20Ballyliffin,%20Co.%20Donegal%20-%20geograph.org.uk%20-%201384902.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/80%20Eire%20at%20Malin%20Head.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kinnagoe%20Bay,%20Inishowen,%20Co%20Donegal%20-%20geograph.org.uk%20-%2083440.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grianan%20of%20Aileach%20Donegal.jpg"}'::text[], '{"Gap of Mamore","Restaurace: Nancy''s Barn (Ballyliffin)","Malin Head (Banba''s Crown)","Kinnagoe Bay","Grianán of Aileach"}'::text[], '{"IE"}'::text[], false, 4400, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Gap of Mamore', 'Sedlo mezi kopci Urris Hills se stoupáním, které patří k nejprudším asfaltům Irska — serpentiny se sklonem přes 30 % a u vrcholu poutní studánka sv. Eigne ověšená růženci. Z vrcholu padá výhled na pláž Tullagh a otevřený oceán. Krátké, prudké, nezapomenutelné; za mokra jeďte s rezervou, výhybny jsou malé.', 55.2379, -7.4664, 'https://commons.wikimedia.org/wiki/Special:FilePath/A%20View%20From%20Mamore%20Gap%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/A%20View%20From%20Mamore%20Gap%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Road%20leading%20to%20the%20Gap%20Of%20Mamore%20-%20geograph.org.uk%20-%20400401.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Nancy''s Barn (Ballyliffin)', 'Bistro v kamenné stodole v golfovém Ballyliffinu, jehož rybí chowder vyhrál titul mistra světa na šampionátu v Newportu v USA. K tomu domácí chleba, koláče a pořádná káva; hodnocení se drží kolem 4,7 hvězdy. Ideální oběd před finálním dojezdem na Malin Head.', 55.276, -7.391, 'https://commons.wikimedia.org/wiki/Special:FilePath/Strand%20Hotel,%20Ballyliffin,%20Co.%20Donegal%20-%20geograph.org.uk%20-%201384902.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Strand%20Hotel,%20Ballyliffin,%20Co.%20Donegal%20-%20geograph.org.uk%20-%201384902.jpg"}'::text[], 1),
    (v_route, 'Malin Head (Banba''s Crown)', 'Nejsevernější bod Irska: věž staré signální stanice z roku 1805, pod útesem obří nápis ÉIRE 80 vyskládaný za války z bílých kamenů pro piloty a výhled, který za jasného dne sahá až ke Skotsku. Právě odsud začínají (nebo končí) všechny přejezdy Irska „od Malinu k Mizenu". Natáčely se tu i Star Wars; večer je to jedno z nejlepších míst na polární záři v Irsku.', 55.382, -7.373, 'https://commons.wikimedia.org/wiki/Special:FilePath/80%20Eire%20at%20Malin%20Head.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/80%20Eire%20at%20Malin%20Head.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Raised%20beaches%20at%20Malin%20Head%20-%20panoramio.jpg"}'::text[], 2),
    (v_route, 'Kinnagoe Bay', 'Skrytá pláž na východním pobřeží Inishowenu, kam vede prudká lesní silnička — zlatý písek, zelené svahy a obvykle ani noha. V roce 1588 tu ztroskotala loď španělské Armady La Trinidad Valencera; artefakty z vraku vystavuje muzeum v Derry. Odměna pro ty, kdo neodbočí zkratkou domů.', 55.257, -7.115, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kinnagoe%20Bay,%20Inishowen,%20Co%20Donegal%20-%20geograph.org.uk%20-%2083440.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kinnagoe%20Bay,%20Inishowen,%20Co%20Donegal%20-%20geograph.org.uk%20-%2083440.jpg"}'::text[], 3),
    (v_route, 'Grianán of Aileach', 'Mohutná kruhová kamenná pevnost na vrcholu kopce (244 m) nad soutokem zálivů Lough Swilly a Lough Foyle, sídlo severních králů dynastie Uí Néill. Zdi silné čtyři metry, uvnitř terasy s ochozy a kolem dokola výhled na půl Ulsteru. K pevnosti vede zábavná točitá silnička — důstojné finále celého okruhu.', 54.989, -7.428, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grianan%20of%20Aileach%20Donegal.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grianan%20of%20Aileach%20Donegal.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Grainan%20of%20Aileach%20Ring%20Fort%20-%20Donegal%20-%20Ireland.jpg"}'::text[], 4);

end $$;
