-- MotoGo24 — dokrytí fotek bodů zájmu (2. dávka): doplnění chybějících + oprava sporných
-- Generováno přes Wikimedia Commons (geosearch dle souřadnic + text), každý nález
-- sémanticky ověřen agentem (název bodu vs. obsah souboru) — rejecty vyřazeny.
-- Zrcadlení nových wiki URL do bucketu media obstará cron mirror-route-images.

begin;

-- === A) route_pois BEZ fotky: doplnění ověřené fotky motivu ===
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%ADo_Trev%C3%A9lez.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/R%C3%ADo_Trev%C3%A9lez.JPG']::text[] where id='0162804c-b3c1-4fb4-bfe9-16381ac3758d' and image_url is null; -- Restaurace: Mesón La Fragua (Trevélez)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Calle_Sagasta_in_Logrono_%281%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Calle_Sagasta_in_Logrono_%281%29.jpg']::text[] where id='02fbbde6-607f-43b2-98eb-803e6e053b24' and image_url is null; -- Restaurace: Bar Soriano (Logroño)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Raticosa_pass_1.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Raticosa_pass_1.JPG']::text[] where id='040963a8-8ff9-4846-9408-dc772501fe92' and image_url is null; -- Restaurace: Chalet Raticosa (Passo della Raticosa)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/P%C5%99%C3%ADbram-Svata_Hora-areal.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/P%C5%99%C3%ADbram-Svata_Hora-areal.jpg']::text[] where id='043834d3-817b-4912-aab2-0880319afb26' and image_url is null; -- Svatá Hora u Příbrami
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/ST_G%C3%B6rans_Kyrka_i_Geta_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/ST_G%C3%B6rans_Kyrka_i_Geta_-_panoramio.jpg']::text[] where id='051b46b7-f256-4f76-bf26-6c34fe479e91' and image_url is null; -- Geta a Getabergen
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vale_Glacial_do_Z%C3%AAzere_-_Portugal_%2840839617583%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vale_Glacial_do_Z%C3%AAzere_-_Portugal_%2840839617583%29.jpg']::text[] where id='0570eae3-385e-41f7-a50c-ef9b5b47a28d' and image_url is null; -- Ledovcové údolí Zêzere
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kr%C3%A1l%C5%AFv_stolec_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kr%C3%A1l%C5%AFv_stolec_-_panoramio.jpg']::text[] where id='05e600bd-9a8e-406f-815a-26fc3e7584f7' and image_url is null; -- Vyhlídka nad Dyjí (Králův stolec)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kom%C3%A1rno%2C_pevnost%2C_buzerplac.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kom%C3%A1rno%2C_pevnost%2C_buzerplac.JPG']::text[] where id='06eff983-a57b-4168-8792-cfe26dd4a2f1' and image_url is null; -- Pevnost Komárno
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Rota_do_Po%C3%A7o_do_Inferno_IV_%2852512200884%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Rota_do_Po%C3%A7o_do_Inferno_IV_%2852512200884%29.jpg']::text[] where id='08d3a0eb-a6f2-4307-b9e2-4c1704442d25' and image_url is null; -- Poço do Inferno
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Den_Burg_-_Overdekte_visbank.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Den_Burg_-_Overdekte_visbank.jpg']::text[] where id='0b70cdca-8b62-4494-99f2-ed7a3c1b1d51' and image_url is null; -- Restaurace: De Twaalf Balcken (Den Burg)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Medvedia_jasky%C5%88a_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Medvedia_jasky%C5%88a_01.jpg']::text[] where id='12f286eb-eef9-4367-ab11-d95e81d1d43e' and image_url is null; -- Medvedia jaskyňa
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na01.jpg']::text[] where id='139bd787-ae36-4840-9a2d-30075ada1c89' and image_url is null; -- Vydrická brána
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Ka%C5%A1tie%C4%BE%2C_Snina.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Ka%C5%A1tie%C4%BE%2C_Snina.jpg']::text[] where id='13b72fd9-a27b-49bb-b2e1-74eba50c3584' and image_url is null; -- Restaurace: Kaštieľ Snina (Snina)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A1bsk%C3%A9_jezero.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/C%C3%A1bsk%C3%A9_jezero.jpg']::text[] where id='14dbf84c-c35a-4c1c-aa67-37c7b6973dc4' and image_url is null; -- Cábské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na01.jpg']::text[] where id='1583106e-d61f-418a-acea-7089580ab465' and image_url is null; -- Vydrická brána
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/River_B%C3%B8vra_in_Lom.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/River_B%C3%B8vra_in_Lom.JPG']::text[] where id='15b3dbf9-210a-4430-95b0-1d126fd9d62a' and image_url is null; -- Restaurace: Bakeriet i Lom (Lom)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Munster%2C_straatzicht_Place_du_March%C3%A9-rue_Saint-Gregoire-Grand_Rue_met_stadhuis_PA00085551_foto4_2013-07-23_17.00.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Munster%2C_straatzicht_Place_du_March%C3%A9-rue_Saint-Gregoire-Grand_Rue_met_stadhuis_PA00085551_foto4_2013-07-23_17.00.jpg']::text[] where id='15c50f7d-6af1-4a37-b600-d9723463f0de' and image_url is null; -- Restaurace: Hôtel Verte Vallée (Munster)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/%C5%9Aluza_P%C4%85tn%C3%B3w.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/%C5%9Aluza_P%C4%85tn%C3%B3w.jpg']::text[] where id='1704c05a-8544-4e3a-b69a-4e73c132ca9a' and image_url is null; -- Pątnowskie Lake
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Old_Lake_Road%2C_Ambleside_-_geograph.org.uk_-_3286529.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Old_Lake_Road%2C_Ambleside_-_geograph.org.uk_-_3286529.jpg']::text[] where id='18401554-8600-4a82-8bca-ddb94847c377' and image_url is null; -- Restaurace: The Old Stamp House (Ambleside)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/De_Geer_moraines_at_Kvarken.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/De_Geer_moraines_at_Kvarken.JPG']::text[] where id='1a1542df-a911-4426-8056-4786e85f24b7' and image_url is null; -- Svedjehamn a Kvarken (UNESCO)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Martin-18.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Martin-18.jpg']::text[] where id='1cfa6a22-986e-4e24-8280-c2b43d90042b' and image_url is null; -- Restaurace: Hotel Čierna pani (Martin)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Chr%C3%A1nen%C3%A9_%C3%BAzemie_Fintick%C3%A9_svahy._Fintice_23_Slovakia_2.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Chr%C3%A1nen%C3%A9_%C3%BAzemie_Fintick%C3%A9_svahy._Fintice_23_Slovakia_2.jpg']::text[] where id='1dc33e1e-b94a-4a10-b5f1-a9414861a53b' and image_url is null; -- Fintické svahy
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/GuentherZ_2011-03-19_0036_Zwettl_Johannes-Nepomuk-Kapelle_Kriegerdenkmal.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/GuentherZ_2011-03-19_0036_Zwettl_Johannes-Nepomuk-Kapelle_Kriegerdenkmal.jpg']::text[] where id='1e7a0dc5-e4c5-4ef4-bd8b-57dadf940079' and image_url is null; -- Restaurace: Bräuhaus Zwettl (Zwettl)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/JN_Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/JN_Velk%C3%A9_Mezi%C5%99%C3%AD%C4%8D%C3%AD.JPG']::text[] where id='1fe537ca-89fd-4c80-b1c6-f82bea1d96b0' and image_url is null; -- Restaurace: Jelínkova vila (Velké Meziříčí)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Alabastrov%C3%A1_jasky%C5%88a_vchod.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Alabastrov%C3%A1_jasky%C5%88a_vchod.jpg']::text[] where id='203107b2-3644-45e9-94d5-b18604a06494' and image_url is null; -- Alabastrová jeskyně
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Lofthus_i_Ullensvang_kommune.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Lofthus_i_Ullensvang_kommune.jpg']::text[] where id='20b65f2f-af22-4030-a3f8-cea52a81e802' and image_url is null; -- Restaurace: Hotel Ullensvang (Lofthus)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Holic_vetrny_mlyn_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Holic_vetrny_mlyn_01.jpg']::text[] where id='24902ac6-4b26-4602-b753-9b9ee10f7130' and image_url is null; -- Větrný mlýn Holíč
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_f%C3%A4stning%2C_Vaxholms_kastell%2C_Vaxholm%2C_Sverige_2009_6293.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vaxholms_f%C3%A4stning%2C_Vaxholms_kastell%2C_Vaxholm%2C_Sverige_2009_6293.jpg']::text[] where id='25231614-fd81-49c6-bf88-6a3fac231449' and image_url is null; -- Pevnost Vaxholm
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kom%C3%A1rom07.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kom%C3%A1rom07.JPG']::text[] where id='2547a7b4-0a21-4d12-8a3c-b155ccb9108f' and image_url is null; -- Nádvoří Evropy (Komárno)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_Tyr%C5%A1ova%2C_kulturn%C3%AD_d%C5%AFm_b%C4%9Bhem_FF_2013_%282013-07-05%3B_01%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9Bbo%C5%99%2C_Tyr%C5%A1ova%2C_kulturn%C3%AD_d%C5%AFm_b%C4%9Bhem_FF_2013_%282013-07-05%3B_01%29.jpg']::text[] where id='26d7489f-fc97-44c0-a66c-a2338e662024' and image_url is null; -- Restaurace: Panský dům (Chotěboř)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_Kara%C5%9B%2C_Wyspa_Sobieszewska_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_Kara%C5%9B%2C_Wyspa_Sobieszewska_-_panoramio.jpg']::text[] where id='277b97c6-52ac-4e91-855e-123da23fb057' and image_url is null; -- Karaś Lake
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hervartov%2C_Kostol_sv%C3%A4t%C3%A9ho_Franti%C5%A1ka_z_Assisi_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hervartov%2C_Kostol_sv%C3%A4t%C3%A9ho_Franti%C5%A1ka_z_Assisi_01.jpg']::text[] where id='291eac53-1b24-4159-9c04-62dc68bb7a15' and image_url is null; -- Dřevěný kostelík Hervartov (UNESCO)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sundlalm%2C_Sundlalmbach.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sundlalm%2C_Sundlalmbach.jpg']::text[] where id='292674d6-232a-4161-ad86-ccd660ee89d3' and image_url is null; -- Sundlsee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg']::text[] where id='29e91222-bb2a-4961-92c4-f0bcbb187c20' and image_url is null; -- Pět Spišských ples
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/St_Wolfgang_Kefermarkt_01.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/St_Wolfgang_Kefermarkt_01.JPG']::text[] where id='2cb25bad-7ac7-4719-bf15-a6e7f12a6c7e' and image_url is null; -- Kefermarkt — gotický oltář
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Tr%C3%A1s-os-Montes%2C_Portugal_%282084525696%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Tr%C3%A1s-os-Montes%2C_Portugal_%282084525696%29.jpg']::text[] where id='2da92c85-dc34-4b20-916c-468e9b16a518' and image_url is null; -- Přírodní park Montesinho
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0atov_sklepn%C3%AD.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0atov_sklepn%C3%AD.JPG']::text[] where id='2e37dec1-450a-4e4b-a0e0-b19f27b6851d' and image_url is null; -- Šatovské vinné sklepy
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Chr%C3%A1nen%C3%A9_%C3%BAzemie_Fintick%C3%A9_svahy._Fintice_23_Slovakia_2.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Chr%C3%A1nen%C3%A9_%C3%BAzemie_Fintick%C3%A9_svahy._Fintice_23_Slovakia_2.jpg']::text[] where id='2e4949ef-c8fb-4d65-a336-157e2e522a8c' and image_url is null; -- Fintické svahy
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na01.jpg']::text[] where id='2e8398df-f065-414c-8a81-8ec59d592d26' and image_url is null; -- Vydrická brána
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bell_tower_Sieppij%C3%A4rvi_Church_Kolari_20250418_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bell_tower_Sieppij%C3%A4rvi_Church_Kolari_20250418_01.jpg']::text[] where id='3350386a-ab55-4c4d-91ca-1e4a9a22b475' and image_url is null; -- Sieppijärvi
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hauklandstrand_03.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hauklandstrand_03.jpg']::text[] where id='3498305a-7180-4a63-afdf-81584b169ac6' and image_url is null; -- Hauklandstranda
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Apoteksg%C3%A5rden%2C_Ystad.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Apoteksg%C3%A5rden%2C_Ystad.jpg']::text[] where id='35d9dd48-1958-4946-be97-669df21b85bd' and image_url is null; -- Restaurace: Store Thor (Ystad)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vene_V%C3%A4%C3%A4ksyn_kanavalla_25.7.2018.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vene_V%C3%A4%C3%A4ksyn_kanavalla_25.7.2018.jpg']::text[] where id='37767f31-78b7-4388-98d1-085505d23af6' and image_url is null; -- Restaurace: Kanavan Panimo (Vääksy)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%2C_Hafen03.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Honfleur%2C_Hafen03.jpg']::text[] where id='37b36722-ac4b-4bd9-95bf-6da1001a78e5' and image_url is null; -- Restaurace: Le Bréard (Honfleur)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/BCH_02_Usciw.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/BCH_02_Usciw.JPG']::text[] where id='38b16cab-a9c0-4d18-bf66-42c61428d920' and image_url is null; -- Uściwierz
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sokolac_Brinje_07_3.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sokolac_Brinje_07_3.jpg']::text[] where id='3bb0e125-821a-435d-930b-c2167e1816f0' and image_url is null; -- Hrad Sokolac
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Viborg_seen_from_S%C3%B8nders%C3%B8_2012-05-28_cropped.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Viborg_seen_from_S%C3%B8nders%C3%B8_2012-05-28_cropped.jpg']::text[] where id='3e39d3a2-1ce5-4639-886d-bc1571de2472' and image_url is null; -- Søndersø
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Chr%C3%A1nen%C3%A9_%C3%BAzemie_Fintick%C3%A9_svahy._Fintice_23_Slovakia_2.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Chr%C3%A1nen%C3%A9_%C3%BAzemie_Fintick%C3%A9_svahy._Fintice_23_Slovakia_2.jpg']::text[] where id='3e4fd3a4-1316-43c3-86a4-a5467939afd1' and image_url is null; -- Fintické svahy
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9_Bud%C4%9Bjovice%2C_Dukelsk%C3%A1%2C_Jiho%C4%8Desk%C3%A9_muzeum.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9_Bud%C4%9Bjovice%2C_Dukelsk%C3%A1%2C_Jiho%C4%8Desk%C3%A9_muzeum.JPG']::text[] where id='41ca6fa1-718b-488f-ac24-0651d867540f' and image_url is null; -- Jihočeské muzeum
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Rellotge_de_Sol_de_Cantavieja.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Rellotge_de_Sol_de_Cantavieja.JPG']::text[] where id='423f9229-8c6d-452c-aff9-4c998f37527b' and image_url is null; -- Restaurace: Balfagón (Cantavieja)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzijanski_samostan_Pleterje_1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzijanski_samostan_Pleterje_1.jpg']::text[] where id='42984c68-92c3-4d44-b35b-d871cab45624' and image_url is null; -- Kartuziánský klášter Pleterje
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sand_%28Rogaland%29.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sand_%28Rogaland%29.JPG']::text[] where id='46c6982a-8e10-48d5-b0fe-cadbb70eed64' and image_url is null; -- Sand
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Outlet_of_Lemonsj%C3%B8en-Utl%C3%B8pet_av_Lemonsj%C3%B8en_%284098072284%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Outlet_of_Lemonsj%C3%B8en-Utl%C3%B8pet_av_Lemonsj%C3%B8en_%284098072284%29.jpg']::text[] where id='471bbac1-1e34-4be8-b6cb-046fa6d9ece4' and image_url is null; -- Lemonsjøen
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sundlalm%2C_Sundlalmbach.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sundlalm%2C_Sundlalmbach.jpg']::text[] where id='48b72aa7-a564-4366-85ca-65d6c383883a' and image_url is null; -- Sundlsee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mese%C4%8Dev_zaliv_-_Strunjan.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mese%C4%8Dev_zaliv_-_Strunjan.jpg']::text[] where id='4bc7ca38-8e4d-4732-bca5-a7b7bf55e2a8' and image_url is null; -- Strunjanské útesy
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Replot_Bridge.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Replot_Bridge.jpg']::text[] where id='4c83c649-d699-47c4-bd80-15cd01b3bb77' and image_url is null; -- Replotský most
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bomban_talo_Nurmes_in_winter.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bomban_talo_Nurmes_in_winter.jpg']::text[] where id='4ed99637-fe9d-49df-80b1-374155eeabad' and image_url is null; -- Restaurace: Bomban talo (Nurmes)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/ValevatnValevatn.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/ValevatnValevatn.jpg']::text[] where id='4fd8ac47-f562-41f3-9439-b570472978d0' and image_url is null; -- Valevatn
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Alabastrov%C3%A1_jasky%C5%88a_vchod.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Alabastrov%C3%A1_jasky%C5%88a_vchod.jpg']::text[] where id='5046742b-a756-43a3-8007-ff46ada7a5dd' and image_url is null; -- Alabastrová jeskyně
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Passerelle_au_dessus_des_rapides_de_Myllykoski_%C3%A0_Juuma._-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Passerelle_au_dessus_des_rapides_de_Myllykoski_%C3%A0_Juuma._-_panoramio.jpg']::text[] where id='5049b1a8-cda9-4b45-9233-b847de33d8b6' and image_url is null; -- Juuma a Myllykoski
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Rottneros_Manor%2C_Sunne%2C_V%C3%A4rmland_%287829297548%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Rottneros_Manor%2C_Sunne%2C_V%C3%A4rmland_%287829297548%29.jpg']::text[] where id='50d81be9-9a0e-4e34-afd7-eb5df1f63c41' and image_url is null; -- Park Rottneros
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Zbojska_salas.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Zbojska_salas.JPG']::text[] where id='510727da-1d3b-4ba7-b2c4-89160b2b1816' and image_url is null; -- Restaurace: Salaš Zbojská (sedlo Zbojská)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Akvofalo_Bobacka1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Akvofalo_Bobacka1.jpg']::text[] where id='516abfb5-a4b1-4d93-ab3b-d6d83b82dfb1' and image_url is null; -- Bobačka
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Svandalsfossen_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Svandalsfossen_-_panoramio.jpg']::text[] where id='5217a2f2-922a-439c-bb13-d3bb59d0801f' and image_url is null; -- Svandalsfossen
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Stara_iza%2C_Bakovci.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Stara_iza%2C_Bakovci.jpg']::text[] where id='52604b33-5759-4273-8566-8cf9e45eca38' and image_url is null; -- Restaurace: Gostilna Rajh (Bakovci)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Le_Mont-Dore_eglise_reformee.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Le_Mont-Dore_eglise_reformee.JPG']::text[] where id='541f1ca0-4709-4b7f-b8a8-8ef1cae43a45' and image_url is null; -- Restaurace: Le Bougnat (Le Mont-Dore)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Aavasaksa_1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Aavasaksa_1.jpg']::text[] where id='5487473b-2c95-4182-8d4c-83a595d3ed92' and image_url is null; -- Hora Aavasaksa
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Nau%C4%8Dn%C3%A1_stezka_Soumarsk%C3%A9_ra%C5%A1elini%C5%A1t%C4%9B_%2801%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Nau%C4%8Dn%C3%A1_stezka_Soumarsk%C3%A9_ra%C5%A1elini%C5%A1t%C4%9B_%2801%29.jpg']::text[] where id='54e38409-ae17-49ba-9dbb-46a94ab00135' and image_url is null; -- Soumarský most a rašeliniště
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kol%C3%A1rovo%2C_m%C5%95tve_rameno_Mal%C3%A9ho_Dunaja_-_panoramio_%284%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kol%C3%A1rovo%2C_m%C5%95tve_rameno_Mal%C3%A9ho_Dunaja_-_panoramio_%284%29.jpg']::text[] where id='54ff8b19-1c73-4aff-b854-7a375ac4a275' and image_url is null; -- Mrtvé rameno Váhu
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Panoramic_view_of_Rabisha_Lake_%28from_the_exit_of_Magurata_cave%29_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Panoramic_view_of_Rabisha_Lake_%28from_the_exit_of_Magurata_cave%29_-_panoramio.jpg']::text[] where id='58275ef0-b243-4a61-8a9c-8c4439b97de6' and image_url is null; -- Jeskyně Magura
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg']::text[] where id='58c74af1-189c-4852-82c2-5644cfbd52b2' and image_url is null; -- Pět Spišských ples
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttan_2010.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Trollh%C3%A4ttan_2010.jpg']::text[] where id='5a74a12f-e5d5-45dd-adf4-d24e6d8bafa6' and image_url is null; -- Restaurace: Albert Kök (Trollhättan)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jaskinia_%C5%9Anie%C5%BCna_otw%C3%B3r.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jaskinia_%C5%9Anie%C5%BCna_otw%C3%B3r.jpg']::text[] where id='5df11798-9caf-456b-8643-e385ceb48776' and image_url is null; -- Śnieżna Studnia
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hintersee-Hochkalter.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hintersee-Hochkalter.jpg']::text[] where id='609b436e-c865-466a-a223-b78fee56bdf5' and image_url is null; -- Hintersee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Apricale_BW_0.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Apricale_BW_0.JPG']::text[] where id='62436122-4e7b-434b-a8a9-4921f34d553c' and image_url is null; -- Restaurace: Ristorante Apricale da Delio (Apricale)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Langavatnet_Gullbotn.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Langavatnet_Gullbotn.JPG']::text[] where id='63fe56f2-d504-403b-a473-2d9d5c1cc1c3' and image_url is null; -- Langavatnet
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro-wiecanowskie.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro-wiecanowskie.jpg']::text[] where id='64c16b23-500a-491e-aa24-dda6e6e2cf9d' and image_url is null; -- Wiecanowské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Dreven%C3%BD_chr%C3%A1m_v_Topoli.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Dreven%C3%BD_chr%C3%A1m_v_Topoli.jpg']::text[] where id='65fb11a8-e87f-43d9-929e-8bfc1a48c2ec' and image_url is null; -- Dřevěný kostelík Topoľa
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sandwich_tern_in_the_bay_of_Ropotamo_river.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sandwich_tern_in_the_bay_of_Ropotamo_river.jpg']::text[] where id='66c1ed8c-b17b-4d73-bf5f-bf193c5bba34' and image_url is null; -- Rezervace Ropotamo
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hotel_Videseter_%283613015477%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hotel_Videseter_%283613015477%29.jpg']::text[] where id='6757754f-10d2-454e-b061-8ae29d4d34fb' and image_url is null; -- Videseter
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Zemono_Slovenia.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Zemono_Slovenia.jpg']::text[] where id='6781d0f7-65ee-47da-a2d3-24eb9683dc7d' and image_url is null; -- Restaurace: Gostilna pri Lojzetu (dvorec Zemono)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Two_wooden_boats_on_a_Polish_marsh.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Two_wooden_boats_on_a_Polish_marsh.jpg']::text[] where id='679a0ebe-7656-44ab-806f-32fb3baec217' and image_url is null; -- Red Marsh Nature Reserve
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Rybie_Stawki.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Rybie_Stawki.jpg']::text[] where id='68ab5b25-39d3-4024-a3b9-3b47264d128e' and image_url is null; -- Rybie Stawki
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/SKUEV0313_Dev%C3%ADnske_jazero.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/SKUEV0313_Dev%C3%ADnske_jazero.jpg']::text[] where id='68dc6e51-4f2c-40f2-a93f-178ceed03b3f' and image_url is null; -- Devínské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg']::text[] where id='69022f95-b39a-491f-baeb-bb4f494b9bc5' and image_url is null; -- Pět Spišských ples
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hunebed%2C_Borger%2C_Netherlands_-_4095621962.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hunebed%2C_Borger%2C_Netherlands_-_4095621962.jpg']::text[] where id='6ac82dd9-5413-41a3-a8fd-c42fd9b2e92c' and image_url is null; -- Hunebedcentrum Borger
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Drachovske_tune_%281%29.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Drachovske_tune_%281%29.JPG']::text[] where id='6c0e90f1-d8fd-4898-a6a1-2326d4edb0b8' and image_url is null; -- jez Dráchov
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Fa%C4%8Dkovsk%C3%A9_sedlo.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Fa%C4%8Dkovsk%C3%A9_sedlo.jpg']::text[] where id='6f8879dc-d74b-43e2-b2df-9b3a6244fc40' and image_url is null; -- Fačkovské sedlo a Kľak
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cejkov%2C_n%C3%A1ves.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cejkov%2C_n%C3%A1ves.jpg']::text[] where id='70396f95-ebd7-46b2-b77f-e063e92d5b7c' and image_url is null; -- Cejkov
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_Rad%C4%99ci%C5%84skie%2C_pomosty_na_pla%C5%BCy_ko%C5%82o_Rad%C4%99cina.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_Rad%C4%99ci%C5%84skie%2C_pomosty_na_pla%C5%BCy_ko%C5%82o_Rad%C4%99cina.jpg']::text[] where id='72f3f66f-b2ad-49d5-b3bc-30c21cc67a18' and image_url is null; -- Jezioro Radęcińskie
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hegyh%C3%A1tszentjakab%2C_Vad%C3%A1sa-t%C3%B3.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hegyh%C3%A1tszentjakab%2C_Vad%C3%A1sa-t%C3%B3.jpg']::text[] where id='754629e3-3d85-4f73-98ee-9ad334731d68' and image_url is null; -- Jezero Vadása
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Fishing_in_the_Kukkola_rapids%2C_Norrbotten%2C_Sweden_%2810082673916%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Fishing_in_the_Kukkola_rapids%2C_Norrbotten%2C_Sweden_%2810082673916%29.jpg']::text[] where id='75e5fba0-4d98-4348-83bb-0de57229b9b0' and image_url is null; -- Peřeje Kukkolankoski
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Zbe%C4%8Dno_ze_%C5%BElut%C3%A9_zna%C4%8Dky.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Zbe%C4%8Dno_ze_%C5%BElut%C3%A9_zna%C4%8Dky.jpg']::text[] where id='76083423-d9f8-43fe-aa4a-d244a76b06b6' and image_url is null; -- Zbečno a Hamousův statek
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Radnice_Jihlava.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Radnice_Jihlava.jpg']::text[] where id='766c69f4-bfea-47c8-9906-0a6dfe4d3141' and image_url is null; -- Restaurace: Radniční restaurace (Jihlava)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Peera_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Peera_-_panoramio.jpg']::text[] where id='7710e1d8-60a7-4738-9801-04fed70007cc' and image_url is null; -- Peerajärvi
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/MODRANSK%C3%89_GRAFITY_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/MODRANSK%C3%89_GRAFITY_-_panoramio.jpg']::text[] where id='781ffa81-8a91-4d0d-8fc4-a40c89ac2fc8' and image_url is null; -- Restaurace: Elesko Wine Park (Modra)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bran%C4%8D%2C_hrad_od_juhov%C3%BDchodu_%282%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bran%C4%8D%2C_hrad_od_juhov%C3%BDchodu_%282%29.jpg']::text[] where id='7a64a4e3-8eca-4f0d-b4dc-570e56028abe' and image_url is null; -- Hrad Branč
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/28567._Grotli_-_Geirangerveien_%286799964206%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/28567._Grotli_-_Geirangerveien_%286799964206%29.jpg']::text[] where id='7e0f69e0-36e7-4805-baf1-637dede96993' and image_url is null; -- Grotli
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/AN_MPQ-55_HAWK_Continuous_Wave_Acquisition_Radar%2C_Stevnsfort_Cold_War_Museum%2C_Denmark%2C_2015-04-01-4826.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/AN_MPQ-55_HAWK_Continuous_Wave_Acquisition_Radar%2C_Stevnsfort_Cold_War_Museum%2C_Denmark%2C_2015-04-01-4826.jpg']::text[] where id='7e500f76-f181-41ef-b05d-d16cafa5495f' and image_url is null; -- Pevnost Stevnsfort
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kitzbuehel06.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kitzbuehel06.JPG']::text[] where id='7f017404-5aab-4de3-8a44-0be25a4361da' and image_url is null; -- Restaurace: Huberbräu Stüberl (Kitzbühel)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bory_Tucholskie%2C_j._Stelchno.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bory_Tucholskie%2C_j._Stelchno.jpg']::text[] where id='7f0b7514-db40-4155-b329-66709cb37b8a' and image_url is null; -- Stelchno Lake
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_D%C5%82ugie_%28Pojezierze_Dobrzy%C5%84skie%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_D%C5%82ugie_%28Pojezierze_Dobrzy%C5%84skie%29.jpg']::text[] where id='817f2908-57fd-4cbc-988b-9c9d82976223' and image_url is null; -- Jezioro Długie
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Fryken_See_Schweden.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Fryken_See_Schweden.JPG']::text[] where id='86a57584-9e5b-49d2-8f71-6ea9a5902ff9' and image_url is null; -- Nedre Fryken
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Trollhattefallen.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Trollhattefallen.jpg']::text[] where id='893d2e7f-7925-4037-9b99-ecb730d6ebf7' and image_url is null; -- Vodopády a zdymadla Trollhättan
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Entrance_of_the_cave_Baradla_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Entrance_of_the_cave_Baradla_-_panoramio.jpg']::text[] where id='89b9d20e-6401-4b58-a186-8d1bec4af5de' and image_url is null; -- Jeskyně Baradla
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kiilin_satama_ja_Salteriet.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kiilin_satama_ja_Salteriet.jpg']::text[] where id='8a8fe7d2-46ce-402e-9975-0e202cd5add0' and image_url is null; -- Restaurace: Salteriet (Svedjehamn)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Admont_-_Nationalpark_Ges%C3%A4use_-_Eisenbahnbr%C3%BCcke_%C3%BCber_die_Ges%C3%A4usestra%C3%9Fe.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Admont_-_Nationalpark_Ges%C3%A4use_-_Eisenbahnbr%C3%BCcke_%C3%BCber_die_Ges%C3%A4usestra%C3%9Fe.jpg']::text[] where id='8c2489d3-742f-4922-8beb-66a0a0a9938e' and image_url is null; -- NP Gesäuse — Gesäuseeingang
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/20180622_18_Kaunertaler_Gletscher_%2843048895491%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/20180622_18_Kaunertaler_Gletscher_%2843048895491%29.jpg']::text[] where id='8ee62ddc-831d-438e-882b-40991cc6f865' and image_url is null; -- Kaunertaler Gletscher
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kaly_-_rozhledna_Babylon_%282016%29_obr6.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kaly_-_rozhledna_Babylon_%282016%29_obr6.jpg']::text[] where id='905cc483-f757-4023-ae0c-e7b1c9154b00' and image_url is null; -- Rozhledna Babylon
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice_-_zidovske_ghetto13.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Boskovice_-_zidovske_ghetto13.JPG']::text[] where id='920e9072-bb24-45fd-84d8-8f666791e758' and image_url is null; -- Židovské město Boskovice
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kom%C3%A1rom173.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kom%C3%A1rom173.JPG']::text[] where id='93221f22-ad3c-4cfb-b710-f1ba1ba8dd33' and image_url is null; -- Restaurace: Banderium (Komárno)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Rev%C3%BAca%2C_pal%C3%A1c_II.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Rev%C3%BAca%2C_pal%C3%A1c_II.jpg']::text[] where id='93bfedf2-4a60-4a83-89bb-87c7e49dc4be' and image_url is null; -- Revúca – První slovenské gymnázium
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Langvatnet_P8122097.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Langvatnet_P8122097.jpg']::text[] where id='95bf3c23-740b-45ce-bf9f-7346fcb63dce' and image_url is null; -- Langvatnet
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sastin_bazilika_2.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sastin_bazilika_2.jpg']::text[] where id='95e1b1cc-8e7d-4cde-a025-69468c33b768' and image_url is null; -- Bazilika Šaštín-Stráže
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/H%C5%99eb%C4%8D%C3%ADn_Mimo%C5%88.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/H%C5%99eb%C4%8D%C3%ADn_Mimo%C5%88.jpg']::text[] where id='963dfa68-c93e-4144-aa4f-407f9c52a64d' and image_url is null; -- Máta – hřebčín
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Overview_of_Rok%C5%A1tejn_castle_near_Brtnice%2C_Jihlava_District.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Overview_of_Rok%C5%A1tejn_castle_near_Brtnice%2C_Jihlava_District.jpg']::text[] where id='985ef821-0f04-4bd0-93be-0279f61a821b' and image_url is null; -- Zřícenina hradu Rokštejn
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kastell_Ala_Nova.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kastell_Ala_Nova.jpg']::text[] where id='99b863bb-8334-46fe-be59-9a0e203733a0' and image_url is null; -- Castra Ala Nova
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Typical_wooden_bridge_and_view_in_the_Czech_part_of_the_Schwarzenberger_Schwemmkanal_-_1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Typical_wooden_bridge_and_view_in_the_Czech_part_of_the_Schwarzenberger_Schwemmkanal_-_1.jpg']::text[] where id='9b68fcf1-1c8c-4573-ac77-8fcedbace8b1' and image_url is null; -- Schwarzenberský plavební kanál (Jelení Vrchy)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Wiki-Iittala-yu1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Wiki-Iittala-yu1.jpg']::text[] where id='9bcb3f09-bec2-4f52-bbe2-9e237dfe7aac' and image_url is null; -- Sklárna Iittala
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Lettercraffroe_Lough_-_geograph.org.uk_-_4637697.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Lettercraffroe_Lough_-_geograph.org.uk_-_4637697.jpg']::text[] where id='9c3287dd-9091-4838-99b7-3482357e2791' and image_url is null; -- Lettercraffroe Lough
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_-_W%C4%85sosze_-_000122n.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_-_W%C4%85sosze_-_000122n.jpg']::text[] where id='9cd56631-fc65-4e52-b35f-fc55b641e41b' and image_url is null; -- Wąsosze
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vinn%C3%A9_sklepy_Petrov-Pl%C5%BEe.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vinn%C3%A9_sklepy_Petrov-Pl%C5%BEe.jpg']::text[] where id='9d7f852e-9e7d-4a61-9fda-2603531a584b' and image_url is null; -- Vinné sklepy Petrov-Plže
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/K%C5%99tiny_kostel_Jm%C3%A9na_Panny_Marie_poutn%C3%AD_are%C3%A1l_5.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/K%C5%99tiny_kostel_Jm%C3%A9na_Panny_Marie_poutn%C3%AD_are%C3%A1l_5.jpg']::text[] where id='9dfedb18-b2bf-45f5-a8de-99dd25ee0780' and image_url is null; -- Poutní kostel Křtiny
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_-_W%C4%85sosze_-_000122n.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_-_W%C4%85sosze_-_000122n.jpg']::text[] where id='9e5d621c-2144-4674-83a1-c5ec0eee9bda' and image_url is null; -- Wąsosze
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A9_Spi%C5%A1sk%C3%A9_pleso_Py%C5%A1n%C3%BD_%C5%A1t%C3%ADt.jpg']::text[] where id='9eb88057-c55a-4063-baa3-b5b4651da65b' and image_url is null; -- Pět Spišských ples
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hotel_maiensee_MDSC04784.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hotel_maiensee_MDSC04784.jpg']::text[] where id='a1bb4d04-c569-4209-8c1e-8d4c6d12214a' and image_url is null; -- Maiensee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Skuleberget-Norrfallsviken.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Skuleberget-Norrfallsviken.jpg']::text[] where id='a2b4342c-f445-4050-9c3b-2a37a0280baf' and image_url is null; -- Norrfällsviken
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Salt_pans_Ston_%284065531015%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Salt_pans_Ston_%284065531015%29.jpg']::text[] where id='a2c70994-a52b-4385-988c-a2e818d96d59' and image_url is null; -- Solné pánve Ston
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Magyarszombatfa_Fazekash%C3%A1z.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Magyarszombatfa_Fazekash%C3%A1z.JPG']::text[] where id='a332da1f-6d8e-4ab8-8861-8027821846bd' and image_url is null; -- Magyarszombatfa – hrnčířství
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov_-_panoramio_%2822%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bardejov_-_panoramio_%2822%29.jpg']::text[] where id='a42d5e24-6a36-4b65-9b77-cb5f504816b4' and image_url is null; -- Restaurace: Roland (Bardejov)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A1_T%C5%95%C5%88a%2C_Slovakia_Jul_08%2C_2022_12-53-38_PM.jpeg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mal%C3%A1_T%C5%95%C5%88a%2C_Slovakia_Jul_08%2C_2022_12-53-38_PM.jpeg']::text[] where id='a50f6c45-09c8-451a-8793-4a90948eecdb' and image_url is null; -- Restaurace: Tokaj Macík Winery (Malá Tŕňa)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Gamlitz_vom_Schererkogl_01.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Gamlitz_vom_Schererkogl_01.JPG']::text[] where id='a5b37479-0c3f-449c-9e8c-850b79007a6b' and image_url is null; -- Restaurace: Sattlerhof (Gamlitz)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/TipperneBanner.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/TipperneBanner.jpg']::text[] where id='a9faa6b4-1dd6-4fb7-b1cc-53cabd0405d5' and image_url is null; -- Tipperne
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Blokzijl_harbour.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Blokzijl_harbour.jpg']::text[] where id='abc922f6-991a-4f00-9e6d-6b3201007580' and image_url is null; -- Blokzijl
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Zor_Alef_Bulgariassa_Belogradchikissa_Kaleto_Fortressissa_Luento_2014.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Zor_Alef_Bulgariassa_Belogradchikissa_Kaleto_Fortressissa_Luento_2014.jpg']::text[] where id='ac389385-4b74-447e-98c5-053212c85b16' and image_url is null; -- Pevnost Belogradčik
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C4%8D%C3%ADn%2C_v%C3%BDhled_z_hradu_%281%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Dale%C4%8D%C3%ADn%2C_v%C3%BDhled_z_hradu_%281%29.jpg']::text[] where id='ad22aebe-e33e-406f-9902-dbbc2d4b7004' and image_url is null; -- Zřícenina hradu Dalečín
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Solnice_na_Piaristick%C3%A9m_n%C3%A1m%C4%9Bst%C3%AD_v_%C4%8Cesk%C3%BDch_Bud%C4%9Bjovic%C3%ADch.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Solnice_na_Piaristick%C3%A9m_n%C3%A1m%C4%9Bst%C3%AD_v_%C4%8Cesk%C3%BDch_Bud%C4%9Bjovic%C3%ADch.JPG']::text[] where id='ae799a9b-9bdb-4223-a402-bd7f5c3682d7' and image_url is null; -- Jihočeské motocyklové muzeum (Solnice)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Schermer_Museum_mill_as_a_reliqt_of_ancient_Dutch_%22polder%22_works_to_conquer_the_lakes_and_transform_it_into_land_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Schermer_Museum_mill_as_a_reliqt_of_ancient_Dutch_%22polder%22_works_to_conquer_the_lakes_and_transform_it_into_land_-_panoramio.jpg']::text[] where id='b19ba1b6-6e06-4610-91fe-709b16e47daa' and image_url is null; -- Museummolen Schermerhorn
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Ehemaliges_Pflegerhaus_in_K%C3%B6tschach-Mauthen.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Ehemaliges_Pflegerhaus_in_K%C3%B6tschach-Mauthen.jpg']::text[] where id='b2c54b7f-dcf5-4405-89d9-3f4a0913768c' and image_url is null; -- Restaurace: Landhaus Kellerwand (Kötschach-Mauthen)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro-wiecanowskie.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro-wiecanowskie.jpg']::text[] where id='b7b5dab3-adc2-437d-a744-1bab164e3e8c' and image_url is null; -- Wiecanowské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Stacks_at_Folhammar%2C_Ljugarn_2.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Stacks_at_Folhammar%2C_Ljugarn_2.jpg']::text[] where id='b7e8aa30-f413-41ca-b0a5-3d3f1e3c6d9d' and image_url is null; -- Rauky Folhammar (Ljugarn)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Dobrich_Region_-_Balchik_Municipality_-_Town_of_Balchik_-_Balchik_Palace_and_Botanical_Garden_%282%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Dobrich_Region_-_Balchik_Municipality_-_Town_of_Balchik_-_Balchik_Palace_and_Botanical_Garden_%282%29.jpg']::text[] where id='b8f6b56f-08e4-4137-a4a8-8d8b79200a3b' and image_url is null; -- Botanická zahrada Balčik
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Lieksa_-_Ukko-Koli_-_View_of_Pielinen_lake_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Lieksa_-_Ukko-Koli_-_View_of_Pielinen_lake_-_panoramio.jpg']::text[] where id='ba67950b-2d35-4256-b7e1-4042585341be' and image_url is null; -- Vyhlídka Ukko-Koli
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na02.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vydrick%C3%A1_br%C3%A1na02.jpg']::text[] where id='bbe60a7b-098e-453f-b4bf-337bb79d04d2' and image_url is null; -- Vydrická brána
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/River_Oslava_riverside_with_path_in_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/River_Oslava_riverside_with_path_in_N%C3%A1m%C4%9B%C5%A1%C5%A5_nad_Oslavou%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg']::text[] where id='bbed0d94-b42b-41f0-b5ca-39577d7bf46d' and image_url is null; -- Barokní kamenný most v Náměšti nad Oslavou
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/First_block_of_Dukovany_Nuclear_Power_Station_near_Dukovany%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/First_block_of_Dukovany_Nuclear_Power_Station_near_Dukovany%2C_T%C5%99eb%C3%AD%C4%8D_District.jpg']::text[] where id='bc4a8304-5036-4a1e-a9ca-7e3669b5855e' and image_url is null; -- Infocentrum JE Dukovany
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Ridderspranget_II.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Ridderspranget_II.jpg']::text[] where id='bfe9701f-b6a5-4b66-b85a-b2b5598c8202' and image_url is null; -- Ridderspranget
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Gulpen-Gulp_voor_Veldmolen.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Gulpen-Gulp_voor_Veldmolen.jpg']::text[] where id='c0a680ca-6ae0-4678-9f6d-d84a130f91de' and image_url is null; -- Restaurace: Gulpener Brouwlokaal (Gulpen)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_Rad%C4%99ci%C5%84skie%2C_pomosty_na_pla%C5%BCy_ko%C5%82o_Rad%C4%99cina.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jezioro_Rad%C4%99ci%C5%84skie%2C_pomosty_na_pla%C5%BCy_ko%C5%82o_Rad%C4%99cina.jpg']::text[] where id='c2da2f05-c52c-4039-a14d-961649bb8a4b' and image_url is null; -- Jezioro Radęcińskie
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mannaminne_Kramfors_2022_-_12.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mannaminne_Kramfors_2022_-_12.jpg']::text[] where id='c63eb725-33fe-4ec3-9fd7-1d7233d653ee' and image_url is null; -- Mannaminne (Häggvik)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sv._Jure%2C_Sveti_Jure%2C_1762_m._-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sv._Jure%2C_Sveti_Jure%2C_1762_m._-_panoramio.jpg']::text[] where id='c88049c5-8ad4-4df8-be2c-b8c20061f660' and image_url is null; -- Vrchol Sveti Jure
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Henningsvaer_2.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Henningsvaer_2.jpg']::text[] where id='d087df47-ab3a-47b9-a9d7-969dc7e8cab7' and image_url is null; -- Restaurace: Fiskekrogen (Henningsvær)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Buzludzha_Monument_Auditorium.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Buzludzha_Monument_Auditorium.jpg']::text[] where id='d1080435-d837-48cf-ad5e-26bb55b40f6d' and image_url is null; -- Pomník Buzludža
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Okshornan_from_Tungeneset%2C_2012_June.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Okshornan_from_Tungeneset%2C_2012_June.jpg']::text[] where id='d1b421f6-5301-4b74-b4b6-d4f8682558f3' and image_url is null; -- Tungeneset a Okshornan
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/On_Snaefell_Mountain_-_geograph.org.uk_-_1409324.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/On_Snaefell_Mountain_-_geograph.org.uk_-_1409324.jpg']::text[] where id='d4ed202b-2e5e-4c2b-946e-6d5d09348508' and image_url is null; -- Snaefell Mountain Road (Bungalow)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/G%C3%B6ta_Canal%2C_Motala%2C_Sweden_%283611178353%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/G%C3%B6ta_Canal%2C_Motala%2C_Sweden_%283611178353%29.jpg']::text[] where id='d5b8b1fe-941c-4a75-ba7a-474f072a0c6b' and image_url is null; -- Göta kanál (Motala)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%2C_kostol_sv._Michala%2C_port%C3%A1l.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Skalica%2C_kostol_sv._Michala%2C_port%C3%A1l.jpg']::text[] where id='d5bc81f2-b4fd-4a55-9103-4c12c43deac9' and image_url is null; -- Restaurace: Sv. Michal (Skalica)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Biokovo_%288341392319%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Biokovo_%288341392319%29.jpg']::text[] where id='d76076da-41d6-4160-adc7-060627d3edb7' and image_url is null; -- Skywalk Biokovo
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/A%C3%ADnsa.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/A%C3%ADnsa.jpg']::text[] where id='d965c795-f858-4aa2-aebb-db2cee6fbbd2' and image_url is null; -- Restaurace: Callizo (Aínsa)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Viking_Ship_Museum%2C_Roskilde_%282169039016%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Viking_Ship_Museum%2C_Roskilde_%282169039016%29.jpg']::text[] where id='dae23f0e-b6cf-4897-940f-e068743db6ed' and image_url is null; -- Muzeum vikingských lodí Roskilde
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Karlsborg_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Karlsborg_-_panoramio.jpg']::text[] where id='dcc4a600-3eec-47e8-98ce-fbe42d70603b' and image_url is null; -- Pevnost Karlsborg
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bl%C3%A5vandshuk_-_Leuchtturm1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bl%C3%A5vandshuk_-_Leuchtturm1.jpg']::text[] where id='dcd909e4-4b3f-4287-adb8-d36f2b1b5790' and image_url is null; -- Blåvand a maják
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/946_03_Kol%C3%A1rovo%2C_Slovakia_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/946_03_Kol%C3%A1rovo%2C_Slovakia_-_panoramio.jpg']::text[] where id='dfb8d055-0eb4-4223-8698-deca308289f4' and image_url is null; -- Vodní mlýn Kolárovo
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Viekijarvi_church_2019.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Viekijarvi_church_2019.jpg']::text[] where id='e022b88f-f3b9-48cd-8ac2-591a7861a484' and image_url is null; -- Viekijärvi
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Slatinka_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Slatinka_-_panoramio.jpg']::text[] where id='e050c34e-1347-47d8-9af3-057a4443facc' and image_url is null; -- Vodní dílo Slatinka
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98sterlars_Kirke_7.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/%C3%98sterlars_Kirke_7.jpg']::text[] where id='e0664e38-24a5-4662-8de0-a9343eddaccc' and image_url is null; -- Kulatý kostel Østerlars
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Sanctuaire_de_Lourdes.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Sanctuaire_de_Lourdes.JPG']::text[] where id='e2226356-c3b4-4666-96c0-4347d303d1ce' and image_url is null; -- Sanktuárium Lourdes
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Soutok_Dyje_a_Moravy.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Soutok_Dyje_a_Moravy.jpg']::text[] where id='e3ed800f-4a79-4784-9823-1af7ebd0cfb2' and image_url is null; -- Soutok Moravy a Dyje
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Mariborsko_Pohorje_ski_resort_%2852577794933%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Mariborsko_Pohorje_ski_resort_%2852577794933%29.jpg']::text[] where id='e61a4b4a-2ba6-4c43-b71c-b00bd302e321' and image_url is null; -- Mariborsko Pohorje
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hora_Svat%C3%A9_Kate%C5%99iny_-_ulice_R%C5%AF%C5%BEov%C3%BD_vrch_obr02.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hora_Svat%C3%A9_Kate%C5%99iny_-_ulice_R%C5%AF%C5%BEov%C3%BD_vrch_obr02.jpg']::text[] where id='e737d452-e2c3-4b96-a457-6749ec4be72b' and image_url is null; -- Růžový vrch
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDidlochovice_-_h%C5%99ebenov%C3%A1_cesta_na_V%C3%BDhonu%2C_2021-11%2C_obr02.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDidlochovice_-_h%C5%99ebenov%C3%A1_cesta_na_V%C3%BDhonu%2C_2021-11%2C_obr02.jpg']::text[] where id='e7bf2210-0aa3-4120-a539-bf0d4fcb22cd' and image_url is null; -- Výhon u Židlochovic
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Eksh%C3%A4rad_kyrka.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Eksh%C3%A4rad_kyrka.JPG']::text[] where id='e9259bf0-43ee-4965-ba6c-29f8ff48c4b1' and image_url is null; -- Kostel v Ekshäradu
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/El_Faro_de_Fisterra_-_Camino_2009_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/El_Faro_de_Fisterra_-_Camino_2009_-_panoramio.jpg']::text[] where id='ea90cd82-1a38-49d6-9b6e-873f4efbc9ef' and image_url is null; -- Restaurace: O Semáforo (Fisterra)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kajsarn_3_Ringmuren_Visby.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kajsarn_3_Ringmuren_Visby.jpg']::text[] where id='ebf72b7d-2e0f-400c-b9f3-276637ece803' and image_url is null; -- Restaurace: Bakfickan (Visby)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Lake_Lysevegen_03.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Lake_Lysevegen_03.jpg']::text[] where id='ed873763-073c-4757-bb45-7e02c8069bf9' and image_url is null; -- Lysevegen – 27 serpentin
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Vaaksynkanava.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Vaaksynkanava.jpg']::text[] where id='ee755543-fc0f-4ba1-a8b8-80f5cc8160b9' and image_url is null; -- Kanál Vääksy
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Parque_Natural_Sierra_de_Cazorla_Ceazorla.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Parque_Natural_Sierra_de_Cazorla_Ceazorla.jpg']::text[] where id='efed3e29-61c1-4a90-ae5a-650937c4103a' and image_url is null; -- Restaurace: Mesón Leandro (Cazorla)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%A4llberg_Golfbana_h%C3%A5l_3.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%A4llberg_Golfbana_h%C3%A5l_3.JPG']::text[] where id='f04be7ed-8ada-4387-870c-4368277f3ec3' and image_url is null; -- Restaurace: Klockargården (Tällberg)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bor%C5%A1a_ka%C5%A1tie%C4%BE_03.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bor%C5%A1a_ka%C5%A1tie%C4%BE_03.jpg']::text[] where id='f4acecc8-ea0b-4837-b801-7f9252cdf99e' and image_url is null; -- Kaštieľ Borša
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Tanumshede_Vitlycke_museum.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Tanumshede_Vitlycke_museum.jpg']::text[] where id='f5045c1a-a4ff-454f-86bc-b43bac0296b2' and image_url is null; -- Skalní rytiny Vitlycke (UNESCO)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Villach_Landskron_Schlossbergweg_30_Burgruine_SW-Ansicht_23072006_31.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Villach_Landskron_Schlossbergweg_30_Burgruine_SW-Ansicht_23072006_31.jpg']::text[] where id='f6785978-d4fc-484a-ad5b-c60045fc61eb' and image_url is null; -- Restaurace: Burgrestaurant Landskron (Villach)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Banner.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Belogradchik_Banner.jpg']::text[] where id='f741a614-3911-4350-bc44-1fbce35fa6df' and image_url is null; -- Belogradčické skály
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Tour_des_Jacobins_%28Bagn%C3%A8res-de-Bigorre%29.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Tour_des_Jacobins_%28Bagn%C3%A8res-de-Bigorre%29.JPG']::text[] where id='f7807c04-0334-4eb1-912c-05dbd5323c53' and image_url is null; -- Restaurace: Le Jardin des Brouches (Bagnères-de-Bigorre)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Ve%C4%BEk%C3%BD_Kamenec_-_A_view_of_the_village_and_the_Tarbucka_hill_ridge_west_of_the_village%2C_from_the_Kamenec_castle_hill_%28October_2006%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Ve%C4%BEk%C3%BD_Kamenec_-_A_view_of_the_village_and_the_Tarbucka_hill_ridge_west_of_the_village%2C_from_the_Kamenec_castle_hill_%28October_2006%29.jpg']::text[] where id='f7b218d6-dd89-4333-bdb4-bf69e1868dc7' and image_url is null; -- Tarbucka
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Kilenclyuk%C3%BA_h%C3%ADd_a_Hortob%C3%A1gyon_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Kilenclyuk%C3%BA_h%C3%ADd_a_Hortob%C3%A1gyon_-_panoramio.jpg']::text[] where id='fafea3a3-c23c-4534-87e9-7777b3e0f2e3' and image_url is null; -- Pastevecké muzeum Hortobágy
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Humenn%C3%A9_-_Humensk%C3%BD_z%C3%A1mok_%28Ka%C5%A1tie%C4%BE_v_Humennom%29_001.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Humenn%C3%A9_-_Humensk%C3%BD_z%C3%A1mok_%28Ka%C5%A1tie%C4%BE_v_Humennom%29_001.jpg']::text[] where id='fd31b8ae-936e-4438-9e8b-1b7322771f11' and image_url is null; -- Kaštieľ Humenné
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Road_to_Trigrad_%2848891163981%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Road_to_Trigrad_%2848891163981%29.jpg']::text[] where id='ff22432e-d409-4397-81d2-0c4ff32ef8f1' and image_url is null; -- Soutěska Trigrad

-- === B) route_pois se ŠPATNOU fotkou (jiný objekt): nahrazení správnou ===
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg']::text[] where id='003cd62b-b4f7-43e7-b3b5-f4c1df2f7459'; -- Skalnaté pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A9_pleso_2010_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A9_pleso_2010_01.jpg']::text[] where id='017e284d-b03a-4d7f-835a-c4f694b4da94'; -- Modré pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Nova_Bystrice_%282%29.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Nova_Bystrice_%282%29.JPG']::text[] where id='07ac2ff5-9c4b-4877-a997-e424dd2a992b'; -- Restaurace: Pivovar Nová Bystřice (Nová Bystřice)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Schloss_Fernstein_%28Kapelle%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Schloss_Fernstein_%28Kapelle%29.jpg']::text[] where id='0e3359b6-87ed-4978-963a-a462477d6764'; -- Fernsteinsee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg']::text[] where id='105f0bfb-d8f1-4752-ad0a-b5afed7e0792'; -- Prášilské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jamnick%C3%A9_pleso.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jamnick%C3%A9_pleso.jpg']::text[] where id='1b617754-b702-46a1-a9dc-669c5d7757b5'; -- Vyšné Jamnícke pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Schloss_Fernstein_%28Kapelle%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Schloss_Fernstein_%28Kapelle%29.jpg']::text[] where id='1d097d62-541d-4ac1-84e1-12986dd0a279'; -- Fernsteinsee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg']::text[] where id='1db9c61f-1f17-4b18-84ca-445ddc8f2aef'; -- Katedrála svatého Martina
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Augstie_Tatri%2C_Vel%27ka_Studena_dolina_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Augstie_Tatri%2C_Vel%27ka_Studena_dolina_-_panoramio.jpg']::text[] where id='2480e916-dd81-4e5f-9b56-beb31c36582d'; -- Nižné Studené pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/POL_Zarzecze_Gocza%C5%82kowickie_Pano_1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/POL_Zarzecze_Gocza%C5%82kowickie_Pano_1.jpg']::text[] where id='24f7b726-fb1b-468d-a3c3-9845518f771a'; -- Goczałkowická přehrada
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg']::text[] where id='27c1f05d-efc3-4789-9ac3-af2f4901db62'; -- Skalnaté pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg']::text[] where id='2d0b80cb-d7e8-4899-955c-5d3fdd7f009e'; -- Prášilské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Morschreuth_Panorama_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Morschreuth_Panorama_01.jpg']::text[] where id='2f169be0-5b33-4d1a-af3e-22f1433bc299'; -- Restaurace: Gasthof Zur Guten Einkehr (Gößweinstein-Morschreuth)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Stara_Vas_Postojna_Slovenia_1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Stara_Vas_Postojna_Slovenia_1.jpg']::text[] where id='3233c304-b13c-470a-ab7f-c9d80d2e1077'; -- Stará Vas – kostel
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Nida-Hafen02.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Nida-Hafen02.jpg']::text[] where id='32405dbc-620c-44dd-9009-d4e81074fc97'; -- Restaurace: Tik Pas Joną (Nida)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Nockberge_Blutige_Alm_Panorama_S_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Nockberge_Blutige_Alm_Panorama_S_01.jpg']::text[] where id='325576b0-3b21-4c78-9a22-ec36c694d02c'; -- Biosférická rezervace Nockberge
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jamnick%C3%A9_pleso.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jamnick%C3%A9_pleso.jpg']::text[] where id='36273719-a6df-416f-98fc-df7229e06c01'; -- Vyšné Jamnícke pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg']::text[] where id='36b9e165-43f1-492f-a65d-70f52a0e6fc0'; -- Prášilské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Baile_Chaisle%C3%A1in_Bh%C3%A9arra_%28Castletownbere%29_-_geograph.org.uk_-_267078.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Baile_Chaisle%C3%A1in_Bh%C3%A9arra_%28Castletownbere%29_-_geograph.org.uk_-_267078.jpg']::text[] where id='37b3a802-f5e4-4122-9fb2-025236a9801c'; -- Restaurace: MacCarthy''s Bar (Castletownbere)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bobolice%2C_zamek_w_Bobolicach_dziedziniec.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bobolice%2C_zamek_w_Bobolicach_dziedziniec.jpg']::text[] where id='3be88d7b-b632-4e93-a801-e6bb466bfbeb'; -- Bobolice
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Banjolei_strand_r%C3%A9szlet_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Banjolei_strand_r%C3%A9szlet_-_panoramio.jpg']::text[] where id='3ed971b6-060e-4cde-aedd-df7b199e6139'; -- Restaurace: Konoba Batelina (Banjole)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A9_pleso_2010_01.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Modr%C3%A9_pleso_2010_01.jpg']::text[] where id='41d7aa2c-a348-4956-8598-4904230235ec'; -- Modré pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jamnick%C3%A9_pleso.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jamnick%C3%A9_pleso.jpg']::text[] where id='4729e794-0966-49fd-bb77-09b804cae6c1'; -- Vyšné Jamnícke pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg']::text[] where id='4870cba7-4af8-487b-950b-760f2940e90c'; -- Katedrála svatého Martina
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Niegocin_w_zimie_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Niegocin_w_zimie_-_panoramio.jpg']::text[] where id='4e8acefe-5650-45b6-8ea7-f0f9e1dba66f'; -- Niegocin
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A1%C5%A1ilsk%C3%A9_jezero-panorama_-_panoramio.jpg']::text[] where id='724980d0-4511-47d4-b4d6-3f0d476a92f3'; -- Prášilské jezero
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Eberlsee03.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Eberlsee03.jpg']::text[] where id='77cd4501-6ce7-41c9-ba14-55f424964840'; -- Eberlsee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg']::text[] where id='83c78ca4-ef6a-494f-abe1-e692172d4cc4'; -- Skalnaté pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg']::text[] where id='87c9243b-94d9-4282-aea5-1ad32d9dae4a'; -- Katedrála svatého Martina
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Trhov%C3%A1_Kamenice%2C_Zub%C5%99%C3%AD%2C_lookout.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Trhov%C3%A1_Kamenice%2C_Zub%C5%99%C3%AD%2C_lookout.jpg']::text[] where id='93e9af2e-2e05-44dc-87a0-18075aa82f76'; -- Zubří – rozhledna
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Corvara_1560_m%2C_Boi_-_Vallon%2C_Sass_Boe_3131m_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Corvara_1560_m%2C_Boi_-_Vallon%2C_Sass_Boe_3131m_-_panoramio.jpg']::text[] where id='9a4044a1-7829-4553-9207-4f4c53c61b28'; -- Restaurace: Ristorante Cialdira Ladina (Corvara)
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Skalnate_pleso_-_panoramio.jpg']::text[] where id='9c517c91-4cb0-406a-a8c9-491e67383909'; -- Skalnaté pleso
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Tauernmoossee_2007-09-03.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Tauernmoossee_2007-09-03.jpg']::text[] where id='a5204920-6c5a-4377-8d78-94d73ea9b22d'; -- Tauernmoossee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Eberlsee03.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Eberlsee03.jpg']::text[] where id='a8cfbb0d-e78d-4994-bd39-cef212593c60'; -- Eberlsee
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/St_Martin_church_001.jpg']::text[] where id='ae22ae92-b4b3-44ce-90b5-7a6f11ec2650'; -- Katedrála svatého Martina
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Besenova-_Thermal_Park_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Besenova-_Thermal_Park_-_panoramio.jpg']::text[] where id='c593863b-dcaf-4841-b35a-355336752348'; -- Vodní nádrž Bešeňová
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Svr%C4%8Dinn%C3%ADk_-_panoramio.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Svr%C4%8Dinn%C3%ADk_-_panoramio.jpg']::text[] where id='c6fbb317-51ec-4d9a-aa50-6b358e29c419'; -- Svrčinník
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Bobolice%2C_zamek_w_Bobolicach_dziedziniec.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Bobolice%2C_zamek_w_Bobolicach_dziedziniec.jpg']::text[] where id='c71e32b0-2ddf-480d-b844-0f6a4cf9d476'; -- Bobolice
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Melechov_Natural_Park_2.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Melechov_Natural_Park_2.jpg']::text[] where id='ccfc7b15-bc53-4160-ab78-06d4acae2fef'; -- Melechov
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/POL_Zarzecze_Gocza%C5%82kowickie_Pano_1.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/POL_Zarzecze_Gocza%C5%82kowickie_Pano_1.jpg']::text[] where id='cdb1be54-0cf2-4ddf-8fa4-5049e1ba0789'; -- Goczałkowická přehrada
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Hronsky_Benadik-Hlavny_portal_klastorneho_kostola.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Hronsky_Benadik-Hlavny_portal_klastorneho_kostola.jpg']::text[] where id='df7feff0-fdfb-449a-8162-47a339e2879d'; -- Klášter Hronský Beňadik
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/Jeskyn%C4%9B_svat%C3%A9ho_Ivana_%28Svat%C3%BD_Jan_pod_Skalou%29_%283%29.jpg', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/Jeskyn%C4%9B_svat%C3%A9ho_Ivana_%28Svat%C3%BD_Jan_pod_Skalou%29_%283%29.jpg']::text[] where id='e4a5a344-aa9b-4e52-8655-5134b7cecd09'; -- Jeskyně Svatého Ivana
update public.route_pois set image_url='https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9_Bud%C4%9Bjovice%2C_%C4%8Cesk%C3%A1_ulice.JPG', images=array['https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cesk%C3%A9_Bud%C4%9Bjovice%2C_%C4%8Cesk%C3%A1_ulice.JPG']::text[] where id='e7a02d44-28d4-4733-a20f-1427a30c3214'; -- Restaurace: Krajinská 27 (České Budějovice)

commit;

