-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — POLSKO (10 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Kladská kotlina a Stolové hory
  delete from public.routes where name = 'Kladská kotlina a Stolové hory' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kladská kotlina a Stolové hory', 'Okruh nejkrásnějšími silnicemi Kladské kotliny hned za českou hranicí. Serpentiny přes Stolové hory, lázeňská městečka a mohutná pevnost Kłodzko střídají svižné úseky mezi Dušníky a Bystřicí. Nejlepší od května do října; pozor na úzké horské okresky, turisty a rychle se měnící počasí v hřebenech.', 'loop', 185, 270, 'medium',
     '[{"lat": 50.4344, "lng": 16.6619, "label": "Start: Kłodzko"}, {"lat": 50.4056, "lng": 16.3706, "label": "Duszniki-Zdrój"}, {"lat": 50.4433, "lng": 16.2469, "label": "Kudowa-Zdrój"}, {"lat": 50.4744, "lng": 16.3372, "label": "Stolové hory – Szczeliniec"}, {"lat": 50.3061, "lng": 16.6486, "label": "Bystrzyca Kłodzka"}, {"lat": 50.4344, "lng": 16.6619, "label": "Cíl: Kłodzko"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.4344,16.6619&destination=50.4344,16.6619&travelmode=driving&waypoints=50.4056,16.3706%7C50.4433,16.2469%7C50.4744,16.3372%7C50.3061,16.6486', 'https://commons.wikimedia.org/wiki/Special:FilePath/Twierdza_K%C5%82odzka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Twierdza_K%C5%82odzka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Duszniki-Zdr%C3%B3j_-_rynek.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szczeliniec_Wielki.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kudowa-Zdr%C3%B3j_-_park_zdrojowy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bystrzyca_K%C5%82odzka_-_panorama.jpg"}'::text[], '{"Pevnost Kłodzko","Duszniki-Zdrój","Szczeliniec Wielki","Kudowa-Zdrój","Bystrzyca Kłodzka"}'::text[], '{"PL"}'::text[], false, 4710, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Pevnost Kłodzko', 'Mohutná barokní pevnost nad městem s labyrintem podzemních chodeb a výhledem na celou kotlinu. Jedna z nejzachovalejších fortifikací v Polsku.', 50.4361, 16.6572, 'https://commons.wikimedia.org/wiki/Special:FilePath/Twierdza_K%C5%82odzka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Twierdza_K%C5%82odzka.jpg"}'::text[], 0),
    (v_route, 'Duszniki-Zdrój', 'Půvabné lázeňské město s historickou papírnou a každoročním Chopinovým festivalem. Ideální zastávka na kávu na náměstí.', 50.4056, 16.3706, 'https://commons.wikimedia.org/wiki/Special:FilePath/Duszniki-Zdr%C3%B3j_-_rynek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Duszniki-Zdr%C3%B3j_-_rynek.jpg"}'::text[], 1),
    (v_route, 'Szczeliniec Wielki', 'Nejvyšší vrchol Stolových hor s bizarními skalními útvary a vyhlídkami do kraje. K parkovišti pod vrcholem vede pěkná horská silnice.', 50.4744, 16.3372, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szczeliniec_Wielki.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szczeliniec_Wielki.jpg"}'::text[], 2),
    (v_route, 'Kudowa-Zdrój', 'Příhraniční lázeňské městečko s parkem a nedalekou kaplí lebek v Czermné. Klidná zastávka kousek od hranice.', 50.4433, 16.2469, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kudowa-Zdr%C3%B3j_-_park_zdrojowy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kudowa-Zdr%C3%B3j_-_park_zdrojowy.jpg"}'::text[], 3),
    (v_route, 'Bystrzyca Kłodzka', 'Historické město na ostrohu nad řekou Nysou s dochovanými hradbami a muzeem sirek. Malebné uličky staré zástavby.', 50.3061, 16.6486, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bystrzyca_K%C5%82odzka_-_panorama.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bystrzyca_K%C5%82odzka_-_panorama.jpg"}'::text[], 4);

  -- Krkonoše z polské strany
  delete from public.routes where name = 'Krkonoše z polské strany' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Krkonoše z polské strany', 'Vyjížďka pod nejvyššími vrcholy Krkonoš na polské straně hor. Karpacz se Sněžkou, Szklarska Poręba a vodopád Kamieńczyka nabízí táhlé zatáčky lesními úseky. Nejlepší v létě; pozor na dřevo a listí v zatáčkách a na horský provoz o víkendech.', 'loop', 150, 225, 'medium',
     '[{"lat": 50.9033, "lng": 15.7367, "label": "Start: Jelenia Góra"}, {"lat": 50.7803, "lng": 15.7519, "label": "Karpacz"}, {"lat": 50.8272, "lng": 15.5219, "label": "Szklarska Poręba"}, {"lat": 50.8072, "lng": 15.51, "label": "Vodopád Kamieńczyk"}, {"lat": 50.8494, "lng": 15.7106, "label": "Zámek Chojnik"}, {"lat": 50.9033, "lng": 15.7367, "label": "Cíl: Jelenia Góra"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.9033,15.7367&destination=50.9033,15.7367&travelmode=driving&waypoints=50.7803,15.7519%7C50.8272,15.5219%7C50.8072,15.51%7C50.8494,15.7106', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_Wang_w_Karpaczu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_Wang_w_Karpaczu.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szklarska_Por%C4%99ba.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Wodospad_Kamie%C5%84czyka.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Chojnik.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jelenia_G%C3%B3ra_-_rynek.jpg"}'::text[], '{"Karpacz a kostel Wang","Szklarska Poręba","Vodopád Kamieńczyk","Zámek Chojnik","Jelenia Góra – náměstí"}'::text[], '{"PL"}'::text[], false, 4720, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Karpacz a kostel Wang', 'Horské středisko pod Sněžkou se středověkým dřevěným kostelem Wang přeneseným až z Norska. Výchozí bod k nejvyššímu vrcholu Krkonoš.', 50.7803, 15.7519, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_Wang_w_Karpaczu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bci%C3%B3%C5%82_Wang_w_Karpaczu.jpg"}'::text[], 0),
    (v_route, 'Szklarska Poręba', 'Oblíbené středisko na západě Krkonoš, brána k vodopádům a hřebenům. Pěkné náměstí a spousta občerstvení.', 50.8272, 15.5219, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szklarska_Por%C4%99ba.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szklarska_Por%C4%99ba.jpg"}'::text[], 1),
    (v_route, 'Vodopád Kamieńczyk', 'Nejvyšší krkonošský vodopád (27 m) padající do úzké skalní rokle. Krátká procházka od parkoviště lesem.', 50.8072, 15.51, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wodospad_Kamie%C5%84czyka.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wodospad_Kamie%C5%84czyka.jpg"}'::text[], 2),
    (v_route, 'Zámek Chojnik', 'Zřícenina gotického hradu na strmém ostrohu s dalekým výhledem do Jelenohorské kotliny. Romantická zastávka nad lesy.', 50.8494, 15.7106, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Chojnik.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Chojnik.jpg"}'::text[], 3),
    (v_route, 'Jelenia Góra – náměstí', 'Historické centrum s podloubím a barevnými měšťanskými domy. Ideální na oběd před nebo po okruhu.', 50.9033, 15.7367, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jelenia_G%C3%B3ra_-_rynek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jelenia_G%C3%B3ra_-_rynek.jpg"}'::text[], 4);

  -- Bieszczady – Velký okruh
  delete from public.routes where name = 'Bieszczady – Velký okruh' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Bieszczady – Velký okruh', 'Legendární Velká bieszczadská obwodnica nejdivočejším koutem Polska. Prázdné silnice, horské průsmyky a poloniny táhnoucí se k obzoru, mezi tím dřevěné cerkve a stáda. Nejlepší od června do září; pozor na dobytek na silnici, řídké čerpací stanice a mlhy v sedlech.', 'loop', 175, 240, 'medium',
     '[{"lat": 49.4703, "lng": 22.3306, "label": "Start: Lesko"}, {"lat": 49.4033, "lng": 22.4589, "label": "Solina – přehrada"}, {"lat": 49.1611, "lng": 22.5158, "label": "Wetlina"}, {"lat": 49.1, "lng": 22.6906, "label": "Ustrzyki Górne"}, {"lat": 49.2003, "lng": 22.7189, "label": "Smolnik"}, {"lat": 49.4703, "lng": 22.3306, "label": "Cíl: Lesko"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.4703,22.3306&destination=49.4703,22.3306&travelmode=driving&waypoints=49.4033,22.4589%7C49.1611,22.5158%7C49.1,22.6906%7C49.2003,22.7189', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zapora_Soli%C5%84ska.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zapora_Soli%C5%84ska.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ustrzyki_G%C3%B3rne.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Wetlina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cerkiew_w_Smolniku.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lesko_synagoga.jpg"}'::text[], '{"Přehrada Solina","Ustrzyki Górne","Wetlina","Cerkev v Smolniku","Lesko – synagoga a zámek"}'::text[], '{"PL"}'::text[], false, 4730, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Přehrada Solina', 'Největší vodní nádrž v Polsku s impozantní hrází a jezerem mezi zalesněnými kopci. Oblíbené místo na projížďku lodí i fotky.', 49.4033, 22.4589, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zapora_Soli%C5%84ska.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zapora_Soli%C5%84ska.jpg"}'::text[], 0),
    (v_route, 'Ustrzyki Górne', 'Horská osada v srdci Bieszczad, výchozí bod na poloniny. Poslední civilizace před nejdivočejšími hřebeny.', 49.1, 22.6906, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ustrzyki_G%C3%B3rne.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ustrzyki_G%C3%B3rne.jpg"}'::text[], 1),
    (v_route, 'Wetlina', 'Osada v údolí obklopená polodivokými kopci, oblíbená mezi motorkáři a trampy. Skvělé místo na svařák a klid.', 49.1611, 22.5158, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wetlina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wetlina.jpg"}'::text[], 2),
    (v_route, 'Cerkev v Smolniku', 'Dřevěná řeckokatolická cerkev zapsaná na seznam UNESCO, památka po zdejších Bojcích. Ukázka mizející kultury Bieszczad.', 49.2003, 22.7189, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cerkiew_w_Smolniku.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cerkiew_w_Smolniku.jpg"}'::text[], 3),
    (v_route, 'Lesko – synagoga a zámek', 'Bývalé pohraniční městečko s renesanční synagogou a zámkem Kmitů. Brána do Bieszczad s dobrým zázemím.', 49.4703, 22.3306, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lesko_synagoga.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lesko_synagoga.jpg"}'::text[], 4);

  -- Pieniny a průlom Dunajce
  delete from public.routes where name = 'Pieniny a průlom Dunajce' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Pieniny a průlom Dunajce', 'Okruh kolem malebného pohoří Pieniny na slovenské hranici. Serpentiny nad průlomem Dunajce, pohádkový hrad Niedzica nad jezerem a lázeňská Szczawnica lákají na svižnou i pohodovou jízdu. Nejlepší od jara do podzimu; pozor na turistický provoz a úzké silnice u přehrady.', 'loop', 140, 210, 'medium',
     '[{"lat": 49.4772, "lng": 20.0322, "label": "Start: Nowy Targ"}, {"lat": 49.4189, "lng": 20.4189, "label": "Krościenko"}, {"lat": 49.4269, "lng": 20.4842, "label": "Szczawnica"}, {"lat": 49.4189, "lng": 20.3053, "label": "Niedzica"}, {"lat": 49.4383, "lng": 20.31, "label": "Czorsztyn"}, {"lat": 49.4772, "lng": 20.0322, "label": "Cíl: Nowy Targ"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=49.4772,20.0322&destination=49.4772,20.0322&travelmode=driving&waypoints=49.4189,20.4189%7C49.4269,20.4842%7C49.4189,20.3053%7C49.4383,20.31', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Niedzicy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Niedzicy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szczawnica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Czorsztyn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Prze%C5%82om_Dunajca.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nowy_Targ_rynek.jpg"}'::text[], '{"Hrad Niedzica","Szczawnica","Zřícenina Czorsztyn","Průlom Dunajce","Nowy Targ"}'::text[], '{"PL"}'::text[], false, 4740, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Niedzica', 'Pohádkový gotický hrad Dunajec nad Czorsztyńským jezerem, opředený legendami o inckém pokladu. Jeden z nejfotogeničtějších hradů v Polsku.', 49.4189, 20.3053, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Niedzicy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Niedzicy.jpg"}'::text[], 0),
    (v_route, 'Szczawnica', 'Půvabné lázeňské městečko na úpatí Pienin, cíl splavů Dunajce na dřevěných vorech. Příjemná promenáda a zázemí.', 49.4269, 20.4842, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szczawnica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szczawnica.jpg"}'::text[], 1),
    (v_route, 'Zřícenina Czorsztyn', 'Zřícenina královského hradu na protějším břehu jezera naproti Niedzici. Krásný výhled na vodní hladinu a Pieniny.', 49.4383, 20.31, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Czorsztyn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Czorsztyn.jpg"}'::text[], 2),
    (v_route, 'Průlom Dunajce', 'Dramatický kaňon, kterým se řeka prořezává mezi vápencovými štíty Pienin. Ikonická scenérie polsko-slovenského pomezí.', 49.4064, 20.42, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prze%C5%82om_Dunajca.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Prze%C5%82om_Dunajca.jpg"}'::text[], 3),
    (v_route, 'Nowy Targ', 'Hlavní město Podhalí s velkým náměstím a výhledy na Tatry. Dobré zázemí a brána do polských hor.', 49.4772, 20.0322, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nowy_Targ_rynek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nowy_Targ_rynek.jpg"}'::text[], 4);

  -- Mazurská velká jezera
  delete from public.routes where name = 'Mazurská velká jezera' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mazurská velká jezera', 'Pohodový okruh krajem tisíce jezer na severovýchodě Polska. Táhlé silnice mezi hladinami, zvedací most v Giżycku, poutní Svatá Lipka a Vlčí doupě spojují klidnou jízdu s historií. Nejlepší od května do září; pozor na turisty v přístavech a přejezdy přes mosty.', 'loop', 210, 270, 'easy',
     '[{"lat": 54.0378, "lng": 21.7644, "label": "Start: Giżycko"}, {"lat": 53.8025, "lng": 21.5789, "label": "Mikołajki"}, {"lat": 53.9375, "lng": 21.5464, "label": "Ryn"}, {"lat": 54.0983, "lng": 21.4972, "label": "Święta Lipka"}, {"lat": 54.0803, "lng": 21.4939, "label": "Wilczy Szaniec"}, {"lat": 54.0378, "lng": 21.7644, "label": "Cíl: Giżycko"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.0378,21.7644&destination=54.0378,21.7644&travelmode=driving&waypoints=53.8025,21.5789%7C53.9375,21.5464%7C54.0983,21.4972%7C54.0803,21.4939', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kanal_Gi%C5%BCycki_i_most_obrotowy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kanal_Gi%C5%BCycki_i_most_obrotowy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Ryn_(3).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Miko%C5%82ajki_miasto.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/POL_Swieta_Lipka_001.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Poland._K%C4%99trzyn._Gier%C5%82o%C5%BC._Wolf%27s_Lair_009.JPG"}'::text[], '{"Giżycko a zvedací most","Zámek Ryn","Mikołajki","Poutní bazilika Święta Lipka","Vlčí doupě (Wilczy Szaniec)"}'::text[], '{"PL"}'::text[], false, 4750, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Giżycko a zvedací most', 'Přístavní město mezi jezery Niegocin a Kisajno s unikátním otočným mostem přes Luczański kanál. Srdce mazurského jachtingu.', 54.0378, 21.7644, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kanal_Gi%C5%BCycki_i_most_obrotowy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kanal_Gi%C5%BCycki_i_most_obrotowy.jpg"}'::text[], 0),
    (v_route, 'Zámek Ryn', 'Mohutný cihlový hrad Německých rytířů nad jezerem Ryńskie, dnes hotel. Dominanta městečka a pěkný výhled na vodu.', 53.9375, 21.5464, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Ryn_(3).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Ryn_(3).jpg"}'::text[], 1),
    (v_route, 'Mikołajki', 'Půvabné přístavní městečko zvané perla Mazur, plné jachet a kaváren u vody. Živá zastávka na oběd.', 53.8025, 21.5789, 'https://commons.wikimedia.org/wiki/Special:FilePath/Miko%C5%82ajki_miasto.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Miko%C5%82ajki_miasto.jpg"}'::text[], 2),
    (v_route, 'Poutní bazilika Święta Lipka', 'Skvostná barokní poutní bazilika s proslulými varhanami s pohyblivými figurami. Jeden z nejkrásnějších kostelů severu.', 54.0983, 21.4972, 'https://commons.wikimedia.org/wiki/Special:FilePath/POL_Swieta_Lipka_001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/POL_Swieta_Lipka_001.jpg"}'::text[], 3),
    (v_route, 'Vlčí doupě (Wilczy Szaniec)', 'Rozsáhlé ruiny Hitlerova hlavního stanu ukryté v lesích u Kętrzynu, dějiště atentátu z roku 1944. Působivá vojenská památka.', 54.0803, 21.4939, 'https://commons.wikimedia.org/wiki/Special:FilePath/Poland._K%C4%99trzyn._Gier%C5%82o%C5%BC._Wolf%27s_Lair_009.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Poland._K%C4%99trzyn._Gier%C5%82o%C5%BC._Wolf%27s_Lair_009.JPG"}'::text[], 4);

  -- Kašubské Švýcarsko
  delete from public.routes where name = 'Kašubské Švýcarsko' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kašubské Švýcarsko', 'Okruh zvlněnou krajinou Kašub jižně od Gdaňsku, mezi jezery a lesnatými kopci. Nejvyšší vrch nížinného Polska Wieżyca, převrácený dům v Szymbarku a klidné okresky dělají z regionu příjemnou vyjížďku. Nejlepší od jara do podzimu; pozor na úzké silnice mezi jezery.', 'loop', 160, 225, 'medium',
     '[{"lat": 54.3324, "lng": 18.1994, "label": "Start: Kartuzy"}, {"lat": 54.2158, "lng": 18.0308, "label": "Chmielno"}, {"lat": 54.2317, "lng": 18.1, "label": "Wieżyca"}, {"lat": 54.1247, "lng": 18.0308, "label": "Szymbark"}, {"lat": 54.1219, "lng": 17.9772, "label": "Kościerzyna"}, {"lat": 54.3324, "lng": 18.1994, "label": "Cíl: Kartuzy"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.3324,18.1994&destination=54.3324,18.1994&travelmode=driving&waypoints=54.2158,18.0308%7C54.2317,18.1%7C54.1247,18.0308%7C54.1219,17.9772', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzy_kolegiata.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzy_kolegiata.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Chmielno_Biale_Jezioro_1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Wie%C5%BCyca_(Ni%C5%BC_Polski)-wieza_widokowa.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szymbark_(Szimbark)%2C_Dom_do_g%C3%B3ry_nogami_-_fotopolska.eu_(180802).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bcierzyna_Rynek.jpg"}'::text[], '{"Kartuzy – kolegiáta","Chmielno a Bílé jezero","Wieżyca – rozhledna","Převrácený dům v Szymbarku","Kościerzyna – náměstí"}'::text[], '{"PL"}'::text[], false, 4760, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kartuzy – kolegiáta', 'Kartuziánský klášterní kostel se střechou ve tvaru rakve, symbol pomíjivosti. Centrum kašubské kultury.', 54.3324, 18.1994, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzy_kolegiata.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kartuzy_kolegiata.jpg"}'::text[], 0),
    (v_route, 'Chmielno a Bílé jezero', 'Vesnice mezi jezery proslulá keramickou dílnou Neclů. Klidné místo na koupání a odpočinek u vody.', 54.2158, 18.0308, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chmielno_Biale_Jezioro_1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Chmielno_Biale_Jezioro_1.jpg"}'::text[], 1),
    (v_route, 'Wieżyca – rozhledna', 'Nejvyšší vrchol Kašub a celé severopolské nížiny (329 m) s vyhlídkovou věží nad lesy. Pěkný rozhled po jezerní pahorkatině.', 54.2317, 18.1, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wie%C5%BCyca_(Ni%C5%BC_Polski)-wieza_widokowa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Wie%C5%BCyca_(Ni%C5%BC_Polski)-wieza_widokowa.jpg"}'::text[], 2),
    (v_route, 'Převrácený dům v Szymbarku', 'Slavný dům postavený vzhůru nohama ve skanzenu, oblíbená turistická atrakce. Zábavná zastávka pro každého.', 54.1247, 18.0308, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szymbark_(Szimbark)%2C_Dom_do_g%C3%B3ry_nogami_-_fotopolska.eu_(180802).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szymbark_(Szimbark)%2C_Dom_do_g%C3%B3ry_nogami_-_fotopolska.eu_(180802).jpg"}'::text[], 3),
    (v_route, 'Kościerzyna – náměstí', 'Kašubské městečko s pěkným náměstím a muzeem železnice. Dobré zázemí uprostřed okruhu.', 54.1219, 17.9772, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bcierzyna_Rynek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ko%C5%9Bcierzyna_Rynek.jpg"}'::text[], 4);

  -- Trójmiasto a poloostrov Hel
  delete from public.routes where name = 'Trójmiasto a poloostrov Hel' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Trójmiasto a poloostrov Hel', 'Pobřežní trasa od hanzovního Gdaňsku přes lázeňský Sopot až na špičku poloostrova Hel. Historické centrum, molo do moře a rovná silnice mezi dunami a plážemi. Nejlepší v létě; pozor na hustý provoz v sezoně a na omezení na úzkém poloostrově.', 'poi', 130, 195, 'easy',
     '[{"lat": 54.348, "lng": 18.6533, "label": "Start: Gdańsk"}, {"lat": 54.4483, "lng": 18.5697, "label": "Sopot – molo"}, {"lat": 54.5189, "lng": 18.5514, "label": "Gdynia"}, {"lat": 54.698, "lng": 18.69, "label": "Jastarnia"}, {"lat": 54.6083, "lng": 18.8036, "label": "Hel"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=54.348,18.6533&destination=54.6083,18.8036&travelmode=driving&waypoints=54.4483,18.5697%7C54.5189,18.5514%7C54.698,18.69', 'https://commons.wikimedia.org/wiki/Special:FilePath/Gda%C5%84sk%2C_D%C5%82ugi_Targ_(HB1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gda%C5%84sk%2C_D%C5%82ugi_Targ_(HB1).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sopot_Molo_and_main_square_2024_aerial.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Dar_Pomorza%2C_Gdynia%2C_20090705%2C_1.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jastarnia%2C_port_rybacki.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Latarnia_morska_hel_lighthouse_poland.JPG"}'::text[], '{"Gdańsk – Długi Targ","Sopot – molo","Gdynia – Dar Pomorza","Jastarnia – rybářský přístav","Hel – maják a fokarium"}'::text[], '{"PL"}'::text[], false, 4770, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Gdańsk – Długi Targ', 'Nádherné hanzovní centrum s Dlouhým trhem, Neptunovou fontánou a Mariánskou bránou. Jedno z nejkrásnějších měst u Baltu.', 54.3489, 18.6533, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gda%C5%84sk%2C_D%C5%82ugi_Targ_(HB1).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Gda%C5%84sk%2C_D%C5%82ugi_Targ_(HB1).jpg"}'::text[], 0),
    (v_route, 'Sopot – molo', 'Nejdelší dřevěné molo v Evropě zasahující daleko do Baltu, srdce lázeňského Sopotu. Živá promenáda a pláže.', 54.4483, 18.5697, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sopot_Molo_and_main_square_2024_aerial.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sopot_Molo_and_main_square_2024_aerial.jpg"}'::text[], 1),
    (v_route, 'Gdynia – Dar Pomorza', 'Moderní přístavní město s historickou plachetnicí Dar Pomorza kotvící na nábřeží. Přímořská atmosféra a muzea.', 54.5189, 18.5514, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dar_Pomorza%2C_Gdynia%2C_20090705%2C_1.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dar_Pomorza%2C_Gdynia%2C_20090705%2C_1.jpg"}'::text[], 2),
    (v_route, 'Jastarnia – rybářský přístav', 'Klidné letovisko uprostřed poloostrova Hel s rybářským přístavem a plážemi z obou stran. Zastávka na čerstvé ryby.', 54.698, 18.69, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jastarnia%2C_port_rybacki.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jastarnia%2C_port_rybacki.jpg"}'::text[], 3),
    (v_route, 'Hel – maják a fokarium', 'Cíp poloostrova s majákem, muzeem rybolovu a fokáriem s tuleni. Konec cesty s výhledem na moře ze všech stran.', 54.6083, 18.8036, 'https://commons.wikimedia.org/wiki/Special:FilePath/Latarnia_morska_hel_lighthouse_poland.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Latarnia_morska_hel_lighthouse_poland.JPG"}'::text[], 4);

  -- Orlí hnízda – Jura Krakowsko-Częstochowska
  delete from public.routes where name = 'Orlí hnízda – Jura Krakowsko-Częstochowska' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Orlí hnízda – Jura Krakowsko-Częstochowska', 'Trasa Orlích hnízd po vápencové Juře mezi Krakovem a Čenstochovou. Skalní hrady na bílých útesech, jeskyně a poutní Jasná Hora tvoří jednu z nejromantičtějších tras Polska. Nejlepší od jara do podzimu; pozor na turisty u hradů a úzké silnice mezi skalami.', 'loop', 170, 240, 'medium',
     '[{"lat": 50.8118, "lng": 19.1203, "label": "Start: Częstochowa"}, {"lat": 50.672, "lng": 19.4472, "label": "Olsztyn"}, {"lat": 50.612, "lng": 19.5344, "label": "Mirów"}, {"lat": 50.6089, "lng": 19.5464, "label": "Bobolice"}, {"lat": 50.4517, "lng": 19.5525, "label": "Ogrodzieniec"}, {"lat": 50.8118, "lng": 19.1203, "label": "Cíl: Częstochowa"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.8118,19.1203&destination=50.8118,19.1203&travelmode=driving&waypoints=50.672,19.4472%7C50.612,19.5344%7C50.6089,19.5464%7C50.4517,19.5525', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cz%C4%99stochowa_-_Aleja_Naj%C5%9Bwi%C4%99tszej_Maryi_Panny.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cz%C4%99stochowa_-_Aleja_Naj%C5%9Bwi%C4%99tszej_Maryi_Panny.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Olsztynie_po%C5%82o%C5%BCony_w_wojew%C3%B3dztwie_%C5%9Bl%C4%85skim%2C_w_powiecie_cz%C4%99stochowskim%2C_w_gminie_Olsztyn._08.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Mirowie-Castle_in_Mirow_-_panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bobolice_Castle_at_sunset.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Ogrodzieniec_w_Podzamczu.jpg"}'::text[], '{"Jasná Hora v Čenstochové","Hrad Olsztyn","Hrad Mirów","Hrad Bobolice","Hrad Ogrodzieniec"}'::text[], '{"PL"}'::text[], false, 4780, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Jasná Hora v Čenstochové', 'Nejvýznamnější polské poutní místo s obrazem Černé Madony a mohutným klášterem. Duchovní srdce Polska.', 50.8125, 19.0967, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cz%C4%99stochowa_-_Aleja_Naj%C5%9Bwi%C4%99tszej_Maryi_Panny.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cz%C4%99stochowa_-_Aleja_Naj%C5%9Bwi%C4%99tszej_Maryi_Panny.JPG"}'::text[], 0),
    (v_route, 'Hrad Olsztyn', 'Malebná zřícenina královského hradu na vápencových skalách nedaleko Čenstochové. První z Orlích hnízd na trase.', 50.672, 19.4472, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Olsztynie_po%C5%82o%C5%BCony_w_wojew%C3%B3dztwie_%C5%9Bl%C4%85skim%2C_w_powiecie_cz%C4%99stochowskim%2C_w_gminie_Olsztyn._08.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Olsztynie_po%C5%82o%C5%BCony_w_wojew%C3%B3dztwie_%C5%9Bl%C4%85skim%2C_w_powiecie_cz%C4%99stochowskim%2C_w_gminie_Olsztyn._08.JPG"}'::text[], 1),
    (v_route, 'Hrad Mirów', 'Romantická zřícenina na skalním hřebeni spojená legendou se sousedními Bobolicemi. Oblíbený fotomotiv Jury.', 50.612, 19.5344, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Mirowie-Castle_in_Mirow_-_panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_w_Mirowie-Castle_in_Mirow_-_panoramio.jpg"}'::text[], 2),
    (v_route, 'Hrad Bobolice', 'Krásně obnovený skalní hrad, jeden z nejfotogeničtějších v Polsku, obzvlášť za soumraku. Přístupný interiér i hradby.', 50.6089, 19.5464, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bobolice_Castle_at_sunset.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bobolice_Castle_at_sunset.jpg"}'::text[], 3),
    (v_route, 'Hrad Ogrodzieniec', 'Největší a nejpůsobivější zřícenina Jury na Podzámčí, kulisa mnoha filmů. Rozlehlý areál na bílých skalách.', 50.4517, 19.5525, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Ogrodzieniec_w_Podzamczu.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamek_Ogrodzieniec_w_Podzamczu.jpg"}'::text[], 4);

  -- Svatokřížské hory
  delete from public.routes where name = 'Svatokřížské hory' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Svatokřížské hory', 'Okruh nejstaršími horami Polska ve Svatokřížském kraji. Klášter na Svatém Kříži, jeskyně Raj a královský hrad v Chęcinach střídají lesní hřebeny Svatokřížského pralesa. Nejlepší od jara do podzimu; pozor na lesní úseky a turistický ruch u památek.', 'loop', 165, 225, 'medium',
     '[{"lat": 50.8661, "lng": 20.6286, "label": "Start: Kielce"}, {"lat": 50.7975, "lng": 20.4667, "label": "Chęciny"}, {"lat": 50.8203, "lng": 20.43, "label": "Jeskyně Raj"}, {"lat": 50.86, "lng": 21.05, "label": "Svatý Kříž"}, {"lat": 50.8661, "lng": 20.6286, "label": "Cíl: Kielce"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.8661,20.6286&destination=50.8661,20.6286&travelmode=driving&waypoints=50.7975,20.4667%7C50.8203,20.43%7C50.86,21.05', 'https://commons.wikimedia.org/wiki/Special:FilePath/20130421_Kielce_Palac_Biskupow_Krakowskich_3127.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/20130421_Kielce_Palac_Biskupow_Krakowskich_3127.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C4%99ciny_Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Jaskinia_Raj.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Swiety_Krzyz_klasztor_3963_20080703.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Kadzielnia_w_Kielcach.jpg"}'::text[], '{"Kielce – Biskupský palác","Hrad Chęciny","Jeskyně Raj","Klášter na Svatém Kříži","Kadzielnia"}'::text[], '{"PL"}'::text[], false, 4790, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kielce – Biskupský palác', 'Renesanční biskupský palác s dochovanými interiéry, dominanta krajského města. Dobrá výchozí zastávka.', 50.8611, 20.6286, 'https://commons.wikimedia.org/wiki/Special:FilePath/20130421_Kielce_Palac_Biskupow_Krakowskich_3127.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/20130421_Kielce_Palac_Biskupow_Krakowskich_3127.jpg"}'::text[], 0),
    (v_route, 'Hrad Chęciny', 'Malebná zřícenina královského hradu na vápencovém hřebeni s vyhlídkovou věží. Daleký rozhled po Svatokřížsku.', 50.7975, 20.4667, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C4%99ciny_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C4%99ciny_Castle.jpg"}'::text[], 1),
    (v_route, 'Jeskyně Raj', 'Nádherná krápníková jeskyně s bohatou výzdobou, jedna z nejkrásnějších v Polsku. Příjemné osvěžení za horka.', 50.8203, 20.43, 'https://commons.wikimedia.org/wiki/Special:FilePath/Jaskinia_Raj.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Jaskinia_Raj.jpg"}'::text[], 2),
    (v_route, 'Klášter na Svatém Kříži', 'Benediktinský klášter na druhém nejvyšším vrcholu Svatokřížských hor, nejstarší poutní místo Polska. Symbolický vrchol trasy.', 50.86, 21.05, 'https://commons.wikimedia.org/wiki/Special:FilePath/Swiety_Krzyz_klasztor_3963_20080703.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Swiety_Krzyz_klasztor_3963_20080703.jpg"}'::text[], 3),
    (v_route, 'Kadzielnia', 'Bývalý vápencový lom v Kielcích proměněný v přírodní rezervaci s jezírkem a amfiteátrem. Klidná zastávka na okraji města.', 50.8564, 20.625, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kadzielnia_w_Kielcach.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kadzielnia_w_Kielcach.jpg"}'::text[], 4);

  -- Roztocze a renesanční Zamość
  delete from public.routes where name = 'Roztocze a renesanční Zamość' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Roztocze a renesanční Zamość', 'Klidná trasa jihovýchodním pomezím Polska přes zvlněné Roztocze. Ideální renesanční město Zamość, národní park a poutní Krasnobród nabízí pohodovou jízdu prázdnými silnicemi. Nejlepší od jara do podzimu; pozor na zemědělskou techniku a řidší zázemí.', 'loop', 180, 240, 'easy',
     '[{"lat": 50.7231, "lng": 23.2519, "label": "Start: Zamość"}, {"lat": 50.5461, "lng": 23.2158, "label": "Krasnobród"}, {"lat": 50.6167, "lng": 22.9767, "label": "Zwierzyniec"}, {"lat": 50.6903, "lng": 22.9789, "label": "Szczebrzeszyn"}, {"lat": 50.7231, "lng": 23.2519, "label": "Cíl: Zamość"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=50.7231,23.2519&destination=50.7231,23.2519&travelmode=driving&waypoints=50.5461,23.2158%7C50.6167,22.9767%7C50.6903,22.9789', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamo%C5%9B%C4%87_Rynek_Wielki.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamo%C5%9B%C4%87_Rynek_Wielki.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Krasnobr%C3%B3d.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Roztocza%C5%84ski_Park_Narodowy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szczebrzeszyn.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Zwierzyniec_ko%C5%9Bci%C3%B3%C5%82_na_wodzie.jpg"}'::text[], '{"Zamość – Velké náměstí","Krasnobród","Národní park Roztocze","Szczebrzeszyn","Zwierzyniec"}'::text[], '{"PL"}'::text[], false, 4800, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Zamość – Velké náměstí', 'Dokonale zachovalé renesanční město zapsané na seznam UNESCO, zvané Padova severu. Arkádové náměstí a radnice patří k nejkrásnějším v Polsku.', 50.7203, 23.2519, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zamo%C5%9B%C4%87_Rynek_Wielki.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zamo%C5%9B%C4%87_Rynek_Wielki.jpg"}'::text[], 0),
    (v_route, 'Krasnobród', 'Půvabné poutní městečko a klimatické lázně v srdci Roztoczí s barokním klášterem. Klidná zastávka mezi lesy.', 50.5461, 23.2158, 'https://commons.wikimedia.org/wiki/Special:FilePath/Krasnobr%C3%B3d.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Krasnobr%C3%B3d.jpg"}'::text[], 1),
    (v_route, 'Národní park Roztocze', 'Chráněná zvlněná krajina bukových lesů, pramenů a divokých koníků. Klid a příroda daleko od ruchu.', 50.6, 23.05, 'https://commons.wikimedia.org/wiki/Special:FilePath/Roztocza%C5%84ski_Park_Narodowy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Roztocza%C5%84ski_Park_Narodowy.jpg"}'::text[], 2),
    (v_route, 'Szczebrzeszyn', 'Městečko proslavené jazykolamem o chrobákovi, s pomníkem brouka a synagogou. Úsměvná i historická zastávka.', 50.6903, 22.9789, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szczebrzeszyn.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szczebrzeszyn.jpg"}'::text[], 3),
    (v_route, 'Zwierzyniec', 'Brána Roztočského národního parku s kostelem na vodě uprostřed rybníka. Malebné místo na oddech.', 50.6167, 22.9767, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zwierzyniec_ko%C5%9Bci%C3%B3%C5%82_na_wodzie.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Zwierzyniec_ko%C5%9Bci%C3%B3%C5%82_na_wodzie.jpg"}'::text[], 4);

end $$;
