-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — MAĎARSKO (9 tras)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Severní břeh Balatonu
  delete from public.routes where name = 'Severní břeh Balatonu' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Severní břeh Balatonu', 'Pohodová vyjížďka podél severního břehu největšího jezera střední Evropy. Poloostrov Tihany s opatstvím, sopečné kopce Badacsony s vinicemi a zámek Keszthely spojují klid u vody s výbornou gastronomií. Nejlepší od května do září; pozor na turistický provoz v letoviscích a horko.', 'loop', 170, 225, 'easy',
     '[{"lat": 46.9333, "lng": 17.8892, "label": "Start: Balatonfüred"}, {"lat": 46.9139, "lng": 17.8931, "label": "Tihany"}, {"lat": 46.7969, "lng": 17.5064, "label": "Badacsony"}, {"lat": 46.7667, "lng": 17.2439, "label": "Keszthely"}, {"lat": 46.9333, "lng": 17.8892, "label": "Cíl: Balatonfüred"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.9333,17.8892&destination=46.9333,17.8892&travelmode=driving&waypoints=46.9139,17.8931%7C46.7969,17.5064%7C46.7667,17.2439', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tihany_Abbey.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tihany_Abbey.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Balatonf%C3%BCred.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Badacsony.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Festetics_Palace_Keszthely.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szigliget.jpg"}'::text[], '{"Opatství Tihany","Balatonfüred","Badacsony","Zámek Festetics v Keszthely","Szigliget"}'::text[], '{"HU"}'::text[], false, 4210, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Opatství Tihany', 'Benediktinské opatství s dvěma věžemi na poloostrově vysoko nad Balatonem, ikona jezera. Nádherný výhled a levandulová pole v okolí.', 46.9139, 17.8892, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tihany_Abbey.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tihany_Abbey.jpg"}'::text[], 0),
    (v_route, 'Balatonfüred', 'Nejstarší lázeňské město u Balatonu s krásnou promenádou a přístavem. Příjemná zastávka na kávu u vody.', 46.9333, 17.8892, 'https://commons.wikimedia.org/wiki/Special:FilePath/Balatonf%C3%BCred.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Balatonf%C3%BCred.jpg"}'::text[], 1),
    (v_route, 'Badacsony', 'Sopečný kopec nad jezerem pokrytý vinicemi, ráj milovníků vína s výhledy do kraje. Zastávka na sklenku a panorama.', 46.7969, 17.5064, 'https://commons.wikimedia.org/wiki/Special:FilePath/Badacsony.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Badacsony.jpg"}'::text[], 2),
    (v_route, 'Zámek Festetics v Keszthely', 'Skvostný barokní zámek s rozlehlým parkem a knihovnou na západním konci Balatonu. Jeden z nejkrásnějších v Maďarsku.', 46.7667, 17.2439, 'https://commons.wikimedia.org/wiki/Special:FilePath/Festetics_Palace_Keszthely.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Festetics_Palace_Keszthely.jpg"}'::text[], 3),
    (v_route, 'Szigliget', 'Vinařská vesnička pod zříceninou hradu s výhledem na Balaton. Malebné místo mezi vinicemi a rákosím.', 46.7947, 17.4342, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szigliget.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szigliget.jpg"}'::text[], 4);

  -- Dunajský ohyb
  delete from public.routes where name = 'Dunajský ohyb' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Dunajský ohyb', 'Romantická trasa údolím, kde se Dunaj prudce stáčí na jih. Královský Visegrád, bazilika v Ostřihomi a umělecký Szentendre nabízí historii a výhledy nad širokou řekou. Nejlepší od jara do podzimu; pozor na turisty a úzké nábřežní silnice.', 'poi', 120, 180, 'easy',
     '[{"lat": 47.6689, "lng": 19.0764, "label": "Start: Szentendre"}, {"lat": 47.7833, "lng": 18.9764, "label": "Visegrád"}, {"lat": 47.7936, "lng": 18.7404, "label": "Ostřihom – bazilika"}, {"lat": 47.7767, "lng": 19.1339, "label": "Vác"}, {"lat": 47.7833, "lng": 18.9764, "label": "Cíl: Visegrád"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.6689,19.0764&destination=47.7833,18.9764&travelmode=driving&waypoints=47.7833,18.9764%7C47.7936,18.7404%7C47.7767,19.1339', 'https://commons.wikimedia.org/wiki/Special:FilePath/Szentendre.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szentendre.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Visegr%C3%A1d_v%C3%A1r.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Esztergom_Basilica.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A9dik%C3%A1l%C3%B3sz%C3%A9k.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A1c.jpg"}'::text[], '{"Szentendre","Hrad Visegrád","Bazilika v Ostřihomi","Vyhlídka Prédikálószék","Vác"}'::text[], '{"HU"}'::text[], false, 4220, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Szentendre', 'Barevné umělecké městečko nad Dunajem s galeriemi, srbským kostelem a kavárnami. Živá zastávka plná atmosféry.', 47.6689, 19.0764, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szentendre.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szentendre.jpg"}'::text[], 0),
    (v_route, 'Hrad Visegrád', 'Královský hrad na kopci nad ohbím Dunaje s dechberoucím výhledem na řeku. Symbol středověké maďarské moci.', 47.7833, 18.9764, 'https://commons.wikimedia.org/wiki/Special:FilePath/Visegr%C3%A1d_v%C3%A1r.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Visegr%C3%A1d_v%C3%A1r.jpg"}'::text[], 1),
    (v_route, 'Bazilika v Ostřihomi', 'Největší kostel v Maďarsku na skále nad Dunajem, sídlo primase. Monumentální kupole viditelná zdaleka i ze Slovenska.', 47.7936, 18.7404, 'https://commons.wikimedia.org/wiki/Special:FilePath/Esztergom_Basilica.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Esztergom_Basilica.jpg"}'::text[], 2),
    (v_route, 'Vyhlídka Prédikálószék', 'Skalní vyhlídka nad Dunajem s pohledem na celý ohyb řeky. Odměna za odbočku do kopců Vyšehradu.', 47.8064, 18.95, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A9dik%C3%A1l%C3%B3sz%C3%A9k.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pr%C3%A9dik%C3%A1l%C3%B3sz%C3%A9k.jpg"}'::text[], 3),
    (v_route, 'Vác', 'Barokní městečko na protějším břehu s triumfálním obloukem a náměstím. Klidná zastávka mimo turistický proud.', 47.7767, 19.1339, 'https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A1c.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/V%C3%A1c.jpg"}'::text[], 4);

  -- Mátra, Bükk a barokní Eger
  delete from public.routes where name = 'Mátra, Bükk a barokní Eger' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mátra, Bükk a barokní Eger', 'Okruh nejvyššími pohořími Maďarska mezi vinařským Egerem a horou Kékestető. Zvlněné lesní silnice, Údolí krásných paní s vinnými sklípky a lesy Bükku spojují jízdu s vínem a přírodou. Nejlepší od jara do podzimu; pozor na lesní úseky a horský provoz.', 'loop', 190, 255, 'medium',
     '[{"lat": 47.9025, "lng": 20.3772, "label": "Start: Eger"}, {"lat": 47.8697, "lng": 20.0136, "label": "Kékestető"}, {"lat": 48.1017, "lng": 20.4394, "label": "Bükk – Szilvásvárad"}, {"lat": 47.9025, "lng": 20.3772, "label": "Cíl: Eger"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.9025,20.3772&destination=47.9025,20.3772&travelmode=driving&waypoints=47.8697,20.0136%7C48.1017,20.4394', 'https://commons.wikimedia.org/wiki/Special:FilePath/Eger_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eger_Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sz%C3%A9passzonyv%C3%B6lgy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%A9kestet%C5%91.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szilv%C3%A1sv%C3%A1rad.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lillaf%C3%BCred.jpg"}'::text[], '{"Hrad Eger","Údolí krásných paní","Kékestető","Szilvásvárad","Lillafüred"}'::text[], '{"HU"}'::text[], false, 4230, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Hrad Eger', 'Slavný hrad, který roku 1552 odolal tureckému obležení, nad barokním městem s minaretem. Symbol maďarské statečnosti.', 47.9053, 20.3767, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eger_Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eger_Castle.jpg"}'::text[], 0),
    (v_route, 'Údolí krásných paní', 'Proslulé údolí vinných sklípků u Egeru, kolébka Egerské býčí krve. Klasická zastávka na vinařskou atmosféru.', 47.8908, 20.3644, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sz%C3%A9passzonyv%C3%B6lgy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sz%C3%A9passzonyv%C3%B6lgy.jpg"}'::text[], 1),
    (v_route, 'Kékestető', 'Nejvyšší bod Maďarska (1014 m) v pohoří Mátra s televizní věží a vyhlídkou. Cíl oblíbeného horského výjezdu.', 47.8697, 20.0136, 'https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%A9kestet%C5%91.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%A9kestet%C5%91.jpg"}'::text[], 2),
    (v_route, 'Szilvásvárad', 'Malebná obec v Bükku proslulá chovem lipicánů a soutěskou Szalajka s vodopádem. Klidné místo v horách.', 48.1017, 20.4394, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szilv%C3%A1sv%C3%A1rad.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szilv%C3%A1sv%C3%A1rad.jpg"}'::text[], 3),
    (v_route, 'Lillafüred', 'Půvabné horské letovisko s pohádkovým hotelem, vodopádem a krápníkovou jeskyní. Osvěžující zastávka v přírodě.', 48.09, 20.6247, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lillaf%C3%BCred.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lillaf%C3%BCred.jpg"}'::text[], 4);

  -- Tokajská vinařská cesta
  delete from public.routes where name = 'Tokajská vinařská cesta' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Tokajská vinařská cesta', 'Klidná trasa proslulým vinařským regionem Tokaj na severovýchodě Maďarska. Vinice na sopečných svazích, historické sklepy a soutok řek dělají z okruhu pohodovou gastronomickou vyjížďku. Nejlepší od jara do podzimu; pozor na zemědělskou techniku a řidší zázemí.', 'loop', 150, 210, 'easy',
     '[{"lat": 48.1178, "lng": 21.4092, "label": "Start: Tokaj"}, {"lat": 48.3245, "lng": 21.5657, "label": "Sárospatak"}, {"lat": 48.3968, "lng": 21.6389, "label": "Sátoraljaújhely"}, {"lat": 48.1178, "lng": 21.4092, "label": "Cíl: Tokaj"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.1178,21.4092&destination=48.1178,21.4092&travelmode=driving&waypoints=48.3245,21.5657%7C48.3968,21.6389', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tokaj.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tokaj.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A1rospatak_v%C3%A1r.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tokaj-hegy.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A1toralja%C3%BAjhely.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hercegk%C3%BAt_Gombos-hegyi_pincesor.jpg"}'::text[], '{"Tokaj","Hrad Sárospatak","Tokajský kopec","Sátoraljaújhely","Vinné sklepy Hercegkút"}'::text[], '{"HU"}'::text[], false, 4240, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Tokaj', 'Historické vinařské městečko u soutoku Tisy a Bodrogu, kolébka slavného sladkého vína. Vinné sklepy a pěkné náměstí.', 48.1178, 21.4092, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tokaj.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tokaj.jpg"}'::text[], 0),
    (v_route, 'Hrad Sárospatak', 'Renesanční hrad Rákócziů na břehu Bodrogu, jeden z nejvýznamnějších v Maďarsku. Krásné nádvoří a expozice.', 48.3245, 21.5657, 'https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A1rospatak_v%C3%A1r.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A1rospatak_v%C3%A1r.jpg"}'::text[], 1),
    (v_route, 'Tokajský kopec', 'Sopečný vrch nad městem pokrytý vinicemi s výhledem na soutok řek. Odkud pochází ono terroir světoznámého vína.', 48.1256, 21.44, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tokaj-hegy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tokaj-hegy.jpg"}'::text[], 2),
    (v_route, 'Sátoraljaújhely', 'Městečko na slovenské hranici s nejdelší bobovou dráhou a lanovkou v zemi. Rozhledy do Zemplínu.', 48.3968, 21.6389, 'https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A1toralja%C3%BAjhely.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/S%C3%A1toralja%C3%BAjhely.jpg"}'::text[], 3),
    (v_route, 'Vinné sklepy Hercegkút', 'UNESCO chráněné patrové vinné sklepy vytesané do sopečného tufu. Ojedinělá památka tokajského vinařství.', 48.3358, 21.5511, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hercegk%C3%BAt_Gombos-hegyi_pincesor.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hercegk%C3%BAt_Gombos-hegyi_pincesor.jpg"}'::text[], 4);

  -- Villány, Pécs a Mecsek
  delete from public.routes where name = 'Villány, Pécs a Mecsek' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Villány, Pécs a Mecsek', 'Vyjížďka jihem Maďarska přes vinařský Villány a pohoří Mecsek. Historický Pécs s křesťanskými památkami UNESCO, vinné sklepy a lesní silnice nabízí kulturu i pohodovou jízdu. Nejlepší od jara do podzimu; pozor na provoz v Pécsi a horko.', 'loop', 160, 225, 'medium',
     '[{"lat": 46.0727, "lng": 18.2323, "label": "Start: Pécs"}, {"lat": 45.8688, "lng": 18.4547, "label": "Villány"}, {"lat": 45.8547, "lng": 18.2989, "label": "Siklós"}, {"lat": 46.0727, "lng": 18.2323, "label": "Cíl: Pécs"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.0727,18.2323&destination=46.0727,18.2323&travelmode=driving&waypoints=45.8688,18.4547%7C45.8547,18.2989', 'https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%A9cs_Cathedral.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%A9cs_Cathedral.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vill%C3%A1ny.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sikl%C3%B3s_v%C3%A1r.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hark%C3%A1ny.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mecsek.jpg"}'::text[], '{"Pécs – katedrála a nekropole","Villány","Hrad Siklós","Harkány","Mecsek – Zsongorkő"}'::text[], '{"HU"}'::text[], false, 4250, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Pécs – katedrála a nekropole', 'Živé jihomaďarské město s katedrálou, mešitou z tureckých dob a UNESCO starokřesťanskou nekropolí. Kulturní perla regionu.', 46.0763, 18.228, 'https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%A9cs_Cathedral.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%A9cs_Cathedral.jpg"}'::text[], 0),
    (v_route, 'Villány', 'Nejslavnější červené vinařství Maďarska s dlouhou uličkou sklípků. Zastávka pro milovníky vína a gastronomie.', 45.8688, 18.4547, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vill%C3%A1ny.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vill%C3%A1ny.jpg"}'::text[], 1),
    (v_route, 'Hrad Siklós', 'Dobře zachovalý středověký hrad na jihu země s výhledem na vinice. Působivé hradby a nádvoří.', 45.8547, 18.2989, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sikl%C3%B3s_v%C3%A1r.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sikl%C3%B3s_v%C3%A1r.jpg"}'::text[], 2),
    (v_route, 'Harkány', 'Termální lázně proslulé léčivou sirnou vodou nedaleko chorvatské hranice. Zastávka na odpočinek.', 45.8514, 18.2333, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hark%C3%A1ny.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hark%C3%A1ny.jpg"}'::text[], 3),
    (v_route, 'Mecsek – Zsongorkő', 'Skalní vyhlídka v lesích Mecseku nad Pécsí s výhledem na pahorkatinu. Odbočka pro milovníky přírody.', 46.1157, 18.1657, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mecsek.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mecsek.jpg"}'::text[], 4);

  -- Őrség a zelené pomezí
  delete from public.routes where name = 'Őrség a zelené pomezí' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Őrség a zelené pomezí', 'Klidná trasa nejzápadnějším cípem Maďarska při rakousko-slovinské hranici. Roztroušené vesničky s hrnčířskou tradicí, lesy a kostely dělají z Őrségu poklidný kout mimo turistický ruch. Nejlepší od jara do podzimu; pozor na úzké silnice a řidší zázemí.', 'loop', 145, 210, 'easy',
     '[{"lat": 46.9068, "lng": 16.355, "label": "Start: Őriszentpéter"}, {"lat": 46.9425, "lng": 16.4864, "label": "Szalafő"}, {"lat": 46.8618, "lng": 16.3106, "label": "Magyarszombatfa"}, {"lat": 46.9068, "lng": 16.355, "label": "Cíl: Őriszentpéter"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=46.9068,16.355&destination=46.9068,16.355&travelmode=driving&waypoints=46.9425,16.4864%7C46.8618,16.3106', 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%90riszentp%C3%A9ter.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%90riszentp%C3%A9ter.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szalaf%C5%91_Pityerszer.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Velem%C3%A9r.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vad%C3%A1sa-t%C3%B3.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Magyarszombatfa.jpg"}'::text[], '{"Őriszentpéter","Szalafő – skanzen","Velemér – kostel","Jezero Vadása","Magyarszombatfa – hrnčířství"}'::text[], '{"HU"}'::text[], false, 4260, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Őriszentpéter', 'Hlavní obec Őrségu s románským kostelem a hrnčířskou tradicí. Klidné centrum zeleného kraje.', 46.9068, 16.355, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%90riszentp%C3%A9ter.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/%C5%90riszentp%C3%A9ter.jpg"}'::text[], 0),
    (v_route, 'Szalafő – skanzen', 'Nejzápadnější obec Maďarska s dochovanými roubenými dvorci pod doškovými střechami. Živoucí ukázka venkovské minulosti.', 46.9425, 16.4864, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szalaf%C5%91_Pityerszer.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szalaf%C5%91_Pityerszer.jpg"}'::text[], 1),
    (v_route, 'Velemér – kostel', 'Gotický kostel s unikátními středověkými freskami mistra Jánose Aquily. Skvost skrytý v pohraničí.', 46.8264, 16.3123, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velem%C3%A9r.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Velem%C3%A9r.jpg"}'::text[], 2),
    (v_route, 'Jezero Vadása', 'Malé rekreační jezero uprostřed lesů Őrségu, oáza klidu. Zastávka na odpočinek u vody.', 46.9564, 16.5065, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vad%C3%A1sa-t%C3%B3.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vad%C3%A1sa-t%C3%B3.jpg"}'::text[], 3),
    (v_route, 'Magyarszombatfa – hrnčířství', 'Vesnice proslulá hrnčířskou a keramickou tradicí u slovinské hranice. Zastávka na místní řemeslo.', 46.8618, 16.3106, 'https://commons.wikimedia.org/wiki/Special:FilePath/Magyarszombatfa.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Magyarszombatfa.jpg"}'::text[], 4);

  -- Puszta a Hortobágy
  delete from public.routes where name = 'Puszta a Hortobágy' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Puszta a Hortobágy', 'Trasa nekonečnou rovinou Velké uherské nížiny, prvního maďarského národního parku UNESCO. Devítiobloukový most, stáda šedého skotu a pastevecká kultura pusty nabízí zážitek jinde nevídaný. Nejlepší od jara do podzimu; pozor na horko, vítr a řidší zázemí.', 'poi', 170, 225, 'easy',
     '[{"lat": 47.5316, "lng": 21.6273, "label": "Start: Debrecín"}, {"lat": 47.5822, "lng": 21.1508, "label": "Hortobágy"}, {"lat": 47.6167, "lng": 20.9564, "label": "Tiszacsege"}, {"lat": 47.5316, "lng": 21.6273, "label": "Cíl: Debrecín"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.5316,21.6273&destination=47.5316,21.6273&travelmode=driving&waypoints=47.5822,21.1508%7C47.6167,20.9564', 'https://commons.wikimedia.org/wiki/Special:FilePath/Debrecen_Great_Church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Debrecen_Great_Church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hortob%C3%A1gy_Nine-holed_Bridge.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hortob%C3%A1gy_cs%C3%A1rda.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Tiszacsege.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mata_Hortobagy.jpg"}'::text[], '{"Debrecín – Velký kostel","Hortobágy – Devítiobloukový most","Pastevecké muzeum Hortobágy","Tiszacsege – břeh Tisy","Máta – hřebčín"}'::text[], '{"HU"}'::text[], false, 4270, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Debrecín – Velký kostel', 'Kalvínský chrám a náměstí druhého největšího města Maďarska, srdce protestantské kultury. Výchozí bod do pusty.', 47.5316, 21.6273, 'https://commons.wikimedia.org/wiki/Special:FilePath/Debrecen_Great_Church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Debrecen_Great_Church.jpg"}'::text[], 0),
    (v_route, 'Hortobágy – Devítiobloukový most', 'Nejdelší kamenný silniční most staré Evropy uprostřed nekonečné pusty. Symbol národního parku.', 47.5822, 21.1508, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hortob%C3%A1gy_Nine-holed_Bridge.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hortob%C3%A1gy_Nine-holed_Bridge.jpg"}'::text[], 1),
    (v_route, 'Pastevecké muzeum Hortobágy', 'Muzeum tradiční pastevecké kultury s ukázkou života na pustě a stády šedého skotu. Autentický zážitek nížiny.', 47.5836, 21.1533, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hortob%C3%A1gy_cs%C3%A1rda.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hortob%C3%A1gy_cs%C3%A1rda.jpg"}'::text[], 2),
    (v_route, 'Tiszacsege – břeh Tisy', 'Klidná obec na břehu líné řeky Tisy s termálním koupalištěm. Zastávka na osvěžení uprostřed roviny.', 47.6167, 20.9564, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tiszacsege.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Tiszacsege.jpg"}'::text[], 3),
    (v_route, 'Máta – hřebčín', 'Proslulý hřebčín u Hortobágye s ukázkami jízdy pastevců csikósů. Živá tradice maďarského jezdectví.', 47.5936, 21.1236, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mata_Hortobagy.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mata_Hortobagy.jpg"}'::text[], 4);

  -- Sopron a Fertő
  delete from public.routes where name = 'Sopron a Fertő' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Sopron a Fertő', 'Vyjížďka nejzápadnějším koutem Maďarska u rakouské hranice kolem jezera Fertő. Historický Sopron, zámek Eszterháza a stepní jezero UNESCO nabízí kulturu i klid. Nejlepší od jara do podzimu; pozor na provoz v Sopronu.', 'loop', 130, 195, 'easy',
     '[{"lat": 47.6817, "lng": 16.5845, "label": "Start: Sopron"}, {"lat": 47.7208, "lng": 16.6564, "label": "Fertőrákos"}, {"lat": 47.6208, "lng": 16.8683, "label": "Fertőd – Eszterháza"}, {"lat": 47.6817, "lng": 16.5845, "label": "Cíl: Sopron"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=47.6817,16.5845&destination=47.6817,16.5845&travelmode=driving&waypoints=47.7208,16.6564%7C47.6208,16.8683', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sopron_Firewatch_Tower.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sopron_Firewatch_Tower.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Eszterh%C3%A1za.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fert%C5%91r%C3%A1kosi_k%C5%91fejt%C5%91.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Fert%C5%91_t%C3%B3.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nagycenk_Sz%C3%A9chenyi_kast%C3%A9ly.jpg"}'::text[], '{"Sopron – Ohnivá věž","Zámek Eszterháza","Fertőrákos – lom","Jezero Fertő","Nagycenk – Széchenyiho zámek"}'::text[], '{"HU"}'::text[], false, 4280, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Sopron – Ohnivá věž', 'Půvabné historické město u rakouské hranice s Ohnivou věží a středověkým jádrem. Klenot západního Maďarska.', 47.6853, 16.59, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sopron_Firewatch_Tower.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sopron_Firewatch_Tower.jpg"}'::text[], 0),
    (v_route, 'Zámek Eszterháza', 'Skvostný barokní zámek zvaný maďarské Versailles, kde působil skladatel Haydn. Nádherné sály a zahrady.', 47.6208, 16.8683, 'https://commons.wikimedia.org/wiki/Special:FilePath/Eszterh%C3%A1za.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Eszterh%C3%A1za.jpg"}'::text[], 1),
    (v_route, 'Fertőrákos – lom', 'Impozantní bývalý kamenolom s podzemními sály sloužícími jako koncertní scéna. Ojedinělá kulisa u jezera.', 47.7208, 16.6564, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fert%C5%91r%C3%A1kosi_k%C5%91fejt%C5%91.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fert%C5%91r%C3%A1kosi_k%C5%91fejt%C5%91.jpg"}'::text[], 2),
    (v_route, 'Jezero Fertő', 'Rozlehlé stepní jezero na hranici s Rakouskem, biosférická rezervace UNESCO plná ptactva. Klid a rákosí.', 47.6833, 16.75, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fert%C5%91_t%C3%B3.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Fert%C5%91_t%C3%B3.jpg"}'::text[], 3),
    (v_route, 'Nagycenk – Széchenyiho zámek', 'Klasicistní zámek rodu Széchenyiů s alejí lip a muzeem parních lokomotiv. Zastávka pro milovníky historie.', 47.6603, 16.69, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nagycenk_Sz%C3%A9chenyi_kast%C3%A9ly.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nagycenk_Sz%C3%A9chenyi_kast%C3%A9ly.jpg"}'::text[], 4);

  -- Aggtelek a jeskyně Baradla
  delete from public.routes where name = 'Aggtelek a jeskyně Baradla' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Aggtelek a jeskyně Baradla', 'Okruh severovýchodním pohraničím ke krasovým jeskyním Aggteleku, UNESCO památce sdílené se Slovenskem. Podzemní chodby Baradly, kopce a hrad Boldogkő nabízí přírodu i historii. Nejlepší od jara do podzimu; pozor na lesní úseky a chladno v jeskyních.', 'loop', 150, 210, 'medium',
     '[{"lat": 48.4685, "lng": 20.4906, "label": "Start: Aggtelek"}, {"lat": 48.4681, "lng": 20.5556, "label": "Jósvafő"}, {"lat": 48.332, "lng": 21.2247, "label": "Boldogkőváralja"}, {"lat": 48.4685, "lng": 20.4906, "label": "Cíl: Aggtelek"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=48.4685,20.4906&destination=48.4685,20.4906&travelmode=driving&waypoints=48.4681,20.5556%7C48.332,21.2247', 'https://commons.wikimedia.org/wiki/Special:FilePath/Baradla-barlang.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Baradla-barlang.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/J%C3%B3svaf%C5%91.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Boldogk%C5%91_v%C3%A1ra.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Rudab%C3%A1nya.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Szalonna_templom.jpg"}'::text[], '{"Jeskyně Baradla","Jósvafő","Hrad Boldogkő","Rudabánya","Szalonna – kostel"}'::text[], '{"HU"}'::text[], false, 4290, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Jeskyně Baradla', 'Nejdelší krápníková jeskyně střední Evropy se sály jako katedrály, UNESCO památka. Podzemní zážitek na hranici se Slovenskem.', 48.4685, 20.4906, 'https://commons.wikimedia.org/wiki/Special:FilePath/Baradla-barlang.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Baradla-barlang.jpg"}'::text[], 0),
    (v_route, 'Jósvafő', 'Malebná krasová vesnička u druhého vchodu do Baradly, obklopená lesy Aggteleku. Klidná zastávka v přírodě.', 48.4681, 20.5556, 'https://commons.wikimedia.org/wiki/Special:FilePath/J%C3%B3svaf%C5%91.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/J%C3%B3svaf%C5%91.jpg"}'::text[], 1),
    (v_route, 'Hrad Boldogkő', 'Malebný hrad na čedičové skále nad vinicemi Zemplínu s dalekým výhledem. Romantická zastávka na jihu okruhu.', 48.332, 21.2247, 'https://commons.wikimedia.org/wiki/Special:FilePath/Boldogk%C5%91_v%C3%A1ra.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Boldogk%C5%91_v%C3%A1ra.jpg"}'::text[], 2),
    (v_route, 'Rudabánya', 'Bývalé hornické městečko s muzeem a nálezem pravěkého lidoopa Rudapithecus. Zastávka pro zvídavé.', 48.3833, 20.6389, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rudab%C3%A1nya.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Rudab%C3%A1nya.jpg"}'::text[], 3),
    (v_route, 'Szalonna – kostel', 'Vzácný románský kostel s rotundou a středověkými freskami v údolí Bódvy. Klenot skrytý mimo hlavní tahy.', 48.4058, 20.7378, 'https://commons.wikimedia.org/wiki/Special:FilePath/Szalonna_templom.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Szalonna_templom.jpg"}'::text[], 4);

end $$;
