-- MotoGo24 — katalog míst: studánky a prameny (CZ/SK, Wikidata 2026-09-20)
-- ---------------------------------------------------------------------------
-- Zadání uživatele (2026-09-20): „chybí většina významných kopců, chybí
-- studánky … málo zajímavých míst v ČR a SR".
--
-- PROČ TO V KATALOGU CHYBĚLO: dávka hor z 19. 9. (20260919_poi_hills_cz_sk_*)
-- vkládala bod jen tehdy, když v okruhu ~70 m NEBYLO VŮBEC NIC. Jenže
-- u významných vrcholů skoro vždy něco je — u Sněžky leží 50 m vedle
-- wikidatový bod „Krkonošský národní park", u Klínovce rozhledna 18 m,
-- u Čerchova Kurzova rozhledna 56 m. Sněžka, Klínovec, Kralický Sněžník,
-- Blaník, Čerchov, Velká Deštná, Děčínský Sněžník ani Zvičina se proto
-- do katalogu NIKDY nedostaly.
--
-- Tahle dávka má guard postavený obráceně a správně:
--   * přeskočí bod, u kterého je v katalogu něco se STEJNÝM normalizovaným
--     názvem (public.poi_norm_name) do 250 m — tj. skutečný dvojník,
--   * přeskočí bod, u kterého je cokoli do 40 m — dva špendlíky přes sebe,
--   * body v rámci dávky jsou proti sobě odduplikované už při generování
--     (staré dávky to nedělaly vůbec — odtud „Pípalka" vedle „Křemešníku").
-- Souřadnice, foto (P18) i nadmořská výška (P2044) jsou z Wikidat; `wikidata_id`
-- se ukládá, aby šlo fotku později dohledat podle IDENTITY bodu, ne podle
-- „co je do 600 m a jmenuje se podobně".
-- Idempotentní: `delete from … where source = '<dávka>'` + vložení znovu.

delete from public.points_of_interest where source like 'wikidata-springs-cz-sk%';

insert into public.points_of_interest
  (category, name, description, lat, lng, country, source, sort_order,
   image_url, wikidata_id, translations)
select v.category, v.name, v.description, v.lat, v.lng, v.country, v.source,
       v.sort_order, v.image_url, v.wikidata_id, v.translations::jsonb
from (values
('spring', 'Alexandřin pramen', 'Pramen / studánka v Česku, 600 m n. m..', 49.96917, 12.70306, 'CZ', 'wikidata-springs-cz-sk-spring', 9400, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pavilon%20Alexandrina%20Pramene%20Marianske%20Lazne.jpg', 'Q13407930', '{"en": {"description": "Spring / well in Czechia, 600 m above sea level."}, "de": {"description": "Quelle / Brunnen in Tschechien, 600 m ü. M.."}, "pl": {"description": "Źródło / studzienka w Czechach, 600 m n.p.m.."}, "nl": {"description": "Bron in Tsjechië, 600 m boven zeeniveau."}, "es": {"description": "Manantial en Chequia, 600 m sobre el nivel del mar."}, "fr": {"description": "Source en Tchéquie, 600 m d’altitude."}, "uk": {"description": "Джерело у Чехії, 600 м над рівнем моря."}}'),
('spring', 'Pumpa Jáji a Páji', 'Pramen / studánka v Česku, 254 m n. m..', 49.74697, 16.97511, 'CZ', 'wikidata-springs-cz-sk-spring', 9746, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pumpa%20J%C3%A1ji%20a%20P%C3%A1ji%2C%20Doubravice%2C%20Moravi%C4%8Dany%2C%20okres%20%C5%A0umperk%202.jpg', 'Q126902336', '{"en": {"description": "Spring / well in Czechia, 254 m above sea level."}, "de": {"description": "Quelle / Brunnen in Tschechien, 254 m ü. M.."}, "pl": {"description": "Źródło / studzienka w Czechach, 254 m n.p.m.."}, "nl": {"description": "Bron in Tsjechië, 254 m boven zeeniveau."}, "es": {"description": "Manantial en Chequia, 254 m sobre el nivel del mar."}, "fr": {"description": "Source en Tchéquie, 254 m d’altitude."}, "uk": {"description": "Джерело у Чехії, 254 м над рівнем моря."}}'),
('spring', 'Studánka Vráblovecký medvědice', 'Pramen / studánka v Česku, 244 m n. m..', 49.87951, 18.22598, 'CZ', 'wikidata-springs-cz-sk-spring', 9756, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stud%C3%A1nka%20Vr%C3%A1bloveck%C3%BD%20medv%C4%9Bdice%2C%20Ludge%C5%99ovice%2C%20okres%20Opava%2C%20Slezsko%2002.jpg', 'Q136653845', '{"en": {"description": "Spring / well in Czechia, 244 m above sea level."}, "de": {"description": "Quelle / Brunnen in Tschechien, 244 m ü. M.."}, "pl": {"description": "Źródło / studzienka w Czechach, 244 m n.p.m.."}, "nl": {"description": "Bron in Tsjechië, 244 m boven zeeniveau."}, "es": {"description": "Manantial en Chequia, 244 m sobre el nivel del mar."}, "fr": {"description": "Source en Tchéquie, 244 m d’altitude."}, "uk": {"description": "Джерело у Чехії, 244 м над рівнем моря."}}'),
('spring', 'Artézska studňa', 'Pramen / studánka na Slovensku.', 47.98948, 18.17212, 'SK', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/NZ%20StudnaSokol1.jpg', 'Q112096303', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'Buková studánka', 'Pramen / studánka v Česku.', 50.05838, 12.26108, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Buchbrunnen.jpg', 'Q997985', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Dymák', 'Pramen / studánka v Česku.', 49.40033, 16.56575, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cern%C3%A1%20Hora%2C%20Dym%C3%A1k%2004.jpg', 'Q127698410', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Jákobova studna', 'Pramen / studánka v Česku.', 50.39829, 15.85194, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Betlem%20u%20kuksu%20jakobova%20studna%202.jpg', 'Q91498344', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Komenského studna', 'Pramen / studánka v Česku.', 50.13988, 15.11285, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Podebrady%2C%20Komensk%C3%A9ho%20studna.JPG', 'Q38048553', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Křišťálová studánka', 'Pramen / studánka v Česku.', 49.55411, 17.55143, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/K%C5%99i%C5%A1%C5%A5%C3%A1lov%C3%A1%20stud%C3%A1nka%20u%20Bohusl%C3%A1vek%2C%20Slavkov%2C%20okres%20Olomouc.jpg', 'Q111976618', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Olšanská studna', 'Pramen / studánka v Česku.', 49.97653, 13.42515, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trojany%2C%20Ol%C5%A1ansk%C3%A1%20studna%20%2801%29.jpg', 'Q124473854', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Pramen Eliška', 'Pramen / studánka v Česku.', 50.03312, 17.03576, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9%20Losiny%2C%20L%C3%A1ze%C5%88sk%C3%A1%20240%20L%C3%A1ze%C5%88sk%C3%BD%20d%C5%AFm%20Eli%C5%A1ka%20%282455%29.jpg', 'Q108058024', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Pramen Karel', 'Pramen / studánka v Česku.', 50.03546, 17.03493, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Velk%C3%A9%20Losiny%2C%20miner%C3%A1ln%C3%AD%20pramen%20Karel%20%282021-07-23%2016.40.52%29.jpg', 'Q108057915', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Rosenfeldov palác, pioniersky d, studňa', 'Pramen / studánka na Slovensku.', 49.22541, 18.73762, 'SK', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%BDilina%20-%20Rosenfeldov%20pal%C3%A1c%20-%20stud%C5%88a%207911.jpg', 'Q112106512', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'Rothschildovy studny', 'Pramen / studánka v Česku.', 49.91421, 18.18449, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rothschildovy%20studny%204%2C%20Hlu%C4%8D%C3%ADn.jpg', 'Q106171944', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna', 'Pramen / studánka v Česku.', 50.44006, 14.08429, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chot%C4%9B%C5%A1ov%2C%20studna%20na%20n%C3%A1vsi%20pod%20kostelem.jpg', 'Q37159805', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna Dvojčata', 'Pramen / studánka v Česku.', 50.01857, 14.48594, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praha%20Kunratice%20Ke%20Hradku%20studna.jpg', 'Q135341780', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna Na Dolní Polance', 'Pramen / studánka v Česku.', 49.77863, 18.18255, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20na%20Doln%C3%AD%20Polance%2C%20Doln%C3%AD%20Polanka%2C%20Polanka%20nad%20Odrou%2C%20Ostrava%2C%20Moravskoslezsk%C3%BD%20kraj%2C%20Slezsko.jpg', 'Q136808380', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna Nová Barbora v zámeckém parku v Cholticích', 'Pramen / studánka v Česku.', 49.98539, 15.61808, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Choltice%2C%20z%C3%A1mek%2C%20kapli%C4%8Dka.jpg', 'Q112215885', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna Obecnice', 'Pramen / studánka v Česku.', 50.20229, 15.78418, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20Obecnice%20%28Kukleny%29.jpg', 'Q123335899', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna V lázni', 'Pramen / studánka v Česku.', 49.56834, 15.19364, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cultural%20monument%20well%20in%20Seno%C5%BEaty%2C%20Pelh%C5%99imov%20District.jpg', 'Q38095175', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna kláštera augustiniánů', 'Pramen / studánka v Česku.', 49.19137, 16.59347, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brno%2C%20Mendlovo%20n%C3%A1m%C4%9Bst%C3%AD%2C%20studna%20a%20socha%20Gregora%20Mendela%20%2815.47.08%29.jpg', 'Q112218392', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na dvoře Dolejšího mlýna v Hostivaři', 'Pramen / studánka v Česku.', 50.04966, 14.52633, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praha%20Hostivar%20K%20Horkam%2023%20studna.jpg', 'Q112213707', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na jižní straně na náměstí Edvarda Beneše ve Švihově', 'Pramen / studánka v Česku.', 49.48032, 13.2856, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20na%20n%C3%A1m%C4%9Bst%C3%AD%20E.Bene%C5%A1e%20ve%20%C5%A0vihov%C4%9B%2C%20ji%C5%BEn%C3%AD%20strana.jpg', 'Q123719522', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na nádvoří radnice na Novém Městě v Praze', 'Pramen / studánka v Česku.', 50.0784, 14.42125, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Novom%C4%9Bstsk%C3%A1%20radnice%2C%20n%C3%A1dvo%C5%99%C3%AD%2C%20studna.jpg', 'Q112213297', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na náměstí Osvobození v Drahotuších', 'Pramen / studánka v Česku.', 49.54967, 17.6955, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Drahotu%C5%A1e.jpg', 'Q123719538', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na východní straně na náměstí Edvarda Beneše ve Švihově', 'Pramen / studánka v Česku.', 49.48075, 13.28664, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20na%20n%C3%A1m%C4%9Bst%C3%AD%20E.Bene%C5%A1e%20ve%20%C5%A0vihov%C4%9B%2C%20v%C3%BDch.%20strana.jpg', 'Q123719523', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna před bývalým západním průčelím konventu v Anežském klášteře v Praze', 'Pramen / studánka v Česku.', 50.09262, 14.42379, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20p%C5%99ed%20konventem%20v%20Ane%C5%BEsk%C3%A9m%20kl%C3%A1%C5%A1te%C5%99e.jpg', 'Q123719521', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna s přístřeškem', 'Pramen / studánka v Česku.', 49.87293, 15.85833, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20s%20p%C5%99%C3%ADst%C5%99e%C5%A1kem%20v%20%C5%BDumberku.jpg', 'Q38234134', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna s vodními prvky v Zámeckém parku', 'Pramen / studánka v Česku.', 50.0101, 14.48243, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praha%20Kunratice%20Zamecky%20park%20studna%20a.jpg', 'Q133460712', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna u čp. 143', 'Pramen / studánka v Česku.', 50.68415, 15.40333, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vysok%C3%A9%20nad%20Jizerou%2C%20studna%20u%20%C4%8Dp.143.jpg', 'Q38193536', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna v Květné zahradě', 'Pramen / studánka v Česku.', 49.29857, 17.38132, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kromeriz%20Kvetna%20zahrada%20studna%20b.jpg', 'Q135156335', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna v Ledeburské zahradě', 'Pramen / studánka v Česku.', 50.09061, 14.40502, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praha%20Mala%20Strana%20Ledeburska%20zahrada%20studna%20d.jpg', 'Q123456070', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna ve Vyšehradských sadech na Vyšehradě v Praze', 'Pramen / studánka v Česku.', 50.06372, 14.41833, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20ve%20Vy%C5%A1ehradsk%C3%BDch%20sadech%20na%20Vy%C5%A1ehrad%C4%9B%20v%20Praze.jpg', 'Q123719525', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna ze Střížovic', 'Pramen / studánka v Česku.', 50.6491, 14.2204, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Zubrnice%20studna%202.jpg', 'Q38228631', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studňa lásky', 'Pramen / studánka na Slovensku.', 48.8958, 18.04516, 'SK', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trencin%20Castle%20Well.jpg', 'Q29954726', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'Středověká studna na Horním Předměstí', 'Pramen / studánka v Česku.', 50.55895, 15.91011, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Trutnov%20Prazska%20studna.jpg', 'Q107690330', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Veterná studňa', 'Pramen / studánka na Slovensku.', 48.1356, 18.3283, 'SK', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tr%C3%A1vnica%20obec%2001.jpg', 'Q112096371', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'Vodní hrátky', 'Pramen / studánka v Česku.', 48.98986, 14.44681, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vodn%C3%AD%20hr%C3%A1tky%2001.jpg', 'Q136230026', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'jižní studna na nádvoří Chvalské tvrze', 'Pramen / studánka v Česku.', 50.11187, 14.59603, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chvalsk%C3%A1%20tvrz%2C%20studna.jpg', 'Q107738519', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'kryt studny se sochou svatého Jana Nepomuckého', 'Pramen / studánka v Česku.', 50.25795, 13.99952, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kv%C3%ADlice%2C%20kryt%20studny%20se%20sochou%20svat%C3%A9ho%20Jana%20Nepomuck%C3%A9ho.jpg', 'Q37451523', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'novogotická studna v Bochově', 'Pramen / studánka v Česku.', 50.15044, 13.04513, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bochov%20studna%20na%20n%C3%A1m.%20M%C3%ADru%20%C4%8Dervenec%202022%20%282%29.jpg', 'Q37009180', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'novogotická studna v Karlachových sadech', 'Pramen / studánka v Česku.', 50.06447, 14.42008, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prague%2C%20Czech%20Republic%2C%20April%202016%20-%20470.jpg', 'Q107738752', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'obecní studna Stračí', 'Pramen / studánka v Česku.', 50.44995, 14.40233, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stra%C4%8D%C3%AD%20-%20pramen.jpg', 'Q127606648', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'rumpálová studna', 'Pramen / studánka v Česku.', 49.67062, 16.65055, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ma%C5%99%C3%ADn.jpg', 'Q40637070', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'severní studna na nádvoří Chvalské tvrze', 'Pramen / studánka v Česku.', 50.11246, 14.59567, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chvalsk%C3%A1%20tvrz%2C%20studna%2C%20z%20N%C3%A1chodsk%C3%A9%20%2802%29.jpg', 'Q107738516', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna na 2. nádvoří Pražského hradu', 'Pramen / studánka v Česku.', 50.09046, 14.39907, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hrad%2022.JPG', 'Q107738898', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna na Anenském náměstí', 'Pramen / studánka v Česku.', 50.08509, 14.41479, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Studna%20%28Star%C3%A9%20M%C4%9Bsto%29%2C%20Praha%201%2C%20Anensk%C3%A9%20n%C3%A1m.%2C%20Star%C3%A9%20M%C4%9Bsto.JPG', 'Q38137095', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna na Malém náměstí', 'Pramen / studánka v Česku.', 50.08663, 14.41951, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Water%20well%20in%20Mal%C3%A9%20n%C3%A1m%C4%9Bst%C3%AD%2C%20Prague%20%28July%202019%29.jpg', 'Q38137269', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna na nádvoří Lichtenštejnského paláce', 'Pramen / studánka v Česku.', 50.08787, 14.40182, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praha%2C%20HAMU%2C%20n%C3%A1dvo%C5%99%C3%AD%2C%20studna.jpg', 'Q37817998', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna na stezce Via Mariana', 'Pramen / studánka v Česku.', 49.18897, 15.72678, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Overview%20of%20well%20in%20Via%20Mariana%20path%20near%20%C5%A0t%C4%9Bm%C4%9Bchy%2C%20T%C5%99eb%C3%AD%C4%8D%20District.jpg', 'Q136802521', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna u kostela sv. Vavřince', 'Pramen / studánka v Česku.', 49.21888, 17.85181, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Overview%20of%20well%20near%20Church%20of%20Saint%20Lawrence%20in%20Vizovice%2C%20Zl%C3%ADn%20District.jpg', 'Q106554758', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna u zámku Police', 'Pramen / studánka v Česku.', 48.96505, 15.62726, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Overview%20of%20well%20of%20Police%20Castle%20in%20Police%2C%20T%C5%99eb%C3%AD%C4%8D%20District.jpg', 'Q125789711', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna v Brně-Bohunicích', 'Pramen / studánka v Česku.', 49.16725, 16.5777, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brno-Bohunice-studna-u-kapli%C4%8Dky2022.jpg', 'Q116233067', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna v Tyršově', 'Pramen / studánka v Česku.', 49.22406, 14.42035, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/T%C3%BDn%20nad%20Vltavou%2C%20Tyr%C5%A1ova%2C%20water%20well%2001.jpg', 'Q108608135', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna ve Vyšehradských sadech', 'Pramen / studánka v Česku.', 50.0641, 14.41694, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Praha%2C%20Vy%C5%A1ehrad%2C%20studna.JPG', 'Q107738619', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna ve dvoře domu U Synků', 'Pramen / studánka v Česku.', 48.94003, 16.73858, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hustope%C4%8De-d%C5%AFm-U-Synk%C5%AF2015dv%C5%AFr-studna.jpg', 'Q138803102', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studňa prírodnej termálnej vody Trajan', 'Pramen / studánka na Slovensku.', 48.58646, 17.84287, 'SK', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Prame%C5%88%20Adam%20Trajan%20%2817.2.2007%29%20-%20panoramio.jpg', 'Q137613080', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'Čtyři studny na Masarykově náměstí - studna u čp. 2', 'Pramen / studánka v Česku.', 50.33833, 15.93024, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cty%C5%99i%20studny%20na%20Masarykov%C4%9B%20n%C3%A1m%C4%9Bst%C3%AD%20-%20studna%20u%20%C4%8Dp.%202.JPG', 'Q37334421', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Čtyři studny na Masarykově náměstí - studna u čp. 25', 'Pramen / studánka v Česku.', 50.33901, 15.92968, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cty%C5%99i%20studny%20na%20Masarykov%C4%9B%20n%C3%A1m%C4%9Bst%C3%AD%20-%20studna%20u%20%C4%8Dp.%2025.JPG', 'Q37334599', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Čtyři studny na Masarykově náměstí - studna u čp. 49', 'Pramen / studánka v Česku.', 50.33872, 15.93123, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C4%8Cty%C5%99i%20studny%20na%20Masarykov%C4%9B%20n%C3%A1m%C4%9Bst%C3%AD%20-%20studna%20u%20%C4%8Dp.%2049.JPG', 'Q37334337', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Šlosarova studánka', 'Pramen / studánka v Česku.', 49.55905, 17.54619, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, 'https://commons.wikimedia.org/wiki/Special:FilePath/%C5%A0losarova%20stud%C3%A1nka%2C%20Odersk%C3%A9%20vrchy%2C%20okres%20Olomouc%2002.jpg', 'Q111976584', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Popova studňa', 'Pramen / studánka na Slovensku, 343 m n. m..', 48.79713, 21.63073, 'SK', 'wikidata-springs-cz-sk-spring', 9657, null, 'Q115195762', '{"en": {"description": "Spring / well in Slovakia, 343 m above sea level."}, "de": {"description": "Quelle / Brunnen in der Slowakei, 343 m ü. M.."}, "pl": {"description": "Źródło / studzienka w Słowacji, 343 m n.p.m.."}, "nl": {"description": "Bron in Slowakije, 343 m boven zeeniveau."}, "es": {"description": "Manantial en Eslovaquia, 343 m sobre el nivel del mar."}, "fr": {"description": "Source en Slovaquie, 343 m d’altitude."}, "uk": {"description": "Джерело у Словаччині, 343 м над рівнем моря."}}'),
('spring', 'Barokní studna na návsi ve Střížovicích', 'Pramen / studánka v Česku.', 50.67891, 13.97982, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719540', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Kaštieľ Betliar s parkom, studňa rumpálová', 'Pramen / studánka na Slovensku.', 48.70554, 20.51024, 'SK', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q112093102', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'Krytá studna na náměstí Republiky v Horšovském Týně', 'Pramen / studánka v Česku.', 49.52957, 12.94437, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719531', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Slaná studňa', 'Pramen / studánka na Slovensku.', 48.9892, 22.07961, 'SK', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q115196610', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'Studna', 'Pramen / studánka v Česku.', 50.39106, 16.17711, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q37463997', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna', 'Pramen / studánka v Česku.', 49.41257, 13.01548, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q38138021', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna', 'Pramen / studánka v Česku.', 49.59222, 18.11884, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q38231623', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna', 'Pramen / studánka v Česku.', 49.58758, 18.11137, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q62009056', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na nádvoří muzea v Přibyslavi', 'Pramen / studánka v Česku.', 49.57723, 15.74038, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719530', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na náměstí v Novém Městě nad Metují', 'Pramen / studánka v Česku.', 50.34378, 16.15212, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719524', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna na návsi v Choustníku', 'Pramen / studánka v Česku.', 49.33335, 14.83874, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719542', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna u kaple svatého Jana Nepomuckého ve Vehlovicích', 'Pramen / studánka v Česku.', 50.39324, 14.465, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719543', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna u kaple ve farní zahradě v Berouně', 'Pramen / studánka v Česku.', 49.96443, 14.07116, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719535', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna u čp. 4', 'Pramen / studánka v Česku.', 49.07158, 17.78186, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q38045111', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna u čp. 57', 'Pramen / studánka v Česku.', 49.32316, 13.35834, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q37029154', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna u školy v Golčově Jeníkově', 'Pramen / studánka v Česku.', 49.81874, 15.47685, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719529', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna usedlosti čp. 6', 'Pramen / studánka v Česku.', 49.1546, 14.56043, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q37302107', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna v Temešváru', 'Pramen / studánka v Česku.', 49.35625, 14.26299, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719532', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna v parku jihovýchodně od zámku Kozel', 'Pramen / studánka v Česku.', 49.66883, 13.53144, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719541', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna v ruinách fary v zaniklé vsi Lučina', 'Pramen / studánka v Česku.', 49.43386, 12.68041, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719534', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna ve Smetanově ulici ve Starém Plzenci', 'Pramen / studánka v Česku.', 49.6934, 13.48618, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719527', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'Studna zaniklé obce Kolvín', 'Pramen / studánka v Česku.', 49.66869, 13.73772, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q123719526', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'bývalá zámecká ledovna/studna', 'Pramen / studánka v Česku.', 49.68594, 18.34511, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q139058575', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'neolitická studna v Ostrově', 'Pramen / studánka v Česku.', 49.97639, 16.03917, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q84986912', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'roľnícka usadlosť, studňa rumpálová', 'Pramen / studánka na Slovensku.', 49.02414, 20.79818, 'SK', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q112097055', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'rumpálová studňa', 'Pramen / studánka na Slovensku.', 49.02718, 20.73026, 'SK', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q112098851', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'rumpálová studňa', 'Pramen / studánka na Slovensku.', 49.01222, 20.76922, 'SK', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q112100708', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}'),
('spring', 'studna', 'Pramen / studánka v Česku.', 49.0826, 17.8292, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q115647585', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna', 'Pramen / studánka v Česku.', 49.1258, 17.69312, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q115647623', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna', 'Pramen / studánka v Česku.', 49.6277, 12.8021, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q116036468', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna', 'Pramen / studánka v Česku.', 49.8261, 13.7091, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q116036504', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna', 'Pramen / studánka v Česku.', 49.9055, 18.4232, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q116166639', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna ve Velkém Újezdu', 'Pramen / studánka v Česku.', 50.40978, 14.63038, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q115808615', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna ve skanzenu Kouřim', 'Pramen / studánka v Česku.', 49.99563, 14.97156, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q115814834', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'studna zemědělského dvora čp. 4', 'Pramen / studánka v Česku.', 49.56604, 16.52562, 'CZ', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q116201702', '{"en": {"description": "Spring / well in Czechia."}, "de": {"description": "Quelle / Brunnen in Tschechien."}, "pl": {"description": "Źródło / studzienka w Czechach."}, "nl": {"description": "Bron in Tsjechië."}, "es": {"description": "Manantial en Chequia."}, "fr": {"description": "Source en Tchéquie."}, "uk": {"description": "Джерело у Чехії."}}'),
('spring', 'vodárenská studňa č. 1', 'Pramen / studánka na Slovensku.', 48.14746, 17.04081, 'SK', 'wikidata-springs-cz-sk-spring', 10000, null, 'Q112088313', '{"en": {"description": "Spring / well in Slovakia."}, "de": {"description": "Quelle / Brunnen in der Slowakei."}, "pl": {"description": "Źródło / studzienka w Słowacji."}, "nl": {"description": "Bron in Slowakije."}, "es": {"description": "Manantial en Eslovaquia."}, "fr": {"description": "Source en Slovaquie."}, "uk": {"description": "Джерело у Словаччині."}}')
) as v(category, name, description, lat, lng, country, source, sort_order,
       image_url, wikidata_id, translations)
where not exists (
  select 1 from public.points_of_interest p
   where p.lat between v.lat - 0.00225 and v.lat + 0.00225
     and p.lng between v.lng - 0.0035 and v.lng + 0.0035
     and ( -- dvojník: stejný normalizovaný název do ~250 m
           (p.norm_name = public.poi_norm_name(v.name)
            and 111320.0 * sqrt(power(p.lat - v.lat, 2)
                + power((p.lng - v.lng) * cos(radians(v.lat)), 2)) <= 250)
        or -- cokoli prakticky na stejném pixelu
           (111320.0 * sqrt(power(p.lat - v.lat, 2)
                + power((p.lng - v.lng) * cos(radians(v.lat)), 2)) <= 40)
     )
);
