-- ════════════════════════════════════════════════════════════════════
-- MotoGo24 — SEED doporučených tras — ŘECKO (10 tras, sort_order 4010–4100)
-- NEAPLIKOVÁNO na živou DB — přehled a spuštění je na adminovi.
-- Trasy: is_active=false (Skryto) + status='approved' → ve Velíně zkontroluj a Publikuj.
-- Idempotence: každá trasa se před vložením smaže dle (name, branch_id).
-- ════════════════════════════════════════════════════════════════════
alter table public.routes add column if not exists countries text[] not null default '{}'::text[];

do $$
declare
  v_branch uuid;
  v_route  uuid;
begin
  -- Domovská pobočka = nejbližší k Mezné (49.3464, 15.2119); fallback první.
  select id into v_branch from public.branches
    order by (power(coalesce(gps_lat,0)-49.3464,2) + power(coalesce(gps_lng,0)-15.2119,2)) asc
    limit 1;
  if v_branch is null then
    raise exception 'Nenalezena žádná pobočka v public.branches — nelze nasadit trasy.';
  end if;

  -- Pelion – poloostrov kentaurů
  delete from public.routes where name = 'Pelion – poloostrov kentaurů' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Pelion – poloostrov kentaurů', 'Okruh po hoře Pelion, kde podle mýtů žili kentauři, je jednou z nejhezčích motorkářských vyjížděk pevninského Řecka. Z Volosu stoupáte úzkými serpentinami mezi kaštanovými lesy do kamenných vesnic Makrinitsa a Tsagarada a na východním pobřeží se silnice stáčí k tyrkysové pláži Mylopotamos. Zpátky vede cesta přes Milies, konečnou stanici legendární úzkorozchodné železnice. Asfalt je vesměs dobrý, ale silnice jsou úzké, plné slepých zatáček a v sezóně potkáte autobusy — jezděte předvídavě. Nejlépe od května do října; brzy zjara bývá na hřebeni mokro a listí na silnici. Večer si ve Volosu dopřejte tsipouradiko, místní rituál drobných rybích chodů.', 'loop', 135, 240, 'medium',
     '[{"lat": 39.3622, "lng": 22.9420, "label": "Start: Volos"}, {"lat": 39.3985, "lng": 22.9855, "label": "Makrinitsa"}, {"lat": 39.3949, "lng": 23.1926, "label": "Tsagarada"}, {"lat": 39.3270, "lng": 23.2310, "label": "Pláž Mylopotamos"}, {"lat": 39.3280, "lng": 23.1480, "label": "Milies"}, {"lat": 39.3622, "lng": 22.9420, "label": "Cíl: Volos"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=39.3622,22.9420&destination=39.3622,22.9420&travelmode=driving&waypoints=39.3985,22.9855%7C39.3949,23.1926%7C39.3270,23.2310%7C39.3280,23.1480', 'https://commons.wikimedia.org/wiki/Special:FilePath/Makrinitsa%20village%20in%20Volos%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Volos%20view%20from%20Pelion%20(cropped).JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Makrinitsa%20village%20in%20Volos%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Platanus%20Tsangarada%20hc.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20Mylopotamos.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Pilionbahn%20in%20milies.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Volos-bynight.JPG"}'::text[], '{"Vyhlídka na Volos a Pagasetický záliv","Makrinitsa","Tsagarada – platan na Agia Paraskevi","Pláž Mylopotamos","Milies – Pélionská železnice","Restaurace: Mezen (Volos)"}'::text[], '{"GR"}'::text[], false, 4010, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Vyhlídka na Volos a Pagasetický záliv', 'Hned v prvních serpentinách nad Portarií se otevře výhled na celý Volos a modrý Pagasetický záliv. Ideální první zastávka na kontrolu stroje a fotku, než začne pravé pélionské klikatění mezi platany.', 39.3850, 22.9750, 'https://commons.wikimedia.org/wiki/Special:FilePath/Volos%20view%20from%20Pelion%20(cropped).JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Volos%20view%20from%20Pelion%20(cropped).JPG"}'::text[], 0),
    (v_route, 'Makrinitsa', 'Kamenná vesnice přilepená na svahu, přezdívaná balkon Pelionu. Motorku nechte na parkovišti pod vesnicí a projděte se po dlážděném náměstíčku s obřími platany, kašnou a výhledem, který patří k nejfotografovanějším v Thesálii.', 39.3985, 22.9855, 'https://commons.wikimedia.org/wiki/Special:FilePath/Makrinitsa%20village%20in%20Volos%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Makrinitsa%20village%20in%20Volos%20Greece.jpg"}'::text[], 1),
    (v_route, 'Tsagarada – platan na Agia Paraskevi', 'Rozlehlá vesnice na zeleném východním svahu Pelionu. Na náměstí Agia Paraskevi roste tisíciletý platan s korunou přes celé náměstí — přirozené místo na kávu ve stínu po sérii zatáček od hřebene.', 39.3949, 23.1926, 'https://commons.wikimedia.org/wiki/Special:FilePath/Platanus%20Tsangarada%20hc.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Platanus%20Tsangarada%20hc.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Tsagkarada%206%20-%20Agia%20Paraskevi.JPG"}'::text[], 2),
    (v_route, 'Pláž Mylopotamos', 'Dvojitá oblázková pláž pod skalním obloukem, jedna z nejkrásnějších v Egejském moři. Sjezd z hlavní silnice je strmý a úzký, ale odměnou je koupání v průzračné vodě přímo pod útesy Tsagarady.', 39.3270, 23.2310, 'https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20Mylopotamos.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Beach%20Mylopotamos.jpg"}'::text[], 3),
    (v_route, 'Milies – Pélionská železnice', 'Konečná stanice úzkorozchodné dráhy, kterou koncem 19. století stavěl otec malíře Giorgia de Chirica. V sezóně sem od Volosu supí historický vláček po kamenných viaduktech — nádražíčko s výtopnou je milé místo na protažení nohou.', 39.3280, 23.1480, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pilionbahn%20in%20milies.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pilionbahn%20in%20milies.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Pelion%20train.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Mezen (Volos)', 'Volos je hlavní město tsipouradik a Mezen patří k nejlépe hodnoceným — k rundě anýzového tsipoura dostanete pokaždé jiný talířek mořských dobrot. Perfektní tečka za okruhem, motorku už ale nechte zaparkovanou u hotelu.', 39.3610, 22.9440, 'https://commons.wikimedia.org/wiki/Special:FilePath/Volos-bynight.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Volos-bynight.JPG"}'::text[], 5);

  -- Delfy, Parnassos a Galaxidi
  delete from public.routes where name = 'Delfy, Parnassos a Galaxidi' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Delfy, Parnassos a Galaxidi', 'Okruh kolem hory Parnassos spojuje antický „střed světa" s horskými serpentinami a přímořskou pohodou Korintského zálivu. Z přístavu Itea vystoupáte olivovým hájem k delfské věštírně a do lyžařské Arachovy, odkud pokračuje prázdná horská silnice přes sedla Parnassu k byzantskému klášteru Osios Loukas. Zpáteční cesta padá dlouhými zatáčkami zpět k moři do námořnického městečka Galaxidi. Povrch je převážně výborný, jen na horských úsecích čekejte štěrk v zatáčkách a volně se pasoucí kozy. Ideální období je duben až červen a září až říjen — v létě bývá u Delf výheň a davy. Brzy ráno projedete areál věštírny téměř sami.', 'loop', 150, 240, 'medium',
     '[{"lat": 38.4325, "lng": 22.4243, "label": "Start: Itea"}, {"lat": 38.4824, "lng": 22.5010, "label": "Delfy"}, {"lat": 38.4790, "lng": 22.5860, "label": "Arachova"}, {"lat": 38.5325, "lng": 22.6220, "label": "Parnassos"}, {"lat": 38.3966, "lng": 22.7469, "label": "Osios Loukas"}, {"lat": 38.3782, "lng": 22.3907, "label": "Galaxidi"}, {"lat": 38.4325, "lng": 22.4243, "label": "Cíl: Itea"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=38.4325,22.4243&destination=38.4325,22.4243&travelmode=driving&waypoints=38.4824,22.5010%7C38.4790,22.5860%7C38.5325,22.6220%7C38.3966,22.7469%7C38.3782,22.3907', 'https://commons.wikimedia.org/wiki/Special:FilePath/Delphi%20tholos%20cazzul.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Delphi%20tholos%20cazzul.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Arachova.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Parnassos2.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Osiosloukas.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Galaxidi%20harbour.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Galaxidi%20Paralia%20at%20Dusk.jpg"}'::text[], '{"Delfy – Apollónova věštírna","Arachova","Parnassos – horský přejezd","Klášter Osios Loukas","Galaxidi","Restaurace: O Tassos (Galaxidi)"}'::text[], '{"GR"}'::text[], false, 4020, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Delfy – Apollónova věštírna', 'Nejslavnější věštírna starověku na terasách pod skalami Parnassu, památka UNESCO. Kruhový tholos Athény Pronaie je nejfotogeničtější stavbou areálu a výhled do údolí s mořem oliv stojí za časný příjezd, než dorazí autobusy.', 38.4824, 22.5010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Delphi%20tholos%20cazzul.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Delphi%20tholos%20cazzul.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20of%20Apollo%20at%20Delphi%202015.jpg"}'::text[], 0),
    (v_route, 'Arachova', 'Horské městečko nalepené na serpentinách nad roklí, v zimě nejrušnější lyžařské středisko Řecka. Kamenné uličky, hodinová věž na skále a krámky s medem, sýrem formaela a vlněnými dekami — v létě příjemně prázdno.', 38.4790, 22.5860, 'https://commons.wikimedia.org/wiki/Special:FilePath/Arachova.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Arachova.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Arachova,%20Viotia,%20Greece%20-%20View%20on%20city.jpg"}'::text[], 1),
    (v_route, 'Parnassos – horský přejezd', 'Silnice k lyžařským střediskům Parnassu šplhá přes 1 600 metrů vysoká sedla holou vápencovou krajinou. Mimo zimu je téměř prázdná — dlouhé oblouky, výhledy na půl středního Řecka a chladný horský vzduch i uprostřed léta.', 38.5325, 22.6220, 'https://commons.wikimedia.org/wiki/Special:FilePath/Parnassos2.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Parnassos2.jpg"}'::text[], 2),
    (v_route, 'Klášter Osios Loukas', 'Byzantský klášter z 10. století na tichém svahu hory Helikon, památka UNESCO. Katholikon ukrývá nejzachovalejší soubor zlatých mozaik makedonské renesance v Řecku; do areálu se vstupuje v dlouhých kalhotách.', 38.3966, 22.7469, 'https://commons.wikimedia.org/wiki/Special:FilePath/Osiosloukas.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Osiosloukas.JPG"}'::text[], 3),
    (v_route, 'Galaxidi', 'Bývalé město kapitánů na Korintském zálivu s kamennými rejdařskými domy kolem dvou přístavních zátok. Dnes je to jedno z nejpoklidnějších míst na pobřeží — nábřeží lemují kavárny a rybí taverny s výhledem na kotvící plachetnice.', 38.3782, 22.3907, 'https://commons.wikimedia.org/wiki/Special:FilePath/Galaxidi%20harbour.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Galaxidi%20harbour.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Galaxidi%20Paralia%20at%20Dusk.jpg"}'::text[], 4),
    (v_route, 'Restaurace: O Tassos (Galaxidi)', 'Proslulá rodinná taverna přímo na nábřeží Galaxidi, kam se jezdí na čerstvé ryby, grilované chobotnice a domácí předkrmy. U stolu nad vodou se západem slunce nad zálivem se okruh uzavírá přesně tak, jak má.', 38.3790, 22.3900, 'https://commons.wikimedia.org/wiki/Special:FilePath/Galaxidi%20Paralia%20at%20Dusk.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Galaxidi%20Paralia%20at%20Dusk.jpg"}'::text[], 5);

  -- Mani – věžové domy a mys Tenaro
  delete from public.routes where name = 'Mani – věžové domy a mys Tenaro' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Mani – věžové domy a mys Tenaro', 'Cesta na nejdivočejší poloostrov Peloponésu, kde kamenné věžové domy hlídají vyprahlou krajinu a silnice končí u bájné brány do podsvětí. Z Kalamaty se pobřežní silnice vlní nad tyrkysovými zátokami přes Kardamyli do Limeni a dál na jih k jeskyním Diros a věžím Vathie, až k majáku na mysu Tenaro — nejjižnějším výběžku pevninského Řecka. Zatáčky nad mořem jsou plynulé, ale krajnice bývají štěrkové a v horku přebíhají silnici kozy. Nejlepší jsou květen, červen a září; v červenci a srpnu počítejte s úmorným vedrem a slabým stínem. Benzín natankujte v Areopoli, dál na jih jsou pumpy vzácné.', 'poi', 175, 300, 'medium',
     '[{"lat": 37.0389, "lng": 22.1142, "label": "Start: Kalamata"}, {"lat": 36.8880, "lng": 22.2330, "label": "Kardamyli"}, {"lat": 36.6902, "lng": 22.3819, "label": "Limeni"}, {"lat": 36.6386, "lng": 22.3810, "label": "Jeskyně Diros"}, {"lat": 36.4744, "lng": 22.4650, "label": "Vathia"}, {"lat": 36.4006, "lng": 22.4818, "label": "Mys Tenaro"}, {"lat": 36.7607, "lng": 22.5664, "label": "Cíl: Gythio"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.0389,22.1142&destination=36.7607,22.5664&travelmode=driving&waypoints=36.8880,22.2330%7C36.6902,22.3819%7C36.6386,22.3810%7C36.4744,22.4650%7C36.4006,22.4818', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vathia%20Mani%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kardamili%20main%20street%20in%20town.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Limeni%20Mani.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Limeni.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Diros%20Cave.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Vathia%20Mani%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Tainaron%20lighthouse.jpg"}'::text[], '{"Kardamyli","Limeni","Restaurace: Takis (Limeni)","Jeskyně Diros","Vathia","Mys Tenaro – maják"}'::text[], '{"GR"}'::text[], false, 4030, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Kardamyli', 'Kamenné městečko mezi mořem a srázy Taygetu, kde prožil většinu života cestovatel Patrick Leigh Fermor. Stará opevněná čtvrť s věžemi rodu Mourtzinos je ochutnávkou maniotské architektury hned na začátku trasy.', 36.8880, 22.2330, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kardamili%20main%20street%20in%20town.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Kardamili%20main%20street%20in%20town.jpg"}'::text[], 0),
    (v_route, 'Limeni', 'Bývalý přístav Areopole — hrst kamenných domů kolem zátoky s neuvěřitelně průzračnou tyrkysovou vodou, ve které se prohánějí mořské želvy. Jedno z nejfotogeničtějších míst celé Mani, ideální na polední koupel.', 36.6902, 22.3819, 'https://commons.wikimedia.org/wiki/Special:FilePath/Limeni%20Mani.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Limeni%20Mani.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Takis (Limeni)', 'Legendární rybí taverna se stoly na molu pár centimetrů nad hladinou. Čerstvé ryby dle denního úlovku, grilovaná chobotnice a výhled na kamenné věže Limeni — rezervace v sezóně nutná, jinak přijeďte mimo poledne.', 36.6899, 22.3826, 'https://commons.wikimedia.org/wiki/Special:FilePath/Limeni.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Limeni.jpg"}'::text[], 2),
    (v_route, 'Jeskyně Diros', 'Zatopený jeskynní systém Vlychada, kterým se plujete na loďce mezi lesy krápníků — jedna z nejpůsobivějších jeskynních plaveb v Evropě. Počítejte s hodinou navíc a chladem uvnitř, u vody je i malá pláž na osvěžení.', 36.6386, 22.3810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Diros%20Cave.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Diros%20Cave.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Diros-cave-greece%2016269357444%20o.jpg"}'::text[], 3),
    (v_route, 'Vathia', 'Nejslavnější věžová vesnice Mani na hřebeni nad mořem — kamenné obranné věže z dob krevní msty dnes zpola opuštěné trčí proti obloze jako středověký Manhattan. Nejlepší světlo na fotky je pozdě odpoledne.', 36.4744, 22.4650, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vathia%20Mani%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Vathia%20Mani%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vathia%20Mani%20Greece%202.jpg"}'::text[], 4),
    (v_route, 'Mys Tenaro – maják', 'Nejjižnější bod pevninského Řecka, kde staří Řekové umísťovali vchod do Hádovy říše. Od parkoviště u kaple je to půlhodina pěšky kamenitou stezkou k osamělému majáku — vezměte vodu a pevné boty, výhled na tři moře za to stojí.', 36.3862, 22.4829, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Tainaron%20lighthouse.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Tainaron%20lighthouse.jpg"}'::text[], 5);

  -- Arkádie – Dimitsana a soutěska Lousios
  delete from public.routes where name = 'Arkádie – Dimitsana a soutěska Lousios' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Arkádie – Dimitsana a soutěska Lousios', 'Horské srdce Peloponésu je přesně ta Arkádie, kterou opěvovali básníci: hluboká údolí, jedlové lesy a kamenné vesnice na srázech. Okruh z Tripoli projíždí serpentinami soutěsky Lousios přes Dimitsanu a Stemnitsu ke zřícenině franckého hradu v Karytaině. Silnice jsou úzké, samá zatáčka a téměř bez provozu — technicky jedna z nejzábavnějších tras Peloponésu. Na jaře kvetou stráně a řeka Lousios burácí, na podzim hrají lesy barvami; v zimě může na hřebenech ležet sníh. Pozor na štěrk po zimě a na stáda ovcí za slepými zatáčkami. Palivo doplňte v Tripoli nebo ve Vytině.', 'loop', 160, 270, 'medium',
     '[{"lat": 37.5089, "lng": 22.3794, "label": "Start: Tripoli"}, {"lat": 37.5946, "lng": 22.0431, "label": "Dimitsana"}, {"lat": 37.5535, "lng": 22.0463, "label": "Stemnitsa"}, {"lat": 37.4886, "lng": 22.0402, "label": "Karytaina"}, {"lat": 37.4010, "lng": 22.1420, "label": "Megalopoli"}, {"lat": 37.5089, "lng": 22.3794, "label": "Cíl: Tripoli"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.5089,22.3794&destination=37.5089,22.3794&travelmode=driving&waypoints=37.5946,22.0431%7C37.5535,22.0463%7C37.4886,22.0402%7C37.4010,22.1420', 'https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20mansion%20in%20Dimitsana,%20Greece%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20mansion%20in%20Dimitsana,%20Greece%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Hydro%20power%20museum%20at%20Dimitsana.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Lousios%20river.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Bell%20tower%20in%20Stemnitsa,%20Greece%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Karytainaview.JPG"}'::text[], '{"Dimitsana","Muzeum vodní síly (Dimitsana)","Soutěska Lousios","Stemnitsa","Karytaina"}'::text[], '{"GR"}'::text[], false, 4040, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Dimitsana', 'Amfiteátr kamenných domů nad soutěskou Lousios, za řecké revoluce zásobárna střelného prachu povstalců. Úzká hlavní ulice s kavárnami a pekárnami je stvořená pro první zastávku; výhled z horního konce vesnice bere dech.', 37.5946, 22.0431, 'https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20mansion%20in%20Dimitsana,%20Greece%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Stone%20mansion%20in%20Dimitsana,%20Greece%20-%20panoramio.jpg"}'::text[], 0),
    (v_route, 'Muzeum vodní síly (Dimitsana)', 'Skanzen pod Dimitsanou u pramenů, kde voda kdysi poháněla mlýny, valchy, koželužnu i prachárnu. Vše je zrestaurované a funkční — půlhodinová zastávka, po které pochopíte, proč bylo tohle údolí průmyslovým centrem Peloponésu.', 37.5880, 22.0450, 'https://commons.wikimedia.org/wiki/Special:FilePath/Hydro%20power%20museum%20at%20Dimitsana.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Hydro%20power%20museum%20at%20Dimitsana.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Gunpowder%20watermill%20at%20Dimitsana%20hydropower%20museum.JPG"}'::text[], 1),
    (v_route, 'Soutěska Lousios', 'Hluboký kaňon řeky, kterou se podle mýtu koupal malý Zeus. Do skalních stěn jsou vlepené kláštery Prodromou a Filosofou; z vyhlídek u silnice mezi Dimitsanou a Stemnitsou je vidí i ten, kdo nechce šlapat pěšky.', 37.5600, 22.0500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lousios%20river.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lousios%20river.jpg"}'::text[], 2),
    (v_route, 'Stemnitsa', 'Vesnice zlatníků a stříbrotepců ukrytá v jedlích pod horou Klinitsa, s kamennou zvonicí na náměstíčku a proslulou zlatnickou školou. V kavárnách pod platany si dejte místní sladkost skaltsounia a kávu z briki.', 37.5535, 22.0463, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bell%20tower%20in%20Stemnitsa,%20Greece%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Bell%20tower%20in%20Stemnitsa,%20Greece%20-%20panoramio.jpg"}'::text[], 3),
    (v_route, 'Karytaina', 'Vesnice pod mohutnou franckou pevností ze 13. století, přezdívaná řecké Toledo. Hrad hlídá soutok údolí a starý kamenný most pod ním kdysi zdobil pětitisícovou drachmovou bankovku — krátká pěší odbočka nahoru nabídne výhled na celou Arkádii.', 37.4886, 22.0402, 'https://commons.wikimedia.org/wiki/Special:FilePath/Karytainaview.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Karytainaview.JPG"}'::text[], 4);

  -- Olymp – hora bohů a hrad Platamon
  delete from public.routes where name = 'Olymp – hora bohů a hrad Platamon' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Olymp – hora bohů a hrad Platamon', 'Okruh kolem nejvyšší hory Řecka spojuje antické Dion, serpentiny do srdce národního parku a středověký hrad nad mořem. Vrcholem je osmnáct kilometrů zatáček z Litochora na Prionii — silnice končí v 1 100 metrech přímo pod skalními štíty Olympu a jinudy než zpátky to nejde, o to víc si ji užijete. Cestou na jih se vyplatí odbočka do kamenné vesnice Palaios Panteleimonas a k hradu Platamon nad pobřežím. Asfalt je slušný, ale v horní části čekejte popadané kamení a v sezóně pomalé kolony k trailheadu. Nejhezčí je červen, kdy na vrcholcích ještě leží sníh, a pak září s křišťálovou viditelností. Ráno bývá hora čistá, odpoledne se štíty zatahují.', 'loop', 150, 240, 'medium',
     '[{"lat": 40.2719, "lng": 22.5025, "label": "Start: Katerini"}, {"lat": 40.1717, "lng": 22.4913, "label": "Dion"}, {"lat": 40.1044, "lng": 22.5006, "label": "Litochoro"}, {"lat": 40.1073, "lng": 22.4143, "label": "Prionia"}, {"lat": 40.0100, "lng": 22.5850, "label": "Palaios Panteleimonas"}, {"lat": 39.9997, "lng": 22.6042, "label": "Hrad Platamon"}, {"lat": 40.2719, "lng": 22.5025, "label": "Cíl: Katerini"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=40.2719,22.5025&destination=40.2719,22.5025&travelmode=driving&waypoints=40.1717,22.4913%7C40.1044,22.5006%7C40.1073,22.4143%7C40.0100,22.5850%7C39.9997,22.6042', 'https://commons.wikimedia.org/wiki/Special:FilePath/Olympus%20Litochoro.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dion%20archaeological%20site%20102.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Olympus%20Litochoro.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Litochoro.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20Olympus,%20Greece%20(Unsplash).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Palaios%20Panteleimonas%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Platamon%20Castle.jpg"}'::text[], '{"Dion – antické město","Litochoro","Restaurace: Gastrodromio En Olympo (Litochoro)","Soutěska Enipeas a Prionia","Palaios Panteleimonas","Hrad Platamon"}'::text[], '{"GR"}'::text[], false, 4050, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Dion – antické město', 'Posvátné město Makedonců na úpatí Olympu, kde Alexandr Veliký obětoval bohům před tažením do Asie. Mezi topoly a potoky tu leží svatyně Dia i Isidy, lázně a divadlo — rovinatý areál se prochází příjemně i v motorkářských botách.', 40.1717, 22.4913, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dion%20archaeological%20site%20102.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Dion%20archaeological%20site%20102.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/The%20santuary%20of%20Zeus%20Olympios,%20Ancient%20Dion%20(6933396342).jpg"}'::text[], 0),
    (v_route, 'Litochoro', 'Městečko přímo pod stěnami Olympu, základna všech výprav na horu bohů. Z náměstí s kašnou je přímý výhled do ústí soutěsky Enipeas na štít Mytikas — kávu si dejte na terase a nechte kolemjdoucí závidět motorku.', 40.1044, 22.5006, 'https://commons.wikimedia.org/wiki/Special:FilePath/Olympus%20Litochoro.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Olympus%20Litochoro.JPG"}'::text[], 1),
    (v_route, 'Restaurace: Gastrodromio En Olympo (Litochoro)', 'Nejproslulejší restaurace pod Olympem — moderní řecká kuchyně z horských surovin, jehněčí, lesní houby a vinný lístek, jaký byste v podhůří nečekali. Po serpentinách z Prionie ideální místo na pořádný oběd.', 40.1049, 22.5000, 'https://commons.wikimedia.org/wiki/Special:FilePath/Litochoro.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Litochoro.jpg"}'::text[], 2),
    (v_route, 'Soutěska Enipeas a Prionia', 'Osmnáct kilometrů serpentin z Litochora nad soutěskou řeky Enipeas až na Prionii, kde asfalt končí pod skalními věžemi Olympu. Jedna z nejpůsobivějších horských silnic Řecka — jeďte brzy ráno, vyhnete se koloně aut turistů mířících na trailhead.', 40.1073, 22.4143, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20Olympus,%20Greece%20(Unsplash).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20Olympus,%20Greece%20(Unsplash).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/At%20Enipeas%20gorge%20(2).jpg"}'::text[], 3),
    (v_route, 'Palaios Panteleimonas', 'Kamenná vesnice na svahu Dolního Olympu, citlivě zrestaurovaná do poslední tašky. Z platany zastíněného náměstí s tavernami se otevírá výhled přes Egejské moře až k hradu Platamon hluboko dole — příjezdová silnička je úzká, ale krásná.', 40.0100, 22.5850, 'https://commons.wikimedia.org/wiki/Special:FilePath/Palaios%20Panteleimonas%201.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palaios%20Panteleimonas%201.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Church%20of%20Palaios%20Panteleimonas.jpg"}'::text[], 4),
    (v_route, 'Hrad Platamon', 'Křižácká pevnost z 13. století na skále mezi dálnicí a mořem, strážící vstup do Tempského údolí. Z hradeb je panoráma od Olympu po Chalkidiki; pod hradem lákají pláže Platamonas na rychlé osvěžení před návratem.', 39.9997, 22.6042, 'https://commons.wikimedia.org/wiki/Special:FilePath/Platamon%20Castle.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Platamon%20Castle.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Platamon%20castro.JPG"}'::text[], 5);

  -- Epirus – Parga, Sivota a řeka Acheron
  delete from public.routes where name = 'Epirus – Parga, Sivota a řeka Acheron' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Epirus – Parga, Sivota a řeka Acheron', 'Pobřežní putování Epirem od Preverzy k Sivotě, kde se jónské pobřeží podobá Karibiku a mezi olivami se skrývají místa antických mýtů. Cestou navštívíte věštírnu mrtvých nad soutokem Acherontu, ledové prameny bájné řeky podsvětí v Glyki a benátské městečko Parga s hradem nad zálivem. Silnice se vlní mezi olivovými háji a mořem — technicky nenáročné, zato scenericky velkolepé kilometry. Ideální od května do začátku října; v srpnu je v Parze plno, ale stačí přijet dopoledne. U Acherontu se v létě zchladíte broděním v průzračné vodě, vezměte sandály. Trasa navazuje na trajekt z Itálie do Igoumenitsy, hodí se jako první den řeckého okruhu.', 'poi', 130, 210, 'easy',
     '[{"lat": 38.9560, "lng": 20.7500, "label": "Start: Preveza"}, {"lat": 39.2358, "lng": 20.5342, "label": "Nekromanteion"}, {"lat": 39.3216, "lng": 20.6094, "label": "Glyki – prameny Acherontu"}, {"lat": 39.2850, "lng": 20.4010, "label": "Parga"}, {"lat": 39.4079, "lng": 20.2447, "label": "Cíl: Sivota"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=38.9560,20.7500&destination=39.4079,20.2447&travelmode=driving&waypoints=39.2358,20.5342%7C39.3216,20.6094%7C39.2850,20.4010', 'https://commons.wikimedia.org/wiki/Special:FilePath/Parga,%20Grekland.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pantokratoras%20Castle,%20Preveza%202.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Promenade%20of%20Preveza,%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Nekromanteion%20of%20Acheron.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Acheron%20Springs,%20Preveza%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Parga,%20Grekland.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Grand%20Harbour%20of%20Syvota.JPG"}'::text[], '{"Preveza","Restaurace: Amvrosios (Preveza)","Nekromanteion – věštírna mrtvých","Prameny Acherontu (Glyki)","Parga","Sivota"}'::text[], '{"GR"}'::text[], false, 4060, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Preveza', 'Přístavní městečko u ústí Ambrakijského zálivu s benátskou pevností Pantokrator a stinnými uličkami plnými kaváren. Na start trasy se sem pohodlně dostanete podmořským tunelem z Aktia — jediným svého druhu v Řecku.', 38.9560, 20.7500, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pantokratoras%20Castle,%20Preveza%202.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Pantokratoras%20Castle,%20Preveza%202.jpg"}'::text[], 0),
    (v_route, 'Restaurace: Amvrosios (Preveza)', 'Kultovní taverna v rybářské uličce u přístavu, proslavená grilovanými sardinkami a domácím vínem za pár eur. Jednoduché stoly, žádné menu pro turisty — přesně tak chutná skutečný Epirus, ideální časný oběd před vyjížďkou na sever.', 38.9565, 20.7515, 'https://commons.wikimedia.org/wiki/Special:FilePath/Promenade%20of%20Preveza,%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Promenade%20of%20Preveza,%20Greece.jpg"}'::text[], 1),
    (v_route, 'Nekromanteion – věštírna mrtvých', 'Na kopci nad soutokem Acherontu stála jediná známá věštírna mrtvých antického světa — poutníci tu v podzemní kryptě rozmlouvali s dušemi zemřelých. Mystické místo s výhledem na deltu bájné řeky, vstup zabere půl hodiny.', 39.2358, 20.5342, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nekromanteion%20of%20Acheron.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nekromanteion%20of%20Acheron.jpg"}'::text[], 2),
    (v_route, 'Prameny Acherontu (Glyki)', 'U vesnice Glyki vyvěrá řeka podsvětí ze soutěsky ledovými prameny — v létě se tu turisté brodí křišťálovou vodou mezi platany a skalami. Osvěžující zastávka s tavernami u břehu; voda má i v srpnu kolem deseti stupňů.', 39.3216, 20.6094, 'https://commons.wikimedia.org/wiki/Special:FilePath/Acheron%20Springs,%20Preveza%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Acheron%20Springs,%20Preveza%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Acheron%20river%202.jpg"}'::text[], 3),
    (v_route, 'Parga', 'Amfiteátr pestrobarevných domů kolem zátoky s ostrůvkem Panagia a benátským hradem na ostrohu. Nejmalebnější městečko epirského pobřeží — vyjeďte k hradu, odkud je celá scenérie s pláží Valtos jako na dlani.', 39.2850, 20.4010, 'https://commons.wikimedia.org/wiki/Special:FilePath/Parga,%20Grekland.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Parga,%20Grekland.JPG"}'::text[], 4),
    (v_route, 'Sivota', 'Rybářský přístav proti souostroví drobných zelených ostrůvků, přezdívaný Karibik Jónského moře. Kolem zátoky Bella Vraka svítí bílý písek a tyrkys; večer na nábřeží u kotvících jachet chutná ouzo nejlíp z celé trasy.', 39.4079, 20.2447, 'https://commons.wikimedia.org/wiki/Special:FilePath/Grand%20Harbour%20of%20Syvota.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Grand%20Harbour%20of%20Syvota.JPG"}'::text[], 5);

  -- Chalkidiki – okruh Sithonií
  delete from public.routes where name = 'Chalkidiki – okruh Sithonií' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Chalkidiki – okruh Sithonií', 'Okruh prostředního prstu Chalkidiki je nejhezčí pobřežní vyjížďka severního Řecka: silnice kopíruje břeh mezi piniemi a desítkami tyrkysových zátok a přes záliv se celý den zjevuje silueta posvátné hory Athos. Po cestě střídáte přímořská městečka Neos Marmaras a Sarti s horskou odbočkou do kamenné vesnice Parthenonas a přírodním přístavem Porto Koufo. Asfalt je kvalitní, převýšení mírné a zatáčky plynulé — pohodová trasa i pro méně zkušené. Nejlépe v červnu nebo září, kdy je moře teplé a silnice prázdné; o prázdninách počítejte s provozem u pláží. Plavky mějte po ruce, zastávek na koupání je nepočítaně.', 'loop', 115, 180, 'easy',
     '[{"lat": 40.2180, "lng": 23.6700, "label": "Start: Nikiti"}, {"lat": 40.0947, "lng": 23.7826, "label": "Neos Marmaras"}, {"lat": 40.1030, "lng": 23.8180, "label": "Parthenonas"}, {"lat": 39.9620, "lng": 23.9200, "label": "Porto Koufo"}, {"lat": 40.0928, "lng": 24.0107, "label": "Sarti"}, {"lat": 40.1950, "lng": 23.7960, "label": "Vourvourou"}, {"lat": 40.2180, "lng": 23.6700, "label": "Cíl: Nikiti"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=40.2180,23.6700&destination=40.2180,23.6700&travelmode=driving&waypoints=40.0947,23.7826%7C40.1030,23.8180%7C39.9620,23.9200%7C40.0928,24.0107%7C40.1950,23.7960', 'https://commons.wikimedia.org/wiki/Special:FilePath/Porto%20Koufo,%20Sithonia,%20Chalkidiki,%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nikiti%20old%201.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/NeosMarmarasMarina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/PARTHENONAS.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/PARTHENONAS%20BY%20NIGHT.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Porto%20Koufo,%20Sithonia,%20Chalkidiki,%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sarti,%20church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Karidi%20beach,%20Sithonia,%20Chalkidiki,%20Greece.jpg"}'::text[], '{"Nikiti – stará čtvrť","Neos Marmaras","Parthenonas","Restaurace: O Platanos (Parthenonas)","Porto Koufo","Sarti","Vourvourou a pláž Karydi"}'::text[], '{"GR"}'::text[], false, 4070, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Nikiti – stará čtvrť', 'Vstupní brána Sithonie se starou čtvrtí kamenných domů a kostelíků na kopci nad letoviskem. Ideální místo na ranní kávu a tankování před okruhem — odtud už silnice vede jen podél moře.', 40.2180, 23.6700, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nikiti%20old%201.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nikiti%20old%201.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Nikiti,%20Halkidiki,%20Greece.jpg"}'::text[], 0),
    (v_route, 'Neos Marmaras', 'Živé přístavní městečko v borovicových svazích se dvěma zátokami a marínou plnou jachet. Na nábřeží je řada kaváren s výhledem na ostrůvek Kelyfos; nad městem se zvedá vinařství Porto Carras, největší vinice Řecka.', 40.0947, 23.7826, 'https://commons.wikimedia.org/wiki/Special:FilePath/NeosMarmarasMarina.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/NeosMarmarasMarina.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Neos%20Marmaras,%20Chalkidiki,%20Greece.jpg"}'::text[], 1),
    (v_route, 'Parthenonas', 'Jediná zachovaná horská vesnice Sithonie ve svahu hory Itamos, kdysi vylidněná a dnes citlivě opravená. Krátká serpentinová odbočka z Neos Marmaras nahoru je zábavná sama o sobě a výhled na záliv Toroneos stojí za každou zatáčku.', 40.1030, 23.8180, 'https://commons.wikimedia.org/wiki/Special:FilePath/PARTHENONAS.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/PARTHENONAS.jpg"}'::text[], 2),
    (v_route, 'Restaurace: O Platanos (Parthenonas)', 'Taverna pod platanem na návsi Parthenonas s poctivou domácí kuchyní — jehněčí z gril, sezónní zelenina a výhled přes střechy až k moři. Po ránu klid, večer romantika; oblíbené místo, v sezóně raději rezervujte.', 40.1032, 23.8175, 'https://commons.wikimedia.org/wiki/Special:FilePath/PARTHENONAS%20BY%20NIGHT.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/PARTHENONAS%20BY%20NIGHT.jpg"}'::text[], 3),
    (v_route, 'Porto Koufo', 'Největší přírodní přístav Řecka — téměř uzavřený fjord mezi vysokými útesy na jižním cípu poloostrova, známý už Thúkydidovi. V rybářských tavernách u mola mají denně čerstvé ryby; útesy u vjezdu nabízejí divoké výhledy na otevřené moře.', 39.9620, 23.9200, 'https://commons.wikimedia.org/wiki/Special:FilePath/Porto%20Koufo,%20Sithonia,%20Chalkidiki,%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Porto%20Koufo,%20Sithonia,%20Chalkidiki,%20Greece.jpg"}'::text[], 4),
    (v_route, 'Sarti', 'Letovisko s dlouhou písečnou pláží na východním pobřeží, odkud je nejblíž k mystické siluetě hory Athos přes záliv. Východní strana Sithonie je divočejší a silnice tu nabízí nejhezčí sled zatáček s mořem pod kolem.', 40.0928, 24.0107, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sarti,%20church.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Sarti,%20church.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Sarti%20630%2072,%20Greece%20-%20panoramio%20(5).jpg"}'::text[], 5),
    (v_route, 'Vourvourou a pláž Karydi', 'Mělká laguna s rozesetými ostrůvky Diaporos a slavná pláž Karydi s bílým pískem a hladkými žulovými balvany. Voda tu má barvu, kterou nikdo nefotí věrně — poslední koupání okruhu, pak už jen pohodový dojezd do Nikiti.', 40.1900, 23.8200, 'https://commons.wikimedia.org/wiki/Special:FilePath/Karidi%20beach,%20Sithonia,%20Chalkidiki,%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Karidi%20beach,%20Sithonia,%20Chalkidiki,%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Vourvourou%20beach%20sithonia%2001.jpg"}'::text[], 6);

  -- Kréta – Chania, Elafonisi a Falassarna
  delete from public.routes where name = 'Kréta – Chania, Elafonisi a Falassarna' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Kréta – Chania, Elafonisi a Falassarna', 'Okruh nejzápadnějším cípem Kréty z benátské Chanie k růžovým plážím Elafonisi a zpět přes Falassarnu. Silnice se provléká skalní soutěskou Topolia, kde jednosměrný tunel proráží útes, a pak padá serpentinami k laguně, která patří k nejkrásnějším plážím Evropy. Návrat po západním pobřeží nabízí výhledy na otevřené Libyjské moře a zlatou pláž Falassarna, proslulou západy slunce. Krétské silnice jsou úzké, se štěrkem v zatáčkách a místními řidiči, kteří jezdí středem — držte si rezervu. Ideální je květen, červen nebo září; v červenci a srpnu vyjeďte na Elafonisi před devátou, jinak nezaparkujete. Večer v Chanii zakončete u benátského přístavu.', 'loop', 160, 270, 'medium',
     '[{"lat": 35.5138, "lng": 24.0180, "label": "Start: Chania"}, {"lat": 35.4210, "lng": 23.6810, "label": "Soutěska Topolia"}, {"lat": 35.2716, "lng": 23.5416, "label": "Elafonisi"}, {"lat": 35.4936, "lng": 23.5786, "label": "Falassarna"}, {"lat": 35.4940, "lng": 23.6550, "label": "Kissamos"}, {"lat": 35.5138, "lng": 24.0180, "label": "Cíl: Chania"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=35.5138,24.0180&destination=35.5138,24.0180&travelmode=driving&waypoints=35.4210,23.6810%7C35.2716,23.5416%7C35.4936,23.5786%7C35.4940,23.6550', 'https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20Old%20Venetian%20Harbour%20in%20Chania,%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20Old%20Venetian%20Harbour%20in%20Chania,%20Greece.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Topolia%20Gorge%20-%20Crete,%20Greece%20(2).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Elafonisi%20Greece%20Crete%2016.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Creta,spiaggia%20di%20Falassarna%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Port%20of%20Kissamos%20in%20Crete,%20Greece%20001.jpg"}'::text[], '{"Chania – benátský přístav","Soutěska Topolia","Elafonisi","Falassarna","Kissamos","Restaurace: Tamam (Chania)"}'::text[], '{"GR"}'::text[], false, 4080, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Chania – benátský přístav', 'Nejkrásnější město Kréty s benátským přístavem, egyptským majákem a spletí uliček staré čtvrti Topanas. Startujte brzy ráno, kdy je nábřeží prázdné a světlo na maják nejhezčí — večer se sem vrátíte na promenádu.', 35.5176, 24.0180, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20Old%20Venetian%20Harbour%20in%20Chania,%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20Old%20Venetian%20Harbour%20in%20Chania,%20Greece.jpg"}'::text[], 0),
    (v_route, 'Soutěska Topolia', 'Silnice na Elafonisi se protahuje úzkou soutěskou pod převislými skalami a jednosměrným tunelem vytesaným do útesu — na semaforu si užijte pohled vzhůru. Kousek za tunelem je jeskyně Agia Sofia s kapličkou v krasovém dómu.', 35.4210, 23.6810, 'https://commons.wikimedia.org/wiki/Special:FilePath/Topolia%20Gorge%20-%20Crete,%20Greece%20(2).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Topolia%20Gorge%20-%20Crete,%20Greece%20(2).jpg"}'::text[], 1),
    (v_route, 'Elafonisi', 'Laguna s bílým a růžovým pískem, brodem na ostrůvek a vodou po kolena do půlky zálivu — chráněná rezervace Natura 2000 a jedna z nejslavnějších pláží Středomoří. Serpentiny posledních kilometrů nad Libyjským mořem jsou samy o sobě zážitek.', 35.2716, 23.5416, 'https://commons.wikimedia.org/wiki/Special:FilePath/Elafonisi%20Greece%20Crete%2016.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Elafonisi%20Greece%20Crete%2016.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Elafonisi%20Lagoon%20and%20Beach%20in%20Greece.jpg"}'::text[], 2),
    (v_route, 'Falassarna', 'Pět kilometrů zlatého písku pod svahy mysu Gramvousa s ruinami antického přístavu na severním konci. Západy slunce tu bývají vyhlášené nejhezčími na Krétě — pokud to čas dovolí, zdržte se do večera a do Chanie se vraťte po setmění.', 35.4936, 23.5786, 'https://commons.wikimedia.org/wiki/Special:FilePath/Creta,spiaggia%20di%20Falassarna%20-%20panoramio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Creta,spiaggia%20di%20Falassarna%20-%20panoramio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Falassarna%20-%20Kr%C3%A9ta%20-%20panoramio%20(4).jpg"}'::text[], 3),
    (v_route, 'Kissamos', 'Přístavní městečko v hlubokém zálivu mezi poloostrovy Gramvousa a Rodopou, odkud vyplouvají lodě k laguně Balos. Klidnější tvář západní Kréty s archeologickým muzeem a tavernami, kam turisté z resortů nedorazí.', 35.4940, 23.6550, 'https://commons.wikimedia.org/wiki/Special:FilePath/Port%20of%20Kissamos%20in%20Crete,%20Greece%20001.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Port%20of%20Kissamos%20in%20Crete,%20Greece%20001.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Tamam (Chania)', 'Vyhlášená restaurace v bývalých tureckých lázních kousek od přístavu — krétská a levantská kuchyně, skvělé vegetariánské meze a domácí víno. Po celodenním okruhu ideální večeře; přijďte dřív, stoly v uličce se plní rychle.', 35.5170, 24.0150, 'https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20Old%20Venetian%20Harbour%20in%20Chania,%20Greece.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20the%20Old%20Venetian%20Harbour%20in%20Chania,%20Greece.jpg"}'::text[], 5);

  -- Argolida – Nafplio, Mykény a Epidauros
  delete from public.routes where name = 'Argolida – Nafplio, Mykény a Epidauros' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Argolida – Nafplio, Mykény a Epidauros', 'Okruh kolébkou evropských dějin: za jediný den projedete mykénskou citadelu, antický Korint, slavný průplav i dokonalé divadlo v Epidauru a večer zaparkujete v nejromantičtějším městě Řecka. Silnice Argolidy vedou mezi pomerančovníkovými sady a vinicemi, mezi Epidaurem a Nafpliem si užijete svižné zatáčky v borovicových kopcích. Provoz je mimo hlavní tahy klidný a povrch dobrý — trasa vhodná i pro cestovní enduro s plnou bagáží. Nejpříjemněji je tu na jaře, kdy voní květy pomerančovníků, a na podzim; památky otevírají v osm, využijte toho. V Nafpliu vystoupejte 999 schodů na pevnost Palamidi — nejlépe až po odložení helmy a bot.', 'loop', 170, 250, 'easy',
     '[{"lat": 37.5680, "lng": 22.8090, "label": "Start: Nafplio"}, {"lat": 37.7308, "lng": 22.7566, "label": "Mykény"}, {"lat": 37.9059, "lng": 22.8797, "label": "Starověký Korint"}, {"lat": 37.9333, "lng": 22.9833, "label": "Korintský průplav"}, {"lat": 37.5961, "lng": 23.0791, "label": "Epidauros"}, {"lat": 37.5680, "lng": 22.8090, "label": "Cíl: Nafplio"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.5680,22.8090&destination=37.5680,22.8090&travelmode=driving&waypoints=37.7308,22.7566%7C37.9059,22.8797%7C37.9333,22.9833%7C37.5961,23.0791', 'https://commons.wikimedia.org/wiki/Special:FilePath/Palamidi%20fortress%20(Nafplio,%20Greece).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palamidi%20fortress%20(Nafplio,%20Greece).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Lions-Gate-Mycenae.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20of%20Apollo%20Ancient%20Corinth.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Corinth%20Canal%20(corinth-canal).jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Theatre%20of%20Epidaurus%20OLC.jpg"}'::text[], '{"Nafplio – pevnost Palamidi","Mykény – Lví brána","Starověký Korint","Korintský průplav","Divadlo v Epidauru","Restaurace: Ta Fanaria (Nafplio)"}'::text[], '{"GR"}'::text[], false, 4090, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Nafplio – pevnost Palamidi', 'První hlavní město novodobého Řecka pod benátskou pevností Palamidi a s vodním hrádkem Bourtzi v zálivu. Stará čtvrť s neoklasicistními domy, bugenvilejemi a kavárnami na Syntagmatu je nejhezčí městská kulisa Peloponésu.', 37.5663, 22.8014, 'https://commons.wikimedia.org/wiki/Special:FilePath/Palamidi%20fortress%20(Nafplio,%20Greece).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Palamidi%20fortress%20(Nafplio,%20Greece).jpg"}'::text[], 0),
    (v_route, 'Mykény – Lví brána', 'Citadela Agamemnonova rodu, srdce mykénské civilizace a památka UNESCO. Lví bránou z 13. století před naším letopočtem procházíte do hradu mezi kyklopskými zdmi; nevynechejte úlovou hrobku zvanou Átreova pokladnice u parkoviště.', 37.7308, 22.7566, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lions-Gate-Mycenae.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Lions-Gate-Mycenae.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/The%20Lion%20Gate,%20Mycenae.jpg"}'::text[], 1),
    (v_route, 'Starověký Korint', 'Rozvaliny antické metropole pod skalou Akrokorintu s archaickým Apollónovým chrámem, jehož monolitické sloupy stojí už dvacet šest století. Odtud kázal apoštol Pavel Korinťanům; na Akrokorint vede krátká, ale strmá asfaltka s výhledem na oba zálivy.', 37.9059, 22.8797, 'https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20of%20Apollo%20Ancient%20Corinth.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20of%20Apollo%20Ancient%20Corinth.jpg"}'::text[], 2),
    (v_route, 'Korintský průplav', 'Šest kilometrů dlouhý zářez v šíji mezi Egejským a Jónským mořem, s kolmými stěnami vysokými přes sedmdesát metrů. Z mostu staré národní silnice je závratný pohled na lodě hluboko dole — odvážlivci tu skáčou bungee.', 37.9333, 22.9833, 'https://commons.wikimedia.org/wiki/Special:FilePath/Corinth%20Canal%20(corinth-canal).jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Corinth%20Canal%20(corinth-canal).jpg"}'::text[], 3),
    (v_route, 'Divadlo v Epidauru', 'Nejdokonalejší antické divadlo světa se čtrnácti tisíci sedadly a akustikou, díky níž je škrtnutí sirkou na jevišti slyšet i v poslední řadě. Cesta z Epidauru do Nafplia borovicovými kopci je motorkářský bonus na závěr.', 37.5961, 23.0791, 'https://commons.wikimedia.org/wiki/Special:FilePath/Theatre%20of%20Epidaurus%20OLC.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Theatre%20of%20Epidaurus%20OLC.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Theatre%20of%20Epidaurus,%20202508.jpg"}'::text[], 4),
    (v_route, 'Restaurace: Ta Fanaria (Nafplio)', 'Stará dobrá taverna v uličce pod Palamidi, kde se pod bugenvileou podávají klasiky jako moussaka, jehněčí kleftiko a domácí retsina. Po dni mezi památkami zasloužená večeře pár kroků od náměstí Syntagma.', 37.5678, 22.8087, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nafplio%20(Nauplia),%20Argolis%20(Argolida),%20Greece.%20View%20from%20the%20Fort.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Nafplio%20(Nauplia),%20Argolis%20(Argolida),%20Greece.%20View%20from%20the%20Fort.jpg"}'::text[], 5);

  -- Attika – mys Sounion a chrám Poseidona
  delete from public.routes where name = 'Attika – mys Sounion a chrám Poseidona' and branch_id = v_branch;
  v_route := gen_random_uuid();
  insert into public.routes
    (id, branch_id, name, description, route_type, distance_km, duration_min, difficulty,
     waypoints, geometry, mapy_url, cover_image, images, image_alts, countries, is_active, sort_order, status)
  values (v_route, v_branch, 'Attika – mys Sounion a chrám Poseidona', 'Klasická athénská vyjížďka po pobřežní silnici Athénské riviéry až na mys Sounion, kde nad útesy září mramorový chrám Poseidona. Pobřežka se vlní nad zátokami kolem jezera Vouliagmeni a nabízí svižné oblouky s mořem na dosah; zpět se vracíte vnitrozemím přes hornické Lavrio a Artemidinu svatyni ve Vravroně. Trasa je nenáročná a krásně sjízdná po celý rok — v zimě si jen ohlídejte vítr na mysu. O víkendech na pobřežce jezdí půlka Athén, vyjeďte proto brzy ráno, nebo naopak odpoledne s návratem po setmění. Západ slunce u Poseidonova chrámu patří k největším divadlům Řecka; přijeďte hodinu předem, ať stihnete parkování i vstup.', 'loop', 140, 210, 'easy',
     '[{"lat": 37.8620, "lng": 23.7540, "label": "Start: Athény – Glyfada"}, {"lat": 37.8064, "lng": 23.7862, "label": "Jezero Vouliagmeni"}, {"lat": 37.6503, "lng": 24.0203, "label": "Mys Sounion"}, {"lat": 37.7146, "lng": 24.0566, "label": "Lavrio"}, {"lat": 37.9262, "lng": 23.9945, "label": "Vravrona"}, {"lat": 37.8620, "lng": 23.7540, "label": "Cíl: Athény – Glyfada"}]'::jsonb, null, 'https://www.google.com/maps/dir/?api=1&origin=37.8620,23.7540&destination=37.8620,23.7540&travelmode=driving&waypoints=37.8064,23.7862%7C37.6503,24.0203%7C37.7146,24.0566%7C37.9262,23.9945', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Sounion%20and%20temple%20of%20Poseidon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Limni%20Vouliagmenis%20kalokairi.JPEG","https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Sounion%20and%20temple%20of%20Poseidon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Capo%20Sounion%20panorama.JPG","https://commons.wikimedia.org/wiki/Special:FilePath/Agardite%20Lavrio.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Brauron%20-%20Votive%20Relief3.jpg"}'::text[], '{"Jezero Vouliagmeni","Chrám Poseidona na mysu Sounion","Restaurace: Syrtaki (Sounion)","Lavrio – město stříbrných dolů","Vravrona – svatyně Artemidy"}'::text[], '{"GR"}'::text[], false, 4100, 'approved');
  insert into public.route_pois (route_id, name, description, lat, lng, image_url, images, sort_order) values
    (v_route, 'Jezero Vouliagmeni', 'Termální jezero v propadlé krasové jeskyni pár metrů od moře — voda má celoročně kolem 24 stupňů a mírně léčivé složení. Elegantní zastávka na kávu nebo ranní koupel, než se pobřežní silnice rozběhne k jihu.', 37.8064, 23.7862, 'https://commons.wikimedia.org/wiki/Special:FilePath/Limni%20Vouliagmenis%20kalokairi.JPEG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Limni%20Vouliagmenis%20kalokairi.JPEG"}'::text[], 0),
    (v_route, 'Chrám Poseidona na mysu Sounion', 'Dórský chrám boha moří ze 5. století před naším letopočtem na útesu šedesát metrů nad Egejským mořem. Podle mýtu se odtud vrhl do vln král Aigeus; do jednoho sloupu vyryl své jméno lord Byron. Při západu slunce nezapomenutelné.', 37.6503, 24.0203, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Sounion%20and%20temple%20of%20Poseidon.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Sounion%20and%20temple%20of%20Poseidon.jpg","https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20of%20Poseidon%202%20Cape%20Sounion%20Greece.jpg"}'::text[], 1),
    (v_route, 'Restaurace: Syrtaki (Sounion)', 'Rybí taverna na svahu pod chrámem s terasou nad zálivem — grilované ryby, kalamáry a výhled přímo na Poseidonův chrám na protějším ostrohu. Ideální pozdní oběd před návratem po pobřežce, při západu slunce romantika první třídy.', 37.6560, 24.0250, 'https://commons.wikimedia.org/wiki/Special:FilePath/Capo%20Sounion%20panorama.JPG', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Capo%20Sounion%20panorama.JPG"}'::text[], 2),
    (v_route, 'Lavrio – město stříbrných dolů', 'Přístavní město, jehož stříbrné doly financovaly athénské loďstvo i stavbu Parthenónu. Hornickou minulost připomínají štoly, haldy a mineralogické muzeum s ukázkami vzácných minerálů, které svět zná právě odsud; na náměstí u přístavu je příjemná kavárenská pauza.', 37.7146, 24.0566, 'https://commons.wikimedia.org/wiki/Special:FilePath/Agardite%20Lavrio.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Agardite%20Lavrio.jpg"}'::text[], 3),
    (v_route, 'Vravrona – svatyně Artemidy', 'Tiché vykopávky svatyně bohyně Artemis v mokřadech u moře, kam athénské rodiny posílaly dcery sloužit jako „medvědice". Obnovená kolonáda stoy, kamenný most z klasické éry a muzeum s dojemnými soškami dětí — klidná tečka před návratem do Athén.', 37.9262, 23.9945, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brauron%20-%20Votive%20Relief3.jpg', '{"https://commons.wikimedia.org/wiki/Special:FilePath/Brauron%20-%20Votive%20Relief3.jpg"}'::text[], 4);

end $$;
